### ISSUE TITLE
[Help][Android]About Auto-Start

### ISSUE THREAD

**Issue by Sak94664** [DNSCrypt/dnscrypt-proxy#10]
How do I let it start on port 53 on every boot.(init.d)
Thanks in advance!

**Comment by jedisct1** [comment]
How did you install it on Android?

**Comment by Sak94664** [comment]
@jedisct1 
Just by compiling it from source code using termux,then copy binary file to ext4 partition,and execute it.
That's all.(Tested with no problems happened)
:D

**Comment by jedisct1** [comment]
This is great.

It builds out of the box with `gomobile`, so there are probably ways to build Android executables (not APK) automatically via Travis, but I haven't figured out the command-line magic to do that.

**Comment by licaon-kter** [comment]
Thanks for the heads up!
