### ISSUE TITLE
DoH: only use the optional IP to bootstrap resolution

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#100]
DoH stamps can include an optional IP address, so that the name doesn't have to be resolved when no other resolvers are available.

This is suboptimal with CDNs, because the IP may not be the one of a close datacenter. If the IP is absent, we currently need a fallback resolver.

Both issues can be solved by sending an initial query to the supplied IP only to resolve the resolver name itself.

Maybe the easiest and less intrusive way to achieve this is to clear the entire IP cache as soon as live resolvers are found.

**Comment by ghost** [comment]
I think that is a great solution!

**Comment by jedisct1** [comment]
To clarify, the current situation is not bad. It would just be an improvement for servers behind a CDN (such as my current experiment with Cloudflare).

**Comment by jedisct1** [comment]
Unfortunately, this ticket has been open for too long.

**Comment by sergeevabc** [comment]
Am sorry, but how could I check the benefits of turning ```doh_servers = true```?
