### ISSUE TITLE
Setting options from command line

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1002]
Can there be some command-line option during startup overriding the same in toml?
Like netprobe_address & fallback_resolver.
So that multiple IP address can be tried in case the initial one is not reachable in a shell startup script.

**Comment by jedisct1** [comment]
That would be a lot of options, but one thing you can do is have multiple configuration files.

In the Docker server image, there is also a template configuration file, with bits that get replaced with IP addresses using `sed` (see the strings within `@` here: https://github.com/DNSCrypt/dnscrypt-server-docker/blob/master/encrypted-dns.toml.in). Maybe something similar would work for you?

**Comment by ghost** [comment]
Ok, I would be content with multiple configuration files. 🙂
