### ISSUE TITLE
Duplicate entries of doh-cleanbrowsing-security in public-resolvers.md; one is doh and one is dnscrypt; IP-address is wrong for doh

### ISSUE THREAD

**Issue by MystesofEternity** [DNSCrypt/dnscrypt-proxy#1004]
Hi,
I would like to tell you that there are two entries for `doh-cleanbrowsing-security` in `public-resolvers.md`
One is an appropriate DNSCrypt entry to `185.228.168.9:8443` which is the ip address for the `security` DNS server
The other is actually a DoH entry but utilizes the "family" DNS server of cleanbrowsing and has the ip address of `185.228.168.168`

**Comment by jedisct1** [comment]
Good catch!

This has been fixed, thanks!

**Comment by MystesofEternity** [comment]
@jedisct1 Thanks for fixing it!`
Also, I want to confirm if there is a slip up because when I tried using doh-cleanbrowsing-security it actually used `185.228.168.10` instead of `185.228.168.9`
