### ISSUE TITLE
DoH: unable to use cloudflare-ipv6 alone (error: "dial tcp: address 2606:4700:4700::1111:443: too many colons in address")

### ISSUE THREAD

**Issue by BinaryKhaos** [DNSCrypt/dnscrypt-proxy#1005]
Starting with dnscrypt-proxy 2.0.29 (on Gentoo Linux), I get the following error when starting dnscrypt-proxy:

Oct 31 15:39:28 dnscrypt-proxy[9869]: dnscrypt-proxy 2.0.29
Oct 31 15:39:28 dnscrypt-proxy[9869]: Network connectivity detected
Oct 31 15:39:28 dnscrypt-proxy[9869]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
Oct 31 15:39:28 dnscrypt-proxy[9869]: Firefox workaround initialized
Oct 31 15:39:28 dnscrypt-proxy[9869]: Loading the set of forwarding rules from [forwarding-rules.txt]
Oct 31 15:39:28 dnscrypt-proxy[9869]: Now listening to 127.0.0.1:53 [UDP]
Oct 31 15:39:28 dnscrypt-proxy[9869]: Now listening to 127.0.0.1:53 [TCP]
Oct 31 15:39:28 dnscrypt-proxy[9869]: Now listening to [::1]:53 [UDP]
Oct 31 15:39:28 dnscrypt-proxy[9869]: Now listening to [::1]:53 [TCP]
Oct 31 15:41:29 dnscrypt-proxy[9869]: Get https://dns.cloudflare.com/dns-query?ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA: dial tcp: address 2606:4700:4700::1111:443: too many colons in address

Here the relevant parts from dnscrypt-proxy.toml:

server_names = ['cloudflare-ipv6']
ipv4_servers = false
ipv6_servers = true
#fallback_resolver = '1.1.1.1:53'
fallback_resolver = '[2606:4700:4700::1111]:53'

Changing the fallback_resolver to IPv4 or setting ipv4_servers to true makes no difference. I tried to debug this issue myself, but I am not too familiar with Go and the dnscrypt-proxy codebase, so I already spent quite some time on it without really finding the root cause. I guess someone more familiar with things can pin point the error way more easily than me, so please let me know if there is anything I can really help with. :-)

**Comment by jedisct1** [comment]
Reverting `bc831816f5851bf55c67a0155d76331a469f07d6` fixes this.

/cc @maage

**Comment by jedisct1** [comment]
All the DoH servers with an IPv6 address are now unreachable :(

**Comment by jedisct1** [comment]
Time to release a .31 version :(

**Comment by BinaryKhaos** [comment]
Wow. Thank you so much. That was some seriously fast reaction time. :-) Just wish I could have been more helpful...

**Comment by jedisct1** [comment]
2.0.31 released :) Thank you!
