### ISSUE TITLE
Connecton at startup

### ISSUE THREAD

**Issue by hgerd11** [DNSCrypt/dnscrypt-proxy#1009]
Dnscrypt-proxy is configured on my system with a single static server which I run myself and with
netprobe_timeout = 0

All sources are commented out so that no information needs to be downloaded at startup.

My goal is a system that does not trigger any network traffic at startup.

However even with this setup dnscrypt-proxy connects to the configured dns server once after boot.
There is no other traffic except this one before or after.

Why does dnscrypt-proxy connect to the server at startup even with netprobe explicitly disabled?

**Comment by hgerd11** [comment]
It seems this is due to latency testing.

How do I disable this check?

**Comment by jedisct1** [comment]
Sorry, that check cannot be disabled. That first query is also required to retrieve the certificates (for DNSCrypt), check if we should use `POST` or `GET` (for DoH) and more generally see if we have at least one usable resolver before telling the system that we can accept connections.
