### ISSUE TITLE
Startup fails when url not specified in sources. 

### ISSUE THREAD

**Issue by thundr** [DNSCrypt/dnscrypt-proxy#101]
Given a local source list, the config file says that we should be able to use it if we just don't specify the URL. When starting up, it throws this error: 
```
[2018-02-07 03:07:37] [CRITICAL] Unable use source [cs-servers]: [No IP found for []]
[2018-02-07 03:07:37] [FATAL] No servers configured
```
Am I missing something, or can we not use local sources? 

On a related note, I don't think I understand the config file. At the top, there are servers to set, and then at the bottom, sources. Is the server setting just allowing you to pick servers from the source list?

**Comment by jedisct1** [comment]
There is an error in the file with your `cs-servers`. An entry with a name instead of an IP address. Or if there are DoH servers in that list, there are names that don't resolve to any IP.

Yes, `server_names` let you pick servers from sources.
