### ISSUE TITLE
cryptostorm.is anonymizers

### ISSUE THREAD

**Issue by privacyguy123** [DNSCrypt/dnscrypt-proxy#1011]
for some reason I cant get these to connect, tried Quad 9 & thru CS-UK and CS-CH - anybody else experiencing this?

**Comment by jedisct1** [comment]
Seems to be working here

```text
[2019-11-01 21:02:58] [NOTICE] Anonymized DNS: routing everything via [anon-cs-uk]
[2019-11-01 21:03:03] [NOTICE] [quad9-dnscrypt-ip4-filter-pri] OK (DNSCrypt) - rtt: 22ms
[2019-11-01 21:03:03] [NOTICE] [scaleway-fr] OK (DNSCrypt) - rtt: 20ms
[2019-11-01 21:03:03] [NOTICE] Sorted latencies:
[2019-11-01 21:03:03] [NOTICE] -    20ms scaleway-fr
[2019-11-01 21:03:03] [NOTICE] -    22ms quad9-dnscrypt-ip4-filter-pri
```

```text
[2019-11-01 21:03:40] [NOTICE] Anonymized DNS: routing everything via [anon-cs-ch]
[2019-11-01 21:03:45] [NOTICE] [quad9-dnscrypt-ip4-filter-pri] OK (DNSCrypt) - rtt: 10ms
[2019-11-01 21:03:45] [NOTICE] [scaleway-fr] OK (DNSCrypt) - rtt: 52ms
[2019-11-01 21:03:45] [NOTICE] Sorted latencies:
[2019-11-01 21:03:45] [NOTICE] -    10ms quad9-dnscrypt-ip4-filter-pri
[2019-11-01 21:03:45] [NOTICE] -    52ms scaleway-fr
```

**Comment by privacyguy123** [comment]
I get no errors in the cmd output however no connectivity at all in windows

**Comment by jedisct1** [comment]
Can you try with a different resolver? Try with `scaleway-fr`.

**Comment by privacyguy123** [comment]
yes, both Quad 9 & bottlepost weren't working O.o

**Comment by privacyguy123** [comment]
scaleway-fr routed thru cs-uk shows my DNS as scaleway-fr.dnscrypt.info on dnsleaktest.com aka not anonymized

**Comment by jedisct1** [comment]
Quite the opposite. It doesn't tell you `cs-uk`, so it *is* anonymized.

Quad9 and Bottlepost use non-standard ports (`5353` and `5443`), and maybe Cryptostorm only allows relaying to port `443`.

**Comment by jedisct1** [comment]
I'll check with Cryptostorm what ports they allow.

**Comment by privacyguy123** [comment]
scaleway-fr wont connect for me either, doesnt seem like a port issue and more a Cryptostorm  issue

**Comment by privacyguy123** [comment]
> 
> 
> Quite the opposite. It doesn't tell you `cs-uk`, so it _is_ anonymized.
> 
>

how come anon-ibksturm shows 3 dns servers on the leak test then?

**Comment by jedisct1** [comment]
It should show whatever servers you are using. Anonymization will not change the results except with anycast resolvers.

**Comment by privacyguy123** [comment]
Im certain Quad 9 isnt located in Switzerland - my config is Quad9 -> anon-ibksturm and dnsleaktest.com shows 
![image](https://user-images.githubusercontent.com/50337995/68056350-d05fd900-fcea-11e9-8ff7-7fcb53a4472c.png)

**Comment by jedisct1** [comment]
WoodyNet = Quad9. They have servers everywhere.

**Comment by privacyguy123** [comment]
Ok - but the anonymizer is leaking then?

**Comment by jedisct1** [comment]
Cryptostorm just opened all the additional ports!

**Comment by jedisct1** [comment]
Nothing's leaking as long as the resolvers you see are the ones you configured.

**Comment by privacyguy123** [comment]
I think somethings wrong, ive only got 1 resolver and 1 anonymizer and 3 IPs are showing in the leak test as you can see

**Comment by jedisct1** [comment]
Quad9 has more than one servers. What you (or the relay) connects to is a load-balancer, and then the actual DNS query can be made by more than one of their servers.

All 3 IPs belong to Quad9.

**Comment by privacyguy123** [comment]
Understood!
