### ISSUE TITLE
invalidate dns cache entry manually

### ISSUE THREAD

**Issue by kpm4** [DNSCrypt/dnscrypt-proxy#1012]
would be nice to have a way to invalidate single or multiple dns entry in the cache, without restart the service?

**Comment by ghost** [comment]
Not sure you will like this, but of course you can with extra effort:
1) Disable cache in dnscrypt-proxy
2) install unbound
3) have your devices make requests to unbound
4) which then resolves them through dnscrypt-proxy

PC <---> unbound <---> dnscrypt-proxy <---> dnscrypt-server

The performance hit is negligible and it will work exactly the same as before.
As root now you can do a full zone or domain specific flush:

```
# unbound-control flush_zone google.com
# unbound-control flush www.google.com
```

I've been there before using two resolvers, it works quite nice and you have the best of both worlds. Just as an option if Frank has no better offer for you.

**Comment by jedisct1** [comment]
Zero progress on that one after 30 days.

It's a good idea, and it may eventually be implemented. Step 0 would be to define how to send commands to a running server.

Closing with the timeout tag for now, which means that it's unlikely to happen now, but it's in the bucket of good ideas to consider later.
