### ISSUE TITLE
Feature request: Auxiliary script to pair available relays and servers based on one's own server location/preferences

### ISSUE THREAD

**Issue by m-ueberall** [DNSCrypt/dnscrypt-proxy#1013]
It would be great to have a script which actually suggests available _(n:1)_ relay/server pairings based on individual server locations and predefined server properties in order to ensure that
-  the resulting query times are not too disadvantageous &nbsp; &nbsp; and
-  both a relay and a server cannot be run by the same entity as mentioned in `example-dnscrypt-proxy.toml` [*].

[*] Maybe the latter check, possibly in simplified form, can be executed by dnscrypt-proxy itself upon parsing the routes (entities can lie about this, of course, therefore this would require additional information/proof and might only be available for a subset of hosts)?

**Comment by jedisct1** [comment]
Scripts are difficult to run on non-linux systems, so it should rather be built-in.

The plan is to benchmark servers through every configured relay, to choose the fastest relay for each server.
