### ISSUE TITLE
ipv6 DNS addressing showing ...

### ISSUE THREAD

**Issue by privacyguy123** [DNSCrypt/dnscrypt-proxy#1015]
... with ipv6 explicity disabled in Windows & dnscrypt-proxy.toml - am I misunderstanding something here? My ISP provides no IPv6 connectivity.

**Comment by jedisct1** [comment]
Clients keep sending queries for IPv6 addresses even on networks without IPv6 connectivity.

The `block_ipv6 = true` setting prevents these useless queries to be sent to upstream servers.

**Comment by privacyguy123** [comment]
I have that option on and still see ipv6 servers listed in my connected DNS though ...

**Comment by privacyguy123** [comment]
Still can't get my head round 2 DNS leak sites showing IPv6 addresses even tho it is explicitity OFF

**Comment by jedisct1** [comment]
DNS leak websites show what resolver IP addresses connected to them, not the IPs you connected to.
