### ISSUE TITLE
DNSCrypt 2.0.31 randomly dies on RPi 4

### ISSUE THREAD

**Issue by Coder84619** [DNSCrypt/dnscrypt-proxy#1018]
I have two RPi 4 B servers, each configured the "same" with DNSCrypt and PiHole. After upgrading from 2.0.28 to 2.0.31, I have experienced DNSCrypt randomly failing to resolve DNS queries after a period of time.

My first solution was to reboot the RPis, and typically that fixed the issue and name resolution starts working. However, today the reboot worked on one RPi but not the other. On the broken RPi I replaced the 2.0.31 binary with the 2.0.28 binary, and the associated old configuration file. Magically it started working again. I had 2.0.28 for some time, and it was rock solid. 2.0.31 seems like a different matter with these random fits of breaking. 

Is this a known issue with 2.0.31?

**Comment by nobura** [comment]
i have same issue on windows 10x64 and dnscrypt 2.0.31

its happen when i disable log,
but when log enable, the issue not happen

**Comment by jedisct1** [comment]
I haven't experienced this yet.

Are you using DoH servers or DNSCrypt servers? With or without anonymization?

The one change that I can think of that could make thing not work well "after some time" is the expiring cache for DoH servers IP addresses.

**Comment by Coder84619** [comment]
I'm using DNSCrypt Servers with anonymization.

**Comment by nobura** [comment]
i dont know about DOH protocol, i use on DNSCrypt protocol only,
with anon relay and without anon relay.

i have try enable log to track the problem,
but whan i enable log, the issue not happen

**Comment by gitsnow** [comment]
I'm on Ubuntu 18.04 running 2.0.31 and also have had dnscrypt-proxy randomly stop answering queries every few days.  After restarting the dnscrypt-proxy service, it starts responding again.  I'm using DoH with just Cloudflare as my DNS provider.

**Comment by jedisct1** [comment]
Unfortunately, there is absolutely nothing that can be done without instructions to reproduce this, or an error message, or a stack trace, or the exact version when it started to happen.

As a workaround, you can revert to version 2.0.28. But for the root cause to be fixed, one of the above is needed.

**Comment by gitsnow** [comment]
Why are you closing the issue when you have multiple people reporting the problem?  You have users trying to work to get this problem resolved.

**Comment by jedisct1** [comment]
Realistically, the problem is never going to be fixed by leaving that issue open. It doesn't provide enough information to have an idea at what to look at.

**Comment by gitsnow** [comment]
And you closing the issue before any users can provide you with the information you need to fix the issue guarantees it will never be resolved.

**Comment by jedisct1** [comment]
The first comment seems to suggest that the bug has nothing to do with the Raspberry Pi4 which was what the original issue is about. Maybe we're talking about completely different things. No progress can be made without a fix, or an accurate bug report.
