### ISSUE TITLE
 DNS Leaks

### ISSUE THREAD

**Issue by spinnenbein** [DNSCrypt/dnscrypt-proxy#102]
Under Windows 10 (1709) 64 bit and OpenVPN massive DNS Leaks! Please check!

**Comment by jedisct1** [comment]
Would you mind writing a documentation page about what DNS leaks are, how to check for them and how DNS and VPNs interact?

Based on your initial content, it will be easier to understand the exact problems that may apply and how to solve them.

Thanks!
