### ISSUE TITLE
Questions about Anonymized DNS configuration

### ISSUE THREAD

**Issue by EauBureau** [DNSCrypt/dnscrypt-proxy#1020]
Hi,
I'm having difficulty getting Anonymized DNS up and running.
I've a few questions:

1. Is there a maximum number of relays per server? The example gives 1 or 2 but could I use 5 or ...10?
1. How does dnscrypt-proxy choose between multiple relays? A sequentially different relay each time that server is used? Random? Something else?

1. How does dnscrypt-proxy choose between servers (if you have multiple Anonymized DNS ones configured), random, sequential, latency or something else?

1. Does DNSSEC work with Anonymized DNS? Is it recommended or is plain DNSCrypt preferred?
1. If I have selected a server from public-resolvers.md and it has DNSSEC available can it be used it with out DNSSEC or will it only work with DNSSEC?

1. Is there a default port the relays use on relays.md? Are they all on 443? If I was behind a firewall with only 80 and 443 open would that reach all relays?

1. Why is DNSEC not enabled in the "default" `example-dnscrypt-proxy.toml` by default? Is there a downside to it?
1. Likewise why is DoH enabled by default in the .toml ?

1. As DoH doesn't work with Anonymized DNS do I need to change `doh_servers = true` to `false` or will it work around that?

1. On `dnsleaktest.com` is it the relay and not the server that would be listed?

**Comment by ibksturm** [comment]
hi there


Is there a maximum number of relays per server? The example gives 1 or 2 but could I use 5 or ...10?

- i still use over 6 relays

How does dnscrypt-proxy choose between multiple relays? A sequentially different relay each time that server is used? Random? Something else?

- as i read this evening @jedisct1 is still working at

How does dnscrypt-proxy choose between servers (if you have multiple Anonymized DNS ones configured), random, sequential, latency or something else?

- work in progress

Does DNSSEC work with Anonymized DNS? Is it recommended or is plain DNSCrypt preferred?

- DNSSEC works with it... relays as i understood are just tunnels between your dnsc-proxy and dnsc-resolvers

If I have selected a server from public-resolvers.md and it has DNSSEC available can it be used it with out DNSSEC or will it only work with DNSSEC?

- as i know when dnssec is on, than its on, if its off, its off... 
if you wanna be more secure youll have to run dnssec validation with dnsmasq or unbound, forwarding internal to dnsc-proxy 

Is there a default port the relays use on relays.md? Are they all on 443? If I was behind a firewall with only 80 and 443 open would that reach all relays?

- no, example ibksturm dnssc-server & relays runs of reasons on 8443

Why is DNSEC not enabled in the "default" example-dnscrypt-proxy.toml by default? Is there a downside to it?

- don‘t know

Likewise why is DoH enabled by default in the .toml ?



As DoH doesn't work with Anonymized DNS do I need doh_servers = true to false or will it work around that?

- DoH doesnt work on Anon‘s ‚cause their technology is different like apple and pumpkins, or schokoladeicecream and oreos or mc-yellow-M and CrownMen.

**Comment by EauBureau** [comment]
Thanks ibksturm.
> as i read this evening @jedisct1 is still working at

> work in progress

Is Anonymized DNS not meant to be used just yet?
I thought it was ready to go.

**Comment by ibksturm** [comment]
@EauBureau 

as i understood (i‘m thankfull if i get corrected) anon as protocol works fine, but the next brik in the wall is to get it randomised

as playing lego, its gonna be funny 👍

**Comment by EauBureau** [comment]
Ok thanks.

**Comment by jedisct1** [comment]
>    Is there a maximum number of relays per server? The example gives 1 or 2 but could I use 5 or ...10?

You can use as many as you like. But to be honest, having more than 2 is pretty much useless.

>    How does dnscrypt-proxy choose between multiple relays? A sequentially different relay each time that server is used? Random? Something else?

For each server, a random relay of the set is selected, and used until the end.

Randomization of individual queries is going to be implemented, even though I'm not really convinced that it is useful.

>    How does dnscrypt-proxy choose between servers (if you have multiple Anonymized DNS ones configured), random, sequential, latency or something else?

Depends on the load-balancing strategy you configured. By default, it picks the two fastest servers.

>    Does DNSSEC work with Anonymized DNS? Is it recommended or is plain DNSCrypt preferred?

DNSSEC doesn't depend on the transport. It works with anonymized DNS, DNSCrypt, DoH, even on good old completely unencrypted and insecure DNS.
It only depends on the server. Some servers support it, some don't.

>    If I have selected a server from public-resolvers.md and it has DNSSEC available can it be used it with out DNSSEC or will it only work with DNSSEC?

Yes, servers able to do DNSSEC validation can also return non-DNSSEC records. Or else, virtually everything on the Internet wouldn't work :)

>    Is there a default port the relays use on relays.md? Are they all on 443? If I was behind a firewall with only 80 and 443 open would that reach all relays?

Most use port 443, but it could be any port. Relay operators choose what they want to use.

>    Why is DNSEC not enabled in the "default" example-dnscrypt-proxy.toml by default? Is there a downside to it?

DNSSEC require individual domains to be explicitly configured to enable it. This is not a global switch.
And sadly, besides websites to check if DNSSEC is supported, virtually nothing supports it. Not even Google. Or Microsoft. Or Facebook. Or banks.
The default used to be `true`, but in practice, having access to more servers is more useful than restricting them to the set that supports DNSSEC.

>    Likewise why is DoH enabled by default in the .toml ?

Why not? Everyone doesn't want to use Anonymized DNS, and in some places or on some network configurations, DoH servers may be faster or more reliable than other options. By default, `dnscrypt-proxy` allows all non-logging servers to be potential candidates, no matter what protocol they support, and the ones that get actually used are the fastest ones.

>    As DoH doesn't work with Anonymized DNS do I need to change doh_servers = true to false or will it work around that?

Ideally, you should change `server_names` to only list the servers you want.
If you enable DoH servers, they will be used, but the traffic will not be anonymized.

>    On dnsleaktest.com is it the relay and not the server that would be listed?

It should be the server. They can't see the relay.

**Comment by EauBureau** [comment]
Great answers. Thank you.

I'm just a basic user with very little knowlwdge of how DNS, dnscrypt, DNSSEC etc actually work.
So please excuse my ignorance if these are dumb points...

First some feedback: It wasn't clear to me that Anonymized DNS servers had to be also listed in `server_names` (~line 30 of the .toml). 
I think that could be made clear in the [Anonymized DNS wiki](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Anonymized-DNS) page.
 I just got it from you answer above and that's what finally got it working for me.


A couple more questions... (sorry!)

#### 1 In reality is DNSSEC pointless?
> DNSSEC require individual domains to be explicitly configured to enable it. This is not a global switch.

> And sadly, besides websites to check if DNSSEC is supported, virtually nothing supports it.

Wow!!! :open_mouth: Do I understand this correctly: Websites have to enable DNSSEC _individually_ for it to be useful, but none in the real world actually do?

So in reality DNSSEC can be just be ignored?



#### 2  What do you mean by "until the end"?
> For each server, a random relay of the set is selected, and used until the end.

The end of the current DNS query (i.e a matter of milliseconds or seconds)? Until the dnscrypt-proxy system reboots? Until the end of a 24hr period?


#### 3 Does the _sequence_ of relays in the route matter?
If I had `relay1 relay2 relay3` and re-used those for three for three different servers would that leak anything? (Having the same 3 relays in the same sequence.)
Is there any meaningful difference if I arranged them `relay3 relay2 relay1`?

#### 4  Is there any way to test... 
...and be sure that requests are actually going through the relays and not just going direct to the servers listed in `server_names` (~line 30 of .toml)?


#### 5 I have five Anonymized servers enabled and appear to be working

On dnsleaktest.com most times it only returns 2 servers!?
I've relaunched the service a few times and sometimes it will show four servers 
But it mostly only returns 2 servers? 
Is that wrong or is it normal for only a couple to be active at a time?



By the way, Anonymized DNS is a really great idea. Thank you. :thumbsup:

**Comment by EauBureau** [comment]
After some research I can answer some of my own questions, they may help others.

> #### 1 In reality is DNSSEC pointless?

If my understandig is correrct: yes.

> #### 3 Does the sequence of relays in the route matter?

Just thinking about it, it shouldn't matter. The servers have no knowledge of the other relays. Only the random one currretly being used.

> #### 5 I have five Anonymized servers enabled and appear to be working

With the default [load balancing strategy](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Load-Balancing-Options) I think 2 serves is actually correct.
`'p2'` = randomly choose between the top 2 fastest servers.


If anyone wants to chime in on **2** and **4** feel free.
