### ISSUE TITLE
 doubts about Anonymized DNS

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#1022]
Thanks for a great job done, and I'm writing to get clarifications on how to set the dns relays in the toml configuration file.

1. First of all if imposed as "cloudflare" server names (`example: server_names = ['cloudflare']`) can I then set the anonymous dns?

2) if I remain DOH on true (doh_servers = true) will the anonymous dns work? or should it be disabled because it could support the service on doh?

3) the list of server names where I find it? the stamp which to use? Can I use stamps for different server names?
```
routes = [
   { server_name='example-server-1', via=['anon-example-1', 'anon-example-2']$
   { server_name='example-server-2', via=['sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM$
]
```
example this stamp "sdns: // gRIxMzcuNzQuMjIzLjIzNDo0NDM" can I use it with any server names? 
if so, which ones do you use which are the best? 
and if I set cloudflare as server names only and set the stamp on server name as a convenient example with a stamp it will work?
give me a concrete example of what to insert to unsubscribe the anonymous dns, at least 2 I think they serve right?

**Comment by EauBureau** [comment]
Hi, I'm just a dnscrypt-proxy user like you. I asked about item 2 in #1020  
The answer 
>>As DoH doesn't work with Anonymized DNS do I need to change `doh_servers = true` to `false` or will it work around that?

>Ideally, you should change server_names to only list the servers you want.
If you enable DoH servers, they will be used, but the traffic will not be anonymized.


The servers are in [here](https://github.com/DNSCrypt/dnscrypt-resolvers)

I can't answer the rest.

**Comment by jedisct1** [comment]
See the documentation: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Anonymized-DNS

**Comment by tigernero79** [comment]
sorry but if a server name uses both doh and dot who establishes which protocol to use in the server? also remaining active doh?

in addition, if no specific relay dnscrypt uses the "relays.md" file or should a relay be specified anyway?

**Comment by tigernero79** [comment]
@jedisct1 do you know an Italian dnscrypt server that supports dnssec doT and anonymous dns?
