### ISSUE TITLE
question: if I don't set a server_names

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#1024]
if in the configuration file I don't set any server_names,
 but I enable the dnssec to true and the doh to false 
I get 36 valid dns servers, 
I wonder for the anonymous dns I have to specify all 36 servers which timbres to use or to put the character "*"?

example of setting without having specified any server_names

```
routes = [
    { server_name='*', via=['sdns://gRIxODUuOTQuMTkzLjIzNDo0NDM', 'anon-scaleway'] },
 ]
```

put "*" okay?

**Comment by volcbs** [comment]
Yes, it should be fine to do that. I use the same configuration as well.

**Comment by jedisct1** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Anonymized-DNS#configuring-anoymized-dns-in-dnscrypt-proxy
