### ISSUE TITLE
Secure DNS on android systems

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#1026]
I have satisfactorily configured a dnscrypt-proxy system with PiHole, and anonymous DNS via relay and it goes very well, I was wondering when I'm out of the home network while losing the anonymous DNS, what do you set as a secure DNS to be quiet?  or can DNS relays be managed?  scalaway-fr can be put as secure DNS in android settings?

**Comment by jedisct1** [comment]
On Android, you can check out [InviZible](https://github.com/Gedsh/InviZible)

There is also a whole thread dedicated to running dnscrypt-proxy on Android: https://github.com/DNSCrypt/dnscrypt-proxy/issues/41

Unfortunately I don't have an Android device so I can't help much with that.

**Comment by tigernero79** [comment]
don't you have android?  do you use sailfish?  ios?  how do you protect dns outside your network?

**Comment by jedisct1** [comment]
iOS has [DNSCloak](https://itunes.apple.com/us/app/dnscloak-dnscrypt-client/id1452162351) which is probably the best mobile DNS client ever made.

**Comment by BrigsLabs** [comment]
for non rooted android phone, i use [adguard](https://github.com/AdguardTeam/AdguardForAndroid/releases), but until their 3.3b2 version still not have implementing relay dns. but i can choose custom stamp dns for dnscrypt server or doh version.

**Comment by tigernero79** [comment]
obviously private DNS option of android 9 to go up does not allow you to choose a relay, and if active it bypasses my dnscrypt-proxy with PiHole while still being in my lan?
