### ISSUE TITLE
Forwarding rules seems not working when domain contains number?

### ISSUE THREAD

**Issue by majiayeah** [DNSCrypt/dnscrypt-proxy#1027]
Hi,

I followed the Wiki to enable the Forwarding rules.
but found it is not working at all. The domain in the forwarding rules is still resloved by servers in configuration.
No forwarding at alll.

For example, I set:

>taobao.com 223.5.5.5

but found the followed two results are totally diffrent: (CDN is used by taobao.com)
>nslookup taobao.com 127.0.0.1
>nslookup taobao.com 223.5.5.5

I have tried many times with different ways and different site. None of it works.
My PC is Windows 10 1809, 64bit.
dnscrypt is version 2.0.31

I also find #898 and #816 mentioned this problem, and were closed without any solution.

So, what is the problem? Can it be solved?

Thanks.

**Comment by jedisct1** [comment]
What happens if you put a random IP such as '1.2.3.4'  instead of a resolver address such as `223.5.5.5`?

**Comment by majiayeah** [comment]
> What happens if you put a random IP such as '1.2.3.4' instead of a resolver address such as `223.5.5.5`?

I put '0.0.0.0' in, then get this in log file:
`127.0.0.1	www.taobao.com	A	DROP	2000ms	0.0.0.0:53`
and get this in CMD:
`ping cannot find the site www.taobao.com`
Looks like the forwarding rule works!

**However, that's not the ending.**

I used 'taobao.com' for instance at first.
The real site I found the problem on is
`s1.hdslb.com`
which is contained in a site page.

If I put this in forwarding rules:
`hdslb.com 0.0.0.0`
I get this in log:
`127.0.0.1	s1.hdslb.com	AAAA	PASS	0ms	-`
and I still can ping the 's1.hdslb.com' with a valid IP.
This is strange. Where does the IP address come from?
(I have cleaned the DNS cache.)

So it seems the forwarding rule is not working for site 's1.hdslb.com'

These results confused me.

 **maybe the forwarding rule will not work if the domain contains number?** 
like 's1' in this example.
I notice #898 also used domains with numbers.

**Comment by majiayeah** [comment]
@jedisct1

**Comment by jedisct1** [comment]
Try forwarding `kunlunar.com` maybe?

**Comment by majiayeah** [comment]
> Try forwarding `kunlunar.com` maybe?

It did not work for domain `s1.hdslb.com`.
The result is the same as I discribed upon.

I have test other domains which contain numbers,
and found most of them works in Forwarding,
except this one `s1.hdslb.com`
Very confused.
