### ISSUE TITLE
Colored or black&white?

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#1030]
![dnscrypt-logo](https://user-images.githubusercontent.com/124872/68513687-f56cc280-027b-11ea-8bb5-3407cb51850c.png)

![dnscrypt-logo copy](https://user-images.githubusercontent.com/124872/68513685-f3a2ff00-027b-11ea-829f-8b30a750db1c.png)

**Comment by evilvibes** [comment]
Colored!
