### ISSUE TITLE
How to kill the service properly?

### ISSUE THREAD

**Issue by punyanagari** [DNSCrypt/dnscrypt-proxy#1031]
Hey!
When I use 
./dnscrypt-proxy -service stop it stops the service successfully 
But then after this ./dnscrypt-proxy -service start fails

I have to reboot again to get it working
Can you show me how to kill it properly? I tried using pid but Im doing something wrong

Thanks!

**Comment by jedisct1** [comment]
What version? What operating system? What happens when you type `./dnscrypt-proxy -service start`? What do you get in log files, especially after increasing verbosity?

**Comment by punyanagari** [comment]
Hi,
version 2.0.31 , Raspbian
I tried using this instead and it's working now:

sudo service dnscrypt-proxy start
sudo service dnscrypt-proxy stop

Is this the right way?

and this is working

**Comment by jedisct1** [comment]
If this is working, don't change anything ;)
