### ISSUE TITLE
dnscrypt-proxy  for  Windows XP

### ISSUE THREAD

**Issue by safsktyqne** [DNSCrypt/dnscrypt-proxy#1033]
Hello.

I tried to launch **dnscrypt-proxy.exe** on **Windows XP SP3**. 
An error has occurred: 
`C:\ProgsXP\dnscrypt-proxy-win32-2.0.31\dnscrypt-proxy.exe is not a valid Win32 application.`

Could you please build **dnscrypt-proxy** for **Windows XP SP3**?

The program **Dependency Walker** shows that the **dnscrypt-proxy.exe** depends on **KERNEL32.DLL** and all the necessary functions in this library are available.

Thanks.

P.S. Guys, please, let's not start discussing the topic that **Windows XP** is outdated.

**Comment by alisonatwork** [comment]
It seems like WinXP support was dropped in 2.0.17: https://github.com/DNSCrypt/dnscrypt-proxy/releases?after=2.0.18  Downloading an older version might work, though.

**Comment by jedisct1** [comment]
Unfortunately, the compiler itself cannot generate code for Windows XP any more.

So, yes, one option is to use an older version of the proxy. Or try to port the current code to old versions of the Go compiler.
