### ISSUE TITLE
Analyze the different logfile, tool recommendation ?

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#1035]
Hi, 
just wanted to use some log file analyzer tools to analyze the various logfile but did not get them working.
Also awstats which can be customized a lot can't get it done.

Does anybody of ypu have some tips for me ?

Thanks

**Comment by jedisct1** [comment]
At some point, I used Flowgger to parse the LTSV logs, and push that into Elasticsearch. It worked really well, but this may not be the easiest thing to setup.

**Comment by jedisct1** [comment]
Also, Elasticsearch is not enough, you need Kibana for visualization. If you already have such a stack deployed for something else, you can reuse it. If not... it’s a bit painful to deploy this just for DNS.

So, I’d also interested in alternatives :)

**Comment by scubasunny** [comment]
I tried to get in done in awstats, but without hacking the source (perl) code it also does not work as awstats expects certain hardcoded values as request method a GET or POST (as usual in httpd logs)
