### ISSUE TITLE
Encrypted ESNI?

### ISSUE THREAD

**Issue by privacyguy123** [DNSCrypt/dnscrypt-proxy#1036]
Does this actually mean anything or just a shameless plug to try and get more people using Cloudflare DNS? https://www.cloudflare.com/ssl/encrypted-sni/

![image](https://user-images.githubusercontent.com/50337995/68702402-acb95000-0580-11ea-8e89-ea86316b867e.png)

**Comment by jedisct1** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/issues?utf8=%E2%9C%93&q=is%3Aissue+esni
