### ISSUE TITLE
relays.md: read-only file system

### ISSUE THREAD

**Issue by barraponto** [DNSCrypt/dnscrypt-proxy#1037]
Every time I start or restart dnscrypt-proxy I see these warnings:

    /etc/dnscrypt-proxy/relays.md: open sf-nqrxcc4tl3wtjxwn.tmp: read-only file system
    /etc/dnscrypt-proxy/relays.md.minisig: open sf-zawy7ceyqecnt7e2.tmp: read-only file system

I used to see the same issue for `/var/cache/dnscrypt-proxy/public-resolvers.md` but i fixed it with `chown dnscrypt-proxy:dnscrypt-proxy /var/cache/dnscrypt-proxy/public-resolvers.md`.

**Comment by jedisct1** [comment]
It means that the partition where the `/etc` directory is cannot be written to.

**Comment by jedisct1** [comment]
Or maybe you're using a funky systemd unit file that prevents the proxy from working with your configuration.

**Comment by vbauerster** [comment]
I had same problem on arch linux. Feeding `cache_file` with full path for both [resolvers](https://github.com/DNSCrypt/dnscrypt-proxy/blob/2c49804bd0f3461a39019637d579048eb05d43d8/dnscrypt-proxy/example-dnscrypt-proxy.toml#L540) and [relays](https://github.com/DNSCrypt/dnscrypt-proxy/blob/2c49804bd0f3461a39019637d579048eb05d43d8/dnscrypt-proxy/example-dnscrypt-proxy.toml#L548) fixed the problem for me.

**Comment by barraponto** [comment]
Yes, that was the case. I'll write it down in the Arch wiki and propose a patch to the default settings in the Arch package.

**Comment by dvzrv** [comment]
Hi! I'm packaging dnscrypt-proxy for Arch Linux.
For integrational purposes, the relative paths for `cache_file` get patched to be absolute paths (so they point to `/var/cache/dnscrypt-proxy` according to FHS).
Additionally, the cache folder is owned by the user `dnscrypt-proxy`.

Seems I didn't see a few paths in the last release though. I have updated the patch, so everything should work as intended again.
