### ISSUE TITLE
[WARNING] [2.dnscrypt-cert.cryptostorm.is.] Incorrect signature

### ISSUE THREAD

**Issue by pjnsmb** [DNSCrypt/dnscrypt-proxy#1038]
If I use the cryptostorm  cs-uk server my dnscrypt-proxy.log shows-

[WARNING] [2.dnscrypt-cert.cryptostorm.is.] Incorrect signature

If I try  my other  local European cryptostorm servers they show up in my Sorted latencies section of the log without a problem.
Is this a problem my end or does someone have to update a record somewhere to remove this warning message ? 

thanks
pjnsmb

**Comment by tigernero79** [comment]
server certificate issue, come out to me too when I set all the dns servers to test and on that server gave error.

**Comment by jedisct1** [comment]
Tell Cryptostorm about it maybe? Also check your clock.

**Comment by jedisct1** [comment]
Confirmed. There is definitely an issue with that server, even with a correct clock.

This is not the correct repository for these issues, though.
