### ISSUE TITLE
ddns duckdns service does not update immediately

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#1041]
I noticed that since I activated scalaway-fr as a DNS server and two different anonymous DNS relays every time my duckdns.org ddns service updates itself to their site it brings updated ip, the request to scalaway-fr server always brings me  old ip, i think after an hour the question is solved.  the propagation of the new ip on dnscrypt servers as ever so slow?

**Comment by tigernero79** [comment]
@jedisct1 if imposed as a cloudflare server its cache is updated immediately after 3 minutes the new ip on duckdns.org's ddns service is updated, if I set scalaway-fr instead I have to wait an hour and pass before I see new ip.  strange.
according to you the problem of the delay in the propagation of the new ip on scalaway-fr server depends on the 2 relays used or by scalaway own?

**Comment by jedisct1** [comment]
Scaleway-fr has been configured to cache records for at least 1 hour. This drastically improves performance, but the flip side is that records from dynamic DNS services are not updated immediately.
