### ISSUE TITLE
Load balancing for Anonymizers

### ISSUE THREAD

**Issue by privacyguy123** [DNSCrypt/dnscrypt-proxy#1042]
If I add more than one server under Anonymized DNS does it pick the fastest out of them all or hop through them all? It seems counterproductive to add unncessary latency, whether it be in the name of privacy or not. 😛

**Comment by jedisct1** [comment]
It currently does what the documentation says.

**Comment by privacyguy123** [comment]
Is it possible to have the loadbalancer options work for Anonymizers too then?

**Comment by jedisct1** [comment]
Everything is possible if somebody does it..

**Comment by privacyguy123** [comment]
I mean I guess that sort of answers my question ...

Is it a feature you are working on? 😄

**Comment by jedisct1** [comment]
Absolutely not :) What I'm working on right now is finding a way to fly back home after Delta screwed up.
