### ISSUE TITLE
dnscrypt-proxy for openWRT stopped working

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1044]
I had dnscrypt-proxy 2.0.25 working on openWRT since the 18.06.04 release in July. Everything was functioning properly with my chosen servers until the past month. I started having issues recently with my connection and decided to check out my settings and found that my router is no longer using my chosen DNS servers and is using Comcast again. I tried updating to the lastest dnscrypt-proxy version and still no luck.

Is Comcast doing something new to bypass my DNS?

**Comment by jedisct1** [comment]
What does your `/etc/resolv.conf` file contain?

**Comment by ghost** [comment]
search lan
nameserver 127.0.0.1

**Comment by jedisct1** [comment]
Can you check if `dnsmasq` is forwarding everything to the IP address `dnscrypt-proxy` is listening to?

**Comment by ghost** [comment]
1
      2 config dnsmasq
      3     option domainneeded '1'
      4     option boguspriv '1'
      5     option filterwin2k '0'
      6     option localise_queries '1'
      7     option rebind_protection '1'
      8     option rebind_localhost '1'
      9     option local '/lan/'
     10     option domain 'lan'
     11     option expandhosts '1'
     12     option nonegcache '0'
     13     option authoritative '1'
     14     option readethers '1'
     15     option leasefile '/tmp/dhcp.leases'
     16     option resolvfile '/tmp/resolv.conf.auto'
     17     option nonwildcard '1'
     18     option localservice '1'
     19     option noresolv '1'
     20     option localuse '1'
     21     option strictorder '1'
     22     list server '127.0.0.53'
     23     option serversfile '/tmp/adb_list.overall'

**Comment by jedisct1** [comment]
If you stop `dnsmasq` (maybe with `pkill -STOP dnsmasq`? I don't know if `pkill` exists on OpenWRT), can you still access websites?

**Comment by ghost** [comment]
Using:

/etc/init.d/dnsmasq stop 

(OpenWRT method)

I was unable to connect to anything

**Comment by jedisct1** [comment]
And what if you restart `dnsmasq` but stop `dnscrypt-proxy`?

**Comment by ghost** [comment]
When stopping dnscrypt-proxy, I have inconsistent connection. I can't connect to the majority of sites but oddly I was able to connect to Twitch.tv and load a stream chat with people chatting but not the stream video.

**Comment by jedisct1** [comment]
What does `dnscrypt-proxy -resolve example.com` return?

**Comment by ghost** [comment]
I tried stopping dnsmasq again and this time pages loaded similarly to when I stopped dnscrypt-proxy. Some sites load, others don't and some load after a minute or so.

This is what happens with -resolve:

Resolving [example.com]

Domain exists:  yes, 2 name servers found
Canonical name: example.com.
IP addresses:   2606:2800:220:1:248:1893:25c8:1946, 93.184.216.34
TXT records:    v=spf1 -all
Resolver IP:    172.68.53.71

**Comment by jedisct1** [comment]
So, your router is not using Comcast, but Cloudflare.

Maybe your computer was configured to use your router for IPv4 DNS resolution, but Comcast for IPv6.

**Comment by ghost** [comment]
That makes sense. I do have cloudflare-ipv6 chosen in my server list for my dnscrypt-proxy.toml file though. Is it possible I have something incorrectly configured there?

**Comment by jedisct1** [comment]
The router is probably fine, and the issue may rather be in your computer (or whatever device you are using) DNS configuration.

**Comment by jedisct1** [comment]
Going to grab something for dinner.

What should I get at Wendy's?

**Comment by ghost** [comment]
Haven't been there is a while but I've always liked the Dave's double

**Comment by ghost** [comment]
Thanks for the help, I'll look into what my PC setting are

**Comment by jedisct1** [comment]
Thanks for the suggestion! I went for Dave's double.
