### ISSUE TITLE
a very exciting feature

### ISSUE THREAD

**Issue by wysnxzm** [DNSCrypt/dnscrypt-proxy#1045]
First of all:https://github.com/bitbeans/SimpleDnsCrypt/issues/453
I came up elsewhere, but I was redirected here.
What I want is whether it is possible to request multiple DNSs in parallel and then get a ip result set of a domain name, and then make a delay to judge the ip using the lowest delay.
When using protocols such as doh and dot, the network usually becomes slow, and I hope to optimize it this way!
Thank you for your contribution!

**Comment by jedisct1** [comment]
Same answer here. This is a terrible idea.

**Comment by wysnxzm** [comment]
> Same answer here. This is a terrible idea.

Ok, you are a developer and you have the final say.
If you or someone else will reconsider this need one day, please let me know.

**Comment by wysnxzm** [comment]
> Same answer here. This is a terrible idea.

Dns chooser This is what I want, it can improve my network status and avoid me accessing invalid IP
Usually, I don't need a lower latency, but I need an ip that I can access normally.
In my country, the pollution of dns is very serious.
