### ISSUE TITLE
Feature request - add an option to block blacklisted domains when they appear in the DNS reply

### ISSUE THREAD

**Issue by ebouaziz** [DNSCrypt/dnscrypt-proxy#1046]
Hi,
you may have heard of the 1st-party trackers issue : some tracking company fool ad-blockers and try to workaround the GDPR by having their clients point a subdomain of their site to the tracker's domain using CNAME like this:
```
dig +short f7ds.liberation.fr
liberation.eulerian.net.
atc.eulerian.net.
109.232.197.179
```

As you can see, the query is not blocked although eurelian.net is in the blacklist:
```
dig +short liberation.eulerian.net
"This query has been locally blocked" "by dnscrypt-proxy"
```

See here for an in-depth analysis of the situation by Aeris: https://blog.imirhil.fr/2019/11/13/first-party-tracker.html (it is in written in french).
A side-effect of this setting is that the tracking company has now access to the cookies of their clients' site, including session cookies. And it can also run scripts with the same privileges.

So it would be nice to have the option to enforce the blacklist in this case as it has a real practical benefit.

**Comment by iWARR** [comment]
@ebouaziz 
Thanks for "situation by Aeris". That was scary interesting...
(I saw this problem first time in the uBO's thread and will keep an eye on it)

And what will happen if I simply put a rule with mask into the BlockList (to block this tracker globally)? I.e.:

`*eulerian.net`

(Of course, we keep in mind that any built-in DNS code parts inside the Browser (e.g DoH, etc.) AND Windows OS ("Dnscache" service) are disabled and we have ONLY "dnscrypt-proxy" for all DNS-relative tasks (incuding his own cache).

Or may be all these redirects will happen only on server's side (user and DNSCrypt just waiting for the response on the 1-st main query and it dorsn't know anything whether queried domain and IP are not spoofed?

**Comment by ebouaziz** [comment]
@iWARR 
I'm not sure I understood your questions
> And what will happen if I simply put a rule with mask into the BlockList (to block this tracker globally)?

In the 2 exmaples above, `*.eulerian.net` **is** in the blocklist.
But the dnscrypt-proxy compares only que query to the blocklist, not the reply. And `eulerian.net` does not appear on the query (`f7ds.liberation.fr`).

> Or may be all these redirects will happen only on server's side

They happen on the recursive resolver and are visible by the dns client (here `dig`), but not by most software that use `gethostbyname()` and see only the resulting IP address. They **are** visible by DNSCrypt-proxy, which sees the whole reply, not just the resulting IP address. So I suppose DNSCrypt-proxy could compare the reply to the blocklist.

**Comment by jedisct1** [comment]
I'd recommend blocking `109.232.197.*` instead.

Matching `CNAME` pointers against blacklists and whitelists will be added. But be aware that this will potentially make queries require 150 times more CPU time.

**Comment by jedisct1** [comment]
Closing because this is a duplicate. Matching `CNAME` pointers was already suggested a while back.
