### ISSUE TITLE
why don't I receive cloudflare server dns Roma?

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#1047]
I know that Cloudflare has enabled its own dns servers in Rome, as well as Milan and yet when I choose cloudflare as a server with dnsleak I find only Ip of the server of Milan and not Rome.  I'm wrong?

![Screenshot_20191115-232722_Chrome](https://user-images.githubusercontent.com/35575744/68980038-8fde8000-07ff-11ea-90d7-972c23ada40d.jpg)

**Comment by jedisct1** [comment]
Cloudflare is free to route the traffic the way they want.

Maybe their Milan servers are faster than the Rome ones from your ISP. Network latency doesn't only depend on geographical distance.

If you feel like their routing tables are not optimal, you should report it on their forums. There's nothing that can be done client-side.
