### ISSUE TITLE
MacOS - Which is the best place for the proxy application?

### ISSUE THREAD

**Issue by idanka** [DNSCrypt/dnscrypt-proxy#105]
Which is the best place for the application?

/Library/Application Support/DNSCrypt2
/usr/local/bin/DNSCrypt2
/usr/local/sbin/DNSCrypt2
/usr/local/lib/DNSCrypt2

or irrelevant?
Thx!

**Comment by jedisct1** [comment]
It's irrelevant. I just keep it in my home directory. It can be anywhere, really.

**Comment by idanka** [comment]
Thx:)
