### ISSUE TITLE
Pass querus through on home network?

### ISSUE THREAD

**Issue by wigster** [DNSCrypt/dnscrypt-proxy#1051]
Hi,

Not sure this is the right place to ask, but not sure where else.

I am running dnscrypt-proxy + pihole on my home network. I would like to install dnscrypt-proxy also on my Windows clients, which sometimes leave home. I would thus like to have the clients use their local dnscrypt-proxy whenever outside of the home network, but automatically switch to the DNS as instructed by the router when connected to the home network.

Essentially it would be some kind of DNScrypt passthrough on particular networks. Is such a thing possible? I suspect this is something that the system DNS  settings should take care of, but I am not sure there is a way of getting Windows to change DNS servers depending on the network it is connected to.

Thanks!

**Comment by jedisct1** [comment]
I don't think Windows can set a specific set of DNS resolvers for a given network (unlike MacOS :) ) but this seems to be possible with Powershell:

https://superuser.com/questions/1123456/specific-dns-setting-for-one-wifi-connection
