### ISSUE TITLE
panic: runtime error with 2.0.32

### ISSUE THREAD

**Issue by dave0003** [DNSCrypt/dnscrypt-proxy#1053]
After upgrading from 2.0.31 to 2.0.32 (linux_x86_64 version on centos-7), restarting the service, and trying to resolve an address, I get this error and dnscrypt-proxy crashes:

`Nov 18 16:50:21 server dnscrypt-proxy: [2019-11-18 16:50:21] [NOTICE] dnscrypt-proxy is ready - live servers: 3`
`Nov 18 16:50:26 server dnscrypt-proxy: panic: runtime error: invalid memory address or nil pointer dereference`
`Nov 18 16:50:26 server dnscrypt-proxy: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x83efaa]`
`Nov 18 16:50:26 server dnscrypt-proxy: goroutine 39 [running]:`
`Nov 18 16:50:26 server dnscrypt-proxy: main.(*BlockedNames).check(0x0, 0xc00005e340, 0xc000ad4520, 0xa, 0xd61920, 0xb)`
`Nov 18 16:50:26 server dnscrypt-proxy: /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:104 +0x3a`
`Nov 18 16:50:26 server dnscrypt-proxy: main.(*PluginBlockName).Eval(0xc00000e088, 0xc00005e340, 0xc0000b22d0, 0x0, 0x0)`
`Nov 18 16:50:26 server dnscrypt-proxy: /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:100 +0xe3`
`Nov 18 16:50:26 server dnscrypt-proxy: main.(*PluginsState).ApplyQueryPlugins(0xc00005e340, 0xc0000ca290, 0xc000b02000, 0x27, 0xfff, 0xc0000eac28, 0xd, 0x0, 0x0, 0x0, ...)`
`Nov 18 16:50:26 server dnscrypt-proxy: /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugins.go:251 +0x1f7`
`Nov 18 16:50:26 server dnscrypt-proxy: main.(*Proxy).processIncomingQuery(0xc0000ca000, 0xc000af4000, 0x95b6dd, 0x3, 0x95b6dd, 0x3, 0xc000b02000, 0x27, 0xfff, 0xc000ae0320, ...)`
`Nov 18 16:50:26 server dnscrypt-proxy: /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:367 +0x26d`
`Nov 18 16:50:26 server dnscrypt-proxy: main.(*Proxy).udpListener.func1(0xc0000ca000, 0xc000b02000, 0x27, 0xfff, 0xc000ae0320, 0xc00000e010)`
`Nov 18 16:50:26 server dnscrypt-proxy: /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:219 +0x17f`
`Nov 18 16:50:26 server dnscrypt-proxy: created by main.(*Proxy).udpListener`
`Nov 18 16:50:26 server dnscrypt-proxy: /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:212 +0xbb`
`Nov 18 16:50:26 server systemd: dnscrypt-proxy.service: main process exited, code=exited, status=2/INVALIDARGUMENT`
`Nov 18 16:50:26 server systemd: Unit dnscrypt-proxy.service entered failed state.`
`Nov 18 16:50:26 server systemd: dnscrypt-proxy.service failed.`

Reverted back to 2.0.31 and it works fine again.  Just reporting the error, no problem running the older version.

**Comment by jedisct1** [comment]
Download it again, or add a `log_file` to the `[blacklist]` section.
If you don't want logging, you can use

```toml
log_file = '/dev/null'
```
