### ISSUE TITLE
2.0.32 Exec format error

### ISSUE THREAD

**Issue by dave0003** [DNSCrypt/dnscrypt-proxy#1054]
Downloaded 2.0.32 (linux_x86_64) a second and third time and get this error, with or without changing all log_file parameters to log_file = '/dev/null'.

`Nov 18 18:18:36 server systemd: Started Encrypted/authenticated DNS proxy.`
`Nov 18 18:18:36 server systemd: Failed at step EXEC spawning /opt/dnscrypt-proxy/dnscrypt-proxy: Exec format error`
`Nov 18 18:18:36 server systemd: dnscrypt-proxy.service: main process exited, code=exited, status=203/EXEC`
`Nov 18 18:18:36 server systemd: Unit dnscrypt-proxy.service entered failed state.`
`Nov 18 18:18:36 server systemd: dnscrypt-proxy.service failed.`

`[root@server dnscrypt-proxy]# ./dnscrypt-proxy`
`-bash: ./dnscrypt-proxy: cannot execute binary file`

**Comment by jedisct1** [comment]
Check that your system has an Intel or AMD CPU. If this is not the case, you need to download the correct version for your device.
