### ISSUE TITLE
2.0.32 about compression

### ISSUE THREAD

**Issue by zlainsama** [DNSCrypt/dnscrypt-proxy#1055]
After switching to dnscrypt-proxy 2.0.32, unbound 1.9.4 is unable to serve "go.skype.com".
Reverting back to dnscrypt-proxy 2.0.31, unbound 1.9.4 served "go.skype.com" normally.
Using dnscrypt-proxy 2.0.32 directly, without unbound, dnscrypt-proxy served "go.skype.com" normally.
I use unbound in front of dnscyrpt-proxy to do filtering and caching, "go.skype.com" is forwarded to dnscrypt-proxy.
I'm on Windows 10 1909, and I'm in China mainland.
I think this might be caused by the compression.
It is quite possible that some other domain also break after the update.
Could you add an option to turn off compression through config so that I can test about it?

**Comment by jedisct1** [comment]
Unfortunately, I was not able to reproduce this, but you can change `true` to `false` here: https://github.com/DNSCrypt/dnscrypt-proxy/blob/925c12d334f20d217d1425acd5f82458a0cd9845/dnscrypt-proxy/plugins.go#L275

**Comment by jedisct1** [comment]
Are you using Cisco resolvers?

**Comment by zlainsama** [comment]
Yes, I'm using Cisco resolvers.
I just compiled and tested without compression, it's same.
Then I switched to cloudflare, unbound served "go.skype.com" normally.
So... the workaround was the problem?

**Comment by jedisct1** [comment]
Yes, this only happens with Cisco.

**Comment by zlainsama** [comment]
Hmm, is there an easy way to revert the workaround?

**Comment by jedisct1** [comment]
The workaround is still needed until they fix their resolvers.

That issue is a different one. I'm going to release 2.0.33 soon.

**Comment by zlainsama** [comment]
2.0.33 works. Thank you.
