### ISSUE TITLE
iOS-App limited to 17 years and older

### ISSUE THREAD

**Issue by Gill-Bates** [DNSCrypt/dnscrypt-proxy#1059]
The App "DNSCloak" is released from 17 years in the AppStore of Apple. Why? I can't use it on children's iOS devices as a content filter. Similar products can be found in the AppStore with a release from 4 or 12 years.

**Comment by jedisct1** [comment]
I guess that limitation was set by Apple, maybe because it uses VPN-like APIs. 

The repository for the DNSCloak project is here: https://github.com/s-s/dnscloak
