### ISSUE TITLE
Own DNS-Server with DNSCloak

### ISSUE THREAD

**Issue by Gill-Bates** [DNSCrypt/dnscrypt-proxy#1060]
Hi There,

I am using Pi Hole on an own Linux Instance and want to use DNSCloak on iOS. But I running into issues and need assistance.

- Pi Hole is up and running
- DNSCrypt-Proxy 2.0 is installed and running
`
$/etc/dnscrypt-proxy# ./dnscrypt-proxy -resolve example.com
`
Will resul tin
`
Resolving [example.com]
Domain exists:  yes, 2 name servers found
Canonical name: example.com.
IP addresses:   2606:2800:220:1:248:1893:25c8:1946, 93.184.216.34
TXT records:    v=spf1 -all
Resolver IP:    74.63.25.244 (res300.ams.rrdns.pch.net.)
`

I create now the Stamp

![image](https://user-images.githubusercontent.com/25774289/69256340-9c752680-0bb9-11ea-97eb-c106617702f4.png)

`
[static.'mycustomdnsserver.com']
stamp = 'sdns://XXXXXX'

Public Key: my 32 Byte SSH Fingerprint from the Server xx:xx:xx

`
DNSCloak will not use it
`
[FATAL] Stamp is too short
`
Where is my mistake? Help is very appreachiated.

**Comment by jedisct1** [comment]
SSH is a different protocol, and a fingerprint is not a public key.

In order to run your own server, you need something like https://github.com/jedisct1/encrypted-dns-server

The stamp is printed when the server starts.
