### ISSUE TITLE
How to check if I’m using Anonymized DNS?

### ISSUE THREAD

**Issue by erasmo52** [DNSCrypt/dnscrypt-proxy#1062]
I changed the configuration to implement the anonymized DNS following the wiki guide and all seem to work fine, but:
How can I check that my query to the destination server effectively pass by the relay servers and  that the destination server doesn't learn anything about my IP addresses?
Visiting the https://browserleaks.com/ip link, it appears my original IP address unlike what happens if I visit the same link in Tor Browser
Thanks for your attention

**Comment by jedisct1** [comment]
You can use a tool such as Wireshark, that displays the network traffic originating from your computer, and check that packets are only sent to the relay.

When relaying is enabled, `dnscrypt-proxy` also prints something about this when it starts.

**Comment by erasmo52** [comment]
You not responded to this my notation.
Visiting the https://browserleaks.com/ip link, it appears my original IP address unlike what happens if I visit the same link in Tor Browser.
Is this behavior normal? I should not see a different IP than mine original?
Thanks for your attention

**Comment by jedisct1** [comment]
Your IP for non-DNS traffic remains the same. This is not a VPN.
