### ISSUE TITLE
Returned an unusable ip

### ISSUE THREAD

**Issue by wysnxzm** [DNSCrypt/dnscrypt-proxy#1063]
The first responding dns returned an ip that I could not ping, which caused me to be unable to access the website. How can I solve it?

**Comment by GrennKren** [comment]
Yeah this was also happen to me but I believe didn't in the previous version. What I'm doing was to unset 127.0.0.1 DNS before starting the service dnscrypt-proxy, and then just set that dns again back to normal, 127.0.0.1.

**Comment by jedisct1** [comment]
Maybe some servers don't return IP addresses that are reachable for your country. Or maybe the website changed its IP address and the new IP didn't propagate to all servers. Or maybe this is an internal server from your ISP and your ISP's DNS returns a different IP than other resolvers.

For the later, you can configure forwarding for the relevant domains.

If this is a temporary configuration issue of the website DNS server, there's not much you can do besides finding a server that may (already or still) have an IP that you can reach.

**Comment by wysnxzm** [comment]
> Maybe some servers don't return IP addresses that are reachable for your country. Or maybe the website changed its IP address and the new IP didn't propagate to all servers. Or maybe this is an internal server from your ISP and your ISP's DNS returns a different IP than other resolvers.
> 
> For the later, you can configure forwarding for the relevant domains.
> 
> If this is a temporary configuration issue of the website DNS server, there's not much you can do besides finding a server that may (already or still) have an IP that you can reach.

Try to get the IP from the alternate dns and test if it is available.
