### ISSUE TITLE
"Network not available" after using "ip netns" command

### ISSUE THREAD

**Issue by phantomcraft** [DNSCrypt/dnscrypt-proxy#1064]
I updated my dnscrypt-proxy lately to 2.0.33 and it's not working with an upstream SOCKS5 proxy, it shows:
```
[2019-11-23 00:00:23] [NOTICE] dnscrypt-proxy 2.0.33
[2019-11-23 00:00:23] [NOTICE] Network not available yet -- waiting...

```
Socks5 proxy is up and running.
Here is my config:

```
listen_addresses = ['172.16.0.2:10053']
max_clients = 2048
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = false
require_nolog = true
require_nofilter = true
disabled_server_names = []
force_tcp = true
proxy = "socks5://172.16.0.2:1080"
timeout = 25000
keepalive = 30
lb_strategy = 'random'
cert_refresh_delay = 240
tls_disable_session_tickets = true
fallback_resolver = '1.1.1.1:53'
ignore_system_dns = true
netprobe_timeout = -1
netprobe_address = "1.1.1.1:53"
log_files_max_size = 1
log_files_max_age = 1
log_files_max_backups = 1
block_ipv6 = false
cache = true
cache_size = 5120
cache_min_ttl = 600000
cache_max_ttl = 86400000
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

  [sources.quad9-resolvers]
  urls = ["https://www.quad9.net/quad9-resolvers.md"]
  minisign_key = "RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN"
  cache_file = "quad9-resolvers.md"
  refresh_delay = 72
  prefix = "quad9-"

  [sources.'opennic']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/opennic.md', 'https://download.dnscrypt.info/resolvers-list/v2/opennic.md']
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = 'opennic.md'

  [sources.'onion-services']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/onion-services.md', 'https://download.dnscrypt.info/resolvers-list/v2/onion-services.md']
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = 'onion-services.md'

```

**Comment by phantomcraft** [comment]
I tested with older versions and I see that this problem starts from 2.0.32 on.

I'm running dnscrypt-proxy inside a network namespace with no default route and a Socks5 proxy on a bridge with the address 172.16.0.2. When I change to 127.0.0.1 instead of the bridge, the same problem persists.

When running in my default network stack (netns 1) with the default route to the Internet, the connection through a SOCKS5 proxy goes fine.

What I'm sure is happening is that before 2.0.32 the connectivity test was performed all through the SOCKS5 proxy even if no connectivity was given by a default route, and after that, from 2.0.32 on the connectivity test is being performed outside the proxy. This is bad because leaks data when TCP output is enabled to go through the proxy.

**Comment by phantomcraft** [comment]
Reproducing this issue:

Run any socks5 proxy server at 0.0.0.0:1080

Create a network namespace with a veth pair, no default route and with the internal loopback interface up:

```
ip netns add nsx
ip link add vethx type veth peer name peerx netns nsx
ip link set vethx up
ip netns exec nsx ip link set peerx up
ip address add 10.0.0.1/24 dev vethx
ip netns exec nsx ip address add 10.0.0.2/24 dev peerx
ip netns exec nsx ip link set lo up
```

SOCKS5 proxy will be accessible inside the network namespace at address 10.0.0.1

Run dnscrypt-proxy inside the namespace with SOCKS5 proxy at 10.0.0.1:1080 (proxy = "socks5://10.0.0.1:1080"):

```
ip netns exec nsx /path/to/dnscrypt-proxy --config /path/to/dnscrypt-proxy.toml
[2019-11-23 23:30:20] [NOTICE] dnscrypt-proxy 2.0.33
[2019-11-23 23:30:20] [NOTICE] Network not available yet -- waiting...
```

Even with the reachable address of the proxy, a default route is needed to initialize a connection in the proxy address.

**Comment by jedisct1** [comment]
I have no idea what these commands do, but if that somehow prevents network connectivity from being detected, you can set `netprobe_timeout` to `0`.

**Comment by phantomcraft** [comment]
Thanks, it solved the problem.

But before 2.0.32, "netprobe_timeout = -1" was working with a SOCKS5 proxy even if no route is detected.

**Comment by jedisct1** [comment]
Before 2.0.32, `netprobe_timeout = -1` didn't work at all :)
