### ISSUE TITLE
update debian version

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1065]
i add debian testing repo, but no new version and github have new version

https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-Debian-and-Ubuntu

thx

**Comment by r4sas** [comment]
Better write bug report at https://bugs.debian.org/. Here we can't help in that.

**Comment by jedisct1** [comment]
Unless you are running debian-testing, just like all other software it ships with, it can take years before a package with a new version is available. And it will still be obsolete by the time a new Debian release is out.

If you need up to date packages, use a distribution with rolling updates such as Arch Linux, or install the software directly using the [generic linux installation instructions](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux).
