### ISSUE TITLE
[systemd] dnscrypt-proxy 2.0.33 Ubuntu PPA doesn't listen to any interfaces

### ISSUE THREAD

**Issue by Shadok** [DNSCrypt/dnscrypt-proxy#1070]
Hello,

I am running Ubuntu 18.04 and installed dnscrypt-proxy from ppa.
But i am unable to use dnscrypt-proxy as it doesn't bind on any interface.

Here is what i did after installing the ppa :
```
$ systemctl stop dnscrypt-proxy.service
$ systemctl stop dnscrypt-proxy.socket
$ systemctl disable dnscrypt-proxy.socket
$ systemctl disable dnscrypt-proxy.service
$ rm /lib/systemd/system/dnscrypt-proxy.service /lib/systemd/system/dnscrypt-proxy.socket
$ rm /var/lib/systemd/deb-systemd-helper-enabled/dnscrypt-proxy.service.dsh-also /var/lib/systemd/deb-systemd-helper-enabled/dnscrypt-proxy.socket.dsh-also /var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/dnscrypt-proxy.service /var/lib/systemd/deb-systemd-helper-enabled/sockets.target.wants/dnscrypt-proxy.socket
$ systemctl daemon-reload
$ systemctl reset-failed
$ dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -service install
$ service dnscrypt-proxy start
```

EDIT - As per given solution below, you should install the service like this : cd /etc/dnscrypt-proxy && dnscrypt-proxy -service install

I stopped systemd-resolved and bind9 services so there is nothing listening on port 53.

With listen_addresses = [] :
```
root@vps:~# service dnscrypt-proxy status
? dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-11-24 11:02:47 CET; 4min 45s ago
 Main PID: 10993 (dnscrypt-proxy)
    Tasks: 10 (limit: 4544)
   CGroup: /system.slice/dnscrypt-proxy.service
           +-10993 /usr/bin/dnscrypt-proxy

Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] -   254ms dnscrypt-07.adsnomore.io
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] -   279ms quad101
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] -   284ms dnscrypt-05.adsnomore.io
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] -   291ms geekdns-hk
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] -   297ms publicarray-au-doh
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] -   305ms publicarray-au
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] -   324ms geekdns-doh-north
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] -   694ms geekdns-doh-east
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] Server with the lowest initial latency: a-and-a (rtt: 4ms)
Nov 24 11:03:30 vps.domain.com dnscrypt-proxy[10993]: [2019-11-24 11:03:30] [NOTICE] dnscrypt-proxy is ready - live servers: 60
root@vps:/etc/dnscrypt-proxy# ss -lp 'sport = :domain'
Netid                            State                             Recv-Q        
```

Same issue with "listen_addresses = ['10.7.0.1:53']", 10.7.0.1 being my openvpn tap interface, where i intend to use dnscrypt-proxy.

No matter how i start it, even with loglevel 0, all i got is "service started" in dnscrypt-proxy.log and normal startup messages in syslog. No error anywhere, but nothing is listening on port 53.

Same result with default config file from ppa.

Here's my config file :
```
listen_addresses = []
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
disabled_server_names = []
force_tcp = false
timeout = 5000
keepalive = 30
cert_refresh_delay = 240
fallback_resolver = '80.67.169.12:53'
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '80.67.169.12:53'
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = true
reject_ttl = 600
cache = true
cache_size = 1024
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[query_log]
  format = 'tsv'
[nx_log]
  format = 'tsv'
[blacklist]
  blacklist_file = 'dnscrypt-blacklist-domains.txt'
[ip_blacklist]
[whitelist]
[schedules]
[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  prefix = ''
  [sources.'relays']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/relays.md', 'https://download.dnscrypt.info/resolvers-list/v2/relays.md']
  cache_file = 'relays.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
[broken_implementations]
broken_query_padding = ['cisco', 'cisco-ipv6', 'cisco-familyshield']
[anonymized_dns]
[static]
```

**Comment by jedisct1** [comment]
When you start `dnscrypt-proxy` with `dnscrypt-proxy -config /path/to/dnscrypt-proxy.toml`, do you see log lines similar to 

```text
[2019-11-24 17:23:50] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2019-11-24 17:23:50] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
```

?

**Comment by Shadok** [comment]
I don't have any listen line.

**Comment by jedisct1** [comment]
With IP addresses in `listen_addresses = [...]`?

**Comment by Shadok** [comment]
With the default listen directive and with the one on my openvpn interface.

**Comment by jedisct1** [comment]
Nothing that says `Now listening to...` even with the default `listen_addresses = ['127.0.0.1:53', '[::1]:53']`?

Well... unfortunately, I don't know what to look for. At that point, I'd just completely remove the package, and install the official package from Github instead.

**Comment by Shadok** [comment]
Not one line :
```
[some output that says "systemd"]
```

**Comment by jedisct1** [comment]
> When you start `dnscrypt-proxy` with `dnscrypt-proxy -config /path/to/dnscrypt-proxy.toml`

Not as a service. You should of course never install the service before it works interactively.

**Comment by Shadok** [comment]
Sorry, missed that point.

It works well that way 👍 
```
[2019-11-24 19:06:50] [NOTICE] Now listening to 10.7.0.1:53 [UDP]
[2019-11-24 19:06:50] [NOTICE] Now listening to 10.7.0.1:53 [TCP]
```

**Comment by jedisct1** [comment]
Since you appear to know linux and systemd pretty well, try figure out what the systemd configuration file does differently than when you type the command yourself.
Maybe the configuration file is not the same?

**Comment by Shadok** [comment]
I don't know if a default file is hardcoded inside dnscrypt-proxy but this line inside the systemd it added is intended for rhel and centos distros :
`EnvironmentFile=-/etc/sysconfig/dnscrypt-proxy`

At the very least, for ubuntu and debian, it should be /etc/default/dnscrypt-proxy.

I tried to define it to this, but it didn't help. I'll keep diging.
`EnvironmentFile=-/etc/dnscrypt-proxy/dnscrypt-proxy.toml`

**Comment by Shadok** [comment]
Daemon works now with with this change :
`ExecStart=/usr/bin/dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml`

It means that a /etc/default/dnscrypt-proxy config file would help with defining variables with default values that should correspond to path where the package install files (eg: /etc/dnscrypt-proxy/dnscrypt-proxy.toml). Then instead of having a path to the config file in the systemd script, we could use the variables loaded from the file defined by the EnvironmentFile variable (/etc/default/dnscrypt-proxy config).

**Comment by jedisct1** [comment]
Looking at the documentation, it seems like you need to be in the directory of the configuration file when the service is installed.

So,

```sh
dnscrypt-proxy -service uninstall
cd /etc/dnscrypt-proxy
dnscrypt-proxy -service install
dnscrypt-proxy -service start
```

may work.

**Comment by Shadok** [comment]
The ppa is already enforcing the config file path by using the same ExecStart as below, but it also create a second service for the dnscrypt-proxy.socket which is forcefully listening on 127.0.2.1:53 :
```
ListenStream=127.0.2.1:53
ListenDatagram=127.0.2.1:53
```

**Comment by Shadok** [comment]
> ```shell
> dnscrypt-proxy -service uninstall
> ```

That's it, it adds this line which makes all the difference 👍 
`WorkingDirectory=/etc/dnscrypt-proxy`

**Comment by Shadok** [comment]
Thanks :)
