### ISSUE TITLE
Why incoming CNAME filtering will become a necessesity over time:

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#1071]
uBlock Origin for Firefox addresses new first-party tracking method
gHacks Technology News  /  Martin Brinkmann

The latest version of the content blocker uBlock Origin for the Mozilla Firefox web browser includes a new feature to detect a new first-party tracking method that some sites have started to use recently.

The issue was first reported ten days ago by user Aeris on the project's official GitHub page. Some sites started to use canonical name records (CNAMEs) to bypass filters used in content blockers. First-party resources, e.g. a subdomain, are not blocked usuall unless they are known to only serve advertisement.

The main issue from a content blocking perspective is that identification and detection is difficult. The extensions would have to uncloak alias hostnames in order to provide the user with information and the ability to do something about it.

Raymond Hill, the developer of uBlock Origin, found a way to address the new first-party tracking method in Mozilla Firefox.

Side-note: Why only Firefox?  Because Mozilla has created DNS APIs that may be used to expose the CNAME while Google has not. For now, it is not possible to protect against this form of tracking in Google Chrome. Hill writes "Best to assume it can't be fixed on Chromium if it does not support the proper API".

Firefox users who upgrade to the latest version of uBlock Origin, may notice a new permission request (Access IP address and hostname information). This is required to unlock access to the DNS API in the browser extension.

Firefox users who run the extension need to do the following to set things up properly on their end:

    Open the Settings of the extension, e.g. from about:addons or by clicking on the dashboard icon in the uBlock Origin interface.
    Check the "I am an advanced user" box on the first page that opens.
    Activate the settings icon next to the option to open the advanced settings.
    Change the value of the parameter cnameAliasList to *.

The change runs the actual hostnames through the filtering that uBlock Origin applies again. The log highlights these in blue.

    Network requests for which the actual hostname differs from the original hostname will be replayed through uBO's filtering engine using the actual hostname. [..] Regardless, uBO is now equipped to deal with 3rd-party disguised as 1st-party as far as Firefox's browser.dns allows it.

The setting of the wildcard means that the process is done for any hostname that differs; this works but it means that a certain number of network requests are processed twice by uBlock Origin.

    The next step is for me to pick a cogent way for filter list maintainers to be able to tell uBO to uncloak specific hostnames, as doing this by default for all hostnames is not a good idea -- as this could cause a huge amount of network requests to be evaluated twice with no benefit for basic users (default settings/lists) while having to incur a pointless overhead -- for example when it concerned CDNs which are often aliased to the site using them.

Hill wants to switch to using a maintained list of known offenders that uBlock Origin (UMatrix will support this as well) will process while leaving any other hostname untouched.
Closing Words

Firefox users may change the configuration to make sure that they are protected against this new form of tracking. Chromium users cannot because the browser's APIs for extensions does not have the capabilities at the time of writing.

Thank you for being a Ghacks reader. The post uBlock Origin for Firefox addresses new first-party tracking method appeared first on gHacks Technology News.

Original Article: https://www.ghacks.net/2019/11/20/ublock-origin-for-firefox-addresses-new-first-party-tracking-method/

**Comment by welwood08** [comment]
This feature has already been implemented 2 days ago and you can expect it to be in the next release. See issue #1067 (and please search all issues next time).

**Comment by jedisct1** [comment]
(and keep the issues short. I didn't read past the title, that was too long)

TBH, I don't think using a `CNAME` is new, nor an evil trick from tracking companies. This is just a way to implement cross-origin requests. If they wanted to work around domain-based content blockers, they would use IP addresses instead.
