### ISSUE TITLE
I think I'm confused between public_resolver and assigned DNS

### ISSUE THREAD

**Issue by rr0ss0rr** [DNSCrypt/dnscrypt-proxy#1072]
I would have thought that the assigned DNS would be from the network of the resolver, but the following shows something different. (The "public-resolver" is retrieved from the dnscrypt-proxy log and the "Assigned DNS" is from a dig +short resolver.dnscrypt.info.  TIA for clarifying my brain fart.

`richard@MacBook-Richard-2:~/bin$ dns
DNSCrypt-Proxy
dnscrypt-proxy (active) public-resolver (quad9-dnscrypt-ip4-nofilter-alt)

Ethernet DNS IP
127.0.0.1

Wi-Fi DNS IP
127.0.0.1

Assigned DNS
74.63.28.246 (res110.mia.rrdns.pch.net) asn (as42)

------------------------------------------------------------------------------------------------------------------------- 2019-11-26 09:19:21
richard@MacBook-Richard-2:~/bin$ dns
DNSCrypt-Proxy
dnscrypt-proxy (active) public-resolver (quad9-dnscrypt-ip4-nofilter-alt)

Ethernet DNS IP
127.0.0.1

Wi-Fi DNS IP
127.0.0.1

Assigned DNS
192.99.183.132 (ip132.ip-192-99-183.net) asn (as16276)

------------------------------------------------------------------------------------------------------------------------- 2019-11-26 10:12:39
richard@MacBook-Richard-2:~/bin$ dns
DNSCrypt-Proxy
dnscrypt-proxy (active) public-resolver (dnscrypt.ca-2)

Ethernet DNS IP
127.0.0.1

Wi-Fi DNS IP
127.0.0.1

Assigned DNS
74.63.28.248 (res310.mia.rrdns.pch.net) asn (as42)

------------------------------------------------------------------------------------------------------------------------- 2019-11-26 16:43:55`

**Comment by jedisct1** [comment]
Is your question

"If I configure `dnscrypt-proxy` to use `dnscrypt.ca-2`, why does the `dnscrypt-proxy -resolve` command say that I'm using `rrdns.pch.net` (which appears to be Quad9)"

?

**Comment by rr0ss0rr** [comment]
Yes ;-) Sorry .. Looks like my question didn't cut/paste correctly

**Comment by jedisct1** [comment]
In order to reduce latency, DNS responses are cached, both by the operating system and by `dnscrypt-proxy`.

The command `dnscrypt-proxy -resolve` uses a special DNS query in order to find what resolver is being used. But this is still a DNS query. As a result, the response is cached.

If you send this query twice in a row, the second response may come from the cache.

If this is not the expected behavior, you may want to restart the service in order to clear the cache.
