### ISSUE TITLE
redirect dnscrypt-proxy (DOH server) to pihole

### ISSUE THREAD

**Issue by jpgpi250** [DNSCrypt/dnscrypt-proxy#1077]
question (apologies for my ignorance on the subject): can the following be achieved, using dnscrypt-proxy?

`client, using system settings (port 53) ► pihole-FTL (dnsmasq) ► unbound (recursive resolver)

DOH client ► dnscrypt-proxy (local DOH server) ▲`

The goal would be to, on the firewall (pfsense), redirect all requests to DOH servers to the local dnscrypt-proxy DOH server, thus eliminating the possibility that clients, including IOT devices, bypass pihole.

Is it possible to use pihole-FTL (dnsmasq) as the server, defined in dnscrypt-proxy?

Thank you for your time and effort.

**Comment by jedisct1** [comment]
This is not going to work. If a connection to a DoH or DNSCrypt server is redirected to another server, this will be detected and the connection will fail.

I wouldn't worry too much about IoT devices, there's still plenty of time before they implement some kind of DNS encryption.

In your scheme, `dnscrypt-proxy` wouldn't be used for anything besides as a DoH server, so you'd better install a DoH proxy instead, such as [doh-proxy](https://github.com/jedisct1/rust-doh). But still, redirections wouldn't work, so it's probably not worth it.
