### ISSUE TITLE
[FATAL] listen udp 10.1.200.10:53

### ISSUE THREAD

**Issue by ropucyka** [DNSCrypt/dnscrypt-proxy#1078]
`[FATAL] listen udp 10.1.200.10:53: bind: The requested address is not valid in its context.`

What a problem? Same with other port and\or address.

`listen_addresses = ['10.1.200.10:53', '[::1]:53']`

**Comment by welwood08** [comment]
This is a standard operating system error that means the IP address you're trying to use is not assigned to any of the network interfaces on the machine where the software is running.
