### ISSUE TITLE
Need Help "[FATAL] listen udp 127.0.0.1:53: bind: permission denied"

### ISSUE THREAD

**Issue by evilvibes** [DNSCrypt/dnscrypt-proxy#108]
I'm making the move from dnscrypt-osxclient on both my mac's i having the issue "[FATAL] listen udp 127.0.0.1:53: bind: permission denied".

I checked the port 53 and don't see anything running on it (I could be wrong).

MacOS 10.13.3

**Comment by jedisct1** [comment]
You need to start it as root. Try `sudo dnscrypt-proxy`.

**Comment by evilvibes** [comment]
Getting command not found. Sorry man i'm a little noobie on commands

**Comment by jedisct1** [comment]
This needs to be documented in the wiki :/

**Comment by evilvibes** [comment]
Yea maybe a little more detail in the Installation wiki would help us noobies until there is a client.

**Comment by jedisct1** [comment]
+1

**Comment by evilvibes** [comment]
ok i got it running now 

sudo /Users/(your user name)/(folder location)/(folder name)/dnscrypt-proxy start

Then (not sure if have to do it this way)

sudo /Users/(your user name)/(folder location)/(folder name)/dnscrypt-proxy -service install
&
sudo /Users/(your user name)/(folder location)/(folder name)/dnscrypt-proxy -service start
