### ISSUE TITLE
Req: Label decloaked dns as "uncloaked" in blocklist.log

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#1080]
This will aid block lists/detection of cname cloaked domains, by increasing user reporting and awareness of first party trackers.

**Comment by jedisct1** [comment]
When something is blocked, no matter why, the rule that triggered it is logged as well. This is the most useful information to check what list triggered the block. We don't need more status codes.

**Comment by rugabunda** [comment]
So you are saying in the blocked.log, tagging dns queries blocked via CNAME is already taking place? Great because this is tremendously useful and convenient.

**Comment by jedisct1** [comment]
Having new and moderately useful labels is tremendously painful when you parse these logs to get metrics about what has been blocked or not.

**Comment by rugabunda** [comment]
If it is optional then its not anti-innovation.

**Comment by jedisct1** [comment]
It's bloat. It's code that has to be maintained while I would never use it.

**Comment by jedisct1** [comment]
And something that would be logged differently according to some configuration option is the worse possible things for log parsers.

**Comment by rugabunda** [comment]
Like the CNAME blocking a I had originally brought up here, its going to become more necessary over time in order to detect CNAME cloaking, and the more convenient & aware we are, the quicker we will adapt. Most people are not skimming through hundreds of thousands of queries looking for entries, then comparing them one by one to another list that actually tells them, oh this was cloaked.

Parsers will have to improve instead of regress or stay stagnant, thats not a bad thing.

**Comment by jedisct1** [comment]
The information is already there, since the rule is logged as well as the name.

**Comment by rugabunda** [comment]
Ok so it is under query.log?

**Comment by jedisct1** [comment]
Yes.

**Comment by rugabunda** [comment]
Excellent! That is great, but please consider adding an option to tag cloaked dns in blocked.log, this will be marvelous for parsers as well.
