### ISSUE TITLE
Whitelist/blacklist weirdness with latest beta..broken interwebs

### ISSUE THREAD

**Issue by stylemessiah** [DNSCrypt/dnscrypt-proxy#1082]
Whenever a new release comes up, i simply overwrite the .exe and example toml file, which i then edit with the same values as the old, saving as the new toml file, so i dont miss out on any new options in in the new release.

Thats worked for eons, until this new beta....now its leaving my browsing largely broken, and its crazy cakes...

Consider that i have not changed a single line in either my whitelist or blacklist...and that ive simply cut&paste the relevant server, whitelist and blacklist lines in the new toml file...

When i try browsing to http://www.yourtv.com.au (a tv guide) it fails to load

When looking at my blocked.log it gives the blocking rule as:

`127.0.0.1	www.yourtv.com.au.edgekey.net	*.edgekey.net`

my blacklist has an entry for `edgekey.net`

but why is the domain `yourtv.com.au` having `.edgekey.net` added to it, all of a sudden?

theres no such domain....

This is one of many examples that have left my PC largely unable to browse.....

I can roll back to the previous install, previous .exe, with exactly the same whitelist, blacklist and config,, and everything works

wtf? :)

**Comment by jedisct1** [comment]
`www.yourtv.com.au` is an alias for `www.yourtv.com.au.edgekey.net`:

```sh
www.yourtv.com.au.	60	IN	CNAME	www.yourtv.com.au.edgekey.net.
www.yourtv.com.au.edgekey.net.	21600	IN	CNAME	e5589.dscg.akamaiedge.net.
e5589.dscg.akamaiedge.net.	20	IN	A	23.56.185.30
```

Blocking `edgekey.net` (Akamai) doesn't seem like a good idea, since this is a CDN; it is going to block half the internet.

**Comment by stylemessiah** [comment]
Did you miss the part where it worked just fine with the previous version? As it wasnt being blocked at all, and without ANY whitelisting for yourtv.com.au

Ive had edgekey blocked for over 2 years, and sites that i want to access whitelisted...again this hasnt been an issue, until this latest beta

Hardly seems liek a me issue :)

You may not agree with my choices on whitelisting and blacklisting, but they worked fine under squid for years and dnscrypt-proxy until this release....

**Comment by GrennKren** [comment]
how about by putting `edgekey.net` line inside whitelist file ?

**Comment by stylemessiah** [comment]
For the simple reason the changes made (CNAME Filtering) should be toggeable so i dont have to spend my time changing things that have always worked....ive alreayd spent too much time since the change trying ot work aroudn it, when the ssystem ive had has worked for like a decade at least, same whitelists, same blacklist sources. Ive done as asked and reported false positive domains to blacklists source authors, where possible (key phrase where possible) and other things asked by dev, and still getting ignored when asking for the ability to toggle the changes made. Ive done all i can, ive removed this software and stopped recommending it until he sees sense and makes it possible to toggle the setting off....whcih hopefully wont be long because im not the only person providing negative feedback on the matter. Its breaking way too many sites....i dont have the time to devote to fixing things on the rest of the internet, nor do i have the will to. Things worked until the latest release, for eons...and they worked even longer than that when i used the same setup (blacklsits and whitelists) for previous DNS servers and Squid....

When youve done as asked, and pointed out youre still having issues, you expect some positive feedback or at leats a reply form the dev, but no....

Tired of filing issue reports and having them summarily closed without discussion, or even a reply, by dev. Not the way to handle things.....
