### ISSUE TITLE
Whitelist/blacklist weirdness with latest beta..broken interwebs - try #3 (and final try, because you seem to be missing the point)

### ISSUE THREAD

**Issue by stylemessiah** [DNSCrypt/dnscrypt-proxy#1084]
So youve made things effecitvely harder to maintain, because up until now, ive never had to have an exception for the site ive been talking about, and tons of others, that have worked for about a decade using the same blacklists (cultivated from the most common blacklists on the internet)

So now i have to know the aliases of every site ive never had to? Thats madness....

How is that progress?

Heres the 1st vote for that change to be reverted in the next release....or at least able to be toggled off....

Till then im stranded on the older verison. and i suspect i wont tbe the only one...see my comment about using the most common blacklist sources on the internet....

Sorry, but this is madness...

**Comment by jedisct1** [comment]
Filtering CNAME pointers seems to be a welcome change, and it's well worth it since this seems to be the current way for trackers to work around content blockers. So, it isn't going to be reverted.

But if something looks like a false positive in a third party list, you can whitelist it, report it to the maintainer, or build your own list.

**Comment by stylemessiah** [comment]
This change fundametnally breaks established whitelsists ive used of years that are mainstream, meaning i would now have to whitelist a shitton of domains i have NEVER had to

This is insane

Please at least allow this "new behaviour" to be toggled off by the user

Otherwise i have to abandon using it, sadly

I need to use the internet, not spend my days whitelisting things endlessly....

**Comment by jedisct1** [comment]
This is your opportunity to be a hero and fix lists that have had false positives for years! Be a hero!

**Comment by stylemessiah** [comment]
Dude, take the valid issue report and allow it to be toggled off at least. I have a full time job, and im a volunteer, why are you now making it MY job to fix your issue or someone elses. Ive given you an issue report 3 times, its valid, ive proven it adversely affects browing ability. Enough with the glib one liners....

I do not have time when i finally get home after a long (often 12 hour) day to start whitelisting sites which ive never had to for years. My config was working perfectly up till i installed the new beta this evening....

**Comment by Samillion** [comment]
@jedisct1 @stylemessiah Would creating a specific list for CNAME blocking help prevent any possible issues like lists and maintaining them?

For example: `cname-blacklist.txt` would block on CNAME level, but `blacklist.txt` just a domain match block.

Just a suggestion.

**Comment by jedisct1** [comment]
That would make things more confusing. If you want to block `tracking-example.org`, you want to block it everywhere. And people would just end up using the same list twice.

**Comment by Samillion** [comment]
True. I haven't thought of that.

**Comment by stylemessiah** [comment]
I wouldnt mention something that was trivial, like i said i had been using the exact same blacklist and whitelist for years without issue...from squid days....my blacklist sources coming from recognised sources, in fact form the collection at https://firebog.net/ which is referenced and used about a millionty pihole users....

The edgekey.net entry tracked to the list provided by https://v.firebog.net/hosts/Kowabit.txt, which i have removed from my blacklist gathering and processing batch file for now. I removed their list as 1) it hasnt been update since October as they have moved to a new list (https://blocklist.kowabit.de/kwbtlist.txt), not listed on firebog (yet), and the edgekey entry is still present. I did send the maintainer a heads up on removing the edgekey.net entry from his list, but then i saw he had entries for other domains that were likely to break things too

But im just waiting for the next occurence that breaks half my browsing ability due to this change/blacklist maintainers oversight. I strongly beleive that one shouldnt have to troubleshoot an issue that wasnt there previously, and only appears because of a change in code that the user should have the ability to decide to use. Like i said last night, when i get home from a 12 hour shift installing multi level wifi system or fixing any number of IT issues, i dont want to sit down at my personal PC and have to troubleshoot stuff just to be able to visit my morning coffee sites.....

I dont want to be playing whackamole at 2am when i get in from a long day

Please make the CNAME filtering toggleable...

**Comment by stylemessiah** [comment]
For what its worth, here is my custom batch (and required files) that i created eons back (took many versions to get where it is now, and ive never shared it anywhere before) to create my blacklist and whitelist files. Doe squite a bit and gives a summary on completion of totals, additons and subtractions...

**In the bin folder:**

Necessary binary files (though some arent used, but im too lazy to rmeove them and well its always being tweaked) for creating the blacklist and whitelist files...most are gnu win32 files...one batch file **hashsum.bat** to verify md5 for shallalist as md5sum (gnu win32) can be unreliable at times with returning a correct errorlevel...

Some files depending on AV may return a suspicious result, but none are harmful and these are false positives.....

**In the static folder (user editable files):**

**ownblacklist.txt** - add own blacklists (blank in archive)
**ownwhitelist.txt** - add own whitelist (blank in archive)
**sources.txt** - add blacklist sources, one per line (only left 10 in for demo purposes, i have many many more entries - im blocking well over a million domains). Line 1 of source.txt is saved as 1.txt in **downloads** folder etc - makes it easy to trace issues in downloaded blacklists as they are available separately and not catted together upon download, that happens much later. Once downloaded the first time, each source is miantained in the **downloads** folder and only updated if it has changed since last script run (sames as with downloading of shallalist..only downloaded if md5 has changed) - this to save unnecessary downlaoding and data 

**Spits out (in the root folder where script is run):** 

**blacklist.txt** - blacklisted domains
**whitelist.txt** - whitelisted domains (ownwhitelits combined with common whitelisted domains form anudeep from pihole)
**ip-blacklist.txt** - blacklisted IP's

I have this script located in a dnscrypt-proxy folder on my d: drive, the dnscrypt-proxy.toml on my c: drive points its blacklist and whitelist and ip blacklist and logs files entries to it

**Download (direct dropbox link):**

[blacklist updater](https://www.dropbox.com/s/wm4s36x2dv5jla4/blacklistupdater.rar?dl=1)

**Comment by rhy-ama** [comment]
@Samillion @jedisct1 

What is the problem with having two sets of whitelist/blacklist rules: **query** based and CNAME **response** based? With query-based rules having priority?

CNAME would be more restrictive, but query-based lists would provide backward compatibility. Regarding one domains on both lists - not sure i understand the necessity of doing so nor eventual harm if any.

I like the project and what has been done. I really do. But the tendency to close new issues ahead of discussion, dismissive tone and overall reception of users is a foreign concept to me. It is not like users are captive or their needs could be ignored.

**Comment by Samillion** [comment]
While I definitely prefer the discussion route, there is always the one undeniable fact when it comes to it: This is an open source project, maintained and developed entirely on a volunteer basis.

I've been using dnscrypt-proxy for a long time now, and I have personally seen user suggestions being considered and implemented many times.

Sometimes a suggestion or a request can be overlooked just on the basis of effort and time. They genuinely put a lot of hard work into this project and I can understand that sometimes they wouldn't want it to overwhelm them and maybe take time to consider and think before they change or add something yet again.

Having said that, I have no doubt in my mind that if there were concerns or issues, they will be addressed, like they always have been.

A cliche line, but, have faith in this project. It's been great since it was created.

**Comment by rhy-ama** [comment]
@stylemessiah while Frank responds to the query-response filtering idea,

i recall that on windows ```%WINDIR%/System32/drivers/etc/hosts``` file could be used for blacklisting to 0.0.0.0. This is similar to blacklisting as per first instances of these blacklists.

I would suggest, as a workaround, 
1. Examine your current hosts file and save the copy you want to persist between blacklist updates as hosts.persist
2. Every time you build your blacklist, run a batch to recreate hosts file with a) copy of hosts.persists and b) for every line in your blacklist, copy that line in this format ```0.0.0.0 someblacklistdomain.com```

System dns resolver (and stub resolvers in chromium for instance) will respect hosts file before querying the dns server.

On unix systems, similar implementation could be done. With 127.0.0.1 or whatever DNSCrypt runs on being the last line. I personally find having query-response sets of rules for DNSCrypt aesthetically appealing.

**Comment by stylemessiah** [comment]
> 
> 
> @stylemessiah while Frank responds to the query-response filtering idea,
> 
> i recall that on windows `%WINDIR%/System32/drivers/etc/hosts` file could be used for blacklisting to 0.0.0.0. This is similar to blacklisting as per first instances of these blacklists.
> 
> I would suggest, as a workaround,
> 
>     1. Examine your current hosts file and save the copy you want to persist between blacklist updates as hosts.persist
> 
>     2. Every time you build your blacklist, run a batch to recreate hosts file with a) copy of hosts.persists and b) for every line in your blacklist, copy that line in this format `0.0.0.0 someblacklistdomain.com`
> 
> 
> System dns resolver (and stub resolvers in chromium for instance) will respect hosts file before querying the dns server.
> 
> On unix systems, similar implementation could be done. With 127.0.0.1 or whatever DNSCrypt runs on being the last line. I personally find having query-response sets of rules for DNSCrypt aesthetically appealing.

Sadly its not possible or efficient, given the size of my blacklist (29Mb currently), to use the hosts file...Windows simply doesnt handle hosts files that size well, it chokes, and even below the limit it introduces lag in system startup as the network stack loads. Its why previous to dnscrypt proxy i used (in order): squid and then Acrylic DNS Proxy...for their ability to load extensive blacklists that Windows couldnt handle.
