### ISSUE TITLE
Feature Request: Filtering CNAME - Allow User To Toggle Off

### ISSUE THREAD

**Issue by stylemessiah** [DNSCrypt/dnscrypt-proxy#1085]
Reason:

Blacklists used for years from recognised sources are now ineffective due this change, breaking browsing and requiring a TON of sites to be whitelisted that were never required to be previous to 2.0.34-beta.1

Why should a user have to whitelist hundreds of sites because of one change to code, that breaks how theyve used blacklists for years, that they cant toggle off?

Telling the user to submit the affected sites to the blacklist maintainers is NOT a valid reply, theres nothing wrong with the blacklists which again have been used for years..you must know full well theyre going to send a user back here because theres nothing wrong with their blacklist....

CName filtering needs to be a toggle-able choice for the user, simples

It breaks browsing currently ...users should have the choice of having their configuration work as it always has

This is disaapointing, having my issue closed 3 times with glib answers you know arent answers that resolve anything....

If you wont revert the code, at least allow the user to make the choice of whether you break their config or not......

This is bad user engagement.....when you purposely discount valid issue reporting (3 times, and counting)

**Comment by jedisct1** [comment]
If a filtering rule is too broad, you can always use whitelists to allow more specific names.

**Comment by jedisct1** [comment]
`edgekey.net` being in the list you are using is likely to be a false positive. It wasn't blocked by accident, because the software you were using only did partial blocking. Fixing FPs will be very useful for all the users of that list.
