### ISSUE TITLE
[REQUEST] Implement option to include new example config files in update script

### ISSUE THREAD

**Issue by jdrch** [DNSCrypt/dnscrypt-proxy#1087]
The official update script does not update the example config files. This makes new settings and options difficult for users to discover. 

Can we have an option to include new example config files in automated updates? I'm thinking something like `Update_Example_Configurations=yes` would work.

**Comment by slawa-dev** [comment]
The update script in question is this one:
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Updates#configuration

**Comment by jdrch** [comment]
@slawa-dev Yes, that's it. Requesting the option to update the example config files too be added to it.

**Comment by jedisct1** [comment]
This is not an official update script, just an example in a wiki page. 

I've never used that script, so feel free to improve it or anything on that page or elsewhere in the documentation. Having that script check for signatures would also be a nice addition.

**Comment by jdrch** [comment]
@jedisct1 I apologize for the confusion. I'm actually referring to the updater script that's included with releases. I mistakenly thought the one posted in the Wiki was the same thing.

**Comment by jedisct1** [comment]
I don't see any updater script here :)

What is the file name? I couldn't even find anything with `update` in the name.

**Comment by jdrch** [comment]
Ah. Dealing with multiple machines and OSes. Sorry! Closing this bug.
