### ISSUE TITLE
DNS cache

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1088]
Hiya
is there a way to set the cache settings in DNSCrypt to unlimited infinite? unlimited time and storage capacity
Would it be possible to have the DNS cache save to SSD / HDD for permanent storage for permanent enhanced performance and reduced latency?
cache_size =
cache_min_ttl =
cache_max_ttl =

**Comment by jedisct1** [comment]
75% of the DNS responses are valid for 5 minutes or less: https://blog.apnic.net/2019/11/12/stop-using-ridiculously-low-dns-ttls/

Even on a very busy resolver, there is zero gain in having a large cache. Bumping `cache_max_ttl` up is useless. `cache_size` can be set to how many different queries are processed in 1 hour. Going beyond that is not going to make a difference.

You can bump `cache_min_ttl` up, even though I wouldn't recommend going beyond a hour. If you do, adjust `cache_size` to how many queries you get during that time. Setting a bigger value is not going to do much besides wasting memory.
