### ISSUE TITLE
[Documentation] Should conflict with WireGuard be documented in the Wiki?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1089]
I ran into a weird edge case today randomly, which definitely *isn't* a dnscrypt issue. 

Basically, there is a weird issue (not sure if a bug or intended?) with the WireGuard client for Windows, where it adds a WFP firewall rules (even with 'block untunneled traffic' toggled off) that will block all UDP traffic on port 53 from applications besides WireGuard.

This makes dnscrypt fail when it has to use the fallback resolver that uses port 53, and if the public resolver cache is stale, ultimately results in it aborting and leaving the system without any DNS at all.

The best work around for this is to use a fallback resolver that uses a non-standard port, like `9.9.9.9:9953`.

That said, I was wondering if something about this edge-case should be added to the Wiki or example config file, to save people who have a similar setup to me some hassle. Or maybe it's too out of scope? I thought it might be best to ask for direction before proceeding.

Thanks for your time.

**Comment by jedisct1** [comment]
That looks like a bit too specific, and maybe that client has an option to avoid disabling that behavior.

And with current versions of `dnscrypt-proxy`, if the public resolver cache is stale, the previous version should keep being used.

**Comment by ghost** [comment]
>That looks like a bit too specific, and maybe that client has an option to avoid disabling that behavior.

Fair enough, figured it was at least worth asking. Also like I said, there is no apparent way to turn off the DNS blocking behavior in the WG Windows client as of yet. In any case if someone else also happens to encounter this problem they should be able to find this issue, with the solution. 😃 

> And with current versions of dnscrypt-proxy, if the public resolver cache is stale, the previous version should keep being used.

Honestly, I'm not really sure what triggered it for me. Considering my system has been working fine regardless of this apparent conflict for several months. But today after restarting the dnscrypt service, my DNS completely broke, and it took me a couple hours to figure out this was the cause.

Gonna go ahead and close this. Thanks for the quick response.
