### ISSUE TITLE
Dnscrypt-proxy service failed to run on Arch Linux.

### ISSUE THREAD

**Issue by fakhrisatu** [DNSCrypt/dnscrypt-proxy#109]
I installed the AUR package. Copied the sugested cofiguration. Started the service with `sudo systemctl start dnscrypt-proxy.service`. Failed. `systemctl status` gave me this:

`Feb 09 13:10:32 whitebase systemd[1]: Started DNSCrypt client proxy.`
`Feb 09 13:10:34 whitebase dnscrypt-proxy[778]: [2018-02-09 13:10:34] [WARNING] public-resolvers.md: open sf-2yywwi3veha23fh6.tmp: read-only file system`
`Feb 09 13:10:34 whitebase dnscrypt-proxy[778]: [2018-02-09 13:10:34] [WARNING] public-resolvers.md.minisig: open sf-mtr7ajurppczdwyz.tmp: read-only file system`
`Feb 09 13:10:34 whitebase dnscrypt-proxy[778]: [2018-02-09 13:10:34] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded`
`Feb 09 13:10:34 whitebase dnscrypt-proxy[778]: [2018-02-09 13:10:34] [NOTICE] dnscrypt-proxy 2.0.0`
`Feb 09 13:10:34 whitebase dnscrypt-proxy[778]: [2018-02-09 13:10:34] [FATAL] listen udp 127.0.0.1:53: bind: permission denied`
`Feb 09 13:10:34 whitebase systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a`
`Feb 09 13:10:34 whitebase systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.`

**Comment by jedisct1** [comment]
You should report this directly to the AUR package maintainer, as that person is unlikely to see your message here.

**Comment by ghost** [comment]
It's an issue with **DynamicUser=yes** under *[Service]* in **dnscrypt-proxy.service**

It's running it as a non-root user trying to read files with a root:root user/group.
