### ISSUE TITLE
Dead lag when trying to open site through VPN

### ISSUE THREAD

**Issue by AlexXanderGrib** [DNSCrypt/dnscrypt-proxy#1091]
I'm using Network Manager Open VPN Client on Ubuntu 18.04 and config looks like this
```INI
[connection]
id=VPN
uuid=0dce83ed-7464-4f17-a983-8f4b324ccf39
type=vpn
permissions=
timestamp=1575484067

[vpn]
ca=/home/USERNAME/.cert/nm-openvpn/VPN-ca.pem
cert=/home/USERNAME/.cert/nm-openvpn/VPN-cert.pem
cert-pass-flags=0
comp-lzo=adaptive
connection-type=password-tls
dev=tun
key=/home/USERNAME/.cert/nm-openvpn/VPN-key.pem
password-flags=0
remote=vpn-server:80:tcp
remote-cert-tls=server
ta=/home/USERNAME/.cert/nm-openvpn/VPN-tls-auth.pem
ta-dir=1
username=USERNAME
service-type=org.freedesktop.NetworkManager.openvpn

[vpn-secrets]
password=PASSWORD

[ipv4]
dns=127.0.2.1;
dns-search=
ignore-auto-dns=true
method=auto

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto
```

When I connected to VPN, and trying to open google.com, for the first time it's loads normal, and for second, and for N time because dns cache, but if I trying to open an other site, google chrome gives me an error 
![Снимок экрана от 2019-12-04 21-55-58](https://user-images.githubusercontent.com/29816814/70172055-fceb8400-16e0-11ea-8dde-a66faa61d278.png)

Yes, it is a problem of DNSCrypt, because when i connecting to VPN,  i also started resolving domain уфсб.рф (punycode xn--90a5afe.xn--p1ai) and it is a result
![Снимок экрана от 2019-12-04 21-58-04](https://user-images.githubusercontent.com/29816814/70172265-6075b180-16e1-11ea-9904-c1d9f1dd837d.png)
But without a VPN it gives me:
![Снимок экрана от 2019-12-04 21-58-04](https://user-images.githubusercontent.com/29816814/70172362-8d29c900-16e1-11ea-84a8-05a664492849.png)

After restart DNSCrypt `sudo service dnscrypt-proxy restart`, i will have a new chance to open a site (VPN connection still alive)

How to fix?

**Comment by arch-btw** [comment]
Similar:

https://github.com/DNSCrypt/dnscrypt-proxy/issues/832
https://github.com/DNSCrypt/dnscrypt-proxy/issues/825
https://github.com/DNSCrypt/dnscrypt-proxy/issues/1099

I have the same issue.

When dnscrypt-proxy is being used over time, it gets slower.

A manual refresh solves this:

> sudo service dnscrypt-proxy restart

Apparently this happens when combining dnscrypt-proxy with a VPN.

**Comment by ianbashford** [comment]
I also use dnscrypt-proxy over a VPN, and I don't notice any slowdown...  
Over how long a period do you see the slowdown?  I'll try to monitor and replicate...
