### ISSUE TITLE
Local DoH should allow TLS to be disabled

### ISSUE THREAD

**Issue by tycho** [DNSCrypt/dnscrypt-proxy#1092]
My goal is to have nginx reverse proxy to dnscrypt-proxy's local DoH server. For this purpose, having TLS in front of the local DoH server itself is really unnecessary: it's listening on localhost, and nginx can be responsible for handling the TLS termination for anything externally accessible. Having TLS in front of it also adds extra latency in the initial connection establishment.

It would be ideal if I had the option to use the local DoH server with no TLS encryption enabled. At the moment, this does not seem to be possible. Leaving `cert_file` and `cert_key_file` undefined results in a rather hard-to-debug fatal error in which dnscrypt-proxy tries to open the path "" (that is, an empty string) and then exits abnormally:

```
Dec 04 12:21:09 elbereth dnscrypt-proxy[785680]: Now listening to https://127.0.0.1:3000/dns-query [DoH]
Dec 04 12:21:09 elbereth dnscrypt-proxy[785680]: open : no such file or directory
Dec 04 12:21:09 elbereth systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 04 12:21:09 elbereth systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
Dec 04 12:21:50 elbereth systemd[1]: Started DNSCrypt-proxy client.
```

**Comment by jedisct1** [comment]
The local DoH feature was really only designed to be used locally, mainly to work around Firefox restrictions.

It only partially implements the protocol and is not secure or scalable enough to be exposed externally.

[rust-doh](https://GitHub.com/jedisct1/rust-doh) would be a way better choice for that use case.

**Comment by tycho** [comment]
rust-doh is actually what I've been using up until now, but there are issues that I'd been hoping to resolve by using dnscrypt-proxy's built-in DoH server.

One main problem is that DNS query logging in dnscrypt-proxy just shows all rust-doh-proxied requests as coming from 127.0.0.1. rust-doh itself has no query logging and has no way to inform dnscrypt-proxy of the real client IP. The only way (at the moment) to log rust-doh requests is on the nginx side, but that doesn't log the contents of POST requests, and even with GET the DoH requests are encoded in a special kind of base64 anyway. So I'd have to force my clients to use `network.trr.useGET = true` *and* do postprocessing on the nginx log file to figure out what request were made and by what clients.

On the other hand, if the dnscrypt-proxy local DoH feature understands the `X-Forwarded-For` header (does it? I haven't tested it thoroughly yet) then it could be logging the actual client IP as reported by nginx when it reverse-proxies. So the query would be logged in the same readable dnscrypt-proxy log format, but with accurate client IPs.

Plus I'd rather just have *one* daemon running rather than dnscrypt-proxy + rust-doh if I could.

**Comment by jedisct1** [comment]
Wait until buIltin support for DoH is merged into [eds](https://github.com/jedisct1/encrypted-dns-server).

dnscrypt-proxy local DoH doesn’t support GET, X-Forwarded-For, or caching headers. It’s also easy to DoS.

**Comment by jedisct1** [comment]
Actually it may support X-Forwarded-For. Need to check 😄

**Comment by tycho** [comment]
Hmm. I hadn't heard of EDS, and I'm not completely sure what it's doing. It looks like it's a DNSCrypt-to-DNS proxy rather than a DNS-to-DNSCrypt proxy? Because that doesn't seem like what I want exactly. None of my clients really speak DNSCrypt to begin with. I guess if it had built-in DoH support then it could replace rust-doh, though.

Frankly my DNS resolution setup for my network is messy and I'd like to simplify it. All my LAN hosts use either DoH or plain DNS to talk to my router box. The router box has this kind of setup:

* nginx reverse-proxies /dns-query to rust-doh
* rust-doh handles the nginx-proxied DoH requests and forwards them to dnsmasq
* dnsmasq responds to plain DNS requests on the LAN side, does caching/ad blocking/LAN hostname resolution, etc. anything not resolved or overridden locally gets forwarded to dnscrypt-proxy
* dnscrypt-proxy handles the upstream DNS resolution over DNSCrypt/DoH
* iptables is also configured to prohibit forwarding of DNS-related packets from LAN-to-WAN (including HTTPS to common public resolver IPs, to thwart DoH). This forces stubborn devices to use the LAN resolver even if they'd prefer to use something else. For example, the Google Chromecast preferentially uses `8.8.8.8` and `8.8.4.4` regardless of what DHCP told it to use, and it probably even tries to use Google's DoH these days (though I haven't checked that since DoH became a thing). The Chromecast does gracefully fall back to using the DHCP-provided resolver address(es) if its preferred resolvers break in some way.

So to log DNS queries, I guess what I'd need to have is logging in rust-doh itself (with comprehension for `X-Forwarded-For`) and logging from dnsmasq for any plain DNS queries from LAN hosts.

I guess there's not much that dnscrypt-proxy could do right now to make *this* less of a mess, though.
