### ISSUE TITLE
Update 2.0.34 also block no blacklisted websites!

### ISSUE THREAD

**Issue by gcpmusic** [DNSCrypt/dnscrypt-proxy#1094]
Hello Frank,
thank you for the update however, as mentioned in the title, the 2.0.34 update blocked a few no blacklisted websites. Meantime I downgraded to 2.0.33 which works fine however a solution would be appreciate for future update.
Thank you.

**Comment by jedisct1** [comment]
Hi,

If you haven't, you can enable the logfile for blacklists (name and ip blacklists).

The file will show what rules from your blacklists were matched.

**Comment by gcpmusic** [comment]
Yes I already have enable the log file for blacklists (name and ip blacklists) and I do have a long list of blocked domain. The problem is that some domain now are blocked and they are not blacklisted. However if I whitelist them will work and pass true but obviously this is no a viable solution. This new issue never happened in all previous version. Any thought about?
Thanks in advance.

**Comment by jedisct1** [comment]
Do you have an example of such a domain?

**Comment by gcpmusic** [comment]
This are some domain that was rejected in the log and I had to whitelisted to let pass true:
github.map.fastly.net
www.speedtest.net (from Speedtest app)
weather-ydn-yql.media.yahoo.com (from Meteorolist app)
la7.it

Please note that some domain is called from an app or menubar item such Meteorolist.
Thanks

**Comment by jedisct1** [comment]
`www.speedtest.net` is an alias for `zd.map.fastly.net`, so if you had `map.fastly.net` or `fastly.net` in your blacklist, it's expected to be blocked.

The current version in git logs the original query name; it may help you better understand when an alias is present in your blocklist.

**Comment by gcpmusic** [comment]
Thank you however all the above domains are not blacklisted and anyway why all previously version works fine, I didnt edit my blacklist, is still the some and when I switch back to 2.0.33 no issue.  What's about the other domains?

**Comment by jedisct1** [comment]
Previous versions didn't block some queries even though they were in the blacklist.

**Comment by gcpmusic** [comment]
I see.
Thank you.
