### ISSUE TITLE
Is there a way to query the server name of the current resolver?

### ISSUE THREAD

**Issue by rr0ss0rr** [DNSCrypt/dnscrypt-proxy#1095]
I looked in the log and only see the "[NOTICE] Server with the lowest initial latency record". (I changed to Log_Level 0) and didn't see any other mention in the log.  I guess I could pull the server name from here if lb_strategy="first", but if you're using p2, ph or random, it would be nice to know which resolver is being used.  Would it be possible to add the current resolver to the application log?  I'm looking for the name not the ip (ex. cs-usil, dnscrypt.ca-2). 

Thanks

**Comment by jedisct1** [comment]
It's visible in the query log, for every query.

**Comment by rr0ss0rr** [comment]
Ah .. Thanks
