### ISSUE TITLE
Windows doesn't resolve LAN hostnames with DNSCrypt enabled

### ISSUE THREAD

**Issue by ghiki** [DNSCrypt/dnscrypt-proxy#1096]
I came from there:
https://github.com/bitbeans/SimpleDnsCrypt/issues/466
But I think it's dnscrypt-proxy related issue, if I enable dnscrypt service, then I cant resollve some of my LAN hostnames (I can't enter in Windows "network" tab and click in any LAN computher without receiving a "Windows can't connect to \\MYLANCOMPUTER")
![explorer_HK1VFWxyQH](https://user-images.githubusercontent.com/854302/70004431-89be0280-1566-11ea-918a-815f0e0cc00a.png)

After that, I configured forwards (these are at this moment):
10.in-addr.arpa      192.168.1.1
168.192.in-addr.arpa     192.168.1.1
192.in-addr.arpa     192.168.1.1
254.169.in-addr.arpa 192.168.1.1
lan                  192.168.1.1
local                192.168.1.1

But anyway, same happens, or worse, since now with service enabled, my lan NAS doesn't appear in the explorer (QNAP TS-212P)

I used Simple DNSCrypt as GUI for Windows:
![rK8Z4t5rCy](https://user-images.githubusercontent.com/854302/70343365-64c3db00-1857-11ea-96d0-49078db51535.gif)

It's W10 build 1809

**Comment by jedisct1** [comment]
What your computer is trying to resolve these hostnames, what exact hostnames do you see in the query log?

**Comment by ghiki** [comment]
Theorically it should pass the DNS query to my network operator's router (what's in 192.168.1.1)
These are the queries in "query.log"
![notepad++_L90jTautp5](https://user-images.githubusercontent.com/854302/70344476-1fed7380-185a-11ea-818f-8b7e9bb09042.png)
And device that I'm trying to access, is "NAS16768.lan", that should be accessible as share with "\\\NAS16768C" as SMB share, butit doesn't work while dnscrypt-proxy enabled

**Comment by jedisct1** [comment]
This is difficult to read, but looks like there are `AAAA` (IPv6) queries here, so if IPv6 was blocked (I don't know how the option is called in Simple DNSCrypt), maybe don't block it.

**Comment by ghiki** [comment]
> 
> 
> This is difficult to read, but looks like there are `AAAA` (IPv6) queries here, so if IPv6 was blocked (I don't know how the option is called in Simple DNSCrypt), maybe don't block it.

You're right, IPv6 is blocked, I thought that blocking IPv6 would be resolved through IPv4
![notepad++_TxXlr6x7OU](https://user-images.githubusercontent.com/854302/70346905-a5bfed80-185f-11ea-95a8-298c22ff171c.png)

Thanks!!! I changed to "false" and now It's working
