### ISSUE TITLE
logged_qtypes - Help Wanted

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#11]
**First of all, good news for **beta 4**:**

• "Chicken-and-egg problem" is gone
• dnscrypt-resolvers.csv.minisig created automatically
• Fast service installation
• dnscrypt-proxy.log (or mine Connections.log) with `log_level = 1` healthy and nice
   (To all: Don't keep this file on the disk for your safety. This one only for troubleshooting)

**Problem:**

I can't test `logged_qtypes` deeper, because it works by "exception principle": if I'll turn it on and miss some type of the record, I'll never see this set of domain names in my log.

I mean, everybody must to know **all possible record types** to have possibility of their control.
`'AAAA', 'A', 'MX', 'NS', 'TLSA', 'DNSKEY'`, ... how about anorher ones???
And, of course, clear description for the each one.

**Better way is change the logic:**

We will write here all the records we want to exclude:

`unlogged_qtypes = ['DNSKEY']`

This is more clear and safe way. Yeah? :)
(If I see unwanted record type - I exclude it)

-------------------
P.S. Ideally, I want such option for the blocklist RULES: `*my.blocking.rule*` to exclude all corresponding  inputs from the main DNS.log
May be some time, in the future...

**Comment by jedisct1** [comment]
No features request for now.
