### ISSUE TITLE
[suggestion] add -testall to check latecy to each and every server available

### ISSUE THREAD

**Issue by elmakong** [DNSCrypt/dnscrypt-proxy#110]
it would be great if you add the feature to test the latency of the servers available/listed in the .md file so we can choose the best server from our region

**Comment by jedisct1** [comment]
You will see these if you set the log level to `2`.

**Comment by elmakong** [comment]
isn't the default log level is 2 already?
i ask for this feature because currently if i commented out the server names, it only replied with timeouts

**Comment by jedisct1** [comment]
If you get a timeout, the server is not reachable. Maybe due to firewall rules.

**Comment by elmakong** [comment]
or maybe because some other things...because, when i add the stamp to static list, it worked just fine

**Comment by jedisct1** [comment]
Unfortunately, I was not able to reproduce this or to find a rationale for this.

**Comment by elmakong** [comment]
possibly because i am currently running tor downloads that hog almost all my bandwidth allocation..
also, when i try to open censored web page, sometimes the dns request is redirected to my isp's dns.

**Comment by jedisct1** [comment]
Also, if you are using `force_tcp`: many servers still run older versions of the software that don't support sending certificates over TCP. So you get a `TIMEOUT`.

**Comment by elmakong** [comment]
i am not using the `force_tcp` flag.

**Comment by jedisct1** [comment]
Sadly I think this is really something specific to your setup, and your network congestion due to your Tor downloads may very well be causing this.

Your ISP may be redirecting traffic based on IP addresses in addition to DNS. In that case, dnscrypt-proxy cannot really help, only a VPN can.

**Comment by elmakong** [comment]
the only one that i cant use vpn and dnscrypt is my campus..dont know how they really set the network up(via biznet, indonesian ISP).
my home setup can work unless there are tor downloads..sometimes using ISP's dns server(telkom, indihome, also indonesian ofc)
