### ISSUE TITLE
Golang CA certificates bundle

### ISSUE THREAD

**Issue by jla3378** [DNSCrypt/dnscrypt-proxy#1103]
I'm trying to use the latest binary version (2.0.34/Linux/ARMv7) but it fails to download the server list as with the following error.

`[CRITICAL] Unable to retrieve source [public-resolvers]: [Get https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md: x509: certificate signed by unknown authority]`

Looking at a previous issue about this topic, it mentions ca-certificates needs to be installed but I am trying to get it to run on an embedded Linux system that does not have a package manager. Where can I get the bundle of certificates and in what directory do I manually have to place them in?

**Comment by welwood08** [comment]
You can grab the same set of CA certificates as used in Firefox from [curl](https://curl.haxx.se/docs/caextract.html), although I'm sure there are others if you have different preferences or trust levels.

The filesystem locations where Go looks for this bundle can be seen [in the source code](https://golang.org/src/crypto/x509/root_linux.go).
