### ISSUE TITLE
2.0.34 whitelist issue

### ISSUE THREAD

**Issue by john-2020-tech** [DNSCrypt/dnscrypt-proxy#1104]
Just updated to 2.0.34 and noticed the following issue:

Scenario (1):
- If the blacklist blocks `*.cloud`
- AND
- If the whitelist allows `globalsign.cloud` AND `ocsp.globalsign.cloud`

Then the web address `ocsp.globalsign.cloud` will still be blocked, even though it's already in the whitelist.

Scenario (2):

- If the blacklist blocks `youtube*.*` (to filter YouTube-related phishing sites)
- AND
- If the whitelist allows `youtube-ui.l.google.com` (a legitimate URL)

Then the web address `youtube-ui.l.google.com` will still be blocked, even though it's already in the whitelist.

<br>

**This has only happened after updating to 2.0.34. Perhaps it is related to the latest change:**

> **Blacklisted names are now also blocked if they appear in CNAME pointers.**

<br>

**Comment by jedisct1** [comment]
Hi John,

Unfortunately, I was not able to reproduce any of these.

Is the whitelist you are referring to the file in the `[whilelist]` section of the `dnscrypt-proxy.toml` file?

**Comment by Ainatar** [comment]
Hi,

im having the same issues that @john-2020-tech mentioned.

One example:
- Add to the blacklist the following: *.trafficmanager.net
- Try to open the next website: https://web.skype.com/
- The website will fail to load with a dns error (ERR_NAME_NOT_RESOLVED)
- Go check the blacklist log, and you will find that the next domains are blocked:
[2019-12-09 20:13:07]	127.0.0.1	wd-prod-ss.trafficmanager.net	*.trafficmanager.net
[2019-12-09 20:13:09]	127.0.0.1	a-0001.a-afdentry.net.trafficmanager.net	*.trafficmanager.net
[2019-12-09 20:13:12]	127.0.0.1	webclientshellserver-prod.trafficmanager.net	*.trafficmanager.net
- Add that 3 domains to the whitelist. Restart dnscrypt-proxy, or stop/start.
- Try again to open the website: https://web.skype.com/
- Still fails to load. Same dns error.
- Check again the blacklist log, the same 3 domains are still blocked.
- The whitelist log is empty. Nothing happened.

This is just an example, it happens with more websites/services.

Its like the whitelist is ignored, or the blacklist has higher priority, or other kind of error related to CNAME, dont know.

With the previous release (2.0.33) https://web.skype.com/ loaded perfectly having *.trafficmanager.net blocked in the blacklist.

Any ideas? Thanks in advance.

**Comment by jedisct1** [comment]
@Ainatar If you want to whitelist `web.skype.com`, you need to whitelist `web.skype.com` or `skype.com`.

Whitelisting doesn't apply to aliases.

**Comment by jedisct1** [comment]
`trafficmanager.net` is Microsoft Azure. Why are you blocking all websites hosted by Microsoft's cloud platform?

**Comment by Ainatar** [comment]
> 
> 
> `trafficmanager.net` is Microsoft Azure. Why are you blocking all websites hosted by Microsoft's cloud platform?

I have it blocked as part of the windows spy domains from @crazy-max list. You can find it here:
https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/dnscrypt/spy.txt

Never had a problem with that until 2.0.34 version of dnscrypt-proxy.

Edit: adding web.skype.com to the whitelist works. Now i have a question. Does this means that on the web.skype.com domain none of the blacklist domains will be blocked?

**Comment by jedisct1** [comment]
That list probably has names that have been included by error, but had never matched anything when used with `hosts` files. These don't know how to block aliases (`hosts` files predate the invention of DNS). Maybe something to report to that list's maintainer.

**Comment by jedisct1** [comment]
`web.skype.com` and `*.web.skype.com` will not be blocked, everything else will still be blocked.

**Comment by crazy-max** [comment]
I will take a look on this, thanks for the hint.

**Comment by Ainatar** [comment]
Thanks for everything.
