### ISSUE TITLE
Question on Forwarding-rules

### ISSUE THREAD

**Issue by rr0ss0rr** [DNSCrypt/dnscrypt-proxy#1105]
I have the following entry in my "query" log which is my local VPN ip.  Should this be forwarded to my router? or the VPN endpoint ip? or don't do anything, nothing to worry about?

message:145.0.29.10.in-addr.arpa  return:NXDOMAIN  server:cs-ca

Thanks

**Comment by jedisct1** [comment]
You can ignore it.
