### ISSUE TITLE
tls cipher suite

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1106]
Hiya

I was wondering if it would be possible to get support for TLS_AES_256_GCM_SHA384
sha384 seems like the highest quality available for tls 1.3?
https://wiki.openssl.org/index.php/TLS1.3#Ciphersuites
https://en.wikipedia.org/wiki/SHA-3
https://en.wikipedia.org/wiki/SHA-3#Security_against_quantum_attacks
I couldn't find out what version of sha tls 1.3 uses so i referenced sha3 2015 instead of sha2 2012 since they are both very old

I searched most of the other cipher suites in the example-dnscrypt-proxy.toml and most were discontinued and or unsupported only one option in the example-dnscrypt-proxy.toml seems to support tls 1.3 TLS_CHACHA20_POLY1305_SHA256

**Comment by jedisct1** [comment]
SHA384 is just SHA2 with 384-bit output. The algorithm was published in 2001, 19 years ago.

But SHA2 is still totally fine today, and remains the only option supported by TLS certificates (actually, there are other options, but even older and broken). No one is using SHA3, because it's too slow in software.

`dnscrypt-proxy` supports `TLS_AES_256_GCM_SHA384` if the server you are connecting to supports it. Most don't and only support AES128, which is totally fine.

You can leave the `tls_cipher_suite` option commented; `dnscrypt-proxy` will simply use whatever the server supports. All cipher suites from TLS 1.2 and 1.3 are supported (and yes, all the primitives used in TLS are very old, but 1. they're still ok 2. there's no choice).

**Comment by ghost** [comment]
Hiya
What number do i select to activate TLS_AES_256_GCM_SHA384 in the dnscrypt-proxy.toml?
I currently have tls_cipher_suite = [4867]
and it works on every web site I have tried

I just tried 
tls_cipher_suite = [TLS_AES_256_GCM_SHA384]
and when i tried to start the service got an error windows could not start the dnscrypt client proxy service on local computer. error 1067: the process terminated unexpectedly

**Comment by welwood08** [comment]
As already mentioned, if you leave the setting commented then all cipher suites will be activated (including the one you want) and the server will select the best you both support.

If you really want specific suites, you can see what Go supports [in the source code (right at the bottom)](https://golang.org/src/crypto/tls/cipher_suites.go). There you can see that TLS_AES_256_GCM_SHA384 has a hexadecimal suite ID of 0x1312, which you can convert to decimal 4866 for use in dnscrypt-proxy.toml.

**Comment by ghost** [comment]
Thank you

I put in
tls_cipher_suite = [4866]
and rebooted pc and it works with all web sites like 4867 did

I also found this online calculator though not sure how to use them all yet
https://coolconversion.com/math/binary-octal-hexa-decimal/_hexadecimal__1302__hexadecimal_+%E2%80%94+Decimal+to+Hexadecimal+Calculator+

// TLS 1.3 cipher suites.
TLS_AES_128_GCM_SHA256       uint16 = 0x1301  code 4865
TLS_AES_256_GCM_SHA384       uint16 = 0x1302  code 4866
TLS_CHACHA20_POLY1305_SHA256 uint16 = 0x1303  code 4867

I just wanted to enforce the proper security level then let servers set some randomized configuration or the server select lowest for performance sake like sha3 controversy
https://en.wikipedia.org/wiki/SHA-3#Capacity_change_controversy
probably why everything still use sha2 maybe lol

I like windows for automation but not that much automation

**Comment by jedisct1** [comment]
Don't do anything, the most secure option supported by the server will automatically be selected.

Also, don't be so focused on the hash function; it's only used to verify the certificate, not to encrypt your data.

If you really want to only use modern cryptography, disable DoH and use only DNSCrypt instead (it's Ed25519 and XChaCha20-Poly1305).

**Comment by jedisct1** [comment]
There's no practical difference between `TLS_AES_128_GCM_SHA256` and `TLS_AES_256_GCM_SHA384` except that the later is slower.

If post-quantum resistance is what you are worried about, a post-quantum key exchange should be used as well. But TLS doesn't support any yet (besides some early experiments). And this is fine.
