### ISSUE TITLE
How to check correct functioning of forwarding-rules.txt?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1109]
How can I verify that requests are being forwarded correctly?  I can't produce a configuration where `dnscrypt-proxy` forwards DNS requests properly.

I'm fairly certain that this is PEBCAK and not a bug, but I'm unable to see what I'm doing wrong and not knowledgeable enough to debug my configuration.  I've read the full threads of #898, #1027, #1105, #816, and #518.  Most appear to get closed with no clear answer on the resolution.   

## Description

The relevant line in `dnscrypt-proxy.toml`:

```
➜  ~ grep forwarding_rules /etc/dnscrypt-proxy/dnscrypt-proxy.toml
forwarding_rules = '/etc/dnscrypt-proxy/forwarding-rules.txt'
```

The non-empty, non-comment parts of the `forwarding-rules.txt` file:

```
➜  ~ grep '^[^# ]' /etc/dnscrypt-proxy/forwarding-rules.txt
lan              192.168.0.1
local            192.168.0.1
home             192.168.0.1
192.in-addr.arpa 192.168.0.1
```

Lookups **do** work on the upstream router:

```
➜  ~ nslookup media.home 192.168.0.1
Server:         192.168.0.1
Address:        192.168.0.1#53

Non-authoritative answer:
Name:   media.home
Address: 192.168.0.2
```

Lookups **do not** work in `dnscrypt-proxy`:

```
➜  ~ nslookup media.home 127.0.0.1
;; Warning: Message parser reports malformed message packet.
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
.       optional =
```

However, #518 led me to this:

```
➜  ~ dig media.home @127.0.0.1
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.14.8 <<>> media.home @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27532
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;media.home.                    IN      A

;; ANSWER SECTION:
.                       0       CLASS4048 OPT   10 8 QRrlpF5ZzWI=

;; ADDITIONAL SECTION:
media.home.             1576003506 IN   A       192.168.0.2

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Dec 10 19:45:01 CST 2019
;; MSG SIZE  rcvd: 77
```

So that works... sort of?  Even so, after that:

```
➜  ~ ping media.home
/usr/bin/ping: media.home: Name or service not known
```

Same with SSH, web browsers, etc.  What are the implications that `dig` works, but `nslookup` and all other programs do not? What's the significance of the malformed message parsing and the recursion unavailability warnings?  What am I doing wrong?

**Comment by pujianto** [comment]
Same here. I am trying to add a forwarding rule `php               127.0.0.1`. But when I test it with `dig test.php`, it gave me a timeout error. Also I discover `[2019-12-26 19:29:28] [WARNING] Too many incoming connections (max=250)` in error log.

**Comment by jedisct1** [comment]
@pujianto You are telling the proxy to ask `127.0.0.1` to resolve `*.php`. `127.0.0.1` is the proxy itself so you just created an infinite loop. Cloaking may be what you are looking for, not forwarding.

**Comment by pujianto** [comment]
@jedisct1 Oops, my bad. I'm sorry for the silly mistake.
Moved those rules to cloaking-rules.txt, and it works like a charm. Thanks.
