### ISSUE TITLE
SSL_ERROR_MISSING_ESNI_EXTENSION

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#1110]
since I activated the local doh server, 
for the Firefox exni crypt I get on some sites I think hosted on cloudflare 
the following error on Firefox: 
SSL_ERROR_MISSING_ESNI_EXTENSION

![Immagine](https://user-images.githubusercontent.com/35575744/70659209-e6ed3e80-1c5f-11ea-9a01-854d0ce76bf5.png)

what could it be due to?
can it be antivirus nod32 eset?

**Comment by jedisct1** [comment]
Google has a few hits for "SSL_ERROR_MISSING_ESNI_EXTENSION" such as

https://community.cloudflare.com/t/firefox-68-0-esni-encrypted-sni-error/99108
https://www.reddit.com/r/firefox/comments/ca2398/esni_dont_work_for_me/
https://mangadex.org/thread/155975/

and probably the most relevant thread to watch:
https://bugzilla.mozilla.org/show_bug.cgi?id=1566175

It may be a bug in Firefox, or it can be on Cloudflare's side.

If your antivirus is doing TLS interception, it may not help, but ESNI is clearly not ready yet.

**Comment by tigernero79** [comment]
@jedisct1 

solved, the problem was ESET NOD32 antivirus that intercepted TLS calls. 
 as in the photo. 
 deactivated has started to work.  thanks.

![IMG_20191211_234228_313](https://user-images.githubusercontent.com/35575744/70666886-e9579480-1c6f-11ea-85be-965b7805f6dd.jpg)

**Comment by tigernero79** [comment]
@jedisct1 

I found this discussion that explains very well error that I also have when I enable encrypted esni, 

I thought I had solved with antivirus but it is not so, 

according to them it concerns the rotation of the sni keys, 

every tot do not know what you say? 

below discussion link, they say to increase the TLL time


https://bugzilla.mozilla.org/show_bug.cgi?id=1566175

**Comment by jedisct1** [comment]
![Screen Shot 2019-12-18 at 19 44 47](https://user-images.githubusercontent.com/124872/71113997-1d323d00-21cf-11ea-86cc-f3ca2e12c819.png)
