### ISSUE TITLE
[ISSUE] WhiteList rules don't work for CNAMES ?

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#1111]
Hello.

First of all I want to THANK YOU the new CNAME feature and cool logging ability of the original query name along with the pointer. These two gave a lot more power to the dnscrypt-proxy today:

- Uncompromised strength in blocking
- Good look into the network interconnection processes and 3-rd party queries (previously ignored from the blocking and hidden from the eyes).
- Ability to make a new blocking rules more precisely and to have a good point for troubleshooting existing rules.

-------------

Due to reorganizing my rules in according with these new possibilities I'm starting expect an issues within **partially working WhiteList.** The example should be a best explanation, as well.

**1)** Lets say I have in the BlockList:
```

################################################
#             BlackListed-Domains              #
################################################

##########   NO OTHER/SPOOFING DNS !   #########

## This will block all subdomains like:
## *dns.google.* ................. Google DNS
## *mdns.* ....................... Zeroconf (APIPA)
## all similar unauthorized 3-rd party DNS requests

*dns.*
*-dns*
*ddns.*
*dnset.*

################################################
```

**2)** Lets say, I want to access the website: https://answers.microsoft.com/

The query will be blocked, because Microsoft uses Akamai CDN and CNAMES (edgekey, akadns, akamaiedge, edge, edgesuite, msedge, etc.):

**query.log**
`127.0.0.1	www.microsoft.com	A	REJECT	47ms	scaleway-fr`

**blocked.log**
`127.0.0.1	www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net	*dns.* (alias for [www.microsoft.com])`

So, we have `*dns.*` concurrent restriction for the long CDN address `...akadns.net`

**3)** Lets try to add `*.akadns.net` into the WhiteList:
```

################################################
#             WhiteListed-Domains              #
################################################

######	DNS : False-Positive								| Rule: *dns.*

###  DNS.WATCH (Germany)
###  https://dns.watch/			
*.dns.watch

###  Akamai CDN (Almost all BIG-BROTHER corps)
*.akadns.net

################################################
```

### ISSUE (WhiteList) EXAMPLE:

a) `*.akadns.net` exception doesn't work for the website that does not load properly, e.g.: https://answers.microsoft.com/
b) `*.akadns.net` exception doesn't appear in the WhiteList log.

Nevertheless `*.dns.watch` exception works for the https://dns.watch/ and appears in the WhiteList log.

For now (I can see) the one difference for this two: MS using CNAMES (WhiteList: **failed**), but DNS.WATCH isn't (WhiteList: **OK**) ...

**Comment by iWARR** [comment]
And another one.

Recheck, please, doubleqouotes `" "` in the:
- `[local_doh]` new section
- `# query_meta =` values...

Everywhere should be a single as usual? `' '`

**Comment by jedisct1** [comment]
This is [documented](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters#a-note-on-whitelists). Whitelists apply to the original name, not to aliases.

You need to whitelist the real name.

**Comment by iWARR** [comment]
I'm afraid this way selective blocking will become much harder and less flexible...
On the other hand, the good side of these is a fact that dnscrypt-proxy blocking will do more agressively and will not skip important (and hidden) things...

It will be a big pain to reorganize everything... THOR's hammer intead of rapier... Ok..

**Comment by jedisct1** [comment]
The problem with whitelists that would be applied to aliases is that, in addition to making things slower, it also introduces a trivial vulnerability.

Assuming that your blacklist looks like this (taking your `*dns*` example):

```text
*dns*
*porn*
```

And, because the `*dns*` rule prevents you from accessing your own router, you may have such a whitelist entry:

```text
dyndns.org
```

Unfortunately, now, any porn website can bypass the `*porn*` filter without changing their name. Just by using an alias such as `prn.dyndns.org`. Same IP, same name, no visible changes, but your blacklist was seamlessly bypassed. Of course, the same technique could be used by trackers, malware, etc. And as other filters start implementing `CNAME` filtering, it's not far fetched to think that this is a technique they may use.

**Comment by iWARR** [comment]
But if you have good attention to things and can "feel" corps phylosophy making a "smart" (wildcard / selective) rules, this is (for years) a very effective method. I had such small and effective rules that covered / replaced hundreds or even thousands of "usual" primitive hosts inputs.

Including these my DNS rules. As example, they prevent DNS redirects inside the any browser (built-in), or any OS - Windows and Android (same rules used), from MS, Adobe and many other redirects, including many of FUTURE hosts that will/was built with the same scheme.

Hosts / Aliases of the big corps are known and they change not so often. "Smart" rules may cover them and not existent yet also (if you have good understanding the way they do). This helps prevent leaking a LOT.

Of course blocking CDNs or frequently changing cloud, mirrors aliases it's another story. But my rules give me a lot of contol for installed software and their calling a home.

Thats why it is so much important and this is the difference with "just a WEB". I cover SOFT and WEB tasks at one time. And thank you again for this exellent instrument.

**Comment by curiosity-seeker** [comment]
> This is [documented](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters#a-note-on-whitelists). Whitelists apply to the original name, not to aliases.
> 
> You need to whitelist the real name.

Frank, please forgive my ignorance but I think the wording in the wiki is a bit confusing for someone as naive as I am. It says:

> Note that starting with version 2.0.34, name-based filters are applied both to the original query name itself, and to aliases (CNAME pointers).

> For example www.nytimes.com doesn't have an IP address. This is actually an alias for nytimes.map.fastly.net. Blocking fastly.net would block *.fastly.net, as well as all aliases pointing to it (in that case example, www.nytimes.com).

> ...

> To avoid foot-shooting, whitelists are only applied to the query name, not to all the aliases it may resolve to.

Now if I compare that with the [wording in the Wikipedia article](https://en.wikipedia.org/wiki/CNAME_record#Possible_confusion) my interpretation is that what you call "original query name" or "real name" is the CNAME - correct? For a layman it rather seems that "query name" or "real name" applies to the alias. Since a correct understanding is important for making the correct entries in the whitelist.log I wonder if the wording in the wiki can be adjusted accordingly or a bit more detailed.

What do you think?

**Comment by jedisct1** [comment]
"original query name" is the query that was sent by your browser (or whatever client).

"alias" is when the DNS resolver said "oh, you want the IP of <original query name>? It doesn't have any, it's actually an alias for <alias>". And the actual IP the client is going to connect to is the one of the alias.

Feel free to improve the wiki!

**Comment by curiosity-seeker** [comment]
> Feel free to improve the wiki!

I would love to do that (I had made a contribution to the wiki before). But in this case I don't feel competent enough as I still don't understand all details.
