### ISSUE TITLE
I found a problem

### ISSUE THREAD

**Issue by liang-hiwin** [DNSCrypt/dnscrypt-proxy#1113]
Use this command to see that the resolution has taken effect "./dnscrypt-proxy -resolve google.com", but use this command dig resolution fails "dig google.com @ 127.0.0.1 -p 5360"

`root@debian:/opt/dnscrypt-proxy# ./dnscrypt-proxy -resolve google.com
Resolving [google.com]

Domain exists:  yes, 4 name servers found
Canonical name: google.com.
IP addresses:   172.217.194.139, 2404:6800:4012:1::200e
TXT records:    globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8= docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e facebook-domain-verification=22rm551cu4k0ab0bxsw536tlds4h95 v=spf1 include:_spf.google.com ~all docusign=1b0a6754-49b1-4db5-8540-d2c12664b289
Resolver IP:    58.217.249.155

root@debian:/opt/dnscrypt-proxy# dig google.com @127.0.0.1 -p 5360

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> google.com @127.0.0.1 -p 5360
;; global options: +cmd
;; connection timed out; no servers could be reached
root@debian:/opt/dnscrypt-proxy#
`

Configuration file listening address

`## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.
## listen_addresses = ['127.0.0.1:53', '[::1]:53']

listen_addresses = ['127.0.0.1:5360']

## Maximum number of simultaneous client connections to accept

max_clients = 250`

**Comment by jedisct1** [comment]
The `dnscrypt-proxy -resolve` command resolves a name the same way your applications will. So, it uses the HOSTS files, OS-specific mechanisms and the configured system resolver. Which probably isn’t using a port different from port 53.
