### ISSUE TITLE
The python script generate-domains-blacklist.py will generate a 0 byte dnscrypt-blacklist-domains.txt if there is no internet connection

### ISSUE THREAD

**Issue by MR-Diamond** [DNSCrypt/dnscrypt-proxy#1115]
I have a cron job that every two day will run `python generate-domains-blacklist.py > dnscrypt-blacklist-domains.txt`, and works like a charm, except when there is no internet connection: in this case the python script `generate-domains-blacklist.py`, instead of stop the job, will generate a 0 byte file (`dnscrypt-blacklist-domains.txt`); the failure is silent and the system is privated of the ad blocking until the user doesn't check `dnscrypt-blacklist-domains.txt`. and re-run the action with a connection available.
If there is no available connection, the script should at least leave `dnscrypt-blacklist-domains.txt` untouched at the previous state . I also tried by passing the -i argument but doesn't help.

**Comment by welwood08** [comment]
Unfortunately, the part that creates the empty file is the `>` in the command line, not the script itself.

I'd suggest either change your cron command to write a temporary file and then check if it's empty before overwriting the actual blacklist, or maybe change the Python script to take the destination filename as an argument instead of printing to stdout.

**Comment by rr0ss0rr** [comment]
I've seen this issue but not sure it's solely related to a network issue.  I also run a script that checks the size and if it's 0 then regenerate the list.  It usually works the second time.  Here's a snippet from my bash script.

size=$(wc -c </usr/local/etc/dnscrypt/domains-blacklist.txt)

if [[ "$size" -eq 0 ]]; then
   generate-list

If you want or need, I'll upload my entire update script.

**Comment by MR-Diamond** [comment]
> If you want or need, I'll upload my entire update script.

Would be useful.

**Comment by rr0ss0rr** [comment]
`
#!/usr/bin/env bash

function generate-list() {
   prt-success "Downloading domains-black/Whitelist.txt"
      pushd ~/bin/dnscrypt-proxy-utils &>/dev/null
      ./generate-domains-blacklist.py 2>~/tmp/generate-domains-blacklist-error | tee /usr/local/etc/dnscrypt/domains-blacklist.txt /Users/richard/Library/Mobile\ Documents/com~apple~CloudDocs/Downloads/domains-blacklist.txt &>/dev/null
      popd &>/dev/null

   #----------------------------------------------------------------------------------------------------
   # Download the current blacklist
   #----------------------------------------------------------------------------------------------------
   #curl -s https://download.dnscrypt.info/blacklists/domains/mybase.txt | tee /usr/local/etc/dnscrypt/domains-blacklist.txt /Users/richard/Library/Mobile\ Documents/com~apple~CloudDocs/Downloads/domains-blacklist.txt &>/dev/null

   #----------------------------------------------------------------------------------------------------
   # Download the current whitelist of bittorrent trackers
   #----------------------------------------------------------------------------------------------------
   echo "thepiratebay.org" >/usr/local/etc/dnscrypt/domains-whitelist.txt
   echo "*.local" >>/usr/local/etc/dnscrypt/domains-whitelist.txt
   curl -s https://torrents.io/tracker-list/?download=latest | awk -F/ '{print $3}' | awk -F: '{print $1}' >>/usr/local/etc/dnscrypt/domains-whitelist.txt

   #----------------------------------------------------------------------------------------------------
   # Check download and restart dnscrypt
   #----------------------------------------------------------------------------------------------------
   size=$(wc -c </usr/local/etc/dnscrypt/domains-blacklist.txt)
   if [[ $size -gt 0 ]]; then
      >/usr/local/log/dnscrypt/domains-blocked.log
      ~/bin/dnscrypt --restart
   else
      echo "domains-blacklist.txt has no entries"
   fi
}

#----------------------------------------------------------------------------------------------------

[[ $1 == '--update' ]] && generate-list

blacklist_age=$((EPOCHSECONDS - $(stat --format=%Y "/usr/local/etc/dnscrypt/domains-blacklist.txt")))
max_age=$((7 * 24 * 60 * 60)) # 7 days

if [[ $blacklist_age -gt $max_age ]]; then
   generate-list
fi

size=$(wc -c </usr/local/etc/dnscrypt/domains-blacklist.txt)

[[ $size -eq 0 ]] && generate-list

`

**Comment by rr0ss0rr** [comment]
[update-dnscrypt-blacklist.txt](https://github.com/DNSCrypt/dnscrypt-proxy/files/3964263/update-dnscrypt-blacklist.txt)

I run this daily and will update the blacklist if older than 7 days or the list is 0 bytes

**Comment by rr0ss0rr** [comment]
[update-dnscrypt-blacklist.txt](https://github.com/DNSCrypt/dnscrypt-proxy/files/3964266/update-dnscrypt-blacklist.txt)

I run this daily and will generate the list if older than 7 days and will check if the list generated is 0 bytes
