### ISSUE TITLE
SIGSEGV when loading blacklist_file 

### ISSUE THREAD

**Issue by aureq** [DNSCrypt/dnscrypt-proxy#1116]
Hi,

I just upgraded from `2.0.33` to `2.0.35` running on Debian 10 (compiled from sources using golang `1.13.4`). Once the package was installed, the service got restarted as expected. However, I noticed the service is now crashing when loading the set of blocking rules (`blacklist_file`). After commenting that configuration entry, the service was able to start correctly.

My `blacklist_file` (see attachment) contains 2624101 lines / 65MB (that's probably a lot).

Searching further, I tried `2.0.34` and it exhibits the same problem where `2.0.33` is unaffected. So, looking into the code, I reverted commit 67c7254dc53c037b036a8eb9f0ee93ae02cb0107.
After removing that commit, the issue is **no longer happening**.

## Logs
```
Dec 14 20:26:58 eris systemd[1]: Started DNSCrypt client proxy.
Dec 14 20:26:58 eris dnscrypt-proxy[11660]: dnscrypt-proxy 2.0.34
Dec 14 20:26:58 eris dnscrypt-proxy[11660]: Network connectivity detected
Dec 14 20:26:58 eris dnscrypt-proxy[11660]: Source [public-resolvers] loaded
Dec 14 20:26:58 eris dnscrypt-proxy[11660]: Firefox workaround initialized
Dec 14 20:26:58 eris dnscrypt-proxy[11660]: Loading the set of blocking rules from [/var/lib/dnscrypt-proxy/blacklist.txt]
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8732e3]
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: goroutine 8 [running]:
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: main.(*PluginBlockName).Init(0xdee3b8, 0xc0000f2000, 0x0, 0x0)
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: #011github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:110 +0x623
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: main.(*Proxy).InitPluginsGlobals(0xc0000f2000, 0xc00006a500, 0x0)
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: #011github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugins.go:139 +0x3c8
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: main.(*App).AppMain(0xc000021650)
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: #011github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/main.go:124 +0xb3
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: main.(*App).Start.func1(0xc000021650)
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: #011github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/main.go:112 +0x2b
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: created by main.(*App).Start
Dec 14 20:26:59 eris dnscrypt-proxy[11660]: #011github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/main.go:111 +0x49
Dec 14 20:26:59 eris systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 14 20:26:59 eris systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
Dec 14 20:26:59 eris systemd[1]: dnscrypt-proxy.service: Start request repeated too quickly.
Dec 14 20:26:59 eris systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
Dec 14 20:26:59 eris systemd[1]: Failed to start DNSCrypt client proxy.
Dec 14 20:26:59 eris systemd[1]: dnscrypt-proxy.socket: Failed with result 'service-start-limit-hit'.
```

## *What* is affected by this bug?
dnscrypt-proxy 2.0.34 and 2.0.35. Version 2.0.33 is ok.

## *When* does this occur?
During the service start up, when (a large) `blacklist_file` is loaded.

## *Where* does it happen?
Debian GNU/Linux 10 (buster) Intel/AMD x64 bits.

## *How* do we replicate the issue?
1. Configure dnscrypt-proxy to use the [attached blacklist.txt](https://github.com/DNSCrypt/dnscrypt-proxy/files/3964361/blacklist.zip) on `blacklist_file`.
2. Start dnscrypt-proxy
3. The service should crash

## Expected behavior (i.e. solution)
No crash on startup and ability to load the entire `blacklist_file` file.

**Comment by welwood08** [comment]
The stack trace from the panic points at plugin_block_name.go:110, which in https://github.com/DNSCrypt/dnscrypt-proxy/commit/67c7254dc53c037b036a8eb9f0ee93ae02cb0107#diff-0c3839a85ca08d8aea4c07ace686e34dR110 suggests that when renaming the variable `blockedNames` to `xBlockedNames` a usage was missed. I'm not familiar with that part of the code or why a rename was needed, so @jedisct1 might want to confirm my analysis before I jump in and just rename the variable.

As a side effect, it seems to have highlighted 2 faulty lines in your blacklist. Since the affected code path is only followed when a line has a time constraint, I checked for lines containing `@` in your attached file. It looks like you've included email addresses with other non-domain junk suffixed, which is probably not what you intended even though it has helpfully revealed a bug in `dnscrypt-proxy` too.

**Comment by aureq** [comment]
Thank you @welwood08 and you're definitely right. The 2 lines were not intended at all.

**Comment by jedisct1** [comment]
Oops, you’re right. There’s an `x` missing here :/
