### ISSUE TITLE
have no idea what I'm doing

### ISSUE THREAD

**Issue by slayerkaido** [DNSCrypt/dnscrypt-proxy#1117]
Ok I'm pretty new to DNS technologies both servers and encryption alike but anything that I can use to make my home network safer is very well accepted. So far no matter what I've tried I cannot get my router to just use a dnscrypt-proxy machine alone, if router settings are changed to the static IP set for the machine on the router itself I get no internet connection, if told to listen to an IP whether it is the machines internal IP address or it is 127.0.2.1, 127.0.0.1 or 0.0.0.0 and the ports that were set I still cannot get a connection and dnscrypt-proxy when told to restart after an update with ANY IP address listed in the "listen_addresses []" portion of the dnscrypt-proxy.toml will immediately tell me that it failed to start stating that the IP address it was told to listen to has no permission.

to my understanding I've tried using it with pi-hole no no avail, tried the docker image for dnscrypt-server to no avail and I think several different options. For some reason I cannot get my router to pass dns queries through it to get an active internet connection, dnscrypt-alone or not.

do I have to have a valid private dns server to use this or is there something I'm missing because I'm new to all this?

**Comment by jedisct1** [comment]
What documentation page did you follow and at what step did you get a different result than expected?

**Comment by slayerkaido** [comment]
several but none work which leads to my conclusion that I'm not doing something right but I cannot find documentation that tells me a proper setup for dnscrypt-proxy on a server to allow my router (which is a netgear nighthawk r7000) to be able to use the device running dnscrypt-proxy as the primary dns server.

https://github.com/DNSCrypt/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes

https://www.derekseaman.com/2019/09/how-to-pi-hole-plus-dnscrypt-setup-on-raspberry-pi-4.html

those 2 are among the last 2 that I tried other than just installing dnscrypt-proxy on a machine attempting a configuration and trying to get it to be the primary dns server the router uses. 

btw ignore the ignore the portion of the last link that says raspberry pi 4, I used the guide to install all the software on Ubuntu server 19.10 which is what I've used the entire time.

**Comment by jedisct1** [comment]
Is your question:

"I was successfully able to install and use `dnscrypt-proxy` with public DNS servers; now, how to set up and use my own server?"

?

**Comment by slayerkaido** [comment]
no I was able to install but I cannot use it at all for some reason.

**Comment by jedisct1** [comment]
Is your question "how to install and use `dnscrypt-proxy` on Ubuntu"?

**Comment by slayerkaido** [comment]
no, how can I use one dnscrypt-proxy machine to encrypt ALL dns traffic on my network?

**Comment by rr0ss0rr** [comment]
Can you install dnscrypt-proxy on your router?

**Comment by slayerkaido** [comment]
I don't believe so, it is a netgear nighthawk R7000

**Comment by evilvibes** [comment]
Try something like AdGuard Home https://github.com/AdguardTeam/AdGuardHome

**Comment by jedisct1** [comment]
Seems to be [supported by OpenWRT](https://openwrt.org/toh/netgear/r7000).

But forget that route if this is too complicated.

Install `dnscrypt-proxy` on your Ubuntu machine using the generic [installation instructions](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux). Don't use the `.deb` package.

After the last step has been done, change `listen_addresses = ['127.0.0.1:53']` to `listen_addresses = ['0.0.0.0:53']`, and configure the rest of your network to use the Ubuntu machine IP address as a stub DNS resolver.
