### ISSUE TITLE
Recurring problem since version 2.0.34

### ISSUE THREAD

**Issue by SpeedyGonzague** [DNSCrypt/dnscrypt-proxy#1119]
Hi,

I'm not reporting a bug given I don't know if it is.
I'm a DNSCrypt-proxy user ever since it's launch. My OS is Windows 7 (x64)
I run DNSCrypt-proxy 2.0.33. I've encountered ever since ver. 2.0.34 the impossibility to download certain files whilst no problem with ver. 2.0.33 and previous.

I presume this is related to the feature added to 2.0.34 : 

> Blacklisted names are now also blocked if they appear in CNAME pointers

Some files download correctly, others don't, i.e. `https://feodotracker.abuse.ch/downloads/ipblocklist.txt`
If this related to a blacklisted name the problem is I have no mean to find out which one : Query Log reports, i.e. for the above mentioned url:
`feodotracker.abuse.ch      REJECTED`

Of course no `feodotracker.abuse.ch`, no `feodotracker`, no `abuse` in my blocking rules.

This is a total mystery. Thanks for your help/advice.

**Comment by jedisct1** [comment]
Enable the logfile for blocked queries, it will tell you what rule triggered a block.

**Comment by SpeedyGonzague** [comment]
I had totally forgotten the blocked queries logfile. I just enabled it and found the culprit. Thanks.

The blocked queries logfile mentioned for `https://feodotracker.abuse.ch/downloads/ipblocklist.txt` (for `https://feodotracker.abuse.ch/ `itself in fact):
`[2019-12-18 19:36:05]	127.0.0.1	p2.shared.global.fastly.net	*fastly* (alias for [feodotracker.abuse.ch])`

That's me, because I'm testing blacklisting `fastly` globally given it gets called practically everywhere when in fact the sites run perfectly without that connection (I do have 2-3 fastly connections whitelisted), but that's another problem ...

Remains the following problematic:

Before 2.0.34 and its _Blacklisted names are now also blocked if they appear in CNAME pointers_, a blacklisted pointer would be blocked without the whole addressed url, but since 2.0.34 the 'healthy' url is blocked as well.

Example:

I regularly visit `https://www.spamhaus.org/statistics/tlds/` and noticed recently that it accesses `www.spamhaus.org.cdn.cloudflare.net`  'behind-the-scene' (doesn't appear i.e. in uBlock Origin). This call to _cloudflare_ is absolutely superfluous so i've added` www.spamhaus.org.cdn.cloudflare.net` in my blocklist and the query logs are:

With DNSCrypt-proxy 2.0.33:
```
127.0.0.1	www.spamhaus.org		A	PASS	32ms	quad9-dnscrypt-ip4-filter-pri	
127.0.0.1	www.spamhaus.org		A	PASS	0ms	-	
127.0.0.1	www.spamhaus.org.cdn.cloudflare.net	A	REJECT	0ms	quad9-dnscrypt-ip4-filter-pri	
```

With DNSCrypt-proxy 2.0.35:
`127.0.0.1	www.spamhaus.org		A	REJECT	32ms	quad9-dnscrypt-ip4-filter-pri`

Which means that 2.0.35 (and 2.0.34) block` www.spamhaus.org`because `www.spamhaus.org.cdn.cloudflare.net` is blacklisted.
What's the point when 2.0.33 keeps the good and blocks the bad?

My style is not al all technical but I hope nevertheless my point remains understandable.

**Comment by jedisct1** [comment]
`www.spamhaus.org` is just another name for `www.spamhaus.org.cdn.cloudflare.net`.

The log file with blocked queries will tell you:

```text
... www.spamhaus.org.cdn.cloudflare.net	... (alias for [www.spamhaus.org])
```

**Comment by SpeedyGonzague** [comment]
I know all of that, @jedisct1 , but applied as presently I'll stick on DNSCrypt-proxy 2.0.33
Your answer doesn't say why I'd have to allow `www.spamhaus.org.cdn.cloudflare.net` in order to access` www.spamhaus.org`, an example among many others. It's just not adequate.
Maybe an option to disable the _Blacklisted names blocked if they appear in CNAME pointers_ would be welcomed.
Thanks anyway for your time.

**Comment by jedisct1** [comment]
Because they are the same!
