### ISSUE TITLE
Add auto-retest server function

### ISSUE THREAD

**Issue by sam1275** [DNSCrypt/dnscrypt-proxy#112]
I noticed that the log only update on each time program start, even if the network is down and recover later, the log doesn't show anything. And it takes a long time for the DNS service to be usable (longer than v1)
Does this mean the servers are only checked on every start and never again? And does this also mean the auto failover is not work?
The log level is 1.
I think the servers in list should be re-checked every few hours or days without restart the program, or at least when the network is down and up.

**Comment by jedisct1** [comment]
Stop staring at log files and just use your computer :)

The RTT of each resolver is updated after every query.

**Comment by jedisct1** [comment]
And queries are forwarded as soon as the first resolver has been verified.
