### ISSUE TITLE
How to ensure the padding option is being used?

### ISSUE THREAD

**Issue by gaia** [DNSCrypt/dnscrypt-proxy#1121]
https://tech.slashdot.org/story/19/12/22/007216/dns-over-https-not-as-private-as-some-think

"Current clients, and most current DoH services, do not implement the optional padding option, which is necessary to obscure the length of the requested hostname."

Quad9 for example. Do they implement the passing option (I imagine it has to be supported on the server side and I assume it is implemented on the client side) ?

**Comment by jedisct1** [comment]
`dnscrypt-proxy` has always done padding. Padding DNS queries and responses was a requirement of the DNSCrypt protocol, years before DoH existed. `dnscrypt-proxy` always does it client-side for all protocols.

Server-side, all DNSCrypt servers do padding.

For DoH servers, at least `doh-crypto-sx`, `cloudflare` and `nextdns` do, as well as all servers using my `rust-doh` server.
