### ISSUE TITLE
Exception during execution of utils/generate-domains-blacklist.py

### ISSUE THREAD

**Issue by partytoni** [DNSCrypt/dnscrypt-proxy#1123]
## *What* is affected by this bug?

The bug affects the execution of the blacklist file, since it stops it and no blacklist file is produced.

## *When* does this occur?

This occurs if it's not possible to resolve an url.

## Expected behavior (i.e. solution)

The solution should be changing the line 165 from:
sys.stderr.write(e.message)
to:
sys.stderr.write(e.msg)

since the message attribute is deprecated since python 2.6.

## Other Comments
Sorry if this is not a valuable issue to be noticed about.

**Comment by jedisct1** [comment]
Fixed, thank you!
