### ISSUE TITLE
DoT support

### ISSUE THREAD

**Issue by DI555** [DNSCrypt/dnscrypt-proxy#1124]
## Is your feature request related to a problem?

since the full DoH support was implemented, would be great to be a DoT full support either !!! By now it's the only local DoT server support, but i hope to be a DoT dns resolvers support either(just to give a plus to choose udp resolving not on usual 53 port).

## Who will that feature be useful to?

it's a much improvement - a lots more ways to be in touch with independent dns data !!!

## What are you going to contribute?

just by now, would like to testing it, unfortunate i'm not much in coding

## Additional context

there ia a bunch of servers that already supports DoT, and i hope will be more

**Comment by r4sas** [comment]
Just leave that here: https://github.com/DNSCrypt/dnscrypt-proxy/search?utf8=%E2%9C%93&q=DoT+support&type=Issues

add: https://github.com/DNSCrypt/dnscrypt-proxy/issues/68#issuecomment-362526814

**Comment by DI555** [comment]
oh, i see...
but may be possible to keep this issue by a time and just place it in todo list, lease !!!

i meam, yes, no benefits...., but it's another plus to security, 
yes only one fixed port... , but what if will be possible to set the port..., or make it variable...,- 
DoT has a much potential !!!

**Comment by DI555** [comment]
but, anyways, keep this issue alive just for the part of it,-
 local DoT server support,
it's a future that imo awaited a lot !!!

**Comment by jedisct1** [comment]
Not going to happen, sorry.

DoT is archaic and I'd be more interested in implementing new anonymization protocols.

DoT may eventually be used (probably not much) between resolvers and authoritative servers, but between clients and resolvers, it doesn't have a bright future. Servers supporting it also support DoH anyway.

**Comment by DI555** [comment]
ok, yes, it's not qite theoretical developed for now ( i would like to see variable port for example )

but what about local DoT server support ?
 it's not bad actually, and i saw someone already asked it in some threads...

**Comment by Mikaela** [comment]
[UncencoredDNS](https://blog.uncensoreddns.org/) appears to support DoT without supporting DoH.

I would hope to see DNSCrypt-proxy supporting DoT and DoT gaining widespread support as DoH has the centralization problem, even if DNSCrypt is easily exempt from that.

**Comment by uBlock-user** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/issues/938#issuecomment-536445790

**Comment by DI555** [comment]
@jedisct1 
hm, don't blame me for that talks, but accordind to those scanning dpi futures:
www.ntop.org/wp-content/uploads/2013/12/nDPI_QuickStartGuide.pdf
-DoH doesn't much doing either (((

but supporting DoT it's just another step to be higher !!!
