### ISSUE TITLE
At startup the first server to be check always gets a timeout

### ISSUE THREAD

**Issue by howl** [DNSCrypt/dnscrypt-proxy#1125]
I used dnscrypt v1 for a long time over OpenWrt and now I have moved to v2.

I have found an issue where at boot, the two first servers always get a timeout, if I set up more timeout from the default 5000 to for example 10000, the result is that only the first server gets the timeout instead of the first two. Setting a ridiculous high timeout value doesn't solve the problem and the result is as expected more time for dnscrypt to startup.

I thought that the wan interface is not ready when dnscrypt detects it as it should, and there seems to be the problem. Setting up only one server is possible to enforce to use it because it retries because there are 0 reachable servers.

Watching the logs dnscrypt-proxy detects connectivity at 02:30:40 but wwan interface is up at 02:30:51.

```
logread | grep wwan
Sat Dec 28 02:30:47 2019 daemon.notice netifd: Interface 'wwan' is enabled
Sat Dec 28 02:30:49 2019 daemon.notice netifd: Interface 'wwan' has link connectivity
Sat Dec 28 02:30:49 2019 daemon.notice netifd: Interface 'wwan' is setting up now
Sat Dec 28 02:30:50 2019 daemon.notice netifd: wwan (2367): udhcpc: started, v1.30.1
Sat Dec 28 02:30:50 2019 daemon.notice netifd: wwan (2367): udhcpc: sending discover
Sat Dec 28 02:30:50 2019 daemon.notice netifd: wwan (2367): udhcpc: sending select for ***.***.***.***
Sat Dec 28 02:30:50 2019 daemon.notice netifd: wwan (2367): udhcpc: lease of ***.***.***.*** obtained, lease time 86400
Sat Dec 28 02:30:51 2019 daemon.notice netifd: Interface 'wwan' is now up
Sat Dec 28 02:32:16 2019 user.notice mwan3[3428]: Execute ifup event on interface wwan (wlan-wan)
Sat Dec 28 02:32:17 2019 user.notice mwan3[3428]: Starting tracker on interface wwan (wlan-wan)
Sat Dec 28 02:32:18 2019 user.notice firewall: Reloading firewall due to ifup of wwan (wlan-wan)
```

```
logread | grep dnscrypt
Sat Dec 28 02:30:32 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:32] [NOTICE] dnscrypt-proxy 2.0.34
Sat Dec 28 02:30:32 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:32] [NOTICE] Network not available yet -- waiting...
Sat Dec 28 02:30:40 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:40] [NOTICE] Network connectivity detected
Sat Dec 28 02:30:41 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:41] [NOTICE] Source [public-resolvers] loaded
Sat Dec 28 02:30:41 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:41] [NOTICE] Source [relays] loaded
Sat Dec 28 02:30:41 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:41] [NOTICE] Firefox workaround initialized
Sat Dec 28 02:30:41 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:41] [NOTICE] Loading the set of blocking rules from [blacklist.txt]
Sat Dec 28 02:30:42 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:42] [NOTICE] Now listening to 127.0.0.53:53 [UDP]
Sat Dec 28 02:30:42 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:42] [NOTICE] Now listening to 127.0.0.53:53 [TCP]
Sat Dec 28 02:30:48 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:48] [NOTICE] [************] TIMEOUT
Sat Dec 28 02:30:48 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:48] [ERROR] read udp ***.***.***.***:46404->***.***.***.***:443: i/o timeout
Sat Dec 28 02:30:48 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:30:48] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
Sat Dec 28 02:32:11 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:32:11] [NOTICE] [************] OK (DNSCrypt) - rtt: 45ms
Sat Dec 28 02:32:11 2019 daemon.err dnscrypt-proxy[1178]: [2019-12-28 01:32:11] [NOTICE] Server with the lowest initial latency: ************ (rtt: 45ms)
```

While writing this I haven't take into account that the router has two wan zone interfaces, wwan but also wan, and wan was up at 02:30:38, so I presume that dnscrypt is raising the network connectivity detected because the wan interface. I have installed mwan3 to manage the wan connections and wan is only used for a very limited purpose.

The wan connection is not able to connect to the netprobe_address I have set up, could be dnscrypt not checking connectivity with the netprobe_address?

**Comment by howl** [comment]
Ok, testing by removing the wan interface dnscrypt start as expected, so the problem seems to be dnscrypt trying to connect using wan instead of wwan because wan gets up first and wan really doesn't have connectivity to the dnscrypt servers.

Is there a way to specify to dnscrypt-proxy the exact connection to use? Or if dnscrypt-proxy checks connectivity to the specified netprobe_address why trigger wan the Network connectivity detected? If dnscrypt-proxy really checks with the netprobe_address I think mwan3 could have a little lag between the wan iface up and the rules it set up.

**Comment by jedisct1** [comment]
You can set `netprobe_address` to an IP address only reachable from the `wwan` interface. Or even set it to the IP address of the resolver you want to use.

**Comment by howl** [comment]
@jedisct1 yes, that what I have done for the first configuration. I have as netprobe_address the fallback dns server which is only reachable by the wwan interface. Could be the problem having netprobe_address as 'ip:53' instead of just 'ip'?

I get confused because the default configuration file defines the netprobe_address exactly the same as the fallback_resolver including the 53 port but I leave it with the port.

Will try to test it without the port when I can.

**Comment by howl** [comment]
netprobe_address address with no port, bad idea, is not possible. I have done various tests and seems that dnscrypt_proxy is not taking into account netprobe_address to test connectivity.

I have tested it by setting a private ip address that only exists inside the wwan interface (the ip private ip address that the router takes form wwan) and not in the wan interface, and dnscrypt-proxy still raises the connectivity event with the wan interface.

**Comment by jedisct1** [comment]
Apparently, there is a simple way to run a command after an interface is up: https://forum.openwrt.org/t/run-a-script-when-an-interface-goes-up-and-down/3728

**Comment by howl** [comment]
Yes, I use that kind of hotplug scripts to automate the orange state of wan leds that some routers have, but it's a pity somehow netprobe_address is not working as it should.

Anyways thanks for the hint, I will disable dnscrypt-proxy and manually start it from script.
