### ISSUE TITLE
Cloaking rules support for a specific port

### ISSUE THREAD

**Issue by arlllk** [DNSCrypt/dnscrypt-proxy#1126]
It could be great to have the cloaking rules to support specific names to redirect an IP with port, in a reverse proxy style, it would be much easier to set up that a complete reverse proxy (mainly in windows that is hell)

**Comment by jedisct1** [comment]
At DNS level, nothing can be redirected. DNS can return an IP address instead of another, but the protocol cannot redirect HTTP traffic to a different port or even to a different hostname.
