### ISSUE TITLE
will no longer listen on 0.0.0.0:53 "udp 0.0.0.0:53 bind: permission denied:"

### ISSUE THREAD

**Issue by slayerkaido** [DNSCrypt/dnscrypt-proxy#1128]
## *Who* is the bug affecting?
my guess is just me

## *What* is affected by this bug?
dnscrypt-proxy

## *How* do we replicate the issue?

for me it was just as simple as editing listen_addreses in the toml to 0.0.0.0:53

## Expected behavior (i.e. solution)
active running dnscrypt-proxy

## Other Comments
I've tried everything in ubuntu server 19.10 including disabling and stopping systemd to trying to work with systemd using this guide: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/systemd
I've also used every installation you can google for ubuntu and I've tried using ubuntu desktop 18.04 with it. I started with dnscrypt-proxy 2.0.19 which is included in ubuntu server 19.10 repository and it stopped working right after the server got its power cut and kept failing with "udp 0.0.0.0:53 bind: permission denied" I then installed the shevchuk repo and upgraded to dnscrypt-proxy 2.0.33 and that never worked right out of the box. 

the goal of all of this is to make a single dnscrypt-proxy machine act like a server and encrypt all dns traffic for every device that is on the network. What am I doing wrong? or how else can I accomplish this? I really don't want to go installing dnscrypt-proxy on all my machines and phones just to accomplish this. 

BTW: yes I did try the dnscrypt-server docker image but the documentation on it isn't that good and I never could understand what the heck I had to do to edit the toml file afterward. any help would be appreciated.

**Comment by jedisct1** [comment]
Uninstall everything and try the standard installation procedure https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux

**Comment by black-cerberon** [comment]
Try run as root, but before change config to:
`listen_addresses = [':53']`
`user_name = 'your_dnscrypt_user'`
