### ISSUE TITLE
[Niche] Blacklists dedicated to DoH only.

### ISSUE THREAD

**Issue by Samillion** [DNSCrypt/dnscrypt-proxy#1129]
## Is your feature request related to a problem?

I wouldn't describe it as a problem, it's a very unique situation to people that use Pi-Hole and add DNSCrypt-Proxy to enhance it even more.

I use Pi-Hole for the normal blacklisting and with it I use DNScrypt-Proxy for Anonymized DNS, CNAME blacklisting (blacklist.txt only contains domains I want to be CNAME blocked) and IP blacklist.

So essentially, Pi-Hole holds the main blocking lists (domains) and DNSCrypt handles everything else as I described.

The issue:
When enabling DoH to be used on Firefox for example, it skips Pi-hole blocking and goes directly to DNSCrypt-Proxy.

## Describe the solution you'd like
An option in `.toml` to have lists for DoH added, ie: `doh-blacklist.txt, doh-ip-blacklist.txt` and so on.

## Alternatives you've considered
Relying fully on DNSCrypt-Proxy by migrating all lists from Pi-Hole to it. The only thing stopping me is that CNAME blocking will cause a lot of tweaks to the lists I use, and to be honest, I absolutely love having CNAME blocking option that I would rather have it always enabled than not at all.

Especially after @jedisct1 explaining use scenarios lately when others showed concerns to something similar, it made sense to me.

## Who will that feature be useful to?
Users that have Pi-Hole + DNSCrypt-Proxy and would like to utilize DoH as well.

## What have you done already?
I'm planning to try and use DoH and Firefox's extension uBlock-Origin as a medium to replace Pi-hole on Firefox DoH.

## What are you going to contribute?
I honestly have no idea, my capabilities are mostly in testing, unfortunately. I sometimes create Bash scripts here and there. Recently I created a bash script to auto-update `ip-blacklist.txt` but my knowledge is without a doubt not good enough to handle projects on this scale.

## Additional context
I added the term [Niche] because this is a very specific use scenario and is definitely a highly optional and low priority feature request.

It's more of "Would be nice, for me and maybe others" scenario.

Nevertheless, I 100% appreciate all the work that has been done with this project, you've definitely made my online experience so much better.

**Comment by jedisct1** [comment]
Having `doh-blacklist.txt` and `doh-ip-blacklist.txt` (and `doh-whitelist.txt`, `doh-forwarding.txt`, `doh-cloaking.txt`, etc) would add a lot of confusion and duplication.

I don’t use Pi-Hole but as a lot of people seem to be using `dnscrypt-proxy` in conjunction with it, a more interesting goal would be to improve their integration.

In particular, it would be nice to be able to use `dnscrypt-proxy` to handle the blacklists managed by Pi-Hole and visible in the web interface. So that `CNAME` blocking, IP blocking, time-based blocking and other features can also be available right from the regular UI.

Log files from `dnscrypt-proxy` already include everything that Pi-Hole needs in the web interface.

In spite of being a common setup, installing and properly configuring `dnscrypt-proxy` on Pi-Hole also seems to be quite complicated at the moment. So, that’s another motivation for a better integration. Maybe it could be a different installer, or an option to choose at installation time.

**Comment by Samillion** [comment]
> Having doh-blacklist.txt and doh-ip-blacklist.txt (and doh-whitelist.txt, doh-forwarding.txt, doh-cloaking.txt, etc) would add a lot of confusion and duplication.

I honestly agree. Even while suggesting it I had doubts.

The easiest (or I should say the most practical) is if Pi-Hole integrates with DNSCrypt-Proxy and use its features, definitely.

That way, we set both DNSCrypt-Proxy as both DNS and DoH "handler" within Pi-hole, or something.

I'll share this with them soon, maybe they can offer more integration with your project as you suggested, hopefully.

Thank you for your reply, I'm going to close this as to not clutter the issues page.

Also, happy new year, everyone.

**Comment by jedisct1** [comment]
Happy new year! 🎉

**Comment by Samillion** [comment]
@jedisct1 Sorry for reviving a closed issue, I didn't want to create a new one to not clutter the page.

Instead of assigning DoH specific blacklists, would this work:

`https://[dnscrypt-proxy]/dns-query` instead of going directly to `/opt/dnscrypt-proxy/dnscrypt-proxy`, it would go to server's assigned DNS.

That way, whether you're using DNSCrypt-Proxy as the primary DNS handler or Pi-Hole+DNSCrypt-Proxy, the result would be the same.

Would that be possible?

In `.toml`, a possible option: `doh-local-dns=[true/false]`, where true = server DNS (ie: `127.0.0.1:53`) and false goes directly to `/dnscrypt-proxy`

**Comment by jedisct1** [comment]
If you need nothing from what `dnscrypt-proxy` does, but just want to forward DoH connection to a server, you can use a DoH proxy such as [rust-doh](https://github.com/jedisct1/rust-doh).

**Comment by Samillion** [comment]
Thank you for the suggestion, will check it out.
