### ISSUE TITLE
Block only ipv6 addresses for specific domains

### ISSUE THREAD

**Issue by mikeS7** [DNSCrypt/dnscrypt-proxy#1130]
## Is your feature request related to a problem?

I'm using VPN with only ipv4 support to route traffic for some sites. If site has ipv6 address it will bypass VPN.
Now the only option to completely disable ipv6 with block_ipv6 = true option.

## Describe the solution you'd like

Extend filtering to support blocking only ipv6 related queries not ipv4 per domain.

## Who will that feature be useful to?

Anyone who wants to have more control on dual stack environment.

**Comment by jedisct1** [comment]
IPv6 leaks is more of an issue with your VPN setup.

You should either use a better VPN, disable IPv6 at OS-level or add firewall rules to block IPv6 traffic.

IPv6 leaks used to be a common issue in the past, but I’m sure you can easily find a lot of solutions to avoid this now. A DNS-based one would be by far the least reliable.
