### ISSUE TITLE
Logs cannot be output to stdout on windows

### ISSUE THREAD

**Issue by GeekDuanLian** [DNSCrypt/dnscrypt-proxy#1131]
## *Who* is the bug affecting?

configuration file

## *What* is affected by this bug?

logging

## *When* does this occur?

always

## *Where* does it happen?

console on windows

## *How* do we replicate the issue?

on configuration file:

> [query_log]
file = '/dev/stdout'

and run

## Expected behavior (i.e. solution)

should be log to the standard output

## Other Comments

It just output to `C:\dev\stdout` file

**Comment by jedisct1** [comment]
Well... this is expected... `/dev/stdout` is a special file on Unix, not on Windows.

I think on Windows it's called 'CON'.

**Comment by GeekDuanLian** [comment]
That should be specially noted, the document only says /dev/stdout

**Comment by GeekDuanLian** [comment]
And 'CON' is also invalid, no output to standard output, nor to any file

**Comment by Kein** [comment]
Someone add small clarification to the config comment that on Android instead of using the linked `/dev/stdout` you just should use direct `/proc/self/fd/1` for STDOUT since the former does not exist/work there.
