### ISSUE TITLE
build failed under Debian Buster

### ISSUE THREAD

**Issue by kairaven** [DNSCrypt/dnscrypt-proxy#1132]
## *What* is affected by this bug?

build of the dnscrypt-proxy binary. The build process aborts with:
`# vendor/github.com/kardianos/service
../vendor/github.com/kardianos/service/service_linux.go:66:6: isInteractive redeclared in this block
        previous declaration at ../vendor/github.com/kardianos/service/service_aix.go:75:29
`
## *When* does this occur?

after the command
go build -ldflags="-s -w" -o $GOPATH/linux-amd64/dnscrypt-proxy

## *Where* does it happen?
after
/opt/git/dcp$ export GOPATH=$PWD
/opt/git/dcp$ cd src/dnscrypt-proxy/
in /opt/git/dcp/src/dnscrypt-proxy

## *How* do we replicate the issue?

sudo aptitude install git golang

mkdir /opt/git/dcp
cd dcp
git clone https://github.com/jedisct1/dnscrypt-proxy src
export GOPATH=$PWD
cd src/dnscrypt-proxy/
go clean
go build -ldflags="-s -w" -o $GOPATH/linux-amd64/dnscrypt-proxy

**Comment by jedisct1** [comment]
It is only tested with the current stable version of Go.

Looks like Debian has a pretty old version of the compiler. Messing with `GOPATH` hasn't been necessary for quite some time.

Releases are built with:

```sh
cd dnscrypt-proxy
env CGO_ENABLED=0 go build -mod vendor
```

Also this error seems to be in a 3rd party package ([kardianos/service](https://github.com/kardianos/service)) not in `dnscrypt-proxy`. So bugs should be reported and fixed there.

**Comment by kairaven** [comment]
Thx for you info. After installing go 1.13 from the Debian testing repository, all works fine (with the mentioned command and without errors regarding kardianos/service).
