### ISSUE TITLE
Possible Iodine with dnscrypt-proxy?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1134]
Hi!

Is it possible to run all traffic and dns requests with dnscrypt-proxy over iodine?

**Comment by ghost** [comment]
. . . I meant hiding all traffic including DNS requests with dnscrypt-proxy over iodine. . .

**Comment by jedisct1** [comment]
Hi,

iodine sets up a tunnel. All the traffic, including DNS traffic (encrypted or not) will go through that tunnel.

So, yes, it works. But keep in mind that `iodine` doesn't provide any security at all. Nothing is encrypted.
