### ISSUE TITLE
Problem with Dnscrypt -resolve

### ISSUE THREAD

**Issue by florentmsl** [DNSCrypt/dnscrypt-proxy#1135]
## Problem 

Im at the point to test the dnscrypt connection like this:

>./dnscrypt-proxy -resolve github.com

and I get the following output:

> Resolving [github.com]
> 
> Domain exists:  probably not, or blocked by the proxy
> Canonical name: -
> IP addresses:   -
> TXT records:    -

so I have no connection to a DNS-Server.. the 

**dnscrypt-proxy.toml** is equivalent to the  (--> [example one](https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml))

my **resolv.conf:**

> root@kali:/opt/dnscrypt-proxy/linux-arm64# cat /etc/resolv.conf
> #Generated by NetworkManager
> nameserver 127.0.0.1

the `./dnscrypt-proxy` works fine:

> root@kali:/opt/dnscrypt-proxy/linux-arm64# ./dnscrypt-proxy
> .......
> [2020-01-04 17:19:11] [NOTICE] dnscrypt-proxy is ready - live servers: 87
> [2020-01-04 17:20:32] [NOTICE] Stopped.

as soon as I change the nameserver in my `resolv.conf` to e.g 1.1.1.1, then the` ./dnscrypt-proxy -resolve github.com` does work.

Port 53 is clear:

> root@kali:/opt/dnscrypt-proxy/linux-arm64# ss -lp 'sport = 53'
> Netid  State  Recv-Q  Send-Q   Local Address:Port   Peer Address:Port  Process

So nothing listens on port 53..

## Device

I am on a Raspberry Pi 3 with Kali Linux as the OS. - Version:

> root@kali:/opt/dnscrypt-proxy/linux-arm64# uname -a
> Linux kali 4.19.81-Re4son-v8+ #1 SMP PREEMPT Wed Nov 6 03:33:03 UTC 2019 aarch64 GNU/Linux

and I chose the [dnscrypt-proxy-linux_arm64-2.0.36.tar.gz](https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.36/dnscrypt-proxy-linux_arm64-2.0.36.tar.gz) version of dnscrypt

I appreciate any kind of help!

**Comment by jedisct1** [comment]
Hi!

Did you keep `dnscrypt-proxy` running while trying the test?

**Comment by florentmsl** [comment]
> Hi!
> 
> Did you keep `dnscrypt-proxy` running while trying the test?

Hi!

I am following [this ](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux)guideline step by step, so `dnscrypt-proxy` is not started as a service yet (currently till step 4).  I thought it should be working even without the service at this point, because im calling dnscrypt-proxy directly and not  through a web browser in example. 
Did I misunderstand your question? 

Thanks for your reply!

**Comment by jedisct1** [comment]
The proxy needs to be running so it can respond to the request.

The `dnscrypt-proxy -resolve` command must be typed in another terminal window.

**Comment by florentmsl** [comment]
Wow.. I thought it is implemented in another way. Dumb mistake, now it works. 

Thanks for your help!
