### ISSUE TITLE
How to force the refresh of a cached address?

### ISSUE THREAD

**Issue by eclipseo** [DNSCrypt/dnscrypt-proxy#1138]
## Subject
* [x ] Other

## Description

I have a cached address that has become stale, how can I force dnscrypt-proxy to update the record it has in its cache?
If I disable the cache it works, but if I reenable it, it doesn't.

**Comment by r4sas** [comment]
Just restart dnscrypt-proxy.
Otherwise: see https://github.com/DNSCrypt/dnscrypt-proxy/issues/1012.

**Comment by eclipseo** [comment]
I tried restarting but the cache seems still there.

Thanks anyhow.

**Comment by r4sas** [comment]
> I tried restarting but the cache seems still there.

If you checked via browser - most of them has internal cache.
