### ISSUE TITLE
Is it possible to tell which program send for which dns query?

### ISSUE THREAD

**Issue by OnionSalt** [DNSCrypt/dnscrypt-proxy#1139]
I dont know if this is normal, but there are so many PTR queries in query.log file, so I want to know which program send all those PTR queries.

I'm using windows 10

**Comment by r4sas** [comment]
iptables + `-j MARK --set-mark`. But every program must run as different users (like in android) to mark packets regrading of user.
There can be any other ways, maybe someone else offer other ideas.

**Comment by OnionSalt** [comment]
Is there anyway to do this on windows 10?

**Comment by r4sas** [comment]
> Is there anyway to do this on windows 10?

nope.
You can try use netstat in command line, or some software which will print information about connections.

**Comment by OnionSalt** [comment]
> > Is there anyway to do this on windows 10?
> 
> nope.
> You can try use netstat in command line, or some software which will print information about connections.

Thanks.
I'm still open for suggestions.

**Comment by jradd** [comment]
> I'd suggest reasonable means to forward-proxy service-pinning with and without OSCP (wildcard domains with[out] SN you can resolve) or tighten service authentication with public key pairs. 

Control of your DNS you can use SSO to filter for SRV queries and require source to be defined and use forwarder.

> for simple connections disabling service discovery (UPNP, SSDP, LLDP) [and ipv6 if you want]

Yeah, lets git right on that

**Comment by OnionSalt** [comment]
Sorry, almost forgot about this

> > I'd suggest reasonable means to forward-proxy service-pinning with and without OSCP (wildcard domains with[out] SN you can resolve) or tighten service authentication with public key pairs.
> 
> Control of your DNS you can use SSO to filter for SRV queries and require source to be defined and use forwarder.
> 
> > for simple connections disabling service discovery (UPNP, SSDP, LLDP) [and ipv6 if you want]
> 
> Yeah, lets git right on that

Thanks for the reply, can you provide the link of the quote? I can't find it.
Also I don't quite understand what you said, maybe a bit more detail?

**Comment by r4sas** [comment]
I think he posted response in wrong issue.
