### ISSUE TITLE
[DNS stamps] vue-dnsstamp demo: Path is ignored for DoH?

### ISSUE THREAD

**Issue by bortzmeyer** [DNSCrypt/dnscrypt-proxy#1144]
At https://dnscrypt.info/stamps/ when I create a stamp for a DoH resolver, the stamp is not changed when I change the path (which, according to https://github.com/DNSCrypt/dnscrypt-proxy/wiki/stamps should be used for the stamp).

**Comment by jedisct1** [comment]
Hi,

As it is displayed on a single line, only the beginning of the string may be visible.

If you copy/paste it, you will get the entire string.

**Comment by bortzmeyer** [comment]
OK, I see. Disturbing.
