### ISSUE TITLE
illegal option -a

### ISSUE THREAD

**Issue by puddingepoch** [DNSCrypt/dnscrypt-proxy#1145]
i was previously able to set dnscrypt_proxy_flags="-a 127.0.0.1:5353"
now i can no longer do this, i cannot see why it was removed but what do i do now instead..?

**Comment by jedisct1** [comment]
Can you explain where `dnscrypt_proxy_flags` comes from?

Is it on OpenBSD, in the `rc.conf.local` file?

**Comment by jedisct1** [comment]
Googling for that string suggests that it was on an old OpenBSD version.

When upgrading OpenBSD, you should check https://www.openbsd.org/faq/ for upgrading instructions.

Instructions from 6.4 to 6.5: https://www.openbsd.org/faq/upgrade65.html
from 6.5 to 6.6: https://www.openbsd.org/faq/upgrade66.html

**Comment by puddingepoch** [comment]
i am using freebsd 11, i just upgraded from dnscrypt 1 to 2 after running it a long timeand the flag no longer works

**Comment by jedisct1** [comment]
`dnscrypt-proxy` version 1 reached end-of-life 2 years ago.

See here for the documentation of the current version: https://github.com/dnscrypt/dnscrypt-proxy/wiki
