### ISSUE TITLE
Fresh install OpenWrt and Dnsycrypt-proxy

### ISSUE THREAD

**Issue by nuketank** [DNSCrypt/dnscrypt-proxy#1147]
Great project, I have been using dnscrypt-proxy for years. Now I am trying to install the newest version and ran into a small problem. I did a fresh install of OpenWrt so I assure have a fresh updated installation on that end. I have successfully installed dnscrypt-proxy on my router, it works perfect on the LAN port, meaning I can do what dnscrypt-proxy is intended to do. Now the problem is my Wifi doesnt seem to behave the same. All traffic via wifi does not go through dnscrypt-proxy. Any help/suggestion is greatly appreciated.

I probably didnt setup the wireless module on OpenWrt properly, I only enabled wifi and add password.

**Comment by jedisct1** [comment]
Is it after following the [instructions for OpenWRT](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-OpenWRT)?

**Comment by nuketank** [comment]
I installed dnscrypt-proxy via the instructions on this github. Instructions for Openwrt are for installing Openwrt firmware only. Maybe there's a setting to bind via WLAN that I missed? Or if the dnscrypt-proxy is not directly applicable for all ports?

**Comment by lessneek** [comment]
@nuketank can you share a backup archive, I shall take a look at your settings. Or at least `/etc/config/network` and `/etc/config/wireless` and `/etc/config/firewall`.
