### ISSUE TITLE
Cloudflare certificate hash not found

### ISSUE THREAD

**Issue by changjo** [DNSCrypt/dnscrypt-proxy#1148]
Hi,
I got an error like below.
Several days ago, I updated it using `https://github.com/DNSCrypt/dnscrypt-resolvers` but I got an error again...

```
...
[ERROR] Certificate hash [3da4b71634a413c1cef34aa96d25a401634d4cf36c3b133c74294e48e637012a] not found for [cloudflare]
[NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
...
```

**Comment by WinkelCode** [comment]
Exact same error here!

Update: Seems to work again for me. I didn't change anything (besides getting the executable, up to date, although that didn't fix the issue) so I guess it must've been something on Cloudflare's side.

Update 2: Happened again... until I restarted the service once again. Some CDN/Load balancing thing maybe?

**Comment by elgab** [comment]
[ERROR] Certificate hash [3da4b71634a413c1cef34aa96d25a401634d4cf36c3b133c74294e48e637012a] not found for [cloudflare]

Same here, using the updated static stamp:
[static.'cloudflare']
stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEgPaS3FjSkE8HO80qpbSWkAWNNTPNsOxM8dClOSOY3ASoSZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk'

**Comment by iefdev** [comment]
Same here… Happened a few days ago, and now yesterday again. In my case _Cloudflare_, so I had to add a few other ones to my list, and it popped back again.

_Status page looks ok'ish: [cloudflarestatus.com](https://www.cloudflarestatus.com). Don't know if the list of issues are related or not._

**Comment by jedisct1** [comment]
Cloudflare changed their certificate chain again.

Since this is happening too frequently, certificate verification has been removed for Cloudflare.

**Comment by iefdev** [comment]
That was fast. Thanks! for the fix. :+1:

**Comment by changjo** [comment]
Thanks! 👍
