### ISSUE TITLE
WSL 2 bug

### ISSUE THREAD

**Issue by privacyguy123** [DNSCrypt/dnscrypt-proxy#1153]
## *Who* is the bug affecting?

WSL 2 users

## *What* is affected by this bug?

Ability to use WSL 2 in Windows 10

## *When* does this occur?

As long as DNSCrypt is installed and listening on port 53

## *How* do we replicate the issue?

Install DNSCrypt, try to run WSL 2

## Expected behavior (i.e. solution)

WSL 2 isn't working if another program is listening on port 53 -  I have no idea how to fix this. :)

**Comment by jedisct1** [comment]
Since this is a question about WSL and not about this project, you may have more luck on forums about Windows or WSL.

**Comment by privacyguy123** [comment]
Posted over there too. :)

**Comment by privacyguy123** [comment]
Is it possible its something to do with the newer build of Windows Dnscache service listening on port 5353 and not 53?

**Comment by privacyguy123** [comment]
Can you confirm if DNSCrypt works as intended listening on port 5353? for now it seems like WSL 2 and it are playing nice together on that port ...
