### ISSUE TITLE
Possible disservice Anonymized DNS ?

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#1155]
@jedisct1 

I configured my dnscrypt proxy to work with scaleway-fr servers and with cs-it and cs-pl relays for dns anonymus. but after a few minutes of correct functioning on my network and pihole I don't surf anymore.  Duckdns domains not immediately updated as cloudflare but above all absence of navigation by mistake dns.  many times for ip not updated on the DNS servers, as I try to remove scaleway-Fr and I put cloudflare everything works again.  I wonder if there are problems or what to do thanks

**Comment by jedisct1** [comment]
Try different relays, with only one relay at a time and without relays.

Enable logging (query log, and log file) to find what exact queries do not return what you expect.

If the do return what you expect and later don't, try to find what happened in-between and how to reliably reproduce this.

Also try with and without pi-hole. If you get different results with and without pi-hole, compare the queries and responses that have been sent and received in both cases.

**Comment by tigernero79** [comment]
I have tested without relay and it seems to be going, I think they have query problems.  but shouldn't relays simply send requests to scaleway-fr?

**Comment by alpe12** [comment]
I have the same problem, but with cloudflare and **without relays**.
I have the cloudflare server configured as static.
Happening on my Ubuntu machine and on my Windows 10 machine (each running their own dnscrypt).

**Comment by alpe12** [comment]
@jedisct1
> Enable logging (query log, and log file) to find what exact queries do not return what you expect.

All queries fail after the server has been running for about 15m.
They all return NETWORK_ERROR.
`2020-01-19 12:23:59]   127.0.0.1       imap.gmail.com  AAAA    NETWORK_ERROR   1ms     cloudflare-ipv6`

My full config:
https://pastebin.com/17PA5g7Q

**Comment by tigernero79** [comment]
@alpe12 
where did you get the cloudflare static "sdns" from?  if you try to comment them then without using them see if you solve

**Comment by alpe12** [comment]
> @alpe12
> where did you get the cloudflare static "sdns" from? if you try to comment them then without using them see if you solve

Got it from https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md some time ago.
I usually disable 'sources' and add them as 'static'.

For the purpose of this test I removed 'static' and re-enable 'sources'.
I tried many different configurations, even disabling tls_disable_session_tickets which I normally enable.

Both 'cloudflare' and 'cloudflare-ipv6' eventually stop working (giving NETWORK_ERROR until restart). But 'google' works.

Edit: Out of nowhere, it appears to have started working again. With the same configuration I was using before.

Edit2: nope. Still not working.

**Comment by tigernero79** [comment]
that I know of cloudflare does not support anonymous dns, but only doh why you cannot use sdns for anonymity dns, but only as a secure dns server.  so much so that I find it in the public list resolve.md and not relay.md whose valid list can be found here: https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/relays.md

**Comment by tigernero79** [comment]
@jedisct1 
I noticed that if I use anonymous relays as name instead of url sdns everything works
How is it possible?
place example

if I use
```
routes = [
   { server_name='scaleway-fr', via=['sdns://gRIxODUuOTQuMTkzLjIzNDo0NDM', 'sdns://gQ81LjEzMy44LjE4Nzo0NDM'] }
 ]
```
navigation is blocked
while if I set the same relays so it works
```
routes = [
   { server_name='scaleway-fr', via=['anon-cs-it', 'anon-cs-po'] }
 ]
```
what can it be?

**Comment by tigernero79** [comment]
unfortunately after a while the network crashes even with relays declared with name.  I had to disable them

**Comment by tigernero79** [comment]
only when I enable relay in anonymity dns connection hangs and I don't understand why, it is some day that I have this behavior no change

**Comment by tigernero79** [comment]
@jedisct1 

on file query log I have these errors when I enable Anonymized DNS both changing different relays and calling them by name or sdns (SERVER_TIMEOUT)

```
[2020-01-22 14:08:14]   127.0.0.1       storage.googleapis.com  A       PASS    42ms    scaleway-fr
[2020-01-22 14:08:48]   127.0.0.1       r2---sn-uxaxpu5ap5-o52e.googlevideo.com AAAA    PASS    43ms    scaleway-fr
[2020-01-22 14:09:11]   127.0.0.1       play.googleapis.com     A       PASS    46ms    scaleway-fr
[2020-01-22 14:09:13]   127.0.0.1       bv2stub.samsungvisioncloud.com  A       PASS    44ms    scaleway-fr
[2020-01-22 14:09:34]   127.0.0.1       r5---sn-4g5ednsl.googlevideo.com        A       PASS    80ms    scaleway-fr
[2020-01-22 14:09:58]   127.0.0.1       44c5weyfzhmufmzql2qyzuhduqbqeaqbaeaq.a.e.e5.sk  TXT     SERVER_TIMEOUT  5005ms  scaleway-fr
[2020-01-22 14:10:02]   127.0.0.1       _http._tcp.raspbian.raspberrypi.org     SRV     SERVER_TIMEOUT  5001ms  scaleway-fr
[2020-01-22 14:10:02]   127.0.0.1       _http._tcp.archive.raspberrypi.org      SRV     SERVER_TIMEOUT  5006ms  scaleway-fr
[2020-01-22 14:10:06]   127.0.0.1       www.duckdns.org AAAA    SERVER_TIMEOUT  5001ms  scaleway-fr
[2020-01-22 14:10:07]   127.0.0.1       _http._tcp.archive.raspberrypi.org      SRV     SERVER_TIMEOUT  5003ms  scaleway-fr
[2020-01-22 14:10:07]   127.0.0.1       _http._tcp.raspbian.raspberrypi.org     SRV     SERVER_TIMEOUT  5003ms  scaleway-fr
```

**Comment by tigernero79** [comment]
@jedisct1 
can this help you understand cs relay problems?
SERVER_TIMEOUT

https://cryptostorm.ch/viewtopic.php?f=32&t=13096

after various tests I can tell you that the timeout block occurs with all the cryptostorm anon-cs relays

**Comment by tigernero79** [comment]
@jedisct1 
could it be related to this problem?

https://github.com/jedisct1/encrypted-dns-server/pull/13

**Comment by Kein** [comment]
It seems to be either relay issues if you use relay routing or the custom DNS server issues if you are not using google/cloudflare, I have the same problem rarely. Switching to DoH and CF/Google mostly solves it. I guess in the end there isnt point of 99999999 dns secure servers when only 2 of them are reliable :woman_shrugging:

**Comment by tigernero79** [comment]
for me with the scaleway-fr server only relays that are not anon-cs work in Europe.
currently with scaleway I use: "anon-dnscrypt.one" and "anon-ibksturm" but I would like to use the Italian one anon-cs-it closest to me.

**Comment by jedisct1** [comment]
Try version 2.0.38 and also different relays. Some may be too far away or have bad connectivity.

**Comment by tigernero79** [comment]
@jedisct1 
updated to 2.0.38 unfortunately with anon-cs relays always timeout error. unfortunately error persists on anon-cs relays

**Comment by alpe12** [comment]
My problem (which isn't exactly the same as op) appears to have been fixed. Kind of....

From time to time there's this:
> [2020-01-30 16:16:00] [INFO] Server [cloudflare] returned temporary error code [2] -- Upstream server may be experiencing connectivity issues
> [2020-01-30 16:16:02] [INFO] Server [cloudflare] returned temporary error code [2] -- Upstream server may be experiencing connectivity issues
> [2020-01-30 16:41:09] [INFO] Server [cloudflare-ipv6] returned temporary error code [2] -- Upstream server may be experiencing connectivity issues
> [2020-01-30 16:41:09] [INFO] Server [cloudflare-ipv6] returned temporary error code [2] -- Upstream server may be experiencing connectivity issues
> [2020-01-30 16:41:11] [INFO] Server [cloudflare-ipv6] returned temporary error code [2] -- Upstream server may be experiencing connectivity issues

And on the query log:

> [2020-01-30 16:41:10]   127.0.0.1       imgix.net.dob.sibl.support-intelligence.net     A       NXDOMAIN        722ms   cloudflare-ipv6
> [2020-01-30 16:41:11]   127.0.0.1       humblebundle.com.multi.surbl.org        A       SERVFAIL        2231ms  cloudflare-ipv6
> [2020-01-30 16:41:37]   127.0.0.1       1337x.to        AAAA    PASS    40ms    cloudflare
> [2020-01-30 16:41:37]   127.0.0.1       1337x.to        A       PASS    40ms    cloudflare-ipv6

But since this usually only affects one query and then starts working normally again, I can live with that.

**Comment by tigernero79** [comment]
@jedisct1 
put back as relay tonight anon-cs-it and anon-cs-po and it seems to go hopefully the situation will last. Good night
