### ISSUE TITLE
TLS client authentication support

### ISSUE THREAD

**Issue by kei0** [DNSCrypt/dnscrypt-proxy#1156]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description
I’m running my personal DoH server which has Nginx on its front end. To make it more personalized, I’d like to enable TLS client authentication between dnscrypt-proxy and the DoH server on the internet.
DoH server is working fine with TLS authentication. So I’m looking for a way to enable client authentication in dnscrypt-proxy configuration. Is this supported (or planned)?

**Comment by jedisct1** [comment]
`dnscrypt-proxy` can add properties (as key/value pairs) to outgoing queries, with the `query_meta` parameter (see the relevant section on the example configuration file).

That can be used for client identification and more. Support for this will probably be added to `encrypted-dns-server` at some point.

**Comment by chantra** [comment]
Hi @jedisct1 ,

I understand that the benefit of `query_meta` is that it would work across the different flavors of protocols supported by `dnscrypt-proxy` and that in many cases, it may be easier to do than provisioning client certs.
That being said, I would be interested in adding support to do TLS client authentication which becomes handy when you manage both clients and servers and already have the certs figured out.

It seems this could easily fit within the [general config](https://github.com/DNSCrypt/dnscrypt-proxy/blob/b041eba311f0f3ad5dbd8f0c787dfbeda819651d/dnscrypt-proxy/config.go#L85), downside is that the client cert would be valid with specific sources/statics settings, in which case it would make more sense to have client cert/key under each `sources/static` sections.

Then it should be easy to update https://github.com/DNSCrypt/dnscrypt-proxy/blob/b041eba311f0f3ad5dbd8f0c787dfbeda819651d/dnscrypt-proxy/xtransport.go#L169 to add the client cert/key and add to the client's `Certificates`

Any thought?

**Comment by jedisct1** [comment]
Maybe the configuration could be similar to what we have for relaying, but with `(server, certificate)` pairs, where `server` can also be `*`.

**Comment by chantra** [comment]
I see, like:
```
client_auths = [
  # authenticate to specific server
  { server_name='example-server-1', client_cert='/path/to/cert', client_key='/path/to/key'},
  # authenticate to all server by default
  { server_name='*', client_cert='/path/to/cert', client_key='/path/to/key'},
]
```

**Comment by kei0** [comment]
@chantra  Thanks!
