### ISSUE TITLE
Blacklist bug: Lines with trailing #comments are ignored

### ISSUE THREAD

**Issue by ForkedLightning** [DNSCrypt/dnscrypt-proxy#1158]
Blacklist lines containing the # symbol are ignored.

Example blacklist line: www.example.com #comment
Expected behavior: www.example.com is blocked. Text after the # is ignored.
Actual behavior: www.example.com is allowed.

Behavior is undocumented so I assume it's a (critical) bug.

**Comment by jedisct1** [comment]
Blacklists and whitelists only contain patterns.

Documentation and examples never said that random characters could be added after them, including a particular way to add inline comments.

The `generate-domains-blacklist.py` script does a bit of preprocessing and, among other things, removes that style of inline comments.
