### ISSUE TITLE
How to add dnscrypt-proxy2 server to lists?

### ISSUE THREAD

**Issue by Strykar** [DNSCrypt/dnscrypt-proxy#116]
How do I generate the stamp/sdns so I can share my server with operators of lists?

**Comment by jedisct1** [comment]
Hi!

Do you already have a server up and running? If you don't, `dnscrypt-wrapper` will print the stamp during the setup, and you can also recover it later in `/opt/dnscrypt-proxy/etc/keys`.

If you are already running a server, you can use this little online tool to compute a stamp from the DNSCrypt or DoH parameters: https://stamp.dnscrypt.info/

**Comment by tuttimann** [comment]
I also want my server to be added to the public list.
Here are the parameters:
Name: 'lazarus-dns'
Stamp: 'sdns://AQECAAAAAAAADzUxLjE1LjQ3LjUxOjQ0MyCMu8TzuASiI5WYVogGZDV_GrNOMs3aLxosi9XlwbZqxhsyLmRuc2NyeXB0LWNlcnQubGF6YXJ1cy1kbnM'

**Comment by jedisct1** [comment]
@tuttimann Any description you want to add to that?

It can be anything. Your name, your website, where the resolver is and what it supports, etc :)

**Comment by tuttimann** [comment]
@jedisct Please add that it is managed by tuttimann and located in Netherlands. It supports DNSSEC and no logs are kept.

**Comment by jedisct1** [comment]
Ok!

By the way, the information about DNSSEC and no logs is included in the stamp. You should have checked these boxes :)

No biggie, I'm going to update the stamp for you.

Thanks a lot for maintaining that resolver! This will be useful!

**Comment by jedisct1** [comment]
Done! 

https://github.com/DNSCrypt/dnscrypt-resolvers/commit/f0834761d1a31306854902c5aebd69c2bd28e74c

**Comment by jedisct1** [comment]
Done! 

https://github.com/DNSCrypt/dnscrypt-resolvers/commit/f0834761d1a31306854902c5aebd69c2bd28e74c

**Comment by tuttimann** [comment]
Can I Check afterwards for DNSSEC and no logs?

**Comment by jedisct1** [comment]
Yes!

Just enter the new stamp `sdns://AQcAAAAAAAAADTE5NC4xMzIuMzIuMzIgxExWaqjWRsQysQT1PQCWGzLccc8cBL2esBPkgOekeCgcMi5kbnNjcnlwdC1jZXJ0LmlwcmVkYXRvci5zZQ` in the web form and you will see the boxes automatically checked (as well as all other parameters).

**Comment by tuttimann** [comment]
Ok. When I‘m checking my stamp the box „no logs“ isn‘t checked. What can I do to update my server‘s stamp?

**Comment by jedisct1** [comment]
Just check the box, and it will update stamp.

But I already computed an updated stamp for you, the one in the list (or in the message just above) is the updated one.

**Comment by jedisct1** [comment]
To clarify: you don't have to do anything on the server.

**Comment by Strykar** [comment]
My server is up and running, I used this package on Arch linux: https://aur.archlinux.org/packages/dnscrypt-proxy-go
I did not see the stamp printed during install and I cannot find the 'keys' file on my system, which I assume is the same 'Provider Public Key' stamp.dnscrypt.info wants. How else can I locate it?

**Comment by norrkin** [comment]
Probably because that is the client you've installed.

**Comment by Strykar** [comment]
@norrkin It's sourced from this repo. Are you suggesting there's no way now to get the info post-install? @jedisct1 Is a reinstall required?

**Comment by jedisct1** [comment]
@Strykar This repository is a client. With it, you can connect to public servers or to your own.

In order to install your own, you need a server implementation such as dnscrypt-wrapper, unbound or dnsdist, as well as a bunch of scripts for key management.

The easiest way to setup your own server is using the docker image, see https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes

**Comment by sergeevabc** [comment]
@tuttimann, what’s happened to your Lazarus DNS service?
``` [2018-03-27 19:45:34] [NOTICE] [lazarus-dns] TIMEOUT```
I am not aware if you have a status website akin to [this][1]. 

[1]: https://status.flatty.co/
