### ISSUE TITLE
Socks5 proxy directive is ignored

### ISSUE THREAD

**Issue by Kein** [DNSCrypt/dnscrypt-proxy#1161]
## *Who* is the bug affecting?
Me?

## *What* is affected by this bug?
DNS query transport

## *When* does this occur?
When resolving occurs

## *Where* does it happen?
Local machine I run dnscrypt-proxy on

## *How* do we replicate the issue?
force_tcp = false
proxy = "socks5://127.0.0.1:1080"

## Expected behavior (i.e. solution)
Queries routed through proxy

## Other Comments
I have shadowsocks proxy with UDP  relay enabled but DNscrypt completely ignores proxy directive.

**Comment by jedisct1** [comment]
The SOCKS protocol can only forward TCP.

Shadowsock's UDP relay requires local firewall rules to redirect specific UDP packets to a local server that transforms UDP into TCP. But this is unrelated to `dnscrypt-proxy`. If you are having issues with using that feature, the shadowsocks repository may be a better place to ask for help.

**Comment by Kein** [comment]
Really? That's weird, because specification says otherwise, here is wiki overview  
https://en.wikipedia.org/wiki/SOCKS#SOCKS5

Shadowsocks claims to be relaying UDP properly. My bittorrent tracker announce (UDP/uTP) seems to be working through it, what exactly prevents dnscrypt-proxy being able to send UDP requests through it?

**Comment by jedisct1** [comment]
Ah, interesting. I didn't know that, maybe because the main use case for SOCKS appears to be forwarding to Tor.

I'm probably not going to spend time on this since it seems to be an exotic scenario, but if you want to code to support this, I'd be glad to merge it. Thanks for your help!

**Comment by jedisct1** [comment]
Looks like the Go SOCK5 module supports this. So maybe all it takes is modify the first lines of the `exchangeWithUDPServer` function the same way as `exchangeWithTCPServer`, and remove `        proxy.mainProto = "tcp"` in `config.go`.

**Comment by Kein** [comment]
Sadly, not familiar with  GO much, otherwise I'd love to, my fren. It is not a big deal but if it is **up for grabs** may be you can then re-open the issue and add appropriate tag so someone else might get it done when they come across?

**Comment by Kein** [comment]
I tested 4d788aed85112472c77e5607c4e6a0b6a89c4ea2 without `proxy.mainProto = "tcp"` - no dice.
Firefox DNS forwarding works just fine with the same proxy, though.
