### ISSUE TITLE
Add an option to serve multiple files as sources for whitelists/blacklists

### ISSUE THREAD

**Issue by opensource-assist** [DNSCrypt/dnscrypt-proxy#1164]
For example, every file under the ```/etc/dnscrypt-proxy/blacklist.d/``` directory will be taken as a source for blacklists.

**Comment by jedisct1** [comment]
These are simple text files. So you can just concatenate them before starting the server.

Since you seem to be running some kind of Unix flavor, it can be done with the `cat` command:

```sh
cat /etc/dnscrypt-proxy/blacklist.d/*.txt > /etc/dnscrypt-proxy/blacklist.txt
exec dnscrypt-proxy ...
```

**Comment by opensource-assist** [comment]
@jedisct1 I know this method, but that would be nicer if dnscrypt-proxy would have native support for it.
