### ISSUE TITLE
Getting query_meta to send TXT records

### ISSUE THREAD

**Issue by eterry1388** [DNSCrypt/dnscrypt-proxy#1168]
## Subject

* [x] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description

Trying to use `query_meta`, but not seeing any TXT queries coming through on `dnsdist`.

I have this in my `toml` file:

```toml
query_meta = ["key1:value1", "key2:value2", "key3:value3"]
```

I have something along these lines in my `dnsdist.config`:

```lua
setLocal('0.0.0.0:5300')
setACL('0.0.0.0/0')

addDNSCryptBind('0.0.0.0:8443', 'name', '/etc/dnsdist/resolver.cert', '/etc/dnsdist/resolver.key')

newServer({ address = '8.8.8.8', name = 'Google 1' })

function run(dq)
  infolog("Got something")

  if (dq.qtype == DNSQType.TXT) then
    infolog("Got TXT record")
  end

  if (dq.qtype == DNSQType.A) then
    local domain = dq.qname:toString()
    infolog(domain)
  end
end

addAction(AllRule(), LuaAction(run))
```

I can see the A records come in as expected through `dnscrypt`. However, I'm not getting any other records, including TXT records that the documentation says should be added.

> These strings will be added as TXT records to queries.

Any help would be appreciated!

**Comment by eterry1388** [comment]
I also tried looking at `dq:getTrailingData()`, but it was a nil value.
https://dnsdist.org/reference/dq.html#DNSQuestion:getTrailingData

**Comment by eterry1388** [comment]
Upon looking more, it seems like `dnsdist` may not make it possible to look at the additional section of a dns question. Do you happen to know?

**Comment by jedisct1** [comment]
Unfortunately, I don't use `dnsdist`, so I can't really help here.

**Comment by jedisct1** [comment]
Saw Remi's answer. Apparently, this is not supported :(

**Comment by eterry1388** [comment]
It isn't supported by the PowerDNS Recursor either.
https://github.com/PowerDNS/pdns/issues/8759#issuecomment-586692829
