### ISSUE TITLE
Quad9 padding broken?

### ISSUE THREAD

**Issue by SerusDev** [DNSCrypt/dnscrypt-proxy#1169]
When working with quad9-dnscrypt-ip4-filter-pri it seems that the server rejects queries if they are big enough. Is it a known issue?
Attached a sample of traffic dump with 3 identical queries. 1 (324 bytes) and 2 (260 bytes) are OK. But 3 (452 bytes) was rejected. I can reproduce this issue.

[quad9.zip](https://github.com/DNSCrypt/dnscrypt-proxy/files/4128894/quad9.zip)

**Comment by jedisct1** [comment]
Maybe they reject packets larger than 512 bytes? This is not great.

As a workaround, you can add their resolvers to the `broken_query_padding` list in the configuration file. But this is definitely something worth reporting to them.

**Comment by SerusDev** [comment]
Thanks. I know about broken_query_padding option but I didn't think that Quad9 is broken.
Can someone please check this from another end? I would like to make sure that I am not missing something.

**Comment by SerusDev** [comment]
I have got a response from Quad9:

> We do not fully support dnscrypt padding at this time. We do not have an estimate on when that may be fully supported. If you would like to hasten our adoption of it, you could try submitting a feature request at https://github.com/PowerDNS/pdns/labels/dnsdist

Apparently, PowerDNS does not properly support dnscrypt padding.
I guess it makes sense to add Quad9 to the broken_query_padding list.

**Comment by jedisct1** [comment]
I don't think the issue is in `dnsdist`. Quad9 may be dropping fragmented UDP packets.

While this is useful for responses coming from authoritative serves, that sounds useless for client queries. And this is what prevents padded queries from going through.

**Comment by jedisct1** [comment]
I take it back. That was in `dnsdist`. It unfortunately took a bit of time to pinpoint the issue, but they fixed it minutes after I finally managed to report it to them.

It's a 2 lines fix, but it is going to drastically improve all DNSCrypt servers running `dnsdist`.
