### ISSUE TITLE
whitelists

### ISSUE THREAD

**Issue by CNMan** [DNSCrypt/dnscrypt-proxy#117]
for example:
blocking rules:`github.com`
cloaking rules:`api.github.com 192.30.255.116`

currently dnscrypt-proxy block all *.github.com including api.github.com.
i want to block main-domain but whitelist some sub-domian,how to config it?thanks

**Comment by jedisct1** [comment]
I don't think this is currently possible.

So, probably the best way to solve this and add some overall flexibility would be to add a whitelist set to the blocking rules, that would have a higher priority than other rules.

**Comment by Biggizen** [comment]
Whitelisting would be awsome!

**Comment by jedisct1** [comment]
+1

**Comment by jedisct1** [comment]
Duplicate of #198
