### ISSUE TITLE
Forwarding rules file syntax error with v2.0.37

### ISSUE THREAD

**Issue by Gedsh** [DNSCrypt/dnscrypt-proxy#1171]
## *Who* is the bug affecting?

Last version 2.0.37 on android with armv7a processor

## *What* is affected by this bug?

DNSCrypt is not working with forwarding rules activated.

## *When* does this occur?

During DNSCrypt startup.

## *Where* does it happen?

Android 6.0 armv7a

## *How* do we replicate the issue?

Start DNSCrypt with default forwarding rules file, default configuration, but activate forwarding rules.

## Other Comments

Log:
[NOTICE] dnscrypt-proxy 2.0.37
[NOTICE] Network connectivity detected
[NOTICE] Source [relays] loaded
[NOTICE] Source [public-resolvers] loaded
[NOTICE] Firefox workaround initialized
[NOTICE] Loading the set of forwarding rules from [forwarding-rules.txt]
[FATAL] Syntax error for a forwarding rule at line 1. Expected syntax: example.com: 9.9.9.9,8.8.8.8

Version 2.0.36 works fine.

**Comment by jedisct1** [comment]
Thanks!

Version 2.0.38 should fix this.

**Comment by Gedsh** [comment]
Fixed. Thank you!
