### ISSUE TITLE
Add new notracking list to domains-blacklist.conf

### ISSUE THREAD

**Issue by curiosityseeker** [DNSCrypt/dnscrypt-proxy#1174]
`domains-blacklist.conf` contains the following list:

```
# NoTracking's list - blocking ads, trackers and other online garbage
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt
```

However, as already mentioned in the [wiki](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Public-blacklists#notrackinghosts-blocklists) , [notracking](https://github.com/notracking/hosts-blocklists) now also maintains a special [list](https://github.com/notracking/hosts-blocklists/blob/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt) for dnscrypt-proxy that does not only contain the `domains.txt` list but also the entries of `hostnames.txt` list which are added as, e.g.

`=ic.wps.cn`

I suggest to replace above entry in the domains-blacklist.conf with the following one:

```
# NoTracking's list - blocking ads, trackers and other online garbage
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt
```

**Comment by Samillion** [comment]
Thank you. I didn't know they provided a list specifically for dnscrypt-proxy. Started using it now.

**Comment by jedisct1** [comment]
I think the current script is going to ignore lines starting with a `=` (which is usually a typo and not part of a real host name in all other lists).

I'll try to change this before updating that URL.

**Comment by curiosityseeker** [comment]
@jedisct1 : Thanks for considering this. I'd like to add that I made [reservations](https://github.com/notracking/hosts-blocklists/issues/223#issuecomment-581477698) in an issue on `notracking` (concerning a list for AdGuardHome) about the distinction between domains and hostnames which doesn't make much sense, IMO. So I rather suggest to use that new list in domains-blacklist.conf and adjust the script such that the `=` are simply removed at the beginning of the relevant lines instead of adding those lines as new entries in mybase.txt.

**Comment by notracking** [comment]
I will likely also remove the = chars (hostname specific blocks) from the dnscrypt list as soon as the adblock variant has proven to be stable

**Comment by curiosityseeker** [comment]
The leading `=` are now [removed](https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt)  so the script doesn't need to be modified.
