### ISSUE TITLE
How to block IP Address Ranges

### ISSUE THREAD

**Issue by S8D** [DNSCrypt/dnscrypt-proxy#1177]
How to block IP Address Ranges of Country with IP blacklist.txt
I want to block IP of China: https://lite.ip2location.com/china-ip-address-ranges
Thanks!

**Comment by jedisct1** [comment]
On Linux you can use `ipset`.

https://linoxide.com/linux-how-to/block-ips-country-ipset/
https://askubuntu.com/questions/868334/block-china-with-iptables

There are many other tutorials about this, search for `linux block country ip`.

But blocking a whole country for security is a very lame practice.
