### ISSUE TITLE
FATAL error, route queries not working properly

### ISSUE THREAD

**Issue by PeterDaveHello** [DNSCrypt/dnscrypt-proxy#1179]
## *Who* is the bug affecting?

Users

## *What* is affected by this bug?

dnscrypt-proxy can't start, or can't use route queries

## *When* does this occur?

when I uncomment: `## example.net 9.9.9.9,8.8.8.8,1.1.1.1` of `Route queries for specific domains to a dedicated set of servers`

## *Where* does it happen?

when I comment the config as example

## *How* do we replicate the issue?

Copy the example config and configure it as needed, remove the comment of the example setting of `Route queries for specific domains to a dedicated set of servers`, and then start dnscrypt-proxy, you'll get error message like this:

> [2020-02-05 18:53:48] [FATAL] Near line 247 (last key parsed ''): bare keys cannot contain '.'

## Expected behavior (i.e. solution)

It should route the query of example.com to server 9.9.9.9, instead of fatal error

## Other Comments

Thanks for the helps!

**Comment by jedisct1** [comment]
The comment explains the format of the dedicated file (`forwarding-rules.txt` in the example), not what should be in the main configuration file :)

I'm going to remove that comment since it looks confusing.

**Comment by PeterDaveHello** [comment]
Oh, thanks for that!
