### ISSUE TITLE
errno -9 on MIPSEL Asus RT-N66U

### ISSUE THREAD

**Issue by dcninja** [DNSCrypt/dnscrypt-proxy#118]
**Update 2**

Have gone back through previous releases, non of the standard MIPS package work dnscrypt-proxy-linux_mips-x-x-x.tar.gz etc

All of the mipsle versions give the same bind -9 error shown below.

**Update 1** 

Noticed the script "may" be grabbing the wrong binary, so grabbed this one.

https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.0/dnscrypt-proxy-linux_mipsle-2.0.0.tar.gz

Copied it over the one and ran, so I am getting further but unable to bind at this time.

`admin@RT-N66U-F830:/jffs/dnscrypt#` ./dnscrypt-proxy --config /jffs/dnscrypt/dnscrypt-proxy.toml

[2015-08-01 00:03:08] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2015-08-01 00:03:08] [NOTICE] dnscrypt-proxy 2.0.0
[2015-08-01 00:03:08] [FATAL] listen udp 127.0.0.1:65053: errno -9`

**Original**  

Hi

Following this guide for asus router: https://www.snbforums.com/threads/release-dnscrypt-installer-for-asuswrt.36071/page-34

For whatever reason the MIPSEL binary won't run on this platform, errors below, let me know if you need anything further from my console?

`admin@RT-N66U-F830:/jffs/dnscrypt# ./dnscrypt-proxy --config /jffs/dnscrypt/dnscrypt-proxy.toml

./dnscrypt-proxy: line 1: syntax error: unexpected "(" `

**Comment by jedisct1** [comment]
Indeed, this kind of behavior oftens means that the binary doesn't match the current architecture. Glad you eventually find the correct one!

I don't really get why you get that `errno -9` error, though. If you changed something besides the port number, can you try with the default example configuration file?

**Comment by jedisct1** [comment]
I think this explains it:

https://daenney.github.io/2017/04/22/monitoring-wifi-with-prometheus.html

Short version: you need a more recent kernel.

**Comment by jedisct1** [comment]
For a better reference: https://github.com/golang/go/wiki/MinimumRequirements#linux

**Comment by thuantran** [comment]
Thanks dcninja and Frank for the confirmation. I will remove the support for ASUS MIPS router out of my script then, unfortunately. Thanks for the confirmation.

**Comment by jedisct1** [comment]
Or can you add a check for the kernel version? Maybe these routers won't be running an obsolete kernel forever.

**Comment by thuantran** [comment]
Not gonna happen, it's Broadcom :D . In any case, there's a firmware dev on it on my side already so he might be able to backport the required kernel changes.
