### ISSUE TITLE
Anonymized Relays: anon-scaleway-ams

### ISSUE THREAD

**Issue by Samillion** [DNSCrypt/dnscrypt-proxy#1180]
In the [public anonymized relays page](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/relays.md) you list `anon-scaleway-ams` with a description that says "IPv6 only".

Right after it there is also a `anon-scaleway-ams-ipv6`, which from title and description say it's also IPv6 only.

Is `anon-scaleway-ams` IPv6 only or was it a typo?

**Comment by jedisct1** [comment]
Good catch!

`anon-scaleway-ams` is indeed the IPv4 version. Fixed, thanks!
