### ISSUE TITLE
2 instances running - different list of live servers ?

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#1182]
I have two instances running, one on a Synology and one on a Linux Mint.
When i start them both in the same minute the numbers of live servers they apply is completely different. 
For example the sysnology one gets around 80 live servers, the running on mint "only" around 40.
Both instances are using the **same** Require settings:

## Require servers (from static + remote sources) to satisfy specific properties
# Use servers reachable over IPv4
ipv4_servers = true
# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = false
# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true
# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true
## Require servers defined by remote sources to satisfy specific properties
# Server must support DNS security extensions (DNSSEC)
require_dnssec = false
# Server must not log user queries (declarative)
require_nolog = true
# Server must not enforce its own blacklist (for parental control, ads blocking...)
require_nofilter = true

And of course they have the same public-resolvers.md and the same fallback hosts (Quad 8 and Quad 9) and the timeoutsettings for both are the same. Both systems are connected to Internet via the same router, only difference the synology is connected by 1G, the mint system only with 100m, Internetspeed 100/40m DSL

on the mint system i can see much more TIMEOUTS than on the synology when the initial list of resolvers is built

**Comment by jedisct1** [comment]
You may be experiencing packet loss or congestion on the second system.

The initial test sends everything simultaneously to speed up the startup time, but this can indeed lead to servers not being picked up if the network is congested.

Retries can be added. This will make the startup slower, even though queries can be processed as soon as at least one server has been proven to be responsive.

**Comment by Samillion** [comment]
Apologies for the off-topic question, if you don't mind me asking, which Synology are you using?

I have an old DS212j, was wondering if it could handle Pi-Hole + DNSCrypt-Proxy.

**Comment by scubasunny** [comment]
> 
> 
> Apologies for the off-topic question, if you don't mind me asking, which Synology are you using?
> 
> I have an old DS212j, was wondering if it could handle Pi-Hole + DNSCrypt-Proxy.

I have a newer 218+ (with an Intel CPU - includes some cryptoacceleration).
I also tried this combination but dropped Pi-Hole as it's redundant to have two systems with caches and blocklist - ok configure whitelist entries is much easier in Pi-Hole when it comes to operation

**Comment by scubasunny** [comment]
@jedisct1 
I will check this and let you know.
How to get more retries, is this something i can configure

**Comment by scubasunny** [comment]
Seems to be an issue on hosting device not to be fast enough
