### ISSUE TITLE
dns server in USA with ipv6 (blocked normally)

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1186]
Hi,

I use dnscrypt proxy as well with windows 10.
I don't use ipv6 and i have disabled all ipv6 functions in windows and toml. I block ipv6 too in toml.

I've made a test with v.dnscrypt.uk-ipv4 and cs-ch servers.

I always have a usa dns too when i made the ipleak test, an ipv6 server.

I've try all i can. I've disabled fallback and netprobe...nothing change.

I always have more than the dnscrypt selected resolvers, a usa dns...

ipleak.net results:

![Annotation 2020-02-09 195020](https://user-images.githubusercontent.com/60618485/74108036-2f4cae00-4b76-11ea-9d28-f0554e76d10b.jpg)

dnsleaktest.com results:
![Annotation 2020-02-09 200914](https://user-images.githubusercontent.com/60618485/74108207-17762980-4b78-11ea-910d-dbe91499da27.jpg)

The usa ipv6 server appear only with ipleak.net

Using the only v.dnscrypt.uk-ipv4, the usa server is connected too.

Can you help to disabled this ipv6 usa dsn please?

*** This is some servers that seems linked to normal dns in usa. The London server is impacted.
When i try only cs-ch, all is nice.

I informe sometime there is a usa ipv6 server in the list without to be selected.

Thanks

regards

Samuel P

**Comment by jedisct1** [comment]
What this website prints is the IP address it received DNS queries from.

The DNS server can use any IP to connect to other servers. If it has multiple ones, it may not be the one you connected to. The fact that you, as a client, are using IPv6 or not is irrelevant.

The responses will be the same not matter if the server uses IPv4 or IPv6.

If you want to ignore IPv6 responses, set `block_ipv6 = true` in your configuration.

**Comment by ghost** [comment]
Thanks for answer.

I understand i can use this server ('v.dnscrypt.uk-ipv4') with the one more in usa (ipv6) without any issue for my encryption, ip and privacy.

I already use block_ipv6 = true in my configuration
