### ISSUE TITLE
Testers wanted for an additional blacklist

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#119]
https://zerodot1.github.io/CoinBlockerLists/ has interesting lists of domains and IP addresses of websites abusing browsers for crypto mining.

Looks like something worth adding to the `domains-blacklist.conf` file, possibly enabled by default and thus ending up in the `mybase.txt` file as well.

Adding new blacklists is always potentially dangerous if they contain false positives, blocking access to legitimate websites, though.

So, if you can, add these to your local dnscrypt-proxy blacklists, and tell me if they look good to add, or if they block legitimate websites you often visit.

**Comment by ghost** [comment]
Hey @jedisct1 :)

I've been using this for an hour after reading your post here, it does seem to block some legitimate domains.

The first list (titled "all domains") : https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt

It blocks several legitimate crypto websites such as:

**getmonero.org** (the official monero website) 

**bitpay.com** (crypto payment processor)

And some other legitimate websites:

I would stick with the "browser mining domains":

https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

Also, this Firefox addon works pretty well: https://addons.mozilla.org/en-US/firefox/addon/no-coin/

Maybe we can use their list: https://github.com/keraf/NoCoin/blob/master/src/blacklist.txt

**Comment by jedisct1** [comment]
Thanks a lot for testing these lists!

And it was worth it. The verdict for the first list is pretty clear :(

So, the browser mining domains list is reliable?

**Comment by ghost** [comment]
:)

Yes that one is definitely reliable! It stopped several miners for me and no broken domains!

**Comment by jedisct1** [comment]
Added, thanks again!

**Comment by ZeroDot1** [comment]
@jedisct1 https://twitter.com/hobbygrafix/status/962793272128233473
| Format | Description | URL |
| --- | --- | --- |
| List | This list contains all domains - A list for administrators to prevent mining in networks| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt) |
| List | This list contains all optional domains - An additional list for administrators| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_optional.txt) |
| List | This list contains all browser mining domains - A list to prevent browser mining only| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt) |
| Hosts | This list contains all domains - A hostslist for administrators to prevent mining in networks| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts) |
| Hosts | This list contains all optional domains - An additional hostslist for administrators| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_optional) |
| Hosts | This list contains all browser mining domains - A hostslist to prevent browser mining only| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser) |
| List | This list contains all IPs - A additional list for administrators to prevent mining in networks| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/MiningServerIPList.txt) |

**Comment by ghost** [comment]
I use 4 of @ZeroDot1 's CoinBloacker Lists, which I concatenate with several others (including dnscrypt.info/blacklists/domains/mybase.txt) to establish the day's domain and IP blacklists as I update them all every morning.

I have to use Rawgit links to download these 4 files:

Added to IP blacklist: https://rawgit.com/ZeroDot1/CoinBlockerLists/master/MiningServerIPList.txt
Added to Domain blacklist: https://rawgit.com/ZeroDot1/CoinBlockerLists/master/list.txt
Added to Domain blacklist: https://rawgit.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt
Added to Domain blacklist: https://rawgit.com/ZeroDot1/CoinBlockerLists/master/list_optional.txt

The DNSCrypt-ready IP and domain blacklists are checked for duplicate lines (and there are!) of course before being finalized. No issue.

**Comment by ZeroDot1** [comment]
@jedisct1 I added it to the readme. 
Thank you for using the CoinBlockerLists.

https://github.com/ZeroDot1/CoinBlockerLists#coinblockerlists-is-used-by-dnscrypt-proxy-httpsgithubcomjedisct1dnscrypt-proxy

**Comment by noblepirate** [comment]
@jedisct1 - that blacklist contains some clean addresses of mining pools i use (like *.hashvault.pro ), that is not acceptable!

**Comment by ghost** [comment]
I've just noted that two of the available ZeroDot1 CoinBlocker lists included `rawgit.com` which has strictly nothing to do with coin mining. Lack of confidence on reliability motivated as well by above comments leads me to stop adding all four CoinBlocker lists to my DNSCrypt-proxy blacklists.

**Comment by jedisct1** [comment]
So, even the "browser mining only" list is unreliable?

If even domains unrelated to cryptocurrencies are included, this is indeed a serious problem.

I appreciate the work made by @ZeroDot1 and these lists could have been very useful to prevent common threats, but with such false positives, I guess we have to disable them by default (so, remove them from mybase).

**Comment by ghost** [comment]
What triggered my abandon was that rawgit.com appeared (still appears at this time) on both
https://rawgit.com/ZeroDot1/CoinBlockerLists/master/list.txt
https://rawgit.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt
I did not find rawgit.com resolved IP in https://rawgit.com/ZeroDot1/CoinBlockerLists/master/MiningServerIPList.txt

Moreover, in the past (perhaps two weeks) I had noted and informed the developer of inconsistencies in his lists. Today, concerning rawgit.com, because if there is one domain which really has not, cannot have a relationship with coin mining it is that one, finalized a doubt of reliability concerning whatever of the four mentioned files. I know there's work behind and that is respectable, but I just don't have enough confidence.  

EDIT: I forgot to mention that I'm a bit surprised that @ZeroDot1 , as he mentions above, has added DNSCtypt-proxy in his readerme, as if there was either a consensus either a decision here as to his lists being added to mybase.txt. As far as I can read @jedisct1 hasn't yet decided.

**Comment by jedisct1** [comment]
I wouldn't trust the IP list, or IP lists in general. Avoiding false positives in IP lists is notoriously hard, especially now with applications running in the cloud, on ephemeral instances, on non-dedicated IPs. No single security vendor was ever able to do this correctly.

**Comment by ghost** [comment]
> I wouldn't trust the IP list, or IP lists in general.

Quite understandable. I do rely on several lists however but daily updated.
EDIT: some sites (seldom) have the nasty practice of calling 3rd-party sites (Facebook for instance when a user may have that domain blocked according to his preferences) with their IP which of course renders domain blacklists inoperative.

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/111

**Comment by Snapy** [comment]
@ameshkov Would you mind telling us what filters are used in AdGuard filters/DNS for blocking cryptominers? TIA

**Comment by ameshkov** [comment]
Here it is:
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/cryptominers.txt
