### ISSUE TITLE
dnscrypt proxy and Windows firewall

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1191]
Hi,

I use dnscrypt proxy (latest version) 64bits on Windows 10 and Windows 7.
I use it as well from maybe more than one year.

I just remember and verify, i 've never created any firewall entry and all is nice, with 7 too.

So i know the Windows firewall is...a little.... (how to say..?) curious and near magic (!!).

But is it normal?

All is up to date and not far from installation.

Thanks

Sam

**Comment by welwood08** [comment]
The default behaviour of the Windows firewall when there is no matching rule is to allow a connection if it is outgoing, or block it if it is incoming. So yes, it is normal and not magic when you run dnscrypt-proxy on the same machine that is making DNS requests for all the outgoing DNSCrypt connections to be allowed without special configuration.

**Comment by ghost** [comment]
Ok, thanks for answer.

I was speaking about "magic" because of on W10 some Windows entry enabled themselves instead you disabled them... Cortana and some app...

Samuel
