### ISSUE TITLE
Error when building dnscrypt-proxy

### ISSUE THREAD

**Issue by HxShard** [DNSCrypt/dnscrypt-proxy#1193]
Building Go framework
package github.com/jedisct1/dnscrypt-proxy: no Go files in /Users/hxshard/desktop/modrclub/dnscloak/platforms/ios/.build/src/github.com/jedisct1/dnscrypt-proxy
\# github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy
.build/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/local-doh.go:56:11: assignment mismatch: 1 variable but proxy.processIncomingQuery returns 2 values
.build/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/local-doh.go:56:40: not enough arguments in call to proxy.processIncomingQuery
	have (*ServerInfo, string, string, []byte, *net.Addr, nil, time.Time)
	want (*ServerInfo, string, string, []byte, *net.Addr, net.Conn, time.Time, int)
gomobile: -target=ios requires XCode

**Comment by HxShard** [comment]
Any ideas how to fix this? *when compiling from DNSCloak*

**Comment by jedisct1** [comment]
You'd better ask on the [dnscloak](https://github.com/s-s/dnscloak) project.
