### ISSUE TITLE
Measure RTT with a full dns query

### ISSUE THREAD

**Issue by AvverbioPronome** [DNSCrypt/dnscrypt-proxy#1199]
## Is your feature request related to a problem?

I have a simple and yet very bothering problem: if I do not specify a server_list and try to rely on public-resolvers.md, most of the time I get assigned the resolver from tiarap.jp, that pings extremely fast (cloudflare in front), but resolves extremely slow (I am in Europe, resolver is in Japan. It takes ~200ms)

## Describe the solution you'd like

I'd like to avoid measuring RTT to resolvers using ICMP pings, and making one full dns query for something random.

## Alternatives you've considered

An alternative that works is specifying a server_list

## Who will that feature be useful to?

Me, and users that want to use all resolvers on the list.

## What have you done already?

Nothing at all.

## What are you going to contribute?

I can do testing.

**Comment by jedisct1** [comment]
Hi,

Latency was never measured using ICMP pings, but by sending a full DNS query :)

The query is for the root zone, which is almost always cached, so it effectively measures the latency between the client and the resolver.

Maybe we can indeed send a query for a random name. From a DNS operator perspective, I'm not too fond of that, and the ability to quickly respond to nonexistent domain greatly depend on how DNS resolvers are configured and do not accurately reflect how they will resolve real traffic.

**Comment by AvverbioPronome** [comment]
Well, I guess it depends on if and where the http cache is. We probably need to avoid getting cached responses from http caches, while resolver caches are fine.

**Comment by jedisct1** [comment]
Maybe what we can do is add an pseudo-record to the EDNS section with some random data.
