### ISSUE TITLE
Enhacement - Launching dnscrypt-proxy.exe

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#12]
1) It would be nice to combine some commands of the system service control.
And make possible combinations:

`dnscrypt-proxy -service --install --start`
`dnscrypt-proxy -service --stop --uninstall`

Why?

• Much faster to troubleshoot and test
• Avoid troubles for the new users moving from v1

For example: If I will uninstall the service, it will be still active. Not too clear.
Next experiments may fail if you forgot stop the service.

2) Fix unnecessary (unclear) messages during executing dnscrypt-proxy commands

For example:

_dnscrypt-proxy -service stop_

```
[NOTICE] Starting dnscrypt-proxy 2.0.0beta4
[NOTICE] Service stopped
```

instead:

`[NOTICE] dnscrypt-proxy 2.0.0 beta 4 : Service stopped`

or

_dnscrypt-proxy -service install_

`[NOTICE] Starting dnscrypt-proxy 2.0.0beta4`

instead:

`[NOTICE] dnscrypt-proxy 2.0.0 beta 4 : Service installed`

... and so on

**Comment by jedisct1** [comment]
After 2.0.0 is done.
