### ISSUE TITLE
Some specified servers don't work at all (Google, geekdns-hk...)

### ISSUE THREAD

**Issue by JoshDaone** [DNSCrypt/dnscrypt-proxy#1204]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [x] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description

Hi there, running latest version of DNSCrypt-proxy on Windows 10 1909 x64, and my case is servers like Google and geekdns-hk never gets connected from day one, no socks5/http proxy configured. My config show as below:

```
server_names = ['cloudflare', 'google', 'nextdns', 'geekdns-doh-east', 'geekdns-hk', 'rubyfish-ea', 'rubyfish-uw'] 
//defined Google and geekdns-hk
...
# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = false

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = false

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true


## Require servers defined by remote sources to satisfy specific properties

# Server must support DNS security extensions (DNSSEC)
require_dnssec = false

# Server must not log user queries (declarative)
require_nolog = true

# Server must not enforce its own blacklist (for parental control, ads blocking...)
require_nofilter = false

# Server names to avoid even if they match all criteria
disabled_server_names = ['doh.li', 'brahma-world', 'aaflalo-me-nyc', 'doh-westus-pi-dns', 'aaflalo-me', 'dns.sb', 'cz.nic']
```
Loglevel set to debug and get no Google/geekdns record at all:

```
9160 [2020-02-25 20:45:45] [NOTICE] dnscrypt-proxy 2.0.39
9161 [2020-02-25 20:45:45] [NOTICE] Network connectivity detected
9162 [2020-02-25 20:45:45] [NOTICE] Source [public-resolvers] loaded
9163 [2020-02-25 20:45:45] [NOTICE] Source [relays] loaded
9164 [2020-02-25 20:45:45] [NOTICE] Firefox workaround initialized
9165 [2020-02-25 20:45:45] [NOTICE] Loading the set of blocking rules from [blacklist.txt]
9166 [2020-02-25 20:45:45] [NOTICE] Loading the set of forwarding rules from [forwarding-rules.txt]
9167 [2020-02-25 20:45:45] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
9168 [2020-02-25 20:45:45] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
9169 [2020-02-25 20:45:58] [INFO] [nextdns] TLS version: 304 - Protocol: h2 - Cipher suite: 4865
9170 [2020-02-25 20:45:58] [NOTICE] [nextdns] OK (DoH) - rtt: 428ms
9171 [2020-02-25 20:46:08] [INFO] [rubyfish-uw] TLS version: 303 - Protocol: h2 - Cipher suite: 49199
9172 [2020-02-25 20:46:08] [NOTICE] [rubyfish-uw] OK (DoH) - rtt: 17ms
9173 [2020-02-25 20:46:09] [INFO] [rubyfish-ea] TLS version: 303 - Protocol: h2 - Cipher suite: 49199
9174 [2020-02-25 20:46:09] [NOTICE] [rubyfish-ea] OK (DoH) - rtt: 13ms
9175 [2020-02-25 20:46:14] [INFO] [cloudflare] TLS version: 304 - Protocol: h2 - Cipher suite: 4865
9176 [2020-02-25 20:46:14] [NOTICE] [cloudflare] OK (DoH) - rtt: 147ms
9177 [2020-02-25 20:46:14] [NOTICE] Sorted latencies:
9178 [2020-02-25 20:46:14] [NOTICE] -    13ms rubyfish-ea
9179 [2020-02-25 20:46:14] [NOTICE] -    17ms rubyfish-uw
9180 [2020-02-25 20:46:14] [NOTICE] -   147ms cloudflare
9181 [2020-02-25 20:46:14] [NOTICE] -   428ms nextdns
9182 [2020-02-25 20:46:14] [NOTICE] Server with the lowest initial latency: rubyfish-ea (rtt: 13ms)
9183 [2020-02-25 20:46:14] [NOTICE] dnscrypt-proxy is ready - live servers: 4
```

And I tried to set the static record in the dnscrypt-proxy.toml like this, still the same problem:

```
  [static.'google']
  stamp = 'sdns://AgUAAAAAAAAABzguOC44LjigHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbkgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5'
```

**Comment by rampageX** [comment]
GeekDNS be DDOSed, just left: (https://www.233py.com/#dnsservice)

DoH: https://i.233py.com/dns-query

DoT: dns.233py.com

**Comment by JoshDaone** [comment]
> GeekDNS be DDOSed, just left: (https://www.233py.com/#dnsservice)
> 
> DoH: https://i.233py.com/dns-query
> 
> DoT: dns.233py.com

Thanks so much, that's nice to know now. And what's about Google in my case?

**Comment by rampageX** [comment]
Do you live in China? If yes, then this is normal...

In dnscrypt-proxy config you selected `Google` means use google 's DoH server `https://dns.google/dns-query`, but China block the `dns.google` domain with **DNS/TCP RST/SNI** lone time ago... 

If you really want use Google, set a working `proxy` or `http_proxy` in your config.

**Comment by JoshDaone** [comment]
> Do you live in China? If yes, then this is normal...
> 
> In dnscrypt-proxy config you selected `Google` means use google 's DoH server `https://dns.google/dns-query`, but China block the `dns.google` domain with **DNS/TCP RST/SNI** lone time ago...
> 
> If you really want use Google, set a working `proxy` or `http_proxy` in your config.

I see, configured the HTTP_PROXY works like a charm, thanks again!

One more question, if Proxy down and DNSCrypt fail to connect, what's the expected behavior for further dns request? I notice this in the config:

`fallback_resolvers = ['9.9.9.9:53', '8.8.8.8:53']`

Just want to confirm with this disconnect scenario, DNSCrypt will fallback to the servers in `fallbck_resolvers` and perform normal UDP 53 DNS query, am I right?

**Comment by rampageX** [comment]
http_proxy only work on DoH server, DNSCrypt will try other no DoH servers when proxy failed, and if all servers failed, DNSCrypt will fallback to the servers in `fallbck_resolvers`.

You can use non-standard port dns server to avoid dns hijack when this happen, like:

`fallback_resolvers = ['9.9.9.9:9953', '208.67.222.222:443']`

> QUAD9's:   9.9.9.9:9953
> Cisco(OpenDNS)'s:  208.67.222.222:443

**Comment by JoshDaone** [comment]
> http_proxy only work on DoH server, DNSCrypt will try other no DoH servers when proxy failed, and if all servers failed, DNSCrypt will fallback to the servers in `fallbck_resolvers`.
> 
> You can use non-standard port dns server to avoid dns hijack when this happen, like:
> 
> `fallback_resolvers = ['9.9.9.9:9953', '208.67.222.222:443']`
> 
> > QUAD9's:   9.9.9.9:9953
> > Cisco(OpenDNS)'s:  208.67.222.222:443

Appreciate it, now I can work with the config file more effectively.

**Comment by welwood08** [comment]
I feel a few of things should be clarified here. According to the initial configuration you posted above, your server list was being filtered in the following ways:
- `google` explicitly logs incoming queries and you set `require_nolog = true`.
- `geekdns-hk` uses the DNSCrypt protocol and you set `dnscrypt_servers = false`.

Configuring `google` with a static stamp means it is no longer subject to the filtering I just mentioned and hence began to work when you configured a proxy.

Regarding fallback resolvers, they are only used when `dnscrypt-proxy` itself needs to know an IP address. As stated in the comment in the example configuration:
> No user application queries will ever be leaked through these resolvers

**Comment by JoshDaone** [comment]
> I feel a few of things should be clarified here. According to the initial configuration you posted above, your server list was being filtered in the following ways:
> 
> * `google` explicitly logs incoming queries and you set `require_nolog = true`.
> * `geekdns-hk` uses the DNSCrypt protocol and you set `dnscrypt_servers = false`.
> 
> Configuring `google` with a static stamp means it is no longer subject to the filtering I just mentioned and hence began to work when you configured a proxy.
> 
> Regarding fallback resolvers, they are only used when `dnscrypt-proxy` itself needs to know an IP address. As stated in the comment in the example configuration:
> 
> > No user application queries will ever be leaked through these resolvers

@welwood08 thanks, that's make sense to me. As for google, I still have `require_nolog = true` in my config, and commented out # [static.'google'], only thing I did is set a HTTP_PROXY and now the google is working as expected. Seems like **Google still get configured** with `require_nolog = true` 

Here is the log output:

```
9479 [2020-02-26 12:19:14] [NOTICE] [google] OK (DoH) - rtt: 300ms
9480 [2020-02-26 12:19:14] [NOTICE] [cloudflare] OK (DoH) - rtt: 38ms
9481 [2020-02-26 12:19:14] [NOTICE] [rubyfish-ea] OK (DoH) - rtt: 12ms
9482 [2020-02-26 12:19:15] [NOTICE] [rubyfish-uw] OK (DoH) - rtt: 14ms
9483 [2020-02-26 12:19:16] [NOTICE] [nextdns] OK (DoH) - rtt: 236ms
9484 [2020-02-26 12:19:18] [NOTICE] Sorted latencies:
9485 [2020-02-26 12:19:18] [NOTICE] -    12ms rubyfish-ea
9486 [2020-02-26 12:19:18] [NOTICE] -    14ms rubyfish-uw
9487 [2020-02-26 12:19:18] [NOTICE] -    38ms cloudflare
9488 [2020-02-26 12:19:18] [NOTICE] -   150ms cisco
9489 [2020-02-26 12:19:18] [NOTICE] -   236ms nextdns
9490 [2020-02-26 12:19:18] [NOTICE] -   300ms google
9491 [2020-02-26 12:19:18] [NOTICE] Server with the lowest initial latency: rubyfish-ea (rtt: 12ms)
9492 [2020-02-26 12:19:18] [NOTICE] dnscrypt-proxy is ready - live servers: 6

```

**Comment by welwood08** [comment]
My apologies, I just checked the code that loads the server lists and discovered my mistake. When you set `server_names` then the `require_*` settings are ignored.
