### ISSUE TITLE
Firefox workaround needs to be configurable

### ISSUE THREAD

**Issue by aidanharris** [DNSCrypt/dnscrypt-proxy#1205]
If you want to use DOH (e.g you're using the built-in local DOH server) then the default blacklisting of `use-application-dns.net` breaks things. I'd suggest making this configurable like this:

```ini
[firefox-workaround]

## dnscrypt-proxy contains a workaround to disable DOH in Firefox.
## This is enabled by default, you do not need to modify this unless 
## you would like to disable this (for example you're using the built-in local DOH server).
# enabled = true
```

**Comment by jedisct1** [comment]
Maybe a better approach is to skip the Firefox workaround when a connection comes from the local DoH server.
