### ISSUE TITLE
Some games unable to download resource (BDO Steam)

### ISSUE THREAD

**Issue by sapphired18** [DNSCrypt/dnscrypt-proxy#1206]
## *Who* is the bug affecting?
Black Desert Online Steam Version

## *What* is affected by this bug?
unable to update the game

## *When* does this occur?
when opening the launcher

## *Where* does it happen?
Windows 10 2004

## *How* do we replicate the issue?

1. Open Steam
2. make sure dnscrypt is running 
3. run bdo launcher from steam
4. connection time out

## Expected behavior (i.e. solution)

bdo run nicely
solution: add app white/blacklist

## Other Comments
![image](https://user-images.githubusercontent.com/58063311/75312953-058dc980-588e-11ea-8caa-e16f7e648d7c.png)

**Comment by jedisct1** [comment]
Can you describe what exact DNS queries are sent by BDO, what responses you get using your ISP resolver, and how they differ from the one you get from another resolver?

**Comment by sapphired18** [comment]
sorry, I just uninstalled that game yesterday, I suggest you build whitelist for app

**Comment by sapphired18** [comment]
the ip that i got from resource monitor
118.98.95.99:80

**Comment by pc-v2** [comment]
Resolving [118.98.95.99]

Domain exists:  probably not, or blocked by the proxy
Canonical name: 118.98.95.99.
IP addresses:   118.98.95.99
TXT records:
Resolver IP:    180.241.233.26

**Comment by jedisct1** [comment]
What is needed is the actual query (what you get in the query log file).

But `180.241.233.26` is not a DNSCrypt or DoH resolver, it's your ISP resolver (PT Telkom Indonesia).

**Comment by sapphired18** [comment]
[2020-03-26 04:37:55]   ::1     dn.sea.playblackdesert.com      A       PASS    65ms    cleanbrowsing-adult
it's passing, but the patching is failed

trying ipv4 too, still same

**Comment by sapphired18** [comment]
tried, to whitelist the domain, still same

**Comment by sapphired18** [comment]
```
pc_v2 C:\..\win64 ❯❯❯ .\dnscrypt-proxy.exe -resolve dn.sea.playblackdesert.com
Resolving [dn.sea.playblackdesert.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: dn.sea.playblackdesert.com.edgesuite.net.
IP addresses:   118.98.95.115, 118.98.95.105
TXT records:
Resolver IP:    180.241.233.121
```

**Comment by sapphired18** [comment]
debug log from game folder
`[0304/104447:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0304/104452:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0304/104457:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0304/104502:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0304/104507:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0304/104512:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0304/104517:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0304/104522:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.`
