### ISSUE TITLE
Windows Defender is always show me :find antivirus!

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#1209]
Windows 10 x64 English 

Download dnscrypt-proxy x86 file,Windows Defender is always show me :It is a threat!

![Image 1](https://user-images.githubusercontent.com/17021524/75442687-f9436280-599a-11ea-8058-8edf9e830be2.png)

![Image 3](https://user-images.githubusercontent.com/17021524/75442704-fea0ad00-599a-11ea-9af8-ff82c667b3ec.png)

**Comment by jedisct1** [comment]
If you downloaded it from this repository, it is a false positive.
