### ISSUE TITLE
Raspberry pi support 

### ISSUE THREAD

**Issue by fir3drag0n** [DNSCrypt/dnscrypt-proxy#121]
Is there a binary for raspbian available?

**Comment by Sak94664** [comment]
You can directly build from source code.
just by run 
`go get github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy`
and the binary file should appear in (/home/user/go/bin)

or you can download arm architecture in github releases page.
:)

Edit:
I compiles it using go 1.9.2.
No problem occured.

**Comment by fir3drag0n** [comment]
If I want to install service, I cannot do this (cf. https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0):

```
pi@raspberrypi:~/dnsproxy/linux-arm $ sudo dnscrypt-proxy -service install
dnscrypt-proxy: invalid option -- 's'
dnscrypt-proxy 1.9.5

Compilation date: Nov  6 2017
Support for plugins: present
Plugins root directory: [/usr/local/lib/dnscrypt-proxy/]
Support for systemd socket activation: present
Support for the XChaCha20-Poly1305 cipher: present

Options:

  -R    --resolver-name=...
  -a    --local-address=...
  -d    --daemonize
  -E    --ephemeral-keys
  -K    --client-key=...
  -L    --resolvers-list=...
  -l    --logfile=...
  -m    --loglevel=...
  -p    --pidfile=...
  -X    --plugin=...
  -N    --provider-name=...
  -k    --provider-key=...
  -r    --resolver-address=...
  -S    --syslog
  -Z    --syslog-prefix=...
  -n    --max-active-requests=...
  -u    --user=...
  -t    --test=...
  -T    --tcp-only
  -e    --edns-payload-size=...
  -I    --ignore-timestamps
  -V    --version
  -h    --help

Please consult the dnscrypt-proxy(8) man page for details.
```

**Comment by norrkin** [comment]
You've installed the wrong version.

> dnscrypt-proxy 1.9.5

You can download dnscrypt-proxy v2 from here [https://github.com/jedisct1/dnscrypt-proxy/releases/latest](url)

**Comment by fir3drag0n** [comment]
I actually downloaded v2. In order to install v2, I tried to rename the install service file, but still no luck:

`
dnscrypt-proxy.toml  example-blacklist.txt       example-dnscrypt-proxy.toml   LICENSE
dnscrypt-proxy-v2    example-cloaking-rules.txt  example-forwarding-rules.txt

pi@raspberrypi:~/dnsproxy/linux-arm $ sudo dnscrypt-proxy-v2 -service install

sudo: dnscrypt-proxy-v2: command not found
pi@raspberrypi:~/dnsproxy/linux-arm $
`

**Comment by ajp2k13** [comment]
Try this one...
https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0

**Comment by fir3drag0n** [comment]
@ajp2k13: I tried the instruction you linked, but I got the problem mentioned  above.

**Comment by ajp2k13** [comment]
Just to be clear, the executable is called 'dnscrypt-proxy' and not 'dnscrypt-proxy-v2'...

**Comment by norrkin** [comment]
Do you already have 1.9.5 installed?  If so remove it.

**Comment by fir3drag0n** [comment]
Yes. How to safely remove the old dnscrypt?

**Comment by jedisct1** [comment]
```sh
sudo apt-get remove --purge dnscrypt-proxy
```

may work

**Comment by fir3drag0n** [comment]
I used this to install the old dnscrypt proxy:

```sh
mkdir -p dnsproxy
cd dnsproxy
wget https://launchpad.net/ubuntu/+archive/primary/+files/dnscrypt-proxy_1.9.5.orig.tar.gz
tar -xf LATEST.tar.bz2
cd dnscrypt-proxy[tab completion]
sudo ldconfig
./configure --with-systemd
make
sudo make install
```

If I try your command, he cannot find the package, it is also not listed if I do `dpkg-query -l` :-(

By using `sudo make uninstall` I was able to uninstall some parts of the old package.

Now, I get the following message:

```sh
pi@raspberrypi:~/dnsproxy/linux-arm $ sudo dnscrypt-proxy -service install

sudo: dnscrypt-proxy: command not found
```

**Comment by jedisct1** [comment]
Use `./dnscrypt-proxy` to run it if it's in the current directory and not where other executables are.

**Comment by fir3drag0n** [comment]
That works. How to install it globally because I always have to use ./dnscrypt-proxy ...

**Comment by ghost** [comment]
@fir3drag0n you could make a systemd file so it just starts every time.

https://github.com/jedisct1/dnscrypt-proxy/tree/master/systemd

Or if you just want to be able to call to be able to call it globally, there's several ways, one that comes to mind:

Open ~/.bashrc in text editor.

Add:

>export PATH=$PATH:/path/to/dnscrypt-proxy

**Comment by fir3drag0n** [comment]
That worked, thank you!  In order to include ipv6, what I have to fill in the socket file as listen stream/datagram? Something like "::2:port"?

**Comment by ghost** [comment]
Yes it would be:

ListenStream=[::]:53

53 being the port.

**Comment by fir3drag0n** [comment]
Why not [::2]:53 for instance?

**Comment by HI54U** [comment]
Can anyone help me to run the service with systemd please. I can't find the right configuration
It seems that I have the wrong directory here in the dnscrypt-proxy.service

```
Change this
ExecStart=/opt/dnscrypt-proxy/dnscrypt-proxy

changed it to
ExecStart=/home/pi/dnsproxy/dnscrypt-proxy

but can't get the service to start

Error:
sudo systemctl status -l dnscrypt-proxy\*
● dnscrypt-proxy.socket - dnscrypt-proxy listening socket
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy.socket; enabled; vendor preset: enabled)
   Active: failed (Result: service-start-limit-hit) since Sat 2018-02-17 08:38:20 CET; 29s ago
   Listen: 127.0.0.1:54 (Stream)
           127.0.0.1:54 (Datagram)

Feb 17 08:38:18 raspberrypi systemd[1]: dnscrypt-proxy.socket: TCP_NODELAY failed: Protocol not available
Feb 17 08:38:18 raspberrypi systemd[1]: Listening on dnscrypt-proxy listening socket.
Feb 17 08:38:20 raspberrypi systemd[1]: dnscrypt-proxy.socket: Unit entered failed state.

● dnscrypt-proxy.service - DNSCrypt client proxy
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-02-17 08:38:20 CET; 29s ago
     Docs: man:dnscrypt-proxy(8)
  Process: 860 ExecStart=/home/pi/dnsproxy/dnscrypt-proxy (code=exited, status=203/EXEC)
 Main PID: 860 (code=exited, status=203/EXEC)

Feb 17 08:38:19 raspberrypi systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=203/EXEC
Feb 17 08:38:19 raspberrypi systemd[1]: dnscrypt-proxy.service: Unit entered failed state.
Feb 17 08:38:19 raspberrypi systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
Feb 17 08:38:20 raspberrypi systemd[1]: dnscrypt-proxy.service: Service hold-off time over, scheduling restart.
Feb 17 08:38:20 raspberrypi systemd[1]: Stopped DNSCrypt client proxy.
Feb 17 08:38:20 raspberrypi systemd[1]: dnscrypt-proxy.service: Start request repeated too quickly.
Feb 17 08:38:20 raspberrypi systemd[1]: Failed to start DNSCrypt client proxy.
Feb 17 08:38:20 raspberrypi systemd[1]: dnscrypt-proxy.service: Unit entered failed state.
Feb 17 08:38:20 raspberrypi systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'

My systemd config look like this:

dnscrypt-proxy.service
`[Unit]
Description=DNSCrypt client proxy
Documentation=man:dnscrypt-proxy(8)
Requires=dnscrypt-proxy.socket
After=network.target
Before=nss-lookup.target
Wants=nss-lookup.target

[Install]
Also=dnscrypt-proxy.socket
WantedBy=multi-user.target

[Service]
Type=simple
NonBlocking=true

ExecStart=/home/pi/dnsproxy/dnscrypt-proxy

Restart=always`

dnscrypt-proxy.socket
`[Unit]
Description=dnscrypt-proxy listening socket

[Socket]
ListenStream=127.0.0.1:54
ListenDatagram=127.0.0.1:54
NoDelay=true
DeferAcceptSec=1

[Install]
WantedBy=sockets.target`

I activated the service with these commands:
sudo cp ./dnscrypt-proxy* /lib/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable dnscrypt-proxy.service
sudo systemctl start dnscrypt-proxy.service

and tested the service with:
sudo systemctl status -l dnscrypt-proxy\*
```

**Comment by ghost** [comment]
@fir3drag0n 

Apologies if my responses to you have already been addressed:

- `Linux/arm64` should work on any raspberry pi. If not, you can install `Go` and then build the binaries easily.

Regarding `systemd`, you should make sure you're able to run the service by itself. You should also provide log output from the actual service; not just the `systemd` unit errors. Chances are you're most likely not installing the service correctly; for example, your `ExecStart` is different than mine and I have no issues: `ExecStart=/opt/dnscrypt-proxy/dnscrypt-proxy -config /etc/dnscrypt-proxy.toml`

**Comment by fir3drag0n** [comment]
I just updated dnscrypt-proxy v2 to the newest version, but now I get the message

`pi@raspberrypi:~/dnsproxy/linux-arm $ sudo systemctl status -l dnscrypt-proxy
● dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2018-02-19 22:42:48 UTC; 6min ago
           └─ ConditionFileIsExecutable=/home/pi/dnsproxy/linux-arm/dnscrypt-proxy was not met
`

I cannot reinstall the service:

`
pi@raspberrypi:~/dnsproxy/linux-arm $ sudo dnscrypt-proxy -service install
sudo: dnscrypt-proxy: command not found
pi@raspberrypi:~/dnsproxy/linux-arm $
`

**Comment by jedisct1** [comment]
Maybe try

```sh
chmod +x /home/pi/dnsproxy/linux-arm/dnscrypt-proxy
```

**Comment by fir3drag0n** [comment]
does not work.

I get the message:

`
pi@raspberrypi:~ $ dnscrypt-proxy -service install
[2018-02-21 21:07:54] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2018-02-21 21:07:54] [NOTICE] dnscrypt-proxy 2.0.1
[2018-02-21 21:07:54] [FATAL] Failed to install DNSCrypt client proxy: open /etc/systemd/system/dnscrypt-proxy.service: permission denied

pi@raspberrypi:~ $ sudo dnscrypt-proxy -service install
sudo: dnscrypt-proxy: command not found
`

**Comment by jedisct1** [comment]
`sudo ./dnscrypt-proxy -service install` maybe?

**Comment by fir3drag0n** [comment]
okay, the service now works, but i cannot set ipv6 correctly as I don't know the structure for ipv6 for socket file. I tried "[::3]:54", but that does not work:

```
pi@raspberrypi:/etc/systemd/system $ sudo systemctl status -l dnscrypt-proxy@\*
● dnscrypt-proxy@dnscrypt.socket - dnscrypt-proxy listening socket
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy@dnscrypt.socket; enabled; vendor preset: enabled)
   Active: active (listening) since Wed 2018-02-21 21:14:50 UTC; 8min ago
   Listen: 127.0.0.1:54 (Stream)
           127.0.0.1:54 (Datagram)

Feb 21 21:14:50 raspberrypi systemd[1]: Listening on dnscrypt-proxy listening socket.

● dnscrypt-proxy@dnscrypt-ipv6.socket - dnscrypt-proxy listening socket
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy@dnscrypt-ipv6.socket; enabled; vendor preset: enabled)
   Active: failed (Result: resources)
   Listen: [::3]:54 (Stream)
           [::3]:54 (Datagram)

Feb 21 21:14:50 raspberrypi systemd[1]: dnscrypt-proxy@dnscrypt-ipv6.socket: Failed to listen on sockets: Cannot assign requeste
Feb 21 21:14:50 raspberrypi systemd[1]: Failed to listen on dnscrypt-proxy listening socket.
Feb 21 21:14:50 raspberrypi systemd[1]: dnscrypt-proxy@dnscrypt-ipv6.socket: Unit entered failed state.
Feb 21 21:20:40 raspberrypi systemd[1]: [/etc/systemd/system/dnscrypt-proxy@dnscrypt-ipv6.socket:5] Failed to parse address valu
Feb 21 21:20:40 raspberrypi systemd[1]: [/etc/systemd/system/dnscrypt-proxy@dnscrypt-ipv6.socket:6] Failed to parse address valu
Feb 21 21:20:40 raspberrypi systemd[1]: dnscrypt-proxy@dnscrypt-ipv6.socket: Unit lacks Listen setting. Refusing.
```

**Comment by jedisct1** [comment]
Why do you want an IPv6 local socket?

**Comment by fir3drag0n** [comment]
Because it is stated in the toml file? And I use ipv6 at the same time.

**Comment by jedisct1** [comment]
It's just an example, to show how to specify multiple IPs, and to explain that IPv6 addresses must be within brackets.

You don't need that. Nobody needs that (even Windows users even though they think they do).
