### ISSUE TITLE
How to... Cloaking-rules for VPN connection dns queries ?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1210]
Windows:

How to use cloaking-rules for vpn connection dns queries?
Maybe some guys will be interested if they use servers name instead of direct IP.

Thanks

Samuel P

**Comment by lessload** [comment]
for OpenVPN you can add  `dhcp-option DNS 127.0.0.1`  to *.opvn file all rule work for me.

**Comment by jedisct1** [comment]
Cloaking rules work the same way no matter how you connect to the Internet.
