### ISSUE TITLE
Is dnscrypt-proxy.socket deprecated ?

### ISSUE THREAD

**Issue by bphd** [DNSCrypt/dnscrypt-proxy#1211]
Because i can't get it to work

The classic:
```
systemd[1]: dnscrypt-proxy.socket: TCP_NODELAY failed: Protocol not available
systemd[1]: dnscrypt-proxy.socket: TCP_DEFER_ACCEPT failed: Protocol not available
systemd[1]: dnscrypt-proxy.socket: Failed with result 'service-start-limit-hit'.
```

**Comment by jedisct1** [comment]
It has been deprecated a long time ago.

**Comment by bphd** [comment]
So why it stills in the package if it don't work

**Comment by jedisct1** [comment]
Package?

**Comment by bphd** [comment]
Solution, software, program, latest version, master branch, whatever you want

Why it stills supported if it don't work

Why don't you just delete the option

**Comment by bphd** [comment]
Please reply me

The socket method still described in the Wiki of this project and on the Wiki of Arch. So why don't you delete this part of the Wiki and delete the method of the program? (And the socket method is the better because it's managed automatically by the system, like all others "system functions")

**Comment by jedisct1** [comment]
It's there, just completely untested and unsupported. The [wiki page](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/systemd) makes that pretty clear.

**Comment by bphd** [comment]
Not the Arch part on top of the page
________________________________
