### ISSUE TITLE
dnscrypt-proxy not detect real internet connection.

### ISSUE THREAD

**Issue by lessload** [DNSCrypt/dnscrypt-proxy#1212]
**Bug found in dnscrypt-proxy for windows.**
Found in specific case when you add loopback to interface too fast (faster than Microsoft NCSI detect internet) it will cause dnscrypt-proxy can not load public-resolvers `log: "System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolvers over tcp"` , becuase dnscrypt-proxy use or trust in [Microsoft NCSI](https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/network-connection-status-indicator-ncsi-showing/02664ddf-4eac-449a-8318-bdae1a5bad3d). some user will found this problem when start dnscrypt-proxy and add loopback before Microsoft NCSI detect internet (but have internet). 

**Loopback problem**
some time [Microsoft NCSI](https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/network-connection-status-indicator-ncsi-showing/02664ddf-4eac-449a-8318-bdae1a5bad3d) cannot detect internet while apply loopback to interface.

**To Fix It**
dnscrypt-proxy should test connection by itself like Microsoft NCSI do. or do something like this batch `powershell -Command "Invoke-WebRequest https://pastebin.com/raw/RH3GW47Q -OutFile '%Temp%\dnscrypt-check.txt' "`
`for /F "delims=:" %%I in (%Temp%\dnscrypt-check.txt) do (if /I "czd" == "%%I" (echo x > "%Temp%\dnscrypt-check.txt" && GoTo powershell) else (GoTo runSomething))
`

**Comment by lessload** [comment]
**To Test It**
- remove all `*.md` & `*.md.minisig` from `dnscrypt-proxy` directory
- run cmd as admin and run</br>`reg add "HKLM\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet" /v "PassivePollPeriod" /t REG_DWORD /d "120" /f` ( default value is `"5"` )
- connect your wifi and run `dnscrypt-proxy` immediately

as i try, dnscrypt-proxy will report as `"System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolver over tcp"` because [windows indicator still yellow](https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/network-connection-status-indicator-ncsi-showing/02664ddf-4eac-449a-8318-bdae1a5bad3d) but while windows indicator was yellow ,firefox work fine with internet.

UWP application have the same issue like dnscrypt-proxy, maybe because of language or function you compile with.

**Comment by jedisct1** [comment]
If `127.0.0.1` is the resolver, and `dnscrypt-proxy` doesn't have any configuration to start, the fallback resolver is used. This is expected and has nothing to do with Windows.

**Comment by lessload** [comment]
> 
> 
> If `127.0.0.1` is the resolver, and `dnscrypt-proxy` doesn't have any configuration to start, the fallback resolver is used. This is expected and has nothing to do with Windows.

127.0.0.1 not the resolver while i test. what i explain is when computer have internet but it got [yellow alert](https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/network-connection-status-indicator-ncsi-showing/02664ddf-4eac-449a-8318-bdae1a5bad3d) on wifi symbol  _dnscrypt-proxy_ will report as `"System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolver over tcp"` , _dnscrypt-proxy_ not found internet while _firefox_ was found. it hard to found this case because normal `PassivePollPeriod` just 5s. if you want to test it you need to extend `PassivePollPeriod` time.

**Comment by iWARR** [comment]
I've prepared the wiki material about NCSI on Windows and CMD file.
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Windows-NCSI

I beleive, most of the NCSI-relative questions should be resolved in the dnscrypt-proxy Git.
I'm using this config for many years and I'm sure it will be useful for many newcomers.

My English is far from perfect, so if anybody wants to improve my sentences or fix smth., feel free to make a necessary edits (w/o loosing details, of course).
