### ISSUE TITLE
DoB

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#1215]
Openwrt x64/Linksys wrt1900ac v1 installed openwrt 
Hope support DNS ON BLOCKCHAIN(DNS-over-HTTPS  Next Generation)

https://www.sohu.com/a/324710162_100191015
https://www.cnbeta.com/articles/tech/883113.htm

Thank you!

**Comment by lessload** [comment]
Cool Ideas.!
