### ISSUE TITLE
Move top-level keys into a table, like [main]

### ISSUE THREAD

**Issue by runapp** [DNSCrypt/dnscrypt-proxy#1219]
Cause both toml language and dnscrypt-proxy itself don't support configure file inclusion, when it comes to seperating default settings and local settings, the only way is to override defaults at the end. However, toml also forbids returning back to top level once a new table is created.
How about moving those keys into a `[top]` or `[main]` table? It's also very helpful if conf file inclusion is supported.

**Comment by jedisct1** [comment]
Awww, that would break everybody's configuration.

But why don't you add your own configuration *before* the default one instead of after?

**Comment by runapp** [comment]
@jedisct1 I've found that toml also doesn't allow duplicate keys. So no tricks at all.
Just maintain configurations by hand.
