### ISSUE TITLE
Help checking a couple of servers

### ISSUE THREAD

**Issue by ajp2k13** [DNSCrypt/dnscrypt-proxy#122]
I can't get a couple of server working, could someone else please check them so I know it's not just me?

dnscrypt.eu-dk
de.dnsmaschine.net

Thanks!

**Comment by jedisct1** [comment]
```
[2018-02-13 11:26:14] [NOTICE] [de.dnsmaschine.net] OK (crypto v2) - rtt: 14ms
[2018-02-13 11:26:14] [NOTICE] [dnscrypt.eu-dk] OK (crypto v1) - rtt: 37ms
```

work fine here.

**Comment by ajp2k13** [comment]
Thanks, that's what mine reports too but they don't resolve anything?

**Comment by jedisct1** [comment]
Indeed :( You should tell them.

**Comment by ajp2k13** [comment]
Thanks for checking! I've contacted dnscrypt.eu before but never get an answer back, sometimes it works for a while before it stops working again but I'm not sure my emails have anything to do with it. Not sure how to contact the owner of de.dnsmaschine.net...

**Comment by ajp2k13** [comment]
Thanks!

**Comment by ajp2k13** [comment]
@jedisct1 I got word from @bitbeans that it should be fixed now but it looks like it was removed from the list, could you add it back please? (de.dnsmaschine.net)

**Comment by jedisct1** [comment]
It's back!

Thanks!
