### ISSUE TITLE
dnscrypt-proxy.exe 2.0.39 detected as malware by multiple AVs on Windows

### ISSUE THREAD

**Issue by mishrashutosh** [DNSCrypt/dnscrypt-proxy#1220]
There are some big names like BitDefender, Emsisoft, Microsoft, etc that are detecting the executable as malware. Results on VirusTotal: https://www.virustotal.com/gui/file/29408fd1e56c6dd99a8c59e32725f0f847a973805355b6d11514afe65bcf3f0d/detection

**Comment by jedisct1** [comment]
If this is an actual binary downloaded from this project's repository, these are false positives.

Please report false positive to these vendors.
