### ISSUE TITLE
Windows internet icon "issue"

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1222]
Hi,

I use Windows 10 Pro x64 and latest dnscrypt-proxy version.

Connection is ethernet and static ip.

All is very stable and works well. So thanks for this tool.

I just inform you again there is an issue with the windows internet icon.

Sometime it appears there isn't any connection.

But near 98% of time, this is good.

Screenshots:

With visual "issue"
![Annotation 2020-03-11 114113](https://user-images.githubusercontent.com/60618485/76408848-e57e0000-638d-11ea-9d68-7eb10c418a67.jpg)

And without visual "issue"
![Annotation 2020-03-11 115003](https://user-images.githubusercontent.com/60618485/76409395-997f8b00-638e-11ea-85f9-e2d20c8e90be.jpg)

I have try all i can, but impossible to resolve for me.

During this visual "issue", dns queries continu to be resolved as well.

It will be very nice to fix it definitively.

Thanks

Samuel P

**Comment by jedisct1** [comment]
Sounds like the same issue: https://support.umbrella.com/hc/en-us/articles/230900948-Umbrella-Roaming-Client-Microsoft-Windows-Limited-Network-Connectivity-Warning-Yellow-Triangle-

I don't use Windows and I don't understand much about what the page says and what the icon is supposed to mean, but you do, so this document will probably help you :)
