### ISSUE TITLE
dnscrypt-proxy works only on port 53

### ISSUE THREAD

**Issue by brzeziniol** [DNSCrypt/dnscrypt-proxy#1224]
Hi everyone
First I would like to thank you for this wonderful piece of software. It really is amazing and helping in privacy protection.
To the point. Recently i installed dnscrypt-proxy and decided to change its default port from 53 ( line listen_addresses = ['127.0.0.1:53', '[::1]:53'] -> modified to listen_addresses = ['127.0.0.1:53000', '[::1]:53000'] Sadly i realized dnscrypt-proxy stopped resolving sites. I even found similar issue https://github.com/DNSCrypt/dnscrypt-proxy/issues/765 but changing to version 2.019 did not help. Currently I am on 2.039 
Installation was done with this tutorial 
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux
System is Ubuntu 18.04.4 LTS
Thanks in advance :)

**Comment by jedisct1** [comment]
`dnscrypt-proxy` can listen to any port, but Linux can only send DNS queries to port 53.
