### ISSUE TITLE
cloaked name returns 'WARNING: recursion requested but not available'

### ISSUE THREAD

**Issue by Sardonimous** [DNSCrypt/dnscrypt-proxy#1225]
Running dnscrypt-proxy 2.0.31 on raspberry pi.

Have a hostname in cloaking-rules.txt.

Querying the hostname notes (in dig)
;; WARNING: recursion requested but not available

nslookup skips to next DNS server:
;; Got recursion not available from 10.0.1.6, trying next server

This limits the usefulness of cloaking.  Is this the intended behavior?

Thanks.

**Comment by jedisct1** [comment]
Please try a current version, 2.0.31 is very old.
