### ISSUE TITLE
Android tethering listens to port 53

### ISSUE THREAD

**Issue by Sporif** [DNSCrypt/dnscrypt-proxy#123]
My phone starts a process (dnsmasq) that listens to 127.0.0.1:53 whenever tethering is enabled. This stops tethering from starting if dnscrypt-proxy is running and vice versa. So I made dnscrypt-proxy listen to some other random port. My question is which port is the best alternative, or does it not matter?

**Comment by jedisct1** [comment]
You can probably use any port, as long as you have firewall rules redirecting queries originally sent to port 53 to that port.

**Comment by Sporif** [comment]
Alright, thanks. :)
