### ISSUE TITLE
If dnscrypt-proxy is started before a SOCKS5 proxy becomes active, it doesn't work after that

### ISSUE THREAD

**Issue by phantomcraft** [DNSCrypt/dnscrypt-proxy#1231]
I wrote a script for connecting to a SSH proxy in my system, I perceived that if the dnscrypt-proxy is started with the SOCKS5 proxy inactive, even if enabling the proxy server after that, the program doesn't work.

Note: I disabled the network connectivity test:

_netprobe_timeout = 0_

Here is my config:

## =================================================
listen_addresses = ['172.16.0.2:10053', '[2001:db8::2]:10053']
max_clients = 2048
ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = true
doh_servers = true
require_dnssec = false
require_nolog = true
require_nofilter = true
disabled_server_names = []
force_tcp = true
proxy = "socks5://[2001:db8::2]:1080"
timeout = 25000
keepalive = 30
lb_strategy = 'random'
cert_refresh_delay = 240
tls_disable_session_tickets = true
fallback_resolver = '1.1.1.1:53'
ignore_system_dns = true
netprobe_timeout = 0
netprobe_address = "1.1.1.1:53"
log_files_max_size = 1
log_files_max_age = 1
log_files_max_backups = 1
block_ipv6 = false
cache = true
cache_size = 5120
cache_min_ttl = 600000
cache_max_ttl = 86400000
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

  [sources.quad9-resolvers]
  urls = ["https://www.quad9.net/quad9-resolvers.md"]
  minisign_key = "RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN"
  cache_file = "quad9-resolvers.md"
  refresh_delay = 72
  prefix = "quad9-"

  [sources.'opennic']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/opennic.md', 'https://download.dnscrypt.info/resolvers-list/v2/opennic.md']
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = 'opennic.md'

  [sources.'onion-services']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/onion-services.md', 'https://download.dnscrypt.info/resolvers-list/v2/onion-services.md']
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = 'onion-services.md'

**Comment by jedisct1** [comment]
Can you clarify what you mean by “doesn’t work”?

**Comment by phantomcraft** [comment]
It doesn't resolve any hostnames.
