### ISSUE TITLE
wiki example dnscrypt-proxy-resolvconf.service doesn't handle IPV6

### ISSUE THREAD

**Issue by Sardonimous** [DNSCrypt/dnscrypt-proxy#1232]
The example dnscrypt-proxy-resolvconf.service in the wiki is not handling IPV6 addresses well and ends with resolv.conf like this,

nameserver [2601

I came up with this which seems to do the trick:

ExecStart=/bin/sh -c 'systemctl show dnscrypt-proxy.socket \
                    | grep "Listen.*Datagram" \
                    | sed -e \'s/.*=//\' -e \'s/ .*//\' -e \'s/\[//\' -e \'s/\]//\' -e \'s/\(.*\):.*/nameserver \1/\' \
                    | /sbin/resolvconf -a lo.dnscrypt-proxy'

Not very elegant, I know....

**Comment by jedisct1** [comment]
Hi!

This is a Wiki, so feel free to update it as needed, especially regarding features that are completely unsupported.
