### ISSUE TITLE
Fallback DNS Shows Up When Checking for DNS Leaks

### ISSUE THREAD

**Issue by Kekerykek** [DNSCrypt/dnscrypt-proxy#1233]
## Subject

* [x] Other

## Description

Don't know if it's even a real issue but the secondary DNS (Fallback DNS from the toml file, 9.9.9.9 in this context) I set from adapter properties on Windows shows up on leak checkups.(https://www.dnsleaktest.com).

Is this a sign of leak? I mean it's not my ISP's DNS or anything.
![Inkedchrome lhsmAH2enj_LI](https://user-images.githubusercontent.com/38137210/76963263-d10fa980-6931-11ea-8321-95d51212caf2.jpg)

I've set things exactly as stated in the wiki.
![dllhost 6dSI7fJty6](https://user-images.githubusercontent.com/38137210/76962999-55156180-6931-11ea-89d0-41e9cb0688d4.png)

**Comment by welwood08** [comment]
I'm not sure why this recommendation was added to the wiki, but yes adding a non-encrypted DNS server to Windows' list of DNS servers will result in DNS leaks whenever Windows decides to query the non-encrypted server.

**Comment by jedisct1** [comment]
Yes, don't do that.

**Comment by Kekerykek** [comment]
So wiki is incorrect and I should just set the 127.0.0.1 on there?

**Comment by Bnwqo** [comment]
The 127.0.0.1 is the use of DNSCrypt. For alternative put an IP from one of the resolvers that use the DNSCrypt protocol.

**Comment by welwood08** [comment]
If you want to avoid leaking unencrypted DNS queries, you should not set any IP outside your local network in the Windows DNS server addresses. It is perfectly fine to leave the second address blank.

**Comment by Kekerykek** [comment]
Ok, got it. Someone should remove that line from the wiki then, as it's giving false information. Thanks for the help, lads.
