### ISSUE TITLE
Has any option can exclude some CDN domain names resolving?

### ISSUE THREAD

**Issue by fred214** [DNSCrypt/dnscrypt-proxy#1238]
When I use dnscrypt-proxy in windows10 and the dns server is openDNS
I found that some CDN domain names will be resolved as close as the DNS server，but it far away from me. It's too slow with some CDN domain names.

Has any option can exclude some domain names resolving?
Thanks a lot

**Comment by jedisct1** [comment]
You can use [forwarding](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Forwarding) to send queries for specific domains to your ISP resolver.

**Comment by fred214** [comment]
@jedisct1 Thanks for your answer and sorry for my carelessness with Wiki.
