### ISSUE TITLE
dnscrypt 2.0.40 armv6 raspberry p0wh

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#1240]
when I try to launch the command

`sudo ./dnscrypt-proxy -service install`

on p0wh raspberry arm

it gives me an error

`instruction not allowed`

pi@PiVpnPiHole:/opt/dnscrypt-proxy $ sudo ./dnscrypt-proxy -service install
instruction not allowed
pi@PiVpnPiHole:/opt/dnscrypt-proxy $ 

version 2.0.39 works

**Comment by incognico** [comment]
Same on PI Zero W, dnscrypt-proxy-linux_arm-2.0.40.tar.gz:

```
root@raspberrypi:/opt# linux-arm/dnscrypt-proxy --help
Illegal instruction
```

**Comment by jedisct1** [comment]
Does the version below work?

[dnscrypt-proxy-linux_arm-2.0.40.tar.gz](https://github.com/DNSCrypt/dnscrypt-proxy/files/4363307/dnscrypt-proxy-linux_arm-2.0.40.tar.gz)

**Comment by zitev** [comment]
...me too, "illegal instruction" on my router (asus rt-ac66u_b1 (amr7)), but i can't reinstall now, because i get an error message (tar: invalid magic error: *** unable to download dnscrypt-proxy package for your router)...

**Comment by incognico** [comment]
> Does the version below work?
> 
> [dnscrypt-proxy-linux_arm-2.0.40.tar.gz](https://github.com/DNSCrypt/dnscrypt-proxy/files/4363307/dnscrypt-proxy-linux_arm-2.0.40.tar.gz)

This one works for me.

**Comment by tigernero79** [comment]
> Does the version below work?
> 
> [dnscrypt-proxy-linux_arm-2.0.40.tar.gz](https://github.com/DNSCrypt/dnscrypt-proxy/files/4363307/dnscrypt-proxy-linux_arm-2.0.40.tar.gz)

I'm going to test it

**Comment by incognico** [comment]
> invalid magic error

This is probably because busybox tar can't handle newer versions of gnu tar files.

**Comment by zitev** [comment]
> > invalid magic error
> 
> This is probably because busybox tar can't handle newer versions of gnu tar files.

It worked well so far, now it's stupid...

**Comment by tigernero79** [comment]
@jedisct1 

https://github.com/DNSCrypt/dnscrypt-proxy/files/4363307/dnscrypt-proxy-linux_arm-2.0.40.tar.gz

tested and working thanks

**Comment by zitev** [comment]
> @jedisct1
> 
> https://github.com/DNSCrypt/dnscrypt-proxy/files/4363307/dnscrypt-proxy-linux_arm-2.0.40.tar.gz
> 
> tested and working thanks

Unfortunately, I'm still not good...

**Comment by jbaker6953** [comment]
The version here does not work either.

```
ROUTER:/sbin# md5sum dnscrypt-proxy
cb0c4b3d90c8d85e71d89f5a63afc42a  dnscrypt-proxy
ROUTER:/sbin# ./dnscrypt-proxy
Illegal instruction
```

**Comment by tigernero79** [comment]
have you recently updated the latest updated file which architecture do you have on your router?

**Comment by jbaker6953** [comment]
What do you mean by "latest updated file"? The firmware is only a month old. The architecture is 32-bit ARM. The OS is linux, kernel 2.6.36.4.

**Comment by tigernero79** [comment]
Try new release https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.40/dnscrypt-proxy-linux_arm-2.0.40.tar.gz

**Comment by jbaker6953** [comment]
That one works.

**Comment by jbaker6953** [comment]
My router has an BCM4709C0 CPU, which is ARMv7. Is there something that changed to make the default builds unable to run on ARMv7?

**Comment by rugabunda** [comment]
> Try new release https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.40/dnscrypt-proxy-linux_arm-2.0.40.tar.gz

"dnscrypt proxy is dead" 2.0.39 works

**Comment by rugabunda** [comment]
> Try new release https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.40/dnscrypt-proxy-linux_arm-2.0.40.tar.gz

This latest one works on AC68U! Jedi's under the comment yesterday did not though.

**Comment by jbaker6953** [comment]
I'm curious why ARM7 and ARM6 version of 2.0.41 do not run on an ARM7 CPU.

**Comment by jedisct1** [comment]
I have no idea :/

**Comment by tigernero79** [comment]
@jedisct1 sorry but the linux-arm version for which cpu is armv8 or armv5?  having you put armv6 and armv7 aside?

**Comment by tigernero79** [comment]
@jedisct1 However, I can confirm that the linux-armv6 package for raspberry p0w works perfectly

**Comment by jedisct1** [comment]
`linux-arm` is for armv5, but it should work on 6 and 7 as well.

If this is confusing, I'm going to remove the optimized versions and just keep the armv5 version.

**Comment by tigernero79** [comment]
@jedisct1 no, I'm glad to have optimized version for arm version, then I would tell you to write linux-armv5, but if you tell me that using linux armv5 or linux-armv6 or linux-armv7 does not change anything on a p0w or similar keep only one version, if instead it is optimized then it's okay just put word armv5

I love the optimized version if it is because it makes sense otherwise what optimization would it be?

**Comment by jbaker6953** [comment]
I don't think it's confusing. I just want to find if the bug is in go compiler or the BCM4709C0 CPU. Although people like me may download ARMv7 thinking it will work on their ARMv7 router and it'll segfault.
