### ISSUE TITLE
dnscrypt-proxy-linux_arm-2.0.40 segfault on start

### ISSUE THREAD

**Issue by jbaker6953** [DNSCrypt/dnscrypt-proxy#1241]
Using dnscrypt-proxy on an Asus RT-AC88U router with Asuswrt Merlin 384.15. dnscrypt-proxy has always worked through version 2.0.39. 2.0.40 segfaults immediately upon launch.

## *How* do we replicate the issue?
1. Download dnscrypt-proxy-linux_arm-2.0.40.tar.gz
2. Run dnscrypt-proxy.

## Expected behavior (i.e. solution)
Runs.

## Other Comments
Firmware is using 2.6.36.4brcmarm kernel. Could the new binaries be incompatible with this kernel?

**Comment by welwood08** [comment]
This sounds like it could be a duplicate of #1240 so you might want to try the version provided there until the next official release. If it's not that, please feel free to re-open and provide the actual segfault message you're seeing.
