### ISSUE TITLE
About new TLS client Feature

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1243]
Hi,

I use dnscrypt proxy as well on Windows.

With the latest version, there is a new feature about TLS client for Doh.

#   TLS Client Authentication                  #

[tls_client_auth]

creds = [
{ server_name='myserver', client_cert='client.crt', client_key='client.key' },
 ]

Can you explain how to use it?

Is "myserver" different of "example-server"?

Where are client.crt and client.key?

Is it only for the users they have a personnal dns server?

thanks

Samuel P

**Comment by jedisct1** [comment]
It's only if you run your own server.
