### ISSUE TITLE
Please, check whether 'anon-kama' is alive

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#1245]
I lost the connection suddenly.
Seems like it's `anon-kama` Anonymized DNS relay, because as soon as I disable relays in the toml, I've got the connection back.

The log report says smth. like that:
```
Unable to get a certificate for [scaleway-fr] via relay ... , retrying over a direct connection
...
dnscrypt-proxy is ready  - live servers: ...
```

Please, check `anon-kama` relay.

----------------------------------
Windows, dnscrypt-proxy v2.0.40

**Comment by jedisct1** [comment]
It's back :)
