### ISSUE TITLE
Name "NewPatternPatcher" looks like a typo

### ISSUE THREAD

**Issue by patterns** [DNSCrypt/dnscrypt-proxy#1248]
The file pattern_matcher.go has the instantiator name "NewPatternPatcher" which returns the reference to a new PatternMatcher. I think this is a typo. Is the desired name supposed to be "NewPatternMatcher"? It builds fine so making the name change means touching (3?) other files that invoke this function.
https://github.com/DNSCrypt/dnscrypt-proxy/blob/c39d66661bcb10615e7c0cafa323f2c9eddda3d9/dnscrypt-proxy/pattern_matcher.go#L33

**Comment by jedisct1** [comment]
Thanks!
