### ISSUE TITLE
Slice size includes the trailing asterisk (*)

### ISSUE THREAD

**Issue by patterns** [DNSCrypt/dnscrypt-proxy#1249]
In the switch case for the substring pattern (`*abc*`), the new slice is constructed by specifying the index (1) and size (Len -1). My understanding is that the intention is to trim both the leading and trailing asterisks. If this is correct, the size is one too many. To be correct, I think it is supposed to be `1 : [len - 2]`

https://github.com/DNSCrypt/dnscrypt-proxy/blob/c39d66661bcb10615e7c0cafa323f2c9eddda3d9/dnscrypt-proxy/pattern_matcher.go#L70

**Comment by patterns** [comment]
If these are valid issues, I would like to help make this change and the one in issue1248. These seem safe for a first ticket.

**Comment by jedisct1** [comment]
The second value of a slice is not the length, but the position of the end of the slice.

So the current code looks correct. With `-2`, it would chop the last character of the pattern, not the `*`.
