### ISSUE TITLE
dnscrypt-proxy servers and their logging promises

### ISSUE THREAD

**Issue by ChrisLane** [DNSCrypt/dnscrypt-proxy#125]
In DNSCrypt-Proxy v1, the public servers list contained information about whether the servers promise not to log queries etc.

Does a similar thing exist for DNSCrypt-Proxy v2 servers?

**Comment by ChrisLane** [comment]
Sorry, just found that this information is contained in the stamps.

**Comment by jedisct1** [comment]
This could be added to the individual descriptions as well.

But the configuration let you filter what kind of servers you like. And `dnscrypt-proxy -list` will print only those matching these criteria.
