### ISSUE TITLE
find a Trojan,download problem

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#1252]
dnscrypt-proxy-win32-2.0.41.zip,the file is downloaded failed,used VPN,TOR and so on.

![Image 1](https://user-images.githubusercontent.com/17021524/77591251-86da8980-6f2a-11ea-9f48-b4f7d563043f.png)

![Image 2](https://user-images.githubusercontent.com/17021524/77591269-8c37d400-6f2a-11ea-90c9-2a8082a29d2c.png)

![Image 4](https://user-images.githubusercontent.com/17021524/77591275-8f32c480-6f2a-11ea-8bb8-a2519245edfb.png)

![Image 5](https://user-images.githubusercontent.com/17021524/77591279-91951e80-6f2a-11ea-8880-e0952643311d.png)

**Comment by jedisct1** [comment]
This is a false positive. Report it to the vendor and use a more serious antivirus.
