### ISSUE TITLE
How to proxy to a standard local resolver?

### ISSUE THREAD

**Issue by deanishe** [DNSCrypt/dnscrypt-proxy#1257]
## Subject

* [x] Other

## Description

How do I tell dnscrypt-proxy to forward requests to a plain old DNS server running on localhost? No DNSCrypt, DoH or DoT. Just a regular DNS server.

I'd like to use dnscrypt-proxy on my DNS server (host) for its blocking capabilities in front of a resolving unbound server (accessible only on 127.0.0.1).

I've generated the stamp `sdns://AAAAAAAAAAAACTEyNy4wLjAuMQ` with `dnsstamp.py plain -a 127.0.0.1` using the Python implementation linked [here](https://dnscrypt.info/stamps-specifications). This should mean "plain old DNS at 127.0.0.1:53" but dnscrypt-proxy exits with the error `Stamp error for the static [unbound] definition: [Unsupported stamp version or protocol]`.

Have I missed something, or does dnscrypt-proxy not support forwarding to normal DNS servers?

Is there any way around this other than setting up a second DoH/DNSCrypt service on the server for dnscrypt-proxy to consume?

Alternatively, has dnscrypt-proxy's blocking feature been extracted to (or does it exist in) a separate, simpler program I could use?

**Comment by welwood08** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Forwarding

Unfortunately I don't think it's possible to have this forwarding as the default, you have to configure every domain you want to be forwarded. An alternative might be to set up a tunnel that uses one of the supported encryption protocols in front of your upstream unbound instance, but I know that's not ideal if it's local.

**Comment by deanishe** [comment]
So I'm right in thinking that dnscrypt-proxy doesn't support regular upstream servers, only more "exotic" ones?

> An alternative might be to set up a tunnel that uses one of the supported encryption protocols in front of your upstream unbound instance

Yeah. I figured that I could probably put another proxy in front of unbound, but that seems excessive, as there's already a DoT server in front of dnscrypt-proxy. Plus there's the significant overhead of DoH/DNSCrypt vs plain UDP DNS.

**Comment by welwood08** [comment]
To my knowledge, only encrypted upstreams are supported. I'm not sure there's much demand for just the blocking feature without the encryption, people who want that probably already know about things like pihole. Perhaps if you explained your use case more?

**Comment by deanishe** [comment]
> Perhaps if you explained your use case more?

I run my own DNS server on a VPS, so I have blocking and (some) privacy whether I'm at home or not.

It provides DNS via DoH and DoT to clients, has a resolving DNS server (not a forwarder) and a large blocklist in between. I'd like to use dnscrypt-proxy purely for its excellent blocking/whitelisting/forwarding capabilities, in between nginx  and unbound.

I'm aware of Pi-Hole (and AdGuard), but I'd prefer less consumer-focussed software that doesn't expect to manage its own configuration files.

My desired setup is currently excessively complicated to achieve because dnscrypt-proxy assumes it's responsible for ensuring security. It won't do DoH or DNS lookup without enforcing encryption. Which is kinda a PITA when you want to put it behind or in front of a "real" web or DNS server.

I understand that ensuring security is dnscrypt-proxy's raison d'être, but it's a shame that its other very powerful capabilities are inherently tied to that.
