### ISSUE TITLE
doh encryption

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1258]
Hi,

I use Windows 10 and dnscrypt-proxy 2.0.42 x64 as well.

I try doh and i need help to understand the encryption between those the app provide?

DoH: Use a specific cipher suite instead of the server preference
49199 = TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
49195 = TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
52392 = TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
52393 = TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
4865 = TLS_AES_128_GCM_SHA256
4867 = TLS_CHACHA20_POLY1305_SHA256

What is the stronger and recent encryption?

Thanks

SamuelP1111

**Comment by jedisct1** [comment]
The client will automatically pick the best option supported by the server.

In that list, they all have the same practical security level.
