### ISSUE TITLE
init.d-script does not work on busybox environments

### ISSUE THREAD

**Issue by the-w1nd** [DNSCrypt/dnscrypt-proxy#126]
Environments that use "busybox" (e.g. LEDE/OpenWRT) do not have the full implementation of "ps" available to check the status of the service through "ps \<PID\>" command.  So, the current function in file "/etc/init.d/dnscrypt-proxy" fails to stop the service:
```
is_running() {
    [ -f "$pid_file" ] && ps $(get_pid) > /dev/null 2>&1
}
```
A simple way to fix it would be to use "/proc" as:
```
is_running() {
    if [ -f "$pid_file" ]; then
        [ -f "/proc/$(get_pid)/cmdline" ] || { rm "$pid_file"; return 1; }
    else
        return 1
    fi
}
```

**Comment by jedisct1** [comment]
I'm confused. Where does that script come from?

**Comment by the-w1nd** [comment]
The script "/etc/init.d/dnscrypt-proxy" gets created whenever "dnscrypt-proxy -service install" is called.  I'm not sure what generates it, since I could not find it in the source code in this project. :-\

**Comment by the-w1nd** [comment]
To be honest, I actually ended up writing a completely new init.d-script for LEDE for simplicity and usability:
```
#!/bin/sh /etc/rc.common

START=50
EXTRA_COMMANDS="status"
EXTRA_HELP="        status  Check service status"

PROG="<FULL-PATH>/dnscrypt-proxy"

start() {
    SERVICE_DAEMONIZE=1 service_start "$PROG"
}

stop() {
    service_stop "$PROG"
}

reload() {
    restart
}

status() {
    if service_check "$PROG"; then
        echo "Running"
    else
        echo "Stopped"
    fi
}
```
On LEDE, there is no "nohup" installed by default, so the auto-generated init.d-script was just sending the process into background, but for some reason, the daemon would die after some random period of time.

**Comment by jedisct1** [comment]
Oh, I see!

This script is installed by the [services](https://github.com/kardianos/service) module.

Since you are more familiar with LEDE than I do, would like reporting this to them directly?
Or do you want me to do it?

**Comment by jedisct1** [comment]
`ps $pid` is quite unusual, though. Not sure that this is intended to be portable.

But doesn't busybox implement `pgrep`?

**Comment by jedisct1** [comment]
Or perhaps using `kill -0 ${pid}` could be an even more straightforward replacement.

**Comment by the-w1nd** [comment]
Thanks Frank!  I'll follow up with the "services" module.

Good call on the alternatives!  I did not check for "pgrep" (which is there) and never expected "kill" to be "process-friendly". :-)

Thanks a lot to everyone involved for a great rewrite of the original utility!
