### ISSUE TITLE
Invalid rule: [[fe80:53:*]] - wildcards can only be used as a suffix

### ISSUE THREAD

**Issue by kimw** [DNSCrypt/dnscrypt-proxy#1261]
## *Who* is the bug affecting?

dnscrypt-proxy 2.0.42

## *What* is affected by this bug?

Error message shows up at the time dnscrypt-proxy start up,

```
[ERROR] Invalid rule: [[fe80:53:*]] - wildcards can only be used as a suffix at line 12
```

With `ip-blacklist.txt` config file has configured as follow, (copied from `example-ip-blacklist.txt`)

```
163.5.1.4
94.46.118.*
[fe80:53:*]        # IPv6 prefix example
```

## *When* does this occur?

The dnscrypt-proxy start up.

## *How* do we replicate the issue?

1. Enable `ip-blacklist` feature
2. Start up dnscrypt-proxy

**Comment by jedisct1** [comment]
Can you try without the brackets (`[` `]`)?

**Comment by kimw** [comment]
@jedisct1 Yes, it works :) I'll change the `example-ip-blacklist.txt` & PR later. Thank you.
