### ISSUE TITLE
Dns Blacklist

### ISSUE THREAD

**Issue by bakunin1848** [DNSCrypt/dnscrypt-proxy#1262]
It has been several days since the update of the blacklist this error is returned to me with this address. (timeout)
Access from browser does not work either.

https://hosts-file.net/ad_servers.txt

Can anyone else confirm?

Perhaps it is no longer valid.

thanks

**Comment by Ainatar** [comment]
Say bye to hpHosts

https://forums.malwarebytes.com/topic/258056-hosts-filenet-domain-lists-are-broken-what-happened/

:-(

**Comment by jedisct1** [comment]
Sigh :(

Thanks for the heads up. It will be removed, then.
