### ISSUE TITLE
update script for rasberry pi 

### ISSUE THREAD

**Issue by blub4747** [DNSCrypt/dnscrypt-proxy#1263]
Hello community,

I am running dnscrypt-proxy on a  Raspberry Pi 2 Model B Rev 1.1 and have some problems with the update script.

could someone please give hand modifying it so it works?

Thx

`#! /bin/sh

INSTALL_DIR="/opt/dnscrypt-proxy"
LATEST_URL="https://api.github.com/repos/jedisct1/dnscrypt-proxy/releases/latest"
#PLATFORM="linux"
PLATFORM="linux_arm"
CPU_ARCH="x86_64"

Update() {
    workdir="$(mktemp -d)"
    curl -sL $(curl -sL "$LATEST_URL" |
        grep dnscrypt-proxy-${PLATFORM}_${CPU_ARCH}- | grep browser_download_url | head -1 | cut -d \" -f 4) |
        tar xz -C "$workdir" -f - ${PLATFORM}-${CPU_ARCH}/dnscrypt-proxy &&
        [ -x ${PLATFORM}-${CPU_ARCH}/dnscrypt-proxy ] &&
        mv -f "${INSTALL_DIR}/dnscrypt-proxy" "${INSTALL_DIR}/dnscrypt-proxy.old" || : &&
        mv -f "${workdir}/${PLATFORM}-${CPU_ARCH}/dnscrypt-proxy" "${INSTALL_DIR}/" &&
        cd "$INSTALL_DIR" && rm -fr "$workdir" &&
        ./dnscrypt-proxy -check && ./dnscrypt-proxy -service install 2>/dev/null || : &&
        ./dnscrypt-proxy -service restart || ./dnscrypt-proxy -service start
}

lversion=$("${INSTALL_DIR}/dnscrypt-proxy" -version)
rmersion=$(curl -sL "$LATEST_URL" | grep "tag_name" | head -1 | cut -d \" -f 4)
[ -z "$lversion" ] && exit 1
[ -z "$rmersion" ] && exit 1

echo locally installed
echo "$lversion"

echo remote git version
echo "$rmersion"

if [ "$rmersion" != "$lversion" ]; then
    echo "Updating" && Update
else
    echo "No Update Needed"
fi
`

**Comment by bakunin1848** [comment]
You say it's a PI.
You have tried changing the value of CPU_ARCH = "x86_64"
to CPU_ARCH = "arm"
or CPU_ARCH = "arm64" ?

**Comment by blub4747** [comment]
CPU_ARCH = "arm"
gives a 
./dnscrypt-proxy-update.sh: 23: ./dnscrypt-proxy-update.sh: /opt/dnscrypt-proxy/dnscrypt-proxy: Exec format error
and I get the error msg for 
CPU_ARCH = "arm64"

**Comment by bakunin1848** [comment]
You could try with variables of this type

ARCH=$(uname -m) as cpu architecture
SYSTEM=$(uname -s) as platform

**Comment by blub4747** [comment]
now this is very interesting or strange. for both command I get nothing as response.
Let me just dig through these details through one of them search engines.

**Comment by blub4747** [comment]
I just done a 

>  uname -a
Linux dnscrypt-pihole 4.19.49v6v7-aufs #1 SMP Tue Jun 11 15:13:27 CEST 2019 armv7l GNU/Linux
which told me that the architecture is armv7
I therefore modified the line accordingly to 

> CPU_ARCH="armv71"
however it still complains by telling me.

> ./dnscrypt-proxy-update.sh
./dnscrypt-proxy-update.sh: 23: ./dnscrypt-proxy-update.sh: /opt/dnscrypt-proxy/dnscrypt-proxy: Exec format error

**Comment by blub4747** [comment]
I just installed dnscrypt-proxy and the update script on a 
Raspberry Pi 3 Model B Plus Rev 1.3
and it all worked fine out of the box.
maybe this issue is specifically model related to the model 2 only.

thx anyway,

blub4747
