### ISSUE TITLE
dnscrypt-proxy causes some websites to return incorrect ssl certs

### ISSUE THREAD

**Issue by aqeelat** [DNSCrypt/dnscrypt-proxy#1267]
I noticed some websites returning incorrect SSL certs. However, they totally work fine when I remove 127.0.0.1 from my DNS servers list.

I only noticed it in https://whereby.com and https://mymasonportal.gmu.edu/

I use MacOS 10.15.3
And dnscrypt-proxy 2.0.42
The issue is browser-independent. I tested it by running
`echo ^d | openssl s_client -connect whereby.com:443`

**Comment by jedisct1** [comment]
What certificate do you get instead of the expected one?

**Comment by aqeelat** [comment]
[mymasonportal.pdf](https://github.com/DNSCrypt/dnscrypt-proxy/files/4446862/mymasonportal.pdf)
[whereby.pdf](https://github.com/DNSCrypt/dnscrypt-proxy/files/4446867/whereby.pdf)

**Comment by jedisct1** [comment]
Both are hosted on AWS with a constantly changing set of IP addresses. Masonportal just moved to it. So you may be getting older IP addresses.

If you bumped `cache_min_ttl` up, bring it back to the default value, or lower.

Try different servers.
