### ISSUE TITLE
Question about skip_incompatible = true

### ISSUE THREAD

**Issue by jumpsmm7** [DNSCrypt/dnscrypt-proxy#1268]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [x] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description

I am reaching out in-regards to **skip_incompatible = true** feature. I am trying to dispose of any questions i may have around this feature. Does this feature have an intelligent method of detecting an incompatible server, or is this relying on what it is "told" to be an incompatible server? What are the capabilities of this feature?

**Comment by jedisct1** [comment]
1500 bytes and 500 bytes test queries are sent. If 500 bytes queries get a response but 1500 bytes queries don't, it is very likely that they are running incompatible software. 

Having resolvers list in the `broken_implementations` makes them skip the test for faster startup.
