### ISSUE TITLE
Add option to sanity check toml config file

### ISSUE THREAD

**Issue by thuantran** [DNSCrypt/dnscrypt-proxy#127]
Hi Frank, as title stated, this feature is appreciated as I'm adding more features to my installation script for asuswrt-merlin. This would allow my script to catch anything wrong early.

**Comment by jedisct1** [comment]
Hi,

I think this has already been done in the developement code. So it will be in the next release :)

**Comment by thuantran** [comment]
Is it an option, that I can start for only checking the config file?

**Comment by jedisct1** [comment]
There isn't, but you can simply use `-list` to do so.

**Comment by thuantran** [comment]
I see, but I still wish there's an explicit option for that as the configuration now contains a lot of settings to change manually. Not all users will notice that hidden feature.

**Comment by jedisct1** [comment]
Maybe this is something you could add to the documentation? :)

**Comment by jedisct1** [comment]
Added.
