### ISSUE TITLE
A question about how the whitelist works, and how could work.

### ISSUE THREAD

**Issue by Ainatar** [DNSCrypt/dnscrypt-proxy#1270]
Hi. Lets say that looking at the blacklist log we have something like this:

```text
[2020-04-06 17:17:17]	127.0.0.1	this.is.a.not.so.baddomain.com	*.baddomain.com (alias for [nicedomain.com])
[2020-04-06 17:17:17]	127.0.0.1	this.is.a.baddomain.com	*.baddomain.com (alias for [nicedomain.com])
[2020-04-06 17:17:17]	127.0.0.1	this.is.a.veeery.baddomain.com	*.baddomain.com (alias for [nicedomain.com])
```

Lets say that because of one or more of that blocked domains, im losing functionality on the nicedomain.com.
This has two possible solutions, but none of them are perfect.

Solution 1: detele baddomain.com from the blacklist. This is not an option, thanks.
Solution 2: add nicedomain.com to the whitelist. This can be problematic, because there will not be blocking none of the subdomains under baddomain.com on nicedomain.com.

The thing is, is there any possibility to allow only one of the subdomains of the main baddomain.com to work on the nicedomain.com? Creating on the whitelist something like:

this.is.a.not.so.baddomain.com nicedomain.com

This way i could keep baddomain.com generally blocked for all, but allow only that specific subdomain for the nicedomain.com.

Thanks in advance.

**Comment by jedisct1** [comment]
Don't forget the `=` prefix, that does exact matching (subdomains will not match). Works with all lists.

**Comment by Ainatar** [comment]
> 
> 
> Don't forget the `=` prefix, that does exact matching (subdomains will not match). Works with all lists.

Thats nice to know, thanks. It can be useful under certain circunstances, but still is not the best option (in this particular case i was thinking about).

Imagine that i add to the blacklist "=baddomain.com", okay, now the subdomains are not blocked, and i need to manually add those i want to block. That, depending on the situation, can be a tough job. Imagine that under the "baddomain.com" there is only 1 good subdomain i need to have whitelisted, and 99 other subdomains i want to have blocked. This solution is not optimal, requires too much manual work.

It would be easier just to generally block "baddomain.com" with all its subdomains, and have the chance to just whitelist the subdomain you need from "baddomain.com", generally or specifically to be used for "nicedomain.com".

I dont know if its possible or not, thats why im asking. Maybe its not possible, or is too much work to be worth it.

**Comment by GrennKren** [comment]
Is this would not work?

inside whilelist
```
=this.is.a.not.so.baddomain.com
nicedomain.com
```
and now blacklist baddomain just leave it be
`baddomain.com`
