### ISSUE TITLE
multi instances or multi ports etc. for allocate domain to multi upstreams?

### ISSUE THREAD

**Issue by cc978** [DNSCrypt/dnscrypt-proxy#1271]
Now I have to run two or more dnscrypt-proxy instances as upstreams of dnsmasq, dnsmasq has a domain bypass/allocate mechanism with: 
`server=/github.com/DNS_A`
`server=/gitlab.com.com/DNS_B`
obviously, dnsmasq forward requests just by port and no supporting of cryption lookup, and I have not found the same bypass/allocate functions in dnscrypt-proxy, so I run two instances of dnscrypt proxy in two or more port for two upstreams dns server by different ports for forwarding to A or B dns, and config two ports and config to dnscrypt-proxy.

so, is it a formal usage of that purpose?? could dnscrypt-proxy run in two ports within one instance by two upstream config individually?

**Comment by jedisct1** [comment]
Should be fine, but if you have two configuration files, you need two instances. 

That shouldn't be a problem as long as each instance has its own log files.

**Comment by cc978** [comment]
is it a good idea to bypass dns requests to different upstreams that dnscrypt-proxy listens different ports just by one instance?
as a new function?
