### ISSUE TITLE
Official docker image (again)

### ISSUE THREAD

**Issue by Queuecumber** [DNSCrypt/dnscrypt-proxy#1274]
I'm a little unclear about how  #921 was resolved. Is there a plan to have an official docker image or are you redirecting people who want one to one of the community projects in an official capacity?

**Comment by jedisct1** [comment]
https://github.com/klutchell/dnscrypt-proxy looks good and is well maintained. It can probably be considered the official image.

**Comment by lucenera** [comment]
> https://github.com/klutchell/dnscrypt-proxy looks good and is well maintained. It can probably be considered the official image.

@jedisct1 Have you seen the code? If you confirm that it is good I can use it for ARM servers.
