### ISSUE TITLE
The blocklist python ends up blocking the pirate bay

### ISSUE THREAD

**Issue by Ph0rk0z** [DNSCrypt/dnscrypt-proxy#1275]
So I had been wondering why I can't reach thepiratebay.org and some other trackers off torrentz2, etc.

Turns out the dnscrypt blacklist generating python uses easylist/antisocial which includes FILTERS for stuff on piratebay. I tried to go through and can't actually find all the lists which are blocking... all I can do is whitelist the domain. 

So either we are blocking entire domains off a filter list or someone has poisoned the well.

also... a suggestion: add https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt from https://hostfiles.frogeye.fr/

this list blocks all those pesky CNAME hijackers

**Comment by jedisct1** [comment]
You can see what list a blocked domain comes from by looking at the comment above it.

Here, it seems to be blocked by that list:

```
########## Blacklist from https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt ##########
```

https://github.com/notracking/hosts-blocklists

/cc @notracking

**Comment by notracking** [comment]
Whitelisted ```thepiratebay.org``` (changes will be visible in a couple of hours..), any others that I should be aware of?

**Comment by jedisct1** [comment]
Wow, that was fast!

**Comment by jedisct1** [comment]
Geoffrey Frogeye's block list has been added.

**Comment by Ph0rk0z** [comment]
Wow! Awesome sauce. If I find any more I will post about it.
