### ISSUE TITLE
How to reset DNS cache? Issue with blocking.

### ISSUE THREAD

**Issue by ObeseChicken** [DNSCrypt/dnscrypt-proxy#1277]
I have DNSCP installed with a blocklist. I had blocked pbs.twimg.com by auto-downloading blocklists. This is the URL that hosts images on twitter if you do not know.

When I figured it out, I whitelisted twitter.com and twimg.com. I had tried to go to the subdomains. Also made sure they were not in the blocklist anymore and restarted the service.

dig on the domains still returned:

;; ANSWER SECTION:
pbs.twimg.com.		1	IN	HINFO	"This query has been locally blocked" "by dnscrypt-proxy"

;; Query time: 107 msec
;; SERVER: 127.0.2.1#53(127.0.2.1)
;; WHEN: Mon Apr 13 16:30:19 CDT 2020
;; MSG SIZE  rcvd: 108

Rebooting did not help nor restarting the service. I specifically whitelisted the domain but was still greeted with the block, just now its intermittant. 

How do I reset the cache? That must be what's doing it, right? I thought failed queries were only blocked for 60s?

**Comment by jedisct1** [comment]
The cache is not stored to disk, only in memory.

If you don't see a change after a restart, the response is cached by something else that you may have in front of the proxy.

**Comment by ObeseChicken** [comment]
Thanks, I long ago removed systemd-resolved, it was affecting both ping and chromium. Any other ideas?
