### ISSUE TITLE
Are the variable names for log files in example-dnscrypt-proxy.toml correct?

### ISSUE THREAD

**Issue by rr0ss0rr** [DNSCrypt/dnscrypt-proxy#1278]
In the example.toml, some logs are defined by "log_file" and some by "file" along with the log format "log_format" and "format".  Is this correct?
```
# log_file = 'dnscrypt-proxy.log'
# file = 'query.log'
# file = 'nx.log'
# log_file = 'blocked.log'
# log_file = 'ip-blocked.log'
# log_file = 'whitelisted.log'
```
Thanks

**Comment by jedisct1** [comment]
The `log_` prefix is not present when the property is in a section already dedicated to logging.
