### ISSUE TITLE
DoH server only response "dnscrypt-proxy local DoH server"

### ISSUE THREAD

**Issue by linkdesu** [DNSCrypt/dnscrypt-proxy#1279]
## Subject

* [x] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [x] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description

Hi, I just start running dnscrypt-proxy on my linode yesterday, everything works find except DoH server. After a lot tries, I found that my DoH server always return `dnscrypt-proxy local DoH server`. Here is the curl command I tested and its configuration, do I miss something important?

```shell
curl --insecure -H 'accept: application/dns-message' 'https://127.0.0.1:54/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB'
```

```
doh_servers = true
listen_addresses = ['0.0.0.0:54']
path = "/dns-query"
cert_file = "/root/localhost.pem"
cert_key_file = "/root/localhost.pem"
```

**Comment by jedisct1** [comment]
The local DoH server only supports `POST` queries, because this is what Firefox uses by default.

**Comment by jedisct1** [comment]
If you want to run an actual DoH server (not for local use) you may want to consider [doh-server](https://github.com/jedisct1/rust-doh) instead.

Or [`encrypted-dns-server`](https://github.com/jedisct1/encrypted-dns-server) for DNSCrypt (optionally with DoH).

**Comment by linkdesu** [comment]
> If you want to run an actual DoH server (not for local use) you may want to consider [doh-server](https://github.com/jedisct1/rust-doh) instead.
> 
> Or [`encrypted-dns-server`](https://github.com/jedisct1/encrypted-dns-server) for DNSCrypt (optionally with DoH).

@jedisct1 Thanks for your advice, [`encrypted-dns-server`](https://github.com/jedisct1/encrypted-dns-server) for DNSCrypt (optionally with DoH) is really a good choice!
