### ISSUE TITLE
DNSCrypt-Proxy-1 Unable To Retrieve Certificates Server If It Listening Address Is All Address (0.0.0.0 / ::0)

### ISSUE THREAD

**Issue by GaneJ** [DNSCrypt/dnscrypt-proxy#128]
Since you mention that DNSCrypt-Proxy-2 had the same feature with DNSCrypt-Proxy-1 (1.9.5), than in DNSCrypt-Proxy-1, it was unable to retrieve certificates server if it listening in All Address (0.0.0.0 / ::0) but able to retrieve certificates server if it listening in private address (127.0.0.1 / ::1). Both use the same server.
I just found out this problem recently.

Maybe in DNSCrypt-Proxy-2 the problem in DNSCrypt-Proxy-1 persist?

**Comment by GaneJ** [comment]
This is from DNSCrypt-Proxy-2 config:
> ## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6. To only use systemd activation sockets, use an empty set: []

Does that mean DNSCrypt-Proxy-2 for windows unable to listen to all address (0.0.0.0 / ::0)?

Update.....
Now I remember.
In old DNSCrypt-Proxy-1, I forgot in what version (1.7.x maybe?), DNSCrypt-Proxy-1 able to listen in all address (0.0.0.0 / ::0). I think it because you change something in 1.9.x (really really forgot about what).

**Comment by jedisct1** [comment]
You can have as many IP addresses to listen to as you like in the `listen_addresses` property. It has no implications on how certificates are being retrieved.

I don't remember how dnscrypt-proxy 1.x works, sorry.
