### ISSUE TITLE
Empty HINFO response

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-proxy#1285]
Can you add config for empty HINFO response? I want to hide which DNS server I use.

**plugin_block_ipv6.go:**
	`hinfo.Cpu = "AAAA queries have been locally blocked by dnscrypt-proxy"` >> `hinfo.Cpu = ""`
	`hinfo.Os = "Set block_ipv6 to false to disable this feature"` >> `hinfo.Os = ""`

**dnsutils.go:**
	`hinfo.Cpu = "This query has been locally blocked"` >> `hinfo.Cpu = ""`
	`hinfo.Os = "by dnscrypt-proxy"` >> `hinfo.Os = ""`

**Comment by black-cerberon** [comment]
Also, this way can bit increase speed.

**Comment by jedisct1** [comment]
This is very useful to understand that this is not the original response, and what caused the blocked. 

This is not going to change anything to speed, and using open source software is not a shame.

**Comment by black-cerberon** [comment]
@jedisct1, shame is not a reason. I just want to hide my blocking methods. 

Then may be use Refused instead HINFO for blocked IPv6 queries, like with blacklisted domains?

**Comment by jedisct1** [comment]
Unfortunately, sending a `refused` error code breaks many stub resolvers that send `AAAA` and `A` queries simultaneously, and assume that `A` responses cannot be obtained if they get a `refused` response for `AAAA`.
