### ISSUE TITLE
QNAME filter

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1287]
## Is your feature request related to a problem?
When choosing resolvers, you have the ability to require no logging, no filtering, and DNSSEC.
I was wondering if an additional requirement could be added: QNAME minimisation.

## Describe the solution you'd like
I would like a `require_qnamemin` filter in the dnscrypt-proxy.toml.

## Alternatives you've considered
There always is the possibility to manually review the resolvers list to see which ones offer QNAME minimisation and manually set them in `server_names`.

## Who will that feature be useful to?
This would benefit all users, as it would allow for more precise resolver filtering and enhanced privacy.

## What have you done already?
I tried searching for servers using QNAME minimisation, but it's often not indicated at all, making it difficult to know.

## What are you going to contribute?
I can document how QNAME minimisation works as well as its upsides and downsides.

**Comment by jedisct1** [comment]
This is probably too much granularity.

Most people don't know what QNAME minimization is, and the actual benefits it provides are anecdotal. 

That information can be added in resolvers description, but I don't think it is worth having a filter specifically for it.
