### ISSUE TITLE
Blacklist upstream change request

### ISSUE THREAD

**Issue by misaka00251** [DNSCrypt/dnscrypt-proxy#1288]
See StevenBlack/hosts#1094, I think the [blacklist](https://download.dnscrypt.info/blacklists/domains/mybase.txt) should change KADhost to the [without controversies](https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts_without_controversies.txt) one.

**Comment by jedisct1** [comment]
Thanks!
