### ISSUE TITLE
Failed to preset unit: File dnscrypt-proxy.service: Invalid argument

### ISSUE THREAD

**Issue by liang-hiwin** [DNSCrypt/dnscrypt-proxy#1289]
`root@iZwz9d1rjhrzzxa4lsoi93Z:~# systemctl status dnscrypt-proxy.service
● dnscrypt-proxy.service - DNSCrypt-proxy socket
   Loaded: error (Reason: Invalid argument)
   Active: failed (Result: exit-code) since Sun 2020-04-19 23:21:24 CST; 1h 2min ago
     Docs: https://github.com/jedisct1/dnscrypt-proxy/wiki
 Main PID: 4354 (code=exited, status=255)

Apr 20 00:08:24 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:7] Unknown section 'Socket'. Ignoring.
Apr 20 00:08:24 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:16] Missing '='.
Apr 20 00:08:24 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:7] Unknown section 'Socket'. Ignoring.
Apr 20 00:08:24 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:16] Missing '='.
Apr 20 00:14:19 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:7] Unknown section 'Socket'. Ignoring.
Apr 20 00:14:19 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:16] Missing '='.
Apr 20 00:14:19 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:7] Unknown section 'Socket'. Ignoring.
Apr 20 00:14:19 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:16] Missing '='.
Apr 20 00:14:19 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:7] Unknown section 'Socket'. Ignoring.
Apr 20 00:14:19 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: [/etc/systemd/system/dnscrypt-proxy.service:16] Missing '='.
`

**Comment by jedisct1** [comment]
The documentation to install it on linux is here: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux

There is no `Socket` section in what `dnscrypt-proxy` installs.
