### ISSUE TITLE
system service doesn't get installed

### ISSUE THREAD

**Issue by Biggizen** [DNSCrypt/dnscrypt-proxy#129]
Hello,

I'm trying to use dnscrypt-proxy v.2 on Windows 10 x64. Following this

https://github.com/jedisct1/dnscrypt-proxy/wiki/installation

instructions, I opened a console with elevated privileges and started the dnscrypt-proxy.exe. After that I changed my Windows-DNS-Settings to 127.0.0.1. Back in the console I typed in "dnscrypt-proxy -service install" and "dnscrypt-proxy -service start". I also tried the "service-install.bat". It shows the following:

N:\Programme\Netz\DNSCrypt-Proxy (p)>.\dnscrypt-proxy.exe -service install
N:\Programme\Netz\DNSCrypt-Proxy (p)>.\dnscrypt-proxy.exe -service start
""
Thank you for using dnscrypt-proxy! Hit [RETURN] to finish

The Problem: The service doesn't get installed! I cannot find it and the "service-uninstall.bat" also says, that it's not installed.

What could be the cause?

V.1 was running fine. Maybe something left behind from v.1 blocks v.2? I have deleted the Windows-service of v.1 with the "sc delete" command, but could it be, that there is something left from v.1 in the registry causing problems?

Please help, your program ist awesome, thank you very much!

EDIT: In my post above I have forgotten to copy the first line of the output of the "service-install.bat":

Es sind keine Einträge in der Liste. [my english translation: There are no entries in the list.]
N:\Programme\Netz\DNSCrypt-Proxy (p)>.\dnscrypt-proxy.exe -service install
N:\Programme\Netz\DNSCrypt-Proxy (p)>.\dnscrypt-proxy.exe -service start
""
Thank you for using dnscrypt-proxy! Hit [RETURN] to finish

**Comment by iWARR** [comment]
@Biggizen 

You have to check, if `*.txt` files (blocking rules, for example) really existing on the right places.
Especially, if you were set absolute pathes in config.

Check all necessary `*.txt` files and corresponding pathes on the disk and in the `*.toml`
Then uninstall and install with `*.bat` files.

**Comment by Biggizen** [comment]
Thank you for your answer, iWARR. Unfortunately it didn't help. In the folder 

N:\Programme\Netz\DNSCrypt-Proxy (p)

are the following files:

```
blacklist.txt
blocked.log
dnscrypt-proxy.exe
dnscrypt-proxy.log
dnscrypt-proxy.toml
example-blacklist.txt
example-cloaking-rules.txt
example-dnscrypt-proxy.toml
example-forwarding-rules.txt
ip-blacklist.txt
ip-blocked.log
LICENSE
nx.log
query.log
service-install.bat
service-restart.bat
service-uninstall.bat
```

And this is the toml-file:


```
##############################################
#                                            #
#        dnscrypt-proxy configuration        #
#                                            #
##############################################

## This is an example configuration file.
## You should adjust it to your needs, and save it as "dnscrypt-proxy.toml"
##
## Online documentation is available here: https://dnscrypt.info/doc



##################################
#         Global settings        #
##################################

## List of servers to use
## If this line is commented, all registered servers matching the require_* filters
## will be used
## The proxy will automatically pick the fastest, working servers from the list.

# server_names = ['scaleway-fr', 'google', 'yandex']


## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.
## To only use systemd activation sockets, use an empty set: []

listen_addresses = ['127.0.0.1:53', '[::1]:53']


## Maximum number of simultaneous client connections to accept

max_clients = 250


## Require servers (from static + remote sources) to satisfy specific properties

# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = true

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true


## Require servers defined by remote sources to satisfy specific properties

# Server must support DNS security extensions (DNSSEC)
require_dnssec = false

# Server must not log user queries (declarative)
require_nolog = true

# Server must not enforce its own blacklist (for parental control, ads blocking...)
require_nofilter = true



## Always use TCP to connect to upstream servers

force_tcp = false


## How long a DNS query will wait for a response, in milliseconds

timeout = 2500


## Load-balancing strategy: 'p2' (default), 'ph', 'fastest' or 'random'

lb_strategy = 'p2'


## Log level (0-6, default: 2 - 0 is very verbose, 6 only contains fatal errors)

log_level = 2


## log file for the application

log_file = 'N:\Programme\Netz\DNSCrypt-Proxy (p)\dnscrypt-proxy.log'


## Use the system logger (syslog on Unix, Event Log on Windows)

# use_syslog = true


## Delay, in minutes, after which certificates are reloaded

cert_refresh_delay = 240


## Fallback resolver
## This is a normal, non-encrypted DNS resolver, that will be only used
## for one-shot queries when retrieving the initial resolvers list, and
## only if the system DNS configuration doesn't work.
## No user application queries will ever be leaked through this resolver,
## and it will not be used after IP addresses of resolvers URLs have been found.
## It will never be used if lists have already been cached, and if stamps
## don't include host names without IP addresses.
## It will not be used if the configured system DNS works.
## A resolver supporting DNSSEC is recommended. This may become mandatory.

fallback_resolver = '9.9.9.9:53'


## Never try to use the system DNS settings; unconditionally use the
## fallback resolver.

ignore_system_dns = false



#########################
#        Filters        #
#########################

## Immediately respond to IPv6-related queries with an empty response
## This makes things faster when there is no IPv6 connectivity, but can
## also cause reliability issues with some stub resolvers. In
## particular, enabling this on macOS is not recommended.

block_ipv6 = false



##################################################################################
#        Route queries for specific domains to a dedicated set of servers        #
##################################################################################

## Example map entries (one entry per line):
## example.com 9.9.9.9
## example.net 9.9.9.9,8.8.8.8

# forwarding_rules = 'forwarding-rules.txt'



###############################
#        Cloaking rules       #
###############################

## Cloaking returns a predefined address for a specific name.
## In addition to acting as a HOSTS file, it can also return the IP address
## of a different name. It will also do CNAME flattening.
##
## Example map entries (one entry per line)
## example.com     10.1.1.1
## www.google.com  forcesafesearch.google.com

# cloaking_rules = 'cloaking-rules.txt'



###########################
#        DNS cache        #
###########################

## Enable a DNS cache to reduce latency and outgoing traffic

cache = true


## Cache size

cache_size = 256


## Minimum TTL for cached entries

cache_min_ttl = 600


## Maxmimum TTL for cached entries

cache_max_ttl = 86400


## TTL for negatively cached entries

cache_neg_ttl = 60



###############################
#        Query logging        #
###############################

## Log client queries to a file

[query_log]

  ## Path to the query log file (absolute, or relative to the same directory as the executable file)

  file = 'N:\Programme\Netz\DNSCrypt-Proxy (p)\query.log'


  ## Query log format (currently supported: tsv and ltsv)

  format = 'tsv'


  ## Do not log these query types, to reduce verbosity. Keep empty to log everything.

  # ignored_qtypes = ['DNSKEY', 'NS']



############################################
#        Suspicious queries logging        #
############################################

## Log queries for nonexistent zones
## These queries can reveal the presence of malware, broken/obsolete applications,
## and devices signaling their presence to 3rd parties.

[nx_log]

  ## Path to the query log file (absolute, or relative to the same directory as the executable file)

  file = 'N:\Programme\Netz\DNSCrypt-Proxy (p)\nx.log'


  ## Query log format (currently supported: tsv and ltsv)

  format = 'tsv'



######################################################
#        Pattern-based blocking (blacklists)        #
######################################################

## Blacklists are made of one pattern per line. Example of valid patterns:
##
##   example.com
##   *sex*
##   ads.*
##   ads*.example.*
##   ads*.example[0-9]*.com
##
## Example blacklist files can be found at https://download.dnscrypt.info/blacklists/
## A script to build blacklists from public feeds can be found in the
## `utils/generate-domains-blacklists` directory of the dnscrypt-proxy source code.

[blacklist]

  ## Path to the file of blocking rules (absolute, or relative to the same directory as the executable file)

  blacklist_file = 'N:\Programme\Netz\DNSCrypt-Proxy (p)\blacklist.txt'


  ## Optional path to a file logging blocked queries

  log_file = 'N:\Programme\Netz\DNSCrypt-Proxy (p)\blocked.log'


  ## Optional log format: tsv or ltsv (default: tsv)

  log_format = 'tsv'



###########################################################
#        Pattern-based IP blocking (IP blacklists)        #
###########################################################

## IP blacklists are made of one pattern per line. Example of valid patterns:
##
##   127.*
##   fe80:abcd:*
##   192.168.1.4

[ip_blacklist]

  ## Path to the file of blocking rules (absolute, or relative to the same directory as the executable file)

  blacklist_file = 'N:\Programme\Netz\DNSCrypt-Proxy (p)\ip-blacklist.txt'


  ## Optional path to a file logging blocked queries

  log_file = 'N:\Programme\Netz\DNSCrypt-Proxy (p)\ip-blocked.log'


  ## Optional log format: tsv or ltsv (default: tsv)

  log_format = 'tsv'



##########################################
#        Time access restrictions        #
##########################################

## One or more weekly schedules can be defined here.
## Patterns in the name-based blocklist can optionally be followed with @schedule_name
## to apply the pattern 'schedule_name' only when it matches a time range of that schedule.
##
## For example, the following rule in a blacklist file:
## *.youtube.* @time-to-sleep
## would block access to Youtube only during the days, and period of the days
## define by the 'time-to-sleep' schedule.
##
## {after='21:00', before= '7:00'} matches 0:00-7:00 and 21:00-0:00
## {after= '9:00', before='18:00'} matches 9:00-18:00

[schedules]

  # [schedules.'time-to-sleep']
  # mon = [{after='21:00', before='7:00'}]
  # tue = [{after='21:00', before='7:00'}]
  # wed = [{after='21:00', before='7:00'}]
  # thu = [{after='21:00', before='7:00'}]
  # fri = [{after='23:00', before='7:00'}]
  # sat = [{after='23:00', before='7:00'}]
  # sun = [{after='21:00', before='7:00'}]

  # [schedules.'work']
  # mon = [{after='9:00', before='18:00'}]
  # tue = [{after='9:00', before='18:00'}]
  # wed = [{after='9:00', before='18:00'}]
  # thu = [{after='9:00', before='18:00'}]
  # fri = [{after='9:00', before='17:00'}]



#########################
#        Servers        #
#########################

## Remote lists of available servers
## Multiple sources can be used simultaneously, but every source
## requires a dedicated cache file.
##
## Refer to the documentation for URLs of public sources.
##
## A prefix can be prepended to server names in order to
## avoid collisions if different sources share the same for
## different servers. In that case, names listed in `server_names`
## must include the prefixes.
##
## A cache file can be specified without a URL in order to maintain lists
## locally.

[sources]

  ## An example of a remote source

  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

  ## Another example source, with resolvers censoring some websites not approriate for children
  ## This is a subset of the `public-resolvers` list, so enabling both is useless

  #  [sources.'parental-control']
  #  url = 'https://download.dnscrypt.info/resolvers-list/v2/parental-control.md'
  #  cache_file = 'parental-control.md'
  #  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'



## Optional, local, static list of additional servers
## Mostly useful for testing your own servers.

[static]

  # [static.'google']
  # stamp = 'sdns://AgUAAAAAAAAAACDyXGrcc5eNecJ8nomJCJ-q6eCLTEn6bHic0hWGUwYQaA5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs'
```

Is there anything wrong?

**Comment by iWARR** [comment]
@Biggizen 

I don't like this:

`N:\Programme\Netz\DNSCrypt-Proxy (p)`

Try

`N:\Programme\Netz\dnscrypt-proxy\`

or

`C:\Program Files\dnscrypt-proxy\`

This kind of issue (`dnscrypt-proxy.exe` service doesn't exist in the Windows `Task Manager`, but present in the `Services`) may happen, if you have somehow wrong-connected files. This problem, in the most cases, relative to some wrong pathes. This all info I have for now....

Do you have `dnscrypt-proxy` in the `Services`?

**Comment by r13s** [comment]
@Biggizen Can you download `https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md` and `https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md.minisig` manually?

**Comment by iWARR** [comment]
In case you have all necessary files in the one root folder, try do not use absolute pathes. Edit and leave all pathes (for the rules, logs, etc.) in your *.toml as relative (by default). For example:

`blacklist_file = 'blacklist.txt'`

**Comment by iWARR** [comment]
`public-resolvers.md` - opens in the browser. You can create the file and copy-paste. This file have to be created automatically after successful connection through fallback resolver after first installation (or encrypted, as usual)

`public-resolvers.md.minisig` - must be created automatically after successful connection (no need to do anything with it absolutely)

**Comment by iWARR** [comment]
1) Do you have `dnscrypt-proxy` in the Windows `Services` ? (Run -> services.msc)
2) Do you have `dnscrypt-proxy` in the Windows `Task Manager` ? (Ctrl+Shift+Esc -> Processes)

**Comment by iWARR** [comment]
@jedisct1 

1) About my "Service ISSUES" experience: https://github.com/jedisct1/dnscrypt-proxy/issues/51#issuecomment-361252151

2) Also, look at first post:

> Es sind keine Einträge in der Liste. [my english translation: **There are no entries in the list.**]

As I said many times (issue #51, #93, etc.), `No items in the list` - is known strange error within your *.bat files on Windows.

-----------------

Two same problems in the one old issue #51. Good occasion to think about...

**Comment by Biggizen** [comment]
@bezdupel and iWARR
Thank you so much for your help! 

The manual download of _public-resolvers.md_ and _public-resolvers.md.minisig_ is the solution.

**Comment by Biggizen** [comment]
Oh noooo..... I made the mistake to change a running system...

Before I manually downloaded the md-files, I had tried iWARRs recommendation to copy the program files to "C:\Program Files\dnscrypt-proxy\". This didn't help. After that I tried the download of the md-files and hooray the service got installed and everything run fine. 

So I thought, now with the knowledge of the solution, I can delete the service again with "sc delete" (which was successfull), copy the files (inkluding the md-files) back to my old folder (N:\Programme\Netz\DNSCrypt-Proxy (p)), run the "dnscrypt-proxy.exe" within the console with elevated privileges and then run the "service-install.bat" to install the service again. 

But this time running the "dnscrypt-proxy.exe" was different in contrast to my attempt before my first post: Before my first post the following was shown, when I run the "dnscrypt-proxy.exe":

```
N:\Programme\Netz\DNSCrypt-Proxy (p)>dnscrypt-proxy.exe
N:\Programme\Netz\DNSCrypt-Proxy (p)>
```

But when I run it after the change of the folder, there was only the first line, not the second anymore. I don't know if this is good, bad or doesn't matter. Anyhow it was different behavior. Maybe for you this is indicative for the problem, that's why I go into this detail. 

Anyhow the problem was, that running the "service-install.bat" again didn't install the service. 

So I thought, that the solution has to be the combination of manually downloading the md-files + using the path "C:\Program Files\dnscrypt-proxy\". So I thought "No problem, then I'll just go back to "C:\Program Files\dnscrypt-proxy\", run the "dnscrypt-proxy.exe" and the "service-install.bat" and be happy, though this isn't my prefered folder."

But then the disillusion: Even though beeing back again in the "C:\Program Files\dnscrypt-proxy\" folder plus having the md-files - like I said, this had worked before -, now it doesn't work anymore! So I am back at the same point again, like I was before my first post.

Has anyone an idea, why it first worked and now doesn't do anymore, though it's the same situation?

I hope my report isn't written in a too confusing way...

EDIT: 
@iWARR 
1. I tried both absolute and relative pathes in the *.toml. 
2. No, dnscrypt-proxy neither is in Task Manager nor in Services.

EDIT 2:
@iWARR 
I think you meant, if "dnscrypt-proxy" is in the "Services"-tab of the Task Manager, right? Otherwise, if you meant, if it is in the "Processes"-tab of the Task Manager, then yes, there is the "dnscrypt-proxy.exe".

EDIT 3:
Does DNSCrypt need the Service "DNSCache" (which I have deaktivated, but I already tried, if the "dnscrypt-proxy"-service installs, when "DNSCache" runs - no it doesn't) or any other service/process/whatever running, which might be deactivated in my system?

**Comment by iWARR** [comment]
@Biggizen 

I recommend you start from the scratch.

1) Uninstall service with `*.bat` (no need any `sc delete` ever). 
    Delete all your DNSCrypt folders/installation files from all disks.

2) Reboot.

3) Start from scratch. Use short pathes for the root folder. This must work:

`N:\Programme\Netz\dnscrypt-proxy\`

(I think, there is a problem with `( )`. dnscrypt-proxy may still expect some problems using absolute pathes there and there... This is my real suggestion until today, sadly)

4) Use relative pathes in the *.toml . "Relative" - mean like this:

`blacklist_file = 'blacklist.txt'`

Check your settings carefully. Check Network adapter settings.

Install and enjoy. 
Running dnscrypt-proxy is not too complicated task.

**Comment by Biggizen** [comment]
I have already tried everything you mention. Maybe I'm doing something wrong with the network adapter settings? 

At the IPv4-settings I choose, that I get an IP-address automatically. Below that I manually type in the DNS-server "17.0.0.1". 

At the IPv6-settings I also choose, that I get an IP-address automatically. Below that I manually type in the DNS-server "::1".

At control panel/internet options/connection/lan setting I do NOT hook using an proxy server.

EDIT: But I think, even when this wouldn't be the correct settings, this would lead to a missing internet connectivity, but it should not prevent the service from installing.

EDIT 2: Maybe, for completeness, I should mention, that I use "G DATA Antivirus", "Commodo Internet Security" and "Privoxy" (a local proxy server), but I have already tried, if it makes a difference when they all are deactivated (including restart) - no it doesn't. None of them had been an problem with v.1 of dnscrypt-proxy either.

@iWARR 
regarding 

> Install and enjoy. Running dnscrypt-proxy is not too complicated task.

No, I'm not an idiot, I'm a computer scientist and had no problem with v.1 of dnscrypt-proxy.

**Comment by r13s** [comment]
@Biggizen Nobody says you're an idiot. Just make sure that the firewall and antivirus do not block `dnscrypt-proxy.exe` access to the Internet. Also try to install the service with the configured public DNS server. If successful, change the settings back to `127.0.0.1` and `::1`.

**Comment by iWARR** [comment]
@Biggizen  

"17.0.0.1"  ????

127.0.0.1

**Comment by r13s** [comment]
@iWARR I think it's just a typo.

**Comment by r13s** [comment]
@Biggizen Also try to comment out the `blacklist` and `IP blacklist` — perhaps access to `download.dnscrypt.info` or its IP is blocked somehow in these files.

**Comment by iWARR** [comment]
@Biggizen 

Turn on logs in all your chain: dnscrypt-proxy + G DATA Antivirus + Commodo Internet Security (suggest w/o installing Comodo antivirus?) + Privoxy

And search for problems. Your system is a "blackbox" for anybody here.

**P.S.** dnscrypt-proxy v1 have a completely different code (language) inside, it's like a different product with same "operational goals". Otherwise, we all here want v2 should have same stability. That because so many comparisons v2 to v1. (But we know that is not too correct).

So, v1 service installation your antiviruses may allow, v2 services - not.

**Comment by iWARR** [comment]
>  Service "DNSCache" (which I have deaktivated

I don't recommend turning this service off, because of (look at the head page):

**• DNS caching, to reduce latency and improve privacy**

You may ask author to be sure 100% if dnscrypt-proxy use standard system (OS Windows) `Dnscache` service or it using it's own (?) cache. I think, it use system cache, that because I leave it working. 

> any other service/process/whatever running

`dnscrypt-proxy.exe` have to appear in both places: Windows `Services` and Task Manager/`Processes`.
If you miss the last - you are in trouble.

**Comment by Biggizen** [comment]
"17.0.0.1" was a typo only in my post, yes ;-)

Service is running now. I deleted all dnscrypt registry entries, made some changes in the *.toml, etc. 

I don't know, what exactly solved the problem and I don't want to check this out by reversing my changes to do them step by step again to see, at what point it makes *click*. I don't want to risk, breaking it again :-/ 

The deaktivated service "dnscache" is the result of the past times, in which I blocked traffic with the hosts-file, because a very large hosts-file causes extreme(!) CPU load, when "dnscache" is active. After switching to dnscrypt-proxy with its black-list, I saw no need to reactivate "dnscache", because everyhing run fine without it. 

I have two other questions, if you are so kind to help me with them too: 

1. In my logfile of the blacklist, every block entry shows up doubled. Is this normal or could this be an indication, that my PC makes unnecessary double-connections, maybe caused by "loopings" through the chain of dnscrypt-proxy and privoxy (both listen on 127.0.0.1, but on different ports)? I tried to check this with wireshark, but its massive output was way to complicated to analyse for me. I'm no expert for network traffic - not yet anyway ;-)

2. What is the right DNS-entry for the router? With dnscrypt-proxy-v.1 I had chosen one specific DNS-server and entered its address in the router, but v.2 has the functionality to choose between different servers automatically, when I understand it right. So what must be entered in the DNS-field of the router? 

Thank you for your helpfulness and time!

**Comment by iWARR** [comment]
> do them step by step again

As I said before. Nice to see you have it working.

> blocked traffic with the hosts-file, because a very large hosts-file causes extreme(!) CPU load

• Very large hosts-file - very bad idea. Don't load your PC within garbage.
• DNS cache - good idea. I said why.
• dnscrypt-proxy blocking is a brilliant tech, that putting hosts -blocking method in the past (obsolete) almost at all. Learn and try to understand all amazing benefits of dnscrypt-proxy blocking with wildcads `*` and how it works. Then you will see that you don't need huge hosts -file, it will become very-very small, when you smartly move your main blocking domains in the dnscrypt-proxy. (I don't mean copy-paste! No!)

1. It's normal behavior. DNS works like a flow.
   I don't have Privoxy, so nothing to say.
   dnscrypt-proxy listen ports from `listen_addresses =` (and `fallback_resolver =` for 30 sec). Usually, this is Port:53. What kind of connection you are using - it's doesn't matter.
Correct network settings and Firewall rules are important, as well.

2. You can use only specific servers if you want. Set them in *.toml

`server_names = ['servername']`

```
[static]
  [static.'servername']
  stamp = 'sdns://'...'
```

You can choose servers you like from the `public-resolvers.md`
But `dnscrypt-resolvers.csv` servers list from v1 was more informative and complete.
Unfortunatelly, the link is now unavailable (or I don't know the new one).

Don't use Google or Cisco (OpenDNS) servers - they are huge spying.
Take into account geographical location (closer to you) and test their pings.

**Comment by Biggizen** [comment]
I have stoped using the hosts-file, when I found dnscrypt-proxy-v.1 and I know the wildcards.

Regarding my second question: I meant, what do I have to enter in the DNS-field of the router, when I want to use v.2's automatic choose between the servers?
