### ISSUE TITLE
generate-domains-blacklist.py creates empty file.  

### ISSUE THREAD

**Issue by marfazz22** [DNSCrypt/dnscrypt-proxy#1290]
Hello,

First and foremost, I would like to thank all contributors for their effort put into this great project. I will soon contribute to the project in one way or another. 

I ultimately decided to install `dnscrypt-proxy` and learn to configure it rather than using some third-party GUI based utility. I am interested in learning and having the option to customize in ways that GUIs don’t allow. Within the last few days, I am proud to say, I have successfully configured the server, and in the process, learned a significant amount. 

I have found 4 similar ‘closed’ issues, however, I am still unclear as to why my script is not executing properly.

**ISSUE:**

I am unable to populate `dnscrypt-blacklist-domains.txt` by executing the `generate-domains-blacklist.py` script. the `domain-blacklist.conf` used to generate the list and `domains-blacklist-local-additions.txt` (not sure if the second file is needed) files are in the same directory as the py script. The script was pasted on notepad from the repository and named exactly as is listed.

From power shell running as administrator I use the following command:

`./generate-domains-blacklist.py > dnscrypt-blacklist-domains.txt`. The script appears to run and creates `dnscrypt-blacklist-domains.txt` however, the file created is empty. What could be wrong? 

thanks in advance.

**Comment by GrennKren** [comment]
I dont know if this could help but I've changed the line 169 in `generate-domains-blacklist.py` on my computer from **exit(1)** into **continue** ..

The reason why because it's always break loop or exit the program if something happen like get response code 403 or anything else from one of source urls.

So this 1 line, can just skip the error and continue getting the content.

**Comment by jedisct1** [comment]
You can simply add the `-i` command-line option to ignore URLs that are failing.

Looks like Banbenek's list, in particular, now returns 403 except to paying customers.

**Comment by marfazz22** [comment]
Ok,

 I'll try those things and report back shortly. Thanks...

**Comment by marfazz22** [comment]
Looks like the issue MAY be with the python interpreter. I am looking into it. I'll report back.

**Comment by marfazz22** [comment]
I am still working on this....

**Comment by vladns** [comment]
Script execution is also interrupted if error 404 is received:
`Loading data from [file:domains-blacklist-local-additions.txt]
Loading data from [https://hosts-file.net/ad_servers.txt]
[https://hosts-file.net/ad_servers.txt] could not be loaded: HTTP Error 404: Not Found
`
The script does not work out errors like 403, 404 and apparently 503, etc. including timeouts. In fact, the script should continue to work.
`socket.timeout: The read operation timed out`

**Comment by jedisct1** [comment]
Some sources can indeed be unreliable or not respond any more.

There is `-i` command-line flag that you can add in order to ignore failures:

```text
  -i, --ignore-retrieval-failure
                        generate list even if some urls couldn't be retrieved
```

**Comment by vladns** [comment]
I use the following code (bash script, generate-domains-blacklist.sh):
```
#!/bin/sh

SHELL=/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin

/usr/bin/python3 /etc/dnscrypt-proxy/utils/generate-domains-blacklist.py > /tmp/dnscrypt-blacklist-domains.txt
size=$(wc -c < /tmp/dnscrypt-blacklist-domains.txt)
if [ $size -gt 0 ]; then
    mv -f /tmp/dnscrypt-blacklist-domains.txt /etc/dnscrypt-proxy/dnscrypt-blacklist-domains.txt
else echo "Файл dnscrypt-blacklist-domains.txt не имеет записей!"
fi
systemctl kill -s SIGHUP dnscrypt-proxy.service
```

Because through cron otherwise it cannot be started. Where to use this key here? After "/usr/bin/python3 -i ..." I added this key, got some kind of interactive line ">>>", with a suggestion to enter something.

**Comment by Marjorie-R** [comment]
The '-i', or you can use the more verbose '--ignore-retrieval-failure' parameter goes after generate-domains-blacklist.py.
So in my bash script (which is in /etc/cron.daily as I used sysvinit not systemd) the relevant line becomes:

python $DOM_MERGE_PY -i > $DOM_BLACKLIST.tmp

The full script looks like this:

```
#!/bin/sh

#  Fetch adblocking lists from remote locations, merge and optimize them, 
# to build a clean blacklist that can be used with dnscrypt-proxy.
#
# Then restarts dnscrypt-proxy to read in blacklist and refresh server
# access times.
#
# Put in one of /etc/cron.daily, /etc/cron.weekly, /etc/cron.monthly
# according to the frequency that you want it to be run
#
# Source, https://github.com/dnscrypt/dnscrypt-proxy/wiki/Public-blacklists
#
# Executable, input and output files are in working directory
#
# Input files are: 
# domains-blacklist.conf                :adblocking lists from various sources
# domains-whitelist.txt                 :our own list of domains not to block
# domains-blacklist-local-additions.txt :your own list of domains to block
# domains-time-restricted.txt           :your own time restrictions on domains

# Output file:
# Combo adblocking domains file to be read by dnscrypt-proxy
DOM_BLACKLIST=domains-blacklist.txt

# executable
DOM_MERGE_PY=generate-domains-blacklist.py
# working directory
DOM_DIR=/usr/share/dnscrypt-proxy

# Check we can find the executable
test -x $DOM_DIR/$DOM_MERGE_BIN || exit 0

# Change to running directory and remove tmp blacklist

cd $DOM_DIR
rm -f $DOM_DIR/$DOM_BLACKLIST.tmp

# Generate combo adblock domains list
python $DOM_MERGE_PY -i > $DOM_BLACKLIST.tmp 

STATUS=$?

if test $STATUS -eq 0
 then
# overwrite canonical blacklist file
 mv -f $DOM_DIR/$DOM_BLACKLIST.tmp $DOM_DIR/$DOM_BLACKLIST
 echo "Updated domains blacklist"

# Restart dnscrypt-proxy to read in new domain blacklist
service dnscrypt-proxy restart
 else
 echo "Failed to update domains blacklist"
fi 

cd $OLDPWD

exit
```
