### ISSUE TITLE
Energized Protection has been blocked by GitHub

### ISSUE THREAD

**Issue by bakunin1848** [DNSCrypt/dnscrypt-proxy#1293]
# Energized Ultimate
# https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/domains.txt

![imagen](https://user-images.githubusercontent.com/11910873/80194831-43ebfe80-861b-11ea-85b5-4e7f95345a6f.png)

I don't know if it's temporary or permanent. In case you think it is appropriate to disable it by default in the domain-blacklist.conf

greetings,

**Comment by jedisct1** [comment]
Yes, this is unfortunate. I didn't expect GItHub to do something like that :(

That list was never enabled in the default configuration, so it doesn't need to be disabled.

Energized's author has lists in his own account:

https://github.com/AdroitAdorKhan/EnergizedProtection

But has anyone reached out to him or discussed this in a more appropriate place to see where the lists will be moved to?

**Comment by bakunin1848** [comment]
So I had it enabled believing that it came by default with the blacklist file. I'm going to try to contact him to comment on it.

As it is not a dnscrypt-proxy problem, I close the issue.
