### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1296]
## *Who* is the bug affecting?
`main.(*ServersInfo).fetchDoHServerInfo(0xc4201343a0, 0xc420134318, 0xc420150045, 0xe, 0xc420321e20, 0x15, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:248 +0x1168
main.(*ServersInfo).fetchServerInfo(0xc4201343a0, 0xc420134318, 0xc420150045, 0xe, 0xc420321e20, 0x15, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:205 +0x192
main.(*ServersInfo).refreshServer(0xc4201343a0, 0xc420134318, 0xc420150045, 0xe, 0xc420321e20, 0x15, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:96 +0x1f0
main.(*ServersInfo).refresh(0xc4201343a0, 0xc420134318, 0x0, 0x0, 0xc4201b2210)
	github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:121 +0x19c
main.(*Proxy).StartProxy(0xc420134318)
	github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:153 +0x9f4
main.(*App).AppMain(0xc420134300, 0xc420134318)
	github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:100 +0x30
main.(*App).Start.func1(0xc420134300, 0xc420134318)
	github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:90 +0x35
created by main.(*App).Start
	github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:89 +0xe8`

## *What* is affected by this bug?
Starting up dnscrypt-proxy

## *When* does this occur?
using the command dnscrypt-proxy

## *Where* does it happen?
Installed DNS https://dnscrypt.info/stamps
Stamps on dnscrypt-proxy.toml with the follwing setup
`
listen_addresses = ['127.0.0.1:5350','[::1]:5350']
server_names = ['NextDNS-Custom']
require_dnssec = true
require_nofilter = false
cache = false

[static.'NextDNS-Custom']
  stamp = 'sdns://xxxx

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''`

After successful installation like to start the service and the error occurred 

Using the protocol DNS-over-http with my accountcode.dns.nextdns.io

## *How* do we replicate the issue?
Ubuntu 18+ version

**Comment by jedisct1** [comment]
The stack trace doesn’t make any sense with the code. What version is it?

**Comment by ghost** [comment]
It has been resolved.
