### ISSUE TITLE
generate-domains-blacklist.py ascii parse errors character not in range (python3)

### ISSUE THREAD

**Issue by LevantinLynx** [DNSCrypt/dnscrypt-proxy#1299]
Hello,

first of all thanks for the amazing software you are providing.
Took my quite a while to figure this one out. 

## *Who* is the bug affecting?
Everyone using python3 to run generate-domains-blacklist.py with the current domains-blacklist.conf
I know the file indicates that it should be run with python 2.7 but it's 2020 and i don't want to retroactively install almost/kinds deprecated software on my server(s).

## *Where* does it happen?
domains-blacklist.conf
https://github.com/DNSCrypt/dnscrypt-proxy/blob/c6b32e059072e736ff60a6fa10b7448988cdf51d/utils/generate-domains-blacklists/domains-blacklist.conf#L47 and https://github.com/DNSCrypt/dnscrypt-proxy/blob/c6b32e059072e736ff60a6fa10b7448988cdf51d/utils/generate-domains-blacklists/domains-blacklist.conf#L50
both contain a tick ´ and not a normal ' which throws a wrench in the ascii parser.

## Expected behavior (i.e. solution)
Example files should just run imho.
Change the ´ to ' or remove them all together will let everything run fine.

**Comment by jedisct1** [comment]
It is certainly not affecting everyone running python3.

Maybe this is happening when not using a UTF8 locale?
