### ISSUE TITLE
ISSUE - Blocking log empty (beta 4)

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#13]
My blocking log is completely empty now.
Reinstallation of dnscrypt-proxy or rebooting PC doesn't help. Seems like new option `logged_qtypes` doesn't matter too.

First time I install beta 4, some info was appeared in the log (one time). But it was very strange lines.
Same like in the previous ISSUE: https://github.com/jedisct1/dnscrypt-proxy/issues/7
But this time **only the 2-nd entry** from my list of "Blacklisted-Domains.txt" was applied.
Same-type outputs in the "Restricted.log" (I dont have this log, but it was smth. like that):

```
[2018-01-20 03:20:58]	127.0.0.1	.	*my-some-rule-2*
[2018-01-20 03:20:58]	127.0.0.1	.	*my-some-rule-2*
[2018-01-20 03:20:58]	127.0.0.1	.	*my-some-rule-2*
[2018-01-20 03:20:58]	127.0.0.1	.	*my-some-rule-2*
...
```
And dots` . ` instead of domain names `example.com`

Then, I can't make blocking to work any more. My log is always empty... :(

**Comment by jedisct1** [comment]
Can you provide a minimal example of a blocking rules file that triggers that behavior?

**Comment by jedisct1** [comment]
Is “*my-some-rule-2*” an actual rule?

**Comment by ghost** [comment]
@iWARR are you using a cache like dnsmasq?

Or are you blocking the same domains in your HOSTS file?

You use Windows right?

Maybe they are stuck in your DNS cache:

> ipconfig /displaydns >c:\dns_cache.txt

Are they in there?

If so, try:

> ipconfig /flushdns

**Comment by iWARR** [comment]
@jedisct1 

> Can you provide a minimal example of a blocking rules file that triggers that behavior?

Sorry, my friend. I can't do it, because I don't want this "BIG Vendor" read this message and make the blocking impossible in his product. (It is not MS). And this is not right place for such info... Hope, you understand. We have to struggle against this agressive behavior smart.

> Is “my-some-rule-2” an actual rule?

No. But it doesn't matter. I can say it looks exactly like this (2-nd one from my list):

`*abc.example-domain.*`

In my blocking list I have 300+ my **own, only custom** fast and smart rules with` * ` . The rules are very universal, and each one can block tens of annoing and spying domains. HOSTS-blocking sucks, it is in the past. HOSTS-blocking is not much helpful today, since we have dnscrypt-proxy. dnscrypt-proxy move us to the next level of protection methods.

@mastad0n 

>  are you using a cache like dnsmasq?

No.

> Or are you blocking the same domains in your HOSTS file?

Some crossing still may exist. But I see that only one domain was blocked many times (2-nd rule from the list). As usual, I'm expecting to see tens of blocked domains (in real life) from hundreds possible (potentially) in short time of testing.

> 
May be they are stuck in your DNS cache

I don't thik so. Again, I see that **only 2-nd rule works** (from 300+) and corresponding domain was blocked. In the v1.9.5 the same blocking list file has worked perfectly.

**Comment by jedisct1** [comment]
Having a way to reproduce the issue would really be useful.

And the constant queries you get for the root zone means that you have a caching, validating resolver somewhere in the chain.

Sorry, I can't help with more details.

**Comment by iWARR** [comment]
Now I have explanation for this:

> Then, I can't make blocking to work any more. My log is always empty... :(

My log was empty, because:

• I had to wait more time until I could see that my 2-nd rule `*abc.example-domain.*` will be catched in my log. 
• Unfortunatelly we have a bug, when only 2-nd rule works, but all others - doesn't.

**Comment by jedisct1** [comment]
New beta is out.
