### ISSUE TITLE
DSNCrypt-Proxy blocked by macOS Gatekeeper 

### ISSUE THREAD

**Issue by mihscr** [DNSCrypt/dnscrypt-proxy#1300]
## *Who* is the bug affecting?
dnscrypt-proxy 2.0.42 on macOS 10.15.4 (19E287) Catalina

## *What* is affected by this bug?
dnscrypt-proxy's ability to run automatically at startup

## *When* does this occur?
At reboot, after login.

## *Where* does it happen?
OS popup error message: "dnscrypt-proxy" cannot be opened because the developer cannot be verified.
![Screen Shot 2020-04-27 at 9 30 21 PM](https://user-images.githubusercontent.com/47869159/80437210-06170080-88cf-11ea-8964-e3edd703483b.png)

## *How* do we replicate the issue?

1. Install the app in /usr/local/bin/
2. Install service
3. Reboot and log in 

## Expected behavior (i.e. solution)
No security warning.

## Other Comments
The message can be disabled for the current session only by going to System Preferences > Security & Privacy > General and allowing the app by inputting admin credentials. After reboot, it pops up again.

**Comment by jedisct1** [comment]
The easiest way to install it on MacOS is probably by using Homebrew.

**Comment by ryandesign** [comment]
[dnscrypt-proxy is also available in MacPorts](https://ports.macports.org/port/dnscrypt-proxy) if you prefer that.

**Comment by mihscr** [comment]
I shared the issue assuming it might be of interest to the developer.

Regardless, I switched to the homebrew install. Thanks for the tips, both of you.

**Comment by jedisct1** [comment]
FWIW, the official binaries available in the download section are Apple signed since... a couple minutes after that ticket was originally created.

**Comment by mihscr** [comment]
Wow. Kudos for the promptness, sir. And thank you!
