### ISSUE TITLE
Is it possible to use custom dns servers that are not in public-resolvers.md?

### ISSUE THREAD

**Issue by Huhni** [DNSCrypt/dnscrypt-proxy#1301]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [X] I'd like to have my existing server added to a public list of encrypted DNS servers (sort of)
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description
I'm using a raspberry pi with pi-hole as dns server for my local network, but I would also like to run dnscrypt-proxy on my pc for some additional rules for that particular machine.
However I can't seem to find an option to use a custom name server other than the ones provided in the **public-resolvers.md** file. Am I missing something or is it not possible yet to use other dns servers? 
I was able to get it working by using the ip of my raspberry pi as fallback_resolver and keeping server_names empty, but that seems quite hacky and I'm not sure if that methods has some drawbacks I'm not aware of

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> I'm using a raspberry pi with pi-hole as dns server for my local network, but I would also like to run dnscrypt-proxy 

i recommend, running dnscrypt-proxy on raspberry as resolver for pi-hole directly

>  Am I missing something or is it not possible yet to use other dns servers?

Yes RTFM:
https://github.com/DNSCrypt/dnscrypt-proxy/blob/3e264b9da9ae2cf7895a53f93b69b71787ad9059/dnscrypt-proxy/example-dnscrypt-proxy.toml#L698

**Comment by Huhni** [comment]
Thank you. I must have missed that in the wiki. It was a bit confusing with the stamp thing, but i got it to work I think.

For anyone with the same problem go to https://dnscrypt.info/stamps/ in order to generate the required stamp. If you select **Anonymized DNS** as protocol you only need to enter the ip and then copy the stamp to the file like this:
```  
[static.'pi-hole']
stamp = 'sdns://gQsxOTIuMTY4LjEuMQ'
```

Then for **server_names** just use the name you chose, in my case 'pi-hole' without the static prefix:
`server_names = ['pi-hole']`

Not sure how do it with DNSCrypt as protocol, since it needs some public key, but it's good enough for my purposes, even though the query.log now shows PARSE_ERROR for every request that isn't blocked.
