### ISSUE TITLE
add china dns

### ISSUE THREAD

**Issue by Potterli20** [DNSCrypt/dnscrypt-proxy#1303]
## add china dns
My China's DNS:
https://dns-api.trli.xyz/dns-query
tls://dns-api.trli.xyz

My Foreign DNS:
https://dns2-api.trli.xyz:444/dns-query
tls://dns2-api.trli.xyz

Other China's DNS:
https://dns.alidns.com/dns-query
tls://dns.alidns.com
****

**Comment by jkle112** [comment]
Thank you ,I add these in my system.

**Comment by jedisct1** [comment]
Duplicate of https://github.com/DNSCrypt/dnscrypt-resolvers/issues/269
