### ISSUE TITLE
Cache behavior with whoami.cloudflare.com

### ISSUE THREAD

**Issue by youtous** [DNSCrypt/dnscrypt-proxy#1304]
## Subject

* [x] Other

## Description

I am running two computers on the same network:
- Computer A is connected to internet trough a VPN.
- Computer B connected to internet without using a VPN.

The two computers are using dnscrypt-proxy using scaleway-fr and cloudflare as DNS.

Computer B is running the following command every 5 minutes: `dig -4 TXT +short whoami.cloudflare.com @ns1.cloudflare.com -4` and send an alert if the ip has changed (comparing the last output of the command).

Today, computer B raised an alert, the dig command returned the VPN ip address of the computer A.

_Computer B never had any access to the VPN._
_Server with the lowest latency is scaleway-fr on both computers._

How is that possible? Is there a cache mechanism or something that could explain this behavior?

**Comment by jedisct1** [comment]
Yes, `dnscrypt-proxy` has a cache.

By the way if you are using `scaleway-fr`, you can simply get your IP address with

```sh
dig my.ip
```

**Comment by youtous** [comment]
Thank you for your _quick_ answer!
I was seeking for an universal command which could work for both DNS servers (scaleway and cloudflare) but I guess it's not possible due to the server cache.

**Comment by youtous** [comment]
This issue is not related to dnscrypt-proxy, but here's my investigation:
On both computers:
- stop dnscrypt-proxy (no DNS queries are available)
- run: `watch -n 0.1 'dig -4 TXT whoami.cloudflare.com @173.245.58.100'`

Ip address returned is sometimes computer A and sometimes computer B, it excludes dnscrypt-proxy.

Using another whoami service:
- `watch -n 0.1 'dig -4 ANY  myip.opendns.com @208.67.222.222'`

Opendns is always returning the ip address corresponding to the computer.

_173.245.58.100 = ns1.cloudflare.com_
_208.67.222.222 = resolver1.opendns.com_

I'm not a DNS expert therefore I cannot explain this behavior but it seems whoami.cloudflare.com is messing with DNS queries.

EDIT: Posted on https://community.cloudflare.com/t/cache-behavior-with-whoami-cloudflare-com/169699

-- 
Thank you for your time @jedisct1

**Comment by welwood08** [comment]
Might also be worth trying `1.1.1.1` instead of `ns1.cloudflare.com` since I suspect that's closer to whatever code is responsible for returning the requester's IP address and not caching it (see [here](https://community.cloudflare.com/t/can-1-1-1-1-be-used-to-find-out-ones-public-ip-address/14971/7)).

**Comment by youtous** [comment]
Thanks @welwood08! No ip overlap when using 1.1.1.1 :100:
