### ISSUE TITLE
Hope for upgrade

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#1305]
Openwrt x64 in a power mini PC or linksys wrt1900ac v1.

Hope dnscrypt-proxy to upgrade used UDP to hide packets that could to be found in ISP.
Used in China.
Dnscrypt over UDP ,Dnscrypt over Https,Dnscrypt over TLS,if not true ,I am very sorry.
Maybe add PDoT: Private DNS-over-TLS with TEE Support.

More information:
https://arxiv.org/abs/1909.11601
https://medium.com/@programthink/%E5%AF%B9%E6%AF%944%E7%A7%8D%E5%BC%BA%E5%8C%96%E5%9F%9F%E5%90%8D%E5%AE%89%E5%85%A8%E7%9A%84%E5%8D%8F%E8%AE%AE-dnssec-dnscrypt-dns-over-tls-dns-over-https-9d489cd4c48e

Thank you!

**Comment by jedisct1** [comment]
Probably not, sorry.
