### ISSUE TITLE
How to set normal DNS as upstream ?

### ISSUE THREAD

**Issue by zhengkai** [DNSCrypt/dnscrypt-proxy#1309]
## Subject
I want to run my own DNSCrypt and/or DoH server

## Description
My plan: some matched domain request DoH, else normal DNS ( 192.168.0.1 )

    server_names = ['local-dns']
    fallback_resolvers = ['192.168.1.1:53']
    [static]
      [static.'local-dns']
      stamp = 'sdns://gQsxOTIuMTY4LjEuMQ'

(the stamp `sdns://gQsxOTIuMTY4LjEuMQ` is `192.168.1.1` )

forwarding rule:  ( `192.168.1.248` is another dnscrypt-proxy server and works well )

    google.com 192.168.1.248

when server started, error in log: 

    [2020-05-02 02:49:49] [ERROR] Unsupported protocol
    [2020-05-02 02:49:49] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable

I can dig "google.com", but fail when dig other domains, log reports:

    [2020-05-02 02:51:13]   127.0.0.1   163.com A   PARSE_ERROR 0ms -

How I should set it up ?

In addition, I think the name rules should be unified, It should allow static name anywhere ( include forwarding rules )

**Comment by ibksturm** [comment]
hi there

look at my git, there‘s a implementation of doh, dot and dnscrypt server

if questions, questions
