### ISSUE TITLE
Can I Used [sources] url with offline file?

### ISSUE THREAD

**Issue by GaneJ** [DNSCrypt/dnscrypt-proxy#131]
1. Code for offline source file:
```
  [sources.'public-resolvers']
  url = 'file:///C:/Program Files/DNSCrypt/public-resolvers.md'
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
```

2. Did you put `cache_file` in the same folder where dnscrypt installed?

**Comment by GaneJ** [comment]
Sorry if I had too many question, I'm just too exciting about your config file. Not like v1 where dnscrypt using registry. Now its the same as `unbound`.
Also I'm still learning about go language you used on dnscrypt. Combination between `basic`, `c` and `pascal`, I think.

**Comment by jedisct1** [comment]
HI!

If you want to use a static,offline source, just remove the url line. You only need cache_file.

**Comment by GaneJ** [comment]
OK thanks.
Close it.
