### ISSUE TITLE
command not found on MacOS

### ISSUE THREAD

**Issue by bibicute333** [DNSCrypt/dnscrypt-proxy#1310]
Hi, I previously installed dnscrypt-proxy without any trouble, I also installed it as a service but today I tried to use its commands via terminal and it showed me this:

 dnscrypt-proxy -resolve google.com
-bash: dnscrypt-proxy: command not found
sudo dnscrypt-proxy
Password:
sudo: dnscrypt-proxy: command not found

I also tried using " ./dnscrypt-proxy " and reinstalling it but it showed me the same error. 
I'm sorry this may seem like a stupid question but I'm a newbie and I don't know how to solve it lol. Did I need to tweak the configuration file before installing it as a system service?

**Comment by jedisct1** [comment]
`./dnscrypt-proxy` or `sudo ./dnscrypt-proxy` require that you are in the directory that contains `dnscrypt-proxy`.

**Comment by bibicute333** [comment]
> `./dnscrypt-proxy` or `sudo ./dnscrypt-proxy` require that you are in the directory that contains `dnscrypt-proxy`.

I tried doing it while being in the folder but

dnscrypt-proxy-macos-2.0.42 user$ sudo .\dnscrypt-proxy -resolve example.com
sudo: .dnscrypt-proxy: command not found

**Comment by bibicute333** [comment]
> `./dnscrypt-proxy` or `sudo ./dnscrypt-proxy` require that you are in the directory that contains `dnscrypt-proxy`.

I did so while being in the directory but it says this. The same error appears if i only type ./dnscrypt-proxy

MyiMac:dnscrypt-proxy-macos-2.0.42 user$ ./dnscrypt-proxy -resolve google.com
./dnscrypt-proxy: line 39: listen_addresses: command not found
./dnscrypt-proxy: line 44: max_clients: command not found
./dnscrypt-proxy: line 58: ipv4_servers: command not found
./dnscrypt-proxy: line 61: ipv6_servers: command not found
./dnscrypt-proxy: line 64: dnscrypt_servers: command not found
./dnscrypt-proxy: line 67: doh_servers: command not found
./dnscrypt-proxy: line 73: require_dnssec: command not found
./dnscrypt-proxy: line 76: require_nolog: command not found
./dnscrypt-proxy: line 79: require_nofilter: command not found
./dnscrypt-proxy: line 82: disabled_server_names: command not found
./dnscrypt-proxy: line 91: force_tcp: command not found
./dnscrypt-proxy: line 112: timeout: command not found
./dnscrypt-proxy: line 117: keepalive: command not found
./dnscrypt-proxy: line 155: cert_refresh_delay: command not found
./dnscrypt-proxy: line 204: fallback_resolvers: command not found
./dnscrypt-proxy: line 209: ignore_system_dns: command not found
./dnscrypt-proxy: line 219: netprobe_timeout: command not found
./dnscrypt-proxy: line 230: netprobe_address: command not found
./dnscrypt-proxy: line 253: log_files_max_size: command not found
./dnscrypt-proxy: line 256: log_files_max_age: command not found
./dnscrypt-proxy: line 259: log_files_max_backups: command not found
./dnscrypt-proxy: line 277: block_ipv6: command not found
./dnscrypt-proxy: line 282: block_unqualified: command not found
./dnscrypt-proxy: line 288: block_undelegated: command not found
./dnscrypt-proxy: line 294: reject_ttl: command not found
./dnscrypt-proxy: line 331: cache: command not found
./dnscrypt-proxy: line 336: cache_size: command not found
./dnscrypt-proxy: line 341: cache_min_ttl: command not found
./dnscrypt-proxy: line 346: cache_max_ttl: command not found
./dnscrypt-proxy: line 351: cache_neg_min_ttl: command not found
./dnscrypt-proxy: line 356: cache_neg_max_ttl: command not found
./dnscrypt-proxy: line 364: [local_doh]: command not found
./dnscrypt-proxy: line 397: [query_log]: command not found
./dnscrypt-proxy: line 407: format: command not found
./dnscrypt-proxy: line 424: [nx_log]: command not found
./dnscrypt-proxy: line 433: format: command not found
./dnscrypt-proxy: line 454: [blacklist]: command not found
./dnscrypt-proxy: line 482: [ip_blacklist]: command not found
./dnscrypt-proxy: line 510: [whitelist]: command not found
./dnscrypt-proxy: line 543: [schedules]: command not found
./dnscrypt-proxy: line 582: [sources]: command not found
./dnscrypt-proxy: line 586: [sources.public-resolvers]: command not found
./dnscrypt-proxy: line 587: urls: command not found
./dnscrypt-proxy: line 588: cache_file: command not found
./dnscrypt-proxy: line 589: minisign_key: command not found
./dnscrypt-proxy: line 590: prefix: command not found
./dnscrypt-proxy: line 594: [sources.relays]: command not found
./dnscrypt-proxy: line 595: urls: command not found
./dnscrypt-proxy: line 596: cache_file: command not found
./dnscrypt-proxy: line 597: minisign_key: command not found
./dnscrypt-proxy: line 598: refresh_delay: command not found
./dnscrypt-proxy: line 599: prefix: command not found
./dnscrypt-proxy: line 623: [broken_implementations]: command not found
./dnscrypt-proxy: line 635: fragments_blocked: command not found
./dnscrypt-proxy: line 647: [tls_client_auth]: command not found
./dnscrypt-proxy: line 659: [anonymized_dns]: command not found
./dnscrypt-proxy: line 691: skip_incompatible: command not found
./dnscrypt-proxy: line 699: [static]: command not found

**Comment by welwood08** [comment]
You seem to have replaced the application with the configuration file. It's probably easiest if you do a clean reinstall at this point.

**Comment by bibicute333** [comment]
> You seem to have replaced the application with the configuration file. It's probably easiest if you do a clean reinstall at this point.

Thank you, how can I uninstall it? Because I tried re-doing the procedure but it always gives me the same error

**Comment by jedisct1** [comment]
To uninstall, just delete the folder.

Looks like you copied the example configuration file `example-dnscrypt-proxy.toml` as `dnscrypt-proxy` instead of `dnscrypt-proxy.toml`.

**Comment by bibicute333** [comment]
> To uninstall, just delete the folder.
> 
> Looks like you copied the example configuration file `example-dnscrypt-proxy.toml` as `dnscrypt-proxy` instead of `dnscrypt-proxy.toml`.

Ahhhh thank you!
