### ISSUE TITLE
I have a modified one stripped to 7.12M for MIPS. Should I release the repository of codes?

### ISSUE THREAD

**Issue by AZ-X** [DNSCrypt/dnscrypt-proxy#1314]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ √] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description

Compared to the standard size 9.4M ref to [bot builds](https://downloads.openwrt.org/releases/packages-19.07/mipsel_74kc/packages/dnscrypt-proxy2_2.0.42-1_mipsel_74kc.ipk), mine is tidy for a 74kc device.

**_I am not regarded as a beginner of go_**. I have modified three go applications in total and never write a hello world. This is the third one.

There are several reasons I don’t want to merge it into current project, so I just leave my question here.

**Comment by jedisct1** [comment]
Feel free to release it and announce it wherever appropriate (maybe the  snb forums?)

By the way, `go 1.15` will also substantially reduce the produced code size.

**Comment by AZ-X** [comment]
Good news. I will prepare a release after [this](https://github.com/AZ-X/An-exhibition-of-Ed25519-signature-to-both-ssh-and-dockerd-inside-of-an-advanced-boot2docker-disc). 
Hopefully the patches will be recognized as a resonator.

**Comment by AZ-X** [comment]
> Feel free to release it and announce it wherever appropriate (maybe the snb forums?)


I don't have any 'ASUS Wireless' and mostly don't care about Merlin users.
The reason I posted here is because people visiting GitHub respect codes. They will read closed issues like me. I am glad to share my knowledge with them.

**Comment by AZ-X** [comment]
By the way, the size of Windows x64 target binary is about 7.08M. No compressing.
