### ISSUE TITLE
Ways to properly filter out servers behind China's GFW

### ISSUE THREAD

**Issue by complyue** [DNSCrypt/dnscrypt-proxy#1315]
## *Who* is the bug affecting?

People behind GFW seeking to overcome it

## *What* is affected by this bug?

Can not workaround polluted DNS records by GFW

## *When* does this occur?

When servers behind GFW is not filtered out

## *Where* does it happen?

Main land China

## *How* do we replicate the issue?

Having e.g. alidns-doh effective, and resolve records for `google.com`

```md
## alidns-doh

A public DNS resolver that supports DoH/DoT in mainland China, provided by Alibaba-Cloud

Homepage: https://alidns.com/

sdns://AgQAAAAAAAAACTIyMy41LjUuNSCoF6cUD2dwqtorNi96I2e3nkHPSJH1ka3xbdOglmOVkQ5kbnMuYWxpZG5zLmNvbQovZG5zLXF1ZXJ5
```

## Expected behavior (i.e. solution)

Having access to `google.com` etc.

## Other Comments

I assumed having `require_nofilter = true` would filter out such servers, but as e.g. alidns-doh declares itself not doing filtering and get accepted, I'm beaten since recently.

On second thought, those servers actually do NO filtering by themselves, but affected by GFW indirectly, and even GFW is not doing blacklisting literally (despite there'll never be an official voice speaking in its behave). What GFW does is obfuscation, i.e. pointing `google.com` to `facebook.com` and vice versa e.g., then effectively rendering their service unusable from the victims.

So I feel `require_nofilter = true` is not enough to fight against GFW, something more effective needs to be figured out.

**Comment by complyue** [comment]
alidns-doh is added by #1303 or https://github.com/DNSCrypt/dnscrypt-resolvers/issues/269 maybe.

**Comment by jedisct1** [comment]
Indeed, the `nofilter` bit should not be set in that case.

This has been  updated. Thanks a lot for pointing this out!

**Comment by AZ-X** [comment]
I can easily rearrange endpoint resources dynamically in my version of this app but I don't think it's an issue. Forgot A li then you have a great peace. Shame out of the world if you are still considerate to such a host.

**Comment by complyue** [comment]
In case others trying to add servers with a description not so obvious in the future, how to verify/validate their `nofilter` statement being technically trustworthy ?

**Comment by AZ-X** [comment]
> In case others trying to add servers with a description not so obvious in the future, how to verify/validate their `nofilter` statement being technically trustworthy ?

No, actually you can’t. When a server is against you randomly, no way to prevent or predicate it.  The only thing you can do is explicitly placing a proper value of ‘server_names’ of the configuration. Remember always trusting yourself.

**Comment by AZ-X** [comment]
> In case others trying to add servers with a description not so obvious in the future, how to verify/validate their `nofilter` statement being technically trustworthy ?

If you believe something was wrong, turn DNSSEC validation on. It’s not within the scope of this app.

**Comment by jedisct1** [comment]
Hi Yue,

Servers having the `nofilter` flag are servers whose purpose is to filter ads, tracker, malware, pornography, etc.

So users chose them on purpose.

But servers behind the GFW are a different story. Some of them resolve Chinese domain names in mainland China, but forward queries for international domains over a VPN to other countries to avoid the GFW pollution.

But this is obviously not the case of AliDNS, so not having the `nofilter` flag is absolutely required for it, and thank you for noticing that it wasn't the case. The description should be also updated to mention that GFW filtering applies to it.

**Comment by jedisct1** [comment]
This has been added, thanks!
