### ISSUE TITLE
DNSCrypt Proxy slowed down Mac 

### ISSUE THREAD

**Issue by bravofrun** [DNSCrypt/dnscrypt-proxy#1316]
## *Who* is the bug affecting?

Hi! I'm a Mac OS user. These are the stats for my mac

- 2.5 GHz Intel Core i9
- 32 GB Ram

## *What* is affected by this bug?

I installed DNSCrypt Proxy for my Mac. I ran it with all the default settings.

I included a cloaking file and a blacklist file with the default settings. 

When I got back to my computer, two things happened-

#1- Everything was much, much slower. I monitored Activity Monitor and normal processes, like starting up a new window in Firefox, took 3-5X as long as they normally would.

#2- None of my websites worked. I only set the DNS IP Address in Network settings to the one recomended in the installation process. Every website I tried to visit served a "website could not be found" error.

## *When* does this occur?

This occurred after installation.

## *Where* does it happen?

On my Mac.

## *How* do we replicate the issue?

This is one helpful note about my installation. I have two separate accounts in my Mac.

One account is the administrator and another account is a regular user account.

I set up DNSCrypt with the admin account, and then logged into the regular user account.

The admin account was somewhat slower and the regular user account was much, much slower. Also, many websites were slower but working in the admin account. No websites worked in the regular account. 

## Expected behavior (i.e. solution)

I would expect only the blacklisted websites to stop working and my computer to be about normal speed.

**Comment by jedisct1** [comment]
I'd recommend starting with the default configuration, and only changing things one by one to see what exact custom change didn't do what you expect.

And of course, check with `dnscrypt-proxy -resolve` before anything else, verify that queries are actually going through `dnscrypt-proxy`, try different resolvers, look at log files to better understand what exactly happens, etc.

**Comment by bravofrun** [comment]
@jedisct1 , thanks for your help. How can I get the log files to work?

I set logging to true and used the default log name, but it wasn't populating the files.
