### ISSUE TITLE
Windows updates

### ISSUE THREAD

**Issue by sutex** [DNSCrypt/dnscrypt-proxy#1317]
Can we have a WHITELIST that allows the PC to update via Windows update!

I had to remove black list just to be able to update my PC

**Comment by jedisct1** [comment]
`dnsrypt-proxy` doesn’t block anything by itself.

If you are using a blacklist that isn’t one you built, and it has false positives, you should report them to the maintainers.

If you are using a server that intentionally blocks some names (for ad blocking, tracker blocking, ...) and it has false positives, you should also report them to whoever operates the server.

The log file will tell you exactly what names have been blocked and what rule triggered the block.

**Comment by AZ-X** [comment]
@sutex 
I guess you would like to drop some unmentioned anonymous improving program.
Why not look into pattern_matcher.go? Just change what you want to allow sub domain fetching.

**Comment by sutex** [comment]
How about a TXT whitelist, that allows for Microsoft updates to happen, that can be imported into Simple DNSCrypt that doesn't need an  'unmentioned anonymous improving program' that requires understanding whatever that could be, or what a  'pattern_matcher.go' is!.. Thanks :)

**Comment by AZ-X** [comment]
@sutex
Not possible. Dealing with _dnsrypt-proxy_, you must be skillful. Simple functionality is a pain to the codes behind. Frank tried teaching you to go to the right way so as to aviod functional request. In my opinion, he is so brilliant.
