### ISSUE TITLE
Another GUI tool for minisig

### ISSUE THREAD

**Issue by AZ-X** [DNSCrypt/dnscrypt-proxy#1318]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [x] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

Hi Frank,
Would you please update the list of the section in [README](https://github.com/jedisct1/minisign/blob/master/README.md)

> Additional tools, libraries and implementations

## Description
[WPF-GO-dnscrypt-proxy-md](https://github.com/AZ-X/WPF-GO-dnscrypt-proxy-md)

**Comment by jedisct1** [comment]
I must confess that I don't understand what that project does and how to use it.

Can you clarify or maybe write a bit of documentation? Is it about dnscrypt-proxy or minisign?

**Comment by AZ-X** [comment]
> I must confess that I don't understand what that project does and how to use it.
> 
> Can you clarify or maybe write a bit of documentation? Is it about dnscrypt-proxy or minisign?

I think both. It enable a simple user to view, edit, save and sign with its own signature. 
The purpose of this project is to shorten the md files served dnscrypt-proxy while supporting a GUI filter for sources review. For example: public-resolvers.md is about 49.8 KB. It’s too big for a low energy consumed MIPS portable device.

**Comment by jedisct1** [comment]
I see. This is a good start and it can indeed be a very handy tool.

Feel free to add it to the documentation once you have a release.

Minisign itself is a general purpose tool and is unrelated to DNSCrypt.

**Comment by AZ-X** [comment]
Too lazy... I haven't finished [this](https://github.com/AZ-X/An-exhibition-of-Ed25519-signature-to-both-ssh-and-dockerd-inside-of-an-advanced-boot2docker-disc)
Actually I prepared more than 199 lines words in my mind for [README](https://github.com/AZ-X/WPF-GO-dnscrypt-proxy-md/blob/master/README.md)
Go dreaming. Bye.
