### ISSUE TITLE
syslog warning dnscrypt certificate

### ISSUE THREAD

**Issue by Ninjanoir87** [DNSCrypt/dnscrypt-proxy#1321]
hi, 

I run dd-wrt with dnscrypt v2 - 2.0.39 (entware) and everything goes well but when I use cleanbrowsing server and some others, I get that kind of warning:

[WARNING] [cleanbrowsing-security] uses a non-standard provider name ('cleanbrowsing.org.' doesn't start with '2.dnscrypt-cert.

I got the same I think with adguard..

`

May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: dnscrypt-proxy 2.0.39
--
May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: Network connectivity detected
May 17 06:47:50 DD-WRT user.notice root: Started dnscrypt-proxy from .
May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: Source [relays] loaded
May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: Source [public-resolvers] loaded
May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: Firefox workaround initialized
May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: Now listening to 127.0.0.3:30 [UDP]
May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: Now listening to 127.0.0.3:30 [TCP]
**May 17 06:47:50 DD-WRT daemon.warn  dnscrypt-proxy[2544]: [cleanbrowsing-family] uses a non-standard  provider name ('cleanbrowsing.org.' doesn't start with  '2.dnscrypt-cert.')**
May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: [cleanbrowsing-family] OK (DNSCrypt) - rtt: 51ms
May 17 06:47:50 DD-WRT daemon.notice dnscrypt-proxy[2544]: [dnscrypt.ca-2] OK (DNSCrypt) - rtt: 35ms
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: [ev-to] OK (DNSCrypt) - rtt: 53ms
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: [dnscrypt.ca-1] OK (DNSCrypt) - rtt: 48ms
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: [quad9-dnscrypt-ip4-filter-alt] OK (DNSCrypt) - rtt: 54ms
May 17 06:47:51 DD-WRT daemon.notice  dnscrypt-proxy[2544]: [quad9-dnscrypt-ip4-filter-alt] OK (DNSCrypt) -  rtt: 54ms - additional certificate
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: [quad9-dnscrypt-ip4-filter-pri] OK (DNSCrypt) - rtt: 115ms
May 17 06:47:51 DD-WRT daemon.notice  dnscrypt-proxy[2544]: [quad9-dnscrypt-ip4-filter-pri] OK (DNSCrypt) -  rtt: 115ms - additional certificate
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: Sorted latencies:
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: -    35ms dnscrypt.ca-2
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: -    48ms dnscrypt.ca-1
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: -    51ms cleanbrowsing-family
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: -    53ms ev-to
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: -    54ms quad9-dnscrypt-ip4-filter-alt
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: -   115ms quad9-dnscrypt-ip4-filter-pri
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: Server with the lowest initial latency: dnscrypt.ca-2 (rtt: 35ms)
May 17 06:47:51 DD-WRT daemon.notice dnscrypt-proxy[2544]: dnscrypt-proxy is ready - live servers: 6

`

thanks

**Comment by jedisct1** [comment]
Well, it means what the message says.

The protocol requires certificate names to start with the protocol version number and `.dnscyrpt-cert.`, and this is actually important for relaying.

But some resolvers use a non-conformant name.

There’s not much you can do, this has to be fixed on their side.

**Comment by Ninjanoir87** [comment]
Ok.

But it is fine?


I have nothing to worry about?

**Comment by jedisct1** [comment]
Nope.
