### ISSUE TITLE
warning notice

### ISSUE THREAD

**Issue by Ninjanoir87** [DNSCrypt/dnscrypt-proxy#1322]
[ ] I have questions about the DNSCrypt warnign logs:

I did not change anything in my configuration (toml file) and since 2 days, I get those warnings in my log. I dont use stamp is the moment and as I wrote, no changing in my toml since few days.

`

May 18 14:32:17 DD-WRT user.notice root: Started dnscrypt-proxy from .
--
May 18 14:32:17 DD-WRT daemon.notice dnscrypt-proxy[3472]: Source [public-resolvers] loaded
May 18 14:32:17 DD-WRT **daemon.warn  dnscrypt-proxy[3472]: Invalid or unsupported stamp**  [sdns://AgcAAAAAAAAAJTJhMDU6ZjQ4MDoxNDAwOjQzNjo1NDAwOjJmZjpmZWI4OjhkMWMgPhoaD2xT8-l6SS1XCEtbmAcFnuBXqxUFh2_YP9o9uDgSamFyamFyLm1lZ2FuZXJkLm5sBC9kb2g]:  Invalid stamp (port range)
May 18 14:32:17 DD-WRT **daemon.warn  dnscrypt-proxy[3472]: Error in source [public-resolvers]: [Invalid or  unsupported stamp**  [sdns://AgcAAAAAAAAAJTJhMDU6ZjQ4MDoxNDAwOjQzNjo1NDAwOjJmZjpmZWI4OjhkMWMgPhoaD2xT8-l6SS1XCEtbmAcFnuBXqxUFh2_YP9o9uDgSamFyamFyLm1lZ2FuZXJkLm5sBC9kb2g
May 18 14:32:17 DD-WRT daemon.notice dnscrypt-proxy[3472]: Source [relays] loaded

`

ideas?

thanks

**Comment by Ninjanoir87** [comment]
I found it, it is ''meganerd'' dns server in ''public-resolvers.md, I dont use it  but the server seems to have a problem..

even If I remove all about that server in resolver.md and in relays.md, the error is still there

**Comment by jedisct1** [comment]
Yes, this is a DoH server that was just added, and looks like its IPv6 address was not properly set.

This is no big deal in spite of the warning, `dnscrypt-proxy` should just ignore it.

This entry has been removed until it is fixed. Thanks!
