### ISSUE TITLE
fragments_blocked config param is ignored in the code

### ISSUE THREAD

**Issue by SerusDev** [DNSCrypt/dnscrypt-proxy#1323]
It seems that in version 2.0.42 conf-file parameter fragments_blocked (FragmentsBlocked) is never used in the actual code.
Apparently, there is some confusion around it and broken_query_padding.

**Comment by jedisct1** [comment]
Can you fix it?

**Comment by SerusDev** [comment]
> Can you fix it?

Sorry, I am a C++ guy and not comfortable with Go yet :)
