### ISSUE TITLE
how to making Source or update by proxy or by local&static?

### ISSUE THREAD

**Issue by cc978** [DNSCrypt/dnscrypt-proxy#1329]
notice that dnscrypt-proxy visited two or more urls for server source by hours schedule, but most of time, the files are static and no need to updating so frequently, and it provides a leakage of info.

is it a way to set the aim files local and static?

and in many cases, users like to run dnscrypt-proxy only visiting upstream dns servers and open firewall's port for that.

so, is there a http/socks proxy settings in dnscrypt-proxy for this?  

[sources.'public-resolvers']
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']

![image](https://user-images.githubusercontent.com/63266600/82636584-882be800-9c35-11ea-8b0b-7787ec0afe1e.png)

https://github.com/DNSCrypt/dnscrypt-proxy/pull/829

**Comment by jedisct1** [comment]
[As written in the documentation](https://github.com/dnscrypt/dnscrypt-proxy/wiki/Configuration-Sources#configuring-the-sources-to-use), you can set `refresh_delay` to whatever update delay you want.

Of course, having an out of date configuration is more likely to cause servers to suddenly stop working.
