### ISSUE TITLE
require_dnssec = true not working

### ISSUE THREAD

**Issue by cantenna** [DNSCrypt/dnscrypt-proxy#1330]
## *Who* is the bug affecting?

Me

## *What* is affected by this bug?

dnssec

## *When* does this occur?

all the time

**Comment by jedisct1** [comment]
What does the following command return, with the example configuration?

```sh
dnscrypt-proxy -list | wc -l
```

Now change `require_dnssec = false` to `require_dnssec = true` and run the command again:

```sh
dnscrypt-proxy -list | wc -l
```

What do you get?
