### ISSUE TITLE
NETWORK_ERROR on Arm64

### ISSUE THREAD

**Issue by alpe12** [DNSCrypt/dnscrypt-proxy#1333]
When I have `user_name` set (to drop privileges) it starts giving only `NETWORK_ERROR` on the querty log after about 30s to 2m.

If I run without `user_name` (not dropping privileges) it works.
If I run with `user_name` and add `AmbientCapabilities=CAP_NET_BIND_SERVICE` to the systemd service it also works.

Maybe the service release the port 53 after sometime and can't get it back?

```
[Unit]
Description=Encrypted/authenticated DNS proxy
ConditionFileIsExecutable=/home/alpe/dnscrypt-proxy-linux_arm/dnscrypt-proxy
After=network.target

[Service]
#AmbientCapabilities=CAP_NET_BIND_SERVICE
PrivateDevices=yes
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/home/alpe/dnscrypt-proxy-linux_arm
ReadWritePaths=/tmp/alpe

StartLimitInterval=5
StartLimitBurst=10
ExecStart=/home/alpe/dnscrypt-proxy-linux_arm/dnscrypt-proxy

WorkingDirectory=/home/alpe/dnscrypt-proxy-linux_arm

Restart=always
RestartSec=60


ExecStartPost=/bin/bash -c 'echo $MAINPID > /home/alpe/dnscrypt-proxy-linux_arm/dnscrypt-proxy.pid'
PIDFile=/home/alpe/dnscrypt-proxy-linux_arm/dnscrypt-proxy.pid


[Install]
WantedBy=multi-user.target
```

**Comment by jedisct1** [comment]
> If I run with user_name and add AmbientCapabilities=CAP_NET_BIND_SERVICE to the systemd service it also works.

So, do that? :)

The systemd service installed with `dnscrypt-proxy -service install` works fine. If you are doing your own thing, this is a bit out of the scope of this project.

**Comment by alpe12** [comment]
Yeah, I've been using like this for a few hours.
However this shouldn't be needed.
But that's ok. ;)

Edit:
Just noticed it's giving NETWORK_ERROR. :/
Trying as root now.

PS: I use Arm64.

**Comment by alpe12** [comment]
It was also giving NETWORK_ERROR as root.
My mistake. I assumed on my original post that it was working because it took way longer to give error.

I returned to 2.0.41 now. Tomorrow I'll post saying if it worked.
I originally used 2.0.38. The problem happened after updating to 2.0.42.

**Comment by alpe12** [comment]
@jedisct1 Only 2.0.38 works. Anything after that doesn't.
