### ISSUE TITLE
Does 'fallback_resolvers' support anything other than regular DNS?

### ISSUE THREAD

**Issue by v1gnesh** [DNSCrypt/dnscrypt-proxy#1338]
The comments say that `fallback_resolvers` is just to get the IP for the primary resolvers when they are not referred to directly by IP address. Does it have to be `something:53` or can `fallback_resolvers` use a DoH endpoint, such as 
```
Addresses [ "dns.adguard.com", "176.103.130.130" ]
Ports [ 443 ]
```

**Comment by jedisct1** [comment]
The main purpose of a fallback resolver is to resolve a DoH host name so that a connection to a DoH server can be established.

If you could put a name here, it couldn't be resolved by using itself :/

**Comment by v1gnesh** [comment]
@jedisct1  Yeah I know, I'm not asking if we can use a hostname here, I'm asking if I can use something like 9.9.9.9 port 443 (referring to Quad9 DoH)

**Comment by jedisct1** [comment]
If a DoH server has a fixed IP address, it will be in the stamp, and fallback resolvers will not be used. Same if you are using DNSCrypt, IPs are always included so fallback resolvers are not required.

**Comment by v1gnesh** [comment]
Ah ok, thank you!
