### ISSUE TITLE
dnscrypt-wrappers 0.4.0 released

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#134]
A new major release of dnscrypt-wrapper is available.

The docker server images have also been updated.

New features have been implemented, the most notable ones being a shared key cache, that makes the proxy about twice as fast, as well as server-side filtering, so you can have blacklists on the server if you want to.

More importantly, it includes security fixes: in previous versions (I think all of them are affected), a malicious DNS query could crash the server.

Everybody is thus encouraged to upgrade.

**Comment by Sporif** [comment]
Thanks for the update. This prompted me to add a wiki page about updating dnscrypt-server.

https://github.com/jedisct1/dnscrypt-proxy/wiki/Manually-updating-your-DNSCrypt-server

Watchtower is cool but I prefer to be in control :)

**Comment by jedisct1** [comment]
Thank you!
