### ISSUE TITLE
NCSI Windows 10 (Internet probing over dns) doses not work

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1342]
## *Who* is the bug affecting?
Simple Dnscrypt

## *What* is affected by this bug?

NCSI Internet status probing over dns

## *When* does this occur?

Everytime when using simplednscrypt

## *Where* does it happen?

Windows 10 newest version 1900 May 2004

## *How* do we replicate the issue?

If i using dhcp or manual configured dns servers connection probing works.
If i using simplednscrypt (127.0.0.1) manual configured dns server for redirecting to dnscrypt, it will not work. Connection status no internet, but internet works well.

## Other Comments
Workaround for simplednscrypt. First dns server 127.0.0.1, and second 8.8.8.8.
Internet connection probing will use 8.8.8.8, and it works but the problem of dnscrypt is not solved.

**Comment by lessload** [comment]
You found the problem when dnscrypt-proxy need to update `dnscrypt-resolvers` right ? or everytime you connect/reconnect internet?

**Comment by jedisct1** [comment]
SimpleDNSCrypt is a different project: https://github.com/bitbeans/SimpleDnsCrypt

**Comment by lessload** [comment]
Why close it ? NCSI problem is come from `dnscrypt-proxy`.!!!
SimpleDNSCrypt just GUI.
