### ISSUE TITLE
Application log is not automatically rotated

### ISSUE THREAD

**Issue by Kein** [DNSCrypt/dnscrypt-proxy#1343]
## *Who* is the bug affecting?
Me

## *What* is affected by this bug?
Logging

## *When* does this occur?
Runtime

## *Where* does it happen?
Filesystem?

## *How* do we replicate the issue?
Run dnscrypt with verbose logging on Android long enough to accumulate >defined_value of logs

## Expected behavior (i.e. solution)
Log file(s) are trimmed to specified value

## Other Comments
```
log_level = 1
log_file = '/storage/dnscrypt.log'
log_files_max_size = 1
log_files_max_age = 7
log_files_max_backups = 1
```

My current main log is 3.2Mb, should be max 1Mb. DNS Queries log havent reached 1Mb in size yet

**Comment by jedisct1** [comment]
The application log file is different from other logs, and doesn't do automatic rotation.

But you can send these logs to the system log (just comment `log_file` as it is by default), and read them with `logcat`.

**Comment by jedisct1** [comment]
Version 2.0.43 truncates the application log (this can be changed with a new option, `log_file_latest`).
