### ISSUE TITLE
[Linux] Possible to blacklist JUST IPv6?

### ISSUE THREAD

**Issue by kroy-the-rabbit** [DNSCrypt/dnscrypt-proxy#1344]
## Is your feature request related to a problem?

I have a Tunnelbroker.net tunnel.  Right now, Netflix counts that as a VPN, which means netflix is inaccessible unless I block it on IPv6 either by routing or DNS.  

DNS is better since it solves the problem without blocking random IPv6 ranges that Netflix might be sharing (like with Google)

## Describe the solution you'd like

Be able to block/drop a regex, but ONLY by IPv6

## Alternatives you've considered

Right now, I accomplish this by running dnscrypt-proxy, with this config:

```
#forward 
 netflix.com 127.0.0.1:10053
```

And then a bind server with a config like

```
      listen-on-v6 port 10053 {any;};
      listen-on port 10053 {any;};
      filter-aaaa-on-v4 yes;
```

I would like to eliminate the bind server.

## Who will that feature be useful to?

Anybody running a tunnelbroker tunnel.  It might be desirable to many filter/forward etc based on IP type in many situations. 

## What are you going to contribute?

I can gladly test and document as I feel this feature is worthy.

**Comment by vladns** [comment]
Maybe it will help https://www.man7.org/linux/man-pages/man5/gai.conf.5.html?

**Comment by jedisct1** [comment]
`dnscrypt-proxy` can block IPv6 responses, but globally not per domain.
