### ISSUE TITLE
[Having Issue] Problem with update

### ISSUE THREAD

**Issue by Kylvan-8** [DNSCrypt/dnscrypt-proxy#1347]
# Subject

    Other

# Description

I had problem to update my pi hole with the script below :

```
INSTALL_DIR="/opt/dnscrypt-proxy"
LATEST_URL="https://api.github.com/repos/jedisct1/dnscrypt-proxy/releases/latest"

Update() {
    workdir="$(mktemp -d)"
    curl -sL $(curl -sL "$LATEST_URL" |
        grep dnscrypt-proxy-linux_arm- | grep browser_download_url | head -1 | cut -d \" -f 4) |
        tar xz -C "$workdir" -f - linux-arm/dnscrypt-proxy &&
        [ -x linux-arm/dnscrypt-proxy ] &&
        mv -f "${INSTALL_DIR}/dnscrypt-proxy" "${INSTALL_DIR}/dnscrypt-proxy.old" || : &&
        mv -f "${workdir}/linux-x86_64/dnscrypt-proxy" "${INSTALL_DIR}/" &&
        cd "$INSTALL_DIR" && rm -fr "$workdir" &&
        ./dnscrypt-proxy -check && ./dnscrypt-proxy -service install 2>/dev/null || : &&
        ./dnscrypt-proxy -service restart || ./dnscrypt-proxy -service start
}

lversion=$("${INSTALL_DIR}/dnscrypt-proxy" -version)
rmersion=$(curl -sL "$LATEST_URL" | grep "tag_name" | head -1 | cut -d \" -f 4)
[ -z "$lversion" ] && exit 1
[ -z "$rmersion" ] && exit 1

echo locally installed
echo "$lversion"

echo remote git version
echo "$rmersion"

if [ "$rmersion" != "$lversion" ]; then
    echo "Updating" && Update
else
    echo "No Update Needed"
fi
```

So i've past this script in hurry https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Updates

Sadly the cpu_arch format was bad and now i get those errors :
`scripts/dnscrypt-proxy-update.sh: 17: scripts/dnscrypt-proxy-update.sh: /opt/dnscrypt-proxy/dnscrypt-proxy: Exec format error`
and when i try to launch the service :
```
Raspberry:~ $ sudo service dnscrypt-proxy status
* dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-05-31 21:40:56 CEST; 1min 4s ago
  Process: 1190 ExecStart=/opt/dnscrypt-proxy/dnscrypt-proxy (code=exited, status=203/EXEC)
 Main PID: 1190 (code=exited, status=203/EXEC)
```
Please can you help ? Don't tell me i've to redo everything as there https://github.com/DNSCrypt/dnscrypt-proxy/issues/1198

( Are you there old pal ? @ibksturm )

EDIT :
I've managed to restore old dnscrypt-proxy file in /opt/dnscrypt-proxy/ and now i've the initial issue encountered before as :
```
mv: impossible d'valuer '/tmp/tmp.gMvHTH629G/linux-x86_64/dnscrypt-proxy': Aucun fichier ou dossier de ce type
scripts/dnscrypt-proxy-update.sh: 14: scripts/dnscrypt-proxy-update.sh: ./dnscrypt-proxy: not found
scripts/dnscrypt-proxy-update.sh: 14: scripts/dnscrypt-proxy-update.sh: ./dnscrypt-proxy: not found
```
When i tried to update

**Comment by ibksturm** [comment]
@Kylvan-8 hi there, what do you want and how can i help you?


aaaaaah i remember :)

ok look, i will try help you tomorrow evening, now i have to put kidis in bed........ any questions ;)

**Comment by Kylvan-8** [comment]
> 
> 
> @Kylvan-8 hi there, what do you want and how can i help you?
> 
> aaaaaah i remember :)
> 
> ok look, i will try help you tomorrow evening, now i have to put kidis in bed........ any questions ;)

No problem, i have fix the major issue, now i've just troubles with updates (dnscrypt + pi hole) so it can wait :)

A developer tells me to not update automatically pi hole, well one problem solved (even if i don't know why them put pimped flash rgb image to tells you that there is new updates if they aren't needed...).

As you can see in my first post, automatic update script for dnscrypt doesn't work. If you could help me on that, that will be awesome :)

**Comment by Kylvan-8** [comment]
I still having issue with updating

**Comment by welwood08** [comment]
> Sadly the cpu_arch format was bad and now i get those errors :
> `scripts/dnscrypt-proxy-update.sh: 17: scripts/dnscrypt-proxy-update.sh: /opt/dnscrypt-proxy/dnscrypt-proxy: Exec format error`

The script you showed mentions both `arm` and `x86_64`, so I'm not surprised you got this error. I suggest the following:
- Delete "${INSTALL_DIR}/dnscrypt-proxy" because the file that's there has the wrong cpu arch so it can't be executed to find out its version.
- Download the correct cpu arch for your system and install it back to that location.
- Use the latest version of the update script on the wiki page you linked (which was there before you posted this issue) and then you only need to change the cpu arch in 1 place at the top and won't make this mistake again.

**Comment by Kylvan-8** [comment]
e

> 
> 
> > Sadly the cpu_arch format was bad and now i get those errors :
> > `scripts/dnscrypt-proxy-update.sh: 17: scripts/dnscrypt-proxy-update.sh: /opt/dnscrypt-proxy/dnscrypt-proxy: Exec format error`
> 
> The script you showed mentions both `arm` and `x86_64`, so I'm not surprised you got this error. I suggest the following:
> 
>     * Delete "${INSTALL_DIR}/dnscrypt-proxy" because the file that's there has the wrong cpu arch so it can't be executed to find out its version.
> 
>     * Download the correct cpu arch for your system and install it back to that location.
> 
>     * Use the latest version of the update script on the wiki page you linked (which was there before you posted this issue) and then you only need to change the cpu arch in 1 place at the top and won't make this mistake again.

Thank you Welwood for your answer ! The little problem i have with this is that, i use a raspeberry pi 3 and i can't find the one that is working for me :/

**Comment by welwood08** [comment]
I don't have a Raspberry Pi 3 to test for myself, but I'm not sure why it's so difficult - you should be able to get a clue from running `uname -m`. From a quick web search it looks like you probably want `arm64` (although if your OS isn't 64bit then probably `arm` instead) - there's no harm in just trying until you find the one that runs. What you have now is probably the `x86_64` version and that clearly doesn't run.

**Comment by Kylvan-8** [comment]
> 
> 
> I don't have a Raspberry Pi 3 to test for myself, but I'm not sure why it's so difficult - you should be able to get a clue from running `uname -m`. From a quick web search it looks like you probably want `arm64` (although if your OS isn't 64bit then probably `arm` instead) - there's no harm in just trying until you find the one that runs. What you have now is probably the `x86_64` version and that clearly doesn't run.

This is my arch : armv7l from uname -m. That's why i've got problems to find the right cpu arch for dnscrypt-proxy

**Comment by welwood08** [comment]
So what have you tried after that? A quick search using that armv7l clue reveals it is not 64bit so you don't want `arm64`, leaving the other option I mentioned...
