### ISSUE TITLE
Installation on OpenWRT: update to dnscrypt-proxy2

### ISSUE THREAD

**Issue by erotavlasme** [DNSCrypt/dnscrypt-proxy#1348]
Hi,
I would be good to have an [updated guide](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-OpenWRT) about how to install dnscrypt-proxy2 on openWRT. The [dnscrypt-proxy](https://github.com/openwrt/packages/tree/openwrt-19.07/net/dnscrypt-proxy) is not maintained and old. Moreover, I found that there is unofficial [luci-app-dnscrypt-proxy2](https://github.com/peter-tank/luci-app-dnscrypt-proxy2).

**Comment by jedisct1** [comment]
I'm a little bit confused here, because the documentation [link](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-OpenWRT) you sent is for `dnscrypt-proxy` v2.

And this is a Wiki page, so if something doesn't seem accurate or up-to-date, feel free to make the required changes to it.

**Comment by erotavlasme** [comment]
Well, but the guide does not use openWRT packages for dnscrypt-proxy and luci Web interface.

**Comment by jedisct1** [comment]
Because you may have some information that the people who wrote that people didn't have :)

Looking forward to your updates!

**Comment by hugepants** [comment]
The [documentation](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-OpenWRT) is already up to date for a **manual installation**. This is [optimised ](https://github.com/DNSCrypt/dnscrypt-proxy/issues/776)to use the latest binaries and to avoid dns leaks, loops, etc.

This guide does not use the OpenWRT packages because, as you've noted, they are out of date.
It also doesn't use the unofficial LuCI app as it's a different implementation.

The manual installation documented here has proven to work very well, but you're free to use any implementation that works for you.

**Comment by jedisct1** [comment]
Thank you @hugepants for the great work you did on that documentation!

**Comment by erotavlasme** [comment]
> The [documentation](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-OpenWRT) is already up to date for a **manual installation**. This is [optimised ](https://github.com/DNSCrypt/dnscrypt-proxy/issues/776)to use the latest binaries and to avoid dns leaks, loops, etc.
> 
> This guide does not use the OpenWRT packages because, as you've noted, they are out of date.
> It also doesn't use the unofficial LuCI app as it's a different implementation.
> 
> The manual installation documented here has proven to work very well, but you're free to use any implementation that works for you.

As I wrote before, dnscrypt-proxy is not maintained and old while [dnscrypt-proxy2](https://github.com/openwrt/packages/tree/openwrt-19.07/net/dnscrypt-proxy2) is updated to the [latest release](https://github.com/DNSCrypt/dnscrypt-proxy/releases). At the moment there is not any official luci GUI package, just this [one](https://github.com/peter-tank/luci-app-dnscrypt-proxy2).
I think that once there will be a luci package for dnscrypt-proxy2, it would be very user to have an updated guide since using openWRT package is simpler and fast than command line installation for an average user.

**Comment by hugepants** [comment]
@erotavlasme 
Thanks for alerting me to the updated [opkg package](https://github.com/openwrt/packages/tree/openwrt-19.07/net/dnscrypt-proxy2). I have updated the documentation to include this and I refreshed the whole document for clarity.

I agree that an official LuCI app would be good for novice users, but this is all we have at the moment.
