### ISSUE TITLE
looking for 'backup' not load-balancing..  (is 'first' what I'm looking for?)

### ISSUE THREAD

**Issue by bcookatpcsd** [DNSCrypt/dnscrypt-proxy#1349]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [X] Other

## Description
Using an upstream encrypted dns provider (example dns.io)

They have two doh nodes I'm using, doh.a.dns.io and doh.b.dns.io.. my provider was having a peering issue and could not reach them, so I added doh.crypto.sx as the third server_name, and when doh.a and doh.b were NETWORK_ERROR or PARSE_ERROR doh.crypto.sx would work.. (this was great)

When the peering issue was being worked on.. occasionally it would work, but it would still check crypto.sx.. even though it looked like dns.a or dns.b had already answered.. 

If I wanted to try (dns.a and dns.b) and if they fail then use doh-crypto-sx.. would that be the 'first' lb_strategy?

Is that how it would work? 

server_names = ['dns.a', 'dns.b', 'doh-crypto-sx']
lb_strategy = 'first'

Would I need to change lb_estimator as well? 

And what is host 192.168.10.100 doing here? asking the same question *twice*?
line 1 is the question and line 2 is the same question again being answered via cache, right?
1: [2020-06-02 14:31:27]	192.168.10.100	min-api.cryptocompare.com	A	PASS	22ms	dns-280
2: [2020-06-02 14:31:27]	192.168.10.100	min-api.cryptocompare.com	A	PASS	0ms	-

Same thing here.. 3 is the question, and 4 is the cached answer, but it's immediately asked.. 
3: [2020-06-02 14:31:53]	192.168.10.100	level3.blizzard.com	A	PASS	28ms	dns-280
4: [2020-06-02 14:31:53]	192.168.10.100	level3.blizzard.com	A	PASS	0ms	-

This 5 is the question (and recursed) then the quadA (blocked), line 6, and the answer from cache being served on line 7.. (right?)
5: [2020-06-02 14:34:52]	192.168.20.32	ips1.unifi-ai.com	A	PASS	18ms	dns-280
6: [2020-06-02 14:35:19]	192.168.20.254	ips1.unifi-ai.com	AAAA	SYNTH	1ms	-
7: [2020-06-02 14:35:19]	192.168.20.254	ips1.unifi-ai.com	A	PASS	1ms	-

In trying to get more information about NETWORK_ERROR or PARSE_ERROR in the logs I saw a bunch of duplicate queries being asked at the same time.. 

Thank you in advance for your time and patience..

**Comment by jedisct1** [comment]
Yes, `first` is the closest to what you want. Or add a 4th server and use the default `p2`.

`0ms` and the absence of a resolver name (`-` instead of `dns-280`) indeed means that the second time was straight from the cache.

**Comment by bcookatpcsd** [comment]
so I have it currently as:

server_names = ['dns-280', 'dns-300', 'doh-crypto-sx']

I've not seen doh-crypto come up in the logs.. but 280 and 300 are answering the questions.. 

Thank you for your response.
