### ISSUE TITLE
[android] GMT/UTC timestamps in dnscrypt-proxy logs instead of system time

### ISSUE THREAD

**Issue by ghjkl99** [DNSCrypt/dnscrypt-proxy#1351]
Rooted LOS 14.1 (android 7.1.2) device, dnscrypt-proxy 2.0.42, latest TZ and ICU data 2020a (/data/misc/zoneinfo/tzdata, /system/usr/share/zoneinfo/tzdata):

There are GMT/UTC timestamps in dnscrypt-proxy logs instead of system time according to device timezone (tried for different timezones). Device shell command-line "date" correctly returns time for the device timezone. "getprop" has "persist.sys.timezone" set to device timezone. Thanks.

**Comment by jedisct1** [comment]
golang/go#20455

**Comment by ghjkl99** [comment]
thanks jedisct1, but starting dnscrypt-proxy from the command-line after setting TZ accordingly, still shows UTC/GMT timestamps. please suggest if i am missing something ? thanks.
