### ISSUE TITLE
`-check` should not try to bind listening sockets

### ISSUE THREAD

**Issue by jumpsmm7** [DNSCrypt/dnscrypt-proxy#1354]
## *Who* is the bug affecting?
Users running dnscrypt-proxy -check -config to check .toml file.

## *What* is affected by this bug?
dnscrypt-proxy claims the listening address is already bound to (when dnscrypt-proxy is using it).

## *When* does this occur?
when running dnscrypt-proxy -check -config to check .toml file.

## *Where* does it happen?
On  Linux-Arm and linux-arm64 devices.

## *How* do we replicate the issue?

Just run dnscrypt-proxy -check -config to check .toml file.

## Expected behavior (i.e. solution)
dnscrypt proxy properly identify bind address. 

## Other Comments
This issue did not start occurring until the new release. After updating to 2.0.43, dnscrypt-proxy refuses to bind to available addresses.

**Comment by jumpsmm7** [comment]
Thanks for a quick response!
Will this get built in as a patch for the release?

**Comment by jedisct1** [comment]
It will be in the next release :)
