### ISSUE TITLE
tls_client_auth key in dnscrypt-proxy.toml prevents service starting

### ISSUE THREAD

**Issue by hcsas** [DNSCrypt/dnscrypt-proxy#1355]
## *Who* is the bug affecting?
Users creating config from example template

## *What* is affected by this bug?
Service fails to start

## *When* does this occur?
The tls_client_auth key is present in the config file used by the service once updated to 2.0.43

## *Where* does it happen?
Raspberry pi zero

## *How* do we replicate the issue?

dnscrypt-proxy -check returns unsupported key in configuration file (tls_client_auth) and service fails to start following latest update

## Expected behavior (i.e. solution)
comment out [tls_client_auth] line in config file.

sudo systemctl daemon-reload
sudo systemctl start dnscrypt-proxy

Service starts correctly

## Other Comments
Breaks existing setups unless user intervenes and makes changes

**Comment by hcsas** [comment]
Unintended consequence of [3e264b9](https://github.com/DNSCrypt/dnscrypt-proxy/commit/3e264b9da9ae2cf7895a53f93b69b71787ad9059) I should think

**Comment by jedisct1** [comment]
Thank you!
