### ISSUE TITLE
How to forward the specified domain query to the specified DOH server?

### ISSUE THREAD

**Issue by cnlog** [DNSCrypt/dnscrypt-proxy#1356]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ *] Other

## Description
How to forward the specified domain query to the specified DOH server?

**Comment by jedisct1** [comment]
Forwarding can only be done to a regular DNS server.

But I guess you can run two `dnscrypt-proxy` instances with different configurations, forwarding some domains to each other.

**Comment by riobard** [comment]
@jedisct1 Would you consider adding the feature for a single instance of `dnscrypt-proxy` to select which upstream DoH/dnscrypt servers to query based on domains?
