### ISSUE TITLE
dnscrtpt-proxy 2.0.43 update not available via homebrew!

### ISSUE THREAD

**Issue by gcpmusic** [DNSCrypt/dnscrypt-proxy#1359]
**dnscrtpt-proxy 2.0.43 and 2.0.44 update not available via homebrew!**

Any reason?
Thank you.

**Comment by jedisct1** [comment]
https://github.com/Homebrew/homebrew-core/pull/55998

**Comment by michael1900** [comment]
So, what is the solution? I can't understand.. when we will last version on brew?

**Comment by jedisct1** [comment]
I don't know  🤷

`dnscrypt-proxy` and `homebrew` are unrelated projects.

The `homebrew-core` repository is the place to submit updates to for Homebrew formulae, to watch for proposed updates (and an update to 2.0.44 was just submitted), and to provide Homebrew-related feedback to.

**Comment by gcpmusic** [comment]
Finally showing up and updated. Thank you.
