### ISSUE TITLE
dnscrypt-proxy Website problem

### ISSUE THREAD

**Issue by haraldj** [DNSCrypt/dnscrypt-proxy#136]
Hello,

and sorry for using the bugtracker of the program to report a problem with your website but your certificate is not valid anymore so at least the Debian checker doesn't know you have a new program version :-(.

Kind regards
Harald

**Comment by jedisct1** [comment]
Works well here... the certificate is fine.

https://dnscrypt.info/

You may have to wait for a Debian package for a long time, so you'd better just download a precompiled binary from here.

**Comment by haraldj** [comment]
Thanks for the information Debian still lists the .org page.
