### ISSUE TITLE
Update 2.0.43 .de websites not working/log not working

### ISSUE THREAD

**Issue by bones78** [DNSCrypt/dnscrypt-proxy#1360]
I have updates from .42 to .43 on the raspberry pi. On version .43 many .de domains are not resolved. If I switch back to .42 everything works fine.
In the .43 version the logfile is not written.
I have tested both issues with the old .toml file and with a new one.

**Comment by jedisct1** [comment]
Can you reproduce this with the default configuration?

Can you provide an example of a query (along with the resolver it is sent to) that returns an unexpected response, along with the response you got and the relevant entry in the query log?

**Comment by bones78** [comment]
the default configuration worked. In the log file (I enabled log_file = 'dnscrypt-proxy.log') everything is fine.
I have started with a new config and had step by step made my changes. Now everything seems to work, I cannot reproduce it anymore with the new version, so everything is fine.
