### ISSUE TITLE
[Having Issue] Problem with DNSCrypt local IP

### ISSUE THREAD

**Issue by poqdavid** [DNSCrypt/dnscrypt-proxy#1361]
Ever since I updated Windows to version 2004 Windows doesn't accept the localhost IP for the DNS like doesn't ping it is this a bug with DNSCrypt or its Windows

**Comment by jedisct1** [comment]
Can you explain, step by step, in non-technical terms, and in a way that is reproducible on a new Windows installation: what you did, what happened, and what should have happened?

**Comment by poqdavid** [comment]
Ok well back when I was on Windows version 1903 everything was fine and smooth
then when I update to Windows version 2004 it looks like Windows is failing to ping the DNS IP in order to detect the connection and it shows this image on taskbar https://i.imgur.com/yzuOEDH.png
this is my config https://hastebin.com/konorehule.ini
and this one is my IP setting https://i.imgur.com/8C8Yhl2.png

**Comment by jedisct1** [comment]
> Windows is failing to ping the DNS IP

So, what does the `ping` command print? Does it stall or does it print an error message?

**Comment by poqdavid** [comment]
Well no the ping command is fine but I assumed that also Windows pings the DNS IP/Port to check for the DNS

**Comment by jedisct1** [comment]
Maybe [this](https://github.com/dnscrypt/dnscrypt-proxy/wiki/Installation-Windows#troubleshooting) can help?

**Comment by poqdavid** [comment]
wow thanks that worked
also are these things here https://github.com/dnscrypt/dnscrypt-proxy/wiki/Windows-NCSI recommended to do?
and would this localhost.localdomain change since i use 127.0.0.100

**Comment by jedisct1** [comment]
If everything works as expected, I wouldn't change anything :)

**Comment by poqdavid** [comment]
Oh ok :) thanks
