### ISSUE TITLE
dnscrypt-proxy TOML file

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1364]
Hiya

what would cause error dnscrypt-proxy TOML file cannot load tom? when opening up simple dns client gui and the dnscrypt client proxy service?

the service it self started and stopped fined without error but no internet
simple dnscrypt client refused to load with error cannot load tom

everything worked fine for a year then abruptly everything went permanently dead tonight i tried deleting everything and restoring from usb flash drive and same errors and no internet

when i opened network adapter and tried to change dns from 127.0.0.1 to anything to try and get internet working again it would always reset back to 127.0.0.1 eventually i had to uninstall network adapter and reinstall network adapter to get internet working again but internet is only currently working with auto dns and not dnscrypt proxy

**Comment by alisonatwork** [comment]
Did you recently update to Windows 10 build 2004? We heard on #1361 that it might reset the DNS policies. You can try troubleshooting advice: https://github.com/dnscrypt/dnscrypt-proxy/wiki/Installation-Windows#troubleshooting

**Comment by ghost** [comment]
how many digits can dnscrypt proxy read?
it seems to error out after 10 digits with cannot load dnscrypt proxy toml
nothing is mentioned here for lowest and maximum settings
https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml
is there a way to set cache size to unlimited?
https://social.technet.microsoft.com/Forums/windows/en-US/8f61cd7e-1803-4273-b8a0-f82358ec0771/dns-server-cache-size?forum=winserverNIS

i am on build 1607
i think the resetting was caused by this
## Always use the fallback resolver before the system DNS settings.
ignore_system_dns = true

microsoft is 1 day dnscrypt proxy is 4 hours?
https://social.technet.microsoft.com/Forums/azure/en-US/e84228ca-95ff-4b22-b478-a8cb60c87c2d/how-often-dns-clients-come-to-dns-server-to-update-their-records-timemtaps-?forum=winserverNIS

microsoft is 900 dnscrypt is 600?
https://docs.microsoft.com/en-us/windows-server/networking/dns/troubleshoot/disable-dns-client-side-caching

comparing settings, are settings not universal?

i think it may have been to many digits for the one error cannot load dnscrypt proxy toml but not sure why it worked prior and now only error

**Comment by jedisct1** [comment]
The default values are reasonable, and things are unlikely to get noticeably faster by tweaking them.

More importantly, if you ever change something, be sure to understand what it does and why you need  that change. 

Adding an arbitrary number of zeros to a value so that a resource is set to take up to terabytes of RAM or expire in 4 million years is bound to break. It may work by accident, and break after an upgrade because it didn’t make sense to start with.

**Comment by ghost** [comment]
it didn't break after an upgrade i never tried for a million years nothing was changed for 4 months to a year an update did not break it on windows or dnscrypt
you never mentioned what the minimum is or the maximum, do you even know?
often you respond with no answers 
where are you getting one terabyte from?
https://social.technet.microsoft.com/Forums/azure/en-US/6e389462-57bd-412e-a2dc-b00ceff22e7e/dns-server-memory-usage?forum=winserverNIS
