### ISSUE TITLE
[Regression] Failed to drop privileges on macOS

### ISSUE THREAD

**Issue by x13a** [DNSCrypt/dnscrypt-proxy#1367]
## *Who* is the bug affecting?

From version 2.0.43 dropping privileges on macOS not working.

## *What* is affected by this bug?

 Executing is failed with:

`[FATAL] Dropping privileges is not supporting on this operating system. Unset `user_name` in the configuration file.`

## *When* does this occur?

When `user_name = 'nobody'` in configuration file.

## *Where* does it happen?

On start.

## *How* do we replicate the issue?

1. Install version 2.0.43 or newer.
2. Set: `user_name = 'nobody'` in `/usr/local/etc/dnscrypt-proxy.toml`.
3. `sudo /usr/local/sbin/dnscrypt-proxy -config /usr/local/etc/dnscrypt-proxy.toml`

## Expected behavior (i.e. solution)

`dnscrypt-proxy` drops privileges and runs under `nobody`.

## Other Comments

Version 2.0.42 is working correctly.

**Comment by jedisct1** [comment]
This is intentional.

Dropping privileges is unreliable on macOS (at least Catalina), at least when doing it the same way as on other operating systems.

Removing the exception for macOS makes a thread die with

```text
fatal error: signal_recv: inconsistent state
```

Most of the time the proxy still seems to be somewhat responding to queries, but sometimes it doesn't go very far:

```text
fatal error: signal_recv: inconsistent state

goroutine 7 [running]:
runtime.throw(0x1595d68, 0x1f)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc000052fa0 sp=0xc000052f70 pc=0x1034822
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/sigqueue.go:140 +0x104 fp=0xc000052fc0 sp=0xc000052fa0 pc=0x104b8b4
os/signal.loop()
	/usr/local/Cellar/go/1.14.3/libexec/src/os/signal/signal_unix.go:23 +0x22 fp=0xc000052fe0 sp=0xc000052fc0 pc=0x13ca352
runtime.goexit()
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x10646d1
created by os/signal.Notify.func1
	/usr/local/Cellar/go/1.14.3/libexec/src/os/signal/signal.go:127 +0x44

goroutine 1 [chan receive]:
github.com/kardianos/service.(*darwinLaunchdService).Run.func1()
	/Users/j/src/dnscrypt-proxy/vendor/github.com/kardianos/service/service_darwin.go:247 +0xbd
github.com/kardianos/service.(*darwinLaunchdService).Run(0xc00000e400, 0xc00012e900, 0x0)
	/Users/j/src/dnscrypt-proxy/vendor/github.com/kardianos/service/service_darwin.go:248 +0xbe
main.main()
	/Users/j/src/dnscrypt-proxy/dnscrypt-proxy/main.go:107 +0xced

goroutine 6 [runnable, locked to thread]:
syscall.SlicePtrFromStrings(0xc0002002c0, 0x16, 0x16, 0xc0000a7c80, 0x3, 0x3, 0x0, 0x0)
	/usr/local/Cellar/go/1.14.3/libexec/src/syscall/exec_unix.go:84 +0x2bf
syscall.Exec(0xc0000aa500, 0x39, 0xc0000a7c60, 0x2, 0x2, 0xc0002002c0, 0x16, 0x16, 0xc0000ef0e0, 0x10c76f1)
	/usr/local/Cellar/go/1.14.3/libexec/src/syscall/exec_unix.go:271 +0xe9
golang.org/x/sys/unix.Exec(...)
	/Users/j/src/dnscrypt-proxy/vendor/golang.org/x/sys/unix/syscall_unix.go:410
main.(*Proxy).dropPrivilege(0xc00012e900, 0xc0000ba932, 0x6, 0xc0000dfb40, 0x2, 0x2)
	/Users/j/src/dnscrypt-proxy/dnscrypt-proxy/privilege_others.go:89 +0x9c5
main.ConfigLoad(0xc00012e900, 0xc000078500, 0x0, 0x0)
	/Users/j/src/dnscrypt-proxy/dnscrypt-proxy/config.go:582 +0x1a41
main.(*App).AppMain(0xc00007f500)
	/Users/j/src/dnscrypt-proxy/dnscrypt-proxy/main.go:127 +0x3c
main.(*App).Start.func1(0xc00007f500)
	/Users/j/src/dnscrypt-proxy/dnscrypt-proxy/main.go:118 +0x2b
created by main.(*App).Start
	/Users/j/src/dnscrypt-proxy/dnscrypt-proxy/main.go:117 +0x49
```

**Comment by jedisct1** [comment]
There has to be a way to fix this, but I really don't know how :(

**Comment by jedisct1** [comment]
Removing `signal.Notify(sigChan, syscall.SIGTERM, os.Interrupt)` from `kardianos/service/service_darwin.go` seems to prevent this but I don't know what the implications are.

It's probably there for a reason :)

**Comment by jedisct1** [comment]
`sleep()`ing before wiring the signal handler also seems to help, but that's just random fiddling.

Maybe the handler should only be set in the parent and not in the child or the other way round.
