### ISSUE TITLE
DNSCrypt Proxy stops working on Windows after a few months

### ISSUE THREAD

**Issue by lolcocks123** [DNSCrypt/dnscrypt-proxy#1368]
Hello,

I have installed DNSCrypt Proxy on a few computers but I have noticed on 4 computers so far that DNSCrypt Proxy stops working after about 3 or 4 months. 

I have setup my own DNSCrypt server which is working completely fine with DNSCrypt Proxy on other computers. I even restarted the server and it's completely fine, there's nothing else running on the server.

On these computers, I need to manually uninstall the service as an Administrator and then reinstall the server as an Administrator.

Only then it will start working again.

Is there any way I can help you to further diagnose this issues? I would like to help but don't know how I can.

Thank you and regards,
Lolcocks.

**Comment by jedisct1** [comment]
Can you define `working`?

**Comment by lolcocks123** [comment]
> 
> 
> Can you define `working`?


I apologize about posting this issue.

The issue was that, these laptops' CMOS battery died, which reset the time. 
To get the correct date and time, Windows will try to connect to the NTP server. But that won't work because Windows uses time.Windows.com and to resolve it, Windows will first contact my DNS Crypt server which will deny the request because the time is incorrect.

So I now need to change the CMOS battery or assign an IP address as the NTP server.

Sorry if I wasted your time @jedisct1.

**Comment by jedisct1** [comment]
Ouch, having to replace these CMOS batteries is indeed something we always forget about.

**Comment by lolcocks123** [comment]
> 
> 
> Ouch, having to replace these CMOS batteries is indeed something we always forget about.

And what are the odds. I have 40 laptops in the office of which I use DNSCrypt on only 6. And the CMOS Battery failed on 4 of those 6 laptops. None of the other 34 laptops' batteries failed even though all of them were purchased on the same date.

What are the odds.

It's like the universe loves to waste my time. But then again I did learn something. :)
