### ISSUE TITLE
Restarting dnscrypt-proxy while Firefox is running

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1369]
Hi,

I'm running flawlessly dnscrypt-proxy 2.0.44 / Windows 7 (x64)
Saying it runs flawlessly is putting it mild, in fact it's running incredibly well.
I have a basic, simple question in mind:

Given dnscrypt-proxy when started/restarted installs a Firefox-specific workaround for Firefox:
`[NOTICE] Firefox workaround initialized`
I'd like to know if I should close Firefox when I decide to restart dnscrypt-proxy.

Thanks!

**Comment by jedisct1** [comment]
Hi!

I don’t think this is necessary. 

Firefox only does the check only when you start it, and when your IP address changes.

**Comment by ghost** [comment]
> Firefox only does the check only when you start it, and when your IP address changes.

OK, thanks. Of course I could just test but because I'm not techie-savvy I remain particularly aware of results which wouldn't appear immediately, leading me to believe all is fine when a drama could be silently in preparation, lol

I'll close the door as my question won't initiate a revolution!
