### ISSUE TITLE
Consider readding dropping privileges on macOS

### ISSUE THREAD

**Issue by thesamesam** [DNSCrypt/dnscrypt-proxy#1371]
Dropping privileges on macOS was removed in https://github.com/DNSCrypt/dnscrypt-proxy/commit/b6b7ed3a67aee7d1af1905a062236493fca0ae8d (2.0.43) but this works fine for me.

Could we possibly have a flag to force this, or an e.g. Go bug report we can follow?

**Comment by jedisct1** [comment]
When it doesn’t crash at startup, the application remains in a weird state that can have security implications, so it would be irresponsible to keep doing this.

The issues seems to be a race between a channel that receives a termination signal and the termination of the parent process when forking.

I don’t think this is a bug in Go. Maybe in the `services` module, but it wasn’t really designed to be used with user id switching.

Reliable user id switching has always been an unsolved problem in Go.

**Comment by jedisct1** [comment]
Another possible explanation is that at least on macOS, channels require file descriptors, so when we reassign them:

```go
    for i := range fds {
        if err := unix.Dup2(int(fdbase+uintptr(i)), int(i)+3); err != nil {
            dlog.Fatalf("Unable to reassign descriptor: [%s]", err)
        }
    }
```

The file descriptor of the signal handler is replaced by a socket.

**Comment by jedisct1** [comment]
Maybe 317cd4fb53c2df9494326adc3973691e92bb060c fixes the issue.

Give it a try.

This is a little bit hacky and ugly, but it should be okay as long as we don't add too much things requiring file descriptors before the user id switch.

**Comment by thesamesam** [comment]
Thank you for this. I didn't think for a second that it was done out of haste -- I package dnscrypt-proxy downstream in Gentoo and I'm a big fan.

I'll try out the fix and report back, but either way, I appreciate the effort & explanation of the problem.
