### ISSUE TITLE
Is that possible to add a configuration like [Client IP]? 

### ISSUE THREAD

**Issue by mervynsword** [DNSCrypt/dnscrypt-proxy#1374]
Hi, I am a dnscrypt-proxy user living in China. As you know, the chinese government is blocking a lot of websites and IPs, so I have to use a proxy every second in my life.

The problem is the DNS, let's say when I'm browsing youtube, the DNS server resolves to the IP address that is closest to my location, also It's the IP address of the Hong Kong server, but my proxy server is located in the US. So my internet connection when browsing youtube is the equivalent of going back and forth twice around the Pacific Ocean, and the performance is very poor. I have also tried setting up an US HTTP proxy for dnscrypt-proxy, but this again significantly degrades the performance of the DNS resolution performance.

So I wonder if it is possible to add a [client ip] config option to use a separately set IP address to make a request to the upstream DNS server during DNS resolution, so as to get the IP address resolution result that best matches the US proxy server while ensuring DNS resolution performance?

**Comment by jedisct1** [comment]
Do you mean setting the edns-clientsubnet option?

**Comment by mervynsword** [comment]
In fact, I want the DNS providers use the IP of my proxy server, not my IP address.

Let's say my local IP address is 2.2.2.2 and my proxy server's IP address is 3.3.3.3, I hope the cloudflare dns server resolves according to 3.3.3.3 not 2.2.2.2. So dnscrypt-proxy has to provide a fake IP address(3.3.3.3 in this case) to cloudflare dns server.

Maybe this is a stupid question, I'm just wondering if it's technically feasible.

**Comment by jedisct1** [comment]
`dnscrypt-proxy` supports SOCKS proxies, so you can configure it to send DNS queries via your proxy.
