### ISSUE TITLE
Public Resolvers multiple stamps for faelix

### ISSUE THREAD

**Issue by mpadilla2** [DNSCrypt/dnscrypt-proxy#1378]
As noted in the subject dnscrypt is failing due to multiple stamps in the faelix entries. Indeed when I view public-resolvers.md all faelix entries have duplicated sdns. This md was pulled directly from dnscrypt.info. Please fix the md and/or advise on a workaround as we have no internet now.

**Comment by jedisct1** [comment]
> Please fix the md

That's a bit harsh. You decided to stick to an antique version.
