### ISSUE TITLE
Windows 10 not detecting network connectivity ...

### ISSUE THREAD

**Issue by privacyguy123** [DNSCrypt/dnscrypt-proxy#1379]
... but there definitely is as my browsers and other programs work. I can't get my head around this bug, my Ethernet symbol in the bottom right is showing disconnected and I've been able to pin point it down to DNSCrypt.

Anybody else noticed this bug?

**Comment by jedisct1** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-Windows#troubleshooting

**Comment by privacyguy123** [comment]
Fixed!
