### ISSUE TITLE
Use cobra/viper for configuration and cli switches and logrus for logging

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#138]
After looking over [config.go](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/config.go), I noticed that configuration/switches are implemented manually.

Instead, I propose switching to cobra/viper because it's a lot more robust than the current manual implementation: [https://github.com/spf13/viper](https://github.com/spf13/viper), and [https://github.com/spf13/cobra](https://github.com/spf13/cobra).

[Logrus](https://github.com/sirupsen/logrus) is also more robust logger than your custom `dlog`; supporting custom output formatting (to send to ELK, statsd, etc).

I am not trying to knock your implementation; I've been using `dnscrypt-proxy` for along time; I'm just trying to help with improvements to 2.0 as I've been programming in Go for 5+ years now. If you are OK with this, let me know and I can attempt to do some migrations to those projects in my free time; and send over a PR.

**Comment by jedisct1** [comment]
Hi!

And thanks a lot for the pointers! These projects can indeed be really convenient. I don't know if I will have the opportunity to write software in Go again, but I'll definitely keep these in mind.

In the context of dnscrypt-proxy, adding these extra dependencies would not solve any open problems and look a bit overkill, though.

But your experience in Go is badly needed, especially for https://github.com/jedisct1/dnscrypt-proxy/issues/135 , https://github.com/jedisct1/dnscrypt-proxy/issues/100 and https://github.com/jedisct1/dnscrypt-proxy/issues/58 .

The last one is probably really trivial, all the bits are here and are well documented, by with virtually no experience in Go, I wasn't able to connect the dots.
