### ISSUE TITLE
Firefox local DoH and HTTP2

### ISSUE THREAD

**Issue by Kedstar99** [DNSCrypt/dnscrypt-proxy#1380]
Hello,

I am currently running dnscrypt-proxy with the.local doh stuff. However, I noticed when I was looking at about:networking on firefox that this server is running http/1.1 rather than http/2. The reason for this is likely because of this commit here.

https://github.com/DNSCrypt/dnscrypt-proxy/commit/3ef9ec8732d53f305d8465b7a2ec2d9fb0f3f8f8#diff-61451a1905c6403d65a90f4cd3cbae9d

Specifically the aspect which defines TLSNextProto to the noh2 defined there.

According to https://golang.org/pkg/net/http/, this explicitly disables http/2 support.

Was there a particular reason for explicitly using http/1.1 as over http/2? 

Thanks in advance for building this awesome project.

Kind regards

**Comment by jedisct1** [comment]
Indeed, HTTP/2 was explicitly disabled for local DoH.

I noticed recurrent reliability issues when using Firefox with ESNI enabled, and disabling HTTP/2 significantly reduces these.

Go HTTP/2 code was still fairly new back then, and Firefox ESNI code was, ahem, the same as it is today, but it may be worth checking if this is still an issue.

**Comment by Kedstar99** [comment]
I did a quick build/test with http2 on the latest go version using HTTP/2 removed and it seems to work fine/stable for me. At least on my raspberry pi 4B.

No crashes after visiting several sites, including several cloudflare specific ones using ESNI too.

Is there anything in particular I should be specifically looking for to trigger a crash?

**Comment by jedisct1** [comment]
It's not a crash, but websites whose addresses suddenly cannot be resolved any more, or Firefox returning blank pages.

If things are more stable now, this is great!

**Comment by Kedstar99** [comment]
I have been running it non-stop for a  day now. Multiple devices all with firefox + esni. I haven't seen a blank page, or resolution error.

**Comment by Kedstar99** [comment]
Sorry, can I ask why the commit was reverted or is this a random github issue?

Actually nvm, I notice that the commit revert doesn't exist anywhere.
