### ISSUE TITLE
dnscrypt suddenly stopped working

### ISSUE THREAD

**Issue by sgjohnson1981** [DNSCrypt/dnscrypt-proxy#1381]
Started machine this morning and couldn't resolve anything. Downloaded most recent dnscrypt-proxy file and replaced my outdated one. Updated the config file also from new template from tarball. Restarted service. Still not working. When I run dnscrypt-proxy directly from folder it says Unable to load configuration file, even when using config flag and pointing to the file.

EDIT: Sorry, forgot to include machine info. I'm running Debian 10.3. I have a dual boot setup with Windows 7 on another partition. I run Simple DNSCrypt on that OS. It seems to be working fine.

**Comment by jedisct1** [comment]
There is no `Unable to load configuration file` string in the application.

**Comment by sgjohnson1981** [comment]
Forget it. Going back to Windows 7.
