### ISSUE TITLE
Delays in reconnection after reboot and/or wakeup from sleep (macOS)

### ISSUE THREAD

**Issue by emikaadeo-git** [DNSCrypt/dnscrypt-proxy#1382]
Hi,
I think this issue is related to #1040 which is closed but not solved.
On every reboot and/or wake up from sleep, there's always a 25-30 seconds delay in reconnection.
I'm using dnscrypt-proxy with `[static]` server and `[anonymized_dns]`
In `system.log` there are multiple entries with this:
`com.apple.xpc.launchd[1] (homebrew.mxcl.dnscrypt-proxy): This service is defined to be constantly running and is inherently inefficient.`

dnscrypt-proxy v2.0.44
macOS Catalina 10.15.5

**Comment by jedisct1** [comment]
`This service is defined to be constantly running and is inherently inefficient` just means that the service is running constantly. This is expected :)

**Comment by emikaadeo-git** [comment]
> `This service is defined to be constantly running and is inherently inefficient` just means that the service is running constantly. This is expected :)

Ok, thanks for clarify this. But what about those delays? This is also expected ?

**Comment by jedisct1** [comment]
Unfortunately, I've never been able to reproduce this. My configuration is the example one, just with DoH servers disabled (`doh_servers = false`).

Can you reproduce it with the same configuration?

**Comment by emikaadeo-git** [comment]
> Unfortunately, I've never been able to reproduce this. My configuration is the example one, just with DoH servers disabled (`doh_servers = false`).
> 
> Can you reproduce it with the same configuration?

Yes. The issue persist. No change.
I would like to help to debug the issue. Any suggestions?

**Comment by jedisct1** [comment]
Try to list everything that happens after every wakeup from sleep, when using your router's DNS servers.

Then, try to do the same thing with a local DNS server, and compare both. This is likely to provide good insights about the root cause.

But how to do that, I have absolutely no idea.

**Comment by emikaadeo-git** [comment]
Some more tests and info.
It turns out that if I add my router's IP as a second DNS in `System Preferences` the issue disappears.
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-macOS#step-3---change-macos-dns-settings

![image](https://user-images.githubusercontent.com/56483380/86120591-e1a8f180-bad4-11ea-975f-840c757eebb5.png)

There's no delay when reboot or/and wake up from sleep.
If I remove second DNS address = delay appears.
Any idea why this happening?

**Comment by emikaadeo-git** [comment]
@jedisct1 
I gathered some more info from logs on my system, router and dnscrypt-proxy.
I think I know where the delay is. I did several reboots and every time it’s the same. Below is an example how it looks on the timeline:
`20:51:23` - this is the moment when dnscrypt-proxy starts. It shows:
```
dnscrypt-proxy 2.0.44
Network not available yet -- waiting...
```
`20:51:30` - this is the moment when my system is connected to router’s Wi-Fi network and got Internet connectivity (so it’s 7 seconds after dnscrypt-proxy starts)
`20:52:13` - this is the moment when dnscrypt-proxy is detecting that there is network connectivity. It shows:
```
Network connectivity detected
Now listening to 127.0.0.1:53 [UDP]
Now listening to 127.0.0.1:53 [TCP]
```
So there’s always ~43 seconds delay between my system’s network connectivity and dnscrypt-proxy knowing that there is network connectivity.

My `dnscrypt-proxy.toml` config file has:
```
netprobe_timeout = 60
netprobe_address = '9.9.9.9:53'
```

Can you help me?

**Comment by jedisct1** [comment]
Looking at query logs after a reboot, the first queries are for `captive.apple.com`. Maybe the system doesn't allow applications to use the network unless that name can be resolved?

You can always set `netprobe_timeout` to something low, even `0`, but this is going to cause a bunch of subsequent queries to fail.

**Comment by emikaadeo-git** [comment]
> Looking at query logs after a reboot, the first queries are for `captive.apple.com`. Maybe the system doesn't allow applications to use the network unless that name can be resolved?
> 
> You can always set `netprobe_timeout` to something low, even `0`, but this is going to cause a bunch of subsequent queries to fail.

@jedisct1 
I'm afraid that's not the case.
I was testing my system on others Wi-Fi networks. On those networks, my system's gain internet connectivity _before dnscrypt-proxy starts_ and then there is no problem/delay.
The problem occurs when system's gain internet connectivity _after dnscrypt-proxy starts_. Even when there is only (for example) 3 seconds delay between dnscrypt-proxy start and internet connectivity, dnscrypt-proxy always waits for internet connectivity for about ~50 seconds from start.
I assuming that `netprobe` process is responsible for checking internet connectivity? Are there any time intervals at which it checks?

Additionally, can you look at my [previous](https://github.com/DNSCrypt/dnscrypt-proxy/issues/1382#issuecomment-651734373) message?
Do you have any clue why adding my router's IP as a second DNS makes the problem go away?

**Comment by emikaadeo-git** [comment]
@jedisct1 
It looks like you were right. It turns out that the problem indeed lies in `captive.apple.com` or more specifically in `Captive Network Assistant`. This utility runs on every boot and causes delays (at least on my system) in network connectivity when trying to resolve `captive.apple.com`
Disabled this utility by running `sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -boolean false` solves the issue.
Tested on macOS Catalina 10.15.6
This info was very helpful: https://developer.apple.com/forums/thread/86589?answerId=273061022#273061022
