### ISSUE TITLE
[Question] DoH json format support?

### ISSUE THREAD

**Issue by SilmorSenedlen** [DNSCrypt/dnscrypt-proxy#1383]
Good day
Does dnscrypt-proxy support json formatted requests for integrated DoH server(like [Cloudflare](https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format/))?

**Comment by jedisct1** [comment]
No.

Encoding DNS records in JSON isn't part of DoH.

It was just an early experiment by Google (that, when it was announced, was considered an April fool's joke). 

Other, incompatible proposals to encode DNS as JSON have been made, and haven't been adopted by anyone.

JSON encoding would remain terribly inefficient for server-to-server communications anyway.

**Comment by SilmorSenedlen** [comment]
Thx for comment.
