### ISSUE TITLE
Anonymized-auto relay sorting

### ISSUE THREAD

**Issue by ReSearchITEng** [DNSCrypt/dnscrypt-proxy#1385]
## Is your feature request related to a problem?

Manually selecting relays means new added ones won't be taken into consideration without config change.
While some may want to have full control of which relays to use, others would like to automate this selection solely on delay.

## Describe the solution you'd like

Making this process dynamic, the same way selecting the fastest dns works now would be nice.

Doing all combinations of relays and dns servers is too much for both local process and would overload the relays.     
Maybe something like this is a reasonable way of doing it:
1. select top X fastest relays based on their delay.
2. for each of them, do the usual DNS selection based on filters as well as delay
3. select the top Y paths (relay+DNS server) which have the sum of both delays the smallest.

**Comment by jedisct1** [comment]
This is going to always pick servers and relays from the same network, or even on the same machine, making relaying useless.

**Comment by ReSearchITEng** [comment]
right, and I guess there is no way to exclude such "paths", as we cannot know when this situation happens, correct?
Maybe at least a tool to sort paths and we manually select which one to populate in the config?
Right now I am not aware of any elegant solution, even manual.

**Comment by jedisct1** [comment]
Can you define exactly what such a tool would do?

The latency between you and a relay may be small, but the one between that relay and an upstream server may be huge. While a relay with poorer latency relative to you may have a direct connection with the same server.

All the possible routes cannot be reasonably tested. And even if it were, doing it with a single query wouldn't mean much, as there can be significant latency variance between queries.

This is similar to optimal Internet routing, which is not a solved problem. The best we have is  people manually tweaking routes all day long.

It seems that trying to automate this would be complicated and would take a very long time to implement, just to save 5 minutes of manual testing. Add the fact that people may want this country, but not that one, and not the relay and the server in the same country, unless it's a neutral country, and not in different countries either if these countries are allies, and...

If you want to write such a tool, go ahead, there may be ways to do something useful. But just defining exactly what that tool would do and how is going to take time that I really can't afford to spend, especially this year.
