### ISSUE TITLE
Request for block details via HTTP API or HINFO query

### ISSUE THREAD

**Issue by DRSDavidSoft** [DNSCrypt/dnscrypt-proxy#1386]
### A context first
I'm working on a Web UI for managing DNS requests (along with some other network aspects), and so far I've been using something similar to `dig HINFO <domain> @<server-ip>` to detect if the domain is being blocked by DNSCrypt.

If it is, the response is something similar to:
```bash
$ dig HINFO example.com

;; ANSWER SECTION:
example.com.        3600    IN      HINFO   "This query has been locally blocked" "by dnscrypt-proxy"
```

This works great for detecting _wether_ a domain is being blocked, but it doesn't specify _why_ it was blocked.

## Is my feature request related to a problem?

I'm looking for a way to get some response as to why some domain is being blocked.

## Describe the solution you'd like

I'd like to purpose a way to retrieve the message when a domain is blocked, through either:
a) a standard HTTP request ("API")
b) a special DNS query

## Alternatives you've considered

By enabling `[blacklist] → log_file`, I can access the message when a certain domain is blocked:
```
qname:subdomain.example.com	message:*.example.com (alias for [something.com])
```

However, this is cumbersome as I need to watch for file changes, then parse the log file.

I'd like to purpose accessing the `message` field present in the logs, via either of the suggested methods above.

## Who will that feature be useful to?

Anybody who would like to query about a domain block details

## What have you done already?

My solution has been to parse the `blacklist`'s `log_file` so far.

## What are you going to contribute?

I'd like to help in testing and extending this feature; also helping in any area of implementation that I can.

## Postscript
Thanks for developing this software.  I have been using DNSCrypt on my network (together with Unbound, Tor, Privoxy, Squid and SoftEther) and It's been working wonderfully like a charm.

Its domain blocking works great and fast, better than the alternatives such as AdGuard Home or Pihole. I have a ~250mb domain list, and DNSCrypt + Unbound works great in this situation.  I have deployed it with the domain forwarding and cloaking features for both my home and workplace (in conjunction with Windows AD).

I really appreciate all the work and efforts you've put in DNSCrypt and I hope to continue seeing updates as they come.

**Comment by jedisct1** [comment]
Hi!

Parsing the query log still seems the best way to go IMHO, because it will let you also store WHEN something was blocked, which can be quite relevant for lists that keep changing.

One thing you can do is log not to a file, but to a pipe. That works. Create a named pipe with the `mkfifo` command, and `dnscrypt-proxy` can push data to it. Then, it should be pretty straightforward to parse the `LTSV` data and store it in something like a sqlite database.

You will get nice, constantly updated historical data that can be amazing to show in a web interface. Not only for blocks but also for queries.

**Comment by DRSDavidSoft** [comment]
Thanks for your response!

While the timestamp stored in the `LTSV` format is hugely beneficial for logging purposes, in this application is not needed and the `message` section would suffice, as the data is being gathered in real-time and in the other end I can log the timestamp of when the request was made.

I was not aware that the log can be outputted to a pipe! It'll really useful to use a pipe instead of watching for file activity. The `LTSV` format is also pretty easy to parse too.

A drawback to this method is that it complicates things a bit, it'd be even more awesome if `dnscrypt-proxy` had some native sqlite.mariadb connectivity.  Of course, I'd understand if you wouldn't want to bring the complexity into the codebase.

In addition to that, it wouldn't be a cross-platform solution as the pipes implementation on Windows differs quite a bit.  I'd also need to perform a second query after the `dig` one into the database to fetch the reason (and I'm a bit afraid if it wouldn't sync if scaled).

I really love the idea of having a real-time and constantly updated web interface, and I think this method fits well for the queries logging.  I have been working on a little ([yet unreleased](https://github.com/DRSDavidSoft/Openlists)) open-source project to display data and control `dnscrypt-proxy` over Web, so this is already a huge improvement.

However, for this project, I'd prefer it if I could access the message data when the initial query is being made.  I'm aware that [the current implementation](https://github.com/DNSCrypt/dnscrypt-proxy/blob/2dda74647de93e0adcaec0186a7bdfa1503e0150/dnscrypt-proxy/dnsutils.go#L71-L78) doesn't really make this an easy change, so I wouldn't want to push you for it.  But if with a simple change (such as a `TXT` record) it'll be possible, I'd appreciate it if you could implement it.  I'd also appreciate it if the same thing can be done via a plugin.

In any case, I'd like to thank you again for taking the time and reading my feature request, and I hope that the web interface I'm developing will be beneficial in either case.

**Comment by jedisct1** [comment]
My fear is that this is something that will have to be implemented and maintained forever but that no one will use.

I don't know how difficult it would be to have loadable plugins, but that would be a nice way to address specific needs. So I'd rather explore this than add something just for one application.

**Comment by DRSDavidSoft** [comment]
I'd like to add another potential use for this, sometimes I'd need to investigate _why_ a certain domain is blocked, and it'd be much easier to just retrieve this information from a one liner than digging through the logs.

More than once an issue has occurred where there are multiple old lines in the log, and `a.b.c.d` is blocked both by `b.c.d` and `c.d`. So, I need to remove `b.c.d` first and after restarting the service, check if it's still blocked, and repeat the process until there are no other lines that cause a block.  It would be super useful to directly query from `dnscrypt-proxy` on the client side which domain is causing the blockage, instead of remoting into the server and browsing the log files.

May I ask that this issue remain open if there is a chance to implement this?  It'll be awesome to implement loadable plugins, or at least have a configuration to enable/disable internal plugins form the config file (if there isn't something like this already.)

Hopefully if implementing this feature is possible, it'll be something easy and manageable to do so, and IMHO other users might also appreciate it (both from a programming and sys-admin'ing stand point).

Of course, I still don't want to burdon you with it as I'm already much grateful for what we have. `dnscrypt-proxy` is as awesome as it can be! 😊

**Comment by jedisct1** [comment]
> if there is a chance to implement this?

You can certainly implement it in a fork. Even if they are not dynamic, plugins are quite independent from the rest of the code, so rebasing your fork shouldn't be much of an issue.

But to be honest, I think having it in the proxy would be bloat, and is not something I'm interested in implementing.

**Comment by ianbashford** [comment]
Would something like Google's mtail help you?  https://github.com/google/mtail

It'll watch a pipe as well as a file, and give you http/json interfaces.   
I suspect you could configure that to work, and probably collect all sorts of other interesting facts for your web interface.  I think its designed with prometheus/grafana in mind so sounds like it could be configured to work for you... 
{just a thought - I've not deployed it myself}
