### ISSUE TITLE
problem about dns server

### ISSUE THREAD

**Issue by Ninjanoir87** [DNSCrypt/dnscrypt-proxy#1387]
hi, 

I used dnscrypt version 2.0,.39 from entware (dd wrt) and now they updated to 2,0,42, everything is fine but dont know why, but I did not change anything but now in my log I have a bug with a new server but I only use one as usual (nextdns)
here my log: (as i said, dont why that server is there)

`Jun 25 17:44:21 DD-WRT daemon.warn dnscrypt-proxy[3207]: Multiple stamps for server [faelix-ch-ipv4-doh]
Jun 25 17:44:21 DD-WRT daemon.warn dnscrypt-proxy[3207]: Multiple stamps for server [faelix-ch-ipv6]
Jun 25 17:44:21 DD-WRT daemon.warn dnscrypt-proxy[3207]: Multiple stamps for server [faelix-ch-ipv6-doh]
Jun 25 17:44:21 DD-WRT daemon.warn dnscrypt-proxy[3207]: Multiple stamps for server [faelix-uk-ipv4]
Jun 25 17:44:21 DD-WRT daemon.warn dnscrypt-proxy[3207]: Multiple stamps for server [faelix-uk-ipv4-doh]
Jun 25 17:44:21 DD-WRT daemon.warn dnscrypt-proxy[3207]: Multiple stamps for server [faelix-uk-ipv6]
Jun 25 17:44:21 DD-WRT daemon.warn dnscrypt-proxy[3207]: Multiple stamps for server [faelix-uk-ipv6-doh]
Jun 25 17:44:21 DD-WRT daemon.warn  dnscrypt-proxy[3207]: Error in source [public-resolvers]: [Multiple  stamps for server [faelix-ch-ipv4], Multiple stamps for server  [faelix-ch-ipv4-doh], Multiple stamps for server [faelix-ch-ipv6],  Multiple stamps for server [faelix-ch`

As you can see, my only server is nexrdns:

`Jun 25 17:44:21 DD-WRT daemon.notice dnscrypt-proxy[3207]: Now listening to 127.0.0.3:30 [UDP]
Jun 25 17:44:21 DD-WRT daemon.notice dnscrypt-proxy[3207]: Now listening to 127.0.0.3:30 [TCP]
Jun 25 17:44:21 DD-WRT daemon.notice dnscrypt-proxy[3207]: [NextDNS-ee6135] OK (DoH) - rtt: 63ms
Jun 25 17:44:21 DD-WRT daemon.notice dnscrypt-proxy[3207]: Server with the lowest initial latency: NextDNS-ee6135 (rtt: 63ms)
Jun 25 17:44:21 DD-WRT daemon.notice dnscrypt-proxy[3207]: dnscrypt-proxy is ready - live servers: 1
`
?? thanks

**Comment by jedisct1** [comment]
Hi!

These are just warnings that you can ignore. They will automatically disappear when your cache will expire, or if you upgrade to a more recent version (current is 2.0.44).

**Comment by Ninjanoir87** [comment]
> Hi!
> 
> These are just warnings that you can ignore. They will automatically disappear when your cache will expire, or if you upgrade to a more recent version (current is 2.0.44).
> 

Thanks.

But I cant take the 2.0.44 cause I need entware for my dd wrt .
Entware just updated to 2.0.42.
