### ISSUE TITLE
Invalid or unsupported stamp, Error in source [public-resolvers].

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1389]
Hello.

Sorry, I don't know if it's a good place to report this but I thought it's better than a 'question' etc.

So, there is a problem with Server `stamp`. During DNSCrypt restart, there are two `WARNING` messages (earlier this day, everything was okay):

`[WARNING] Invalid or unsupported stamp [sdns://[a-zA-Z0-9]*]: Invalid stamp
(port range)`
`[WARNING] Error in source [public-resolvers]: [Invalid or unsupported stamp
[sdns://[a-zA-Z0-9]*]: Invalid stamp (port range)] -- Continuing with reduced server count [225]`

It seems, that this issue is related with `meganerd-doh-ipv6` because `sdns` stamp shows exactly mentioned server (vide `public-resolvers.md` file; resolver list - `v2`). However, this Resolver is not used, configured etc. DNSCrypt is working normally, there is an internet connection and so on.

**EDIT:** One more thing: It seems, that it started to happen during testing `anon-ibksturm` relay (changing relay didn't solved described issue).

Best regards.

**Comment by jedisct1** [comment]
Bogus entry removed, thanks!
