### ISSUE TITLE
OrangePi zero doesn´t load the complete file

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#139]
Hi,

I want to use my OrangePi zero to do the adblocking (piHole) and encrypt my DNS requests. I try to follow your dnscrypt-proxy guide untill the download of the file. Even the file is bigger than 2 MB my Pi only loads a couple of kb:

`@orangepizero:~/dnsproxy$ sudo wget https://github.com/jedisct1/dnscrypt-proxy/releases/tag/2.0.0/dnscrypt-proxy-linux_arm-2.0.0.tar.gz

...

dnscrypt-proxy-linu     [  <=>               ]  45.59K   169KB/s    in 0.3s
2018-02-17 21:49:20 (169 KB/s) - ‘dnscrypt-proxy-linux_arm-2.0.0.tar.gz’ saved [                                      46683]`

I have the file in my folder but can`t proceed. Getting a error:

`@orangepizero:~/dnsproxy$ sudo tar -xf dnscrypt-proxy-linux_arm-2.0.0.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
`

What am I doing wrong? Thanks for the help

Phil

**Comment by jedisct1** [comment]
You downloaded a web page: https://github.com/jedisct1/dnscrypt-proxy/releases/tag/2.0.0/dnscrypt-proxy-linux_arm-2.0.0.tar.gz

The link to the actual file appears to be https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.0/dnscrypt-proxy-linux_arm-2.0.0.tar.gz
