### ISSUE TITLE
V2: now unable to use source [public-resolvers]: [Invalid signature] [Multiple stamps for server [cloudflare-family-ipv6]

### ISSUE THREAD

**Issue by Marjorie-R** [DNSCrypt/dnscrypt-proxy#1391]
## *Who* is the bug affecting?
Users of old dnscrypt-proxy versions, still loading v2 of the public-resolvers file. I can't check for V3.
- I am using dnscrypt-proxy v 2.0.19 (Stable Debian Buster/Devuan Beowulf), there is no later backport available.

## *What* is affected by this bug?
Unable to use the published sources in public-resolvers.
Currently I have 'fixed' my immediate need for DNS by adding a [static] source to .toml

## *When* does this occur?
When starting/restart the dnscrypt-proxy service.
I do this daily using a cron job.

## *Where* does it happen?
in source from [[https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md]]]    

## *How* do we replicate the issue?

Start dnscrypt-proxy.

## Expected behavior (i.e. solution)
Can be fixed by editing the sources fuel and removing duplicate.
Earlier there was a similar issue with another source (one that seems to have been edited out of the online list):
[ERROR] Invalid or unsupported stamp: [sdns://AgcAAAAAAAAAJTJhMDU6ZjQ4MDoxNDAwOjQzNjo1NDAwOjJmZjpmZWI4OjhkMWMgPhoaD2xT8-l6SS1XCEtbmAcFnuBXqxUFh2_YP9o9uDgSamFyamFyLm1lZ2FuZXJkLm5sBC9kb2g] 
[CRITICAL] Unable to use source [public-resolvers]: [Invalid stamp (port range)]  
 
Ideally the code should just exclude faulty source  - here server [cloudflare-family-ipv6] but load rest of server list.

## Other Comments
Problem confounded by github being down for 2 hours this morning making the files and webpages inaccessible. 
Possibly there have been issues in data recovery.

**Comment by jedisct1** [comment]
> Ideally the code should just exclude faulty source

Invalid entries are ignored, and if a signature issue arises, the previous version of a list is kept.

But version 2.0.19 is very old, and it probably wasn't the case back then. I would really recommend using a more version instead of that package.

**Comment by Marjorie-R** [comment]
Frank,
OK, understand that any de-bugging goes into the current version and
the bugs may well have fixed already. 
However Debian Buster/Devuan Beowulf is the stable (LTS) version and
only fairly recently promoted to such so there are a lot of systems
running it and will be for some time. 
There is more a recent dnscrypt-proxy version 2.0.39 packaged in
Debian/Devuan testing and unstable so I'll look into creating a
backport package, but I'm not a programmer these days.
Meanwhile will the V2 sources file be cleaned up (i.e. any broken
entries removed)? 
It was working OK and I can see that you are in the process of updating
the sources files so some temporary problems are completely
understandable. 
Otherwise I can get working with multiple sources by parsing the file
to create [static] entries, but that is not ideal as, obviously, it's
not dynamic and doesn't help anyone else. 
best regards,--Marjorie
