### ISSUE TITLE
Adding fritz.box to undelegated

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1392]
Care to add fritz.box for all the avm routers (most common ones in germany) to undelegated? Info: [Opening the FRITZ!Box user interface](https://en.avm.de/service/fritzbox/fritzbox-7590/knowledge-base/publication/show/1_Opening-the-FRITZ-Box-user-interface/)

**Comment by jedisct1** [comment]
`.box` is an existing [global TLD](https://icannwiki.org/.box), so it shouldn't be undelegated.

Is `192.168.178.1` always the IP address of `fritz.box`? If that is the case, maybe having it in the examples of cloaking rules may be better an idea. If the IP address can change, maybe rather in the `forwarding` examples.

**Comment by ghost** [comment]
`192.168.178.1` is the default IP but it can be changed by the user. `fritz.box` can however always be accessed using the emergency IP `169.254.1.1`, even if you change the default one. Documentation says that the emergency IP has the same functions. However I'm a little bit scared off by the word emergency.

**Comment by dodmi** [comment]
It says emergency, because it can be used if you broke your router's IP configuration and can't get an IP by the built in dhcp. You won't be able to access the router on 169.254.1.1 if your network adapter is probably configured (or not probably configured with manual ip configuration).

**Comment by ghost** [comment]
@dodmi 
Thank you for your comment but please do not make up wrong stuff.

The router can _always_ be accessed by the emergency IP, no matter what. That's what it's for. 
The normal IP instead allows you to choose your own one for convenience.

**Comment by dodmi** [comment]
@guser-sudo 
I guess you have tested to reach 169.254.1.1 before posting?
169.254.0.0/16 is the [APIPA network range](https://www.dummies.com/programming/networking/cisco/automatic-private-ip-addressing-apipa/), which forms a non-routable network, 
Devices will be able to communicate on the same network if they both have addresses in the APIPA range (e.g. don't get an IP address from a DHCP server and are not manually configured).
If your network card is configured to 192.168.178.x you should not be able to communicate with 169.254.1.1 in 169.254.0.0/16 as it's in a different network segment.
I doubt the FRITZ!Box does any strange stuff to behave otherwise (but it would be possible, as all packages which need to be routed to another net are sent to the gateway address (your FRITZ!Box, if all is properly configured))

**Comment by jedisct1** [comment]
> If your network card is configured to 192.168.178.x you should not be able to communicate with 169.254.1.1 in 169.254.0.0/16 as it's in a different network segment.

If a network, reserved or not, is not directly accessible via an attached interface, packets are going to be sent to... the router.

Which, I guess, is what we want here.

**Comment by ghost** [comment]
> @guser-sudo
> I guess you have tested to reach 169.254.1.1 before posting?

Yes, I did. I don't know about the internals of the FRITZ!Box but:

1. You can access it with `169.254.1.1`. The configuration doesn't matter.
2. It reports requests actually coming from `169.254.1.1` as coming from a `192.168.178.x` address instead.
3. If you have several AVM devices you cannot control which one you reach with the emergency address.

**Comment by dodmi** [comment]
Then I'm sorry. 
As you can read in the last section of the page, I've linked, APIPA addresses should not work this way in networks in general. It seems to be something special how Fritz!Box devices handle this traffic.

**Comment by ghost** [comment]
@jedisct1 
Because my initial issue was a different one I didn't gave much thought about adding a Fritz!Box example to the cloaking rules.
However now I think that's a bad idea and should be reverted:

Every Fritz!Box has a dns-rebind-protection enabled by default which prevents it from answering local requests.

- With cloaking every single word name is considered local and therefore blocked. AFAIK this cannot be changed in the Fritz!Box.
- With forwarding only local single word names are blocked and you can also unblock them in the Fritz!Box. However I recommend _against_ a forwarding example, either.

Because the example works differently than people would expect, they would open new issues here and cause unnecessary work. To have a proper setup which e.g. doesn't leak requests to your ISP alot of different settings in DNSCrypt-Proxy and the Fritz!Box need to be made correctly which is out of reach of a simple example.

Sorry for that.
