### ISSUE TITLE
Anonymized DNS relay not used in some situations when fetching certificate

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1393]
## Is your feature request related to a problem?
When fetching the certificate for a dnscrypt server there appear to be a couple of situations where the client will go direct and not via a configured relay. It isn't clear to someone using Anonymized DNS that this will happen and doesn't line up with documentation that suggests DNS servers won't learn the IP address of a client when using a relay.

I believe this is happening in dnscrypt_certs.go by setting relayUDPAddr and relayTCPAddr to nil:

Non-standard provider name:
`	if !strings.HasPrefix(providerName, "2.dnscrypt-cert.") {
		dlog.Warnf("[%v] uses a non-standard provider name ('%v' doesn't start with '2.dnscrypt-cert.')", *serverName, providerName)
		relayUDPAddr, relayTCPAddr = nil, nil
	}`

Failed to get certificate via relay:
`		dlog.Infof("Unable to get a certificate for [%v] via relay [%v], retrying over a direct connection", *serverName, relayUDPAddr.IP)
		relayUDPAddr, relayTCPAddr = nil, nil`

## Describe the solution you'd like
I'd like there to be a config option that allows you to disable directly connecting to DNS servers when relays are configured for them so if one of the above situations occurs then the server isn't used.

**Comment by jedisct1** [comment]
Hi,

Anonymization requires DNS servers to implement the protocol correctly. Unfortunately, this is not the case for some servers.

There's not much that can be done client-side, it has to be fixed on the servers. The best we can do is issue a warning as done here, in order to encourage them fix the issue.

**Comment by ghost** [comment]
Hello @jedisct1 

I rely on Anonymized DNS hence use only servers accepting the DNSCrypt protocol given it is required for DNS Anonymization. I'm running dnscrypt-proxy 2.0.44.

Sorry if the answer to my wondering is obvious but I'd appreciate the following made clear in my mind:

Am I sure that no servers having incorrectly implemented the Anonymization (within of course the DNSCrypt protocol) will be used if I set:
```
[anonymized_dns]
skip_incompatible = true
```
I ask this because I don't understand that when skipping incompatible servers is _true_, I may nevertheless encounter in my proxy.log, i.e:
`[WARNING] [skyfighter-dns] is incompatible with anonymization`

Why this warning given skip_incompatible has been set to true? For information only or is it that the server remains accessed? I'm puzzled here.

Thanks!

**Comment by jedisct1** [comment]
At startup, servers are tested in order to get a rough estimate of their latency and detect if they can be used via anonymizers. The warning you see is printed when the detection is done. 

Then, if `skip_incompatible` is set to `true`, resolvers detected as incompatible will not be used.

**Comment by ghost** [comment]
> Then, if skip_incompatible is set to true, resolvers detected as incompatible will not be used

OK, I get it and feel more comfortable. Thanks.

**Comment by ghost** [comment]
Hello,

I disagree that we can't do anything about this in the client - the issue I have is with the clients behavior in these situations. I've raised a pull request to add the functionality I suggested which might help if I haven't explained the issue well enough here.
