### ISSUE TITLE
Slow response when benchamarking multiple servers.

### ISSUE THREAD

**Issue by mikegleasonjr** [DNSCrypt/dnscrypt-proxy#1395]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description

Hi,

If I understand things correctly, with the default configuration sometimes the proxy sends the request to multiple servers to determine their speed and maybe re-sort the list of the servers.

Is it me or when the request is sent to multiple servers, dnscrypt waits for a response from everyone before sending back the response to the client?

If so, can't it simply send the first successful response it receives and continue process in the background the server sorting stuff?

For example my dnscrypt once sent the same request to 2 servers and it took the first one 60ms and the second one 5000ms to reply, my client waited 5000ms. Unless I am missing something

Thanks

**Comment by jedisct1** [comment]
Resolver latencies are incrementally estimated as they are being used.

If a chosen resolver returns a temporary error or times out, the query will be retried using a second choice.

5000ms is likely to be a timeout.

**Comment by mikegleasonjr** [comment]
I don't think the question was read carefully.

**Comment by jedisct1** [comment]
> If I understand things correctly, with the default configuration sometimes the proxy sends the request to multiple servers to determine their speed and maybe re-sort the list of the servers.

A query is sent to a server, and then, only on error, to a second choice. This is to hopefully get a response from the second choice.

> Is it me or when the request is sent to multiple servers, dnscrypt waits for a response from everyone before sending back the response to the client?

A query is sent to a server, and then, only on error, to a second choice. It is not send to multiple servers simultaneously.

> If so, can't it simply send the first successful response it receives and continue process in the background the server sorting stuff?

The first successful response it sent to the client.

Latency is estimated incrementally, there is no benchmarking except at startup time.

> For example my dnscrypt once sent the same request to 2 servers and it took the first one 60ms and the second one 5000ms to reply, my client waited 5000ms. Unless I am missing something

5000ms is a timeout.
