### ISSUE TITLE
[CRITICAL] Unable to use source [relays]: [Unsupported stamp version or protocol]

### ISSUE THREAD

**Issue by yik77** [DNSCrypt/dnscrypt-proxy#1396]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description

I have installed dnscrypt proxy 2.0.19 on my pi zero w, where I run pihole. There are some critical errors in the log, what can I do about it? It is on clean system and fresh installation of debian for raspberry.

-- Logs begin at Fri 2020-06-26 19:04:03 EDT, end at Wed 2020-07-01 16:11:28 EDT. --
Jun 26 19:04:31 raspberrypi systemd[1]: Started DNSCrypt client proxy.
Jun 26 19:04:32 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:32] [NOTICE] Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [NOTICE] Source [/var/cache/dnscrypt-proxy/relays.md] loaded
**Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [ERROR] Invalid or unsupported stamp: [sdns://gRE1MS4xNTguMTY2Ljk3OjQ0Mw]
Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [CRITICAL] Unable to use source [relays]: [Unsupported stamp version or protocol**
Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [NOTICE] dnscrypt-proxy 2.0.19
Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [NOTICE] Now listening to 127.0.0.1:5300 [UDP]
Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [NOTICE] Now listening to 127.0.0.1:5300 [TCP]
Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [NOTICE] Now listening to [::1]:5300 [UDP]
Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [NOTICE] Now listening to [::1]:5300 [TCP]
Jun 26 19:04:33 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:33] [NOTICE] Wiring systemd UDP socket #0, dnscrypt-proxy.socket, 127.0.2.1:5300
Jun 26 19:04:36 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:04:36] [NOTICE] [a-and-a] OK (DoH) - rtt: 94ms
Jun 26 19:06:49 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:06:49] [NOTICE] [acsacsar-ams-ipv4] OK (crypto v2) - rtt: 100ms
Jun 26 19:06:49 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:06:49] [NOTICE] [acsacsar-ams-ipv6] OK (crypto v2) - rtt: 122ms
Jun 26 19:06:49 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:06:49] [NOTICE] [ams-dnscrypt-nl] OK (crypto v1) - rtt: 106ms
Jun 26 19:06:50 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:06:50] [NOTICE] [ams-doh-nl] OK (DoH) - rtt: 106ms
Jun 26 19:06:50 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:06:50] [NOTICE] [arvind-io] OK (crypto v2) - rtt: 221ms
Jun 26 19:06:50 raspberrypi dnscrypt-proxy[545]: [2020-06-26 19:06:50] [NOTICE] [cloudflare] OK (DoH) - rtt: 22ms

**Comment by jedisct1** [comment]
Did that version had support for relays? I don't think the protocol even existed back then.

You can't use a recent configuration file with an antique version of the software.

Start with the example config file for that version, or upgrade to a more recent version.

**Comment by yik77** [comment]
This is the newest package I received 4 days ago when I installed it on raspbian buster with apt-get install as expected. 
I do not know how to get newer version than that, is there a debian package than runs on raspberry?

**Comment by jedisct1** [comment]
Current version is 2.0.44

https://github.com/dnscrypt/dnscrypt-proxy/releases/tag/2.0.44

`dnscrypt-proxy-linux_arm-2.0.44.tar.gz` should run on Raspberry Pi.
