### ISSUE TITLE
dnscrypt-proxy stops resolving every now and then

### ISSUE THREAD

**Issue by oliversturm** [DNSCrypt/dnscrypt-proxy#1399]
## *Who* is the bug affecting?

Not sure what the goal of this template question is, but my situation is that I'm running dnscrypt-proxy on a pihole which acts as a resolver for the entire house wifi.

## *What* is affected by this bug?

Resolving via the pihole doesn't work - that's the indication. I try then to resolve directly on the pihole by calling `dnscrypt-proxy -resolve <server>` and I see results like this:

```
Resolving [cqrlog.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -
Resolver IP:    195.30.193.36
```

## *When* does this occur?

Every now and then (can be after a few hours or many days), somebody in the household notices that certain websites are not accessible anymore, YouTube doesn't work or whatever. There is no pattern to this - the problematic domain names vary every time, and so does the time between failures.

## Expected behavior (i.e. solution)

Obviously I expect the service to keep running correctly. 

## Other Comments

When I restart the proxy, everything is back to normal - until the next time. I have observed this behavior for several months now and updated to the latest version yesterday - today it failed again.

I set `log_level=1` in the config file a while ago, but I never see anything out of the ordinary in the output. I appreciate that the information in this bug report may not be sufficient for anybody to come up with a solution, but perhaps someone can point me at a way to retrieve some more useful log information? I understand `log_level=0` [does not add any useful troubleshooting detail](https://github.com/DNSCrypt/dnscrypt-proxy/pull/1370), so I have not tried it.

**Comment by oliversturm** [comment]
I thought my last comment about `log_level=0` was a bit stupid &lt;g&gt; so I decided to activate that log level and see what happens. I'd still appreciate any other comments, of course.

**Comment by oliversturm** [comment]
One more thing that comes to mind. I thought previously that perhaps the proxy was hung up on a particular server and that this server had just stopped working. I don't know the internals to judge whether this is possible or not, and I know that the problem doesn't go away by itself once it starts. But then I also did a test like this:

```
pi@raspberrypi:~ $ /usr/local/dnscrypt-proxy/dnscrypt-proxy -resolve sts.platform.rmunify.com
Resolving [sts.platform.rmunify.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -
Resolver IP:    51.15.62.65
pi@raspberrypi:~ $ sudo systemctl restart dnscrypt-proxy
pi@raspberrypi:~ $ /usr/local/dnscrypt-proxy/dnscrypt-proxy -resolve sts.platform.rmunify.com
Resolving [sts.platform.rmunify.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: rm-unify-live01-sso.cloudapp.net.
IP addresses:   104.41.223.173
TXT records:    -
Resolver IP:    51.15.62.65 (65-62-15-51.rev.cloud.scaleway.com.)
```

If I trust the "Resolver IP" in the output, the first attempt was using the same server as the second - but with the restart in between, it worked suddenly. So it seems that the issue is not actually related to the specific server being used.

**Comment by jedisct1** [comment]
Maybe the `query_log` can provide more information?

Also, try sending queries directly to the proxy (using `dig`, `drill`, or whatever).

**Comment by oliversturm** [comment]
> try sending queries directly to the proxy

I thought `dnscrypt-proxy -resolve` was the most direct way of querying the proxy?

**Comment by oliversturm** [comment]
@jedisct1  I just activated the query log - I never realized that it would contain information about the server used to resolve. Now of course I need to wait for something to wrong again - who knows how long that will take. Thanks for the idea.

**Comment by jedisct1** [comment]
> I thought `dnscrypt-proxy -resolve` was the most direct way of querying the proxy?

`dnscrypt-proxy -resolve` simulates what a normal application would do.

**Comment by oliversturm** [comment]
Something new. I have found that the issue may be connected somehow to the pihole setup. Late last night it suddenly became impossible to resolve `beta.protonmail.com`. I took @jedisct1 's advice and used `dig` to query dnscrypt-proxy directly. Here are all the results:

```
pi@raspberrypi:~ $ /usr/local/dnscrypt-proxy/dnscrypt-proxy -resolve beta.protonmail.com
Resolving [beta.protonmail.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -
Resolver IP:    51.15.122.250 (scaleway-ams.dnscrypt.info.)

pi@raspberrypi:~ $ dig beta.protonmail.com

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> beta.protonmail.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 3675
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;beta.protonmail.com.		IN	A

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Jul 05 14:42:01 BST 2020
;; MSG SIZE  rcvd: 48

pi@raspberrypi:/usr/local/dnscrypt-proxy $ dig -p 53000 @127.0.0.1 beta.protonmail.com

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> -p 53000 @127.0.0.1 beta.protonmail.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45444
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;beta.protonmail.com.		IN	A

;; ANSWER SECTION:
beta.protonmail.com.	2399	IN	A	185.70.41.139

;; Query time: 229 msec
;; SERVER: 127.0.0.1#53000(127.0.0.1)
;; WHEN: Sun Jul 05 14:49:10 BST 2020
;; MSG SIZE  rcvd: 64
```

So - when talking to the proxy directly, I can resolve the name, but not through the pihole resolver. So I checked the pihole log files and found this:

```
...
Jul  4 22:40:41 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:40:41 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:40:41 dnsmasq[511]: dnssec-query[DS] beta.protonmail.com to 127.0.0.1
Jul  4 22:40:41 dnsmasq[511]: reply beta.protonmail.com is 185.70.41.139
Jul  4 22:40:41 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:40:41 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:40:41 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:40:41 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:40:41 dnsmasq[511]: dnssec-query[DS] beta.protonmail.com to 127.0.0.1
Jul  4 22:40:41 dnsmasq[511]: reply beta.protonmail.com is 185.70.41.139
Jul  4 22:41:43 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:41:43 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:41:43 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:41:43 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:41:43 dnsmasq[511]: dnssec-query[DS] beta.protonmail.com to 127.0.0.1
Jul  4 22:41:43 dnsmasq[511]: reply beta.protonmail.com is no DS
Jul  4 22:41:43 dnsmasq[511]: validation beta.protonmail.com is BOGUS
Jul  4 22:41:43 dnsmasq[511]: reply beta.protonmail.com is 185.70.41.139
Jul  4 22:41:44 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:41:44 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:41:44 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:41:44 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:41:44 dnsmasq[511]: validation beta.protonmail.com is BOGUS
Jul  4 22:41:44 dnsmasq[511]: reply beta.protonmail.com is 185.70.41.139
Jul  4 22:41:46 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:41:46 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:41:46 dnsmasq[511]: query[A] beta.protonmail.com from 10.0.0.1
Jul  4 22:41:46 dnsmasq[511]: forwarded beta.protonmail.com to 127.0.0.1
Jul  4 22:41:46 dnsmasq[511]: validation beta.protonmail.com is BOGUS
Jul  4 22:41:46 dnsmasq[511]: reply beta.protonmail.com is 185.70.41.139
...
```

It seems that from some random point onwards, pihole starts reporting this BOGUS thing. Looking around for the meaning of it, I find that BOGUS indicates an invalid DNSSEC signature.

Now I'm at a loss again - where does that signature come from? Why is it suddenly invalid? And why can the problem be fixed by restarting dnscrypt-proxy, if it is really a pihole problem? The only hint I found so far is that the time on the pihole may be off, but that's not it - it uses NTP and looked precise when I checked it.

**Comment by gael1980** [comment]
Dumb question, but the date and time are right on the rpi?
I already had the same problem, I solved it by forcing an ntp update.

**Comment by bjoe2k4** [comment]
Having the same problem, that for some random domains I am getting servfail directly from dnscrypt-proxy over and over with dig. Very annoying. Resarting dnscrypt-proxy resolves the issue. Happened after upgrade from `2.0.39` to `2.0.44`. I have used a new example config and modified a few settings. Also running on a raspi4 with correct ntp-time.

**Comment by jedisct1** [comment]
Check that your router is not blocking UDP fragments.

**Comment by bjoe2k4** [comment]
I've just identifiert `ams-doh-nl` as the culprit returning lots of servfail responses for almost any DS query.

```
[2020-07-08 22:39:12]   127.0.0.1   mailbox.org DNSKEY  SERVFAIL    28ms    ams-doh-nl
[2020-07-08 22:57:29]   127.0.0.1   office365.com   DS  SERVFAIL    22ms    ams-doh-nl
[2020-07-08 22:57:37]   127.0.0.1   msedge.net  DS  SERVFAIL    23ms    ams-doh-nl`
```

**Comment by jedisct1** [comment]
@bjoe2k4 Good catch, thanks!

**Comment by oliversturm** [comment]
Well, I think this issue needs to be reopened. It is certainly possible that the SERVFAIL response has to do with the issue. But it is by no means limited to ams-doh-nl:

```
pi@raspberrypi:/usr/local/dnscrypt-proxy $ grep SERVFAIL query.log | cut  -f 7 | sort | uniq
ams-dnscrypt-nl
ams-doh-nl
bcn-dnscrypt
bcn-doh
cloudflare
dnscrypt.ca-2-doh
doh.appliedprivacy.net
doh-crypto-sx
faelix-ch-ipv4
faelix-ch-ipv4-doh
ffmuc.net
rumpelsepp.org
sth-doh-se
v.dnscrypt.uk-ipv4
```

**Comment by bjoe2k4** [comment]
Indeed. I've just experienced the same with with ffmuc.net. Somehow dnscrypt-proxy should have some counter-measures for such situations when lots of servfails are returned. At least trying a different server for the next request to the same dns question instead of trying the same one over and over again.

**Comment by jedisct1** [comment]
@bjoe2k4 This is already the case. Timeouts or server failures add penalties to a server, so that it gets less and less chance to be picked.

That being said, I think it this is unrelated to the original issue.

If restarting the proxy changes the behavior, it is likely that large packets are being blocked by the router or some firewall, as the minimum size may increase as needed.

**Comment by oliversturm** [comment]
I'm not sure I'm following the discussion here. Whether or not the SERVFAIL results are the cause, the fact remains that dnscrypt-proxy can't handle whatever is happening and ends up unresponsive. Why is this issue closed? It is not fixed.

> If restarting the proxy changes the behavior, it is likely that large packets are being blocked by the router or some firewall, as the minimum size may increase as needed.

I'm not sure what you mean to say here. Why would large packets be blocked somewhere only after dnscrypt-proxy has been running for a while? Why would they suddenly not be blocked if the proxy is restarted? Are you saying that the proxy increases its package size over time and doesn't realize it when it went too far?

**Comment by jedisct1** [comment]
Yes, the packets size can increase (and then decrease) according to the received responses. Which is totally fine, but maybe not on your network.

Try `force_tcp = yes` maybe, especially if you are running an old version.

Realistically, debugging something that happens “every now and then, only on my machine” is going to be complicated. So any progress on this is very unlikely, except if it is immediately and reliably reproducible.

Meanwhile, try tweaking the configuration and try to understand what happens as `dnsmasq` level and at network level. You may eventually find settings that make a difference.

**Comment by oliversturm** [comment]
Alright, thank you.
