### ISSUE TITLE
Question, Correction and Request (Pull ?)

### ISSUE THREAD

**Issue by GaneJ** [DNSCrypt/dnscrypt-proxy#140]
1. *Question*:
   If **```"type Config struct {"```** don't have **```"toml:x"```** what string I had to use in config file?
   For example: **```"Cache int"```** don't have **```"toml:"```**, should I use **```"cache"```** in your config file?
2. *Correction*:
   In your config file, string for **```"Timeout"```** is **```"timeout"```**, but in config structure it say **```Timeout int toml:"timeout_ms"```**.
   Which one is correct, **```"timeout"```** or **```"timeout_ms"```**?
3. *Request*:
   Add **no information will be log** in query log file.
   Maybe we can change something in **"plugin_query_log.go"**.
   **Before**:
          **```if strings.EqualFold(ignoredQtype, qType) {```**
   **After**:
          **```if strings.EqualFold(ignoredQtype, "*") || strings.EqualFold(ignoredQtype, qType) {```**
4. For **```"[source]"```**, it still can not accept **```cache_file```** without minisign key and downloading it. I found out in **"config.go"** -> **```loadSource(....```**
But maybe you can fix it later :wink:

**Comment by jedisct1** [comment]
1. yes
2. `timeout_ms`
3. Why do you want to create an empty file and never write anything into it?
4. Lists must have a signature. But the `url` property can be removed if you don't want to download updates.
