### ISSUE TITLE
Can we forwarding different domain queries to different DoH servers?

### ISSUE THREAD

**Issue by bydvoid** [DNSCrypt/dnscrypt-proxy#1400]
**What I need:**

In forwarding rules, it seems like we can only forwarding some domain queries to any non encrypted upstream DNS resolver. But in my contry, I need to redirect 2 kinds of queries to 2 different upstream resolver, AND they ALL support DoH. How can I forwarding these 2 kinds of queries to different DoH servers?

**How we can do?**
Maybe we can add some new features in forwarding rules to help us.

**Comment by jedisct1** [comment]
Run two instances, and have one of them forward selected domains to the other.

**Comment by bydvoid** [comment]
> Run two instances, and have one of them forward selected domains to the other.

OK, I'll try it. Could this can be a new panned feature?

**Comment by jedisct1** [comment]
Maybe, but probably not in a near future.
