### ISSUE TITLE
Rename blacklist -> blocklist in all locations

### ISSUE THREAD

**Issue by fulldecent** [DNSCrypt/dnscrypt-proxy#1402]
Old wording is deprecated.

**Comment by ianbashford** [comment]
We've got that handled in https://github.com/DNSCrypt/dnscrypt-proxy/commit/b089d49d25bf0d35a1a4a7a7637e63e0a3f93501  
Should be in the next release... 
See the new example files for details of the new names https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml 

Note that the old names (blacklist/whitelist) are not fully deprecated - there's likely too many existing config files out there to break in one hit.  There's log mesages to indicate the move though.

**Comment by fulldecent** [comment]
Great, thank you
