### ISSUE TITLE
Need help with Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by evilvibes** [DNSCrypt/dnscrypt-proxy#141]
So after a long battle with Ubuntu i believe i got dnscrypt-proxy working on it. I'm super new to the linux world so sorry if this was easy lol. I need someone to test it out to make sure it works then ill add it to the Installation wiki like i did for macOS.

Getting dnscrypt-proxy up and running was easy but getting 127.0.0.1 to work was the battle for me. I made the dns 127.0.0.1 under the network but didn't work. So after a lot of searching i edited /etc/network/interfaces with the command "sudoedit /etc/network/interfaces" and added dns-nameservers 127.0.0.1

It will look like this:

"#" interfaces(5) file used by ifup(8) and ifdown(8)
auto lo
iface lo inet loopback
dns-nameservers 127.0.0.1

Save and reboot.

**Comment by jedisct1** [comment]
Yes, changing DNS settings on Linux has become very difficult, and I never know how to do it either.

Can you document this in the wiki?

**Comment by evilvibes** [comment]
Once someone can test it for me and it 100% works i'll add it i just don't want to add something that don't work.

**Comment by Sporif** [comment]
@evilvibes Just tried it on an Ubuntu VM and it works. Though instead of rebooting I just did `sudo ifdown lo` then `sudo ifup lo`. Which I think on a normal install it would be `eth0` or `wlan0` instead of `lo`.

**Comment by evilvibes** [comment]
Awesome thanks.

Added macOS - https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation#installing-dnscrypt-proxy-on-macos-as-a-system-service

Added Ubuntu 16.04.3 LTS - https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation#installing-dnscrypt-proxy-on-ubuntu-16043-lts-as-a-system-service

**Comment by jedisct1** [comment]
Fantastic, thank you!
