### ISSUE TITLE
-check reports lots of unsupported keys with example config

### ISSUE THREAD

**Issue by bjoe2k4** [DNSCrypt/dnscrypt-proxy#1410]
## *Who* is the bug affecting?
me.

## *What* is affected by this bug?
not sure what, probably nothing, but 

## *When* does this occur?
when using `-check` on my config, it reports many directives are unsupported:

(one at a time, after commenting offensive key, next unsupported key is reported)
```
[2020-07-08 19:52:54] [FATAL] Unsupported key in configuration file: [fallback_resolvers]
[2020-07-08 19:55:07] [FATAL] Unsupported key in configuration file: [block_unqualified]
[2020-07-08 19:55:49] [FATAL] Unsupported key in configuration file: [block_undelegated]
[2020-07-08 19:56:17] [FATAL] Unsupported key in configuration file: [reject_ttl]
[2020-07-08 19:56:35] [FATAL] Unsupported key in configuration file: [local_doh]
...
```

## *Where* does it happen?
on a raspi4 with 32bit raspbian and dnscrypt-proxy v2.0.44 binary from github

## *How* do we replicate the issue?

Use above system with example toml with following modifications:

```diff
$ diff example-dnscrypt-proxy.toml raspi.toml
39c39
< listen_addresses = ['127.0.0.1:53']
---
> listen_addresses = ['127.0.0.1:9053', '127.0.0.1:9054','[::1]:9053','[::1]:9054']
52c52
< # user_name = 'nobody'
---
> user_name = 'nobody'
61c61
< ipv6_servers = false
---
> ipv6_servers = true
73c73
< require_dnssec = false
---
> require_dnssec = true
194c194
< # tls_cipher_suite = [52392, 49199]
---
> tls_cipher_suite = [52392, 49199]
411c411
<   # file = 'query.log'
---
>   file = '/var/log/dnscrypt-proxy/query.log'
```

## Expected behavior (i.e. solution)
not reporting any problems with example config on `-check`

## Other Comments
Why doens't dnscrypt-proxy report these issues on startup?
Probably it would also be nice if -check would report all unsupported options at once instead of one at a time.

**Comment by jedisct1** [comment]
Try the `-version` command-line switch to verify what version you are running.

Uninstall old versions.

In order to run a command in the current directory on Linux, you need to prefix the command with `./`, for example `./dnscrypt-proxy`.

**Comment by bjoe2k4** [comment]
Silly me, Thanks!
