### ISSUE TITLE
Getting parse error when setting up server Docker , no SDNS being made?

### ISSUE THREAD

**Issue by mukberty** [DNSCrypt/dnscrypt-proxy#1414]
I have run `apt update; apt dist-upgrade`. 
Then, I run `docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host \
jedisct1/dnscrypt-server init -N example.com -E IP`.

The output is -
`Unable to find image 'jedisct1/dnscrypt-server:latest' locally
latest: Pulling from jedisct1/dnscrypt-server
d51af753c3d3: Pull complete 
fc878cd0a91c: Pull complete 
6154df8ff988: Pull complete 
fee5db0ff82f: Pull complete 
25fbec78bc43: Pull complete 
196a9d7d5182: Pull complete 
2d0658d0590c: Pull complete 
31ee0b4fdad5: Pull complete 
187b23ad21e0: Pull complete 
7e8627b3f48a: Pull complete 
13f30728b9da: Pull complete 
d7cc8668dca3: Pull complete 
90695a13d4ca: Pull complete 
ed68abc99b5c: Pull complete 
ebc254931fa5: Pull complete 
525a8d9b2c6b: Pull complete 
6089863afd35: Pull complete 
Digest: sha256:0f3eb8a6703e987871ab85df8d15548ced3a2be3f8a347eadfb51b0d3bb2e651
Status: Downloaded newer image for jedisct1/dnscrypt-server:latest
WARNING: Published ports are discarded when using host network mode
IP and port should be specified as 'ipv4_addr:port' or '[ipv6_addr]:port'
Provider name: [2.dnscrypt-cert.example.com]
Error: Parse error in the configuration file: invalid IP address syntax for key `listen_addrs` at line 26 column 15

-----------------------------------------------------------------------

Congratulations! The container has been properly initialized.
Take a look up above at the way dnscrypt-proxy has to be configured in order
to connect to your resolver. Then, start the container with the default command.

`
What should I do?
I am using pre-configured Docker on Digital Ocean.

**Comment by jedisct1** [comment]
`-E` should be followed by the IP address and port, for example `-E '192.168.1.1:443'`

By the way, this is a distinct project, whose repository is here: https://github.com/DNSCrypt/dnscrypt-server-docker
