### ISSUE TITLE
Use Pihole's gravity db list

### ISSUE THREAD

**Issue by Kedstar99** [DNSCrypt/dnscrypt-proxy#1415]
## Is your feature request related to a problem?

On my network at home, I use both dnscrypt-proxy and pihole. The Pihole provides a nice, clean way to manage blocklists, whitelists and with clear statistics for each domain hit. However, pihole does not offer at present DoH or DoT, with the current recommendation being to offload such requests to dnscrypt-proxy or cloudflared if required.

Now, devices are coming along that are offering DoH as a default (such as iOS 14, Windows, edge, Firefox, chrome) etc.... With features being built on top of that for things like ESNI. These services can currently make do with the local-doh server provided by dnscrypt-proxy.

**It would be nice if DNSCryptProxy could take advantage of the blacklists/whitelists generated by pihole.**

## Describe the solution you'd like

A request made via DNSCryptProxy be checked against gravity list set as a configuration option. I imagine there is some overlap in blocklist/whitelist filtering approaches anyway so doing so may de-duplicate effort.

## Alternatives you've considered

For now, the needs of the filtering are mostly managed by in-browser solutions such as ublock-origin. For things like iOS14/Windows it would be nice to perhaps just point to my local-DoH system and retain my pihole filtering.

## Who will that feature be useful to?

iOS/Windows users mainly for now who also probably use pihole.

## What have you done already?

No prototype at the moment.

## What are you going to contribute?

I am happy to help with the feature whether to write SQL or testing. I haven't written go before though but i can learn quickly i imagine. 

## Additional context

This may need some collaboration between pihole devs and dnscrypt-proxy to maybe standardize/stabilize the gravity list. I figure with the move to 5, and the use of sqllite, maybe things can be a bit more stable/flexible at this stage.

**Comment by alisonatwork** [comment]
Could you just write a small script that select from the gravity db and output a list in the dnscrypt-proxy format? There is currently a Python script that does this for hosts-style lists (see https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Public-blacklists and https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/utils/generate-domains-blocklists/generate-domains-blocklist.py). I guess the setup would be similar, but querying from SQLite instead of downloading from the web.
