### ISSUE TITLE
"[FATAL] listen udp 127.0.0.1:53: bind: permission denied" Upon Startup

### ISSUE THREAD

**Issue by FrigidReward** [DNSCrypt/dnscrypt-proxy#1417]
Note: I know there have been 2 similar posts to mine, but I still had trouble understanding. I'm also new to this, so please explain in detail if you don't mind. 

OS: MacOS Catalina 10.15.5 

Issue: 
> Last login: Thu Jul 16 12:50:42 on console
/Applications/dnscrypt-proxy/dnscrypt-proxy ; exit;
zb@zb-MacOS ~ % /Applications/dnscrypt-proxy/dnscrypt-proxy ; exit;
[2020-07-16 12:50:47] [NOTICE] dnscrypt-proxy 2.0.44
[2020-07-16 12:50:47] [NOTICE] Network not available yet -- waiting...
[2020-07-16 12:51:19] [NOTICE] Network connectivity detected
[2020-07-16 12:51:19] [FATAL] listen udp 127.0.0.1:53: bind: permission denied
>
>[Process completed]

Description: The internet works just fine when the process is "complete" & I'm not sure if I should just ignore it. I have dnscrypt-proxy as a login item (for automatic-startup purposes) if that matters. I looked through the MacOS installation guide & it seems like the problem is that dnscrypt-proxy isn't starting up via root shell (under Step 2: "listen udp 127.0.0.1:53: bind: permission denied: you are not using a root shell as explain in Step 1. Use sudo -s to get one."). The thing is I don't know & can't find how to make items startup via root shell. I have root user enabled on my system but I'm not sure if that's the same thing as root shell.

**Comment by jedisct1** [comment]
To have a shell, you should run the `Terminal` app.

Typing the command as documented, with `sudo` at the beginning of a line will run the command as root.

You don't need to st it up as a login item. The `-service install` command will do it for you.

**Comment by FrigidReward** [comment]
Gotcha. So it automatically starts up without being needed to be added as a login item correct?

**Comment by jedisct1** [comment]
Yes.

**Comment by FrigidReward** [comment]
Forgive my ignorance, & thank you for the replies.
