### ISSUE TITLE
Question: How To Disable Query Log?

### ISSUE THREAD

**Issue by GaneJ** [DNSCrypt/dnscrypt-proxy#142]
Me:
> *Request*:
Add **no information will be log** in query log file.
Maybe we can change something in **"plugin_query_log.go"**.
*Before*:
**```if strings.EqualFold(ignoredQtype, qType) {```**
*After*:
**```if strings.EqualFold(ignoredQtype, "*") || strings.EqualFold(ignoredQtype, qType) {```**

@jedisct1:

> Why do you want to create an empty file and never write anything into it?

Me:
I think that the only way to disable a log created for querying some name server don't they?
At least that for temporary solution. Well, what do you think?

**Comment by jedisct1** [comment]
I'm not sure I follow.

If you don't want a log to be created, just comment or delete the line with the log file name :)
