### ISSUE TITLE
"TLS fatal alert" when trying to download mybase.txt

### ISSUE THREAD

**Issue by curiosityseeker** [DNSCrypt/dnscrypt-proxy#1421]
I normally download mybase.txt automatically with a script using wget -N. Now I noticed that the last version on my disk is from 2020-09-07 although the website says that the file was updated on 2020-07-16. So when trying to download it from the console in Arch Linux I get:

```
wget https://download.dnscrypt.info/blacklists/domains/mybase.txt
--2020-07-17 17:37:28--  https://download.dnscrypt.info/blacklists/domains/mybase.txt
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving download.dnscrypt.info (download.dnscrypt.info)... 37.59.238.213
Connecting to download.dnscrypt.info (download.dnscrypt.info)|37.59.238.213|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [70]: Error in protocol version
Unable to establish SSL connection.
```

It seems that something is misconfigured.

**Comment by jedisct1** [comment]
Try with `curl` maybe?

**Comment by curiosityseeker** [comment]
Yeah, I was just about to report that there is no problem using `curl`. How can this different behavior be explained? There had not been any problem with `wget` and your site before, and downloading files from other sites still works as always. Strange ...

**Comment by jedisct1** [comment]
Your version seems to use GnuTLS, which is quite unusual.

A severe vulnerability was recently found in GnuTLS, and maybe the update broke something.

Nothing changed on my end.
