### ISSUE TITLE
[ERROR] read udp xxx.xxx.xxx.xxx:57048->xxx.xxx.xxx.xxx:443: i/o timeout

### ISSUE THREAD

**Issue by junyo** [DNSCrypt/dnscrypt-proxy#1422]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description
I've deployed an encrypted-dns-server on Google Computed Engine and an dnscrypt-proxy client on Bandwagon Host.
The proxy throws an error  

> [ERROR] read udp xxx.xxx.xxx.xxx:57048->xxx.xxx.xxx.xxx:443: i/o timeout

I've checked the port by NCat and it connected successfully. I don't know how to fix it

**Comment by ianbashford** [comment]
That's no response from server, so I don't think it's managing to get the packet through (or its not coming back).
What response did you get from netcat that made you think it connected via UDP ?

I don't know what else you've tried, but I'd confirm the client on a working service first so you know the client setup is good.

On the server I'd suspect firewall first, so after verifying the FW rules you've setup, maybe use tcpdump and make sure the packets are arriving?  
Or, shutdown the service, and setup a netcat listen service on 443 and use validate the firewall is good that way.

**Comment by junyo** [comment]
I already add udp:443 and tcp:443 rule
> ![image](https://user-images.githubusercontent.com/433309/88075516-7d48f180-cbab-11ea-8a64-a10a86444ef1.png)

encrypted-dns-server is listening on udp/tcp 443
> [root@instance-1 ~]# netstat -nlp|grep encrypted
tcp&nbsp;&nbsp;&nbsp;15&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0 0.0.0.0:443&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.0.0.0:\*&nbsp;&nbsp;&nbsp;&nbsp;LISTEN&nbsp;&nbsp;&nbsp;&nbsp;1509/./encrypted-dn
udp&nbsp;&nbsp;&nbsp;214272&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0 0.0.0.0:443&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.0.0.0:\*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1509/./encrypted-dn

ncat message
> [root@critical-fan-3 ~]# nc -zvu xxx.xxx.xxx.xxx 443
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to xxx.xxx.xxx.xxx:443.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.22 seconds.

**Comment by junyo** [comment]
tcpdump reports that the server have received the udp packet, but never sent back a packet. No Errors and only startup info in the log file of the encrypted dns server.
It seems the packet is too big, is it the reason？

> 17:20:21.691188 IP (tos 0x0, ttl 51, id 21941, offset 0, flags [+], proto UDP (17), length 1500)
    xxx.xxx.xxx.xxx.54691 > xxx.xxx.xxx.xxx: UDP, bad length 1532 > 1472

**Comment by welwood08** [comment]
Just FYI for anyone who notices, I deleted the first revision of the last message from history because it contained uncensored addresses. I figured I should be transparent since my name's attached but I can't attach a reason.

**Comment by ianbashford** [comment]
Are you running in docker?  If so, then try running ```--network=host``` in case the bridge is causing issues (just for diagnostics)

Otherwise I'm afraid I'm getting to the limit of my knowledge on google cloud / MTUs.

My 2 pence though -- I'm not sure about that netcat being accurate over udp - seems to work on any port
```
nc -zvu  www.google.com  449
Connection to www.google.com 449 port [udp/*] succeeded!
```

**Comment by junyo** [comment]
No, not in docker.  tcp dump proved that the server can recieve the client's datagram, but did not repond. I think some thing is wrong with the server config or anything else. I'll try on another cloud server.

**Comment by junyo** [comment]
Oh~god! I downloaded the precompiled server by FDM which cache the old file.
Compilation from source code solve the problem.
