### ISSUE TITLE
Dig command: No servers could be reached

### ISSUE THREAD

**Issue by jorgsmash** [DNSCrypt/dnscrypt-proxy#1423]
After installing DNS-crypt proxy and configuring pi-hole to use 127.0.0.1:5353 as upstream DNS, I'm getting the following:

> $ dig pi-hole.net @127.0.0.1 -p 5353
; <<>> DiG 9.16.1-Ubuntu <<>> pi-hole.net @127.0.0.1 -p 5353
;; global options: +cmd
;; connection timed out; no servers could be reached
jorg@elder-mac-smash:$ netstat -ano | grep 5353
udp 0 0 0.0.0.0:5353 0.0.0.0:* off (0.00/0/0)
udp6 0 0 :::5353 :::* off (0.00/0/0)
jorg@elder-mac-smash:~$
$ sudo service dnscrypt-proxy status
● dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Wed 2020-07-22 18:27:21 UTC; 1s ago
Process: 344367 ExecStart=/opt/dnscrypt-proxy/dnscrypt-proxy -config dnscrypt-proxy.toml (code=exited, status=255/EXCEPTION)
Main PID: 344367 (code=exited, status=255/EXCEPTION)

This command works, however:

>/opt/dnscrypt-proxy$ ./dnscrypt-proxy -resolve pi-hole.net
Resolving [pi-hole.net]
Domain exists:  yes, 4 name servers found
Canonical name: pi-hole.net.
IP addresses:   192.124.249.118
TXT records:    v=spf1 +a +mx +ip4:23.92.70.115 +ip4:23.92.70.123 ~all stripe-verification=9e06f31a825fe879e428d1e4e85ec8dd47ce696f05afc3ccd92fbdf97f7ea254 google-site-verification=we1cZQSPMA1xzb6I81fa9Wdx1oVl-6l7-HOBNEGvpmY
Resolver IP:    74.63.17.251 (res311.iad.rrdns.pch.net.)

I tried skimming through the dnscrypt-proxy.toml file and I didn't see anything there that looked off. I used the example-dnscrypt-proxy.toml file during setup. I followed this guide: https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0 

Thanks to all!

**Comment by jedisct1** [comment]
```text
Active: activating (auto-restart) (Result: exit-code) since Wed 2020-07-22 18:27:21 UTC; 1s ago
Process: 344367 ExecStart=/opt/dnscrypt-proxy/dnscrypt-proxy -config dnscrypt-proxy.toml (code=exited, status=255/EXCEPTION)
Main PID: 344367 (code=exited, status=255/EXCEPTION)
```

Looks like `dnscrypt-proxy` is not running, maybe because your configuration is incorrect.

Try running it in interactive mode, and only once you successfully tested that everything behaves as expected, install it as a service.

**Comment by jorgsmash** [comment]
I don't see an interactive mode listed when I check the "Usage of ./dnscrypt-proxy:"
This is what I tried: 

> $ sudo ./dnscrypt-proxy -check
[2020-07-23 15:30:31] [NOTICE] dnscrypt-proxy 2.0.44
[2020-07-23 15:30:37] [NOTICE] Source [public-resolvers] loaded
[2020-07-23 15:30:37] [NOTICE] Source [relays] loaded
[2020-07-23 15:30:37] [NOTICE] Configuration successfully checked
jorg@elder-mac-smash:/opt/dnscrypt-proxy$ sudo ./dnscrypt-proxy
[sudo] password for jorg:
[2020-07-23 15:54:29] [NOTICE] dnscrypt-proxy 2.0.44
[2020-07-23 15:54:29] [NOTICE] Network connectivity detected
[2020-07-23 15:54:29] [FATAL] listen udp 127.0.0.1:5353: bind: address already in use
$ sudo ./dnscrypt-proxy -service stop
[2020-07-23 15:55:00] [NOTICE] Service stopped
jorg@elder-mac-smash:/opt/dnscrypt-proxy$ sudo ./dnscrypt-proxy
[2020-07-23 15:55:02] [NOTICE] dnscrypt-proxy 2.0.44
[2020-07-23 15:55:02] [NOTICE] Network connectivity detected
[2020-07-23 15:55:02] [FATAL] listen udp 127.0.0.1:5353: bind: address already in use

**Comment by jedisct1** [comment]
```text
 [2020-07-23 15:54:29] [FATAL] listen udp 127.0.0.1:5353: bind: address already in use
```

So, there is already something listening to port 5353.

```sh
sudo ss -lp 'sport = :5353'
```

May display the application listening to that port.

**Comment by jorgsmash** [comment]
Hmmmmmmm shows up as avahi-daemon. Not entirely sure what that is as I don't recall installing it, unless it comes standard on Ubuntu. Googling it looks like it's a service discovery thing similar to Bonjour.

> $ sudo ss -lp 'sport = :5353'
[sudo] password for jorg:
Netid        State          Recv-Q         Send-Q                 Local Address:Port                 Peer Address:Port        Process
udp          UNCONN         0              0                            0.0.0.0:mdns                      0.0.0.0:*            users:(("avahi-daemon",pid=793,fd=12))
udp          UNCONN         0              0                               [::]:mdns                         [::]:*            users:(("avahi-daemon",pid=793,fd=13))

Perhaps I installed this a long time ago when tinkering with other DNS solutions. Can I assume it's safe to uninstall? Thanks for the command. 

Edit: Or perhaps I could just change the port for DNScrypt

**Comment by jedisct1** [comment]
You know Linux better than I do, but to be safe, choosing a different port may be better.

**Comment by jorgsmash** [comment]
I changed the port to 5300 in the config and restarted the service. All is working now! I can't believe I didn't to check to see what was using 5353 because I just assumed it was DNSCrypt!
