### ISSUE TITLE
dnscrypt.ca-2 IPv6 Change

### ISSUE THREAD

**Issue by dnscrypt-ca** [DNSCrypt/dnscrypt-proxy#1425]
Greetings,

Please update the IPv6 entries for dnscrypt.ca Server 2 with these:

===

dnscrypt.ca-2-ipv6

Free, Canadian, uncensored, no-logs, encrypted, and DNSSEC validated DNS service for your pleasure.

sdns://AQcAAAAAAAAAHFsyNjA3OjUzMDA6NjA6NjUyZjo6MjAwXTo0NDMgmHxwqJfb2hUaNK1LVeqADvVhzASq1cV90sPYYfwX9CkiMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNhLTItaXB2Ng

dnscrypt.ca-2-ipv6-doh

Free, Canadian, uncensored, no-logs, encrypted, and DNSSEC validated DNS service for your pleasure.

sdns://AgcAAAAAAAAAGFsyNjA3OjUzMDA6NjA6NjUyZjo6MjAwXSA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBRkbnMyLmRuc2NyeXB0LmNhOjQ1MwovZG5zLXF1ZXJ5

Thank you,
s.

**Comment by jedisct1** [comment]
Updated, thanks!
