### ISSUE TITLE
[Question] Android 10 - Private DNS options predominate my dnscrypt 

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1429]
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description

I have my own ubuntu server running VPN on cloud with following tools.

1) Softether VPN Server
2) Dnscrypt - Anonymized DNS is active
3) Pihole

I am using Arne Schwabe - OpenVPN for Android app for only couple of apps. VPN is enabled only for couple of apps. Rest of apps are not using VPN.

Private DNS option predominate my dnscrypt options on Android 10 and Pihole adblocker doesnt work. i dont want to close private dns because other apps that are not using VPN is uslng private dns option.

Private DNS: 1dot1dot1dot1.cloudflare-dns.com

How can i overcome this issue?

Thanks
Onder

**Comment by Kein** [comment]
This isnt really dnscrypt issue and dnscrypt cant really solve that in any built-in way.
However, instead of VPN you could try using shadowsock proxy, it has custom DNS setup, albeit it is a bit buggy and wishes for something better but still, comparing to nothing it is the best option

**Comment by emsd1981** [comment]
Check
