### ISSUE TITLE
Question quad9

### ISSUE THREAD

**Issue by ibksturm** [DNSCrypt/dnscrypt-proxy#143]
hi there

thirst a big thank to the hole team for development dnscrypt-proxy

my question is, if its possible could you ad the quad9 server (9.9.9.9:853) in the resolverfile? or is there a roundabout to hack the ip manuali in the conf file?

**Comment by jedisct1** [comment]
Hi!

Quad9 doesn't seem to be support DNSCrypt or DNS-over-HTTP/2 yet.

They announced that they were working on implementing DNSCrypt a while back, but we're still waiting.

They will be added as soon as it is the case :)

**Comment by ibksturm** [comment]
Hi jedisct1

Thanks to your very fast response

greets
