### ISSUE TITLE
Log file using UTC time instead of local time even with TZ env-variable defined

### ISSUE THREAD

**Issue by CampionLoong** [DNSCrypt/dnscrypt-proxy#1434]
## *Who* is the bug affecting?
Logging to file

## *What* is affected by this bug?
timestamp is in UTC rather than local time

## *When* does this occur?
logging in all log file (query/blocked/whitelisted/nx)

## *Where* does it happen?
On a DD-WRT router (happens on R7000 and two board variants of R6300v2 I have) -- so an embedded system. 
logging in all log file (query/blocked/whitelisted/nx)

## *How* do we replicate the issue?

I can only speak to a DD-WRT environment. 'TZ' environmental variable is defined, which #57 suggests is a relevant detail:

> # env | grep TZ
> TZ=EST5EDT,M3.2.0,M11.1.0

Simply check log file timestamp - it is in UTC rather than local time.

**Comment by jedisct1** [comment]
Check that your system has a time database installed, and that `/etc/localtime` is properly set.

**Comment by CampionLoong** [comment]
> 
> 
> Check that your system has a time database installed, and that `/etc/localtime` is properly set.

DD-WRT uses busybox and '/' is a read-only filesystem, so I cannot do this (the the zoneinfo data-base is in /opt, installed via a repor - Entware ):

```
# ln -s /opt/share/zoneinfo/America/New_York /etc/localtime 
ln: /etc/localtime: Read-only file system
```

On the other hand, the TZ variable or /etc/TZ are present:
```
#more /etc/TZ
EST5EDT,M3.2.0,M11.1.0
#env | grep TZ
TZ=EST5EDT,M3.2.0,M11.1.0
```

It can be argued that DD-WRT should just have a user set-able /etc/localtime link (which I can raise on their side), but that being a popular embedded environment for router it'd be good if DNSCrypt-proxy can accomodate that. I got the impression from #57 that having a TZ variable is enough, but apparently DNSCrypt-proxy is not reading that now

**Comment by CampionLoong** [comment]
I believe this is a legitimate ask.  @jedisct1 would you consider this and, if you agree, re-open this?

**Comment by jedisct1** [comment]
This is all handled by the Go standard library, not by `dnscrypt-proxy`, so there's not much that can be done on our end.

Maybe the `TZ` variable should be set to something like `America/New_York`?

**Comment by CampionLoong** [comment]
Hum. Setting TZ to America/New_York doesn't change the timestamps either. How is the 'TZ' variable play out here -- is the description in #57 still true?

**Comment by jedisct1** [comment]
Quoting https://golang.org/src/time/zoneinfo_unix.go :

`$TZ="foo" means use /usr/share/zoneinfo/foo`

**Comment by CampionLoong** [comment]
I don't have write access to /usr/share, so I ended up needing to do this:

TZ='/opt/share/zoneinfo/America/New_York'

And unfortunately that doesn't do anything ...
