### ISSUE TITLE
Export periodically the list of Public DOH server used in a file 

### ISSUE THREAD

**Issue by dtouzeau** [DNSCrypt/dnscrypt-proxy#1435]
When defining DNSCrypt Proxy to a set of DOH public DNS services we can see only selected services in logs after booting the service.

Is there a way to have a list of really used DNS services trough a command-line or exported to a temp file periodically

## Describe the solution you'd like
Export each 60s the list of selected public dns services in the working directory.
Or output the list by a kill -USR1

**Comment by jedisct1** [comment]
Servers are visible in the query logs.

Using the LTSV output, it is fairly simple to extract only that column.

Query logs can also be processed by Flowgger/ElasticSearch/Kibana or equivalent for both a real-time view and historic views according to any criteria.
