### ISSUE TITLE
Query logging to syslog

### ISSUE THREAD

**Issue by dtouzeau** [DNSCrypt/dnscrypt-proxy#1436]
## Is your feature request related to a problem?
Unbale to use a SIEM or a syslog server in Query logging

## Describe the solution you'd like
instead of 

```
[query_log]
## Path to the query log file (absolute, or relative to the same directory as the config file)
## Can be set to /dev/stdout in order to log to the standard output.

file = 'query.log'
```

should be 

```
[query_log]
## Path to the query log file (absolute, or relative to the same directory as the config file)
## Can be set to /dev/stdout in order to log to the standard output.
## Can be set to "syslog" in order to log to the standard syslog system.
file = 'syslog'
```

**Comment by jedisct1** [comment]
I don't think query logs are a good fit for syslog, as they would be mixed up with other unrelated messages.

If this is really what you want, a posible way to achieve this is to pipe the file's (which can be a named pipe) content to the `logger` command.
