### ISSUE TITLE
Question about blacklist

### ISSUE THREAD

**Issue by ibksturm** [DNSCrypt/dnscrypt-proxy#144]
hi there

second question, how does the blacklist work and how could i activate? and yeah, i found in config file the entry and yea i made some blacklist file with the py script ^^ but it seams proxy doesnt want run with blacklisting

greets

**Comment by jedisct1** [comment]
Hi,

Can you mention what your environment is, all the steps you went through, what was expected and what actually happened, so that your issue can be reproduced on a newly installed system?

**Comment by ibksturm** [comment]
hi there 
i found the problem, it was between the keyboard and the chair... *shame*
i wrote the absolut path in the config file to the blacklist.txt and wrote ....../dncrypt-proxy/... instead of .../dnscrypt-proxy/...

now its blocking in web browser (tested with wemfbox.ch and doubleclick.net), on iphone and its writen in the blackbox logfile from dnscrypt

**Comment by sergeevabc** [comment]
@jedisct1, I have tried a lot of blocklists to date, even StevenBlack’s one (a [rude][1] fellow, who blindly aggregates various half outdated lists), and found NoTracking’s [hostnames.txt][2] to suit my needs best, i.e. zero false alarms for a long time. It uses ```0.0.0.0 host``` format and works fine on the router, but how to make it work with DNSCrypt on Windows (of course, without renaming it to ```hosts``` and placing to ```System32/drivers/etc```)? Is it possible to support this popular format out of the box without conversion?
 
[1]: https://github.com/StevenBlack/hosts/issues/281
[2]: https://github.com/notracking/hosts-blocklists

**Comment by jedisct1** [comment]
You can simply add it to your `domains-blacklist.conf` file.

Note that it doesn't seem to be a very useful list. It contains very few records that are not already present in other lists, even the default ones from the example configuration:

```
########## Blacklist from https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt ##########

# Ignored duplicates: 21224

# Ignored entries due to the whitelist: 146
```

**Comment by jedisct1** [comment]
Using his more efficient `domains.txt` list, there are only 6 entries that are not present in other lists already:

```
########## Blacklist from https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt ##########

# Ignored duplicates: 30734

# Ignored entries due to the whitelist: 6
```

This has been added to the example configuration no matter what, but all these lists still mostly have the same content.

**Comment by sergeevabc** [comment]
@jedisct1, thank you for a quick examination, let me try your mybase.txt then (however it blocks fewer .ru).

**Comment by sergeevabc** [comment]
> but all these lists still mostly have the same content

While trying out ```mybase.txt``` I immediately faced a false alarm about ```liveinternet.ru``` ([details][1]).
And I see no easy way to whitelist it as the [corresponding issue][2] contains no solution so far.

[1]: https://github.com/StevenBlack/hosts/issues/281
[2]: https://github.com/jedisct1/dnscrypt-proxy/issues/198

**Comment by jedisct1** [comment]
https://github.com/jedisct1/dnscrypt-proxy/blob/master/utils/generate-domains-blacklists/domains-whitelist.txt

**Comment by jedisct1** [comment]
https://github.com/jedisct1/dnscrypt-proxy/blob/fa2c95084ef9b575bfbe62543e0765623c9b8a0e/utils/generate-domains-blacklists/domains-blacklist.conf#L16-L17

**Comment by sergeevabc** [comment]
Hmm, at first I created ```domains-whitelist.txt``` with ```liveinternet.ru``` in it and restarted ```dnscrypt-proxy.exe```, then I realized it was not meant to work this way. Your offer seems to be about using external Python script ```generate-domains-blacklist.py``` to generate my own version of ```mybase.txt```, right? Alas, being a mere user, I stay away from Python. Well, it seems I have to wait till an internal feature is ready.

**Comment by jedisct1** [comment]
If this is a false positive, you should report it to the lists it comes from.

**Comment by sergeevabc** [comment]
@jedisct1, for the third time this evening I post [the link][1] about my experience on removing false positive. Problem is false positives are copied between lists, then some douchebag, who aggregates those lists to makes “best” version, says “multiple sources cannot be wrong”. That’s why I switched to NoTracking’s list. Also, I was lucky to convince [AdGuard][3] and [Cryptostorm][2] teams to give it a try as well. 

So whitelisting feature is a crucial one to overcome list errors that might not be corrected by uplink ever.

[1]: https://github.com/StevenBlack/hosts/issues/281
[2]: https://github.com/cryptostorm/cstorm_deepDNS/issues/4
[3]: https://github.com/AdguardTeam/AdguardDNS/issues/148#issuecomment-311228763

**Comment by sergeevabc** [comment]
Alright, an hour in the morning is worth two in the evening.
So I wrote the following script to download and convert Notracking’s list to DNSCrypt’s format:
```
@echo off
wget -q -N https://raw.github.com/notracking/hosts-blocklists/master/hostnames.txt
gawk "/::|#/ {next} {print substr($0,9)}" hostnames.txt > blacklist.txt
rm -f hostnames.txt
```
The only thing that troubles me further is the _speed_ of blocking requests.

Let’s blacklist ```content.ad``` via DNSCrypt, then ```ping content.ad```, then repeat using Windows feature by means of inserting ```0.0.0.0 content.ad``` into ```hosts```. The former option expects something for a while, while the latter option does the job instantly. Is it possible to tune DNSCrypt to block just as fast?

**Comment by ghost** [comment]
@sergeevabc  wrote,

> Alas, being a mere user, I stay away from Python. Well, it seems I have to wait till an internal feature is ready.

Same here. Exactly. Would be nice to have a dedicated whitelist feature alongside the blacklist, integrated to dnscrypt-proxy. Maybe in a future version?

**Comment by jedisct1** [comment]
+1
