### ISSUE TITLE
anonymized_dns with skip_incompatible = true does not skip incompatible

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1440]
Hi,

dnscrypt-proxy 2.0.44 / Windows 7 (x64), running smoothly.

I was just surprised to notice that even though I had set `anonymized_dns` with `skip_incompatible = true`, server was honored and no connection issue.

`server_names = ['decloudus-prod-ipv4']`

```
[anonymized_dns]
skip_incompatible = true
```

```
[WARNING] [decloudus-prod-ipv4] is incompatible with anonymization
[NOTICE] Server with the lowest initial latency: decloudus-prod-ipv4 (rtt: 21ms)
```

Only one server running, warning it is incompatible, skip_incompatible = true and yet connection is established

`skip_incompatible `is explained as: 

> skip resolvers incompatible with anonymization instead of using them directly

I must be missing something ... thanks for further info.

**Comment by jedisct1** [comment]
`server_names` defines a set of servers you explicitly want to use. Filters don't apply to that list.

Filters are used when the servers list is empty, which means "use all servers matching the set of filters".

**Comment by ghost** [comment]
> server_names defines a set of servers you explicitly want to use. Filters don't apply to that list.

Filters don't apply to that list : where is this mentioned?  Reading and following the _example-dnscrypt-proxy.toml_ shows nowhere that filters don't apply to the` server_names` defined by the user, and reading that _skip_incompatible = true means that incompatible resolvers with anonymization will be skipped_ seems clear as it is. Maybe  the ambiguity could be removed with extra info in the _example-dnscrypt-proxy.toml_ file. Not everyone is an expert nor fluent with technological semantics.

**Comment by jedisct1** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Configuration-Sources#filters

**Comment by ghost** [comment]
So it appears it is mentioned, somewhere in this repository, and that somewhere is https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Configuration-Sources#filters
OK. Remains that having to read in extenso an application's wiki in order to nuance what is explicitly mentioned in the application's Configutation (example-dnscrypt-proxy.toml) is IMO not the best approach. I've added to and emphasized in my dnscrypt-proxy.toml:

```
## LIST OF SERVERS TO USE ##
## https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Configuration-Sources#filters
## server_names DEFINES A SET OF SERVERS YOU EXPLICITLY WANT TO USE. FILTERS DON'T APPLY TO THAT LIST.
## Filters are used when the servers list is empty, which means "use all servers matching the set of filters".
```

Three lines which enlighten the user immediately.
Anyway, I've been using DNSCrypt-proxy for years and it's only here and now that I discover that

> This [filters] applies to the case where server_names is empty, which means "use all the resolvers, from all lists, matching the criteria".
> If you explicitly list the resolvers you want to use in server_names, your choice will be respected no matter how the filters are configured.

There we go.

**Comment by ghost** [comment]
Hello.

I wanted to ask the same question, but since there is already a proper thread, I will ask here:

So, all filter-related (e.g. `require_{dnssec,nolog,nofilter}`) and `skip_incompatible` options are valid only when `server_names` option (vide `.toml` file) is empty - which means using all available Servers - and there is not any Server/s added by the User, right?

By the way: is it possible to make `skip_incompatible` option to be respected and used even when there are Servers configured/added by the User (I mean `server_names` option, of course)? It seems, that not everyone is using all available Servers (but let say: three, five etc.), so such an important option - to skip incompatible Servers, could be very needed.

Thanks, best regards.
