### ISSUE TITLE
Can I have multiple listen ports, one for each upstream server.  Instead of one listen port which automatically picks from all my upstream server.

### ISSUE THREAD

**Issue by chrcoluk** [DNSCrypt/dnscrypt-proxy#1443]
## Subject

Can I have multiple listen ports, one for each upstream server.  Instead of one listen port which automatically picks from all my upstream server's.

## Description

The old dnscrypt-proxy was one process per upstream server, so something like unbound I could easily pick which dnscrypt I wanted to use based on listening port, can I do the same with this?

**Comment by jedisct1** [comment]
Yes, you can run multiple `dnscrypt-proxy` instances, each listening to its own IP/port and with its own configuration.

**Comment by chrcoluk** [comment]
thanks, I did this now, made a custom rc.d script, where it scans a location for toml files and runs an instance for each one.
