### ISSUE TITLE
dd wrt dnscrypt 2.0.42 

### ISSUE THREAD

**Issue by Ninjanoir87** [DNSCrypt/dnscrypt-proxy#1444]
## Subject

* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

hi, 

since I ve updated with 2.0.42, I just use one server (nextdns) and before 2.0.42 version in my dd wrt log, everything was clean, now I have many log entries about multiple stamp servers::

**_`Aug 10 05:44:11 DD-WRT daemon.notice dnscrypt-proxy[8471]: Source [public-resolvers] loaded
--
**_Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [cloudflare-family-ipv6]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [cloudflare-ipv6]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [cloudflare-security-ipv6]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [faelix-ch-ipv4]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [faelix-ch-ipv4-doh]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [faelix-ch-ipv6]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [faelix-ch-ipv6-doh]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [faelix-uk-ipv4]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [faelix-uk-ipv4-doh]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [faelix-uk-ipv6]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [faelix-uk-ipv6-doh]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [quad9-dnscrypt-ip4-filter-pri]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [quad9-dnscrypt-ip4-nofilter-pri]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [quad9-dnscrypt-ip6-filter-pri]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [quad9-dnscrypt-ip6-nofilter-pri]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [quad9-doh-ip4-filter-pri]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [quad9-doh-ip4-nofilter-pri]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [quad9-doh-ip6-filter-pri]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [quad9-doh-ip6-nofilter-pri]
Aug 10 05:44:11 DD-WRT daemon.warn dnscrypt-proxy[8471]: Multiple stamps for server [safesurfer]
Aug 10 05:44:11 DD-WRT daemon.warn  dnscrypt-proxy[8471]: Error in source [public-resolvers]: [Multiple  stamps for server [cloudflare-family-ipv6], Multiple stamps for server  [cloudflare-ipv6], Multiple stamps for server  [cloudflare-security-ipv6],_**_** Multiple stamps for se
Aug 10 05:44:11 DD-WRT daemon.notice dnscrypt-proxy[8471]: Source [relays] loaded
Aug 10 05:44:11 DD-WRT daemon.notice dnscrypt-proxy[8471]: Firefox workaround initialized
Aug 10 05:44:11 DD-WRT daemon.notice dnscrypt-proxy[8471]: Now listening to 127.0.0.3:30 [UDP]
Aug 10 05:44:11 DD-WRT daemon.notice dnscrypt-proxy[8471]: Now listening to 127.0.0.3:30 [TCP]
Aug 10 05:44:11 DD-WRT daemon.notice dnscrypt-proxy[8471]: [NextDNS-ee6135] OK (DoH) - rtt: 26ms
Aug 10 05:44:11 DD-WRT daemon.notice dnscrypt-proxy[8471]: Server with the lowest initial latency: NextDNS-ee6135 (rtt: 26ms)
Aug 10 05:44:11 DD-WRT daemon.notice dnscrypt-proxy[8471]: dnscrypt-proxy is ready - live servers: 1`

**Comment by jedisct1** [comment]
For some reason, you seem to be using a configuration file for a more recent version on an old version of the software.

Either change `/v3/` to `/v2/` in the configuration file, ignore the message (this is an informational message, not an error), or use a more recent version (the configuration file you have seem to be for version 2.0.44).
