### ISSUE TITLE
domain redirect to a landing page by isp

### ISSUE THREAD

**Issue by TehBotolSosro** [DNSCrypt/dnscrypt-proxy#1445]
Hello,

I use SimpleDnsCrypt which is the third party gui for dnscrypt-proxy on windows 10 x64

my Fiber Optic ISP Telkom is an Indonesian state-owned ISP which basically the only isp that have better Fiber Optic national coverage so i'm forced to use them since other privately-owned fiber company are not yet available in my place

the ISP is a bit malicious since they do http injection (https://gist.github.com/donnykurnia/2356dad4119ce85d18d18708914c60e3) to inject their own ads and do some analytics?! 

they also have transparent dns and dns hijacking so people can't access sites that are on national block list (reddit/netflix/vimeo/piracy/porn/extremist/fake news) but this one can be solved by using the dnscrypt

the issue i'm having, is sometime the isp redirect me to a landing page, it's happen randomly it seem it's happen when i try to visit new site or visit a site that i haven't visited in a while, and this seem to happen several times a day, example i entered wikipedia.com in a browser and instead of opening wikipedia, the browser instead redirect me to welcome.indihome.co.id (some kind of landing page)

i already block the site in my router but the redirect it self is a bit annoying since i need to reenter the url to visit the site i'm trying to visit.

so my question is there a solution to avoid this domain redirection with dnscrypt? also does anyone  can explain how they can do this type of redirect 

thank you for this wonderful software 👍

**Comment by jedisct1** [comment]
In addition to DNS, they probably also redirect some IP addresses.

Against IP address redirection, your only hope is using a VPN or Tor.

**Comment by TehBotolSosro** [comment]
could it be also possible it's because when i click a link on a site or type the url address, the url is an http:// and the isp did http injection that redirect to a landing page even though i'm using dnscrypt?

thanks for responding

**Comment by jedisct1** [comment]
That can also be the case.

The [HTTPS everywhere](https://www.eff.org/https-everywhere) extension can prevent most websites to be used over `http` instead of `https`.

**Comment by TehBotolSosro** [comment]
will definitely try https everywhere first before choosing the vpn
thanks
