### ISSUE TITLE
DNSCrypt-Proxy and DoH 'local_doh' - a few doubts.

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1446]
Hello.

I would like to ask a simple question related to `local_doh` and Firefox configuration editor: **about:config** - just to be one hundred percent sure. 

So, enabling `local_doh` feature will cause Firefox to tolerate and use all the `TRR` (_Trusted Recursive Resolver_) options such as - for example - _disable-ECS_, _allow-rfc1918_ or _ESNI_ etc., right? (On the other hand, mentioned options cannot be used - they simply will be not tolerated by Firefox when DoH will be used without `local_doh`, right?).

By the way: both Wiki page [1] and `example-dnscrypt-proxy.toml` file (please see `local_doh` [in:] "_Local DoH server_" section) mentions `127.0.0.1:3000` IP address and port. What about, for example Debian and all available Distributions based on this system where - if I remember correctly - `127.0.2.1` address  is used? 

What could be done in such a situation? Does Users should use `127.0.2.1` for DNSCrypt and `127.0.0.1:3000` for `local_doh` or both address needs to be exactly the same?

If yes, then is it sufficient to change `local_doh` address to `127.0.2.1:3000`? (Or maybe DNSCrypt default address, should be changed to address used in mentioned sources, so it will be `127.0.0.1:3000`?)

Thanks, best regards.
_______________________
[1] https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Local-DoH

**Comment by jedisct1** [comment]
IP addresses in Firefox and in the `local_doh` setting must match. That's all what is required.

They can both be `127.0.0.1` or `127.0.2.1`; this is equivalent.

It would recommend sticking to `127.0.0.1` as it is going to work everywhere, while `127.0.2.1` seems to be a alternative choice made by some Debian package.

**Comment by ghost** [comment]
Hello.

Thanks for an answer. So, as You've written "_IP addresses in Firefox and in the local_doh setting must match_" - lets assume such a situation: DNSCrypt-Proxy address is `127.0.2.1`. 

User want to enable DoH with `local_doh`. He needs to change default `127.0.0.1` address, found in an example file (vide `example-dnscrypt-proxy.toml`) to the address used by default in DNSCrypt-Proxy (I mean Debian and Debian-base distributions), which is: `127.0.2.1`, right?

According to the above statement, listen address in a "_Local DoH server_" section, should looks this way?
```
[local_doh]
listen_addresses = ['127.0.2.1:3000']
```
And here is a change in `dnscrypt-proxy.toml` file (or in a `dnscrypt-proxy.socket` file if User is using `systemd` activaction, right?):
```
# Empty listen_addresses to use systemd socket activation
listen_addresses = ['127.0.2.1:3000']
```
Am I right? 

And what about first question about all the `TRR` (_Trusted Recursive Resolver_) options such as - for example - _disable-ECS_, _allow-rfc1918_ or _ESNI_? Enabling `local_doh` makes these options available for DNSCrypt-Proxy Users, right? (Without `local_doh`, Firefox simply ignore them?).

I want to apologize for such a naive questions. Best regards.

**Comment by jedisct1** [comment]
`listen_addresses` in the `global` section is for standard DNS queries. Keep that on port `53`; it can't be the same port as `listen_addresses` in the `local_doh` section.

`dnscrypt-proxy` doesn't add ECS information, with or without local DoH, so I don't think the related option in Firefox does anything. `dnscrypt-proxy` also let you block any IP addresses, so `allow-rfc1918` in Firefox isn't very useful either. Besides participating in the ESNI test program, enabling TRR doesn't bring anything.

**Comment by ghost** [comment]
Hello **jedisct1**.

Okay, thanks. Regarding your opinion about _disable-ECS_, _allow-rfc1918_ and _ESNI_, do You think that enabling `local_doh` has some advantages? I'm asking, because - for example - disabling _ECS_ could be an interesting addition to Users privacy etc.

Anyway, sorry but I wasn't precise enough in my previous message. One more time: if `127.0.2.1` address is used in DNSCrypt, then `local_doh` section also should contain `127.0.2.1` address? 

Or maybe something oposite is correct: I mean DNSCrypt with `127.0.2.1` address and `local_doh` with a default address used in `example-dnscrypt-proxy.toml` file, which is `127.0.0.1`?

Summarizing: IP address have to be the same for both: DNSCrypt and `local_doh` or it doesn't matter? (I know, that port number should be different).

I'm sorry for such a naive questions. This is my last message/question in this thread.

Best regards.

**Comment by jedisct1** [comment]
IP addresses don't have to be the same.
