### ISSUE TITLE
[SOLVED] How do I configure dnscrypt to never depend on a public-resolvers.md but instead connect to a specific DNSCrypt server using the sdns key?

### ISSUE THREAD

**Issue by MystesofEternity** [DNSCrypt/dnscrypt-proxy#1448]
## Subject
* [-] Other

## Description

I stumbled upon this post while I was doing research on another subject:
https://forum.ipfire.org/viewtopic.php?f=50&t=11252&p=75655&hilit=dnscrypt#p75655

Particularly this one:
dnscrypt-proxy --provider-key=2342:215C:409A:85A5:KL25:2A3B:42CD:5089:6BA8:551A:8BDC:4267:CF57:804F:B1B2:8039 --provider-name=2.dnscrypt-cert.ns17.ca.us.dns.opennic.glue --resolver-address=173.230.156.28:443 --local-address=127.0.0.1:5353 --pidfile=/run/dnscrypt.pid --daemonize

I was amazed at the fact that dnscrypt-proxy used to not rely on having to fetch a public-resolvers.md list in order to function properly, which was exactly what I was looking for!

So I tried searching through the docs for something about running dnscrypt-proxy being configured to stick to a specific provider by manually providing the key/sdns key, provider name, and resolver address but no luck on my search.

I also tried running the binary with the --help argument and I noticed that those parameters weren't even mentioned in the text that was displayed by --help.

Because of that, I would like to humbly request for the specifics in getting to run dnscrypt-proxy without having to depend on undeterred access to a publicly available source of public-resolvers.md because I suspected that I was hit by an attack either by the ISP itself or a hacking group lurking in the ISP that specifically kept me from getting public-resolvers.md on both the raw.githubusercontent.com and dnscrypt.info.

Manually getting it thru a VPN on my hardened Linux configuration did the trick to make it work but I think it's a major hassle to have to do this periodically just to make it work. Asides from that, I only use one resolver anyways.

**Comment by welwood08** [comment]
Those command-line options were from v1, in v2 they've been replaced with options in the .toml configuration file. If you look in the `example-dnscrypt-proxy.toml` file, you should focus on the `[sources]` and `[static]` sections to do what you want.

**Comment by MystesofEternity** [comment]
Wonderful! It worked nicely!
I figured it out thanks to your reply, you have my gratitude for leading me to the solution!
