### ISSUE TITLE
Hope

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#1450]
The dnscrypt-proxy code is changed quickly,hope releases update at the same week,maybe beta version,thank you!

**Comment by welwood08** [comment]
Is there anything specific that you think needs an urgent release?

If you just want to test the latest code, it's easy to build it yourself.

**Comment by jedisct1** [comment]
The current version (2.0.44) is fine!

There's no need to rush releasing a new version :)
