### ISSUE TITLE
[Feature Request] Auto-Update Blacklists

### ISSUE THREAD

**Issue by FrigidReward** [DNSCrypt/dnscrypt-proxy#1453]
## Is your feature request related to a problem?

It's a minor inconvenience, but having to manually update blacklists can waste one's time. Even if it's only a few minutes every day/week/month.

## Describe the solution you'd like

I want to have an ability to add my blacklists from links & have the ability to auto-update instead of having to do it manually. 

## Alternatives you've considered

On my iOS devices, Adguard Pro has the aforementioned feature where one can simply type in a link for a blacklist & it would be automatically added & updated. 

## Who will that feature be useful to?

I think it would be an improvement to all users & permit them some convenience. Having the ability to auto-update one's blacklist takes away the need to spend a few minutes every day/week/month manually downloading files and importing them. 

## What have you done already?

I don't have any skills in programming/coding, therefore, I have nothing to showcase. 

## What are you going to contribute?

I could probably contribute to some testing, but that's about it due to my current lack of skills in programming/coding.

**Comment by alisonatwork** [comment]
This feels like something that would be better written as a separate tool, because everyone has their own favorite bundle of block lists. On a UNIX machine, it could be implemented as a very short shell script run as a cron job - download the file, move it into the right place (keeping a backup of the old file), then restart the server. On Windows it could be a bit trickier, but still doable. Which platform are you using?

**Comment by dfaslfjasdlf** [comment]
This is "FrigidReward." I had lost the aforementioned account. 

Nevertheless, I use all operating systems (Windows, MacOS & Linux - specifically Manjaro). 

> This feels like something that would be better written as a separate tool, because everyone has their own favorite bundle of block lists

In regards to that, I beg to differ. I believe that it would not be better for the feature to be implemented separately. Yes, everyone would have their own favorite bundles of block lists, but an inherent feature to automatically update & add their **own collection** surely would not interfere.
