### ISSUE TITLE
EdgeOS Cache Question

### ISSUE THREAD

**Issue by samphonic** [DNSCrypt/dnscrypt-proxy#1463]
## Subject
* [x] Other

## Description
I'm following the [EdgeOS install instructions](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-EdgeOS) (which are very clear so far, nicely done) on my EdgeRouter-X, and essentially I'll be pointing the built-in dnsmasq server to the local instance of dnscrypt-proxy using the `server=127.0.0.1#5353` forwarding option.  Dnsmasq is already caching queries on its own, and it seems like out of the box dnscrypt-proxy will **also** maintain its own cache.  I don't think having a double-cache will cause any problems per se, but it does seem like wasted effort/RAM.

- Should I disable dnscrypt-proxy's cache if I'm using it behind dnsmasq?  (If so, that might be a good addition to the installation wiki linked above)
- Would there be any advantage to disabling the cache on dnsmasq instead and using only dnscrypt-proxy's cache?

**Comment by rhester72** [comment]
I always disable dnscrypt-proxy's cache for exactly that reason.

**Comment by jedisct1** [comment]
I'd rather disable `dnsmasq` cache, since `dnscrypt-proxy`'s cache is more flexible and can serve records even expiration when connectivity is unreliable.
