### ISSUE TITLE
Consistingly use 'log_file =' in toml

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1464]
Some logs use 'file =' (query.log, nx.log) others 'log_file =' in the toml. Would be nice if they could all be the same for consistency and also e.g. making it easier to switch them all on or off at once.

**Comment by welwood08** [comment]
Duplicate of #1278. There is a logic to it and I'm not sure changing it is worth breaking everybody's configuration.

**Comment by ghost** [comment]
Sorry for the duplicate and thanks for the answer.
Currently 'file =' is only used for logs. Can I rely on that? I.e. are 'file =' and 'log_file =' only ever used for log files?

**Comment by jedisct1** [comment]
In a section already entirely dedicated to a log file:

```toml
[query_log]
```

```toml
[nx_log]
```

It would be redundant to prefix all properties with `log` (`query_log.log_file`, `query_log.log_format`).

Whereas in a section that covers something else, and where a log file is just one of the features, the `log` prefix clarifies what the file is about.
