### ISSUE TITLE
Strange behaviour of public DoH/DNScrypt servers

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#1465]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ X] Other

## Description

I am using DNScrypt proxy on my NAS for all devices at my home.
Today i wanted to cancel Disney+ ( ;-) ) at my telco provider, German Telekom, - impossible.
Reason was that the upstream Doh/DNScrypt servers i have configured did reject one of the URLs of that service:

- pix.telekom.de

even if had choosen only to use servers with no logging and no filters in dnscrypt.toml file.
Even at the webpage https://dnscrypt.info/public-servers/ 
these servers are listed as no-logging, no filtering
In particular these have been 
[2020-09-03 12:00:44]   192.168.178.47  pix.telekom.de  A       REJECT  24ms    skyfighter-dns

skyfighter-dns:
Uncensored, DNSSEC, no logging DNSCrypt server in Netherlands by Scaleway.com Maintained by tuttimann 
or

[2020-09-03 12:01:06]   192.168.178.47  pix.telekom.de  A       REJECT  25ms    ams-dnscrypt-nl
ams-dnscrypt-nl:
Resolver in Amsterdam. Dnscrypt protocol. Non-logging, non-filtering, DNSSEC

ok, pix.telekom.de is an alias for

pix.telekom.de
Server:  fritz.box
Address:  192.168.178.1

Nicht autorisierende Antwort:
Name:    telekom01.webtrekk.net
Address:  185.54.150.52
Aliases:  pix.telekom.de

and indeed webtrekk.net is inside my local blacklist. So if i try to resolve locally this real name i get the rejection i expect:

[2020-09-03 12:06:08]   192.168.178.47  telekom01.webtrekk.net  A       REJECT  0ms     -

as this domain webtrekk.net is included inside
http://someonewhocares.org/hosts/hosts

which i have sourced in my domains-blacklist.conf file

But i'm worring about the fact that the non-filtering upstream servers  reject this !!!!

**Comment by ghost** [comment]
Nothing's strange.
An alias means another name/address for the same website. You cannot only block one of them (pix.telekom.de or telekom01.webtrekk.net) because they are the same.
 The resolvers didn't block anything, it's your local blacklist.
So it seems you need to unblock/whitelist telekom01.webtrekk.net to watch Disney+.

**Comment by scubasunny** [comment]
Sorry but my problem is that the **upstream** DNS servers do REJECT 
 [2020-09-03 12:00:44] 192.168.178.47 pix.telekom.de A REJECT 24ms **skyfighter-dns**
[2020-09-03 12:01:06] 192.168.178.47 pix.telekom.de A REJECT 25ms **ams-dnscrypt-nl**

and this is what **they shouldn't do** - at least as they are "marked" as non-logging and **non-filtering**

**Comment by ghost** [comment]
Tested both resolvers and they resolve pix.telekom.de just fine as expected.

What happens for you is that because pix.telekom.de is _not_ in your blacklist it is send to the resolver and it resolves it, including the information that it is an alias for telekom01.webtrekk.net. Because webtrekk.net is in your blacklist DNSCrypt now rejects the answer for pix.telekom.de, too, because it's the same as telekom01.webtrekk.net.

**Comment by jedisct1** [comment]
Hi,

`REJECT` means that a query has been blocked by a rule in your local configuration, not by a server.

**Comment by scubasunny** [comment]
Hi
are you sure about this?
In my local config for instance i block access to .local and then i get in the logfile
2020-09-03 12:57:12]   192.168.178.39  nexus.officeapps.live.com       A       REJECT  0ms     -
so - no servername 
same for ;-)
[2020-09-03 13:35:47]   192.168.178.47  xhamster.com    A       REJECT  0ms     -
as this is somewhere in the porn block section i load.

Anyway i could solve this by deleting webtrekk.net from the blacklist.
On the other hand adding to whitelist DID not help.
This all seems a bit strange to me, maybe adding this rejection of aliases in the logfile could help in such cases as they are happening more often. And then out of the blue some webapps are not working properly.
I know thats always a thin red line between blocking and functional webpages.

**Comment by jedisct1** [comment]
You can see that it was blocked due to it being an alias in the blocklist log:

```text
127.0.0.1       telekom01.webtrekk.net  *.webtrekk.net (alias for [pix.telekom.de])
```

**Comment by scubasunny** [comment]
Your are fully right !
The only thing that irritated me that after the reject the upstream DNS server was noted. 
The first impression then is that this **server rejects** the query and not a local rule

**Comment by jedisct1** [comment]
`dnscrypt-proxy` still needs to send the query to a server in order to learn that it is an alias.

A direct query for the `webtrekk.net` wouldn't have a server logged, because the response would be instant. But here, `dnscrypt-proxy` sent a query, then learned in the response that it was actually `webtrekk.net` and blocked it based on the response, not the query. The upstream server was necessary :)

**Comment by jedisct1** [comment]
That's also why the alias technique is not used by trackers; it's more difficult to block, as responses have to be inspected by blocked, not just queries any more.

**Comment by scubasunny** [comment]
This i fully understand 
The only thing which mislead me was the reject and behind the server name in the query log as I didn’t looked at the blocked log at same time
My fault 
Maybe that logentry into query log could be enhanced?
