### ISSUE TITLE
Cosmetics/consistency: use single quotes everywhere in toml

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1466]
query_meta, local_doh and dns64 use double quotes, everything else uses single quotes (except comments).

**Comment by jedisct1** [comment]
Thanks!

These single quotes feel very unnatural.

**Comment by welwood08** [comment]
The difference is double quotes denote basic strings which support backslash escapes whereas single quotes are for literal strings without escaping, not important either way for how we were using them.

**Comment by jedisct1** [comment]
Ah, right!

I now remember that the reason double quotes were changed to simple quotes was to make it easier to use backslashes-delimited paths on Windows.
