### ISSUE TITLE
[Feature Request] Multiple requests

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-proxy#1467]
Usally dnscrypt-proxy send single requests (by random or fastest load-balance policy) but sometimes responses have high lag time (200 ms-1200 ms) with nearest servers and low ping (uncached domains?). It's possible for implementation when dnscrypt-proxy will do a multiple requests to 2-4 servers by one time and choose just fastest response? 

```
                                      1120 ms             
                                         |                
                                         |                
                       720 ms            |                
                         |               |                
                         |               |                
       340 ms            |               |                
         |               |               |              52 ms - fastest response for client
         |               |               |                |
	dns1		dns2		dns3		dns4
         |---------------|---------------|----------------|
				 |
			   dnscrypt-proxy	

```

**Comment by jedisct1** [comment]
Unfortunately not. That would be very selfish and triple the load on servers, only to make most of the responses they send completely useless.
