### ISSUE TITLE
[Feature Request] Automate Anonymized DNSCrypt

### ISSUE THREAD

**Issue by tartpvule** [DNSCrypt/dnscrypt-proxy#1468]
## Is your feature request related to a problem?
Currently, setting up Anonymized DNSCrypt involves manually digging through the MD files (e.g. `public-resolvers.md` and `relays.md`) and manually putting things into the configuration file. This is tedious and just not scalable.

## Describe the solution you'd like
Automate the steps outlined in the Anonymized DNSCrypt specification:
```
Clients choose the relay they want to use, as well as the server. As
not doing so would defeat the purpose of Anonymized DNSCrypt, users
should carefully choose them so that they are operated by different
entities. Having these services on different networks is also
recommended.
```
For the MD files, it will probably need to have metadata in each entries that describe, at minimum, the owner entity and country.

## Alternatives you've considered
Seeing as the steps are outlined in the specification, I don't see alternatives apart from leaving it to the user to do everything manually as it currently is.

## Who will that feature be useful to?
Everyone who uses or plan to use Anonymized DNSCrypt.

## What have you done already?
Obligatory Disclaimer: protoype, crude, incomplete, not ready for production, bugs galore, etc.
I have attached a configuration file generator script written in NodeJS JavaScript that does the process semi-automatically.
Rename it to `.js`.
It fetches `public-resolvers.md` and `relays.md`, processes them and put them into a template file (`template.toml` in the same directory as the script) at specific substrings (`SUBSTR_DISABLED_NAMES` and `SUBSTR_ROUTES`)
It requires the modules `node-fetch` and `binary-parser` from npm.
Due to the lack of easily parsable metadata, the user has to define "keywords" in the script that identify "owner entities" in both resolver's and relay's names, so the script can avoid putting them together.
Run `node dnscrypt-proxy-anongen.js` and it will print the resulting TOML config to stdout.

[dnscrypt-proxy-anongen.txt](https://github.com/DNSCrypt/dnscrypt-proxy/files/5178346/dnscrypt-proxy-anongen.txt)

## What are you going to contribute?
I have no Go programming knowledge, and thus will be unable to contribute code.

## Additional context
Seeing that Tor does automatic circuit creation over (by default) 3 relays, perhaps such an idea might also be useful to DNSCrypt?

P.S. The JavaScript implementation of DNS Stamps linked in the Wiki page (`https://github.com/rs/node-dnsstamp`) seems to be outdated and could not parse relay stamps.

**Comment by jedisct1** [comment]
This requires solving a bunch of complicated problems.

1) Clustering servers by entities operating them. The easiest way to do it is probably to use IP-to-ASN maps, and since companies can own multiple ASNs, cluster servers according to the owner information for these ASNs. This is still far from reliable, and a reason why I wouldn't even consider automation for that task.
2) Satisfying other constraints about servers/relays relationships that people may expect. Such as these being in different countries, or in different country sets. But of course, one may still want to minimize latency, so how do you weights these constraints? Can we make an exhaustive list of these constraints? What would the actual cost function look like?
3) On latency minimization, how to pick the optimal server/relay tuples? The latency between a client and a relay can be measured (albeit not reliably without a protocol extension). The latency between a relay and a server can't without a substantial amount of samples. The average latency for the end server to resolve a name is a different metric and also requires a substantial amount of samples. That's a multi-armed bandit problem. An exhaustive search would not be a reasonable way to solve this. 

A neural network may be a way to approach these problems. But I don't think we can come up right of the bat with a perfect model ready to merge in this repository. 

If you want to tackle these problems, go ahead. This is fun research. And the programming language is irrelevant.

Unfortunately, I really don't have the skills or time to solve them.

**Comment by tartpvule** [comment]
> Clustering servers by entities operating them. The easiest way to do it is probably to use IP-to-ASN maps, and since companies can own multiple ASNs, cluster servers according to the owner information for these ASNs. This is still far from reliable, and a reason why I wouldn't even consider automation for that task.

That is not just complicated, it is unsolvable, even for humans.

1. ASNs are just not suitable for this, and there is really no way for humans to *definitively* do it either. For example, AS54680 "Hewlett-Packard Company" and AS25867 "HEWLETT PACKARD ENTERPRISE COMPANY", a program must recognize that they are probably the same entity. An impossible task in the case of ASfoofoo "Contoso Corporation" and ASblahblah "Northwind Traders".
2. There is still the problem of hosting services. For example in the current `public-resolvers.md`, there are `v.dnscrypt.uk-ipv4` in Vultr and `dnscrypt.uk-ipv4` in Digital Ocean, but both are operated by the same entity. Parsing the information out of the MD file in its current state is impractical for non-humans.

**Proposal**: this step is impossible to solve automatically so let the one who maintains the MD file (human) put that information in a machine-parsable/readable format. See below.

> Satisfying other constraints about servers/relays relationships that people may expect. Such as these being in different countries, or in different country sets.

Solvable with the right metadata and configuration format.
**Proposal**: See below.

>But of course, one may still want to minimize latency, so how do you weights these constraints? Can we make an exhaustive list of these constraints? What would the actual cost function look like?
>On latency minimization, how to pick the optimal server/relay tuples? The latency between a client and a relay can be measured (albeit not reliably without a protocol extension). The latency between a relay and a server can't without a substantial amount of samples. The average latency for the end server to resolve a name is a different metric and also requires a substantial amount of samples. That's a multi-armed bandit problem. An exhaustive search would not be a reasonable way to solve this.

I agree.

**Proposal**: Sidestep the problem; use the planned relay randomization and failover features.

1. For every `resolver`, pick a random `relay` to use.
2. Measure and rank latencies like what `dnscrypt-proxy` currently does, with "TIMEOUT" meaning infinite latency.
3. For the n highest latency `resolver` and `relay` combinations, pick another `relay` randomly then remeasure and rerank.

Measurements could be done on-the-go with real client queries and rankings could change over time. These measured latencies and rankings could be saved and reloaded for later use.
One might imagine a scoring system for `resolver` and `relay` combinations, but I think that might be too complicated for an initial implementation?

BTW, this is too complicated for me to implement in Go with my non-existent Go programming knowledge.

---

Source MD File Proposal:
Example taken from the current `public-resolvers.md`
```
## skyfighter-dns

Country: Netherlands
Region: Western Europe
Entity: Scaleway.com, tuttimann
Some-other-thing: Foo

Uncensored, DNSSEC, no logging DNSCrypt server in Netherlands by Scaleway.com
Maintained by tuttimann

sdns://<a bunch of things>
```
Where the metadata block is parsed similarly to HTTP headers.
This is even backward compaible, as the metadata block will be seen as part of "description" and ignored.

Configuration TOML Proposal:
```
must_be_same: [ 'Region', 'Some-other-thing' ]
must_not_be_same: [ 'Country', 'Entity' ]
ignore_if_incomplete_metadata: true
```

The program could then avoid pairing this resolver with relays in the same country (`Netherlands`) and with the same entity (`Scaleway.com` or `tuttimann`), but pair it with relays in the same region (`Western Europe`) and "some-other-thing" (`Foo`).

> If you want to tackle these problems, go ahead. This is fun research. And the programming language is irrelevant.

I will probably implement this proposal in a future revision of the `dnscrypt-proxy-anongen.js` in my original post, in which I implemented "keyword" as described, which is far cruder than this metadata proposal.

It will probably have to stay an external configuration file generator, not something integrated into `dnscrypt-proxy`, as I could not program in Go.

---

Should I keep this issue closed?

**Comment by tartpvule** [comment]
I have created a configuration file generator.
It implements the idea I proposed.
If anyone is interested, please have a look:
https://github.com/tartpvule/anondnscrypt-confgen
