### ISSUE TITLE
Suggestion: organize files in folders

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1469]
Now that there are already 7 example files maybe it would be cleaner to put them in 1 'examples' folder?

**Comment by jedisct1** [comment]
Why not.

But the fact that examples will have to be copied into a different directory in order to be used may be confusing.

**Comment by ghost** [comment]
I assume the toml-file needs to stay where the executable is. The txt-files could be moved because one needs to specify their name or relative or absolute path in the toml anyhow to use them.

**Comment by jedisct1** [comment]
Subfolders can be useful to group things by category, but here, each file is in its own category.

So I'm not sure that there is any benefits here, besides being a breaking change.
