### ISSUE TITLE
How to choose my preferred server for DNSCrypt

### ISSUE THREAD

**Issue by ashikurtipu** [DNSCrypt/dnscrypt-proxy#147]
Using Dnscrypt 2.0.0 with Pi Hole on my orange pi zero. Whenever the service starts it shows randomize server instead of my chosen server. I edited the .toml file with my chosen server. It's not working.
i have choosen 3 servers from canada. which line should i edit on dnscrypt-proxy.toml ?, How to fix this ? ::: Sorry for my bad english ::: 

``

**Comment by ghost** [comment]
> I edited the .toml file with my chosen server. It's not working.

If you've edited the following line with your servers and removed the hashtag then I don't understand.

`# server_names = ['scaleway-fr', 'google', 'yandex']`

**Comment by ibksturm** [comment]
i choose cisco

`server_names =['cisco']`

(without hashtag), cause i hade since year a userlogin and since i've got children, i blocked some non child like webpages there

don't whorry at the day my kids realise how to use Tor Browser and keep their data under the table, i will deactivate it ^^

**Comment by evilvibes** [comment]
Added it

https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation#setting-up-dnscrypt-proxy

**Comment by jedisct1** [comment]
Cool! Don't forget to add your name to the main page :)
