### ISSUE TITLE
[Suggestion, if feasible] Public servers anonymization availability included in their description

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1470]
Hi,

Sorry for the long title. I emphasize on the feasibility of the suggestion given that my guess is that if it were possible it would be done.
I'm referring to the excellent [DNSCrypt - List of public DoH and DNSCrypt servers](https://dnscrypt.info/public-servers/) page which includes for all servers,

- Protocol
- DNSSEC
- No filters
- No logs

Having _Anonymization_ in the lot (for servers using the DNSCrypt protocol given it's the only one to support anonymization) would be quite helpful IMO, especially for users who prefer the `server_names =` approach to the _all servers with filters approach_ as myself, when I discover only lately a `[WARNING] [_server_] is incompatible with anonymization`

This of course doesn't concern directly the DNSCrypt-proxy application (which runs perfectly well), but I have no idea where other than here where to suggest this.

Thanks!

**Comment by jedisct1** [comment]
Hi!

My hope was that all servers would eventually be compatible, but servers like Cleanbrowsing and the Cryptostorm servers are still running old versions of the server software.

Instead of introducing a new property for this, maybe mentioning the incompatibility in the servers descriptions would indeed be useful.

The resolvers list has its own repository: https://github.com/dnscrypt/dnscrypt-resolvers

**Comment by ghost** [comment]
I guess that keeping a positive state of mind includes/requires taking into consideration all explanations, which means that I've certainly concluded my thoughts too quickly when I presumed that resolvers handling the dnscrypt protocol but not its anonymization feature was explained by their wish to know who was addressing them. 

`The resolvers list has its own repository`
Thanks, added to my bookmarks.

I always feel it strange to close a door of a flat which isn't mine but I'll close this post given it's acknowledged and issue-free. Thanks @jedisct1
