### ISSUE TITLE
Allow overriding subnet data on EDNS for privacy and accuracy

### ISSUE THREAD

**Issue by zero77** [DNSCrypt/dnscrypt-proxy#1471]
# Is your feature request related to a problem?

EDNS can be used to leek your location: as described in the bottom part of this post.

https://medium.com/tenable-techblog/turning-signal-app-into-a-coarse-tracking-device-643eb4298447

## Describe the solution you'd like

As described in this issue:
https://github.com/AdguardTeam/AdGuardHome/issues/1974

Basicallya text-field could be added in the configuration menu such that alternative public IPs could be given for generating EDNS sub-net data.
This would enhance privacy as you could pick random public IPs from your ISP (Or even another ISP) in different ranges, that still Geo-Locate to the same area as your real public IP, to be used for EDNS sub-net data sent to upstreams.

This is already implemented at NextDNS:
https://medium.com/nextdns/how-we-made-dns-both-fast-and-private-with-ecs-4970d70401e5

**Comment by jedisct1** [comment]
Added. But this can only *reduce* privacy.

**Comment by zero77** [comment]
@jedisct1 Thank you


> But this can only reduce privacy.

What makes you say this.

**Comment by jedisct1** [comment]
You're providing additional information to resolvers and authoritative servers. This makes fingerprinting easier and defeats the purpose of DNS anonymization. Privacy is increased by sending less device-specific information, not more.

And without anonymization, resolvers still get your real IP address no matter what. The ECS information now allows them to fingerprint your individual devices.

Sending fake ECS information can also decrease performance but also provide a false sense of privacy improvement, as some resolvers (e.g. OpenDNS) ignore this information and will send over your real network address to upstream servers no matter what.
