### ISSUE TITLE
dns TYPE65

### ISSUE THREAD

**Issue by bcookatpcsd** [DNSCrypt/dnscrypt-proxy#1473]
looks like ios (beta 14 currently) has a new dns type.. 

I can't find much on it.. 

I used another dns server to isolate it, but it doesn't show up in dnscrypt as anything..

[INFO] 192.168.10.102:54277 - 8789 "TYPE65 IN www.googleadservices.com. udp 53 false 4096" NOERROR qr,ra 143 0.018247606s
[INFO] 192.168.10.200:63908 - 27810 "TYPE65 IN feelinsonice-mvm.l.google.com. udp 58 false 4096" NOERROR qr,aa,rd,ra 129 0.000080823s
[INFO] 192.168.10.100:54671 - 16707 "TYPE65 IN mesu.g.aaplimg.com. udp 47 false 4096" NOERROR qr,rd,ra 139 0.089358939s
9:49
[INFO] 192.168.10.100:54946 - 28360 "TYPE65 IN downloaddispatch.itunes.apple.com. udp 62 false 4096" REFUSED qr,rd 51 0.000063936s

https://tools.ietf.org/html/draft-ietf-dnsop-svcb-https-01

2.  The SVCB record type
   The SVCB DNS resource record (RR) type (RR type 64) is used to locate
   alternative endpoints for a service.
Other SVCB-compatible resource record types can also be defined as-
   needed.  In particular, the HTTPS RR (RR type 65) provides special
   handling for the case of "https" origins as described in Section 7.

the 10.100, 10.102, and 10.200 are all running ios beta 14.. 

https://www.techradar.com/news/apple-devices-will-get-encrypted-dns-in-ios-14-and-macos-11

**Comment by jedisct1** [comment]
I guess this will automatically show up once https://github.com/miekg/dns/pull/1067 is implemented.
