### ISSUE TITLE
How to add several blacklists.

### ISSUE THREAD

**Issue by yutayu** [DNSCrypt/dnscrypt-proxy#1474]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [x] I'd like to announce a new application/website/article related to the project
* [x ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description
Thank you for your Great job.
and I cannot add several lists.

**Comment by yutayu** [comment]
Path to the file of blocking rules (absolute, or relative to the same directory as the executable file)
blacklist_file = 'blacklist.txt'

This is only one list.

or I should merge lists to one list?

**Comment by jedisct1** [comment]
See the [Combining blocklists](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Combining-Blocklists) page in the documentation

**Comment by yutayu** [comment]
excuse me and thanks.
