### ISSUE TITLE
IPv6 DNS rebind protection additions

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1478]
Hi!
I saw the rebind protection stuff in the wiki and wanted to suggest the addition of IPv6 rules, see below.
EDIT: [fc*] and [fd*] are invalid. Do I need to write them all out from fc00::* to fdff::*?

```
# Localhost rebind protection
0.0.0.0
127.0.0.*
::
::1

# RFC1918 rebind protection
10.*
172.16.*
172.17.*
172.18.*
172.19.*
172.20.*
172.21.*
172.22.*
172.23.*
172.24.*
172.25.*
172.26.*
172.27.*
172.28.*
172.29.*
172.30.*
172.31.*
192.168.*

# Link-Local rebind protection
169.254.*
fe80::*

# Unique-Local rebind protection
[fc*]
[fd*]
```

**Comment by jedisct1** [comment]
Take a look at the [example file](https://raw.githubusercontent.com/DNSCrypt/dnscrypt-proxy/master/dnscrypt-proxy/example-blocked-ips.txt).
