### ISSUE TITLE
Blocklist/allowlist: Allowing a domain, but blocking a subdomain

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1479]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description

Hello,
I tried to search, but I didn't find an answer how to do this.

A third-party blocklist has a domain, say _mydomain.com_ that has been added to my blocked domains, `domains-blocklist.txt` after running the Python utility script. However, I would like to allow this, so I added _mydomain.com_ to my `domains-allowlist.txt` file. But this domain has a subdomain, say _evil.mydomain.com_, which I want to be blocked.

I added _evil.mydomain.com_ to my `domains-blocklist-local-additions.txt` and run the Python script to generate my the `domains-blocklist.txt` file again. A line _evil.mydomain.com_ is not added to the blocklist file, because I have _mydomain.com_ is in my allowlist. I changed `domains-allowlist.txt` to have `=mydomain.com` (exact match), but then it is not recognized by the utility script - _mydomain.com_ appears in `domains-blocklist.txt`. I restarted the service and _mydomain.com_  is not resolved.

How could I solve a problem like this?

**Comment by jedisct1** [comment]
Add `=mydomain.com` to the proxy allowlist, not to the list processed by the Python script.

**Comment by emsd1981** [comment]
در پنجشنبه 17 سپتامبر 2020 در 23:40 Jussi <notifications@github.com> نوشت:

**Comment by ghost** [comment]
Ok, this was a bit stupid question. But now I understand. Thanks!
