### ISSUE TITLE
Use my own dnscrypt

### ISSUE THREAD

**Issue by nya1998** [DNSCrypt/dnscrypt-proxy#148]
Hello,
How to use my own dnscrypt server?

**Comment by jedisct1** [comment]
See https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes and other items in the same section.

**Comment by nya1998** [comment]
already set up, and how to connect it?
* in v 2.0
