### ISSUE TITLE
Wi-Fi Internet Connection Status is No Internet Connection When Using Dnscrypt

### ISSUE THREAD

**Issue by ChainofChaos** [DNSCrypt/dnscrypt-proxy#1481]
## *Who* is the bug affecting?
Wi-Fi internet connection status shows no internet connection.

## *What* is affected by this bug?
Wi-Fi internet connection status
![image](https://user-images.githubusercontent.com/17515882/93813417-48295000-fc7d-11ea-8b31-ff64bba51c78.png)

## *When* does this occur?
When using Dnscrypt

## *Where* does it happen?
I started got this issue when I updated to Windows 10 version 2004.

## *How* do we replicate the issue?

1. Follow the install guide steps from Installation Windows

## Expected behavior (i.e. solution)
Internet connection status shows no internet connection in your pc. But your internet connection in your pc is actually working fine.

## Other Comments
My PC Wi-Fi internet connection status is not detected or no internet connection. But the internet in this pc is working fine in fact, I'm using the current Wi-Fi, and it works fine. I can download anything, playing games, browsing the internet, etc. meanwhile, It says no internet connection. The problem is that I cannot access any apps from Microsoft store because it always says no internet connection.
![image](https://user-images.githubusercontent.com/17515882/93811686-bae4fc00-fc7a-11ea-99e6-78d5eb3e06cb.png)

**Comment by jedisct1** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-Windows#troubleshooting
