### ISSUE TITLE
tls handshake failure

### ISSUE THREAD

**Issue by poentodewo** [DNSCrypt/dnscrypt-proxy#1482]
> Sep 22 06:06:59 raspberrypi dnscrypt-proxy[18038]: [2020-09-22 06:06:59] [NOTICE] [cf-gateway] OK (DoH) - rtt: 44ms
Sep 22 06:06:59 raspberrypi dnscrypt-proxy[18038]: [2020-09-22 06:06:59] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 44ms)
Sep 22 06:06:59 raspberrypi dnscrypt-proxy[18038]: [2020-09-22 06:06:59] [NOTICE] dnscrypt-proxy is ready - live servers: 1
Sep 22 10:06:59 raspberrypi dnscrypt-proxy[18038]: [2020-09-22 10:06:59] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 123ms)
Sep 22 14:06:59 raspberrypi dnscrypt-proxy[18038]: [2020-09-22 14:06:59] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 81ms)
Sep 22 18:06:59 raspberrypi dnscrypt-proxy[18038]: [2020-09-22 18:06:59] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 42ms)
Sep 22 21:27:03 raspberrypi dnscrypt-proxy[18038]: [2020-09-22 21:27:03] [WARNING] TLS handshake failure - Try changing or deleting the tls_cipher_suite value in the configuration file
Sep 22 22:06:59 raspberrypi dnscrypt-proxy[18038]: [2020-09-22 22:06:59] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 42ms)
Sep 23 02:06:59 raspberrypi dnscrypt-proxy[18038]: [2020-09-23 02:06:59] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 33ms)

why tls handshake still failure ? im using tls handsake 4865 in the config

**Comment by jedisct1** [comment]
Did you try changing or removing the custom `tls_cipher_suite` as displayed?

**Comment by poentodewo** [comment]
@jedisct1 il try using 4867 = TLS_CHACHA20_POLY1305_SHA256 only and let see showing warning or no. if i keep the config default # commented did dnscrypt proxy using tls 1.3 ?

**Comment by jedisct1** [comment]
Yes, it will always use TLS 1.3 if the server supports it.

**Comment by poentodewo** [comment]
> Sep 23 17:56:49 raspberrypi dnscrypt-proxy[14268]: [2020-09-23 17:56:49] [NOTICE] [cf-gateway] OK (DoH) - rtt: 109ms
Sep 23 17:56:49 raspberrypi dnscrypt-proxy[14268]: [2020-09-23 17:56:49] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 109ms)
Sep 23 17:56:49 raspberrypi dnscrypt-proxy[14268]: [2020-09-23 17:56:49] [NOTICE] dnscrypt-proxy is ready - live servers: 1
Sep 23 21:36:49 raspberrypi dnscrypt-proxy[14268]: [2020-09-23 21:36:49] [WARNING] TLS handshake failure - Try changing or deleting the tls_cipher_suite value in the configuration file
Sep 23 21:56:49 raspberrypi dnscrypt-proxy[14268]: [2020-09-23 21:56:49] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 41ms)

Getting tls handshake failure too with 4867 = TLS_CHACHA20_POLY1305_SHA256
I will switch to default config

**Comment by jedisct1** [comment]
What is `cf-gateway`? Is it your own server?

**Comment by poentodewo** [comment]
no im just test using cloudflare gateway as endpoint in dnscrypt proxy 

after some hours look like no issue using default config

> Sep 23 22:47:54 raspberrypi dnscrypt-proxy[30674]: [2020-09-23 22:47:54] [NOTICE] [cf-gateway] OK (DoH) - rtt: 38ms
Sep 23 22:47:54 raspberrypi dnscrypt-proxy[30674]: [2020-09-23 22:47:54] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 38ms)
Sep 23 22:47:54 raspberrypi dnscrypt-proxy[30674]: [2020-09-23 22:47:54] [NOTICE] dnscrypt-proxy is ready - live servers: 1
Sep 24 02:47:54 raspberrypi dnscrypt-proxy[30674]: [2020-09-24 02:47:54] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 34ms)
Sep 24 06:47:54 raspberrypi dnscrypt-proxy[30674]: [2020-09-24 06:47:54] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 39ms)
Sep 24 10:47:54 raspberrypi dnscrypt-proxy[30674]: [2020-09-24 10:47:54] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 45ms)
Sep 24 14:47:54 raspberrypi dnscrypt-proxy[30674]: [2020-09-24 14:47:54] [NOTICE] Server with the lowest initial latency: cf-gateway (rtt: 42ms)

but my confuse is if not set cipher in the config(default) dnscrypt keep connect using tls 1.3 or fallback to 1.2 according this https://golang.org/pkg/crypto/tls/

**Comment by jedisct1** [comment]
Glad to hear that the printed error message is useful!

I don't think the cipher list has any impact on using TLS 1.3 (or not) as long as that list includes TLS 1.3 compatible ciphers.
