### ISSUE TITLE
Got DNS hijack by ISP, How ?

### ISSUE THREAD

**Issue by lessload** [DNSCrypt/dnscrypt-proxy#1483]
## Description

> [2020-09-20 05:12:33]	::1	ocsp.digicert.com	AAAA	PASS	0ms	-
> [2020-09-20 05:12:33]	::1	ocsp.digicert.com	AAAA	PASS	0ms	-
> [2020-09-20 05:12:33]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:33]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:33]	::1	o.ss2.us	AAAA	PASS	34ms	cloudflare
> [2020-09-20 05:12:33]	::1	crl4.digicert.com	AAAA	PASS	0ms	-
> [2020-09-20 05:12:33]	::1	crl4.digicert.com	AAAA	PASS	0ms	-
> [2020-09-20 05:12:33]	::1	o.ss2.us	AAAA	PASS	44ms	cloudflare
> [2020-09-20 05:12:33]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:33]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:33]	::1	o.ss2.us	AAAA	PASS	43ms	cloudflare
> [2020-09-20 05:12:33]	::1	o.ss2.us	AAAA	PASS	42ms	cloudflare
> [2020-09-20 05:12:34]	::1	s.symcd.com	AAAA	PASS	0ms	-
> [2020-09-20 05:12:34]	::1	s.symcd.com	AAAA	PASS	0ms	-
> [2020-09-20 05:12:34]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:34]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:34]	::1	s.symcb.com	AAAA	PASS	34ms	cloudflare
> [2020-09-20 05:12:34]	::1	s.symcb.com	AAAA	PASS	36ms	cloudflare
> [2020-09-20 05:12:34]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:34]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:34]	::1	s.symcb.com	AAAA	PASS	33ms	cloudflare
> [2020-09-20 05:12:34]	::1	s.symcb.com	AAAA	PASS	35ms	cloudflare
> [2020-09-20 05:12:34]	::1	rb.symcd.com	AAAA	PASS	0ms	-
> [2020-09-20 05:12:34]	::1	rb.symcd.com	AAAA	PASS	0ms	-
> [2020-09-20 05:12:35]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-
> [2020-09-20 05:12:35]	::1	xxx.hijack.xxx	AAAA	REJECT	0ms	-

This is log sample while i use dnscrpyt-proxy on windows.
`xxx.hijack.xxx` is ISP redirect url (fake url for privacy reason)
My question is " How ISP hijack dns, while i using dnscrypt-proxy ? "

**Comment by jedisct1** [comment]
It is probably not a hijack. Your web browser (probably) tried to access it.

Either because you went to their website, or because the browser tried to preload it, as most modern browsers do for frequently/recently accessed websites.

`dnscrypt-proxy` blocked it, this is what matter 😃
