### ISSUE TITLE
Upgrade ideas

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#1484]
openwrt x64, gl-inet.com mv1000w

The proxy HTTPT, which resists active detection, has source code on github.com. I hope that this code can be used to open a secure tunnel. If possible, udp, http, tcp, https, tls are all through HTTPT, then all queries will be more secure, and at the same time All regular servers can be used.
Also upgrade the available source code
Original title: Investigating the recently deployed protocol filters in Iran
In early 2020, Iran deployed a protocol filter, allowing only DNS, HTTP and HTTPS protocols, and censoring any connections that use other protocols. Kevin Bock and others from the University of Maryland conducted an investigation (PDF) on this and tested their recently open source genetic algorithm Geneva against protocol filters. Researchers found that Iran’s review of the prohibited protocol is to discard all data packets from the client. The data packets from the server are not affected, and the client still receives the data packets from the server. But because the client could not confirm or respond, the connection was actually censored. It differs from the Great Firewall in one-way inspection rather than two-way inspection. In addition, the protocol filter only inspects TCP traffic, which is limited to ports 53, 80 and 443. The traffic sent by other ports is not filtered. Researchers say Geneva discovered three ways to defeat protocol filters within two hours. Geneva's code is hosted on GitHub, and currently only supports Linux systems, not OS X or Windows.
If not true ,I am sorry, thank you!

**Comment by jedisct1** [comment]
Thank you!

Servers can use any port. Also, most of the DNSCrypt traffic uses UDP, not TCP.

**Comment by jkle112** [comment]
In China:
The firewall was discovered and started to block ESNI (Encrypted Server Name Indication). TLS1.3 introduces ESNI (not yet an official specification), which uses encrypted SNI to prevent intermediaries from viewing specific websites that clients want to visit. Because they do not know the websites that users visit using ESNI, the censors either do not block any ESNI connections or block all ESNI connections. The firewall chose the latter. The test found that the firewall prevents ESNI connections by dropping data packets from the client to the server. In addition, ESNI blocking will not only occur on port 443, but also on all ports from 1 to 65535. After blocking the ESNI handshake, the firewall will continue to block any connections related to the (source IP, destination IP, destination port) 3-tuple for a period of time.
Hope Dnscrypt-proxy upgrade to deal with the firewall to block more.
If not true ,I am sorry, thank you!
