### ISSUE TITLE
iOS14+/macOS11+ is available for built-in encrypted DNS. 

### ISSUE THREAD

**Issue by d6rkaiz** [DNSCrypt/dnscrypt-proxy#1485]
## Subject

* [x] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description

iOS 14, iPad14 and macOS 11 is available for built-in encrypted DNS. Is this would be possible to use with DNSCrypt ?

see also:
https://developer.apple.com/documentation/devicemanagement/dnssettings
https://developer.apple.com/documentation/devicemanagement/dnssettings/dnssettings

**Comment by jedisct1** [comment]
Unfortunately not, see https://github.com/s-s/dnscloak/issues/32
