### ISSUE TITLE
May be a coding flaw?

### ISSUE THREAD

**Issue by lifenjoiner** [DNSCrypt/dnscrypt-proxy#1490]
When adjusting my balancing strategy, I came to:
https://github.com/DNSCrypt/dnscrypt-proxy/blob/65f42918a1f85652ea4a378e20300d04b15ef2a8/dnscrypt-proxy/serversInfo.go#L210-L212
I think:
`candidateRtt >= currentBestRtt*4.0` --> `candidateRtt/2.0 >= currentBestRtt*2.0`
-->
`MinF(MaxF(candidateRtt/2.0, currentBestRtt*2.0), candidateRtt)`
= MinF(candidateRtt/2.0, candidateRtt)
= candidateRtt/2.0

**Comment by ghost** [comment]
@lifenjoiner Out of curiosity, why was this closed?

**Comment by lifenjoiner** [comment]
It's not  really a bug/issue. It's a reminder, and should have been noticed.
