### ISSUE TITLE
Firefox - Connection Settings - DNS over HTTPS - Custom provider?

### ISSUE THREAD

**Issue by Utini2000** [DNSCrypt/dnscrypt-proxy#1497]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ x ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description
I just noticed that the default setting in firefox is now to use cloudflare for DNS over HTTPS.
I wonder if I should change this to "custom provider" with IP "127.0.0.1" so that it uses whatever is currently configured by DNSCrypt?

Also, how can I verify that DNS over HTTPS works correctly with DNSCrypt?

Thanks!

**Comment by ianbashford** [comment]
If you do configure firefox to use a local dnscrypt-proxy, then there's an article on checking here https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Checking

**Comment by Utini2000** [comment]
Ahh ye that makes sense. Basically if I disable dnscrypt and nothing is able to resolve anymore, then this means that everything is routed via dnscrypt and there for DNS over HTTPS will also work (if configured in dnscrypt).

Additionally:
Is there any easy/quick way to get wifi-login pages (e.g. in hotels/airports/...) to work? 
Simply disabling dnscrypt on Arch (systemctl disable dnscrypt.service) will not work because then nothing gets routed outside?

**Comment by Utini2000** [comment]
Ah found a quick solution and script as workaround:

`
#!/bin/bash

    set -e

    if [ "$EUID" -ne 0 ]; then
      echo "Please run as root"
      exit 1
    fi

    if [[ "$1" = "stop" ]]; then
      echo "Stopping dnscrypt-proxy"
      chattr -i /etc/resolv.conf
      systemctl stop dnscrypt-proxy
      resolvconf -u
      echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1\nnameserver 8.8.8.8" > /etc/resolv.conf
      chattr +i /etc/resolv.conf
      exit
    fi

    if [[ "$1" = "start" ]]; then
      echo "Starting dnscrypt-proxy"
      chattr -i /etc/resolv.conf
      resolvconf -u
      echo -e "nameserver 127.0.0.1\noptions edns0 single-request-reopen" > /etc/resolv.conf
      systemctl start dnscrypt-proxy
      chattr +i /etc/resolv.conf
      exit
    fi

    echo 'Please provide command "start" or "stop"'
    exit 1 
`
