### ISSUE TITLE
Does Dnscrypt-proxy support edns client subnet?

### ISSUE THREAD

**Issue by BugKun** [DNSCrypt/dnscrypt-proxy#1498]
I had updated dnscrypt-proxy to `2.0.44`. And I add a config for edns client subnet as same as the [example](https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L125).
But It dosen't work. Dnscrypt-proxy printed `[FATAL] Unsupported key in configuration file: [edns_client_subnet]`.

**Comment by jedisct1** [comment]
This is not supported yet. Probably in the next release.
