### ISSUE TITLE
public-resolvers.md isn't updated

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#150]
dnscrypt-proxy 2.0 / Firefox 58.0.2 (x64) / Win7 (x64)

Hi,
It seems my public-resolvers.md file isn't updated. Related config is that of default:
```
[sources]
[sources.'public-resolvers']
url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
cache_file = 'public-resolvers.md'
format = 'v2'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
```
The file itself has it's date updated, but not its content. It still states updated on 2018-02-11, my Windows file manager shows _public-resolvers.md_ and _public-resolvers.minisign_ as dated 2018-02-18 21:15 but public-resolvers.md's content hasn't been updated (when an 2018-02-18 update is available).

Not a problem, only that I'm puzzled. Thanks.

**Comment by jedisct1** [comment]
Because having the date in the description in these files was a stupid idea since I always forget to update it :)

**Comment by ghost** [comment]
Frank,
My public-resolvers.md file hasn't been updated, whatever the dates. On the server there is a new public-resolvers.md file and it hasn't been auto-downloaded. It has two new resolvers, cleanbrowsing-family and cleanbrowsing-adult. All I see is that if I don't get them downloaded myself by removing public-resolvers.md and public-resolvers.minisign then uninstalling + installing dnscrypt-proxy, public-resolvers.md will never get updated ...

**Comment by jedisct1** [comment]
Or maybe the update mechanism never worked :)

**Comment by ghost** [comment]
I was wondering if,

```
fallback_resolver = '9.9.9.9:53'
ignore_system_dns = false
```

could have anything to do with the update mechanism...

**Comment by jedisct1** [comment]
No, I think it just never worked :(

**Comment by ghost** [comment]
OK. Perfection is not of this world :=) No big deal on the short-medium term, but worth being aware of on the long term, perhaps, especially if servers have been chosen by the user and that they happen to disappear later on, which is why it is advised to always run more than one server .... I run two here, `server_names = ['de.dnsmaschine.net', 'scaleway-fr']` so a possible issue is unlikely given neither is fantasy...
Thanks
