### ISSUE TITLE
inkompatible with anonymization

### ISSUE THREAD

**Issue by timi35** [DNSCrypt/dnscrypt-proxy#1501]
Hi,

since today I don't find any combination of anoymized-dns.
All servers told me that they are incompatible? I tried it with a lot of servers, but I couldn't find a working combination.
Is the anonymization not longer available?

Thanks!
Tim

**Comment by ianbashford** [comment]
I just whipped up a quick anonymised pair -- I get this in the logs
``` 
[2020-11-02 15:55:52] [NOTICE] Source [public-resolvers] loaded
[2020-11-02 15:55:52] [NOTICE] Anonymized DNS: routing [dnscrypt.uk-ipv4] via [v.dnscrypt.uk-ipv4]
[2020-11-02 15:55:52] [NOTICE] Firefox workaround initialized
```

So it seems I can make a valid anonymised route.  I can't think of much that's happened this weekend but the US clocks changed, and sometimes that can make things unhappy.  If that looks OK on your server, can you post some config and log snippits so we can see if we can reproduce?

**Comment by jedisct1** [comment]
@timi35 check that your router is not blocking UDP fragments.

**Comment by timi35** [comment]
@ianbashford,

hhm, I thought I try your server, but I don't find v.dnscrypt.uk-ipv4. 
There is only anon-v.dnscrypt.uk-ipv4 in relays.md.
Your config doesn't work for me - v.dnscrypt.uk-ipv4 is not available.

@jedisct1 
thanks, for the tip, but a restart of the router solved already the problem.
The solution is sometimes so near.

**Comment by ianbashford** [comment]
@timi35   good to hear that "turn it off and back on again" continues to be the ultimate solution :-) 
Looks like I typo'd trying to do the test quickly during a break...  I'm glad it worked out though.

**Comment by jedisct1** [comment]
Glad to hear that everything's working fine now 👍
