### ISSUE TITLE
[Wiki] Installation Guides: listening on 127.0.0.1

### ISSUE THREAD

**Issue by privacy-advo** [DNSCrypt/dnscrypt-proxy#1506]
## Question:

* [x ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description
I would like to know why I would only rebind the DNS IPv4 to 127.0.0.1? What about the IPv6 DNS servers if I have a IPv6 functionality? Are these irrelevant? Am I missing something? 

Thank you in advance
pa

**Comment by jedisct1** [comment]
Can you clarify what you want to do?

**Comment by ChainofChaos** [comment]
@jedisct1 What he/she meant is why we need to only change IPv4 to 127.0.0.1? Why don't you change the IPv6?
@privacy-advo Changing the IPv4 is enough for you to use the DNSCrypt service. Unless if you are an advanced user, you can change both IPv6 and IPv4 or either one of them. It's just for the service to listen to these addresses.

**Comment by privacy-advo** [comment]
First, I'm sorry @jedisct1 for the unclear wording.
Thank you @ChainofChaos. That was what I wanted to say/ask. 

Changing the system's DNS to 127.0.0.1 is done because dnscrypt is listening. Is there a leakage if my system is configured IPv4-DNS server 127.0.0.1 and e.g. IPv6 2606:4700:4700::1111. Could queries reach the latter? Is there a hierarchy between IPv4 and IPv6 requests?
In my setup, I normally set both 127.0.0.1 and ::1 as system DNS server and config dnscrypt to listen_addresses = ['127.0.0.1:53', '[::1]:53'] without using a IPv6 resolver in dnscrypt and block_ipv6 = true. 

The reason why I came up with this is a problem with EA's Origin Client. I was not able to login/play while I configured system DNS to ::1 and dnscrypt listening ::1. But when I did _not_ config the system DNS to ::1, the client worked. Which made me wonder about a probable leakage.

**Comment by privacy-advo** [comment]
I want to repost the remaining questions:
a) Could there be a leakage to _2606:4700:4700::1111_ if my system is configured IPv4-DNS server _127.0.0.1_ and thus using DNSCrypt and the IPv6-DNS server is 2606:4700:4700::1111. Could queries reach the latter?
b) Is there a hierarchy between IPv4 and IPv6 requests?

**Comment by jedisct1** [comment]
`127.0.0.1` is only accessible from the host itself, not via the network.

Individual applications can do what they want if a name has both IPv4 and IPv6 addresses. The traditional behavior is to try IPv6 first

**Comment by privacy-advo** [comment]
Thank you @jedisct1 
To recap for me if I got it right:
An application requests _sample.com_. The request will _in most cases_ first be processed by the system's IPv6-DNS server and will not reach DNSCrypt only listening to 127.0.0.1. 
The take-away for me is, that I will set both system DNS servers to 127.0.0.1 and ::1.
