### ISSUE TITLE
Version 2.0.1 is available for download

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#151]
Mostly bug fixes.

**Comment by kmleow** [comment]
Good work on the rewrite.
Been using your 1.x versions.
With extracted binary size of 6.8MB, this is unlikely to fit into vast majority of OpenWRT on home router installations.

Is there any chance that you will introduce a Lite edition that has just DOH, and perhaps a separate Lite edition that is strictly just DNSCrypt, without all the other nice to have features i.e. cloaking, blacklist?

**Comment by jedisct1** [comment]
Removing features wouldn't help much, but you can use UPX to significantly reduce the file size: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

Add the `--lzma` flag for even better compression.

**Comment by kmleow** [comment]
Thanks. Reminds me of the good old days of shrinking DOS binaries. :)

May I know how much space do you have left after putting this into LEDE on Archer C7 (which I believe is what you use)?

**Comment by jedisct1** [comment]
```
/dev/mtdblock3           12.1M      4.2M      7.9M  35% /overlay
```

**Comment by kmleow** [comment]
Looking forward to trying your shiny new package once it arrives on LEDE snapshots :)
Still 1.9.5 as at now.
