### ISSUE TITLE
--service-name not working

### ISSUE THREAD

**Issue by kainjinez** [DNSCrypt/dnscrypt-proxy#1511]
## Subject

* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
## Description

As I see in Windows doc, I can register DnsCrypt-proxy as a service with specific name using `--service-name=<name>` but this argument in command line is not exist. How can I do it? Thanks.

**Comment by jedisct1** [comment]
Hi!

Not sure where you saw that, but there was never a `--service-name` command-line option, neither in the software nor in the documentation!

But a way to set the service name (to run multiple instances?) can be always be added.
