### ISSUE TITLE
Time for 2.0.45 ?

### ISSUE THREAD

**Issue by ianbashford** [DNSCrypt/dnscrypt-proxy#1516]
It's been a while since there's been a release.  There's been quite a few dependencies changed.

I pull my own copy from master every now and then to run -- in fact I'm about to do it again now which is what made me think of it... 

Maybe after .45 we can begin to make a plan for 2.1  for the new year.
Just a thought :-)

**Comment by jedisct1** [comment]
#1475 is a blocker, and captive portals need to be handled after startup.

The later shouldn't be too hard (probably just yet another plugin), but the former... I have absolutely no idea how to tackle this.

**Comment by ianbashford** [comment]
Oh yes,  I've read through #1475 that a couple of times and it hurt my head.
I'll re-read and try and give it some brain cycles...

**Comment by jedisct1** [comment]
It hurts my head as well.

The short version is: if `ipv4_servers` is set to `false`, the list of resolvers cannot be downloaded, because the hosts they are downloaded from don't have IPv6 addresses.
