### ISSUE TITLE
default toml location

### ISSUE THREAD

**Issue by bphd** [DNSCrypt/dnscrypt-proxy#1517]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [x ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description

Where the toml file is supposed to be per default?

Because on a fresh install

```
$ locate -i *dns*toml*
/etc/dnscrypt-proxy/dnscrypt-proxy.toml
$ sudo dnscrypt-proxy -loglevel 6
[2020-11-20 13:13:28] [FATAL] Unable to load the configuration file [dnscrypt-proxy.toml] -- Maybe use the -config command-line switch?
$ sudo dnscrypt-proxy -check
[2020-11-20 13:17:25] [FATAL] Unable to load the configuration file [dnscrypt-proxy.toml] -- Maybe use the -config command-line switch?
$ sudo dnscrypt-proxy -check -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
$ sudo dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
```

**Comment by jedisct1** [comment]
In the current directory, or in the same directory as the `dnscrypt-proxy` program.

**Comment by bphd** [comment]
Why the installation store the toml here

```
$ locate -i *dns*toml*
/etc/dnscrypt-proxy/dnscrypt-proxy.toml
```

And the program needs it here

```
$ which dnscrypt-proxy 
/usr/bin/dnscrypt-proxy
```

It wasn't used to be like that, it worked flawlessly oob before an update who break it

A workaround should be something like `# ln /etc/dnscrypt-proxy/dnscrypt-proxy.toml /usr/bin/` but it's a poor idea to place such files here or to modify configuration files but it needs systematic modification oob to work

A solution should be to revert to the old behaviour
