### ISSUE TITLE
可以提供个centos 6 64bit可用的二进制文件？

### ISSUE THREAD

**Issue by 1265578519** [DNSCrypt/dnscrypt-proxy#152]
他能支持缓存并且替换系统自带的dns管理？

**Comment by CNMan** [comment]
you can use dnscrypt-proxy-linux_i386-2.0.1.tar.gz for 32bit or dnscrypt-proxy-linux_x86_64-2.0.1.tar.gz for 64bit from https://github.com/jedisct1/dnscrypt-proxy/releases
