### ISSUE TITLE
IPV6 for download.dnscrypt.info

### ISSUE THREAD

**Issue by ianbashford** [DNSCrypt/dnscrypt-proxy#1520]
## Description

I've spun the ipv6 availability from #1475 into a new issue.
I've used netlify to run a simple proxy to https://download.dnscrypt.info - they give it ipv4 and ipv6 addresses by default.
I imaginatively named it https://download.dnscrypt.uk  

It would be simple for anyone else to clone from https://github.com/ianbashford/dnscrypt-download  

As it's not  hosting any files, we shouldn't have any significant sync issues.
They'll deliver around 100GB / month in the free plan -- given the size of the files I doubt we'll get near that, but if you have any information from hosting your site that contradicts that please LMK.

If you're happy with that approach, then I can issue a PR to the example-dnscrypt-proxy.toml file and add the additional resolver.

**Comment by ianbashford** [comment]
@jedisct1  I think we can close this as I see you've created a ipv6 name for dnscrypt.info
Do you see a use for multiple servers?   If not I'll shut this one down...

**Comment by syphyr** [comment]
The site (ipv6.download.dnscrypt.info) does not resolve for me.

**Comment by poentodewo** [comment]
> 
> 
> The site (ipv6.download.dnscrypt.info) does not resolve for me.

its resolve for me

`; <<>> DiG 9.10.3-P4-Raspbian <<>> AAAA ipv6.download.dnscrypt.info
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58885
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ipv6.download.dnscrypt.info.   IN      AAAA

;; ANSWER SECTION:
ipv6.download.dnscrypt.info. 86349 IN   AAAA    2001:41d0:c:46d::2

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 25 07:59:21 WIB 2020
;; MSG SIZE  rcvd: 84`

**Comment by syphyr** [comment]
dig gives me the following response:

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> ipv6.download.dnscrypt.info
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33868
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ipv6.download.dnscrypt.info.	IN	A

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Nov 25 02:11:28 CET 2020
;; MSG SIZE  rcvd: 56

But, when I enter the url (https://ipv6.download.dnscrypt.info/resolvers-list/v3/public-resolvers.md) in my browser, it says that it can not find the site.

**Comment by jedisct1** [comment]
Hi Ian,

And sorry for the delayed response.

Does your netlify setup directly proxy the content?

If we add mirrors, maybe it would be better to have them cache the content, so that we get some redundancy.

I did some experiments with CDNs. Cloudflare requires the entire domain to be delegated to them, which I'd rather avoid if we can have better options

With Fastly, I got a nice setup, that can keep serving the files even if the server is down for an extended period of time. And even with the free tier, useful things can be done such as having multiple origins. And it works for a single hostname.

However, I could either get full support for TLS but without IPv6, or IPv6 support but without TLS :) I probably overlooked something obvious, so I'll keep trying, or ask around.

**Comment by mibere** [comment]
Something interesting at [Best CDN providers of 2020 to speed up any website](https://www.techradar.com/news/the-best-cdns-of-2018)?

**Comment by jedisct1** [comment]
Nice list! But besides Cloudflare and Fastly, none of these seem to have a free tier.

**Comment by mibere** [comment]
Folks, can you please check if you can resolve the mirror [download.dnscrypt.net](https://download.dnscrypt.net/) via IPv4 and IPv6?

**Comment by syphyr** [comment]
I can resolve it now. I'm not sure what changed, but now it works..

**Comment by mibere** [comment]
@syphyr Please note, this is my server, not Frank's ;-)

**Comment by syphyr** [comment]
OK.  just a note that ipv4 and ipv6 both work on download.dnscrypt.net and ipv6.download.dnscrypt.net now.

**Comment by ianbashford** [comment]
@mibere  did you set yours up with content?  
I was thinking about a mechanism to make sure I stayed in sync i.e. a message from commits in the resolvers repo triggering a build.   Have you come up with a different mechanism?

**Comment by mibere** [comment]
I host the files locally on download.dnscrypt.net, there is no redirect to download.dnscrypt.info / ipv6.download.dnscrypt.info.
A cronjob updates the files every 3 hours, source is https://download.dnscrypt.info

(download.dnscrypt.net has IPv4 and IPv6, DNSSEC, HTTPS)

**Comment by jedisct1** [comment]
Sounds good!

Maybe we can even set a webhook to trigger an update every time there is a new commit to the `master` branch.

**Comment by ianbashford** [comment]
That was exactly what I had in mind....
