### ISSUE TITLE
Windows 10 ver > 1803 any server incompatible with anonymization - udp corrupted

### ISSUE THREAD

**Issue by frankiezapp** [DNSCrypt/dnscrypt-proxy#1521]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [x] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description
In Windows 10 version > 1803 UDP packets larger than MTU in size (larger than 1472 bytes of max payload), will be corrupted and dropped by the network stack. This ends up in any server being incompatible with anonymization .
It appears to be of some help disabling UDP Checksum Offload in the NIC properties. Not in my case.

https://social.technet.microsoft.com/Forums/en-US/965e107e-d9b0-4240-ac3f-74797c91b476/unable-to-send-udp-packets-larger-than-the-mtu-with-windows-build-1809-using-c-udpclient

**Comment by jedisct1** [comment]
Large packets seem to be flowing fine on version `20H2`.

Check that your router is not blocking fragments.

**Comment by frankiezapp** [comment]
Dns crypt it's working with anonymization without any issue on android with the same router.
The router is a Huawey personalized Vodafone version (Vodafone Station 2) working with fiber .There is nothing about udp fragmentation in the configuration you can change. I did the tricks ond the udp checksum offload in the nic and many others but nothing change. I 'll try the 20h2
