### ISSUE TITLE
How can I allow only certain IPs to use my server ?

### ISSUE THREAD

**Issue by mukberty** [DNSCrypt/dnscrypt-proxy#1522]
* [x] I want to run my own DNSCrypt and/or DoH server

How can I allow only certain IPs to use my server ? Allow access only to a select few.
Do I have to setup `iptables` and edit the rules everytime I add r remove an `IP`, or is their an in-built feature?

Thanks a ton!

**Comment by jedisct1** [comment]
Configure a set of keys allowed to access your server in the [`[access_control]`](https://github.com/jedisct1/encrypted-dns-server#access-control) section of the server configuration, and, on each authorized client, set a key in the `query_meta` property.
