### ISSUE TITLE
select a true working server

### ISSUE THREAD

**Issue by luweitest** [DNSCrypt/dnscrypt-proxy#1524]
## *Who* is the bug affecting?
user

## *What* is affected by this bug?
DNS resolving fail

## *When* does this occur?
always

## *Where* does it happen?
china

## *How* do we replicate the issue?

Normally start the service, dnscrypt-proxy begins to scan working servers, reporting "rtt" values of servers or time out; then it seems to select one with the least rtt value, which is, 100% a chinese server, and do not work at all.

## Expected behavior (i.e. solution)
It should check whether a server truly supports the protocol, by sending a customizable testing resolving request like www.google.com, and check if the response is OK.

## Other Comments
The chinese fake servers list (rtt value <100ms): 
alidns-doh
rubyfish-uw
rubyfish-ea
nextdns
geekdns-doh
cisco-familyshield

Those should be excluded out of all the public lists.

**Comment by jedisct1** [comment]
An actual query is sent. In version 2.0.44, this is a query for the root zone, in the development code, it is randomized.
