### ISSUE TITLE
Add "exclude" or "blacklist" feature to server list

### ISSUE THREAD

**Issue by luweitest** [DNSCrypt/dnscrypt-proxy#1525]
## Is your feature request related to a problem?

The public server list is signed and cannot be edited. The user can pick some of them by adding "server_names =" item in dnscrypt-proxy.toml, but cannot exclude some bad servers.

## Describe the solution you'd like

Add a "!" in front of the server name to disable it, e.g. server_names =['!alidns-doh']

## Alternatives you've considered

Add "disable sigcheck = true" to allow user edit the public-resolvers.md file.

## Who will that feature be useful to?

All users.

## What have you done already?

Nope

## What are you going to contribute?

I can help to test.

**Comment by jedisct1** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/blob/f9c11f0897fa415ba1a0727b89af4b0329e90955/dnscrypt-proxy/example-dnscrypt-proxy.toml#L80-L83

**Comment by luweitest** [comment]
That " disabled_server_names = [] " must be added in later versions. I download 2.0.44 only to find it not work in my old XP machine. :( 
Thanks anyway.

**Comment by jedisct1** [comment]
It was introduced in version 2.0.20.
