### ISSUE TITLE
Add Quad9 dns servers with EDNS to dnscrypt & doh servers list?

### ISSUE THREAD

**Issue by HellboyPI** [DNSCrypt/dnscrypt-proxy#1528]
Quad9 also offers secured service supporting [ECS](https://www.quad9.net/faq/#What_is_EDNS_Client-Subnet). 
Provides: Security blocklist, DNSSEC, EDNS Client-Subnet
This service should be added to public dnscrypt & doh servers list.

IPv4: 9.9.9.11, 149.112.112.11
IPv6: 2620:fe::11, 2620:fe::fe:11

DoH address: https://dns11.quad9.net/dns-query

DNSCrypt, IPv4:
2.dnscrypt-cert.quad9.net
9.9.9.11:8443

DNSCrypt, IPv6:
2.dnscrypt-cert.quad9.net
[2620:fe::11]:8443

**Comment by jedisct1** [comment]
As you saw in the configuration file, Quad9 maintains the list of their servers themselves: https://www.quad9.net/quad9-resolvers.md

If some entries are missing, you should ping them to add them!
