### ISSUE TITLE
Question/Feature Request: Prefer ipv6 over ipv4

### ISSUE THREAD

**Issue by iamperson347** [DNSCrypt/dnscrypt-proxy#153]
Question/Feature Request: Prefer ipv6 over ipv4

Hi @jedisct1,

I was curious if there was a way to make dnscrypt-proxy prefer ipv6 over ipv4 for a server source that listens on both. For example, it appears 'doh-crypto-sx' is listening on both (or at the very minimum, response to ping on ipv6). I'm assuming google probably supports both as well (since their primary dns service listens on both... could be a bad assumption though).

I tried changing ipv4_servers = false and ipv6_servers = true, but dnscrypt-proxy could not connect (at least to google).

What do you think? Is this already possible? Or maybe something for the future?

**Comment by jedisct1** [comment]
Hi!

When using DoH servers:

-  either their stamp includes an IP address (v4 or v6); this is where the client will always connect to
- or the stamp just includes a host name and no IP address -> the operating system rules are used to prefer IPv4 over IPv6 or the opposite, if both families are available.

The tradition with dnscrypt servers is to use dedicated names for IPv6 and IPv4 variants. Maybe the same tradition will be respected for DoH servers as well.

It would make sense to try using only IPv6 or IPv4 when resolving DoH server names according to what is in the configuration file, though. Not sure how difficult implementing this is, but that's something I'll try to take a look at (unless you want to).
