### ISSUE TITLE
I'd like implementation of BLAKE3...

### ISSUE THREAD

**Issue by zt3ph4n** [DNSCrypt/dnscrypt-proxy#1530]
## Is your feature request related to a problem?
not really. if you think speed, enhance etc as a problem, well then...

## Describe the solution you'd like
'full' implementation of Blake3 in dnscrypt-proxy.
the speeds of blake3 and security+ would really make a nice impact.
https://github.com/BLAKE3Team/
https://www.blake3.com/

## Alternatives you've considered
Duuh..

## Who will that feature be useful to?
Hashing. Performance. Memory. Time.

## What have you done already?
Im doing tryout's w/ blake3 and Ed-448 etc etc.

## What are you going to contribute?
Testing. Some bash-scripting maybe.

## Additional context
None else than the obvious.

**Comment by jedisct1** [comment]
Lol.
