### ISSUE TITLE
Autoupdate script is has mismatch path/layout for macos binary

### ISSUE THREAD

**Issue by bitomaxsp** [DNSCrypt/dnscrypt-proxy#1531]
## *Who* is the bug affecting?
Users who are trying to use autoupdate using cron on macos

## *What* is affected by this bug?
Autoupdate functionality

## *When* does this occur?
On every run of proposed script here: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Updates

## *Where* does it happen?
`download_url="$(curl -sL "$LATEST_URL" | grep dnscrypt-proxy-${PLATFORM}_${CPU_ARCH}- | grep browser_download_url | head -1 | cut -d \" -f 4)"`

macos archive has no CPU_ARCH 

## *How* do we replicate the issue?
Run autoupdate script mentioned on this page on macos https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Updates 

## Expected behavior (i.e. solution)
macos download link must not be empty and update update should pass

**Comment by jedisct1** [comment]
macOS binaries actually do have an arch now that an arm64 version is available. 

This script is just a documentation example. The "arch" part of the filename is set according to how the Go language defines it, which doesn't necessarily match what the "arch" command returns.

**Comment by bitomaxsp** [comment]
@jedisct1 
only one of two macos archives have arch, which is arm64. x86_64 doesn 't 
Also note that arm64 does not have zip extention
Could you please add arch to macos and fix the extension in the next release?

<img width="354" alt="image" src="https://user-images.githubusercontent.com/866806/100583522-1838a180-32eb-11eb-97f8-4d28ba445a73.png">

**Comment by jedisct1** [comment]
Good catch for the ZIP extension!

Including x86_64 in the x86_64 macOS package will break existing update scripts. But on macOS, the vast majority of people is probably using Homebrew, so it may be okay.
