### ISSUE TITLE
SOCKS Proxy Disobedience

### ISSUE THREAD

**Issue by treycetra** [DNSCrypt/dnscrypt-proxy#1532]
## *Who* is the bug affecting?
Users who have enabled SOCKS proxying (i.e. Tor users)

## *What* is affected by this bug?
Initial connections to DNSCrypt servers are made without the configured SOCKS proxy.

## *When* does this occur?
At start of DNSCrypt_proxy daemon (Linux, Debian)

## *How* do we replicate the issue?

Configure DNSCrypt_proxy SOCKS proxy for Tor (127.0.0.1:9050) and enable "force_tcp". Start packet capture. Start tor daemon. Start DNSCrypt_proxy daemon.

## Expected behavior (i.e. solution)
Expected all DNSCrypt traffic to pass through SOCKS proxy, including handshakes to any DNSCrypt server.

## Other Comments
Traffic works as expected after the initial connection. I made sure that the Tor client was active before DNSCrypt_proxy started up.

**Comment by jedisct1** [comment]
This is all public data, there is nothing confidential here.

Furthermore, I think this was fixed a long time ago. I can't start the proxy if SOCKS has been configured but the SOCKS server is intentionally down.

Make sure that you are not running an obsolete version. The current stable version is 2.0.44.
