### ISSUE TITLE
When and how does DNSCrypt change/check for faster resolvers?

### ISSUE THREAD

**Issue by Utini2000** [DNSCrypt/dnscrypt-proxy#1535]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ x ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description
I am running DNSCrypt on Arch Linux with the following settings:
`
keepalive = 30
# lb_strategy = 'p2'
# lb_estimator = true
`

I noticed that for 30 minutes I have been using the same DNSCrypt resolver. The problem with this is that the check for the fastest server was done right after connecting to a wifi network. Because of that, many servers initially timed out on the speed check and only a few were left which might only provide "okayish" speed.

So I wonder, when will DNSCrypt check again and switch to a faster resolver?

**Comment by jedisct1** [comment]
After each query.

**Comment by Utini2000** [comment]
And what exactly is a query? For example, why hasn't there been any query in the last 30 minutes?

**Comment by jedisct1** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Load-Balancing-Options#how-the-servers-are-sorted

Servers that completely timed out at the beginning may get a new chance when certificates are refreshed, after `cert_refresh_delay` (https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Load-Balancing-Options#how-the-list-of-servers-is-populated)

**Comment by Utini2000** [comment]
Oh okay. So I was probably using that one resolver because nothing else was faster.

Thanks for explaining!
