### ISSUE TITLE
anonymized_dns in combination with Require servers ...

### ISSUE THREAD

**Issue by theltalpha** [DNSCrypt/dnscrypt-proxy#1536]
Hallo!

I have a question which has been asked before in #1235, but that issue has been closed without answering the author's question. The question is: If in the dnscrypt-proxy.toml file you do not have defined specific servers at "server_names = ..." in the "List of servers to use" section, but you rather let dnscrypt-proxy chose a server based on the settings in the "Require servers ..." section, how can you make this work in combination with anonymized_dns? Is is possible currently? Please don't tell me to use * as has been told the author in the above mentioned issue. According to how I understand the comments in the toml file, * will refer to servers defined at server_names = ... in the "List of servers to use" section.

**Comment by Zastoff** [comment]
Setting from my toml (Called "Automatic" from the [DNSCrypt-proxy Installer on Asuswrt-Merlin](https://www.snbforums.com/threads/dnscrypt-proxy-installer-for-asuswrt-merlin-nov.67435/)) 
`# server_names = ['sth-dnscrypt-se', 'dnscrypt.eu-dk']` 
**(Note the # before server_names = line ignored)**
**It will use all servers from public-resolvers.md instead**
These settings filter this list:
`ipv4_servers = true`

`ipv6_servers = false`

`dnscrypt_servers = true`

`doh_servers = false`

`require_dnssec = true`

`require_nolog = false`

`require_nofilter = false`

`disabled_server_names = ['sth-dnscrypt-se', 'cs-swe']`

The disabled server_names i use depends on the relays chosen, I manually added(in the installer) the disabled, I use "anon-sth-se" & "anon-cs-se" relays, And do not want to use relay and server from the same provider

`lb_strategy = 'p2'`

`lb_estimator = true`

Relays:
`routes = [ { server_name='*', via=['anon-sth-se', 'anon-yofiji-se-ipv4', 'anon-cs-se'] } ]`
`skip_incompatible = true`
Part from syslog:
`dnscrypt-proxy[9676]: Anonymized DNS: routing everything via [anon-sth-se anon-yofiji-se-ipv4 anon-cs-se]`
`dnscrypt-proxy[9676]: Server with the lowest initial latency: adguard-dns-unfiltered (rtt: 19ms)`
`dnscrypt-proxy[9676]: dnscrypt-proxy is ready - live servers: 42`
And the Installer i use have a built in restart function for the proxy to randomize relays used.

**Comment by theltalpha** [comment]
Hi! Thank you very much for your detailed answer. So I understood that actually the * won't only pick a server from the "List of servers to use" section, but if there aren't any servers defined, it will take the server derived from the "Require servers ..." section. I think it would beneficial to note this in the dnscryp-proxy.toml file, for example after the sentence _"server_name" can also be set to "*" to define a default route, but this is not recommended. If you do so, keep "server_names" short and distinct from relays._ something like _If you do not have defined any servers at "server_names" in the "List of servers to use" section, then dnscrypt-proxy will chose the server derived from the "Require servers ..." section._

> And the Installer i use have a built in restart function for the proxy to randomize relays used.

That sounds very useful. I would like to see this as native feature in dnscrypt-proxy.

**Comment by jedisct1** [comment]
> That sounds very useful. I would like to see this as native feature in dnscrypt-proxy.

Relays are already randomized when the proxy starts.

**Comment by theltalpha** [comment]
> Relays are already randomized when the proxy starts.

Sorry, @jedisct1, for writing again in this already closed thread, but your statement does not make sense to me and I want to understand it. What do you mean by "relays are already randomized when the proxy starts"? I thought relays were statically defined via _routes = [ { server_name='*', via= ..._?! How can you randomise this? How do you specify how many relays should be used?

**Comment by Zastoff** [comment]
As i understand it
You can select many relays/server or with * 
But the proxy choose's **one** of the relays randomly when the proxy starts and it will use that relay until it(the proxy) is restarted.
That's why we added a sort of cron to restart the dnscrypt-proxy in the installer for Asuswrt-merlin to increase the randomisation of which relay is used(can be a long time between restarts on a router)
