### ISSUE TITLE
rule priority in filters

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1537]
What priorities are used in filter lists?

E.g. I tried to use both of these cloaking rules at once:

=example.com   1.1.1.1
*.example.com   2.2.2.2

I expected rules to be tried in order and example.com to resolve to 1.1.1.1 and e.g. www.example.com to 2.2.2.2 however they both fail. If I only use one of them it works fine.

**Comment by jedisct1** [comment]
Time-based rules have a higher priority than global rules.

Then, within each class, in version 2.0.44, priorities are:

- longest suffix
- longest prefix
- substrings
- regular expressions
- exact matches

**Comment by ghost** [comment]
Thanks. I'll try your commit [0d260d0](https://github.com/DNSCrypt/dnscrypt-proxy/commit/0d260d0e2d074bc9a0c3ab9ca454b9576abe419f) when the new version is out. However I'm still wondering why having both rules simultaneously fails completely instead of just giving the wrong IP.
