### ISSUE TITLE
Change the logo due to the new GitHub dark mode

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#1541]
GitHub just introduced a dark mode.

Unfortunately, logos with dark text have become barely readable in such a configuration, and this affects the `dnscrypt-proxy` logo :(

**Comment by jacob755** [comment]
im not expert but with paint.net 
![dns](https://user-images.githubusercontent.com/65178892/103438770-f490b000-4c36-11eb-8a17-e71a69eb59a1.png)

**Comment by jedisct1** [comment]
Amazing, thank you so much @jacob755 !
