### ISSUE TITLE
Oblivious DNS

### ISSUE THREAD

**Issue by InnovativeInventor** [DNSCrypt/dnscrypt-proxy#1542]
Following up on: https://github.com/DNSCrypt/dnscrypt-proxy/issues/656, Cloudflare implemented oblivious DNS and it looks to be gaining support: https://blog.cloudflare.com/oblivious-dns/. Is there an implementation of oblivious DNS in dnscrypt-proxy planned?

**Comment by jedisct1** [comment]
Here's one bit: https://github.com/jedisct1/go-hpke-compact

Do the rest :)
