### ISSUE TITLE
Is Cloaking rules work correctly ?

### ISSUE THREAD

**Issue by lessload** [DNSCrypt/dnscrypt-proxy#1545]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description

I set custom Cloaking rules for one domain with two ip.
```
custom-url.com   10.x.x.1
custom-url.com   10.x.x.2
```
but when i test by nslookup it show only 1 ip.
```
> nslookup custom-url.com
Server:  UnKnown
Address:  127.0.0.1

Non-authoritative answer:
Name:    custom-url.com
Address:  10.x.x.1
```
Is it normal ? i think it should show two ip like.
```
> nslookup cloudflare.com
Server:  UnKnown
Address:  127.0.0.1

Non-authoritative answer:
Name:    cloudflare.com
Addresses:  104.16.132.229
            104.16.133.229
```

**Comment by jedisct1** [comment]
Test more than once :)
