### ISSUE TITLE
Enable HTTP/2.0

### ISSUE THREAD

**Issue by SeanBurford** [DNSCrypt/dnscrypt-proxy#1546]
## Is your feature request related to a problem?

From code inspection it appears that dnscrypt-proxy is only using HTTP/1.1 and below for DoH connections.

In Go's http stack HTTP/2.0 is conservatively disabled if a custom dialer is provided.  Since you're using the same dialer that transport would use anyway, with a wrapper to cache IP addresses, it appears that reenabling HTTP/2.0 is low risk.

https://tools.ietf.org/html/rfc8484#section-5.2 also makes a good argument for using HTTP/2.0 for DoH:

```
   HTTP/2 [RFC7540] is the minimum RECOMMENDED version of HTTP for use
   with DoH.

   The messages in classic UDP-based DNS [RFC1035] are inherently
   unordered and have low overhead.  A competitive HTTP transport needs
   to support reordering, parallelism, priority, and header compression
   to achieve similar performance.  Those features were introduced to
   HTTP in HTTP/2 [RFC7540].  Earlier versions of HTTP are capable of
   conveying the semantic requirements of DoH but may result in very
   poor performance.
```

## Describe the solution you'd like

`dnscrypt-proxy/xtransport.go` creates an http.Transport with a DialContext.  HTTP/2.0 is conservatively disabled when DialContext is provided (https://github.com/golang/go/issues/14275).  To re-enable it you set `ForceAttemptHTTP2: true` in the http.Transport.

## Alternatives you've considered

The alternative is to do nothing out of concern that something may break.  This can be mitigated by testing your features with HTTP/2.0 enabled.

## Who will that feature be useful to?

Anyone who uses DoH and wants lower bandwidth usage or latency.

## What have you done already?

https://dnscrypt.info/public-servers lists 214 DoH address/port combinations.

`curl -I -k` is able to connect to 188 of these servers.  The output of curl indicates that 187 of them negotiated HTTP/2.0, with just https://doh.li:443 negotiating HTTP/1.1.  This should not be a problem, as golang http falls back to HTTP/1.1 if 2.0 is not available.  https://tools.keycdn.com/http2-test verifies that https://doh.li:443 does not support HTTP/2.0, so doh.li would be a good server to include in testing.

Likewise, `curl -I -k --http1.1` is able to connect to 188 of these servers, indicating that attempting a HTTP/2.0 negotiation does not affect ability to connect to these servers.

## What are you going to contribute?

The above.

**Comment by jedisct1** [comment]
[It has always been using HTTP/2](https://github.com/DNSCrypt/dnscrypt-proxy/blob/85e7dddc9bf4c8a1b21d987b4aa3e0084e3d97ec/dnscrypt-proxy/xtransport.go#L193) and [even prints warnings](https://github.com/DNSCrypt/dnscrypt-proxy/blob/85e7dddc9bf4c8a1b21d987b4aa3e0084e3d97ec/dnscrypt-proxy/serversInfo.go#L482) if a server doesn't support HTTP/2.
