### ISSUE TITLE
time based blocklist entries are ignored

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1548]
## *What* is affected by this bug?

time based restriction lists are not generated as expected

## *When* does this occur?

whenever I execute the `generate-domains-blocklist.py` script and redirect the result to `blacklist.txt`

## *Where* does it happen?

on Linux 5.9.14-arch1-1 with dnscrypt-proxy version 2.0.44 

## *How* do we replicate the issue?

1. enter the following entries in `domains-time-restricted.txt`

```
discord.*  @work 
discordapp.*  @work 
```

2. the `domains-blocklist.conf` file has the following uncommented line although the end result is the same even if I comment it

```
file:domains-time-restricted.txt
```

3. run the script `generate-domains-blocklist.py` and generate the `blacklist.txt` file

```
./generate-domains-blocklist.py > ../blacklist.txt
Loading data from [file:domains-time-restricted.txt]
Loading data from [file:domains-time-restricted.txt]
Loading data from [file:domains-allowlist.txt]
```
4. open `blacklist.txt` and it contains the following lines

```
########## Time-based blocklist ##########

# ignored: [discordapp.*      @work] was in the time-restricted list, but without a time restriction label
# ignored: [discord.*         @work] was in the time-restricted list, but without a time restriction label
```

5. the `dnscrypt-proxy.toml` file already contains the following lines and the service had been restarted before running the script

```
[schedules]
  [schedules.'work']
  mon = [{after='18:00', before='02:00'}]
  tue = [{after='18:00', before='02:00'}]
  wed = [{after='18:00', before='02:00'}]
  thu = [{after='18:00', before='02:00'}]
  fri = [{after='18:00', before='02:00'}]
  sat = [{after='18:00', before='02:00'}]
  sun = [{after='2:00', before='23:00'}]
``` 

## Expected behavior (i.e. solution)

The `blacklist.txt` file should have uncommented entries of the domains defined in `domains-time-restricted.txt` and the domains mentioned in it should be blocked.

## Other Comments
Am I missing something? Did I forget a configuration somewhere?

**Comment by jedisct1** [comment]
The `generate-domains-blocklist.py` tool has a dedicated command-line switch for time-restricted inputs:

```text
optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        file containing blocklist sources
  -a ALLOWLIST, --allowlist ALLOWLIST
                        file containing a set of names to exclude from the blocklist
  -r TIME_RESTRICTED, --time-restricted TIME_RESTRICTED
                        file containing a set of names to be time restricted
  -i, --ignore-retrieval-failure
                        generate list even if some urls couldn't be retrieved
  -o OUTPUT_FILE, --output-file OUTPUT_FILE
                        save generated blocklist to a text file with the provided file name
  -t TIMEOUT, --timeout TIMEOUT
                        URL open timeout
```

**Comment by ghost** [comment]
@jedisct1 that still generates the same output as I mentioned above.

```
./generate-domains-blocklist.py -r domains-time-restricted.txt > ../blacklist.txt
head -5 ../blacklist.txt

########## Time-based blocklist ##########

# ignored: [discord.*         @work] was in the time-restricted list, but without a time restriction label
# ignored: [discordapp.*      @work] was in the time-restricted list, but without a time restriction label
```

**Comment by jedisct1** [comment]
Ah indeed, this is due to `discord.*` being a regular expression.

2baabbca8a9126ea248e01de42227e68cef1ae0e should fix it.
