### ISSUE TITLE
Respecting original record TTLs when caching is enabled

### ISSUE THREAD

**Issue by guillaumerenault** [DNSCrypt/dnscrypt-proxy#1552]
Respecting original record TTLs when caching is enabled

## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [X] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [X] Other

## Description

This question both applies to the [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) and the [encrypted-dns-server](https://github.com/jedisct1/encrypted-dns-server) projects (I'm unsure where to open this issue and if this is a feature request)

Is there a way to strictly respect the TTL values given by upstream resolvers when enabling the cache storage ? My question applies to both [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) and [encrypted-dns-server](https://github.com/jedisct1/encrypted-dns-server) projects.

I'm hosting a DNSCrypt server using [encrypted-dns-server](https://github.com/jedisct1/encrypted-dns-server) and I'm running on my local machine [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) using my DNSCrypt server as upstream resolver (single entry in the server_name directive)

I would like the dnscrypt-proxy cache to strictly honor the given TTL values for the records returned by the upstream resolver (my DNSCrypt server)

So far the current setup I've adopted is disabling caching on my DNSCrypt server and set the cache TTL to 30 seconds for successful queries on my local dnscrypt-proxy cachel
```
DNSCrypt-server: no cache
Local dnscrypt-proxy: cache with forced 30s for all successful queried records
```
With the following directives in my ```dnscrypt-proxy.toml``` configuration:

```toml
cache = true
cache_size = 4096
cache_min_ttl = 30
cache_max_ttl = 30
cache_neg_min_ttl = 0
cache_neg_max_ttl = 0
```
I'd like to have the original/exact TTL for a record, not one I have set in a configuration file which assigns all the successful queried records the same TTL.

Assuming there is a way to store the correct the TTL values in the cache, I've thought about the possible scenarios:

Local cache
```
DNSCrypt-server: no cache
Local dnscrypt-proxy: cache with original TTL values for successful queried records
```

Resolver cache
```
DNSCrypt-server: cache with original TTL values for successful queried records
Local dnscrypt-proxy: no cache
```

No cache
```
DNSCrypt-server: no cache
Local dnscrypt-proxy: no cache
```

I've read both of @jedisct1 's articles : [Stop using ridiculously low DNS TTLs](https://00f.net/2019/11/03/stop-using-low-dns-ttls/) and [DNS records and TTL - how long does a second actually last?](https://00f.net/2011/11/17/how-long-does-a-dns-ttl-last/)

While I do agree with the rationale against low TTLs, I think it should be possible to have a cache that does not tamper with TTLs set by the original authoritative server.

In the first article, it is written "I patched Encrypted DNS Server to store the original TTL of a response", could this patch be made into an available option (for dnscrypt-proxy aswell maybe?) ?

What do you think ?  Please let me know if I've overlooked or misunderstood some details regarding DNS caches and TTLs and how it's handled in the [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) and the [encrypted-dns-server](https://github.com/jedisct1/encrypted-dns-server) projects.

Thank you.

**Comment by jedisct1** [comment]
```toml
cache_min_ttl = 30
cache_max_ttl = 30
```

This forces the received TTL to be set to 30.

If you don't want the TTL to be altered, set the minimum to `0` and leave the maximum to its default value or higher:

```toml
cache_min_ttl = 0
cache_max_ttl = 86400
```

**Comment by jedisct1** [comment]
```toml
cache_neg_min_ttl = 0
cache_neg_max_ttl = 0
```

Same here, setting `max_ttl` to `0` would force the TTL to be zero, doing exactly the opposite of what you are trying to achieve. Leave `max` high. TTL is clamped between `min` and `max`.

**Comment by guillaumerenault** [comment]
Thank you!
