### ISSUE TITLE
Failure to connect to Internet after upgrading to version 2.0.44 on Fedora 32 !!

### ISSUE THREAD

**Issue by Nokia808** [DNSCrypt/dnscrypt-proxy#1556]
Hi. I was using dnscrypt-proxy on my Fedora since long time without problem since you inform me how to configure it correctly - see my previous post & it's date bellow:
https://github.com/DNSCrypt/dnscrypt-proxy/issues/856

But today I received update for dnscrypt-proxy from my official Fedora 32 repositories .... I updated dnscrypt-proxy to version: 2.0.44
Just after rebooting of my PC, I became unable to connect to Internet at all !! I did not change any thing, I did not change my ISP, all other devices that do not use dnscrypt-proxy are working very well without any problem !

It seem that this update is the cause of the problem !

Please, your kind help ! 

## *When* does this occur?
Just after updated dnscrypt-proxy to version 2.0.44-5.fc32 X86_64

## Expected behavior (i.e. solution)
Internet connection should not affected & should be possible after updating & rebooting the PC.

## Other comment
1) I did not open a ticket on RedHat BugZilla waiting your response 1st .....
2) I'm currently, reaching to Internet from my PC through using other WiFi point that I connected to it - after bug - using the default (non dnscrypt-proxy setting).

**Comment by Nokia808** [comment]
Hi. 
I discover the following, just after I post the above comment:
I run:
`$ systemctl status dnscrypt-proxy`
& I received the following output:
`Unit dnscrypt-proxy.service could not be found.`

But when I run "dnf info dnscrypt-proxy" I received the following output:
```
$ dnf info dnscrypt-proxy
Last metadata expiration check: 0:12:10 ago on Fri 25 Dec 2020 01:27:44 PM GMT.
Installed Packages
Name         : dnscrypt-proxy
Version      : 2.0.44
Release      : 5.fc32
Architecture : x86_64
Size         : 12 M
Source       : dnscrypt-proxy-2.0.44-5.fc32.src.rpm
Repository   : @System
From repo    : updates
Summary      : Flexible DNS proxy, with support for encrypted DNS protocols
URL          : https://github.com/jedisct1/dnscrypt-proxy
License      : ISC
Description  : 
             : A flexible DNS proxy, with support for modern encrypted DNS
             : protocols such as DNSCrypt v2 and DNS-over-HTTP/2.
             : 
             : Features:
             : 
             :  - DNS traffic encryption and authentication. Supports
             :    DNS-over-HTTPS (DoH) and DNSCrypt.
             :  - DNSSEC compatible
             :  - DNS query monitoring, with separate log files for regular and
             :    suspicious queries
             :  - Pattern-based local blocking of DNS names and IP addresses
             :  - Time-based filtering, with a flexible weekly schedule
             :  - Transparent redirection of specific domains to specific
             :    resolvers
             :  - DNS caching, to reduce latency and improve privacy
             :  - Local IPv6 blocking to reduce latency on IPv4-only networks
             :  - Load balancing: pick a set of resolvers, dnscrypt-proxy will
             :    automatically measure and keep track of their speed, and
             :    balance the traffic across the fastest available ones.
             :  - Cloaking: like a HOSTS file on steroids, that can return
             :    preconfigured addresses for specific names, or resolve and
             :    return the IP address of other names. This can be used for
             :    local development as well as to enforce safe search results on
             :    Google, Yahoo and Bing.
             :  - Automatic background updates of resolvers lists
             :  - Can force outgoing connections to use TCP; useful with tunnels
             :    such as Tor.
```

**Comment by ianbashford** [comment]
Season's Greeting @Nokia808 

I don't have Fedora I'm afraid - hopefully we can bump you along a little. 
You could start with checking out the known services:

`systemctl list-unit-files | grep enabled |grep dns`
If there's no dnscrypt-proxy in there, remove the enabled
`systemctl list-unit-files | grep dns`

You can look at logs for services with journalctl like this:

`journalctl -u dnscrypt-proxy`

**Comment by Nokia808** [comment]
@ianbashford 
Thank you very much for your kind & very fast response !

Before informing you the output of commands that you asked me to perform, I have to inform you about the following:
I'm already used to use the following setting from within my "Advanced Network Configuration" from my application menu of my Cinnamon DE - see the following screenshot no. 1
![1](https://user-images.githubusercontent.com/25375330/103137160-7b391080-46be-11eb-9b46-bcb986b17149.png)
The above setting "Automatic (DHCH) addresses only" method was working very good before receiving the update. But after receiving the update became not working at all (no any Internet connection) !
I tried to change the above "Method" setting from "Automatic (DHCH) addresses only" into "Automatic DHCH" - see screenshot no. 2, then I rebooted the PC, then visit site https://ipleak.net & really it seem that the issue is fixed because this site does not show my ISP DNS further !
![2](https://user-images.githubusercontent.com/25375330/103137440-e97ed280-46c0-11eb-8362-c70662138524.png)

To be sure, I re-changed "Method" into "Automatic (DHCH) addresses only" & reboot the PC. It DID NOT worked at all & no any Internet connection could be used. Finally, I re-changed "Method" into "Automatic (DHCH)" then rebooted the PC, & it worked very fine without showing my ISP DNS on the site https://ipleak.net
There are other "Method" configurations like "Manual", "Link-Local Only", Shared to other computer", & "Disabled" but I did not used any of them before & not know how to configure them ......

Now let we go to the output of commands that you are asked me to perform:
1) the output of "$ systemctl list-unit-files | grep enabled |grep dns"
is nothing !
2) the output of "$ systemctl list-unit-files | grep dns"
was the following:
```
chrony-dnssrv@.service                       static          disabled     
dnsmasq.service                              disabled        disabled     
chrony-dnssrv@.timer                         disabled        disabled  
```   
3) the output of command "journalctl -u dnscrypt-proxy"
was the following:
```
-- Logs begin at Fri 2020-12-25 14:19:49 GMT, end at Fri 2020-12-25 15:12:33 GM>
-- No entries --
lines 1-2/2 (END)
```

Kindly, what could be this ?

**Comment by ianbashford** [comment]
can I ask the command you used to upgrade?  (I'm not a Fedora expert at all) but it looks like it's not installed at the moment.

I checked the rpm file for dnscrypt-proxy-2.0.44-5.fc32.src.rpm (from your `dnf info` command and it's what I'd expect -- the source code and not an installation.
That's consistent with not be able to find any of the unit files.

I suspect a new install command might be required...

A couple of other things to try:
`which dnscrypt-proxy` (to find the binary)
`find / -name dnscrypt-proxy 2>/dev/null`   ( if it's not on the path, try to find the binary )

The binary rpm file drops it in `/usr/bin/dnscrypt-proxy`   so i suspect it's there.
running `/usr/bin/dnscrypt-proxy -help`  will tell you if there is a binary

**Comment by ghost** [comment]
Hi, the latest changes to the RPM removed the systemd files and falls back to `dnscrypt-proxy`'s method instead. I ran into this issue myself. Since `dnscrypt-proxy` doesn't overwrite the existing service file, the one previously shipped with Fedora will cause `dnscrypt-proxy` to not start.

Try removing `/etc/systemd/system/dnscrypt-proxy.service` and re-run `sudo dnscrypt-proxy -service install`.

Since the RPM no longer uses sockets, you might need to edit the config as well to specify listening addresses:

```
listen_addresses = ['127.0.0.1:53', '[::1]:53']
```

**Comment by ianbashford** [comment]
thanks @remyabel  
Let us know if this solves it @Nokia808

**Comment by Nokia808** [comment]
@ianbashford 
I'm using the ordinary command for updating my system since I installed Fedora for 1st time (Fedora 24 at that time), which is:
sudo dnf upgrade --refresh
No any new command at all !!

@remyabel 
I run - as a NON root - the following to see (just view):
/etc/systemd/system/dnscrypt-proxy.service
but the output was:
bash: /etc/systemd/system/dnscrypt-proxy.service: No such file or directory
Then I run the following (as a NON root also):
vi /etc/systemd/system/dnscrypt-proxy.service
& this lead to try to open a NEW file, so I closed the terminal.

Now, what I have to try ? Is still there a need to run "sudo dnscrypt-proxy -install service" command ? (Please review it's spell if correct because I did not used such command before "-install"

**Comment by ghost** [comment]
Yes you need to run that command. See: https://src.fedoraproject.org/rpms/dnscrypt-proxy/blob/master/f/dnscrypt-proxy.spec#_141

It'll install the service file.

**Comment by Nokia808** [comment]
@remyabel 
Okay, but just one concern: which is better run "sudo dnscrypt-proxy -install service" or run "sudo dnf reinstall dnscrypt-proxy"
Also, regarding 1st command is the flag "-install" or "--install" ?

**Comment by ianbashford** [comment]
If I've understood this right, dnscrypt-proxy is now correctly installed for fedora so you don't need to run `dnf reinstall` again.

The new fedora install means **_you_** need to install the service.  you do that with 
`sudo dnscrypt-proxy -install service`

They're single hyphens.

**Comment by Nokia808** [comment]
@ianbashford 
@remyabel 
Hi again ! I tried the command "sudo dnscrypt-proxy -install service"
but the output was the following:
flag provided but not defined: -install
```
Usage of dnscrypt-proxy:
  -check
    	check the configuration file and exit
  -child
    	Invokes program as a child process
  -config string
    	Path to the configuration file (default "dnscrypt-proxy.toml")
  -json
    	output list as JSON
  -list
    	print the list of available resolvers for the enabled filters
  -list-all
    	print the complete list of available resolvers, ignoring filters
  -logfile string
    	Write logs to file
  -loglevel value
    	Log level (0-6) (default 2)
  -netprobe-timeout int
    	Override the netprobe timeout (default 60)
  -pidfile string
    	If specified, write pid to file.
  -resolve string
    	resolve a name using system libraries
  -service string
    	Control the system service: ["start" "stop" "restart" "install" "uninstall"]
  -show-certs
    	print DoH certificate chain hashes
  -syslog
    	Send logs to the local system logger (Eventlog on Windows, syslog on Unix)
  -version
    	print current proxy version
```

What was this ??

**Comment by jedisct1** [comment]
>  -service string
>    	Control the system service: ["start" "stop" "restart" "install" "uninstall"]

It should be `-service install` not `-install service`.

But check that it works in interactive mode before installing it as a service.

**Comment by Nokia808** [comment]
Does this mean that we need to run "sudo dnscrypt-proxy -service install" then followed by reboot & finally run "sudo dnscrypt-proxy -service start" ??

**Comment by Nokia808** [comment]
@jedisct1 
What is the interactive mode & how can I use it ?

**Comment by ianbashford** [comment]
Sorry -- my bad on flipping the command 
interactive mode will just run in the foreground.   
If the file `/etc/dnscrypt-proxy/dnscrypt-proxy.toml` exists from your old install, then try
`dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml` 

If there are issues it will let you know.

**Comment by ghost** [comment]
No a reboot is not necessary. And you can do `systemctl start dnscrypt-proxy`. Either would work fine, but why don't you try the commands?

> What is the interactive mode & how can I use it ?

Make sure your configuration works by running the command manually, i.e `dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml`. The service file calls this under the hood.

Also thanks for pointing out the typo, I fixed it now.

**Comment by Nokia808** [comment]
@ianbashford 
I run (as NON root):
$ dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
& output was nothing ! Is this okay ? If yes, then what is further ?

**Comment by ianbashford** [comment]
While it's running interactively, I'd open a second terminal window and try 
`dig www.google.com` and check you get a result.  If that works, then you should be ready to run the service install and service start commands.

**Comment by Nokia808** [comment]
@remyabel 
@ianbashford 
@jedisct1 
I run "sudo dnscrypt-proxy -service install" & it installed it okay. Then I run "sudo dnscrypt-proxy -service start" then changed the "Method" from "Automatic (DHCP) into "Automatic (DHCP) addresses only" then power OFF my PC, waited 3 minutes, finally power ON my PC, but it does not worked !!
I run "systemctl status dnscrypt-proxy" & it gave me the following:
```

● dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
     Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2020-12-26 19:25:22 GMT; 14s ago
    Process: 3368 ExecStart=/usr/bin/dnscrypt-proxy -config dnscrypt-proxy.toml (code=exited, status=255/EXCEPTION)
   Main PID: 3368 **(code=exited, status=255/EXCEPTION)**
        CPU: 9ms
```
then I tried "sudo dnscrypt-proxy -service restart" but still not working !!
What I have to do now ? Do I have to try:
`sudo systemctl start dnscrypt-proxy`
then
`sudo systemctl enable dnscrypt-proxy`

**Comment by ghost** [comment]
Try editing `dnscrypt-proxy.toml` as I said earlier to set the listening addresses since the socket file is now removed.

Editing your network manager settings should not be necessary, you only need to add this to `/etc/resolv.conf`:

```
nameserver ::1
nameserver 127.0.0.1
options edns0 single-request-reopen
```

**Comment by Nokia808** [comment]
@remyabel 
1) The listening address is already set on:
listen_addresses = ['127.0.0.1:53']
I have no IPv6 because no ISP providing it in my country (Iraq), so is there a further need to set it at:
listen_addresses = ['127.0.0.1:53', '[::1]:53']

2) regarding /etc/resolv.conf does there a need to add "nameserver : :1" as long as I have no IPv6 ?
The current state of it is as following:
```
# Generated by NetworkManager
nameserver xxx.xxx.xxx.x
nameserver 127.0.0.1
```

I used xxx because I do not know if the 1st address of private data that should not demonstrated to public or not.

**Comment by Nokia808** [comment]
Any further instruction ?

**Comment by eclipseo** [comment]
> Hi, the latest changes to the RPM removed the systemd files and falls back to `dnscrypt-proxy`'s method instead. I ran into this issue myself. Since `dnscrypt-proxy` doesn't overwrite the existing service file, the one previously shipped with Fedora will cause `dnscrypt-proxy` to not start.

I wasn't aware of that, I'll try to fix it somehow.. In any case the config file needs to be updated to switch listen-adresses after update and Idon't know how to signal that to the users.I'm sorry about the trouble caused.

**Comment by eclipseo** [comment]
> @remyabel
> 
>     1. The listening address is already set on:
>        listen_addresses = ['127.0.0.1:53']
>        I have no IPv6 because no ISP providing it in my country (Iraq), so is there a further need to set it at:
>        listen_addresses = ['127.0.0.1:53', '[::1]:53']
> 
>     2. regarding /etc/resolv.conf does there a need to add "nameserver : :1" as long as I have no IPv6 ?
>        The current state of it is as following:
> 
> 
> ```
> # Generated by NetworkManager
> nameserver xxx.xxx.xxx.x
> nameserver 127.0.0.1
> ```
> 
> I used xxx because I do not know if the 1st address of private data that should not demonstrated to public or not.

If you have no IPV6, just set it at `listen_addresses = ['127.0.0.1:53']`

You need to disable NetworkManager handling of `resolv.conf`

Create a new `/etc/resolv.conf` file with the following content:

```
nameserver 127.0.0.1
options edns0
```

and disable editing with `sudo chattr +i /etc/resolv.conf`

See https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux#if-the-content-of-etcresolvconf-doesnt-stick

Alternatively you can disable NeworkManager handling of resolv.conf in /etc/NetworkManager/NetworkManager.conf by setting dns=none:

```
[main]
#plugins=ifcfg-rh
dns=none
```

**Comment by Nokia808** [comment]
@eclipseo 
Hi. Thank you for your help.
But I'm already set dns=none in my /etc/NetworkManager/NetworkManager.conf !!
Listen address is already set to = ['127.0.0.1:53']

So, what is wrong with my case ?!! Do I have to edit resolv.conf file to change it from:
```
# Generated by NetworkManager
nameserver xxx.xxx.xxx.x
nameserver 127.0.0.1
```
into:
```
nameserver 127.0.0.1
options edns0
```
and if yes, then do I still have to use "sudo chattr +i /etc/resolv.conf" inspite the fact that I'm already set dns=none in my /etc/NetworkMnanger/NetworkManager.conf ?

**Comment by eclipseo** [comment]
> So, what is wrong with my case ?!! Do I have to edit resolv.conf file to change it from:
> 
> ```
> # Generated by NetworkManager
> nameserver xxx.xxx.xxx.x
> nameserver 127.0.0.1
> ```
> 
> into:
> 
> ```
> nameserver 127.0.0.1
> options edns0
> ```

I think yes. The chattr shouldn't be needed but it doesn't hurt. I don't know how what you've edited in the NM GUI impacts things.

**Comment by eclipseo** [comment]
What does `systemctl status dnscrypt-proxy.service` say?

t should look like this:

```
dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
     Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2020-12-28 11:18:01 CET; 2s ago
   Main PID: 82511 (dnscrypt-proxy)
      Tasks: 11 (limit: 76411)
     Memory: 7.2M
        CPU: 32ms
     CGroup: /system.slice/dnscrypt-proxy.service
             └─82511 /usr/bin/dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml

Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: Network connectivity detected
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: Now listening to 127.0.0.1:53 [UDP]
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: Now listening to 127.0.0.1:53 [TCP]
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: Now listening to https://127.0.0.1:3000/dns-query [DoH]
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: Source [relays] loaded
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: Source [public-resolvers] loaded
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: Firefox workaround initialized
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: [scaleway-fr] OK (DNSCrypt) - rtt: 23ms
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: Server with the lowest initial latency: scaleway-fr (rtt: 23ms)
Dec 28 11:18:01 Cassini dnscrypt-proxy[82511]: dnscrypt-proxy is ready - live servers: 1
```

**Comment by Nokia808** [comment]
@eclipseo 

1) on my system the output of "systemctl status dnscrypt-proxy" is:

```
● dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
     Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2020-12-28 13:35:46 GMT; 1min 37s ago
    Process: 10469 ExecStart=/usr/bin/dnscrypt-proxy -config dnscrypt-proxy.toml (code=exited, status=255/EXCEPTION)
   Main PID: 10469 (code=exited, status=255/EXCEPTION)
        CPU: 6ms
```

2) regarding /etc/resolv.conf file does the following step is correct:
sudo rm /etc/resolv.conf
sudo vi /etc/resolv.conf
then adding within new file the contents you already detailed.
And what about my network connection to Internet, power if OFF during this process from GUI (press Fn+F8) or can leave it powered ON ?

**Comment by ghost** [comment]
Please try things before asking, this thread is getting way too long. Removing `/etc/resolv.conf` is not needed, you only need to edit it and changes are applied automatically. You don't need to turn the Internet on/off either.

I think the original issue related to Fedora has been resolved, yes?

**Comment by Nokia808** [comment]
@remyabel 
I will try now !

**Comment by eclipseo** [comment]
> @remyabel
> I will try now !

I think the issue might be in `/usr/bin/dnscrypt-proxy -config dnscrypt-proxy.toml`. This does not point to the config file in /etc.
Try :

```
sudo dnscrypt-proxy -service uninstall
sudo dnscrypt-proxy -service install --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
sudo systemctl restart dnscrypt-proxy.service
```

**Comment by Nokia808** [comment]
@remyabel 
@eclipseo 
Hi. I tried & ended by failure !
I did the following (WHILE I'M STILL USING "Automatic (DHCP)" as a method from my NetworkManager GUI:
sudo vi /etc/resolv.conf
& change contents into the following
127.0.0.1
options edns0

Just when saved changes (by :qw), I loss any Internet connection though I'm still using "Automatic (DHCP)" as a method ! I perform vi /etc/resolv.conf to see my changed still be saved or lost & they were still saved. I changed method into "Automatic (DHCP) addresses only" then reboot my PC. After reboot, I found by self without Internet connection ! I perform vi /etc/resolv.conf & saw the following ONLY:
`nameserver 127.0.0.1`
The line "options edns0" was lost !!
I tried "sudo dnscrypt-proxy -service restart" & output said it is restarted, but no any Internet connection was possible !
So, I changed method from my NetworkManager GUI into "Automatic (DHCP)" then reboot my PC. After reboot my PC I'm now able to use my Firefox & browse Internet. I run vi /etc/resolv.conf & surprisingly I saw the following:
nameserver xxx.xxx.xxx.x
nameserver 127.0.0.1
So, the xxx.xxx.xxx.x (the DNS of my ISP as I thinking now) return !! This is seem to be due to effect of NetworkManager GUI ..... But when I visited site https://ipleak.net I did not saw DNS of my ISP (I saw other DNS as if that the dnscrypt-proxy working okay !!!)

So, Fedora problem do not solved on my side. But I did not received new update for dnscrypt-proxy till now. I have to wait some days before receiving it.
It is very obvious that dnscrypt-proxy do not run on my system.
But why resolv.conf file changed so that it loss the line "options edns0" was lost ?? And how changing "method" from within GUI will change etc/resolv.conf ??

**Comment by eclipseo** [comment]
You shouldn't change anything in the NetworkManager GUI, let the defaults in place . If you do this you will overwrite your resolv.conf file. If you have nameserver xxx.xxx.xxx.x you are not effectively using dnscrypt-proxy.

The output of `systemctl status dnscrypt-proxy` when you have no Internet connection should tell us more. I don't think the issue is caused by the failing update.

Did you run:
```
sudo dnscrypt-proxy -service uninstall
sudo dnscrypt-proxy -service install --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
sudo systemctl restart dnscrypt-proxy.service
```

This should fix part of the problem.

**Comment by Nokia808** [comment]
@eclipseo 
1) Okay I will retry again, but just inform me: which setting you prefer to use in GUI "Automatic (DHCP)" or "Automatic (DHCP) addresses only" as a method ? Just inform me about this to try with it without change.
2) no I did not run:
sudo dnscrypt-proxy -service uninstall
sudo dnscrypt-proxy -service install --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
sudo systemctl restart dnscrypt-proxy.service
I will run them now & see the result ...
3) what about remove dnscrypt-proxy then install it again from scratch ? Does this resolve the issue ?

**Comment by eclipseo** [comment]
> Okay I will retry again, but just inform me: which setting you prefer to use in GUI "Automatic (DHCP)" or "Automatic (DHCP) addresses only" as a method ? Just inform me about this to try with it without change.

Just let it at the default "Automatic (DHCP)" with no other DNS servers specified. Then rewrite the resolv.conf file as said before.

> I will run them now & see the result ...

This should let dnscrypt-proxy find the config file. Then give us again the output of `systemctl status dnscrypt-proxy` to see what is the remaining issue.

> what about remove dnscrypt-proxy then install it again from scratch ? Does this resolve the issue ?

Might not be useful for you, you can try installing the version I pushed earlier by downloading and installing it from Koji: https://kojipkgs.fedoraproject.org//packages/dnscrypt-proxy/2.0.44/8.fc32/x86_64/dnscrypt-proxy-2.0.44-8.fc32.x86_64.rpm

**Comment by ghost** [comment]
Please stop pinging people. It's unnecessary and resubscribes them to the thread.

I think we've already given you the necessary steps to resolve the issue. Try the given advice *before* posting a comment (this thread is already reaching 34 comments).

The steps I posted worked for me on my system, you can check the spec I linked to see the exact commands run by Fedora. Anything else is likely out of scope and an issue on your personal system.

**Comment by Nokia808** [comment]
@eclipseo 
I run the following commands:
sudo dnscrypt-proxy -service uninstall
sudo dnscrypt-proxy -service install --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
sudo systemctl restart dnscrypt-proxy.service
They worked 100% & now every time I reboot or power OFF/ON my PC then run:
$ systemctl status dnscrypt-proxy
I'm getting the following output:
```
● dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
     Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2020-12-28 18:29:20 GMT; 8min ago
   Main PID: 774 (dnscrypt-proxy)
      Tasks: 10 (limit: 9163)
     Memory: 30.9M
        CPU: 1.635s
     CGroup: /system.slice/dnscrypt-proxy.service
             └─774 /usr/bin/dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
```
However, it seem that dns=none NOT WORKING because /etc/resolv.conf is still editable & I'm unable to use dnscrypt-proxy **UNLESS** by set NetworkManager GUI at "Automatic (DHCP) addresses only" as a method with set "DNS servers" within it at 127.0.0.1 While using default setting with method set at "Automatic (DHCP)" with no any DNS set within it, it will lead to overwrite /etc/resolv.conf with deleting "127.0.0.1" & "options edns0" & replace them by just "nameserver xxx.xxx.xxx.x" which is my ISP DNS !!
It seem that this issue is Fedora specific, & for that I will close this issue & kindly please let we continue it on:
https://bugzilla.redhat.com/show_bug.cgi?id=1910969
Immediately after close this issue here on GitHub, I will post my comment on RedHat BugZilla. It seem that this bug lead us to discover other bug which is Fedora specific !

@remyabel
I'm sorry & I understand now why you insisted on stop discussion here !

Thank you all for your kind help !

**Comment by ghost** [comment]
Hello.

**Nokia808**, you have written that `/etc/resolv.conf` file is replaced with namserver informations etc. Please open NetworkManager, set "_Automatic (DHCP), addresses only_" and add `127.0.0.1` as a DNS server. If it's about `/etc/resolv.conf` file: please read ["If 'immutable' flag doesn't work"](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux#if-the-content-of-etcresolvconf-doesnt-stick) subsection [in:] "**If the content of /etc/resolv.conf doesn't stick**".

To check DNSCrypt-Proxy status you can use the following command  (run as a normal user): `journalctl -u dnscrypt-proxy.service` There are also another two commands, that should help you to determine what is happening with DNSCrypt-Proxy:

`systemctl is-enabled dnscrypt-proxy.service`
`systemctl is-active dnscrypt-proxy.service`

First command should return `enabled` while second - `active` as a result. Additionally, first result tell us that DNSCrypt-Proxy is enabled on boot up; second result whether the service is active (i.e. running).

Hope this helps. Best regards and all the best in 2021...
