### ISSUE TITLE
Log resolved IP addresses in the query log

### ISSUE THREAD

**Issue by ZzZombo** [DNSCrypt/dnscrypt-proxy#1557]
## Is your feature request related to a problem?
Not really, I'd just like to see resolved IP-addresses in the query log.

## Describe the solution you'd like
Results of DNS resolution should include resolved IP-addresses where applicable. Alternatively, make the log format configurable by the end user so it's possible to adjust it on a whim.

## Alternatives you've considered
I took a look at the source code, and it appears the log format is hardcoded into the application, so short of creating a fork there is nothing I can do myself.

## Who will that feature be useful to?
There may be not a whole lot of practical uses, but I feel the logs w/o that information are kind of incomplete.

## What are you going to contribute?
I don't know Go, I'm not sure I can be of any help delivering this feature. However, it's probable with guidance I could contribute something useable.

## Additional context
None.

**Comment by black-cerberon** [comment]
bump
