### ISSUE TITLE
Fresh dnscrypt-proxy install not working on pfsense

### ISSUE THREAD

**Issue by Jsalas424** [DNSCrypt/dnscrypt-proxy#1559]
## *What* is affected by this bug?
DNSCrypt Proxy not resolving in pfsense as expected per: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-pfsense

## *How* do we replicate the issue?

DNSCrypt 2.0.44 was installed on pfsense 2.4.5-RELEASE as per instructions here: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-pfsense

## Expected behavior (i.e. solution)

DNS should be resolving and Forwarding config should be reflected under Status -> DNS Resolver

## Other Comments
The service is running at port 5360 and it's working. 
```
[2.4.5-RELEASE][jon@pfSense.TracheNet]/usr/local/etc/dnscrypt-proxy: dig sigfail.verteiltesysteme.net @127.0.0.1 -p 5360

; <<>> DiG 9.14.12 <<>> sigfail.verteiltesysteme.net @127.0.0.1 -p 5360
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57522
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;sigfail.verteiltesysteme.net.	IN	A

;; Query time: 281 msec
;; SERVER: 127.0.0.1#5360(127.0.0.1)
;; WHEN: Sat Dec 26 20:49:05 EST 2020
;; MSG SIZE  rcvd: 57

[2.4.5-RELEASE][jon@pfSense.TracheNet]/usr/local/etc/dnscrypt-proxy: dig sigok.verteiltesysteme.net @127.0.0.1 -p 5360

; <<>> DiG 9.14.12 <<>> sigok.verteiltesysteme.net @127.0.0.1 -p 5360
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9841
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;sigok.verteiltesysteme.net.	IN	A

;; ANSWER SECTION:
sigok.verteiltesysteme.net. 2399 IN	A	134.91.78.139

;; Query time: 281 msec
;; SERVER: 127.0.0.1#5360(127.0.0.1)
;; WHEN: Sat Dec 26 20:49:17 EST 2020
;; MSG SIZE  rcvd: 71
```

**Comment by Jsalas424** [comment]
I have found that this was actually NOT working. I added  `
forward-zone:
  name: "."
  forward-addr: 127.0.0.1@5353` to Services -> DNS Resolver -> Custom options but my clients failed to resolve.

**Comment by jedisct1** [comment]
> I added `forward-zone: name: "." forward-addr: 127.0.0.1@5353`

The documentation seems to mention something slightly different:

```text
do-not-query-localhost: no

forward-zone:
  name: "."
  forward-addr: 127.0.0.1@5353
```

Note the first line, and the new lines and spaces before `name` and `forward-addr`.

**Comment by welwood08** [comment]
What happens if you forward to port 5360 instead of 5353?
