### ISSUE TITLE
[Question] Blocking a url but not its domain.

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1565]
## Subject

* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description

Hi,

I've been using DNSCrypt-proxy for years, flawlessly. I just happen to encounter a situation which brings me to this question:

Is there any way to block a specific url but not its domain?
Blocking `=example.com`, `*.example.com`, `example.*` is obvious, but is there a way to block `exmaple.com/example2/*` only?

I'm facing an extension which connects to a site to retrieve favicons, I want to prevent that without blocking the domain. Browser tools (I have in mind uBO) cannot, unfortunately, have a grip on extensions' connections. Moreover and anyway I prefer system-wide rules.

Thanks.

**Comment by welwood08** [comment]
DNS is entirely about domain names (it's in the name), the full URL is never queried. It's simply not possible to do what you want at the DNS level.

You're probably looking for something like a filtering web proxy, but I think that's overkill for just the example you give.
