### ISSUE TITLE
Add an HTTP listener to the local DoH as an alternative to the HTTPS one

### ISSUE THREAD

**Issue by D34DPlayer** [DNSCrypt/dnscrypt-proxy#1567]
## Is your feature request related to a problem?
The DoH is very useful, but if you already have one in place with a reverse proxy, there's no easy way to forward requests from the reverse proxy to the local DoH server.

## Describe the solution you'd like
Add an option to have an HTTP listener instead of the HTTPS one, for proxying behind an existing HTTPS server.

## Alternatives you've considered
Right now what can be done is installing another DoH server with an HTTP listener and make it forward to the dnscrypt-proxy DoH server.

## Who will that feature be useful to?
This is needed the moment you have any other HTTPS server running and as such you need a reverse proxy.

## What are you going to contribute?
I'd need to learn Go first, but I could probably give it a try, no idea right now how hard it would be to implement this.

## Additional context
Nothing.

**Comment by jedisct1** [comment]
The local DoH feature is only meant to be used locally, by a trusted web browser, as a workaround for the current limitations of Firefox regarding the ESNI experiment.

If you need an actual DoH server, you can use [DoH server](https://github.com/jedisct1/doh-server) or Adguard.
