### ISSUE TITLE
"Unrecognized DNS" & "listen udp 127.0.0.1:53: bind: permission denied"

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1573]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [x ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description

Hi everyone,
I have gone through the DNSCrypt installation description and everything has run pretty smoothly. I also installed BitBar and the dnsswitcher plugin. However, I am now in a bind.

Firstly, BitBar only shows "Unrecognized DNS" in the menu bar, which feels less informative as it should be. Is this a normal behaviour or should I expect more information about the DNS server I am using? (picture 1 shows BitBar through the Terminal window)

<img width="797" alt="Picture 1" src="https://user-images.githubusercontent.com/65501345/103476046-b91af080-4db2-11eb-83a1-baf34c7b1c58.png">

Secondly, I have DNSCrypt installed and started as a service. However, if I launch it using "./dnscrypt-proxy" in the Terminal, I see a fatal error linked to listening on port 53. See picture 2 below.

<img width="698" alt="Picture 2" src="https://user-images.githubusercontent.com/65501345/103476049-ba4c1d80-4db2-11eb-8380-509f6d82c0b4.png">

I have seen the related information in the installation description, but turning off SIP in Big Sur seems way more of a hurdle than it used to in the past (see: https://eclecticlight.co/2020/06/25/big-surs-signed-system-volume-added-security-protection/). Note that the same happens if I change the listening port to something else (e.g. 52) in dnscrypt-proxy.toml.

Any ideas for a workaround that does not involve turning off SIP? There is a line about using another port and forwarding to port 53, but I am unsure about how to do that. 

Anyway, all help is appreciated. The end goal is to use DNSCrypt for DNS anonymization.

Thanks in advance!

Paul

Set up: macOS Big Sur; DNSCrypt v2.0.44; Little Snitch 5

**Comment by ianbashford** [comment]
I'm not sure about bitbar and dnsswitcher, but the bind permissions from the terminal can be overcome by running with sudo.  Note that if the service is already running it will still fail as two services can't both bind to the same port
```
sudo ./dnscrypt-proxy -config dnscrypt-proxy.toml
```
If you want to keep the service running AND run a command line as well, then take a copy of dnscrypt-proxy.toml and put in a high port (5300 for example) and you'll avoid the collision (and avoid the need to sudo).

PS. I'd keep the service running on 53.  From memory, I never did have much joy getting OSX to run DNS on a port other than 53, but that was a while ago and things evolve of course... YMMV.

**Comment by jedisct1** [comment]
macOS cannot access a DNS service on a non-standard port, so you should use port `53` here, and type `sudo` before `./dnscrypt-proxy`.

I don't know much about `dnsswitcher` either, but since Big Sur, changing DNS settings require administrative privileges.

You can use [`dnscrypt-proxy switcher`](https://github.com/jedisct1/bitbar-dnscrypt-proxy-switcher), which works fine on Big Sur.

**Comment by ghost** [comment]
Thanks @ianbashford and @jedisct1! So, if I get this right, the second error is not that dnscrypt is not working, simply that I try and launch it while it's already launched as a service. That would make sense.

As for the first point, I just replaced dnsswitcher with dnscrypt-proxy switcher and it seems much better. 

That would seem to answer both questions. Thanks a lot for the rapid responses!

Paul

**Comment by ghost** [comment]
NB: it seems like the "Unrecognized DNS" in DNSswitcher (just like the exclamation mark in DNScrypt-proxy Switcher) is linked to the DNS settings being automatically overridden by the VPN's own DNS servers where all requests are re-routed.
