### ISSUE TITLE
IP Blocklist

### ISSUE THREAD

**Issue by ACEx86** [DNSCrypt/dnscrypt-proxy#1574]
## Is your feature request related to a problem?

The IP Blocklist should not been bypassed by name allowlist.
Usually Ip blocklist is full of malware domains that can use domain name allow list to bypass the restriction.
Some ips that you don't want to access may be (always) bypass Ip blocklist if they are on domain allow list.

## Describe the solution you'd like

IP Blocklist should only get bypassed by IP allow list. ( For an IP range block.. )

## Alternatives you've considered

A setting that could allow IP block list take priority over Domain Name Allowlist

## Who will that feature be useful to?

Some ips that you want to block may get access with name allowlist.
Blocking unwanted connections to some domains even if they are in allowlist.

**Comment by ianbashford** [comment]
I'm no expert on this, but content filtering is a tricky issue.  
As a company I was once at used some cisco software for this I went to check their pages to see if I could get a reference.  Checkout: https://documentation.meraki.com/MX/Content_Filtering_and_Threat_Protection/Content_Filtering/Content_Filtering_Troubleshooting  

There they prioritise whitelisting domains based on reputation over the IP's reputation.

A malicious actor could use a domain to mask a malware loaded IP address, but I'd question the decision taken to add that domain name to an allow_list without adequate verification that the domain name wasn't malicious.
The poor decision in this case is to add that domain to an allow_list.
For reference, the priority order you can use is:
AllowedName > BlockedName > AllowedIP > BlockedIp
