### ISSUE TITLE
Method to upgrade config files and rules lists

### ISSUE THREAD

**Issue by eclipseo** [DNSCrypt/dnscrypt-proxy#1576]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description

With the latest release, the config file headers and settings changed to remove blocklist/whitelist, how do I update the current config files of my users without losing their custom settings? Is there a provision to auto-convert the config files?

**Comment by lifenjoiner** [comment]
Generally, I use a 'diffmerge' GUI tool to update it semi-automatically. A and B, side by side. **Line based**.
In this case, I guess MS Office Word's `compare` functionality will help, or any other 'diffmerge' tool which is **word/character based**.
But if there are a lot of users with all different custom settings, that is not easy ...

**Comment by jedisct1** [comment]
The following strings need to be replaced:

| before       | after         |
|--------------|---------------|
| `blacklist`    | `blocked_names` |
| `whitelist`   | `allowed_names` |
| `ip_blacklist` |` blocked_ips`   |

And a `sed` script can probably do the job in most cases.

But the previous names are still supported in this release. They will only be removed in version 2.1.0.

**Comment by ghost** [comment]
Hello.

**jedisct1**, maybe above information: "_the previous names are still supported in this release_" should be added to the official release info (vide [DNSCrypt-Proxy v. 2.0.45](https://github.com/DNSCrypt/dnscrypt-proxy/releases/tag/2.0.45))?

An information, that "_they will only be removed in version 2.1.0_" seems to be important also.

Best regards.
