### ISSUE TITLE
Discrepancies between example-dnscrypt-proxy.toml/config.go

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#158]
Hi, I notice 2 discrepancies between default values in `example-dnscrypt-proxy.toml` versus `config.go`:

- (1) listen_addresses:
    - set to ['127.0.0.1:53', '[::1]:53'] in [example-dnscrypt-proxy.toml](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L31)
    - set to []string{"127.0.0.1:53"} in [config.go](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/config.go#L60)

- (2) max_clients:
    - set to 250 in [example-dnscrypt-proxy.toml](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L36)
    - set to 100 in [config.go](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/config.go#L75)

Am I correctly assuming these are oversights instead of intentional differences?

Regards

**Comment by jedisct1** [comment]
Good catch!

`max_clients` should probably match.

For `listen_address`, I'd rather keep it that way, so that the default value is safe (everybody doesn't have an IPv6 stack) but the config file still works for most people and shows that multiple IP addresses can be specified.

Thanks!
