### ISSUE TITLE
Should I convert 0.0.0.0 cloaking list to blocklist?

### ISSUE THREAD

**Issue by black-ish** [DNSCrypt/dnscrypt-proxy#1581]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [X ] Other

## Description

Hello,
So I had an old list of a hosts file converted to cloaking and at one point I wondered since they all resolve to 0.0.0.0 should I convert that to the normal blocklist? Should I?

Thank you for reading my rather miniscule question.
And thank you for creating this nice piece of software!

**Comment by jedisct1** [comment]
If the purpose of that list is to block names, yes, it should absolutely be in the block list, not in the cloaking list.

Returning `0.0.0.0` doesn't block a response. On Linux and possibly others, `0.0.0.0` is a valid IP address and an alias for your local machine. Plus, you won't be proper logging information.

The `generate-domains-blocklist` script can parse a bunch of formats, including `hosts` files with `127.0.0.1` or `0.0.0.0` and convert them to optimized block lists. So maybe this is something you could use, too.

**Comment by black-ish** [comment]
That's the kind of answer I was looking for, thank you very much.
