### ISSUE TITLE
Oblivious DoH

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [DNSCrypt/dnscrypt-proxy#1582]
## Is your feature request related to a problem?

IETF published an extension to DoH, which allow hiding client IP address via proxying encrypted DNS transactions.

## Describe the solution you'd like

dnscrypt-proxy should accept ODoH as well from resolver list file or configuration file, which could encoding an ODoH service using similar `sdns` stamps, fetching ODoH as another DoH service, and do querying as the way specified by IETF draft.

## Who will that feature be useful to?

Anyone who know a server that running ODoH service, and want to use that via dnscrypt-proxy to gain pravacy.

## Additional context

See the draft: https://tools.ietf.org/html/draft-pauly-dprive-oblivious-doh-03

**Comment by welwood08** [comment]
As mentioned in #1544, Cloudflare have offered to contribute this support to `dnscrypt-proxy`. Since the IETF link you provided still shows this is a draft standard there is no rush.
