### ISSUE TITLE
'edns_client_subnet' option and a new networks (IP address).

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1583]
Hello.

There is a new `edns_client_subnet` option with two default IP address (IPv4 and IPv6), added in DNSCrypt-Proxy v2.0.45 Release. Description says, that: "_Multiple networks can be listed; they will be randomly chosen. These networks don't have to match your actual networks_".

I would like to ask a very naive question: can User add e.g. `0.0.0.0/8` (reserved for self-identification), `172.16.0.0/12` (reserved for Private-Use Networks) address and so on, or it's a bad idea because of a nature of such IPs?

If it's not possible or recommended, what about - for example: `111.222.333.0/23` address etc.? (Here is more accurate example: `64.68.90.1/24`. It's one of the Google public address).

By the way: if IPv6 Protocol is not in use and is disabled, can `"2001:db8::/32"` address be removed from `edns_client_subnet` option?

Thanks, best regards.

**Comment by jedisct1** [comment]
Hi!

You can use whatever you want here, including `0.0.0.0/8` or a private network. Your settings will be sent to upstream resolvers, that can do whatever they want with this information.

They may not do what you expect, though. Unless that recently changed, Cisco ignores it and will always send the real network address. Others may interpret `0.0.0.0/8` as "don't forward ECS" or fall back to the actual address.

`2001:db8::/32` is just an example, not something that really makes sense in an actual configuration. If you don't have IPv6 connectivity, it's probably better to not include IPv6 addresses here.

**Comment by ghost** [comment]
Hello.

Thank You for an answer and I apologize for such a long time without my answer. I'd studied, almost all ["RFC 7871 Client Subnet in DNS Queries".
](https://tools.ietf.org/rfcmarkup?doc=7871)

Mentioned document contains many important informations etc. (Please check - for example - ["11.  Security Considerations"](https://tools.ietf.org/html/rfc7871#section-11) and especially **_11.1 Privacy_** section. There is an interesting infromation: "_Users who wish their full IP address to be hidden need to configure their client software, if possible, to include an ECS option specifying the wildcard address (i.e., a SOURCE PREFIX-LENGTH of 0)._" So, is it possible to use wildcard address  in **edns_client_subnet** option?

Also, because ECS adds an information to the DNS query tuple, there is a possibility to implement e.g. **Birthday Attacks** (please check already mentioned **_11.1 Privacy_** section). 

So, **jedisct1** what is your opinion on **edns_client_subnet** option? Are You using this option? If yes, do You use a default value (for both IPv{4,6} address if You use both protocols, of course) or do You add some other address? 

Anyway: is it a good idea to use **edns_client_subnet** option (with all the informations available in "**RFC 7871 Client Subnet in DNS Queries**"?

Thanks, best reagards.

**Comment by jedisct1** [comment]
> Are You using this option?

No.
