### ISSUE TITLE
No logging to declared file after dropping priviliges

### ISSUE THREAD

**Issue by Nepherte** [DNSCrypt/dnscrypt-proxy#1585]
**What doesn't work**
When using a log file in conjuction with dropping priviliges, the log file is no longer updated after dropping priviliges. This worked in 2.0.44 but no more in 2.0.45.

**Steps to reproduce**
Use the default config file with following modifications:
- user_name = 'nobody' # uncomment from the default
- log_file = 'dnscrypt-proxy.log' # uncomment from the default

Note: Dropping privileges while using syslog works (ie. the logs appear in syslog), using the log file without dropping privileges also works.

**Comment by jedisct1** [comment]
On your unknown operating system, does the `nobody` user have write access to the log file and the directory it is in?

**Comment by Nepherte** [comment]
Point taken: I'm using Raspberry Pi OS aka Raspbian 10.

The directory with its username and permissions:
drwxrwxr-t 3 nobody nogroup 4096 Jan 17 23:36 dnscrypt-proxy

dnscrypt proxy succesfully runs as user nobody, creates the various files as nobody:nogroup (except for the log file):
-rw-r--r-- 1 root   root        165 Jan 18 00:58 dnscrypt-proxy.log
-rw-r--r-- 1 nobody nogroup   72991 Jan 18 00:58 public-resolvers.md
-rw-r--r-- 1 nobody nogroup     307 Jan 18 00:58 public-resolvers.md.minisig
-rw-r--r-- 1 nobody nogroup    5655 Jan 18 00:58 relays.md
-rw-r--r-- 1 nobody nogroup     297 Jan 18 00:58 relays.md.minisig

Changing the log file's user:group to nobody:nogroup after it's created, doesn't make a difference. Same thing with widening the file permissions.

Contents of the created log file:
[2021-01-18 00:58:54] [NOTICE] dnscrypt-proxy 2.0.45
[2021-01-18 00:58:54] [NOTICE] Network connectivity detected
[2021-01-18 00:58:54] [NOTICE] Dropping privileges

In the above I would expect to see entries about which resolvers are used, latency info, etc.

(Reverting back to 2.0.44 and the info appears in the logs again.)

**Comment by black-cerberon** [comment]
Same problem was solved by remove log files and restart dnscrypt-proxy.

**Comment by Nepherte** [comment]
Unfortunately, I've tried that already. If I delete the log file and restart dnscrypt-proxy, it just recreates the log file as root.

I can't spot any issues with my file permissions and user:group ownerships. Did I miss something?

**Comment by black-cerberon** [comment]
@Nepherte your log directory must be owned by `nobody` user or someone else which you set in config.

**Comment by Nepherte** [comment]
@black-cerberon Appreciate the help. The directory in which the log resides, is dnscrypt-proxy and is owned by nobody:nogroup as mentioned in an earlier post.

**Comment by jedisct1** [comment]
Yup, this is a regression introduced in 2.0.45. This has been fixed.

Thanks!
