### ISSUE TITLE
www.dnscrypt.org/dnscrypt-resolvers.html page fails to display any resolver details

### ISSUE THREAD

**Issue by craSH** [DNSCrypt/dnscrypt-proxy#1587]
## *Who* is the bug affecting?

Public users of the https://www.dnscrypt.org/dnscrypt-resolvers.html web page

## *What* is affected by this bug?

The web page is referencing an old github URL which no longer exists to display the list of dnscrypt supporting public resolvers.

## *When* does this occur?

100% of the time

## *Where* does it happen?

From the perspective of a user's browser.

## *How* do we replicate the issue?

Visit https://www.dnscrypt.org/dnscrypt-resolvers.html
Note there is an error loading the content. Inspect the page source, and note the page being accessed from github is https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-resolvers.csv - this no longer exists.

## Expected behavior (i.e. solution)

Replace the above raw.github.com URL with the new one, which I believe should be something from https://github.com/DNSCrypt/dnscrypt-resolvers but the formats appear to have changed, so I'll leave the implementation specifics to someone who's familiar with those changes.

## Other Comments

Thanks ;)

**Comment by jedisct1** [comment]
The official website is https://dnscrypt.info

The one you mentioned is a fake one designed to spam search engines and promote some shady casino services.

**Comment by craSH** [comment]
Yikes, sorry to hear that. For your information, the .org domain is referenced in the IEEE Press/Wiley book “DNS Security Management”, page 168.

Have you sent a takedown request to the hosting provider?

**Comment by jedisct1** [comment]
Unfortunately, I don't have high hopes that the hosting provider would do anything.

**Comment by craSH** [comment]
Understood. I've reported it to a takedown service that I have access to, perhaps it will be acted on - no promises.

**Comment by jedisct1** [comment]
Awesome, thank you for that!
