### ISSUE TITLE
confusing handling of [::]

### ISSUE THREAD

**Issue by csamsel** [DNSCrypt/dnscrypt-proxy#1588]
Hi,

## Is your feature request related to a problem?
i just have setup dnscrypt-proxy. I wanted it to listen on all ipv4 and ipv6 interfaces.
Based on https://github.com/DNSCrypt/dnscrypt-proxy/blob/213695f651e3f0145ff5c74ef8cc2b653943a327/dnscrypt-proxy/example-dnscrypt-proxy.toml#L37 and my limited networking knowledge i tried the following first:

`listen_addresses = ['0.0.0.0:53', '[::]:53']`

As it turned out, [::]:53 includes 0.0.0.0:53 so dnscrypt-proxy failed to start with address already in used, because it tried to bind twice.
Took me a while to figure that out, as i thought something went wrong with changing the port of dnsmasq.

## Describe the solution you'd like
I suggest that `[::]:53` specificly binds to IPv6 only.

## Alternatives you've considered
changing the documentation would help, too. But maybe somewant wants to only bind to IPv6.

## Who will that feature be useful to?

People having a working ipv6 config?

## Context
System is a Gentoo Linux with kernel 5.4.80-gentoo-r1-x86_64, but i assume this affects all modern Linux's

**Comment by jedisct1** [comment]
<img width="573" alt="Screen Shot 2021-01-20 at 19 49 48" src="https://user-images.githubusercontent.com/124872/105220889-a8ab9980-5b58-11eb-9d87-0f3628597d10.png">

<img width="210" alt="Screen Shot 2021-01-20 at 19 50 00" src="https://user-images.githubusercontent.com/124872/105220912-b06b3e00-5b58-11eb-84af-1747417b6166.png">

<img width="169" alt="Screen Shot 2021-01-20 at 19 50 22" src="https://user-images.githubusercontent.com/124872/105220962-c1b44a80-5b58-11eb-9751-b0cf3b96c997.png">

**Comment by csamsel** [comment]
@jedisct1 Are you trying to say something with your post?

**Comment by jedisct1** [comment]
Thought it was a typo, sorry.

Listening to `::` seems to mean listening to both the IPv4 and IPv6 address spaces: https://github.com/golang/go/blob/master/src/net/ipsock_posix.go#L164-L167

Looks confusing indeed. I must confess that I've never used this, but the comment here seems to imply that this is the expected behavior for `::`? I'm not even sure that the behavior can be changed, do you know?

**Comment by csamsel** [comment]
Ah no worries.

Yes it's confusing, it seems by default `[::1]` refers to ipv6 localhost, whereas `[::]` refers to all adresses (both ipv4 and ipv6). I'm not sure if other users would be aware of this.

I dont know anything about go, but low level (in C that is) it's possible explictly configure a socket as IPv6 only via socket option `IPV6_V6ONLY`.

Looking a bit around the interwebs, this seems to be a quiet general problem, see for example: https://serverfault.com/questions/408667/how-do-i-disable-ipv4-mapped-ipv6

**Comment by jedisct1** [comment]
In Go, using `tcp6` and `udp6` as the protocol appears to be the way to bind only IPv6.

But I'm not sure that this is a good idea to introduce a breaking change which also doesn't seem to match what `::` is supposed to do.

Maybe we should rather clarify what `0.0.0.0` and `::` do in the documentation and examples in order to avoid confusion.

**Comment by csamsel** [comment]
That is reasonable. Because this is globally inconsistent, people more experienced then me might expect it to work exactly like that. In case someone has the requirement to bind exactly to all IPv6 interfaces it is still possible to change the kernel behavior as described in the stackoverflow article.

**Comment by black-cerberon** [comment]
You can use `listen_addresses = [':53']`

**Comment by csamsel** [comment]
I figured it out. The problem was, that how the example is layed out, i thought i should use `['0.0.0.0:53', '[::]:53']`. Maybe stating in the example that it's best to use `listen_addresses = [':53']` to listen on all interfaces would  help already.
