### ISSUE TITLE
[Android] How to install/run?

### ISSUE THREAD

**Issue by HI54U** [DNSCrypt/dnscrypt-proxy#159]
System: Android LOS 7.1.2 latest, amd64 compiled, root, Afwall+ (on/off) moved the folder dnscrypt-proxy to data/local/tmp, all files 777 privileges

I encountered the following error while starting it with ./dnscrypt-proxy:
[FATAL] listen udp 127.0.0.1:5353: bind: address already in use

I changed the standard configuration file:

listen_addresses = ['127.0.0.1:53', '[::1]:53']
to
listen_addresses = ['127.0.0.1:5353', '127.0.0.1:5353']

require_dnssec = false
to
require_dnssec = true

fallback_resolver = '9.9.9.9:53'
to 
fallback_resolver = '9.9.9.9:5353'

How can I fix this and run dnscrypt-proxy permantly?

**Comment by jedisct1** [comment]
Maybe the discussion should continue where it started: https://github.com/jedisct1/dnscrypt-proxy/issues/41

**Comment by jedisct1** [comment]
```
fallback_resolver = '9.9.9.9:53'
to
fallback_resolver = '9.9.9.9:5353'
```

I wouldn't change that, though.

And for the first one, port 5353 may be already used by something else on Android.
