### ISSUE TITLE
Certificate Hash Invalid of Adguard-DNS-DOH

### ISSUE THREAD

**Issue by thomasjcf21** [DNSCrypt/dnscrypt-proxy#1590]
The certificate hash of adguard-dns-doh is reporting invalid, please see the below entry from starting it :(

`[2021-01-21 14:14:32] [ERROR] Certificate hash [f9ff37f02e632cb7387025c07e57908a3d371b7c95d8cdd0390de231ed943a12] not found for [adguard-dns-doh]
[2021-01-21 14:14:32] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable`

**Comment by jedisct1** [comment]
Thank you!
