### ISSUE TITLE
Sources tests are failing

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#1591]
Looks like the sources tests are now failing: https://github.com/DNSCrypt/dnscrypt-proxy/runs/1742240545

I think some of that was due to relay randomization, but the rest may have been caused by the recent changes to keep updated lists in memory.

Do you have more insights on what's happening @ianbashford @welwood08 ?

**Comment by ianbashford** [comment]
Well I've rolled back until it worked, and it looks to me like the 'Randomize source URLs' commit
https://github.com/DNSCrypt/dnscrypt-proxy/runs/1644671629   

I'll try and understand what's up....

**Comment by ianbashford** [comment]
Could it be that the 'equals' is seeing the different order or elements as 'not equal' ?

https://github.com/DNSCrypt/dnscrypt-proxy/runs/1644671629  lines 97 & 98 are not the same as lines 127 & 128 (different order)

`urls: ([]*url.URL) (len=2) {

                (*url.URL)(http://127.0.0.1:43877/7/minimal_relay.md),
                (*url.URL)(http://127.0.0.1:43877/0/minimal_relay.md)
              }`

`urls: ([]*url.URL) (len=2) {

                (*url.URL)(http://127.0.0.1:43877/0/minimal_relay.md),
                (*url.URL)(http://127.0.0.1:43877/7/minimal_relay.md)
              },`

**Comment by ianbashford** [comment]
ProtoBufs equals:

// Lists are equal if each element value is also equal.

**Comment by ianbashford** [comment]
What about if you turn these lists into maps to do the comparison

"// Maps are equal if they have the same set of keys, where the pair of values
// for each key is also equal."

Oh -- or run a sort on them first I guest...

**Comment by jedisct1** [comment]
Didn't https://github.com/DNSCrypt/dnscrypt-proxy/commit/a76ffb01438463aa5e14509983bca06385162f13 address the randomization issue?

Looks like in other tests, some sources are missing instead of not being in the right order?

**Comment by ianbashford** [comment]
I hadn't pulled in that commit. Let me do that an continue.

**Comment by lifenjoiner** [comment]
I think I got how the error happens.

First:
![shuffle_issue_in_tests](https://user-images.githubusercontent.com/19585474/105488461-99f5eb80-5cec-11eb-9492-c28ad2c62918.png)
The directory part of path indicates the `state`.
https://github.com/DNSCrypt/dnscrypt-proxy/blob/0ab9e30fa9a7479e46f90bfdd0b6ce49119d1560/dnscrypt-proxy/sources_test.go#L33-L45

Then, let's take an example:
The error:
```
    --- FAIL: TestNewSource/cache_missing,_download_missing-sig,correct/10-1 (0.01s)
        sources_test.go:231: Unexpected HTTP request log
            Checker:  DeepEqual
            Expected: (map[string]uint) (len=4) {
              (string) (len=11) "/0/empty.md": (uint) 1,
              (string) (len=19) "/0/empty.md.minisig": (uint) 1,
              (string) (len=11) "/5/empty.md": (uint) 1,
              (string) (len=19) "/5/empty.md.minisig": (uint) 1
            }
            Actual:   (map[string]uint) (len=2) {
              (string) (len=11) "/0/empty.md": (uint) 1,
              (string) (len=19) "/0/empty.md.minisig": (uint) 1
            }
```
And the inputs:
```
id: 10-1, e.urls: [http://127.0.0.1:63635/5/empty.md http://127.0.0.1:63635/0/empty.md]
Before Shuffle source.urls: [http://127.0.0.1:63635/5/empty.md http://127.0.0.1:63635/0/empty.md]
After Shuffle source.urls: [http://127.0.0.1:63635/0/empty.md http://127.0.0.1:63635/5/empty.md]
```

Finally, you get it. The error occurs when a `0` leading path is shuffled to the 1st, which means `TestStateCorrect` and **leads to an end**!

**Comment by lifenjoiner** [comment]
Got the current failure:
```
 [2021-01-22 13:51:34]	127.0.0.1	tracker.xdebian.org	tracker.*
*** Test #51 FAILED ***
```
![test-51-failure](https://user-images.githubusercontent.com/19585474/105502270-3f668a80-5d00-11eb-93a3-baf4919f8fc7.png)

Is it caused by https://github.com/DNSCrypt/dnscrypt-proxy/commit/ac0b9cdfe847041a8fd22f0c50a67afb8566c65d?

**Comment by ianbashford** [comment]
So glad you got it -- that was baking my noodle last night...  
I saw it leaving in the debugger, but hadn't grok'd that was what was happening.   Good learning session though :-) 
And thanks for posting the full solution
