### ISSUE TITLE
EDNS Client Subnet useless feature?

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-proxy#1592]
With dig test DNS server return same IPs for different location. 

_Boston, US_
```
$ dig +short youtube.com @1.1.1.1 +subnet=68.66.112.0/20
173.194.73.93
173.194.73.91
173.194.73.136
173.194.73.190
```

_São Paulo, BR_
```
$ dig +short youtube.com @1.1.1.1 +subnet=54.240.16.0/21
173.194.73.136
173.194.73.91
173.194.73.93
173.194.73.190
```

_Frankfurt, DE_
```
$ dig +short youtube.com @1.1.1.1 +subnet=54.93.128.0/17
173.194.73.190
173.194.73.136
173.194.73.91
173.194.73.93
```

_Tokyo, JP_
```
$ dig +short youtube.com @1.1.1.1 +subnet=176.32.64.0/19
173.194.73.91
173.194.73.93
173.194.73.136
173.194.73.190
```

 It must return differnt IP for different location, right?

**Comment by jedisct1** [comment]
You're using Cloudflare. Cloudflare intentionally doesn't support EDNS Client Subnet because [it's bad for privacy](https://00f.net/2013/08/07/edns-client-subnet/) and they have enough POPs all over the world to make this information useless.

Try with Google `8.8.8.8` instead.
