### ISSUE TITLE
Reading System Logs While Running as Background Service 

### ISSUE THREAD

**Issue by emreozcelik** [DNSCrypt/dnscrypt-proxy#1596]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description

Hello there,

I want to read the logs after DNSCrypt is started as a service. I used Task Scheduler in Windows for this. (Not sure if there is a better way. It starts a PowerShell Script.)

The problem is that the first message sent when DNSCrypt starts up is "dnscrypt-proxy 2.0.45". Since Windows uses XPath 1.0, I have to change the following code in every release. In XPath 1.0, we cannot scan through text. **It would be nice if it could deliver a simple message like "Started." as soon as it started.**

```
<QueryList>
  <Query Id="0" Path="Application">
    <Select Path="Application">
    *[System[Provider[@Name='dnscrypt-proxy']]]
    and
    *[EventData[Data='dnscrypt-proxy 2.0.45']]
    </Select>
  </Query>
</QueryList>
```

Simple script:

```
$aidx = (Get-EventLog -LogName Application -Source dnscrypt-proxy -Newest 1).Index

while ($true)
{
  Start-Sleep -Milliseconds  500
  $aidx2  = (Get-EventLog -LogName Application -Source dnscrypt-proxy -Newest 1).Index
  Get-EventLog -LogName Application -Newest ($aidx2 - $aidx) |  sort Index
  $aidx = $aidx2
}
PAUSE
```

If you know better solution, I would appreciate if you could inform me.

**Comment by lifenjoiner** [comment]
>     and
>     *[EventData[Data='dnscrypt-proxy 2.0.45']]
Maybe just remove these to get all logs?

And locate `Network connectivity detected`, the 2nd record of a launch, then the 1st, and then get all of a recent launch.

**Comment by lifenjoiner** [comment]
First, as you use script, get the version is not a problem by `dnscrypt-proxy.exe -version`.

Second, I learnt more about [Get-WinEvent](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-7.1) and [Get-EventLog](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-eventlog?view=powershell-5.1), and found out that the problem for your (@emreozcelik)  purpose to `get the full log records of a recent dnscrypt-proxy launch` is no matter of what the 1st message dnscrypt-proxy logs! Your codes doesn't make sense.

PS, to save all your time:
The key is `Get-WinEvent` and `Get-EventLog` are completely different!
The advantage of `Get-WinEvent` is having `XPATH` expression. But it can't be queried by `Index`! Even if you can locate the 1st startup message, you can't get the index.
For `Get-EventLog`, it's just the opposite! You must test records by index.
So, generally, just `Get-EventLog`  by index recursively and test to locate the most recent '1st message' will work.
Considering WinEvent is deleted on the fly, take a snapshot for all is required.

It's not an issue about `dnscrypt-proxy` at all.

**Comment by emreozcelik** [comment]
The task depends on whether dnscrypt-proxy is running or not. First, the system logs should be checked to see if dnscrypt-proxy has started. To see dnscrypt-proxy in logs, use_syslog setting must be set to true. And if a starting point is not specified, this allows all messages to re-trigger the task. That's the problem. I am solving this problem by checking if the startup message of dnscrypt-proxy is found or not.

Edit: By the way, when I run or stop it manually, I can't see the log in Service Control Manager. So the above method is the only way for me.

> dnscrypt-proxy.exe -version

Thanks, this will work for me. :)

**Comment by lifenjoiner** [comment]
If you insist, there are more unique strings indicates `dnscrypt-proxy` has started: `Network connectivity detected`, `Now listening to 127.0.0.1:53 [UDP]`, `Source [relays] loaded`, `Firefox workaround initialized`, or `Sorted latencies:`.

If you prefer console logs, why not run it as a normal application? If you prefer file logs, why not specify a log file?
