### ISSUE TITLE
About the "sdns://" link

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1597]
I wonder how can  I convert my DNS server into the "sdns://" link?

**Comment by jedisct1** [comment]
Hi!

`encrypted-dns-server` prints it on start. The Docker image prints it after creation. `doh-server` prints it on start, too.

If you are running something else, the easiest way is probably to use the [online DNS stamp calculator](https://dnscrypt.info/stamps/).

Hope this helps!

**Comment by vladns** [comment]
The online calculator has a field "Hashes", how to determine it for this server https://servers.opennic.org/edit.php?srv=ns8.ca.dns.opennic.glue ?
And where can I get the data for the "Host name (vhost + SNI) and optional port number" field and what is the port separator?

**Comment by jedisct1** [comment]
The stamps for that server would be `sdns://AQcAAAAAAAAAEzE5OC4xMDAuMTQ4LjIyNDo0NTMg-I9_7aXj72-YfDvHJRG_Q3zhfU3m33yuKPcfqYpr_VYkMi5kbnNjcnlwdC5jZXJ0LmpvbHRlb24uYm9vdGhsYWJzLm1l` (DNSCrypt) and `sdns://AgcAAAAAAAAADDE1OC42OS41My43MyAyhv9lpl-vMghe6hOIw3OLp-N4c8kGzOPEootMwqWJiBBkb2guYm9vdGhsYWJzLm1lCi9kbnMtcXVlcnk` (for DoH).

But none of these work. On that server, only queries over unauthenticated DNS get a response.

**Comment by vladns** [comment]
Okay. Then tell me how can I get this data using a calculator? That was my question.

**Comment by jedisct1** [comment]
> The online calculator has a field "Hashes", how to determine it

This is only for DoH. See https://github.com/jedisct1/doh-server#dns-stamp-and-certificate-hashes

> And where can I get the data for the "Host name (vhost + SNI) and optional port number

The DNS operator chooses these parameters. They can be anything :)

>  what is the port separator?

It's `:`. In the online calculator, you can paste existing stamps to see the information they contain.

**Comment by vladns** [comment]
According to the link you provided, to get "Hashes" you need to configure the [static] section. To configure the [static] section, you need to know "Hashes", do I understand correctly?

**Comment by jedisct1** [comment]
I would just try and see what happens.
