### ISSUE TITLE
ISSUE (beta 6) - Blocking logs are empty

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#16]
Now I've changed absolutely ALL double quotes " to single quotes ' in my *.toml config, same as in your config file.

**Questions:**

1) Didn't change servers of my choice to your example `'scaleway-fr'` yet.
   And left my `server_names =` parameter active as it was for some time.

 -- Can I use parameters and syntax, like in previous betas? Or you recommend change `[servers]` parameters to the new format? How I can use it?
 -- Don't understand parameter `stamp =`
 -- Why I don't see `'scaleway-fr'` server in the `dnscrypt-resolvers.csv` ?

2) How I can play with `prefix = ''` parameter? What does it mean? How to use it?

**ISSUE (beta 6) - Blocking logs are empty (blocking still doesn't work?)**

Deleted all logs. After service has been started, all logs-files was created (except `nx.log`), and all of them are empty. After some long time I've found some new lines in main DNS.log (Stuck again?)
Then I've cleared DNS.log again, but nothing new was appeared.

(For the test I opening different web-pages intensivly and running software I want restrict access to some domains). My logs are empty.

Olny `dnscrypt-proxy.log` (Connections) always works perfect...

**Comment by jedisct1** [comment]
I don't know what `DNS.log` is. Is that the query log?

If you delete it, you need to restart the service.

**Comment by iWARR** [comment]
> query log?

 Yes

**Comment by jedisct1** [comment]
So, yes, you need to restart the service after you delete the file.

And make sure that your queries are actually going to the proxy.

The best way to check is to use a dns client, not a web browser that has its own cache (plus, you apparently have another one).

**Comment by iWARR** [comment]
> you need to restart the service after you delete the file.

You are right. Just tired. and forgot. Basicly I'm doing that often.
Restarted service and query log now looks healthy again.
But `'blocked.log'` show me that only 3 my rules works.

I think about this: May be v2 really take take into account my HOSTS entries?
I'll try delete `hosts` file, reboot PC and will test some time.

**Comment by iWARR** [comment]
No. Nothing changed with `'blocked.log'`
After 2 reboots - only same 3 rules (random from beta to beta?) continue  working, since my last messege to you,.. Some kind of stuck every time with blocking...

And no any reaction on our test site https://technet.microsoft.com
No any `*social.microsoft*` , no any `*vortex.data.*` in log.
No reaction on software with DNS-blocking in dnscrypt-proxy...

`'query.log'` seems Ok, I think (~like in v1).

**Comment by iWARR** [comment]
And another one. 

> So, yes, you need to restart the service after you delete the file.

I remember that everything I'm done right. Look;

1) Before update to new beta I stop & uninsall service
2) Delete all log-files completely.
3) Prepear new beta pack for the launch
4) Install & Start new beta

Result - empty logs. Until your advise make RESTART service.
So, I did that test in the right way? Take into account this situation too.

**Comment by jedisct1** [comment]
I don't understand what this issue is about, sorry.

**Comment by jedisct1** [comment]
Next beta will probably include something like v1's `hostip` tool. That will make it easier to diagnose issues by directly sending queries to the proxy.

**Comment by iWARR** [comment]
May be this trouble comes from memory isolation problem, known as Meltdown & Spectre (CPU vulnerability)? I have this patches (updates) installed in Windows. Intel says that in case of Spectre many kind of software have to adopt their code. Otherwise it may not work...

I'm also don't know what to think...

**Comment by iWARR** [comment]
> The best way to check is to use a dns client

> Next beta will probably include something like v1's `hostip` tool.

I see. Would `hostip` tool be enough to diagnose issues? Or DNS client would be useful also?
What kind of DNS client you can recommend for me (on Windows)?

**Comment by jedisct1** [comment]
hostip is enough. Use it to send queries to 127.0.0.1

**Comment by elmakong** [comment]
hostip from v1 is good enough..but i am expecting improved tool for v2.
PS: usage for hostip v1 is: hostip -r ip.of.dns.server domain.to.be.checked
cmiiw

**Comment by jedisct1** [comment]
@elmakong Have you tried `dnscrypt-proxy -resolve` ?

**Comment by elmakong** [comment]
@jedisct1 well, thats new..havent noticed, but just tried.nice feature!
