### ISSUE TITLE
Mac install commands not working

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [DNSCrypt/dnscrypt-proxy#160]
I downloaded and unpacked **[dnscrypt-proxy-macos-2.0.1.tar.gz](https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.2/dnscrypt-proxy-macos-2.0.2.tar.gz)**.

I renamed the folder DNSCrypt and placed it in the Application Support folder.
The path to the executable is sudo /Users/xxx/Library/Application\ Support/DNSCrypt/dnscrypt-proxy

But Terminal returns **[2018-02-20 23:03:21] [FATAL] open dnscrypt-proxy.toml: no such file or directory**

There _is_ an **example-dnscrypt-proxy.toml** file inside the folder.

NOTICE that the [Mac instructions](https://github.com/jedisct1/dnscrypt-proxy/wiki/installation#installing-dnscrypt-proxy-on-macos-as-a-system-service) provided say 

> Start dnscrypt-proxy and install as a service by opening Terminal type:
sudo /User/YourUserName/Dnscrypt/dnscrypt-proxy start

All 3 commands have typos since the path is /users/ - **PLURAL**.
But I used the plural path and it still fails (also tried the singular path).

> Extract the tar.gz move it to a location you would like to put it in. You can also rename the folder.
Example: Put it in the home directory and rename the folder to Dnscrypt. It will look like this for the Terminal /User/YourUserName/Dnscrypt

Start dnscrypt-proxy and install as a service by opening Terminal type:
sudo /User/YourUserName/Dnscrypt/dnscrypt-proxy start

sudo /User/YourUserName/Dnscrypt/Dnscrypt/dnscrypt-proxy -service install

sudo /User/YourUserName/Dnscrypt/Dnscrypt/dnscrypt-proxy -service start

**Comment by evilvibes** [comment]
Thanks good eye all been fixed

**Comment by GitTheHellOutaHere** [comment]
Okay, but that doesn’t explain the Terminal error.

Where is dnscrypt-proxy.toml?

**Comment by evilvibes** [comment]
Bro you have to stop editing so people can help you. We answer what you say first then you edit it and it looks like we didn't.

Go to the DNSCrypt folder you made and change the `example-dnscrypt-proxy.toml` to `dnscrypt-proxy.toml`

**Comment by GitTheHellOutaHere** [comment]
Sorry, sometimes after posting I notice I omitted something or it would help to add or change something.

**Comment by evilvibes** [comment]
It's all good it's just it will turn into a post editing battle lol

**Comment by GitTheHellOutaHere** [comment]
SUCCESS!

Now, without a menu item how do I access/control it?

**Comment by evilvibes** [comment]
You edit the `dnscrypt-proxy.toml`

**Comment by GitTheHellOutaHere** [comment]
Yah, no - not my _thang_.
If I have to tweak it manually I probably won’t use it.

I _have_ edited Tor’s config file, but generally don’t like to mess with 'em.

**Comment by GitTheHellOutaHere** [comment]
I spoke too soon - (SUCCESS!).

After uninstalling the macos client and rebooting, I couldn’t get online. Had to allow the default DNS servers to replace the 127.0.0.1 address I’d entered.

The system keeps adding Google’s servers and I’m able to connect again.
Each time I change 'em back to 127.0.0.1 I get kicked offline.

Rebooted three times already.

Also there’s no sign of dnscrypt in Activity Monitor now, should there be if it’s running?


Will dnscrypt-proxy run correctly with the default .toml file or does it require user customization to work at all? If that’s the case I’ll be uninstalling it.

**Comment by evilvibes** [comment]
Did you install it as a service and start it? 

`-service install`

`-service start`

**Comment by GitTheHellOutaHere** [comment]
I ran all 3 commands as instructed:

sudo /Users/xxx/Library/Application\ Support/DNSCrypt/dnscrypt-proxy start

sudo /Users/xxx/Library/Application\ Support/DNSCrypt/dnscrypt-proxy install

sudo /Users/xxx/Library/Application\ Support/DNSCrypt/dnscrypt-proxy start

**Comment by evilvibes** [comment]
`sudo /Users/xxx/Library/Application\ Support/DNSCrypt/dnscrypt-proxy start`

`sudo /Users/xxx/Library/Application\ Support/DNSCrypt/dnscrypt-proxy -service install`

`sudo /Users/xxx/Library/Application\ Support/DNSCrypt/dnscrypt-proxy -service start`

Also to check the status

`sudo /Users/xxx/Library/Application\ Support/DNSCrypt/dnscrypt-proxy status`

**Comment by GitTheHellOutaHere** [comment]
Were those the instructions provided or did you just edit them to add the -service part?

I don’t remember seeing that but it’s possible I accidentally deleted it when changing the paths.

Anyway, I’ve now installed and started the service and it’s working with 127.0.0.1 in place.

Thanks a lot!

But as to my previous question, is tweaking necessary or will it work just fine with the default servers?

Seems to be working.

 scutil --dns | grep 'nameserver\[[0-9]*\]'
  nameserver[0] : 127.0.0.1
  nameserver[0] : 127.0.0.1
  nameserver[0] : 127.0.0.54

**Comment by evilvibes** [comment]
They were always there. 

`But as to my previous question, is tweaking necessary or will it work just fine with the default servers?`

It will work fine it's up to you if you want to edit things or not.

**Comment by GitTheHellOutaHere** [comment]
BTW, is this a known issue and it’s not signed because the dev. isn’t a registered Apple developer?

> “dnscrypt-proxy” has no code signature. The executable can be maliciously modified without being detected.

I keep getting those alerts in Little Snitch.

**Comment by jedisct1** [comment]
I don't know how to do it with Travis, and most macOS users are going to install this using Homebrew anyway.
