### ISSUE TITLE
2.0.45 only wrote limited log with "log_level=0" verbosity

### ISSUE THREAD

**Issue by CampionLoong** [DNSCrypt/dnscrypt-proxy#1600]
## *Where* does it happen?

Similarly running on DD-WRT as previous tickets, trying the native 2.0.45 Linux ARM binary on a Netgear router with Broadcom BCM4709A0 CPU.

With 2.0.44, at "log_level=2" (from [Entware repo](http://bin.entware.net/armv7sf-k3.2/dnscrypt-proxy2_nohf_2.0.44-1_armv7-3.2.ipk)), dnscrypt-proxy wrote detailed log with server timing, anonymized routes, lists loading etc.

With the official 2.0.45 Linux ARM (from here), the main log only shows 3 lines of info even at "log_level=0":

    [2021-01-27 19:38:52] [NOTICE] dnscrypt-proxy 2.0.45
    [2021-01-27 19:38:53] [NOTICE] Network connectivity detected
    [2021-01-27 19:38:53] [NOTICE] Dropping privileges

All other logs, query, blocklists are as expected. Folder permissions are as in 2.0.44 (suppossedly correct).

One thing to note is query/blocklist/whitelist logs are written using the Dropped privileges. The main log is written as root (as it has always been). Is there any chance dnscrypt-proxy cannot write back to the main log after dropping privileges?

**Comment by jedisct1** [comment]
That was fixed in d0f981156b694742b99bd714353f49b6ddbcbfc5 , so application logs will be written when privileged are dropped in the next version :)

**Comment by CampionLoong** [comment]
Great, thanks! Please cut a release soon :)
