### ISSUE TITLE
Stupid security question

### ISSUE THREAD

**Issue by asakura42** [DNSCrypt/dnscrypt-proxy#1601]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [x] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description

I am interested in the security and anonymity of the protocol itself. As I know, an unfair DNS hoster can spoof any page with a phishing one. Is this possible when using DNSCrypt? My settings:

dnscrypt_servers = true
doh_servers = false
require_dnssec = true
require_nolog = true
require_nofilter = true
disabled_server_names = [ 'cloudflare' ]

Other kept unchanged.

**Comment by jedisct1** [comment]
I had to look what "DNS hoster" means; apparently it is a company operating authoritative DNS servers.

If such company changes records for a domain it is authoritative for, no protocol can help, not even a VPN.

This happens all the time when registrar accounts get compromised. And DNSSEC is completely useless here.
The only mitigation would be pinning DNSSEC KSKs, but no one does.

So, effectively, DNS hosters have all the rights on the domains they host.
