### ISSUE TITLE
Fast installation problem,linux intelx64.fedora.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [DNSCrypt/dnscrypt-proxy#1603]
Fast installation problem,linux intelx64.fedora.How to clear address 0.0.0.0 that is listening to my port 53?
* [ ] Other

## Description
I read the guide and followed but I cannot seems to remove the stuff that is currently listening to my port 53,thus failing to run the dns.

the guide say check the port status right?so,
 ss -lp 'sport = :domain'
Netid State   Recv-Q  Send-Q   Local Address:Port     Peer Address:Port Process 
udp   UNCONN  0       0        127.0.0.53%lo:domain        0.0.0.0:*            
tcp   LISTEN  0       4096     127.0.0.53%lo:domain        0.0.0.0:*           

> But I have no idea how to remove them,thus,
>  ./dnscrypt-proxy
> [2021-01-29 03:19:40] [NOTICE] dnscrypt-proxy 2.0.45
> [2021-01-29 03:19:40] [NOTICE] Network connectivity detected
> [2021-01-29 03:19:40] [FATAL] listen udp 127.0.0.1:53: bind: permission denied
> 

Anyone have experience about how to remove this?This does not seems to be like an app in the example guide.
Thank you very much.

**Comment by jedisct1** [comment]
`listen udp 127.0.0.1:53: bind: permission denied`

https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux#troubleshooting

This means that you need to be `root` in order to start it.
