### ISSUE TITLE
The mybase public blacklist seems to be corrupted

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1604]
[Index of /blacklists/domains](https://download.dnscrypt.info/blacklists/domains/) shows `mybase.txt   29-Jan-2021 00:34   67029406`
67029406 bytes is more than 6 times its usual size ...

**Comment by jedisct1** [comment]
Ouch, this is due to the `dbl.oisd.nl` list that went insane.

I'm going to remove it.

Thanks!

**Comment by jedisct1** [comment]
Should be better now!

Thank you!
