### ISSUE TITLE
which anonymizing relay is used when a dns server has multiple relays? 

### ISSUE THREAD

**Issue by dim-geo** [DNSCrypt/dnscrypt-proxy#1607]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [x] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description

Which anonymizing relay is used when a dns server has multiple relays defined? 
What is the algorithm selecting relays to use? round-robin? first until failover? latency between client-relay? dns query time?
How are multiple relays are impacting server selection strategy p2/ph?
Wiki seems not to explain that detail.

**Comment by jedisct1** [comment]
If the relay set is a wildcard, the relay is randomly chosen among the ones with the smallest common network suffix shared with the server IP address

If this is an explicit set, a random relay from the set is selected.
