### ISSUE TITLE
dnscrypt-proxy.service fails with 31/SYS status

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1608]
`dnscrypt-proxy.service` exits abnormally while browsing. `journald` shows the following error even at `log_level=0`

```
dnscrypt-proxy.service: Main process exited, code=killed, status=31/SYS
dnscrypt-proxy.service: Failed with result 'signal'.
```

I disabled the adblock lists I have enabled to resolve this issue but that isn't a solution for me.

## *What* is affected by this bug?

The system DNS stops working as the `dnscrypt-proxy.service` exits with error.

## *When* does this occur?

When adblock lists are enabled and when opening certain websites like Spotify or GitHub or just web browsing in general.

The following adblock lists were enabled:

- [Steven Black Fake News + Gambling](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts)
- [OISD Basic](https://dbl.oisd.nl/basic/)

## *Where* does it happen?

On my laptop with Arch Linux. `uname -sr` is `Linux 5.10.13-arch1-1`

## *How* do we replicate the issue?

Enable the adblock lists mentioned above. Try to use websites like GitHub or Spotify.

## Expected behavior (i.e. solution)

`dnscrypt-proxy.service` should keep on working without exiting abnormally.

**Comment by jedisct1** [comment]
Seems to be a duplicate of https://bugs.archlinux.org/task/66817

If there is an issue with the Arch package, and pinpointing it is difficult, uninstall it, try downloading the official package and install it with the generic installation procedure.

**Comment by ghost** [comment]
hmm, not sure what the problem was but I haven't seen this error after reporting this issue. I didn't change anything and re-enabled the adblock list and `dnscrypt-proxy` hasn't been updated in the meantime.

I'll go ahead and close this issue. If it happens again, I'll reopen it.
