### ISSUE TITLE
Remote logging support for query_log and nx_log

### ISSUE THREAD

**Issue by inflatador** [DNSCrypt/dnscrypt-proxy#1609]
## Is your feature request related to a problem?
query_log and nx_log only support logging to a file.

## Describe the solution you'd like
Ability to log to system facility or arbitrary socket file (such as /dev/log)

## Alternatives you've considered
Manually configuring rsyslog to handle dnscrypt-proxy's query_log and nx_log files

## Who will that feature be useful to?
Users with centralized logging requirements

## What have you done already?
Nothing as of yet, my golang skills are weak ;(

## What are you going to contribute?
Testing/documentation. I may even be able to do a PR, but I don't know golang so it might take awhile.

**Comment by jedisct1** [comment]
Hi!

You can already log to pipes and named sockets :)

Sending logs over the network is more of something that should be done with a dedicated tool such as Flowgger.
