### ISSUE TITLE
dnscrypt-proxy and logrotate?

### ISSUE THREAD

**Issue by kanyck** [DNSCrypt/dnscrypt-proxy#161]
dnscrypt-proxy seems not to have a mechanism to reopen log file to be used with logrotate. Is there any solution available at the moment?

**Comment by jedisct1** [comment]
Hi @kanyck !

The server has to be restarted at the moment.

Handling signals in Go look a bit tricky, and a different mechanism is required for Windows users.

So maybe we should just implement a built-in log rotation mechanism, so it works the same way everywhere.
Do you want to do it?

**Comment by kanyck** [comment]
Hi @jedisct1 !
In fact, I quit programming some 20 years ago, so I doubt you'll cope with my coding))) 

So, restarting the service seems to be the only optiion so far. Not a big deal, but certainly ain't as elegant as it should be... I prefer unattended services that "just work". Letting logs to grow infinitely is a bad idea. And duplicating existing system service looks not so attractive to me, either.

As for Windows, the system is one big kludge and I doubt logs are maintained properly there (I just don't know). And yes, there is https://sourceforge.net/projects/logrotatewin/ . Maybe it's reasonable to have a native solution for *nixes  as a "production" solution, and if Win users need it, let them install logrotate for windows.

Thanks!

UPDATE: the signal handling is probably not necessary, some kind of interprocess communication will do the trick. I looked into /etc/logrotate.d and found than a few services actually receive signals. More often you'll find something like 
	

> postrotate
> 		/usr/bin/chronyc cyclelogs
> 	endscript

for chrony, for example.

**Comment by kanyck** [comment]
If interprocess communication can be used for reopen files, it may be coupled with this
 #135

**Comment by jedisct1** [comment]
I still think that having to run a command would be too complicated and not very common on Windows.

Built-in logrotate works the same way everywhere, so this is going to be less painful from a support perspective :)
