### ISSUE TITLE
"not allowed to bind on any interface" for deb package

### ISSUE THREAD

**Issue by zcattacz** [DNSCrypt/dnscrypt-proxy#1610]
Sorry this is a comment to the locked threads #1066 . Hope this can be moved to #1066 as comment. Thank you.

The deb package service files add 

    "User=_dnscrypt-proxy"

to `dnscrypt-proxy.service` file, which cause dnscrypt-proxy to be unable to start with root privilidge then drop to limited user `_dnscrypt-proxy`.
The solution is to comment out above mentioned line from `/lib/systemd/system/dnscrypt-proxy.service` and add `user_name=_dnscrypt-proxy` to `/etc/dnscrypt-proxy/dnscrypt-proxy.toml`

I also comment out `Requires=dnscrypt-proxy.socket`, `Also=dnscrypt-proxy.socket`, since I only need dnscrypt-proxy to listen on local interface. socket wouldn't be necessary.
This sadly still applys to dnscrypt-proxy 2.0.19 in debian10. 
Hope this info can help users using similar setup.

**Comment by jedisct1** [comment]
No one should use a version that old, really.

**Comment by zcattacz** [comment]
But that's the latest I can find in distro's stable repo.

**Comment by jedisct1** [comment]
It is completely unsupported, even for security issues.
