### ISSUE TITLE
How do I only allow specific domains?

### ISSUE THREAD

**Issue by vladns** [DNSCrypt/dnscrypt-proxy#1611]
Is it possible to allow certain domains such as ".lib"? This can be done in dnsmasq:
`server=/.lib/172.104.136.243`
But in this case, the traffic can be intercepted. Can this be done using dnscrypt-proxy?

**Comment by jedisct1** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters#allowlist-only

Block everything (`*.*` in the block list) and explicitly allow what you want in the allow list.

**Comment by vladns** [comment]
I don't need to block anything. On the contrary, I need to enter the domains of the ".lib" zone. To do this, you need to use opennic dns servers. I did it using dnsmasq, but it is not secure. So I wondered how to do this using dnscrypt-proxy. Since it works now, there is no way to visit rutracker.lib for example.
I want to use, for example, this dns server https://servers.opennic.org/edit.php?srv=ns8.ca.dns.opennic.glue only for the Lib zone.

**Comment by jedisct1** [comment]
You can use forwarding to redirect specific zones to specific servers. But forwarding is not going to work over dnscrypt unless you forward to a second instance.
