### ISSUE TITLE
Anonymized DNS relays in logs

### ISSUE THREAD

**Issue by lesowin370** [DNSCrypt/dnscrypt-proxy#1614]
## The problem
Anonymized DNS relays and/or DNSCrypt servers fail sometimes with NETWORK_ERROR or SERVER_TIMEOUT responses. Query logs don't show what exactly failed - a relay or a server. It would be great to have such information in logs so I could remove slow relays/servers instead of increasing timeout to insane values.

**Comment by jedisct1** [comment]
Relay are transparent. They can't send information of their own to clients. So, there is no simple and reliable way for a client to know if a network error comes from a relay or the actual server.

But if some relays or servers don't seem to work as expected, feel free to open an issue on https://github.com/DNSCrypt/dnscrypt-resolvers - The lists are constantly updated to try to provide reliable configurations that everyone can use.

**Comment by lesowin370** [comment]
Okay, but at least I'll be able to see that _this server_ with _that relay_ takes N milliseconds to process a query. If it happens regularly I could remove such pairs from config to improve performance.
Sorry for late reply.
