### ISSUE TITLE
A question about load-balancing

### ISSUE THREAD

**Issue by blub4747** [DNSCrypt/dnscrypt-proxy#1615]
Hello Community,

I am located in central Europe near the polish boarder.
Due to his location and the therefore ping timings I always end up with the same server eg _soltysiak_
I already tried all documented load-balancing options and I do still end each time with the same server.
Is there anything one could suggest, besides from removing this one particular server.
Thx, blub4747

**Comment by jedisct1** [comment]
Looks like this is the fastest option for you, but if you don't want to use use that resolver, you can add it to the `disabled_server_names` set.

(as a side note `soltysiak` doesn't exist any more, so your resolvers list may be out of date)

**Comment by blub4747** [comment]
hmm I guess that I will have to do some experimenting by disabling some servers. At the end of the day though to disable to a server 'feels' almost the same like removing a server. And, yes I notice that `soltysiak` might have changed their name to dnscrypt poland. I still need to do a bit reading into them if they are same people or not. 

Can I also use this chance to add additional question, which also has been on my mind?

How can I please filter and export the results into a separate file, when I do execute the script `./dnscrypt-proxy` ?
Such as timeout or 'WARNING' for later processing.
I already tried without any luck the following options.
`./dnscrypt-proxy | grep timeout`
`./dnscrypt-proxy && | grep timeout`

I was thinking towards something like this
`./dnscrypt-proxy && | grep timeout > error`

Thx,blub4747

**Comment by jedisct1** [comment]
`./dnscrypt-proxy -show-certs -logfile /tmp/result.txt` maybe?

**Comment by blub4747** [comment]
That was exactly what I was looking for. 
Thank you!

**Comment by blub4747** [comment]
Sorry for reopening this.
What do I need to fill into the brackets please ?
`disabled_server_names = []`
To disable the server in poland.
Is it the name of the server? or the sdns address ?
Thx,blub4747

**Comment by jedisct1** [comment]
What does the comment on the line right before it say?

**Comment by blub4747** [comment]
Hello I was busy with other stuff or the last few days.

Here is the result for both ways I tried.

```txt
# Server names to avoid even if they match all criteria
disabled_server_names = [dnscrypt.pl]

./dnscrypt-proxy
[2021-02-16 10:16:58] [FATAL] Near line 85 (last key parsed 'disabled_server_names'): expected value but found "dnscrypt" instead


# Server names to avoid even if they match all criteria
disabled_server_names = [AQcAAAAAAAAAFDE3OC4yMTYuMjAxLjEyODoyMDUzIH9hfLgepVPSNMSbwnnHT3tUmAUNHb8RGv7mmWPGR6FpGzIuZG5zY3J$

./dnscrypt-proxy
[2021-02-16 10:20:13] [FATAL] Near line 85 (last key parsed 'disabled_server_names'): expected value but found "AQcAAAAAAAAAFDE" instead
```

**Comment by jedisct1** [comment]
I'm not even suggesting looking at the [documentation](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Configuration-Sources#disabling-servers-by-name), but please look at the rest of the example `dnscrypt-proxy.toml` file.

The comment right before the line you changed says the values are server names.

Now, look at how strings are represented, absolutely everywhere in the configuration file, including the `server_names` list, that looks very similar to `disabled_server_names`.

**Comment by blub4747** [comment]
Once someone points the obvious, it is right before ones own eyes.
I finally spotted the missing ''
from `[dnscrypt.pl] to ['dnscrypt.pl']

Thanks alot for the massive help!
