### ISSUE TITLE
Question regarding 'block_unqualified'

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1617]
Hi,

dnscrypt-proxy 2.0.45 / Firefox 85.0.2 (x64) / Windows 7 (x64)

I've always had,
```
## Immediately respond to A and AAAA queries for host names without a domain name
block_unqualified = true
```

I've encountered issues on two sites, https://lbry.tv/ and https://odysee.com/ (the latter depends of the former) where video thumbnails simply wouldn't display. These thumbnails' links are of the form, as an example :  `https://lbry.tv/@davidpakman:7/will-marjorie-taylor-greene-be-removed:a`

I then set `block_unqualified` to `false`, restarted dnscrypt-proxy, restarted Firefox and the thumbnails displayed correctly.

My question is:

I'm technically ignorant, I don't know what `block_unqualified` corresponds to. What are the implications of having it set to true or false? If I leave it on false do I face specific problems? Thanks!

**Comment by jedisct1** [comment]
`lbry.tv` is a domain name, so  the value of `block_unqualified` should not make any difference here. The problem is likely somewhere else.

**Comment by ghost** [comment]
Thanks. Factually setting `block_unqualified` to `false` resolved my issue, that's all i'm able to confirm.
I went into dnscrypt's configuration after having noticed that the logs (ips and domains) were empty.
After, luck.

**Comment by ghost** [comment]
The issue I mentioned here appears to have vanished. I don't know what had happened then but I do know I had proceeded exactly as I described it. Coincidence is my conclusion.
I'm closing therefor this non-issue.
