### ISSUE TITLE
DNS Stamp query and DoH direct IP connections

### ISSUE THREAD

**Issue by daverof** [DNSCrypt/dnscrypt-proxy#1618]
I am using two static DNS stamps for Cloudflare Family DoH 1.1.1.3 and 1.0.0.3 aka `family.cloudflare-dns.com`

```
[static]
[static.'cloudflare-family']
stamp = 'sdns://AgMAAAAAAAAABzEuMS4xLjMAGWZhbWlseS5jbG91ZGZsYXJlLWRucy5jb20KL2Rucy1xdWVyeQ'
[static.'cloudflare-family2']
stamp = 'sdns://AgMAAAAAAAAABzEuMC4wLjMAGWZhbWlseS5jbG91ZGZsYXJlLWRucy5jb20KL2Rucy1xdWVyeQ'
```
My `dnscrypt-proxy.toml` has:  `server_names = ['cloudflare-family', 'cloudflare-family2']`

Questions-

1) It seems like in both cases, dnscrypt-proxy resolves and connects to `family.cloudflare-dns.com:443`. Are the IP addressses only used when the hostname cannot be resolved?

2) I want to use both IP addresses for some redundancy, but if the IPs are not being used to connect most of the time, then is there any point in using the second stamp? In the official v3 resolver lists, some entries have two stamps with different IPs (but the same hostname), so I assumed all of these IPs would be used for redundancy.

3) As the IPs never change, I would like to skip hostname resolution completely. Is there a way to force a connection using only the IP? In this case, the IPs do have valid certificates so in theory a connection can be made to e.g. `https://1.1.1.3/dns-query`. I tried removing the `family.cloudflare-dns.com` from the stamp and it fails with the error `no host in request URL` in the log.

Thanks

**Comment by jedisct1** [comment]
If there is an IP address, the name is not used to find an IP address. The name is only used for SNI.
