### ISSUE TITLE
Also proxy DNS query for cloaking domains

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1620]
## Is your feature request related to a problem?

clocking-rules.txt
```
www.google.com forcesafesearch.google.com
```

For the above conf, dnscrypt-proxy will not send `forcesafesearch.google.com` to remote DNSCrypt servers in  an **encrypted** protocol, Instead, querying for local DNS in **unencrypted** UDP protocol

## Describe the solution you'd like

As said in the issue title

## Additional context

<details><summary>In the rare case if </summary>

1. State's censorship is affecting the domain `cn.nytimes.com`

2. To access the site, use domain fronting tool [Accesser](https://github.com/URenko/Accesser/blob/master/README.en.md) which is relying on dnscrypt-proxy to get correct DNS response

3. `cn.nytimes.com` itself sometimes return non-domain-frontable IPs, and we want it always use domain-frontable `x.cloudfront.net` IPs

4. so below written in cloaking-rules.txt
```
cn.nytimes.com d1emgxxou2di91.cloudfront.net
```

5.  and its CNAME `d1emgxxou2di91.cloudfront.net` is also affected (return malformed response)

6. dnscrypt-proxy use local poisoned DNS (and of course, unencrypted) for `d1emgxxou2di91.cloudfront.net`

dnscrypt-proxy and the domain fronting tool never got the correct IP
</details>

**Comment by jedisct1** [comment]
If a name is used instead of an IP address, the name is resolved with a query to the local resolver, which has already been configured to use dnscrypt-proxy. So, no unencrypted queries leaves the host.

**Comment by ghost** [comment]
> the name is resolved with a query to the local resolver, which has already been configured to use dnscrypt-proxy.

It requires that the system-wide dns resolver to be set to like `127.0.0.1:x`(x is the port dnscrypt-proxy is listening on)

I wish that dnscrypt-proxy use **itself** instead of use **system-wide dns resolver**, for the cloaking domains.

**Comment by jedisct1** [comment]
But if the system hasn't been configured to use the proxy, how are you using it?

**Comment by ghost** [comment]
A censorship-circumvention tool use a built-in dnscrypt-proxy for dns lookups, as a child process of itself

I thought it'll be better if making a pull request myself...

https://github.com/DNSCrypt/dnscrypt-proxy/blob/1b4045a098749c0efaaf0580f1757c70ca29acc1/dnscrypt-proxy/plugin_cloak.go#L126

dnscrypt-proxy should instead find itself then use `net.Resolver`...

**Comment by lifenjoiner** [comment]
> built-in dnscrypt-proxy

New case ...

Normally, the configured different name will go back to SDNS finally, I agree.
And by my tests **on Windows**, there are a little differences for cloaking:
1. `cache = false`
    It can't control the OS cache strategy. The cloaked host result depends on the OS cache.
2. TTL
    For the cloaked host, OS cache may take the configured different name's TTL. It may greater or less than `cloak_ttl`. `dnscrypt-proxy` **always** counts the `cloak_ttl`, even `cache = false`.
    For the configured different name, TTL depends on the remote.
![SDNS-TTL](https://user-images.githubusercontent.com/19585474/108582367-c47ba880-736d-11eb-9fe2-6ae8eb5232ba.png)

I don't use this feature much ;p
