### ISSUE TITLE
Add option to fallback resolvers

### ISSUE THREAD

**Issue by Romulo-Romero** [DNSCrypt/dnscrypt-proxy#1621]
## Is your feature request related to a problem?
No, but it could become a problem if privacy is breached

## Describe the solution you'd like
I would like to see an option to disable fallback resolvers, if none of the dns servers resolve. Fallback could breach privacy if none of the servers respond.  I've made changes locally so I could use this in my pc. For those privacy centered people, they don't want the fallback feature at all, since the intention of using dnscrypt was to actually encrypt dns traffic in first place, otherwise it defeats its purpose. 
So we want to ignore both fallback and system dns, and these should be optional.

## What have you done already?

 So this is what I came up with so far, and I am not sure if that's the best way to go about it, but here it goes:
config.go:
`	
DisableFallback			 bool 						``toml:"disable_fallback"`

`proxy.xTransport.disableFallback = config.DisableFallback`

`if(!config.DisableFallback)	{`
		`if len(config.FallbackResolver) > 0 {`
			`config.FallbackResolvers = []string{config.FallbackResolver}`
		`}`
		`if len(config.FallbackResolvers) > 0 {`
			`for _, resolver := range config.FallbackResolvers {`
				`if err := isIPAndPort(resolver); err != nil {`
					`return fmt.Errorf("Fallback resolver [%v]: %v", resolver, err)`
				`}`
			`}`
			`proxy.xTransport.ignoreSystemDNS = config.IgnoreSystemDNS`
		`}`
	`}`
`

EDIT: Just for the sake of completeness I'm adding the dialog notice
xtransport.go:

`type XTransport struct {`
	`transport                *http.Transport`
	`keepAlive                time.Duration`
	`timeout                  time.Duration`
	`cachedIPs                CachedIPs`
	`fallbackResolvers        []string`
	`mainProto                string`
	`ignoreSystemDNS          bool`
	`disableFallback			 bool`
	`useIPv4                  bool`
	`useIPv6                  bool`
	`tlsDisableSessionTickets bool`
	`tlsCipherSuite           []uint16`
	`proxyDialer              *netproxy.Dialer`
	`httpProxyFunction        func(*http.Request) (*url.URL, error)`
	`tlsClientCreds           DOHClientCreds`
`}`
`if err != nil && xTransport.disableFallback	{`
		`dlog.Noticef("Oops! unable to get DOH server ip and fallback is disabled...")`
		`goto jump_here`
	`}`
`if !xTransport.disableFallback &&  (xTransport.ignoreSystemDNS || err != nil) {`
		`protos := []string{"udp", "tcp"}`
		`if xTransport.mainProto == "tcp" {`
			`protos = []string{"tcp", "udp"}`
		`}`
		`for _, proto := range protos {`
			`if err != nil {`
				`dlog.Noticef("System DNS configuration not usable yet, exceptionally resolving [%s] using fallback resolvers over %s", host, proto)`
			`} else {`
				`dlog.Debugf("Resolving [%s] using fallback resolvers over %s", host, proto)`
			`}`
			`foundIP, ttl, err = xTransport.resolveUsingResolvers(proto, host, xTransport.fallbackResolvers)`
			`if err == nil {`
				`break`
			`}`
		`}`
	`}`
	`jump_here:`
	`if err != nil && xTransport.ignoreSystemDNS {`
		`dlog.Noticef("Fallback resolvers didn't respond - Trying with the system resolver as a last resort")`
		`foundIP, ttl, err = xTransport.resolveUsingSystem(host)`
	`}`

dnscrypt-proxy.toml:
`# Never use fallback resolvers`

`disable_fallback = true`

## Who will that feature be useful to?
This feature would be useful for those who don't want any fallback functionality at all, since it can resolve without encryption, thus breaching privacy. Even though it alerts the user that it is using fallback due to failure, once it's done , it's done and the addresses already breached.

**Comment by jedisct1** [comment]
The actual issue seems to be confusing around the name `Fallback Resolver`.

Queries are not sent there if "none of the DNS servers resolve".

The fallback resolver is used if servers with DoH stamps that don't include an IP address are used, and usage of the system resolver has been disabled. There's no way to connect to anything at that point, so the name of these DoH servers needs to be resolved with a 3rd party resolver.

**Comment by Romulo-Romero** [comment]
> 
> 
> The actual issue seems to be confusing around the name `Fallback Resolver`.
> 
> Queries are not sent there if "none of the DNS servers resolve".
> 
> The fallback resolver is used if servers with DoH stamps that don't include an IP address are used, and usage of the system resolver has been disabled. There's no way to connect to anything at that point, so the name of these DoH servers needs to be resolved with a 3rd party resolver.

Hi jedisct1,
Thanks for clarifying the issue. The name fallback can indeed cause misinterpretation. Even though, if the name of these DOH servers need to be resolved using a 3rd party resolver due to ipless situation, I would like to manually fix the issue, by either changing servers or something like that.

I don't use DOH at the moment due to anonymization, but just in case I will keep that setting off. Thanks again for your reply and for clarifying what Fallback Resolver actually means.
