### ISSUE TITLE
Cached responses had a non-decrementing TTL before version 2.0.45

### ISSUE THREAD

**Issue by KilometerM** [DNSCrypt/dnscrypt-proxy#1624]
## *Who* is the bug affecting?

Users of dnscrypt-proxy.

## *What* is affected by this bug?

DNS cache and TTL does not behave as it did in prior versions. TTL does not decrement on the second query for the same domain name and queries after that show erratic TTL behavior.

## *When* does this occur?

It is most easily seen between the first and second queries for the same domain name with dnscrypt-proxy cache enabled.

## *Where* does it happen?

Version 2.0.45: macOS, linux-arm, linux-arm64

## *How* do we replicate the issue?

1. install dnscrypt-proxy version 2.0.45 from GitHub releases. (reproduced on macOS, linux-arm, and linux-arm64)
2. query a domain that will have it's TTL set according to the min-TTL defined in the .toml file.
3. see in the response that it's TTL is set to that min-TTL value (e.g. 2399).
4. make a 2nd query for the same domain name after a few seconds (or minutes) have passed.
5. see in the response for the second query that it's TTL still shows as 2399 rather than the expected decremented TTL, but it has responded from cache according to the query log file.
6. immediately make a 3rd query and see that it's TTL "jumps" down to a decremented TTL in accordance with how much time has passed since the 1st query.

## Expected behavior (i.e. solution)

1. The 1st query for a domain name would be cached for it's TTL or the min-TTL defined in the .toml file. (e.g. 2399 seconds).
2. After waiting 90 seconds, a 2nd query for the same domain name would then show a decremented TTL of original TTL - 90. (e.g. 2309 seconds in this example)

## Other Comments
Since updating to version 2.0.45 I have observed a change in cache behavior in comparison to prior versions. I am not sure if this is known or intended, but I thought I would ask. When a DNS query is made I would expect it to be cached for the TTL and then decrement in real time. On version 2.0.45 the first query shows a TTL of 2399 in accordance with the default .toml file. Then the second query also shows a TTL of 2399 no matter the amount of time that has passed in between the first and second query. If I waited 100 seconds between queries, for example, I would expect the TTL of the second query to have a TTL of 2299. You can tell that it is responding from cache, however, because the response time is much lower than the initial query and it is indicated in the query log. The third query will then "jump" to the expected TTL in relation to when the first query was made. As more queries for the same domain name are made, the response TTL continues to be odd. As seen in one of my screenshots, I made two queries about 103 seconds apart, however the TTL only decreases by 3.

I have re-run my tests using version 2.0.44 and it does not exhibit this behavior. The TTL decreases from the first to second query and also reliably decreases in accordance with the amount of time that has passed between queries.

I don't believe this is a "just me" issue as I have reproduced this behavior on the release binaries for macOS, linux-arm (raspberry pi), and linux-arm64 (router). I have also compared past versions and this is new as of 2.0.45. Version 2.0.44 behaves as expected.

**Screenshots:**

<img width="563" alt="Screen Shot 2021-02-21 at 9 45 21 PM" src="https://user-images.githubusercontent.com/65037176/108737448-da18db80-74ef-11eb-8d91-b4ce72a5e120.png">

<img width="583" alt="Screen Shot 2021-02-21 at 9 40 14 PM" src="https://user-images.githubusercontent.com/65037176/108737514-e866f780-74ef-11eb-8995-1fa3397506a5.png">

<img width="495" alt="Screen Shot 2021-02-22 at 8 43 48 AM" src="https://user-images.githubusercontent.com/65037176/108737618-059bc600-74f0-11eb-8aa2-3c2c6481367f.png">

**Comment by jedisct1** [comment]
Are you sending these queries directly to `dnscrypt-proxy` or is there something like `dnsmasq` in-between?

**Comment by KilometerM** [comment]
Directly to `dnscrypt-proxy`. There is nothing in between in all cases of my testing.

**Comment by jedisct1** [comment]
This is weird. I can't duplicate this.

~~and there haven't been any changes to the cache at all in between 2.0.44 and 2.0.45~~ 
Cached responses used to be served with a constant TTL before version 2.0.45.

**Comment by jedisct1** [comment]
> see in the response that it's TTL is set to that min-TTL value (e.g. 2399).
> make a 2nd query for the same domain name after a few seconds (or minutes) have passed.
> see in the response that it's TTL is set to that min-TTL value (e.g. 2399).

Nothing unexpected here if a new response was returned, and its TTL was lower than the minimum configured TTL.

I'm still a little bit confused about what the issue is, maybe because there is too much information here.

This is what I did:

- Set `cache_min_ttl = 5`
- Set `server_names` to a single resolver that doesn't have a minimum TTL
- Then send queries for `one.stdc.org` that has a 1 second TTL, every second:

```sh
$ while :; do drill one.stdc.org @127.0.0.1; sleep 1; done
one.stdc.org.	4	IN	A	42.42.42.42
one.stdc.org.	3	IN	A	42.42.42.42
one.stdc.org.	2	IN	A	42.42.42.42
one.stdc.org.	1	IN	A	42.42.42.42
one.stdc.org.	0	IN	A	42.42.42.42
one.stdc.org.	4	IN	A	42.42.42.42
...
```

The response always had a TTL between `0` and `4`, changing every second.  The log shows an upstream query every 5 second, as expected:

```text
[2021-02-22 18:38:01]	127.0.0.1	one.stdc.org	A	PASS	177ms	fastly
[2021-02-22 18:38:02]	127.0.0.1	one.stdc.org	A	PASS	0ms	-
[2021-02-22 18:38:03]	127.0.0.1	one.stdc.org	A	PASS	0ms	-
[2021-02-22 18:38:04]	127.0.0.1	one.stdc.org	A	PASS	0ms	-
[2021-02-22 18:38:05]	127.0.0.1	one.stdc.org	A	PASS	0ms	-
[2021-02-22 18:38:06]	127.0.0.1	one.stdc.org	A	PASS	51ms	fastly
[2021-02-22 18:38:07]	127.0.0.1	one.stdc.org	A	PASS	0ms	-
[2021-02-22 18:38:08]	127.0.0.1	one.stdc.org	A	PASS	0ms	-
[2021-02-22 18:38:09]	127.0.0.1	one.stdc.org	A	PASS	0ms	-
[2021-02-22 18:38:10]	127.0.0.1	one.stdc.org	A	PASS	0ms	-
[2021-02-22 18:38:11]	127.0.0.1	one.stdc.org	A	PASS	52ms	fastly
```

Now with a query every 6 second:

```sh
$ while :; do drill one.stdc.org @127.0.0.1; sleep 6; done
one.stdc.org.	4	IN	A	42.42.42.42
one.stdc.org.	4	IN	A	42.42.42.42
one.stdc.org.	4	IN	A	42.42.42.42
one.stdc.org.	4	IN	A	42.42.42.42
one.stdc.org.	4	IN	A	42.42.42.42
```

The 5 second TTL always expires between queries, so I get the max TTL, and in the log, an upstream query every time:

```text
[2021-02-22 18:39:33]	127.0.0.1	one.stdc.org	A	PASS	33ms	fastly
[2021-02-22 18:39:39]	127.0.0.1	one.stdc.org	A	PASS	29ms	fastly
[2021-02-22 18:39:46]	127.0.0.1	one.stdc.org	A	PASS	59ms	fastly
[2021-02-22 18:39:52]	127.0.0.1	one.stdc.org	A	PASS	48ms	fastly
[2021-02-22 18:39:58]	127.0.0.1	one.stdc.org	A	PASS	41ms	fastly
[2021-02-22 18:40:04]	127.0.0.1	one.stdc.org	A	PASS	34ms	fastly
[2021-02-22 18:40:10]	127.0.0.1	one.stdc.org	A	PASS	37ms	fastly
[2021-02-22 18:40:16]	127.0.0.1	one.stdc.org	A	PASS	31ms	fastly
[2021-02-22 18:40:22]	127.0.0.1	one.stdc.org	A	PASS	42ms	fastly
[2021-02-22 18:40:28]	127.0.0.1	one.stdc.org	A	PASS	68ms	fastly
[2021-02-22 18:40:34]	127.0.0.1	one.stdc.org	A	PASS	38ms	fastly
[2021-02-22 18:40:40]	127.0.0.1	one.stdc.org	A	PASS	37ms	fastly
[2021-02-22 18:40:46]	127.0.0.1	one.stdc.org	A	PASS	56ms	fastly
```

Did I miss something?

**Comment by jedisct1** [comment]
Looking at the change log, cached responses used to be served with a constant TTL.

Decrementing TTLs of cached responses was implemented in 2.0.45. This is the correct thing to do if you have downstream caches.

The constant TTL in previous versions was only due to laziness :)

**Comment by KilometerM** [comment]
I've recreated your test case. As you can see my first two response both show a TTL of 4. Based on what you have said, is this expected? I'm just trying to make sure I understand :) It doesn't appear to happen in your test results.

> This is what I did:
>Set cache_min_ttl = 5
>Set server_names to a single resolver that doesn't have a minimum TTL
>Then send queries for one.stdc.org that has a 1 second TTL, every second:

`% while :; do drill one.stdc.org @127.0.0.1; sleep 1; done`
`one.stdc.org.	4	IN	A	42.42.42.42`
`one.stdc.org.	4	IN	A	42.42.42.42`
`one.stdc.org.	3	IN	A	42.42.42.42`
`one.stdc.org.	2	IN	A	42.42.42.42`
`one.stdc.org.	1	IN	A	42.42.42.42`
`one.stdc.org.	4	IN	A	42.42.42.42`
`one.stdc.org.	4	IN	A	42.42.42.42`
`one.stdc.org.	3	IN	A	42.42.42.42`
`one.stdc.org.	2	IN	A	42.42.42.42`
`one.stdc.org.	1	IN	A	42.42.42.42`

**Comment by KilometerM** [comment]
Compare with the same test run on version 2.0.44:

`% while :; do drill one.stdc.org @127.0.0.1; sleep 1; done`
`one.stdc.org.	4	IN	A	42.42.42.42`
`one.stdc.org.	3	IN	A	42.42.42.42`
`one.stdc.org.	2	IN	A	42.42.42.42`
`one.stdc.org.	1	IN	A	42.42.42.42`
`one.stdc.org.	0	IN	A	42.42.42.42`
`one.stdc.org.	4	IN	A	42.42.42.42`
`one.stdc.org.	3	IN	A	42.42.42.42`
`one.stdc.org.	2	IN	A	42.42.42.42`
`one.stdc.org.	1	IN	A	42.42.42.42`
`one.stdc.org.	0	IN	A	42.42.42.42`

**Comment by jedisct1** [comment]
There doesn't seem to be anything wrong here.

**Comment by KilometerM** [comment]
Okay, thank you!
