### ISSUE TITLE
IP Blocklist

### ISSUE THREAD

**Issue by HellsAngel79** [DNSCrypt/dnscrypt-proxy#1625]
Im trying to get the ip blocklist to work but sofar only hostnames work every ip i put in iplist keeps replying to pings.
Ive tried this on the windows dnscrypt and the one running on an edgerouter both basically use identical .toml
to my understanding ive got it setup right its just ignoring the banning on windows i can see it say it loaded the
blocked-ips.txt but thats it. I have attached the config file hopefully that is the problem and an easy fix.
Thanks in advance.

[dnscrypt-proxy.zip](https://github.com/DNSCrypt/dnscrypt-proxy/files/6024881/dnscrypt-proxy.zip)

**Comment by jedisct1** [comment]
> keeps replying to pings

`dnscrypt-proxy` operates at DNS level.

If you try to connect (or "ping") a host name that resolves to a blocked IP address, an empty response will be returned, causing the operation to fail.

But if you are trying to directly reach an IP address, you completely bypass DNS.

If you really want to prevent IP addresses from being routed from your host when you type them directly, you need to use a firewall instead.

**Comment by jedisct1** [comment]
By the way: hello.

**Comment by HellsAngel79** [comment]
Ah ok thanks for the quick reply been going at it for hours as im not too familiar with edgeos and its firewall this seemed quick and easy thanks for explaining why it didnt work.
