### ISSUE TITLE
Question: cloaking file syntax

### ISSUE THREAD

**Issue by kanyck** [DNSCrypt/dnscrypt-proxy#163]
Hi! 
Couldn't find any info on cloacking rules syntax. Does it accept wildcards etc. as blacklist file does or it is simply domain pairs? For instance, google has few dozen domains and to force safe search with google shall I have few dozen lines or I may use a wildcard? The example file is not self-documented enough, at least I'm not sure about it.

**Comment by jedisct1** [comment]
It does not accept wildcards at the moment.

**Comment by kanyck** [comment]
Okay. Thank you Frank!

**Comment by jedisct1** [comment]
Maybe in a future version!

**Comment by kanyck** [comment]
I think it's not very important, for the cloaking files are not nearly that big as blacklists are. Rather, it's a matter of being documented in a clearer way. Tnanks again!

**Comment by jedisct1** [comment]
The documentation is a wiki; anybody can edit it :)
