### ISSUE TITLE
dnscrypt-proxy server : why the tool use so much memory ?

### ISSUE THREAD

**Issue by Grimst** [DNSCrypt/dnscrypt-proxy#1630]
## Subject : a lot of memory is used even if the server is pending /waiting (?) conections

it is the top "five" of my process that use the most memory (in descending order ) :
-- | --
EXCEL,"97232" |  
explorer,"104112" |  
MsMpEng,"117304" |  
googledrivesync,"143540"
dnscrypt-proxy,"344628" |  

powershell command : Get-Process | Sort-Object WorkingSet64 | Select-Object Name,@{Name='WorkingSet';Expression={($_.WorkingSet64/1KB)}} | Export-Csv -Path "processes64.csv" -Delimiter ","

I use your tool everyday on my laptop to work at the University of Geneva and have a great tool but why is the server using so much memory? I specify that for the test above, i purposely closed all my browsers and I don't interact with the network with another tool

thanks for your job guys.

Steve

**Comment by jedisct1** [comment]
Maybe you're looking at virtual memory, not active memory usage?

**Comment by Grimst** [comment]
I am not a specialist, here is what I read in the microsoft documentation (concerning my command above)
link => [https://docs.microsoft.com/fr-fr/windows/win32/psapi/process-memory-usage-information?redirectedfrom=MSDN](url)

**The working set is the amount of memory physically mapped to the process context at a given time.**
the above command (simplified) : Get-Process | Sort-Object WorkingSet64 | Select-Object Name,@{Name='WorkingSet';Expression={($_.WorkingSet64/1Mb)}} 

or this one : 
`Get-Process | %{
[pscustomobject]@{
    ID=$_.Id
    'Process Name'=$_.Name
    WS=[math]::Round($_.WorkingSet/1MB, 1)
    Private=[math]::Round($_.PrivateMemorySize/1MB, 1)
    Virtual=[math]::Round($_.VirtualMemorySize/1MB, 1)
}
} | Sort WS | ft -AutoSize`

link => [https://stackoverflow.com/questions/50940496/powershell-script-sorting-by-object-size-in-mbs](url)

result :

ID : 1508
Process Name :    dnscrypt-proxy  
WS :  239   
Private(Mb) :   341,6   
Virtual(Mb) : 1102
                      

i just execute the commande now. 
is the expected result of memory usage for this tool ?

thanks in advance,
Steve

**Comment by lifenjoiner** [comment]
Hi Grimst,

I'm also a user on Windows. And by my observation, it keeps ~ 30 M: 32b version, no `*_names_file` nor `*_rules`, no cache, but 1+ service ports. I'm keeping a process monitor running all the time ;)

```
PS D:\> Get-Process dnscrypt-proxy
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    345      21    36072      32948   1,369.39  10796   1 dnscrypt-proxy
```

Seems your case is abnormal ... but how it got this needs more information to say.
Provide your config, error messages, logs, version, uptime, etc.

**Comment by Grimst** [comment]
> Hi Grimst,
> 
> I'm also a user on Windows. And by my observation, it keeps ~ 30 M: 32b version, no `*_names_file` nor `*_rules`, no cache, but 1+ service ports. I'm keeping a process monitor running all the time
> 
> ```
> PS D:\> Get-Process dnscrypt-proxy
> Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
> -------  ------    -----      -----     ------     --  -- -----------
>     345      21    36072      32948   1,369.39  10796   1 dnscrypt-proxy
> ```
> 
> Seems your case is abnormal ... but how it got this needs more information to say.
> Provide your config, error messages, logs, version, uptime, etc.




Ok thanks for the reply

i just re-install dnscrypt-proxy tool with the same package version (dnscrypt-proxy-win64-2.0.45) and relaunch it with all the default parameters and all works with less memory usage !

PS C:\Users\Steve\Desktop> Get-Process dnscrypt-proxy
```
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    269      14    22900      11448              6324   0 dnscrypt-proxy
```

I think that maybe it comes from the logs that I have configured (query, blacklist, etc.

thanks guys for the help, for me the issue is closed!

Steve
