### ISSUE TITLE
ping giving "System error" when dnscrypt-proxy blocks a site

### ISSUE THREAD

**Issue by mabod** [DNSCrypt/dnscrypt-proxy#1631]
I am using `dnscrypt-proxy 2.0.45-1` on arch Linux. The other  day I experienced and issue with compiling the bitwarden package on one of my computers and found that the reason was `dnscrypt-proxy`.

During compilation of the bitwarden AUR package it tries to resolve server name `fonts.gstatic.com`. This was blocked by my dnscrypt-proxy configuration which causes the bitwarden compilation to error out. I had to put `fonts.gstatic.com` into the `allowed-names.txt` list to make it work. 

That made me investigate dnscrypt-proxy a little further. I have facebook.com blocked in my config. When I ping facebook.com I get a system error:

```
33# ping facebook.com    
ping: facebook.com: System error
```

That is probably the same error code that causes the bitwarden compilation to fail.

From my point of view that should not be the case. It should more react like if a host name does not exist. Example:

```
36# ping facebook.xx.yyy
ping: facebook.xx.yyy: Name or service not known
```

That is correct behavior for blocking a site from my point of view. But not a "system error".

**Comment by jedisct1** [comment]
A response for a blocked name uses the standard `REFUSED` DNS error code.

From here, applications can do whatever they want :) `System error` is not a message that comes from dnscrypt-proxy.

You can change the `blocked_query_response` setting if you like, maybe `ping` will print a different message.
