### ISSUE TITLE
Does it make sense to add support for ODoH now offered by Cloudfare?

### ISSUE THREAD

**Issue by newkton1** [DNSCrypt/dnscrypt-proxy#1633]
if support for ODoH could be implemented in the binary for RPI (3b), I'd be happy to beta test.

**Comment by welwood08** [comment]
As mentioned a few months ago in #1544, Cloudflare have offered to contribute this support to `dnscrypt-proxy`. I don't have any additional news on their plans, but in any case ODoH itself is still in the draft phase and subject to change.
