### ISSUE TITLE
Clarification on ODoH & Anonymized DNSCrypt

### ISSUE THREAD

**Issue by Svallinn** [DNSCrypt/dnscrypt-proxy#1634]
## Subject

* [X] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description
I read the protocol regarding *Anonymized DNSCrypt* and also read up a bit on *ODoH*.
The way I interpreted it, I noticed a clear difference between the 2 and I just wanted clarification on whether or not that's actually the case or not.
(FYI this isn't really a critique or anything, it's just curiosity
IMO, this isn't really an issue)

---
My question is focused mainly on the **client-relay** connection
*ODoH* seems to encrypt the entire message with E2EE and also the client-relay and relay-target connections through HTTPS.
But *Anonymized DNSCrypt* only encrypts the query with E2EE just like normal DNSCrypt does, it was designed that way after all.
So, in the client-relay connection, if some outside actor is looking in on that connection, contrasting with *ODoH* (which makes **only the relay IP and relay port discernible**),
**both the relay and the target IPs and ports are discernible (in plain text)** when using *Anonymized DNSCrypt*, is that correct?

**Comment by jedisct1** [comment]
Correct.

There is no reencryption to the relay. The client encrypts the query directly for the resolver (so any intermediate relay cannot see nor tamper with anything), and sends the resolver and the encrypted query to the relay.
