### ISSUE TITLE
Quad 9  1067

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1636]
Hiya

any time i try and add Quad 9 I get error Windows could not start the DNSCrypt client proxy service on Local Computer. Error 1067: The process terminated unexpectedly.
with
server_names = ["quad9-dnscrypt-ip4-filter-pri"]
or
server_names = ["quad9-doh-ip4-filter-pri"]

also tried with
server_names = ["quad9-doh-ip4-nofilter-pri"]
and same error

both produce same error separately
 
https://support.quad9.net/hc/en-us/articles/360041193212-Quad9-IPs-and-other-settings
https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md
https://www.ghacks.net/2021/02/17/dns-provider-quad9-moves-to-switzerland/
https://www.quad9.net/news/blog/quad9-public-domain-name-service-moves-to-switzerland-for-maximum-internet-privacy-protection/
https://en.wikipedia.org/wiki/Quad9

also quad 9 does not show up in simple dns crypt proxy list no matter what options i choose in the application either
https://www.simplednscrypt.org/

**Comment by lifenjoiner** [comment]
AFAIK:
1. If there is any error about the servers, `dnscrypt-proxy` will log it.
2. Seems `Error 1067: The process terminated unexpectedly` is an error of the OS about a service startup failure, `sfc /scannow` related, by searching on the net. Try it first.

If there is still any error of `dnscrypt-proxy`, paste it.

**Comment by Icekiss69** [comment]
this works
server_names = ["google"] 
without error 1067 but not quad 9

1067 is common in dnscrypt proxy when it doesn't like a setting in the toml file
i don't see any logs for dnscrypt proxy

**Comment by lifenjoiner** [comment]
Try run `dnscrypt-proxy.exe` from command line in your installed directory, to see if there will be any useful message ...

**Comment by jedisct1** [comment]
What's your `dnscrypt-proxy` version? You may be trying to use a `v3` list with an old version that only supports `v2`.

**Comment by Icekiss69** [comment]
2.0.42 came with simple dns crypt proxy
