### ISSUE TITLE
Is multiple relays between host and resolver server supported for Anonymized DNSCrypt?

### ISSUE THREAD

**Issue by matchatealeaf** [DNSCrypt/dnscrypt-proxy#1637]
## Subject

* [X] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description

Is multiple relays in a single route supported? For example having 2 relays:
`me --> relay1 --> relay2 --> resolver`

I tried:
```toml
[anonymized_dns]
routes = [
    { server_name='example-server-1', via=['anon-example-2'] },
    { server_name='anon-example2', via=['anon-example-1']}
]
```
`me --> anon-example1 --> anon-example2 --> example-server-1`

But only the last relay is reflected in the status:
`[NOTICE] Anonymizing queries for [example-server-1] via [anon-example-2]`

I am not sure if there are any additional benefits of having multiple relays to the resolver. I'm just curious if it is possible.

**Comment by jedisct1** [comment]
Hi!

There can be only one relay.

The protocol is intentionally very strict. This prevents relays from being abused for relaying other protocols, and by design, loops will never happen.
