### ISSUE TITLE
Permission denied for public-resolvers.md and relays.md

### ISSUE THREAD

**Issue by changemenemo** [DNSCrypt/dnscrypt-proxy#1640]
this is happening in raspbian up-to-date

in reference to[ this issue](https://github.com/klutchell/dnscrypt-proxy/issues/15) that I found out when looking for a solution: 

I would like to say, at least for the future, that on the raspbian version up to date with the dnscrypt-proxy from the official repos from raspbian : 
```
mars 14 20:08:39 redacted sudo[3298]: pam_unix(sudo:session): session closed for user root
mars 14 20:08:39 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:39] [NOTICE] Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [WARNING] /etc/dnscrypt-proxy/relays.md: open sf-t6o45zek5ewbhi45.tmp: permission denied
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [WARNING] /etc/dnscrypt-proxy/relays.md.minisig: open sf-mvw7i6ykum2va3jp.tmp: permission dmars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [NOTICE] Source [relays.md] loaded
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [ERROR] Invalid or unsupported stamp: [sdns://gQ01MS4xNTguMTY2Ljk3]
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [CRITICAL] Unable to use source [relays]: [Unsupported stamp version or protocol]
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [NOTICE] dnscrypt-proxy 2.0.19
```

I've followed the advice of @jedisct1 to put 777 and the user is `_dnscrypt-proxy` group `nogroup `. Problem process from official repo is in root. So I don't know who is maintaining this repo but that would be nice to put a notice to them ? 

Thanks in advance

**Comment by jedisct1** [comment]
Looks like you're mixing a recent configuration with an old server.

> mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [ERROR] Invalid or unsupported stamp: [sdns://gQ01MS4xNTguMTY2Ljk3]
> mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [CRITICAL] Unable to use source [relays]: [Unsupported stamp version or protocol]

Version 2.0.19 is very old and DNS relays didn't exist at that time.

Maybe start with the default configuration from that version? It may solve the permission issue at the same time.

**Comment by jedisct1** [comment]
```text
mars 14 20:08:39 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:39] [NOTICE] Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [WARNING] /etc/dnscrypt-proxy/relays.md: open sf-t6o45zek5ewbhi45.tmp: permission denied
```

There are paths in two completely different locations. Looks like `/var/cache/dnscrypt-proxy` is what your system installation expects, not `/etc/dnscrypt-proxy`.

All the supported features are in the default `example-dnscrypt-proxy.toml` file shipped with the package you installed. 

Start from this, so that you will know what options are available for your version. Anything else from a more recent version is not going to work.
