### ISSUE TITLE
unsupported keys

### ISSUE THREAD

**Issue by changemenemo** [DNSCrypt/dnscrypt-proxy#1641]
Sorry but I have a question that have been unresolved until now that I4ve read [this ](https://github.com/DNSCrypt/dnscrypt-proxy/issues/1410) and sorry to reopen this. 
2.0.19 on raspbian is the official version available. 
So this:
`dnscrypt-proxy[3243]: [2021-03-14 20:06:01] [FATAL] Unsupported key in configuration file: [block_undelegated]`

is relevant to last version 2.0.45 then? Since the other guy was using 2.0.44 and it was still nto accepted... 
I'm having the same problem but my version is then way older because of using the raspbian version.

Also I was understanding the error message as an actual key for the server that would need to be present so I've been turning this around for hours without understanding. In place of key I would maybe suggest the word `keyword ` . I know that key here is appropriate in this context but it can still lead to misunderstanding since we can talk about dnssec keys, a key file or other things that are also present in this context for this piece of software...

**Comment by jedisct1** [comment]
I don't think that feature existed in version 2.0.19 either.
