### ISSUE TITLE
problem in comprehension of listening addresses between service and socket 

### ISSUE THREAD

**Issue by changemenemo** [DNSCrypt/dnscrypt-proxy#1642]
Sorry I'm going maybe to ask a dumb question but I have troubles to find actual clear documentation about this: 

the only place I could find which is in archlinux [wiki ](https://wiki.archlinux.org/index.php/Dnscrypt-proxy)

it talks about : 

> Socket method
> 
> Edit dnscrypt-proxy.socket with the following contents:
> 
> [Socket]
> ListenStream=
> ListenDatagram=
> ListenStream=127.0.0.1:53000
> ListenStream=[::1]:53000
> ListenDatagram=127.0.0.1:53000
> ListenDatagram=[::1]:53000
> When queries are forwarded from the local DNS cache to 53000, dnscrypt-proxy.socket will start dnscrypt-proxy.service.
> 
> Service method
> 
> Edit the listen_addresses option in /etc/dnscrypt-proxy/dnscrypt-proxy.toml with the following:
> 
> listen_addresses = ['127.0.0.1:53000', '[::1]:53000']

but before that it talks about : 

> The service can be started in two mutually exclusive ways (i.e. only one of the two may be enabled):
> 
> With the systemd service dnscrypt-proxy.service.
> The listen_addresses option must be configured (e.g. listen_addresses = ['127.0.0.1:53', '[::1]:53']) in the configuration file when using the service.
> Through socket activation using dnscrypt-proxy.socket.
> The listen_addresses option must be set to empty (i.e. listen_addresses = [ ]) in the configuration file, since systemd is taking care of the socket configuration.

and from what I've just experienced: 
1/ I have to specify a address and a port for the socket part so it doesn't use systemd
2/ I have to modify the systemd-resolved service too
3/ I have to specify a different port for the service part in toml

Where I was under the impression that actually I had to specify a port and a adress in the socket part and so this adress would be the one used by the service also but apparently not. (which yes i know it's consistent but still) 

A piece of documentation about that, putting that into light would be nice. 
Obviously here I've specified a cache setting (so I guess the socket has been triggered then?) and so the superior layer, here the service is calling the socket layer which will do the actual request and cache everything ? 
And I'm asking it because from my udnerstanding of reading this, I was more under the impression that specify an address in service would deactivate socket and leaving it blank would make systemd configuring the socket part on its own and make the service using the same address...

**Comment by jedisct1** [comment]
Official documentation is here: https://github.com/DNSCrypt/dnscrypt-proxy/wiki

For Linux (just follow the generic instructions) https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux

Issues found on other websites should be reported to these other websites :)
