### ISSUE TITLE
Can't bind address

### ISSUE THREAD

**Issue by PawelGluszek** [DNSCrypt/dnscrypt-proxy#1644]
## Subject
I'm running PiHole and DNSCrypt on same raspberry pi.

## Description
OS: Raspbian GNU/Linux 10 (buster)
I tried setting up DNSCrypt for my network, after rebooting pi i have this error:
`
[2021-03-22 12:49:07] [NOTICE] dnscrypt-proxy 2.0.45
[2021-03-22 12:49:07] [NOTICE] Network connectivity detected
[2021-03-22 12:49:07] [FATAL] listen udp 127.10.10.1:5350: bind: address already in use

`

I tried adding this to `/etc/systemd/system/dnscrypt-proxy.service` but didn't help
`
Wants=network-online.target
After=network-online.target

`
Here is my PiHole DNS config:

![Screenshot_20210322_125506](https://user-images.githubusercontent.com/29426967/111986217-f10e1600-8b0d-11eb-95eb-de6e890dc166.png)

What should I do to fix this?

**Comment by jedisct1** [comment]
Maybe it's already running and you're trying to run it twice?

**Comment by PawelGluszek** [comment]
Output of  `/dnscrypt-proxy -resolve openwrt.org`


```Resolving [openwrt.org] using 127.10.10.1 port 5350

Resolver      : 162.158.101.17
Lying         : no
DNSSEC        : yes, the resolver supports DNSSEC

Canonical name: openwrt.org.

IPv4 addresses: 139.59.209.225
IPv6 addresses: 2a03:b0c0:3:d0::1af1:1

Name servers  : ns3.digitalocean.com., ns1.digitalocean.com., ns2.digitalocean.com.
DNSSEC signed : no
Mail servers  : 1 mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : -
````
Is it working?

**Comment by jedisct1** [comment]
Stop the proxy. If you can't do DNS resolutions any more, you were using it :)

**Comment by PawelGluszek** [comment]
I used `./dnscrypt-proxy -service stop` and used `./dnscrypt-proxy -resolve google.com` and it didn't resolve dns but why I have to stop service to get it working?

**Comment by jedisct1** [comment]
Errr... you don't have to stop it to get it working. If resolution doesn't happen any more when it's stopped, it means that you were using it. Start it again :)
