### ISSUE TITLE
I want to stop polling to .toml file.

### ISSUE THREAD

**Issue by yutayu** [DNSCrypt/dnscrypt-proxy#1645]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description
When I use this command , it seems dnscrypt-proxy polls .toml file much.
sudo iotop -oPa
I want to stop polling to .toml file.

**Comment by jedisct1** [comment]
The configuration file is only read once once the server starts.

Make sure you understand the command you are typing.

Maybe you have a configuration error and some script which is trying to constantly restart the server, even if the configuration has a syntax error?

In doubt, uninstall it and start over.

**Comment by yutayu** [comment]
I found config error . Thanks.

**Comment by yutayu** [comment]
I couldn't fixt it.
apt show dnscrypt-proxy
Package: dnscrypt-proxy
Version: 2.0.19+ds1-2

I will check more.

**Comment by yutayu** [comment]
@jedisct1 
dnscrypt-proxy saves and reads cached query to/from disk?

**Comment by yutayu** [comment]
#Empty listen_addresses to use systemd socket activation
listen_addresses = []
#server_names = ['cloudflare']
#server_names = ['jp.tiar.app']
server_names = ['dnscrypt-jp-blahdns-ipv4']

block_ipv6 = true
#cache = true
#cache = false
cache_size = 2048
cache_min_ttl = 21600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[query_log]
#file = '/var/log/dnscrypt-proxy/query.log'

[nx_log]
#file = '/var/log/dnscrypt-proxy/nx.log'

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

**Comment by yutayu** [comment]
fixed.
I reinstalled dnscrypt-proxy and wrote same config on .toml file.
Polling stopped.
Thanks  and excuse me.

**Comment by yutayu** [comment]
Sorry .
It reproduces again.

I will check more.
uname -a
Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

**Comment by yutayu** [comment]
I think it was dnscrypt-proxy accesses to swap .
