### ISSUE TITLE
DNSCrypt Proxy ain't resolving

### ISSUE THREAD

**Issue by Dev380** [DNSCrypt/dnscrypt-proxy#1647]
## *What* is affected by this bug?
DNS resolving

## *When* does this occur?
Whenever I access a server with a domain name

## *Where* does it happen?
Everywhere on my computer

## *How* do we replicate the issue?

Install 2.0.44+ds1-2
Install into service directory
Change resolv.conf to point to 127.0.0.1

## Expected behavior (i.e. solution)

DNS actually resolves

## Other Comments
DNS doesn't resolve properly for me.
```service dnscrypt-proxy status```
● dnscrypt-proxy.service - Encrypted/authenticated DNS proxy
     Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2021-03-25 19:47:52 EDT; 1min 50s ago
TriggeredBy: ● dnscrypt-proxy.socket
    Process: 20693 ExecStart=/usr/sbin/dnscrypt-proxy -config dnscrypt-proxy.toml (code=exited, status=255/EXCEPTION)
   Main PID: 20693 (code=exited, status=255/EXCEPTION)

**Comment by welwood08** [comment]
Looks to me like it's not starting properly and your service manager is repeatedly trying to restart it. Can't really suggest much without proper logs and I don't know what commands to suggest to retrieve those on your system, you probably have an error in your configuration so maybe running the application interactively would shine more light as well.
