### ISSUE TITLE
torsocks while dnscrypt-proxy is in used

### ISSUE THREAD

**Issue by matchatealeaf** [DNSCrypt/dnscrypt-proxy#1648]
`torsocks` is a wrapper to run commands under Tor. For example:
`torsocks wget duckduckgo.com` will `wget` the page via Tor.

At the same time I am using anonymized dnscrypt on my system, how does this affect `torsocks`? Will `torsocks` routes DNS queries through Tor or dnscrypt-proxy?

An older issue #1420 asked a similar question for the Tor browser.
For the Tor browser:

> If you really are just trying to use the Tor Browser, it should safely route its own DNS queries through its own instance of Tor out of the box.

However, I am not sure if this is true for `torsocks`.

Will I be better off by just configuring dnscrypt to use Tor instead of using anonymized dnscrypt?

The [wiki](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Anonymized-DNS) says:
> In order to prevent this, using DNS over Tor or over proxies (HTTP, SOCKS) has become quite common. However, this is slow and unreliable as these mechanisms were not designed to relay DNS traffic.

How significant is the decrease in speed and reliability when using dnscrypt over Tor?

**Comment by jedisct1** [comment]
Try both :)

This is the only way to know if there is a measurable difference, and what it is, for your network and the way you use it.

**Comment by jedisct1** [comment]
> Will `torsocks` routes DNS queries through Tor or dnscrypt-proxy?

This is a question about `torsocks`, so maybe a better place to ask is in their repository.
