### ISSUE TITLE
generate-domains-blocklist.py: Consider not using stderr for `load_from_url` if `output-file` is specified

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1651]
Consider the following use-case:

```
python3 generate-domains-blocklist.py -o blocklist.txt > /dev/null
```

This is on a cron file. The idea is to redirect domain output to a file and any stdout to `/dev/null`, so that only `stderr` is output (and if so, an e-mail is sent). However, `load_from_url` uses `stderr` always:

```
sys.stderr.write("Loading data from [{}]\n".format(url))
```

This is not an "error" and I think `stdout` should be used if the `output-file` switch is specified.

**Comment by lifenjoiner** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/blob/873522c7f75175b472a5c0ac7cb4ed29e8d80904/utils/generate-domains-blocklist/generate-domains-blocklist.py#L204-L207
Will this help?

**Comment by jedisct1** [comment]
Having that message sent to `stdout` would indeed make sense, even though a different behavior according to the output type may not feel very intuitive.

The least horrible way to support this would be to add a global for the output stream of "informative" messages. Having to introduce a global is sad, but well...

**Comment by lifenjoiner** [comment]
I was suggesting maybe @remyabel can use:
`python3 generate-domains-blocklist.py -o blocklist.txt 1>Y.txt 2>N.txt && <do_A> || <do_B>`
All messages wrote in `stderr` also works (with more details).

Test case `test-exit.py`:
```python
import sys

sys.stdout.write("stdout\n")
sys.stderr.write("stderr\n")

ret = 0
if len(sys.argv) > 1:
    ret = int(sys.argv[1])

exit(ret)
```
With **non-zero exit code**, `python test-exit.py 1 1>Y.txt 2>N.txt && echo "Y" || echo "N"` works as "N" is displayed.


Anyway, It has been fixed :)
