### ISSUE TITLE
TTL limits not honored

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1654]
Starting from 2.0.45 TTL limits in the TOML aren't properly honored anymore:

If one resolves a domain and then sends a 2nd query during the cache period the actual TLL can be much longer then the expected one, actually up to twice as long.
E.g. resolve 'github.com' with default TOML says it has a 40min TTL. Now send a 2nd query after 39min, so it's served from the cache, again having a TTL of 40min. You end up with an actual TTL of 39min + 40 min = 79min, instead of the intended 40 min.

If that's the new intended behaviour, you should rename TTL (e.g. TTBC = time to be cached) to avoid confusion and lower the current TTL values in the TOML. We then would also need a new way how to limit the actual TTL.

Verified on Windows and Linux. Not tested, but Mac treats TTL differently, right?

This is a direct consequence of bug [#1624](https://github.com/DNSCrypt/dnscrypt-proxy/issues/1624).

Ah, and btw. there's still one mention of the term 'whitelisting' in 'dnscrypt-proxy.log' when using an allowed-names list.

**Comment by jedisct1** [comment]
Can you please open a discussion about this first?

Thank you.
