### ISSUE TITLE
More details how to redirect / check port redirection from 53 -> 5353

### ISSUE THREAD

**Issue by rootTHC** [DNSCrypt/dnscrypt-proxy#1665]
The command `dig @localhost -p 5353 google.com` works fine (as expected).

However, `netstat -an | grep 53` shows nothing listening on port 53. Using `dig @192.168.1.1 google.com` does not work (where 192.168.1.1 is the USG's ip).

Helpful to get more information to configure or check that port forwarding from 53 to 127.1:5353 is working.

-s

**Comment by jedisct1** [comment]
Hi!

The issue tracker is for tracking bugs.

For help with Linux and other discussions, please use the [discussions](https://github.com/DNSCrypt/dnscrypt-proxy/discussions) section, thanks!

**Comment by rootTHC** [comment]
it appears that UBNT upgraded the dnsmasq package and the new version fails on options from the previous version of dnsmasq (dnssec-check-unsigned). It fails ungracefully when encountering that option:
/etc/init.d/dnsmasq restart
dnsmasq: unsupported option (check that dnsmasq was compiled with DHCP/TFTP/DNSSEC/DBus support) at line 17 of /etc/dnsmasq.conf.

Solution: disable service dns forwarding options dnssec-check-unsigned solved this).

The 2017 documentation for dnscrypt-proxy recommended this setting. So when upgrading from the 2017 dnscrypt-proxy to the latest I guess this should be mentioned in the documentation...

-s
