### ISSUE TITLE
IP set in 'blocked-ips.txt' file is not blocked 

### ISSUE THREAD

**Issue by Grimst** [DNSCrypt/dnscrypt-proxy#1677]
## This is a test i just do it now 

**My ".toml" config file contains the blocked-ips section like this :** 
```
[blocked_ips]
  blocked_ips_file = 'blocked-ips.txt'
  log_file = 'blocked-ips.log'
  log_format = 'tsv'
```
**My "blocked-ips.txt" file contains 1 valid line :**

```34.70.138.19```

**i restart my dnscrypt-proxy and i check the above ip (34.70.138.19)**

**My 'blocked-ips.log' file seems to say me that's the website is blocked :**
```
[2021-04-20 16:50:51]	127.0.0.1	forkmonitor.info	34.70.138.19	34.70.138.19
[2021-04-20 16:50:57]	127.0.0.1	forkmonitor.info	34.70.138.19	34.70.138.19
```
**BUT in fact i receive a html response ??! :**   
```
<!DOCTYPE html>
<html>
  <head>
    <title>Fork Monitor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <script src="/packs/js/forkMonitorApp/index-8b94ce323697e78636ef.js"></script>
    <link rel="stylesheet" media="screen" href="/packs/css/forkMonitorApp/assets/stylesheets/bootstrap-8decb790.css" />
    <link rel="stylesheet" media="screen" href="/packs/css/forkMonitorApp/assets/stylesheets/app-bc1ce00c.css" />
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon-d5c76621d806ce538c76674a9639b16bcea576ff5f9336c497124a511e5b2fe2.png">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32-4b5c16fe33d131b53017fcdfc26bc0264c91423e9a0761f221d42c5829142f0f.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16-b6c628da1633e717954fd19fba07e16b66f398cad290c5bff623dd848233d1bd.png">
<link rel="manifest" href="/assets/site-2d7cbccb6581fb0eaac523202aeb18ab204e6abc623639764a14215c024ca6be.webmanifest">
<link rel="mask-icon" href="/assets/favicon/safari-pinned-tab-b336422bf815787ab757f8995200e64640b4d121528db309c3774c415ab74975.svg" color="#5bbad5">
<link rel="shortcut icon" href="/assets/favicon/favicon-b8b54fea0b4f2184de059c794bcec31ce4cee89d7acf178089faf70ec66a40fe.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/assets/favicon/browserconfig-7d11057c87a1e7d9b05c410cf8b4249fb109c8b412e279fefab89deae0d4064a.xml">
<meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <div id='fork-monitor-app'></div>
  </body>
</html>
```

**Comment by jedisct1** [comment]
The log shows that DNSCrypt-proxy sent a blocked response.

Maybe you have multiple resolvers configured, and your system retried with other ones?

Try sending a query directly to the proxy (with a command such as `dig` or with `dnscrypt-proxy -resolve`) to verify what response you get. The proxy cannot change anything to what happens after the response has been sent.

**Comment by Grimst** [comment]
Hi, 

thanks for the reply and your time to read my answer.

For me, it's a non-sens to say "Maybe you have multiple resolvers configured, and your system retried with other one" because if you have a file called "blocked-ips.txt" the proxy should blocks even the ip for resolver X or the resolver Y, Z, etc., but the problem is not here because i have 1 resolver in my file (server_names = ['ibksturm']).

And i test with another one, the resule is the same, i have a REJECT in the log : **with youtube.com for exemple, it works, i have REJECT and i have a NXDOMAIN diplayed in my browser .. but with forkmonitor.info i don't have the same behaviour, why ?**

Please, Can you do the test  ? =>  i try to block this domain name (https://) forkmonitor.info (ip = 34.70.138.19)  


the log say : 

```
[2021-04-21 13:29:27]	127.0.0.1	forkmonitor.info	AAAA	REJECT	15ms	-
[2021-04-21 13:29:27]	127.0.0.1	forkmonitor.info	AAAA	REJECT	0ms	-
[2021-04-21 13:29:27]	127.0.0.1	forkmonitor.info	AAAA	REJECT	0ms	-
[2021-04-21 13:29:27]	127.0.0.1	forkmonitor.info	AAAA	REJECT	10ms	-
[2021-04-21 13:29:27]	127.0.0.1	forkmonitor.info	AAAA	REJECT	0ms	-
```
 BUT in fact it's not true.
thanks in advance for taking time to do this test
i'm a bit lost

Steve

**Comment by jedisct1** [comment]
```sh
./dnscrypt-proxy -resolve forkmonitor.info
```

```text
Resolving [forkmonitor.info] using 127.0.0.1 port 53

Resolver      : 212.47.228.136 (scaleway-fr.dnscrypt.info.)

Canonical name: forkmonitor.info.

IPv4 addresses: -
IPv6 addresses: -
```

```sh
dig forkmonitor.info @127.0.0.1
```

```text
forkmonitor.info.	1	IN	HINFO	"This query has been locally blocked" "by dnscrypt-proxy"
```

Looks fine!

**Comment by jedisct1** [comment]
> For me, it's a non-sens to say "Maybe you have multiple resolvers configured, and your system retried with other one" 

Sorry if it was confusing. I was referring to your system DNS configuration (or whatever is sending queries to `dnscrypt-proxy` such as `dnsmasq`).

**Comment by Grimst** [comment]
## Thanks to much jedisct1 

i seee where is probably the problem.

I try like you the cmd command :  

**C:\Program Files\dnscrypt-proxy-win64-2.0.45\win64>dnscrypt-proxy -resolve forkmonitor.info**
```
Resolving [forkmonitor.info] using 127.0.0.1 port 5353

Resolver      : 140.238.215.192

Canonical name: forkmonitor.info.

IPv4 addresses: -
IPv6 addresses: -

Name servers  : server returned REFUSEDDNSSEC signed : no
Mail servers  : no mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : -
```

###    **OK**  i have the same behaviour than you 👍 


###  Next, when i try with the url with my browser [https://forkmonitor.info](https://forkmonitor.info), **Badabuuuum**
=> i have a html response and not a NXDOMAIN like youtube.com or facebook.com or other website ! ?

### i suspect that ths url is NOT with **WWW** or **someting** (dot)forkmonitor(dot)info but just **forkmonitor.info**

and i have in my 'blocked-names.txt' file :  
```
forkmonitor.info
youtube.com
```

with **youtube.com** it's works fine ([https://www.youtube.com](https://www.youtube.com) or [https://m.youtube.com](https://m.youtube.com)) i received a NXDOMAIN !

but not with [https://forkmonitor.info](https://forkmonitor.info) i have a html response. i tink it's maybe because probably i dont have the **WWW** or **SOMETHING** behind the domain name ? 
### do you have a solution to have the same behaviour than ([https://www.youtube.com](https://www.youtube.com) or [https://m.youtube.com](https://m.youtube.com)) and to receive A NXDOMAIN (and display by the browser) ?

# Thanks in advance for your work, it's a great great tool
Steve

**Comment by jedisct1** [comment]
> OK i have the same behaviour than you 

Great! The proxy returned the expected response, so this doesn't seem to be a bug.

If you want help with something involving DNS configuration and your particular environment and web browser, feel free to open a discussion instead.

**Comment by Grimst** [comment]
Thanks for your time jedisctl1, i will investigate for my case.

Regards,
Steve
