### ISSUE TITLE
Are all these connections necessary?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [DNSCrypt/dnscrypt-proxy#168]

**Comment by jedisct1** [comment]
Yes.

**Comment by GitTheHellOutaHere** [comment]
Ha - I didn’t think I posted yet, I left the editor to do other things.

But here’s the post I was working on:

I keep getting alerts in Little Snitch.

Of course there’s the usual ports which I’ve allowed - 443, 53, 5353.

But others I’m not familiar with:
UDP port 553 (pirp)
UDP port 1053 (remote-as)
UDP port 2053 (lot105-ds-upd)
