### ISSUE TITLE
blocked_names_file block not working for all domains in the blacklist.

### ISSUE THREAD

**Issue by newedgex** [DNSCrypt/dnscrypt-proxy#1688]
1) I'm using 2.0.45 on Arch and it's working fine (check displays no output and it resolves the domains correctly).
2) I have created a blacklist using generate-domains-blocklist and a configuration file that generated the below list.
[big-blacklist.txt](https://github.com/DNSCrypt/dnscrypt-proxy/files/6371606/big-blacklist.txt)
3) In order to test I started using drill to test the domains included in the blacklist (from the top to the bottom) and found out that while some of the domains included in the blacklist where blocked correctly : 

`
;; ANSWER SECTION:
marketing2.globalpointofcare.abbott.	1	IN	HINFO	"This query has been locally blocked" "by dnscrypt-proxy"
;; ANSWER SECTION:
smetrics.citibank.ae.	1	IN	HINFO	"This query has been locally blocked" "by dnscrypt-proxy"
`

others where not : 
`
;; ANSWER SECTION:
af89dacd-4aec-4ac1-9d52-2a66ce5e4fb5.edge.permutive.app.	300	IN	A	104.18.5.81
af89dacd-4aec-4ac1-9d52-2a66ce5e4fb5.edge.permutive.app.	300	IN	A	104.18.4.81
;; ANSWER SECTION:
stats.qawl.app.	3600	IN	CNAME	custom.plausible.io.
custom.plausible.io.	300	IN	A	46.101.161.209
`
## To reproduce
1) Download the blacklist file (or generate your own, I reproduced the problem also without my "specific" list)
2) restart dnscrypt-proxy 
3) try resolving the blacklisted domains and you will actually end up resolving around 40% of them.

NOTE: it doesn't seem to be related to formatting or the banlist.txt file syntax since it's not like the domains that fails to be banned has a specific pattern or domains below it are actually all bypassing the ban.

**Comment by jedisct1** [comment]
Trying to rephrase as a bug report:

1. Download and install dnscrypt-proxy 2.0.45:

```sh
curl -L https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.45/dnscrypt-proxy-linux_arm64-2.0.45.tar.gz | tar xzf -
cd linux-*
```

2. From the default configuration, enable blocked names. And query logs, which are often useful to understand configuration errors:

```sh
cat example-dnscrypt-proxy.toml | sed -e "s/# blocked_names_file/blocked_names_file/" -e "s/# file = 'query.log'/file = 'query.log'/" > dnscrypt-proxy.toml
```

3. Remove/disable anything listening to `127.0.0.1:53`, including other `dnscrypt-proxy` instances. See the documentation for details. Verify that this is actually the case, and that without `dnscrypt-proxy` running, queries don't get a response:

```sh
./dnscrypt-proxy -resolve example.com
```

```text
Resolving [example.com] using 127.0.0.1 port 53

Unable to resolve: [Timeout]
```

4. Download the "big blacklist" as the `blocked-names.txt` file:

```sh
curl -L https://github.com/DNSCrypt/dnscrypt-proxy/files/6371606/big-blacklist.txt > blocked-names.txt 
```

5. Start the proxy:

```sh
sudo ./dnscrypt-proxy -check
sudo ./dnscrypt-proxy
```

6. In another terminal, go back to the previous directory and check that `af89dacd-4aec-4ac1-9d52-2a66ce5e4fb5.edge.permutive.app` is blocked:

```sh
./dnscrypt-proxy -resolve af89dacd-4aec-4ac1-9d52-2a66ce5e4fb5.edge.permutive.app
```

Expected result: prints `This query has been locally blocked by dnscrypt-proxy`
Actual result: prints IP addresses

---

Unfortunately, I wasn't able to reproduce this. The last step properly prints:

```text
Resolving [af89dacd-4aec-4ac1-9d52-2a66ce5e4fb5.edge.permutive.app] using 127.0.0.1 port 53

Resolver      : 165.232.32.95 (do.dnscrypt.uk.)

Canonical name: af89dacd-4aec-4ac1-9d52-2a66ce5e4fb5.edge.permutive.app.

IPv4 addresses: -
IPv6 addresses: -

Name servers  : no name servers found
DNSSEC signed : no
Mail servers  : no mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : This query has been locally blocked by dnscrypt-proxy
TXT records   : -
```

Can you confirm that you got IP addresses and not the blocked message when following the exact steps above?

**Comment by jedisct1** [comment]
> try resolving the blacklisted domains and you will actually end up resolving around 40% of them.

To reproduce, after step 6 above, type:

```sh
for i in $(grep -vE '^(#|$)' blocked-names.txt | head -n 100); do
  ./dnscrypt-proxy -resolve "$i" | grep -F Host ;
done
```

Expected result: prints `This query has been locally blocked by dnscrypt-proxy` 100 times.
Actual result: prints `This query has been locally blocked by dnscrypt-proxy` 40 times.

---

Unfortunately, I wasn't able to reproduce this either. The command above prints the blocked message 100 times.

**Comment by newedgex** [comment]
I rebooted now and somehow it worked, I tried 1000 blacklisted hosts. Closing.
