### ISSUE TITLE
Still wondering what all these connections are for

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [DNSCrypt/dnscrypt-proxy#173]
Since the issue was closed without an answer I’m asking again.

I keep getting alerts for dnscrypt-proxy in Little Snitch.

I’ve allowed the usual ports - 53, 443, 5353.

But I’m not familiar with:

UDP port 553 (pirp)
UDP port 1053 (remote-as)
UDP port 2053 (lot105-ds-upd)
UDP port 4434 (unassigned)

**Comment by ghost** [comment]
I think those are the ports of the servers you are using.

For example, this opennic server:

https://servers.opennic.org/edit.php?srv=ns1.any.dns.opennic.glue

Under dnscrypt, look at ipv4 ports:

54, 443, **1053**, 1194, 5353, 8080, 27015

Or the Soltysiak server:

178.216.201.222:**2053**

**Comment by GitTheHellOutaHere** [comment]
Makes sense.
All the OpenVPN servers I use go through ports in the 1000-2000 range.
But that doesn’t explain the purpose of 553 and 2053.

Port lot105-ds-upd is registered as DSuper Updates. So what’s that for?

Port 553 is unassigned, so I guess it can be used for anything; So what’s it being used for?

So I really need to allow connections to any port like I’ve done for my VPN client.
But I like to know what a port is for before I throw its doors open.

DNSCrypt is supposed to somehow provide more security, yet it’s causing me to open up a lot of unfamiliar ports.

**Comment by GitTheHellOutaHere** [comment]
Internet connection still works with ports 553, 1053, 2053, 4434 blocked.

**Comment by jedisct1** [comment]
If a resolver is not reachable for whatever reasons, it will be ignored, so you will be only using a subset of what you configured.
The ports you are referring to are destination ports, not source ports, so you don't need to "open" any of these on your firewall.
