### ISSUE TITLE
Android: -resolve option shows old resolver IP after stopping dnscrypt-proxy

### ISSUE THREAD

**Issue by Sporif** [DNSCrypt/dnscrypt-proxy#175]
This only happens on my phone, windows works fine. Haven't tested linux yet. The strange part is that after some time (haven't tested how long) it gives the correct default resolver IP.

STR:

```
./dnscrypt-proxy 
# Starts normally

./dnscrypt-proxy -resolve google.com
# gives correct resolver from .toml

kill pidof 'dnscrypt-proxy'

./dnscrypt-proxy -resolve google.com 
# still gives resolver from .toml

# wait some unknown amount of time

./dnscrypt-proxy -resolve google.com 
# now correctly gives default resolver 
```

**Comment by jedisct1** [comment]
`-resolve` resolves the name exactly as other applications on your system would. For debugging purposes, this is more useful than tools such as `nslookup` that use a completely different path.
I guess Android has its own local cache, so it doesn't always hit the proxy to return a response.

**Comment by Sporif** [comment]
Yeah looks like an android issue, the cache is kept for 10 mins it seems. And I can't find a way to clear it. Though it's strange how dnsleaktest.net gives the right resolver immediately.

**Comment by jedisct1** [comment]
Because they resolve random names, that are unlikely to be cached.

You can resolve `somerandomname.resolver.dnscrypt.info` as well to get the same result.
