### ISSUE TITLE
Using dnscrypt-proxy on android

### ISSUE THREAD

**Issue by MF-Debug** [DNSCrypt/dnscrypt-proxy#176]
i can not figure out how to use it on my device. i downloaded the zip file for arm as my device is arm. can i flash the zip file or do i have to follow any other procedures? also do i need busybox or toybox installed? any help will be very much appreciated. thanks in advance.

**Comment by jedisct1** [comment]
See https://github.com/jedisct1/dnscrypt-proxy/issues/41
