### ISSUE TITLE
Issue with latest v. 2.0.3

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#177]
DNSCrypt-proxy 2.0.3 / Firefox 58.0.2 (x64) / Windows 7SP1 (x64)

```
server_names = ['de.dnsmaschine.net', 'scaleway-fr']
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
```

I've updated to latest v. 2.0.3 and started Firefox
I opened several links : OK
I opened the following link: https://forums.malwarebytes.org/ : unresolved (network error)
I opened http://www.isitdownrightnow.com/ to check above site:: unresolved (network error)
I checked DNS leaks with https://ipleak.net/ : no DNS recognized

Closed/Restarted Firefox. Proceeded again as above mentioned: same issues

Downgrading to DNSCrypt-proxy 2.2 fixed the issue.

**Comment by jedisct1** [comment]
It would be great to have some debug logs. In order to do so, you need to define a `DEBUG` environment variable (the associated value doesn't matter) and run the proxy with `-loglevel=0`.
I don't know how to do that on Windows, though.

**Comment by ghost** [comment]
Hi Frank,

> I don't know how to do that on Windows, though

Neither do I, whatever environment by the way. Bad scenario when an issue is reported by a non-techie as myself.

All is fine with v. 2.0.2 which doesn't resolve anything except my personal comfort and maybe that of others: would be nice if a similar issue be reported by other  users.

**Comment by the-w1nd** [comment]
I can confirm the problem with https://forums.malwarebytes.org/ site with 2.0.3 release.
Downgrading to 2.0.2 resolves the problem.

Here are the log and the query-log files that I collected when opening the url: [debug_logs_v2.0.3.zip](https://github.com/jedisct1/dnscrypt-proxy/files/1752140/debug_logs_v2.0.3.zip)
The DEBUG option does not provide much information on what's going on.

**Comment by ghost** [comment]
Thanks @the-w1nd . Hopefully the log you provide will help to spot the cause. What seems surprising is that the issue is initiated by calling https://forums.malwarebytes.org/ , maybe specifically when calling other sites (the few I ran in my case) prior to this one didn't trigger any issue, and that once this issue encountered it's as if the whole DNS resolving was broken...

**Comment by jedisct1** [comment]
Having a way to reproduce this helps a lot!

I could reproduce this using that domain name. The bug has been fixed, and a new version is getting compiled now :)

**Comment by jedisct1** [comment]
/ping @bitbeans because he's been slacking off too much these days :)

(or rather because he just shipped a new version with this bug, sigh. I'm totally guilty).

**Comment by bitbeans** [comment]
@jedisct1 only in de CI build :)

**Comment by jedisct1** [comment]
slacker!!!
