### ISSUE TITLE
🎉 Celebrating 10 years of encrypted DNS! 🎉 

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#1782]
DNSCrypt is now 10 years old! 🥂

**Comment by dapphp** [comment]
Thank you for all of your hard work over the years to make the internet a safer place, be it for better encryption or privacy protocols.

You sir are a legend!

**Comment by Romulo-Romero** [comment]
Thank you for your great contribution to the community, there is no doubt this is one of the best/must have security/privacy tool created in the past 10 years. This is so true, that most of the big tech companies, have only recently started to adopt dns over tls etc, let alone the facts on the technical details . Good job and keep up the nobel work !
Note: Thanks also to everyone contributing to the expansion of this project, really outstanding stuff

**Comment by jumpsmm7** [comment]
I hope there is a pathway for another 10 years for this excellent utility. @jedisct1 and community great work, and let's continue to progress as a community for the sake of privacy, security, and anonymity.

**Comment by ghost** [comment]
Discovering then applying encrypted DNS was for me a major step in security and privacy, both with DNSCrypt, right here.
I'd like to emphasize that this fantastic work, that of a precursor, given the easiness of use, is not reserved to techies. No need to understand the elaborated code to deploy it flawlessly.
I am most grateful to @jedisct1 for his work, time, talent, for his essential contribution to a better life for us all on the Web.

**Comment by jumpsmm7** [comment]
I give kudos to @jedisct1 and devs for making dnscrypt-proxy2 flexible enough to be used on a variety of platforms.

**Comment by ianbashford** [comment]
@jedisct1 
Thank you for all the hard work you put into this project.

I've been using it reliably for many years and it's stability and takeup is a testament to the thought and work you've put into building not just great software, but a great community around it.

Maybe circumstances will allow an opportunity us to share a glass of great french wine one day...
