### ISSUE TITLE
Help: Problem when i try to install in ubuntu 16.04.03

### ISSUE THREAD

**Issue by MasterUploader** [DNSCrypt/dnscrypt-proxy#179]
When I run the command: 

> sudo / home / myusername / Dnscrypt / dnscrypt-proxy start

how appers in the documentation, the program always returns :

![captura de pantalla de 2018-02-23 14-36-51](https://user-images.githubusercontent.com/9924626/36615788-14e629e6-18a7-11e8-92b7-a7e25d375bff.png)

> sudo: dnscrypt-proxy: command not found

I already tried everything that occurred to me.

**Comment by norrkin** [comment]
Try;

sudo /home/YourUserName/Dnscrypt/dnscrypt-proxy -service install
sudo /home/YourUserName/Dnscrypt/dnscrypt-proxy -service start

Looks like that is a typo in the wiki.

**Comment by jedisct1** [comment]
On Linux, in order to run a file in the current directory, you need to prepend `./`

So: `./dnscrypt-proxy`.

**Comment by MasterUploader** [comment]
@jedisct1 
![captura de pantalla de 2018-02-23 15-18-02](https://user-images.githubusercontent.com/9924626/36617392-d4ac629a-18ac-11e8-86fc-84eea383ee51.png)

**Comment by norrkin** [comment]
sudo ./dnscrypt-proxy -service install
sudo ./dnscrypt-proxy -service start

**Comment by MasterUploader** [comment]
@norrkin 
![captura de pantalla de 2018-02-23 15-57-04](https://user-images.githubusercontent.com/9924626/36618824-40a3f648-18b2-11e8-9f10-7a76486043ad.png)

**Comment by jedisct1** [comment]
Maybe not the right executable for your system.

**Comment by MasterUploader** [comment]
I try 
>dnscrypt-proxy-linux_x86_64-2.0.4
>dnscrypt-proxy-linux_mipsle-2.0.4

**Comment by evilvibes** [comment]
If you follow the install wiki the way it was made there will be no issue. I installed it myself but it looks like the wiki has been edited now.

**Comment by jedisct1** [comment]
What does the following command return:

```
uname -a
```

?

**Comment by MasterUploader** [comment]
Linux brayan93-Inspiron-3421 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by norrkin** [comment]
@evilvibes 

The original cmd @MasterUploader was trying to run from the wiki was wrong so I edited it.

**Comment by evilvibes** [comment]
@norrkin The command was right for the example directory for both ubuntu and macOS.

**Comment by evilvibes** [comment]
@MasterUploader When you Extract the tar.gz file where did you put it?

**Comment by MasterUploader** [comment]
@evilvibes 
In home

**Comment by MasterUploader** [comment]
@evilvibes Now when i use the first command
![captura de pantalla de 2018-02-23 16-37-10](https://user-images.githubusercontent.com/9924626/36620303-03fb2bac-18b8-11e8-98ea-026c18767b25.png)

**Comment by evilvibes** [comment]
try this Type: 

`sudo /home/brayan93/Dnscrypt/dnscrypt-proxy start`

`sudo /home/brayan93/Dnscrypt/dnscrypt-proxy -service install`

`sudo /home/brayan93/Dnscrypt/dnscrypt-proxy -service start`

change the toml from `example-dnscrypt-proxy.toml` to `dnscrypt-proxy.toml`

**Comment by evilvibes** [comment]
@jedisct1 Maybe you should add a default `dnscrypt-proxy.toml` file seem like a lot of people have this issue.

**Comment by MasterUploader** [comment]
@evilvibes in the first commad
![captura de pantalla de 2018-02-23 16-43-02](https://user-images.githubusercontent.com/9924626/36620442-ae427ba6-18b8-11e8-99ed-eec991149bf9.png)

**Comment by evilvibes** [comment]
@MasterUploader Go the the Dnscrypt folder you made in the home directory and change rename example-dnscrypt-proxy.toml to dnscrypt-proxy.toml

**Comment by MasterUploader** [comment]
@evilvibes  That worked

@norrkin  @jedisct1 @evilvibes Thank guys

**Comment by evilvibes** [comment]
No worries i think you cd into the wrong directory that's why the commands did not work for you.

Enjoy
