### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Marco-vW** [DNSCrypt/dnscrypt-proxy#18]
Not really an issue, and maybe I'm overlooking it, but could you include a minimal changelog in the archive, so I can keep track of the changes? I just posted @ snbforums.com about how well beta 4 runs on my Asuswrt-Merlin powered router (not as a service btw, the installer messes up our folder structure, but running the executable from one of startup scripts works greay), only to find out that I'm already 4 releases behind. Keeping up with your pace and keeping track of the changes is a bit of a challenge, so something of a changelog would be much appreciated. Keep up the good work!

**Comment by jedisct1** [comment]
I can't keep up either :)

But once 2.0.0 is tagged, I'll take the time to update the change log every time.

Meanwhile, looking at what's new in the configuration file is a good way to keep track of changes.
`./dnscrypt-proxy -help` also has some new things since beta 4.

**Comment by iWARR** [comment]
@jedisct1 
Your `-help` will look more correctly and clear this way:

```
- config <string>
- loglevel <value>
- resolve <string>
- service <string>
```
