### ISSUE TITLE
[Feature] Make a difference between domain and its subdomains

### ISSUE THREAD

**Issue by t33st33r** [DNSCrypt/dnscrypt-proxy#180]
This is just a suggestion.
Can dnscrypt-proxy distingish between __*.example.com__ and __example.com__ in white/blacklists and forwarding/cloaking rules (in future versions)?
An example how to do it: *Acrylic DNS Proxy* use the character **>** to take both parts, __example.com__ only for domain, and __*.example.com__ for only its subdomains.
Thanks in advance.
Excuse my bad english, please.

**Comment by jedisct1** [comment]
Cloaking rules do exact matching, and wildcards will be implemented later.

For blocking rules, this is not planned. At least, I'm not going to do it since it is rarely useful, but if you want to implement it and it doesn't make anything slower, I'd be glad to merge your code :)

**Comment by t33st33r** [comment]
Well, then I have no other way to block some hosts using dnscrypt as secondary resolver.

Unfortunately I am not a go coder.

**Comment by jedisct1** [comment]
Sorry, it probably won't happen then :(

**Comment by iWARR** [comment]
@jedisct1 

Please, **do NOT implement** such behavior, even if you will have a code. This is not a good idea.

_Two good examples:_

**1)** If I want to block all from host "abuse.com"

```
some.bad-1.abuse.com
some.bad-2.abuse.com
```

My rule will be:

`*.abuse.com`

**2)** If I want to block connections from "cloud.com" selectively (not everything):

```
ads.host.cloud.com ............. block (have subdomains!)
more.ads.cloud.com ............. block (have subdomains!)
uploads.cloud.com .............. ALLOW (have subdomains!)
```

My rule will be:

`*.ads*`

It will work for **both** №1,2 (AS IT SHOUD BE) and also doesn't touch №3 (in case of` . `)

### Everithing working as expected, nothing to change and rework!

**Comment by t33st33r** [comment]
@iWARR , if i am right there is no way to block **example.com** without its subdomains (no matter how many they are).

@jedisct1 , I have noticed dnscrypt-proxy have *half* support of *regular expressions* (**[0-9]** is part of it)... Why not make it fully support RegExp?

**Comment by jedisct1** [comment]
Too slow.

**Comment by iWARR** [comment]
>  no way to block example.com without its subdomains

You are right. This is task for the "WiteList" option, that is not implemented yet.

But you may try to analyse resources of the site and block everything exept what you need.
It's take a bit more time (depends of your task), but still possible.

For example, you may look into `uBlock Origin` live blocking list (when you open the webite), use `Firewall` logs, `query.log` of the dnscrypt-proxy, going to `robtex.com`, and other tools.

Also, I like "**The Web, tracker free**" website an their lists + descriptions:

The Web, tracker free: 			  https://better.fyi/trackers/
Alexa Top 500 Trackers by popularity: https://better.fyi/trackers/alexa-top-500-news/

**Comment by sergeevabc** [comment]
Example: ```ad.liveinternet.ru``` is about advertisements, but ```liveinternet.ru``` is about diaries.
