### ISSUE TITLE
Cannot use public-resolvers locally

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [DNSCrypt/dnscrypt-proxy#182]
I have downloaded public-resolvers.md from upstream, then I configured dnscrypt-proxy.toml to make the main app use it locally. However I get the following message when I try to install the service:
```
D:\dnscrypt-proxy-win64>.\dnscrypt-proxy.exe -service install
[2018-02-25 00:53:31] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [] using fallback resolver [9.9.9.9:53]
[2018-02-25 00:53:31] [CRITICAL] Unable use source [local-resolvers]: [No IP found for []]
[2018-02-25 00:53:31] [FATAL] No servers configured

D:\dnscrypt-proxy-win64>.\dnscrypt-proxy.exe -service start
[2018-02-25 00:53:31] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [] using fallback resolver [9.9.9.9:53]
[2018-02-25 00:53:32] [CRITICAL] Unable use source [local-resolvers]: [No IP found for []]
[2018-02-25 00:53:32] [FATAL] No servers configured
""
Thank you for using dnscrypt-proxy! Hit [RETURN] to finish
```
So what's wrong with me? Please check.

[dnscrypt-proxy.toml.zip](https://github.com/jedisct1/dnscrypt-proxy/files/1754666/dnscrypt-proxy.toml.zip)

**Comment by jedisct1** [comment]
Hi,

Before doing something very custom, I'd recommend starting with a standard configuration as documented and as everybody else.

Remove the service (`-service uninstall`) and delete whatever files you downloaded manually. These will be downloaded automatically.

Then, make sure that your computer is configured normally, and can access the internet. Do not change the DNS settings to `127.0.0.1` yet, just have a working configuration.

Save a copy of the example configuration file as `dnscrypt-proxy.toml`. Do not change anything to it yet. Then, start the proxy without installing the service.

If it works, tweak the configuration file the way you want. Every time you change something, check that the proxy can still be started (not as a service yet).

Eventually, when you get to something that fits you needs and works, install it as a service and change your DNS settings.

**Comment by jedisct1** [comment]
Closing, because after looking at your configuration file, you will find your mistake by following the process above. I promise.

**Comment by KrasnayaPloshchad** [comment]
I know what's wrong with me. If I missed public-resolvers.md.minisig, then the resolver list become illegal, but when I get minisig from remote server, it works.

**Comment by KrasnayaPloshchad** [comment]
Althrough I get both md and minisig files, they works for me only one day, then I've to reconfigure and redownload the resolver list in the next day, that's weird. Anyway I'll try 2.0.6 to see what will happen.

**Comment by jedisct1** [comment]
That's expected. Cache files expire according to what you set the `refresh_delay` value to.

**Comment by KrasnayaPloshchad** [comment]
Thank you very much.

**Comment by KrasnayaPloshchad** [comment]
The problem appearing to me again even if I set `refresh_delay=65536`.
