### ISSUE TITLE
Virustotal results 4 / 68

### ISSUE THREAD

**Issue by MojtabaFaal** [DNSCrypt/dnscrypt-proxy#1821]
Hi
I searched the file on **Virustotal** website and it says that the file has a virus?
[https://www.virustotal.com/gui/file/b1a3091b7380768f1f3b1e6e964e29f94263a3c2f068e9c8b7de1dad43db8a52/detection](https://www.virustotal.com/gui/file/b1a3091b7380768f1f3b1e6e964e29f94263a3c2f068e9c8b7de1dad43db8a52/detection)
Seriously?
Why ?
What is the problem ?

**Comment by Kaiyangshi-Ito** [comment]
Same question.
