### ISSUE TITLE
Fallback_resolver throws fatal error instead of warning

### ISSUE THREAD

**Issue by Ing-Med** [DNSCrypt/dnscrypt-proxy#1826]
I am gonna keep this really short. Just after the update which was deployed right now, the docker container instance will crash when using fallback_resolver in the .conf file, instead of showing a warning as mentioned in the changelogs. 

`
[2021-08-15 19:36:00] [FATAL] Unsupported key in configuration file: [fallback_resolver]
`

**Comment by jedisct1** [comment]
`fallback_resolver` has been deprecated since version 2.0.38.
