### ISSUE TITLE
[ENHANCEMENT] : Blocking Rules - Left Wildcard (A bit more flexibility)

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#184]
**If I want:**
```

head.pic.example.com ........................... allow
frame.pic.example.com .......................... allow

pic.banner.example.com ......................... block
pic.ads.example.com ............................ block
pic.abuse.example.com .......................... block
```

**Rules:**

 - `*.pic.*` - Today behavior (leave as it is) - Will block everything here, as usual.
- `pic.*` - Proposition (enhancement) - Add selective blocking possibility as extra option

Would be nice have a different effects depending on` *.  `presence at the BEGINNING of rule.
(LEFT wildcard).

-- if rule have left ` *.  `at the beginning, all blocking works as usual
-- if rule miss left ` *.  `at the beginning, this talk to algo: "this is EXACTLY BEGINNING of the searched domain name".

Lets imagine that rule `*.pic.*` (will block all, ok) is not same as `pic.*` or `pic*` (will block the last 3 only)

- **Missing** of the left wilcard+dot ` *. ` in the RULE (`pic.*` or `pic*`) says to algo:

--- this rule `pic.*` mean BEGINNING of the searched name: `pic._______`
--- compare, select and calculate names with SAME FIRST letters ONLY
--- try make a substitution in final algo result within `www.pic. _______`
--- send command to block such domains

- **Presence** of the left  wilcard+dot ` *. ` in the RULE (`*.pic.*` or `*pic*`) means full blocking anywere, as usual.

_Not sure how to workaround with `www.` (and etc. auto-substitutions).
May be it's not a problem, if algo sorting first, then making substitution for "positive" results only._

**BENEFITS**

[+] Better flexibility (**local small "WhiteList"** is possible in some situations)
[+] Faster algo skipping mismatched lines :)  _(my guess)_

**DISADVANTAGES**

[-] Need more accuracy during rules creating.
[-] Partially incompatible with older lists, that have to be corrected (if any)
[-] No mention, how hard to implement. Headake for you ;)

**NEUTRAL**

(•) Help description is a MUST

_Will be this proposition a GOOD option? How do you think?_

**Comment by jedisct1** [comment]
That looks very complicated, and I'm not sure I follow.

The rule `example.com` matches:

`example.com`
`www.example.com`

A slightly different rule `^example.com` would only do exact matching, not suffix matching. So it would match:

`example.com`
but not `www.example.com`

Would that `^` operator solve your problem?

**Comment by jedisct1** [comment]
Maybe `=` would make more sense than `^`, but this is not really important.

**Comment by iWARR** [comment]
It's not about `www.` suffix, but about smarter algo.
I know such domain selections, when you don't want block all, but only first couple of `sub. `

If it's too complicated, you may leave this task for the future, may be.
And I don't have any problems, it's just a smarter option to select a domains.
(Like a local **small "WhiteList"**, you know)

Thank you for your time and answers :+1:

**Comment by jedisct1** [comment]
If it can't be described in a single paragraph, it's probably way too complicated even for users.

**Comment by iWARR** [comment]
You may close this thread in case it's not a "problem".
I think, you have more important tasks with GO in the list.
I guess it's not right time for this option, but you will return to it later.
So, you may Close this, but don't delete.

It will be OK for the users and useful with mine :) a bit simplified description. (In future, may be).
Asking users also will be helpful a lot :))))))

**Comment by iWARR** [comment]
I thinked about such option many times, that because my Blocklist is already "compatible" for such implementation (for important domains). Regardless it still "under construction". 

But other users would must "adopt" their lists, or it would skip a blocking. This is main disadvantage.
