### ISSUE TITLE
Test certificate expiration and supply options through arguments

### ISSUE THREAD

**Issue by raidenii** [DNSCrypt/dnscrypt-proxy#185]
Hello Frank,

First of all thanks for pushing DNSCrypt to 2.0 and continues the development of this awesome project!

I came into the issue of utilizing dnscrypt-proxy in the rotation of keys for dnscrypt-wrapper. As mentioned in the Key Rotation section of README.md of dnscrypt-wrapper, we can use dnsproxy-proxy 1.x to detect if the certificate of server is going to expire in a certain time period, such as:

```
$ dnscrypt-proxy --resolver-address=127.0.0.1:443 \
                 --provider-name=2.dnscrypt-cert.<yourdomain> \
                 --provider-key=<provider_public_key> \
                 --test=10080
```

And I use this function in the auto-rotation of my certificates on the server.

But now as of 2.0, it seems that test argument is no longer valid, and dnscrypt-proxy does not allow user to connect to a server through arguments, but only using configuration files.

Is it possible to add back this function, so that dnscrypt-proxy can still be used in automated scripts?

Thanks!

**Comment by jedisct1** [comment]
The configuration file can hardly be expressed as command-line switches, and that would be very messy.

But maybe a `-test=<delay in minute>` option, that checks if all certificates will still be valid within that delay?

For DoH, it means checking all the chain of all SSL certificates. Not fun :(

Anyway, yes, it can be good to have.

**Comment by jedisct1** [comment]
For DoH we need to make sure that this also verifies that for every SSL certificate chain, there is at least one matching the optional signature of the corresponding stamp.

**Comment by raidenii** [comment]
Right, I forgot about the DoH one. But if we have to use configuration file, we can specify the test option only valid for dnscrypt servers, at least for now?

**Comment by jedisct1** [comment]
Err.. no. If we add this, it has to work properly with all current and future protocols.

**Comment by jedisct1** [comment]
Done in 2158674d17133b712efd1a70c2bdfde688bb1691 but I don't like it much.

Maybe a small, dedicated tool would make more sense than having that in the client proxy.

**Comment by raidenii** [comment]
I agree. A separated tool will fulfill this purpose better. Thanks for the effort still!
