### ISSUE TITLE
[Need Help] With DNSCrypt server with vultr.com

### ISSUE THREAD

**Issue by evilvibes** [DNSCrypt/dnscrypt-proxy#186]
So i been trying to get [DNSCrypt server with vultr.com](https://github.com/jedisct1/dnscrypt-proxy/wiki/DNSCrypt-server-with-vultr.com) to work but cannot get it to communicate from dnscrypt-proxy to the dnscrypt server.

maybe it's a firewall issue but i'm not sure.

@bitbeans maybe you could help?

**Comment by bitbeans** [comment]
@evilvibes yes you are right! script needs an update, the firewall is blocking.

Workaround so long:
` systemctl stop iptables`

i will will update it as soon i have some time :)

Update: or feel free to do so :)

**Comment by evilvibes** [comment]
I would but i have no idea what to update it too. The cmd did the trick Thanks.
