### ISSUE TITLE
DoH server address incorrectly cached from DoH DNS-stamp for entries with explicit port number

### ISSUE THREAD

**Issue by cobratbq** [DNSCrypt/dnscrypt-proxy#1861]
_I have searched for known issues but cannot find any trace. I have traced what I believe is the root cause for this issue. The issue becomes apparent for me due to a certain configuration choices. I decided to skip starting a discussion due to the fact that I believe I have fully traced the issue. This also seems inconsistent in the DNSStamps specification._

For DoH DNS stamps, the `hostname` (called `ProviderName` in the code) __may__ contain a port number. Some DoH resolver entries contain such (explicit) port numbers.

DNSCrypt-proxy assumes that the `ProviderName` does not contain a port number and immediately stores the address in the cache indefinitely. When later loading the IP address from cache while fetching DoH server information with a query, it will query the cache with __only__ the hostname and will therefore not find the just-inserted cache entry. It will then be forced to use a system resolver even though full address information is part of the DNS stamp. (IIUC, the consequence is not having verified the DoH server address that gets resolved.)

Logging reports notices:

> System DNS configuration not usable yet, exceptionally resolving [dns9.quad9.net] using fallback resolvers over udp
> System DNS configuration not usable yet, exceptionally resolving [dns9.quad9.net] using fallback resolvers over tcp

## Example case

Quad9 DoH server (entry from public-resolvers v2/v3 list.)

My personal configuration is set to ignore the system DNS resolvers - as that points to dnscrypt-proxy already.

DNS stamp: `sdns://AgMAAAAAAAAABzkuOS45LjkgKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoSZG5zOS5xdWFkOS5uZXQ6NDQzCi9kbnMtcXVlcnk`
Address: `9.9.9.9`
Hostname: `dns9.quad9.net:443`

Trace in source code (master):

- DNS Stamps spec defines that DoH stamps can contain hostname with optional port numbers, which is separate from field IP address.
- `serversInfo.go:610` stores IP in cache indefinitely for key stamp.ProviderName, i.e. key could contain port number.
- `serversInfo.go:620` initiates query using URL constructed from stamp.ProviderName, i.e. which could include port number.
- `xtransport.go:375` extracts and splits host and port, continues with host value only.
- `xtransport.go:379` resolve host-without-port from cache and will not find indefinite cache entry previously stored *with the port number*.

## Reproducibility

1. Select _DoH entry_ from public-resolvers list that contains hostname-with-port, and address without port.
2. Set option to ignore system resolvers - for convenient log entries.
3. Start dnscrypt-proxy and wait for it to start complaining during initialization.
4. Resolving will work, but DoH server address was resolved through different means, instead of using the information from the DNS stamp.

Although I'm unfamiliar with the code, it seems that stripping the port number before storing the IP in cache (`serversInfo.go:610`) would be the way to solve this. I have not yet tried this.

__update__ Discussion #1828 could be related, but didn't show in my search at the time.

**Comment by jedisct1** [comment]
Fixed, thank you!
