### ISSUE TITLE
Limit use of HTTP Headers for DoH

### ISSUE THREAD

**Issue by msoxzw** [DNSCrypt/dnscrypt-proxy#1866]
The "dnscrypt-proxy" sends additional HTTP headers for DoH:

User-Agent header field:
https://github.com/DNSCrypt/dnscrypt-proxy/blob/0f00cd27f92cee434336c6d6cde9df26286d8dbe/dnscrypt-proxy/xtransport.go#L359

Cache-Control header field:
https://github.com/DNSCrypt/dnscrypt-proxy/blob/0f00cd27f92cee434336c6d6cde9df26286d8dbe/dnscrypt-proxy/xtransport.go#L366

As per [RFC 8484](https://datatracker.ietf.org/doc/html/rfc8484#section-8), implementations are advised to expose the minimal set of data needed to achieve the desired feature set.

Furthermore, [Google also recommends](https://developers.google.com/speed/public-dns/docs/doh#privacy_best_practices) that client's DoH implementation sends only the HTTP headers required for DoH, and prefers GET over POST for better HTTP cache.

**Comment by jedisct1** [comment]
`max-stale` drastically helps with reliability when the server is cached by a CDN and the origin times out.

`dnsrypt-proxy` always prefers `GET` over `POST`, even for ODoH. However, some servers and relays don't support the `GET` method, in which case it falls back to `POST` for all transactions.

The issue with DoH and headers is browsers sending data that can be used to fingerprint a given user. With `dnscrypt-proxy`, all users have the same profile.
