### ISSUE TITLE
Custom server documentation for v2.x

### ISSUE THREAD

**Issue by drduh** [DNSCrypt/dnscrypt-proxy#187]
I am using dnscrypt-wrapper v0.4.0 to run my own server on Debian. I'm having trouble figuring out how to connect to it using dnscrypt-proxy v2.0.4.

The documentation explains how to use public resolvers. I read https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes but those directions give me the following error:

    [FATAL] Unsupported key in configuration file: [servers]

I tried providing the stamp string in various other ways in the configuration to no avail. How can I connect to just one custom server?

**Comment by evilvibes** [comment]
Add your stamp here

```
## Optional, local, static list of additional servers
## Mostly useful for testing your own servers.

[static]

# [static.'google']
# stamp = 'sdns://AgUAAAAAAAAAACDyXGrcc5eNecJ8nomJCJ-q6eCLTEn6bHic0hWGUwYQaA5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs'
```

Change `[static.'google']` to a name you would like to use then add it too `# server_names = ['scaleway-fr', 'google', 'yandex']`

Don't forget to remove the leading `#`

**Comment by drduh** [comment]
I did that. Now it appears to be trying to connect to my server on port 443, but the service is hosted on port 5353. How do I specify which port to use?

**Comment by jedisct1** [comment]
The port number is encoded in the stamp.

You can use https://stamps.dnscrypt.info to adjust it. Paste the old stamp, add `:5353` to the host name, and copy the new stamp.

**Comment by drduh** [comment]
Can I adjust the stamp locally like so, without submitting information about my resolver to a third party?

**Comment by jedisct1** [comment]
Yes, of course!

And actually, https://stamps.dnscrypt.info doesn't submit anything, it's computed locally in javascript by your browser.
