### ISSUE TITLE
[FR] support Multicast DNS queries

### ISSUE THREAD

**Issue by NightMachinary** [DNSCrypt/dnscrypt-proxy#1870]
Apple supports Multicast DNS very well; Apple devices are assigned an address `HOSTNAME.local`, such as `xs-MacBook-Pro.local`, automatically. This address resolves to the correct IP address by Apple devices using Multicast DNS.

The support is, unfortunately, not as good on Android. So I am thinking that, if `dnscrypt` can support mDNS queries, I can just fire up `dnscrypt` on my android devices using `Termux`, and use `127.0.0.1` as my android device's DNS server. This way, `x.local` addresses would work on all android apps (I think).

Related:
- https://github.com/DNSCrypt/dnscrypt-proxy/discussions/1785
- https://github.com/DNSCrypt/dnscrypt-proxy/issues/41

**Comment by NightMachinary** [comment]
Here is a guide on registering an mDNS name on Linux, and then getting the IP corresponding to that address on Android:
- https://www.dodgycoder.net/2015/02/setting-up-bonjourzeroconfmdnsnsd.html

I am not sure if it's possible to read the mDNS query from golang on Android though. If it's not, feel free to say so and close the issue.

**Comment by jedisct1** [comment]
Not a bug.
