### ISSUE TITLE
dns lookup fail for system utilities specifically for forwarding rules server

### ISSUE THREAD

**Issue by piyushgarg** [DNSCrypt/dnscrypt-proxy#1873]
Reported bugs must reproducible in the context described in the "Context" section.

Installation and configuration issues are not bugs, but individual assistance request.

Context: the LATEST version of `dnscrypt-proxy` (precompiled binaries downloaded from this repository) is correctly installed and configured on your system, but something doesn't seem to produce the expected result.

If the bug is not trivial to reproduce on any platform, please include ALL the steps required to reliably duplicate it, on a vanilla, generic install of macOS, Windows, OpenBSD or Ubuntu Linux system, in their most current version.

If you don't have any clear understanding of the issue or can't enumerate the steps to reproduce it, open a discussion instead:
https://github.com/DNSCrypt/dnscrypt-proxy/discussions

## Output of the following commands:

$ dnscrypt-proxy -version
2.1.0

$ dnscrypt-proxy -config ~/.config/dnscrypt/dnscrypt-proxy.toml -check
[2021-09-10 14:38:52] [NOTICE] dnscrypt-proxy 2.1.0
[2021-09-10 14:38:52] [NOTICE] Source [public-resolvers] loaded
[2021-09-10 14:38:52] [NOTICE] Source [relays] loaded
[2021-09-10 14:38:52] [NOTICE] Configuration successfully checked

$ dnscrypt-proxy -config ~/.config/dnscrypt/dnscrypt-proxy.toml -resolve git.xxx.mycompany.com
Resolving [git.xxx.mycompany.com] using 127.0.0.53 port 53

Resolver      : 103.107.xxx.xxx

Canonical name: gitlab.xxxx.xxxx.mycompany.com.

IPv4 addresses: 100.111.xxx.xx
IPv6 addresses: -

Name servers  : no name servers found
DNSSEC signed : no
Mail servers  : no mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : -

- [ ] Initially raised as discussion #...

## *What* is affected by this bug?
ping ssh etc

ssh git@git.xxx.mycompany.com
ssh: Could not resolve hostname git.xxx.mycompany.com: Temporary failure in name resolution

ping git.cec.mycompany.com
ping: git.cec.mycompany.com: Temporary failure in name resolution

## *When* does this occur?
This occurs when the query is sent to forwarding server using forwarding rules

#forwarding rule
mycompany.com        201.xxx.xx.1,201.xxx.xx.2

## *Where* does it happen?
This occurs when the query is sent to forwarding server

$ nslookup git.xxx.mycompany.com
;; Truncated, retrying in TCP mode.
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
git.xxx.mycompany.com	canonical name = gitlab.xxx.xxx.mycompany.com.
Name:	gitlab.xxx.xxx.mycompany.com
Address: 100.111.xxx.xx

## *How* do we replicate the issue?

Add a forward rule like
mycompany.com        201.xxx.xx.1,201.xxx.xx.2

## Expected behavior (i.e. solution)
ssh git@git.xxx.mycompany.com
ping git.xxx.mycompany.com

should work

## Other Comments
The same server with ping, ssh etc using dns lookup using the 201.xxx.xx.1 directly in /etc/resolv.conf works fine.
nameserver 201.xxx.xx.1
nameserver 127.0.0.53
And I do not want to use systemd-resolv.

Why the forwarding server rule is working but throwing ";; Truncated, retrying in TCP mode." ?
I am not sure if this is the cause of the problem.
If I specify the same hostname ip rule in cloaking then there is no problem, but that does not serve the purpose of looking up dns servers in forward servers.

Attached the sample response for forward server.
[dig.txt](https://github.com/DNSCrypt/dnscrypt-proxy/files/7142980/dig.txt)

**Comment by jedisct1** [comment]
```text
dnscrypt-proxy -config ~/.config/dnscrypt/dnscrypt-proxy.toml -resolve git.xxx.mycompany.com
Resolving [git.xxx.mycompany.com] using 127.0.0.53 port 53

Resolver : 103.107.xxx.xxx

Canonical name: gitlab.xxxx.xxxx.mycompany.com.
```

Looks like `dnscrypt-proxy` is properly resolving `gitlab.xxxx.xxxx.mycompany.com`.

You can try the same directly with `dig`:

```sh
dig gitlab.xxxx.xxxx.mycompany.com @127.0.0.53
```

**Comment by piyushgarg** [comment]
@jedisct1 
I am not saying it is not working, its just that the using it with forward rules, the system utilities like ping and git is not working and mostly others will fail too. As per the response it is truncating something and switching to tcp, this behavior is not seen using systemd-resolv and the system utilities works fine.

**Comment by jedisct1** [comment]
Can you provide a way to reproduce this, step by step, starting from the vanilla Ubuntu Linux distribution?

**Comment by piyushgarg** [comment]
Hi Jedisct1
I am not sure if you will be able to reproduce it with the forwarding server (forwarding dns on a corp network) I have or its related to this peculiar dns sever. Please tell me how to generate the debug logs when I hit the dns query to the forward server (the log level 0 does not print anything except INFO and NOTICE, how to print TRACES or DEBUG?). 
[confandlogs.zip](https://github.com/DNSCrypt/dnscrypt-proxy/files/7143339/confandlogs.zip)

**Comment by jedisct1** [comment]
The documentation says to add `options edns0` to `resolv.conf`. Did you do that?

Otherwise, without a way to reproduce this, I'm really sorry, but I don't think any progress can be made since it looks very specific to your environment, and you can only provide incomplete information.

**Comment by piyushgarg** [comment]
Hi @jedisct1 ,
I am closing this issue as I was not able to update here the reproducible instructions and it is always not possible to get the same setup as production environment. Though the problem persists and I had moved on to dnsmasq for supporting upstream servers without any problems.

Here are my suggestions, verbose logging should be able to log as much data required which will help the developers to try to replicate and resolve the same problem without depending on the production environment. I was using dnscrypt proxy since 2017 as a standalone dns server without having any issues.
