### ISSUE TITLE
DNS still leaking

### ISSUE THREAD

**Issue by exiled52** [DNSCrypt/dnscrypt-proxy#1874]
so i basically install according to the installation guide in here,
i didn't do any big change except the recommendation inside the guides
so i did the dnsleaktest to check is it working or not? so yeah it is working no leaking at all but after a few hour or so i checked it again and somehow my isp was registered again when i did the dnsleak for the second time
i did the second test because the website I'm trying to reach are getting blocked again
so i need to close my browser and then open cmd every time that happen just to input ipconfig /flushdns 
if i stick to this website for a while it doesn't even take an hour and it's already get blocked again
is it something i missed during installation progress?
sorry i am newbie here

**Comment by exiled52** [comment]
![image](https://user-images.githubusercontent.com/77949814/132900474-37535c6b-89a2-420d-bd38-174554df1287.png)
this is before opening reddit
![image](https://user-images.githubusercontent.com/77949814/132900510-05173621-9f2f-48b3-9dac-617f26fd0776.png)
and this is after opening reddit just about 2 minute surfing

**Comment by jedisct1** [comment]
Not a bug.
