### ISSUE TITLE
Simple AdBlock for OpenWrt

### ISSUE THREAD

**Issue by Tallefer** [DNSCrypt/dnscrypt-proxy#188]
Just a possible heads-up. Feel free to close it if it's not relevant here.
https://github.com/stangri/openwrt-packages/blob/simple-adblock/net/simple-adblock/files/README.md
People reported that thing is holding up on ~40K hosts, while common adblock is causing the router to crash on just ~20K hosts.
I hope it could be useful to examine and compare it with DNScrypt's performance, if someone is willing to test it.
Possible related issue: https://github.com/jedisct1/dnscrypt-proxy/issues/162

**Comment by jedisct1** [comment]
Looks like it is just a script fetching data from different sources and deduplicating entries?

There is something similar in the dnscrypt-proxy package: https://github.com/jedisct1/dnscrypt-proxy/tree/master/utils/generate-domains-blacklists

**Comment by jedisct1** [comment]
https://github.com/stangri/openwrt-packages/blob/simple-adblock/net/simple-adblock/files/simple-adblock.init#L10

```sh
wget --no-check-certificate
```

I stopped reading here.
