### ISSUE TITLE
generate-domains-blocklist.py overlapping local patterns

### ISSUE THREAD

**Issue by stevehartwell** [DNSCrypt/dnscrypt-proxy#1896]
### Discussed in https://github.com/DNSCrypt/dnscrypt-proxy/discussions/1864

<div type='discussions-op-text'>

<sup>Originally posted by **stevehartwell** September  7, 2021</sup>

The `generate-domains-blocklist.py` script has code to eliminate domains which are already matched by a trusted, file-local glob expression, saving thousands of duplicate entries which might have a measurable performance improvement.<br/>
That optimization seems to have stopped working with a change introduced on 2020-12-20.<br/>
The change that intended to ignore time-based glob entries identifies them by matching the regex
> `rx_timed = re.compile(r".+\s*(@\S+)?$")`.

But since the `?` allows `@\S+` to occur 0 or once, it actually matches all glob entries, so all of the glob expressions are ignored and no duplicates are eliminated.<br/>
When I change this expression to: `r".+\s*@\S+$"`, only time-based glob entries are ignored, and the output now includes lines like:
`# Ignored due to overlapping local patterns: NNNN`
where they weren't being output before.
</div>

**Comment by jedisct1** [comment]
Good catch, thank you so much!

This should be fixed now.

Thanks again!
