### ISSUE TITLE
dnscrypt-proxy-win32-2.0.0beta8

### ISSUE THREAD

**Issue by ysz223** [DNSCrypt/dnscrypt-proxy#19]
dnscrypt-proxy-win32-2.0.0beta8

1、Modify server_names = ['cisco'] and [servers.'cisco ']

2、install service sc create dnscrypt-proxy binPath= "C:\Program Files\DNSCrypt\dnscrypt-proxy.exe"

3、Configure the service sc config dnscrypt-proxy start= AUTO

4、Turn on service net start dnscrypt-proxy

5、Use the web page https://www.dnsleaktest.com to detect Hostname Is 136-228-47-212.rev.cloud.scaleway.com

6、Open the web page https://welcome.opendns.com, suggesting You are not using OpenDNS yet. Let's fix that If you have not restarted your computer yet, please do that now.

7、How can I install correctly to use cisco?

**Comment by Marco-vW** [comment]
Make sure there's no hash on the line server_names and 'cisco' is the only dns service specified. Also I think your config needs to be changed (and possibly even configuring the service) prior to starting the dnscrypt-proxy service. After changing the config it probably needs to be restarted to reflect your changes. It works here without issues with:

`## List of servers to use`
`## If this line is commented, all registered servers will be used`

`server_names = ['cisco']`

and

`[servers]`
`  [servers.'cisco']`
`  provider_name = '2.dnscrypt-cert.opendns.com'`
`  address = '208.67.220.220'`
`  public_key ='B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79'`

Running dnscrypt-proxy v2 on an Asuswrt-Merlin powered ASUS router, so unable to test the Windows version.

**Comment by jedisct1** [comment]
> sc create dnscrypt-proxy binPath= "C:\Program Files\DNSCrypt\dnscrypt-proxy.exe"

There is a built-in way to install the service (`-service install`) and you install it by hand :(

![sad](https://metrouk2.files.wordpress.com/2015/06/sad-cat.png)

> sc config dnscrypt-proxy start= AUTO
> net start dnscrypt-proxy

![sad](https://metrouk2.files.wordpress.com/2015/06/sad-cat.png)

> Modify server_names = ['cisco'] and [servers.'cisco ']

The proxy *should* work with their servers, but I haven't checked yet. There's no extension to send them your IP and password yet, so you'd better stick to version 1 if you use them.

> Use the web page https://www.dnsleaktest.com to detect Hostname Is 136-228-47-212.rev.cloud.scaleway.com

Means that you started the service with `scaleway-fr` in `server_names`.

You can use `dnscrypt-proxy -resolve` instead of dnsleaktest.

**Comment by jedisct1** [comment]
To verify that your DNS queries are going through the proxy, enable the query log, and check that the names you are using appear in it.

The information you see on external web pages cannot be trusted.

**Comment by ysz223** [comment]
> There is a built-in way to install the service (-service install) and you install it by hand.

Excuse me, 32-bit Windows system how to use this installation method?

**Comment by jedisct1** [comment]
https://github.com/jedisct1/dnscrypt-proxy#installing-as-a-system-service-windows-linux-macos

**Comment by ysz223** [comment]
> With administrator privileges, type dnscrypt-proxy -service install to register dnscrypt-proxy as a system service, and dnscrypt-proxy -service start to start it.

I am in the 32-bit windows 7 Professional this operation, the command window prompt instruction does not exist, I was very puzzled.

**Comment by jedisct1** [comment]
You need to go in the directory where you extracted dnscrypt-proxy.

**Comment by ysz223** [comment]
> You need to go in the directory where you extracted dnscrypt-proxy.

I extract it, the following documents:

- blacklist.txt

- dnscrypt-proxy.exe

- dnscrypt-proxy.toml

- forwarding-rules.txt

- LICENSE

Run dnscrypt-proxy.exe with administrator privileges, only the front-end command line window, and did not install the service, is it where I misuse it?

**Comment by r13s** [comment]
`dnscrypt-proxy.exe -service install` and then `dnscrypt-proxy.exe -service start`

**Comment by ysz223** [comment]
When I use the command dnscrypt-proxy.exe -service install, the following occurs:

> Microsoft

 Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

> C:

 \ Windows \ system32> dnscrypt-proxy.exe -service install
'dnscrypt-proxy.exe' is not an internal or external command, executable program or batch file.

**Comment by ysz223** [comment]
When I use the command dnscrypt-proxy.exe -service install, the following occurs:

> MicrosoftWindows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

> C:\ Windows \ system32> dnscrypt-proxy.exe -service install
'dnscrypt-proxy.exe' is not an internal or external command, executable program or batch file.

**Comment by jedisct1** [comment]
You have to go to the path where the executable is.
You were in the `/Windows/system32` directory. This is probably not where you uncompressed dnscrypt-proxy.

**Comment by ysz223** [comment]
@jedisct1 
 use the administrator privileges to open the command window, the default is `C: \ Windows \ System32`, and my dnscrypt-proxy.exe on `C: \ Program Files \ DNSCrypt` below, is not required to dnscrypt-proxy.exe on `C : \ Windows \ System32` The following can be normal operation?

**Comment by jedisct1** [comment]
Type `cd /Program Files/DNSCrypt` to go to the `/Program Files/DNSCrypt` directory.

Or maybe `/Program\ Files/DNSCrypt` if it doesn't work.

**Comment by ysz223** [comment]
@jedisct1 Use the command `cd / Program Files / DNSCrypt` successfully opened, thank you very much!
