### ISSUE TITLE
Documentation should mention that cache files must not be older than refresh_delay

### ISSUE THREAD

**Issue by a1346054** [DNSCrypt/dnscrypt-proxy#190]
Windows 7, SP1, 64bit, english language

dnscrypt 2.0.0 worked

dnscrypt 2.0.4 does not work

public-resolvers.md and public-resolvers.md.minisig and mybase.txt were manually downloaded and put into that folder

[dnscrypt-proxy.zip](https://github.com/jedisct1/dnscrypt-proxy/files/1759689/dnscrypt-proxy.zip)

What is wrong with that config?

dnscrypt 2.0.4 works if I use this config (I added the .txt to make it upload to github)
[dnscrypt-proxy.toml.txt](https://github.com/jedisct1/dnscrypt-proxy/files/1759699/dnscrypt-proxy.toml.txt)

Sorry for my english!

**Comment by a1346054** [comment]
#182 might be related

**Comment by jedisct1** [comment]
Your cache files expired.

Bump `refresh_delay` up or update them (or at least the files dates).

**Comment by a1346054** [comment]
Thank you! Everything works now with the dnscrypt-proxy.zip above.

What I did:
$ touch public-resolvers.md public-resolvers.md.minisig

Why it happened:
I used wget to download those files, which copied the server time of the files, which was too old.

I apologize I did not manage to debug this on my own. Thank you for your help, you are awesome and dnscrypt is a great software.
