### ISSUE TITLE
Windows: Set Config To Listen Only Local Address But DNScrypt-Proxy-2 Also Listen All Adress

### ISSUE THREAD

**Issue by GaneJ** [DNSCrypt/dnscrypt-proxy#192]
After testing ```DNSCrypt-Proxy-2``` in **Windows**, I found out ```DNSCrypt-Proxy-2``` also listen ```0.0.0.0:53``` eventhough in my config, listen address have been set on ```127.0.0.1::53``` and ```[::1]:53```.

This is my config:
```
log_level = 3
log_file = 'D:\Documents\DNSCrypt\DNSCrypt.log'
use_syslog = false
server_names = ['securedns', 'soltysiak']
listen_addresses = ['127.0.0.1:53', '[::1]:53']
force_tcp = false
timeout_ms = 3000
cert_refresh_delay = 360
cert_ignore_timestamp = false
lb_strategy = 'p2'
block_ipv6 = true
cache = true
cache_size = 64
cache_neg_ttl = 0
cache_min_ttl = 60
cache_max_ttl = 86400
require_dnssec = true
require_nolog = true
require_nofilter = true
dnscrypt_servers = true
doh_servers = true
ipv4_servers = true
ipv6_servers = false
max_clients = 32
fallback_resolver = '0.0.0.0:53'
ignore_system_dns = true
# forwarding_rules = 'C:\Program Files\DNSCrypt\Forwards'
# cloaking_rules = 'C:\Program Files\DNSCrypt\Cloaks'

[query_log]
file = 'D:\Documents\DNSCrypt\DNSCrypt_Query.log'
format = 'tsv'
ignored_qtypes = ['A', 'NS', 'MD', 'MF', 'CNAME', 'SOA', 'MB', 'MG', 'MR', 'NULL', 'WKS', 'PTR', 'HINFO', 'MINFO', 'MX', 'TXT', 'RP', 'AFSDB', 'X25', 'ISDN', 'RT', 'NSAP', 'NSAP-PTR', 'NSAP', 'SIG', 'KEY', 'PX', 'GPOS', 'AAAA', 'LOC', 'NXT', 'SRV', 'ATMA', 'NAPTR', 'KX', 'CERT', 'A6', 'DNAME', 'OPT', 'APL', 'DS', 'SSHFP', 'IPSECKEY', 'RRSIG', 'NSEC', 'DNSKEY', 'DHCID', 'NSEC3', 'NSEC3PARAM', 'TLSA', 'HIP', 'SPF', 'NID', 'L32', 'L64', 'LP', 'TKEY', 'TSIG', 'IXFR', 'AXFR', 'MAILB', 'MAILA']

[nx_log]
file = 'D:\Documents\DNSCrypt\DNSCrypt_Query-NX.log'
format = 'tsv'

[blacklist]
blacklist_file = 'C:\Program Files\DNSCrypt\BLock-Names'
log_file = 'D:\Documents\DNSCrypt\DNSCrypt_Blocks.log'
log_format = 'tsv'

[ip_blacklist]
# blacklist_file = 'C:\Program Files\DNSCrypt\BLock-IPs'
blacklist_file = ''
log_file = 'D:\Documents\DNSCrypt\DNSCrypt_Block-IPs.log'
log_format = 'tsv'

[static]
  [static.'bn-fr0']
  stamp = 'sdns://AQYAAAAAAAAAETUuMTM1LjY2LjIyMjo1MzUzIIeUBwoUPTXKHKYy57GJMChOrl2v67QB499S6fA3q9GCHzIuZG5zY3J5cHQtY2VydC5iYWJ5bG9uLm5ldHdvcms'
  [static.'bn-fr1']
  stamp = 'sdns://AQYAAAAAAAAAFDE2NC4xMzIuMTMwLjE3MTo1MzUzIIeUBwoUPTXKHKYy57GJMChOrl2v67QB499S6fA3q9GCHzIuZG5zY3J5cHQtY2VydC5iYWJ5bG9uLm5ldHdvcms'
  [static.'bn-nl0']
  stamp = 'sdns://AQYAAAAAAAAAEzg3LjI1My4xNTIuMTkwOjUzNTMgh5QHChQ9NcocpjLnsYkwKE6uXa_rtAHj31Lp8Der0YIfMi5kbnNjcnlwdC1jZXJ0LmJhYnlsb24ubmV0d29yaw'
  [static.'securedns']
  stamp = 'sdns://AQcAAAAAAAAAEzE0Ni4xODUuMTY3LjQzOjUzNTMgs6WXaRRXWwSJ4Z-unEPmefryjFcYlwAxf3u0likfsJUcMi5kbnNjcnlwdC1jZXJ0LnNlY3VyZWRucy5ldQ'
  [static.'soltysiak']
  stamp = 'sdns://AQcAAAAAAAAAFDE3OC4yMTYuMjAxLjIyMjoyMDUzICXE4YgpFUaXj5wrvbanr6QB7aBRBQhdUwPnGSjAZo8hHTIuZG5zY3J5cHQtY2VydC5zb2x0eXNpYWsuY29t'

[sources]
  [sources.'customs']
  # url = 'file:///C:/Program%20Files/DNSCrypt/DNSCrypt-Resolvers.md'
  url = ''
  minisign_key = 'RWQeqY1xweEUbjD1evdmLjaDoUuEK+IYb7JqODyz9DiRX+hn2+AUXRkD'
  cache_file = 'C:\Program Files\DNSCrypt\DNSCrypt-Resolvers.md'
  format = 'v2'
  refresh_delay = 360
  prefix = ''

[schedules]
```
**Attachment:** A screenshot of ```DNSCrypt-Proxy-2``` and ```Unbound``` listen address (it cause ```DNSCrypt-Proxy-2``` and ```Unbound``` conflicting, because they both listen into the same address):
![2-listening](https://user-images.githubusercontent.com/20153153/36690659-9a3208d4-1b65-11e8-9671-69b4947b247e.png)

**Comment by GaneJ** [comment]
This doesn't happen with ```DNSCrypt-Proxy-1```.

**Comment by jedisct1** [comment]
```
fallback_resolver = '0.0.0.0:53'
```

What?

**Comment by GaneJ** [comment]
> fallback_resolver = '0.0.0.0:53'

Query through unbound.
DNSCrypt need small query doesn't it?

If this what you saying causing that issue, its not. I already try it with different ip. Its the same.

PS: Don't bother about ```ignored_qtypes```, I did this for testing purpose. Sometimes I just want see some query, sometimes its not.

**Comment by GaneJ** [comment]
DNSCrypt need small query doesn't it?

**Comment by jedisct1** [comment]
You need to put a host address here, not `0.0.0.0`.

And if Unbound forwards to dnscrypt-proxy, you'll have a loop problem.

**Comment by GaneJ** [comment]
I'll update first my DNSCrypt. I'm using the 1st version (2.0.0.0).
I'll post again after doing some test.
I don't know when I'm going to test it again.
For now lets close this first.
But don't delete it.
thanks.

**Comment by GaneJ** [comment]
Testing again...

1. DNSCrypt-2 always listen on ipv4 "this host address (0.0.0.0)"
No mater what I do, it always listen to that address.
Because of that, we can not use this -> ```fallback_resolver = '0.0.0.0:53'```. It cause loop behaviour if DNSCrypt server is offline or won't answer any question.

2. DNSCrypt-2 always listen on ipv4 "this host address (0.0.0.0)" and ipv6 "this host address (::0)", if we use this config -> ```listen_addresses = ['0.0.0.0:53', '127.0.0.1:53', '[::1]:53']```

3. No offline source allowed. Use ```[static]``` for offline source.

Thats it.

**Comment by jedisct1** [comment]
Can you explain what `0.0.0.0` is?

**Comment by GaneJ** [comment]
IANA said:
0.0.0.0/8 -> "This host on this network"
Check here:
[https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml)
For IPv6:
[https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml](https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml)

**Comment by GaneJ** [comment]
> 2.0.5 release:
> a fallback server supporting DNSSEC.

Great news.
Did DNSCrypt really check TLD DNSKEY or let DNS Server do that job?

**Comment by jedisct1** [comment]
>  Check here:

And as you can see with the rest of that table, this is a __network__ address. Don't try to connect to this.

**Comment by jedisct1** [comment]
>  Did DNSCrypt really check TLD DNSKEY or let DNS Server do that job?

The issue was due to an `OPT` record being received along with `A` records. The parser only expected `A` records.
