### ISSUE TITLE
service-install.bat infinite looping when 'Server' service is Disabled

### ISSUE THREAD

**Issue by a1346054** [DNSCrypt/dnscrypt-proxy#193]
Windows 7, SP1, 64bit, english.

dnscrypt-proxy 2.0.4

'Server' service set to Disabled. This is a common config for users who do not want to have SMB ports open.

Running service-install.bat will make it infinitely keep on spawning many cmd.exe windows, with no easy way of cancelling it, consuming a lot of RAM and CPU, requiring a computer restart to fix.

**Comment by jedisct1** [comment]
You have far more experience with Windows that I do.

How to fix this?

**Comment by a1346054** [comment]
Unfortunately, I am not familiar with writing windows .bat files, so I am hoping someone else will come along with insight on how to fix this.

In the meantime, this is a workaround for installing dnscrypt-proxy on windows:

1. Manually start cmd.exe with administrator permissions
2. Navigate to the dnscrypt-proxy directory
3. Execute the commands:

```
dnscrypt-proxy.exe -service install
dnscrypt-proxy.exe -service start
```

This installs dnscrypt-proxy.

**Comment by jedisct1** [comment]
A probably better workaround is to install Simple DNSCrypt :)

**Comment by GaneJ** [comment]
Agreed.

This dnscrypt is a "root", isn't it?
So to configure this "root", user should have a good knowledge about "rooting" their system.
If its not, use another program. Simple.

**Comment by jedisct1** [comment]
People able to disable the `Server` services (which I don't even know how to do) probably have enough skills to type the commands instead of using the script, indeed.
For everybody else, Simple DNSCrypt is fantastic.
