### ISSUE TITLE
dnscrypt-proxy-macos_arm64-2.1.1.zip is a build for x86_64

### ISSUE THREAD

**Issue by Kaiyangshi-Ito** [DNSCrypt/dnscrypt-proxy#1946]
So I installed dnscrypt-proxy arm64 version on my M1 Macbook Pro, but it showed up as an intel process on activity monitor. Why does this happen? I thought arm version should show up as Apple? In general, intel process will be consuming more power if running through rosetta.

**Comment by jedisct1** [comment]
Thanks for reporting this!

Indeed, there was a bug in the release script, and the arm64 zip file contains an x86_64 build instead of arm64.

I'll try to update these builds as soon as possible.

**Comment by jedisct1** [comment]
Done! The package has been reuploaded, and is now an arm64 binary.

Thanks for spotting this!
