### ISSUE TITLE
Log 'port already in use' to stderr

### ISSUE THREAD

**Issue by publicarray** [DNSCrypt/dnscrypt-proxy#195]
Nice work on v2
When trying to run a instance of dnscrypt-proxy when an instance is already running it I think It would be better to also log this in the terminal not just in the log file `[FATAL] listen udp 127.0.0.1:53: bind: address already in use`. Helps the user out when the program exits.

**Comment by jedisct1** [comment]
Maybe all messages with `FATAL` security should go to `stderr` in addition to syslog/windows logs/a file?

I don't know... Pretty sure there will be people complaining about things going to `stderr` in spite of them having configured a log file specifically to have nothing sent to `stderr`.

Sending log only to one channel is also by far the most current practice. Not saying that it is convenient, especially now with systemd, though.

**Comment by publicarray** [comment]
Yea I get your point.
I just realised without specifying a log file the output is in the terminal so I think that is good enough. 👍
