### ISSUE TITLE
Run as less privileged user

### ISSUE THREAD

**Issue by zivender** [DNSCrypt/dnscrypt-proxy#199]
In version 1.9.x, it was possible to run dnscrypt-proxy with user other than superuser (with 'user' parameter), for security purpose of course. I could not find the same option in v2.
Is it possible to implement ?

**Comment by jedisct1** [comment]
As you already saw in the documentation, this is possible on Linux.

But not on other platforms, as this is currently a tricky thing to do in Go, that may be addressed in a future release of the language.
