### ISSUE TITLE
Can we have a config option to write the PID to file?

### ISSUE THREAD

**Issue by georgep56** [DNSCrypt/dnscrypt-proxy#200]
As the subject says really: 
Monitoring services such as 'monit' need to read the process's PID from (for example) /var/run/progname.pid. 
This is generally configured by an option such as "--pidfile=/var/run/myname.pid" or by a line in the config file.
At the moment this doesn't seem to be an option?
Thanks!

**Comment by jedisct1** [comment]
Done.
