### ISSUE TITLE
dnscrypt crashes

### ISSUE THREAD

**Issue by caribpa** [DNSCrypt/dnscrypt-proxy#202]
Hi,
I've been testing dnscrypt proxy, both stable (2.0.5-1) and git (2.0.6.r0.g2c7513a-1) versions, and they seem to crash when **ignore_system_dns = true** and when using one of [mastad0n's](https://mastad0n.github.io) sources.
I've attached the .toml, the .log and the service's dump: [dnscrypt.zip](https://github.com/jedisct1/dnscrypt-proxy/files/1774803/dnscrypt.zip)

**Comment by jedisct1** [comment]
Should be fixed in 2.0.6. Thanks a lot!
