### ISSUE TITLE
[Q] : scaleway-fr - Explaining IPs to bypass Firewall

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#203]
Now I must allow at least 2 IPs to bypass Firewall using `'scaleway-fr'` resolver w/o restrictions.
Can you explain exact difference of this IPs? And why 2 at once?
```
37.59.238.213:443		recital.c9x.org , iNFO: https://fr.dnscrypt.info/
212.47.228.136:443		scaleway-fr.dnscrypt.info
```

Is information on the page https://fr.dnscrypt.info a bit obsoleted?
For example `dnscrypt-proxy2 stamp` (too long) or missing your new nesessary IP(s).

Is https://fr.dnscrypt.info/ the right place to get explanations for everybody?

**Comment by jedisct1** [comment]
The former is the frontend accessible using DNS-over-HTTPS. The later is the backend using the DNSCrypt protocol.

Note that the former was removed from the lists, as `doh-crypto-sx` is a faster version of it (using a CDN).

**Comment by iWARR** [comment]
What does it mean in practical sence when using these IPs? Need further explanation in "simple words". (No "coder" language, please). I have read your FAQ page some time ago (DNS over HTTPS (DoH)), but it is not an answer on my question.

I'm expecting for several clear sencences, no more.
This will be useful for all users, I think. Thanks.

**Comment by iWARR** [comment]
Instead of:

> former was removed from the lists

• I have a `[CRITICAL]` error in the `'dnscrypt-proxy.log'`, if `37.59.238.213` was not allowed by Firewall.

• If `212.47.228.136` was not allowed, dnscrypt-proxy works, but I see it was blocked by Firewall, no errors in the `'dnscrypt-proxy.log'` . 

`log_level = 3`

(Testing `'scaleway-fr'` as my 2-nd resolver, no DoH used, but `doh_servers = true`, if any)
I wanna say to Firewall "what is allowed", because everything "else" is restricted "by default".

This is "practical" side of my question. A "theory" is welcome.

**Comment by jedisct1** [comment]
Understanding your issues is complicated for me. I'm not a network expert. I don't use firewalls, I don't know the tools you are using, I never had a complex configuration like yours.
So I can only guess, but you know far more than me what you are doing. You only provide partial information every time, without any ways to reproduce your issues, so this doesn't help.

All I know is that `37.59.238.213` is the `doh.scaleway-fr` server (or something like that, I don't remember how it used to be called), as well as the web server for the `fr.dnscrypt.info` website.

The other IP is the `scaleway-fr` dnscrypt server.

**Comment by iWARR** [comment]
If my mention is right, I need 2 IPs alowed:

```
212.47.228.136:443	- 'scaleway-fr' DNSCrypt server (one of my static servers)

37.59.238.213:443	- Asking for to DoH doh.scaleway-fr server, if doh_servers = true
			- Website https://fr.dnscrypt.info
```

This is enough to answer on my question from the header. 
That's why I have to allow both in the Firewall.
Thank you.
