### ISSUE TITLE
Cache to disk

### ISSUE THREAD

**Issue by ZIEXED** [DNSCrypt/dnscrypt-proxy#204]
Please add an option to cache DNS to disk
Currently restarting the service discard the cache

**Comment by jedisct1** [comment]
I'm not planning to do this, but if you want to implement it, your changes will be welcome.

**Comment by sergeevabc** [comment]
@jedisct1, I believe default ```cache_size = 256``` is too low, so I changed it to 4096 for now.
How much memory does this change cost me?

**Comment by sergeevabc** [comment]
@ZIEXED, if you need to keep DNS cache on disk, the workaround is to pair DNSCrypt with [AncrylicDNS][1].

[1]: http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome

**Comment by ZIEXED** [comment]
I'm arleady doing this from a very long time, I'm using Ancrylic for Blacklisting and Caching
_I had a hope to remove it but my suggestion rejected immediately @@"_
Thank you <:3
