### ISSUE TITLE
DNS cache doesn't work for forwarding rules

### ISSUE THREAD

**Issue by Jay54520** [DNSCrypt/dnscrypt-proxy#2049]
## Output of the following commands:
```
$ dnscrypt-proxy -version
2.0.31
$ dnscrypt-proxy -check
[2022-02-23 20:18:41] [NOTICE] dnscrypt-proxy 2.0.31
[2022-02-23 20:18:41] [NOTICE] Network connectivity detected
[2022-02-23 20:18:41] [NOTICE] Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
[2022-02-23 20:18:41] [NOTICE] Configuration successfully checked
$ dnscrypt-proxy -resolve example.com
Resolving [example.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: example.com.
IP addresses:   0.0.0.0, ::
TXT records:    -
Resolver IP:    117.169.50.222 (localhost.)
```

## *What* is affected by this bug?

DNS cache doesn't work for forwarding rules.

cache_min_ttl = 2400

1. The TTL returned by forwarding DNS can be 320 which should be 2400
2. Dnscrypt will query forwarding DNS every time even the TTL is greater than 0. But for non forwarding rules, Dnscrypt won't query again but uses cache which displays 0ms in query log.

## *When* does this occur?

Every time.

## *Where* does it happen?

Both the sever dnscrypt running and client of dnscrypt server.

## *How* do we replicate the issue?

dnscrypt-proxy.toml
```
forwarding_rules = 'forwarding-rules.txt'
```

forwarding-rules.txt
```
baidu.com 119.29.29.29
```

Run on instance where dnscrypt resides
```
dig @localhost -p 53 baidu.com
dig @localhost -p 53 baidu.com
```

You can see two queries in `/var/log/dnscrypt-proxy/query.log` and the TTL is 145 far more smaller than expected 2400.
## Expected behavior (i.e. solution)

Make the DNS cache of forwarding rules can work like non forwarding rules. 

Do I miss something? But I don't find any relevant config to control DNS cache of forwarding rules in [example-dnscrypt-proxy.toml)](https://github.com/DNSCrypt/dnscrypt-proxy/blob/a20d1685b27f345726a0b131c34599e723a2feae/dnscrypt-proxy/example-dnscrypt-proxy.toml) or [example-forwarding-rules.txt](https://github.com/DNSCrypt/dnscrypt-proxy/blob/a20d1685b27f345726a0b131c34599e723a2feae/dnscrypt-proxy/example-forwarding-rules.txt)

## Other Comments

Cache works normal for non forwarding rules. The TTL of non forwarding rules returned by dnscrypt is expected 2400.
`dig @localhost -p 53 google.com`

**Comment by ghost** [comment]
[https://github.com/DNSCrypt/dnscrypt-proxy/discussions/1880#discussioncomment-1312145](https://github.com/DNSCrypt/dnscrypt-proxy/discussions/1880#discussioncomment-1312145)

**Comment by jedisct1** [comment]
This is intentional, so that the router stays the source of truth for the local domains it manages.

**Comment by Jay54520** [comment]
> [#1880 (comment)](https://github.com/DNSCrypt/dnscrypt-proxy/discussions/1880#discussioncomment-1312145)

But don't cache for WAN names too. Or should I put WAN names cache to another config?

> My use case is less with local network, but routing WAN names to specific resolvers (i.e. the 'example.com' case in forwarding_rules's comments).

> Are those results cached? Shouldn't they be?

**Comment by Jay54520** [comment]
I solve it by running the other dnscrypt that using DNS in forwarding rules as main DNS. Then update DNS in forwarding rules in first dnscrypt to the other dnscrypt.

**Comment by jedisct1** [comment]
We can introduce a special syntax to enable caching for specific rules. Or maybe introduce a new config file for that use case, but that may be confusing.

But running a second dnscrypt instance should indeed do the trick!

**Comment by Jay54520** [comment]
> We can introduce a special syntax to enable caching for specific rules. Or maybe introduce a new config file for that use case, but that may be confusing.
> 
> But running a second dnscrypt instance should indeed do the trick!

A second instance can only work one DNS which is enough for me, so a new config is better.

You can create a new feature request about that, I'll close this issue.
