### ISSUE TITLE
Virustotal results 16 / 67

### ISSUE THREAD

**Issue by CanCanCan3** [DNSCrypt/dnscrypt-proxy#205]
https://www.virustotal.com/#/file/dd441446b2f44547a6a63f3beaacae51fb6ff26a48d09149908bf9c778efc95c/detection

Why is this?

**Comment by jedisct1** [comment]
Antiviruses are a joke.

But you can report this to them as a false positive.

**Comment by kravietz** [comment]
The newer version is reported as safe so the solution is to upgrade. For the older version I'd suggest everyone who gets here goes to https://www.virustotal.com/#/file/2e760fd512781c532b6a3d9c0a26816d01a8c89a10b6f046e958d184eecdc232/community and votes **Safe**.
