### ISSUE TITLE
Enhancement: human readable sdns:// stamps

### ISSUE THREAD

**Issue by a1346054** [DNSCrypt/dnscrypt-proxy#208]
Any chance of changing the sdns:// stamps to something more human-readable?

`sdns://resolvername/providername=xxxx?protocol=dnscrypt&addr=xxxx&port=xxxx&publickey=xxxx&dnssec=yes&log=no&block=no`

resolvername is e.g. "scaleway-fr"
providername is e.g. 2.dnscrypt-cert.fr.dnscrypt.org
protocol is dnscrypt-v1, dnscrypt-v2, or doh
addr is the ip address
port is the port number
publickey is the server public key
dnssec/log/block are the props

and so on.

for example, compare these two

`sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc`

vs

`sdns://scaleway-fr/providername=2.dnscrypt-cert.fr.dnscrypt.org?protocol=dnscrypt-v2&addr=212.47.228.136&port=443&publickey=e801b84ea606bfb0bac0ce43445bb15eba64b02fa3c4aa31ae10636a0790324d&dnssec=yes&log=no&block=no`

This is just an example. I like to be able to read strings I can understand rather than a bunch of meaningless characters. Any input welcome on this.

**Comment by jedisct1** [comment]
No.

**Comment by NgoHuy** [comment]
In public-resolvers.md, we should note port of server, because I need port number to whitelist the firewall.
