### ISSUE TITLE
Build Failed - https://github.com/DNSCrypt/dnscrypt-proxy/security/code-scanning/181 

### ISSUE THREAD

**Issue by ianbashford** [DNSCrypt/dnscrypt-proxy#2081]
Hi -- I saw [this](https://github.com/DNSCrypt/dnscrypt-proxy/security/code-scanning/181)  had re-occurred yesterday.  
I'm not in a position to issue a PR at the moment, but I think this can be solved by adding  ewma into 

`vendor/github.com/jedisct1/ewma/`

It's missing at the moment.  There may be better solutions...

**Comment by syphyr** [comment]
https://github.com/syphyr/dnscrypt-proxy/commit/eaa6031efedf8e9996d37533d0df6ff80a9561f8

**Comment by jedisct1** [comment]
Awww, yes, that was introduced by https://github.com/DNSCrypt/dnscrypt-proxy/pull/2079

**Comment by ghost** [comment]
Oh, sorry for that.

**Comment by ghost** [comment]
These are the commits that were made on my behalf to fix an issue which never existed in the first place.
Sorry again for being that stupid and causing so much unnecessary work.
Please revert them all and this chapter can be closed for good.
1. https://github.com/DNSCrypt/dnscrypt-proxy/commit/ca076ce1333ecfc67a539383d47d2fd9db3416e4
2. https://github.com/DNSCrypt/dnscrypt-proxy/commit/034d3bd42483fdd634fb22fe8c2479038e49e6ac
3. https://github.com/DNSCrypt/dnscrypt-proxy/commit/c08852feb16e7f7d25fde0f1c26ff8ef1c0657b8
4. https://github.com/DNSCrypt/dnscrypt-proxy/commit/9373cc71625456f9012d0186b8393d208bca4666
5. https://github.com/DNSCrypt/dnscrypt-proxy/commit/cb140673fa9d5acc12b226891b2ec7a8dac098bd
6. https://github.com/DNSCrypt/dnscrypt-proxy/commit/7956ba5b104a1635214d2ddfbabb69b12ffefcf5
