### ISSUE TITLE
Permission denied for a temporary file. 

### ISSUE THREAD

**Issue by hostmaster** [DNSCrypt/dnscrypt-proxy#210]
dnscrypt-proxy-linux_arm-2.0.6 runs as an unprivileged user, with `/bin/false` shell.  I see `permission denied` errors in a log file. 

```
dnscrypt-proxy[330]: public-resolvers.md: open sf-dskyq3hy57somkp7.tmp: permission denied
dnscrypt-proxy[330]: public-resolvers.md.minisig: open sf-e7ixnpcmlpqjveu5.tmp: permission denied
dnscrypt-proxy[330]: Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
```

Apparently, it needs a write permission for a temporary file/folder right? What is that file/folder?

**Comment by jedisct1** [comment]
The one you have in the configuration file in the `cache_file` property. It is either an absolute path, or relative to the path of the config file itself.
