### ISSUE TITLE
Unable to resolve download.dnscrypt.info

### ISSUE THREAD

**Issue by thuantran** [DNSCrypt/dnscrypt-proxy#211]
Having problem with this domain, so can't download public resolver list. Please check.

nslookup download.dnscrypt.info
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

*** google-public-dns-a.google.com can't find download.dnscrypt.info: Server failed

**Comment by jedisct1** [comment]
Should be fixed now, thanks!
