### ISSUE TITLE
Unsupported key in configuration file: [servers] using an old configuration file

### ISSUE THREAD

**Issue by gpdevsoft** [DNSCrypt/dnscrypt-proxy#213]
when i try to install the version 2.0.6 (2.0.0 work fine) typing sudo ./dnscrypt-proxy -service install
appear the error message: [FATAL] Unsupported key in configuration file: [servers]
the same error occured with all version above 2.0.0
before installing the 2.0.6 i have typing sudo ./dnscrypt-proxy -service uninstall (for uninstall 2.0.0)  and then i have removing manually the dnscrypt-proxy.service and dnscrypt-proxy.socket files from /usr/lib/systemd/system/ and typing  sudo systemctl daemon-reload  then reboot.

**Comment by jedisct1** [comment]
There is a syntax error in your configuration file.

Start with the example configuration file, make incremental changes, and test each of them so that you know when you unintentionally break it.

**Comment by jedisct1** [comment]
There is no `[servers]` section. I think it's what is called `[static]` now. So, start over from the current example configuration file, this is the best way to have something that works with current versions.

**Comment by gpdevsoft** [comment]
i have solving changing the server, the only difference is in dnscrypt-resolvers.csv file, the old one server in version's column have "version 2" it's the only server that have this "feature", maybe version2's servers don't work any more since upgrade ( 2.0.1 and above)
