### ISSUE TITLE
dnscrypt.ca Has Always Been Recursive

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#214]
Can anyone tell me why

https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md

incorrectly says dnscrypt.ca forwards queries to Quad9?

**Comment by evilvibes** [comment]
@jedisct1 made the change here [https://github.com/DNSCrypt/dnscrypt-resolvers/commit/6c959524f834b202daef3993eb7eef6fc6a24443](https://github.com/DNSCrypt/dnscrypt-resolvers/commit/6c959524f834b202daef3993eb7eef6fc6a24443)

**Comment by ghost** [comment]
Thanks evilvibes, perhaps @jedisct1 can tell me why.

**Comment by jedisct1** [comment]
It looks like a bad mistake :( Just checked now and they indeed are recursive. I'm awfully sorry. This has been changed.
