### ISSUE TITLE
Consideration related to component – Enhancement requests regarding some features

### ISSUE THREAD

**Issue by Ricky-Tigg** [DNSCrypt/dnscrypt-proxy#215]
Hi jedisct1. As noticeable from the Linux distributions I used, in Fedora's and Centos' respective stable package repositories (https://rpms.remirepo.net/rpmphp/) components 'dnscrypt-proxy.x86_64 1.9.0-4.fc27 @fedora' and 'dnscrypt-proxy.x86_64 1.6.1-3.el7 @epel' have been left in obsolete states and for a reason since they are no longer maintained by the mentioned organisation in those repositories' lists; official site 'http://dnscrypt.org/' is obsolete as well. Those packages currently do not contain corresponding systemd unit, which had been reported as issue and remained unfixed.
 
As current maintainer of the open source project, your up-to-date component (https://bugzilla.redhat.com/show_bug.cgi?id=1464793) is reasonably expected to be released now as the official one, since it has the benefit to exist. Such action may indirectly have some beneficial effect regarding the dnscrypt-proxy-gui project (https://github.com/F1ash/dnscrypt-proxy-gui), in a way that the released components related to it – which are currently available in Fedora, but not in EPEL repository– have the potential of an up-to-date component; the one currently taken as reference is still the above mentioned unmaintained component.

- While launching a resolver, an alert is produced in terminal when the key rotation of the –assumed dnscrypt– certificate is beyond the security recommendations, but there is no mention of the current period time that triggers this alert.
- No mention neither regarding the used encryption protocols used on the encrypted channels. 
Is that possible to get those valuable informations as well in a release to come?

At last as noticeable, last available file dnscrypt-proxy.conf lacks obviously instruction, even poor, in order to get any one of the available IPv6 Tier 2 DNS resolvers to operate as intended. Be it  eventually on Ethernet interface, by disabling the IPv4 protocol, and setting DNS address to ::1, regarding the IPv6 protocol, which I indeed tested but host was unable to reach any Pv6 enabled servers.

Though, while dnscrypt-proxy was off,  disabling IPv4 protocol and setting IPv6 addresses for host and DNS respectively to DHCP and automatic, allowed my host to connect for instance to https://fi.wikipedia.org/, http://test-ipv6.netiter.dk/, https://www.google.be, https://be.yahoo.com/?p=us. Regards.

**Comment by jedisct1** [comment]
> While launching a resolver, an alert is produced in terminal when the key rotation of the –assumed dnscrypt– certificate is beyond the security recommendations, but there is no mention of the current period time that triggers this alert.

24 hours is the maximum recommended by the specification; the warning is printed for certificates valid for more than 7 days.

> No mention neither regarding the used encryption protocols used on the encrypted channels

This is displayed at startup time:

```
...
[2018-03-07 20:41:02] [NOTICE] [doh-crypto-sx] OK (DoH) - rtt: 55ms
[2018-03-07 20:41:02] [NOTICE] [ev-ca] OK (crypto v2) - rtt: 97ms
[2018-03-07 20:41:02] [NOTICE] [ev-us] OK (crypto v2) - rtt: 166ms
[2018-03-07 20:41:02] [NOTICE] [ev-us2] OK (crypto v2) - rtt: 79ms
[2018-03-07 20:41:03] [NOTICE] [ev-us3] OK (crypto v2) - rtt: 117ms
[2018-03-07 20:41:03] [NOTICE] [freetsa.org] OK (crypto v1) - rtt: 379ms
...
```

`crypto v1` is DNSCrypt with XSalsa20, `crypto v2` is DNSCrypt with XChacha20, `DoH` is DNS-over-HTTP/2.

There is no `dnscrypt-proxy.conf` file. Are you referring to `dnscrypt-proxy.toml`? What is Tier 2 DNS?
If you want to access DNS servers only using IPv6, you can change:

```toml
# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = false
```

to

```toml
# Use servers reachable over IPv4
ipv4_servers = false

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = true
```

**Comment by Ricky-Tigg** [comment]
Tested In Fedora with currently available 'component 'dnscrypt-proxy.x86_64 1.9.0-4.fc27 @fedora'. Output results in terminal:
`$ rpm -ql dnscrypt-proxy|grep -i .conf
/etc/dnscrypt-proxy.conf
/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv

$ rpm -ql dnscrypt-proxy|grep -i dnscrypt-proxy.toml
$ `

Tier 1 servers which act as authoritative servers only in the DNS infrastructure (DNS Tier1/Tier 2), are inappropriate for use as DNS resolver by a client. For instance [OpenNIC](https://wiki.opennic.org/opennic/tier2) and [Comodo](https://help.comodo.com/uploads/helpers/Comodo_Internet_Security_4.1_User_Guide.pdf) are known for those infrastructures. 

In OpenNIC infrastructure, Tier 2 DNS resolvers are represented either by decentralized servers or anycast servers; those last ones are usually highly reliable but in return their latency fluctuates a lot and worse, they make the network centralized. In the end, decision to choose one server from another is always up to the client. 

I had made the assumption, which may not be relevant, that servers part of the list contained in the dnscrypt-resolvers.csv file are Tier 2 DNS resolvers as well, and overall assumed them to be non-anycast, in other words decentralized the way some of the OpenNIC servers are.

Following OpenNIC Public Servers (hostnames) are not part yet of the dnscrypt-resolvers.csv file (which comes along with installation of component dnscrypt-proxy. Currently none of those DNSCrypt enabled servers are off-line or fail testing for more than 48 hours. List is:
ns1.any.dns.opennic.glue – ns3.any.dns.opennic.glue – ns3.ca.dns.opennic.glue – ns4.ca.dns.opennic.glue – ns3.cz.dns.opennic.glue – ns3.nw.de.dns.opennic.glue – ns1.hau.fr.dns.opennic.glue – ns1.tus.it.dns.opennic.glue – ns7.nh.nl.dns.opennic.glue – ns1.ma.us.dns.opennic.glue.

**Comment by jedisct1** [comment]
dnscrypt-proxy 1.9.0 is not only very old (it was released in 2016, and the last 1.x release was 1.9.5), but has also reached end of life. I don't have it on my machine any more and I barely remember how it worked.

It's unmaintained. Unsupported. Has vulnerabilities that won't be fixed. The CSV file is not being updated any more.

Switch to version 2.x.
