### ISSUE TITLE
Unknown is the server selected by dnscrypt-proxy

### ISSUE THREAD

**Issue by Ricky-Tigg** [DNSCrypt/dnscrypt-proxy#2152]
**General information**
```
$ cat /etc/redhat-release
Fedora release 36 (Thirty Six)
$ uname -ro
5.18.11-200.fc36.x86_64 GNU/Linux
$ dnf -q rq --installed --qf '%{name} %{version}' dnscrypt-proxy
dnscrypt-proxy 2.1.1
```
**Permanent change made to _dnscrypt-proxy.toml_**
`require_dnssec = true `

Hello.
- Configurations applied to _server_names = [(VALUES)]_ with those VALUES:
  - case 1 |  `'ams-doh-nl', 'dns.digitalsize.net', 'google', 'cloudflare'`
  - case 2 |  `'google', 'cloudflare'`

- Servers  properties as [reported](https://dnscrypt.info/public-servers/):
  - _ams-doh-nl_  | Resolver in Amsterdam. DoH protocol. Non-logging, non-filtering, DNSSEC.
  - _dns.digitalsize.net_ | A public, non-tracking, non-filtering DNS resolver with DNSSEC  enabled and hosted in Germany (https://dns.digitalsize.net)
  - _google_ | Google DNS (anycast) (_logging warning_)
  - _cloudflare_ | Cloudflare DNS (anycast) - aka 1.1.1.1 / 1.0.0.1

_Note_: lack of mention _(DoH)_ with regard to _google_ and _cloudflare_.

In order that changes take effect | `sudo systemctl restart dnscrypt-proxy`

**Results**
- case 1
```
$ systemctl status dnscrypt-proxy
(...)
(...) dnscrypt-proxy[168038]: /var/cache/dnscrypt-proxy/relays.md: open /var/cache/dnscrypt-proxy/sf-2gjj44lwvg5xx3ee.tmp: no such file or directory
(...) dnscrypt-proxy[168038]: Source [relays] loaded
(...) dnscrypt-proxy[168038]: Firefox workaround initialized
(...) dnscrypt-proxy[168038]: [cloudflare] OK (DoH) - rtt: 49ms
(...) dnscrypt-proxy[168038]: [google] OK (DoH) - rtt: 45ms
(...) dnscrypt-proxy[168038]: Sorted latencies:
(...) dnscrypt-proxy[168038]: -    45ms google
(...) dnscrypt-proxy[168038]: -    49ms cloudflare
(...) dnscrypt-proxy[168038]: Server with the lowest initial latency: google (rtt: 45ms)
(...) dnscrypt-proxy[168038]: dnscrypt-proxy is ready - live servers: 2
```
  - Unknown is the server selected by _dnscrypt-proxy_.
  - Expected DNSSEC-capable.
  - `/var/cache/dnscrypt-proxy/relays.md: open /var/cache/dnscrypt-proxy/sf-2gjj44lwvg5xx3ee.tmp: no such file or directory` may be expected and thus not an issue.

- case 2  | `'google', 'cloudflare'`
```
$ systemctl status dnscrypt-proxy
(...)
(...) dnscrypt-proxy[168287]: [ams-doh-nl] OK (DoH) - rtt: 79ms
(...) dnscrypt-proxy[168287]: [dns.digitalsize.net] OK (DoH) - rtt: 76ms
(...) dnscrypt-proxy[168287]: [google] OK (DoH) - rtt: 41ms
(...) dnscrypt-proxy[168287]: Sorted latencies:
(...) dnscrypt-proxy[168287]: -    38ms cloudflare
(...) dnscrypt-proxy[168287]: -    41ms google
(...) dnscrypt-proxy[168287]: -    76ms dns.digitalsize.net
(...) dnscrypt-proxy[168287]: -    79ms ams-doh-nl
(...) dnscrypt-proxy[168287]: Server with the lowest initial latency: cloudflare (rtt: 38ms)
(...) dnscrypt-proxy[168287]: dnscrypt-proxy is ready - live servers: 4
```
  - Unknown is the server selected by _dnscrypt-proxy_.
  - Expected DNSSEC-capable.

Might the server selected in each case be the one having the lowest initial latency regardless not being DNSSEC-capable?

**Comment by jedisct1** [comment]
Filters are used when the resolvers list is empty: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Configuration-Sources#filters

If you provide an explicit list of the servers you want to use, they are ignored.
