### ISSUE TITLE
TCP_DEFER_ACCEPT failed

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#216]
> dnscrypt-proxy.socket: TCP_DEFER_ACCEPT failed: Protocol not available
> dnscrypt-proxy.socket: TCP_NODELAY failed: Protocol not available

any ideas?

**Comment by jedisct1** [comment]
No idea since I'm not familiar with systemd, but you can remove these options; it shouldn't make a big difference. Or just don't use systemd sockets, and let the proxy create the sockets itself.
