### ISSUE TITLE
Timeouts for unknown record types

### ISSUE THREAD

**Issue by wintersteiger** [DNSCrypt/dnscrypt-proxy#2168]
I'm running release 2.1.2 of dnscrypt-proxy on Linux x86_64 and whenever I submit a query for a CAA record, e.g. 

```
...~$ dig service42.adns.ccf.dev. CAA

; <<>> DiG 9.16.1-Ubuntu <<>> service42.adns.ccf.dev. CAA
;; global options: +cmd
;; connection timed out; no servers could be reached
```

I get a `PARSE_ERROR` in the query log and the request is not forwarded (to a DOH server in my case) and no response is generated so that the query times out:

```
[2022-08-03 14:01:22]   167.220.197.171 service42.adns.ccf.dev  CAA     PARSE_ERROR     1ms
```

I see exactly the same behavior when I try other unknown/unsupported record types, e.g. `TYPE1234`. 

Is this a known and accepted limitation of dnscrypt-proxy that I should try to work around?

For context: while attempting to get a certificate from Let's Encrypt, their ACME servers look for CAA records. They are fine with those records not being present (I think), but they abort if the DNS query times out.

**Comment by jedisct1** [comment]
That seems to be independent from `dnscrypt-proxy`, as the same thing happens when querying servers over regular DNS:

```sh
dig service42.adns.ccf.dev. CAA @1.1.1.1

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 483
```

In fact, this happens with any query type:

```sh
dig service42.adns.ccf.dev. A @1.1.1.1

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 52408
```

**Comment by wintersteiger** [comment]
I'm currently working on that name and on the server code, it's simply offline for most of the time. This is what I get:

```
...:~$ dig service42.adns.ccf.dev. A

; <<>> DiG 9.16.1-Ubuntu <<>> service42.adns.ccf.dev. A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63812
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;service42.adns.ccf.dev.                IN      A

;; ANSWER SECTION:
service42.adns.ccf.dev. 0       IN      A       51.143.161.224

;; Query time: 0 msec
;; SERVER: 172.21.64.1#53(172.21.64.1)
;; WHEN: Wed Aug 03 15:56:53 BST 2022
;; MSG SIZE  rcvd: 78
```

However, this doesn't work via `@1.1.1.1`, I'll have to investigate that.

**Comment by wintersteiger** [comment]
`1.1.1.1` seems to be unreachable from where I am:

```
...:~$ dig google.com. A @1.1.1.1

; <<>> DiG 9.16.1-Ubuntu <<>> google.com. A @1.1.1.1
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by jedisct1** [comment]
Same with another resolver:

```sh
dig service42.adns.ccf.dev. CAA @4.2.2.2

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 30296
```

**Comment by wintersteiger** [comment]
Again, that resolver is unreachable for me:

```
...:~$ dig google.com. A @4.2.2.2

; <<>> DiG 9.16.1-Ubuntu <<>> google.com. A @4.2.2.2
;; global options: +cmd
;; connection timed out; no servers could be reached
```

(For example, see https://dnschecker.org/#A/service42.adns.ccf.dev for a list of resolvers the reach my resolver.)

This is all beside the point, however. I'm not trying to serve CAA records. The problem is that dnscrypt-proxy drops the request instead of fowarding it or returning an empty answer:

```
[2022-08-03 14:01:22]   167.220.197.171 service42.adns.ccf.dev  CAA     PARSE_ERROR     1ms
```

I want that `PARSE_ERROR` to turn into a `PASS`.

**Comment by jedisct1** [comment]
But... there's no empty answer (which would be a valid answer). The resolver doesn't return anything besides an error or a timeout. So, `dnscrypt-proxy` returns what it got.

**Comment by wintersteiger** [comment]
So, then, am I inferring correctly that dnscrypt-proxy should be forwarding the request after a `PARSE_ERROR`? (Mine doesn't seem to do that, but I first have to get rid of the gazillions of spam requests in my logs before I know for sure.)

**Comment by lifenjoiner** [comment]
Querying on 3 servers could get 3 different responses (`dnscrypt-proxy` logs):
```
[2022-08-04 10:00:31]   127.0.0.1       service42.adns.ccf.dev  CAA     SERVFAIL        5392ms  dnscrypt.ca-2
[2022-08-04 10:00:36]   127.0.0.1       service42.adns.ccf.dev  CAA     SERVER_TIMEOUT  10193ms resolver4.dns.openinternet.io
[2022-08-04 10:00:45]   127.0.0.1       service42.adns.ccf.dev  CAA     NETWORK_ERROR   14243ms wevpn-useast
```
`PARSE_ERROR` could be one of the results.

**Comment by wintersteiger** [comment]
I think I found those requests, totally my fault, sorry for the noise!

@lifenjoiner I can't explain your results; the server was offline since I left work yesterday. It runs on an Azure VM though, so the network around it is usually busy.
