### ISSUE TITLE
Function request?

### ISSUE THREAD

**Issue by idanka** [DNSCrypt/dnscrypt-proxy#218]
Function request, if acceptable, realizable!

*1-2 days old dns addresses queries on the background?
*Smart (petty) ping, frequently visited web sites?

Similar functionality is used by the cfosspped program, it speeds up the loading of web pages.
[https://www.cfos.de/en/cfosspeed/cfosspeed.htm](https://www.cfos.de/en/cfosspeed/cfosspeed.htm)

Sorry but google translate!

**Comment by jedisct1** [comment]
Hi,

I don't think this is a good idea.

First, all modern web browsers already preload frequently visited websites.

Automatically replaying previous queries also makes it easy to fingerprint your devices. From a privacy standpoint, this is really bad.

Finally, it increases the load on servers for no major benefits. 

So, well... probably not, sorry :(

**Comment by idanka** [comment]
OK, I understand.
