### ISSUE TITLE
[local DoH][TLS] 2.1.2 bad signature

### ISSUE THREAD

**Issue by mpas97** [DNSCrypt/dnscrypt-proxy#2190]
Since 2.1.2 the local DoH server doesn't work anymore. Error is SEC_ERROR_BAD_SIGNATURE in the Firefox Browser and in the local logs I see `tls: error decrypting message`.
```
[2022-08-29 14:44:44] [NOTICE] dnscrypt-proxy 2.1.2
[2022-08-29 14:44:44] [NOTICE] Network connectivity detected
[2022-08-29 14:44:44] [NOTICE] Now listening to 127.0.0.1:5300 [UDP]
[2022-08-29 14:44:44] [NOTICE] Now listening to 127.0.0.1:5300 [TCP]
[2022-08-29 14:44:44] [NOTICE] Now listening to https://127.0.0.1:443/dns-query [DoH]
[2022-08-29 14:44:44] [NOTICE] Source [public-resolvers] loaded
[2022-08-29 14:44:44] [NOTICE] Source [relays] loaded
[2022-08-29 14:44:44] [NOTICE] Firefox workaround initialized
[2022-08-29 14:44:44] [WARNING] [adguard-dns] uses a non-standard provider name ('2.dnscrypt.default.ns1.adguard.com.' doesn't start with '2.dnscrypt-cert.')
[2022-08-29 14:44:50] [NOTICE] [adguard-dns] OK (DNSCrypt) - rtt: 21ms
[2022-08-29 14:44:50] [NOTICE] Server with the lowest initial latency: adguard-dns (rtt: 21ms)
[2022-08-29 14:44:50] [NOTICE] dnscrypt-proxy is ready - live servers: 1
2022/08/29 14:45:15 http: TLS handshake error from 127.0.0.1:63914: remote error: tls: error decrypting message
2022/08/29 14:45:15 http: TLS handshake error from 127.0.0.1:63915: remote error: tls: error decrypting message
```

The layers below (eg., DNSCrypt to adguard) are working correctly.

 The only changes are:
```
diff example-dnscrypt-proxy.toml dnscrypt-proxy.toml
33c33
<
---
> server_names = ['adguard-dns']
42c42
< listen_addresses = ['127.0.0.1:53']
---
> listen_addresses = ['127.0.0.1:5300']
437c437
< # listen_addresses = ['127.0.0.1:3000']
---
> listen_addresses = ['127.0.0.1:443']
445c445
< # path = '/dns-query'
---
> path = '/dns-query'
451,452c451,452
< # cert_file = 'localhost.pem'
< # cert_key_file = 'localhost.pem'
---
> cert_file = 'localhost.pem'
> cert_key_file = 'localhost.pem'
```

Applying the same changes to 2.1.1 works like a charm. (macos x86_64)

## Output of the following commands:

./dnscrypt-proxy -version
```
2.1.2
```
./dnscrypt-proxy -check
```
[2022-08-29 14:48:45] [NOTICE] dnscrypt-proxy 2.1.2
[2022-08-29 14:48:45] [NOTICE] Source [public-resolvers] loaded
[2022-08-29 14:48:45] [NOTICE] Source [relays] loaded
[2022-08-29 14:48:45] [NOTICE] Configuration successfully checked
```
./dnscrypt-proxy -resolve example.com
```
...
IPv4 addresses: 93.184.216.34
...
```

**Comment by mpas97** [comment]
When opening the site through Safari I get a second error line `tls: client using inappropriate protocol fallback`

**Comment by jedisct1** [comment]
```text
2022/08/29 14:45:15 http: TLS handshake error from 127.0.0.1:63914: remote error: tls: error decrypting message
2022/08/29 14:45:15 http: TLS handshake error from 127.0.0.1:63915: remote error: tls: error decrypting message
```

Where are these logs coming from?

I'm confused by the port numbers. The local DoH server is on port `443`:

```text
[2022-08-29 14:44:44] [NOTICE] Now listening to https://127.0.0.1:443/dns-query [DoH]
```

So what are ports 63914 and 63915?

**Comment by jedisct1** [comment]
Recent Go versions require TLS to be at least version 1.2, but certainly Firefox uses version 1.3?

**Comment by mpas97** [comment]
These strange ports are the ones of the corresponding browser dns requests.

And yes, Firefox, Safari etc they all support TLS 1.3

**Comment by jedisct1** [comment]
How do you configure Safari to use DoH?

**Comment by mpas97** [comment]
In Brave and Safari I just tested with https://localhost/dns-query. After accepting the untrusted cert, they all show this connection error. (again, using 2.1.1 works everywhere)

**Comment by jedisct1** [comment]
I wasn't able to duplicate this on macOS with Firefox :( 

But now you're saying it's Brave, not Firefox ?

**Comment by mpas97** [comment]
In Firefox (my default) I have DoH set as trr only. In Brave and Safari I just checked with the url above if I can establish a TLS connection.

**Comment by mpas97** [comment]
I will look into Wireshark tomorrow. Let's see which ciphers are available etc

**Comment by jedisct1** [comment]
No issues with Safari either.

Is it a custom cert? Or the example one?

**Comment by mpas97** [comment]
I tested both cert types with 2.1.1 and 2.1.2. Again, 2.1.1 works either way, 2.1.2 in neither case.

**Comment by mpas97** [comment]
With a complete different Mac, I have the same issue.

**Comment by jedisct1** [comment]
Unfortunately I can't reproduce this. I don't know what to look at :(

**Comment by mpas97** [comment]
2.1.1 (using tls 1.3):
<img width="967" alt="grafik" src="https://user-images.githubusercontent.com/9994218/187392071-0306b755-57ee-412b-93b4-09cc3310a436.png">
2.1.2 (using tls 1.3):
<img width="970" alt="grafik" src="https://user-images.githubusercontent.com/9994218/187392605-89e26dca-2904-44ca-82fa-04b6407f7363.png">

2.1.1 (using tls 1.2):
<img width="752" alt="grafik" src="https://user-images.githubusercontent.com/9994218/187393597-9f9a7bb3-a152-490a-a26a-d04a3000e9b9.png">
2.1.2 (using tls 1.2):
<img width="752" alt="grafik" src="https://user-images.githubusercontent.com/9994218/187393872-6e35b654-27d0-4e35-a004-892bf0c6a0a1.png">


The only thing I can conclude from Wireshark:
The browser resets the tcp connection after `Server Hello Done` due to `TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Decrypt Error)`. On 2.1.1 and regardless of tls 1.2 or 1.3 `Change Cipher Spec` is sent instead, which is the correct next step.

**Comment by mpas97** [comment]
Also using curl:
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):

vs

* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* error:04FFF087:rsa routines:CRYPTO_internal:salt length recovery failed

So the `TLS handshake, Finished (20)` coming from the dnscrypt-proxy server seems to throw a `rsa routines: salt length recovery failed` in the client (curl).

**Comment by jedisct1** [comment]
Is that with the macOS binary downloaded from this repository?

**Comment by mpas97** [comment]
yes, I use https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.1.2/dnscrypt-proxy-macos_x86_64-2.1.2.zip

**Comment by mpas97** [comment]
Very interesting: just installed 2.1.2 via brew and there are no such issues.

**Comment by mpas97** [comment]
The binary from brew is 14M whereas the one from this repo only 11M..
```
ls -lah /usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy
-r-xr-xr-t  1 xxx  xxx    14M  1 Aug 17:59 /usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy
ls -lah dnscrypt-proxy-macos_x86_64-2.1.2/dnscrypt-proxy
-rwxr-xr-x@ 1 xxx  xxx    11M  1 Aug 18:00 dnscrypt-proxy-macos_x86_64-2.1.2/dnscrypt-proxy
```

**Comment by jedisct1** [comment]
Wow, indeed. Not sure what happened with that build. Connecting to DoH/ODoH servers doesn't work either. Essentially anything using TLS.

A buggy dependency?

I deleted these builds, and rebuilt them using the current Go version and dependencies.

Does the new build work for you?

**Comment by mpas97** [comment]
Yeah, it works! Thank you.
Looking at your changes, there has even been a TLS repo using beta version.
