### ISSUE TITLE
Change systemd dnscrypt-proxy.socket to listen in dual stack mode

### ISSUE THREAD

**Issue by bmeirellesRJ** [DNSCrypt/dnscrypt-proxy#2194]
Hi friends,

If possible change the file /etc/systemd/system/sockets.target.wants/dnscrypt-proxy.socket to listem in dual stack mode.

Everytime I update it goes back to:
ListenStream=127.0.0.1:53
ListenDatagram=127.0.0.1:53

To work on dual stack it should look like this:
ListenStream=[::]:53
ListenDatagram=[::]:53

Thanks

**Comment by jedisct1** [comment]
This is not part of dnscrypt-proxy, but something some distributions did on their own.

So, you should suggest this to whatever distribution you are using :)

**Comment by bmeirellesRJ** [comment]
Hi jedisct1,

ok. thanks.
