### ISSUE TITLE
sdns

### ISSUE THREAD

**Issue by elmakong** [DNSCrypt/dnscrypt-proxy#22]
i cant help but notice there is a sdns:// on the toml file. where should i look for that for another servers?
also, is there any update for the resolver list used on the sources?

**Comment by jedisct1** [comment]
A pull request was just sent for `dnscrypt-wrapper` to display server stamps. Give the maintainer some time to merge it, and server operators some time to publish this information for their servers.

**Comment by elmakong** [comment]
okay, will wait for the update.
still wondering how to host a public dns server for dnscrypt(probably host on centos). as i havent seen any singaporean server since D0wn is removing the SG&ID servers

**Comment by jedisct1** [comment]
To run your own server, the easiest way is to use the docker image: https://github.com/jedisct1/dnscrypt-server-docker

**Comment by elmakong** [comment]
i have tried to follow your wiki, but it cant be used due to sdns:// with sdns://
