### ISSUE TITLE
Is there some building instructions?

### ISSUE THREAD

**Issue by yvoinov** [DNSCrypt/dnscrypt-proxy#220]
Is there some building instructions with GCCGO? May be, Makefile?

PS. Sources useless without Makefile or, at least, useful building instructions. Not at all is go experts.

**Comment by jedisct1** [comment]
With the standard Go compiler, you can just type `go get -u github.com/jedisct1/dnscrypt-proxy` to download compile it.

With gccgo, I'm sorry, I have no idea. I am new to Go and I've never used gccgo.

But if you find out how to do, can you add this to the documentation? Thanks!
