### ISSUE TITLE
[ISSUE] Automatic log files rotation (log_files_max_age)

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#221]
**[ISSUE]**

Until today I used the next settings:
```

log_files_max_size = 50
log_files_max_age = 1
log_files_max_backups = 1
```

But my `'query.log'` still keep all inputs since 05.03.2018.
With my setting `log_files_max_age = 1` I'm expecting for every day trimming.
So, this setting doesn't work for me.

**[GOOD NEWS]**

Today my `'query.log'` has been reached 12 Mb size for 6 days.
This is good result: rescent dnscrtpt-proxy doesn't produce huge *.log files I had before in some case.

To have a look, if `log_files_max_size` setting work, I'm artificially reduced the limit to 8 Mb (having 12 Mb file) and restarted dnscrypt-proxy. Two "backup" archive files `*.log.gz` were created.
So, this setting works.

-------------------

If `log_files_max_age` will work as expected, I'll `set log_files_max_backups = 0` and 1...2 day long history without backups will be enough for me. I guess my new settings will be:

```
log_files_max_size = 10 
log_files_max_age = 2
log_files_max_backups = 0
```

**Comment by iWARR** [comment]
Remind you about **Log Management**, this option still very desired:
https://github.com/jedisct1/dnscrypt-proxy/issues/172#issuecomment-369953960

**Comment by jedisct1** [comment]
Max Age is how long to keep old log files (backups), not the current one.

**Comment by iWARR** [comment]
It would be nice contolling logs by time, not by size only. As I proposed in my request.
Sad :(

**Comment by iWARR** [comment]
All I can do in this case, is set (~2 days log in average):

```
log_files_max_size = 4
log_files_max_age = 0 or 1
log_files_max_backups = 0 or 1
```

with unpredictable day and time of the trimming, because a loading of the network may differ.
