### ISSUE TITLE
A cloaking rule is always interpreted as starting with a wildcard

### ISSUE THREAD

**Issue by jean-christophe-manciot** [DNSCrypt/dnscrypt-proxy#2211]
## Output of the following commands:

./dnscrypt-proxy -version
```
2.1.2
```
./dnscrypt-proxy -check
```
```
./dnscrypt-proxy -resolve example.com
```
Resolver      : 212.47.228.136 (scaleway-fr.dnscrypt.info.)

Canonical name: example.com.

IPv4 addresses: 93.184.216.34
IPv6 addresses: 2606:2800:220:1:248:1893:25c8:1946

Name servers  : b.iana-servers.net., a.iana-servers.net.
DNSSEC signed : yes
Mail servers  : 1 mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : wgyf8z8cgvm2qmxpnbnldrcltvk4xqfn, v=spf1 -all
```

## *What* is affected by this bug?
all resolutions

## *When* does this occur?
all the time

## *Where* does it happen?
paris, france

## *How* do we replicate the issue?
cloaking-rules.txt
```
ns2.domain.local        192.168.122.77
```

Resolving ns2.domain.local
```
dig ns2.domain.local A +short
192.168.122.77
```
Resolving any other fqdns ending with the same fqdn:
```
dig whateverns2.domain.local A +short
192.168.122.77
```
The last part should never happen!

**Comment by jedisct1** [comment]
This is expected.

An `=` prefix is required for exact matching. See the documentation: [filter patterns](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters#filter-patterns).

**Comment by jean-christophe-manciot** [comment]
Very strange rule :(

A correct rule would have been to require the presence of a wildcard (*) to interpret the hostname as starting with a ... wildcard.
