### ISSUE TITLE
soinfo_relocate(linker.cpp:987): cannot locate symbol "sigfillset" referenced by "./dnscrypt-proxy"...CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by MegaLite** [DNSCrypt/dnscrypt-proxy#222]
Android 4.2.2 @ Alcatel OneTouch Pixi 2. Attempt to run downloaded binary (arm) from rw, allow-exec location /custpack/dp2/ (emmc@custpack /custpack ext4 rw,relatime,noauto_da_alloc,commit=1,data=ordered 0 0)
```
cat /proc/cpuinfo
Processor	: ARMv7 Processor rev 3 (v7l)
processor	: 0
BogoMIPS	: 1993.93

Features	: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 3

Hardware	: MT6572
Revision	: 0000
Serial		: 0000000000000000
```

И почему его линкер не линкует? P.S. От таких вещей я далёк..

**Comment by MegaLite** [comment]
Почему его линкер не линкует?

**Comment by jedisct1** [comment]
The minimum Android version required is 5.0 (API 21).

**Comment by MegaLite** [comment]
Where is it described in description?.. Thanks.

**Comment by jedisct1** [comment]
Probably nowhere yet, so you should add it :)
