### ISSUE TITLE
Connection time out when using QUIC

### ISSUE THREAD

**Issue by kfken** [DNSCrypt/dnscrypt-proxy#2232]
Using the latest commit with HTTP3/QUIC, I configured `google` and `cloudflare` as my only servers.  QUIC works successfully with google for about 5 minutes, and then stops working.  When I output debug logging, every request to Google returns:

```NO_ERROR: 168: Connection max age expired```

All subsequent queries to Google fail, only cloudflare (which uses HTTP/2) continue to work.  If I restart dnscrypt-proxy, the same behavior repeats.  

There also seems to be a race condition - if `google` is used first on startup, it's not able to establish an HTTP3 connection and the server blocks.  If `cloudflare` is chosen first, it succeeds and queries work until the error above starts occuring.

I'm guessing that somewhere in xtransport.go Fetch() needs to create a new client transport, when the connection expires, but not sure the best place for this.

**Comment by jedisct1** [comment]
We need to close and reopen a QUIC connection when this happens.

Detecting these return codes is easy, but I don't know how to close and reopen a connection :(

**Comment by kfken** [comment]
> Detecting these return codes is easy, but I don't know how to close and reopen a connection :(

Would this work for closing?
https://github.com/lucas-clemente/quic-go/blob/v0.30.0/http3/roundtrip.go#L184

**Comment by jedisct1** [comment]
I guess this is fixed in https://github.com/quic-go/quic-go/pull/3684

**Comment by jedisct1** [comment]
Feel free to reopen if the same issue persists after the HTTP3 library update.
