### ISSUE TITLE
[v2.0.6][Android][mDNS] Chromecast devices not showing.

### ISSUE THREAD

**Issue by rprimus** [DNSCrypt/dnscrypt-proxy#226]
Wed Mar 14 10:27:27 GMT 2018

Am running dnscrypt-proxy via the ```Magisk module v2.1.2 - 03.07.2018```.

### Problem
The Google Home app only lists "Linked Devices" and not the usual display - which shows a picture of the device and allows adjusting the settings.
Other Apps that have ```Chromecast``` capabilities also do not list any devices (eg Podcast Addict).

Upon disabling dnscrypt-proxy,  all cast devices immediately show up.

### Debug
Wireshark
```
 1   278  2018-03-14 10:11:02.116492  192.168.0.14  5353  224.0.0.251  5353  MDNS 72  Standard query 0x0000 PTR _googlecast._tcp.local, "QM" question
```
A "QU" question is also asked.

**Comment by jedisct1** [comment]
Add a forwarding rule to forward `*.local` to your router.

**Comment by rprimus** [comment]
Thu Mar 15 11:17:22 GMT 2018

After adding the forwarding rule, chromecast devices are still not discovered.

With dnscrypt v1, devices were discoverable.
No problems with dnscrypt v2 on macos (no forwarding rule required).

**Comment by jedisct1** [comment]
I have no idea what the Magisk module does, but maybe it's setting up firewall rules to redirect all DNS traffic.

**Comment by rprimus** [comment]
Fri Mar 16 13:15:09 GMT 2018

The magisk module adds the following two rules:

```
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:5353
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5353
```
The configuration file has:
```
listen_addresses = ['127.0.0.1:5353', '[::1]:5353']
```

When I ran dnscrypt-proxy v1, I used the similar rules, however dnscrypt was listening on port 53.

**Comment by rprimus** [comment]
Fri Mar 16 13:53:39 GMT 2018

I've just changed the dnscrypt config to listen on port 53 (and the iptables rules to match). All cast devices are being seen.

Thanks for your time on this.

**Comment by bluemeda** [comment]
I will update Magisk module to solve this issue.
