### ISSUE TITLE
is dnscrypt-proxy  using its own local DNS cache or the one integrated in Windows?

### ISSUE THREAD

**Issue by Carl1971** [DNSCrypt/dnscrypt-proxy#228]
I had visited https://ipleak.net/ and I am not leaking any DNS resolver (I am using a resolver with DNSSEC+no logs and 127.0.0.1 as my primary DNS address). It just a curiosity since I was looking for some info about the dnscrypt-proxy  and the DNS local cache it uses (without having a third local DNS caching service like dnsmasq installed) and I didn't find anything concrete.  

I am asking you this because  I am using _Simple DNSCrypt_ with the option Cache enabled (I suppose that GUI it's setting up the cache=true parameter from behind) I see how all the DNS queries are been registered in the  ipconfig /displaydns command. I clean and disable it and I still see all my DNS queries been locally cached by Windows, so:
 
- Is Windows always caching all my DNS queries whether I am using DNSCrypt or any other DNS local cacher program?.  It represents any threat  to my privacy or it leaks my queries to outside? should I disable the Windows cache then?
- I am thinking in using a third party service like unbound or dnsmasq to create a local cache because as I read it can add some privacy and speed to my resolutions. Do you recommend me this?  

Thank you all for your help and work with this amazing project! :D

**Comment by jedisct1** [comment]
Hi!

It has its own DNS cache. So, adding something like dnsmasq is not required.

**Comment by Carl1971** [comment]
Hi!, 

First of all, apologize for my delay I was in a travel until yesterday (BTW, that was a fast reply :D).  Good to know about the fact that it uses its own cache but, in the future, I will create an Unbound setup for other features. So Windows is registering all the DNS requests in its local cache anyway, then I had another question in this regard:

_**Could the local DNS cache of Windows and the one built-in Firefox/Chrome leak some DNS information?**_

_BTW, I read some months ago about You leaving the project and now using a VPN (I think it was a tweet actually) I am really happy about you continuing the Dnscrypt-proxy with this new version. I've been using your software for some years (even without Simple DNSCrypt) and I learnt a lot about the DNS protocol since the very first day I discover your project and start researching about it, so thank you so much for all those years of work._

**Comment by sergeevabc** [comment]
@Carl1971, I have visited the website you mentioned earlier, /ipleak.net, and in my case it says
```DNS Addresses - 20 servers, 22 errors``` What about yours? I am a bit worried about ```errors```.
