### ISSUE TITLE
Enhancement request Need for a Uniform table of DNS resolvers. - Ricky-Tigg

### ISSUE THREAD

**Issue by evilvibes** [DNSCrypt/dnscrypt-proxy#229]
Not sure if this was meant to be here but it end up in the wiki pages.

https://github.com/jedisct1/dnscrypt-proxy/wiki/Enhancement-request----Need-for-a-Uniform-table-of-DNS-resolvers. 

Enhancement request  - Need for a Uniform table of DNS resolvers.

The seek of appropriate sources of material hosted at [location](https://github.com/jedisct1/dnscrypt-proxy/wiki/DNS-server-sources#opennic-servers) rises the need for a coherent way to visualise desired DNS resolvers aimed to be used in dnscrypt-proxy configuration file (dnscrypt-proxy.toml). Indeed filtering upon criteria Non-anycast, DNSSEC, IPv6, No logs, Namecoin, would be most appropriate. A table in which are merged lists maintained respectively by [mastad0](https://mastad0n.github.io/) and Frank Denis [source 1](https://download.dnscrypt.info/dnscrypt-resolvers/v2/opennic.md), [source 2](https://download.dnscrypt.info/dnscrypt-resolvers/v2/parental-control.md), [source 3](https://download.dnscrypt.info/dnscrypt-resolvers/v2/public-resolvers.md), would be indeed the way for users to no longer determinate the hard way the appropriate DNS resolvers aimed to be used in  configuration file dnscrypt-proxy.toml. Regards.

@Ricky-Tigg

**Comment by Ricky-Tigg** [comment]
Links in question (from page https://github.com/jedisct1/dnscrypt-proxy/wiki/DNS-server-sources) were not displayed at message sent.

**Comment by evilvibes** [comment]
@Ricky-Tigg It would of been easier if you deleted the wiki page (as i just did) and made the post here. I added the links also.

@jedisct1 He wanted to make enhancement request here but made it in the wiki pages.
