### ISSUE TITLE
OpenBSD x87 mode compilation fails

### ISSUE THREAD

**Issue by lifenjoiner** [DNSCrypt/dnscrypt-proxy#2296]
- https://github.com/DNSCrypt/dnscrypt-proxy/actions/runs/4078040093/jobs/7027768021#step:6:35
- [Go 1.16 drops support for OpenBSD x87 mode compilation (GO386=387)](https://go.dev/doc/go1.16#openbsd).

**Comment by jedisct1** [comment]
Thank you!
