### ISSUE TITLE
Go install fails with Go 1.20

### ISSUE THREAD

**Issue by DomT4** [DNSCrypt/dnscrypt-proxy#2306]
I'm not completely sure if you officially support installing via `go install` but I was updating a few bits earlier locally after updating to Go 1.20 `go version go1.20 darwin/arm64` and experienced a failure whilst executing `go install -v github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy@latest`. Thought I'd flag to you just in case.

```
go: github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy@latest: github.com/DNSCrypt/dnscrypt-proxy@v0.0.0-20230204211518-3f31c4d3e210: parsing go.mod:
	module declares its path as: github.com/dnscrypt/dnscrypt-proxy
	        but was required as: github.com/DNSCrypt/dnscrypt-proxy
```

## *What* is affected by this bug?

Installing via `go install`

## *When* does this occur?

After upgrade to Go 1.20

## *Where* does it happen?

During installation.

## *How* do we replicate the issue?

With Go 1.20 installed execute `go install -v github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy@latest` in a command-line environment.

## Expected behavior (i.e. solution)

`dnscrypt-proxy` builds successfully from a `go install` invocation

**Comment by jedisct1** [comment]
Does `go install -v github.com/dnscrypt/dnscrypt-proxy/dnscrypt-proxy@latest` work?

**Comment by DomT4** [comment]
Hilariously, yes. I'll update my script locally to use the lowercase. Thanks!
