### ISSUE TITLE
In version 2.1.3, cloaking returns a block for names that are not in the cloaked list

### ISSUE THREAD

**Issue by homewirehub** [DNSCrypt/dnscrypt-proxy#2311]
Starting with any operating system (issue is system-independant):

1) Install dnscrypt-proxy 2.1.3 (doesn't happen with other versions) downloaded from this repository
2) Copy the example configuration file
3) Uncomment the `cloaking_rules = 'cloaking-rules.txt'` line.
4) Start the proxy in this configuration: `./dnscrypt-proxy`
5) Test the service with `./dnscrypt-proxy -resolve example.com`

## Expected output (as in version 2.1.2 with exactly the same config file):

```txt
Resolver      : 185.2.28.226

Canonical name: example.com.

IPv4 addresses: -
IPv6 addresses: -

Name servers  : a.iana-servers.net., b.iana-servers.net.
DNSSEC signed : yes
Mail servers  : 1 mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : v=spf1 -all, wgyf8z8cgvm2qmxpnbnldrcltvk4xqfn
```

## Actual output in version 2.1.3 with cloaking enabled

```txt
Resolving [example.com] using 127.0.0.1 port 53

Resolver      : -

Canonical name: example.com.

IPv4 addresses: 93.184.216.34
IPv6 addresses: 2606:2800:220:1:248:1893:25c8:1946

Name servers  : a.iana-servers.net., b.iana-servers.net.
DNSSEC signed : yes
Mail servers  : no mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : This query has been locally blocked by dnscrypt-proxy
TXT records   : -
```

IP addresses are properly returned, but the resolver, host info and TXT records don't match.

## Workaround

Reverting to the default configuration file, with cloaking disabled, doesn't exhibit this issue.

**Comment by jedisct1** [comment]
*How* do we replicate the issue?

Please list all the steps required to reliably replicate it, starting from a newly installed operating system.

**Comment by jedisct1** [comment]
(hint: cloaking probably needs to be enabled)

**Comment by homewirehub** [comment]
Cloaking is enable. I installed the proxy on fresh new Ubuntu arm64. Cloaking PTR is enable.

**Comment by jedisct1** [comment]
Starting with any operating system (issue is system-independant):

1) Install dnscrypt-proxy 2.1.3 (doesn't happen with other versions) downloaded from this repository
2) Copy the example configuration file
3) Uncomment the `cloaking_rules = 'cloaking-rules.txt'` line.
4) Start the proxy in this configuration: `./dnscrypt-proxy`
5) Test the service with `./dnscrypt-proxy -resolve example.com`

## Expected output (as in version 2.1.2 with exactly the same config file):

```txt
Resolver      : 185.2.28.226

Canonical name: example.com.

IPv4 addresses: -
IPv6 addresses: -

Name servers  : a.iana-servers.net., b.iana-servers.net.
DNSSEC signed : yes
Mail servers  : 1 mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : v=spf1 -all, wgyf8z8cgvm2qmxpnbnldrcltvk4xqfn
```

## Actual output in version 2.1.3 with cloaking enabled

```txt
Resolving [example.com] using 127.0.0.1 port 53

Resolver      : -

Canonical name: example.com.

IPv4 addresses: 93.184.216.34
IPv6 addresses: 2606:2800:220:1:248:1893:25c8:1946

Name servers  : a.iana-servers.net., b.iana-servers.net.
DNSSEC signed : yes
Mail servers  : no mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : This query has been locally blocked by dnscrypt-proxy
TXT records   : -
```

IP addresses are properly returned, but the resolver, host info and TXT records don't match.

## Workaround

Reverting to the default configuration file, with cloaking disabled, doesn't exhibit this issue.

**Comment by jedisct1** [comment]
That was fixed in 68f3ab249cd69e93d0a89564eb57e5f20dd542ee

Version 2.1.4 is currently being packed in order to include that fix. Thanks!

**Comment by homewirehub** [comment]
Great thank you! Really fast replied 🚀

**Comment by jedisct1** [comment]
Version 2.1.4 released!

Thanks!
