### ISSUE TITLE
[macOS] BitBar plugin to control dnscrypt-proxy usage

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#232]
Just whipped up a BitBar plugin to quickly change your DNS settings:

https://github.com/jedisct1/bitbar-dnscrypt-proxy-switcher

**Comment by evilvibes** [comment]
Works :)

**Comment by michael1900** [comment]
why when i use "Use default DNS" i have this error:

"WiFi resolvers: There aren't any DNS Servers set on WIFI"

I maked different tries but always the same message.

In wifi option i have obviously only this "dns": 127.0.0.1

**Comment by jedisct1** [comment]
This is not an error.

**Comment by michael1900** [comment]
so, what is the purpose of this script? _Maybe i have not understood. I thought about it to switch between "standard" dns and dnscrypt 127.0.0.1

Thanks

**Comment by jedisct1** [comment]
Yes, this is what it does.

**Comment by michael1900** [comment]
so ok.. but when i switch to standard dns, nothing happens in dns setting, there is always only 127.0.0.1 so in this "sense" it is not useful because there is no switch on my side.

How can solve this problem?

I mean: when i set Use default DNS i want that it set for example 8.8.8.8 and when i set Use dnscrypt i want that it set 127.0.0.1 and so on

**Comment by jedisct1** [comment]
`default` is no specific IP address, so it will use what the router (or whatever provides DHCP) suggests.

You can use an unauthenticated server as well. By default it is Quad9, but you can replace it with Google if you like. Look at the beginning of the file and change what you want accordingly:

https://github.com/jedisct1/bitbar-dnscrypt-proxy-switcher/blob/bf50415a1353e1485bb48c1633f31e3d0e6085f0/dnscrypt-proxy-switcher.10s.sh#L16

**Comment by michael1900** [comment]
I think it works not good for what i need i think, btw thanks ;)

**Comment by JayBrown** [comment]
Got my own BitBar plugin now, originally derived from this one: https://github.com/JayBrown/DNSCrypt-Menu

**Comment by jedisct1** [comment]
@JayBrown Wow, this is really neat!

**Comment by rr0ss0rr** [comment]
Curious .. Is BitBar still supported? v2b10 is getting up to 2 years old.

**Comment by jedisct1** [comment]
Well... it works...

There's a rewrite in Swift: https://github.com/oleander/bitbar

Not sure how it compares.
