### ISSUE TITLE
Periodically dnscrypt-service does not start after Windows startup 

### ISSUE THREAD

**Issue by userneu** [DNSCrypt/dnscrypt-proxy#234]
Events 7000:

> The DNSCrypt client proxy service failed to start due to the following error:
> The service did not respond to the start or control request in a timely fashion.

 and 7009:

> Timeout (30000 milliseconds) waiting for the DNSCrypt client proxy service to connect.

 are logged.
Windows 7 x64 Pro
dnscrypt proxy 2.06 final

**Comment by jedisct1** [comment]
Sorry, I have absolutely no idea what it means, and I don't even know what application is displaying or logging this.

So, you're the expert here :)

If you can find out what is causing this and how to improve or fix it, I'd be more than happy to merge any required changes!

**Comment by userneu** [comment]
Please tell me that you do not understand exactly.
I use dnscrypro proxy as Windows service. For some reason that service sometimes doesnot start with Windows. I have to start it manually. 

> nd I don't even know what application is displaying or logging this.
Its Windows event log obviously. 

> So, you're the expert here :)
> If you can find out what is causing this and how to improve or fix it, I'd be more than happy to merge any required changes!

Sorry Iam not coder. I have just submitted issue. Is this section ("Issues") not created for this? 
Or should I have a degree in software development to submit issue?
Please tell me I dont understand.

**Comment by jedisct1** [comment]
Unfortunately, I don't use Windows. Just today, you probably used it more than I did in my entire life :)

So this issue would stay open forever until you find a workaround.

Maybe you can try https://simplednscrypt.org ?

**Comment by bitbeans** [comment]
@userneu maybe you can play with the _ServicesPipeTimout_ https://support.microsoft.com/en-us/help/922918/a-service-does-not-start-and-events-7000-and-7011-are-logged-in-window

**Comment by userneu** [comment]
@jedisct1 
@bitbeans 
Thanks.

**Comment by a1346054** [comment]
I have the same issue as you @userneu 

The solution is to update the timestamp on your public-resolvers.md.minisig in the dnscrypt folder, and then restart the windows service.

You can update the timestamp by using cygwin and running the command `touch public-resolvers.md.minisig` when in the dnscrypt folder.

It is related to #190
