### ISSUE TITLE
some ipv6 address base64 code in "public-resolvers.md" don't contain the port info.

### ISSUE THREAD

**Issue by bleeee** [DNSCrypt/dnscrypt-proxy#235]
for example:

## cisco-ipv6
Cisco OpenDNS IPv6 sandbox
sdns://AQAAAAAAAAAAD1syNjIwOjA6Y2NjOjoyXSC3NRFAIG8iXT4r2CLX_WkeocM8yNZmjQy-BL-rykP7eRsyLmRuc2NyeXB0LWNlcnQub3BlbmRucy5jb20

it don't contain  port ":443" in the serveraddress

**Comment by bleeee** [comment]
It should be "sdns://AQAAAAAAAAAAE1syNjIwOjA6Y2NjOjoyXTo0NDMgtzURQCBvIl0-K9gi1_1pHqHDPMjWZo0MvgS_q8pD-3kbMi5kbnNjcnlwdC1jZXJ0Lm9wZW5kbnMuY29t"

Anyway thank you so much for your effort! I can finally run dnscrypt on my mipsle router!

**Comment by jedisct1** [comment]
The port is not required if this is the default port...

**Comment by bleeee** [comment]
Sorry about the default port.  With all due respect still the stamp won't work on my ipv6 link. So I digged it a little bit.

the 102-104 lines in the file "stamps.go“ are as follow
`	if net.ParseIP(stamp.serverAddrStr) != nil {
		stamp.serverAddrStr = fmt.Sprintf("%s:%d", stamp.serverAddrStr, DefaultPort)
	}`

these lines mean to attach defaultport(443) to the bare address, however the "stamp.serverAddrStr" is given as a form of “[2001::1]” while the function "net.ParseIP()" only recognize ipv6 address form as “2001::1” (without the Square brackets) . 
So the dafaultport(443) never attached to any bare ipv6 address.
