### ISSUE TITLE
Ipv6 default port attach function bug with stamps.go

### ISSUE THREAD

**Issue by bleeee** [DNSCrypt/dnscrypt-proxy#236]
Sorry about the default port issues (https://github.com/jedisct1/dnscrypt-proxy/issues/235) before. With all due respect , the stamps without a port setup won't work on my ipv6 link. So I digged it a little bit.

the 102-104 lines in the file "stamps.go“ go as follow:

` if net.ParseIP(stamp.serverAddrStr) != nil {
 stamp.serverAddrStr = fmt.Sprintf("%s:%d", stamp.serverAddrStr, DefaultPort) 
}`

these lines mean to attach defaultport(443) to the bare address, however the "stamp.serverAddrStr" is given as a form of “[2001::1]” while the function "net.ParseIP()" only recognize ipv6 address form as “2001::1” (without the Square brackets) .

So the dafaultport(443) never attached to any bare ipv6 address.

**Comment by jedisct1** [comment]
Good catch!

Since I don't have a computer now, would you mind submitting a pull request to fix this?

**Comment by bleeee** [comment]
Anyway I have managed to submit a bug fix. It's kind of cool !

**Comment by jedisct1** [comment]
Thanks a lot!

Had to apply to the fix to DoH IPv6 addresses, too.
