### ISSUE TITLE
systemd: allow to run as dedicated user

### ISSUE THREAD

**Issue by dvzrv** [DNSCrypt/dnscrypt-proxy#239]
I might be mistaken, but at least with the previous dnscrypt-proxy (pre 2.0.0) it was possible to run the service as a dedicated user using systemd, not requiring root.

However, if one wants to bind ports below 1024, it is needed to set some additional things.
Also, it would be beneficial to use DynamicUser (so it will not be required to set up a new system user).

Here is an example of such a service

```
[Unit]
Description=DNSCrypt client proxy
Documentation=man:dnscrypt-proxy(8)
After=network.target
Before=nss-lookup.target
Wants=nss-lookup.target

[Service]
NonBlocking=true
DynamicUser=yes
RuntimeDirectory=dnscrypt-proxy
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/dnscrypt-proxy

[Install]
WantedBy=multi-user.target
```
Also note: `Type=simple` is the default in the case of dnscrypt-proxy and can be omitted.

Additionally, it can be beneficial to have templated services (only start proxying to a specific server). I'm not sure, this is still useful with version > 2.0.0, but it was with version < 2.0.0.
Here is an example:

```
[Unit]
Description=DNSCrypt client proxy
Documentation=man:dnscrypt-proxy(8)
Requires=dnscrypt-proxy@.socket
After=network.target
Before=nss-lookup.target
Wants=nss-lookup.target

[Service]
NonBlocking=true
DynamicUser=yes
RuntimeDirectory=dnscrypt-proxy
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/dnscrypt-proxy -R %i -S -Z "%p@%i"

[Install]
WantedBy=multi-user.target
```
It's unclear to me atm, if the flags are still those from before version 2.0.0.

As the templated service also requires a templated socket (but the socket can not be set dynamically), it's not necessarily needed to provide a file.
However, if one wanted to use a certain server on a specific port, it can be achieved in the following way:

* copying the following to `/etc/systemd/system/dnscrypt-proxy@myserver.socket`

```
[Unit]
Description=dnscrypt-proxy listening socket

[Socket]
ListenStream=127.0.0.1:53 #example port
ListenDatagram=127.0.0.1:53 #example port
NoDelay=true
DeferAcceptSec=1

[Install]
WantedBy=sockets.target
```
* systemctl start dnscrypt-proxy@myserver.socket

This will automatically start `dnscrypt-proxy@myserver.service` the server according to the server name, once the port is accessed (e.g. by your local DNS server).

**Comment by jedisct1** [comment]
Hi,

That's all Greek to me, but if you want to write instructions for advanced Linux users and Linux package maintainers, the wiki can be edited by anyone. Maybe create a new page to document this?

**Comment by dvzrv** [comment]
@jedisct1 eh, sure.
Nonetheless, it would be nice to update the shipped systemd service/socket files accordingly. I can make a pull request for it, if you want to.

**Comment by jedisct1** [comment]
Please do! I don't know anything about systemd.

Just make sure not to break other distros and Android .

**Comment by dvzrv** [comment]
Alright.
AFAIK, systemd drops all unknown settings. So, in the case that the Linux is using an old version, prior to DynamicUser, it will drop this setting and start the system as root instead (which is how it is running currently anyways).
