### ISSUE TITLE
Checking config should not require root privileges

### ISSUE THREAD

**Issue by a1346054** [DNSCrypt/dnscrypt-proxy#2416]
## Output of the following commands:

./dnscrypt-proxy -version
2.1.4

./dnscrypt-proxy -check
[2023-06-17 23:01:28] [NOTICE] dnscrypt-proxy 2.1.4
[2023-06-17 23:01:28] [FATAL] Root privileges are required in order to switch to a different user. Maybe try again with 'sudo'

./dnscrypt-proxy -resolve example.com
Resolving [example.com] using 127.0.0.1 port 53

Resolver      : 51.15.122.250 (scaleway-ams.dnscrypt.info.)

Canonical name: example.com.

IPv4 addresses: 93.184.216.34
IPv6 addresses: 2606:2800:220:1:248:1893:25c8:1946

Name servers  : a.iana-servers.net., b.iana-servers.net.
DNSSEC signed : yes
Mail servers  : 1 mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : v=spf1 -all, wgyf8z8cgvm2qmxpnbnldrcltvk4xqfn

## *What* is affected by this bug?
Checking the config file.

## *When* does this occur?
Every time the command is run.

## *How* do we replicate the issue?
1) Debian linux, using dnscrypt-proxy from github.

1) In dnscrypt-proxy.toml, configure some non-privileged user that was created for this purpose, for example:
user_name = '_dnscrypt-proxy'

1) Install and start the service.

1) Run `dnscrypt-proxy -check` and notice this output:

```
[2023-06-17 23:01:28] [NOTICE] dnscrypt-proxy 2.1.4
[2023-06-17 23:01:28] [FATAL] Root privileges are required in order to switch to a different user. Maybe try again with 'sudo'
```

## Expected behavior (i.e. solution)
`dnscrypt-proxy -check` should not require root privileges if the config file can be read without root permissions.

**Comment by jedisct1** [comment]
root privileges are never needed for `-check`, unless the configuration includes a `user_name` directive to mention that the server should run as a different user.

The purpose of `-check` is to verify that the current configuration is valid; i.e. that the server with such a configuration would properly start. If `-check` passes, you know that it's fine to kill the currently running server, and start it again (for example after an update). So, it's important that `-check` runs in the same context as start the server would.

The server reads multiple configuration files, reads and creates caches and log files.

If any of these are accessible under the user you are running the `-check` command as, but the `user_name` directive is ignored by `-check`, the `-check` command can return success, but after an actual restart, the server would actually not start. That completely defeats the purpose of `-check`.

And if a directory is accessible by the user configured in `user_name` but not by the account the `-check` command is run as, `-check` would fail even though the configuration may be valid, and actually work.

> `dnscrypt-proxy -check` should not require root privileges if the config file can be read without root permissions.

It already doesn't, if the user it will be running as is the same as the one running the command.

If these users are different, the only way to check the configuration in the same context the server would be running as, is to first run it with the required privileges to switch to a different user.

`-check` should not lie, that would defeat its purpose.

**Comment by a1346054** [comment]
Thank you for the information.

```sh
dnscrypt-proxy -help
```
Says:

```
-check
        check the configuration file and exit
```

Which mislead me about what it actually does. I thought it just checks the configuration file for errors or other problems.
