### ISSUE TITLE
Downloaded dnscrypt-proxy 2.0.7, but it shows version 2.0.4

### ISSUE THREAD

**Issue by ibksturm** [DNSCrypt/dnscrypt-proxy#244]
Hi there

i downloaded aktualy version https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.7/dnscrypt-proxy-linux_arm-2.0.7.tar.gz

and after installing it shows me version 2.0.4... did you build something wrong? 

greets

andi

**Comment by jedisct1** [comment]
Where does it show version 2.0.4?

**Comment by ibksturm** [comment]
shit, i try to restep the error and now it shows 2.0.7 on log file... holy crap... ^^

as i say theres some reason why i didn't work in the learnend profession anymore... 

you can close this thread frank
