### ISSUE TITLE
go 1.21 support

### ISSUE THREAD

**Issue by namtsui** [DNSCrypt/dnscrypt-proxy#2456]
Reported bugs must reproducible in the context described in the "Context" section.

Installation and configuration issues are not bugs, but individual assistance request.

Context: the LATEST version of `dnscrypt-proxy` (precompiled binaries downloaded from this repository) is correctly installed and configured on your system, but something doesn't seem to produce the expected result.

If the bug is not trivial to reproduce on any platform, please include ALL the steps required to reliably duplicate it, on a vanilla, generic install of macOS, Windows, OpenBSD or Ubuntu Linux system, in their most current version.

If you don't have any clear understanding of the issue or can't enumerate the steps to reproduce it, open a discussion instead:
https://github.com/DNSCrypt/dnscrypt-proxy/discussions

## Output of the following commands:

./dnscrypt-proxy -version

./dnscrypt-proxy -check

./dnscrypt-proxy -resolve example.com

- [ ] Initially raised as discussion #...

## *What* is affected by this bug?

using go 1.21 causes build breakage with latest dnscrypt-proxy release

## *When* does this occur?

trying to build from openbsd ports which has recently updated go to 1.21

## *Where* does it happen?

build breakage

## *How* do we replicate the issue?

```
from openbsd ports, make clean configure then make build

===>  Building for dnscrypt-proxy-2.1.4
cd /usr/obj/pobj/dnscrypt-proxy-2.1.4/go/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy && /usr/bin/env -i GO386=softfloat GOCACHE="/usr/obj/pobj/dnscrypt-proxy-2.1.4/go-cache" TMPDIR="/usr/obj/pobj/dnscrypt-proxy-2.1.4/build-amd64" GOPROXY=invalid://ports.should.not.fetch.at.buildtime/ GO111MODULE=off GOPATH="/usr/obj/pobj/dnscrypt-proxy-2.1.4/go:/usr/local/go-pkg" PORTSDIR="/usr/ports" LIBTOOL="/usr/bin/libtool"  PATH='/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11R6/bin' PREFIX='/usr/local'  LOCALBASE='/usr/local' X11BASE='/usr/X11R6'  CFLAGS='-O2 -pipe'  TRUEPREFIX='/usr/local' DESTDIR=''  HOME='/dnscrypt-proxy-2.1.4_writes_to_HOME' PICFLAG="-fpic"  BINGRP=bin BINOWN=root BINMODE=755 NONBINMODE=644  DIRMODE=755  INSTALL_COPY=-c INSTALL_STRIP=  MANGRP=bin MANOWN=root MANMODE=644 BSD_INSTALL_PROGRAM="/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin/install -c  -m 755"  BSD_INSTALL_SCRIPT="/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin/install -c -m 755"  BSD_INSTALL_DATA="/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin/install -c -m 644"  BSD_INSTALL_MAN="/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin/install -c -m 644"  BSD_INSTALL_PROGRAM_DIR="/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin/install -d -m 755"  BSD_INSTALL_SCRIPT_DIR="/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin/install -d -m 755"  BSD_INSTALL_DATA_DIR="/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin/install -d -m 755"  BSD_INSTALL_MAN_DIR="/usr/obj/pobj/dnscrypt-proxy-2.1.4/bin/install -d -m 755" go build
# github.com/jedisct1/dnscrypt-proxy/vendor/github.com/quic-go/quic-go/internal/qtls
../vendor/github.com/quic-go/quic-go/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

## Expected behavior (i.e. solution)

successfully build against go 1.21

## Other Comments

what is the status of go 1.21 support? can a new release be made supporting go 1.21 and quic-go? I see the recent commits supporting these: https://github.com/DNSCrypt/dnscrypt-proxy/commit/0a98be94a78e088c211c7bb58a84d71287e37b34 and https://github.com/DNSCrypt/dnscrypt-proxy/commit/0a98be94a78e088c211c7bb58a84d71287e37b34

I'm trying to update the openbsd port and would want to update to a new release if available.

**Comment by jedisct1** [comment]
The current development code is completely broken, so this is not a good candidate for a release.

I can try to revert the changes that broke the cache updates, see if a release can be made before reintroducing them and eventually understanding how they can be fixed.

**Comment by namtsui** [comment]
Thanks for letting me know the status. fwiw building against 5085a22903cfc70bd48cffe99fd73c9d38d58e1d worked with go 1.21 / quic-go and dnscrypt-proxy itself runs.

**Comment by jedisct1** [comment]
CI doesn't pass. There's another issue which is hard to find because it was a comment on a commit, but it's also a blocker.

**Comment by jedisct1** [comment]
Version 2.1.5 released!
