### ISSUE TITLE
tls_key_log_file permissions

### ISSUE THREAD

**Issue by namtsui** [DNSCrypt/dnscrypt-proxy#2459]
New configuration directive: tls_key_log_file. When defined, this is the path to a file where TLS secret keys will be written to, so that DoH traffic can be locally inspected.

## Output of the following commands:

./dnscrypt-proxy -version
2.1.5

./dnscrypt-proxy -check

./dnscrypt-proxy -resolve example.com

- [ ] Initially raised as discussion #...

## *What* is affected by this bug?
tls_key_log_file can't be written to by the _dnscrypt-proxy user

## *When* does this occur?
on startup

## *Where* does it happen?
syslog:
```
Aug 11 13:24:51 dust2 dnscrypt-proxy[59985]: dnscrypt-proxy 2.1.5
Aug 11 13:24:51 dust2 dnscrypt-proxy[59985]: TLS key log file [/var/dnscrypt-proxy/keylog.txt] enabled
Aug 11 13:24:51 dust2 dnscrypt-proxy[59985]: Network connectivity detected
Aug 11 13:24:51 dust2 dnscrypt-proxy[59985]: Dropping privileges
Aug 11 13:24:51 dust2 dnscrypt-proxy[59985]: Unable to create key log file [/var/dnscrypt-proxy/keylog.txt]: [open /var/dnscrypt-proxy/keylog.txt: permission denied]
```

## *How* do we replicate the issue?

uncomment in /etc/dnscrypt-proxy.toml: tls_key_log_file = '/var/dnscrypt-proxy/keylog.txt'
in /etc/dnscrypt-proxy.toml: user_name = '_dnscrypt-proxy'

```
$ ls -al /var/dnscrypt-proxy/                                             
total 192
drwxr-xr-x   2 _dnscrypt-proxy  _dnscrypt-proxy    512 Aug 11 13:29 .
drwxr-xr-x  32 root             wheel              512 Aug  9 22:10 ..
-rw-------   1 root             _dnscrypt-proxy      0 Aug 11 13:28 keylog.txt
-rw-r--r--   1 _dnscrypt-proxy  _dnscrypt-proxy  77987 Aug 11 13:05 public-resolvers.md
-rw-r--r--   1 _dnscrypt-proxy  _dnscrypt-proxy    307 Aug 11 13:05 public-resolvers.md.minisig
-rw-r--r--   1 _dnscrypt-proxy  _dnscrypt-proxy   8957 Aug 11 13:05 relays.md
-rw-r--r--   1 _dnscrypt-proxy  _dnscrypt-proxy    297 Aug 11 13:05 relays.md.minisig
```

## Expected behavior (i.e. solution)
dnscrypt-proxy drops permissions such that the _dnscrypt-proxy user can't write to keylog.txt. keylog.txt should have write permissions for the _dnscrypt-proxy user.

**Comment by jedisct1** [comment]
Is it really a bad idea to keep secret keys that allow decrypting all the traffic only accessible to the administrator? After all capturing the packets requires root privileges.

**Comment by namtsui** [comment]
that makes sense
