### ISSUE TITLE
[FATAL] - Failed to install Service (registry key already exists)

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#246]
1) Uninstalled v2.0.6 and Reboot.

2) During installation v2.0.7 I've got this (log):

```
[FATAL] Failed to install DNSCrypt client proxy: InstallAsEventCreate() failed: SYSTEM\CurrentControlSet\Services\EventLog\Application\dnscrypt-proxy registry key already exists
[FATAL] Failed to start DNSCrypt client proxy: The specified service does not exist as an installed service.
```
3) [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\dnscrypt-proxy]

Deleted "dnscrypt-proxy" registry key completely.

4) Installed again.

5) OK.

**Comment by jedisct1** [comment]
Can you describe all the steps (all the commands you typed, and things you clicked) to reproduce this on a new Windows installation?

**Comment by iWARR** [comment]
1) First, you must have v2.0.6 installed and working. Install and reboot PC to be sure that dnscrypt-proxy works and service started automatically, as usual.

2) Uninstall v2.0.6 using *.bat
Update all necessary files to v2.0.7 in the installation folder.
Mine folder (permanent path) is : `C:\Program Files\dnscrypt-proxy\`
Move your settings to v2.0.7.
Everything as usual.

3) Try to install the new v2.0.7 with *.bat file. But, probably, dnscrypt-proxy will not work. You will find described error in the `'dnscrypt-proxy.log'`.

I don't know if it reproducable on your fresh Windows installation. But mine error was.

4) To fix this, you have to delete registry key, that breaks v2.0.7 service installation (I never saw such trouble before). So:

Start -> Run
Type the command: `regedit`

Go to:

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\dnscrypt-proxy]

and delete the last key (looks like a yellow folder) from the path above: dnscrypt-proxy

5) Now, installation of dnscrypt-proxy have to work.

--------------
Very strange error. But very easy to fix manually.

**Comment by evilvibes** [comment]
I had this issue also when using SimpleDNS (https://github.com/bitbeans/SimpleDnsCrypt/issues/202)

I fixed it by doing the same thing. Can't give much more info on it as I moved away from windows for linux.

**Comment by iWARR** [comment]
v2.0.8 is OK. May close.
