### ISSUE TITLE
org site's content partially obsolete

### ISSUE THREAD

**Issue by Ricky-Tigg** [DNSCrypt/dnscrypt-proxy#2469]
Hello. With the existence of **two sites** dedicated to DNSCrypt protocol, _dnscrypt xxxorg_ and _dnscrypt.info_, linking the development to https://github.com/DNSCrypt/dnscrypt-proxy, it cannot be determined which is of higher relevancy or official. When it comes to the content located at https://www.dnscrypt xxxorg/#about, it cannot be missed that it has become partially obsolete.

Illustrations:
- Current stable DNSCrypt client and server versions, respectively "_1.9.5_" and "_0.3_". Version mentions not updated automatically.
- "_[Nov 1, 2017] Simple DNSCrypt 0.4.3 released!_". Date and version mention not updated automatically.
- See section _DNSCrypt for Windows_. Suggestions; _note:_ order matters:
  - _**Open source products for Windows that implement the DNSCrypt protocol**_
  - _dnscrypt-proxy https://github.com/DNSCrypt/dnscrypt-proxy/ | Reference client implementation that works natively on Windows, from XP to 11 editions. Runs as a service. Does not provide a graphical user interface. Command-lines required for its installation and configuration. Excellent choice for advanced users. Actively maintained._
  - _Simple DNSCrypt https://github.com/bitbeans/SimpleDnsCrypt | All-in-one, easy-to-use, stand-alone client. Not actively maintained and for reason; one-way relationship. Get a good illustration by looking at numbers of open tickets and pull requests._
  - _pique (or repique) https://github.com/AZ-X/pique | Advanced DNS stub. Runs on OpenWRT, Linux, Windows. Excellent choice._
  - _instantsc's SimpleDnsCrypt as for of bitbeans' SimpleDnsCrypt https://github.com/instantsc/SimpleDnsCrypt/ | Action required to migrate existing settings._
- See section _Alternative clients, installation scripts and GUIs for Unix_. Suggestions:
  - DNSCrypt-Loader https://github.com/GortCodex/DNSCrypt-Loader | Console-based tool to manage the DNSCrypt proxy client on Linux. Requires a minimal amount of dependencies. Has an always up-to-date list of resolvers. Can automatically change the DNS settings to use DNSCrypt. Not actively maintained.
  - Link for _Pcap_DNSProxy_ has become obsolete. Though on the same platform, the existence of a same-named repository whose project also deals with the DNSCrypt protocol can be found.

**Comment by jedisct1** [comment]
That website is not affiliated with the project.

It's run by what presumably is some shady marketing/black hat SEO company.

They made a copy of an early version of the website, only to add links to an online casino website.

I guess the intent is to steal traffic and cheat on Google results.

Don't go there. Block it. Report it. 

Unfortunately, results from Google (and other search engines) cannot be trusted, as crooks constantly find ways to manipulate them.
