### ISSUE TITLE
Enable DNSECC

### ISSUE THREAD

**Issue by jonathanmmm** [DNSCrypt/dnscrypt-proxy#247]
Hello,

I am using Dnscrypt-proxy 2.0.7 linux arm 32 bit

The dnscrypt-proxy is used as the dns for my pihole (same machine) and both have enabled dnssec, so what means enable dnssec means?

Is the dnscrypt-proxy already checking with dnssec so because it is only in my home LAN the second is not of any use or is the dnssec enabled mean it enables clients to use dnscrypt-proxy with their service to use dnssec.

Hope you can help me, the version 2 is a great upgrade to version 1.9.5, could delete version 1.9.5.

Secon question? Is it possible to have backup dnscrypt servers (if my first dnscrypt server adguard-dns is failing somehow)? It always picks the fastest but I want that it picks another, if the first fails or is the fallback for this issue used?

Greetings

**Comment by jedisct1** [comment]
Hi!

`dnscrypt-proxy` doesn't do DNSSEC validation itself, but can be configured to only use servers that already do it for you. This is what `require_dnssec` does.

You don't need to enable this on Pi-Hole. Maybe this has changed, but I remember messages about dnsmasq being too old to reliably do DNSSEC validation anyway.

The configuration file can include as many servers as you like, and the way the load is balanced can be configured with the `lb_strategy` property. With `fastest`, it will use only the fastest, but if that one fails, it will use the next one.

**Comment by jonathanmmm** [comment]
Thanks for the reply.

What do you mean with servers that already do it for you?

So if I would use dnscrypt-proxy as the dnsserver for a Client without pihole it would let the client make the dnssec to e.g. adguard-dns (through dnscrypt-proxy)?

I thought dnscrypt-proxy only accepts dnsecc validated DNS resolves when it is set to "true"

**Comment by jedisct1** [comment]
```
<authoritative server>----<recursive server>----<dnscrypt-proxy>---<dnsmasq("pi-hole")>---<client>
                      ^^^^^
          this is what DNSSEC verifies    

                            ^^^^^^^^^^^^^
                      this is where it gets verified
```

**Comment by ibksturm** [comment]
hi there 
@jonathanmmm i've got the same "Herausforderung" (i did'nt know the english word and yes, translate.google was rolled-out in switzerland too) so my solution was the servers:

[2018-03-21 21:22:13] [NOTICE] [cloudflare] OK (DoH) - rtt: 17ms
[2018-03-21 21:22:13] [NOTICE] [dnscrypt.eu-dk-ipv6] OK (crypto v1) - rtt: 46ms
[2018-03-21 21:22:13] [NOTICE] [dnscrypt.nl-ns0-ipv6] OK (crypto v1) - rtt: 43ms

ok, i prefer IPV6 servers (i clicked myself a tunnel at hurrican, cause my **** ISP want sell me a true DUALSTACK V4 and V6 internetcable)

cloudflare seems to be stable and fast as a shark, with DNSSEC... porn, malware and adblocking do i on dnscrypt-proxy at home with the cool generating file in the dnscypt-proxy git

as frank wrote about, DNSSEC is to verifies the trueness of dns request's... so as i understand all dns-forwarders need to handle it with dnssec (or you have to install a bind or a unbound server yourself, that handle it with the root servers himself)

on my experience adguard-dns doesn't handle at the moment DNSSEC (it's in their pipeline), cleanbrowsing-adult && cleanbrowsing-familiy wrote that they are using DNSSEC, but my tests at https://dnssec.vs.uni-due.de/ sucks... 

with cisco (opendns) the same shit.. opendns marketing people wanna push dnscrypt, and wrote on their website how super are the combination between dnssec and dnscrypt (https://www.opendns.com/about/innovations/dnscrypt/), but they never ever implemented dnssec... (https://support.opendns.com/hc/en-us/community/posts/220028387-OpenDNS-and-DNSSEC)

greets from switzerland

**Comment by jedisct1** [comment]
(FWIW, I invented the protocol, and don't believe web pages written by marketing departments).

**Comment by jedisct1** [comment]
Regarding IPv6, some changes have been made today so that IPv6 will be preferred even for DoH servers if `require_ipv4` is set to `false`.

So, if you have IPv6 connectivity, it will now also use Cloudflare over IPv6.

Seems to work well, so it will be in the next release. I'm gonna add IPv6 support to `doh.crypto.sx` as well.

**Comment by ibksturm** [comment]
@jedisct1 sorry, if i trumped on your feed, don't wanna do that :(

with marketing companys, i've got too much to do on work (eventtechmen) they grab the money an we techies the... something else... 

cloudflare on IPv6 and doh works fine
