### ISSUE TITLE
[RESEARCH] Drawback of servers list 2.0

### ISSUE THREAD

**Issue by sergeevabc** [DNSCrypt/dnscrypt-proxy#249]
In 2017, I made a Windows [batch script][3] that helps to find the most reachable DNSCrypt servers, given the current network environment. The first step to accomplish this task is to extract IPs along with NoLogs and DNSSEC flags out of [```dnscrypt-resolvers.csv```][1]. Now I see a new list [```public-resolvers.md```][2] is emerging, where these features are hidden. Thus, it becomes harder to decide which servers to use or to avoid.

It appears to be a drawback, what would you say? 

![](https://pli.io/4506y.png)

[1]: https://raw.githubusercontent.com/dyne/dnscrypt-proxy/master/dnscrypt-resolvers.csv 
[2]: https://download.dnscrypt.info/dnscrypt-resolvers/v2/public-resolvers.md
[3]: https://app.box.com/s/a5144laen397pty0lob8d2b50803h3lx

**Comment by s-s** [comment]
These flags are encoded in [stamps](https://github.com/jedisct1/dnscrypt-proxy/wiki/stamps).
Also, there is a "-json" flag that can be mixed with "-list" or "-list-all" flags to dump resolvers lists as json.

**Comment by s-s** [comment]
Forgot to mention, that dnscrypt-proxy v2 has a built-in "ping" and different load balancing strategies among a set of resolvers.

**Comment by jedisct1** [comment]
And some resolvers don't have an IP at all...

**Comment by sergeevabc** [comment]
@jedisct1, please, keep in mind that a lot of SOHO routers [cannot be updated ][1] to DNSCrypt 2.x,
therefore the previous servers list format (CSV) will remain in demand for a long time

[1]: http://www.linksysinfo.org/index.php?threads/any-thoughts-about-dnscrypt-proxy-2-and-tomato.74088/#post-295497
