### ISSUE TITLE
Could anyone  tell me how to add my own server, please?

### ISSUE THREAD

**Issue by zbc258** [DNSCrypt/dnscrypt-proxy#2491]
I have tried to add the Public DNS address (202.206.240.12) provided by our school as a local server to the toml.
I declared its name first: 
server_names = ['school']
Then I calculated its stamp  through this site : https://dnscrypt.info/stamps/ 
And put it in the 'static' column:
[static]
	[static.school]
		stamp ='sdns://AQAAAAAAAAAADjIwMi4yMDYuMjQwLjEyAAA' 
But it didn't work as expected.
In log, it told me:
[2023-09-24 21:54:19] [FATAL] Stamp error for the static [school] definition: [Stamp is too short]
So how can I solve it?  I will appreciate it.

**Comment by jedisct1** [comment]
`dnscrypt-proxy` was made for encrypted DNS servers. An unencrypted, unauthenticated server cannot be used.
