### ISSUE TITLE
How to setup your own DNSCrypt server in 10 minutes

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#25]
Just wrote some from-scratch instructions to setup your own DNSCrypt server in less than 10 minutes:

https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes

There are other ways to do it, for example using dnsdist or unbound's built-in dnscrypt support.
But this is how I've been running my server for years, and it doesn't require any maintenance.

**Comment by ghost** [comment]
This is awesome. Great work!

**Comment by elmakong** [comment]
thanks! will start to read, and may be soon be available

update:
i have read the wiki, and then i wondering how to use ipv6 also with ipv4?

update:
tried to duplicate your steps on wiki, got sdns, but the dnscrypt-proxy expecting dnsc

> D:\Program Files\dnscrypt-proxy-win64-2.0.0beta8\win64>dnscrypt-proxy.exe -service install
[2018-01-24 19:08:40] [NOTICE] Source [https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v1/dnscrypt-resolvers.csv] loaded
[2018-01-24 19:08:40] [FATAL] Stamps are expected to start with dnsc://

The server detail i got from docker:

> Stamp for dnscrypt-proxy 2.x:
  >sdns://AQECAAAAAAAAEjEyOC4xOTkuMTU3LjUyOjQ0MyBZAbQgN9AuTDnesGW1wGzyBqH_mwhEBwmYfBXtD0hFVRsyLmRuc2NyeXB0LWNlcnQuc2cuaG9zaGkuaWQ
>
>Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=5901:B420:37D0:2E4C:39DE:B065:B5C0:6CF2:06A1:FF9B:0844:0709:987C:15ED:0F48:4555
                 --resolver-address=128.199.157.52:443
                 --provider-name=2.dnscrypt-cert.sg.hoshi.id


i will keep this server running. currently on digitalocean(Ubuntu Docker 17.12.0~ce on 16.04)

**Comment by jedisct1** [comment]
Old version of dnscrypt-proxy; update it :)

**Comment by elmakong** [comment]
waiting for pre-built binary for win64 😄

**Comment by jedisct1** [comment]
New binaries are available: https://github.com/jedisct1/dnscrypt-proxy/releases/latest

Thought it was already the case, but I forgot to push the tag.

**Comment by jedisct1** [comment]
I don't expect the procedure to be radically different on Digital Ocean, AWS, Hetzner or whatever, but if that happens to be the case, please let me know so I can add specific instructions for other cloud providers.

**Comment by jedisct1** [comment]
@elmakong your stamp is valid but looks like the service is not running any more:

```
[2018-01-24 16:09:28] [ERROR] read udp 192.168.100.4:56985->128.199.157.52:443: i/o timeout
```

**Comment by elmakong** [comment]
@jedisct1 it seems, the command to autostart the docker service after reboot is not working as expected. i have restarted the service

also, the ufw(firewall) entry must be added for port used. for mine:
 `sudo ufw allow https`

now i can confirm that the server is can be used

> D:\Program Files\dnscrypt-proxy-win64-2.0.0beta9\win64>dnscrypt-proxy.exe -resolve google.com
Resolving [google.com]
>
>Domain exists:  yes, 4 name servers found
Canonical name: google.com.
IP addresses:   216.58.221.78
TXT records:    v=spf1 include:_spf.google.com ~all
Resolver IP:    128.199.157.52 (sgp2.host.hoshi.id-docker.)

update: 
i am bit confused as the dns sometimes got passed through my ISP dns server(it means i got no unfiltered/uncensored dns record sometimes)

**Comment by ewan2395** [comment]
It seems that this container also suffers from the issue raised here: https://github.com/DNSCrypt/dnscrypt-server-docker/issues/38

Applying this [patch](https://gist.github.com/chantra/2636c99ec14e2d044846aa90011c8019) seems to solve the issue.

**Comment by tuttimann** [comment]
Does the docker image automatically upgrade the dnscrypt-server if a newer version is published?

**Comment by jedisct1** [comment]
Docker images don't self upgrade. They are very easy to upgrade, though (just "docker pull" but double check that you have a copy of the secret keys somewhere before), and there are 3rd party tools to do it automatically such as [watchtower](https://github.com/v2tec/watchtower).

**Comment by tuttimann** [comment]
Can you tell me how to store a copy of the secret keys outside Docker? Is it possible to cp a file in Docker out of it? Thanks for your help

**Comment by jedisct1** [comment]
I added some instructions here: https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes#backuping-important-data

**Comment by tuttimann** [comment]
Big thanks for your work! :)

**Comment by tuttimann** [comment]
Is it possible that you also add the instruction how to upgrade the docker image with „docker pull“?
Maybe you could give an example of the command that would upgrade your docker image in the HowTo.

**Comment by bitbeans** [comment]
Added an alternative (provider): https://github.com/jedisct1/dnscrypt-proxy/wiki/DNSCrypt-server-with-vultr.com :)

**Comment by jedisct1** [comment]
Awesome!

**Comment by Sporif** [comment]
@bitbeans I followed your guide and the server _seems_ to be working fine on the server end, but dnscrypt-proxy cannot resolve anything. This is the server:

```
[static.'uk.dnscrypt.net']
  stamp = 'sdns://AQECAAAAAAAAETQ1Ljc2LjEzNC4xNDM6NDQzIIwpnuEB6DunquMHZEDIFr93EQPUU51Skaa-hqyq5J_QHzIuZG5zY3J5cHQtY2VydC51ay5kbnNjcnlwdC5uZXQ'
```

It doesn't seem to be responding to any requests. No idea what's wrong. Tried reinstalling it, same thing happens. Also the startup script did not get executed, I had to manually download and start it.

**Comment by jedisct1** [comment]
```
[2018-01-31 00:35:41] [NOTICE] [uk.dnscrypt.net] TIMEOUT
[2018-01-31 00:35:41] [ERROR] read udp 192.168.100.4:50936->45.76.134.143:443: read: connection refused
```

Maybe a firewall issue? I'm not familiar with Vultr, but do you have to do something to allow ports to be reachable?

**Comment by Sporif** [comment]
Yep it was a firewall issue, all connections were set to be rejected:
```
[root@uk ~]# iptables -L INPUT -n --line-numbers
Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination
1    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
2    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
3    INPUT_direct  all  --  0.0.0.0/0            0.0.0.0/0
4    INPUT_ZONES_SOURCE  all  --  0.0.0.0/0            0.0.0.0/0
5    INPUT_ZONES  all  --  0.0.0.0/0            0.0.0.0/0
6    DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
7    REJECT     all  --  0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited

```

I removed the 7th line with ` iptables -D INPUT 7` and now https is accepted. Looks like it's working now! :)

Now to figure out how to save this for reboots...

**Comment by bitbeans** [comment]
@Sporif i updated the wiki and the script :)
You also can disable the firewall and add a firewall at the vultr.com webinterface for your server.

EDIT: feel free to edit/update the wiki :P

**Comment by jedisct1** [comment]
It works!

```
[2018-01-31 07:36:33] [NOTICE] [uk.dnscrypt.net] OK (crypto v2) - rtt: 13ms
[2018-01-31 07:36:33] [NOTICE] Server with the lowest initial latency: uk.dnscrypt.net (rtt: 13ms)
[2018-01-31 07:36:33] [NOTICE] dnscrypt-proxy is ready - live servers: 1
```

**Comment by chaosbunker** [comment]
I set this up a week ago and it worked fine but now when i am doing it again i get after `docker run ...`

> error: unknown option `--nofilter`
>Usage: dnscrypt-wrapper [options]
>
>    -h, --help                                show this help message and exit
>    --gen-cert-file          
>etc..
> chmod: cannot access '/opt/dnscrypt-wrapper/etc/keys/secret.key': No such file or directory

**Comment by Sporif** [comment]
Same here, mine just broke. Watchtower must've restarted it with this new image. Reinstall gives that same error too. dnscrypt-server:/opt/dnscrypt-wrapper/etc/keys/ is empty except for provider-info.txt, which only contains the the usage options of dnscrypt-wrapper.

**Comment by jedisct1** [comment]
Oops my bad. I updated one of the scripts without bumping the Docker image revision number, so it didn't pick up the latest version of dnscrypt-wrapper.

The docker hub should build the updated image in a couple minutes.

Sorry for that :(

**Comment by tuttimann** [comment]
Hi all, what is the command when you want to pull a newer Docker image and when you already have installed this image in an older version?
I don't get the right command.

**Comment by chaosbunker** [comment]
docker pull jedisct1/dnscrypt-server

**Comment by tuttimann** [comment]
> docker pull jedisct1/dnscrypt-server

Thanks for your work and your help with my problems :)

**Comment by chaosbunker** [comment]
@jedisct1 would you mind offering an arm64 image as well? I made my own now but it would be cool if i could just pull it from docker hub in the future:-)

**Comment by jedisct1** [comment]
Images are built automatically by the Docker Hub, but I don't think they support ARM64 at this time.

**Comment by chaosbunker** [comment]
Oh, ok. I thought since you are running a dnscrypt-server on a scaleway arm64 server anyway you would already have an arm64 image ready and could just push that to docker hub

**Comment by jedisct1** [comment]
It's running exactly the same code and scripts as in the docker image, but... not in Docker.

Since the server doesn't do anything else, I initially didn't bother using Docker.

**Comment by Sporif** [comment]
@jedisct1 After reinstalling and running dnscrypt-server I tried restoring the keys folder but it doesn't work, dnscrypt-proxy can't resolve anything (the new key works though). I see that there's also 'short-term' folder in dnscrypt-server:/opt/dnscrypt-wrapper/etc/keys that isn't in my backup. Is there any way of regenerating it for the old key? It isn't a big deal, I can just use the new key, but I just wanted to know.

**Comment by jedisct1** [comment]
Remove everything from `/etc/keys`, especially the short-term keys. Just copy the backed up files, and restart the container.

**Comment by Sporif** [comment]
Alright, removing short-term folder then copying backups works. Thanks! :)

**Comment by JunShine** [comment]
Can I change the server's 443 port?.......

**Comment by jedisct1** [comment]
@JunShine Yes, you can change the port.

In that command:
```sh
docker run --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host \
        jedisct1/dnscrypt-server init -N example.com -E 192.168.1.1:443
```

Replace `-p 443:443` with `-p 4242:443` to export port 4242 instead. The container will still use port 443 internally, but clients will connect to port 4242.

If it doesn't work, you may have to remove `--net=host`.
