### ISSUE TITLE
Not a dnscrypt-proxy issue, only a strange server behavior

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#253]
This is in no way a dnscrypt-proxy issue, and I understand servers' responsibility is their own; yet I face an odd behavior with Cloudflare.

I decided by curiosity to test the Cloudflare server, alone: `server_names = ['cloudflare']`

As soon as I restarted dnscrypt-proxy sith this new Cloudflare server, a look at _Nirsoft's CurrPorts_ application showed a 3rd `dnscrypt-proxy.exe` appearing and disappearing with _Remote Address = **104.19.193.102**_ which is a CloudFlare address.

I've tested several servers (always alone) and I've never noticed a connection to their parent company.
I don't understand why a dnscrypt-proxy server needs to behave independently so to say of the application (dnscrypt-proxy) it... serves.

This thread aims to a better understanding, it is in no way meant to discredit dnscrypt-proxy (2.0.7) which runs here perfectly well.

Thanks.

**Comment by jedisct1** [comment]
`104.19.193.102` is the IP address of `dns.cloudflare.com`, the public DNS server you are using.

Unlike DNSCrypt servers, these types of servers (DNS-over-HTTP/2) work like websites. They connect, exchange some data, and disconnect when there hasn't been anything to transfer any more for quite some time.

**Comment by ghost** [comment]
So that's the explanation... thanks @jedisct1 

I know nothing of DNS-over-HTTP/2, not even if DNS-over-HTTP/2 and DNS-over-HTTPS are two different protocols. I thought that doh (DNS-over-HTTPS) would be activated only if I had chosen,
```
## doh-crypto-sx
Experimental DNS-over-HTTPS server, globally cached via Cloudflare.
Maintained by Frank Denis.
```
Looks like I'm riding a Ferrari as if it were driving an old _2 cheveaux_ (_dodoche_ in French). 
I have a lot to learn, lol

Thanks.

**Comment by jedisct1** [comment]
Cloudflare and Google use DoH.

But really, it doesn't make any practical difference.

**Comment by ghost** [comment]
All this is obvious for you, Frank, for those who have the knowledge. Not a complaint, a fact.

1 -There is the conceptualization, understanding the basics. SSL becoming TLS, then DNS, then encryption, OK. Now, DNS over TLS ... getting tougher but documentation is available.

2- Terminology. I read DNS over TLS, DNS over http, DNS over https, DNS over http/2 ... and that's where the merry starts going square rather than round!

Thanks, Frank. I'll have to spend some time and dig as deep as I can to better figure out these new DNS protocols. At this time I'm mixed up!

Another question:

What's the difference between using _Google_ or _Cloudflare_ (with `doh_servers = true` of course) and using _doh-crypto-sx_ (Experimental DNS-over-HTTPS server)? That, I really don't understand.
...
I'm presently testing `server_names = ['doh-crypto-sx']` (experimental) and it works flawlessly.
But what difference with `server_names = ['cloudflare']`? Both are DoH?

Frankly, Frank, gimme a hint if you please!
