### ISSUE TITLE
Add an option for 2nd resolver (backup resolver)?

### ISSUE THREAD

**Issue by Utini2000** [DNSCrypt/dnscrypt-proxy#256]
Hey there,
I have been using dnscrypt for ~2 years now and experienced several times already that the dns resolver of my choice went offline for a few days (cisco, dnscrypt.eu-nl, d0wn,...).

Could you add an option to the dnscrypt-proxy.conf to specify a 2nd resolver in case the first one goes offline? This is smth that you can usually also set with most network managers on windows,linux,android and even iOS.

**Comment by jedisct1** [comment]
As documented (and the example file even includes two resolvers), you can list as many resolvers as you like in `server_names`.

Or even leave the list empty to use *all* the resolvers matching the filters.
