### ISSUE TITLE
> Use IP instead of the domain for the http_proxy (e.g., https://192.168.1.100:1883/ instead of https://proxy.acme.com:1883/)

### ISSUE THREAD

**Issue by ahmad1986Ahmad** [DNSCrypt/dnscrypt-proxy#2621]
> Use IP instead of the domain for the http_proxy (e.g., https://192.168.1.100:1883/ instead of https://proxy.acme.com:1883/)

I think it is the easy solution and normal way, that leads people without motivation to do it in the hard way.

_Originally posted by @lifenjoiner in https://github.com/DNSCrypt/dnscrypt-proxy/issues/2256#issuecomment-1441709395_

**Comment by jedisct1** [comment]
Spam bots are getting weird.
