### ISSUE TITLE
Privdrop is needed for OpenBSD if one desires to run it on port 53.

### ISSUE THREAD

**Issue by mtrxgltch** [DNSCrypt/dnscrypt-proxy#263]
Right now dnscrypt-proxy does not have a privsep/privdrop/chroot mechanism. I made a small quick and dirty patch. This allows me to run it on the default port (53) with dropped permissions (not as root) on OpenBSD. However dnscrypt-proxy downloads the server list file (as root) as one of the first things it does before binding. The download should somehow happen only after a privdrop/chroot for security reasons. Talking to the network as root, subsequent permission issues, etc... It would take a substantial amount of work to rework it to download the file(s) after a privdrop/chroot. Otherwise it's great! Thank you for this new version. I hope it will get proper privdrop eventually so we can enjoy it on the default port on the BSDs with chroot.
[dnscrypt-proxy-privdrop.patch.txt](https://github.com/jedisct1/dnscrypt-proxy/files/1844810/dnscrypt-proxy-privdrop.patch.txt)

**Comment by jedisct1** [comment]
Unfortunately, it isn't safe to do so: https://github.com/golang/go/issues/1435

fork+execute is a better approach, but passing the descriptors also seem tricky in Go.

`pledge()` is natively supported, though: https://go.googlesource.com/sys/+/8fd966b47dbdd4faa03de0d06e3d733baeb9a1a9%5E%21/ -- maybe something we can use on OpenBSD.

**Comment by mtrxgltch** [comment]
Threads disrespecting privdrop changes seems to be a linux only issue. I could be wrong, but I didn't see any threads continuing to run as root on OpenBSD.

**Comment by jedisct1** [comment]
Maybe, but this is not something that can be merged, unless it works as expected on all platforms, including Linux, Android, iOS and Windows.

**Comment by mtrxgltch** [comment]
I also wonder if it's possible to move the initial server list downloads into a separate process that can run privdropped in go? I guess BSDs could apply their own privdrop patches in packages, but the download part would result in a complete rewrite I think.
