### ISSUE TITLE
[feature-request] Option to avoid usage of servers from client country

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#264]
I recently did upgrade to v2 and enjoy it, especially how "the proxy will automatically pick the fastest, working servers from the list". For some people this means though that they will be connected to servers in their country. So unless manually defining a list you have not much options to counter this.

There are a few reasons why it could be bad if client and server are in the same country:
1) makes it easier to monitor clients of that server if you have jurisdiction over both
2) no control over physical access if a 3rd party hoster is involved
3) if your country is a member of the five eyes intelligence alliance

Suggesting an option like:
avoid_location = 'CN'

It should only be one country to avoid crippling the config, I still hope for the best and that most servers will be safe to use, just not those where a person lives.

**Comment by JayBrown** [comment]
You could also implement an additional options for broader geoblocks with `5E` (five eyes), `9E` (nine eyes), `14E` (fourteen eyes).

**Comment by jedisct1** [comment]
I'm not sure that such a feature should be part of the proxy itself. 

And what really matters, especially after the CLOUD Act, is not just where the server is, but if it's a company with a presence in the US.

If this is a concern, really, one should carefully choose the server they want to use, or run their own. I don't think the proxy should attempt to apply unreliable filters.

**Comment by ghost** [comment]
Location can be a field in public-resolvers.md and the owner of the server likely can provide it as they would know best. I am not trying to force a feature you don't like, but it seems trivial to check a text file for that. Either way thanks for the reply, consider it and decide as you please :)

**Comment by jedisct1** [comment]
The text is freeform, so it's not easy to parse as it's designed to be read by humans.

A server operated by Digital Ocean or Google, can be in Japan, but since Digital Ocean and Google are US companies, US will be allowed to freely access their content no matter what.

An OVH server can have an IP in Ireland, but actually be in France. So, that's a bit tricky, and probably out of scope of this project.
