### ISSUE TITLE
Dnscrypt --version Shows 1.9.5

### ISSUE THREAD

**Issue by jonathanmmm** [DNSCrypt/dnscrypt-proxy#266]
Hi,
I am running rasbian Jessie Lite.

It seems I have not completely removed the old Version, can you help me, please?
/Etc/systemd/system i disabled everything or is this just normal?

Also in the .toml File, the p2, ph for which resolver is locker does Not make an difference.

Ich want that it picks allways the First, unless it dies not work. Then it should try the second and so on.

Hope you can help me, great programm by the way :)

**Comment by jonathanmmm** [comment]
I downloaded 2.0.7 arm 32bit

Just disabling everything dnscrypt-proxy and to remove ist in etc/systems/system is the right way or can I somehow Upgrade properly?

**Comment by jedisct1** [comment]
`apt-get remove --purge dnscrypt-proxy` should remove the package and its configuration.

**Comment by jonathanmmm** [comment]
Doesnt Work, it was installed not through apt-get

But with the guide from https://itchy.nl/raspberry-pi-3-with-openvpn-pihole-dnscrypt I believe
Am 26.03.18, 11:33, Frank Denis <notifications@github.com> schrieb:
apt-get remove --purge dnscrypt-proxy should remove the package and its configuration.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jedisct1/dnscrypt-proxy","title":"jedisct1/dnscrypt-proxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jedisct1/dnscrypt-proxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jedisct1 in #266: `apt-get remove --purge dnscrypt-proxy` should remove the package and its configuration."}],"action":{"name":"View Issue","url":"https://github.com/jedisct1/dnscrypt-proxy/issues/266#issuecomment-376104894"}}}

**Comment by jonathanmmm** [comment]
It is working and choosing the right settings from .toml, but why is the .toml service dead?

Before I also removed everything in /lib/systemd/system

aspberrypi:~/dnsproxy/dnscrypt-proxy $ sudo ./dnscrypt-proxy -service i               
nstall                                                                                    
[2018-03-26 12:11:39] [NOTICE] Source [https://download.dnscrypt.info/resol               
vers-list/v2/public-resolvers.md] loaded                                                  
[2018-03-26 12:11:39] [NOTICE] dnscrypt-proxy 2.0.7                                       
[2018-03-26 12:11:40] [NOTICE] Installed as a service. Use `-service start`               
 to start                                                                                 
pi@raspberrypi:~/dnsproxy/dnscrypt-proxy $ sudo ./dnscrypt-proxy -service s               
tart                                                                                      
[2018-03-26 12:11:48] [NOTICE] Source [https://download.dnscrypt.info/resol               
vers-list/v2/public-resolvers.md] loaded                                                  
[2018-03-26 12:11:48] [NOTICE] dnscrypt-proxy 2.0.7                                       
[2018-03-26 12:11:48] [NOTICE] Service started                                            
pi@raspberrypi:~/dnsproxy/dnscrypt-proxy $ dnscrypt-proxy --version                       
dnscrypt-proxy 1.9.5                                                                      
                                                                                          
Compilation date: Aug 14 2017                                                             
Support for plugins: present                                                              
Plugins root directory: [/usr/local/lib/dnscrypt-proxy/]                                  
Support for systemd socket activation: present                                            
pi@raspberrypi:~/dnsproxy/dnscrypt-proxy $ sudo systemctl status dnscr*                   
● dnscrypt-proxy.service - Encrypted/authenticated DNS proxy                              
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled)                   
   Active: active (running) since Mon 2018-03-26 12:11:48 CEST; 29s ago                   
 Main PID: 18690 (dnscrypt-proxy)                                                         
   CGroup: /system.slice/dnscrypt-proxy.service                                           
           └─18690 /home/pi/dnsproxy/dnscrypt-proxy/dnscrypt-proxy                        
                                                                                          
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
Mar 26 12:11:48 raspberrypi dnscrypt-proxy[18690]: [2018-03-26 12:11:48]...               
                                                                                          
● dnscrypt-proxy.toml.service                                                             
   Loaded: not-found (Reason: No such file or directory)                                  
   Active: inactive (dead)                                                                
Hint: Some lines were ellipsized, use -l to show in full.                                 
Am 26.03.18, 11:33, Frank Denis <notifications@github.com> schrieb:
apt-get remove --purge dnscrypt-proxy should remove the package and its configuration.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jedisct1/dnscrypt-proxy","title":"jedisct1/dnscrypt-proxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jedisct1/dnscrypt-proxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jedisct1 in #266: `apt-get remove --purge dnscrypt-proxy` should remove the package and its configuration."}],"action":{"name":"View Issue","url":"https://github.com/jedisct1/dnscrypt-proxy/issues/266#issuecomment-376104894"}}}

**Comment by jedisct1** [comment]
Remove everything with `dnscrypt` in the file name and start over.

I have no idea where the `dnscrypt-proxy.toml.service` file come from; there isn't anything like that in any versions.

**Comment by jonathanmmm** [comment]
Where should I remove it?

It does not matter in which folder I am.
If I enter dnscrypt-proxy --version it Shows 1.9.5

**Comment by jonathanmmm** [comment]
I removed everything in:
/usr/local/share/doc
/usr/local/sbin
and after /usr/local/share/doc I believe it is gone.

But now after this I can not use dnscrypt-proxy in every folder.

Also uninstalled (now sucessfully 2.0.7) and installed it again.

Do I have to put a file in the doc or in some other folder named below to make this work?

Like you can use everywhere "cd" or "pihole" and so on.

**Comment by jonathanmmm** [comment]
Also If I use lb_strategy ph or p2 or fastest or random it allways just gives the following in "sudo systemctl status dnscrypt-proxy.service"

 Server with the lowest initial latency: .... (but random should ignore that, right and the other two probably too).

What does ph or p2 mean? fastest and random is clear.

**Comment by jedisct1** [comment]
This will be eventually documented :)
