### ISSUE TITLE
[FATAL] error returns for .toml when trying to use dnscrypt-proxy CLI

### ISSUE THREAD

**Issue by JayBrown** [DNSCrypt/dnscrypt-proxy#267]
I tried to use the dnscrypt-proxy CLI today, e.g. `dnscrypt-proxy -config "dnscrypt-proxy.toml"`, `dnscrypt-proxy -check` etc., but it always returns the error:

```
[YYYY-MM-DD HH:MM:SS] [FATAL] open dnscrypt-proxy.toml: no such file or directory
```

I'm on v2.0.7, installed using Homebrew on 10.11.6. DNSCrypt proxy itself is working great, only the CLI produces these errors. Seems like it doesn't find the .toml file. It's in `/usr/local/etc` and named correctly: `dnscrypt-proxy.toml`.

**Comment by jedisct1** [comment]
It's trying to find the configuration file in the current directory, as well as in the directory of the executable file. If it's in `/usr/local/etc`, you should use `-config /usr/local/etc/dnscrypt-proxy.toml`.

I haven't looked at the Homebrew package yet, but I guess they changed the startup script to include this option.

**Comment by JayBrown** [comment]
Ah, this worked. Thank you. I do see another "fatal error":

```
dnscrypt-proxy -config /usr/local/etc/dnscrypt-proxy.toml
[2018-03-26 11:41:49] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2018-03-26 11:41:49] [NOTICE] dnscrypt-proxy 2.0.7
[2018-03-26 11:41:49] [FATAL] listen udp 127.0.0.54:53: bind: permission denied
```

`force_tcp` in the TOML is set to `false`, so the denied permission should have another reason. (?)

**Comment by JayBrown** [comment]
Only for the -config option. This one still says there's no toml:

```
dnscrypt-proxy -check /usr/local/etc/dnscrypt-proxy.toml
[2018-03-26 11:58:28] [FATAL] open dnscrypt-proxy.toml: no such file or directory
```

PS: OK, you actually have to `cd` into /usr/local/etc. Then it works. (!)
