### ISSUE TITLE
[ISSUE] - Automatic log files rotation

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#268]
Using this settings for **Automatic log files rotation**:

```
log_files_max_size = 4
log_files_max_age = 0
log_files_max_backups = 0
```

...I have 2 archives ***.log.gz** for `'query.log'` and 2 archives for `'blocked.log'` since 22.03.2018 until today. Why it continue producing of the backups within ` 0 ` settings?

For example, if I'm expecting for the cutted `'query.log'`, 4Mb in size, (it works) with no backups (it doesn't works).

**Comment by jedisct1** [comment]
Log files are handled by a 3rd party project called [Lumberjack](https://github.com/natefinch/lumberjack)

Apparently, when `MaxBackups` is zero, it means "keep all backups".
