### ISSUE TITLE
feature suggestion: add DNS-over-HTTP support

### ISSUE THREAD

**Issue by fantuz** [DNSCrypt/dnscrypt-proxy#269]
Recently discussed at Hackathon 101 in London this past weekend, having library support for such wannabe-standard is desired.

https://tools.ietf.org/html/draft-ietf-doh-dns-over-https-04

As status draft, specifications (all the verbal process of specifiyng details) are being refined and re-defined in a work-in-progerss fashion.

I am not part of IETF but as independent I developed a similar protocol, back in time, on my own. This is why I participated to the event, and will keep listening and developing with high focus.

So @jedisct1  why don't you give a read to draft, and also check the github https://github.com/dohwg/draft-ietf-doh-dns-over-https for corresponding evolving document ?

Having more implementors is surely a good support for interoperability testing, your library should have a look into this draft protocol, supporting the ingestion/output of DNS messages over HTTP, with one (or more) specific MIME types to be (read the draft, it will be clearer).
The response format of input/output is easy to understand, if you talk DNS (the hex dump of response packet corresponds to the print() output format required, for example)

thanks for your interest in doh ! Let me know if I can help.

Warm regards,
Max

**Comment by jedisct1** [comment]
dnscrypt-proxy2 has been supporting DoH since the very first release, and is probably the most widely deployed client today.

And [stamps](https://github.com/jedisct1/dnscrypt-proxy/wiki/stamps) are a convenient way to encode DoH URLs, but also certificate hashes, and IP addresses for the bootstrap process. dnscrypt-proxy supports all of these.

There's also a server implementation: https://github.com/jedisct1/rust-doh

**Comment by jedisct1** [comment]
And a couple servers on [that list](https://dnscrypt.info/public-servers) use DoH, but people don't really care (and don't have to) about the protocol as long as "it works".

dnscrypt-proxy still provides a filter to use only DoH or only DNSCrypt servers when server names are not explicitly provided (= use all servers from all feeds, with a preference for the fastest ones. The protocol is irrelevant).
