### ISSUE TITLE
DNS also listens to ipv6 despite listen_addresses is being set to ['0.0.0.0:53'] in config

### ISSUE THREAD

**Issue by korn3r** [DNSCrypt/dnscrypt-proxy#2699]
## Output of the following commands:

./dnscrypt-proxy -version
`2.1.5`

./dnscrypt-proxy -check
```
[2024-09-18 02:44:40] [NOTICE] dnscrypt-proxy 2.1.5
[2024-09-18 02:44:40] [NOTICE] Source [public-resolvers] loaded
[2024-09-18 02:44:40] [NOTICE] Source [relays] loaded
[2024-09-18 02:44:40] [NOTICE] Configuration successfully checked
```

./dnscrypt-proxy -resolve example.com
```
Resolving [example.com] using 127.0.0.1 port 53

Resolver      : 74.125.74.153

Canonical name: example.com.

IPv4 addresses: 93.184.215.14
IPv6 addresses: 2606:2800:21f:cb07:6820:80da:af6b:8b2c

Name servers  : a.iana-servers.net., b.iana-servers.net.
DNSSEC signed : yes
Mail servers  : 1 mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : -
TXT records   : v=spf1 -all, wgyf8z8cgvm2qmxpnbnldrcltvk4xqfn

```

- [x] Initially raised as discussion #...
**THE ISSUE**
```
netstat -tulpn | grep :53
tcp6       0      0 :::53                   :::*                    LISTEN      2174/dnscrypt-proxy 
udp6       0      0 :::53                   :::*                                2174/dnscrypt-proxy 
```

**meanwhile config**
```
cat dnscrypt-proxy.toml | grep ^listen_address
listen_addresses = ['0.0.0.0:53']
```

## *What* is affected by this bug?
well... it doesnt listen on ipv4

## *When* does this occur?
when i do ./dnscrypt-proxy -service start

## *Where* does it happen?
on my Rocky 9.4 virtual server

## *How* do we replicate the issue?
1. install system
2. install dnscrypt-proxy (i used pre-compiled binary)
3. run dnscrypt-proxy

## Expected behavior (i.e. solution)
```
## To listen to all IPv4 addresses, use `listen_addresses = ['0.0.0.0:53']`
## To listen to all IPv4+IPv6 addresses, use `listen_addresses = ['[::]:53']`
```
according to quoted part of comments from example configuration 'listen_addresses = ['0.0.0.0:53']' should make app listen only on ipv4. and it wouldnt be an issue if it still would listen on both (for me at least), but it does listen only on ipv6.
and yes, i did notice "using 127.0.0.1 port 53" in -resolve output, yet netstat doesnt show ipv4 53 as listening.
and no, selinux is not enabled (yet, just for testing purposes)

## Other Comments
its not an issue for me to set specific address to listen, but its funny to see how it listens only on ipv6 and not on ipv4 while according to settings it supposed to be exactly the opposite.

```
cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

**Comment by lifenjoiner** [comment]
Thanks for your feedback!
Already had been fixed by https://github.com/DNSCrypt/dnscrypt-proxy/commit/ac5087315c9c48eb1d113b42c69fa14e451a9a1c.
