### ISSUE TITLE
How is this different from Simple DNSCrypt?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [DNSCrypt/dnscrypt-proxy#270]
I'm still [reading the wiki](https://github.com/jedisct1/dnscrypt-proxy/wiki/installation) but I just don't understand the differences? How does dnscrypt-proxy differ from [Simple DNSCrypt](https://www.simplednscrypt.org/)?

Is Simple DNSCrypt using dnscrypt-proxy and just adding a GUI in front of it?

**Comment by jedisct1** [comment]
Simple DNSCrypt is using dnscrypt-proxy under the hood :)

So they obviously support the same protocols, and have the same features.
