### ISSUE TITLE
Enable forwading rules cause loop problem on Android

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#271]
So i install the dnscrypt-proxy  magisk module [](https://github.com/bluemeda/dnscrypt-proxy-magisk) created   by  @bluemeda
It runs flawlessly, untill i enable the forwading rules file, the symptoms are:

- dnscrypt log filled with the same line: wanning ! too many connections blahblahh..

- upload speed is almost same as download speed

- very low actually internet speed, like i am using a 56k modem 

Like you said there must be something cause a loop, here is my geuss: i dont know how dnscrypt-proxy handles the forwading rules , but if the way it handle them is by sending the dns query back to the Android system, it will cause a loop.
Because during the boot state, the dnscrypt-proxy  magisk module will execute a shell script contains this command:(dnscrypt is set to listening 127.0.0.1:5354 by defualt in this magisk module)
`````
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:5354
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5354
`````
i dont know much about iptables but thoes command will redirect the dns query package to the dnscrypt-proxy right? If my guess was right, when i open a website which is in the forwading rules file ,the dns query package will goes like : web brower → Android → dnscrypt-proxy →Android →dnscrypt-proxy→Android........ and goes forever...

**Comment by bluemeda** [comment]
currently I have deleted `iptables -t nat -A INPUT....` line because it was invalid rules.

**Comment by ghost** [comment]
@bluemeda just flashed your latest magisk module, but the problem still exist...

**Comment by porsche613** [comment]
The iptables rules redirects all traffics using port 53, it would cause a loop when you use a normal DNS server in the forwarding rules. I use a DNS server with non-53 port in the forwarding rules, like OpenDNS port 443, problem solved temporary XD.

It's very careful and cautious that using iptables, with my opinion, I suggest to modify the system DNS settings, I have used an app call Override DNS, it can change the system DNS settings (root permission needed).
