### ISSUE TITLE
[Request] Separate Stable Process For Updates

### ISSUE THREAD

**Issue by zero77** [DNSCrypt/dnscrypt-proxy#272]
Can you please add a separate process that automatically checks for and installs updates. 

I think it’s important to have stable and automated updates early on in development.

Because, if any vulnerabilities or bugs were to be discovered later on then it would not be as big of an issue to fix.

As opposed to having manual updates which would result in lots of users who still have old vulnerable or unstable versions because, they forgot to check for updates, I can give many examples of this happening.

Thanks

**Comment by jedisct1** [comment]
That would be redundant and incompatible with package managers already available for your operating system.

This kind of this is better managed by choco, homebrew, apt, pacman, etc. We should rather help dnscrypt-proxy2 get into these package repositories if it is not available already :)
