### ISSUE TITLE
Note ip:port in resolvers file

### ISSUE THREAD

**Issue by NgoHuy** [DNSCrypt/dnscrypt-proxy#273]
Hi @jedisct1 
In some cases, I need allow the firewall to specific ip:port.
Can you provide ip:port in public-resolvers.md ?

Best regards,

**Comment by jedisct1** [comment]
Hi!

Maybe you can add this information to the output of `dnscrypt-proxy -list -json`? And once you have done this, maybe even add this to the online list (for larger screen sizes)?

For DoH, IP addresses are optional so maybe you want to display the host name instead (+ still the bootstrap IP addresses if any)?

**Comment by NgoHuy** [comment]
the output looks like this
```
 {
  "name": "yandex",
  "proto": "DNSCrypt",
  "ipv6": false,
  "ports": [
   15353
  ],
  "dnssec": false,
  "nolog": false,
  "nofilter": true,
  "description": "Yandex public DNS server (anycast)"
 }
```
It contains port not ip, bro

**Comment by jedisct1** [comment]
Yes. It doesn't have host names either. So, maybe you can you add this?

**Comment by NgoHuy** [comment]
Yes, I can add it manually. But I think we can support it by parsering sdns again.

**Comment by jedisct1** [comment]
Thanks! Looking forward to your pull request!

**Comment by jedisct1** [comment]
Done in e09f0875c1c052fb57f00f16886a7f77d36a0f0b

Not sure that this is worth adding to the online list, but this can still be useful if someone wants to display servers on a map.
