### ISSUE TITLE
DNSCrypt local address not listening on upd4

### ISSUE THREAD

**Issue by JayBrown** [DNSCrypt/dnscrypt-proxy#276]
I'm always getting the fatal error `listen udp 127.0.0.54:53 bind: permission denied`. I assume that DNSCrypt is then using TCP only. However, I have set `force_tcp = false` in the TOML, so I'm thinking about opening port 53 for udp.

Anyone know how this works? The `bind` program is not part of macOS anymore, but you can install it with homebrew, and then you'll have a `named.conf` in /etc, symlinked from `/usr/local/etc/named.conf`. Not sure if this is the right way, but if it _is_, how do I go about it precisely? 

Is it enough to add `inet 127.0.0.54 port 53 allow {any;}` to `named.conf`?

**Comment by jedisct1** [comment]
`permission denied` means that you are trying to listen to a port `< 1024` (which is totally expected for DNS) but didn't start the server with admin privileges.

Type `sudo dnscrypt-proxy` instead of `dnscrypt-proxy`.

**Comment by JayBrown** [comment]
That would be weird, because `dnscrypt-proxy` is always launched at login by root using the homebrew service (or manually with `sudo`). Maybe it's a Homebrew thing again?

**Comment by jedisct1** [comment]
Maybe Homebrew's launchd file switches to a different user.

**Comment by JayBrown** [comment]
No, I think you're right after all. I was running the command `dnscrypt-proxy -config dnscrypt-proxy.toml`, with the dnscrypt daemon/service already enabled as root. That's when I got the error. When adding `sudo`, the error is gone. So it was a sudo thing after all.

The issue in general might remain, though, because `netstat` is not showing dnscrypt listening on udp4, only on tcp4.

```
netstat -an | grep LISTEN | grep 127
tcp4       0      0  127.0.0.54.53          *.*                    LISTEN
tcp4       0      0  127.0.0.1.60964        *.*                    LISTEN
tcp4       0      0  127.0.0.1.6263         *.*                    LISTEN
tcp4       0      0  127.0.0.1.6258         *.*                    LISTEN

**Comment by JayBrown** [comment]
Grep only for the DNSCrypt address:

```
netstat -an | grep 127\.0\.0\.54
tcp4       0      0  127.0.0.54.53          *.*                    LISTEN
udp4       0      0  127.0.0.54.53          *.*
udp4       0      0  127.0.0.54.4500        *.*
udp4       0      0  127.0.0.54.500         *.*
```

**Comment by jedisct1** [comment]
There are way too many ports here, I'm not sure I follow which one is supposed to be used by the proxy. What does the `listen_addresses` line look like?

**Comment by jedisct1** [comment]
If you are referring to the word `LISTEN` not being displayed here:

```
udp4       0      0  127.0.0.54.53          *.*
udp4       0      0  127.0.0.54.4500        *.*
udp4       0      0  127.0.0.54.500         *.*
```

This is expected since UDP is a connection-less protocol. The "LISTEN" state doesn't exist.

**Comment by JayBrown** [comment]
OK. Your last comment explains it. Thank you.
