### ISSUE TITLE
dnscrypt-server (docker) suddenly stops working until restarted

### ISSUE THREAD

**Issue by chaosbunker** [DNSCrypt/dnscrypt-proxy#277]
I find that at some point my dnscrypt-server stops resolving and i need to restart the docker container, then all works fine again.

i searched the logs today and found this:

```
[9551] 08 Mar 14:17:07.862 [warning] [udp_request.c:302] Short query received
[32385] 15 Mar 16:55:35.113 [warning] [tcp_request.c:141] Short query received
[32385] 15 Mar 16:55:35.306 [warning] [tcp_request.c:141] Short query received
[32385] 15 Mar 16:56:34.076 [warning] [tcp_request.c:141] Short query received
```

not sure if this is related to the issue, but all i could find.

Possible that this was around the time the dnscrypt-server stopped working for me (i use a vpn most of the time so i did not care to restart it until today)

**Comment by jedisct1** [comment]
This is not the right repository for this (maybe use https://github.com/cofyc/dnscrypt-wrapper/issues instead).

These warnings are harmless, and just means that non-dnscrypt queries have been received.

Try running a shell in the container (`docker exec`) and check whether unbound is still resolving or not (I think it should listen to port 553).

You can also restart individual services to see which one was stuck.

**Comment by chaosbunker** [comment]
thanks for pointing at the repository. checked https://github.com/jedisct1/dnscrypt-server-docker but there was no option to open an issue. I will do it as suggested, next time when it happens.
