### ISSUE TITLE
where to find the server_name list file?

### ISSUE THREAD

**Issue by jcx70100** [DNSCrypt/dnscrypt-proxy#279]
I installed dnscrypt-proxy, but didn't see any file with `server_name` listed in it, so would you please tell me where to find the `server_name` list file, the only server_name i know is `google`, but it doesn't work well in my location.
thanks.

**Comment by bitbeans** [comment]
https://github.com/jedisct1/dnscrypt-proxy/wiki/DNS-server-sources

**Comment by jedisct1** [comment]
You can see the list of resolvers in the `public-resolvers.md` file here: https://dnscrypt.info/public-servers

Or using the command `dnscrypt-proxy -list-all`

The `server_name` property itself is in the configuration file, `dnscrypt-proxy.toml`, which should be in the archive you extracted, in the same folder as the dnscrypt-proxy command if you downloaded it from here.

**Comment by jcx70100** [comment]
Thanks so much, it works. ^_^
@jedisct1 @bitbeans
