### ISSUE TITLE
Dnscrypt-proxy v2.0.8 install failure

### ISSUE THREAD

**Issue by jdferron** [DNSCrypt/dnscrypt-proxy#281]
When trying to install the dnscrypt-proxy as a service on Linux Mint 18.3, I receive the following error:

$ sudo ./dnscrypt-proxy --service install
@@@�����dd: not found ELF�0@�@8@
./dnscrypt-proxy: 2: ./dnscrypt-proxy: 3: not found
./dnscrypt-proxy: 3: ./dnscrypt-proxy: Syntax error: ")" unexpected

**Comment by jedisct1** [comment]
Looks like you didn’t download the right file for your operating system/CPU type.

**Comment by jdferron** [comment]
Well I feel like an idiot!  Thanks!

**Comment by jdferron** [comment]
Next error: 
$ sudo ./dnscrypt-proxy --service install
[2018-03-29 07:58:38] [NOTICE] Source [public-resolvers.md] loaded
[2018-03-29 07:58:38] [NOTICE] dnscrypt-proxy 2.0.8
[2018-03-29 07:58:39] [FATAL] Failed to install DNSCrypt client proxy: "systemctl" failed: exit status

**Comment by jedisct1** [comment]
Start with `sudo ./dnscrypt-proxy` only to see if you get any errors.

**Comment by jdferron** [comment]
No errors from what I can see.

**Comment by ibksturm** [comment]
whats with the command 

`service dnscrypt-proxy status`

oder

`tail -f /var/log/syslog | grep proxy`
