### ISSUE TITLE
[Q]: Missing comment signs # in the 'public-resolvers.md' ?

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#282]
There are lot of non-commented ` # ` text strings in the `public-resolvers.md`
Is it normal for this file? I'm guessing only `sdns://.....` lines are code-relative?

Just found this strange...

**Comment by jedisct1** [comment]
`#` and `##` indicate titles and subtitles (this is the Markdown format). These are not comments :)

Everything is free form. Each resolver just need a title with its name. `sdns://` patterns are extracted from the text no matter where they are.
