### ISSUE TITLE
Provide way to reload blacklist without restarting the proxy

### ISSUE THREAD

**Issue by B00ze64** [DNSCrypt/dnscrypt-proxy#287]
Right now have to restart the proxy to reload the blacklist. Since I like to update the blacklist frequently (especially for malware block rules) I leave myself with no DNS resolution for some time (10 seconds? maybe a bit more?) a few times a day, while the proxy restarts. Would prefer if the proxy had a way to reload the blacklist (and probably flush cache) without leaving me with no DNS resolution.

PS: I'm on Windows so I am assuming that specifying dnscrypt-proxy.exe -service restart means that Windows is asked to restart the service, which takes time. If -service restart doesn't actually stop the service but instead simply reloads the toml file and re-runs configuration then maybe it's the best we can do. I dunno, tell me if my request makes any sense at all lol.

Thank you.

**Comment by B00ze64** [comment]
Hey Frank,

I played with the BAT files on Windows, removed all the @ you had everywhere and used ECHO OFF instead, and other tweaks like this (e.g. Echo "" actually prints the quotes, you need to use Echo. to print a blank line). Anyway, I'm not sure the improvements are big enough to warrant my copying the repository so I can do a pull request; let me know.

ANYWAY, this made me test Stop/Start/Restart a lot and I over-estimated the time it takes to restart the proxy. When I restart it from the Services console it takes about 2 seconds. So I'm not sure it's really necessary to add a method to reload without restarting the service. Up to you.

Thank you.
Best Regards,

**Comment by jedisct1** [comment]
2.0.9b1 should be way faster to load blacklists, so this should be even less of an issue now.
