### ISSUE TITLE
Sandbox .service by default?

### ISSUE THREAD

**Issue by Utini2000** [DNSCrypt/dnscrypt-proxy#289]
Hey there,
from the old DNSCrypt version I remember that the .service could be sanboxed by editing the .service file similiar to this:

> [Service]
CapabilityBoundingSet=CAP_IPC_LOCK CAP_SETGID CAP_SETUID
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
PrivateTmp=true
PrivateDevices=true
MemoryDenyWriteExecute=true
NoNewPrivileges=true
RestrictRealtime=true
RestrictAddressFamilies=AF_INET AF_INET6
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @ipc @module @mount @obsolete @raw-io

Maybe you could add a similiar approach out of the box?

**Comment by ghost** [comment]
Some of those are already [done](https://github.com/jedisct1/dnscrypt-proxy/blob/master/systemd/dnscrypt-proxy.service#L9). Keep in mind that while using `DynamicUser=true` dnscrypt-proxy runs as completely unprivileged user disconnected from rest of the system so any further improvements are marginal. Anyway if they are tested across ditributions can be added as well.

Being more specific:
`CapabilityBoundingSet=CAP_IPC_LOCK CAP_SETGID CAP_SETUID` **Not implemented**
`ProtectSystem=strict` [Done (DynamicUser=true)](https://github.com/jedisct1/dnscrypt-proxy/blob/master/systemd/dnscrypt-proxy.service#L19)
`ProtectHome=true` [Done](https://github.com/jedisct1/dnscrypt-proxy/blob/master/systemd/dnscrypt-proxy.service#L12)
`ProtectKernelTunables=true` **Not implemented**
`ProtectKernelModules=true` [Done (DynamicUser=true)](https://github.com/jedisct1/dnscrypt-proxy/blob/master/systemd/dnscrypt-proxy.service#L19)
`ProtectControlGroups=true` [Done](https://github.com/jedisct1/dnscrypt-proxy/blob/master/systemd/dnscrypt-proxy.service#L13)
`PrivateTmp=true` [Done (DynamicUser=true)](https://github.com/jedisct1/dnscrypt-proxy/blob/master/systemd/dnscrypt-proxy.service#L19)
`PrivateDevices=true` **Not implemented**
`MemoryDenyWriteExecute=true` **Not implemented**
`NoNewPrivileges=true` **Not implemented**
`RestrictRealtime=true` **Not implemented**
`RestrictAddressFamilies=AF_INET AF_INET6` **Not implemented**
`SystemCallArchitectures=native` **Not implemented**
`SystemCallFilter=~@Clock @cpu-emulation @debug @keyring @ipc @module @mount @obsolete @raw-io` **Not implemented**

**Comment by jedisct1** [comment]
Recommendation for systemd moved here: https://github.com/jedisct1/dnscrypt-proxy/wiki/systemd
