### ISSUE TITLE
[Suggestion] Include "/go-systemd/activation" in vendor

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#29]
> systemd_linux.go:6:2: cannot find package "github.com/coreos/go-systemd/activation" in any of: /tmp/yaourt-tmp-****/aur-dnscrypt-proxy-go-git/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/vendor/github.com/coreos/go-systemd/activation (vendor tree)

I did it in my repo, but not sure how to do pull requests, also my repo is a mess.

**Comment by ghost** [comment]
Sorry I just noticed you did it 10 minutes ago. My bad.

**Comment by jedisct1** [comment]
Yes, it was already done, but I forgot to commit it :)
