### ISSUE TITLE
Update Question/Issue

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [DNSCrypt/dnscrypt-proxy#291]
I'm running MacOS and want to understand how to correctly update an existing installation of the program.  When a new version is available, can I simply overwrite the executable in my directory and reboot my computer, or do I need to use Terminal to stop, uninstall the previous version, install the new version, and restart the service?  I've been overwriting the executable each time but I don't know how to verify that the service is the latest version.  Also, please let me know if there's a better way or different medium to ask questions.

**Comment by jedisct1** [comment]
Hi!

Yes, that's all you have to do. Just replace the executable with the new version.

Or use [Homebrew](https://brew.sh/).

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Awesome thank you for the quick response and for developing this amazing software!

**Comment by jedisct1** [comment]
Thank you!
