### ISSUE TITLE
Running dnscrypt-proxy2 together with unbound on FreeBSD

### ISSUE THREAD

**Issue by ctsrc** [DNSCrypt/dnscrypt-proxy#292]
I've been trying to configure dnscrypt-proxy2 to work together with unbound on FreeBSD as suggested in the post-install message of the dnscrypt-proxy2 port but can't get it to work. I have submitted a bug report to FreeBSD because I believe the post-install message is not sufficiently detailed.

However, while probably technically a FreeBSD ports tree bug IMO, I wanted to submit a reference to said bug report here in case someone can help me out, given that it relates to dnscrypt-proxy2 and there might be more people watching these GitHub issues that are familiar with dnscrypt-proxy2.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227129

**Comment by jedisct1** [comment]
What upstream resolver are you using? Did you change anything to the default dnscrypt-proxy configuration?

Depending on its configuration, Unbound may refuse to respond if the server you chose doesn't support DNSSEC.

**Comment by ctsrc** [comment]
I am using unmodified config for dnscrypt-proxy2. DNSSEC was the reason that Unbound did not respond. Someone responded to the FreeBSD Problem Report I filed with a suggestion for a edit to the pkg-message in FreeBSD ports collection which explains this in a good way:

> If you are using local_unbound, DNSSEC is enabled by default and you should comment "auto-trust-anchor-file ..." line or change dnscrypt-proxy to use servers with DNSSEC support only.

With that I am now closing this upstream issue. Hopefully FreeBSD ports will make that change. Otherwise there is at least a way for people to find out about this now that these upstream and downstream issue reports exists.

**Comment by jedisct1** [comment]
Thanks for the follow up!

Change `require_dnssec = false` to `require_dnssec = true` if you want dnscrypt-proxy to only use servers with DNSSEC support.
