### ISSUE TITLE
Whitelist would be welcomed

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#293]
I know this has been discussed but I'm unable to find the threads.

I use the the [mybase.txt](https://download.dnscrypt.info/blacklists/domains/mybase.txt) blacklist which I update once a day.

I was unable to run video from [ARTE Live](https://www.arte.tv/guide/fr/direct) and the culprit was a filter included in mybase.txt : **ssl.p.jwpcdn.com**

Of course I've removed it manually and ARTE's live streaming is now flawless.
Tomorrow I'll update again _**mybase.txt**_ and unless **_ssl.p.jwpcdn.com_** is removed meanwhile, I'll have to remember to delete its entry again from the list.

I know, @jedisct1 mentioned the availability of a _python_ script to get these whitelist entries removed, but for those as myself who are not techies and use _dnscrypt-proxy for Windows_, _python_ is another universe.

This is why I assume the risk of bothering, when I'm aware that so much is already provided here, by putting again on the table the pertinence of a _dnscrypt-proxy built-in whitelist_ feature accessible as easily as the _blacklists_.

Many thanks.

**Comment by Biggizen** [comment]
Such a whitelist option is by far my most wanted feature! In my opinion, nothing would enhance this otherwise practical program more!

Thanks to anyone who is able and willing to implement this!

**Comment by ghost** [comment]
Just to be clear, when I mentioned above the availability of a _python_ script and the fact I was a Windows' user of dnscrypt-proxy, I didn't mean that python was unavailable for Windows, of course it is. I only meant that, IMO, Windows users were, generally speaking, maybe less inclined to using script tools than Linuxians. I'd add that I hope so, otherwise I'd be a sadder even exception :=)
