### ISSUE TITLE
Backup resolver usage for a PC with 24/7 uptime?

### ISSUE THREAD

**Issue by Utini2000** [DNSCrypt/dnscrypt-proxy#294]
Hey there,  
as far as I understand DNSCrypt (on Linux) will check several resolver and will pick the fastest one from the resolvers that are actually online.
But what happens when it picked a resolver, keeps using it for 2 weeks and then the resolver goes offline?

Will DNSCrypt notice it and re-scan for a new fast & online resolver?

**Comment by jedisct1** [comment]
If a server constantly times out, it's not the fastest any more :)

The speed of the servers is constantly updated, not just at startup time.

**Comment by Utini2000** [comment]
@jedisct1 oh okay. So I guess when I run "systemctl status dnscrypt-proxy.service" I should see when it made the last "scan"? So if I let my pc run for two weeks and check the systemctl status, then it should show me a recent scan to re-adjust automatically for the fastest resolver?

And in case that resolver goes offline, dnscrypt will notice and immediately switch to a new resolvers?

**Comment by jedisct1** [comment]
I don't know much about systemd, so I don't know what this command does.

You can see when the certificates are being refreshed (and this is also something you can tune) in the logs. This is also when a new full latency benchmark is made.

But latency measurements are adjusted after every query.
