### ISSUE TITLE
Linux: how to start the proxy after the network is up?

### ISSUE THREAD

**Issue by Utini2000** [DNSCrypt/dnscrypt-proxy#295]
Hey again,
I noticed that DNSCrypt starts scanning/testing/rating the resolvers before my laptop is actually connected to the network. This means that the first 3-5 tested servers will always be "timed out".  

This only happens when I wake up my laptop from suspend/sleep mode.

Archlinux, connecting to WiFi 5GHz.
Which .logs can I provide for helping?

**Comment by jedisct1** [comment]
That's more of an issue with your startup scripts, or on Arch Linux, the systemd configuration.
The proxy should be started after the network.

**Comment by Utini2000** [comment]
@jedisct1 we use the same .service file that you provide:
https://github.com/jedisct1/dnscrypt-proxy/blob/master/systemd/dnscrypt-proxy.service

It contains:

> After=network.target
Before=nss-lookup.target

**Comment by jedisct1** [comment]
A quick Google search seems to suggest `network-online.target` instead of `network.target`.

**Comment by Utini2000** [comment]
Will u change the original .service to network-online.target then? I believe this is a systemd wide problem?
