### ISSUE TITLE
TLS 1.3 Support?

### ISSUE THREAD

**Issue by virtuallynathan** [DNSCrypt/dnscrypt-proxy#298]
CloudFlare's DoH implementation seems to support TLS 1.3, this could improve performance if used.

**Comment by jedisct1** [comment]
It will as soon as [this issue](https://github.com/golang/go/issues/9671) is closed.

**Comment by jedisct1** [comment]
Also, connections are reused, so TLS 1.3's 0RTT wouldn't really improve performance.
