### ISSUE TITLE
How to use it on FreeBSD?

### ISSUE THREAD

**Issue by Drugoy** [DNSCrypt/dnscrypt-proxy#299]
No man entry.
No info in this repo.
No info on port's page.
`dnscrypt-proxy` returns `[FATAL] open dnscrypt-proxy.toml: no such file or directory`. I found this <a href="https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml">dnscrypt-proxy.toml</a>, but what is the path I should save it to?
It also contains `listen_addresses = ['127.0.0.1:53', '[::1]:53']` yet at the same time the port's pkg-message says:
```
By default, the dnscrypt-proxy2 port will listen on (tcp/udp) port 5353
as the _dnscrypt-proxy user.
It's possible to change back to port 53, but not recommended.
```
So why use 53 in example config if you don't recommend it at the same time?

`service dnscrypt-proxy start` tells me to add `dnscrypt_proxy_enable="YES"` to `/etc/rc.conf`, after doing so it just starts silently with a listener on `127.0.0.1:5353`.
What server did it use?
How to make the system now use that server for DNS queries?
Do I need to use **named**/**unbound** in conjunction with **dnscrypt-proxy**?

**Comment by jedisct1** [comment]
The FreeBSD port was not made by and is not maintained by dnscrypt-proxy authors.

Since the instructions are very specific to this operating system, you'd better ask on a FreeBSD mailing list, or ask the maintainer directly.
