### ISSUE TITLE
Feature request: DoH: configurable client side idle timeout

### ISSUE THREAD

**Issue by phemmer** [DNSCrypt/dnscrypt-proxy#300]
Right now the client side http keep-alive timeout is hard coded to 5 seconds:
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/xtransport.go#L40

It would be nice if we could configure this to a larger value. Establishing https connections is very computationally expensive, so every time a DNS query is made after dnscrypt-proxy kills the connection , it takes an excessively long time.
In my setup I'm running dnscrypt-proxy on a consumer grade off-the-shelf router. Every time dnscrypt-proxy has to establish a new https connection, it takes about 1.8 seconds. However once the connection is established, further queries take less than 20ms.

**Comment by jedisct1** [comment]
Sure!

Done.
