### ISSUE TITLE
Linux instructions unclear

### ISSUE THREAD

**Issue by guido4000** [DNSCrypt/dnscrypt-proxy#302]
In step2 it says that systemd-resolve needs to be deactivated:

```
You may also see the port being served by systemd-resolved.
That one cannot be uninstalled, but can be disabled with the following command:
...
```

So, it seems the actual command is missing.

**Comment by jedisct1** [comment]
Because I was still writing this page, and I had no idea what the command was. So I had to install a Linux server with this in order to find out.

The magic command has been added since :)

**Comment by guido4000** [comment]
Great
