### ISSUE TITLE
Wildcard support for cloaking rules

### ISSUE THREAD

**Issue by sphr2k** [DNSCrypt/dnscrypt-proxy#306]
It would be great if you could add wildcard support for cloaking rules.

Great work by the way!

**Comment by jedisct1** [comment]
Unfortunately, I'm currently busy filling the Wiki with documentation. And there's still quite a lot to document for new users, including what cloaking rules are.

And I can't do that and write code at the same time :/

**Comment by sphr2k** [comment]
Hi jedisct1,

thanks for you reply. I din't mean to push, just thought it might be a good idea to have this in the issue tracker as an anhancement idea once you get to it.

Cheers,
Jan
