### ISSUE TITLE
Does a Brew Update restart the dnscrypt-proxy service on the Mac?

### ISSUE THREAD

**Issue by rr0ss0rr** [DNSCrypt/dnscrypt-proxy#307]
I have a brew update scripted to run nightly, Not sure if brew will do the restart automatically or if I need to code  the restart.

Thanks

**Comment by jedisct1** [comment]
I think you need to restart the service. Which is not a bad idea, if only if there are breaking changes in the configuration.

**Comment by publicarray** [comment]
`sudo brew services restart dnscrypt-proxy` is the command that will do that for you.
