### ISSUE TITLE
size is too big to run it on openwrt router

### ISSUE THREAD

**Issue by w01230** [DNSCrypt/dnscrypt-proxy#309]
Is that possible to reduce the size,? it's too big to put it into openwrt router.

**Comment by jedisct1** [comment]
Yep: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

**Comment by w01230** [comment]
it seems ishould use upx.

**Comment by jedisct1** [comment]
Yes!

And adding the option `-lzma` usually gives even better compression.

**Comment by w01230** [comment]
OK.Thanks.
