### ISSUE TITLE
Forward Configuration - Use of DNSCrypt or DoH

### ISSUE THREAD

**Issue by VindicatorDS** [DNSCrypt/dnscrypt-proxy#311]
I might be missing something, but is it possible to use the forward plugin with DNSCrypt or DoH protocols? dnscrypt-proxy seems to always resort to normal DNS over UDP for these entries.

I've dnscrypt-proxy.toml configured with cloudflare and google DNS in server_names. It works as expected and dnscrypt-proxy uses DoH for both servers. Cloudflare is the DNS with the lowest initial latency (few ms vs google's few hundred ms...) and I'm using the default load-balacing algorithm.

However, since cloudflare doesn't forward edns subnet information, I'm being redirected to less optimal CDNs in certain edge cases. Hence my desire to create forward entries for specific domains (e.g., akamai.net, akadns.net, playstation.net, edgesuite.net) to force dnscrypt-proxy to use another DNS server, but keeping DNSCrypt or DoH as the protocols used. Ideally it would be configured like the server line in the toml file.

Is it already possible and I'm missing something?

**Comment by jedisct1** [comment]
Not supporting edns-clientsubnet is actually a feature. This extension was poorly designed, and doesn't really help with performance nowadays, especially with modern CDNs and dense anycast networks such as Cloudflare.

But what you can do is run two instances of the proxy, with the second one using Google as an upstream server, and the first one forwarding specific domains to the first one.

This will work fine; the second one just has to listen to a different port.

**Comment by VindicatorDS** [comment]
Thanks for the quick reply, although it would be a nice-to-have for dnscrypt-proxy to support DNSCrypt or DoH protocols with forwarding domains, regardless of edns-clientsubnet. I'll see if I can contribute to the project with this. Got to learn Go first...

Anyway, it's interesting what you propose because it's similar to the workaround I was using (was using dnsmasq to distribute queries to two dnscrypt-proxy instances).

What you refer about anycast is true. But in my situation, I only get good performance with a pair of specific akamai subnets that I only get with google (and other edns-clientsubnet enabled resolvers). Else, I'm always redirected to non-optimal servers (both akamai and cloudflare CDN's IPs). This is specially noticeable with playstation\xbox content, where I switch from a few Mbps to the maximum bandwidth I'm paying my ISP for. Probably because there isn't any cloudflare CDN for this content near me (hence anycast doesn't give me any benefit for now) and probably akamai hasn't anycast properly configured... 

Anyway, I'm diverging. The workaround works, thanks.
