### ISSUE TITLE
Need help reviewing a blacklist

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#313]
Hi everyone,

I'm working on a parental control system for dnscrypt-proxy, and I would really need some help to clean the training set.

No programming knowledge required.

It's about reviewing a blacklist of about 35k domains to remove obvious false positives. Browsing the websites is not required, just remove the obvious false positives based on the domain name.

Could anybody possibly help?

**Comment by jedisct1** [comment]
Of course, this is never going to happen.

**Comment by B00ze64** [comment]
I'm sorry, I came back here twice, read the request, and thought: How the hell am I going to spot false positives? Sure, if I see google.com then I'll get it, but I don't know that many websites. I could spot anything with the word sex in it [EDIT: Oops, actually those are good positives lol], but you can catch those yourself with a simple search. I'm not sure we can help (and 35K is quite a lot to go through as well lol).

**Comment by fantuz** [comment]
maybe run the list against a DNS BL (there are mny online, SPFBL too) ..
and again, domain blacklisting is just "complementar" to IP blacklisting.
hard task to maintain such lists within a swoftware project.

**Comment by jedisct1** [comment]
Wrote a blog post about what I am building and why I needed this: https://00f.net/2018/04/05/building-a-parental-control-system/
