### ISSUE TITLE
High DNS lookup latency for DoH queries on Raspi 3

### ISSUE THREAD

**Issue by ginkel** [DNSCrypt/dnscrypt-proxy#315]
I recently set up dnscrypt-proxy v2.0.8 on a Raspberry Pi 3 for use with Cloudflare DoH. With v2.0.8 I have been seeing a consistent DNS lookup latency of ~ 300 ms for requests that are not yet cached by dnscrypt-proxy. Regular DNS lookups (UDP, port 53) to Cloudflare take around 20 ms.

This has been getting somewhat better after deploying a current version built based on master w/ keepalive support, but I am still seeing regular latency spikes for uncached requests.

Is the TLS handshake / crypto that expensive on a Raspi?

Is there a way to make dnscrypt-proxy use cheaper ciphers, such as ChaCha20 (AFAICS supported by Cloudflare)?

If you need further details, please let me know.

**Comment by jedisct1** [comment]
Hi!

ChaCha20 should be supported, but the chosen cipher suite follows the server's preference list.

Cloudflare puts ChaCha20 first on mobile devices only. In your case, they have no way to know that what is connecting is a Raspberry Pi.

The key exchange and protocol negotiation is likely to be what introduces so much latency, not so much the encryption. So I don't think ChaCha20 vs AES is relevant.

What you can do is increase the `keepalive` parameter, so that once a connection has been established, it gets reused for a longer period of time.

**Comment by ginkel** [comment]
Thanks for your reply!

I'll give increasing the keepalive a try, although I already set it to 60 s with mixed results. As I see periodic load spikes from the dnscrypt-proxy process, I think that compute-intensive operations such as crypto could be involved. I'll give it a try.

Do you know how CF detects mobile devices and which keepalive values should be acceptable (i.e., not cause the connection to be terminated prematurely due to CF timing out)?

**Comment by jedisct1** [comment]
They probably detect it with the `User-Agent`, which is something you can change (currently, I think this is just `dnscrypt-proxy`).

As to the timeouts, I don't know but feel free to experiment and report your findings :)

**Comment by jedisct1** [comment]
Also, unless you really want to use Cloudflare, the DNSCrypt protocol is always faster than DoH.

**Comment by ginkel** [comment]
I performed some benchmarks w/ `openssl -speed`. ChaCha20 is roughly twice as fast as AES256 on a Raspi 3:

```
$ time openssl speed -evp aes-256-cbc -elapsed
You have chosen to measure elapsed time instead of user CPU time.
Doing aes-256-cbc for 3s on 16 size blocks: 4701719 aes-256-cbc's in 3.00s
Doing aes-256-cbc for 3s on 64 size blocks: 1531002 aes-256-cbc's in 3.00s
Doing aes-256-cbc for 3s on 256 size blocks: 414574 aes-256-cbc's in 3.00s
Doing aes-256-cbc for 3s on 1024 size blocks: 106065 aes-256-cbc's in 3.00s
Doing aes-256-cbc for 3s on 8192 size blocks: 13315 aes-256-cbc's in 3.00s
Doing aes-256-cbc for 3s on 16384 size blocks: 6674 aes-256-cbc's in 3.00s
OpenSSL 1.1.0f  25 May 2017
built on: reproducible build, date unspecified
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/arm-linux-gnueabihf/engines-1.1\"" 
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256-cbc      25075.83k    32661.38k    35376.98k    36203.52k    36358.83k    36448.94k
openssl speed -evp aes-256-cbc -elapsed  17.97s user 0.01s system 99% cpu 18.050 total
```

```
$ time openssl speed -evp chacha20-poly1305 -elapsed
You have chosen to measure elapsed time instead of user CPU time.
Doing chacha20-poly1305 for 3s on 16 size blocks: 5731452 chacha20-poly1305's in 3.00s
Doing chacha20-poly1305 for 3s on 64 size blocks: 3020200 chacha20-poly1305's in 3.00s
Doing chacha20-poly1305 for 3s on 256 size blocks: 909781 chacha20-poly1305's in 3.00s
Doing chacha20-poly1305 for 3s on 1024 size blocks: 241420 chacha20-poly1305's in 3.00s
Doing chacha20-poly1305 for 3s on 8192 size blocks: 30629 chacha20-poly1305's in 3.00s
Doing chacha20-poly1305 for 3s on 16384 size blocks: 15297 chacha20-poly1305's in 3.00s
OpenSSL 1.1.0f  25 May 2017
built on: reproducible build, date unspecified
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/arm-linux-gnueabihf/engines-1.1\"" 
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
chacha20-poly1305    30567.74k    64430.93k    77634.65k    82404.69k    83637.59k    83542.02k
openssl speed -evp chacha20-poly1305 -elapsed  17.97s user 0.00s system 99% cpu 18.015 total
```

Regarding cipher selection, I guess it can't be the User-Agent header, which is sent through the TLS tunnel well after the ciphersuite has been negotiated during the handshake. Instead, I think that the order of cipher suites presented by the client during the ClientHello handshake phase influences whether ChaCha20 is chosen over AES. Is there a way to influence the ciphersuite order in the client code?

OTOH I also see repeated calls to `clock_gettime` when attaching `strace` to the dnscrypt-proxy process (cf. #310 -- maybe these are related):

```
[pid  9001] clock_gettime(CLOCK_REALTIME, {tv_sec=1522955108, tv_nsec=108379336}) = 0
[pid  9001] clock_gettime(CLOCK_MONOTONIC, {tv_sec=1071248, tv_nsec=712058686}) = 0
[pid  9001] clock_gettime(CLOCK_MONOTONIC, {tv_sec=1071248, tv_nsec=712138634}) = 0
[pid  9001] read(9, 0x12b19c00, 1024)   = -1 EAGAIN (Resource temporarily unavailable)
[pid  9001] clock_gettime(CLOCK_REALTIME, {tv_sec=1522955108, tv_nsec=108755741}) = 0
[pid  9001] clock_gettime(CLOCK_MONOTONIC, {tv_sec=1071248, tv_nsec=712429258}) = 0
[pid  9001] clock_gettime(CLOCK_REALTIME, {tv_sec=1522955108, tv_nsec=109016209}) = 0
[pid  9001] clock_gettime(CLOCK_MONOTONIC, {tv_sec=1071248, tv_nsec=712688893}) = 0
[pid  9001] clock_gettime(CLOCK_REALTIME, {tv_sec=1522955108, tv_nsec=109197980}) = 0
[pid  9001] clock_gettime(CLOCK_MONOTONIC, {tv_sec=1071248, tv_nsec=712869622}) = 0
[pid  9001] clock_gettime(CLOCK_REALTIME, {tv_sec=1522955108, tv_nsec=109378552}) = 0
[pid  9001] clock_gettime(CLOCK_MONOTONIC, {tv_sec=1071248, tv_nsec=713048892}) = 0
```

P.S.: If possible, I'd like to stick with CF due to their reliability compared with smaller providers

**Comment by jedisct1** [comment]
Yes, I think the ciphersuite used by the client can used, and preferred over the server's choice.

See what we have here in the `Config` structure: https://golang.org/pkg/crypto/tls/#Config

So this is something we could add to the configuration file.

Want to give it a spin?

**Comment by jedisct1** [comment]
Try 2.0.9b1 with the recommended value for the TLS cipher suite. It may help a lot on ARM devices.
