### ISSUE TITLE
Block IPV6 for certain names

### ISSUE THREAD

**Issue by nobody99999** [DNSCrypt/dnscrypt-proxy#316]
Would be nice to combine the block ipv6 and block name plugin to block AAAA replies for certain names. Usage for: Netflix on an ipv6 tunnel, for those of us who don't have native IPV6 ISP's.  Avoid running a separate process just to filter out AAAA for a few domains.

**Comment by jedisct1** [comment]
That's a very niche use case, and having such a level of flexibility would make the configuration very complicated.

For something that can apparently already be done today with two processes.

So let's keep things simple for most people :)
