### ISSUE TITLE
Add -v flag for compatibility with Adblock

### ISSUE THREAD

**Issue by starcms** [DNSCrypt/dnscrypt-proxy#317]
Hello!  Great work on dnscrypt-proxy verison 2.0!  Just one minor thing.

Alot of us use this on our routers in OpenWRT/LEDE in combination with Adblock.  One of the checks that Adblock does to make sure the dns-resolver you select is running is by running name_of_dns_resolver -v.  However, I noticed that in version 2.0, there is only a -version flag, not a -v one.  Could you please add?  Much thanks!!!

**Comment by starcms** [comment]
Sorry, not needed, my mistake.

**Comment by jedisct1** [comment]
Hahah, just as I added it :)

**Comment by jedisct1** [comment]
Well, I'm gonna revert the change, then. No worries :)
