### ISSUE TITLE
dnscrypt-proxy Installation failed: bash: /opt/dnscrypt-proxy/dnscrypt-proxy: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by drew1kun** [DNSCrypt/dnscrypt-proxy#320]
Good day!

Installing dnscrypt-proxy-linux_arm64-2.0.8.tar.gz on raspberrypi 3 (pihole).

```
$ uname -a
Linux raspberry.localdomain 4.14.31-v7+ #1104 SMP Thu Mar 29 16:52:18 BST 2018 armv7l GNU/Linux
```

Installation fails with the following error:

```
$ /opt/dnscrypt-proxy/dnscrypt-proxy -service install
bash: /opt/dnscrypt-proxy/dnscrypt-proxy: cannot execute binary file: Exec format error$
```

Any ideas what could be wrong?
Thank you.

**Comment by jedisct1** [comment]
Good day :)

You probably didn't download the right package for your OS.

Even though the Pi3 has an arm64 CPU, I think Pi-Hole is still based on a 32 bit version of Debian, so you should download the regular arm version of dnscrypt-proxy as well.

**Comment by drew1kun** [comment]
You are right! Thank you!
