### ISSUE TITLE
dnscrypt-proxy failed to load cache

### ISSUE THREAD

**Issue by tedel** [DNSCrypt/dnscrypt-proxy#327]
Hello,

I installed dnscrypt-proxy in a computer using Linux and systemd. The first run failed because it couldn't download the lists of sources. I modified my _resolv.conf_ file so it would take my ISP's DNS servers, and then I ran _dnscrypt-proxy -check_. It downloaded the lists of servers successfully, so I started the service, modified my _resolv.conf_ file so it would stop taking my ISP's DNS servers and only listened to dnscrypt-proxy, and everything worked as intended.

After a couple of days, I got the same error message, and I didn't have Internet. So I did the same thing: modified _resolv.conf_, then ran _dnscrypt-proxy -check_, and then modified _resolv.conf_ file after the lists of resolvers updated.

I am writing to ask whether it is possible to order _dnscrypt-proxy_ to check the cached resolvers files first, connect, and try to update them _after_ the connection has succeeded to any of the servers in the previous lists. Doing the previously described editions may be annoying if I had to do them in an ongoing basis.

Thanks. =)

**Comment by jedisct1** [comment]
Hi tedel@,

You shouldn't have to change `resolv.conf`.

If Quad9 is blocked on your network, change `fallback_resolver` in the configuration file instead. Change it to your ISP's IP address. And maybe set `ignore_system_dns = true`.

**Comment by tedel** [comment]
Hello,

Ok, I tested, but I am afraid that if I don't edit `resolv.conf`, my Internet connection skips DNScrypt and uses only my ISP DNS servers. This is what I would like to avoid.

So I am trying chainging the `fallback_resolver` setting as you suggested. I'll be back here as soon as I have news about that.
