### ISSUE TITLE
[QUESTION] Latest 2.09b1 > DoH: Disable TLS session tickets

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#328]
Testing latest dnscrypt-proxy 2.09b1 : flawless
RAM with a big blacklist is fantastically reduced!
Whitelist feature is applaused!

Question about a new setting for TLS 'session  tickets':

```
## DoH: Disable TLS session tickets
## increases privacy but also latency - Bump keepalive up to compensate.
# tls_disable_session_tickets = false
```

I'm setting `tls_disable_session_tickets` to `true`,
Here on Firefox 59 I already have:
// disable SSL session tracking -- aka session ticket
user_pref("security.ssl.disable_session_identifiers", true); // (hidden pref)

My question is about _Bump keepalive up to compensate_
This refers to `keepalive` : default = 10, **would bumping to 30 be adequate, more, less?**

Thanks

**Comment by jedisct1** [comment]
If you bump it to 30, after 30 seconds of inactivity, a new query will be a bit slower, and then it's gonna be fast again until nothing happens for 30 seconds.

So, it really depends on your connection latency, and on your DNS traffic. If the value is too high, it may take longer to recover if your IP address changes or if your connection is not stable.

**Comment by ghost** [comment]
OK, but if I leave `keepalive = 10` with `tls_disable_session_tickets = true` the new query occurs sooner, hence increasing it as mentioned in the config file delays the new query. In fact the only con with a higher value is that the IP address would have changed meanwhile. So it's a balance as I understand it. That's why I was wondering on a suggested value for bumping this keepalive, and I understand as well that "_it really depends on your connection latency, and on your DNS traffic_" Probability delta between 10 and 30 seconds of increased risk of changed IP seems low, but I'm no expert. I'll stick on 30.

**Comment by jedisct1** [comment]
As a server operator I would say stick to 10 because it means less connections to the server doing nothing. But for Cloudflare it doesn't matter much.

**Comment by ghost** [comment]
OK. I wouldn't even have thought about modifying the default `keepalive` value hadn't it been for the "_Bump keepalive up to compensate_." proposition in the config file. But OK, I'll revert `keepalive` back to `10` (default).
