### ISSUE TITLE
[QUESTION] Latest 2.09b1 > difference between TTL for cached entries and keepalive

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#329]
Sorry, me again. 2.09b1 introduces new settings so I'm trying to figure them out.

I don't understand the difference between:
```
## Minimum TTL for cached entries
cache_min_ttl = 600
## Maximum TTL for cached entries
cache_max_ttl = 86400
```
and
```
## Keepalive for HTTP (HTTPS, HTTP/2) queries, in seconds
keepalive = 10
```
Cached entries does concern the resolved DNS queries, doesn't it? keepalive as well, no?
I'm missing something here, thanks again!

**Comment by jedisct1** [comment]
Keepalive is the connections, Cache is how long the result is stored in memory.
This will eventually be in the documentation.

**Comment by ghost** [comment]
Acknowledged, thanks again.
