### ISSUE TITLE
[windows 64] dnscrypt-proxy -version returns wrong version

### ISSUE THREAD

**Issue by elmakong** [DNSCrypt/dnscrypt-proxy#33]
i tried to use the command `dnscrypt-proxy.exe -version` on binary version beta 9 and beta 8, while currently running beta 8, it only return the current exe version. not the currently running (as service) one.

> D:\Program Files\dnscrypt-proxy-win64-2.0.0beta8\win64>dnscrypt-proxy.exe -version
2.0.0beta8

> D:\Program Files\dnscrypt-proxy-win64-2.0.0beta9\win64>dnscrypt-proxy.exe -version
2.0.0beta9

**Comment by jedisct1** [comment]
You can see the version of the running on in the log files.

**Comment by elmakong** [comment]
i disabled logging..haha.. if possible, can you fix the -version to show running service version. and if possible, add alias `-V`
