### ISSUE TITLE
[Feature Request] Operational Metrics

### ISSUE THREAD

**Issue by JasonSwindle** [DNSCrypt/dnscrypt-proxy#337]
Howdy,

I am really loving DNSCrypt-Proxy 2, but it is a bit of a blackbox when it monitoring it.  I would love to see metrics outputs from the application to I can better understand things like:

- Cache hit / miss
- Memory usage
- Number of queries handled
- etc
- heartbeats

This would allow my to graph these data-points in Netdata / prometheus and then take action if some metric is out of line.

Right now, it seems like I would need to process the queries.log file, which will get really costly memory and cpu wise. 

Thanks,
Jason

**Comment by jedisct1** [comment]
Adding all these features would add quite a lot of bloat for something virtually no one is going to use.

So I'm not sure that this is something that should go mainline (I'd like to eventually *reduce* the executable file size and memory usage rather than make it grow to support nice features).

But I'm sure that people who need that kind of enterprise-like feature have the ability to write the actual code for it. So I'm not going to do it for them, sorry.

**Comment by JasonSwindle** [comment]
Metrics would also allow projects like Pi-Hole[1] to graph actions going on, maybe to a deeper level or allow monitoring tools like Netdata to report back.  It will also help in Github issues, like for example unbound has metrics like:

```
thread0.num.queries=15278
thread0.num.cachehits=12479
thread0.num.cachemiss=2799
thread0.num.prefetch=331
thread0.num.recursivereplies=2443
thread0.requestlist.avg=11.6428
thread0.requestlist.max=72
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=72
thread0.requestlist.current.user=70
thread0.recursion.time.avg=9.599264
thread0.recursion.time.median=2.41553
total.num.queries=15278
total.num.cachehits=12479
total.num.cachemiss=2799
total.num.prefetch=331
total.num.recursivereplies=2443
total.requestlist.avg=11.6428
total.requestlist.max=72
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=72
total.requestlist.current.user=70
total.recursion.time.avg=9.599264
total.recursion.time.median=2.41553
time.now=1522699377.776428
time.up=17958.972226
time.elapsed=17958.972226
```
 
Overall, I love you work and the software you have made, so I will have to trust in your judgement on this.

[1] https://i2.wp.com/pi-hole.net/wp-content/uploads/2018/04/Screenshot-2018-04-01-14.39.10.png
