### ISSUE TITLE
Unable [to] use source - Invalid signature?

### ISSUE THREAD

**Issue by B00ze64** [DNSCrypt/dnscrypt-proxy#342]
Salut Frank.

I got this the other day on Windows power-up:

```
[2018-04-08 00:06:53] [INFO] Loading source information from URL [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md]
[2018-04-08 00:06:53] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [download.dnscrypt.info] using fallback resolver [9.9.9.9:53]
[2018-04-08 00:06:54] [CRITICAL] Unable use source [public-resolvers]: [Invalid signature]
[2018-04-08 00:06:54] [FATAL] No servers configured
```

Not sure where it got this invalid signature error from, corrupted download? It loaded fine 10 minutes later (time it took me to discover I had no DNS.) Wondering if some kind of retry setting should be added to DNSCrypt-Proxy. Or maybe I should just specify the same source twice? I don't know how often this will happen, wondering if I should start thinking about mitigating this.

Thanks.

**Comment by norrkin** [comment]
Try deleting public-resolvers.md & public-resolvers.md.minisig and restart dnscrypt.

**Comment by jedisct1** [comment]
Looks like a corrupted downloaded downloaded indeed. Maybe you downloaded it right while I was upgrading nginx?

Anyway, it shows that signatures are useful :)

At startup time, there are no retries (maybe this should be added) but once the server is running, there are periodic background retries.

**Comment by jedisct1** [comment]
Changing the cipher suite to something incompatible with what the web server serving the lists supports, can also prevent the files from being properly downloaded.

2.0.9 final improves this, not only by switching to the default cipher suites if something goes wrong, but also by explaining what to change in the configuration file when this happens.

**Comment by B00ze64** [comment]
Good afternoon.

Since no list is a fatal error, could you retry? Or alternatively, what happens if I specify the source twice in the configuration file; is that OK to do? Will that try the same source twice?

Thanks.

**Comment by jedisct1** [comment]
Specifying the same source twice *might* work, but you need to use different names.

**Comment by B00ze64** [comment]
Yeah, it works (you anticipated this obviously.) Loading the same list twice does not make the proxy end-up with double-entries in the final list of servers. I have commented it out for now; if this happens again then I will use a double-list. Thanks!
