### ISSUE TITLE
Invalid issue

### ISSUE THREAD

**Issue by DRSDavidSoft** [DNSCrypt/dnscrypt-proxy#344]
Invalid issue

**Comment by jedisct1** [comment]
Hi,

This is the wrong project :) Unfortunately I can't help you with SimpleDNSCrypt, but you should ask here: https://github.com/bitbeans/SimpleDnsCrypt

**Comment by DRSDavidSoft** [comment]
@jedisct1 Sorry, I seem to have created the issue in the base project instead of Client app.
Thanks for the great work :)
