### ISSUE TITLE
feature req: store the cache to disk?

### ISSUE THREAD

**Issue by Fiyorin** [DNSCrypt/dnscrypt-proxy#346]
thanks for dnscrypt-proxy

i got a random idea: it would be nice if you'd store the cache to disk, so you don't loose it when restarting. i restart quite often, trying out new versions of the program.

question on the config: what is the meaning of this setting?
cache_size = 256
is it bytes, number of entries? i set mine to 262144, trying to cache as much as possible.

**Comment by jedisct1** [comment]
The answer is in the documentation https://github.com/jedisct1/dnscrypt-proxy/wiki/Caching#dns-cache :)

I'm not planning to implement a disk-based cache, but it this is something you want to do, I'd be glad to merge it :)
