### ISSUE TITLE
Hope to support yum installation

### ISSUE THREAD

**Issue by LisonFan** [DNSCrypt/dnscrypt-proxy#349]
:)

**Comment by jedisct1** [comment]
This is probably something you should ask on Fedora forums, or directly to the maintainers of the previous version. I doubt they will see your message here :)

**Comment by LisonFan** [comment]
@jedisct1 ok, thank for you reply

**Comment by jedisct1** [comment]
A Google search points to this: https://copr.fedorainfracloud.org/coprs/eclipseo/dnscrypt-proxy/

**Comment by LisonFan** [comment]
@jedisct1 ok, thank you very much

**Comment by LisonFan** [comment]
@jedisct1 Does not support CentOS :(
