### ISSUE TITLE
Many "upstream connectivity issues" messages in the log file

### ISSUE THREAD

**Issue by mibere** [DNSCrypt/dnscrypt-proxy#351]
System: Debian Stretch, dnscrypt-proxy 2.0.9 (Release) 

With `log_level = 1` in _dnscrypt-proxy.toml_ there are a lot of 

> [2018-04-12 08:24:59] [INFO] Server [XXXXX] returned error code [2] -- It might be experiencing upstream connectivity issues
> [2018-04-12 08:25:05] [INFO] Server [XXXXX] returned error code [2] -- It might be experiencing upstream connectivity issues
> [2018-04-12 08:26:01] [INFO] Server [XXXXX] returned error code [2] -- It might be experiencing upstream connectivity issues
> [2018-04-12 08:26:07] [INFO] Server [XXXXX] returned error code [2] -- It might be experiencing upstream connectivity issues
> [2018-04-12 08:26:12] [INFO] Server [XXXXX] returned error code [2] -- It might be experiencing upstream connectivity issues

messages in the log file, for several different servers.
It also happens with a server running a current, original and unmodified [dnscrypt-server-docker](https://github.com/jedisct1/dnscrypt-server-docker) (_jedisct1/dnscrypt-server_).

**Comment by jedisct1** [comment]
If you are using Cloudflare, it means that you sent too many queries, and have been rate limited.

**Comment by jedisct1** [comment]
Oh sorry, didn't notice that it was using a DNSCrypt server docker image.

`error code [2]` means that the server returned a `SERVFAIL` response. This comes from Unbound, and can happen if queries were sent to zones with invalid DNSSEC signatures, or if there were too many timeouts for Unbound to resolve some queries.

**Comment by mibere** [comment]
Yes, it happens with Cloudflare too. But I don't use Cloudflare, I'm using my own server (a current, original and unmodified jedisct1/dnscrypt-server). And as written, there are other servers too.
For me it looks like a general problem or issue.

**Comment by jedisct1** [comment]
Getting responses from misconfigured and slow servers happens all the time. Unless is happens with server you know are perfectly fine, this can be ignored especially since these are temporary errors.

Maybe the severity of this message should be decrased even further to `DEBUG`.

**Comment by mibere** [comment]
I hope and expect ;-) that my environment - server with your Docker image, client with your dnscrypt-proxy -  is working fine.

It was just irritating that the messages have been logged for/with so many servers, not only my and Cloudflare.

So, you say I should ignore it -> `log_level = 2`.

**Comment by jedisct1** [comment]
Yes, it's safe to ignore it. This is logged for diagnostics purposes, but once your proxy is up and running, you should keep `log_level >= 2`.

**Comment by mibere** [comment]
Thanks for the response. I'll close the issue...
