### ISSUE TITLE
Brew Package?

### ISSUE THREAD

**Issue by rr0ss0rr** [DNSCrypt/dnscrypt-proxy#354]
Saw that 2.09 came out but the brew formula hasn't been updated yet for the Mac.  Does anyone know the timeframe when this will happen?

Thanks

**Comment by jdmartin** [comment]
I made a pull request, and it has been merged in homebrew-core.  You should see the result when you brew update. :)

**Comment by publicarray** [comment]
In future I suggest reporting brew formula stuff to https://github.com/Homebrew/homebrew-core. It's also very easy to submit a pull request with a version bump.

**Comment by rr0ss0rr** [comment]
Thanks to all .. Didn't know about homebrew-core .. will take a look

**Comment by rr0ss0rr** [comment]
Sebastian .. I'm kind of new to brew ... Are you saying that anyone can submit a brew bump-formula-pr? Would the changes be just the location of the 2.09 tar file and the chksum?

Thanks

**Comment by publicarray** [comment]
> Are you saying that anyone can submit a brew bump-formula-pr

yes, anyone with a github account 😄
> Would the changes be just the location of the 2.09 tar file and the chksum

With `brew bump-formula-pr` yes, it's that simple.

**Edit:** see @jdmartin PR: https://github.com/Homebrew/homebrew-core/pull/26580

**Comment by jdmartin** [comment]
If it helps, this was the exact command used:

`brew bump-formula-pr --strict dnscrypt-proxy --url='https://github.com/jedisct1/dnscrypt-proxy/archive/2.0.9.tar.gz' --sha256='482e5ded79cd6b0251fb7aa103c6ee929968a8c3f0903f9730e09631e3963918'`

The details came from here: https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md

:)

**Comment by rr0ss0rr** [comment]
Thanks .. I was reading up and looking at the commits ... Any idea how some of the verbage got changed ie "using a random resolver." ?  I don't see how that could have happened with the bump-formula-pr.  Also, my other question was what's the difference between "archive/2.0.9.tar.gz" vs "releases/download/2.0.9/dnscrypt-proxy-macos-2.0.9.tar.gz".  

Thanks again

**Comment by jdmartin** [comment]
The change to the text still somewhat puzzles me, but I'm new to committing to brew with bump-formula-pr.  It was easy enough to revert, but still strange.

For the archive, I just used the archive/2.0.9.tar.gz as the existing formula was pulling the archive version.  I'll let smarter people comment on the meaningful differences. ;)

**Comment by publicarray** [comment]
I think the text issue was because your local copy of homebrew-core was not up-to-date when you ran `bump-formula-pr.` A `git pull` would have avoided it.

`https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.9/dnscrypt-proxy-macos-2.0.9.tar.gz` contains the binary and `https://github.com/jedisct1/dnscrypt-proxy/archive/2.0.9.tar.gz` contains the source code

While I don't mind helping, I personally think that future questions should go to https://discourse.brew.sh

**Comment by jdmartin** [comment]
Oh, of course.  That makes total sense.  

And yes, I agree.  Thanks for your patience with all this. :)

**Comment by rr0ss0rr** [comment]
Thanks again

**Comment by publicarray** [comment]
Thanks for understanding and Welcome to the brew community! 😃
