### ISSUE TITLE
feature suggestion: load balance mode with concurrent recurse (speculative execution)

### ISSUE THREAD

**Issue by ak2k** [DNSCrypt/dnscrypt-proxy#355]
It would be great if a mode existed to attempt to resolve using the two (or N) fastest upstream servers concurrently (and discard the result from the server with the slower reply).

**Comment by jedisct1** [comment]
Server operators would get twice as many queries, pay twice as more, to serve the same number of clients. Not cool.

**Comment by ak2k** [comment]
PowerDNS has this feature.
It's not necessarily the case that DNS hosting services are unpaid. I actually pay for my query volume.
