### ISSUE TITLE
ignore_system_dns = ture, still tries to use system's dns settings (pihole, raspbian stretch)

### ISSUE THREAD

**Issue by drew1kun** [DNSCrypt/dnscrypt-proxy#356]
**/opt/dnscrypt-proxy/dnscrypt-proxy.toml:**
```
fallback_resolver = '9.9.9.9:53'

## Never try to use the system DSN settings; unconditionally use the
## fallback resolver.
ignore_system_dns = ture
```

**/etc/resolv.conf**
```
# Pushed by DHCP server:
nameserver 8.8.8.8
```

**Expected results:**
Pihole uses either dnscrypt-enabled forwarder, matching all `require_*` filters from the remote list, or 9.9.9.9 fallback server.

**Actual results:**
Pihole is using google's dns (system dns):
```
# dnscrypt-proxy -resolve google.com
Resolving [google.com]

Domain exists:  yes, 4 name servers found
Canonical name: google.com.
IP addresses:   216.58.216.142, 2607:f8b0:400a:809::200e
TXT records:    docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e v=spf1 include:_spf.google.com ~all
Resolver IP:    74.125.187.2
```

**Comment by publicarray** [comment]
Sorry, did you mean "true" instead of "ture"?

**Comment by drew1kun** [comment]
Oh sorry, of course! It is just a typo here. the actual config is fine (just double checked it) - no typos there but the system dns is not ignored

**Comment by publicarray** [comment]
Thanks for double checking. Unfortunately I can't help on this one 😞. You have to wait for @jedisct1 to respond.

**Comment by publicarray** [comment]
Actually what does your log-file/stdout say?
Something like this should give you a clue what the preferred server is:
```
[2018-04-15 20:54:18] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 23ms)
[2018-04-15 20:54:18] [NOTICE] dnscrypt-proxy is ready - live servers: 27
```

Have you specified any `server_names` ?

As far as I know the `ignore_system_dns` and `fallback_resolver` are only relevant when first looking up the other name servers (if it needs to) and looking up the `download.dnscrypt.info` domain to download `public-resolvers.md` and the signature file.

**Comment by jedisct1** [comment]
As @publicarray , `ignore_system_dns` and `fallback_resolver` are only used to resolve the IP address of some resolvers (actually, only Google as of today) as well as resolve `donwload.dnscrypt.info` in order to retrieve the initial list of resolvers.

These options do not change anything to your system settings, and have no effect on other software.

**Comment by drew1kun** [comment]
Oh I see. I was just confused, because the comments in config sample says the following:
```
## Never try to use the system DSN settings; unconditionally use the
## fallback resolver.
ignore_system_dns = ture
```

**Comment by JayBrown** [comment]
Related question: in the BitBar plugins dnscrypt-proxy-switcher and DNSCrypt Menu there is a setting "DNSCrypt + Fallback", which means that the plugins write one or more additional resolver IP addresses into Network preferences _in addition_ to the local dnscrypt proxy address, e.g. 

```
127.0.0.1
1.1.1.1
1.0.0.1
9.9.9.9
```

which then all wind up in `/etc/resolv.conf`. Does this mean that for this kind of setting, the TOML needs to read `ignore_system_dns = false`? I guess so, right?

**Comment by jedisct1** [comment]
I'd recommend always leaving `ignore_system_dns` to `false`.
