### ISSUE TITLE
A newbie question. After installing with docker, why can't I dig?

### ISSUE THREAD

**Issue by sgon00** [DNSCrypt/dnscrypt-proxy#358]
Hi, I am a newbie. I followed the wiki instruction and install docker version on my server:

```s
$ docker run --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host \
jedisct1/dnscrypt-server init -N example.com -E 1.2.3.4:443
```

and start the docker container. 

In the client side, first, I make sure I can connect to my server:

```s
$ telnet 1.2.3.4 443
```

It shows I can connect to my server's 443 port successfully and the port is open. 

Then, I tried to use the following to test the dns server is running fine:

```s
$ dig @1.2.3.4 +dnssec google.com

; <<>> DiG 9.12.0 <<>> @1.2.3.4 +dnssec google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

I don't know why I can't dig the dnssec server. Thanks a lot for your help.

**Comment by publicarray** [comment]
Docker is listening on port 443 like you said

So you need to tell dig to use the port:

```sh
$ dig -p443 @1.2.3.4 +dnssec google.com
```
However this still won't work, dig does not support the dnscrypt protocol. So you can only (meaningfully) use the port for things that understand the dnscrypt protocol like dnscrypt-proxy.

**Comment by sgon00** [comment]
@publicarray Thanks a lot for the reply. When I read `Compatible with DNSSEC`, I thought it meant I can use `dig +dnssec` query directly. Actually I tried some public dnscrypt-proxy v1 servers and they all can return the result with `dig +dnssec`. Maybe I am just too new to this tech. OK, I know I have to use some dnscrypt-proxy clients for this server now. Thanks and closing this issue.

**Comment by publicarray** [comment]
@sgon00 No worries, happy to help.
DNSSEC is stands for DNS Security Extension and is part of DNS. Technologies like DNSCrypt, DNS-over-TLS or DNS-over-HTTPS are more like wrappers around the transport of DNS. Kind of what TLS is for HTTP. And if you want to find out more I suggest you checkout the [Wikipedia article on DNSSEC](https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions) or https://dnscrypt.info/faq (Feel free to offer feedback on improving the site or send pull requests)
