### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by dakarf** [DNSCrypt/dnscrypt-proxy#359]
# Error
panic: runtime error: slice bounds out of range

goroutine 254 [running]:
main.ReadPrefixed(0xc4200aa0b0, 0xbeac9e03b0cf4d7c, 0x36b77c1e2f, 0x9761e0, 0x0, 0x0)
        /wrkdirs/usr/ports/dns/dnscrypt-proxy2/work/dnscrypt-proxy-2.0.8/dnscrypt-proxy/common.go:67 +0x304
main.(*Proxy).tcpListener.func1(0x7dfe20, 0xc4200aa0b0, 0xc4200fc598)
        /wrkdirs/usr/ports/dns/dnscrypt-proxy2/work/dnscrypt-proxy-2.0.8/dnscrypt-proxy/proxy.go:175 +0x12d
created by main.(*Proxy).tcpListener
        /wrkdirs/usr/ports/dns/dnscrypt-proxy2/work/dnscrypt-proxy-2.0.8/dnscrypt-proxy/proxy.go:167 +0x95

# Reproduce
`telnet 127.0.0.1 53` and write any ASCII text.

**Comment by publicarray** [comment]
I was unable to reproduce. Can you provide your os and arch? thanks.
![screen shot](https://user-images.githubusercontent.com/5497998/38777886-0ecf816e-40f3-11e8-897e-2d5f9f8642c9.png)

**Comment by dakarf** [comment]
Use Windows' telnet. I get that crash every single time with it.
I also tried UNIX telnet, but it didn't crash.

**Comment by publicarray** [comment]
Thanks I can confirm the crash on Windows 10.
For anyone else debugging this, to install telnet: `dism /online /Enable-Feature /FeatureName:TelnetClient`
