### ISSUE TITLE
dnscrypt-proxy-win32-2.0.0beta10

### ISSUE THREAD

**Issue by ysz223** [DNSCrypt/dnscrypt-proxy#36]
In beta10, change the configuration in `dnscrypt-proxy.toml` to

`server_names = ['cisco']`

and

```
# [servers]
    [servers.'cisco ']
   stamp='sdns://AQMAAAAAAAAAEjIxMi40Ny4yMjguMTM2OjQ0MyDoAbhOpga_sLrAzkNEW7FeumSwL6PEqjGuEGNqB5AyTR8yLmRuc2NyeXB0LWNlcnQuZnIuZG5zY3J5cHQub3Jn'
```

After, still can not use cisco, how can I do? Thank you!

**Comment by HybridSarcasm** [comment]
Don't specify 'cisco' in the [servers] stanza

**Comment by ysz223** [comment]
@SeminolesFan78 

If you do not specify, you will not be able to install the service.

**Comment by HybridSarcasm** [comment]
Works for me. Check out my current config: https://pastebin.com/hmA2p3dM

**Comment by ysz223** [comment]
Supplement:

I try to open `public-resolvers.md`, find `cisco` configuration, the original configuration

`stamp='sdns://AQMAAAAAAAAAEjIxMi40Ny4yMjguMTM2OjQ0MyDoAbhOpga_sLrAzkNEW7FeumSwL6PEqjGuEGNqB5AyTR8yLmRuc2NyeXB0LWNlcnQuZnIuZG5zY3J5cHQub3Jn'`

replaced manually

`stamp='sdns:After//AQAAAAAAAAAAEjIwOC42Ny4yMjAuMjIwOjQ0MyC3NRFAIG8iXT4r2CLX_WkeocM8yNZmjQy-BL-rykP7eRsyLmRuc2NyeXB0LWNlcnQub3BlbmRucy5jb20'`

cisco the normal use. 

However, before Singapore, now it has become Japan.

**Comment by ysz223** [comment]
@SeminolesFan78 

Thank you for your guidance, and now I try to use cisco after adding `server_names = ['cisco']` under `# server_names = ['scaleway-fr']` in `dnscrypt-proxy.toml`.
