### ISSUE TITLE
Cannot access blocked site without https

### ISSUE THREAD

**Issue by haidarvm** [DNSCrypt/dnscrypt-proxy#364]
I have an issue if the site running "http" its not working and redirecting to my ISP warning, but it's working fine on https.

So how to fix it ?

running on ubuntu 16.04 kernel  4.16.2
dnscrypt -version 2.0.9
using browser firefox 59.0.2, Opera 52 , Chrome  65

**Comment by Sak94664** [comment]
contents transferred via http can be easily captured and rewrited.but https don't.

**Comment by publicarray** [comment]
> So how to fix it ?

Don't browse via http and use https ([why?](https://www.youtube.com/watch?v=E_wX40fQwEA)), get a different ISP, use TOR or use a VPN?. There is nothing dnscrypt-proxy can do about this. Like @Sak94664 said http traffic is frequently manipulated by [MiTM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)

**Comment by haidarvm** [comment]
Ok i found the solutions just put some string of the link at the end of url
example : 
http://reddit.com/index.html

**Comment by publicarray** [comment]
Hi. 
I think your ISP is doing a bad job of blocking if it can be so simply bypassed. They should know better. I should mention that if they block sites they are probably doing some kind of data collection/monitoring/tracking too. So I recommend using the solutions I mentioned above.
