### ISSUE TITLE
v2 list sorted by country

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#37]
Thought maybe this could help:

https://raw.githubusercontent.com/mastad0n/dnscrypt_resolvers/master/resolvers/v2/v2.md

No offence if it's not helpful 😄

**Comment by jedisct1** [comment]
Hey, this is great!

And you needed to add comments inside that file, which is interesting. Not something that I had thought about. But it makes sense. Maybe lines starting with `*` should be ignored when displaying a resolver description, then. Unless Markdown has an established syntax for comments, that doesn't clash with lists.

Do you think you will be maintaining these lists?

What could be great is one list per country, and a webpage that summarizes all these lists (mostly: the URL they are available at), as well as your public key.

So, the link to your page will be referenced in the documentation, and people can subscribe to whatever countries they are interested in.

**Comment by ghost** [comment]
Thank you so much @jedisct1 !

I will try to follow your suggestions :-)

I'm not sure how long I can maintain them for, but I can try :)

**Comment by kim0** [comment]
This is awesome! Thanks @mastad0n  .. Looking forward to seeing this merged soon 👍

**Comment by TraderStf** [comment]
May I suggest a strict (and simple) layout, using ISO values.
Validated by a good old very awkward regex test :-)
Something like a good old CSV:
nick,name,provider,country,ip6,anycast,log,censored,eyes,commercial,legal,dnsc,dnsh,....  sdn

eyes:5,7,14
legal:indicator of what the country can do, ask... with or without warrant... you get the idea

**Comment by ghost** [comment]
Thanks guys! I'm just making initial draft here: https://mastad0n.github.io

**Comment by ghost** [comment]
All sorted :) https://github.com/mastad0n/mastad0n.github.io/tree/master/resolvers/v2

Also updated https://mastad0n.github.io

@TraderStf those are good suggestions. Maybe @jedisct1 could give his input on that?

**Comment by ghost** [comment]
@mastad0n You rock! I also second @TraderStf proposal.

**Comment by Marco-vW** [comment]
Thanks for your effort @mastad0n. Quick question: why is Cisco/OpenDNS missing in The Netherlands?

**Comment by ghost** [comment]
@AtAM1 Thank you! And thanks for your input!


Hi @Marco-vW No problem :) Cisco/OpenDNS is anycast. Meaning, the location changes depending on where you connect from it (https://www.opendns.com/data-center-locations/) . It's in the anycast.md:


https://raw.githubusercontent.com/mastad0n/mastad0n.github.io/master/resolvers/v2/anycast.md

**Comment by jedisct1** [comment]
Yandex and Google are anycast, too.

**Comment by TraderStf** [comment]
I have these. Verify, it's a copy paste from my @&#" mess. 😜

```
anycast.censurfridns.dk     91.239.100.100
                            2001:67c:28a4::
ns1.censurfridns.dk         89.233.43.71
                            2002:d596:2a92:1:71:53::

resolver#.dns.watch         84.200.69.80
                            84.200.70.40
resolver#v6.dns.watch       2001:1608:10:25::1c04:b12f
                            2001:1608:10:25::9249:d69b


DNS Service           DNS1                  DNS2               Privacy   Ads   Flush
Google Public DNS    8.8.8.8               8.8.4.4
OpenDNS               208.67.220.220        208.67.222.222
Norton ConnectSafe    198.153.194.50        198.153.192.50
Comodo Secure DNS     8.20.247.20           8.26.56.26
DNS Advantage         156.154.71.1          156.154.70.1
FreeDNS               37.235.1.174          37.235.1.177
GreenTeamDNS          81.218.119.11         209.88.198.133
DNS.WATCH             84.200.69.80          84.200.70.40
Level3 Free DNS       209.244.0.3           209.244.0.4

verisign              64.6.64.6             64.6.65.6          yes       no     yes
                      2620:74:1b::1:1       2620:74:1c::2:2 

```

**Comment by jedisct1** [comment]
Level3 has `4.2.2.2` which is easier to remember, but none of these support dnscrypt or DoH, so they are not very relevant here.

**Comment by ghost** [comment]
Thank you @jedisct1 I've added them! (yandex & google)

**Comment by jedisct1** [comment]
This is fantastic!

In order for these file to be automatically loaded by dnscrypt-proxy, can you add a signature to these files and publish your public key?

Minisign now accepts multiple files to be signed, so you can just use `minisign -Sm *.md` to sign them all at once.

**Comment by ghost** [comment]
Thank you very much @jedisct1 
Yes, I will do minisign on them and publish my public key!

**Comment by thundr** [comment]
@mastad0n Did you ever get around to signing these lists? If you could put your pub key somewhere, that would be great.

**Comment by ghost** [comment]
@thundR Thank you, I haven't forgotten about it but am having some issues with minisign. Will figure it out asap!

**Comment by ghost** [comment]
@jedisct1 @kim0 @TraderStf @AtAM1 @Marco-vW @thundR 

All done and signed with minisign :) :

https://github.com/mastad0n/mastad0n.github.io/tree/master/resolvers/v2

minisign.pub is in there too!

**Comment by jedisct1** [comment]
Great!

Added here: https://github.com/jedisct1/dnscrypt-proxy/wiki/DNS-server-sources

The web page may have a bit too much margin. On my laptop this is how it looks:

![screen shot 2018-02-08 at 8 40 03 am](https://user-images.githubusercontent.com/124872/35960895-c6ea86b2-0cab-11e8-97be-a3737bb4b516.jpg)

It could be useful to have the public key here, too.

And some resolvers seem to be missing: comodo (anycast), doh.crypto.sx (anycast), de.dnsmaschine.net (germany), opennic-luggs (canada), opennic-luggs-ipv6, opennic-onic (usa), opennic-onic-ipv6.

**Comment by ghost** [comment]
Thank you very much @jedisct1  :)

I'm going to fix those errors right now! And add those servers, Sorry about that!

**Comment by jedisct1** [comment]
It looks really great now! Congrats!

**Comment by ghost** [comment]
Thank you very much @jedisct1 !!
