### ISSUE TITLE
Dnscrypt-proxy will not run on Raspian stretch on rpi

### ISSUE THREAD

**Issue by Mrjelly13** [DNSCrypt/dnscrypt-proxy#372]
When attempting to run dnscrypt-proxy on a raspberry pi with raspian stretch I just get this error:
`./dnscrypt-proxy: 1: ./dnscrypt-proxy: Syntax error: ")" unexpected`

I've tried on 2.0.8, 2.0.9, and 2.0.10 all with the same problem.. I even completly reinstalled the os to see if that helped.

**Comment by jedisct1** [comment]
The answer is in the [documentation](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux) :)

**Comment by Mrjelly13** [comment]
I swear I tried both arm versions. Thanks though.
