### ISSUE TITLE
Add the Android version into F-Droid

### ISSUE THREAD

**Issue by KOLANICH** [DNSCrypt/dnscrypt-proxy#373]

**Comment by jedisct1** [comment]
_No description provided._

**Comment by iWARR** [comment]
In spite of "no description", the main message is very clear.
I beleive **dnscrypt-proxy** will and must appear as "ready-to-go" App for Android, sooner or later.

A big question is **who may help and provide** creating, regular and stable support for the app.
Then it will appear as ***.apk** on F-Droid. I'm also waiting for this baby born.

**Comment by CHEF-KOCH** [comment]
It would also be wise to introduce it directly into Google Play Store in order to get more attention.
