### ISSUE TITLE
Abandon the current format of the URIs

### ISSUE THREAD

**Issue by KOLANICH** [DNSCrypt/dnscrypt-proxy#376]
The current format of URIs is complete crap.
1 It is not human-editable in the sense I cannot edit it with a text editor.
2 It is not even human-readable!
3 It contains useless metadata like signs if it logs and spies. This should be a part of the certificate, not the URI because it's server's claim, not the claim of the one spreading uris.

The proposed changes:
1 don't base64 human-readable and human-editable strings but base64 binary blobs like crypto keys
2 Don't store lengths of strings, buffers, etc, just use separators encoding each buffer with base64 separately.
3 indicate the type with 2 ascii chars:
```
p<n> - plain dns, version n
c<n> - dnscrypt version n
h<n> - dns over https version n
t<n> - dns over tos version n
```

**Comment by jedisct1** [comment]
Thank you.
