### ISSUE TITLE
allow dnscrypt proxies to be supplied as a fallback_resolver

### ISSUE THREAD

**Issue by KOLANICH** [DNSCrypt/dnscrypt-proxy#378]

**Comment by jedisct1** [comment]
`fallback_resolver` is a fallback resolver. Which means that configured system resolvers are tried first. And the configured system resolvers can be the proxy address itself.

**Comment by KOLANICH** [comment]
System resolver may be censored. So I may be not able to ger the resolvers' addresses. Chicken and egg problem again.
