### ISSUE TITLE
[CTITICAL] Unable use source [public-resolvers] - beta 10

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#38]
After `service-install.bat` :

```
[CTITICAL] Unable use source [public-resolvers]: [Get http://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md.minisig: dial tcp: lookup download.dnscrypt.info: no such host]
[FATAL] No servers configured
```

Using your (new) standard `[sources]` section :
```

[sources]

  [sources.'public-resolvers']
  url = 'http://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = 'public-resolvers.md'
  format = 'v2'
  refresh_delay = 168
  prefix = ''
```

**Comment by jedisct1** [comment]
Means that the server you chose is not in that list.

**Comment by iWARR** [comment]
### chicken-egg problem again?

It works only if I:

1) Download and look into `public-resolvers.md` on **beta 9** first

2) Fill my config with corresponding values for chosen server :

```
[servers]
  [servers.'server-of-my-choice']
  stamp = 'sdns://................'
```

3) Don't comment this lines in your config, as they are really needed to launch new dnscrypt-proxy.

```
# [servers]
#   [servers.'scaleway-fr']
#   stamp = 'sdns://AQMAAAAAAAAAEjIxMi40Ny4yMjguMTM2OjQ0MyDoAbhOpga_sLrAzkNEW7FeumSwL6PEqjGuEGNqB5AyTR8yLmRuc2NyeXB0LWNlcnQuZnIuZG5zY3J5cHQub3Jn'
```

Commenting this will be unclear to use as example.
(If I look at it, I'm imagine this unneeded lines, instead they are MUST).

**Comment by jedisct1** [comment]
You need to have a working DNS configuration before running that software.

**Comment by iWARR** [comment]
**chicken-egg problem**

New user must to know, where get the URL, where to look, what lines put there and there...
(Now product don't work "out of the box", like prevous versions).

**Comment by jedisct1** [comment]
Yes, this will be explained in the documentation. Which I haven't written yet and nobody else offered to write.

**Comment by iWARR** [comment]
> You need to have a working DNS configuration before running that software.

Ah... This because I've just stopped and uninstalled the service before moving to new version?

**Comment by iWARR** [comment]
> nobody else offered to write.

I would like to help you with this. Just say.
My English is terrible, I'm not a programmer. But I'm ready to do something for you.
