### ISSUE TITLE
Stop promoting 9.9.9.9 as the default server.

### ISSUE THREAD

**Issue by KOLANICH** [DNSCrypt/dnscrypt-proxy#380]
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/xtransport.go#L25

**Comment by jedisct1** [comment]
It's a default server. You can change it. We just need something that works for most people, is globally available, and supports DNSSEC. 9.9.9.9 fits the bill.

**Comment by KOLANICH** [comment]
I can change, but by default it is used. It's a political decision to select that company and not another and I personally prefer it not to be made.
