### ISSUE TITLE
Virus windows?

### ISSUE THREAD

**Issue by MBurtsev** [DNSCrypt/dnscrypt-proxy#386]
I have win10
When i started service-install.bat i saw ten console windows per second. open-close, open-close. WTF ?? It looks like a virus.
Why did you do everything so stupidly? Why bother hacking something. After all, you could make a local DNS(with forward traffic to remote DNS). Which I can specify in the interface settings as 127.0.0.1

**Comment by jedisct1** [comment]
Read the documentation. Which intentionally doesn't mention `service-install.bat`.

**Comment by AL3x3y0** [comment]
Got the same problem untill I read wiki. But for what then these .bat files needed, if they won't work?
