### ISSUE TITLE
start/stop script for OpenWRT

### ISSUE THREAD

**Issue by chuacw** [DNSCrypt/dnscrypt-proxy#391]
Hi,

I created a start/stop script for dnscrypt-proxy as well as a working config on my repo at https://github.com/chuacw/DNS-over-HTTPS-for-OpenWRT/ .

Do you want to consider adding this to your repo?

**Comment by jedisct1** [comment]
HI @chuacw ,

This is great!

Maybe the best place to put this would be to add a documentation to the wiki.
A new page that details how to install it on OpenWRT, including the scripts.

**Comment by chuacw** [comment]
Sure, I can help you do that. Do I need credentials to add docs to wiki, or can I do it without any credentials, just using my Github account to add to the wiki?

**Comment by jedisct1** [comment]
You can already edit anything you want :)

**Comment by jedisct1** [comment]
Here's a start: https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-on-OpenWRT :)

Don't forget to add your name to the main page :)

**Comment by chuacw** [comment]
Thanks! Done! I'll close this then.
