### ISSUE TITLE
[Question] keepalive

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#393]
Hi, I noticed that in 2.0.10 there is 30 seconds keepalive in config:
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

But here it's 5:
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/config.go

Why is that?

And here https://github.com/jedisct1/dnscrypt-proxy/issues/328#issuecomment-379544314 you said you will revert keepalive back to 10, and you do it:
https://github.com/jedisct1/dnscrypt-proxy/commit/dee7960be671a8747f17f9eb1af4574bed882b82#diff-f6f04170f3c6b8b556a88fa842de545c
but then you bump it to 30 again:
https://github.com/jedisct1/dnscrypt-proxy/commit/8bebb50d498f7c4dd06bfbfc69e4918354c80578#diff-f6f04170f3c6b8b556a88fa842de545c

So what number is better for keepalive?

**Comment by jedisct1** [comment]
Just use the default.

30 seconds may reduce the latency a little bit over 10 seconds, but will take longer to recover from network failures. 

I bumped the default to 30 seconds to see if people would suddenly complain about slow recovery after network failures. Nobody did. So, we're going to keep that value :)
