### ISSUE TITLE
intalled the latest version of dnscrypt-proxy V2, some issues

### ISSUE THREAD

**Issue by jpgpi250** [DNSCrypt/dnscrypt-proxy#398]
- Whenever I reboot my system (raspberry pi), the following error appears in the dnscrypt-proxy log:
**[ERROR] dial udp 176.56.237.171:443: connect: network is unreachable**

-I'm running dnscrypt-proxy on raspberry pi on address 127.10.10.1, port 5551. In the dnsmasq log, the following error is logged:
**dnsmasq[501]: nameserver 127.10.10.1 refused to do a recursive query**

when the command ./dnscrypt-proxy restart is executed, the following error is displayed:
**[FATAL] listen udp 127.10.10.1:5551: bind: address already in use**

**Comment by mibere** [comment]
Reproducible, especially after a complete system reboot.

dnscrypt-proxy 2.0.10, Raspbian/Debian 9.4

dnscrypt-proxy.log:

> [2018-04-22 11:27:03] [NOTICE] Source [public-resolvers.md] loaded
> [2018-04-22 11:27:03] [NOTICE] dnscrypt-proxy 2.0.10
> [2018-04-22 11:27:03] [NOTICE] Now listening to 127.0.0.1:7053 [UDP]
> [2018-04-22 11:27:03] [NOTICE] Now listening to 127.0.0.1:7053 [TCP]
> [2018-04-22 11:27:03] [NOTICE] Now listening to [::1]:7053 [UDP]
> [2018-04-22 11:27:03] [NOTICE] Now listening to [::1]:7053 [TCP]
> [2018-04-22 11:27:03] [NOTICE] [dnscrypt.me] TIMEOUT
> [2018-04-22 11:27:03] [ERROR] dial udp 94.199.213.171:443: connect: network is unreachable
> [2018-04-22 11:27:03] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
> [2018-04-22 11:27:13] [NOTICE] [dnscrypt.me] OK (crypto v2) - rtt: 32ms
>

**Comment by jedisct1** [comment]
Looks like the server was started before the network was available.

The root cause doesn't seem to be dnscrypt-proxy, but the way it is started.

**Comment by jpgpi250** [comment]
I followed the installation instructions for pihole on the [wiki](https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0), they state:
./dnscrypt-proxy -service install: install dnscrypt-proxy service
./dnscrypt-proxy -service start: start the new service
If there is a better way, I'd really like to know...

**Comment by mibere** [comment]
Yes, it seems the dnscrypt-proxy service depends on other services or functionality...the dnscrypt-proxy service starts too early.

It was installed with

`sudo ./dnscrypt-proxy -service install`

**Comment by poentodewo** [comment]
@jpgpi250 try use `sudo ./dnscrypt-proxy -service install` inside /opt/dnscrypt-proxy/

**Comment by jpgpi250** [comment]
All my install procedures are scripted. I checked, dnscrypt-proxy is installed as indicated:
**sudo ./dnscrypt-proxy -service install**
thus, NOT the problem...

**Comment by jdferron** [comment]
I have noticed this too.  When it happens (either from sleep or after complete boot), I'm forced to restart the service.

I am wondering if there is an enhancement that could be made to check for network connection prior to starting.   If network is not up, to wait and retry up until a given set time period.

**Comment by jedisct1** [comment]
Maybe https://github.com/kardianos/service can be improved to create a better systemd service file for network services, that includes whatever it takes for systemd to check that the network is up before starting the service.

**Comment by jpgpi250** [comment]
Don't shoot me if I'm completely wrong, As a noob, I try...

I found dnscrypt-proxy.service in /etc/systemd/system.
Since this a newly installed system, I assume this is not a leftover and has actually been put there by the dnscrypt-proxy install command.

On the web, I find information, describing a method to force a service to wait for the network, something like:
[Unit]
Wants=network-online.target
After=network.target network-online.target

dhcpcd5.service in the same folder has such an entry. Am I wrong in assuming this may be a way to delay the startup? 

furthermore, I never read an answer here that clarifies the problem regarding the restart:
[FATAL] listen udp 127.10.10.1:5551: bind: address already in use

**Comment by zenofile** [comment]
The supplied dnscrypt-proxy service file since #395 already includes the aforementioned wait targets. But they time out after 90s _and_ require the system's network manager wait service to be active aswell in order to function properly (`systemd-networkd-wait-online.service`, `NetworkManager-wait-online.service`, ..). 

A more robust (and recommended, see [here](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)) approach would be to watch `rtnetlink ` and dynamically react to network changes.

Edit: clarified which commit added this fix.

**Comment by jpgpi250** [comment]
Again ,I may be completely wrong, but...
I've installed from dnscrypt-proxy-linux_arm-2.0.10.tar.gz (on a raspberry pi 3B)
The file I mentioned (/etc/system/system/dnscrypt-proxy.service) does NOT contain the wait targets.
The complete content of the file is:
[Unit]
Description=Encrypted/authenticated DNS proxy
ConditionFileIsExecutable=/opt/dnscrypt-proxy/dnscrypt-proxy

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/opt/dnscrypt-proxy/dnscrypt-proxy

WorkingDirectory=/opt/dnscrypt-proxy

Restart=always
RestartSec=120
EnvironmentFile=-/etc/sysconfig/dnscrypt-proxy

[Install]
WantedBy=multi-user.target

So wat I'm I missing.

**Comment by zenofile** [comment]
It was added a few days ago, #389 #395 - several days after the release of 2.0.10.

**Comment by jpgpi250** [comment]
thank you for the explanation.
Leaves the open question:
**when the command ./dnscrypt-proxy restart is executed, the following error is displayed:
[FATAL] listen udp 127.10.10.1:5551: bind: address already in use**

**Comment by welwood08** [comment]
`./dnscrypt-proxy -service restart`

**Comment by jpgpi250** [comment]
thank you for this (**sudo** /opt/dnscrypt-proxy/dnscrypt-proxy -service restart)

and now for the last error:
-I'm running dnscrypt-proxy on raspberry pi on address 127.10.10.1, port 5551. In the dnsmasq log, the following error is logged:
dnsmasq[501]: nameserver 127.10.10.1 refused to do a recursive query

any idea where this might be coming from?

**Comment by jpgpi250** [comment]
I installed version dnscrypt-proxy 2.0.11 (dnscrypt-proxy-linux_arm-2.0.11.tar.gz), released today (27/04/2018)
The content of the file hasn't changed, the required network test entries aren't there).
What am I doing wrong?

**Comment by mibere** [comment]
@jpgpi250 2.011 does not contain changes/fixes for this, see [changelog](https://github.com/jedisct1/dnscrypt-proxy/releases/tag/2.0.11)

**Comment by jpgpi250** [comment]
Thank you.

Any ideas regarding:
dnsmasq[501]: nameserver 127.10.10.1 refused to do a recursive query

**Comment by welwood08** [comment]
Sounds like dnsmasq is not receiving responses from the service (or lack of service) running on 127.10.10.1 port 53 (the default DNS port when you don't specify any). You mention above you're running dnscrypt-proxy on 127.10.10.1 port 5551, but not what's on port 53...

**Comment by jpgpi250** [comment]
thank you for this;
I forwarded your reply to Simon Kelley, the developer of dnsmasq.
I will reply, as soon as I get an answer.

**Comment by jpgpi250** [comment]
What I was doing:
I had the dnscrypt-proxy setting '**block_ipv6 = true**' in the dnscrypt-proxy configuration file, because I still have a docsis 2 modem (no ipv6 support) and my provider refuses to upgrade it.

restarted dnscrypt-proxy (sudo /opt/dnscrypt-proxy/dnscrypt-proxy -service restart)
restarted dnsmasq (sudo service dnsmasq restart)
made dns requests using 'sudo apt-get update'

I got a:
SECURE validation on raspberrypi.org
BOGUS validation on archive.raspberrypi.org
BOGUS validation on raspbian.raspberrypi.org
and
**dnsmasq[24168]: nameserver 127.10.10.1 refused to do a recursive query**

I than changed, as instructed by Simon (the dnsmasq developer), the dnscrypt-proxy setting back to '**block_ipv6 = false** (default)

now I get:
SECURE validation on raspberrypi.org
SECURE validation on archive.raspberrypi.org
INSECURE validation on raspbian.raspberrypi.org
and
**the dnsmasq error disappeared**

according to Simon (the dnsmasq developer):
'quote'
Looking at your logs, this is responsible for some of the BOGUS validations, if dnscrypt-proxy gives a synthetic reply to a query in a signed domain, that will fail DNSSEC validation, obviously.

If your network doesn't support IPv6, chances are that your applications are still constantly trying to resolve IPv6 addresses, causing unnecessary slowdowns.
This causes the proxy to immediately reply to IPv6 requests, without having to send a useless request to upstream resolvers, and having to wait for a response.
This uses a plugin that requires dnscrypt-proxy to be compiled with the ldns library.
'/quote'

Conclusion:
Despite the fact that the [wiki](https://github.com/jedisct1/dnscrypt-proxy/wiki/Caching) says (section making things go fast) to change the 'block_ipv6 = false', if you only have IPv4 and you're using dnsmasq (and possibly other products), combined with DNSSEC, **don't change the setting** (keep the default = 'block_ipv6 = false')

Maybe the dnscrypt-proxy developer can add this as a comment in the example configuration file, e.g.:
'**don't change this setting if your only have IPv4 and also are using DNSSEC**'.

Thank you all for your patience and effort.

**Comment by mibere** [comment]
Even if closed, still hope there will be an improvement regarding this reproducible issue

> [2018-04-22 11:27:03] [NOTICE] [dnscrypt.me] TIMEOUT
> [2018-04-22 11:27:03] [ERROR] dial udp 94.199.213.171:443: connect: network is unreachable
> [2018-04-22 11:27:03] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable

**Comment by poentodewo** [comment]
yea look like error show after restarting device

> [NOTICE] Now listening to 127.0.0.1:54 [TCP]
[2018-04-28 00:25:29] [NOTICE] [sg-ndlamput] TIMEOUT
[2018-04-28 00:25:29] [ERROR] dial udp 167.99.78.78:443: connect: network is unreachable
[2018-04-28 00:25:29] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
[2018-04-28 00:25:39] [NOTICE] [sg-ndlamput] OK (crypto v2) - rtt: 32ms

**Comment by mibere** [comment]
**Solution**

Raspbian/Debian 9.4

`sudo nano /etc/systemd/system/dnscrypt-proxy.service`

Add the following two lines in section [Unit]

> Wants=network-online.target
> After=network-online.target

After a reboot there is no error in _dnscrypt-proxy.log_ anymore

> [2018-04-27 21:45:10] [NOTICE] Now listening to [::1]:7053 [TCP]
> [2018-04-27 21:45:10] [NOTICE] [dnscrypt.me] OK (crypto v2) - rtt: 33ms
> [2018-04-27 21:45:10] [NOTICE] Server with the lowest initial latency: dnscrypt.me (rtt: 33ms)
> [2018-04-27 21:45:10] [NOTICE] dnscrypt-proxy is ready - live servers: 1

**Comment by poentodewo** [comment]
yes that fix error on startup

**Comment by eli-schwartz** [comment]
Note these lines merely tell the dnscrypt-proxy service to wait for network-online.target, but it is still the responsibility of some network management utility like NetworkManager to register a blocking service that delays network-online.target until some checks for successful connections are made. This usually means enabling some *-wait-online.service, if you've manually configured your connection manager rather than having it preinstalled and preconfigured by your distro.
