### ISSUE TITLE
Network/connectivity death after idle period

### ISSUE THREAD

**Issue by stylemessiah** [DNSCrypt/dnscrypt-proxy#399]
This has me a little stumped

Have 2.0.8 working fine, I'm running it via script in smanager, but after a period of idle, i.e. waking device up after an hour or so, the devices wifi and/or cell icons have crosses on them, only a reboot will bring my connection back

Never experienced a single issue with connectivity without dnscrypt...

Any ideas?

**Comment by jedisct1** [comment]
I have no idea what you are talking about and "Ng smanager" on Google doesn't return anything relevant to computers.

What is it? Is it something on Windows? Android? iPhone maybe?

**Comment by stylemessiah** [comment]
Apologies, autocorrect murdered that sentence...fixed the sentence

**Comment by stylemessiah** [comment]
Apologies, autocorrect murdered that sentence...fixed
