### ISSUE TITLE
Clarify the license of the content in the wiki

### ISSUE THREAD

**Issue by KOLANICH** [DNSCrypt/dnscrypt-proxy#400]

**Comment by Yinchie** [comment]
Stop trolling.

**Comment by KOLANICH** [comment]
I'm serious. I wanna the official statement about if it is the same as the project license or something else. Because wiki is a separate git repo and it doesn't contain license file. I wanna know if it is legal to put pieces of text from wiki into the source code comments.

**Comment by jedisct1** [comment]
Can you give a couple examples of projects having a license on their wiki in order to use a different license than the project itself, along with their motivation and, for github-hosted wikis, the way they enforce this?

**Comment by KOLANICH** [comment]
>Can you give a couple examples of projects having a license on their wiki in order to use a different license than the project itself

I'm not aware of any.

>along with their motivation and, for github-hosted wikis, the way they enforce this?

Usually projects store the official docs not in wiki, but in either separate folder or in a separate repo.

I'm not sure if that needs any special enforcement except puting a license file into the wiki and adding some words about it into project's license file since all the changes in the wiki are revertable.

**Comment by jedisct1** [comment]
Ok, so let's not invent anything here.
