### ISSUE TITLE
non root user DNScrypt-proxy v2?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#402]
Hi!
I can't run DNScrypt-proxy v2 at non root user. In DNScrypt-proxy v1 @ dnscrypt-proxy.service
User=dnscrypt-proxy works great but
how in DNScrypt v2?

Please help!
Thanks!

**Comment by jedisct1** [comment]
Please read the documentation, as well as the ticket that already discussed this to death.

**Comment by ghost** [comment]
Active: failed (Result: exit-code) since Mon 2018-04-23 15:35:32 CEST; 3s ago
  Process: 15691 ExecStart=/usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml (code=exited, status=255)
 Main PID: 15691 (code=exited, status=255)

Apr 23 15:35:32 amd systemd[1]: Started #### DNSCrypt PROXY v2 - CLIENT ####.
Apr 23 15:35:32 amd dnscrypt-proxy[15691]: [2018-04-23 15:35:32] [NOTICE] dnscrypt-proxy 2.0.10
Apr 23 15:35:32 amd dnscrypt-proxy[15691]: [2018-04-23 15:35:32] [FATAL] listen udp 127.0.0.3:41: bind: permission denied
Apr 23 15:35:32 amd systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
Apr 23 15:35:32 amd systemd[1]: dnscrypt-proxy.service: Unit entered failed state.
Apr 23 15:35:32 amd systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
