### ISSUE TITLE
Instant Segfault on OpenBSD

### ISSUE THREAD

**Issue by margaretjoanmiller** [DNSCrypt/dnscrypt-proxy#406]
Upon extracting the binary release for OpenBSD amd64 and running ./dnscrypt-proxy, all I get is a "Segmentation fault (core dumped)." And this core: [dnscrypt-proxy.core](https://u.teknik.io/zGlHs.core).

**Comment by jedisct1** [comment]
If you are running -current, this is due to the introduction of [MAP_STACK](https://undeadly.org/cgi?action=article;sid=20180413065457), that broke *all* go binaries.

This requires recompilation using go from ports, that has the required patches.

**Comment by jedisct1** [comment]
Discussion: https://twitter.com/jedisct1/status/985981108935364608
