### ISSUE TITLE
Feature Request: Blacklist for upstream servers

### ISSUE THREAD

**Issue by kairaven** [DNSCrypt/dnscrypt-proxy#410]
It would be nice to have a blacklist to put names of servers i don't want to use, e. g. if i don't trust Cloudflare, Google or don't want to use them most of the time, because they have the shortest answer times servers regardless of the type of lb method or servers which have a overlength key validity period.

**Comment by jedisct1** [comment]
Just build your own source :)

Or, regarding Google and Cloudflare, you can easily exclude then with `use_doh = false` (or `enable_doh`, I don't remember how it's called).
