### ISSUE TITLE
Directions for verifying release file signatures

### ISSUE THREAD

**Issue by drduh** [DNSCrypt/dnscrypt-proxy#412]
Please write some instructions or examples for verifying the .tar.gz files with Minisign. I did find directions at https://jedisct1.github.io/minisign/ but they're not sufficient. Where is your public key?

**Comment by jedisct1** [comment]
In the documentation?

**Comment by drduh** [comment]
Ah, so it's after Installation. You should probably put it in the [Installation](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation) page right after the download step.

**Comment by drduh** [comment]
I was looking at the [Installation linux](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux) page which didn't mention it, but I see it now on the general Installation page.
