### ISSUE TITLE
RFE: TLD resolver affinity

### ISSUE THREAD

**Issue by kim0** [DNSCrypt/dnscrypt-proxy#415]
Hello folks,

I have the public resolvers configured. And also the opennic resolvers configured. My current problems, is that I cannot open *.bit domains with that configuration.

I do not want to only use opennic servers, bec they're very few and less reliable. And I do not want to only use the public resolvers, bec they do not allow resolving the "special" TLDs resolved by opennic.

Is it possible to configure the proxy, so that certain TLDs (say .bit) goes to the opennic resolvers, while everything else goes to the normal public resolvers?

Thanks

**Comment by jedisct1** [comment]
You can use forwarding for that.

**Comment by kim0** [comment]
Thanks @jedisct1 .. Per my understanding however, forwarding allows (example.com) to be resolved via a certain resolver IP (ex: 8.8.8.8).

Is it possible to allow a full TLD (ex: *.bit *.o) via a "source" .. i.e. all DNS resolvers under the "opennic" config section ? If yes, could you please show a config example. That would be great.

**Comment by jedisct1** [comment]
Just replace`example.com` with `bit` :)

**Comment by kim0** [comment]
Very well, thanks. The syntax could be clearer though (say, *.bit) .. maybe something to consider.

The one unanswered bit though, is it possible to direct those domains to all DNS resolvers under the "opennic" section, instead of choosing a fixed resolver IP ?

**Comment by jedisct1** [comment]
You can always run two instances, the primary one using whatever sources you want, and a secondary one using only OpenNIC sources. And on the primary one, foward `*.bit` to the IP of the secondary.

**Comment by jedisct1** [comment]
8509cc1bd7cadb3766e703df59ef4bce1aa3a065  should clarify this :)

**Comment by kim0** [comment]
Thanks man :) .. While technically this does meet my needs (and I don't wanna be a pain in the arse), but I have to say that running two proxies is not the best user experience. For example, on my OSX homebrew provides scripts to manage the service (starting, stopping ..etc). Running that second instance will be more painful than the first. I'll always be forgetting to run that daemon when my laptop restarts...etc. 

I suggest to leave this bug open as a request for enhancement. Say with the below syntax
bit sources.opennic

meaning *.bit will be resolved from resolvers defined in the opennic section. 

Thanks for your excellent software. This v2 has been rock solid stable for me! Good job

**Comment by jedisct1** [comment]
Implementing this would take way more time than a script to start two instances.

**Comment by kim0** [comment]
Alright, I guess I can live with manually picking an opennic resolver. The below forwarding rules are working well enough for me, with a single proxy instance. Thanks for the help 👍 
```
bit 185.121.177.177,169.239.202.202
o 185.121.177.177,169.239.202.202
oz 185.121.177.177,169.239.202.202
geek 185.121.177.177,169.239.202.202
```
