### ISSUE TITLE
Issue with dnscrypt-proxy with TCP only.

### ISSUE THREAD

**Issue by GanjiKumar** [DNSCrypt/dnscrypt-proxy#417]
I am using dnscrypt-proxy-1.9.4.1 with libsodium-1.0.11.1 from packages-lede-17.01. As and when I start
dnscrypt-proxy, it able to get validation certificates and authentication done as per below log:

```
####################################################################
root@routerB50211:/usr/sbin# Tue Apr 17 13:27:01 2018 [NOTICE] Starting dnscrypt-proxy 1.9.4
Tue Apr 17 13:27:01 2018 [INFO] Generating a new session key pair
Tue Apr 17 13:27:01 2018 [INFO] Done
Tue Apr 17 13:27:01 2018 [INFO] Server certificate with serial #1517943461 received
Tue Apr 17 13:27:01 2018 [INFO] This certificate is valid
Tue Apr 17 13:27:01 2018 [INFO] Chosen certificate #1517943461 is valid from [2018-02-06] to [2019-02-06]
Tue Apr 17 13:27:01 2018 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
Tue Apr 17 13:27:01 2018 [INFO] Server key fingerprint is 240B:11B7:AD02:FAC0:6285:1E88:6EAA:44E7:AE5B:AD2F:921F:9577:514D:E226:D552:6836
Tue Apr 17 13:27:01 2018 [NOTICE] Proxying from 127.0.0.1:40 to 208.67.220.220:443
##########################################################################
```

 I am able to see queries in file:dns-queries.log as per dnscrypt-proxy.conf but no packet getting out of the box towards opendns server. Then I changed configuration to TCP only from default UDP.
Then I see SYN pkt from localhost(WAN IP) to 208.67.220.220:443. and SYN+ACK is being received to the localhost but after receiving the SYN+ACK, the localhost is sending RST to 208.67.220.220:443.

Please help why it is not working UDP and after changing to TCP why RST is being initiated to the server upon receiving SYN+ACK. Is there any problem with my libsodium package? if not what could be the problem.

**Comment by jedisct1** [comment]
```
Tue Apr 17 13:27:01 2018
```

Check your clock, maybe; the date doesn't seem to be right.

Did you try with other servers?

**Comment by GanjiKumar** [comment]
I am getting the same log as and when I am stating dnscrypt-proxy, by mistakenly I have pasted older 

> Did you try with other servers?

I did not try with other servers.

```
It is compiled for ARM 32bit as below:
src/proxy# file dnscrypt-proxy
dnscrypt-proxy: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.16, not stripped
```

**Comment by jedisct1** [comment]
Try other servers? Maybe that one doesn't work well.
