### ISSUE TITLE
Archive dnscrypt-proxy.log

### ISSUE THREAD

**Issue by B00ze64** [DNSCrypt/dnscrypt-proxy#420]
Salut.

I noticed that while query.log gets archived correctly at the size I have specified (into a zip file) the log for the proxy itself does not get archived. Did I mis-configure or is this normal? Can the proxy log be archived too?

Thanks.

**Comment by jedisct1** [comment]
Maybe you can send these logs to syslog (or the Windows logger) instead?

**Comment by B00ze64** [comment]
Hmm, it's an option, but not an attractive one - It is much easier to read the log file in a text editor than it is to read Windows Event Logs (yes, I can use XPath in the Event Log, but I don't need that to read the DNSCrypt-Proxy log.) Why not support Automatic log files rotation for the proxy log?

**Comment by jedisct1** [comment]
The application log uses completely different and generic code which is not part of dnscrypt-proxy. It's only designed to be printed to the standard error output, or sent to a system logger like other applications.

**Comment by B00ze64** [comment]
Ah yes, I see now, it uses your own dlog library.
Alright, I'll just compress it in NTFS and delete it once in a while.
Thanks.

**Comment by jpgpi250** [comment]
On Linux, this can be easily achieved by

Step one: modify '/opt/dnscrypt-proxy/dnscrypt-proxy.toml'

`log_file = '/var/log/dnscrypt-proxy.log'`

Step two; create a file '/etc/logrotate.d/dnscrypt-proxy', containing:

```
/var/log/dnscrypt-proxy.log {
    daily
    rotate 5
    copytruncate
    delaycompress
    compress
    notifempty
    missingok
}
```
