### ISSUE TITLE
PPA doesn't contain package for Ubuntu 16.04

### ISSUE THREAD

**Issue by gislikarl** [DNSCrypt/dnscrypt-proxy#422]
There are only packages for Bionic and Artful, no Xenial package available.

**Comment by jedisct1** [comment]
You should really tell the package maintainer. I don't think he or she is watching issues reported here.

**Comment by Haraade** [comment]
https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-Debian-Ubuntu

**Comment by gislikarl** [comment]
My mistake, assumed you were the package maintainer. And @Haraade the problem is that the ppa doesn't contain version 2.0 for Ubuntu Xenial.
