### ISSUE TITLE
arm vs arm64 for Pi 3B+

### ISSUE THREAD

**Issue by p1r473** [DNSCrypt/dnscrypt-proxy#427]
I am using dnscrypt arm build on my 3B+. I know that the Pixel OS's are 32 bit, but since the 3B+ has a 64 bit cpu, has anyone tried dnscrypt arm64 on the 3B+?

**Comment by jedisct1** [comment]
I use the 64 bit version on a Pi3, but this requires a 64-bit OS such as [Pi64](https://github.com/bamarni/pi64).

And Pi64 doesn't work on the PI3B+ yet (AFAIK).

**Comment by poentodewo** [comment]
is there any difference in performance ?

**Comment by jedisct1** [comment]
It's negligible.
