### ISSUE TITLE
Help wanted: website

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#43]
A dedicated website would be great.

To explain what DNS is and why encrypted/authenticated DNS is not a bad idea.

And to list available specifications, implementations and public servers.

So, if you're familiar with static websites generators such as Gatsby and Nuxt, and if you can do something that looks great and has fascinating content to read, that would be awesome!

**Comment by Tallefer** [comment]
Good idea! But what about using that existing site of yours? 
Also, here is a good concise text to start with, quoted from https://ipleak.net/

> ### What is a "DNS leaks"?
> In this context, with "DNS leak" we mean an unencrypted DNS query sent by your system OUTSIDE the established VPN tunnel.

> ### Why my system suffers DNS leaks?
> In brief: Windows lacks the concept of global DNS. Each network interface can have its own DNS. Under various circumstances, the system process svchost.exe will send out DNS queries without respecting the routing table and the default gateway of the VPN tunnel, causing the leak.

> ### Should I be worried for a DNS leak?
> If you don't want that your ISP, and anybody with the ability to monitor your line, knows the names your system tries to resolve (so the web sites you visit etc.) you must prevent your system to leak DNS. If you feel that you're living in a human rights hostile country, or in any way the above mentioned knowledge may harm you, you should act immediately to stop DNS leaks.

**Comment by Snapy** [comment]
I think you should put back a generic website (Github pages) w/ readme.md content on dnscrypt.org and linking to Wikipedia & other reputable sources for detailed / in depth explanations.

**Comment by jedisct1** [comment]
I don't own dnscrypt[.]org any more. There's [dnscrypt.info](https://dnscrypt.info) but what's currently there is... not great.

**Comment by ghost** [comment]
[off-topic]

**Comment by jedisct1** [comment]
Use v2 now. It does way more than 1.x. Cisco users may want to stick to 1.x. Everybody else should use v2.

**Comment by jedisct1** [comment]
But that thread is about the website. It would be nice to avoid hijacking it with off-topic questions :)

**Comment by publicarray** [comment]
@jedisct1 Can I ask why use js frameworks? Isn't a static site with some css enough? something like jekyll can be used if a static website generator is needed.

PS. Currently the server of dnscrypt.info is sending the `Vary: Accept-Encoding` header twice and sending the `Server` header with the exact version of nginx.

**Comment by jedisct1** [comment]
Hi Sebastian!

It can totally be something like Jekyll. I'd just like to avoid things such as Wordpress, if only for security purposes.

Good catch for the duplicated `Vary` header! Fixed :)

**Comment by publicarray** [comment]
Hello Frank!

Ah thanks, yes that makes sense. If you like I can try and come up with something.

No worries 😄

**Comment by publicarray** [comment]
@jedisct1 I've developed a new site would you mind taking a look? I haven't made the repo public just yet but I'm happy to transfer it to @dnscrypt or to you.

**Comment by jedisct1** [comment]
Thanks to Sebastian, we got a new nice website :)

https://dnscrypt.info

**Comment by jedisct1** [comment]
Source is here if you want to tweak it: https://github.com/DNSCrypt/dnscrypt-website

stamps.dnscrypt.info now redirects there.
