### ISSUE TITLE
false DNSSEC BOGUS errors.

### ISSUE THREAD

**Issue by jpgpi250** [DNSCrypt/dnscrypt-proxy#430]
I'm writing this here, because the wiki also has a section 'How to setup your own DNSCrypt server in less than 10 minutes' and really don't know if this is the image used by 'Martin 'd0wn' Albus', who provides a lot of 'd0wn' dnscrypt servers.

After communicating with the developer of dnsmasq (Simon Kelley), and performing a lot of test, Simon even duplicated my dnsmasq + DNSSEC + dnscrypt-proxy setup, this to determine the cause of **false BOGUS errors**, I have been getting.

His conclusion:
'quote'
The fundamental problem is still the one I showed before: missing RRSIG data in the AUTHORITY section validating NSEC records which prove that a DS record does not exist. The insight is that these are only missing when the answer comes via UDP: they are present when the answer comes via TCP.

Getting the answer via UDP or TCP depends on the state of the dnsmasq cache. This is because the answer to query for the root key is too long to fit in a UDP packet via dnscrypt. If dnsmasq queries the root key during its attempt to validate the query above, then the answer will be truncated, and dnsmasq will restart the whole process, using TCP. Since when using TCP, the RRSIG are not omitted, everything works.

If, on the other hand, dnsmasq has the root key cached (or more generally, doesn't trip over anything that requires a move to TCP) then the missing RRSIGs in the answer via UDP now matter, and the validation fails.
'/quote'

When using NO 'd0wn' servers, limiting the servers to 'dnscrypt.eu-dk' and 'dnscrypt.eu-nl', the problem disappears.

Simon tried to get info regarding the versions of running dns software of the dnscrypt servers, used by 'd0wn', but hasn't received a reply (yet).

Currently, a lot of (pihole) users are driven away from dnscrypt-proxy towards a solution, using ubound, because the use of DNSSEC leads to problems, when using dnscrypt-proxy. It's only very recent that it has been determined the problem is related to certain servers, providing dnscrypt + DNSSEC.

Is it possible to find out witch servers are using the docker image, this to determine if the servers, using this image, are also causing this problem? It would be helpful if the versions of the DNS software used, could also be mentioned.

Thanks

**Comment by jedisct1** [comment]
The Docker image uses Unbound. d0wn servers don't appear to be using Unbound. It doesn't send anything different over TCP than UDP, besides possibly truncated responses.

The Docker image also supports ChaChaPoly for encryption (and not the old cipher any more). d0wn servers apparently don't support it.

So, d0wn servers don't appear to be running that image. Bugs should be reported to him directly.

**Comment by jpgpi250** [comment]
Would it be possible to provide a list of servers, that use the docker image, so I can test them?

I'm using [this](https://dnscrypt.info/public-servers/) site  (https://dnscrypt.info/public-servers/) to get servernames.

Thanks

**Comment by jedisct1** [comment]
How would I know?

`scaleway-fr`, `sfw.scaleway-fr` and `doh.crypto.sx` do. I don't know about the other ones.

**Comment by mibere** [comment]
@jpgpi250 [dnscrypt.me](http://dnscrypt.me/) uses a [modified](https://github.com/mibere/dnscrypt-server-docker/blob/master/unbound.sh) docker image with Unbound too,
