### ISSUE TITLE
Feature Request: SOCKS proxy for upstream connections?

### ISSUE THREAD

**Issue by CHLLHC** [DNSCrypt/dnscrypt-proxy#431]
Hi,

I want to hide my request to DNS server also, so I want to route the TCP request coming out of the dnscrypt-proxy to a socks5 proxy. I read the example toml, it said the TCP requests to the upstream server can be routed to tor, but without elaborate. I think it needs a `uptream_proxy` right after the `force_tcp` setting.

Thanks

**Comment by jedisct1** [comment]
Is it something you could contribute?

**Comment by CHLLHC** [comment]
Yes, I could. I already read the code and it seems like a minor change (just plug in the socks5 dialer?). But this is my first time using Go, it might take a while.

Thanks.

**Comment by jedisct1** [comment]
I'm not very familiar with Go and this is my first project in this language as well, but indeed it looks like it comes with everything we need to support SOCKS.

There's already a dialer defined for HTTP/2 queries (see `xtransport.go`), so I'm not sure how two dialers could be stacked together, or if there is another way to do it for HTTP.

**Comment by CHLLHC** [comment]
Thanks, I will check it.
Just want to make sure, all outgoing traffic is handled by functions in `xtransport.go`, right?

**Comment by jedisct1** [comment]
`xtransport.go` is only for HTTP traffic.

**Comment by unixfox** [comment]
This feature is a great idea for routing the DNSCrypt traffic trough tor, why closing the issue?
