### ISSUE TITLE
[windows] primary vs alternate dns server setup issue

### ISSUE THREAD

**Issue by Skrell** [DNSCrypt/dnscrypt-proxy#433]
Because Windows requires the specification of 2 dns server addresses both of which must be accessible what do we put in the alternate box after using 127.0.0.1 for the primary?

**Comment by jedisct1** [comment]
I've never seen Windows require 2 DNS resolvers.

**Comment by Skrell** [comment]
![untitled](https://user-images.githubusercontent.com/590266/39666028-146cd284-506b-11e8-86e0-5e3736abcca8.png)

**Comment by Skrell** [comment]
both of the bottom boxes need to be filled in or windows errors on it.  So the 1st one should be 127.0.0.1 for dnscrypt-proxy but what should the bottom be?  Currently they are set to ComodoDNS server.

**Comment by gordyf** [comment]
Can you enter the same IP address twice?

**Comment by Skrell** [comment]
No.. This is probably a misunderstanding on my part of what windows wants
but I'd like confirmation of how setup should be done in a working
environment?

**Comment by Skrell** [comment]
![untitled](https://user-images.githubusercontent.com/590266/39667780-32ba32fc-508b-11e8-8d8e-15796be4dc10.png)

**Comment by Noxwizard** [comment]
Windows does not require that you provide an alternate DNS server address. Set the preferred address to 127.0.0.1 and erase all of the fields for the alternate server.

**Comment by Skrell** [comment]
And what should these settings be? 
![untitled2](https://user-images.githubusercontent.com/590266/39675431-07c7a0fe-5129-11e8-8332-a08a8f9a08ee.png)

**Comment by Noxwizard** [comment]
The defaults are fine.

**Comment by Skrell** [comment]
thank you
