### ISSUE TITLE
Feature Req: Option to automatically block detected suspicious query's

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#434]
Some query's are pretty creative and difficult to filter or block. I see no way currently possible to block 'p' without breaking a massive chunk of the internet. Having an option to block all detected suspicious entries automatically would mitigate against 0 day threats, threats that are difficult or impossible to block with patterns, and save a lot of trouble constantly monitoring for entries. Whitelisting logged entries then can be used for false positives.

Some suspicious entries I have seen lately:
[2018-05-05 12:25:05]	127.0.0.1	p	A
[2018-05-06 23:05:45]	127.0.0.1	favicon.png	A

May  6 23:05:45 dnsmasq[4150]: query[A] favicon.png from 192.168.50.241
May  6 23:05:45 dnsmasq[4150]: forwarded favicon.png to 127.0.0.1
May  6 23:05:45 dnsmasq[4150]: validation result is SECURE

**Comment by jedisct1** [comment]
What you saw is just due to broken code in web pages.

Nobody knows how to block 0 day threats, especially not just by looking at DNS query names.

**Comment by rugabunda** [comment]
How do you know that? Since when was broken code is secure?

**Comment by jedisct1** [comment]
These names don't resolve to anything, so there are no risks. And if they do resolve, the TLD exists, so you want to connect to them anyway.
