### ISSUE TITLE
Feature request: Dnscrypt-proxy option to automatically block suspicious entries in realtime

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#436]
This would be an awesome feature. Please consider this. Thank you so much!

**Comment by jedisct1** [comment]
That would be quite dangerous. If you type `com`, it won't resolve, and block `*.com`.

**Comment by rugabunda** [comment]
Unless the code expressly accounts for these potential dangers; like don't auto block anything alpha 2-3 characters unless specified; this will block the majority of suspicious entries, then human intervention can do what little remains in suspicious.log.  Or, what about having those entries in a simple predefined white-list?

**Comment by rugabunda** [comment]
A list of all valid top-level domains is maintained by the IANA and is updated from time to time. It does not include .co.uk for exmaple. https://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by jedisct1** [comment]
And if a name doesn't resolve because of a temporary configuration error, you won't be able to access it ever again.

A better alternative that achieves a similar result is to bump the `cache_neg_min_ttl` and `cache_neg_max_ttl` values. This controls how long a "this name doesn't exist" response is cached.

**Comment by rugabunda** [comment]
Unless dnscrypt blocks these entries by default but does not save these entries permanently. Lets say it throws them away immediately.  For best security practices, what setting do you recommend for cache_neg_min_ttl and cache_neg_max_ttl?

**Comment by rugabunda** [comment]
Actually if dnscrypt simply (optionally) blocks these querys in realtime without saving them, but logs them for monitoring and whitelisting purposes... just like a firewall, you can't beat that imo. For best security practices, what setting do you recommend for cache_neg_min_ttl and cache_neg_max_ttl?
