### ISSUE TITLE
show in log file releated to which process

### ISSUE THREAD

**Issue by heforfree** [DNSCrypt/dnscrypt-proxy#438]
hello
im new this tool.but thanks for great tool
can we see in logs (query.log,blocked.log) each address related to which process?
example
[2018-05-07 18:20:28]	127.0.0.1	adservice.google.com	*.adservice.google.com
turn to
[2018-05-07 18:20:28]	firefox.exe 127.0.0.1	adservice.google.com	*.adservice.google.com

also if it even sow path of file much better

also possible to use dnscrypt for some process not entire system?

thanks

**Comment by jedisct1** [comment]
Hi!

The proxy doesn't have this information. All it receives is the IP address. The DNS protocol doesn't include anything about the process having sent a query.

**Comment by heforfree** [comment]
ok thanks i assume it answer second part of my question too
