### ISSUE TITLE
Can't get any log files

### ISSUE THREAD

**Issue by ChrisLane** [DNSCrypt/dnscrypt-proxy#439]
Version: 2.0.11
Systemd service log: https://paste.ee/p/73YkF
Systemd socket log: https://paste.ee/p/l0y2k
Config: https://paste.ee/p/lAOJi

I am unable to get a query.log etc. I've checked in both /etc/dnscrypt-proxy and /var/log/dnscrypt-proxy and found no log files.

**Comment by ghost** [comment]
You have to change log path in dnscrypt config to `/var/log/dnscrypt-proxy/<log>`, example: 
`log_file = 'dnscrypt-proxy.log' `should be:
`log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'`
See [how Archlinux does it](https://git.archlinux.org/svntogit/community.git/tree/trunk/configuration.diff?h=packages/dnscrypt-proxy).

**Comment by ChrisLane** [comment]
That sorted it, thanks!
