### ISSUE TITLE
Help wanted: Linux installer

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#44]
Having the ability to download and install the thing using a shell command such as

```sh
wget https://...
minisign -op ... | sh
```

would be convenient. Can you imaging if that even played well with systemd and didn't break your Linux distribution? That would be sweet.

I rarely use Linux, and when I do, the way I configure DNS is not something you want to hear about.

So, your help would be welcome!

**Comment by thuantran** [comment]
Hum although I'm also quite familiar with systemd and Linux, maintaining a universal package for all the distros would be quite tedious.

In any case, my script for asuswrt-merlin might be a good starting point for that at https://github.com/thuantran/dnscrypt-asuswrt-installer/tree/dnscrypt-proxy-v2

**Comment by bdossantos** [comment]
Maybe this could be a starting point too: https://github.com/bdossantos/bds.home/blob/f04c75226b922b1fe6f70b899f32622f2658a326/install.d/20-dnscrypt-proxy#L1-L36

But not (yet) systemd support and minisign check.

Edit: I've used systemd with a previous dnscrypt-proxy version but It was "ugly" (cuz multiple instances of program) https://github.com/bdossantos/bds.home/commit/d8461155c85d5917b6e690f1dd54c242c0c10eec#diff-98e9865a6ae96ad1d39a6571e45aab12
