### ISSUE TITLE
Subdomains/CNAME fail to resolve

### ISSUE THREAD

**Issue by ChrisLane** [DNSCrypt/dnscrypt-proxy#440]
Version: 2.0.11
Systemd service log: https://paste.ee/p/73YkF
Systemd socket log: https://paste.ee/p/l0y2k
Dnscrypt Config: https://paste.ee/p/lAOJi
Pdnsd Config: https://paste.ee/p/6GpR6

I've changed my configuration to use pdnsd for permanent caching, pdnsd operates on port 53 and dnscrypt is on 5354.
When using drill to request DNS records, everything works fine. However, if I attempt to access websites using Firefox, queries start to fail and these get cached.
I did not have issues before using pdnsd, however, clearly there must be some interoperability issues here that I cannot see due to #439. The issue goes away if I change pdnsd to use a dns server other than dnscrypt.

**Comment by ChrisLane** [comment]
Nothing strange in query.log.

Here's an example of an incorrect entry cached in pdnsd currently: https://paste.ee/p/wfD2G
Clearing the cache and then querying again seems to fix the issue sometimes.

**Comment by jedisct1** [comment]
Can you remove the blacklist and forwarding rules?

**Comment by jedisct1** [comment]
```
block_ipv6 = true
```

Try removing that.

**Comment by jedisct1** [comment]
By the way, pdnsd development stopped 6 years ago. Ubuntu does not package it any more (since Zesty, so it's been a while).

Not sure that running that thing in 2018 is a good idea, if only from a security perspective.

**Comment by ChrisLane** [comment]
Ah, I hadn't noticed. I'll be moving to a different solution soon.

Removing `block_ipv6 = true` seems to have fixed the issue for some reason.
