### ISSUE TITLE
Feature request: add the ability to drop privileges on Unix

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#441]
fork+exec seems to work fine on Linux/BSD/macOS. We can create sockets, and easily pass them to children: https://gist.github.com/jedisct1/92a75f1dc7a4c2c1cad4802131994736

Feature request: implement this in `kardianos/service`.

**Comment by jedisct1** [comment]
There are still some issues, such as the root process that remains around (or else, it breaks installation as a service).

But we can take advantage of this to implement a simple supervisor, that restarts the child if it ever dies.

**Comment by publicarray** [comment]
> There are still some issues, such as the root process that remains around (or else, it breaks installation as a service).

I was afraid that there might me something that would break 😢

Regarding the supervisor, It's a good idea but I also think that this stuff adds code for not much gain. Many init systems can already be configured to restart a service if it dies.
