### ISSUE TITLE
DoH cloudflare does not return a IP after 15 minutes

### ISSUE THREAD

**Issue by Jimmy89** [DNSCrypt/dnscrypt-proxy#442]
Hi all,

I am using the 2.0.11 version of Dnscrypt with the following config:

```
server_names = ['cloudflare', 'doh-crypto-sx']
listen_addresses = ['127.0.10.1:1053']
max_clients = 250
keepalive = 60
lb_strategy = 'fastest'
log_level = 1
log_file = '/opt/dnscrypt-proxy/dnscrypt-proxy.log'
tls_disable_session_tickets = false
tls_cipher_suite = [52392, 49199]
cert_ignore_timestamp = true
```
Everything else is exactly as the example toml file.

Cloudflare is always chosen as the fastest server. I am NOT running this through systemd. I use Fedora ARM (27) for the raspberry pi 3.

The problem:
When the dnscrypt service starts everything is fine. However, after 15 minutes dnscrypt does not return a IP address anymore.

Command:
` dig @127.0.10.1 -p 1053 google.com`

Result:
```
; <<>> DiG 9.11.3-RedHat-9.11.3-4.fc27 <<>> @127.0.10.1 -p 1053 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8264
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0257, udp: 1536
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             599     IN      A       216.58.211.110

;; Query time: 35 msec
;; SERVER: 127.0.10.1#1053(127.0.10.1)
;; WHEN: Thu May 10 20:27:03 CEST 2018
;; MSG SIZE  rcvd: 65
```

The got answer is empty. Normally. this header must contain the IP address. I get this behavior by after some time by default! It's not incidentally.

I grabbed the compiled version for the ARM system. I do not compile dnscrypt myself. The error log shows the following error: _Server [cloudflare] returned temporary error code [2] -- Upstream server may be experiencing connectivity issues_

Just to be clear: the first 15 minutes I can send dozens of DNS queries to cloudflare with a normal response.

Anyone any clue?

Update: I checked the logs and it's exactly 15 minutes after starting the server that the error start occurring.

**Comment by jedisct1** [comment]
Unfortunately that's a known problem with Cloudflare, that also happens without encrypted DNS.

You're not alone on that one: https://community.cloudflare.com/t/nxdomain-servfail-for-google-com-from-1-0-0-1-amsterdam-nl/17848

**Comment by jedisct1** [comment]
There's not much that can be done on the client. It just returns what it got from the server.

As a mitigation, you can increase the minimum TTL so that valid responses get cached for a longer period of time. Or use forwarding to send queries for failing domains to another resolver.

**Comment by jedisct1** [comment]
So, these are things you should report on their forum, along with the datacenter you are hitting (use `https://www.cloudflare.com/cdn-cgi/tracey` to get it).
