### ISSUE TITLE
Installed dnscrypt-proxy 2.0.12 - changelog

### ISSUE THREAD

**Issue by jpgpi250** [DNSCrypt/dnscrypt-proxy#443]
I've just uninstalled 2.0.11 and installed 2.0.12

The changelog says: 'The proxy will now wait for network connectivity before starting. This is useful if the proxy is automatically started at boot, possibly before the network is fully configured.'

I checked /etc/systemd/system/dnscrypt-proxy.service but the entries we've previously discussed ( Wants=network-online.target and After=network-online.target) aren't there.

Did you use an alternative method to wait for the network?

Thanks

**Comment by mibere** [comment]
dnscrypt-proxy has its own check now, see https://github.com/jedisct1/dnscrypt-proxy/commit/ce62981c44913f59a0d638397edf17ebd7da27bb

**Comment by jedisct1** [comment]
Yes, the proxy does it. It doesn't depend on systemd, so the behavior is consistent across all operating systems no matter how the proxy is started.

`Wants=network-online.target` and `After=network-online.target` are not required any more.
