### ISSUE TITLE
ipv6 disabled, still getting ipv6 responses and/or SERVFAIL

### ISSUE THREAD

**Issue by jmccorm** [DNSCrypt/dnscrypt-proxy#445]
IPv6 is disabled in my configuration. (ipv6_servers = false, block_ipv6 = true) I noticed a problem when I did an apt-get and it failed. I saw that it wasn't able to resolve raspbian.raspberrypi.org. Jumping forward to the workaround, the issue was fixed when I set cache=false in dnscrypt-proxy.toml.

To investigate, first I did this...

> pi@pi3:/opt/dnscrypt-proxy $ ./dnscrypt-proxy -resolve raspbian.raspberrypi.org
> Resolving [raspbian.raspberrypi.org]
> 
> Domain exists:  probably not, or blocked by the proxy
> Canonical name: mirrordirector.raspbian.org.
> IP addresses:   2a00:1098:0:80:1000:75:0:3
> TXT records:    -
> Resolver IP:    [PRIVATE]

Uh... it was returning an IPv6 address despite my configuration? That's strange. Anyhow, I *am* using Pi-Hole on port 53 (and dnscrypt on port 5353). When trying to look the host up through Pi-Hole (which is correctly configured to go through dnsmasq which then talks to dnscrypt), it returns...

> pi@pi3:~ $ nslookup
> > raspbian.raspberrypi.org
> Server:         127.0.0.1
> Address:        127.0.0.1#53
> 
> ** server can't find raspbian.raspberrypi.org: SERVFAIL

In dnscrypt-proxy.toml, I then set "cache=false" and rebooted. Now it does this (which seems good)...

> pi@pi3:/opt/dnscrypt-proxy $ ./dnscrypt-proxy -resolve raspbian.raspberrypi.org
> Resolving [raspbian.raspberrypi.org]
> 
> Domain exists:  probably not, or blocked by the proxy
> Canonical name: mirrordirector.raspbian.org.
> IP addresses:   93.93.128.193
> TXT records:    -
> Resolver IP:    [PRIVATE]

...and then...

> pi@pi3:/opt/dnscrypt-proxy $ nslookup
> > raspbian.raspberrypi.org
> Server:         127.0.0.1
> Address:        127.0.0.1#53
> 
> Non-authoritative answer:
> raspbian.raspberrypi.org        canonical name = mirrordirector.raspbian.org.
> Name:   mirrordirector.raspbian.org
> Address: 93.93.128.193
 
My interpretation of the experiments is that somehow, in an IPv4 only environment, enabling the cache inside of dnscrypt-proxy will cause it to return IPv6 results, despite being configured to the contrary. I'll attach my dnscrypt-proxy.toml file.

[dnscrypt-proxy.toml.txt](https://github.com/jedisct1/dnscrypt-proxy/files/2007310/dnscrypt-proxy.toml.txt)

**Comment by jmccorm** [comment]
I'm doing this to myself, aren't I? Now that I re-read the config file...

> #########################
> #        Filters        #
> #########################
> 
> ## Immediately respond to IPv6-related queries with an empty response
> ## This makes things faster when there is no IPv6 connectivity, but can
> ## also cause reliability issues with some stub resolvers.
> ## Do not enable if you added a validating resolver such as dnsmasq in front
> ## of the proxy.
> 
> block_ipv6 = true

**Comment by jmccorm** [comment]
I'll go ahead and keep this ticket open, because the output seems suspect from the initial command I used to investigate the problem:

>     pi@pi3:/opt/dnscrypt-proxy $ ./dnscrypt-proxy -resolve raspbian.raspberrypi.org
>     Resolving [raspbian.raspberrypi.org]
> 
>     Domain exists: probably not, or blocked by the proxy
>     Canonical name: mirrordirector.raspbian.org.
>     IP addresses: 2a00:1098:0:80:1000:75:0:3
>     TXT records: -
>     Resolver IP: [PRIVATE]

**Comment by phixion** [comment]
I have the exact same issue after disabling ipv6 entirely it doesn't resolve anymore

phixion@omega:/opt/dnscrypt-proxy $ ./dnscrypt-proxy -resolve raspbian.raspberrypi.org
Resolving [raspbian.raspberrypi.org]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -
Resolver IP:    209.250.235.170 (209.250.235.170.vultr.com.)

**Comment by jedisct1** [comment]
You're not using dnsmasq, right?

Because the option explicitly says "do not enable if you are using dnsmasq".
