### ISSUE TITLE
Feature request: DNS Cache statistics

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#448]
Hi,

would be nice to get some statistics about the cache efficiency, cache hits and cache misses - also if cache is filled or has still some space.
could be useful to configure cache size properly

**Comment by jedisct1** [comment]
+1

**Comment by JasonSwindle** [comment]
+1 as I have this same request:

https://github.com/jedisct1/dnscrypt-proxy/issues/337

**Comment by meguroyama** [comment]
May need more research but I'm looking into see if we can use [expvar ](https://golang.org/pkg/expvar/)to monitor dnscrypt in [netdata](https://github.com/firehol/netdata/wiki/Monitoring-Go-Applications).

**Comment by IceCodeNew** [comment]
+1

**Comment by Misiek304** [comment]
+1

**Comment by beelze** [comment]
+1 for cache stat and cache memory usage

**Comment by mikegleasonjr** [comment]
A Prometheus exporter or Prometheus-compatible endpoint would be great!

**Comment by jedisct1** [comment]
Yes, using Prometheus instead of some ad-hoc protocol would be great.

But it looks like you have far more experience with Go that I do, so go ahead :)

**Comment by mikegleasonjr** [comment]
@jedisct1 I will consider it for sure... thanks for the project. Running it in a docker environment easily with pi-hole!

**Comment by J0s3f** [comment]
Would be great to not only have cache statistics but also statistics about the DNS servers.

**Comment by scubasunny** [comment]
@jedisct1 : Hi, some reason why you closed this request ?

Thx
