### ISSUE TITLE
Feature request: set order of resolvers instead using the fastest

### ISSUE THREAD

**Issue by dntndnm** [DNSCrypt/dnscrypt-proxy#452]
Hello, I'm new to this great looking software and I want to start using it, but...

I don't like automation anywhere.

As far as I know I can set an online source for usable resolvers or I can set a list (called 'static') in the config file and dnscrypt-proxy v2 will ping each of the items on my list and use the fastest one automatically.

Can we have a simple feature where this behavior can be turned off and the user can set the order of resolvers to be used?

So for example I set resolver_1 as 1st on my list, resolver_2 as 2nd etc. and dnscrypt-proxy v2 will use the first one only and if that doesn't respond it will change to the second one, but only when the 1st is offline or unresponsive and it won't ping or try any other resolvers just the ones I set and only in the set order and only when the actual one doesn't respond.

Thank you for everyone who contributes in any way in developing this software!

**Comment by IceCodeNew** [comment]
I'd prefer this feature too~

**Comment by dntndnm** [comment]
Sorry, I don't know how this works...I saw you closed this issue and added "timeout" label to it.
What do you mean by this?
It was open a for weeks, I thought you will consider this feature, but now you closed it.
Can you explain please?
I'm not a programmer, also I'm new to Github, I don't know how things work around here.

**Comment by jedisct1** [comment]
@dntndnm There has been zero progress on this for 30 days, because nobody showed interest in implementing this.

After 30 days, ticket are closed but get a "timeout" label. So a query can be used later to look at all the tickets that are good ideas, but are not high priority and that no one was interested in implementing by the time they were posted.
