### ISSUE TITLE
The service won't start automatically (Windows 7)

### ISSUE THREAD

**Issue by Hasshu** [DNSCrypt/dnscrypt-proxy#454]
Windows 7 Ultimate (64-bit); dnscrypt-proxy appears to have been broken since v2.0.12, as the service doesn't start automatically anymore. According to the Event Viewer:

> A timeout was reached (30000 milliseconds) while waiting for the DNSCrypt client proxy service to connect.

> The DNSCrypt client proxy service failed to start due to the following error: 
> The service did not respond to the start or control request in a timely fashion.

Possibly related to #447.

**Comment by r13s** [comment]
[Here's](https://support.microsoft.com/en-us/help/922918/a-service-does-not-start-and-events-7000-and-7011-are-logged-in-window) the solution.

**Comment by jedisct1** [comment]
Can you update the wiki with the solution?

**Comment by jedisct1** [comment]
Apparently not.

**Comment by Hasshu** [comment]
@jedisct1 Whom exactly were you addressing? Incidentally, the solution mentioned above is just a workaround (which even doesn't work all the time).
