### ISSUE TITLE
Resolving does not work after 2.0.14 upgrade

### ISSUE THREAD

**Issue by ZJaume** [DNSCrypt/dnscrypt-proxy#456]
After 2.0.14 upgrade on Arch Linux, the nslookup queries return connection timed out and the status of the systemd service does not report any error. I'm using default configuration and cloudflare dns server. If I use cloudflare dns servers in resolv.conf, normal dns queries work well.
How can I debug this problem? I have tried to set log_level=0 but journalctl does not display more information.

Edit: I have tried to manually downgrade to 2.0.11 and everything works well

**Comment by 26000** [comment]
Same issue, disabled dnscrypt for now. Waiting for updates!

**Comment by jedisct1** [comment]
What happens if you run it from the command line?

**Comment by 26000** [comment]
@jedisct1 nothing, journalctl is ok (pings servers and says it's ready). Still times out:
```
~ $ dig @127.0.0.1 github.com

; <<>> DiG 9.12.1-P2 <<>> @127.0.0.1 github.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by 26000** [comment]
Hmm, I think it doesn't bind to that port:
```
~ $ sudo netstat -lptu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 localhost:versiera      0.0.0.0:*               LISTEN      530/tor             
tcp6       0      0 [::]:mshvlm             [::]:*                  LISTEN      1190/mpd            
udp        0      0 kappa:bootpc            0.0.0.0:*                           439/NetworkManager  
udp    19136      0 0.0.0.0:mdns            0.0.0.0:*                           1229/chromium --dis 
udp6   34368      0 [::]:mdns               [::]:*                              1229/chromium --dis 
```

And I'm running it with sudo, though if I don't, it doesn't complain.

**Comment by ZJaume** [comment]
Querying with dnscrypt-proxy command says that domain does not exist or is blocked. But if I set the resolv.conf to 1.1.1.1 the dnscrypt-proxy command sucess

**Comment by jedisct1** [comment]
From the command line:

```sh
dnscrypt-proxy -config /path/to/config/file/dnscrypt-proxy.toml
```

It shouldn't do anything with journald here.

**Comment by ZJaume** [comment]
Also noticed if I upgrade to 2.0.14 and restart the daemon with that version, it works well. The problem appears after reboot

**Comment by 26000** [comment]
lol!

@jedisct1 it writes to syslog, which is in the default config. The command I used is `sudo /usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml`.

**Comment by jedisct1** [comment]
@26000 What is the `listen_addresses =` value in the configuration file?
Did you try `listen_addresses = ['127.0.0.1:53']`?

**Comment by jedisct1** [comment]
@ZJaume Maybe systemd is not starting the correct file? Remove all the related systemd files, and type `dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -service install`

**Comment by 26000** [comment]
@jedisct1 it works if I comment out that section. Well, it says 'When using systemd socket activation, choose an empty set (i.e. [] )'. Seems like socket activation was broken, and I don't even know how it works...

**Comment by 26000** [comment]
Hm. `sudo systemctl start dnscrypt-proxy.socket` and it works! Thank you @jedisct1 , seems that vendor preset for socket activation has been changed and it was disabled for us.

**Comment by poentodewo** [comment]
btw are this normal dnscrypt look like only listen on tcp ?

![97](https://user-images.githubusercontent.com/15877677/40279787-07e5b9ae-5c73-11e8-85ff-8deeb8b29c07.png)

**Comment by jedisct1** [comment]
@poentodewo Yes, UDP is not a connected protocol; the "LISTEN" state doesn't exist.
