### ISSUE TITLE
[Enhacement] ip-blacklist - CIDR (diapasones) support

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#457]
Would be nice to have support for a blocking IPs not only one by one, but using diapasones (subnets).

Let's say, I know some spying/ad/tracking/malware subnet.
For example (M$ Ads Partner):

**216.252.164.0 - 216.252.167.255** --- (1024 ip) --- AppNexus (US) ----M$ Ads Partner

Blocking all 1024 IPs one-by-one is an absurd.

But if CIDR will be supported, you can easily and fast add whole unwanted subnet
216.252.164.0 - 216.252.167.255 with only one string in **CIDR format**:

**216.252.164.0/22**

-----------------------------
You can easily transform any IP diapasone to CIDR (and backward) using one of the websites over Internet:

IPADDRESSGUIDE: http://www.ipaddressguide.com/cidr

**Comment by jedisct1** [comment]
The ratio between tickets labeled "Features request" and contributions is a bit too high already. In fact, it triggers a division by zero.

**Comment by iWARR** [comment]
OK. If you can, you do.
This feature is rare supported by different software products, unfortunatelly (far not all Firewalls or filtering parts in other products have this). I guess, it is not easy to implement...

But it will be **bless feature** for portable devices/mobile phones that have lack of the firewalls (not many of people install firewalls on mobiles). It will be handy and simple to restrict thousands of unwanted connections via dnscrypt-proxy, using IPs blackist also, not only domain filtering.
