### ISSUE TITLE
Feature(for release) request: statically linked release

### ISSUE THREAD

**Issue by honwen** [DNSCrypt/dnscrypt-proxy#458]
Release in https://github.com/jedisct1/dnscrypt-proxy/releases

Some are ```statically linked```, like ```linux_mips```
Some are ```dynamically linked```, like ```linux_x86_64```

Can U release binary all statically linked, please? THX a lot.

**Comment by jedisct1** [comment]
Duh?

Go cannot produce dynamically linked executables.

**Comment by jedisct1** [comment]
Ah, interesting, when the thing is compiled on Linux (as Travis does), it depends on `/lib64/ld-linux-x86-64.so.2`, but if you compile it on macOS, you get a static executable.

Apparently, the `-tags netgo` can avoid this.

But you obviously have far more experience with Go than me, so I'd gladly accept a pull request to change the Travis file and build static files, provided that it doesn't remove features or degrades performance.

Thanks for your help!
