### ISSUE TITLE
Subreddit made for dnscrypt-proxy

### ISSUE THREAD

**Issue by meguroyama** [DNSCrypt/dnscrypt-proxy#460]
I've started a [subreddit ](https://www.reddit.com/r/dnscrypt/)for the project, it'll auto-post the new releases feed to the page. Please let me know if you'd like to be added to the moderation queue.

**Comment by jedisct1** [comment]
This is great, thank you!

> Please let me know if you'd like to be added to the moderation queue.

Yes, that would be great!

**Comment by meguroyama** [comment]
Great, if I can get a list of reddit usernames to be added to the mod queue. I can have everyone added.

**Comment by jedisct1** [comment]
`jedisct1` :)

**Comment by scubasunny** [comment]
Great!

**Comment by brainscar** [comment]
Great! 

The css could use some work on the old layout, I can't figure out how to toggle reddit's new layout.

**Comment by meguroyama** [comment]
>The css could use some work on the old layout, I can't figure out how to toggle reddit's new layout.

Thanks for the feedback @brainscar , I'm testing out the new layout by visiting https://new.reddit.com/r/dnscrypt/

**Comment by mkirisame** [comment]
Hello, I've talked to Eric of Debian in early spring this year that he may update the official packages for easy installation:
https://github.com/jedisct1/dnscrypt-proxy/issues/254#issuecomment-376846783

It took a little longer than expected, but he released a first version a few days ago and now is fully up-to-date:
https://packages.debian.org/sid/net/dnscrypt-proxy

Can the wiki be updated?
https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux

It should be as easy now as simply doing this on ubuntu/debian linux:
```
sudo apt-get install dnscrypt-proxy
```

**Comment by mkirisame** [comment]
Interesting label, how is an announcement off-topic? I don't have a reddit account so I merely told about the Debian packages being finally available and that the wiki still falsely claims we are on 1.9.x

https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-Debian-Ubuntu

It is your wiki, I'd probably wouldn't edit it to your liking.
