### ISSUE TITLE
dnscrypt-proxy stops working after update

### ISSUE THREAD

**Issue by pguizeline** [DNSCrypt/dnscrypt-proxy#462]
Hi!

My setup uses dnsmasq listening on port 53 and dnscrypt-proxy listening on port 5053, it works really well, but on two different devices I lose DNS resolution after upgrading the dnscrypt-proxy binary. To upgrade I just stop dnscrypt service, swap the binary, and start the service again. Am I doing something wrong? Some cache that I need to clear?

Thanks!

**Comment by Haraade** [comment]
Have you set block_ipv6 to true in dnscrypt-proxy.toml ?

**Comment by pguizeline** [comment]
It's set to false

**Comment by pguizeline** [comment]
I forgot to post a little bit more info, I'm using Debian 9 and I've manually installed dnscrypt-proxy (I couldn't get the PPA to work, a problem with the .socket systemd)

Here's my config:
[dnscrypt-proxy.toml](https://ghostbin.com/paste/44cjm)
[dnsmasq.conf](https://ghostbin.com/paste/c94cz)

Everything works until I update! Any help would be great! Thanks!

**Comment by Haraade** [comment]
Have you seen what syslog says?
sudo cat /var/log/syslog | grep dnscrypt proxy

If installation is set up as system service.
sudo systemctl status dnscrypt proxy

**Comment by pguizeline** [comment]
It says "Unable to resolve", the crazy thing is that a reboot of the server fixed it.

I'm using a NUC as my DNS server at home, and the router is a UniFi Security Gateway, I think that my DNS redirect rule could be causing this. Really strange.
