### ISSUE TITLE
Resolver not working.

### ISSUE THREAD

**Issue by cedws** [DNSCrypt/dnscrypt-proxy#465]
* Operating System: Windows 10
* Version: 2.0.14

I have downloaded 2.0.14 and copied the `example-dnscrypt-proxy.toml` to `dnscrypt-proxy.toml`. I have only changed the resolvers to look like this:
```
server_names = ['cisco']
```
When I run `dnscrypt-proxy.exe -resolve google.com -config dnscrypt-proxy.toml`, the request succeeds, but shows my ISP's DNS under `Resolver IP`. I have changed my network interface to use `127.0.0.1` as a DNS server. I have also ran `ipconfig /flushdns`.

**Comment by cedws** [comment]
My bad. I am using some software named `simplewall` which was blocking loopback connections. Thanks!

**Comment by jedisct1** [comment]
Glad to see that you figured it out :)
