### ISSUE TITLE
error starting dnscrypt  2.0.14 on android 4.4.2

### ISSUE THREAD

**Issue by admzzz** [DNSCrypt/dnscrypt-proxy#466]
root@localhost:/data/local/entware/root/android-arm# ./dns* --version
CANNOT LINK EXECUTABLE: cannot locate symbol "sigfillset" referenced by "./dnscrypt-proxy"...

and at the same time
root@localhost:/data/local/entware/root/linux-arm# ./dns* --version
2.0.14
this is starting/working ok, but cannot be installed as service on android

**Comment by jedisct1** [comment]
Android 4.4 is so old. I don't think it's supported by Go.

**Comment by admzzz** [comment]
jedisct1,
if there are no workaround for 4.4, than mark the required android's version in the description, pls.

jfyi: on 4.4.2 linux-arm version of dnscrypt works fine when starts from /etc/init.d, but one had to know this way and avoid starting it as service.

**Comment by Sporif** [comment]
I think that error is to do with the Android NDK binaries, they are built with `--api 21` in .travis.yml. We could try api 14, that should give us Android 4.0 compatibility.

Also the service feature won't work on any Android version, that vendor module simply doesn't support Android. /etc/init.d or the like must be used.

**Comment by admzzz** [comment]
Sporif, jedisct1,
once again: linux-arm version works fine, but on android another feature is required (and i cannot make it work in a bash script) - forking from root to nobody after successful start of dnscrypt-proxy.
otherwise one had to open internet access on firewall to all programs with root permission, and that is totally undesirable.
