### ISSUE TITLE
EvilVibes servers 2/3 removed

### ISSUE THREAD

**Issue by B00ze64** [DNSCrypt/dnscrypt-proxy#468]
Salut Denis.

FYI, as per their homepage, ev-us2 and ev-us3 DNScrypt servers are now removed.

Best Regards,

**Comment by publicarray** [comment]
The related PR is already merged: https://github.com/DNSCrypt/dnscrypt-resolvers/pull/25. It just takes clients a little bit of time before they get the updated list.
