### ISSUE TITLE
new dnscrypt homeserver, switzerland

### ISSUE THREAD

**Issue by ibksturm** [DNSCrypt/dnscrypt-proxy#469]
hi Frank @jedisct1 

I'm Running now a own dnscrypt server at home, where could i write the sdns in your file?

sdns://AQcAAAAAAAAADzIxNy4xNjIuMjA2LjE3OCB2x0U7IXv1uDMjPD3ypxKY4xhAxu7bxJrlMs0vfeSV0BgyLmRuc2NyeXB0LWNlcnQuaWJrc3R1cm0

thanks for maintainig, i'm going now to bed..

andi

**Comment by publicarray** [comment]
The build-in list is here https://github.com/DNSCrypt/dnscrypt-resolvers. Feel free to send a Pull Request.

**Comment by ibksturm** [comment]
@publicarray ok ill try, mersi
