### ISSUE TITLE
Make pre-compiled Android zips to flash

### ISSUE THREAD

**Issue by J316** [DNSCrypt/dnscrypt-proxy#472]
It would be useful to have pre-compiled zips for different architectures to flash with TWRP after choosing the desired resolver by modifying a file in the zip,  or even better a tool with drop-down menus where the user can choose architecture, android version and resolver in order to download a customized zip file

**Comment by jedisct1** [comment]
I don't know Android.

Since you apparently know it very well, can you open a pull request with all the required changes to do this?

Thanks again for your help!
