### ISSUE TITLE
Wrong file name caused compilation failure

### ISSUE THREAD

**Issue by wuzhongyi1105** [DNSCrypt/dnscrypt-proxy#474]
I build dnscrypt-proxy in the latest version of snapshot openwrt on MT7620, and I notice that the source code could not be downloaded due to a file name error, resulting in a compilation failure.
In the latest version of snapshot openwrt, the result of variable $(ARCH) output is mipsel, so dnscrypt-proxy-linux_mipsle-2.0.14.tar.gz should be changed to dnscrypt-proxy-linux_mipsel-2.0.14.tar.gz

**Comment by jedisct1** [comment]
Hi,

What file name error are you referring to?

For Go, the architecture is called `mipsle`. It's confusing that different things use different conventions :( But for consistency the file names match the target given to the Go compiler.
