### ISSUE TITLE
Compatibility with dnscrypt-wrapper

### ISSUE THREAD

**Issue by chrcoluk** [DNSCrypt/dnscrypt-proxy#475]
I find this v2 project interesting but there seems to be a glaring flaw.

I cannot find a way to run a compatible dnscrypt server on a non docker server, there is a guide to run on docker, and a link to a docker package, but there seems to be no such thing as dnscrypt-server for plain linux/freebsd.  It simply doesnt seem to exist on the internet.

Am I missing something here?  Can this newer version of dnscrypt-proxy be made to work with dnscrypt-wrapper? the wrapper doesnt generate the sdns value which seems to be a requirement.

I run 2 dnscrypt server's one on freebsd and one on debian, I dont like docker, I will never use it, so am looking for either the src code to compile or appropriate freebsd/debian packages all 3 which dont exist.

**Comment by Yinchie** [comment]
v2 project works with dnscrypt-wrapper.

Have you ever tried to use a wrapper server with v2, seems you didn't.

And you can generate a sdns value for your server.
https://dnscrypt.info/stamps/

**Comment by ibksturm** [comment]
https://github.com/DNSCrypt/dnscrypt-resolvers/pull/26#issuecomment-394053786


since a week im running dnscrypt (ibksturm) on a unbound server. version 1.7.1 got if you compilz it yourself (./configure —emable-dnscrypt) nativly with dnscrypt

if i got some minutes time i will write a dokumentation

**Comment by jedisct1** [comment]
As pointed out by @Yinchie , standard [dnscrypt-wrapper](https://github.com/cofyc/dnscrypt-wrapper) is compatible.

And it does print the stamp after you create the keys: https://github.com/cofyc/dnscrypt-wrapper/commit/bef4ddfbc6a3a8383533c8389d635df72bf7a8eb

Make sure that you aren't using an old version.
