### ISSUE TITLE
Microsoft is acquiring GitHub! - Will you move repo away

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#477]
Saw already many other Open Source projects moving away to other options.

Will you do the same?

Personally i'm also not really convinced and happy to see one of the biggest monopolists having access to all of this.

Anyway, whatever you decide i'm still fine with this project

Regards

**Comment by jedisct1** [comment]
One could be worried about *private* repositories.

But for code that is already public, this is not going to change anything. They always had access to it.

And Gitlab is backed by Google, so moving the code there wouldn't be any better.

Things may change for enterprise users, but as long as GitHub remains free for opensource users and developers, I don't see any incentive to move. Microsoft network has proven to be rock solid, so we may even get a more reliable service.

**Comment by scubasunny** [comment]
Ok

thanks for clarification and your point of view
