### ISSUE TITLE
Excluding a server in .toml config file

### ISSUE THREAD

**Issue by salmanaligeek** [DNSCrypt/dnscrypt-proxy#479]
Hi,
I don't want to use a specific DNSCrypt server but I want to use all others. Is there any to exclude that server in config file?
I don't want to write names of all servers manually in server_names = []
I just want to exclude one server. Any possibility?

**Comment by stylemessiah** [comment]
How many servers do you think it would actually use if you exclude just one? It might poll more than 3, but its only going to use the fastest one, and if thats offline, switch to the next.....if we ever get to a world where its going to the 5th server in a list, then im calling zombie apocalypse and heading to the countryside

The default config file lists 3 to include (i change to add my nearest server and then my preference after that: server_names = ['publicarray-au', 'cloudflare', 'google'] , theres zero benefit adding more than that, one would think (its almost impossible that all 3 would be down at the same time), so an exclusion list would be backwards thinking imho. Just my 5 cents

**Comment by salmanaligeek** [comment]
Sorry for being late. I accomplished this by dropping all traffic to a particular DNSCrypt server :-)
