### ISSUE TITLE
Beta 11

### ISSUE THREAD

**Issue by ysz223** [DNSCrypt/dnscrypt-proxy#48]
1, I add server_names = ['cisco'] below # server_names = ['scaleway-fr', 'google', 'yandex'], unable to install the service, I do not know where is the error?

2, There is no google service in public-resolvers, how to use?

Thank you.

**Comment by jedisct1** [comment]
That's something that must be in the documentation instead of explaining over and over again.

But there is no documentation yet. If someone wants to write it, that would be great. I won't be able to do it before 1 month.

**Comment by ysz223** [comment]
@jedisct1 
Since the same method works fine with Bate 10, it will not be used again until Bate 11 is available. I am very sorry for the troubles caused to you.
