### ISSUE TITLE
dnscrypt-proxy config tool?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#484]
I'm a little new to the open-source scene and I want to contribute this summer. I was thinking of building a GUI config tool to help users configure this system on Linux. Is this permissible? Can I just start a new repository or something?

**Comment by jedisct1** [comment]
That would be fantastic!

And of course you can do whatever you want, just start a new repository and go ahead!

For Linux, there is https://github.com/F1ash/dnscrypt-proxy-gui already, but it doesn't work with dnscrypt-proxy 2.x as far as I know.

**Comment by ghost** [comment]
Excellent.

I will update you once I make good progress.
