### ISSUE TITLE
Allow multiple fallback resolvers?

### ISSUE THREAD

**Issue by physkets** [DNSCrypt/dnscrypt-proxy#485]
Can multiple resolvers be specified here? In many cases, this is a single point of failure, especially when there is no other 'system resolver'.

**Comment by jedisct1** [comment]
Hi,

Only one fallback resolver can currently be used.

Adding support for multiple ones should be very easy. Is it something you could do?

**Comment by physkets** [comment]
I've never used Go before, but I can try.

I made some of the trivial changes necessary. Can you take a look?
https://github.com/physkets/dnscrypt-proxy/commits/multiple_fallback

Now how do I make it 'try' the first string in the array, and if unsuccessful, move to the next, and so on?

Does this happen in the `xtransport.go` file? That file seems to have a value ("9.9.9.9:53") hard-coded as the 'DefaultFallbackResolver'. That doesn't seem right. That status should be given to, maybe the first string the array.

**Comment by jedisct1** [comment]
This looks great!

Yes, the IP has to be changed to an array as you did, and then addresses can be tried sequentially or randomly. And you found it, `xtransport.go` is indeed where the resolution happens.

`DefaultFallbackResolver` is just a default value, when the functions are called by absolutely nothing has been configured. I'm not every sure that it is used. But you can set it to the default list of default resolvers.

**Comment by physkets** [comment]
How exactly do I 'try each sequentially'? Is there some function for the 'try' part of it?

**Comment by jedisct1** [comment]
Use a `for` loop around calls to `resolve()`.

**Comment by physkets** [comment]
okay, so I'm trying to implement it in `config.go` instead, so that there is still a `fallbackResolver` that is a regular string, and can be used as such, elsewhere.

So then I'm guessing I'll have to access the function as `proxy.xTransport.resolve()`.

If yes, then what do I use as its first two arguments? I don't quite understand `dnsClient`. For the `host`, can I just use something like `example.org`?

If not, then I'll implement it in `xtransport.go`.

**Comment by jedisct1** [comment]
That should be in `xtransport`.

Functions in `config` are only run once to parse the configuration file.

**Comment by physkets** [comment]
Yes, and the fallback only needs to be determined that one time, purely for the sake of being able to resolve `http://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md` for the first time that it starts (if there is no SystemDNS). After that, the resolvers themselves are available. Is that not right?

**Comment by jedisct1** [comment]
The fallback servers can also be used for DoH servers, if their stamp doesn't include an IP.
