### ISSUE TITLE
Reverse lookup

### ISSUE THREAD

**Issue by m4rkusxxl** [DNSCrypt/dnscrypt-proxy#486]
I use dnscrypt-proxy as dns server/cache for the local network.
I wanted to add some static (local) hosts.
That works with the cloaking like:
router 192.168.0.1

It works, that a local machine can lookup "router" and gets the right ip. But looking up the ip address will fail.
Is it already possible to somehow be able to archive this?
If not: Is it possible to add it in a future version as feature request?

Thanks!

**Comment by jedisct1** [comment]
Reverse lookups are actually normal lookups within the `in-addr.arpa` domain (and `in6-addr.arpa` for IPv6).

So you need to cloak this domain for reverse lookups to go to your router.

And if you only need to cloak reverse lookups for `192.168.*`, use `168.192.in-addr.arpa` (the IP has to be in reverse).

**Comment by m4rkusxxl** [comment]
I now have in the cloaking file:
router                          192.168.0.1
1.0.168.192.in-addr.arpa        router

Still, a lookup of 192.168.0.1 or 1.0.168.192.in-addr.arpa does not return "router".

**Comment by jedisct1** [comment]
Try

```
168.192.in-addr.arpa 192.168.0.1
```

**Comment by m4rkusxxl** [comment]
No, unfortunatelly that does not work.
I want that dnscrypt looks up "192.168.0.1" to "router".
(When I add "192.168.0.1 router" to /etc/hosts, then the resolving works in both directions, but only on the local pc where i edited the hosts file.)

**Comment by jedisct1** [comment]
Oh, I now realized... This is not cloaking...

What you want to use is forwarding.

**Comment by m4rkusxxl** [comment]
Reading the wiki page about forwarding:
Is it correct that I will need a separate dns server just for the reverse lookup to work in dnscrypt-proxy?

**Comment by jedisct1** [comment]
No, just forward the `in-addr.arpa` zone to your router IP.

**Comment by m4rkusxxl** [comment]
No, just a timeout. (As I would expect, without an additional dns server.)
The way I understand forwarding is that the requests are just sent to another dns server.

**Comment by m4rkusxxl** [comment]
Any updates? dnscrypt-proxy is still not resolving the local ips to local names. (name to ip is working by cloaking)

(internet) --- (router with dnscrypt-proxy) --- (lan)
ips in the lan are static and also setup in /etc/hosts at the router.

**Comment by jedisct1** [comment]
I updated the OpenWRT instructions with my configuration: https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-on-OpenWRT/72a21b3f6bce67a51de6d7449d14dede7cbfc173

It properly resolves local host names and IP addresses.
