### ISSUE TITLE
how to configure dnscrypt for corporate's firewall?

### ISSUE THREAD

**Issue by admzzz** [DNSCrypt/dnscrypt-proxy#489]
jedisct1,
firewall opens outside only 80 and 443 ports, how dnscrypt should be configured in order to work without restarting-reconfiguring in both situtation (behind firewall and without firewall)?

**Comment by Cheeselets** [comment]
Configure dnscrypt to use DoH over port 443.
This means you will need to use 'cloudflare' or other 'Servers supporting DoH'. 
FYI: Corporate network, if security is configured properly, WILL detect use of dnscrypt over port 443.

**Comment by jedisct1** [comment]
You don't have to use DoH. 

The DNSCrypt protocol also uses port 443 and can use only TCP if you set `force_tcp = true`.

In fact on a corporate network I wouldn't use DoH. If DoH works while DNSCrypt doesn't, it means that something has been installed on your endpoint to intercept outgoing traffic, including HTTPS.

**Comment by Cheeselets** [comment]
Oops, obviously misunderstood something, thought you could ONLY use port 443 IF you used DoH.
So dnscrypt can use any port and UDP or TCP as set via the config file. ???

**Comment by jedisct1** [comment]
DNSCrypt default port is 443, but it can use any port. Either using UDP+TCP or just TCP. It can also share the same port as regular DNS (unencrypted queries will pass through).
