### ISSUE TITLE
Can't get past DPI/DNS based blocking in Turkey most of the time. 

### ISSUE THREAD

**Issue by harakiru** [DNSCrypt/dnscrypt-proxy#491]
I haven't done much testing but it appears that unless the connection is through a regular internet connection (Fiber, DSL etc.) neither DoH or DNSSEC servers are being used. In Turkey DPI based blocking is used to block websites that host politically challenging ideas or explicit content such as wikipedia. It seems that dns-crypt works fine when it is used over mobile connections (mobile data through a WWAN or SIM card), but all other requests done with dnscrypt gets re-routed back to "website is blocked" page when using regular internet.

Example when using a DoH ipv6 server:

`
Domain exists:  yes, 1 name servers found
Canonical name: wikipedia.org.
IP addresses:   195.175.254.2
TXT records:    -
Resolver IP:    212.154.100.18 (dns2.turk.net.)
`

I've tried most combinations of different load balancing settings, servers, protocols, and settings. I would be really great full if someone could inform me on how to get past this issue.

**Comment by jedisct1** [comment]
If your ISP blocks IP addresses, and not just DNS, encrypted DNS cannot help you.

Bypassing rules is not what this project was designed for.

**Comment by harakiru** [comment]
Sorry for bumping but what I meant to say was that the blocking that is done in Turkey is done mainly by DNS spoofing, where even the requests that are sent to a third party DNS server gets rerouted back  to the ISP/Government DNS server. Since this technique is really similar to what is being used in Russia it is widely known that these signals are intercepted and rerouted by some kind of DPI. There are some experimental programs developed by some Russians that can get past or "trick" DPI and access blocked sites, but that stuff is way over my head and its only available on Windows at the moment with no English documentation present. I think it would be really beneficial for both Russian and Turkish internet users if we could add some kind of disclaimer to the wiki saying that this particular kind of blocking could be defeated by using dnscrypt-proxy. As I have said servers that use ipv6 or DoH are being rendered useless by this mechanism, however DNS servers that use DNSSEC and serve over ipv4 work fine. I wasn't requesting for you guys to find a solution to make ipv6 and DoH servers work in these countries. The technology that is responsible for the blocking is kept secret for good reasons, but we should at least open this issue so people interested in the field can drop in and give their insight.

**Comment by jedisct1** [comment]
I'd rather keep "how to bypass filters" discussions elsewhere, as this project was created for security, not evasion.
