### ISSUE TITLE
High CPU usage.

### ISSUE THREAD

**Issue by cedws** [DNSCrypt/dnscrypt-proxy#495]
Hi there.

I'm currently seeing a somewhat high CPU usage (a steady 5%) from `dnscrypt-proxy.exe` in Windows 10. It might be worth mentioning that my `blacklist.txt` contains 53995 entries totaling ~1MB.

**Comment by jedisct1** [comment]
If your computer doesn't do anything else at the same time, 5% CPU usage is nothing...

**Comment by cedws** [comment]
That's not the point. If it's not resolving any domains, there's no reason it should be consuming that much of the machine's resources - in fact, it should be completely idle.

**Comment by jedisct1** [comment]
If you can identify what is consuming CPU when it is idle, that would be great! Thanks for your help.

**Comment by cedws** [comment]
I checked the process today and it's idling at around 0.5% according to Task Manager. If I see it again behaving oddly again and diagnose the problem, I will let you know.
