### ISSUE TITLE
Option to use default DNS as fallback.

### ISSUE THREAD

**Issue by cedws** [DNSCrypt/dnscrypt-proxy#496]
I use `dnscrypt-proxy` on my laptop, and often switch between networks. I will often have to add a forwarding rule for specific domains so that I can resolve hostnames on that network.

This option would be a boolean which specifies whether the resolver should use the default assigned DNS if a domain cannot be resolved.

This would also resolve another issue I've been having, where I am locked out of Wi-Fi networks because I cannot access the captive portal with the specified resolver.

**Comment by jedisct1** [comment]
That would completely defeat the purpose of having secure DNS. An attacker can just blackhole encrypted responses and you would transparently fall back to unencrypted, unauthenticated DNS. That would be convenient, but completely insecure.

Temporarily switching to unauthenticated DNS should be handled by user interfaces. Users should know and explicitly allow when they disable authentication. They must confirm that they are indeed trying to pass a captive portal. That can't be safely done automatically.

**Comment by cedws** [comment]
I suppose you're right. Perhaps the fallback DNS can only be allowed to resolve domains within the same network. 

Having to add another forwarding rule for every network I join is incredibly inconvenient. I already know privacy comes at a cost, but I don't think there's any reason a more elegant/easy solution can't be implemented.

**Comment by jedisct1** [comment]
This requires strong interaction with an user interface. So, that would rather be a Simple DNSCrypt feature.

**Comment by cedws** [comment]
I don't see how this requires any user interface. I came across the term for what I'm requesting, I believe it's called split DNS. And, although you are right that an attacker could force DNSCrypt to use the fallback, this is unlikely to happen. From my understanding, DNSCrypt's goal is not to protect against attacks, but to prevent passive DNS spying.
