### ISSUE TITLE
Can't access webpage on internal network

### ISSUE THREAD

**Issue by dntndnm** [DNSCrypt/dnscrypt-proxy#498]
My employer's website has kind of an internal version that I can access by writing ':portnumber' after the usual web url in the browser (for example www.company.com:3456). This internal version has content that can only be accessed this way so it's important that employees (me, in this case) can access it.
I'm not sure, but I think that this internal version with the port number can only be accessed using the wifi in the building and not from any different or outside internet source.

When I use the normal built-in windows dns service I can access this website but when I use DNSCrypt I can't.

Thank you for this great software!

**Comment by jedisct1** [comment]
Use [forwarding](https://github.com/jedisct1/dnscrypt-proxy/wiki/Forwarding).
