### ISSUE TITLE
log and resolver path

### ISSUE THREAD

**Issue by elmakong** [DNSCrypt/dnscrypt-proxy#5]
it seems that windows client( i am using windows 10 x64) must use / as the path separator. also, it would be nice if the default path is the same as the executable(just like the toml file)
as for mine, i use `D:/Program Files/dnscrypt-proxy-win64-2.0.0beta2/win64/` as the path, and it works fine.

**Comment by KrasnayaPloshchad** [comment]
I used `file:///D:/dnscrypt-proxy-win64-2.0.0beta2/win64/` as well, but I agree with you that dnscrypt-proxy should accept such relative path.

**Comment by GrizzlyJr** [comment]
just insert log or resolver file without path. it will be place on the same folder as exe

**Comment by elmakong** [comment]
@GrizzlyJr i have tried without the absolute path and i cant find the log file. assuming the toml instruction is right, it should be an absolute path as seen on line 119(beta 2): `## Full path to the query log file`

**Comment by GrizzlyJr** [comment]
@elmakong Mine working perfectly, i just remove comment and space look like this `cache_file = "dnscrypt-resolvers.csv"` `log_file = "blocked.log"` `file = "query.log"`.

are you sure running as administrator?

**Comment by iWARR** [comment]
DNSCrypt-Proxy 2 v2.0.0 beta 2, Win8.1 [x64]

### ISSUE with absolute pathes (double-quotes)

There was no luck for me with service insallation until I changed all double quotes` " `in the absolute pathes to single` ' `. Then it worked.

_For example:_
`
forwarding_rules = 'C:\Program Files\DNSCrypt\forward\forwarding-rules.txt'`
`file = 'C:\Program Files\DNSCrypt\log\DNS.log'`
`blacklist_file = 'C:\Program Files\DNSCrypt\block\Blacklisted-Domains.txt'`
`log_file = 'C:\Program Files\DNSCrypt\log\Restricted.log'`
`cache_file = 'C:\Program Files\DNSCrypt\dnscrypt-resolvers.csv'`

But it may be a global problem with other entries also. Let author look at it.

_Note: This is **mine** handy folder structure with absolute pathes and filenames, not default!_

**Comment by jedisct1** [comment]
Thanks for reporting this.

Paths don't have to be absolute indeed. The comment is wrong and I'm going to fix it right away.
By default, everything will be loaded and saved from the same directory as the executable file. So, you have everything in one place, and you don't need to specify any path at all.

Regarding paths not working with double quotes, I think this is because a `\` character is handled as an escape character in a doubly quoted string. So you have to either use `\\`, or use single quotes.
The later is more natural, so I'm going to update the example configuration that way.

**Comment by jedisct1** [comment]
Sample configuration file updated. Thanks!

**Comment by iWARR** [comment]
**jedisct1**

> So, you have everything in one place, and you don't need to specify any path at all.

I'm understand, it's easyer for all. But I WANT have my own handy folder structure on my taste.

I'm happy to do something useful for you and all fans of your great software.
DNSCrypt-Proxy 2 is very young, but I can feel the speed improvement already at present stage.
And your comparison tab is very, very impessive!

I will write about other issues in a correspondent thread.
Keep going, my friend! Wish you all the best!

**Comment by jedisct1** [comment]
Thanks a lot, @iWARR! Glad you like it!

**Comment by elmakong** [comment]
i see the file path is now correct on beta 3. doesn't need an absolute path to file means the file is stored in the same directory as the executable. 
Thank you for the fix and fast update! Been a fan of the project since V1!

PS: this issue should be labeled as solved
