### ISSUE TITLE
Removing old (1.*) version - how to. A bit more specific?

### ISSUE THREAD

**Issue by blucap** [DNSCrypt/dnscrypt-proxy#503]
I would like to remove DNScrypt 1.6.1-1, and replace it with the latest (2.0.15). However, I am reading this from the git-site: "Do not upgrade from v1.x on Ubuntu Xenial. Instead first backup your systemd units (service and socket) then remove the old version and delete the systemd service file (keep the socket), then upgrade (replace artful with xenial in ppa sources.list). If you don't remove the old systemd unit service, the upgrade will not replace it and the new version will attempt to be started using the old systemd unit, which will fail."

As a non-technical person, how do I

1.  backup the systemd units (service and socket)
2. remove the old version
3. delete the systemd service file (keep the socket),
4. then upgrade (replace artful with xenial in ppa sources.list).

Re the 4th point, I assume this can be done via
```
sudo add-apt-repository ppa:shevchuk/dnscrypt-proxy && \
sudo apt update && \
sudo apt install dnscrypt-proxy
```
However, the first 3 points look cryptic to me. Could one clarify this on the wen-site?

**Comment by jedisct1** [comment]
I would just do `apt-get purge dnscrypt-proxy`, then install the PPA, or follow the generic instructions.
