### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cjjdaq** [DNSCrypt/dnscrypt-proxy#504]
openwrt x64

[2018-06-17 19:55:07] [NOTICE] dnscrypt-proxy is ready - live servers: 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7deb85]

goroutine 29 [running]:
main.(*Proxy).exchangeWithTCPServer(0xc42015a018, 0xc4201b4000, 0xc420088ec0, 0xc42023a0c0, 0xc0, 0xc0, 0xc420086fb0, 0xc, 0xc, 0xc0, ...)
	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:225 +0xf5
main.(*Proxy).processIncomingQuery(0xc42015a018, 0xc4201b4000, 0x8d6d41, 0x3, 0x8d6d41, 0x3, 0xc420234002, 0x1f, 0x1000, 0xc42017ae10, ...)
	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:295 +0xcbc
main.(*Proxy).tcpListener.func1(0xc420028030, 0xc42015a018)
	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:184 +0x242
created by main.(*Proxy).tcpListener
	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:171 +0xc8

**Comment by jedisct1** [comment]
That one was fixed a long time ago, so I guess you are running an old version.

Try to use the current stable version.

**Comment by cjjdaq** [comment]
@jedisct1  

I use the latest version. My own server, because udp always breaks, so I use udp2raw to map the remote udp port to 127.0.0.1 and the dnscrypt connection maps to the 127.0.0.1 port. There is no mapping for tcp. This error occurs when using dig+tcp locally. Is it possible to add a parameter that forces dnscrypt and server to use udp and ignore local tcp requests.

**Comment by jedisct1** [comment]
TCP is currently required for DNSCrypt, even though it is rarely used, and mostly only at the beginning.

Using UDP only is possible. When a query packet is too small, this would require retrying over UDP instead of TCP.

This is not implemented, though, since people frequently report the opposite, with TCP being more stable than UDP.

Can you implement this?

**Comment by cjjdaq** [comment]
I do not understand programming at all. Although tcp is more stable than udp, it increases latency. So I used udp2raw to masquerade udp as tcp mapped to the local. This allows you to continue using udp without delay. For tcp, I use haproxy to map to the local. . This error will not occur. . .

**Comment by jedisct1** [comment]
It won't noticeably increase latency. In DNSCrypt, TCP is only used for queries returning very large responses, and only the first time.

**Comment by cjjdaq** [comment]
Currently I have used haproxy+udp2raw to map tcp and udp locally to resolve this error.

**Comment by jedisct1** [comment]
Your setup looks very complicated and way out of my head.

Anyway, with a1c8012fc62c2a0998a96c298addfce896aa2329 the proxy should now ignore the error instead of crashing.

**Comment by cjjdaq** [comment]
THANKS
