### ISSUE TITLE
After reconnect of DSL uplink:  Too many connections (max=250)

### ISSUE THREAD

**Issue by bjo81** [DNSCrypt/dnscrypt-proxy#506]
Hi,
from time to time my DSL connection at home breaks down, after the reconnect dnscrypt-proxy logs too many connections (Too many connections (max=250)) for the next 10-15 minutes. Does the FritzBox which uses dnscrypt-proxy too many connections or what happens there?

Setup: a FritzBox for DSL and routing, uses 2 dnscrypt-proxy instances on 2 boxes in my LAN as primary/secondary resolver.

**Comment by jedisct1** [comment]
You can enable query logging to see what devices are sending these queries and what they are.

Web browsers tend to preload all the websites you frequently access after you regain network connectivity. This causes a storm of DNS requests.
