### ISSUE TITLE
The standard output not always available on Android

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#507]
### CORRECTLY:

```
log_level = 2
log_file = 'dnscrypt-proxy.log'
```
or
```
# log_level = 2
# log_file = 'dnscrypt-proxy.log'
```

### WRONG WAY:

```
log_level = 2
# log_file = 'dnscrypt-proxy.log'
```

### Background:

You have to Disable/Enable Logs together with supported parameters or this may hadly break the thigs: Network Wi-Fi connections (on Android) will be broken.

This little difference can make a BIG troubles for you. It's VERY HARD TO FIND WHERE THE PROBLEM IS on your device and why **dnscrypt-proxy** won't start at all !

I suppose that I'm kinda an experianced user, but this little thing accidentlally caused a big @ss pain (:

### Proposal:

Make all `log_file` or `file` parameters - as "General", special (supported) parameters - as "Secondary" (`log_level` , `format`). Better for PC (and other OS) also.

If "General" logging disabled for the sertain section, then other "Secondary" parameters should have no influence.

This should prevent **dnscrypt-proxy** from malfunction (at least on Android).

**Comment by jedisct1** [comment]
`2` is the default log level, so there are no differences between

`log_level=2`

and

`# log_level=2`

**Comment by iWARR** [comment]
You didn't understand. That because so hard to find this bug.

All relative parameters have to be commented all together, or not commented all together. That's OK.
If one is commented while other one is not, then **dnscrypt-proxy** stops working on Android.
See my example.

**Comment by iWARR** [comment]
### Further testing

The bug is more ugly then I thought. 
**Full disabling of the log file for the application is the MAIN cause.**
I.e. this breaks **dnscrypt-proxy** from working on Android:
```
# log_level = 2
# log_file = 'dnscrypt-proxy.log'
```
(I know, this is very-very strange! But it's fact and I have reproduced this many times).

So the only way to have **dnscrypt-proxy** working is **enabling log for the app**.
I have no any idea why. 

I must enable app `'dnscrypt-proxy.log'` and set `6` (only fatal errors) to keep log as small as possible in the future.
```
log_level = 6
log_file = 'dnscrypt-proxy.log'
```

**Comment by jedisct1** [comment]
Maybe because it can't print to screen (or whatever the standard output is). This depends on how you start it.

You can use `/dev/null` as the file name, or set `use_syslog = true` if that works on Android.

**Comment by iWARR** [comment]
The most strange thing that I want set NO OUTPUT, but I can't.
Turning OFF/ON logs for the rules seems OK, except APP output.
If I disabling an app output, then it won't work...

> This depends on how you start it.

Well, exactly for starting **dnscrypt-proxy** binary I'm using oldschool init.d. But this is only a small part of the opera. 

I'm using a complex method to get **dnscrypt-proxy** working. There is a lot of big and small nuances. But method is pretty simple, you just have to know exactly "how to" and "why" to do this or that.

It's reliable and it works on different phones/OS (MIUI & RR tested). Sadly, running **dnscrypt-proxy** stable "from the box" is impossble. I'm using 3-rd party app also to help run it in a predictable way. Because I know why all efforts of using custom IPTABLE commands will fail, early or later.

I'm understand sharing this experience in according thread #41 would help people a lot. Or creating a Wiki, may be... My methods is also around things has been already discussed in thread #41, but no one described the clear steps how to win this competition step by step.

Otherwise, first, would be nice to have a clear idea of present (suddenly appeared and very strange) issue.

> You can use `/dev/null` as the file name

Sorry, I don't know what is it at all...

> `use_syslog = true`

I know this works on Windows, but only with log file-output disabled. I can't imagine if this can work on Android. Even if it can (doubting), then where to find a log, output or smth... And I'm satisfied with log files if I want them.
