### ISSUE TITLE
Empty `ct` parameter in DoH GET queries incompatible with Cloudflare

### ISSUE THREAD

**Issue by dwimmer** [DNSCrypt/dnscrypt-proxy#509]
Cloudflare doesn't like the empty "ct" param in the GET request. Was there a reason behind including this?
https://github.com/jedisct1/dnscrypt-proxy/blob/e0f2391c0d81bc70990868d13a83322afd4a21ec/dnscrypt-proxy/xtransport.go#L269

I think this may also be what was causing issues in #470 but since it only shows up if the POST request fails it wasn't obvious.

**Comment by jedisct1** [comment]
Until draft 5, the DoH specification said:

```
When using the GET method the URI path MUST contain a query parameter
   name-value pair [QUERYPARAMETER] with the name of "ct" and a value
   indicating the media-format used for the dns parameter.  The value
   may either be an explicit media type (e.g. ct=application/dns-
   udpwireformat&dns=...) or it may be empty.  An empty value indicates
   the default application/dns-udpwireformat type (e.g. ct&dns=...).
```

An empty value was preferred over `application/dns-udpwireformat`, since the MIME type was subject to change, and actually changed later.

So, that was to maximize compatibility with older servers.

Recent drafts dropped that parameter in favor of a header.

We can drop the `ct` parameter, but as early drafts said that it `MUST` be present, this will break compatibility with these.

This may still be the best thing to do, after checking that at least the public DoH servers we know of still work without `ct`.

**Comment by dwimmer** [comment]
Cloudflare seems to allow both ct=application/dns-message and ct=application/dns-udpwireformat, so we could maybe use one of those instead of empty to maintain backwards compatibility if necessary.

**Comment by jedisct1** [comment]
The absence of `ct` breaks Google :(

**Comment by dwimmer** [comment]
AH! Actually it allows empty ct as well, but it must be actually empty instead of an empty string. It looks like if we just change it to match the spec reference "ct&dns=..." we should be ok.

**Comment by jedisct1** [comment]
Google refuses `application/dns-message`, accepts `application/dns-udpwireformat`, but they may eventually change this.

**Comment by jedisct1** [comment]
So, Cloudflare accepts `ct` but not `ct=`? Weird.

Maybe this is something that can be fixed on their end.

**Comment by jedisct1** [comment]
Ping'ed friends at Cloudflare :)

**Comment by dwimmer** [comment]
It seems that way yes. I'm guessing that it's the difference between null and "" on their end. Given that the spec quotes `ct&dns=...` it might be better for us to use that either way. Does Google work with that?

**Comment by jedisct1** [comment]
Cloudflare is going to add support for `ct=`.

**Comment by jedisct1** [comment]
When using the standard library to build URLs, Go always adds the `=` [even for empty values](https://github.com/golang/go/issues/20820). I guess that's also the case with many other languages and HTTP libraries.

So, servers should really not make a distinction between both.

Anyway, Cloudflare is going to support this (thanks to them!) and I'll drop the `ct` parameter completely once Google updates their implementations. Or, worse case scenario, add probing.

Thanks a lot for reporting this!

**Comment by jedisct1** [comment]
"(It will go out in ~2 days unless it's causing problems)"

**Comment by dwimmer** [comment]
Sounds great. Thanks for handling the upstreaming. (It's not really an issue for me, just something I noticed while testing #505 when I had my timeout set too low. It shouldn't really affect most people since POST should succeed.)
