### ISSUE TITLE
Service ISSUES - beta 11

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#51]
1) When I launch any `*.bat` command, firstly I've got the message (translated to English):

`There are no items in the list.`

Below I see usual [NOTICE] messages as expected, without errors.

2) I don't have `dnscrypt-proxy.exe` in the "Task Manager" as background process in Windows any more. At the same time, dnscrypt-proxy has been really installed and existing as Service - `DNSCrypt client proxy`.

So, beta 11 doesn't work for me (no connection, no resolve).
I don't have errors, except `There are no items in the list.`
According to the launch messages, service was normally installed and started.
Strange...

P.S. I reconfigured *.toml to have running [static] public servers of my choice, not google (as purposed).

**Comment by jedisct1** [comment]
What is the exact message in your language, so I can google for it and find where it comes from?

**Comment by iWARR** [comment]
### I'm really sorry! It was my fault.

I've forgot put blocking rules file. Now everithing is OK.
Path from the *.toml was not found and I've got the message: `There are no items in the list.`

------------------------

But here we've found unwanted dangerous scenario that may occure.

If user one time will forgot put the file with some rules (for example, blocking *.txt rules) in the corresponding path, the dnscrypt-proxy service may not start. If it possible, it's better avoid such scenario.
I think, the service must start in any case, regardless of missed rules.
(Actually, it starts, but not exist in the Windows processes - Task Manager, so it stuck)

Or make more clear scenario:

```
[CRITICAL] Unable find source. File ... .txt was not found.
[FATAL] No servers configured.
```

Please, accept my apologies... Shame on me...
