### ISSUE TITLE
log_file option in dnscrypt-proxy.toml for service starting

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#510]
After edited dnscrypt-proxy.toml 
log_file = '/var/log/dnscrypt-proxy.log'

Then restart 
$ sudo dnscrypt-proxy -service restart (stop/start)

Still cannot see any log file
/var/log/dnscrypt-proxy.log

Did not see any instruction in setup section

Is that caused by root permission?
$ ps auwx|grep dnsc
root      4928  0.1  1.1  18808 10440 ?        Ssl  15:30   0:01 /opt/dnscrypt-proxy/dnscrypt-proxy

**Comment by jedisct1** [comment]
Is `use_syslog` set to `true`?

**Comment by ghost** [comment]
I forgot (or not be reminded by installation guide) to 
$sudo chown -R root.root /opt/dnscrypt-proxy
after change ownership of everything, it works now
