### ISSUE TITLE
How to set up a whitelist for forwarding rules

### ISSUE THREAD

**Issue by cjjdaq** [DNSCrypt/dnscrypt-proxy#512]
There are too many entries in the forwarding rules (such as accelerated-domains.china.conf), and forwarding rules are automatically updated on a regular basis. How do I ignore a domain name in a forwarding rule through another list of lists?
In addition:
Does the rules file allow multiple files to be loaded? For example: forwarding_rules = 'forwarding-rules.txt,own-rules.txt'
The forwarding-rules.txt file is automatically updated through the shell, and own-rules.txt is maintained manually by myself or manually through openwrt's web.

**Comment by jedisct1** [comment]
Only one file can be loaded, but you can construct that file by concatenating multiple files before running the server.

There are no whitelists for forwarding rules. Can you implement this?

**Comment by cjjdaq** [comment]
I don't understand golang at all, so I can't do anything about it. But I think these two functions are still very useful.

Hope to be able to add multi-rule file loading, with a white list for forwarding rules, which makes it much easier to use dnscrypt in openwrt
http://i63.tinypic.com/2wfodah.png
