### ISSUE TITLE
proxy log not created/used on windows, v2.0.15

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#513]
using the log_file option in .toml file

log_file = 'C:\\Program Files\\bitbeans\\Simple DNSCrypt x64\\dnscrypt-proxy\\proxy.log'

or only 

log_file = 'proxy.log'

does not work, even when i create the file manually it is not filled.

snip -----
listen_addresses = ["0.0.0.0:53"]
max_clients = 250
dnscrypt_servers = true
doh_servers = true
daemonize = false
timeout = 2500
log_level = 1
use_syslog = true
cert_refresh_delay = 240
fallback_resolver = "9.9.9.9:53"
ignore_system_dns = false
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 2
cache_size = 1024
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60

cloaking_rules = 'cloaking-rules.txt'

**Comment by jedisct1** [comment]
Read the configuration you just posted line by line.

Or, as usual, start with the default configuration and only modify one thing at a time.

Do not set arbitrary properties if you don't understand what they do.

You will find why logs don't go to the log file :)

**Comment by scubasunny** [comment]
Hi,
ok found it, have to set use_syslog to false.
But this was **not** clearly stated in the example file and in the Wiki nothing said about this!
And i think it's not by nature that using syslog is preventing to send other information to any other logfile.

Maybe you can just add a line to the example file telling that use_syslog = true will disable the "normal" logfile usage.

Regards
