### ISSUE TITLE
How to decode 2.dnscrypt-cert TXT record?

### ISSUE THREAD

**Issue by nopoz** [DNSCrypt/dnscrypt-proxy#515]
How can I decode the TXT record in a 2.dnscrypt-cert .[domain] query? I would like to retrieve the public key, but I can't figure out what the formatting is. 

For example:

```
$ dig +short txt 2.dnscrypt-cert.opendns.com
"DNSC\000\001\000\000;\200\196\196\240\012\002\219\217\012\192\172/\223\024\240on\171\012\209\140d\128\189\211B\1962D{\1294j\006lg}\020\178\019a\210@\180*a\004\162^\167\165\149:d\211\157\025\228)\183\1400\007$\011\017\183\173\002\250\192b\133\030\136n\170D\231\174[\173/\146\031\149wQM\226&\213Rh6qNzimeuUZy\250\165Zy\250\165\\[.%"
```

**Comment by jedisct1** [comment]
The certificates format is documented in the [DNSCrypt specification](https://dnscrypt.info/protocol).

**Comment by nopoz** [comment]
I've read that, but it specifies the formatting of the record. I'm not understanding how that format gets encoded into the above example and how to decode it back into the format specified in your link. What am I missing here?

**Comment by jedisct1** [comment]
There is no extra encoding. TXT records are binary data.

The `"DNSC\000\001\000\000;\...` strings you see is just the way the `dig` command tries to print that data in a human-readable way. But if you use any DNS library to send that query, you will get the actual data, not a string.
