### ISSUE TITLE
forwarding-rules no work?

### ISSUE THREAD

**Issue by SergeyDjam** [DNSCrypt/dnscrypt-proxy#518]
add my domain in forwarding-rules.txt
myhome.domain 192.168.1.1
myhome.local 192.168.2.1
be.libre 192.168.3.1

dnscrypt-proxy --resolve myhome.domain
Resolving [myhome.domain]

Domain exists:  yes, 2 name servers found
Canonical name: -
IP addresses:   -
TXT records:    -
Resolver IP:    77.88.56.68

dnscrypt-proxy --resolve myhome.local
Resolving [myhome.local]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -
Resolver IP:    77.88.56.68

dnscrypt-proxy --resolve be.libre
Resolving [be.libre]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -
Resolver IP:    77.88.56.68

what fix it?

**Comment by SergeyDjam** [comment]
dig be.libre @192.168.3.1

; <<>> DiG 9.10.7 <<>> be.libre @192.168.3.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25291
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 13, ADDITIONAL: 27

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;be.libre.                      IN      A

;; ANSWER SECTION:
be.libre.               30      IN      A       161.97.219.84

;; AUTHORITY SECTION:
.                       155265  IN      NS      e.root-servers.net.
.                       155265  IN      NS      j.root-servers.net.
.                       155265  IN      NS      k.root-servers.net.
.                       155265  IN      NS      m.root-servers.net.
.                       155265  IN      NS      d.root-servers.net.
.                       155265  IN      NS      l.root-servers.net.
.                       155265  IN      NS      b.root-servers.net.
.                       155265  IN      NS      c.root-servers.net.
.                       155265  IN      NS      i.root-servers.net.
.                       155265  IN      NS      h.root-servers.net.
.                       155265  IN      NS      g.root-servers.net.
.                       155265  IN      NS      a.root-servers.net.
.                       155265  IN      NS      f.root-servers.net.

;; ADDITIONAL SECTION:
a.root-servers.net.     155265  IN      A       198.41.0.4
a.root-servers.net.     155265  IN      AAAA    2001:503:ba3e::2:30
b.root-servers.net.     155265  IN      A       199.9.14.201
b.root-servers.net.     155265  IN      AAAA    2001:500:200::b
c.root-servers.net.     155265  IN      A       192.33.4.12
c.root-servers.net.     155265  IN      AAAA    2001:500:2::c
d.root-servers.net.     155265  IN      A       199.7.91.13
d.root-servers.net.     155265  IN      AAAA    2001:500:2d::d
e.root-servers.net.     155265  IN      A       192.203.230.10
e.root-servers.net.     155265  IN      AAAA    2001:500:a8::e
f.root-servers.net.     155265  IN      A       192.5.5.241
f.root-servers.net.     155265  IN      AAAA    2001:500:2f::f
g.root-servers.net.     155265  IN      A       192.112.36.4
g.root-servers.net.     155265  IN      AAAA    2001:500:12::d0d
h.root-servers.net.     155265  IN      A       198.97.190.53
h.root-servers.net.     155265  IN      AAAA    2001:500:1::53
i.root-servers.net.     155265  IN      A       192.36.148.17
i.root-servers.net.     155265  IN      AAAA    2001:7fe::53
j.root-servers.net.     155265  IN      A       192.58.128.30
j.root-servers.net.     155265  IN      AAAA    2001:503:c27::2:30
k.root-servers.net.     155265  IN      A       193.0.14.129
k.root-servers.net.     155265  IN      AAAA    2001:7fd::1
l.root-servers.net.     155265  IN      A       199.7.83.42
l.root-servers.net.     155265  IN      AAAA    2001:500:9f::42
m.root-servers.net.     155265  IN      A       202.12.27.33
m.root-servers.net.     155265  IN      AAAA    2001:dc3::35

;; Query time: 235 msec
;; SERVER: 192.168.3.1#53(192.168.3.1)
;; WHEN: Thu Jun 21 16:13:28 MSK 2018
;; MSG SIZE  rcvd: 836

**Comment by jedisct1** [comment]
`dnscrypt-proxy --resolve` cannot show the resolver you are using for a specific name.

**Comment by s-s** [comment]
dnscrypt-proxy --resolve uses local resolver, so you have to run dnscrypt-proxy instance and setup your system first.

**Comment by SergeyDjam** [comment]
@jedisct1 ok,

nslookup ya.ru
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   ya.ru
Address: 87.250.250.242

nslookup be.libre
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find be.libre: NXDOMAIN

nslookup myhome.domain
Server:         127.0.0.1
Address:        127.0.0.1#53

*** Can't find aqline.lan: No answer

thus the forvarding of zones doesn't work

**Comment by SergeyDjam** [comment]
so the program shouldn't work. Why at settings there is a forwarding-rules point?
