### ISSUE TITLE
How to set up logging? (Ubuntu 18)

### ISSUE THREAD

**Issue by oneletter1** [DNSCrypt/dnscrypt-proxy#519]
I've got logging in the main syslog but I want to move it to a dedicated log file.

In  /etc/dnscrypt-proxy/dnscrypt-proxy.toml:

```
## Log level (0-6, default: 2 - 0 is very verbose, 6 only contains fatal errors)
log_level = 2
## log file for the application
log_file = '/etc/dnscrypt-proxy/dnscrypt-proxy.log'
## Use the system logger (syslog on Unix, Event Log on Windows)
use_syslog = false
```

Then I created  the log file and chown the directory (see https://github.com/jedisct1/dnscrypt-proxy/issues/510)

```
touch /etc/dnscrypt-proxy/dnscrypt-proxy.log
chown -R root.root /etc/dnscrypt-proxy/
systemctl restart dnscrypt-proxy.service
```

however the file is not updated (shows 0 bytes)

```
root@ubuntu /etc/dnscrypt-proxy # ls -la
total 36
drwxrwxrwx   2 root root  4096 Jun 21 14:43 .
drwxr-xr-x 108 root root  4096 Jun 21 13:40 ..
-rwxrwxrwx   1 root root     0 Jun 21 13:39 dnscrypt-proxy.log
```

Prior to this I also tried without the log file creation stage and no log file was created.

I also was thinking it could be related to permissions.

```
root@ubuntu-2gb-nbg1-2 /etc/dnscrypt-proxy # ps aux | grep dns
dnscryp+ 20172  0.3  0.8 468652 16792 ?        Ssl  14:47   0:00 /usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
```

Shows dnscrypt-proxy running as the user **dnscryp+**

Which is confusing since in `/etc/passwd` there is no mention of any user **dnscrypt** or any similar permutations.  And I'm sure the first column in **ps aux** lists the user that owns the running process.

I've got some other issues also which i'll put in a second post.

thanks guys for helping me :)

**Comment by jedisct1** [comment]
Pretty sure systemd is preventing you from writing logs to that directory.

Uninstall everything, and follow the normal procedure. Download the binary file, uncompress it wherever you want, and type `./dnscrypt-proxy -service install`.

**Comment by admzzz** [comment]
oneletter1,
jfyi: logs should be written to /var/log/* ;-)

jedisct1,
you did not answer clearly on my idea (or feature request, if you want) of dropping privileges after successful start of dnscrypt-proxy (linux's version).

**Comment by ThomasCr** [comment]
also have the same problem with the package from PPA and Ubuntu 18.04.

And the package or systemd creates the following:
```
# ls -lah /var/log/dnscrypt-proxy
lrwxrwxrwx 1 root root 22 Jun 22 21:37 /var/log/dnscrypt-proxy -> private/dnscrypt-proxy
```
but folder stays empty:
```
# ls -lah /var/log/dnscrypt-proxy/
total 8,0K
drwxr-xr-x 2 dnscrypt-proxy dnscrypt-proxy 4,0K Jun 22 21:37 .
drwx------ 3 root           root           4,0K Jun 22 21:37 ..

```

**Comment by ThomasCr** [comment]
Ok, we need to set the full path, like this:
`log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'`
I was expecting, that the correct logpath is compiled in, so that the file name is enough.
