### ISSUE TITLE
Dnscrypt not resolving name queries

### ISSUE THREAD

**Issue by vikashiiitdm** [DNSCrypt/dnscrypt-proxy#521]
Hi, 
i have installed dnscrypt-proxy on my kde-neon system. i have created and modified a dnscrypt-proxy.toml in /etc/dnscrypt-proxy/ to use cloudflare DNS. when i run` dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml` it runs fine producing output 

[2018-06-22 21:02:47] [NOTICE] Source [public-resolvers.md] loaded
[2018-06-22 21:02:47] [NOTICE] dnscrypt-proxy 2.0.15
[2018-06-22 21:02:50] [NOTICE] [cloudflare] OK (DoH) - rtt: 582ms
[2018-06-22 21:02:50] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 582ms)
[2018-06-22 21:02:50] [NOTICE] dnscrypt-proxy is ready - live servers: 1

Now, in the next step when i set DNS server to 127.0.0.1 in my network-connections, it stops resolving name queries. I am unable to understand what is happening. 

`sudo ss -lp 'sport = :domain'` outputs this : 

Netid State      Recv-Q Send-Q                            Local Address:Port                                             Peer Address:Port                

udp   UNCONN     0      0                                     127.0.2.1:domain                                                      *:*                     users:(("systemd",pid=1,fd=92))
udp   UNCONN     0      0                                     127.0.1.1:domain                                                      *:*                     users:(("dnsmasq",pid=2026,fd=4))
tcp   LISTEN     0      128                                   127.0.2.1:domain                                                      *:*                     users:(("dnscrypt-proxy",pid=4113,fd=5),("systemd",pid=1,fd=90))
tcp   LISTEN     0      5                                     127.0.1.1:domain                                                      *:*                     users:(("dnsmasq",pid=2026,fd=5))

**Comment by jedisct1** [comment]
I'm not sure I follow. You are talking about `dnscrypt-proxy`, but your log file is about another software called `cloudflared`.

Did you follow the [installation guide](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux) ?

**Comment by vikashiiitdm** [comment]
i am so sorry, i accidently copied the output of another daemon i was trying. I have updated it with the correct logs.

I couldn't follow the installation guide since it said that there shouldn't be anything listening on port 53, but i definitely have some programs listening and i don't suppose i should remove them.

**Comment by jedisct1** [comment]
So, you should configure `dnscrypt-proxy` to listen to another port, for example:

```toml
listen_addresses = ['127.0.0.1:5353']
```

And then configure `dnsmasq` to forward everything to `127.0.0.1`, port `5353`.

**Comment by vikashiiitdm** [comment]
I tried what you have suggested; i changed the forwarding address of dnsmasq to 127.0.0.1:5354 (since 5353 was already being used by chrome and it returned a fatal error of `bind address already in use`.  I also modified the .toml file accordingly, it still does not seem to work. 

[2018-06-22 22:27:06] [NOTICE] Source [public-resolvers.md] loaded
[2018-06-22 22:27:06] [NOTICE] dnscrypt-proxy 2.0.15
[2018-06-22 22:27:06] [NOTICE] Now listening to 127.0.0.1:5354 [UDP]
[2018-06-22 22:27:06] [NOTICE] Now listening to 127.0.0.1:5354 [TCP]
[2018-06-22 22:27:08] [NOTICE] [cloudflare] OK (DoH) - rtt: 201ms
[2018-06-22 22:27:08] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 201ms)
[2018-06-22 22:27:08] [NOTICE] dnscrypt-proxy is ready - live servers: 1

doing  `dnscrypt-proxy -resolve google.com` returns 
Resolving [google.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -

**Comment by ThomasCr** [comment]
I am having the same problem (but not because a other running dns server), I get no answer from dnscrypt-proxy.
Maybe I have something not understand well?!
I NEED dnsmasq as resolver between **OR** can I point my client pc to my internal lan server which is running only dnscrypt-proxy?

dnscrypt-proxy also works, but my client pc (or also local) can't query with nslookup/host command the dns server.

I also modified my dnscrypt-proxy.socket:
```
# systemctl status dnscrypt-proxy.socket
● dnscrypt-proxy.socket - DNSCrypt-proxy socket
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy.socket; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/dnscrypt-proxy.socket.d
           └─override.conf
   Active: active (running) since Fri 2018-06-22 22:30:20 CEST; 11min ago
     Docs: https://github.com/jedisct1/dnscrypt-proxy/wiki
   Listen: 127.0.2.1:53 (Stream)
           127.0.2.1:53 (Datagram)
           192.168.99.200:53 (Stream)
           192.168.99.200:53 (Datagram)
           [::]:53 (Stream)
           [::]:53 (Datagram)
    Tasks: 0 (limit: 4230)
   CGroup: /system.slice/dnscrypt-proxy.socket

Jun 22 22:30:20 zentrale systemd[1]: dnscrypt-proxy.socket: TCP_DEFER_ACCEPT failed: Protocol not available
Jun 22 22:30:20 zentrale systemd[1]: dnscrypt-proxy.socket: TCP_NODELAY failed: Protocol not available
Jun 22 22:30:20 zentrale systemd[1]: Listening on DNSCrypt-proxy socket.

# cat /etc/systemd/system/dnscrypt-proxy.socket.d/override.conf
[Socket]
BindIPv6Only=ipv6-only
ListenStream=192.168.99.200:53
ListenDatagram=192.168.99.200:53
ListenStream=[::]:53
ListenDatagram=[::]:53

# ss -lp 'sport = :domain'
Netid           State             Recv-Q            Send-Q                           Local Address:Port                           Peer Address:Port
udp             UNCONN            2304              0                               192.168.99.200:domain                              0.0.0.0:*                users:(("systemd",pid=1,fd=45))
udp             UNCONN            1536              0                                    127.0.2.1:domain                              0.0.0.0:*                users:(("systemd",pid=1,fd=43))
udp             UNCONN            33792             0                                127.0.0.53%lo:domain                              0.0.0.0:*                users:(("systemd-resolve",pid=1023,fd=12))
udp             UNCONN            0                 0                                         [::]:domain                                 [::]:*                users:(("systemd",pid=1,fd=50))
tcp             LISTEN            0                 128                             192.168.99.200:domain                              0.0.0.0:*                users:(("dnscrypt-proxy",pid=4386,fd=3),("systemd",pid=1,fd=44))
tcp             LISTEN            0                 128                                  127.0.2.1:domain                              0.0.0.0:*                users:(("dnscrypt-proxy",pid=4386,fd=11),("systemd",pid=1,fd=42))
tcp             LISTEN            0                 128                              127.0.0.53%lo:domain                              0.0.0.0:*                users:(("systemd-resolve",pid=1023,fd=13))
tcp             LISTEN            0                 128                                       [::]:domain                                 [::]:*                users:(("dnscrypt-proxy",pid=4386,fd=5),("systemd",pid=1,fd=49))

# host google.com 127.0.2.1
;; connection timed out; no servers could be reached
```

**Comment by pepoluan** [comment]
I experienced the same; for some reasons letting systemd handle the socket causes a lot of grievance for me.

What worked for me finally:

1. Delete the `dnscrypt-proxy.socket` symlink from `/etc/systemd`
2. Ensure that _that_ file is no longer referenced in the `dnscrypt-proxy.service` file
3. Configure `dnscrypt-proxy.toml` to listen on `127.0.0.53:53`
3. Remove _all_ vestiges of `dnsmasq` and `unbound`
4. Enable & start the dnscrypt-proxy service using `systemctl`

(I also configured NetworkManager [I think that's the component] to _not_ handle resolv.conf, and manually hardcoded it to 127.0.0.53.)

I'm using Ubuntu 17.10 by the way.

**Comment by jedisct1** [comment]
If only that was documented in the wiki...

**Comment by johnavp1989** [comment]
@jedisct1 Where is this issue covered in the wiki? The wiki say UDP should work despite the warnings but only tcp was working for me when systemd was handling the socket.

**Comment by ghost** [comment]
@johnavp1989 you probably hit https://github.com/jedisct1/dnscrypt-proxy/issues/480 . The 2.0.15 has broken systemd sockets.
