### ISSUE TITLE
ER: Send dummy queries to keep connections alive

### ISSUE THREAD

**Issue by kontaxis** [DNSCrypt/dnscrypt-proxy#522]
Issue: Middleboxes (firewalls, etc.) might start silently dropping data for a TCP connection that has been idle for too long.
For dnscrypt-proxy this means DNS resolution will initially work (new connection) and, after a period during which there are no DNS resolutions, future resolutions will time out.

Proposed mitigation: dnscrypt-proxy should have a connection_keepalive interval (proposed: 30 seconds) at which it should try to resolve a dummy query (e.g., example.com) so that traffic is generated thereby keeping the connection active and alive.

More details: Linux will send TCP keepalive messages (TCP length zero, ACK flag set) when the SO_KEEPALIVE option is set on a socket. I tested dnscrypt-proxy and it appears TCP keepalive messages are in fact used when connecting to upstream resolvers. (Every ~30 seconds it seems)

However, when using a socks proxy, such as when sending DoH traffic over Tor, there is a TCP connection between dnscrypt-proxy and the Tor SOCKS proxy and another TCP Connection between the SOCKS proxy and the DoH resolver. (over Tor) The Tor SOCKS proxy does not set the SO_KEEPALIVE socket option and thus does not send TCP keepalive messages to the DoH resolver. But this is not a Tor-specific issue as users might employ different SOCKS proxies that do the same.

The result of not using TCP keepalive messages is TCP connections that stall. I.e., they remain in the ESTABLISHED state and the application can still send data (write() returns no error) but any data sent might be silently dropped by a middlebox that hasn't seen traffic for a while and stopped tracking the connection as established.
For DNS this means resolutions will fail by timing out.

P.S.: The existing keepalive option (which maps to IdleConnTimeout in the Go http package) is a bit misleading. All it does is set the HTTP "Connection: keep-alive" header so that the HTTP server (DoH resolver) does not immediately close the connection following an HTTP (DNS) request. So neither side closes the connection but doesn't do anything to prevent it from being silent for a long time.

P.S.2: Right now a mitigation to this issue is to have the existing keepalive option be the default (30 seconds) or less than that. However this hurts latency because the connection keeps closing too fast. Ideally dnscrypt-proxy maintains a long-lived connection to the resolver. (I'd say at least a few minutes or more)

**Comment by jedisct1** [comment]
You know far more than I do about all these things, so a pull request would be more than welcome.

Note that DNSCrypt requires a new TCP connection for each query to mitigate fingerprinting.

**Comment by jedisct1** [comment]
Thanks for your help!
