### ISSUE TITLE
DNSCrypt-Proxy 2 logo in SVG

### ISSUE THREAD

**Issue by lukateras** [DNSCrypt/dnscrypt-proxy#523]
I'd like to know if https://github.com/jedisct1/dnscrypt-proxy/blob/master/logo.png is available in some vector format.

**Comment by jedisct1** [comment]
It is!

I just added it here: https://github.com/jedisct1/dnscrypt-proxy/blob/5e3c58f9e01745e414f359e0bd0c3c655c06344c/logo.svg

**Comment by lukateras** [comment]
Thanks! Although, that seems to be raster layers embedded in SVG, i.e. not vector.
