### ISSUE TITLE
howto unbound on local debian server

### ISSUE THREAD

**Issue by ibksturm** [DNSCrypt/dnscrypt-proxy#525]
hi frank :)

i wrote a little howto to configure unbound include dnscrypt proxy on debian 9, running on bananpi (or raspberry pi or something similar with debian 9)

https://github.com/ibksturm/dnscrypt-switzerland

perhabs you could link to it

**Comment by molybden123** [comment]
Ill look at it tomorrow

**Comment by jedisct1** [comment]
This is great!

But how are you rotating keys?

**Comment by ibksturm** [comment]
hi frank

look https://github.com/ibksturm/dnscrypt-switzerland/issues/1

i wrote a little cron.daily job...  but as sebastian wrote, maybe i habe to change it to hourly i look this weekend

**Comment by jedisct1** [comment]
I'd be glad to add a link but I don't know where :)

**Comment by ibksturm** [comment]
bon soir frank

peut d'etre ici.... here https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes. je pense tu toi ouvrir une nouveau chapitre pour installe une outre server...

uuuu sorry, in english for all other people, i'm sorry, working today with a lot of west-swiss people

maybe here https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes, maybe you could open a new chapter "how to install dnscrypt + unbound on debian 9"

**Comment by Yinchie** [comment]
It isn't a good HowTo imo.
I was thinking to make an actual how to, from download to compile, install and configure and get it compatible with PiHole.
Because that is how I have done it (running live at dnscrypt.nl) and not using the dnscrypt built-in feature of Unbound.

**Comment by ibksturm** [comment]
hi @Yinchie 

could you explane why it is'nt a good how to? so that i could learn something new :)

b) in https://github.com/ibksturm/dnscrypt-switzerland/blob/master/Unbound/HowTo i documented allready how to download and compile it ;) 

why you are using pi-hole?
