### ISSUE TITLE
A bug found while connect doh via dnscrypt-proxy

### ISSUE THREAD

**Issue by zoonderkins** [DNSCrypt/dnscrypt-proxy#526]
Doh-server: https://github.com/m13253/dns-over-https/commit/523b6120b9a573237e3ab6d1e71515915ea5837a
Bug: https://github.com/m13253/dns-over-https/issues/14

**Comment by m13253** [comment]
DNSCrypt-Proxy is probing a DNS-over-HTTPS server by sending a request with Transaction ID = 0xcafe.

When the server replies with a packet with Transaction ID = 0, DNSCrypt-Proxy rejects the server by saying "Webserver returned an unexpected response".

According to the draft (version 11), this is a violation of the protocol:
> In order to maximize cache friendliness, DoH clients using media formats that include DNS ID, such as application/dns-message, SHOULD use a DNS ID of 0 in every DNS request. HTTP correlates the request and response, thus eliminating the need for the ID in a media type such as application/dns-message. The use of a varying DNS ID can cause semantically equivalent DNS queries to be cached separately.

I patched the bug by crafting a special response to bypass the check (commit https://github.com/m13253/dns-over-https/commit/523b6120b9a573237e3ab6d1e71515915ea5837a). But I would like to see the problem fixed here in upstream.

**Comment by jedisct1** [comment]
`SHOULD`.

**Comment by m13253** [comment]
There is no problem for the client to send 0xcafe, because it is a `SHOULD`.

But the client should also expect a response that does not have 0xcafe, because the server does not have to reply in the same ID. -- I mean, my server always replies with ID=0, regardless of the ID client sents. I think this is an acceptable behavior.

Anyway, I will construct the special response whenever I detect a DNSCrypt-Proxy client to bypass the check.

P.S.: I have removed the offensive words and left a comment there in the code. And sorry about that.

**Comment by jedisct1** [comment]
An nice property of DoH is that it just encapsulates DNS queries and responses. The inner protocol remains unmodified DNS. Allowing peers to reply with arbitrary query IDs would be completely at odd with that.

Recommending that clients send a fixed query ID can improve caching with HTTP proxies that don't know about DoH, but it shouldn't impact the inner protocol. These are different layers. All existing DoH servers and proxies respect this. Cloudflare briefly didn't, but that was fixed a couple hours later.

dnscrypt-proxy uses query id `0` for all queries, except at startup, as a way to check that it's actually talking to a DoH server.

**Comment by m13253** [comment]
> dnscrypt-proxy uses query id 0 for all queries, except at startup, as a way to check that it's actually talking to a DoH server.

That's okay. If it does not affect the functionality, I will keep the code as is.

The reason I reply with ID=0 is that, I found it difficult to keep the original request ID in my implementation (because I built an abstract layer between Google DoH and IETF DoH).
