### ISSUE TITLE
Blacklist block makes the PC fallback to the secondary DNS

### ISSUE THREAD

**Issue by alpe12** [DNSCrypt/dnscrypt-proxy#53]
The way the blacklist works now, it makes the client fallback to the secondary DNS.
Instead of blocking, all queries to blacklisted hosts should be answered to a blackhole ip, like 0.0.0.0, or maybe 127.0.0.1 or an user-configured ip.
This way, these queries would actually be blocked, since the client received an answer it can use.
Whois ads.adsite.com? 0.0.0.0! :)

Edit: Ok, I'll keep using dnsmasq for that.

**Comment by jedisct1** [comment]
Don't use a "secondary DNS" if you don't expect queries to leak through it! I'm not even sure that entries are defined resolvers are guaranteed to be tried sequentially.

DNS has many more types than `A` (IPv4 address), and you want to block them all. There is a dedicated standard return code for this (`REFUSED`) and this is what dnscrypt-proxy uses.

Returning `0.0.0.0` or `127.0.0.1` is a terrible idea if you run servers as it will connect to the local machine.

**Comment by ibksturm** [comment]
aaah ok good input thanks
