### ISSUE TITLE
Unable to detect and adjust for network connection change

### ISSUE THREAD

**Issue by putztzu** [DNSCrypt/dnscrypt-proxy#530]
Have been extremely happy with delivered functionality when in a same site connecting to a single network connection.

Have found though,
When deployed on a laptop moving from one wireless network to another, Win10 networking is able to automatically detect new wireless network connection and automatically connect but DNScrypt-proxy is unable to also adjust accordingly, connectivity to remote DNS is broken. Restarting the DNScrypt-proxy service also does not work, seems unable to use the new wireless network connection. Configured fallback in config to 9.9.9.9 does not work, likely confirming the problem likely is the wireless network connection connectivity problem and not a networking configuration problem like bad DNS.

In the meantime, I have disabled DNScrypt-proxy when moving between wireless networks (by resetting the IPv4 adapter property to DHCP client, removing 127.0.0.1)

Problem should be easy to replicate based on my description...

**Comment by jedisct1** [comment]
Is that when using DNSCrypt servers or DoH?

**Comment by putztzu** [comment]
When DNScrypt is running, is using DNS that can be found using standard
startup.

**Comment by uniquenode** [comment]
@jedisct1 with DNS-over-HTTPS

**Comment by jedisct1** [comment]
So, it doesn't happen with DNSCrypt?

**Comment by putztzu** [comment]
Hi,
I guess I'm not entirely clear about the question.
When DNScrypt-proxy is running, it works for the existing wireless network
connection, but won't if I connect to a different WiFi connection. Nothing
I try including restarting the DNScrypt-proxy service can get name
resolution working.
To resolve, I have to change network properties to point directly to DNS
servers instead of the DNScrypt-proxy service (127.0.0.1).
I don't know if DNScrypt is configured to connect to different types of DNS
when the service starts (or restarts).

**Comment by uniquenode** [comment]
@jedisct1 I ran some tests, happens also with only DNSCrypt. Query log shows the requests they just don't resolve. The problem arises when switching network state, so for example when switching from WiFi to LAN.
