### ISSUE TITLE
Unable to bind to link-local IPv6 address

### ISSUE THREAD

**Issue by MrCowKing** [DNSCrypt/dnscrypt-proxy#531]
Adding a link-local ( [fe80::]/64 ) address to the "listen_addresses" line will cause the program to fail.

Working Example: 
`listen_addresses = ['127.0.0.1:53','192.168.1.254:53', '[::1]:53']`

Broken Example:
`listen_addresses = ['127.0.0.1:53','192.168.1.254:53', '[::1]:53', '[fe80::1234:1234:fe37:2bc7]:53']`

Here's the systemd error message that's given:
`[FATAL] listen udp [fe80::1234:1234:fe37:2bc7]:53: bind: invalid argument`

I am not using the SystemD sockets. That's disabled and stopped. I've double checked that I put in the correct address that ifconfig gave.

**Comment by jedisct1** [comment]
Isn't a link-local address tied to a specific interface?

**Comment by jedisct1** [comment]
You need to specify the scope.

**Comment by MrCowKing** [comment]
How would I specify the scope?

**Comment by jedisct1** [comment]
Append `%` and the scope, like everywhere else when using link-local addresses.

**Comment by MrCowKing** [comment]
My oh my, that was easy.

For future users that had the same brain fart:
`listen_addresses = ['127.0.0.1:53','192.168.1.254:53', '[::1]:53', '[fe80::1234:1234:fe37:2bc7%enp0s25]:53']`

"enp0s25" will probably be different though. Look in ifconfig for the interface ID/name
