### ISSUE TITLE
about edns-client-subnet

### ISSUE THREAD

**Issue by mcnk328** [DNSCrypt/dnscrypt-proxy#532]
Can dnscrypt-proxy2 support edns-client-subnet?

**Comment by jedisct1** [comment]
Hi!

Yes, it does. If the client sends a ECS option, dnscrypt-proxy will send it to the server. If the server sends it to authoritative servers, it will keep doing so, with or without dnscrypt.

**Comment by mcnk328** [comment]
Hello, how to let the client send edns request by default @jedisct1

**Comment by jedisct1** [comment]
The client doesn't do that, as edns-clientsubnet is very bad for privacy.

Is it for use with Google?

**Comment by mcnk328** [comment]
@jedisct1 Does dnscrypt-proxy2 support ECS by default, or does it need to be modified to take effect?

**Comment by jedisct1** [comment]
It supports ECS by default, but it doesn't add this information, the client has to add it.

This will only work if you are using Google DNS.

**Comment by jedisct1** [comment]
Even with Google, it doesn't seem to work (any more? It seemed to me that it used to work at some point). What Google transmits is the real network address, not what the client sends.

**Comment by mcnk328** [comment]
I try to send edns option to Google, the result is the same as the option to not send edns @jedisct1

**Comment by jedisct1** [comment]
Yes, so like Cisco, Google ignores ECS data from the client and sends the real network IP to companies and organizations that asked for it.

If dnscrypt-proxy adds ECS information, it wouldn't change anything.

**Comment by mcnk328** [comment]
Ok, I hope dnscrypt can really support edns in the future. @jedisct1

**Comment by jedisct1** [comment]
It does, it always did. But resolvers don't forward this information, with or without DNSCrypt.
