### ISSUE TITLE
How to check whether the traffic is encrypted before the DNSCrypt-proxy DNS server?

### ISSUE THREAD

**Issue by wolfmen7** [DNSCrypt/dnscrypt-proxy#534]
Hi everybody.
I installed and tuned the script-asking in my debian stretch. Configured to the address 127.0.0.7:53. For some reason, when viewing network traffic through a wireshark, the requests go only from 127.0.0.1 to 127.0.0.7 in the open view.
Queries and answers:
303860 3285.752803436 127.0.0.1 127.0.0.7 DNS 77 Standard query 0x3a1a A linux-notes.org
303861 3285.752812609 127.0.0.1 127.0.0.7 DNS 77 Standard query 0x9a22 AAAA linux-notes.org
303862 3285.752974512 127.0.0.7 127.0.0.1 DNS 104 Standard query response 0x3a1a A linux-notes.org A 31.187.70.238 OPT
303863 3285.752994723 127.0.0.7 127.0.0.1 DNS 147 Standard query response 0x9a22 AAAA linux-notes.org SOA ns1.r01.ru OPT

Prompt, how will check up work dnsript-proxy in debian?
Through sites:
https://www.dnsleaktest.com/
https://www.dns-oarc.net/oarc/services/dnsentropy/
Show the real addresses of DNS servers. Here's how to check if traffic is encrypted before them.

**Comment by jedisct1** [comment]
Stop or pause `dnscrypt-proxy`. If you can't resolve anything any more, it means that all your DNS traffic was going through it, and is encrypted.

**Comment by jedisct1** [comment]
Some suggestions have been added to the wiki: https://github.com/jedisct1/dnscrypt-proxy/wiki/Checking
