### ISSUE TITLE
socket activation from unbound fails since 2.0.15

### ISSUE THREAD

**Issue by eatdust** [DNSCrypt/dnscrypt-proxy#535]
Hi there,
I am an old fan of dnscrypt-proxy, and till version 2.0.15, I used socket activation from unbound. Namely,
in dnscrypt-proxy.toml, I have

``
listen_addresses = []
``

A dnscrypt-proxy.socket systemd activation unit with

``
[Socket]
``
``
ListenStream=127.0.0.1:40
``
``
ListenDatagram=127.0.0.1:40
``

and an unbound service with unbound.conf having a forward zone as:

``
forward-zone:
``
``
   name: "."
``
``  
 forward-addr: 127.0.0.1@40
``

This configuration seems to be broken with dnscrypt-proxy 2.0.15, but was working with 2.0.12. I think there is an issue with socket activation because if I stop the dnscrypt-proxy.socket unit, change dnscrypt-proxy.toml into

``
listen_addresses = ['127.0.0.1:40', '[::1]:40']
``

Then, everything works fine again. So unbound properly forward the query to 127.0.0.1:40, but somehow, dnscrypt-proxy socket does not succeed to activate dnscrypt-proxy.service anymore!

Any help appreciated!
Cheers.

**Comment by jedisct1** [comment]
Hi!

This is a duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/480

**Comment by eatdust** [comment]
Oops, sorry, thanks!
