### ISSUE TITLE
dnscrypt-proxy V2 + pihole + FTLDNS (tls_disable_session_tickets?)

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#536]
Hi!

I use dnscrypt-proxy V2 + pihole + FTLDNS.

Are my dnscrypt-proxy.toml settings good enough for security in dnscrypt-proxy?

What about with this? good or not?

tls_disable_session_tickets = true
tls_cipher_suite = [52392, 49199]

Should I use that or not? 

My settings:

#### LIST of local ADDRESSEZ & PORTZ to listen:
listen_addresses = ['127.0.0.3:41']
max_clients = 250
#
#
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 2500
keepalive = 30
lb_strategy = 'p2'
log_level = 2
log_file = '/var/tmp/dnscrypt-proxy.log'
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = true
tls_disable_session_tickets = false
#tls_cipher_suite =
#fallback_resolver = '208.67.222.222:53'
ignore_system_dns = false
log_files_max_size = 10
log_files_max_age = 1
block_ipv6 = true
cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60

[query_log]

file = '/var/tmp/query.log'
format = 'tsv'
ignored_qtypes = ['DNSKEY', 'NS']

[nx_log]

file = '/var/tmp/nx.log'
format = 'tsv'

[blacklist]

blacklist_file = 'blacklist.txt'
log_file = '/var/tmp/blocked.log'
log_format = 'tsv'

[ip_blacklist]

blacklist_file = 'ip-blacklist.txt'
log_file = '/var/tmp/ip-blocked.log'
log_format = 'tsv'

[static]

  [static.'arvind-io']
  stamp = 'sdns://AQcAAAAAAAAAEjEzOS41OS4xNi4xMzA6NTM1MyCORifHOIOoUQMIIbpa5-XQQfSq75W3gpAWy2Udh8MoyRkyLmRuc2NyeXB0LWNlcnQuYXJ2aW5kLmlv'
  [static.'dnscrypt.eu-nl']
  stamp = 'sdns://AQcAAAAAAAAADDQ1Ljc2LjM1LjIxMiBMhPuMBRFd-l-Xxe0DKRNwx4q81k4V3VOrCN5y-4RKyh8yLmRuc2NyeXB0LWNlcnQubnMwLmRuc2NyeXB0Lm5s'
  [static.'dnscrypt.nl-ns0']
  stamp = 'sdns://AQcAAAAAAAAADDQ1Ljc2LjM1LjIxMiBMhPuMBRFd-l-Xxe0DKRNwx4q81k4V3VOrCN5y-4RKyh8yLmRuc2NyeXB0LWNlcnQubnMwLmRuc2NyeXB0Lm5s'

My pihole-FTL.conf:

SOCKET_LISTENING=all
QUERY_DISPLAY=yes
AAAA_QUERY_ANALYSIS=no
MAXDBDAYS=0
RESOLVE_IPV6=no
RESOLVE_IPV4=yes
DBINTERVAL=1.0
#DBFILE=/etc/pihole/pihole-FTL.db
MAXLOGAGE=24.0
FTLPORT=4711
PRIVACYLEVEL=3
IGNORE_LOCALHOST=no
BLOCKINGMODE=NULL

**Comment by ghost** [comment]
My dnscrypt-proxy.service config:
[Unit]
Description=#### DNSCrypt PROXY v2 - CLIENT ####
ConditionFileIsExecutable=/etc/dnscrypt-proxy/dnscrypt-proxy

[Service]
NonBlocking=true
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/etc/dnscrypt-proxy/dnscrypt-proxy

WorkingDirectory=/etc/dnscrypt-proxy

ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
PrivateDevices=yes
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=yes
NoNewPrivileges=yes
RestrictNamespaces=yes
MemoryDenyWriteExecute=yes
RestrictRealtime=yes

Restart=always
RestartSec=120
EnvironmentFile=-/etc/sysconfig/dnscrypt-proxy

[Install]
WantedBy=multi-user.target

**Comment by jedisct1** [comment]
90% of that is completely useless and will only prevent the server from working properly.

Start with the example configuration and with a minimal systemd config.

# DO NOT USE STATIC STAMPS

Just don't. Unless you really have a reason to, but in that case, you probably shouldn't open a ticket to ask about your configuration. These are not even used in what you posted..

The only thing you may need to change is `listen_addresses`.

**Comment by jedisct1** [comment]
The wiki also contains instructions for pi-hole: https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0
