### ISSUE TITLE
dnscrypt-proxy doesn't listen to 127.0.0.1 (Windows 10 x64)

### ISSUE THREAD

**Issue by Rolf185** [DNSCrypt/dnscrypt-proxy#537]
I'm running dnscrypt-proxy on a VirtualBox virtual Windows 10 x64 system using the default setup configuration with cloudflare servers.
dnscrypt-proxy -resolve google.de is fine.
nslookup google.de ::1 is fine.
nslookup google.de 127.0.01 fails with a timeout. The Windows 10 firewall is off.

**Comment by ghost** [comment]
Every localhost has 16777216 loopback addresses available. You can try 127.0.0.2 and check if it works. Given that dnscrypt-proxy works on ipv6 which only has a single localhost address I assume some other software might be blocking 127.0.0.1 for you?

**Comment by Rolf185** [comment]
Seems to be a Windows problem. Anyway, nothing changed but now working.
