### ISSUE TITLE
No resolve via Pihole LOG but Internet works with FTLdns + dnscrypt 

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#539]
No resolve via Pihole LOG but Internet works with FTLdns + dnscrypt

Hi!

What is wrong with my configs?
Internet with dnscrypt+pihole works, blocking works but why I get the error message in
pihole debug?

Which all values must I change for correct config?

pihole log shows me:

Ports in use
[4711] is in use by pihole-FTL
[53] is in use by dnsmasq
[9050] is in use by tor
[53] is in use by dnsmasq
[53] is in use by dnsmasq

dnscrypt-proxy will showed in pihole debug log when I change port 53 to 513 @
listen_addresses = ['127.0.0.1:53'] to 127.0.0.1:513 and under
dnscrypt-proxy.socket to 513

[✗] Failed to resolve  via localhost (127.0.0.1)
[✗] Failed to resolve  via Pi-hole (192.168.178.100)
[✓] doubleclick.com is 172.217.16.78 via a remote, public DNS server (8.8.8.8)

Pi-hole processes
[✗] dnsmasq daemon is inactive
[✗] lighttpd daemon is inactive
[✓] pihole-FTL daemon is active

my configz:

In NetworkManager (UbuntuMate) = 127.0.0.1

/etc/dnsmasq.d/
###############
01-pihole.conf:

addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list
localise-queries
#no-resolv
cache-size=10000
log-queries=extra
log-facility=/var/log/pihole.log
local-ttl=2
log-async
server=127.0.2.1
dnssec
trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D
interface=enp4s0

/etc/dnsmasq.d/
###############
02-dnscrypt-proxy.conf:

server=127.0.2.1
#no-resolv
proxy-dnssec

/etc/dnscrypt-proxy/
####################
dnscrypt-proxy.toml

listen_addresses = ['127.0.0.1:53']

/lib/systemd/system/
dnscrypt-proxy.socket:

ListenStream=127.0.2.1:53
ListenDatagram=127.0.2.1:53

/etc/pihole/
############
pihole-FTL.conf:

SOCKET_LISTENING=all
RESOLVE_IPV4=yes
RESOLVE_IPV6=no
QUERY_DISPLAY=yes
AAAA_QUERY_ANALYSIS=yes
MAXDBDAYS=1
MAXLOGAGE=24.0
DBFILE=/etc/pihole/pihole-FTL.db
DBINTERVAL=1.0
FTLPORT=4711
PRIVACYLEVEL=3
IGNORE_LOCALHOST=no
BLOCKINGMODE=NULL

/etc/pihole/
############
setupVars.conf:

DNSSEC=true
PIHOLE_INTERFACE=enp4s0
IPV4_ADDRESS=192.168.178.100/24
IPV6_ADDRESS=
PIHOLE_DNS_1=
PIHOLE_DNS_2=
QUERY_LOGGING=true
INSTALL_WEB=false
INSTALL_WEB_SERVER=false
INSTALL_WEB_INTERFACE=false
LIGHTTPD_ENABLED=0

/etc/
#####
dnsmasq.conf:

listen-address=127.0.0.1
port=5353
domain-needed
bogus-priv
dnssec
proxy-dnssec
strict-order
no-resolv
no-poll
server=127.0.2.1
#cache-size=1000
neg-ttl=3600
dns-forward-max=150
bind-interfaces

/etc/network/
#############
interfaces:

# [INTERFACE] FILE used by IFUP and IFDOWN:
auto lo
iface lo inet loopback

#### STATIC // [!LAN!]
allow-hotplug enp4s0
iface enp4s0 inet static
 address 192.168.178.100
 netmask 255.255.255.0
 gateway 192.168.178.1
 dns-nameservers 127.0.0.1

Please help, thanks!

**Comment by jedisct1** [comment]
Did you follow the [documentation](https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0)?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
which values must I change?

**Comment by ghost** [comment]
I don't have dnsmasq enabled (pihole install disabled it) because FTLdns is enabled.

**Comment by ghost** [comment]
Get it working with this:  STATIC-CONFIG, none DHCP.

/etc/dnsmasq.conf: Port: 5353

NetworkManager:   127.0.0.1
/etc/NetworkManager/NetworkManager.conf:  dns=none
/etc/Network/interfaces: 

auto lo
iface lo inet loopback

#### STATIC // [!LAN!]
allow-hotplug enp4s0
iface enp4s0 inet static
 address "your IP"
 netmask 255.255.255.0
 gateway "your ROUTER_IP"
 dns-nameservers 127.0.0.1

01-pihole.conf:  server=127.0.0.1#54

02-dnscrypt-proxy.conf:
server=127.0.0.1#54
#no-resolv
proxy-dnssec

Removed package:   resolvconf

create a new "resolv.conf" in /etc/
nameserver 127.0.0.1
options edns0 single-request-reopen timeout:1

dnscrypt-proxy.toml: (comment out)
#listen_addresses = ['127.0.0.1:54']

/lib/systemd/system  (dnscrypt-proxy.socket)

[Unit]
Description=####//dnsCRYPT-PROXY [SOCKET]

[Socket]
ListenStream=127.0.0.1:54
ListenDatagram=127.0.0.1:54

NoDelay=true
DeferAcceptSec=1

[Install]
WantedBy=sockets.target

/lib/systemd/system (dnscrypt-proxy.service)

[Unit]
Description=####//dnsCRYPT-PROXY [SERVICE]
Requires=dnscrypt-proxy.socket
Wants=network-online.target
After=network.target network-online.target

[Service]
NonBlocking=true
User=dnscrypt-proxy
DynamicUser=true
LockPersonality=yes
Group=nogroup
ExecStart=/usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
ExecStop=/bin/kill -TERM $MAINPID

TimeoutStartSec=180
Restart=on-failure
RestartSec=10s

UMask=0077
RestrictAddressFamilies=AF_INET AF_INET6
RestrictRealtime=yes
RestrictNamespaces=yes

AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

PrivateDevices=yes
ProtectControlGroups=yes
ProtectKernelModules=yes

StateDirectory=dnscrypt-proxy

[Install]
Also=dnscrypt-proxy.socket
#Also=dnscrypt-proxy.socket
WantedBy=multi-user.target

pihole (setupVars.conf):
PIHOLE_DNS_1=127.0.0.1#54

pihole (pihole-FTL.conf):
SOCKET_LISTENING=all
RESOLVE_IPV4=yes

PIHOLE checkout from FTLDNS to MASTER branch:
cd /pihole
sudo su
pihole checkout master
pihole -up
pihole -g

NOW it works :-)
