### ISSUE TITLE
How can a single dns server be used?

### ISSUE THREAD

**Issue by idanka** [DNSCrypt/dnscrypt-proxy#54]
How can a single dns server be used?
Where should I set it?

Very slow or remote servers are set up.
Central Europe is quick to OpenDNS, google dns (or opennic).
I mostly like OpenDNS.
_Sorry google translate._
Thx!

**Comment by Marco-vW** [comment]
By specifying a single DNS server in the dnscrypt-proxy.toml config file.

For OpenDNS the first section should look like:

```
`##################################
#         Global settings        #
##################################

## List of servers to use
## If this line is commented, all registered servers will be used

server_names = ['cisco']`
```

Make sure there's no hashtag (#) in front of the line _server_names_, otherwise all available servers will be used.

**Comment by idanka** [comment]
Thx Marco:)
I should have seen
