### ISSUE TITLE
dnscrypt-proxy user account?

### ISSUE THREAD

**Issue by 3k2** [DNSCrypt/dnscrypt-proxy#541]
Hey

I've been trying to troubleshoot this case to find out why is there now dnscrypt-proxy user account option to login from my sddm? far as I can tell it doesn't exist in the accounts list..

**Comment by r4sas** [comment]
Clairvoyants on vacation.
Need more information.

**Comment by 3k2** [comment]
I'm using arch linux with plasma DE and after reboot I saw dnscrypt-proxy account as option to login. 

what could I do to give more info?

when doing commands "groups" and "users" it doesn't display any dnscrypt-proxy related.

**Comment by r4sas** [comment]
How you installed it?
It's not dnscrypt problem. Contact with Arch Linux package maintainer.
https://www.archlinux.org/packages/community/x86_64/dnscrypt-proxy/

**Comment by jedisct1** [comment]
I had no idea what sddm was, but Googling for it landed me to this page: https://wiki.archlinux.org/index.php/SDDM

It includes a section that describes how to show (or hide) specific users.

By the way the `users` command only prints users that are logged in. On Linux, to see the list of users, the command is `getent passwd`.
