### ISSUE TITLE
What has to be entered in the DNS-server-field of the router?

### ISSUE THREAD

**Issue by Biggizen** [DNSCrypt/dnscrypt-proxy#542]
Hello,

if I understand it right, dns-proxy automaticly chooses a DNS-server from the public-resolvers.md. In Windows I have to enter 127.0.0.1 (IPv4) and ::1 (IPv6) as DNS-servers. But what do I have to enter in the DNS-server-field of my router? The same?

Thanks in advance!

**Comment by jedisct1** [comment]
Since you are running the proxy on your computer instead of the router, there is nothing to change on the router.

**Comment by Biggizen** [comment]
This means, that the DNS-setting of Windows/dns-proxy overrides the router-setting?

**Comment by jedisct1** [comment]
Yes, exactly. This will also protect you from malware changing DNS settings of routers such as DNSChanger.

**Comment by Biggizen** [comment]
Thanks!
