### ISSUE TITLE
Latest 2.0.16 download is blocked by Google Chrome: "...is not commonly downloaded and may be dangerous."

### ISSUE THREAD

**Issue by onmyouji** [DNSCrypt/dnscrypt-proxy#543]
Hi,

Just want to let you know that Chrome triggers a warning when I tried to download the latest dnscrypt-proxy-win64-2.0.16.zip. 

This didn't happen when downloading previous versions.

**Comment by KrasnayaPloshchad** [comment]
Try other download manager instead.

**Comment by jedisct1** [comment]
Fun :)
