### ISSUE TITLE
Systemd service failed to run on Linux Mint 19

### ISSUE THREAD

**Issue by seth100** [DNSCrypt/dnscrypt-proxy#546]
Hi,

I did:

```
$ sudo add-apt-repository ppa:shevchuk/dnscrypt-proxy && \
sudo apt update && \
sudo apt install dnscrypt-proxy
```
and followed all parts under https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-Debian-Ubuntu#configuration 

Then done:
`$ sudo systemctl restart NetworkManager`
`$ sudo systemctl restart dnscrypt-proxy`

But failed:
`$ sudo systemctl status dnscrypt-proxy`

```
dnscrypt-proxy.service - DNSCrypt-proxy client
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-07-15 14:19:53 CEST; 29s ago
     Docs: https://github.com/jedisct1/dnscrypt-proxy/wiki
  Process: 10424 ExecStart=/usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml (code=exited, status=255)
 Main PID: 10424 (code=exited, status=255)

jul 15 14:19:52 user systemd[1]: Started DNSCrypt-proxy client.
jul 15 14:19:53 user dnscrypt-proxy[10424]: [2018-07-15 14:19:53] [NOTICE] Source [public-resolvers.md] loaded
jul 15 14:19:53 user dnscrypt-proxy[10424]: [2018-07-15 14:19:53] [NOTICE] dnscrypt-proxy 2.0.16
jul 15 14:19:53 user dnscrypt-proxy[10424]: [2018-07-15 14:19:53] [FATAL] listen udp 127.0.0.1:53: bind: permission denied
jul 15 14:19:53 user systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
jul 15 14:19:53 user systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
```

Any help please?

Thanks

**Comment by jedisct1** [comment]
Looks like these instructions don't work, then :(

Remove everything and follow the generic installation steps instead: https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux

**Comment by jedisct1** [comment]
I think you forgot to change:

```
listen_addresses = ['127.0.0.1:53']
```

to

```
listen_addresses = ['']
```

Granted, the page had a `diff` output supposed to suggest this, but it was very hard to read.

**Comment by seth100** [comment]
@jedisct1, thank you it works now the service, after setting `listen_addresses = ['']`!

The problem now is that after setting `127.0.0.1` from GUI as DNS (not auto DNS) internet does now work anymore. It can't succeed in resolve addresses.
Am I missing anything?

Thanks

Ps I think you had a typo [here](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-Debian-Ubuntu#configure-dnscrypt-proxytoml):
you wrote:
In `dnscrypt-proxy.toml`, replace `listen_addresses = ['127.0.0.1:53']` with `listen_addresses = ['127.0.0.1:53']`.

but should be:

In `dnscrypt-proxy.toml`, replace `listen_addresses = ['127.0.0.1:53']` with `listen_addresses = []`.

right?

**Comment by jedisct1** [comment]
Good catch for the typo. Fixed, thanks!

**Comment by seth100** [comment]
> The problem now is that after setting 127.0.0.1 from GUI as DNS (not auto DNS) internet does now work anymore. It can't succeed in resolve addresses.
> Am I missing anything?

Any tip for my problem?

**Comment by MinIsMin** [comment]
Got the same problem since 2.0.15, am on Ubuntu 18.04.

**Comment by jedisct1** [comment]
Don't use systemd sockets activation, and all your troubles will go away.

**Comment by MinIsMin** [comment]
Then I still have the problem seth mentioned first (permission denied on all ips with port 53)

**Comment by jedisct1** [comment]
Remove all the dnscrypt systemd service files, and install the service with `dnscrypt-proxy -service install`.

**Comment by MinIsMin** [comment]
Thanks, now it's working fine!
