### ISSUE TITLE
dnscrypt-proxy doesn't kill its child process if the main process is stopped

### ISSUE THREAD

**Issue by konimex** [DNSCrypt/dnscrypt-proxy#547]
## Description

When the main dnscrypt-proxy program/service (root) is stopped, the child process is still running. This means if I restart the dnscrypt-proxy service, it would fail since there's already a dnscrypt-proxy instance running.

## Expected

The child process is also killed along with its parent process.

## Actual result

The child process still runs under init.

![2018-07-16-185505_1490x363_scrot](https://user-images.githubusercontent.com/15692230/42757561-be4de8c2-892a-11e8-8fd8-0c81e2749dd9.png)

I'm not sure if this is intended or a bug. But I'm leaning towards the latter.

**Comment by jedisct1** [comment]
What operating system is that on? How are you stopping it? Using `dnscrypt-proxy -service stop`?

**Comment by konimex** [comment]
Artix Linux, using runit as init system. <s>(Also testing on Void Linux to see if this problem only exists on Artix or also happens on Void)</s>Also happened on Void.

I stopped it using `sv stop dnscrypt-proxy` command provided by runit.

**Comment by jedisct1** [comment]
Do you know how to fix this?

**Comment by konimex** [comment]
I think when the main process caught SIGTERM from the service manager (in this case, runit), kill its child process (if any). However I'm not sure if the main process tracks its child, and I'm not well-versed in Go.
