### ISSUE TITLE
Windows: dnscrypt-proxy service stopped during network initialization 

### ISSUE THREAD

**Issue by Rolf185** [DNSCrypt/dnscrypt-proxy#548]
My Windows needs quite a long time to connect to my wireless. Somtimes I must connect by hand. I see that the dnscrypt-proxy service starts and waits for the network. Message "[NOTICE] Network not available yet -- waiting..."
When the network comes up later the service is stopped meanwhile an must be started again.
Maybe related to #530?

Rolf

**Comment by jedisct1** [comment]
You can adjust `netprobe_timeout` to the maximum amount of time to wait for network connectivity before giving up. The default is 30 seconds.

**Comment by Ainatar** [comment]
What is the maximum amount of time that you cant set to wait for network connectivity? Depends on the OS? (I'm using Windows 10) And what happens if you set netprobe_timeout to 0?

**Comment by Rolf185** [comment]
I've just tested with netprobe_timeout = 300. Can't see any change at the first try. There's no stop message in the log file. So, the only message I see is the "Network not available ..." one. By the way, there's also no start message. The "Network not available ..."  one is the first message.

**Comment by Rolf185** [comment]
Now I can confirm that this isn't working:
[2018-07-18 **12:04:42**] [NOTICE] Network not available yet -- waiting...
**12:05:13,16** sc query dnscrypt-proxy
SERVICE_NAME: dnscrypt-proxy
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0

**Comment by jedisct1** [comment]
Can you run it from the command line, not as a service?

**Comment by Rolf185** [comment]
Yes, I did (wireless not connected, netprobe_timeout = 300, log_level = 
0):

c:\Windows\System32\dnscrypt-proxy>dnscrypt-proxy
[2018-07-18 12:44:52] [NOTICE] Network not available yet -- waiting...
[2018-07-18 12:49:52] [ERROR] Timeout while waiting for network 
connectivity
[2018-07-18 12:49:52] [NOTICE] Source [public-resolvers.md] loaded
[2018-07-18 12:49:52] [NOTICE] dnscrypt-proxy 2.0.15
[2018-07-18 12:49:52] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2018-07-18 12:49:52] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
[2018-07-18 12:49:52] [NOTICE] Now listening to [::1]:53 [UDP]
[2018-07-18 12:49:52] [NOTICE] Now listening to [::1]:53 [TCP]
[2018-07-18 12:49:52] [ERROR] Get 
https://dns.cloudflare.com/dns-query?body=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&random_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: 
dial tcp 1.0.0.1:443: connectex: Ein Socketvorgang bezog sich auf ein 
nicht verfügbares Netzwerk.
[2018-07-18 12:49:52] [NOTICE] dnscrypt-proxy is waiting for at least 
one server to be reachable
[2018-07-18 12:51:52] [INFO] Loading source information from URL 
[https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md]
[2018-07-18 12:51:52] [INFO] Loading source information from URL 
[https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md.minisig]
...
[2018-07-18 13:02:10] [NOTICE] Stopped.

I didn't see the "[ERROR] Timeout ...", the "[NOTICE] Stopped." and all 
messages between when running as a service. Maybe this is a hint that 
Windows has a timeout starting a service and stops it if it doens't 
report ok in time?


------ Originalnachricht ------
Von: "Frank Denis" <notifications@github.com>
An: "jedisct1/dnscrypt-proxy" <dnscrypt-proxy@noreply.github.com>
Cc: "Rolf185" <rolf.wetjen@mail.de>; "Author" 
<author@noreply.github.com>
Gesendet: 18.07.2018 12:20:37
Betreff: Re: [jedisct1/dnscrypt-proxy] Windows: dnscrypt-proxy service 
stopped during network initialization (#548)

**Comment by jedisct1** [comment]
It timed out after 30 seconds. There was still no network connectivity...

**Comment by cubakcabak** [comment]
can it make so the dnscrypt-proxy running and standby even before the network available?

i remembered the version 1 can

**Comment by Rolf185** [comment]
Hi jedisct1,
this is definitly a service start timeout issue. I found service control manager messages 7000 and 7009 in the system log.
7000: The dnscrypt-proxy service failed to start due to the following error:
The service did not respond to the start or control request in a timely fashion.
7009: A timeout was reached (30000 milliseconds) while waiting for the dnscrypt-proxy service to connect.

**Comment by r13s** [comment]
@Rolf185 https://github.com/jedisct1/dnscrypt-proxy/issues/454#issuecomment-390471496

**Comment by bezdupel** [comment]
#454

**Comment by Hasshu** [comment]
There just should be an option to start the service right away (pre-v2.0.12 behavior).

> #454 (comment)

@bezdupel It's a hit-or-miss workaround, unfortunately.

**Comment by jedisct1** [comment]
> There just should be an option to start the service right away (pre-v2.0.12 behavior).

Incidentally, there is one, and it's documented.

If the network is not available, it's not going to work any better.

But for the first time, we get an interesting hints: `A timeout was reached (30000 milliseconds) while waiting for the dnscrypt-proxy service to connect`.

So, services are supposed to "connect". I don't know what that means, but Go has an `mgr.Connect()` method that `establishes a connection to the service control manager`. Maybe this has to be explicitly called at some point? Anybody knows?

**Comment by Hasshu** [comment]
> Incidentally, there is one, and it's documented.

@jedisct1 Oops... Not sure how I missed that. Thanks.

> And what happens if you set netprobe_timeout to 0?

@Ainatar It gets disabled. See `example-dnscrypt-proxy.toml`.

**Comment by Rolf185** [comment]
In Windows terms: The OnStart method of the service must return within 30000 milliseconds.
