### ISSUE TITLE
Using dnscrypt-proxy with Docker

### ISSUE THREAD

**Issue by seth100** [DNSCrypt/dnscrypt-proxy#549]
Hi,

I'm trying to create a Dockerfile that installs `dnscrypt-proxy` and starts it.
After that I'd like to find a way to configure the Docker container to use as resolver. So that I will set an IP as my DNS server in my Network Manager and it will use the `dnscrypt-proxy` instance in the Docker container.

Is it possible?
Any way to make it work and maybe add a guide for it?

Thanks a lot!

**Comment by jedisct1** [comment]
Maybe https://github.com/gordyf/dnscrypt-proxy-2-docker can be used as a base?

**Comment by gordyf** [comment]
Hey, that's me. :) I wouldn't mind handing this off to you/whomever to be maintained as an official image for the project.

**Comment by jedisct1** [comment]
Good job, @gordyf!

I don't use Linux much, but maybe you can add a link to it somewhere in the documentation?

**Comment by seth100** [comment]
Great thank you guys!

**Comment by seth100** [comment]
Just one question @gordyf, what IP do I have to set in my Network Manager as DNS server to use the container as resolver?

**Comment by gordyf** [comment]
If you're using `network_mode: host` or exposing port 53 via the command-line (via `-p 53:53/udp` or the like) then you should use the IP address of the host on your network, such as `192.168.1.x`.

**Comment by seth100** [comment]
thank you @gordyf, I have opened an issue on your project to better explain the issue.
Thanks
