### ISSUE TITLE
Why to sign tags?

### ISSUE THREAD

**Issue by KOLANICH** [DNSCrypt/dnscrypt-proxy#550]
It's quite useless for now: the key is not publicly available and I and most of us don't know you personally, and the web of trust is untrustworthy itself.

**Comment by jedisct1** [comment]
Because if I don't, people complain that I didn't.

**Comment by KOLANICH** [comment]
@jedisct1, it is useless if we can't verify the signature. I couldn't find that public key anywhere in the internet including keyservers and keybase. Could you publish it?
