### ISSUE TITLE
Bypassing ISPs DNS Server

### ISSUE THREAD

**Issue by RozzyNoder** [DNSCrypt/dnscrypt-proxy#552]
No matter what I do my dnscrypt proxy service always ends up using my ISPs DNS server to resolve queries.  This DEFEATS the entire purpose of installing it in the first place.

The config file is fine with a [server_names] entry at top with 6 preferred servers defined in the static section with name and respective sdns stamp. I commented out the entire "sources to use" section after experimenting with OpenNic and PublicResolver list which worked fine. I played with use_system_dns setting true/false but that has no impact.

So how do I prevent the dnscrypt-proxy to NOT use my ISPs DNS server even if it is the fastest. Instead use one of the six defined in [server_names] of the config file even if they might be tad slower.  Any pointers/suggestions are much appreciated.

**Comment by jedisct1** [comment]
`dnscrypt-proxy` never sends data to servers that don't authenticate and encrypt packets.

So the actual issue is likely that you're not using the proxy at all. Make sure that your system has been configured to use the IP address of the proxy for DNS resolution.

**Comment by RozzyNoder** [comment]
@jedisct1  Thank you for pointing me  in the right direction. It seemed that on reboot my resolve.conf was getting overwritten by "Network Manager." 

So after locking the file and after "apt-get remove resolvconf" it is running fine.  Previously I had just removed execute permission from resolvconf and not locked resolv.conf file.

Anyhow, my closing question is there a cleaner way to cripple resolveconf without having to remove package from system as the install instruction suggest ?

**Comment by lenwar** [comment]
If you really want to use Network Manager, then you'll have to configure Network Manager to use another DNS-server than the one it's currently configured for.
Depending on your distro and installation type use the GUI, the TUI (should be something like   nmtui  ) or manually (as root-user, use sudo if needed)

nmcli con mod < connectionName > ipv4.dns "< dns server >"
Your connectionName can be found using:    nmcli con
