### ISSUE TITLE
dnscrypt servers not being proxied through socks5

### ISSUE THREAD

**Issue by 3onyc** [DNSCrypt/dnscrypt-proxy#553]
I've set force_tcp to true, and added the Tor socks proxy to the config file, however the latencies for non DoH servers are too low to be routed over Tor (< 20ms vs > 200ms for DoH), and when adding a firewall rule to reject any packets not destined for the Tor socks proxy they all time out.

**Comment by jedisct1** [comment]
Unfortunately I wasn't able to duplicate this.

Maybe something due to caching?
