### ISSUE TITLE
Cloaking rules not working

### ISSUE THREAD

**Issue by Gitoffomalawn** [DNSCrypt/dnscrypt-proxy#555]
#### Issue
I'm trying to use the cloaking feature of this proxy (awesome work, by the way!), but whatever I put in the cloaking rules file isn't getting picked up. The domains and IPs are resolved as they normally would, bypassing the cloaking rules. Blacklists are functioning normally.

#### Steps to reproduce
1. Uncomment the `cloaking_rules = '/path/to/cloaking-rules.txt'` in `/etc/dnscrypt-proxy/dnscrypt-proxy.toml`
2. Insert cloaking rules into `/path/to/cloaking-rules.txt` file
3. Restart dnscrypt-proxy
4. Try one of the cloaking rules inserted in `/path/to/cloaking-rules.txt`

**Comment by jedisct1** [comment]
Can you post an example `cloaking-rules.txt` file? How are you testing that a query that should be cloaked isn't?

**Comment by Gitoffomalawn** [comment]
Some sample entries:
```
netdata          192.168.1.10:19999
index.local      127.0.0.1
google.com       duckduckgo.com
```
All of these don't work. 

I'm testing by browsing to these locations after activating the proxy. They either don't resolve (the first two examples) or resolve normally (the last example).

**Comment by jedisct1** [comment]
Good. So, before using a  browser, can you directly send direct queries to the proxy with a command such as

```
dig index.local. @127.0.0.1
```

(or whatever the proxy IP address is?)

Send that to the proxy. Not to `dnsmasq` or some other intermediary.

**Comment by jedisct1** [comment]
Also try to enable query logs, and check if you can see your queries here.

**Comment by Gitoffomalawn** [comment]
These are the answers I get from `dig`:

```
; <<>> DiG 9.13.0 <<>> netdata @192.168.1.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 30809
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;netdata.			IN	A

;; AUTHORITY SECTION:
.			417	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2018072700 1800 900 604800 86400

;; Query time: 50 msec
;; SERVER: 192.168.1.10#53(192.168.1.10)
;; WHEN: Fri Jul 27 20:36:24 CEST 2018
;; MSG SIZE  rcvd: 111


; <<>> DiG 9.13.0 <<>> index.local @192.168.1.10
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7638
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;index.local.			IN	A

;; ANSWER SECTION:
index.local.		600	IN	A	127.0.0.1

;; Query time: 1 msec
;; SERVER: 192.168.1.10#53(192.168.1.10)
;; WHEN: Fri Jul 27 20:36:34 CEST 2018
;; MSG SIZE  rcvd: 56


; <<>> DiG 9.13.0 <<>> google.com @192.168.1.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60164
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		429	IN	A	107.20.240.232

;; Query time: 1 msec
;; SERVER: 192.168.1.10#53(192.168.1.10)
;; WHEN: Fri Jul 27 20:36:43 CEST 2018
;; MSG SIZE  rcvd: 54
```
The only one returning what I entered is the `index.local` one, and when I browse there, it dowsn't resolve.

**Comment by Gitoffomalawn** [comment]
Ok, so I may have some more information on what's going wrong. It appears the `google.com` entry is messing things up due to the search functionality in the address bar of the browser. It's trying to redirect my queries for `netdata` to Google, but fails.

Removing those and renaming `netdata` to `netdata.lan` gives me the correct `dig` results:
```
; <<>> DiG 9.13.0 <<>> netdata.lan @192.168.1.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39015
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;netdata.lan.			IN	A

;; ANSWER SECTION:
netdata.lan.		600	IN	A	192.168.1.10

;; Query time: 1 msec
;; SERVER: 192.168.1.10#53(192.168.1.10)
;; WHEN: Fri Jul 27 20:51:25 CEST 2018
;; MSG SIZE  rcvd: 56
```
Browsing to `netdata.lan` lands me squarely on the index page on port 80. Still, if I try to redirect it to another port using `address:port` notation, the `dig` fails retrieving results.

**Comment by jedisct1** [comment]
DNS can return IP addresses, not ports. This is not a limitation of dnscrypt-proxy, this is not something the protocol does :)

**Comment by jedisct1** [comment]
(technically, this is wrong, in theory, DNS could return anything, but not when asked for an IP address, which is the only thing your browser does)

**Comment by Gitoffomalawn** [comment]
Looks like you're correct. I tried some more stuff, only to come to the conclusion it ignores everything after the IP address. However due to the cloaking being able to return other sites by name (like `www.bing.com             strict.bing.com` from the examples in the file), I thought it might take other notations as well.
