### ISSUE TITLE
Update Documentation for Ubuntu 18.04

### ISSUE THREAD

**Issue by thmtrxhsu** [DNSCrypt/dnscrypt-proxy#557]
First of all, the specific installation instructions for Ubuntu / Debian are crap for several reasons.
Installing the dnscrypt-proxy service right away as that wiki would have you do makes it harder to get dnscrypt-proxy up and running.  Not only that, but at least with respect to Ubuntu 18.04 that whole page is garbage = will greatly confuse the user and greatly increase time needed to get dnscrypt-proxy up and running. 

 Delete the whole thing: https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-Debian-Ubuntu
Now, with respect to: https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux
Do not provide instructions with root shell; this is bad practice.
Also, commands like ss -lp 'sport = :domain' will partially work, and in partially working send the user on a goose chase to figure out what the pid or process is.
On this goose, I discovered an alternate command:
ADD
sudo netstat -upln|grep ":53 "  //UDP
sudo netstat -tpln|grep ":53 "  //TCP

Unlike the other one, this one gives the service/process name; systemd-resolved  and 1/Init.  The latter disappears after restart so long as the former was disabled.  To disable:
sudo systemctl disable systemd-resolved  

DEL
"It is totally possible to have the executable file in one place, the configuration file in another place, the cache files elsewhere and the log files yet somewhere else.

But if this is the first time you install the software, and you don't have any good reasons to makes things more complicated than they should be, just keep everything in the same directory. At least to start with, and to ensure that everything works as expected.

Then, go crazy if you like. But please don't change everything before even starting the proxy once, and then complain that "it doesn't work". Start with something boring, and gradually tweak it. If you really need to.

Also, do not change your DNS settings at this point."

ADD
[FATAL] Unable to load the configuration file [dnscrypt-proxy.toml] -- Maybe use the -config command-line switch? This means dnscrypt-proxy.toml was not found in the directory. 

[FATAL] cannot bind with the requested address  This means port 53 has already been reserved by another service or process.  You were suppose to disable systemd-resolved  and perform a restart.  If the issue persists sudo run either: netstat -upln|grep ":53 "   or ss -lp 'sport = :domain'
Nothing should be listening on port 53 otherwise the bind will fail.

ADD
Edit dnscrypt-proxy.toml
remove the # symbols from,  server_names = 
change, listen_addresses = ['127.0.0.1:53']
change, fallback_resolver = 'InternetProviderDNS:53'
To get internet provider DNS use command
nmcli dev show | grep DNS
There should only be one plausible IP address.
FYI: This command cannot inform you as to if dnscrypt-proxy is working or not.
save.
sudo ./dnscrypt-proxy

No errors? Amazing!
Don't close the terminal window yet. We're going to change the system DNS settings.

IMPROVE
Does your system have a directory called /etc/resolvconf (not the resolv.conf file)? If this is the case, remove it:

sudo apt-get remove resolvconf
Or if that says there is nothing to remove, then sudo FileManager and delete /etc/resolvconf folder

IMPROVE
Then delete the /etc/resolv.conf file (important, since this can be a dangling link instead of an actual file):  rm -f /etc/resolv.conf
However, that file might be a symbolic link, if so sudo FileManager and delete /etc/resolv.conf

sudo gedit /etc/resolv.conf
Add:
nameserver 127.0.0.1
options edns0 single-request-reopen
Save.

IMPROVE
Let's check that everything works by sending a first query using dnscrypt-proxy:
First, in one terminal run sudo ./dnscrypt-proxy
And in another run, sudo ./dnscrypt-proxy -resolve google.com
The most telling test is nslookup google.com
server and address should be 127.0.0.1
If you got that, and the IP of the URL, you're golden. 

Superior Linux Instructions

**Comment by jedisct1** [comment]
```sh
$ netstat
zsh: command not found: netstat

$ nslookup
zsh: command not found: nslookup

$ gedit
zsh: command not found: gedit
```

Using these obsolete commands doesn't seem to be an improvement, especially for the generic instructions.
