### ISSUE TITLE
Proxy authentication not supported

### ISSUE THREAD

**Issue by colemar** [DNSCrypt/dnscrypt-proxy#560]
This is not working on Windows 10:
`proxy = "http://domain\\user:pass@10.29.176.1:8080"`

**Comment by jedisct1** [comment]
Is the user name actually `domain\user`?

Are you talking to a SOCK5 proxy?

**Comment by colemar** [comment]
It is a Microsoft proxy, so domain\user is the required syntax.
It is an HTTP/HTTPS proxy, not SOCKS5.
Anyway the error is something like "Cannot parse proxy string".
HTTPS proxy support (otherwise known as http "tunneling" and it uses the CONNECT command) would be very useful.

**Comment by jedisct1** [comment]
The `proxy` feature is only for SOCKS proxies.

HTTP proxies are not supported. It wouldn't work in most cases. The DNSCrypt protocol doesn't use HTTP, and DoH requires HTTP/2 and a certificate chain that can be verified.

**Comment by colemar** [comment]
HTTP proxies also support the CONNECT method, which would work for DSNCrypt using TCP only.
I tried Proxifier (http://www.proxifier.com/) and it works: the network calls from dnscrypt-proxy are intercepted and tunneled through the proxy. I guess the linux equivalent would be proxychains.

About the title: does dnscrypt-proxy support authentication for SOCKS5? How? Nowhere in documentation is described how to specify credentials.

**Comment by jedisct1** [comment]
`socks5://user:password@127.0.0.1:9050` should work.

TBH, I haven't tried but the Go SOCK5 client code I use appears to support authentication out of the box.
