### ISSUE TITLE
Valid logging configurations?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#561]
I am finally writing the GUI. I just need some help understanding the logging configuration: namely what configurations are valid.

```
## Log level (0-6, default: 2 - 0 is very verbose, 6 only contains fatal errors)

# log_level = 2


## log file for the application

# log_file = 'dnscrypt-proxy.log'


## Use the system logger (syslog on Unix, Event Log on Windows)

# use_syslog = true
```

For instance, can syslog be used while there is no log level? Or can a log file be used while the log level key is commented out? Things like that.

**Comment by jedisct1** [comment]
Hi,

It's okay to have some or all of these properties not explicitly defined in the configuration file, as they all have a default value.

If you don't specify a log level, it will be the one in the comment by default (here: 2).

**Comment by ghost** [comment]
All right, thanks.
