### ISSUE TITLE
EC certificate support for handshake DoH

### ISSUE THREAD

**Issue by Yinchie** [DNSCrypt/dnscrypt-proxy#562]
Recently it has come to my attention that TLS certificates based on EC aren't supported, only RSA.
Any future plans for this?

**Comment by jedisct1** [comment]
Did you change the cipher suite?

ECDSA is definitely supported, as it is selected by default at least with Cloudflare and `doh.crypto.sx`.

**Comment by Yinchie** [comment]
Just re-tested it.

In my NGINX setup I have a dual ECDSA + RSA TLS certificate setup.
I disabled the RSA certificate by commenting it out.
Ciphersuite not changed.
Restarted NGINX.

In dnscrypt-proxy I enabled only the DoH server.
Restarted dnscrypt-proxy.

dnscrypt-proxy returns the error:
remote error: tls: handshake failure

**Comment by Yinchie** [comment]
Ah I found the problem!
It is the ciphersuite inside dnscrypt-proxy config.

Guess I keep both RSA and ECDSA enabled in NGINX for compatibility.

Problem solved.

**Comment by jedisct1** [comment]
The reason you may want to use RSA is that it is faster than ECC on non-Intel devices (routers, phones).
