### ISSUE TITLE
"minisign -Vm dnscrypt-proxy-linux_arm64-2.0.16.tar.gz -P RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3" gives me this output:

### ISSUE THREAD

**Issue by taoje** [DNSCrypt/dnscrypt-proxy#566]
Signature key id in dnscrypt-proxy-linux_arm64-2.0.16.tar.gz.minisig is 79833371EA15D7E4
but the key id in the public key is E7620F1842B4E81F

**Comment by jedisct1** [comment]
That doesn't seem to match what the documentation says:

https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation

The public key you tried is used for signing resolvers lists, not the software.

**Comment by taoje** [comment]
Excellent. Thank you for the quick and accurate response: 

"minisign -Vm dnscrypt-proxy-linux_x86_64-2.0.16.tar.gz -P RWTk1xXqcTODeYttYMCMLo0YJHaFEHn7a3akqHlb/7QvIQXHVPxKbjB5"

solved the issue, for the linux_x86 tar in this case.
