### ISSUE TITLE
SELinux blocking service.

### ISSUE THREAD

**Issue by cedws** [DNSCrypt/dnscrypt-proxy#567]
Hi there. I'm running Fedora 28 and I have installed the latest version (2.0.16) of `dnscrypt-proxy` manually. It appears that SELinux is blocking the service from binding to loopback, or something like that.

If I execute `sudo setenforce 0`, which disables SELinux, I can successfully make encrypted DNS requests. However, if I reenable SELinux by executing `sudo setenforce 1`, DNS requests will fail. I have ran `sudo setcap cap_net_bind_service=+pe dnscrypt-proxy`. 

If I try to start the `dnscrypt-proxy` service before disabling SELinux, the service will immediately exit and not run. Executing `sudo service dnscrypt-proxy status` reports `(code=exited, status=203/EXEC)` in red.

I did read something that claimed installing binaries in an expected location (such as `/bin`, `/usr/local/bin`) would be allowed through SELinux, but moving my installation from `/opt/dnscrypt-proxy` to `/usr/local/bin/dnscrypt-proxy` did not correct the issue.

Thanks.

**Comment by cedws** [comment]
One other thing. I have defined a listen address in `dnscrypt-proxy.toml` to be `127.0.0.1:53`. Not sure if this makes a difference.

**Comment by eclipseo** [comment]
Hi I'm the new maintainer for Fedora. You could install 2.016 using:

```
sudo dnf install dnscrypt-proxy --releasever=rawhide
```
It is preconfigured to use systemd sockets. Please remove any file of your current installation otherwise your current config would not be overwritten with the defaults.

You still need to configure NetworkManager and resolv.conf:

> **Edit /etc/NetworkManager/NetworkManager.conf**:
>
> add dns=none under [main]
> 
> **Create a new /etc/resolv.conf file with the following content:**
> 
> nameserver 127.0.0.1
> options edns0 single-request-reopen

Unfortunately there are still issues with SystemD DynamicUser functions, see bug https://github.com/systemd/systemd/issues/9583
I'm working on pushing a temporary fix which will be available tomorrow as dnscrypt-proxy-2.0.16-2. You can get it here https://koji.fedoraproject.org/koji/buildinfo?buildID=1135890 if you're in a hurry.

**Comment by admzzz** [comment]
@eclipseo,
consider (as a possible variant of your solution) _chattr +i /etc/resolv.conf_ after editing - it helps fantastically ;-)

**Comment by cedws** [comment]
@eclipseo Thanks for taking on responsibility for a package! I will give it a go tomorrow once `2.0.16-2` has been pushed.

**Comment by cedws** [comment]
@eclipseo Just tried to install your package, but encountered an error:
```
warning: /var/cache/dnf/updates-f2bc174df9355ab8/packages/dnscrypt-proxy-2.0.16-1.fc29.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 429476b4: NOKEY
Curl error (37): Couldn't read a file:// file for file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-rawhide-x86_64 [Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-rawhide-x86_64]
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
```

Unsure whether it's on my end. Thanks.

**Comment by eclipseo** [comment]
It's because F28 doesn't have the GPG keys for Rawhide installed. Just use:

```
sudo dnf install dnscrypt-proxy --releasever=rawhide --nogpgcheck
```
Or import the key before install:

```
sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-x86_64
```
Note that the package is not yet in Rawhide.

**Comment by cedws** [comment]
I can see 2.0.16-2.fc29 on the repository, but when I try to install it using that command, it's asking if I want to install `-1.fc29`. You said it isn't in Rawhide yet, but it looks like it is [here](https://apps.fedoraproject.org/packages/dnscrypt-proxy/overview).

**Comment by eclipseo** [comment]
@c-edw Sorry I didn't see your comment, have you managed to install it now?

**Comment by cedws** [comment]
@eclipseo Works now, thanks for your help. I had quite a bit of trouble figuring out how to get NetworkManager to stop updating `resolv.conf`. I will close this issue now.
