### ISSUE TITLE
Is query logging a deprecated or new feature?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#568]
I am making rapid progress on the GUI configuration tool: https://github.com/computerwonk/dnscrypt-proxy-config

I think I'll have an alpha version done by the end of the week. Then my summer break is over, so my contributions will slow down.

Right now I see that the query logging features are not documented in the wiki. Are they a brand new feature or will they be deprecated in the future?

**Comment by jedisct1** [comment]
Logging is here to stay. It's just like nobody cared to write documentation about logging features.
