### ISSUE TITLE
DNS Rebind protection?

### ISSUE THREAD

**Issue by jackyaz** [DNSCrypt/dnscrypt-proxy#569]
Can DNS rebind protection be implemented?

**Comment by jedisct1** [comment]
It was implemented a long time ago, even version 1 had it.

See how filters work:

https://github.com/jedisct1/dnscrypt-proxy/wiki/Filters

You can use them to block names, but also responses matching IP addresses. So if your local network is `192.168.*`, just block responses containing `192.168.*`.

Google even immediately returns that blog post about it:

https://blog.envimate.com/preventing-dns-rebinding-attacks-using-dnscrypt-proxy/

I wish someone had updated the Wiki instead, though.

**Comment by rr0ss0rr** [comment]
* Never mind .. I activated the wrong blacklist section

A quick question on the envimate article ..

I added a blacklist to the .toml listing the private ip addresses, restarted dnscrypt-proxy .. should I be seeing the REFUSED on the "nslookup net192.rebindtest.com"?

sudo /usr/local/sbin/dnscrypt-proxy -config /usr/local/etc/dnscrypt-proxy.toml
[2018-08-14 21:35:31] [NOTICE] Source [public-resolvers.md] loaded
[2018-08-14 21:35:31] [NOTICE] dnscrypt-proxy 2.0.16
[2018-08-14 21:35:31] [NOTICE] Loading the set of blocking rules from [/usr/local/etc/blacklist.txt]

blacklist.txt contains

10.*
172.16.*
172.17.*
172.18.*
172.19.*
172.20.*
172.21.*
172.22.*
172.23.*
172.24.*
172.25.*
172.26.*
172.27.*
172.28.*
172.29.*
172.30.*
172.31.*
192.168.*

When I do the nslookup, I receive

nslookup net192.rebindtest.com
Server:		10.0.0.1
Address:	10.0.0.1#53

Non-authoritative answer:
Name:	net192.rebindtest.com
Address: 192.168.0.1

Thanks

**Comment by jedisct1** [comment]
Is `10.0.0.1` the address of the proxy? If not, the system DNS settings have to be changed to use the proxy as a DNS resolver instead of `10.0.0.1` (which might be your router).
