### ISSUE TITLE
OpenBSD pledge call crash

### ISSUE THREAD

**Issue by eau-u4f** [DNSCrypt/dnscrypt-proxy#571]
Trying to run the openbsd amd64 binary as well as a locally built one (using go get), lead to the same problem:

> $ ./dnscrypt-proxy -check -config /etc/dnscrypt-proxy.toml 
> Abort trap (core dumped)`
Syslog shows:
> ...
> Aug 15 15:16:50 klamboe /bsd: dnscrypt-proxy[84693]: pledge "unix", syscall 97
> ...

3 small issues seems to have been identified:

- _pledge_(2) was referring to/implementing the [6.2 version of pledge(2)](https://man.openbsd.org/OpenBSD-6.2/pledge.2) using:
`int 
pledge(const char *promises, const char *paths[]);`
while [pledge(2) 6.3+](https://man.openbsd.org/OpenBSD-6.3/pledge.2) display the following primitive:
`int 
pledge(const char *promises, const char *execpromises);`
- the promises were missing the "unix" promises mainly due to a use of hashicorp/gsyslog which implement its own dial to a syslog ("unix" socket) service (not sure if it's good or not... i tend to prefer standard library and i have not investigated further, but explain the pledge killing syscall 97)
- the _PledgeChild()_ is seems redundant with the _execpromises_ param of _pledge_(2)

I made a quick (not sure if it takes all dnscrypt needs into account) fix here as pull-request:
#570

**Comment by jedisct1** [comment]
Actually, just adding `unix` to the promises should be fine.

`execpromises` was intentionally set to `nil` in order to avoid compatibility issues.

**Comment by eau-u4f** [comment]
yes, although execpromises are not []string anymore, but like promises just a string, but I guess your decision to drop Pledge for the time being seems better for now.
HTH.
