### ISSUE TITLE
feature request (take off warnings in android*-arm dnscrypt-proxy)

### ISSUE THREAD

**Issue by admzzz** [DNSCrypt/dnscrypt-proxy#574]
@jedisct1,
can you, please, in next releases take off two lines of warnings that appears on every call of dnscrypt-proxy from the shell script? it's very annoying and may spoil script's logic in some circumstances (in my  setup of afwall+dnscrypt-proxy script afwall.on analyzes the flow of itself and calls afwall.off in case of emergency to drop all traffic). 

```
# /system/xbin/dnscrypt-proxy -resolve intel.com
WARNING: linker: /system/xbin/dnscrypt-proxy: unused DT entry: type 0x6ffffffe arg 0xe24
WARNING: linker: /system/xbin/dnscrypt-proxy: unused DT entry: type 0x6fffffff arg 0x1
Resolving [intel.com]

Domain exists:  yes, 4 name servers found
```

**Comment by jedisct1** [comment]
Google returns some useful information about this:

https://stackoverflow.com/questions/33206409/unused-dt-entry-type-0x1d-arg

And maybe one thing you can do is use what they call a "cleaner" such as that one: https://github.com/kost/android-elf-cleaner

**Comment by admzzz** [comment]
@jedisct1 ,
thanks, it works.
