### ISSUE TITLE
HOW to create a own custom RESOLVER-LIST for static servers of "dnsCRYPT-PROXY v2"?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#576]
I want add these static servers because I don't trust all dns-servers in the
public RESOLVER-list.md

I want only the best/safest dnsCRYPT-PROXY v2 server.

Here is my list:

[static]

####//: ipv4-SERVER

	[static.'aaflalo-me']
	stamp = 'sdns://AgMAAAAAAAAADjE3Ni41Ni4yMzYuMTc1ID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4DmRucy5hYWZsYWxvLm1lCi9kbnMtcXVlcnk'

	[static.'arvind-io']
	stamp = 'sdns://AQcAAAAAAAAAEjEzOS41OS4xNi4xMzA6NTM1MyCORifHOIOoUQMIIbpa5-XQQfSq75W3gpAWy2Udh8MoyRkyLmRuc2NyeXB0LWNlcnQuYXJ2aW5kLmlv'

	[static.'cs-caeast']
	stamp = 'sdns://AQIAAAAAAAAADjE2Ny4xMTQuODQuMTMyIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'cs-cawest']
	stamp = 'sdns://AQIAAAAAAAAADzE2Mi4yMjEuMjA3LjIyOCAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM'

	[static.'cs-cfi']
	stamp = 'sdns://AQIAAAAAAAAADTIxMi44My4xNzUuMzEgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz'

	[static.'cs-ch']
	stamp = 'sdns://AQIAAAAAAAAADTE4NS42MC4xNDcuNzcgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz'

	[static.'cs-dk2']
	stamp = 'sdns://AQIAAAAAAAAADzE4NS4yMTIuMTY5LjEzOSAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM'

	[static.'cs-fi']
	stamp = 'sdns://AQIAAAAAAAAADjE4NS4xMTcuMTE4LjIwIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'cs-lv']
	stamp = 'sdns://AQIAAAAAAAAADTgwLjIzMy4xMzQuNTIgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz'

	[static.'cs-nl']
	stamp = 'sdns://AQIAAAAAAAAADjIxMy4xNjMuNjQuMjA4IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'cs-pl']
	stamp = 'sdns://AQIAAAAAAAAACzUuMTMzLjguMTg3IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'cs-pt']
	stamp = 'sdns://AQIAAAAAAAAADTEwOS43MS40Mi4yMjggMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz'

	[static.'cs-ro']
	stamp = 'sdns://AQIAAAAAAAAADDUuMjU0Ljk2LjE5NSAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM'

	[static.'cs-rome']
	stamp = 'sdns://AQIAAAAAAAAADjE4NS45NC4xOTMuMjM0IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'de.dnsmaschine.net']
	stamp = 'sdns://AQcAAAAAAAAAEzIwOS4yNTAuMjM1LjE3MDo0NDMgz0wbvISl_NVCSe0wDJMS79BAFZoWth1djmhuzv_n3KAiMi5kbnNjcnlwdC1jZXJ0LmRlLmRuc21hc2NoaW5lLm5ldA'

	[static.'dnscrypt.ca-1']
	stamp = 'sdns://AQcAAAAAAAAAFDE5OS4xNjcuMTMwLjExODo1MzUzIHT3RVUXvCb3EXflbXKTJ4hscpFbP0YoMD-RDEfDjoJ5HTIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5jYS0x'

	[static.'dnscrypt.ca-2']
	stamp = 'sdns://AQcAAAAAAAAAFDE5OS4xNjcuMTI4LjExMjo1MzUzIEPVLIJZIpbC22-NSM4iT9zHJibhBvbjiGGT-gCQKWMbHTIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5jYS0y'

	[static.'dnscrypt.eu-dk']
	stamp = 'sdns://AQcAAAAAAAAADDc3LjY2Ljg0LjIzMyA3SFWF47nQiP0lrTawNwH1UgzWSJ6a3VIUV0lVnwqZVSUyLmRuc2NyeXB0LWNlcnQucmVzb2x2ZXIyLmRuc2NyeXB0LmV1'

	[static.'dnscrypt.eu-nl']
	stamp = 'sdns://AQcAAAAAAAAADjE3Ni41Ni4yMzcuMTcxIGfADywhxVSBRd18tGonGvLrlpkxQKMJtiuNFlMRhZxmJTIuZG5zY3J5cHQtY2VydC5yZXNvbHZlcjEuZG5zY3J5cHQuZXU'

	[static.'dnscrypt.me']
	stamp = 'sdns://AQcAAAAAAAAADjk0LjE5OS4yMTMuMTcyIGBM5f1Wb-7SLs4vAJ7gc4hyFSmM5OOLWOvI3Hu5gRVOGzIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5tZQ'

	[static.'dnscrypt.nl-ns0']
	stamp = 'sdns://AQcAAAAAAAAADDQ1Ljc2LjM1LjIxMiBMhPuMBRFd-l-Xxe0DKRNwx4q81k4V3VOrCN5y-4RKyh8yLmRuc2NyeXB0LWNlcnQubnMwLmRuc2NyeXB0Lm5s'

####//: ipv6-SERVER

	[static.'dnscrypt.eu-dk-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAFFsyMDAxOjE0NDg6MjQzOjpkYzJdIDdIVYXjudCI_SWtNrA3AfVSDNZInprdUhRXSVWfCplVJTIuZG5zY3J5cHQtY2VydC5yZXNvbHZlcjIuZG5zY3J5cHQuZXU'

	[static.'dnscrypt.nl-ns0-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAJlsyMDAxOjE5ZjA6NTAwMTozMGE6NTQwMDpmZjpmZTU4OjcxNDBdIEyE-4wFEV36X5fF7QMpE3DHirzWThXdU6sI3nL7hErKHzIuZG5zY3J5cHQtY2VydC5uczAuZG5zY3J5cHQubmw'

	[static.'securedns-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAIVsyYTAzOmIwYzA6MDoxMDEwOjplOWE6MzAwMV06NTM1MyCzpZdpFFdbBInhn66cQ-Z5-vKMVxiXADF_e7SWKR-wlRwyLmRuc2NyeXB0LWNlcnQuc2VjdXJlZG5zLmV1'

	[static.'zeroaim-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAGVsyYTAzOjQwMDA6YjoyMjM6OjFdOjg0NDMgcrQcuGXx2fhX6rmtaP6aPXj8gumVIrn4GIrn6aTB1fUfMi5kbnNjcnlwdC1jZXJ0Lnplcm9haW0uZGUtaXB2Ng'

####//: DoH-SERVER

	[static.'dnscrypt.ca-2-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAH1syNjA1OjIxMDA6MDoxOjpiNWFkOjE4ZTJdOjUzNTMgQ9UsglkilsLbb41IziJP3McmJuEG9uOIYZP6AJApYxsdMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNhLTI'

	[static.'doh-crypto-sx']
	stamp = 'sdns://AgcAAAAAAAAADTEwNC4xOS4xOTguMjkgHdhQioxWWQQ5fHhkUeCPV2E888inI_bzef1MOFi2858NZG9oLmNyeXB0by5zeAovZG5zLXF1ZXJ5'

	[static.'doh-ibksturm']
	stamp = 'sdns://AgcAAAAAAAAADzIxNy4xNjIuMjA2LjE3OAAYaWJrc3R1cm0uc3lub2xvZ3kubWU6ODUzCi9kbnMtcXVlcnk'

	[static.'dnscrypt.nl-ns0-doh']
	stamp = 'sdns://AgcAAAAAAAAADjEwOC42MS4xOTkuMTcwID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4D2RvaC5kbnNjcnlwdC5ubAovZG5zLXF1ZXJ5'

	[static.'gridns-sg']
	stamp = 'sdns://AgMAAAAAAAAADDE2Ny45OS4zMS42OSA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBFzZy5kbnMuZ3JpZC5pbi50aAovZG5zLXF1ZXJ5'

	[static.'publicarray-au-doh']
	stamp = 'sdns://AgcAAAAAAAAAETM1LjIwMS4yMC4xNzk6NDQzAAtkb2guc2VieS5pbwovZG5zLXF1ZXJ5'

When I add all these server to "dnscrypt-proxy.toml" ...it won't work...

Only when I select 3-4 server at one time then it goes, when I add all these server then it won't working.

A good option would be if a selected dns-server automatically switches to the next working dns-server

when offline.

Some Idea how can I create my own CUSTOM-RESOLVER-list?

**Comment by ghost** [comment]
My idea at custom static-resolver-list:

Example of the file:

#//dnsCRYPT-PROXY "static-RESOLVERS"//#

####//:	SOURCE from: "/etc/dnscrypt-proxy/static-resolvers.md"

	[sources.'static-resolvers']
	urls = ['/etc/dnscrypt-proxy/static-resolvers.md']
	cache_file = 'static-resolvers.md'

How do I have to write it correctly so that I can use my custom-static-resolver-list with
dnsCRYPT-PROXY v2?

How to change URL to path Dir, what must i write in the file?

**Comment by cokeflash** [comment]
I can't get it work with server_name in .toml config-file, what is wrong?

server_names = ['aaflalo-me', 'arvind-io', 'cs-caeast', 'cs-cawest', 'cs-cfi', 'cs-ch', 'cs-dk2', 'cs-fi', 'cs-lv', 'cs-nl', 'cs-pl', 'cs-pt', 'cs-ro', 'cs-rome',
'de.dnsmaschine.net', 'dnscrypt.ca-1', 'dnscrypt.ca-2', 'dnscrypt.eu-dk', 'dnscrypt.eu-nl', 'dnscrypt.me', 'dnscrypt.nl-ns0', 'dnscrypt.eu-dk-ipv6', 'dnscrypt.nl-ns0-ipv6',
'securedns-ipv6', 'zeroaim-ipv6', 'dnscrypt.ca-2-ipv6', 'doh-crypto-sx', 'doh-ibksturm', 'dnscrypt.nl-ns0-doh', 'gridns-sg', 'publicarray-au-doh',]

[static]

####//: ipv4-SERVER

	[static.'aaflalo-me']
	stamp = 'sdns://AgMAAAAAAAAADjE3Ni41Ni4yMzYuMTc1ID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4DmRucy5hYWZsYWxvLm1lCi9kbnMtcXVlcnk'

	[static.'arvind-io']
	stamp = 'sdns://AQcAAAAAAAAAEjEzOS41OS4xNi4xMzA6NTM1MyCORifHOIOoUQMIIbpa5-XQQfSq75W3gpAWy2Udh8MoyRkyLmRuc2NyeXB0LWNlcnQuYXJ2aW5kLmlv'

	[static.'cs-caeast']
	stamp = 'sdns://AQIAAAAAAAAADjE2Ny4xMTQuODQuMTMyIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'cs-cawest']
	stamp = 'sdns://AQIAAAAAAAAADzE2Mi4yMjEuMjA3LjIyOCAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM'

	[static.'cs-cfi']
	stamp = 'sdns://AQIAAAAAAAAADTIxMi44My4xNzUuMzEgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz'

	[static.'cs-ch']
	stamp = 'sdns://AQIAAAAAAAAADTE4NS42MC4xNDcuNzcgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz'

	[static.'cs-dk2']
	stamp = 'sdns://AQIAAAAAAAAADzE4NS4yMTIuMTY5LjEzOSAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM'

	[static.'cs-fi']
	stamp = 'sdns://AQIAAAAAAAAADjE4NS4xMTcuMTE4LjIwIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'cs-lv']
	stamp = 'sdns://AQIAAAAAAAAADTgwLjIzMy4xMzQuNTIgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz'

	[static.'cs-nl']
	stamp = 'sdns://AQIAAAAAAAAADjIxMy4xNjMuNjQuMjA4IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'cs-pl']
	stamp = 'sdns://AQIAAAAAAAAACzUuMTMzLjguMTg3IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'cs-pt']
	stamp = 'sdns://AQIAAAAAAAAADTEwOS43MS40Mi4yMjggMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz'

	[static.'cs-ro']
	stamp = 'sdns://AQIAAAAAAAAADDUuMjU0Ljk2LjE5NSAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM'

	[static.'cs-rome']
	stamp = 'sdns://AQIAAAAAAAAADjE4NS45NC4xOTMuMjM0IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw'

	[static.'de.dnsmaschine.net']
	stamp = 'sdns://AQcAAAAAAAAAEzIwOS4yNTAuMjM1LjE3MDo0NDMgz0wbvISl_NVCSe0wDJMS79BAFZoWth1djmhuzv_n3KAiMi5kbnNjcnlwdC1jZXJ0LmRlLmRuc21hc2NoaW5lLm5ldA'

	[static.'dnscrypt.ca-1']
	stamp = 'sdns://AQcAAAAAAAAAFDE5OS4xNjcuMTMwLjExODo1MzUzIHT3RVUXvCb3EXflbXKTJ4hscpFbP0YoMD-RDEfDjoJ5HTIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5jYS0x'

	[static.'dnscrypt.ca-2']
	stamp = 'sdns://AQcAAAAAAAAAFDE5OS4xNjcuMTI4LjExMjo1MzUzIEPVLIJZIpbC22-NSM4iT9zHJibhBvbjiGGT-gCQKWMbHTIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5jYS0y'

	[static.'dnscrypt.eu-dk']
	stamp = 'sdns://AQcAAAAAAAAADDc3LjY2Ljg0LjIzMyA3SFWF47nQiP0lrTawNwH1UgzWSJ6a3VIUV0lVnwqZVSUyLmRuc2NyeXB0LWNlcnQucmVzb2x2ZXIyLmRuc2NyeXB0LmV1'

	[static.'dnscrypt.eu-nl']
	stamp = 'sdns://AQcAAAAAAAAADjE3Ni41Ni4yMzcuMTcxIGfADywhxVSBRd18tGonGvLrlpkxQKMJtiuNFlMRhZxmJTIuZG5zY3J5cHQtY2VydC5yZXNvbHZlcjEuZG5zY3J5cHQuZXU'

	[static.'dnscrypt.me']
	stamp = 'sdns://AQcAAAAAAAAADjk0LjE5OS4yMTMuMTcyIGBM5f1Wb-7SLs4vAJ7gc4hyFSmM5OOLWOvI3Hu5gRVOGzIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5tZQ'

	[static.'dnscrypt.nl-ns0']
	stamp = 'sdns://AQcAAAAAAAAADDQ1Ljc2LjM1LjIxMiBMhPuMBRFd-l-Xxe0DKRNwx4q81k4V3VOrCN5y-4RKyh8yLmRuc2NyeXB0LWNlcnQubnMwLmRuc2NyeXB0Lm5s'

####//: ipv6-SERVER

	[static.'dnscrypt.eu-dk-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAFFsyMDAxOjE0NDg6MjQzOjpkYzJdIDdIVYXjudCI_SWtNrA3AfVSDNZInprdUhRXSVWfCplVJTIuZG5zY3J5cHQtY2VydC5yZXNvbHZlcjIuZG5zY3J5cHQuZXU'

	[static.'dnscrypt.nl-ns0-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAJlsyMDAxOjE5ZjA6NTAwMTozMGE6NTQwMDpmZjpmZTU4OjcxNDBdIEyE-4wFEV36X5fF7QMpE3DHirzWThXdU6sI3nL7hErKHzIuZG5zY3J5cHQtY2VydC5uczAuZG5zY3J5cHQubmw'

	[static.'securedns-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAIVsyYTAzOmIwYzA6MDoxMDEwOjplOWE6MzAwMV06NTM1MyCzpZdpFFdbBInhn66cQ-Z5-vKMVxiXADF_e7SWKR-wlRwyLmRuc2NyeXB0LWNlcnQuc2VjdXJlZG5zLmV1'

	[static.'zeroaim-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAGVsyYTAzOjQwMDA6YjoyMjM6OjFdOjg0NDMgcrQcuGXx2fhX6rmtaP6aPXj8gumVIrn4GIrn6aTB1fUfMi5kbnNjcnlwdC1jZXJ0Lnplcm9haW0uZGUtaXB2Ng'

####//: DoH-SERVER (DNS!over!HTTPZ)

	[static.'dnscrypt.ca-2-ipv6']
	stamp = 'sdns://AQcAAAAAAAAAH1syNjA1OjIxMDA6MDoxOjpiNWFkOjE4ZTJdOjUzNTMgQ9UsglkilsLbb41IziJP3McmJuEG9uOIYZP6AJApYxsdMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNhLTI'

	[static.'doh-crypto-sx']
	stamp = 'sdns://AgcAAAAAAAAADTEwNC4xOS4xOTguMjkgHdhQioxWWQQ5fHhkUeCPV2E888inI_bzef1MOFi2858NZG9oLmNyeXB0by5zeAovZG5zLXF1ZXJ5'

	[static.'doh-ibksturm']
	stamp = 'sdns://AgcAAAAAAAAADzIxNy4xNjIuMjA2LjE3OAAYaWJrc3R1cm0uc3lub2xvZ3kubWU6ODUzCi9kbnMtcXVlcnk'

	[static.'dnscrypt.nl-ns0-doh']
	stamp = 'sdns://AgcAAAAAAAAADjEwOC42MS4xOTkuMTcwID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4D2RvaC5kbnNjcnlwdC5ubAovZG5zLXF1ZXJ5'

	[static.'gridns-sg']
	stamp = 'sdns://AgMAAAAAAAAADDE2Ny45OS4zMS42OSA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBFzZy5kbnMuZ3JpZC5pbi50aAovZG5zLXF1ZXJ5'

	[static.'publicarray-au-doh']
	stamp = 'sdns://AgcAAAAAAAAAETM1LjIwMS4yMC4xNzk6NDQzAAtkb2guc2VieS5pbwovZG5zLXF1ZXJ5'

**Comment by Yinchie** [comment]
You shouldn't set statics. Just configure the server_names which ones you wish to use. Since the servers you have chosen are already known on the public list.

**Comment by ghost** [comment]
i want use this:
server_names = ['aaflalo-me', 'arvind-io', 'cs-caeast', 'cs-cawest', 'cs-cfi', 'cs-ch', 'cs-dk2', 'cs-fi', 'cs-lv', 'cs-nl', 'cs-pl', 'cs-pt', 'cs-ro', 'cs-rome', 'de.dnsmaschine.net', 'dnscrypt.ca-1', 'dnscrypt.ca-2', 'dnscrypt.eu-dk', 'dnscrypt.eu-nl', 'dnscrypt.me', 'dnscrypt.nl-ns0', 'dnscrypt.eu-dk-ipv6', 'dnscrypt.nl-ns0-ipv6', 'securedns-ipv6', 'zeroaim-ipv6', 'dnscrypt.ca-2-ipv6', 'doh-crypto-sx', 'doh-ibksturm', 'dnscrypt.nl-ns0-doh', 'gridns-sg', 'publicarray-au-doh']

how to place this? top of the config file? or bottom?

**Comment by ghost** [comment]
I place it at the top of the config-file.toml but some sites shows me:

Hmm. We’re having trouble finding that site.

We can’t connect to the server at www.dnsleaktest.com.
If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web.

**Comment by cokeflash** [comment]
with server_names in the config-file =  no name_resolution
...without it, no problems with:

[sources]

#server_names = ['aaflalo-me', 'arvind-io', 'cs-caeast', 'cs-cawest', 'cs-cfi', 'cs-ch', 'cs-dk2', 'cs-fi', 'cs-lv', 'cs-nl', 'cs-pl', 'cs-pt', 'cs-ro', 'cs-rome', 'de.dnsmaschine.net', 'dnscrypt.ca-1', 'dnscrypt.ca-2', 'dnscrypt.eu-dk', 'dnscrypt.eu-nl', 'dnscrypt.me', 'dnscrypt.nl-ns0', 'doh-crypto-sx', 'doh-ibksturm', 'dnscrypt.nl-ns0-doh', 'gridns-sg', 'publicarray-au-doh']

####//:	REMOTE-SOURCE from: https://github.com/DNSCrypt/dnscrypt-resolvers (ONLINE)

	[sources.'public-resolvers']
	urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
	cache_file = 'public-resolvers.md'
	minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
	refresh_delay = 72

**Comment by ghost** [comment]
I can't get dnsCRYPT-PROXY to work with "server_names"

**Comment by Haraade** [comment]
A good start will be to remove # in front of server_names =

**Comment by ghost** [comment]
yes, that I have @ Haraade ;-) :-P

I got it now:  some dnsCRYPT-PROXIES in the LIVE server-list won't working @me.

server_names = ['arvind-io', 'cloudflare', 'de.dnsmaschine.net', 'dnscrypt.ca-1', 'dnscrypt.ca-2', 'dnscrypt.eu-nl', 'dnscrypt.me', 'dnscrypt.nl-ns0', 'freetsa.org', 'ibksturm', 'publicarray-au', 'publicarray-au2', 'scaleway-fr', 'securedns']

now its working fine :)

**Comment by ghost** [comment]
...which online resolver-list  URL is up-to-date with all working dnsCRYPT-PROXY-server?

**Comment by Yinchie** [comment]
The one that is already listed in the config because that is the only one.

**Comment by ghost** [comment]
many dnsCRYPT-SERVER in the online-resolver-list are not working at me, TIMEDOUT, unreachable...

**Comment by Yinchie** [comment]
Why does that matter if you only pick the ones you want to use with server_names?
Even without using server_names DNSCRYPT proxy doesn't choose a server that doesn't work.

**Comment by ghost** [comment]
I want use only dnscrypt-servers that I'm could trust. 

A new feature would be good for dnscrypt-proxy which implements a option for automatically select the most secure dnscrypt-proxy server.

**Comment by Yinchie** [comment]
You can use server_names as mentioned to choose which ones to use that you trust. Why add something that is not needed. DNSCRYPT doesn't know which one is more secure than others. It can all be configured in the toml file. See example toml file.

From what I can understand you don't fully understand how configuration works.

**Comment by jedisct1** [comment]
Read the [configuration](https://github.com/jedisct1/dnscrypt-proxy/wiki/Configuration) section in the documentation. Not just the first page; go through all the pages and examples to better understand how it works.
