### ISSUE TITLE
feature request (again): support for android 4.4.*

### ISSUE THREAD

**Issue by admzzz** [DNSCrypt/dnscrypt-proxy#577]
@jedisct1,
i'd googled two flags for ndk: 
-D__ANDROID_API__=19
-DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=gold" 
and two for golang:
export GOARM=7 
export GOARCH=arm
could they solve the problem?

i dunno golang at all, maybe you'll get them a try?

...i guess that there should be at least one or two workarounds... ;-)

my failed first attempt:

```
export NDK_TOOLS=android-ndk-r18-beta2
export NDK_STANDALONE=/home/admz/build/android-ndk-r18-beta2
export PATH=$PATH:$NDK_STANDALONE/arm/bin
export INSTALL_DIR=/home/admz/build/ndk-standalone-r18-beta2
export MAKE_TOOLCHAIN=$NDK_TOOLS/build/tools/make_standalone_toolchain.py
cd $NDK_TOOLS
python $MAKE_TOOLCHAIN --arch arm --install-dir $INSTALL_DIR/arm
```
**WARNING:__main__:Defaulting to target API 16 (minimum supported target for arm)**

```
cd ../dnscrypt-proxy-src/
#export CC=arm-linux-android-clang
#export CCX=arm-linux-android-clang++
export CC=arm-linux-androideabi-clang
export CCX=arm-linux-androideabi-clang++
export GOPATH=$PWD
export CGO_ENABLED=1
export GOOS=android
export GOARCH=arm
export GOARM=7
cd src/dnscrypt-proxy
go clean
go build -ldflags="-s -w" -o $GOPATH/android-arm/dnscrypt-proxy
```
**xtransport.go:5:2: cannot find package "context" in any of:
	/home/admz/build/dnscrypt-proxy-src/src/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/admz/build/dnscrypt-proxy-src/src/context (from $GOPATH)**

$GOROOT was not mentioned in the wiki at all - had to be?

**Comment by jedisct1** [comment]
I don't know much about Android, sorry.

But looks like you are onto something! Keep googling and trying (since you even have a device to test on) until you succeed!

**Comment by admzzz** [comment]
@jedisct1,
the problem not in android (the latest ndk-rc18-beta supports api 16 without any compilation flags), but in go (which i do not know at all) - answer about $GOROOT at least, please, where it had to point on linux (i'm crosscompiling for arm)?

```
$ go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="android"
GOPATH="/home/admz/build/dnscrypt-proxy-src"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="arm-linux-android-clang"
GOGCCFLAGS="-fPIC -marm -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by jedisct1** [comment]
Maybe your Go version is too old? The current stable version is 1.10.3.

**Comment by jedisct1** [comment]
`GOROOT` should be a writable directory. I use `~/go`. But I heard it's not required any more.

**Comment by admzzz** [comment]
@jedisct1 
$ go version
go version go1.6.2 linux/amd64

thank you, all compiles cleanly with go 1.10.3 and it WORKS at last ;-)
$ file dnscrypt-proxy 
dnscrypt-proxy: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
$ ll dnscrypt-proxy 
-rwxr-xr-x 1 admz admz 7891080 авг 24 12:59 /home/admz/build/dnscrypt-proxy-src/android-arm/dnscrypt-proxy*

**Comment by admzzz** [comment]
@jedisct1 
will you recompile binary for android api 16 yourself with the latest ndk rc18-beta2 and put it on the download page, or you'll use mine?
[dnscrypt-proxy-2.16-api_16.zip](https://github.com/jedisct1/dnscrypt-proxy/files/2317993/dnscrypt-proxy-2.16-api_16.zip) - erroneos name of the zip, had to be _dnscrypt-proxy-2.0.16-api_16.zip_
[dnscrypt-proxy-2.0.16-api_19.zip](https://github.com/jedisct1/dnscrypt-proxy/files/2321095/dnscrypt-proxy-2.0.16-api_19.zip)

**Comment by jedisct1** [comment]
I didn't upload anything, these files are built automatically by the continuous integration system.

**Comment by admzzz** [comment]
@jedisct1 ,
can you change the version of ndk to the latest android-ndk-r18-beta2 for this "continuous integration system"?
or add for the current ndk previously mentioned flag -D__ANDROID_API__=19 ?

**Comment by jedisct1** [comment]
Does it work with r17b?

**Comment by admzzz** [comment]
guess that it had to:

```
$ python $MAKE_TOOLCHAIN -help
usage: make_standalone_toolchain.py [-h] --arch {arm,arm64,x86,x86_64}
                                    [--api API] [--stl STL] [--force] [-v]
                                    [--package-dir PACKAGE_DIR | --install-dir INSTALL_DIR]
make_standalone_toolchain.py: error: argument -h/--help: ignored explicit argument 'elp'

```
api 19 only, lower numbers are supported only in rc18-beta*

**Comment by jedisct1** [comment]
Is it intentional?

I'm a little bit surprised that *newer* NDKs are adding support for old, unsupported targets, whereas Google constantly *removes* support for older targets everywhere else.

I fear this is just a mistake in that beta version, that will go away in the actual release.

**Comment by admzzz** [comment]
yes, it is intentional: check discussion in the links about  Android NDK r15c on https://github.com/jedisct1/dnscrypt-proxy/wiki/Building-the-Android-version-on-non-Android-OS - i'd start my yesterday's googling there.

jfyi: android 4.* still keeps a little less than a quarter of all android devices.

https://gist.github.com/admzzz/6f2eb8ce85f846199c1d086b67a9c069 - do not delete this issue, pls., i'd referenced it and maybe will enlarge my gist with the proper afwall's start-stop scripts for dnscrypt-proxy (they depend on android's version, for android 4.* dnscrypt-proxy could be started on the 53 port).

**Comment by admzzz** [comment]
@jedisct1 ,
just for fun (and as i'm living on android 4.4.2 ;-) ) i compiled an arm for api 19 with go 1.11 - the binary is 2mb bigger than yestearday's build, can you suppose/explain why? or tell the proper optimization's keys?

btw (looking at your latest commits): key -D__ANDROID_API__=19 had to be used in compiling standalone ndk.

**Comment by jedisct1** [comment]
Sorry, I'm not exactly a Go expert. How do you add `-D__ANDROID_API__=19`?

**Comment by admzzz** [comment]
once again:
i'd found in the mentioned above discussions that -D__ANDROID_API__=19 had to be added during compilation of the old standalone ndk,  as i'm using the latest one, i never tried it and used native command:
python $MAKE_TOOLCHAIN --arch arm --api 19 --install-dir $INSTALL_DIR/arm

my googling of the subject a week ago started on https://github.com/android-ndk/ndk/issues/602#issuecomment-352594475 - there's a link in a dnscrypt-proxy's wiki leading there.

i think that it had to be used in LDFLAGS , maybe accompanying switching to ld.gold
