### ISSUE TITLE
Help wanted (golang): send HTTP/2 padded frames

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#58]
I don't think the high-level `net/http` API, that we use in `XTransport` (itself used for all requests) uses padded HTTP/2 frames.

The low-level `x/net/http2` API does support padded frames though: https://godoc.org/golang.org/x/net/http2#Framer.WriteDataPadded

Padding would be useful for DoH.

**Comment by thuantran** [comment]
https://developers.google.com/speed/public-dns/docs/dns-over-https this random_padding?

**Comment by jedisct1** [comment]
No. [HTTP/2 padding](https://tools.ietf.org/html/rfc7540#section-6.1).

**Comment by thuantran** [comment]
I see, but will achieve the same purpose. In any case, if golang API does support the rfc way, better go with it :).

**Comment by jedisct1** [comment]
Zero progress on that one, so I lost hope. Closing.
