### ISSUE TITLE
Whitelist of domains using URLs of data sources

### ISSUE THREAD

**Issue by dimqua** [DNSCrypt/dnscrypt-proxy#582]
Instead of manually put domains into a `domains-whitelist.txt` file, I get them from the sources such as [uBlock Unbreak](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt) and [Brave Unblock](https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt), using external script. But it's probably a quite useful feature to implement in `generate-domains-blacklist.py` script.

**Comment by jedisct1** [comment]
Since it can trivially be done with external scripts, I'm not sure that it's worth adding bloat to the proxy, especially since it would be very limited compared to what can be done with scripts.

**Comment by dimqua** [comment]
Sorry, I meant not dnscrypt-proxy itself, but `generate-domains-blacklist.py` script (which is handle various data sources to generate blacklists).

**Comment by jedisct1** [comment]
Because unless you reimplement a full shell, you will always be more limited than what the shell can do.

**Comment by dimqua** [comment]
Sorry, I meant not dnscrypt-proxy itself, but `generate-domains-blacklist.py` script (which is handle various data sources to generate blacklists).

**Comment by jedisct1** [comment]
I think you can already use `--whitelist https://...`.

**Comment by dimqua** [comment]
@jedisct1 I can't specify multiple URLs for some reason, in this case only the first one is used:
`generate-domains-blacklist.py -w https://... -w https://... > list.txt`

**Comment by dimqua** [comment]
@jedisct1 I can't specify more than one whitelist source for some reason.

**Comment by jedisct1** [comment]
The reason is that you haven't implemented support for this yet :)
