### ISSUE TITLE
Wiki: Small Issue with Filter Patterns Explanation

### ISSUE THREAD

**Issue by jrnewell** [DNSCrypt/dnscrypt-proxy#587]
> ads[0-9]\*| matches "ads" followed by one or more digits 

This isn't 100% correct because the code is using file system globbing and not regex, it actually matches "ads[0-9]" then any number of characters including non-digits, so "ads4blah" will match.

I came across this because I was trying to come up with a pattern to match subdomain.xxx only one level deep (i.e. not match subdomain.example.com), but it doesn't seem possible.

**Comment by jedisct1** [comment]
Could you fix it?

**Comment by jrnewell** [comment]
Do you want to correct the wiki or add optional regex filters?

**Comment by jrnewell** [comment]
never mind, i just updated the wiki :)
