### ISSUE TITLE
blacklist_file : same for adr and ip rules?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#59]
dnscrypt-proxy-win64-2.0.0beta12 / dnscrypt-proxy.toml

```
[blacklist]
## Path to the file of blocking rules (absolute, or relative to the same directory as the executable file)
# blacklist_file = 'blacklist.txt'
```

```
[ip_blacklist]
## Path to the file of blocking rules (absolute, or relative to the same directory as the executable file)
# blacklist_file = 'ip-blacklist.txt' 
```

Does this mean that the same _blacklist_file_ is used for address and IP rules?

Thanks

**Comment by jedisct1** [comment]
No.

As you can see, they are different files, and they are configured in different sections.

**Comment by Ainatar** [comment]
Hi, one doubt. What happens if by mistake you put an ip in the blacklist, or a domain in the ip blacklist?

**Comment by ghost** [comment]
> As you can see, they are different files, and they are configured in different sections.

Different files for a same constant _blacklist_file_ ...
I ignored that that a same constant would be treated differently depending on its section.
OK, Franck, thanks.

While we're at it (I won't open an issue just for this simple question):

```
[sources]
  [sources.'public-resolvers']
  url = 'http://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
```
https is valid, may I use it instead?
Merci bien.

**Comment by jedisct1** [comment]
You can certainly use `https`.

The reason it uses HTTP by default is that some routers don't have a clock, so they can't use HTTPS right after having started (HTTPS requires to know the current date).
