### ISSUE TITLE
Is there an API documentation?

### ISSUE THREAD

**Issue by kar** [DNSCrypt/dnscrypt-proxy#591]
Hi, I am considering integrating dnscrypt-proxy into my app, but I can't find any API docs / reference / guide. Am I missing something or it's not available?

**Comment by jedisct1** [comment]
Hi!

Can you clarify what you mean by API? `dnscrypt-proxy` is an app, not a library nor a web service, so I'm a little bit confused here :)

The protocol itself is documented here: https://raw.githubusercontent.com/DNSCrypt/dnscrypt-protocol/master/DNSCRYPT-V2-PROTOCOL.txt
