### ISSUE TITLE
Documentation on wiki: please expand setup information on PFSense

### ISSUE THREAD

**Issue by srk** [DNSCrypt/dnscrypt-proxy#596]
The information provided on the wiki on how to set up dsncrypt-proxy on PFSense seems incomplete. Specifically, it is missing information about how to change the PFSense settings through the GUI so that the installed 'dnscrypt-proxy' executable will be used as the default DNS server.

**Comment by jedisct1** [comment]
Did you manage to do it? Using the GUI?

**Comment by srk** [comment]
No. Having configured dnscrypt-proxy.toml to use 127.0.0.1:53 it was unclear as to whether I should be setting up the 'DNS Resolver' as 127.0.0.1, or using something like 127.0.0.2:53 in the .toml file and setting up the 'DNS forwarder' to look at that address. I have 127.0.0.1 set up as the first DNS server in my 'General/DNS' together with a few fallbacks (8.8.8.8 and so on). Testing the DNS resolution via the Diagnostics menu shows that a lookup of, say, www.yahoo.com skips right past 127.0.0.1 and gets resolved OK by the fallback DNS servers.
Running dnscrypt-proxy from the command line works just fine, except now it only seems to pick up responses from DoH servers,

**Comment by bdossantos** [comment]
Maybe this could help https://github.com/bdossantos/pfsense-dnscrypt-proxy
