### ISSUE TITLE
Child process not terminated when parent recieves SIGTERM while run on OpenWRT

### ISSUE THREAD

**Issue by crass** [DNSCrypt/dnscrypt-proxy#597]
When dnscrypt-proxy is run with the `user_name` option configured a child process with reduced privileges is spawned.  When the parent process is killed with a TERM signal, only the parent process is killed, but not the child process.  This is a problem when trying to restart the process because the old child process prevents the new one from binding to the listening port causing the new process to fail.

Also there is no `service` executable normally used to do init management.  So `dnscrypt-proxy -service stop` fails.  I'd suggest that there be fallback code that does the cleanup internally.  Or perhaps add openwrt's `procd` init system support.

**Comment by crass** [comment]
Another option would be to have the pidfile written contain the pid of the child process because the parent exits when the child exits.

**Comment by jedisct1** [comment]
This is a known problem. We tried, but couldn't get this to work reliably everywhere.

If you know how to do this, please submit a pull request (either here, or to the `service` module). Thanks!
