### ISSUE TITLE
After Update... dnsCRYPT-PROXY fails after BOOT but Service is is not loaded correctly

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#598]
dnscrypt-proxy.service - ####//dnsCRYPT-PROXY [SERVICE] (client)
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor p
   Active: activating (auto-restart) (Result: exit-code) since Fri 2018-09-28 20
 Main PID: 1315 (code=exited, status=255)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/dnscrypt-proxy.service

Hi! PLS PLS help!

Version:  2.0.16~ppa1~bionic OS: Ubuntu

I got an Update via Update-Manager of "dnsCRYPT-PROXY" Update was installed but
after BOOT, the Service of "dnsCRYPT-PROXY" not responding well, sometimes it worked after BOOT, sometimes not. 
Then I have to disconnect my Network via NetworkManager and stop "dnsCRYPT-PROXY" and start it again, then the Service was loaded and runs. 
After that I must wait a while until internet is online.

Error:

dnscrypt-proxy.service - ####//dnsCRYPT-PROXY [SERVICE] (client)
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor p
   Active: activating (auto-restart) (Result: exit-code) since Fri 2018-09-28 20
 Main PID: 1315 (code=exited, status=255)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/dnscrypt-proxy.service
   
My .service CONFIG:

[Unit]
Description=####//dnsCRYPT-PROXY [SERVICE] (client)
ConditionFileIsExecutable=/etc/dnscrypt-proxy/dnscrypt-proxy

[Unit]
Description=####//dnsCRYPT-PROXY [SERVICE] (client)
ConditionFileIsExecutable=/etc/dnscrypt-proxy/dnscrypt-proxy

[Service]
NonBlocking=true
Group=nogroup
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/etc/dnscrypt-proxy/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml

####//: SeCUrITy
CapabilityBoundingSet=CAP_IPC_LOCK CAP_SETGID CAP_SETUID CAP_NET_BIND_SERVICE
InaccessiblePaths=/boot
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
PrivateTmp=true
PrivateDevices=true
MemoryDenyWriteExecute=true
NoNewPrivileges=true
RestrictRealtime=true
RestrictAddressFamilies=AF_INET
RestrictAddressFamilies=~AF_INET6
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @ipc @module @mount @obsolete @raw-io

WorkingDirectory=/etc/dnscrypt-proxy

Restart=always
RestartSec=10
EnvironmentFile=-/etc/sysconfig/dnscrypt-proxy

[Install]
WantedBy=multi-user.target

What is wrong with my settings in the .service file?

On my Debian OS in VirtualBox the same settings are working.

On my Host-PC with Ubuntu not correctly. Before the Update I had no problems with that.

**Comment by jedisct1** [comment]
Can you uninstall everything, including all the systemd changes you made, and follow the [generic installation instructions for Linux](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux) ?

**Comment by ghost** [comment]
I uninstalled "dnsCRYPT-PROXY" from Synaptic, removed PPA ShevChuck.
Deleted: /etc/dnscrypt-proxy

Create folder in: /opt/dnscrypt-proxy
Downloaded "dnsCRYPT-PROXY" from:  https://github.com/jedisct1/dnscrypt-proxy/releases/tag/2.0.16
Extracted to: /opt/dnscrypt-proxy

Pasted my old config files in it.

Created dnscrypt-proxy.service in: /etc/systemd/system/

Put in my old values.

Edited: /lib/systemd/system/unbound.service

Put in it:  After=network.target dnscrypt-proxy.service

Rebooted and "dnsCRYPT-PROXY service is running now after BOOT and Internet is fast online.

**Comment by jedisct1** [comment]
Good, but the instructions never told you to do create systemd files.
