### ISSUE TITLE
dnscrypt start or restart show setting info

### ISSUE THREAD

**Issue by phonphen** [DNSCrypt/dnscrypt-proxy#6]
please add info what setting is saved, when dnscrypt start or restart

and thank you for v2 👍

**Comment by jedisct1** [comment]
Hi @phonphen 

Can you clarify what you mean? What settings are you referring to? What would you like to be saved?

**Comment by phonphen** [comment]
i am sorry for my bad language
i mean when dnscrypt start or restart, just print info what config in dnscrypt-proxy.toml
for example: dnscrypt print info when start, blacklist active or not


in ver 1x, when dnscrypt start, print info, plugin for blacklist is loaded
but in ver2, blacklist is build in feature in dnscrypt, and dnscrypt dont show info that blacklist is active

**Comment by elmakong** [comment]
probably some debug information such as:

> Loaded config file: [file path]/dnscrypt-proxy.toml
> require_dnssec: false
> require_nolog: true
>
> Query logging: [on]
> Logfile: [filepath]/query.log
>
> Blacklist: [on]
> Rules: [file path]/blacklist.txt
> Logfile: [filepath]/blocked.log

 etc

so the information can be read at start. probably also adding the service log(as it cant be seen if started on windows services window)

**Comment by phonphen** [comment]
@elmakong, that what i mean 😄 
thanks for explanation

or maybe can add some command, like `dnscrypt-proxy -showinfo` to print info like that

**Comment by elmakong** [comment]
i guess there is no need for this feature as it is just some information. if you believe your configuration in the toml file are correct, it will be working just fine.
back to my suggestion tho, if those information is needed, maybe adding a service log feature would be great. not just query and blacklist logging. also, it would be great if there is one option to just enable/disable the feature without commenting the line?

**Comment by jedisct1** [comment]
I'm a little bit confused about why such a feature would be useful?

Why not just open the configuration file, especially since everything is at the same place?

If you want more logs, you can always use `-loglevel=1`.

**Comment by r13s** [comment]
And if dnscrypt-proxy is installed as a Windows service?

The -loglevel option only works when the program is launched from the console. When the program starts as a Windows service, -loglevel and -logfile do not work.

How to track possible errors at startup, if there are no logs?

**Comment by jedisct1** [comment]
You want an option to store logs to a file, or to the Windows logger. This is a completely different thing from printing the configuration file.

**Comment by jedisct1** [comment]
Closing this until 2.0.0 is released.

Please, only bugs for now.

**Comment by elmakong** [comment]
> I'm a little bit confused about why such a feature would be useful?

probably for a replacement of an GUI i guess..maybe in the future after stable version is out
