### ISSUE TITLE
Elevated privileges possible issue, on my side

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#60]
dnscrypt-proxy-win64-2.0.0beta12.zip / Windows 7 (x64)

I've encountered a big issue when running service-install.bat, it's obviously my system's fault, I'd like to ask you diagnose the cause, I have a possible explanation.

Running service-install.bat opened of course the console window but it entered in an infinite loop. I couldn't access anything, I tried to stop the process with Task Manager, this one was immediately covered by the console, no way out I had to hard close (button) the computer.

All three bat files (install, restart, uninstall) include:
```
:ELEVATE
ECHO Elevated privileges are temporarily required, just to register or remove the dnscrypt-proxy service
CD /d %~dp0
MSHTA "javascript: var shell = new ActiveXObject('shell.application'); shell.ShellExecute('%~nx0', '', '', 'runas', 1); close();"
EXIT
```
Des this happen to require Windows Script Host? I had disabled Script Host at a time I was in a "Secure all you can" period. 
```
;Disable Windows Script Host
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Script Host\Settings]
"Enabled"=dword:00000000
```
Anyway, could a disabled Script Host be the cause of my issue?

Concerning Elevated privileges, is it required on a system which has UserAccountControl UAC disabled? If not I could simply remove these lines from the bat files.

I'm a basic user trying to deploy a nice but technically advanced tool, updating it from ver. 1.9.5.
I want V2 but I lack knowledge to explain what happened here.

Thanks for your advice/help.

**Comment by ghost** [comment]
@mazesy 

Hi! 👍  yes I think it's Windows Script Host. If I recall correctly ShellExecute is used in both jscript and vbscript.

Have you tried enabling it? You need to delete the key to enable it again.

In elevated command prompt line:

REG DELETE “HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Script Host\Settings” /v Enabled /f

**Comment by jedisct1** [comment]
The scripts are just for convenience. You don't have to use them, especially if they require changes to your system.

**Comment by ghost** [comment]
Hi @mastad0n , @jedisct1 

Because I've disabled my UAC since always the script for enabling Elevated Privileges is obsolete.
Hence, I call service-install/restart/uninstall as I used to with DNSCrypt 1.9.5, and all is fine

service-install.bat
```
@echo off
cmd.exe /c "dnscrypt-proxy.exe -service install"
cmd.exe /c "dnscrypt-proxy.exe -service start"
cmd.exe /c "c:\Program Files (x86)\DnsJumper\DnsJumper.exe" 127.0.0.1
```

service-restart
```
@echo off
cmd.exe /c "dnscrypt-proxy.exe -service restart"
```

service-uninstall
```
@echo off
cmd.exe /c "dnscrypt-proxy.exe -service stop"
cmd.exe /c "dnscrypt-proxy.exe -service uninstall"
cmd.exe /c "c:\Program Files (x86)\DnsJumper\DnsJumper.exe" 9.9.9.9,149.112.112.112
```

DnsJumper.exe is an external DNS configurator which may be run from a bat file, which simplifies the operation.

I'm running right now dnscrypt-proxy-win64-2.0.0rc and it's brilliant. Daddy 1.9.5 has retired :=)

Thanks!
