### ISSUE TITLE
Unable to build with go 1.11

### ISSUE THREAD

**Issue by dvzrv** [DNSCrypt/dnscrypt-proxy#600]
I'm currently attempting a rebuild of the dnscrypt-proxy package on Arch Linux (version 2.0.16).
However, this fails with go 1.11:
`github.com/aead/poly1305.supportsAVX2: relocation target runtime.support_avx2 not defined`

This seems to be the same issue: https://github.com/minio/highwayhash/issues/6

It would be great, if this could be fixed in an upcoming release to the software. Thanks!

**Comment by jedisct1** [comment]
It has already been fixed. Update your repository :)

**Comment by dvzrv** [comment]
Eh... repository? I'm building from the 2.0.16 tarball for the package!

**Comment by jedisct1** [comment]
2.0.16 was released before Go 1.11 :)

Maybe we can tag a new version, but it would be great to fix the `user_name` issues in order to better justify a new version.

Unfortunately, I lost hope that we will eventually be able to make that feature work.

**Comment by dvzrv** [comment]
Well, whatever causes this behavior: I'm unable to build 2.0.16 because of this.
You did update the dependencies for dnscrypt-proxy after the release, I see. If that fixes this issue, it would sure be a good idea to tag a new release!
