### ISSUE TITLE
Main process exited

### ISSUE THREAD

**Issue by poentodewo** [DNSCrypt/dnscrypt-proxy#601]
just tryng from 76fdb51 commit and got error

`Oct  3 21:27:17 raspberrypi dnscrypt-proxy[4832]: [2018-10-03 21:27:17] [NOTICE] Loading the set of forwarding rules from [forwarding-rules.txt]
Oct  3 21:27:17 raspberrypi dnscrypt-proxy[4832]: [2018-10-03 21:27:17] [NOTICE] Loading the set of IP blocking rules from [dnscrypt-blacklist-ip.txt]
Oct  3 21:27:17 raspberrypi dnscrypt-proxy[4832]: [2018-10-03 21:27:17] [FATAL] user: Current not implemented on linux/arm
Oct  3 21:27:17 raspberrypi systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
Oct  3 21:27:17 raspberrypi systemd[1]: dnscrypt-proxy.service: Unit entered failed state.
Oct  3 21:27:17 raspberrypi systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.`

reverb to build  c043bd7 no error
how to produce I was stop and uninstall before upgrade

add binary to /opt/dnscrypt-proxy

sudo ./dnscrypt-proxy -service install

sudo ./dnscrypt-proxy -service start

**Comment by jedisct1** [comment]
Stick to releases...

Development versions are rarely tested on Linux, except before a new release.

**Comment by poentodewo** [comment]
@jedisct1 oke Thanks
