### ISSUE TITLE
Anonymize DNS via Tor?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#603]
Hi. 

I want to know if I can combine DNScrypt with Pihole+Unbound+"DNS over Tor"? 

I'd like to try DNS over Tor. 
Would that be safe? 

DNScrypt+Pihole with Unbound works very well for me.

**Comment by jedisct1** [comment]
All you have to do is uncomment that line: https://github.com/jedisct1/dnscrypt-proxy/blob/b81a72cc3e6b95ac83d677f25e3052695cd2a017/dnscrypt-proxy/example-dnscrypt-proxy.toml#L88-L92

As well as use `force_tcp=true` since Tor doesn't support UDP.

**Comment by ghost** [comment]
When I set this:

proxy = "socks5://127.0.0.1:9050"
force_tcp = true

In my web-browser I can't open websites. Nothing happend.

With this setting it is working:
#proxy = "socks5://127.0.0.1:9050"
force_tcp = false

**Comment by ghost** [comment]
Must I change something in the torrc-file of TOR?

**Comment by jedisct1** [comment]
I don't think so. I just start `tor` without any configuration file (the only one I see is `torrc.sample` which seems to be an example).

**Comment by ghost** [comment]
hmm... I'm running Pi-Hole with Unbound+DNScrypt together.

What can I do to get it work with route dns-traffic over tor and dnscrypt to work with Unbound+Pihole?

In dnscrypt-proxy.toml... it don't work for me:

proxy = "socks5://127.0.0.1:9050"
force_tcp = true

But Tor @ 127.0.0.1:9050 is working standalone also when I try it with another Browser.

**Comment by jedisct1** [comment]
I don't know much about Linux and never used Pi-Hole, but just for you, I installed Raspbian and Pi-Hole.

After the installation, I added Tor:

```sh
apt install tor
```

I didn't edit any configuration files at this point

I then followed the instructions from Pi-hole's Wiki to install dnscrypt-proxy: https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0

The only changes I made to the configuration file:

```toml
 listen_addresses = ['127.0.0.1:5300', '[::1]:5300']
force_tcp = true
proxy = "socks5://127.0.0.1:9050"
```

The original Wiki instructions used port `5353` as an example, but it didn't work for me, something was already listening to port 5353, so I used `5300` instead and updated the Wiki accordingly.

And it worked. If I stop the `tor` process, nothing resolves any more (besides what has  been cached), so I guess all the DNS queries go through Tor as expected.

So, if you follows these instructions, it should work as well :)

**Comment by ghost** [comment]
My config:

Route goes to...
01. Host
to

02. Pi-hole
to

03. Pihole DNS-custom1 = 192.168.178.1#53 (Router)

04. From Router = 192.168.178.1#53
to

05. Pi-hole DNS-custom2 = 127.0.0.1#5353 (Unbound)
to

06. Unbound

07. Unbound forwards DNS to dnsCRYPT-PROXY with
listen_addresses = ['127.0.0.1:54']

I'll try it out what you have posted ;-)

**Comment by ghost** [comment]
I add to /etc/tor/torrc = 

DNSPort 127.0.0.1:9054

Changed in dnscrypt-proxy.toml:

proxy = "socks5://127.0.0.1:9051"

force_tcp = true

I try to open a webpage but nothing appears.

**Comment by ghost** [comment]
tor.log says:
Oct 06 22:28:51.000 [notice] Tor 0.2.9.16 (git-9ef571339967c1e5) opening new log file.
Oct 06 22:28:51.766 [notice] Tor 0.2.9.16 (git-9ef571339967c1e5) running on Linux with Libevent 2.0.21-stable, OpenSSL 1.1.0f and Zlib 1.2.8.
Oct 06 22:28:51.767 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Oct 06 22:28:51.767 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Oct 06 22:28:51.767 [notice] Read configuration file "/etc/tor/torrc".
Oct 06 22:28:51.771 [warn] You have asked to exclude certain relays from all positions in your circuits. Expect hidden services and other Tor features to be broken in unpredictable ways.
Oct 06 22:28:51.771 [notice] Opening Socks listener on 127.0.0.1:9051
Oct 06 22:28:51.771 [notice] Opening DNS listener on 127.0.0.1:9054
Oct 06 22:28:51.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.
Oct 06 22:28:51.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.
Oct 06 22:28:52.000 [notice] Bootstrapped 0%: Starting
Oct 06 22:28:52.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Oct 06 22:28:52.000 [notice] Signaled readiness to systemd
Oct 06 22:28:52.000 [notice] Opening Socks listener on /var/run/tor/socks
Oct 06 22:28:52.000 [notice] Opening Control listener on /var/run/tor/control
Oct 06 22:28:53.000 [notice] 22 entries in guards
Oct 06 22:28:53.000 [notice] Bootstrapped 85%: Finishing handshake with first hop
Oct 06 22:28:53.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Oct 06 22:28:53.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Oct 06 22:28:53.000 [notice] Bootstrapped 100%: Done

**Comment by ghost** [comment]
From this tutorial:  https://github.com/pi-hole/pi-hole/wiki/DNS-over-Tor
...it says I have to add the "socks5 IP 127.0.0.1:9051" into my Pihole custom DNS-settings to get it work.
But in my Pi-hole custom DNS-settings are:
DNS 1:  192.168.178.1#53 (Router)
DNS 2:  127.0.0.1#5353 (Unbound)  ...forwards to dnsCRYPT-PROXY with 127.0.0.1:54 ...then from

dnsCRYPT-PROXY routing to DNS-over-Tor with "proxy = "socks5://127.0.0.1:9051" ???

But why it will not work?
Some idea?

**Comment by ghost** [comment]
TOR is running without errors...
dnsCRYPT-PROXY is running without errors...
Pi-Hole is running without errors...

Don't work :-(
proxy = "socks5://127.0.0.1:9051"
force_tcp = true

Result in WebBrowser = Hmm. We're having trouble finding that site.

Web-Browsing works with:
#proxy = "socks5://127.0.0.1:9051"
force_tcp = false

**Comment by jedisct1** [comment]
Don't mix and match different tutorials.

The first one says to configure only one upstream, `127.0.0.1#5300`, so try to do that.

Also try without Unbound first. dnscrypt-proxy has a built-in cache, so you're just wasting memory anyway.

**Comment by ghost** [comment]
I set it up:

Pi-Hole Custom 1 DNS: 127.0.0.1#5300 (Upstream)

.toml Config
listen_addresses = ['127.0.0.1:5300']
force_tcp = true
proxy = "socks5://127.0.0.1:9051"

Don't work :-(

Error-message:  Hmm. We're having trouble finding that site.

**Comment by jedisct1** [comment]
By default it is `proxy = "socks5://127.0.0.1:9050"`

**Comment by ghost** [comment]
TOR.log says:

[notice] Tried for 41 seconds to get a connection to [scrubbed]: 853 - Giving up...
[warn] Your application (using socks5 to port 443) is giving Tor only an IP address....

**Comment by ghost** [comment]
> By default it is `proxy = "socks5://127.0.0.1:9050"`

Yes but on my HOST I use 9050 with TOR and in my DietPi VM I use 9051...

More warning in TOR.log
Consider using Socks4A (e.g. via privoxy or socat) instead... Rejecting

**Comment by jedisct1** [comment]
You know your custom environment far better than anybody else, so I don't think I can help at this point.

**Comment by ghost** [comment]
I'm now running DNS over Tor but in tor.log shows:

Oct 07 02:39:02.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.

Oct 07 02:43:37.000 [warn] Socks version 0 not recognized. (Tor is not an http proxy.)
Oct 07 02:43:37.000 [warn] Fetching socks handshake failed. Closing.

I don't know what does it means. Some idea?

**Comment by ghost** [comment]
Rebooted my pc:

Status of:  dnsCRYPT-proxy in terminal:
( when this: force_tcp = true & proxy = socks5://127.0.0.01:9050)

(code=exited, status=255)
dnscrypt-proxy.service: Unit entered failed state.
dnscrypt-proxy.service: Failed with result 'exit-code'.

**Comment by ghost** [comment]
Got it running in my OS in VBox.

Add to my config: (torrc)
SocksPort 127.0.0.1:9050
SocksPolicy accept *

then:
force_tcp = true
proxy = "socks5://127.0.0.1:9050

Hmm, with enabled it, DNS is very slow on my config, without it, very fast with DNScrypt.

**Comment by jedisct1** [comment]
Yes, Tor adds a lot of latency. There are many users but not too many running router nodes.

**Comment by ghost** [comment]
Is it possible to route all my internet-traffic throu TOR and use Pi-hole, Unbound+dnsCRYPT (as DNS-resolver)?
