### ISSUE TITLE
Incorrect site name resolution.

### ISSUE THREAD

**Issue by vladns** [DNSCrypt/dnscrypt-proxy#604]
Hello! I do not know where to ask, but some dns servers sometimes do not properly allow rutracker.org giving it Indian IPs. I understand that the problem is not related to dnscrypt.

**Comment by jedisct1** [comment]
Hi!

What resolver(s) are you using?

**Comment by vladns** [comment]
Hi!
From the list of public-resolvers.md. I can only say what ip was resolved, this one 202.83.21.15

**Comment by jedisct1** [comment]
You can use `dnscrypt-proxy -resolve rutracker.org` to see what resolver you are using (and other useful info)

**Comment by vladns** [comment]
Did not know about this opportunity! As soon as this happens, I will answer.

**Comment by jedisct1** [comment]
<Insert a "you didn't read the documentation" meme here :)>

**Comment by vladns** [comment]
Of course I did not read :), I just set up the config file and use it. Moreover, English is not native to me, and I am swimming in the subject. But anyway, I will check and then unsubscribe from which server ls not the correct IP is allowed.

**Comment by vladns** [comment]
It happened :). Here is:

```
root@home-router:~# dnscrypt-proxy -resolve rutracker.org
Resolving [rutracker.org]

Domain exists:  yes, 2 name servers found
Canonical name: rutracker.org.
IP addresses:   202.83.21.15
TXT records:    v=spf1 +mx mx:mail.rutracker.org +a a:mx.rutracker.org -all
Resolver IP:    46.38.250.225 (zeroaim.de.)
```
