### ISSUE TITLE
Wiki: Forwarding the first line that matches the query

### ISSUE THREAD

**Issue by outloudvi** [DNSCrypt/dnscrypt-proxy#605]
It seems that the proxy will apply the first line that matches the query (even it's not the most accurate one). It's not yet mentioned on the wiki, so I've added [a small note](https://github.com/jedisct1/dnscrypt-proxy/wiki/Forwarding/_compare/e30455ed43f614cd758f5c73be06979d1112e607...e2e257d9e138cdd75de3e4819789b1d607c8df7c). Would the words be clear enough, or it would be better to use some examples to illustrate?

Suggestions are appreciated.

**Comment by jedisct1** [comment]
Indeed. Thanks for adding this to the wiki! This is very clear and useful.

Thank you!
