### ISSUE TITLE
2.0.17 still doesn't work on Android SDK 19

### ISSUE THREAD

**Issue by sfionov** [DNSCrypt/dnscrypt-proxy#608]
```
shell@lt01wifi:/data/local/tmp $ ./dnscrypt-proxy                              
CANNOT LINK EXECUTABLE: cannot locate symbol "sigfillset" referenced by "./dnscrypt-proxy"...
1|shell@lt01wifi:/data/local/tmp $ getprop ro.build.version.sdk                
19
```

**Comment by sfionov** [comment]
Ah, sorry, I see that there is commit https://github.com/jedisct1/dnscrypt-proxy/commit/c53b28d1f1093f1dccc372cd2e4462e5a377d712 that removed -D__ANDROID_API__=19 flag again.

Can you please add it for armeabi arch to support older devices?
Also seems that arm64 arch builds only with -D__ANDROID_API__=21 because it didn't exist earlier.

**Comment by jedisct1** [comment]
It doesn't compile any more if I add it back. Maybe this is not the way to add it?

Since you obviously know Android way better than I do, can you submit a pull request with the required changes to the `travis.yml` file?

Thank you!

**Comment by sfionov** [comment]
I've created a PR.

**Comment by jedisct1** [comment]
Thank you!
