### ISSUE TITLE
How to FIX?  open . tmp read-only file system @ public-resolvers.md

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#615]
Hi!

on "service dnscrypt-proxy status" I got this WARN-message:

[WARNING] /etc/dnscrypt-proxy/public-resolvers.md: open sf-"bla bla bla".tmp: read-only file system

How can I fix it? I don't have a read-only file system.

**Comment by ghost** [comment]
My dnscrypt-proxy.service config:
[Unit]
Description=####//dnsCRYPT-pR0Xy [SERV!CE] (client)
ConditionFileIsExecutable=/opt/dnscrypt-proxy/dnscrypt-proxy

[Service]
NonBlocking=true
Group=nogroup
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/opt/dnscrypt-proxy/dnscrypt-proxy --config /opt/dnscrypt-proxy/dnscrypt-proxy.toml

####//: SeCUrITy :\\####
CapabilityBoundingSet=CAP_IPC_LOCK CAP_SETGID CAP_SETUID CAP_NET_BIND_SERVICE
InaccessiblePaths=/boot
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
PrivateTmp=true
PrivateDevices=true
MemoryDenyWriteExecute=true
NoNewPrivileges=true
RestrictRealtime=true
RestrictAddressFamilies=AF_INET
RestrictAddressFamilies=~AF_INET6
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @ipc @module @mount @obsolete @raw-io

WorkingDirectory=/opt/dnscrypt-proxy

Restart=always
RestartSec=10
EnvironmentFile=-/etc/sysconfig/dnscrypt-proxy

[Install]
WantedBy=multi-user.target

**Comment by ghost** [comment]
Whats wrong?

**Comment by jedisct1** [comment]
Remove this systemd junk and install it as documented.

**Comment by publicarray** [comment]
@cokeflash Please use the code blocks for config files when commenting on github:

````
```
code here
```
````

You've just send emails to github users in the `SystemCallFilter` line by using `@username` 

See: https://guides.github.com/features/mastering-markdown/#syntax
