### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by wpuckering** [DNSCrypt/dnscrypt-proxy#616]
It would be great to have official Docker images of this project for Linux and Windows.

**Comment by publicarray** [comment]
Can I ask what the use-case is? 
Most users install decrypt-proxy as a system service on boot and as the default DNS provider. Having docker start-up first means that the system has to wait a bit longer before DNS is ready to accept requests.

**Comment by kometchtech** [comment]
@wpuckering 
Is there a Dockerfile that I created for myself, but will it be helpful?

https://github.com/kometchtech/docker-build/blob/master/dnscrypt-proxy/Dockerfile

This was created for Arm, but I think that by modifying a part of the syntax, it can correspond to other distributions.

**Comment by jedisct1** [comment]
This is great. But we can probably build a way smaller image, see [Building minimal docker donctainers for go applications](https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/)

**Comment by kometchtech** [comment]
@jedisct1 
Thank you for the good information.

@wpuckering 
I created a Dockerfile and performed a multi stage build.
https://github.com/kometchtech/docker-build/blob/master/dnscrypt-proxy/Dockerfile

Thanks to this, the image size will be less than 10MB, I think that the merit of Docker will be further obtained.
It is for Arm for my environment, but please adjust the environment variables when building to the environment that you use.
