### ISSUE TITLE
Dualstack & round-robin cloaking

### ISSUE THREAD

**Issue by Mikaela** [DNSCrypt/dnscrypt-proxy#617]
In my dnscrypt-proxy.toml I set `cloaking_rules = '/etc/dnscrypt-proxy/cloaking_rules.txt'` and in the file:

```
localhost.123 127.0.0.1
localhost.123 ::1
```

When I call `host localhost.123` I receive:

```
localhost.123 has address 127.0.0.1                                            
Host localhost.123 not found: 3(NXDOMAIN) 
```

I get similar results with `dig localhost.123` and `dig localhost.123 AAAA`.

When I attempt to use a cloaking rule `localhost.123 127.0.0.1 ::1`, I see a syntax error in journalctl: `Oct 17 23:19:48 sedric dnscrypt-proxy[13151]: [2018-10-17 23:19:48] [ERROR] Syntax error in cloaking rules at line 4 -- Unexpected space character` and the A record also breaks.

I think the traditional hosts file allows mapping domain into multiple addresses and I expected that from dnscrypt-proxy too. In case they are supported, I am not seeing them in https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-cloaking-rules.txt .

* Debian GNU/Linux testing (buster)                                              
* dnscrypt-proxy 2.0.16

**Comment by jedisct1** [comment]
Indeed, names map to a single entry.

It shouldn't be very hard to have them map to `(query type, IP)` tuples instead.

Would you like to try implementing this?

**Comment by Mikaela** [comment]
>  Would you like to try implementing this?

I fear that I am not capable of that as I don't have coding background and while learning is on my daily todo, I don't think I will get enough skilled in near future to touch dnscrypt-proxy's code and I think it's not in Go, even if I cannot remember what it is as I type this comment on phone. 


I am also having a strange issue that after cloaking IPv6-only addresses with IPv6-only domains, ssh and mosh started requiring -6 flag to not timeout. Is it related to dnscrypt-proxy / this issue or did I just happen to do something else wrong by happenstance?

**Comment by Mikaela** [comment]
> I am also having a strange issue that after cloaking IPv6-only addresses with IPv6-only domains, ssh and mosh started requiring -6 flag to not timeout. 

I think they and Firefox are getting confused by hearing that the domain exists and doesn't exist simultaneously. I guess dnscrypt-proxy should recognise that the cloak is IPv4/IPv6-only and give empty response instead of NXDOMAIN for the other protocol. Does that make this two related issues?

Not-cloaked:

```
└┌(%:~)┌- host y.relpda.mikaela.info                         
y.relpda.mikaela.info has IPv6 address 201:ef0c:cebe:f000:183c:9326:cbba:8fe1
```

Cloaked:

```
└┌(%:~)┌- host relpda.mikaela.internal
relpda.mikaela.internal has IPv6 address 201:ef0c:cebe:f000:183c:9326:cbba:8fe1
Host relpda.mikaela.internal not found: 3(NXDOMAIN)
```

(and in the original submission there was localhost.123 which had the issue on IPv4 instead of IPv6)

Howver I don't understand why this issue I am quoting started happening when I cloaked y.relpda.mikaela.info as it never had an A record or is it getting confused by mikaela.info being DNSSEC-signed?

**Comment by Mikaela** [comment]
Thank you :smile:

**Comment by poentodewo** [comment]
` $ ping -4 -c 4 i.imgur.com
PING i.imgur.com (151.101.100.193) 56(84) bytes of data.
64 bytes from 151.101.100.193 (151.101.100.193): icmp_seq=1 ttl=51 time=210 ms
64 bytes from 151.101.100.193 (151.101.100.193): icmp_seq=2 ttl=51 time=210 ms
64 bytes from 151.101.100.193 (151.101.100.193): icmp_seq=3 ttl=51 time=210 ms
64 bytes from 151.101.100.193 (151.101.100.193): icmp_seq=4 ttl=51 time=210 ms

--- i.imgur.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 210.064/210.340/210.784/0.624 ms
 $ ping -c 4 i.imgur.com
PING i.imgur.com(2a04:4e42::193 (2a04:4e42::193)) 56 data bytes
64 bytes from 2a04:4e42::193 (2a04:4e42::193): icmp_seq=1 ttl=60 time=27.7 ms
64 bytes from 2a04:4e42::193 (2a04:4e42::193): icmp_seq=2 ttl=60 time=27.6 ms
64 bytes from 2a04:4e42::193 (2a04:4e42::193): icmp_seq=3 ttl=60 time=27.0 ms
64 bytes from 2a04:4e42::193 (2a04:4e42::193): icmp_seq=4 ttl=60 time=27.5 ms

--- i.imgur.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 27.086/27.501/27.767/0.253 ms
 $ host i.imgur.com
i.imgur.com has address 151.101.100.193
i.imgur.com has IPv6 address 2a04:4e42::193
i.imgur.com is an alias for prod.imgur.map.fastlylb.net.`

Thank You 👍

**Comment by jedisct1** [comment]
You can also have multiple addresses of the same class. dnscrypt-proxy will do load-balancing between these IPs.
