### ISSUE TITLE
Question regarding configuration

### ISSUE THREAD

**Issue by thuantran** [DNSCrypt/dnscrypt-proxy#62]
Hi Frank,

Sorry but this is my first time working with toml file. When I add cert_ignore_timestamp = true at the end of the file, is it valid? Or will it count to the last table https://github.com/toml-lang/toml#user-content-table as stated here?

Best regards,
Thuan

**Comment by jedisct1** [comment]
Each `[...]` block defines a new section.

If you add `cert_ignore_timestamp` to the end, it will apply to the last section (`[time_ranges]` in the current code) instead of the global section, so it probably won't do what you expect.

So, order is important :)

**Comment by thuantran** [comment]
Ouch, ok.

I'm looking to parse toml file from linux shell to migrate my user settings from old version to new version, so I started to look at toml spec. Thanks for the info, now I know I need to fix my script first lol.

**Comment by jedisct1** [comment]
Yes, TOML can be a little bit confusing at first.

But it probably remains the easiest human-readable format to represent structured data.
