### ISSUE TITLE
get old cvs listing for quad9?

### ISSUE THREAD

**Issue by ingber** [DNSCrypt/dnscrypt-proxy#620]
My dd-wrt router only accepts lines from the old cvs file, e.g., like
cs-uswest,"CS Seattle WA US DNSCrypt server","provided by cryptostorm.is","Seattle, WA",,"https://cryptostorm.is",1,"no","yes","yes",64.120.5.251:443,2.dnscrypt-cert.cryptostorm.is,3133:72AD:5956:32C2:416B:872F:098F:851B:DDB9:6528:4C6C:BE9A:4F19:0964:30DB:A95A,

I would like the similar line for quad9-doh-ip4-filter-pri for which I only see the sdns stamp:
\## quad9-doh-ip4-filter-pri
Quad9 (anycast) dnssec/no-log/filter 9.9.9.9
sdns://AgMAAAAAAAAABzkuOS45LjmAABJkbnM5LnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ
in the current file public-resolvers.md.

**Comment by jedisct1** [comment]
Sorry, this old version is not supported any more.
