### ISSUE TITLE
Stops after a few minutes

### ISSUE THREAD

**Issue by justmwa** [DNSCrypt/dnscrypt-proxy#627]
Platform: linux-arm on a RT-AC68U
Both entware-ng package (2.0.16) and the github build (2.0.17) behave the same:
starts OK, resolves OK
after a variable delay from 1 to a few minutes, it logs "Stopped." That's it, even in DEBUG mode.
Conf is stock except that I specified a couple servers to speed up startup.

**Comment by jedisct1** [comment]
This is a clean stop, not a crash, so something explicitly asked it to terminate.

How did you start it?

Does it happen if you run it from the command-line and don't close the terminal?

**Comment by justmwa** [comment]
Hrm, you are right. If I start with /jffs/scripts/services-start it gets killed eventually for no good reason.
Starting right from the shell without closing it and it lasts. Yawn... Sorry for the false positive.

**Comment by alexyangjie** [comment]
@justmwa I have this exact issue too. Is there another way of starting the service in the background that won't close it afterwards?
