### ISSUE TITLE
Installed as a service, want to run as non-root (manual startup as non-root works okiedokie)

### ISSUE THREAD

**Issue by tonsimple** [DNSCrypt/dnscrypt-proxy#629]
Hi!

Long story short, installed, tested, everything works (including non-root startup and resolving), decided to install as service.

Works, but only as root.

Found the systemd unit it creates when installing as service.

Tried adding User=nobody directive.

No cigar - still starts as root.

Documentation does not appear to contain a clear instruction as to how does one achieve "non-root execution" with service install.

**Comment by jedisct1** [comment]
It's not supported on Linux yet.

**Comment by jedisct1** [comment]
To clarify, you shouldn't touch the systemd configuration. There is a `user_name` option in the `dnscrypt-proxy.toml` configuration file that you can try, but it's not very reliable, and requires some environment variables to be set on Linux.

**Comment by tonsimple** [comment]
@jedisct1 

Thanks! Could you go into more details as to what "not very reliable" implies and what are those variables?

P.S.
quite surprising that it works as nobody manually, but just switching user in the unit file doesn't stick. If I may ask (out of curiosity, if you don't mind) why is that?

**Comment by jedisct1** [comment]
https://github.com/golang/go/issues/1435

Open since 2011.
