### ISSUE TITLE
how to define openDNS server?

### ISSUE THREAD

**Issue by njscorpion** [DNSCrypt/dnscrypt-proxy#630]
how to define openDNS server?
i think i have to define it in place of 'server1' but which name? will ip address work?
> server_names = ["server1","server2"]

is there a list of servers available i can refer to?

**Comment by jedisct1** [comment]
Hi,

You can see a list of servers with their name here: https://dnscrypt.info/public-servers

The OpenDNS company doesn't exist any more, it's now a Cisco product. In order to send your data to Cisco, you need to use `cisco` as a server name.

**Comment by njscorpion** [comment]
thanks
