### ISSUE TITLE
What does do dnscrypt-proxy exactly?

### ISSUE THREAD

**Issue by hasanalizxc** [DNSCrypt/dnscrypt-proxy#631]
Dear jedisct1 and Github users,

Hope you are fine. I have some questions about this tool.

1) First question is title.
2) Second question is this encrypts DNS traffic? If yes, my ISP can be monitored content even if encrypted? I mean is this encrypts my dns queries (web)?
3) Third question when i installed this, internet connection of other devices in my LAN made laggy and slow (freezes internet connection, for ex. videos are waiting for fetch. When i turn off software, everything is normal). And sometimes 30-40 seconds there is no internet on my LAN. What is the reason?
4) Fourth question you had wrote "you can configure plenty of options" in Installation section. Could you please explain some of them?
5) Fifth question when i run from folder via command line it is faster than installed service. There are too much difference between two of them. Installed service is too much slow. I tested this scenario on five (5) different computers. Please make fix for this.
6) Sixth question i saw there are many public DnsCrypt resolvers but i couldn't understand how can i use sdns://78438....... address as like in this picture.
http://prntscr.com/ld9udu
7) Seventh question how can i configure this tool "only use encrypted Dnscrypt protocols"?

Have a happy day.

Thanks in advance.
Best Regards.

**Comment by jedisct1** [comment]
Hi,

The answer to most of your questions are in the documentation: https://github.com/jedisct1/dnscrypt-proxy/wiki

It doesn't encrypt your web traffic. Which is mostly already encrypted these days. But it encrypts and authenticates DNS, which is used before you load any web page, and is the easiest, cheapest, most common way to do monitoring and censorship.

It doesn't do anything to web content, even less to videos. But some services use DNS information to route you to a server close to your ISP. If you use your ISP DNS, they will serve the content from a location close to your ISP, or from caches hosted by the ISP itself.
If you use a DNS resolver which is far away, they may send the files from a far away location.
But this is less and less the case with modern CDNs.

Options are described in the documentation, as well as how to choose the resolvers. You don't need to copy the `sdns://....` addresses.

If you use this tool, you will always use encrypted DNS services. It will never connect to an unencrypted one (it can't, this is not even implemented).

**Comment by hasanalizxc** [comment]
Thank you for your interest and polite answers. So, is this supports DNS Over TLS, right?

**Comment by jedisct1** [comment]
It supports the more recent DNS-over-HTTPS, as well as DNSCrypt.

**Comment by hasanalizxc** [comment]
I got it. Do you think add Dns-over-TLS feature?

**Comment by jedisct1** [comment]
Probably not.

DNS-over-TLS doesn't have any security advantage over other protocols. It's badly designed, can hardly evolve, it's slow and can reduce privacy. Its funky port number also makes it impossible to use on many public WiFi where it could actually be useful.

"It's a standard" is the only argument it had. Now what DNS-over-HTTPS is an official IETF protocol and that DNSCrypt is about to be submitted, there is no point in supporting it.

**Comment by hasanalizxc** [comment]
I got it. Thank you for your interest.

**Comment by hasanalizxc** [comment]
Last one thing. How often Dns resolvers is been updating?

**Comment by jedisct1** [comment]
Every 3 days by default.
