### ISSUE TITLE
[Not an issue] can we have more than one black list file?

### ISSUE THREAD

**Issue by njscorpion** [DNSCrypt/dnscrypt-proxy#632]
can we have more than one black list file?
Example : 

> blacklist_file = 'blacklist_ads.txt', 'blacklist_porn.txt'

if yes how do i define it?

**Comment by jedisct1** [comment]
There can be only one file, but you can concatenate multiple files into a single one in the startup script.

**Comment by njscorpion** [comment]
i guess that should work nicely, i will have a look. 

Thank you.
