### ISSUE TITLE
[Linux] /opt/dnscrypt-proxy/: read-only file system

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#633]
I've been getting a lot of warnings lately.

Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolver [84.200.69.80:53]
Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [WARNING] /opt/dnscrypt-proxy/public-resolvers.md: open sf-ybatgnhxyso2sgob.tmp: read-only file system
Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [WARNING] /opt/dnscrypt-proxy/public-resolvers.md.minisig: open sf-44efadarglwwom2a.tmp: read-only file system
Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [NOTICE] Source [public-resolvers.md] loaded
Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [NOTICE] dnscrypt-proxy 2.0.17
Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [NOTICE] Loading the set of forwarding rules from [...]
Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [NOTICE] Now listening to 127.0.0.1:54 [UDP]
Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [NOTICE] Now listening to 127.0.0.1:54 [TCP]

Why do I got these "WARNINGS" of dnscrypt-proxy?
public-resolvers.md: open sf-ybatgnhxyso2sgob.tmp: read-only file system
public-resolvers.md.minisig: open sf-44efadarglwwom2a.tmp: read-only file system

Why ".tmp" read-only file system? I only have the default settings from install.

Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [WARNING] /opt/dnscrypt-proxy/public-resolvers.md: open sf-ybatgnhxyso2sgob.tmp: read-only file system
Nov  2 19:28:44 amd dnscrypt-proxy[21120]: [2018-11-02 19:28:44] [WARNING] /opt/dnscrypt-proxy/public-resolvers.md.minisig: open sf-44efadarglwwom2a.tmp: read-only file system

dnscrypt-proxy still works.

When I install dnscrypt-proxy AGAIN as service via "sudo ./dnscrypt-proxy -service install" and then "sudo ./dnscrypt-proxy -service start", after that
I have dnscrypt-proxy running without the ".tmp read-only file WARNING"

systemd[1]: Started Encrypted/authenticated DNS proxy.
Nov  2 19:38:38 blabla dnscrypt-proxy[22014]: [2018-11-02 19:38:38] [NOTICE] Source [public-resolvers.md] loaded
Nov  2 19:38:38 blabla dnscrypt-proxy[22014]: [2018-11-02 19:38:38] [NOTICE] dnscrypt-proxy 2.0.17
Nov  2 19:38:38 blabla dnscrypt-proxy[22014]: [2018-11-02 19:38:38] [NOTICE] Loading the set of forwarding rules from [f0rw@Rd!Ng-rULeZ.txt]
Nov  2 19:38:38 blabla dnscrypt-proxy[22014]: [2018-11-02 19:38:38] [NOTICE] Now listening to 127.0.0.1:54 [UDP]
Nov  2 19:38:38 blabla dnscrypt-proxy[22014]: [2018-11-02 19:38:38] [NOTICE] Now listening to 127.0.0.1:54 [TCP]

**Comment by ghost** [comment]
Slowly dnscrypt-proxy starts to get on my nerves. I installed dnscrypt-proxy again... so far so good. After 2 days the warning appears again.

[NOTICE] System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolver [84.200.69.80:53]
[WARNING] /opt/dnscrypt-proxy/public-resolvers.md: open sf-x32vykza3fn7jj3i.tmp: read-only file system
[WARNING] /opt/dnscrypt-proxy/public-resolvers.md.minisig: open sf-mzh4hgjo67yij2tv.tmp: read-only file system

I don't have a read-only file-system on root.

Folder /opt/dnscrypt-proxy is read+write on permissions.

/tmp also rw.


What's going on with dnscrypt-proxy, why is it constantly open public-resolvers.md: open sf-x32vykza3fn7jj3i.tmp/public-resolvers.md.minisig: open sf-mzh4hgjo67yij2tv.tmp: 
read-only file system and so on?

I deleted "public-resolvers.md & public-resolvers.md.minisig"  installed dnscrypt-proxy again and it worked without "read-only file-system Warning in Log-FileViwer.

Then after 2 days, read only-file-system Warnung on these 2 files: "public-resolvers.md & public-resolvers.md.minisig"


I don't know what to do.

Please HELP to fix that.

**Comment by publicarray** [comment]
Huh, what distro and version are you running? I’ve never seen this error. Do you have selinux or apparmor? Can you share your `/etc/fstab` file? `du` and `df` commands can show the amount of free space on /var some OSs partition the var directory on a seperate partition. Are there any other errors on the OS related to this? `dmesg` can also help. I assume the folder has the correct permissions? Are you using the `user_name` Option and if so would disabling the option fix this?

**Comment by ghost** [comment]
Permission of folder "dnscrypt-proxy" = root, create+delete... / root, access..., Others, access

Permission of the runtime "dnscrypt-proxy" = 2000 - user #2000, Read+write, 2000, Read-only , Others, Read-only

Permission of the other files in the folder = root, create+delete... / root, access..., Others, access

**Comment by publicarray** [comment]
Hm, Are you able to create new files in those locations when dnscrypt-proxy has a problem? I'm not a sure but those `tmpfs` might be the problem or the filesystem has a problem and linux remounted the disk in read only mode. I'm at a loss maybe @zenofx may be able to help you.

**Comment by ghost** [comment]
ok, with dnscrypt-proxy v2.0.18 the WARNING-message (read-only...tmp) is gone...

**Comment by ghost** [comment]
(SOLVED)

**Comment by publicarray** [comment]
Can you please close the issue? there is a button below the text box.
