### ISSUE TITLE
is it possible to get acctual DNS used to serve the query in log?

### ISSUE THREAD

**Issue by njscorpion** [DNSCrypt/dnscrypt-proxy#634]
Current log:

> [2018-11-04 16:25:14]	127.0.0.1	live.sysinternals.com	A	PASS
> [2018-11-04 16:25:14]	127.0.0.1	live.sysinternals.com	A	PASS

Expected:

> [2018-11-04 16:25:14]	8.8.8.8	live.sysinternals.com	A	PASS
> [2018-11-04 16:25:14]	9.9.9.9:9953	live.sysinternals.com	A	PASS

**Comment by njscorpion** [comment]
the following is the content of my toml file:

> server_names = ["cloudflare", "aaflalo-me","aaflalo-me-gcp"]
> listen_addresses = ["127.0.0.2:53", "[::1]:53"]
> max_clients = 250
> ipv4_servers = true
> ipv6_servers = false
> dnscrypt_servers = true
> doh_servers = true
> require_dnssec = true
> require_nolog = true
> require_nofilter = true
> force_tcp = true
> timeout = 2500
> keepalive = 30
> log_level = 0
> use_syslog = false
> netprobe_timeout = 45
> cert_refresh_delay = 240
> dnscrypt_ephemeral_keys = true
> fallback_resolver = "9.9.9.9:9953"
> ignore_system_dns = true
> log_files_max_size = 5
> log_files_max_age = 7
> log_files_max_backups = 1
> block_ipv6 = true
> cache = true
> cache_size = 512
> cache_min_ttl = 600
> cache_max_ttl = 86400
> cache_neg_min_ttl = 60
> cache_neg_max_ttl = 600
> #daemonize = false ##old
> #fallback_resolver = "9.9.9.9:53" "1.1.1.1:853" "208.67.222.222:5353" "9.9.9.9:9953"
> 
> [query_log]
> file = "A:\\DNSCrypt_query.log"
> format = "tsv"
> 
> [nx_log]
> file = 'A:\\DNSCrypt_nx.log'
> format = "tsv"
> 
> [blacklist]
> blacklist_file = "mybase.txt"
> log_file = "A:\\DNSCrypt_blocked.log"
> log_format = 'tsv'
> 
> [sources]
> 
> 	[sources.public-resolvers]
> 	urls = ["https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md", "https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md"]
> 	cache_file = "public-resolvers.md"
> 	minisign_key = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"
> 	refresh_delay = 72
> 	prefix = ""

however sometime i feel like the dns is intercepted as i will end up in "blocked as per the directions received from XYZ" page.

**Comment by jedisct1** [comment]
The address being logged is the address of the client.

This is the expected behavior, and this is very useful when the proxy is running on the router, so you know what device sent each query.
