### ISSUE TITLE
Automatic reverse lookup forwarding

### ISSUE THREAD

**Issue by nariox** [DNSCrypt/dnscrypt-proxy#635]
Hi, I've read the wiki page on [Forwarding](https://github.com/jedisct1/dnscrypt-proxy/wiki/Forwarding), but it seems to assume you always have the same IP for your router. Is there a way to route all local domain requests to the "default route" ip address instead?

**Comment by jedisct1** [comment]
Hi,

Yes, you are correct. Sending this to the default route would be a bit complicated because it's very different on each operating system.

But maybe your startup script can look up the default route and write a configuration file with that route (possibly from a template config file)?

**Comment by nariox** [comment]
Hmm, I see. Making it cross-platform would indeed be tricky. I don't know much go, but my guess is that there is no standardized way to do this. Bummer. I'll probably end up writing a script then. Or just change my settings ad-hoc as I need. Thanks for the quick answer. Should I close this?
