### ISSUE TITLE
How to port this version support  IOS ?

### ISSUE THREAD

**Issue by tuannv19** [DNSCrypt/dnscrypt-proxy#637]
Is there anyone can tell me way to port or  using this project   with  IOS project  ?

**Comment by jedisct1** [comment]
If you are looking for an existing iOS app with dnscrypt-proxy, try [DNSCloak](https://itunes.apple.com/us/app/dnscloak-dnscrypt-doh-client/id1330471557?mt=8), it's awesome. By far the best DNS app on mobile devices.

If you are looking to build your own app also embedding dnscrypt-proxy, you need to compile it with [go mobile](https://github.com/golang/go/wiki/Mobile).

**Comment by tuannv19** [comment]
Thank you. I'll try compile it with go mobile. Can u help me close topic.

**Comment by tuannv19** [comment]
@jedisct1  i build project with gomobile and run simple test in ios . This is log message 
`[2018-11-15 11:59:45] [NOTICE] Source [public-resolvers.md] loaded
[2018-11-15 11:59:45] [NOTICE] dnscrypt-proxy 2.0.17
[2018-11-15 11:59:45] [FATAL] listen udp 127.0.0.1:53: bind: permission denied`

So what can i do? 

Thanks you so much.

**Comment by tuannv19** [comment]
@jedisct1  seem i port everything done.  But can u tell me where  i see code to  stop or restart  dnscrypt-proxy in your project. I'm just starter golang , very hard to find. Plz help me.

**Comment by jedisct1** [comment]
It's in the https://github.com/kardianos/service module.
