### ISSUE TITLE
DoH over HTTP proxy (squid)

### ISSUE THREAD

**Issue by dtouzeau** [DNSCrypt/dnscrypt-proxy#638]
Is it possible to add HTTP Proxy support (like squid ) for DoH requests ?

**Comment by jedisct1** [comment]
Support for HTTPS proxies have been recently added to Go, so it can be implemented. But the performance will not be good at all. DoH requires HTTP/2 for acceptable performance, but proxies like Squid only support HTTP/1.1.

**Comment by dtouzeau** [comment]
Thanks, this is a Squid team issue but in a secure outgoing  environnement it should be a really good feature especially if Unbound act has caching behind, first requests should be slower but just for quik moment.

**Comment by dtouzeau** [comment]
You are the best!
