### ISSUE TITLE
Hosts file compatibility

### ISSUE THREAD

**Issue by Avamander** [DNSCrypt/dnscrypt-proxy#639]
Would it be somehow possible to tell dnscrypt-proxy that my cloaking rules follow the default linux hosts file format instead the current one dnscrypt-proxy reads?

The reason I'd like that feature is that it would be so much easier to just maintain one cloaking/hosts file than two.

**Comment by jedisct1** [comment]
The host file and cloaking rules can hardly share the same format.

The host file just maps strict names to IP addresses.

Cloaking rules match patterns, so a single rule can be equivalent of hundreds lines in the `hosts` file. 

Cloaking rules can also redirect to addresses from other host names, and can change according to the time and day.

If you are using dnscrypt-proxy, you don't need to maintain a `hosts` file in addition to it. This will let you share the same rules across all computers in the network.

**Comment by Avamander** [comment]
All that you've said should not mean that dnscrypt-proxy shouldn't be able to read regular hosts file format. I also have other pieces of software that do only read the standard hosts format so I do have to maintain that list.

**Comment by Avamander** [comment]
@jedisct1, are you certain a compatibility mode to read a hosts file is out of the question?

**Comment by jedisct1** [comment]
I fear this is a feature that only very few people will use. But this will still need to be maintained forever.
