### ISSUE TITLE
Empty listen_addresses should not be considered an error in the logs

### ISSUE THREAD

**Issue by Zirkelite** [DNSCrypt/dnscrypt-proxy#64]
Commit a364e51d9e2ea5b6907c706315349b812ab86572 changed the log level of the "no local IP/port configured" message and it is now displayed as an error. However, it should be rather be displayed as a notice (or as debug level like before), since configuring the listening addresses at the configuration file is unneeded when using systemd sockets. In fact, the comment before the listen_addresses line recommends setting it to an empty set when using systemd-based sockets.

**Comment by jedisct1** [comment]
Ah indeed. While reviewing error levels, I was surprised that this was not an error. Couldn't figure out why it was just a debug statement. I had forgotten about the existence of systemd.

This has been reverted.

Thanks!
