### ISSUE TITLE
Feature request: Outgoing interface

### ISSUE THREAD

**Issue by dtouzeau** [DNSCrypt/dnscrypt-proxy#640]
Is it possible for next version to define an outgoing interface for outgoing DNS requests.
In this case it should be a real "proxy" in a router mode or computer with 2 network interfaces with specific lo rules.

**Comment by jedisct1** [comment]
Can you implement it?

**Comment by dtouzeau** [comment]
??

**Comment by jedisct1** [comment]
For UDP/TCP connections, it should be straightfoward, and for HTTP, it doesn't seem to be too complicated either: https://stackoverflow.com/questions/44571331/specify-network-interface-for-http-request-in-golang

I'm not planning to do that, but if you do, I'd be happy to review and merge your code. Thanks for your help!

**Comment by dtouzeau** [comment]
Sorry but i have no GO skills...
