### ISSUE TITLE
Console output (windows) for start and stop different - just not consistent output

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#642]
when stopping via command line dnscrypt-proxy.exe -service stop you get on console 

_[2018-11-16 09:55:18] [NOTICE] dnscrypt-proxy 2.0.18
[2018-11-16 09:55:18] [NOTICE] Service stopped_

starting however shows just dnscrypt-proxy.exe -service start
**NOTHING**

so just for the sake of being consistent i would expect something as 

_[2018-11-16 09:55:18] [NOTICE] dnscrypt-proxy 2.0.18
[2018-11-16 09:55:18] [NOTICE] Service **started**_

**Comment by scubasunny** [comment]
what is strange as this is coded in main.go ?????

		} else if *svcFlag == "start" {
			dlog.Notice("Service started")
		} else if *svcFlag == "stop" {
                       dlog.Notice("Service stopped")

**Comment by jedisct1** [comment]
No idea why :/
