### ISSUE TITLE
How to use --pidfile?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#643]
How to use --pidfile?

I read about to use "--pidfile=/var/run/prog-name.pid...

add it to "dnscrypt-proxy.service" ?

ExecStart=/etc/dnscrypt-proxy/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml --pidfile /var/run/dnscrypt-proxy.pid ?

I tested it, dnscrypt starts but don't create the pidfile.

I have rw access because other programs create pidfiles in /var/run...

**Comment by ghost** [comment]
I tried it this way once.
sudo service dnscrypt-proxy start

status:
/etc/dnscrypt-proxy/dnscrypt-proxy --pidfile /var/run/dnsCRYPT-pR0Xy.pid --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -child

**Comment by ghost** [comment]
...but no pidfile of dnscrypt-proxy is created at /var/run

program is running with user_name and it works.

**Comment by jedisct1** [comment]
The comment above the `user_name` option says:

    ## Note (3): when using -pidfile, the PID file directory must be writable by the new user

If it the case?

**Comment by ghost** [comment]
what's the right spelling @ .service file?

ExecStart=/etc/dnscrypt-proxy/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -pidfile

ExecStart=/etc/dnscrypt-proxy/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -pidfile /var/run/dnscrypt-proxy.pid

ExecStart=/etc/dnscrypt-proxy/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml --pidfile=/var/run/dnscrypt-proxy.pid

or

ExecStart=/etc/dnscrypt-proxy/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -pidfile=$PIDFILE >/var/run/dnscrypt-proxy.pid

which is correct?

**Comment by publicarray** [comment]
\# 2

Both one and two dashes are supported

Edit:
The --option=value syntax also works on the command line but I'm not sure if systemd will chuck a syntax error.

**Comment by ghost** [comment]
I'll try that

ExecStart=/etc/dnscrypt-proxy/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -pidfile /var/run/dnscrypt-proxy/dnscrypt-proxy.pid

but:
status systemd message: running 
WARNING:
dnscrypt-proxy.service: Current command vanished from the unit file, execution of the command list won't be resumed.


Which file/folder permission must I set?

Owner: root, create+delete... / Group: root, access..., Others: access...

or:

Owner: nobody, create+delete... / Group: dnscrypt-proxy/nogroup?    (because of user_name 'nobody' in dnscrypt-proxy.toml)

**Comment by ghost** [comment]
Output of systemd:
● dnscrypt-proxy.service - dnscrypt-proxy
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-11-16 22:09:52 CET; 17min ago
 Main PID: 14780 (dnscrypt-proxy)
    Tasks: 17 (limit: 4915)
   CGroup: /system.slice/dnscrypt-proxy.service
           └─14780 /etc/dnscrypt-proxy/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -pidfile /var/run/dnscrypt-proxy/dnscrypt-proxy.pid -child

but no "PIDFILE" of dnscrypt-proxy was created :-(

**Comment by ghost** [comment]
which folder permissions of: "/var/run/dnscrypt-proxy/" ???

Owner?
Group etc.?

**Comment by ghost** [comment]
No chance to run dnscrypt-proxy v2. 0. 18 with creating a pidfile.

I've tried everything I can. Various folders etc. Use it now without pidfile-option.
