### ISSUE TITLE
User_name question

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#645]
Which User_name should/can I use for dnscrypt-proxy in the "config .toml" file?

Can I use my user name of my home folder in ubuntu? Or should I use "nobody"

I want non-root user for dnscrypt-proxy.

**Comment by jedisct1** [comment]
It doesn't work reliably on Linux. Do not use this option. The documentation mentions another way to run the server without root privileges on Linux.

**Comment by ghost** [comment]
I done this:

addgroup --system dnscrypt-proxy

adduser --system dnscrypt-proxy --shell /bin/false --no-create-home --disabled-password --ingroup dnscrypt --quiet

user_name = 'dnscrypt-proxy' in "dnscrypt-proxy.toml"

and now my dnscrypt is running non root.

Another method doesn't work on my system. I've tried all sorts of things. DynamicUser does not work either.
