### ISSUE TITLE
HTTP/HTTPS proxy (Only for DoH servers)

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#646]
Hi!
How can I use it with dnscrypt-proxy?

I got:
[CRITICAL] Unable to use source [quad9-resolvers]: [Get https://www.quad9.net/quad9-resolvers.md: proxyconnect tcp: dial tcp 127.0.0.1:8888: connect: connection refused]
[2018-11-17 18:59:19] [FATAL] No servers configured]

Must I open port 8888 for TCP+UDP in my ROUTER?

Rule for iptables? TCP/UDP?

**Comment by jedisct1** [comment]
`127.0.0.1` is your local machine. If you are running a HTTP proxy on your local machine, you don't need to do anything on other devices, including your router.

But according to the message, you are not running a HTTP proxy on your local machine. Remove the `http_proxy` option.

**Comment by ghost** [comment]
ok, thanks!
