### ISSUE TITLE
Sandboxing /DNScrypt-Proxy/ + Question about dnscrypt-proxy.service

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#647]
Hi!

Do I need Sandboxing "dnscrypt-proxy.service"

with?

CapabilityBoundingSet=CAP_IPC_LOCK CAP_SETGID CAP_SETUID CAP_NET_BIND_SERVICE
InaccessiblePaths=/boot
ProtectSystem=strict
ProtectKernelTunables=true
ProtectKernelModules=true
MemoryDenyWriteExecute=true
NoNewPrivileges=true
RestrictRealtime=true
RestrictAddressFamilies=AF_INET
RestrictAddressFamilies=~AF_INET6
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @ipc @module @mount @obsolete @raw-io

**Comment by publicarray** [comment]
I recommend you stay with the [standard installation](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux) until your linux distribution updates dnscrypt-proxy to v2.

These might help you: https://github.com/jedisct1/dnscrypt-proxy/pulls?utf8=%E2%9C%93&q=systemd+

> Only read what follows if you are a systemd expert and think you need a complicated configuration. Everybody else should just follow the standard installation instructions.

https://github.com/jedisct1/dnscrypt-proxy/wiki/systemd

**Comment by ghost** [comment]
ok, thanks for the info!
