### ISSUE TITLE
Is Restarting enough after new blacklists?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#65]
Good evening Frank,

Just to be sure : I assume that in order for new _blacklists_ to be correctly integrated while DNSCrypt-proxy is running, a _restart_ is enough, no need to _uninstall_ + _install_. Is this correct?

The new _service-restart_ is really nice (wasn't available in DNSCrypt-Proxy 1.9.5), made it perfectly after I had changed _server_names_ (yes, I use only 3), and blacklists were correctly handled (I checked), but checking updated blacklists is not as easy given the fact they include minor changes.

Thanks.

**Comment by jedisct1** [comment]
Yes, that's all you have to do!

**Comment by ghost** [comment]
Thanks Frank for confirming. That's what I was practically sure of but not at a 100% (otherwise I wouldn't have asked!).
Wow, fast, slick ... I won't buy you a beer, that'd be cheap compared to the quality of your work.
A Magnum maybe!
"Mais le coeur y est" (that's French!)

**Comment by jedisct1** [comment]
I don't drink alcohol, but I'm glad to hear that this tool is useful to you!

Cheers!
