### ISSUE TITLE
Cache path question + pi-hole cache

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#650]
Question 1:

Is there any way if I turn on the cache 
under a different path? 
I'd like to choose the path to (tmpfs)/tmp. 

If you can't do that, it'd be good if you put this in 
you would include a next version.

Question 2:

Is it advantageous if I switch on the cache of dnscrypt-proxy and use the cache of pi-hole at the same time? 

Or should I just use the cache of pi-hole and 
with dnscrypt-proxy switched off.

**Comment by jedisct1** [comment]
You can set all the paths (logfiles, sources, etc) in the configuration file:

`cache_file = ...`
`log_file = ...`
`blacklist_file = ...`

All of these accept a file name, relative to the executable path or a full, absolute path.

And you don't need multiple DNS caches on the same machine, you're just duplicating information, thus wasting memory and eventually caching less.
