### ISSUE TITLE
Resolving error

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-proxy#651]
Error type: NXDomain
Version: 2.0.18, Linux ARM64
Config file: https://0bin.net/paste/a85EZ13GvBDp7aKp#xJmUffIRChxqLeEqp9qOILnsVivy3OYBsTZuiONvDBA

Domain 'www.metacritic.com' got NXDomain error, but resolving directly (nslookup www.metacritic.com 1.1.1.1) work fine. Sometimes this error happen with 'www.youtube.com'. All other domains work.

**Comment by jedisct1** [comment]
`listen_addresses = ['127.0.0.1:53333']`

Regular clients can't connect to this port, so there is some other software involved you didn't mention.

Can you check what exact server is returning `NXDOMAIN` for Youtube?

**Comment by black-cerberon** [comment]
Problem gone by fixing privileges.
