### ISSUE TITLE
minisig signature fails on release 2.0.19

### ISSUE THREAD

**Issue by omega32** [DNSCrypt/dnscrypt-proxy#652]
Hi. The signature verification of `dnscrypt-proxy-win64-2.0.19.zip` (latest release at the moment) fails:

> `minisign -Vm dnscrypt-proxy-win64-2.0.19.zip -P RWTk1xXqcTODeYttYMCMLo0YJHaFEHn7a3akqHlb/7QvIQXHVPxKbjB5`

Output:
>Signature verification failed

**Testing the previous version works as expected:**
>`minisign -Vm dnscrypt-proxy-win64-2.0.18.zip -P RWTk1xXqcTODeYttYMCMLo0YJHaFEHn7a3akqHlb/7QvIQXHVPxKbjB5`

Output:
>Signature and comment signature verified
Trusted comment: timestamp:1542305474   file:dnscrypt-proxy-win64-2.0.18.zip

Thanks

**Comment by jedisct1** [comment]
The build was restarted and all files got reuploaded. Hopefully this fixes the issue. Thanks!
