### ISSUE TITLE
Dnscrypt blacklists block only outgoing DNS query?

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#653]
I am blocking outgoing domains matching *analytics*, yet incoming <cname> responses from dns servers, which include in the domain "analytics" are not being blocked. Blacklist security/functionality is cut in half. Please also include an option for replies via blacklists

13:19:30 dnsmasq[1211]: query[A] s.update.fbsbx.com from 192.168.50.142
13:19:30 dnsmasq[1211]: forwarded s.update.fbsbx.com to 127.0.0.1
13:19:30 dnsmasq[1211]: reply s.update.fbsbx.com is <CNAME>
13:19:30 dnsmasq[1211]: reply s.agentanalytics.com is <CNAME>
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 52.20.233.11
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 35.170.177.215
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 34.235.44.232
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 34.194.252.192
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 18.206.130.128
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 52.202.107.183
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 18.209.97.44
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 35.173.82.169
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 23.22.178.204
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 18.206.103.1

**Comment by jedisct1** [comment]
How would you get a response if you don't send a matching query first?

Name-based blacklists cause the blocking to happen when the query is received, so that the upstream server doesn't even know that you tried to access a blocked name.

On the other hand, IP-based blacklists are applied after the response is received.

I think you got confused by what dnsmasq is logging, which, granted, is very confusing. There is only one question here `A s.update.fbsbx.com`, and one matching response `CNAME s.update.fbsbx.com`. The rest is garbage ignored by resolvers, as it is not within the parent zone.

**Comment by rugabunda** [comment]
@jedisct1 [wrong](https://pasteboard.co/HPErWtq.jpg), this reoccurs over, and over and over again with every query to s.update.fbsbx.com; According to [robotex](https://www.robtex.com/dns-lookup/s.update.fbsbx.com), S.update.fbsbx.com is a CNAME to s.agentanalytics.com, though it has far more IP addresses than what are listed on their website

Any domain query with the word analyitics was and is being blocked by dnscrypt proxy blacklist, thus could not have been made, but they were being received, indeed they were as you can clearly see above. @jedisct1 is "invalid"; if I can point you to the source of this query I will;  

I was forced to block "s.update.fbsbx.com" altogether, possibly breaking some legit functionality of whatever it was, while ensuring no reply connection to any domain with "analtytics" data-harvesting. 

It is not garbage according to the resolver, once a response is received and cached, any application could use the ip addresses provided, as it appears indeed this fb app / website was doing. Not even dnsmasq could block or forward these incoming replies.

its coming from a laptop @ the residence so I'd have to wireshark their laptop to find out, I will consider doing this so you could potentially test this out for yourself.

**Comment by rugabunda** [comment]
Ok its coming from a laptop @ the residence so I'd have to wireshark their laptop to find out, I will consider doing this so you could potentially test this out for yourself.

**Comment by rugabunda** [comment]
According to robotex, S.update.fbsbx.com is a CNAME to s.agentanalytics.com.

https://www.robtex.com/dns-lookup/s.update.fbsbx.com

though it has far more IP addresses than what are listed on their website

**Comment by rugabunda** [comment]
@jedisct1 a banking Trojan uses this domain: https://www.proofpoint.com/us/threat-insight/post/danabot-new-banking-trojan-surfaces-down-under-0

The trojan connects to or sniffs s.update.fbsbx.com analytics. Who made this banker bandit, Zuckerburgerstein? And seeing that a banker thief trojan wants access to the analytics over this domain in its Sniffer filter list, it doesn't make me feel comfortable with with what may already flowing over this domain to facebook. And they've cleverly disguised it to be immune to one-way wildcard blacklists, like yours.
