### ISSUE TITLE
No IP found for [download.dnscrypt.info]

### ISSUE THREAD

**Issue by k4yt3x** [DNSCrypt/dnscrypt-proxy#654]
Either the newest update pushed to Kali broke the configuration file, or the domain which was up is no longer available. I had to change the resolver list manually in the configuration file.

I took a screenshot but lost it. I can take another one if you need it.

Affected version: `2.0.16-2`
![screenshot_2018-11-27_00-16-41](https://user-images.githubusercontent.com/21986859/49060028-badc5800-f1d9-11e8-8369-9d4238481645.png)

**Comment by jedisct1** [comment]
The `dnscrypt.info` website itself was not accessible. In fact, all my domains were gone, including my corporate ones, due to my server running out of memory.

This should be fixed now.

**Comment by k4yt3x** [comment]
Ok good to know. Thanks for the quick response.
