### ISSUE TITLE
Oblivious DNS

### ISSUE THREAD

**Issue by uBlock-user** [DNSCrypt/dnscrypt-proxy#656]
https://tools.ietf.org/html/draft-annee-dprive-oblivious-dns-00

Would you be adding support for it ?

**Comment by jedisct1** [comment]
If it ever gets finalized and deployed.

I proposed the same idea 6 years ago, but deployment seems complicated. Authoritative DNS servers have too much inertia.

**Comment by uBlock-user** [comment]
> If it ever gets finalized and deployed.

It's still in the dev. stage, so fingers crossed, thanks for the response.
