### ISSUE TITLE
Question about dnscrypt TLS_cipher_suite

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#657]
Oh, I see it now, its enabled in Firefox "about:config"

security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256  true
security.ssl3.ecdhe_rsa_aes_128_gcm_sha256	= true

# set TRUE or FALSE?
user_pref("security.enable_ssl2", false);
user_pref("security.enable_ssl3", true;

from:  http://kb.mozillazine.org/Security.tls.version.*
# WHICH value? 
security.tls.version.min = 3 (min. TLS 1.2)?
security.tls.version.max = 0 (max TLS 3.0)?
security.tls.version.fallback-limit = 3 (min. TLS 1.2)

correct? what value would you recommend?

Sorry about that ;-)

**Comment by cokeflash** [comment]
49199 = TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
=
or?
user_pref("security.ssl3.ecdhe_rsa_aes_128_gcm_sha256", true);
user_pref("security.ssl3.ecdhe_rsa_rc4_aes_128_gcm_sha256", true);

**Comment by cokeflash** [comment]
Oh, I see it now, its enabled in Firefox "about:config"

security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256  true
security.ssl3.ecdhe_rsa_aes_128_gcm_sha256	= true

Sorry about that ;-)

Which ciphers can I disable for more security reason in firefox?


security.ssl3.dhe_rsa_aes_128_sha		= false
security.ssl3.dhe_rsa_aes_256_sha		= false
security.ssl3.ecdhe_ecdsa_aes_128_gcm_sha256	= true
security.ssl3.ecdhe_ecdsa_aes_128_sha		= false
security.ssl3.ecdhe_ecdsa_aes_256_gcm_sha384	= true
security.ssl3.ecdhe_ecdsa_aes_256_sha		= true
security.ssl3.ecdhe_ecdsa_chacha20_poly1305_sha256	= true
security.ssl3.ecdhe_ecdsa_rc4_128_sha		= false
security.ssl3.ecdhe_rsa_aes_128_gcm_sha256	= true
security.ssl3.ecdhe_rsa_aes_128_sha		= false
security.ssl3.ecdhe_rsa_aes_256_gcm_sha384	= true
security.ssl3.ecdhe_rsa_aes_256_sha		= true
security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256 = true
security.ssl3.ecdhe_rsa_rc4_128_sha		= false
security.ssl3.rsa_aes_128_sha			= true
security.ssl3.rsa_aes_256_sha			= true
security.ssl3.rsa_des_ede3_sha			= false
security.ssl3.rsa_rc4_128_md5			= false
security.ssl3.rsa_rc4_128_sha			= false

**Comment by jedisct1** [comment]
Do not change anything.

DNSCrypt doesn't use TLS.
dnscrypt-proxy uses TLS 1.3 to connect to DoH servers, but Firefox has nothing to do with this.
