### ISSUE TITLE
Listen on port 53 on FreeBSD

### ISSUE THREAD

**Issue by mimugmail** [DNSCrypt/dnscrypt-proxy#658]
Hi, 

just looked around the closed issues but I can't find a good answer.
I want to run dnscrypt-proxy on port 53 but I always get:

 `listen udp 127.0.0.1:53: bind: permission denied`

I already tried `user_name = 'root'` or `listen_address = []` and also checked via sockstat if port 53 is already in use (but isn't).

Is there another way I'm not aware of?

**Comment by jedisct1** [comment]
Hi!

How are you starting it? Are you using the FreeBSD port?

You should start is as `root`. You don't need to change `user_name` or `listen_address`.

**Comment by mimugmail** [comment]
I'm using the HBSD port and start via rc as root. I'm building the OPNsense plugin for it and would like to offer also running on 53

**Comment by jedisct1** [comment]
Unfortunately, I don't know much about HardenedBSD (assuming that this is what HBSD stands for).

But maybe there is something to explicitly allow command to be able to listen to specific ports?

**Comment by mimugmail** [comment]
Setting `dnscrypt_proxy_suexec:="YES"` as rc variable helps. Now I can finalize the plugin :) Thanks
