### ISSUE TITLE
Blacklist additional lists

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-proxy#660]
Does blacklist support additional files with lists like this?

> #### blacklist.txt
> include: advert-list.txt
> include: tracking-list.txt
> 
> ad.*
> advert.*
> ...

**Comment by jedisct1** [comment]
You can use the [`generate-domains-blocklist.py` script](https://github.com/jedisct1/dnscrypt-proxy/wiki/Public-blacklists) for this
