### ISSUE TITLE
Feature request: HTTP/3 support

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [DNSCrypt/dnscrypt-proxy#661]
With this feature any communication with remote DNSCrypt or DoH server would be passed through HTTPS/3 proctol.

**Comment by jedisct1** [comment]
HTTP/3 does not exist yet.

And you can get the same performance as DNS-over-HTTP-over-QUIC today, with better privacy, by using DNSCrypt instead.

**Comment by uBlock-user** [comment]
@jedisct1 

https://www.zdnet.com/article/http-over-quic-to-be-renamed-http3/
https://quicwg.org/base-drafts/draft-ietf-quic-http.html

**Comment by Mikaela** [comment]
I guess it's in the same state as https://github.com/jedisct1/dnscrypt-proxy/issues/656, not finalized and deployed yet.

**Comment by uBlock-user** [comment]
> same state as #656

Not exactly, it's not even in fully developed yet, on the other hand QUIC soon to be known as HTTP/3 is already used in stable builds of Chromium/Chrome since 2012 and is in deployed on all google sites including youtube.

**Comment by publicarray** [comment]
@uBlock-user I just want to point out that HTTP/3 is in a draft stage, meaning more changes to the protocol are expected until it is finalised. Interestingly there are Google QUIC Transport and IETF QUIC Transport [Implementations](https://github.com/quicwg/base-drafts/wiki/Implementations) with different draft revisions.

[HTTP-over-QUIC](https://tools.ietf.org/html/draft-ietf-quic-http) != [QUIC](https://tools.ietf.org/html/draft-ietf-quic-transport)

---

Some reading material: 

Book by curl developer Daniel Stenberg: https://http3-explained.haxx.se/en/ - [Github](https://github.com/bagder/http3-explained)

Recent Changes:
https://github.com/quicwg/base-drafts/commits/master/draft-ietf-quic-http.md

https://mailarchive.ietf.org/arch/msg/quic/RLRs4nB1lwFCZ_7k0iuz0ZBa35s

**Comment by publicarray** [comment]
[From the book:](https://http3-explained.haxx.se/en/proc-status.html)

> As of November 2018, there still has not been any larger interoperability tests with HTTP/3 - only with the existing two implementations and none of them are done by a browser or a popular open server software.
>[..]
> None of the larger browser vendors have yet shipped any version, at any state, that can run the IETF version of QUIC or HTTP/3.
>
>Google Chrome has shipped with a working implementation of Google's own QUIC version since many years, but that does not interoperate with the official QUIC protocol and its HTTP implementation is different than HTTP/3.

**Comment by jedisct1** [comment]
Good read on QUIC and HTTP/3: https://calendar.perfplanet.com/2018/quic-and-http-3-too-big-to-fail/
