### ISSUE TITLE
Tired, befuddled, old man needs help with verifing minisign signatures

### ISSUE THREAD

**Issue by EauBureau** [DNSCrypt/dnscrypt-proxy#663]
Before I start, sorry if this is tedious basic stuff, but it's tripping me up...

I've tried verification using the `signify-openbsd` (a.k.a signify) tool.

I've stuck this in a plain text file and called it key.pub:
`untrusted comment: diy test public key
RWTk1xXqcTODeYttYMCMLo0YJHaFEHn7a3akqHlb/7QvIQXHVPxKbjB5`

I got that base64 string from the bottom of the [installation page](https://github.com/jedisct1/dnscrypt-proxy/wiki/installation)

I tried to verify using

`$ signify-openbsd -C -p key.pub -x 'dnscrypt-proxy-android_arm-2.0.19.zip.minisig' 'dnscrypt-proxy-android_arm-2.0.19.zip'`

But it just returns
`signify-openbsd: signature verification failed`

I guess my diy public key file is the issue?
Where do you publish your "proper" minisign public key file?

Why is `minisign` not in the Debian/Ubuntu resposiotries?
It seems the only way to get `minisign` is to compile it.
I've not compiled my own binaries before and it's a bit of a step too far for me.

How come you don't provide `minisign` linux binaries like you do for `dnscrypt-proxy`?
Why not just use GnuPG to sign a list of checksums?

Again, sorry and thanks.

**Comment by jedisct1** [comment]
Windows and MacOS binaries for Minisign are available here: https://jedisct1.github.io/minisign/

It's also available as a package for most Unix-based operating systems and Linux distributions.

If it is not available for yours, maybe you can build and submit one? Or at least bump [this ticket](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869169)?

I don't use Linux, and I wrote Minisign because it was faster and easier than understand how to use GPG.

**Comment by EauBureau** [comment]
Thanks for the reply.

> If it is not available for yours, maybe you can build and submit one

I'm flattered, but you're severely overestimating my abilities. I'm struggling just to verify this signature.  :confused:

Where do you post the official public key for `dnscrypt-proxy` or is that bsae64 string at the end of the [Installation page](https://github.com/jedisct1/dnscrypt-proxy/wiki/installation) sufficient?

Thanks.

**Comment by jedisct1** [comment]
You just need to copy and paste the command given in that page. The public key is very short, and is a command-line argument.

**Comment by EauBureau** [comment]
Unfortunately I don't have `minisign`. 
I'm trying to use `signify` as a workaround.
I think `signify` needs a public key _file_ instead of a ~base64 string~ command line argument.
I tired to make my own DIY public key file but I'm not sure its working right.
I'm new to `signify` too

**Comment by jedisct1** [comment]
`minisign` can verify signatures produced by `signify`, but `signify` doesn't support `minisign` extensions.

**Comment by EauBureau** [comment]
But `signify` can verify `minisign` signatures?

**Comment by jedisct1** [comment]
I don't think so.

**Comment by EauBureau** [comment]
But [minisign docs]( https://jedisct1.github.io/minisign/) says
> Signature written by minisign can be verified using OpenBSD's signify tool: public key files and signature files are compatible.

???

**Comment by jedisct1** [comment]
Ah, so maybe it can, then. Sorry, I don't remember.

**Comment by EauBureau** [comment]
I know the feeling ...  :smile:

**Comment by EauBureau** [comment]
So there is no official public key _file_?

**Comment by jedisct1** [comment]
The `minisign.pub` file is in the dnscrypt-proxy repository.

**Comment by jedisct1** [comment]
It seems to work with signify and [that public key](https://download.dnscrypt.info/dnscrypt-resolvers/v2/).

**Comment by EauBureau** [comment]
I'm getting this error with that key
`signify-openbsd: verification failed: checked against wrong key`

Looking inside `minisign.pub` :
`untrusted comment: minisign public key used to sign the resolvers list
RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3`

Shouldn't that base64 string be...
`RWTk1xXqcTODeYttYMCMLo0YJHaFEHn7a3akqHlb/7QvIQXHVPxKbjB5`
...like it says on the [installation page](https://github.com/jedisct1/dnscrypt-proxy/wiki/installation)?


Look, I'm sure you're **way** busier than to be fixing my `signify` key signing hassles.
Simple thing is I'm just going to have to get my head around compiling my own `minisign`.

Thanks again.
