### ISSUE TITLE
[Feature Request] Schedules for Mac Addresses or IP

### ISSUE THREAD

**Issue by bytespider** [DNSCrypt/dnscrypt-proxy#669]
I would like to set up schedules for different users on my network, for instance block the children from YouTube and Games etc while they do their homework but allow the adults to continue to use the internet unrestricted.

In my case my router is also responsible for DHCP.

**Comment by jedisct1** [comment]
Hi!

You can configure the adult's computers to use a different DNS IP.

I run such a setup, with two dnscrypt-proxy instances, running with different configurations, different  local IPs, but on the same router.

**Comment by bytespider** [comment]
Thats an interesting Idea, wonder what the overhead is like for that on my PI Zero.
I could probably even forward to the different DNS server based on mac address using iptables
