### ISSUE TITLE
[ISSUE] No elements in the list | [Help] ignore_system_dns

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#67]
**1) Strange message** again during launching `*.bat` commands (on English):

`There are no elements in the list.`

Last time it was my fault, I've forgot put the `*.txt` file where it should be (custom path).
This time I've rechecked all settings (as always), files and pathes.
If I'm using your pack as it is, I have the same error.

May be it is problem with spaces in the path again or so?

But dnscrypt-proxy works, I don't see other issues.

**2) Small advise**

IMHO, the name of this parameter and description is very unclear:

`ignore_system_dns = false`

Because, when I see "system", I think about traditional meaning - Windows Network adapter settings.

Better should be like this:

```
# Switch to common non-encrypted DNS resolver. Fallback resolver will be used.
# All bennefits of the DNS encryption technology will be eliminated.

non_encrypted_dns = false
```

**Comment by iWARR** [comment]
May be new option [schedules] doesn't understand, where is my custom blocking file and custom path?
I don't use schedules, anyway this lines are commented/deleted:

`# [schedules]`

(on the bottom - empty space, rest of lines deleted, end of file)

**Comment by jedisct1** [comment]
`ignore_system_dns` means exactly that: Windows Network adapter settings (on Windows).

In order to load `https://example.com/resolvers.md`, should it try the system DNS settings to resolve `example.com` (and fallback to the fallback resolver if that fails), or should it assume that the current settings don't work, and go straight to the fallback resolver?

There's no encryption here. Setting this to "true" just eliminates a 30 second delay, only the first time the service is launched, and only if even that first time, you have a system with a DNS configuration that doesn't work.

I suspect that some people on some routers may want that.

**Comment by jedisct1** [comment]
As a side note, people with the same issues as yours will never ever find them.

In order to avoid this, it would be nice to give issues a more relevant title (here: the exact error message you saw), and to dedicate one issue to one topic instead of mixing unrelated subjects. Thanks!

**Comment by iWARR** [comment]
Thanks for the explanation. This time I understand the meaning.

Anyway, I think, the info in the *.toml is very unsatisfactory.
Your new good explanation + info about 30 sec. may become useful (user will understand what waiting for from this mode).

**Comment by iWARR** [comment]
> ignore_system_dns means exactly that: Windows Network adapter settings (on Windows).

**My disagrees:**

-  `ignore_system_dns = false` [ **Q:** Are you "ignore_system_dns" using DNSCrypt normally? **A:** (?) ]
Yes? So, why you have "false" here? Misunderstood.

- `ignore_system_dns` will have no luck on Windows Network adapter, because 127.0.0.XX1, 127.0.0.XX2 are already set in this place (if you already had dnscrypt-proxy installed). The very new customer will read the wiki or short manual on 3-rd party forum and will set the same 127.0.0.XX1, 127.0.0.XX2 on the adapter before starting dnscrypt-proxy first time)   :))))

- `ignore_system_dns` = (unlucky) system DNS = `fallback_resolver` for 30 sec. OK?` fallback_resolver` comes from `*.toml`, isn't it? Yep, this is not Windows Network adapter settings again.

- `fallback_resolver` is not ISP DNS also, because you recommend DNSSEC support for it (or external IBM Quad9 - 9.9.9.9 as example). Internal ISP DNS don't have such support in most cases. So, it is not ISP, so it's not relevant to settings from Windows Network adapter again.

(I don't know how this work in routers yet, but soon I will. Very nice, you care about routers!)

So, I'm propose clear and short variant:

```
# Temporary switch to common non-encrypted DNS resolver.
# Fallback resolver will be used for 30 seconds to load resolvers list.

30sec_fallback_dns = false
```

**Comment by halmansour7** [comment]
[](url)http://halmanbitter7moh.wordpress.com

**Comment by jedisct1** [comment]
Since it's confusing, this flag will be removed from the example configuration file, and just be left in the documentation, when there will be a documentation.
