### ISSUE TITLE
Uninstall DNScrypt From Android

### ISSUE THREAD

**Issue by hasanalizxc** [DNSCrypt/dnscrypt-proxy#670]
Hi All,

I flashed Dnscrypt with [this](https://dnsmanager.me/dnscrypt-proxy-android-armv7-a-1.9.4.zip) and i want to uninstall now. Is there any flashable uninstall.zip?

Thank you.

**Comment by r4sas** [comment]
Try this

[dnscrypt-proxy-android-armv7-a-1.9.4-uninstall.zip](https://github.com/jedisct1/dnscrypt-proxy/files/2720009/dnscrypt-proxy-android-armv7-a-1.9.4-uninstall.zip)
