### ISSUE TITLE
HOWTO: Connecting to a remote dnscrypt-proxy client from Android P using DNS-over-TLS

### ISSUE THREAD

**Issue by chew-z** [DNSCrypt/dnscrypt-proxy#676]
Not an issue per se but perhaps not everyone noticed this.

As Android P supports configurable DNS-over-TLS it is very easy to redirect DNS queries from smartphone to your own server with dnscrypt-proxy (with your own blacklists, whitelists etc.). No additional app is required.

You will need:

- server with dnscrypt-proxy
- nginx with stream modules ( build with --with-stream, --with-stream_ssl_module)
- open port 853

Just add this snippet to nginx.conf

```
stream {
    upstream dns-servers {
        server    127.0.0.1:53;
    }

    server {
        listen 853 ssl;
        proxy_pass dns-servers;

        ssl_certificate            /etc/nginx/ssl/dot-server.crt;
        ssl_certificate_key        /etc/nginx/ssl/dot-server.key;

        ssl_protocols        TLSv1.2;
        ssl_ciphers          HIGH:!aNULL:!MD5;
        
        ssl_handshake_timeout    10s;
        ssl_session_cache        shared:SSL:20m;
        ssl_session_timeout      4h;
    }
}
```
Restart nginx. 

In Android go to Settings-Network-Advanced-Private DNS and add the name of your server. This setting will persists for Wifi and Mobile connections.

**Comment by jedisct1** [comment]
Thanks for the tip, Chew-Z! Maybe something worth adding to the Wiki!
