### ISSUE TITLE
Freeze on downloading list from URL

### ISSUE THREAD

**Issue by ur0b0r0** [DNSCrypt/dnscrypt-proxy#677]
In config file "domains-blacklist.conf" updated URL should be: http://sysctl.org/cameleon/hosts**.win**

**Comment by publicarray** [comment]
The only difference is the line endings. Are you on Windows? I always thought that python dosn't care
```
http://sysctl.org/cameleon/hosts: UNIX (LF)
http://sysctl.org/cameleon/hosts.win: DOS/Windows (CR-LF)
```

**Comment by ur0b0r0** [comment]
In 29 Dec 2018 there was problem witch http://sysctl.org/cameleon/hosts file, but now it is reachable. 
In this case replace extension to "hosts.win" allowing generate updated "dnscrypt-blacklist-domains.txt" without freeze, eventually using switch "generate-domains-blacklist.py -i "  solve problem witch inactive URL link. I also think that end line signs don't matter to python.

I'am on Arch.
