### ISSUE TITLE
Connecting more servers

### ISSUE THREAD

**Issue by ngx3** [DNSCrypt/dnscrypt-proxy#679]
Hello,

I currently use Simple DNSCrypt and currently use the pre-defined resolvers but like to use a couple from https://servers.opennic.org/ I don't see anywhere to add IPs or DNSCrypt keys to connect to those servers.

**Comment by jedisct1** [comment]
This is probably because they don't support secure connections, only regular DNS.

dnscrypt-proxy will not send unencrypted queries to DNS servers.

**Comment by ngx3** [comment]
But they do support secure connections with the use of DNSCrypt. How would I add a resolver to either dnscrypt-proxy service (https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-Windows) or SimpleDNSCrypt?

For example, this network that I want to connect to below isn't on your https://dnscrypt.info/public-servers list.

**Provider Address:** X.XX.X.XX:5353 
**Provider Name:** 2.dnscrypt-cert
**DNSCrypt Key:** < key >

And if you see here: https://servers.opennic.org/ you can see they support DNSCrypt connections by the orange flag.

**Comment by jedisct1** [comment]
If the list is incomplete, the list has to be updated :)

What servers are missing?

**Comment by ngx3** [comment]
So it's not possible for users to add/connect to servers manually while using DNSCrypt?

There are too many servers to list.

**Comment by r4sas** [comment]
You can use `[static]` block to add your servers.

**Comment by jedisct1** [comment]
You can add new servers, and this is in the documentation, but all the OpenNIC servers should be in the list. If they aren't, it would be better to report which ones are missing so they can be added.

**Comment by r4sas** [comment]
I can report about them.

Currently opennic-onic and opennic-tumabox (+ opennic-tumabox-ipv6) not listed at servers.opennic.org.

Unlisted servers:
https://servers.opennic.org/edit.php?srv=ns3.vic.au.dns.opennic.glue
> sdns://AQYAAAAAAAAADzEwMy4yMzYuMTYyLjExOSCsA3mel5peBSzSovzwdgGi5qkfpWXYHfBxtBp7n8dliCkyLmRuc2NyeXB0LWNlcnQubnMwMy5tZWwudXNlcnNwYWNlLmNvbS5hdQ

But here not provided port. Full with port 443 here
>sdns://AQYAAAAAAAAAEzEwMy4yMzYuMTYyLjExOTo0NDMgrAN5npeaXgUs0qL88HYBouapH6Vl2B3wcbQae5_HZYgpMi5kbnNjcnlwdC1jZXJ0Lm5zMDMubWVsLnVzZXJzcGFjZS5jb20uYXU

IPv6 (port 5353):
>sdns://AQYAAAAAAAAAJ1syNDA0Ojk0MDA6MzowOjIxNjozZWZmOmZlZTA6N2Y2OV06NTM1MyCsA3mel5peBSzSovzwdgGi5qkfpWXYHfBxtBp7n8dliCkyLmRuc2NyeXB0LWNlcnQubnMwMy5tZWwudXNlcnNwYWNlLmNvbS5hdQ

https://servers.opennic.org/edit.php?srv=ns16.de.dns.opennic.glue

IPv4:
>sdns://AQYAAAAAAAAAEjUuMTg5LjE3MC4xOTY6NTM1MyBUNSxVQDuC7pPEB_3CNESXDZpW7yK_z_nskJzNMiQyaygyLmRuc2NyeXB0LWNlcnQubnMxNi5kZS5kbnMub3Blbm5pYy5nbHVl

IPv6:
>sdns://AQYAAAAAAAAAIFsyYTAyOmMyMDc6MjAwODoyNTIwOjUzOjoxXTo1MzUzIFQ1LFVAO4Luk8QH_cI0RJcNmlbvIr_P-eyQnM0yJDJrKDIuZG5zY3J5cHQtY2VydC5uczE2LmRlLmRucy5vcGVubmljLmdsdWU

https://servers.opennic.org/edit.php?srv=ns8.fr.dns.opennic.glue

IPv4:
>sdns://AQYAAAAAAAAAETE1MS44MC4yMjIuNzk6NDQzIO4Y9lZnORlvodxu39dnm6mFruwTRnlmovbEga4Fyw3TIDIuZG5zY3J5cHQtY2VydC5vcGVubmljLmkycGQueHl6

IPv6:
>sdns://AQYAAAAAAAAAG1syMDAxOjQ3MDoxZjE1OmI4MDo6NTNdOjQ0MyDuGPZWZzkZb6Hcbt_XZ5upha7sE0Z5ZqL2xIGuBcsN0yAyLmRuc2NyeXB0LWNlcnQub3Blbm5pYy5pMnBkLnh5eg

**Comment by uBlock-user** [comment]
> dnscrypt-proxy will not send unencrypted queries to DNS servers.

But it does to the domains listed in forwarding-rules.txt ?

**Comment by jedisct1** [comment]
Ah, yes, and with cloaking, too.

**Comment by uBlock-user** [comment]
I added `cloudflare-dns.com 8.8.8.8` to the `forwarding-rules.txt` and yet the website when [visited](https://cloudflare-dns.com/help) tests postive for DoH, why is that ?

**Comment by jedisct1** [comment]
That web page seems to use other domains for detection, namely `videodelivery.net`, `cloudflareresolve.com` and `cloudflarestream.com`. It connects to Google APIs, too.
