### ISSUE TITLE
How to configure transparent dns proxy for Linux host?

### ISSUE THREAD

**Issue by garywill** [DNSCrypt/dnscrypt-proxy#680]
I run dnscrypt-proxy listening on some port on linux, and use iptables.
I googled a lot and find two ways to do a transparent DNS proxy for Linux host
```
iptables -t nat -I OUTPUT -j REDIRECT -p udp --dport 53 --to-ports 1053
iptables -t nat -I OUTPUT -j DNAT -p udp --dport 53 --to 127.0.0.1:1053
```

When I use `dig` to lookup, `dig` says 

> except x.x.x.x(DNS in /etc/resolv.conf) but x.x.x.x(host's IP)

This issue only occur in udp, `dig +tcp` is ok.

**Comment by jedisct1** [comment]
`except x.x.x.x(DNS in /etc/resolv.conf) but x.x.x.x(host's IP)`

It's hard to decipher this, but what probably happens is that the query is sent to an IP address, but the response comes from a different one. Which means that your NAT rules don't work.

Maybe you don't need just `DNAT`, but also NAT in the other direction.

Sorry, I don't use Linux, so I can hardly help here.
