### ISSUE TITLE
[2.dnscrypt-cert.qualityology.com.] Incorrect signature

### ISSUE THREAD

**Issue by MystesofEternity** [DNSCrypt/dnscrypt-proxy#681]
This thing started since December 26 and I found a thread here made by the owner of this DNS Server so I decided to open this up in hopes of reaching out to the owner that their DNS server may have been compromised already.

**Comment by jedisct1** [comment]
It doesn't necessarily mean that it has been compromised. It can just be that the server clock is off, or that a key rotation script didn't work as expected. 

You should rather comment on where these servers were added: https://github.com/DNSCrypt/dnscrypt-resolvers/pulls?utf8=%E2%9C%93&q=is%3Apr+qualityology

**Comment by publicarray** [comment]
@jedisct1 note that the linked pull requests are locked...

**Comment by ex-git** [comment]
Not sure why it happened.  Just recreated the server.
