### ISSUE TITLE
ARM releases should have builds for arm5, arm6, arm7 respectively

### ISSUE THREAD

**Issue by eripa** [DNSCrypt/dnscrypt-proxy#682]
I tried to setup dnscrypt-proxy using the released version of dnscrypt-proxy (2.0.19) for FreeBSD "arm" on a Raspberry Pi 2. Unfortunately it seem to have been compiled with `GOARM=5` which causes it to exit with:

```
./dnscrypt-proxy -version
runtime: this system has multiple CPUs and must use
atomic synchronization instructions. Recompile using GOARM=7.
```

If I recompile it manually on my Mac using either:

`GOOS=freebsd GOARCH=arm go build -ldflags="-s -w"`
or
`GOOS=freebsd GOARCH=arm GOARM=6 go build -ldflags="-s -w"`
or
`GOOS=freebsd GOARCH=arm GOARM=7 go build -ldflags="-s -w"`
**it runs fine.** 

If I compile it using `GOARM=5` it will result in a binary with the _same broken behaviour_. 

It seems like the release builds are built using GOARM=5, or that the default Go build parameter is different than mine is (`go version go1.11.4 darwin/amd64`).

**Comment by jedisct1** [comment]
This is a bit weird, because the `freebsd-arm` build simply uses `GOARCH=arm`: https://github.com/jedisct1/dnscrypt-proxy/blob/b8865854869ae5cbaad2c7e5ea64780b60b83ed1/.travis.yml#L54-L58

**Comment by jedisct1** [comment]
It's using Go 12, though. Maybe a regression here?

**Comment by eripa** [comment]
Yeah, it is a bit strange indeed.

I just tried to build it using the `HEAD` version of Go:

```
go version devel +73fb3c38a6 Mon Jan 7 14:13:33 2019 +0000 darwin/amd64
```

and it still works fine with the default (i.e. GOARM unset).

**Comment by jedisct1** [comment]
`¯\_(ツ)_/¯ `

**Comment by eripa** [comment]
`(｡◕‿◕｡)`
I suppose the easiest thing to do would be to set `GOARM=6`. As far as I understand that should work for both arm6 and arm7, which is more compatible than the `5` binary.

**Comment by jedisct1** [comment]
Maybe there was a change in Go between the snapshot used to build the release and the one you used?

In that case, the next release should be good without any change.

**Comment by eripa** [comment]
Sorry for the slow response. To verify this I tested past freebsd/arm releases back to 2.0.10, and they all behave the same. This indicates that this is not caused by the specific Go version.

**Comment by jedisct1** [comment]
Is it still the case?
