### ISSUE TITLE
Running as SYSTEM on Windows

### ISSUE THREAD

**Issue by milgradesec** [DNSCrypt/dnscrypt-proxy#686]
dnscrypt-proxy windows service runs as NT AUTHORITY\SYSTEM (full control over machine) , it should run with fewer privileges as NT AUTHORITY\NetworkService user.

**Comment by jedisct1** [comment]
I have no idea how to do that, but if you do, or manage to find people to write the required changes, I'd be glad to merge them!

Thanks for your help!

**Comment by milgradesec** [comment]
Add this line to service-install.bat before starting the service:

sc config dnscrypt-proxy obj="NT AUTHORITY\NetworkService" password= ""

**Comment by jedisct1** [comment]
Where exactly?

Between

```
dnscrypt-proxy.exe -service install
```

and

```
dnscrypt-proxy.exe -service start
```

?

What about `restart` and `uninstall`?
What Windows systems does that work on?
What happens after an update if the service wasn't previously installed with that command?

**Comment by r4sas** [comment]
https://github.com/jedisct1/dnscrypt-proxy/blob/b8865854869ae5cbaad2c7e5ea64780b60b83ed1/vendor/github.com/kardianos/service/service_windows.go#L214-L215

**Comment by milgradesec** [comment]
1) Yes , like this:
dnscrypt-proxy.exe -service install
sc config dnscrypt-proxy obj="NT AUTHORITY\NetworkService" password= ""
dnscrypt-proxy.exe -service start

2) Only needed at install , HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dnscrypt-proxy!ObjectName key stores it (by default is LocalSystem and changes to NT AUTHORITY\NetworkService)

3) sc.exe is included with all versions of windows since Xp or 2000

4) If you dont run the command dnscrypt service will run as SYSTEM, if you do it will run as NetworkService.

**Comment by jedisct1** [comment]
@r4sas Do you mean that we should set `ServiceStartName` to `NT AUTHORITY\NetworkService`?

**Comment by r4sas** [comment]
@jedisct1 yes, but it need testing.

add:
If all configured correctly, `sc` must return output like this:
```cmd
>sc qc dnscrypt-proxy
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: dnscrypt-proxy
        ...
        SERVICE_START_NAME : NT AUTHORITY\NetworkService
```

**Comment by milgradesec** [comment]
it works fine as NetworkService

**Comment by r4sas** [comment]
<strike>Doesn't it was easier to add `ServiceStartName` here?
https://github.com/jedisct1/dnscrypt-proxy/blob/1877ca83defd73f1e9a53e662d3158e9467cc19c/dnscrypt-proxy/main.go#L32-L37
</strike>
upd:
ah, you done that for covering all type of services

upd2:
Tested, all works as needed.
![image](https://user-images.githubusercontent.com/7023612/51014045-cbbd0f00-1576-11e9-996e-ec4147685291.png)
