### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN error in web-browser

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#687]
Hi!

Before a few days, I get this message in my web-browser:

The server ip could not be found...

"DNS_PROBE_FINISHED_NXDOMAIN"

Then 3-5 seconds after that, the webpage is still reloaded and then it works.

What can I do to fix that?

Try another dnscrypt-proxy-server?

Please help, thanks!

**Comment by jedisct1** [comment]
A quick [Google search](https://community.cloudflare.com/t/dns-probe-finished-nxdomain/16113/2) says that it happens when an *authoritative* server is broken. That is, one of the servers of the website you are trying to reach.
