### ISSUE TITLE
connecting to server failed

### ISSUE THREAD

**Issue by ted-dev-42** [DNSCrypt/dnscrypt-proxy#69]
It has been working for a while, but after I rebooted my client computer(didn't change anything on client and server),  dnscrypt-proxy can't connect to server any more, only got the following output, 

[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate #1517516072 received
[INFO] This certificate has not been activated yet
[WARNING] Unsupported certificate version
[ERROR] No useable certificates found
[INFO] Refetching server certificates
[INFO] Server certificate #1517516072 received
[INFO] This certificate has not been activated yet
[WARNING] Unsupported certificate version
[ERROR] No useable certificates found
[INFO] Refetching server certificates
[INFO] Server certificate #1517516072 received
[INFO] This certificate has not been activated yet

any help will be greatly appreciated.

**Comment by phonphen** [comment]
i think dnscrypt-proxy 1.6.0, not supported anymore

get new dnscrypt-proxy 2

**Comment by ted-dev-42** [comment]
I finally figure it out, it's because the client's timezone is different with the server's timezone, making them the same solves the problem.
