### ISSUE TITLE
feature request: disable sni

### ISSUE THREAD

**Issue by updatede** [DNSCrypt/dnscrypt-proxy#693]
for privacy please add an option to disable sni in request to doh server.
if doh server’s default certificate does not include its hostname, please add an option to designate which name to be verified.

**Comment by jedisct1** [comment]
The host name is independent from the IP address and can already be set to anything in the DNS stamp. You can put random garbage here or even have it empty.

But that would do more harm that good.

If no SNI information is present, it means that the server hosts a DoH server and nothing else, so the purpose of your connection is obvious.

If the server hosts multiple websites, SNI information is required to connect. It's not just about what name should be verified; the server needs to send you the correct certificate chain and content to start with.

**Comment by updatede** [comment]
@jedisct1 
In stamp, there’s no seperate name for virtual host and sni, so if set hostname to empty or garbage, doh  server cant locate right virtual server. Host name is in url and encrypted, no privacy issue, but sni is cleartext, if can’t set them separately ,it would be nice to disable it. SNI is just for server to select certificate, if no sni, server will send a default certificate, some server will include doh server name in this default certificate, if not, it’s ok, we just verify this default certificate and default name, not host name we send, it will not break security but keep privacy.(esni is another option, but now not depolyed widely).

**Comment by jedisct1** [comment]
Domain fronting is slowly getting block everywhere, this is not something you can rely on.

**Comment by updatede** [comment]
This is totally not domain fronting , we send correct domain name in url , just do not send sni, how about clients not support sni ? server absolutely won’t block it, just send a cert let client possibly fail to verify, we just let it pass.

**Comment by jedisct1** [comment]
I don't know how to do that.

**Comment by Mikaela** [comment]
> (esni is another option, but now not depolyed widely).

from https://github.com/jedisct1/dnscrypt-proxy/issues/622 I understand that dnscrypt-proxy supports it so I think maybe it would be better for you to enable esni on your server?
