### ISSUE TITLE
suggestion and question: all in one v1

### ISSUE THREAD

**Issue by absynteZero** [DNSCrypt/dnscrypt-proxy#699]
Hi guys and jedisct1 particularly.

First i know private message are disabled but..we need to share and communicate.
i suggest to github to create a new section.

We already have code, issues, pull request, wiki and insight.

I suggest to add a forum tab for all other things.

For the app, i like it but i need really to be able to stop the dnscrypt-proxy service from the app folder.
Can you add a stop-service.bat to run as admin?

The app is really stable, very lightweight.
Nothing more is needed but i need too more verbosity in the query.log.
About security options and cipher used.
Are they really used..? The needs to know that.
*Comparing to openvpn logs (...).

I have already said this, but with android, we don't have any dnscrypt app, it will be a very great pleasure to use it on my phone too.

I have personaly some concept and app ideas but i will not disturb with because i don't know how to create.

Last thing, i try to find a clipboard overrider and eraser.
I already use a .bat to clean and a near 512 Mo txt file full of letters, numbers, and caracters.

I need an app to do this simply in one click, i need to set how many time i override.

So...thanks

Best regards

**Comment by jedisct1** [comment]
GIthub doesn't have forums, but there is a [subreddit](https://www.reddit.com/r/dnscrypt/) dedicated to DNSCrypt.
