### ISSUE TITLE
509: certificate is valid for 192.168.1.1, not dns.cloudflare.com

### ISSUE THREAD

**Issue by zloeby4i** [DNSCrypt/dnscrypt-proxy#701]
Hi, I got an error, what could be wrong?
Сhanged configuration parameters:
```
server_names = ['cloudflare']
listen_addresses = ['127.0.0.1:53']
dnscrypt_servers = false
fallback_resolver = '1.0.0.1:53'
```
Error
`янв 17 18:49:25 depher dnscrypt-proxy[15386]: Get https://dns.cloudflare.com/dns-query?body=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&random_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: x509: certificate is valid for 192.168.1.1, not dns.cloudflare.com`

**Comment by jedisct1** [comment]
This is good.

There is something hijacking your connection. Maybe some kind of proxy, that sent you a fake certificate.

`dnscrypt-proxy` detected this, and refused to connect.

Since you didn't provide any context, that's all I can say.

**Comment by Mikaela** [comment]
I think it's a captive portal and if you went to http://192.168.1.1/ it would ask you to accept terms and/or click connect.

A tip I saw somewhere is running `ip -4 route show` and attempting to connect to the default gateway using http so it should show the captive portal page.

**Comment by jedisct1** [comment]
Ah yes, good catch, that's definitely an option.

**Comment by zloeby4i** [comment]
The reason was in the router from my provider. After replacing router, everything works fine. Thanks.
