### ISSUE TITLE
Use network default DNS as fallback resolver?

### ISSUE THREAD

**Issue by MikuAuahDark** [DNSCrypt/dnscrypt-proxy#702]
Hello, and thank you for this nice software. Sorry if the title is somewhat misleading, I can't think of any issue name for my problem.

I have a problem on my specific case, where `dnscrypt-proxy` fails to start because it cannot use the fallback resolver address. After some investigation, it looks like my ISP **blocks** all DNS request if it's not their own resolver. This means I can't use `8.8.8.8`, `1.0.0.1`, `9.9.9.9`, `114.114.114.114`, or any external DNS resolver IPs at all.

The another problem is I don't know their DNS resolver IP address (also I'm often switching network so hardcoding the fallback resolver to their own is not an option), so I'm only left with `192.168.*.*` as fallback resolver. Unfortunately, the WiFi I commonly use has dynamic local address too (and I don't have permission to make it static), which means, say if I put `192.168.43.150` as fallback resolve, it won't work when the WiFi is restarted as the IP is changed.

A workaround in Ubuntu is to modify the network setting, make the DNS resolver automatic, restart network, and dnscrypt-proxy will use system fallback DNS. Then switch back to dnscrypt DNS resolver IP. This works, but it somewhat annoying to do on every boot. In Windows, I created task scheduler which runs on boot to touch the `public-resolvers.md` so dnscrypt-proxy thinks the public resolver is updated. Of course I'm not happy with that workaround in a long-term.

I experienced this problem both in Ubuntu 18.04 (2.0.19) and Windows 10 (2.0.17), both uses dnscrypt-proxy v2.0 or later, so a version may not really relevant in my problem, as long as it's v2.0 or later.

Is anyone have a solution for my problem? I'm currently writing this by forcing Firefox to use Cloudflare DoH because dnscrypt-proxy fails to download the public resolvers at all.

**Comment by rampageX** [comment]
Are you try DNS server with non-standard port? OpenDNS have these:
```
208.67.222.222:443
208.67.222.222:5353
```

**Comment by MikuAuahDark** [comment]
Sorry, looks like OpenDNS IP is blocked by my ISP.

Pada tanggal Sab, 19 Jan 2019 13.27, rampageX <notifications@github.com>
menulis:

**Comment by MikuAuahDark** [comment]
Didn't know OpenDNS has non-standard port for ISPs that monitors port 53, thanks.

**Comment by jedisct1** [comment]
As documented, you can use `dnscrypt-proxy -resolve` to see the IP address of the DNS resolver you are using.

So you can use it to find the IP address of your ISP.

```sh
./dnscrypt-proxy -resolve example.com
Resolving [example.com]

Domain exists:  yes, 2 name servers found
Canonical name: example.com.
IP addresses:   93.184.216.34, 2606:2800:220:1:248:1893:25c8:1946
TXT records:    v=spf1 -all
Resolver IP:    162.158.192.88
```

**Comment by absynteZero** [comment]
Very nice!

Thanks to jedisct1 to help the censured world.

We all nice peace and liberty.
