### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by Elite** [DNSCrypt/dnscrypt-proxy#703]
I had tried multiple times to install and use DNSCloak on my iOS device but online DNS tests always show my ISP dns and no ads are being blocked. How to go about troubleshooting this?

**Comment by jedisct1** [comment]
What did you install exactly? DNSCloak?

**Comment by Elite** [comment]
Yes, isn't that the only option for iOS ?

**Comment by jedisct1** [comment]
On a jailbroken device, you can run the proxy directly.

Verify that the VPN icon is displayed, and turn on "connect on demand" if necessary.

**Comment by Elite** [comment]
Not jailbroken, what options am I left with. 

The VPN icon shows and everything seems to run without any error/warning but it simply does not work for blocking ads.

**Comment by pengelana** [comment]
For troubleshooting try to enable service log: DSCloack - DNSCrypt Setting - tap Enable Service log. 

![Imgur](https://i.imgur.com/2IQzDYP.jpg)

After connecting, check the log. You should see something like this:

[2019-01-20 02:49:29] [NOTICE] Server with the lowest initial latency: id-gmail (rtt: 6ms)
[2019-01-20 02:49:29] [NOTICE] dnscrypt-proxy is ready - live servers: 4

if you want to try adblocking server, you can try id-gmail or id-gmail-doh, it's currently blocking 280K unique ad/ad-tracking  domains.

with browser all the ad will become blank:

![Imgur](https://i.imgur.com/XcEGgJP.png)
