### ISSUE TITLE
dnscrypt and frokplayer = 404

### ISSUE THREAD

**Issue by uzazzap** [DNSCrypt/dnscrypt-proxy#705]
Hi!
When im configured dnscrypt and forkplayer dns replace with mac of my TV, my forkplayer return 404 error and never start. 
404 cause dnscrypt? Can i configure exception for my tv?

**Comment by jedisct1** [comment]
I don't know what forkplayer is, but some domains may resolve differently when sent to a local resolver (typically, the router) and when sent somewhere else.

As explained in the documentation, you can have exceptions for this: https://github.com/jedisct1/dnscrypt-proxy/wiki/Forwarding

Look at the query log to see what domain names forkplayer is trying to resolve, and forward these to the router.
