### ISSUE TITLE
Guide for OpenWRT with IPv6?

### ISSUE THREAD

**Issue by nariox** [DNSCrypt/dnscrypt-proxy#707]
I'm trying to use DNSCrypt-Proxy with Openwrt. The wiki shows how to set 127.0.0.53 as the dns for LAN and WAN, but no information on how to do it with WAN6. I've tried for a little bit to set up a listen-address with a local IPv6 address, but I'm not very acquainted with IPv6 (like scopes, etc). Anyone here could give me some help to set it up?

Thank you

**Comment by r4sas** [comment]
https://github.com/jedisct1/dnscrypt-proxy/blob/c8156829c5d0705d57f22a3f6f9a548031f2ef19/dnscrypt-proxy/example-dnscrypt-proxy.toml#L36

**Comment by jedisct1** [comment]
For WAN6, you can try using `::FFFF:127.0.0.53`.
