### ISSUE TITLE
[Question] Intended -list-all behaviour

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#71]
Hi, while doing some tests I noticed that the '-list-all' switch works as advertised (or as I understand it) when using a TOML config file like example-dnscrypt-proxy.toml. When 'server_names' is commented, the -list-all command indeed does show the full list of available resolvers. Yet when uncommenting the 'server_names' array, this behavior changes (drastically). In that scenario '-list-all' only returns the resolvers specified, not 'all' as I was expecting.

```
Arch Linux
$ pacman -Q dnscrypt-proxy-go-git
dnscrypt-proxy-go-git 2.0.0rc.r7.gbf56644-1

$ grep -m 1 server_names /etc/dnscrypt-go/dnscrypt-proxy.toml
# server_names = ['scaleway-fr', 'google', 'yandex']

$ sudo /usr/bin/dnscrypt-proxy -list-all # output cut for readability
adguard-dns-family
adguard-dns
adguard-dns-family-ipv6
...
ventricle.us
yandex
google

$ sudo sed 's/# server_names/server_names/' /etc/dnscrypt-go/dnscrypt-proxy.toml
$ grep -m 1 server_names /etc/dnscrypt-go/dnscrypt-proxy.toml
server_names = ['scaleway-fr', 'google', 'yandex']

$ sudo /usr/bin/dnscrypt-proxy -list-all
scaleway-fr
yandex
google

```
 Is this the intended behaviour of the -list-all switch?

I tried reading and understanding the code, and I *think* it *might* be a bug. 
[dnscrypt-proxy/config.go](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/config.go#L235) contains the below snippet. If I only knew Go I could experiment and
find out by myself :)
Alas I'll have to resort to (very pseudo) pseudo-code here...

```
if *listAll {
                <<< also set config.ServerNames to an empty string here ??? >>>
		config.SourceRequireDNSSEC = false
		config.SourceRequireNoFilter = false
		config.SourceRequireNoLog = false
		config.SourceIPv4 = true
		config.SourceIPv6 = true
}
```

Regards

**Comment by jedisct1** [comment]
Oh, indeed!

Good catch!

This has been fixed, exactly as you suggested.

Thanks again!
