### ISSUE TITLE
Can't get time restrictions to work

### ISSUE THREAD

**Issue by ajp2k13** [DNSCrypt/dnscrypt-proxy#710]
I just setup dnscrypt-proxy 2.0.19 as a standalone dns proxy on a Pi and it's working great. I can't get time restrictions to work though, I have defined schedules in the .conf and set hostnames with schedule name in the domains-time-restricted.txt and generated the blacklist but it doesn't seem to be working.

What am I doing wrong? Any ideas?

**Comment by ajp2k13** [comment]
@jedisct1 any ideas? I can get time-restricted whitelisting to work but not blacklisting... I must be missing something. Not super important but it's a nice feature...

**Comment by jedisct1** [comment]
Can you upload a minimal set of configuration files that reproduces the issue?

**Comment by jedisct1** [comment]
Also, you didn't provide any information about your environment, but is the time correct in the log files? Just wondering if it couldn't be a time zone issue (which is apparently the case on Android and on some router Linux distros).

**Comment by ajp2k13** [comment]
Well I managed to get time restricted whitelist to work so it shouldn't be a time issue right? It's on a Raspberry Pi and the time is correct on the system but I must confess I didn't check time-stamps in the log. 
I define the schedules in dnscrypt-proxy.toml and then edit domains-blacklist-time-restricted.txt (for example I put *.youtube.* @time-to-sleep) and run the command to generate the blacklist-file but it's not added to the blacklist file (cat blacklist.txt | grep *.youtube.* doesn't find anything).

Which config files would you need?

**Comment by ajp2k13** [comment]
@jedisct1 I feel like I'm misunderstanding something. What is the correct procedure to use time-restricted blacklisting? What are the steps I have to take? I managed to get time-restricted whitelisting to work and I've checked the timestamps in the logs and they are correct...

**Comment by ajp2k13** [comment]
@jedisct1 I discovered that if I edit the blacklist file directly and enter for example "www.facebook.com @work" and restart dnscrypt-proxy, it works fine. However, if I edit the domains-time-restricted.txt and add "www.fackebook.com @work" and run the python script to generate a blacklist it doesn't work. It's like the python script doesn't add the ones with @schedule after them?

**Comment by jedisct1** [comment]
Time-restricted rules must be in a separate file. See the `-r` option of the Python script:

```
  -r TIME_RESTRICTED, --time-restricted TIME_RESTRICTED
                        file containing a set of names to be time restricted
```

**Comment by ajp2k13** [comment]
Thanks, I tried that once but I'll try it again! :)

When running the script it lists the file:domain-time-restricted.txt at the end so I thought it included it by default.

**Comment by ajp2k13** [comment]
@jedisct1 I tried again with the switch -r pointing to domains-time-restricted.txt which contains this:

*.twitter.com       @work
*.facebook.com      @work
*.youtube.com @time-to-sleep

The genereated blacklist.txt does not contain any references to to those domains and schedules though and I can still reach the domains.

**Comment by r2munz** [comment]
I have looked it up briefily and it looks like the parse_list() funct does not handle the '@' character for the time span definition. It returns an empty result instead. Tested with Python 2.7.
I am sure this is not the best solution at all but I have created a separate parse_list funct to handle the time based restriction. I have tested it and it works nicely.
```
def parse_list_tb(content, trusted=False):
        rx_comment = re.compile(r'^(#|$)')
        rx_inline_comment = re.compile(r'\s*#\s*[a-z0-9-].*$')
        rx_u = re.compile(r'^@*\|\|([a-z0-9.-]+[.][a-z]{2,})\^?(\$(popup|third-party))?$')
        rx_l = re.compile(r'^([a-z0-9.-]+[.][a-z]{2,})$')
        rx_h = re.compile(r'^[0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}\s+([a-z0-9.-]+[.][a-z]{2,})$')
        rx_mdl = re.compile(r'^"[^"]+","([a-z0-9.-]+[.][a-z]{2,})",')
        rx_b = re.compile(r'^([a-z0-9.-]+[.][a-z]{2,}),.+,[0-9: /-]+,')
        rx_dq = re.compile(r'^address=/([a-z0-9.-]+[.][a-z]{2,})/.')
        rx_tb = re.compile(r'^([*a-z0-9.-]+)(\s)+\@([a-z,A-Z])+$')
        rx_trusted = re.compile(r'^([*a-z0-9.-]+)$')

        names = set()
        rx_set = [rx_u, rx_l, rx_h, rx_mdl, rx_b, rx_dq, rx_tb]
        if trusted:
            rx_set = [rx_trusted]
        for line in content.splitlines():
            line = str.lower(str.strip(line))
            if rx_comment.match(line):
                continue
            line = rx_inline_comment.sub('', line)
            for rx in rx_set:
                matches = rx.match(line)
                if not matches:
                    continue
                name = matches.group()
                names.add(name)
        return names
```
