### ISSUE TITLE
Problem Changing 127.0.0.1:53 to 127.0.0.1:40

### ISSUE THREAD

**Issue by lenkarin** [DNSCrypt/dnscrypt-proxy#711]
I install the DNSCrypt to make my computer more secure, but , I use acrylic dns proxy and I wanted to use both together. And I see in Acrylic DNS Proxy page that I have to change the listen to a nonstandard port.

Here's the link for you guys see the FAQ, in Acrylic DNS Proxy page and understanding
https://mayakron.altervista.org/wikibase/show.php?id=AcrylicFAQ

In the moment I use 127.0.0.1:53 , I want change the DNSCrypt listen address to 127.0.0.1:40 or a nonstandard port to work together with Acrylic DNS Proxy, but I'm beginner on this and don't know how to this

**Comment by Yinchie** [comment]
Edit dnscrypt-proxy.toml and change the port.

**Comment by lenkarin** [comment]
How can I edit dnscrypt-proxy.toml , did you know the commands?

**Comment by r4sas** [comment]
Any text editor.

**Comment by lenkarin** [comment]
Thank you, I just change it . Can end the topic the admins. thank you the help guys

**Comment by uBlock-user** [comment]
> Edit dnscrypt-proxy.toml and change the port.

I did that, doesn't work on Windows 10, DNS is binded to port 53. You will have to tweak the registry.
