### ISSUE TITLE
DSA-4380-1 golang-1.8 -- security update

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#718]
https://www.debian.org/security/2019/dsa-4380

A vulnerability was discovered in the implementation of the P-521 and P-384 elliptic curves, which could result in denial of service and in some cases key recovery.

Might affect something? I don't know which ciphers DOH etc may use.

**Edit:**
If none of these are used forgive me. I only know HTTPS / TLS make use of them, so I wasn't sure if DNS over HTTPS may require them. In your code I could only spot the Curve25519.

**Comment by jedisct1** [comment]
The official binaries are built using Go 1.12.

But even if you compiled it yourself with an older Go version, these curves are not used by any DoH resolver.
