### ISSUE TITLE
fvz-anyone and fvz-anytwo TIMEOUT error

### ISSUE THREAD

**Issue by ankar84** [DNSCrypt/dnscrypt-proxy#72]
Hello!
I think, that **fvz-anyon**e and **fvz-anytwo** OpenNIC resolvers now getting TIMEOUT error because confugured to **default 443** port, but currently running at **5353 port**.
I`m using your dnscrypt-proxy v 1.9.5 on my Keenetic Ultra router and port 5353 works great on that resolvers.
Version 2.0.0beta12, that I try to run on router gets TIMEOUT error on that resolvers and I cannot do anything to fix it, because now it is in stamp format.
Please, try to change port to **5353** and if it works for you too, change stamps in resolver files:
https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md
https://download.dnscrypt.info/resolvers-list/v2/opennic.md
PS. I prefer OpenNIC resolvers bacause they resolve ".lib" domains (very useful in Russia)
Thanks for your really great job!

**Comment by iWARR** [comment]
[off-topic]

**Comment by jedisct1** [comment]
Hi Ankar,

And thanks for reporting this!

I'm going update the port right away.

https://stamps.dnscrypt.info/ can be used to quickly view/create/update stamps.

**Comment by jedisct1** [comment]
Updated, thanks!
