### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by opav** [DNSCrypt/dnscrypt-proxy#720]
This is so frustrating, that I have resorted to fixing it by removing the entire [sources] section and move to using static servers.

Otherwise it will continuously keep spamming with updates every minute.  Changing 'refresh_delay'  setting does not work.

`Feb  6 14:12:43 dnscrypt-proxy[17859]: Loading source information from URL  https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md]
Feb  6 14:12:43 dnscrypt-proxy[17859]: Loading source information from URL [https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md.minisig]
Feb  6 14:13:43 dnscrypt-proxy[17859]: Loading source information from URL [https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md]
Feb  6 14:13:43 dnscrypt-proxy[17859]: Loading source information from URL [https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md.minisig]`

**Comment by jedisct1** [comment]
You didn't provide any information about the environment, so this is going to be a shot in the dark.

Are the cache files being written? Are the time stamps correct?

**Comment by opav** [comment]
Sorry, the environment is a router installed with pre-built mipsle binary, tested version 2.0.17 & 2.0.19.  

If I deleted the public-resolvers.md & public-resolvers.md.minisig, and restart, it will fail to download with these log entries:

```
Feb  8 13:47:36 dnscrypt-proxy[10840]: Loading source information from URL [https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md]
Feb  8 13:47:36 dnscrypt-proxy[10840]: Loading source information from URL [https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md.minisig]
Feb  8 13:47:36 dnscrypt-proxy[10840]: Loading from [https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md] failed
Feb  8 13:47:36 dnscrypt-proxy[10840]: Loading source information from URL [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md]
Feb  8 13:47:38 dnscrypt-proxy[10840]: Loading source information from URL [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md.minisig]
Feb  8 13:47:38 dnscrypt-proxy[10840]: Loading from [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] failed
Feb  8 13:47:38 dnscrypt-proxy[10840]: Unable to use source [public-resolvers]: [Get https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md: x509: certificate signed by unknown authority

```
If I manually wget these 2 files, then it will work as expected until sometime later when they expired.

If I change the sources url from **https** to **http**, it will work as expected but not safe.

So it looks like a https issue, but I don't know why wget can download same https links.

**Comment by jedisct1** [comment]
This is due to a missing or outdated `ca-certificates` package (or whatever it is for the Linux distribution you didn't mention).

**Comment by opav** [comment]
Thanks, installing ca-certificates fixed it.  I already have ca-bundle installed and thought that one was enough, didn't know ca-certificates is needed too.
