### ISSUE TITLE
nsswitch.conf recommendations

### ISSUE THREAD

**Issue by scotte** [DNSCrypt/dnscrypt-proxy#721]
Are there an recommendations for settings the hosts entry in nsswitch.conf to work best with dnscrypt-proxy? If so, is it worth documenting? Thanks!

**Comment by jedisct1** [comment]
To possibly avoid some DNS leaks, you may want to move `resolve [!UNAVAIL=return]` to the end.

But things like Docker may not like a `nsswitch.conf` file that's not the default one. So, if you notice anything weird, go back to the default configuration.
