### ISSUE TITLE
Play商店打不开

### ISSUE THREAD

**Issue by gwc12412** [DNSCrypt/dnscrypt-proxy#725]
不管在哪种模式，使用此模块会导致Play商店打不开。

**Comment by r4sas** [comment]
Huh, I haven't any problems with Google Play when use dnscrypt. Maybe Google services has different IP addresses in your country, about which other root DNS servers doesn't know?

Try find which domains requested by Play Store and compare their IP addresses between resolved by dnscrypt-proxy and your ISP DNS server.

**Comment by gwc12412** [comment]
网络没问题，YouTube正常使用，用的VPN不是其它代理。取消模块后就能正常打开Google Play。

R4SAS <notifications@github.com> 于 2019年2月12日周二 05:10写道：

**Comment by rampageX** [comment]
什么手机？如果是华为，我记得要：

#HuaWei Google Play
server=/services.googleapis.cn/127.0.0.1#5353

cn 域名通常会被指向国内 DNS ，但是这个域名用国内 DNS 就不行。

**Comment by gwc12412** [comment]
Pixel 2 XL

rampageX <notifications@github.com> 于 2019年2月17日周日 10:32写道：

**Comment by jhouzvicka** [comment]
The same issue here on Android 8.0 (Samsung Galaxy S7) and 8.1 (Samsung J7 2016) devices after updating to version 2.0.21.
And I can't attach any files to Viber messages.
Reverting back to version 2.0.19 solves these issues on both of my Android devices.

**Comment by jedisct1** [comment]
Try version 2.0.22.
