### ISSUE TITLE
dnscrypt_servers = false disables proxy and tcp only?

### ISSUE THREAD

**Issue by J0s3f** [DNSCrypt/dnscrypt-proxy#726]
I want to route all DNS querys over TOR on my router with custom [padavan-ng](https://github.com/Linaro1985/padavan-ng) firmware and [entware](https://github.com/Entware/Entware).

I created the following config:

```
listen_addresses = ['127.0.0.1:5354']
max_clients = 250
user_name = 'dnscrypt'
ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
force_tcp = true
proxy = "socks5://127.0.0.1:9050"
timeout = 3500
keepalive = 120
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false
fallback_resolver = '1.1.1.1:53'
ignore_system_dns = true
netprobe_timeout = 80
```

I started it and all seemed to work. But the RTT times where way too fast for TOR.
So i changed the Socks Proxy to a wrong port to test: `proxy = "socks5://127.0.0.1:9051"`

It was still working, so clearly **TOR is not used!!!**

> [2019-02-13 14:11:47] [NOTICE] Source [public-resolvers.md] loaded
> [2019-02-13 14:11:47] [NOTICE] dnscrypt-proxy 2.0.19
> [2019-02-13 14:11:47] [NOTICE] Dropping privileges
> [2019-02-13 14:11:47] [NOTICE] Source [public-resolvers.md] loaded
> [2019-02-13 14:11:47] [NOTICE] dnscrypt-proxy 2.0.19
> [2019-02-13 14:11:47] [NOTICE] Now listening to 127.0.0.1:5354 [UDP]
> [2019-02-13 14:11:47] [NOTICE] Now listening to 127.0.0.1:5354 [TCP]
> [2019-02-13 14:11:48] [NOTICE] [bottlepost-dns-nl] OK (crypto v2) - rtt: 36ms
> ...
> [2019-02-13 14:11:55] [NOTICE] Server with the lowest initial latency: dnscrypt.me (rtt: 30ms)
> [2019-02-13 14:11:55] [NOTICE] dnscrypt-proxy is ready - live servers: 32

By trial and error I found out, it works if I **disable DNSCrypt**:  `dnscrypt_servers= false`

> [2019-02-13 14:14:32] [NOTICE] Source [public-resolvers.md] loaded
> [2019-02-13 14:14:32] [NOTICE] dnscrypt-proxy 2.0.19
> [2019-02-13 14:14:32] [NOTICE] Dropping privileges
> [2019-02-13 14:14:32] [NOTICE] Source [public-resolvers.md] loaded
> [2019-02-13 14:14:32] [NOTICE] dnscrypt-proxy 2.0.19
> [2019-02-13 14:14:32] [NOTICE] Now listening to 127.0.0.1:5354 [UDP]
> [2019-02-13 14:14:32] [NOTICE] Now listening to 127.0.0.1:5354 [TCP]
> [2019-02-13 14:14:32] [ERROR] Get https://doh.securedns.eu/dns-query?ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA: socks connect tcp: dial tcp 127.0.0.1:9051: connect: connection refused
> [2019-02-13 14:14:32] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable

If I then correct the TOR port again, it works with believable RTT.

> [2019-02-13 14:15:17] [NOTICE] Source [public-resolvers.md] loaded
> [2019-02-13 14:15:18] [NOTICE] dnscrypt-proxy 2.0.19
> [2019-02-13 14:15:18] [NOTICE] Dropping privileges
> [2019-02-13 14:15:18] [NOTICE] Source [public-resolvers.md] loaded
> [2019-02-13 14:15:18] [NOTICE] dnscrypt-proxy 2.0.19
> [2019-02-13 14:15:18] [NOTICE] Now listening to 127.0.0.1:5354 [UDP]
> [2019-02-13 14:15:18] [NOTICE] Now listening to 127.0.0.1:5354 [TCP]
> [2019-02-13 14:15:28] [NOTICE] [cloudflare] OK (DoH) - rtt: 179ms
> [2019-02-13 14:15:29] [NOTICE] [cloudflare-ipv6] OK (DoH) - rtt: 419ms
> [2019-02-13 14:15:38] [NOTICE] [doh-ibksturm] OK (DoH) - rtt: 224ms
> [2019-02-13 14:15:39] [NOTICE] [powerdns-doh] OK (DoH) - rtt: 292ms
> [2019-02-13 14:15:43] [NOTICE] [publicarray-au-doh] OK (DoH) - rtt: 640ms
> [2019-02-13 14:15:44] [NOTICE] [securedns-doh] OK (DoH) - rtt: 687ms
> [2019-02-13 14:15:44] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 179ms)
> [2019-02-13 14:15:44] [NOTICE] dnscrypt-proxy is ready - live servers: 6

I don't know if this is intended, but it is clearly not what I expected.
If I set a socks proxy, **it should be used for all connections!**

**Comment by jedisct1** [comment]
Start with the default configuration.

The only thing you need to change is `force_tcp = false` to `force_tcp = true`. You don't need to disable DNSCrypt.

The RTTs you are seeing are for certificates retrieval, not for DNS queries. Actual RTTs are dynamically updated as you use the service.
