### ISSUE TITLE
Issues with SELinux on Fedora 29.

### ISSUE THREAD

**Issue by cedws** [DNSCrypt/dnscrypt-proxy#727]
Similar to #567, #437.

The dnscrypt-proxy package for Fedora 29 currently does not work out of the box due to SELinux. I found that another user that posted a command that fixes it:

```
sudo ausearch -c '(pt-proxy)' --raw | audit2allow -M my-ptproxy
```

@eclipseo
Do you still maintain this package? Can we look at perhaps getting a fix so users don't need to worry about running this?

**Comment by eclipseo** [comment]
Yes I maintain it. I have reported the SELinux issue upstream: https://github.com/fedora-selinux/selinux-policy/issues/231 but no action has been taken yet.
I'll push an update with a workaround for now.
