### ISSUE TITLE
generate-domains-blacklist.py results not as expected

### ISSUE THREAD

**Issue by no-replies** [DNSCrypt/dnscrypt-proxy#728]
There are some odd things happening here. The merge and clean up seems to completely remove some domains rather than just leaving one, it will still add subdomains when root is already blocked, and most oddly added "com" "im" and "co" as domains (that really confused me for a while as everything was blocked)

I aslo don't see a script to combine IP-blocklist. Given neither CIDR or IP Ranges are supported it would be useful? Or am I missing something ??

**Comment by jedisct1** [comment]
Can you provide a minimal, reliable way to reproduce the issue you are experiencing, and explain what output you were expecting?

**Comment by no-replies** [comment]
I will try to. Reviewing the script atm to try to figure out what it's doing.

I did a combine from external sources and a local-additions file. Many of the domains in local-additions disappeared. 

It also appeared to rewrite some which became :
com
im
co

(without a  . or *)

In meantime can you advise on the IP-blocklist question?

**Comment by jedisct1** [comment]
The script doesn't handle IP addresses yet.

**Comment by no-replies** [comment]
I will see if I can figure out what’s wrong and also consider adding ip-blacklist. CIDR or IP Ranges Would be easier; are they on the roadmap?

**Comment by jedisct1** [comment]
Not really, but if you can implement these your contribution would be more than welcome.
