### ISSUE TITLE
Failure to read symlinked dnscypt-proxy.toml.

### ISSUE THREAD

**Issue by cedws** [DNSCrypt/dnscrypt-proxy#729]
I'm trying to manage my `dnscrypt-proxy.toml` with GNU Stow (which will create a symlink to the real config file).

A `permission denied` error is thrown:

```
Feb 16 18:20:29 ce systemd[1]: Started DNSCrypt-proxy client.
Feb 16 18:20:29 ce dnscrypt-proxy[2891]: [2019-02-16 18:20:29] [FATAL] open /etc/dnscrypt-proxy/dnscrypt-proxy.toml: permission denied
Feb 16 18:20:29 ce systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
Feb 16 18:20:29 ce systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
```

These are the file permissions:

```
lrwxrwxrwx. 1 root root 76 Feb 16 18:19 /etc/dnscrypt-proxy/dnscrypt-proxy.toml -> ../../OMITTED
```

I'm managing config files for another application in this manner and it works for that one, so I'm not sure what's going wrong here.

**Comment by jedisct1** [comment]
`Permission denied` means that the file (the actual file, not the symlink) is not readable by the user the service was started with.

**Comment by cedws** [comment]
I think the dnscrypt-proxy service runs as a system service. Even if it were running under my user, the file being symlinked to is in my home directory, so it should be readable.

Permissions of the actual file:
```
16 -rw-rw-r--. 1 cedwards cedwards 14975 Feb 16 19:00 dnscrypt-proxy.toml
```

**Comment by jedisct1** [comment]
Can you start the service from the command line, as root, without using systemd?

**Comment by cedws** [comment]
When I start the program as root, there's no output for some reason (I checked the logging options in the config, syslog is off). If I start it under my own user, everything seems normal and it loads the config file, but I can't resolve DNS queries.

It only seems to be failing to open the config file when ran through systemd.

**Comment by cedws** [comment]
I tested linking the `dnscrypt-proxy.toml` to another path in /etc and the service works. ~~I don't understand why it isn't able to follow the symlink to my home directory.~~

Found why. It's because of `ProtectHome=yes` in the `dnscrypt-proxy.service`. Can we remove this safely?

**Comment by jedisct1** [comment]
Yes, remove it, it's useless.

**Comment by cedws** [comment]
I don't see `dnscrypt-proxy.service` in the repo, has this file been created by the package maintainer? If so then I'll probably need to get in contact with them to remove this.

**Comment by jedisct1** [comment]
The built-in installer installs a systemd service on Linux, but it doesn't have `ProtectHome=yes`, so I guess that one was indeed installed by a package.

**Comment by cedws** [comment]
Alright, thanks. I'm going to try to get to the bottom of this packaging stuff in the next few days because the dnscrypt-proxy Fedora package is really not being done properly.

**Comment by jedisct1** [comment]
It's okay to add a clause to only accept the configuration file in a specific directory if the configuration file is always in that directory. But yeah, people are different requirements, and packages probably shouldn't do such assertions.

**Comment by cedws** [comment]
I've sent an email to the package maintainer so hopefully we can work on fixing this issue and #727.

**Comment by eclipseo** [comment]
I have removed ```ProtectHome``` for your use case. It will be in the next update if everything goes as planned.
