### ISSUE TITLE
Use my servers on Android Pie

### ISSUE THREAD

**Issue by ooonea** [DNSCrypt/dnscrypt-proxy#734]
Hello, I have a mobile phone with Android Pie and I would like to follow your guide to use my servers with TLS ( https://github.com/jedisct1/dnscrypt-proxy/wiki/Connecting-to-a-remote-dnscrypt-proxy -client-from-Android-Pie-using-DNS-over-TLS ). But I do not know how to do it. I have a sever on Scaleway and the other on Vultr. Do I have to install nginx on both servers and then insert the guide strings to the nginx.conf file? Please enlighten me!

**Comment by jedisct1** [comment]
This is indeed a good way to achieve it: add software doing TLS termination on top of a running dnscrypt-proxy, on the servers you want to connect to that way. It doesn't have to be Nginx.

The guide is a little bit incomplete, though, as it assumes that you already know how to set up Nginx servers with TLS certificates. Even with Letsencrypt, this requires more than the few lines in the nginx configuration.

I'll try to complete the guide, but unfortunately I don't have any device running Android to test.

**Comment by ooonea** [comment]
For any proof I will help you as I can. Unfortunately I do not have the economic possibility to provide you with a device with Android Pie.

**Comment by ooonea** [comment]
At the moment I have solved the problem by installing on my Samsung S9 the latest official version of LineageOS (15.1 - 2019.03.03 nightly) with Magisk and the excellent form of DNSCrypt-proxy https://github.com/Magisk-Modules-Repo/dnscrypt-proxy. Unfortunately it is not applicable to all devices and not everyone is willing to modify their terminal. I hope you can complete your guide. For me it can be closed here.

**Comment by chew-z** [comment]
Hi @lucenera 

Installing and fine tuning nginx is too large a subject in itself but fortunately there is a lot of material on the web. There is also nothing magical about getting Letsencrypt SSL certificate. 

You can [find my gist](https://gist.github.com/chew-z/533e112b298507bacac6af14bfeb2f53) with basic, trimmed down configuration of my own nginx server and also links to some resources that should make installing nginx and adding DNS-over-TLS and DNS-over-HTTP relatively easy.

Good luck

**Comment by ooonea** [comment]
Thank you. I will treasure the information you gave me.

**Comment by jedisct1** [comment]
Hi @lucenera,

Can you check the state of `charis`? Looks like it's not responsive any more at the moment. Thanks!
