### ISSUE TITLE
[CLOSED]issue

### ISSUE THREAD

**Issue by absynteZero** [DNSCrypt/dnscrypt-proxy#736]
Hi,

I use Windows 10 Pro x64.

I use dnscrypt proxy from month and i have two issues.

First with openvpn the vpn disconnect itself, using dnscrypt proxy.

Second, when i use openvpn connected to a vpn service, after some hours and not always, openvpn is disconnected but unable to reconnect because of the app couldn't determine if ipv4 or ipv6.

I 've this issue with all vpn running on openvpn.

Netprobe timeout is disable (0)

i use random selection on dnscrypt v2 servers

It seems openvpn is'nt able to send dns query for vpn connection, only after hours.

Sorry for my poor English language...

Tap are ok and i've already try to delete them and renew all...

I don't know how to fix the issue.

The issue comes with dnscrypt proxy installation.

And i use a very good internet connection, my vpn never disconnect itself without dnscrypt proxy.

Regards

EDIT 02-24: I just update to NEW openvpn release.
I've renew all tap configuration.
I've try with and without cache, issue still persist.
I've verify power economy fonction.
...

Issue is about two or three times a week.

I don't know if it's my ISP but my modem is always ok and my connection failed only during maintenance three or four time a year.

EDIT: After a 72h run same node, same vpn connection, i haven't any issue with the new openvpn version 2.4.7.

It re- connects without any issue in case of disconnection.

There is no issue when using openvpn and dnscrypt proxy.

**Comment by absynteZero** [comment]
Last edit: Issue still persist arggg.

I don't know what happened.
![capture](https://user-images.githubusercontent.com/18337243/53689933-edf63080-3d60-11e9-8a3a-e39f2c409719.PNG)

**Comment by Yinchie** [comment]
This isn't a DNSCrypt issue. Why not ask at openvpn?
https://www.google.com/search?q=openvpn+could+not+determine+protocol&oq=openvpn+could+not+determine+protocol

http://www.catb.org/esr/faqs/smart-questions.html

**Comment by jedisct1** [comment]
You're indeed more likely to receive help from OpenVPN communities.

I don't use OpenVPN.

**Comment by absynteZero** [comment]
Hi,

Thanks.

I was thinking the issue comes with dnscrypt because it has started with dnscrypt installation,

BUT,

I just remember i have started to use multi Tap and dev-node option with openvpn.

So it's not a dnscrypt issue.

I've no issue using dnscrypt and openvpn.

@jedisct1 How can you use vpn? and other client or app?
