### ISSUE TITLE
Blacklist feature breaks DNS resolution on Android 8+

### ISSUE THREAD

**Issue by notr1ch** [DNSCrypt/dnscrypt-proxy#737]
I'm running dnscrypt-proxy on my router and it handles DNS resolution and increases privacy via the blacklist feature for my whole network.

I recently upgraded one of my devices to Android 8, and seemingly randomly I would lose all DNS resolution - sniffing the network showed queries weren't even making it to the resolver. After much debugging, it turns out that Android 8+ tracks the results of recent DNS queries, and if too many of them fail, it marks the DNS server as unavailable. "Fails" in this context include status code REFUSED, which is returned by DNS queries that match the blacklist. So every time I loaded a page with too many ads / trackers, dnscrypt-proxy would respond with a whole bunch of REFUSED answers and then Android would mark the DNS server as down.

A solution would be to send an empty answer or NXDOMAIN instead of REFUSED (or at least make it configurable).

References:
https://github.com/aosp-mirror/platform_bionic/blob/92c6f7ee9014f434fbcce89ab894c745e36732d2/libc/dns/resolv/res_stats.c#L68-L97

https://github.com/jedisct1/dnscrypt-proxy/blob/97f604670c6fa249107810c05c8bc115fe26cd5e/dnscrypt-proxy/plugins.go#L172-L178

https://github.com/jedisct1/dnscrypt-proxy/blob/cc327fdc480eb77c662b662b730fe66ee05047a5/dnscrypt-proxy/dnsutils.go#L34-L41

**Comment by jedisct1** [comment]
Thanks for your report!

A new option has been added to control this.

Returning `NXDOMAIN` would probably be a bad idea. We may want to block `example.com` but not `a.example.com`, and a caching resolver can infer than `*.example.com` doesn't exist from a `NXDOMAIN` response code on `example.com`.

Returning a successful, empty response is a lie, and DNSSEC-validating caches may not like it.

But I guess that's the only option :/

**Comment by notr1ch** [comment]
Thanks for the quick fix, it's working great!
