### ISSUE TITLE
Add refused_code_in_responses to example-dnscrypt-proxy.toml

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#738]
Hi, just noticed the newly added boolean `refused_code_in_responses` from https://github.com/jedisct1/dnscrypt-proxy/commit/a726a40dc552bae23f545e73f5d42fab3ea1af68. Would it be possible to provide info on where to put this in a dnscrypt-proxy.toml and with which wording/syntax? I can deduce from the commit the value is set to false by default, but was wondering if this could be properly documented, e.g. in the repo's [example-dnscrypt-proxy.toml](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml) file.

Regards

**Comment by jedisct1** [comment]
Sending a pull request would have been faster.

**Comment by ghost** [comment]
I wasn't sure on the wording, otherwise I'd made a PR. Thanks for taking care of this.
