### ISSUE TITLE
[Project?] Interactive dnscrypt servers world map

### ISSUE THREAD

**Issue by absynteZero** [DNSCrypt/dnscrypt-proxy#741]
Hi,

I think about a world card with all dnscrypt servers, an open data map.

I don't know how to do, or where to suggest it...

It will be very nice for the user knows what are the servers he can needs and where they are.

A map where each servers give their ip, port, stamp, servers etc....

Regards

Thanks

**Comment by jedisct1** [comment]
https://dnscrypt.info/map
