### ISSUE TITLE
domains-blacklist-all.conf correct url

### ISSUE THREAD

**Issue by pashamcr** [DNSCrypt/dnscrypt-proxy#743]
Quidsup NoTrack
https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt -->> 404: Not Found
https://github.com/quidsup/notrack -->> New URLs are:

NoTrack-Blocklist: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
NoTrack-Malware: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt

**Comment by jedisct1** [comment]
Thank you!
