### ISSUE TITLE
What's the correct binary file for Youku YK1 running OpenWrt 18.06?

### ISSUE THREAD

**Issue by hillz2** [DNSCrypt/dnscrypt-proxy#744]
I have Youku YK1 with MediaTek MT7620A running OpenWrt 18.06.2 I have tried to download

1. dnscrypt-proxy-linux_arm64-2.0.19.tar.gz
2. dnscrypt-proxy-linux_mips64-2.0.19.tar.gz
3. dnscrypt-proxy-linux_arm-2.0.19.tar.gz

They all don't work on my router, when I try to run `dnscrypt-proxy` it always says `line 1: syntax error: unexpected "("`

Which binary file is suitable for my router ?

**Comment by r4sas** [comment]
You must build binary yourself with specific toolchain, because standart linux ABI is not comptible with your device ABI.

**Comment by jedisct1** [comment]
The [OpenWRT page for this device](https://openwrt.org/toh/hwdata/youku/youku_yk1) appears to say that it's `mipsle`.
