### ISSUE TITLE
How to determine the real TLS version & Cipher 

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#746]
I am reading "[cloudflare] TLS version: 304 - Protocol: h2 - Cipher suite: 4867" 

These are non standard numbers. What TLS version is this really, and what Cipher suite is this really? Why only 4 characters, when the .toml has 5 figure character suites and 4867 is not listed? 

Thank you.

**Comment by ghost** [comment]
My brain would interpret 4867 as decimal. I guess it is hex 0x1303 since they are the same number.
aka TLS_CHACHA20_POLY1305_SHA256 if I look up in my docs of TLS

**Comment by jedisct1** [comment]
Yes, this is the identifier as defined in the protocol.
