### ISSUE TITLE
Feature Request: Tunnel DNS requests through SOCKS5 proxy when using it

### ISSUE THREAD

**Issue by phantomcraft** [DNSCrypt/dnscrypt-proxy#750]
When I start using dnscrypt-proxy by the first time with Tor (Socks5 port 9050) and choose to use a DNS server to help downloading the servers list, the DNS request use the local UDP connection instead of tunneling them through SOCKS5 tunnel.

This feature would be useful if the system is firewalled and hasn't UDP connectivity or port 53 is blocked by ISP.

**Comment by jedisct1** [comment]
It uses the normal system DNS settings since there is nothing confidential here.
