### ISSUE TITLE
doh.seby.io DNS request every 4 hours. Why?

### ISSUE THREAD

**Issue by EauBureau** [DNSCrypt/dnscrypt-proxy#751]
Sorry if this is a dumb question.
I can see in my DNS log that `doh.seby.io` is requested every 4 hours continuously.
Why?

**Comment by Yinchie** [comment]
Because it is being requested every 4 hours by something that requests it every 4 hours.
https://dns.seby.io/

**Comment by jedisct1** [comment]
The `dnscrypt-proxy.toml` configuration file includes this setting:

```toml
## Delay, in minutes, after which certificates are reloaded
cert_refresh_delay = 240
```

By default, every 4 hours, a quick check is made in case a resolver's certificate needs an update.

For DoH servers, this can also be useful to update the IP address, in case it changed.

**Comment by EauBureau** [comment]
> The `dnscrypt-proxy.toml` configuration file includes this setting:
> 
> ```toml
> ## Delay, in minutes, after which certificates are reloaded
> cert_refresh_delay = 240
> ```
> 
> By default, every 4 hours, a quick check is made in case a resolver's certificate needs an update.
> 
> For DoH servers, this can also be useful to update the IP address, in case it changed.

Perfect. Thank you. I was worried something was wrong with my setup.
