### ISSUE TITLE
(FreeBSD) Where dnscrypt-proxy after INSTALL stored dnscrypt-proxy.service file on FreeBSD?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#752]
Hi!

Where dnscrypt-proxy after INSTALL stored dnscrypt-proxy.service file?

I can't find it in /etc/rc.d

**Comment by jedisct1** [comment]
`dnscrypt-proxy.service` is a Linux/SystemD thing.

I don't think FreeBSD has been contaminated by SystemD yet.
