### ISSUE TITLE
[FATAL] Built-in service installation is not supported on this platform  (on BSD)

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#753]
Hi!

I installed the freebsd package  'dnscrypt-proxy' on terminal via

sudo ./dnscrypt-proxy -service install
sudo ./dnscrypt-proxy -service start

Log_Output says:
[FATAL] Built-in service installation is not supported on this platform

What can I do to fix that?

**Comment by jedisct1** [comment]
In order to fix that, you need to contribute FreeBSD support to this package: https://github.com/kardianos/service
