### ISSUE TITLE
Not working on Linksys RE6500-HG

### ISSUE THREAD

**Issue by mrsnax** [DNSCrypt/dnscrypt-proxy#755]
Hi,

I tried to install dnscrypt-proxy v 2 with mimps. As my router version is : 

`Linux openwrt 4.4.153 #0 SMP Thu Aug 30 12:10:54 2018 mips GNU/Linux`

After `upx --lzma dnscrypt-proxy` and upload to SCP then try to run a command line, the error show like this: 

`/usr/sbin/dnscrypt-proxy: line 1: syntax error: unexpected "("`

If I tried to change Mipsle version, the error show like this: 

`Bus Error`

Its dnscrypt-proxy version 2.0 support my router?

Thank you

**Comment by jedisct1** [comment]
According to the OpenWRT page, `mipsle` should be the correct architecture.

Can you try without UPX?

**Comment by mrsnax** [comment]
If I tied without UPX, the file size is not enuogh space. Its required 9 MB, but on my router space available only 3 MB

**Comment by mrsnax** [comment]
Hi 

After many tries with mipsle, now dnscrypt-proxy version 2 are working...

Thank you @jedisct1
