### ISSUE TITLE
[FATAL] Near line 31 (last key parsed 'server_names'): expected a comma or array terminator ']', but got 'c' instead

### ISSUE THREAD

**Issue by DjCrays** [DNSCrypt/dnscrypt-proxy#757]
Hey, 

ive started to add more DNSCrypt-Servers into my DNSCrypt-Proxy 2 Config on my Rasbi3B+. 

Now when i want to check my config with ./dnscrypt-proxy -check i get this error message:

`
root@raspberrypi:/opt/dnscrypt-proxy# ./dnscrypt-proxy -check
[2019-03-13 18:25:37] [FATAL] Near line 30 (last key parsed 'server_names'): expected a comma or array terminator ']', but got 'c' instead
`

But my Config on line 30 looks like this: ` server_names = ['bottlepost-dns-nl', 'cloudflare', 'cloudflare-ipv6', 'cs-caeast', 'cs-cawest', 'cs-de', 'cs-de3', 'cs-dk2', 'cs-fi', 'cs-fr2', 'cs-lv', 'cs-pl', 'cs-pt', 'cs-ro', 'cs-rome', 'cs-useast2', 'cs-usnorth', 'cs-uswest, 'cs-uswest3', 'dnscrypt.me', 'ipredator', 'securedns', 'securedns-ipv6']
`

Also im running the newest version (2.0.19) on my RasPi3B+ running (lsb_release -a Distributor ID: Raspbian Description:    Raspbian GNU/Linux 9.8 (stretch) Release:        9.8 Codename:       stretch ). Could someone look over my Config and tell me if this is just a Erorr in my Config or is it an Bug?

Greets,
Erwin.

**Comment by jedisct1** [comment]
There is a syntax error in your configuration file, maybe in the lines before that one, or the line just after it.

**Comment by DjCrays** [comment]
https://paste.d-ku.de/?140bb9787effe86c#6ay7pbj26dTxKtF6jrm7SXmWwmxJskW5BAq4NNAHsrg= Well.. there is my full config.. i dont think that there is something wrrong with it...

**Comment by davidkna** [comment]
`'cs-uswest` should be `'cs-uswest'`

**Comment by DjCrays** [comment]
Works now... Just overseen this. :D Thank you. ^^
