### ISSUE TITLE
[FIXED] 2.0.20 binaries

### ISSUE THREAD

**Issue by sergeevabc** [DNSCrypt/dnscrypt-proxy#758]
Dear Frank,
Tag 2.0.20 mentions source code only, no binaries are attached.
Could you be so kind to fix it or at least explain why binaries are missing?

**Comment by sergeevabc** [comment]
Binaries are attached now, thank you.

**Comment by jedisct1** [comment]
When a new release is tagged, new binaries are automatically built. But it takes a couple minutes to have them built and uploaded for all architectures.
