### ISSUE TITLE
Can't start DNSCrypt over OpenWRT

### ISSUE THREAD

**Issue by vanyaindigo** [DNSCrypt/dnscrypt-proxy#759]
While trying to enable and start the service I've got an error
`root@OpenWrt:~# /etc/init.d/dnscrypt-proxy enable
': No such file or directory.common`
I think the issue in start script:

```
 #!/bin/sh /etc/rc.common

USE_PROCD=1
 
 # starts before dnsmasq starts
 START=18
 # stops before networking stops
 STOP=89
 
 PROG=/usr/sbin/dnscrypt-proxy
 CONFIGFILE=/etc/config/dnscrypt-proxy.toml
 
 start_service() {
         procd_open_instance
         procd_set_param command "$PROG" -config "$CONFIGFILE"
         procd_set_param file "$CONFIGFILE"
         procd_set_param respawn
         procd_close_instance
 }
```

What do I do wrong?

**Comment by jedisct1** [comment]
Where does this start script come from?

**Comment by jedisct1** [comment]
Answering my own question, it looks like is it that one:

https://raw.githubusercontent.com/etam/DNS-over-HTTPS-for-OpenWRT/master/dnscrypt-proxy

Maybe the file you made has Windows-style line terminators?

Try downloading it directly from the link above.

**Comment by jedisct1** [comment]
Do you have an `/etc/rc.common` file on your system?

**Comment by vanyaindigo** [comment]
Yes, I do, I downloaded it. What encoding does it have? ANSI or UTF-8?

**Comment by jedisct1** [comment]
There wouldn't be any difference between ANSI and UTF-8 for that file. But the end of the lines must be Unix style.

**Comment by vanyaindigo** [comment]
And how to check it?

**Comment by jedisct1** [comment]
It depends on your text editor.

But if you download it from the link above, it should be fine.

**Comment by vanyaindigo** [comment]
Ok, I'll try, any other file must be converted dos2unix? To edit I use Notepad+++

**Comment by vanyaindigo** [comment]
One more question is how to correctly write the blacklist file obtained from Adblock to the/tmp directory?
`blacklist_file = 'domains:/tmp/adb_list.overall'` is this correct?

**Comment by jedisct1** [comment]
```toml
blacklist_file = '/tmp/adb_list.overall`
```

**Comment by vanyaindigo** [comment]
Thanks a lot for your help

**Comment by vanyaindigo** [comment]
It finally started but Luci becomes very slooowly, very lazy. How can I speed it up?

**Comment by jedisct1** [comment]
Maybe you're running out of memory.

**Comment by vanyaindigo** [comment]
Nope, I've got 512 Mb RAM
