### ISSUE TITLE
crypto/rand: blocked for 60 seconds waiting to read random data from the kernel

### ISSUE THREAD

**Issue by poentodewo** [DNSCrypt/dnscrypt-proxy#760]
dnscrypt-proxy need -+3 minute to working if system get reboot or shutdown 
I was try to edit netprobe but nothing happen

> dnscrypt-proxy[332]: [2019-03-14 20:07:42] [NOTICE] dnscrypt-proxy 2.0.20
dnscrypt-proxy[332]: [2019-03-14 20:07:42] [NOTICE] Loading the set of cloaking rules from [cloaking-rules.txt]
dnscrypt-proxy[332]: [2019-03-14 20:07:42] [NOTICE] Loading the set of forwarding rules from [forwarding-rules.txt]
dnscrypt-proxy[332]: [2019-03-14 20:07:42] [NOTICE] Loading the set of IP blocking rules from [dnscrypt-blacklist-ip.txt]
dnscrypt-proxy[332]: [2019-03-14 20:07:42] [NOTICE] Now listening to 127.0.2.1:54 [UDP]
dnscrypt-proxy[332]: [2019-03-14 20:07:42] [NOTICE] Now listening to 127.0.2.1:54 [TCP]
dnscrypt-proxy[332]: [2019-03-14 20:07:42] [NOTICE] Now listening to [::1]:54 [UDP]
dnscrypt-proxy[332]: [2019-03-14 20:07:42] [NOTICE] Now listening to [::1]:54 [TCP]
dnscrypt-proxy[332]: crypto/rand: blocked for 60 seconds waiting to read random data from the kernel
dnscrypt-proxy[332]: [2019-03-14 20:09:55] [NOTICE] [sg-melek] OK (crypto v2) - rtt: 26ms
dnscrypt-proxy[332]: [2019-03-14 20:09:55] [NOTICE] Server with the lowest initial latency: sg-melek (rtt: 26ms)
dnscrypt-proxy[332]: [2019-03-14 20:09:55] [NOTICE] dnscrypt-proxy is ready - live servers: 1

**Comment by jedisct1** [comment]
```
dnscrypt-proxy[332]: crypto/rand: blocked for 60 seconds waiting to read random data from the kernel
```

Your system doesn't have enough entropy to securely generate random numbers.

Install `rng-tools`, `haveged` or `jitterentropy`.

**Comment by poentodewo** [comment]
Thank You fix after install rng-tools

> dnscrypt-proxy[351]: [2019-03-14 20:59:16] [NOTICE] Now listening to 127.0.2.1:54 [UDP]
 dnscrypt-proxy[351]: [2019-03-14 20:59:16] [NOTICE] Now listening to 127.0.2.1:54 [TCP]
 dnscrypt-proxy[351]: [2019-03-14 20:59:16] [NOTICE] Now listening to [::1]:54 [UDP]
 dnscrypt-proxy[351]: [2019-03-14 20:59:16] [NOTICE] Now listening to [::1]:54 [TCP]
 dnscrypt-proxy[351]: [2019-03-14 20:59:16] [NOTICE] [sg-melek] OK (crypto v2) - rtt: 29ms
 dnscrypt-proxy[351]: [2019-03-14 20:59:16] [NOTICE] Server with the lowest initial latency: sg-melek (rtt: 29ms)
 dnscrypt-proxy[351]: [2019-03-14 20:59:16] [NOTICE] dnscrypt-proxy is ready - live servers: 1

**Comment by jedisct1** [comment]
Faster :)

And your entire system is now far more secure.
