### ISSUE TITLE
Add support for adding a whole directory as a domain filter list

### ISSUE THREAD

**Issue by lyndalopez544** [DNSCrypt/dnscrypt-proxy#762]
Something like the following:
In the dnscrypt-proxy.toml file:
<pre>
[blacklist]
  blacklist_filesdir = 'filter/'
</pre>

And dnscrypt-proxy would search for all files in that directory and apply all domain blocking rules from each of those files.

**Comment by jedisct1** [comment]
You can use the included script (`generate-domains-blacklist.py`) for this.

It can load blacklists from remote locations, but also from any number of local files.
