### ISSUE TITLE
Problem with dnscrypt-proxy version 2.0.20/2.0.21 on linux/arm64 devices

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#763]
Specifically on routers running the asuswrt-merlin firmware using the dnscrypt asuswrt installer: 
https://github.com/thuantran/dnscrypt-asuswrt-installer

Throws the error:
Mar 15 23:38:14 admin: Warning: dnscrypt-proxy is not responding

Device is RT-AC86U running asuswrt-merlin firmware 384.9

**Comment by r4sas** [comment]
As I see in that repo, your installers' maintainer uses custom build with your device toolchain ([readme](https://github.com/thuantran/dnscrypt-asuswrt-installer#how-i-made-this)), so please firstly report issue in his repo.

Also try run binary of `dnscrypt-proxy` directly without scripts and check output.

**Comment by jedisct1** [comment]
Indeed, if it's something related to a third-party installer, you should report the issue on the relevant repository.
