### ISSUE TITLE
DNS resolution only possible on port 53 after update to 2.0.21

### ISSUE THREAD

**Issue by tiiiecherle** [DNSCrypt/dnscrypt-proxy#765]
Hey,

First of all, thanks a lot for this project and and the effort put into it. Very much appreciated.

I'm using dnscrypt-proxy on archlinux (all packages up-to-date). Yesterday the package was upgraded from version 2.0.19 to 2.0.21 (so I can`t tell about 2.20). After the upgrade (with no other changes) the dns resolution stops working. I use dnscrypt-proxy on port 53000 according to the arch-wiki as dnsmasq is running on port 53.

If I stop dnsmasq and set dnscrypt-proxy to port 53 then everything is back working (even with 2.0.21) with the rest of the configuration unchanged.

If I leave dnsmasq running, set dnscrypt-proxy to port 53000 and downgrade to 2.0.19 everything is woking again, too.

Hope a fix can be implemented soon, I`ll stick with 2.0.19 for now.

Please let me know if you need any other input.

Thanks in advance

Kind regards

Tom

**Comment by r4sas** [comment]
Check journalctl logs.

**Comment by tiiiecherle** [comment]
> Check journalctl logs.

Thanks, but sorry, I already did and couldn't find anything that helped me fix it. Anything specific I could look for?

**Comment by r4sas** [comment]
When dnscrypt-proxy starting, it must write anything in syslog. Can you provide that messages?

**Comment by tiiiecherle** [comment]
Sure, thanks for looking into it.
These are the service logs if I restart dnscrypt-proxy with 2.0.21 where .

```
unit=dnscrypt-proxy
ts=$(systemctl show -p ActiveEnterTimestamp $unit)
journalctl -u $unit --since "$(echo $ts | awk '{print $2 $3}')" > /media/sf_files/"$unit"_log.txt
```


```
Mär 21 09:41:35 archvbox systemd[1]: Started DNSCrypt-proxy client.
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: dnscrypt-proxy 2.0.21
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: Dropping privileges
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: dnscrypt-proxy 2.0.21
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: Now listening to 127.0.0.1:53000 [UDP]
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: Now listening to 127.0.0.1:53000 [TCP]
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: Now listening to [::1]:53000 [UDP]
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: Now listening to [::1]:53000 [TCP]
Mär 21 09:41:35 archvbox dnscrypt-proxy[17651]: [arvind-io] OK (crypto v2) - rtt: 294ms
Mär 21 09:41:36 archvbox dnscrypt-proxy[17651]: [bottlepost-dns-nl] OK (crypto v2) - rtt: 44ms
Mär 21 09:41:36 archvbox dnscrypt-proxy[17651]: [cloudflare] OK (DoH) - rtt: 22ms
Mär 21 09:41:36 archvbox dnscrypt-proxy[17651]: [d0wn-is-ns2] OK (crypto v1) - rtt: 70ms
Mär 21 09:41:36 archvbox dnscrypt-proxy[17651]: [d0wn-tz-ns1] OK (crypto v1) - rtt: 171ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [de.dnsmaschine.net] OK (crypto v2) - rtt: 20ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [denise] OK (crypto v2) - rtt: 45ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [dnscrypt.ca-1] OK (crypto v1) - rtt: 111ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [dnscrypt.ca-2] OK (crypto v1) - rtt: 110ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [dnscrypt.eu-dk] OK (crypto v2) - rtt: 29ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [dnscrypt.eu-nl] OK (crypto v2) - rtt: 29ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [dnscrypt.me] OK (crypto v2) - rtt: 45ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [dnscrypt.nl-ns0] OK (crypto v2) - rtt: 31ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [dnscrypt.uk-ipv4] OK (crypto v2) - rtt: 33ms
Mär 21 09:41:37 archvbox dnscrypt-proxy[17651]: [doh-crypto-sx] OK (DoH) - rtt: 43ms
Mär 21 09:41:41 archvbox dnscrypt-proxy[17651]: [doh-ibksturm] OK (DoH) - rtt: 2136ms
Mär 21 09:41:41 archvbox dnscrypt-proxy[17651]: [edociccio] OK (crypto v2) - rtt: 59ms
Mär 21 09:41:41 archvbox dnscrypt-proxy[17651]: [ev-va] OK (crypto v2) - rtt: 164ms
Mär 21 09:41:41 archvbox dnscrypt-proxy[17651]: [ev-to] OK (crypto v2) - rtt: 111ms
Mär 21 09:41:41 archvbox dnscrypt-proxy[17651]: [freetsa.org] TIMEOUT
Mär 21 09:41:43 archvbox dnscrypt-proxy[17651]: [gridns-jp] OK (DoH) - rtt: 262ms
Mär 21 09:41:44 archvbox dnscrypt-proxy[17651]: [gridns-sg] OK (DoH) - rtt: 345ms
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [ibksturm] OK (crypto v2) - rtt: 232ms
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [ipredator] OK (crypto v1) - rtt: 48ms
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [kenshiro] OK (crypto v2) - rtt: 34ms
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [lucenera] OK (crypto v2) - rtt: 53ms
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [opennic-ethservices] OK (crypto v1) - rtt: 32ms
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: System DNS configuration not usable yet, exceptionally resolving [doh.powerdns.org] using fallback resolver [9.9.9.9:53]
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [powerdns-doh] OK (DoH) - rtt: 29ms
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [publicarray-au] OK (crypto v2) - rtt: 321ms
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [qag.me] TIMEOUT
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [qualityology.com] TIMEOUT
Mär 21 09:41:45 archvbox dnscrypt-proxy[17651]: [scaleway-fr] OK (crypto v2) - rtt: 37ms
Mär 21 09:41:46 archvbox dnscrypt-proxy[17651]: [securedns] OK (crypto v1) - rtt: 29ms
Mär 21 09:41:46 archvbox dnscrypt-proxy[17651]: [securedns-doh] OK (DoH) - rtt: 100ms
Mär 21 09:41:46 archvbox dnscrypt-proxy[17651]: [soltysiak] TIMEOUT
Mär 21 09:41:46 archvbox dnscrypt-proxy[17651]: [suami] OK (crypto v2) - rtt: 43ms
Mär 21 09:41:46 archvbox dnscrypt-proxy[17651]: [trashvpn.de] OK (crypto v2) - rtt: 27ms
Mär 21 09:41:46 archvbox dnscrypt-proxy[17651]: [ventricle.us] OK (crypto v2) - rtt: 107ms
Mär 21 09:41:46 archvbox dnscrypt-proxy[17651]: Server with the lowest initial latency: de.dnsmaschine.net (rtt: 20ms)
Mär 21 09:41:46 archvbox dnscrypt-proxy[17651]: dnscrypt-proxy is ready - live servers: 34
```

When I try to use ping afterwards I get:
`ping google.de temporary failure in name resolution`

**Comment by jedisct1** [comment]
Has `dnsmasq` been configured to forward its queries to `127.0.0.1:53000`?

What does `dig -p 53000 @127.0.0.1 example.com` say?

**Comment by tiiiecherle** [comment]
Yes, these settings are set in the dnsmasq configuration:
```
listen-address=127.0.0.1
server=127.0.0.1#53000
```
And I think (if not anything for this has been changed in the meantime) the setup is ok as it is working after downgrading to dnscrypt-proxy 2.0.19 without any other changes.

The output of `dig -p 53000 @127.0.0.1 example.com` with 2.0.21 is:
```

; <<>> DiG 9.13.7 <<>> -p 53000 @127.0.0.1 example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10259
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1252
;; QUESTION SECTION:
;example.com.			IN	A

;; ANSWER SECTION:
example.com.		26154	IN	A	93.184.216.34

;; Query time: 36 msec
;; SERVER: 127.0.0.1#53000(127.0.0.1)
;; WHEN: Do Mär 21 16:35:03 CET 2019
;; MSG SIZE  rcvd: 67

```

**Comment by matoro** [comment]
I believe I *may* have seen this issue on a non-systemd distro (Gentoo) as well.  Everything seemed to work fine with just dnscrypt-proxy as my primary resolver, but when I put it behind dnsmasq, things started to go haywire.  The strange thing was, I could run direct queries with `drill` and get an answer, but any applications using glibc `getaddrinfo()` would consistently fail with `EAGAIN`.  Still debugging but this sounded suspiciously similar so offering my 2 cents.

**Comment by matoro** [comment]
I am definitely seeing strange behavior now.  See the the following series of commands:

```
$ curl -L "https://registry.npmjs.org/" -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: registry.npmjs.org
$ drill @localhost registry.npmjs.org
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 41504
;; flags: qr tc rd ra ; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; registry.npmjs.org.  IN      A

;; ANSWER SECTION:
registry.npmjs.org.     193     IN      A       104.16.25.35
registry.npmjs.org.     193     IN      A       104.16.22.35
registry.npmjs.org.     193     IN      A       104.16.27.35
registry.npmjs.org.     193     IN      A       104.16.24.35
registry.npmjs.org.     193     IN      A       104.16.16.35
registry.npmjs.org.     193     IN      A       104.16.18.35
registry.npmjs.org.     193     IN      A       104.16.26.35
registry.npmjs.org.     193     IN      A       104.16.20.35
registry.npmjs.org.     193     IN      A       104.16.21.35
registry.npmjs.org.     193     IN      A       104.16.17.35
registry.npmjs.org.     193     IN      A       104.16.19.35
registry.npmjs.org.     193     IN      A       104.16.23.35

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 18 msec
;; SERVER: 127.0.0.1
;; WHEN: Tue Mar 26 00:16:41 2019
;; MSG SIZE  rcvd: 228

;; WARNING: The answer packet was truncated; you might want to
;; query again with TCP (-t argument), or EDNS0 (-b for buffer size)
$ cat /etc/resolv.conf
nameserver 127.0.0.1
# nameserver 9.9.9.9
# nameserver 1.1.1.1
$ sudo lsof -i -P | grep "dns"
dnsmasq   27087        dnsmasq    4u  IPv4 103922915      0t0  UDP 10.2.0.1:53 
dnsmasq   27087        dnsmasq    5u  IPv4 103922916      0t0  TCP 10.2.0.1:53 (LISTEN)
dnsmasq   27087        dnsmasq    6u  IPv4 103922917      0t0  UDP 10.0.0.1:53 
dnsmasq   27087        dnsmasq    7u  IPv4 103922918      0t0  TCP 10.0.0.1:53 (LISTEN)
dnsmasq   27087        dnsmasq    8u  IPv4 103922919      0t0  UDP localhost:53 
dnsmasq   27087        dnsmasq    9u  IPv4 103922920      0t0  TCP localhost:53 (LISTEN)
dnscrypt- 27159 dnscrypt-proxy    5u  IPv4 103922999      0t0  UDP localhost:8053 
dnscrypt- 27159 dnscrypt-proxy    6u  IPv4 103923000      0t0  TCP localhost:8053 (LISTEN)
dnscrypt- 27159 dnscrypt-proxy    7u  IPv6 103923001      0t0  UDP localhost:8053 
dnscrypt- 27159 dnscrypt-proxy    8u  IPv6 103923002      0t0  TCP localhost:8053 (LISTEN)
dnscrypt- 27159 dnscrypt-proxy    9u  IPv4 103923003      0t0  UDP 10.2.0.1:8053 
dnscrypt- 27159 dnscrypt-proxy   10u  IPv4 103923004      0t0  TCP 10.2.0.1:8053 (LISTEN)
```

Results are not strictly reproducible but a good portion of the time they are.  It also seems to depend on timing after service restart, etc. (queries made immediately after initialization have a much better chance of going through)

Going to downgrade to 2.0.19 and see if it helps.

**Comment by matoro** [comment]
2.0.19 seems to run without issue.  Guess the next step is a bisect but that is going to be a pain in the ass to track down

**Comment by jedisct1** [comment]
Did you try `refused_code_in_responses = true`?

**Comment by tiiiecherle** [comment]
Sorry, I did not have to get back to this earlier. Thanks for the suggestion. When looking for the config option I couldn't find it in my config file. So it must have been introduced any time after I installed dnscrypt-proxy.

So I started with a clean new config file and set all options as in the setup before. And it seems now version 2.0.21 is partially working.

Now this is even stranger. It resolves some domains and some not. I can ping google, but can not ping archlinux.org (regardless if setting refused_code_in_responses true or false) . Would be nice to get some suggestions for solving this.

Additionally it would be great to add a hint to the release notes when new config options are introduced as the config file is not automatically updated on archlinux.

Thanks for both in advance

**Comment by rprimus** [comment]
Sun Mar 31 20:24:27 BST 2019

> Now this is even stranger. It resolves some domains and some not. I can ping google, but can not ping archlinux.org (regardless if setting refused_code_in_responses true or false) . Would be nice to get some suggestions for solving this.

@tiiiecherle - Try setting `cache = false`.

**Comment by tiiiecherle** [comment]
@rprimus Thanks, now archlinux.org is resolved and can be pinged. At least most of the times. Before the first ping is sent, it takes a very long time and sometimes it fails. Two questions:
1    Am I supposed to run dnscrypt-proxy with `cache = false` all the time?
2   Is it normal for the first ping to take that long dnscrypt-proxy enabled without cache or ist there another setting that makes the whole setup more reliable?

Thanks in advance.

**Comment by rprimus** [comment]
Sun Mar 31 22:19:13 BST 2019

@tiiiecherle 

> 1 Am I supposed to run dnscrypt-proxy with cache = false all the time?

I've also had problems with `org` domains not resolving and have been with `cache = false` on all my platforms - with no problems.

> 2 Is it normal for the first ping to take that long dnscrypt-proxy enabled without cache or ist there another setting that makes the whole setup more reliable?

`dnscrypt-proxy` takes some time to startup.  Try tailing `dnscrypt-proxy.log` to see when dnscrypt-proxy has fully started before running the ping command.

**Comment by tiiiecherle** [comment]
@rprimus ok, thanks a lot. Then I think this issue is solved and can be closed. Thanks for all the help.

**Comment by jedisct1** [comment]
If you're using dnsmasq, `cache=false` should be used. In all other cases, keep it to `true`.

**Comment by jedisct1** [comment]
Try 2.0.22.
