### ISSUE TITLE
[WARNING!] 'dnsc' stamp = service INSTALLATION failure!

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#766]
**Config:** Windows 8.1 [x64], dnscrypt-proxy v2.0.21, 100% reproducible.

**ISSUE:**

**1)** `'dnsc'` **stamp**

`'dnsc'` stamp in the `dnscrypt-proxy.toml` configuration cause INSTALLATION (*.bat) failure of the `DNSCrypt client proxy` service on Windows.

For example, if you use `[static]` server configuration and your stamp for the chosen server begins from `stamp = 'dnsc://...'`, you are in trouble.

Notes:
-------
• `public-resolvers.md` and `public-resolvers.md.minisig` files somehow will be properly loaded anyway
• dnscrypt-proxy v2.0.19 does not have such issue

**2)** `service-install.bat` **output**

a) There was no corresponding warning for my `toml` config from the `service-install.bat` output.
Just "Thank you..." and no installed sevice, in fact.

b) Instead, if `toml` config looks closer to default, then I have a bit more info about this issue.
For example, if I change only `my server_names`, `listen_addresses`, `fallback_resolver` and `[static]` section (I have 2 servers) in the default config, then I have next output:

```
[2019 ...] [NOTICE] Source [public-resolvers.md] loaded
[2019 ...] [FATAL] Stamps are expected to start with sdns:
[2019 ...] [NOTICE] Source [public-resolvers.md] loaded
[2019 ...] [FATAL] Stamps are expected to start with sdns:

Thank you for using DNSCrypt-Proxy!
Press [Enter] to exit . . .
```

So, the completeness of the `service-install.bat` output somehow depends on a rest toml parameters. I don't know how.
    
**WORKAROUND:**

Just change the `stamp = 'dnsc://......'` to the `stamp = 'sdns://......'` in the `toml` config

**P.S.**
**jedisct1**, also you should fix wrong info line of the `dnscrypt-proxy2 stamp` there:	https://fr.dnscrypt.info/

**Comment by jedisct1** [comment]
The scheme on the website has been updated, thanks!
