### ISSUE TITLE
How do I specify multiple fallback resolvers, IPv4 and IPv6?

### ISSUE THREAD

**Issue by Mikaela** [DNSCrypt/dnscrypt-proxy#767]
I don't seem to be able to figure this out, I don't know which syntax do I use for IPv6 fallback resolver and my attempts result to dnscrypt-proxy failing to start.

This is possibly a duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/485, but I cannot ask there as that is closed and locked.

**Comment by jedisct1** [comment]
Hi!

Only one fallback resolver is currently supported.
