### ISSUE TITLE
Can I add an automatic update command?

### ISSUE THREAD

**Issue by liang-hiwin** [DNSCrypt/dnscrypt-proxy#768]
The automatic update script provided by the wiki is not suitable for the Raspberry Pi, and it is x86-64. I am the Raspberry Pi. I don't know how to update it.

**Comment by jedisct1** [comment]
What automatic update script are you referring to?

If you OS/distribution doesn't prove up to date packages, you can simply download a new version, replace the executable, and restart. There is nothing else to change.
