### ISSUE TITLE
unable to pull downloads from steam when dnscrpyt-proxy is set as the dns

### ISSUE THREAD

**Issue by gottaeat** [DNSCrypt/dnscrypt-proxy#770]
in a case where i use the /etc/resolv.conf configuration of dnscrpyt-proxy and have dnscrypt-proxy running as a sysvinit service, i'm unable to download games from steam. downloads get stuck at the 'starting' stage.

i'm running the latest possible dnscrpyt-proxy release at the time of writing with everything properly configured as literally everything else works the way they should.

i'm on a fully ~amd64 gentoo openrc+sysvinit installation. i didn't use the gentoo package for dnscrypt-proxy but have followed the linux installation precisely.

this is my /etc/init.d/dnscrypt-proxy script:
```
#!/sbin/openrc-run
description="dnscrypt-proxy service mode"
pidfile="/run/${RC_SVCNAME}.pid"
command="/opt/dnscrypt/dnscrypt-proxy"
command_background=true


depend() {
	need net.enp2s0
}
```

**Comment by jedisct1** [comment]
What resolvers are you using?

**Comment by gottaeat** [comment]
> What resolvers are you using?

running dnscrypt runs a ping test and picks cloudflare due to low latency each and every time.

**Comment by jedisct1** [comment]
Can you enable query logging and pinpoint what exact queries do not get an expected response?
