### ISSUE TITLE
Service exited with abnormal code: 255

### ISSUE THREAD

**Issue by gcpmusic** [DNSCrypt/dnscrypt-proxy#771]
Hello 
since update to 2.0.21 I noticed in my system log this two lines going for ever every 10 seconds:

Mar 24 14:21:25 gCs-MacBook-Pro com.apple.xpc.launchd[1] (homebrew.mxcl.dnscrypt-proxy[27144]): Service exited with abnormal code: 255
Mar 24 14:21:25 gCs-MacBook-Pro com.apple.xpc.launchd[1] (homebrew.mxcl.dnscrypt-proxy): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Mar 24 14:21:35 gCs-MacBook-Pro com.apple.xpc.launchd[1] (homebrew.mxcl.dnscrypt-proxy[27145]): Service exited with abnormal code: 255
Mar 24 14:21:35 gCs-MacBook-Pro com.apple.xpc.launchd[1] (homebrew.mxcl.dnscrypt-proxy): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

However DNSCript start log seem fine:

[2019-03-24 14:23:22] [NOTICE] Source [public-resolvers.md] loaded
[2019-03-24 14:23:22] [NOTICE] dnscrypt-proxy 2.0.21
[2019-03-24 14:23:22] [NOTICE] Loading the set of whitelisting rules from [/Users/gc/Documents/dnscrypt-proxy/whitelist.txt]
[2019-03-24 14:23:22] [NOTICE] Loading the set of blocking rules from [/Users/gc/Documents/dnscrypt-proxy/blacklist.txt]
[2019-03-24 14:23:22] [NOTICE] Loading the set of IP blocking rules from [/Users/gc/Documents/dnscrypt-proxy/ip-blacklist.txt]
[2019-03-24 14:23:22] [NOTICE] Now listening to 127.0.0.54:53 [UDP]
[2019-03-24 14:23:22] [NOTICE] Now listening to 127.0.0.54:53 [TCP]
[2019-03-24 14:23:22] [NOTICE] [cloudflare] OK (DoH) - rtt: 70ms
[2019-03-24 14:23:22] [NOTICE] [cs-rome] OK (crypto v2) - rtt: 31ms
[2019-03-24 14:23:22] [NOTICE] Server with the lowest initial latency: cs-rome (rtt: 31ms)
[2019-03-24 14:23:22] [NOTICE] dnscrypt-proxy is ready - live servers: 2

Any help?
Thank you in advance

**Comment by jedisct1** [comment]
I think you have a launchd service that tries to run a file that doesn't exist any more.

And the actual dnscrypt-proxy instance you have right now is using another one.

If you installed the service both via Homebrew and via the built-in installer, that may explain it.

Remove the `homebrew.mxcl.dnscrypt-proxy` launchd service.

**Comment by gcpmusic** [comment]
Many thanks for the reply . . you absolutely right. I Had 2 homebrew.mxcl.dnscrypt-proxy.plist, 1 in the /usr/local/Cellar/dnscrypt-proxy/2.0.21 folder and the other in the /Library/LaunchDaemons/ .

However I always had both in this directories as any new update, true homebrew, always include it in the new version folder and starting the service via terminal always create it in the  /Library/LaunchDaemons/ and true all the many updates I never had this issue.

Deleting the one in the in the /usr/local/Cellar/dnscrypt-proxy/2.0.21 solved the issue however I guess next update will include it again and I guess I have to delete it again.

All the best
gC

**Comment by rr0ss0rr** [comment]
How do you start/stop the dnscrypt-proxy service?  "brew services start/stop"?  I believe that command will remove the plist from LaunchDaemons or install the plist from the cellar into LaunchDaemons.

**Comment by gcpmusic** [comment]
Yes that's what I thought too. Now after deleting the one in the usr/ when stoped, doesnt delete the one in the LaunchDaemons and if I delete it manually, will be re-create automatically again "in the LaunchDaemons " but surely not copied as in the cellar/ there isnt anymore and everything is fine.

So looks like to me that the homebrew.mxcl.dnscrypt-proxy.plist within the update folder is useless.

**Comment by r4sas** [comment]
Please go to brew's package maintainer, it is not dnscrypt-proxy issue.

**Comment by jedisct1** [comment]
Indeed. There's not much I can do if this is a Homebrew  issue.

**Comment by gcpmusic** [comment]
Sure and thank you both for your time.
