### ISSUE TITLE
Occasional extremely slow responses

### ISSUE THREAD

**Issue by username-password** [DNSCrypt/dnscrypt-proxy#772]
Randomly, about once every two minutes on average, a DNS request takes multiple (5+) seconds to resolve. I have no idea why and have tried everything I could think of to fix this:
- setting various timeout values in the conf or none
- different load balancing settings
- various static servers or any
- TCP or UDP
- cache settings
- dnscrypt or DOH
- different machines
- different phys. networks
- logging requests (looks random)

Often the names to resolve are common ones like "google.com" and this makes dnscrypt-proxy a pain to use.

**Comment by jedisct1** [comment]
Might be a network issue. But without any context or more low-level investigation from your part, this is unlikely to be solved.

**Comment by username-password** [comment]
@jedisct1 I did some testing and I think the issue is with the servers dnscrypt-proxy selected as the "best" options, based (solely?) on ping. While they had the lowest ping they sometimes failed to resolve properly (SERVER ERROR messages in the query log) causing huge delays that slowed down browsing to a crawl among other things. Switching servers manually yet again made it at least tolerable. Better server selection strategy or failover needed I suppose.
