### ISSUE TITLE
Proposal to improve OpenWRT configuration instructions

### ISSUE THREAD

**Issue by the-w1nd** [DNSCrypt/dnscrypt-proxy#776]
First of all - Thanks a lot to Frank (@jedisct1) and everyone else who contributed to such a great utility!  Kudos!

In order to tighten the security, I would like to propose some changes to installation instructions for OpenWRT environments, so it does not leak DNS requests to the ISP.  I've written my current tested changes in the [OpenWRT forum](https://forum.openwrt.org/t/how-to-properly-configure-dnsmasq-for-dnscrypt-v2-to-prevent-leaks-to-isp/33907) and improved/finalized it with the help of others.

I would like to hear any comments or suggestions before changing the wiki page here.  Or feel free to modify the wiki from my suggestions.

The important part is that the proper configuration should pass the tests (1) and (2) from the section ["How to check what features are supported by your resolver"](https://openwrt.org/it/docs/guide-user/services/dns/dnscrypt#how_to_check_what_features_are_supported_by_your_resolver).

Thanks

**Comment by jedisct1** [comment]
Hi!

And thanks for pointing out that `dnsmasq` was still used.

I thought DNS queries were redirected using firewall rules. But you are correct, port 53 was always bound to `dnsmasq`, and what happens is quite the opposite of the original intent.

The original intent was to use `dnsmasq` only for local domain names (DHCP device names).

This can still be easily achieved by having `dnsmasq` listen to a different port.

The Wiki was updated to do this, and as an unexpected result, everything is easier since there is no need to change the DNS settings on individual interfaces.

I just followed the steps on an OpenWRT router, and everything seems to work fine, but your reviews and additions are more than welcome.

**Comment by the-w1nd** [comment]
Well ... while your proposed configuration is going to hide `dnsmasq` from direct requests, the important part is that the `/etc/resolv.conf` is still there and pointing to the ISP.  So, local programs running on the router (e.g. `nslookup`) would be able to use it and still hit the ISP.

Also, if you have static DHCP with hostnames populated, hosts on the local network would not be able to resolve other host names by their short names.  They'd have to use fqdn with the ".lan" suffix (or the configured domain).

**Comment by jedisct1** [comment]
Doesn't `/etc/resolv.conf` have this by default?

```text
search lan
nameserver 127.0.0.1
```

I just reinstalled OpenWRT from scratch and got this.

Resolving local names without the domain should also be fine if the DHCP server sends `.dev` as the default search domain.

**Comment by the-w1nd** [comment]
Most likely, you've done "sysupgrade" on your router and it preserved your old configuration.  If you use the "*-factory.img" image of OpenWRT for your router, it will make it a sparkling clean default environment, which can be referenced under `/rom/etc/config/` folder.  You can see that `/rom/etc/config/dhcp` has the following option:
`config dnsmasq
        option resolvfile       '/tmp/resolv.conf.auto'`
which is going to point to your ISP and get copied into `/tmp/resolv.conf` and sym-linked into `/etc/resolv.conf`.

You must've either customized your `/etc/resolv.conf` file or enabled option `option localuse 1`

On my Windows client, I can see that the DHCP server properly provided "DNS Suffix Search List", so maybe it was some old problem that I had experienced when looking up other machines by their short names.  Or maybe I had it when using Windows shares, which uses WINS (if I remember it right).

Anyway, I believe using `dnsmasq` as the primary service is the right approach architecture wise, so everything goes through it.  And making DNSCrypt v2 as a separate service for outside DNS requests only by dnsmasq is the right approach.  Your suggested configuration puts DNSCrypt in front of dnsmasq and creates an unnecessary overhead and configuration loop (when either service can send a request to the other one).  Could be just my opinion.

**Comment by jedisct1** [comment]
You know OpenWRT far better than I do, so feel free to update the Wiki with something great :)

**Comment by the-w1nd** [comment]
> You know OpenWRT far better than I do

I would never make such a claim.  That's why I need others' help in double-checking my proposals. :)

One other thing to add - DNSCrypt v1 was created many years ago and knowledgeable people integrated it properly into OpenWRT.  I just tried to preserve that layout for DNSCrypt v2.

**Comment by the-w1nd** [comment]
Just updated the wiki: https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-on-OpenWRT
Could somebody double-check my changes, please?

**Comment by jedisct1** [comment]
This is awesome, thank you so much for this!

**Comment by the-w1nd** [comment]
You're welcome.  Just added one small section to redirect all external DNS requests into the router,

One thing I wanted to check with with - you've listed this topic on the wiki:
> Check that you are not using your ISP resolver any more:
> 
> openwrt > dnscrypt-proxy -resolve google.com
> 
> Resolver IP should not belong to your ISP. 

Does it mean that "dnscrypt-proxy" would behave in "client" mode and use network's configuration to run the request?  Or would it still try to use its toml-file and pick one of its servers to resolve the query?

**Comment by vanyaindigo** [comment]
Is there any way to use 2 separate blacklist.txt files in dnscrypt-proxy.toml config file (first for adblock and second for local domains)?

**Comment by the-w1nd** [comment]
> Is there any way to use 2 separate blacklist.txt files in dnscrypt-proxy.toml config file (first for adblock and second for local domains)?

At the moment, there is no way to provide more than one entry for the `blacklist_file` configuration option.  But anyone who builds their own black lists from external sources (e.g. adblock, etc.) should use a file with local domains that will be included into the black list by its generator.  All [examples provided with DNSCrypt v2](https://github.com/jedisct1/dnscrypt-proxy/tree/master/utils/generate-domains-blacklists) include the following line to do that:
```
# Local additions
file:domains-blacklist-local-additions.txt
```

I guess this can also be filed as an enhancement to configuration options of DNSCrypt v2 to support more than one blacklist file.  @jedisct1, what's your opinion?

**Comment by vanyaindigo** [comment]
In fact, this is a half-measure: each time after the refirmware manually create one file blacklist.txt is not optimal. The peculiarity here is that one file is permanent, the second is variable. Of course, I can solve this problem by constantly adding local domains to the Adblock for manual blocking.

**Comment by vanyaindigo** [comment]
Don't like this new solution. Works with lag.

**Comment by the-w1nd** [comment]
What configuration did you have before?  The same one as on the wiki before my change?
Have you been using adblock filters with DNSCrypt or dnsmasq?  Have you tried disabling them?  Any process spikes on the CPU when you run DNS queries?

**Comment by vanyaindigo** [comment]
My today configuration that was before:

/etc/config/dhcp
```
config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option filterwin2k '0'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option noresolv '1'	
	list server '/pool.ntp.org/1.0.0.1'
	list server '127.0.0.53#53'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option nonegcache '0'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option ednspacket_max '1280'
	option cachesize '10000'
	option nonwildcard '1'
	option localservice '1'
        option dnsforwardmax '300'
```

/etc/dnsmasq.conf empty

/etc/config/dnscrypt-proxy.toml
```
listen_addresses = ['127.0.0.53:53']
forwarding_rules = 'forwarding-rules.txt'
```

forwarding-rules.txt

```
test 127.0.0.1
onion 127.0.0.1
localhost 127.0.0.1
local 127.0.0.1
invalid 127.0.0.1
bind 127.0.0.1
lan 127.0.0.1
internal 127.0.0.1
intranet 127.0.0.1
private 127.0.0.1
workgroup 127.0.0.1

10.in-addr.arpa 127.0.0.1
16.172.in-addr.arpa 127.0.0.1
168.192.in-addr.arpa 127.0.0.1
254.169.in-addr.arpa 127.0.0.1
```

/etc/config/firewall
```
config redirect 'force_dns_53'
	option name 'Force DNS'
        option src 'lan'
	option dest 'lan'
	option proto 'tcp udp'
	option src_dport '53'
        option target 'DNAT'
	option dest_port '53'        	

config redirect 'force_dns_853'
	option name 'Force DNS, port 853'
	option src 'lan'
	option dest 'lan'
	option proto 'tcp udp'
	option src_dport '853'
	option target 'DNAT'
	option dest_port '53'

config redirect 'force_dns_5353'
	option name 'Force DNS, port 5353'
	option src 'lan'
	option dest 'lan'
	option proto 'tcp udp'
	option src_dport '5353'
	option target 'DNAT'
	option dest_port '53'
```

Works perfect.

**Comment by the-w1nd** [comment]
> My today configuration that was before:

I'm not sure what you mean. :)  Is this your old config?  Or the new one?

The above config seems fine for handling requests for external addresses.  However, for internal PTR queries, it will kill your services in the following way:
1. Let's say a client on the local network performs DNS Service Discovery (a.k.a. dns-sd) - it will send the following PTR query to your `dnsmasq` (if your router is on 192.168.1.1):
   `dig -x lb._dns-sd._udp.0.1.168.192.in-addr.arpa @192.168.1.1`
2. Since your `dnsmasq.conf` is empty, and you're using `option localuse 1`, the `dnsmasq` will forward the query to DNSCrypt
3. DNSCrypt's `forwarding-rules.txt` will make it sent again to `dnsmasq`, which in turn will create a new connection and forward it back to DNSCrypt
4. A short moment later, one of them is going to reach the limit of open connections and refuse the new one after printing a message in the syslog.
5. However, the other process, that was denied the connection, will keep retrying to connect until you stop both processes.

That's why it's important to not make loops in the configuration and use the `dnsmasq.conf` and `blacklist` like the wiki says.

**Comment by vanyaindigo** [comment]
> That's why it's important to not make loops in the configuration and use the `dnsmasq.conf` and `blacklist` like the wiki says.

It's not possible with adblock

**Comment by the-w1nd** [comment]
I don't see a problem with adblock.  You've commented earlier about configuration troubles during re-flashing the firmware, so let's talk about it - there are several ways to get it done properly:

One approach you can use (and I've been using forever) is the adblock supplied by OpenWRT.  It makes changes in `dnsmasq` configuration, so it block domains before even forwarding them to DNSCrypt.

Another approach is to use adblock filters in DNSCrypt.  In order for the configuration to persist between firmware re-flashes is to put the list of local domains into `/etc/config/domains-blacklist-local-additions.txt` and have it included into the black list generator's config (which can also be configured to be preserved during re-flashes).

However - the proper way to solve this problem is by listing the local domains in `/etc/dnsmasq.conf` just like the wiki says.  Since your network configuration will dedicate `dnsmasq` as the sole entry point for DNS requests, no local queries are going to reach DNSCrypt.  So, not only there would not be any need for `forwarding-rules.txt`, but you would also not need to keep the static list for DNSCrypt's adblock.

**Comment by vanyaindigo** [comment]
In Adblock blacklist you can't use ip addresses, wildcards & regex. So you can't add something you mention in adblock to add it to one blacklist.txt. And your solution resolves with lag around 1 sec.

**Comment by the-w1nd** [comment]
> In Adblock blacklist you can't use ip addresses, wildcards & regex.

Of course wildcards and regexes are supported!  Take a look at the [example-blacklist.txt](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-blacklist.txt) and you'll see them.  The code also uses PatternMatcher to process queries.

> And your solution resolves with lag around 1 sec.

I don't see any performance difference between using the old config from the wiki and the new one.  Can you try to figure out which change in the configuration introduces the lag for you?  Just remember that dnsmasq and DNSCrypt both have caches, so to make tests fair, restart both services before running searches with them.  And try using "dig" on the router to hit DNSCrypt directly just to see the time it takes for DNSCrypt to get the answer from the external DNS server: `dig <host> @127.0.0.53`
