### ISSUE TITLE
DNS traffic isn't encrypted or authenticated

### ISSUE THREAD

**Issue by Tomb-3** [DNSCrypt/dnscrypt-proxy#777]
I followed this: https://github.com/jedisct1/dnscrypt-proxy/wiki/Checking and I when the service is stopped it still resolves the likes of youtube.com for example even when I add/use it on the blacklist.txt file.

Other than that when I check at dnsleaks.com it shows my queries are going over those dnscrypt has set.

**Comment by vanyaindigo** [comment]
Use instructions from this thread https://github.com/jedisct1/dnscrypt-proxy/issues/776

**Comment by Tomb-3** [comment]
That thread doesn't relate to my issue. 

Prior to following [https://github.com/jedisct1/dnscrypt-proxy/wiki/Checking](https://github.com/jedisct1/dnscrypt-proxy/wiki/Checking), I believe my connection was 'partially' or more along the lines of broken i.e, some queries were still showing up as resolving from my ISP. I understand my method for checking, using 'dnsleaks.com' wasn't the most thorough, but works nonetheless.

Having gone through the wiki I found [https://github.com/jedisct1/dnscrypt-proxy/wiki/Checking](https://github.com/jedisct1/dnscrypt-proxy/wiki/Checking) and began debugging, but it appears I was right and it doesn't encrypt traffic fully for me.

> If applications cannot resolve anything any more, it probably means that all your DNS traffic was going through the proxy, and was therefore encrypted and authenticated.

After stopping the service my requests still resolve. And therefore tried the blacklist method.

> If you can't access it any more, it means that your DNS traffic is using the proxy, and is therefore encrypted. If you still do, then make sure to flush your DNS cache and restart dnscrypt-proxy service.

with 'flushdns' QUERY.LOG

```
[2019-04-05 18:49:34]	127.0.0.1	youtube.com	CNAME	PASS
[2019-04-05 18:49:34]	127.0.0.1	youtube.com	A	PASS
[2019-04-05 18:49:34]	127.0.0.1	resolver.dnscrypt.info	A	PASS
[2019-04-05 18:49:34]	127.0.0.1	ip.in-addr.arpa	PTR	SERVER_ERROR
[2019-04-05 18:49:34]	127.0.0.1	ip.in-addr.arpa	PTR	SERVER_ERROR
[2019-04-05 18:49:55]	127.0.0.1	secure20.sync.com	A	PASS
[2019-04-05 18:49:59]	127.0.0.1	youtube.com	CNAME	PASS
[2019-04-05 18:49:59]	127.0.0.1	resolver.dnscrypt.info	A	PASS
[2019-04-05 18:49:59]	127.0.0.1	my.ip.in-addr.arpa	PTR	SERVER_ERROR
[2019-04-05 18:49:59]	127.0.0.1	my.ip.in-addr.arpa	PTR	SERVER_ERROR
```

**Also, not sure why my post was closed.**

**Comment by uBlock-user** [comment]
> After stopping the service my requests still resolve

Every DNS query is cached by default. Clear the cache and try again, it will not resolve.

On Windows, it's `ipconfig /flushdns`

**Comment by jedisct1** [comment]
You didn't provide any information about your environment, so it's hard to help.

If arbitrary queries still resolve when the proxy is disabled, it means that your DNS settings still list other IP addresses than the one of the dnscrypt-proxy server.
