### ISSUE TITLE
Add checksums to verify downloads

### ISSUE THREAD

**Issue by J316** [DNSCrypt/dnscrypt-proxy#782]
Compiling minisign just to verify the sporadically downloaded file is a daunting process, some Linux distribution don't package Libsodium, so that must be compiled too. Adding checksums in the download section is very easy and has no downsides, thus they should be provided in addition to minisign in order to verify downloads.

**Comment by jedisct1** [comment]
Checksums don't verify anything, as anybody can generate them for any file.

But I'll try to add precompiled binaries for Linux.

**Comment by J316** [comment]
@jedisct1 You are saying all the people who present them as a mean to verify the distro/app/software/whatever you just downloaded are delusional, and I really don't mean to change your mind. But what are the cons of providing them? Why in the world shouldn't they be provided? What's one single reason why putting that small string would be unreasonable or a problem?

**Comment by jedisct1** [comment]
The file size is displayed. A checksum offers the the same authenticity assurance (none).

**Comment by J316** [comment]
@jedisct1 Why not provide them? What's to lose?
