### ISSUE TITLE
Issue with some Windows functions

### ISSUE THREAD

**Issue by absynteZero** [DNSCrypt/dnscrypt-proxy#785]
Hi,

I see there was already a post for this but this is the 2.0.22.

i use Windows 10 Pro x64, very simple installation.
All is runnig well except some Windows functions.

I can update my computer system but i can't access to Windows Store. I've to set an other dns form ethernet.

* i'm not engineer...
I can't too log into my Microsoft account.

I've try by using an other dns and all is ok.

There is an issue with Windows store connection and with account login.

It will be nice to fix it.

I think it's not very possible to be hiden from Microsoft. Why don't you send Windows dns queries to the second dns setted in toml?
For my use this is what i need. but maybe some advanced users will want to set by ip themself..?

Thanks.

Samuel

**Comment by r4sas** [comment]
That's not dnscrypt-proxy issue, use other dns server.
