### ISSUE TITLE
[Enhancement] Use of Bit 0x20 in DNS Labels to Improve Transaction Identity

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [DNSCrypt/dnscrypt-proxy#788]
It's random case switching for query domain. For example this can make repeated query for same domain but without padding, look less the same for adversary also. As [described by ietf](https://tools.ietf.org/html/draft-vixie-dnsext-dns0x20-00)
Easy to implement. :) [Research Increased DNS Forgery Resistance Through 0x20-Bit Encoding SecURItY viA LeET QueRieS
](http://courses.isi.jhu.edu/netsec/papers/increased_dns_resistance.pdf)

**Comment by jedisct1** [comment]
Some servers and stub resolvers still have compatibility issues with this, and it's useless since queries and responses are encrypted.
