### ISSUE TITLE
[Enhancement] add configuration Prefer IPv6 or IPv4

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [DNSCrypt/dnscrypt-proxy#789]
Add configuration setting for preference of a result would let IPv4-prioritized devices to use IPv6 first, or lets IPv6-prioritized devices to use IPv4 first. 

Here's how it works (when IPv6 is set as priority. IPv4 is similar):

If it's a type A query, send an AAAA query to upstream DNS server
If there's an AAAA record, forward it to client; if not, send the A query result to client.

Could be speed up by using ANY to upstream but not all support ANY nowadays. To not add extra latency, make use of `go` threads to spawn a second query for the other type in parralell.

**Comment by jedisct1** [comment]
If the client gets a response of a different type that it asked, the reponse will be ignored.
