### ISSUE TITLE
[Enhancement] add a new tor server filter

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [DNSCrypt/dnscrypt-proxy#790]
We do suggest, to add a new server filter for tor dns server. Because of [Issue.](https://github.com/DNSCrypt/dnscrypt-resolvers/pull/114#issuecomment-482927830)
`# Use servers reachable over hidden services -- Do not enable if you don't have tor connectivity`
`onion_servers = false`

**Comment by jedisct1** [comment]
The issue you link is not about Tor connectivity, but about accessing onion services.

You can maintain a source of onion services providing DNS if you like.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
@jedisct1 i believe this is issue is fixed by https://github.com/jedisct1/dnscrypt-proxy/commit/5c9edfccfe67474bee2836ada67f955f10e43357
