### ISSUE TITLE
Please add an ARMv7 build to releases

### ISSUE THREAD

**Issue by jwlsinx** [DNSCrypt/dnscrypt-proxy#792]
While trying to use on a [new device](https://www.netgate.com/solutions/pfsense/sg-3100.html), I get the following error

```
$ ./dnscrypt-proxy -version
runtime: this system has multiple CPUs and must use
atomic synchronization instructions. Recompile using GOARM=7.
```

This appears to be an issue not covered during the discussion in #682

**Comment by jwlsinx** [comment]
Realized that this is exactly what was raised in #682 but not fully resolved. I will build manually for now.

**Comment by jedisct1** [comment]
Does it work with `GOARM=6`?

**Comment by jwlsinx** [comment]
> Does it work with `GOARM=6`?

No, I get the same error.

**Comment by jedisct1** [comment]
`GOARM=7`?

**Comment by jwlsinx** [comment]
Building with `GOOS=freebsd GOARCH=arm GOARM=7 go build -ldflags="-s -w"` works (pulled from #682).

The `GOOS=freebsd GOARCH=arm GOARM=6 go build -ldflags="-s -w"` build failed though (same error on device).
