### ISSUE TITLE
High CPU load and unavaibility on router

### ISSUE THREAD

**Issue by Askelipasa** [DNSCrypt/dnscrypt-proxy#794]
I installed dnscrypt-proxy2 (2.0.21-1) from Entware on my Xiaomi Router 3g with Padavan firmware and when i use internet CPU on my router loads to ~60-90% for ~3sec every minute, when that happens internet connection becomes unavaible for these ~3 sec . 
dnscrypt-proxy.log (log level 0)
[2019-04-17 11:38:12] [NOTICE] Stopped.
[2019-04-17 11:38:18] [NOTICE] Source [public-resolvers.md] loaded
[2019-04-17 11:38:19] [NOTICE] dnscrypt-proxy 2.0.21
[2019-04-17 11:38:19] [NOTICE] Now listening to 127.0.0.1:65053 [UDP]
[2019-04-17 11:38:19] [NOTICE] Now listening to 127.0.0.1:65053 [TCP]
[2019-04-17 11:38:20] [NOTICE] [cloudflare] OK (DoH) - rtt: 13ms
[2019-04-17 11:38:20] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 13ms)
[2019-04-17 11:38:20] [NOTICE] dnscrypt-proxy is ready - live servers: 1
CPU load graph 
![Utilization](https://user-images.githubusercontent.com/49719134/56286841-6c493f00-6123-11e9-8dd3-0b1e394042ac.png)
My dnscrypt-proxy.toml
[dnscrypt-proxy.txt](https://github.com/jedisct1/dnscrypt-proxy/files/3089590/dnscrypt-proxy.txt)
Sorry if I'm writing in the wrong place.

**Comment by r4sas** [comment]
Please firstly check which app create load. Use for example `top` program, it must be available in firmware or in entware.

**Comment by Askelipasa** [comment]
Here 
![1555506698862](https://user-images.githubusercontent.com/49719134/56290318-8d159280-612b-11e9-8ce4-e9730cbc4b80.png)

**Comment by AnyWAT** [comment]
example-dnscrypt-proxy.toml：fallback_resolver = '9.9.9.9:53'
dnscrypt-proxy.txt：fallback_resolver = '1.1.1.1'

**Comment by AnyWAT** [comment]
> My dnscrypt-proxy.toml
> [dnscrypt-proxy.txt](https://github.com/jedisct1/dnscrypt-proxy/files/3089590/dnscrypt-proxy.txt)

fallback_resolver = '1.1.1.1'
1.1.1.1:65053 ？listen_addresses = ['127.0.0.1:65053']
example-dnscrypt-proxy.toml：fallback_resolver = '9.9.9.9:53'

**Comment by Askelipasa** [comment]
Сhanged to fallback_resolver = '1.1.1.1:65053', CPU still loads
![1555508960656](https://user-images.githubusercontent.com/49719134/56293006-f0ee8a00-6130-11e9-9ff4-11b2b0c6dec0.png)

**Comment by jedisct1** [comment]
Try to disable logging, and use a DNSCrypt server instead of DoH.

**Comment by Askelipasa** [comment]
.# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = false
I disabled logging and choose Yandex dns without DoH.
![изображение](https://user-images.githubusercontent.com/49719134/56294278-63606980-6133-11e9-9d24-43496011efad.png)
For at least 5 min there is no high cpu load
17:04-17:20 still ok

**Comment by jedisct1** [comment]
DoH is slow. It requires more traffic. About 10 times more: https://twitter.com/PowerDNS_Bert/status/1064290946731384832

It's also bad at recovering from packet loss https://twitter.com/PowerDNS_Bert/status/1064424694374432768

And TLS is taxing on the CPU. This is not too significant on modern Intel CPUs, but on routers, using TLS for DNS is not a good idea.

This router may not have a very powerful CPU. Which can be okay, since network interfaces do a lot of offloading these days. Not so much for running other software, especially software doing a lot of TLS traffic.

**Comment by Askelipasa** [comment]
I asked the author of a video instruction on installing dnscrypt2(with DoH) how it all works today on his router, but 6 months ago everything was in perfect order on his router with a really weaker processor.
Anyway thank for help

**Comment by jedisct1** [comment]
For DoH, `tls_cipher_suite = [52392, 49199]` can also help.

**Comment by Askelipasa** [comment]
Seems it worked. Sorry, i didn't see this section before
![изображение](https://user-images.githubusercontent.com/49719134/56298210-6f9bf500-613a-11e9-8219-297348f316cf.png)
