### ISSUE TITLE
Post update scripts?

### ISSUE THREAD

**Issue by nyarly** [DNSCrypt/dnscrypt-proxy#795]
I've configured dnscrypt-proxy2 behind unbound as a local forwarder. (I need to use a split-resolving VPN, which I manage with unbound.)

The trouble is that, when I lose network, dnscrypt needs a while to re-collect its upstream servers. During this period it fails to resolve, and unbound marks it as lame.

What I'd like to do is have dnscrypt-proxy2 run a script when it's ready to serve traffic that I could use to flush unbound's cache (which is what I do manually to fix this situation.) Is there a way to do this, or a better approach?

**Comment by jedisct1** [comment]
> dnscrypt needs a while to re-collect its upstream servers

Can you clarify what you mean here? Is `dnscrypt-proxy` restarted after the network goes down? What causes this?

**Comment by nyarly** [comment]
I'm honestly not sure. What I find is that when my network goes down (e.g. my WAP loses power), when the connection is restored, I frequently need to mess with my DNS stack, and part of that has been seeing dnscrypt re-checking it's server list. At one point I was restarting dnscrypt and unbound until name resolution was restored, but I'm trying to find a more automatic solution.

**Comment by jedisct1** [comment]
The server list is only refreshed every 3 days by default (this is configurable for each source, see the `refresh_delay` parameter). And certificates are reloaded after 2 hours, never after a network event.

How is the server started? Did you just install it with `dnscrypt-proxy -service install`?

**Comment by jedisct1** [comment]
a9a13485a9078567380d4e3c1de96c643d8d8a8d39412f7f8269ac2cfd42edf5

**Comment by nyarly** [comment]
I'm installing it via NixOS. I've just observed the behavior, so I think I can characterize it better:

* My machine loses network while I'm away from it.
* While the network is unavailable, dnsproxy reloads certificates. All servers time out.
* I return and try something that uses DNS.
* That doesn't work, but unbound has cached negative response from dnsproxy.
* I reconnect network, and restart dnsproxy.
* Dnsproxy reloads the server list and checks upstream servers.
* Unbound still needs to be flushed or the negative result allowed to expire. 

I'm also investigating whether I can get unbound to cache negative results from a single forwarder for a shorter period, but it seems to be a whole-server setting, and VPN requirements would mean I apply that to many other flakier DNS servers.

Does that make sense?
