### ISSUE TITLE
CPU periodically at 100% on mips64 platform

### ISSUE THREAD

**Issue by cinergi2** [DNSCrypt/dnscrypt-proxy#797]
I'm running dnscrypt-proxy 2.0.22 on a mips64 embedded platform (Ubiquiti Edgerouter).  I've noticed that seemingly at random, the dnscrypt-proxy process spikes to >100% CPU usage (it's a dual-core processor) for approx. 10-20 minutes, then goes back to normal.  I've noticed this happening every few days, but it might be more often (I have no way of knowing).  When it happens, dnscrypt-proxy is unresponsive and DNS lookups for the entire network fail as a result; that's how I know to check it.  The log shows nothing abnormal.

My only DNS provider is cloudflare (DoH).

Any ideas?

-cinergi

**Comment by jedisct1** [comment]
See https://github.com/jedisct1/dnscrypt-proxy/issues/794

**Comment by cinergi2** [comment]
Thanks, I had already seen #794 but in my case, the high CPU usage lasts for much longer (~10-20 minutes) and then goes down to 0%.  There is no significant load on the network while the CPU usage is high, so I don't think my issue is due to DoH encryption overhead.  In any case, I've uncommented the tls_cipher_suite line as recommended and will keep an eye on it.

Thanks
cinergi
