### ISSUE TITLE
File paths relative to dnscrypt-proxy.toml

### ISSUE THREAD

**Issue by Sporif** [DNSCrypt/dnscrypt-proxy#80]
Not sure if [c2494cf](https://github.com/jedisct1/dnscrypt-proxy/commit/c2494cfc400e0ba2b67a59d2d5337dbd6e70c6e7) is working, files included in the same folder as dnscrypt-proxy.toml (with dnscypt-proxy.exe in a different folder) aren't being detected. Unless that wasn't the intention?

**Comment by jedisct1** [comment]
It should be good now. Thanks!
