### ISSUE TITLE
dnscrypt-proxy + too max connections again with v2.0.22

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#800]
Hi!

I installed v2.0.22 and my log says even often "too max connections"

I didn't have any problems with the previous version and I don't edited anything.

max_clients = 250

How to fix that? Lowering max_clients to 200-240?

**Comment by jedisct1** [comment]
Can you look at the query log to see what the queries are?

**Comment by ghost** [comment]
How can I set Query.logs in the config-file of dnscrypt-proxy?

**Comment by AnyWAT** [comment]
Try：
![image](https://user-images.githubusercontent.com/37962734/55392322-a506e700-556d-11e9-84fd-d8f6eb746fed.png)
To：
log_file = 'dnscrypt-proxy.log'
Run：
"service-restart.bat"

**Comment by jedisct1** [comment]
Look for `query log` in the configuration file, there's a whole section dedicated to it.

**Comment by ghost** [comment]
I've set:

[query_log]

 file = 'dNz-qUEr!eZ.log'

 format = 'tsv'

 ignored_qtypes = ['DNSKEY', 'NS']

[nx_log]

 file = 'dNz-nX.log'

 format = 'tsv'

...but dnscrypt-proxy don't create the files.

Do I have to create the files myself?

**Comment by ghost** [comment]
I created the 2 log-files myself, but dnscrypt-proxy don't write logs to it.

**Comment by vanyaindigo** [comment]
There are too many PTR requests: *.168.192.in-addr.arpa

**Comment by ghost** [comment]
How can I fix it @ vanyaindigo?

**Comment by mezzovide** [comment]
For me it was because incorrect routing issues
