### ISSUE TITLE
Question re. outgoing connections to raw.githubusercontent.com/camo.githubusercontent.com

### ISSUE THREAD

**Issue by 9jkh** [DNSCrypt/dnscrypt-proxy#806]
Can you kindly offer an explanation as to the purpose of these 2 outgoing connections. Related to version update checking: Initial version installed was v2.0.22 and seeing now a new v2.0.23 release?

**Comment by jedisct1** [comment]
Look at your config file...

**Comment by 9jkh** [comment]
Sorry, don’t understand. On MacOS 10.13.6, not finding a dnscrypt-proxy config file anywhere. And if I find it what should I be looking for. Maybe you can just tell me what the purpose is of these connections. I only want to be certain that these 2 connections are legitimate, nothing nefarious.

Thanks

**Comment by jedisct1** [comment]
This is where the up-to-date lists of working public DNS servers are downloaded from. But you should really try to find where the configuration file is, and read the documentation to see what you can do with the software. https://github.com/jedisct1/dnscrypt-proxy/wiki

**Comment by 9jkh** [comment]
OK, I’m seeing the “config" file you refer to is the dnscrypt-proxy.toml (line 499 in my text editor): https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md 

Think I understand now. But not sure why it needs to DL these from raw.github. Seems redundant, since I have already listed selected servers in the .toml (Quad9 from https://dnscrypt.info/public-servers/) 

But anyway, obviously needed, nothing nefarious or amiss. Won’t bother with this any longer. End of newbie question.

**Comment by 9jkh** [comment]
OK, thanks. emails crossed. Will read into this some more.
