### ISSUE TITLE
DNSCrypt DoH

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#808]
If using a DoH server does this need to be commented back in?

#HTTP/HTTPS proxy
#Only for DoH servers

#http_proxy = "http://127.0.0.1:8888

I'm having issues with Firefox recognising I'm connected to the internet with TRR mode forced on (`network.trr.mode:3`) - seems to happen with it commented in and out. :S

**Comment by jedisct1** [comment]
If you are not using a HTTP proxy, leave this commented.
