### ISSUE TITLE
Unable to load the configuration file [dnscrypt.proxy.toml]

### ISSUE THREAD

**Issue by 480gh8q0hg08** [DNSCrypt/dnscrypt-proxy#813]
Hi does anyone know why I'm not able to use dnscrypt proxy with Quad9? I can connect to cloudflare just fine and even other services like the OpenNIC. But Quad9 doesn't work for me. 

Usually I've tried typing this in for the sources
quad9-dnscrypt-ip4-filter-pri
quad9-dnscrypt-ip4-filter-alt

But I've also tried these and no luck

quad9-dnscrypt-ip4-nofilter-pri
quad9-dnscrypt-ip4-nofilter-alt
quad9-doh-ip4-filter-alt

**Comment by jedisct1** [comment]
Can you define "doesn't work"?

What exact log/error messages from dnscrypt-proxy  do you get when `server_names` includes one of the Quad9 resolver name?

**Comment by AnyWAT** [comment]
[2019-05-04 21:38:55] [NOTICE] [quad9-dnscrypt-ip4-filter-pri] OK (DNSCrypt) - rtt: 148ms
[2019-05-04 21:38:55] [NOTICE] [quad9-dnscrypt-ip4-filter-alt] OK (DNSCrypt) - rtt: 102ms
[2019-05-04 21:38:55] [NOTICE] [quad9-dnscrypt-ip4-nofilter-pri] OK (DNSCrypt) - rtt: 140ms
[2019-05-04 21:38:55] [NOTICE] [quad9-dnscrypt-ip4-nofilter-alt] OK (DNSCrypt) - rtt: 187ms

[2019-05-04 21:39:01] [NOTICE] [quad9-doh-ip4-filter-pri] OK (DoH) - rtt: 330ms
[2019-05-04 21:39:01] [NOTICE] [quad9-doh-ip4-filter-alt] OK (DoH) - rtt: 342ms
[2019-05-04 21:39:01] [NOTICE] [quad9-doh-ip4-nofilter-pri] OK (DoH) - rtt: 144ms
[2019-05-04 21:39:02] [NOTICE] [quad9-doh-ip4-nofilter-alt] OK (DoH) - rtt: 137ms

[2019-05-04 21:39:23] [NOTICE] Server with the lowest initial latency: geekdns-doh-east (rtt: 25ms)
[2019-05-04 21:39:23] [NOTICE] dnscrypt-proxy is ready - live servers: 44

**Comment by jedisct1** [comment]
There doesn't seem to be anything wrong here?

`geekdns-doh-east` was preferred because it's 6 times faster than Quad9 servers for you. But the quad9 resolvers responded just fine.

If you want to use specific resolvers, set their names in `resolver_names`.

**Comment by 480gh8q0hg08** [comment]
> Can you define "doesn't work"?
> 
> What exact log/error messages from dnscrypt-proxy do you get when `server_names` includes one of the Quad9 resolver name?

Hi I don't get an error message, but when I try to go to any websites nothing loads. I'm on Linux Mint, and I kept dnsmasq but followed the wiki and set 127.0.2.1 in network manager. 

I'm using the sources.'public-resolvers' that was included by default. Could you elaborate on where I set resolver_names? Should I have enabled the "sources.quad9-resolvers" option?

Thanks

**Comment by jedisct1** [comment]
Sorry, I was confused by AnyWAT who hijacked the thread.

After stopping the service, can you attach the output of the `dnscrypt-proxy` command? (starting it manually)

**Comment by 480gh8q0hg08** [comment]
> Sorry, I was confused by AnyWAT who hijacked the thread.
> 
> After stopping the service, can you attach the output of the `dnscrypt-proxy` command? (starting it manually)

Sure it says "[FATAL] Unable to load the configuration file [dnscrypt.proxy.toml] -- Maybe use the -config command line switch?" 

Hmmm it's strange that it says that because it seems dsncrypt is working with the toml file. When I use dnsleaktest it shows the dns servers I set the toml file to.

**Comment by jedisct1** [comment]
Do you have a `dnscrypt-proxy.toml` file in the current directory?

See the generic installation instructions for Linux here: https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux
