### ISSUE TITLE
use dnssec pihole with active dnscrypt

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#814]
I wanted to ask the community having installed and configured dnscrypt on a pihole Raspberry pizero w and using it with server_names cloudflare and dnssec active in the configuration file,

I repeat, I was wondering if the use dnssec checkbox of pihole under DNS should still be enabled or not.  or just indicate dnssec = true in the configuration file?

**Comment by jedisct1** [comment]
I would tend to say that this is useless and will only make everything slower.

**Comment by tigernero79** [comment]
Do you want to enable dnssec in pihole?
or are you referring to installing dnscrypt on pizero w and pihole?
