### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by EstherMoellman** [DNSCrypt/dnscrypt-proxy#815]
Hi! This is not an issue... is just a simple question:

Please, if possible, I want to know the pros and cons of enabling or disabling Windows' DNS Client Service, while having DNSCrypt installed (I use SimpleDNSCrypt).

I already tried to read the Wiki, as much as I can.
I also read some comments, closed issues etc.
And it is not totally clear to me the pros/cons.

I know DNSCrypt already has its own cache.
I also know Windows DNS Client Service has some potential privacy risks.
But I read lot of webpages recommending to keep Windows DNS Client Service enable because seems to deal with lot of Windows' functions.

My main focus is not privacy, but browser/system performance.
If by keeping Windows DNS Client Service enable I can achieve better browser/system performance, then I would like this option.
And vice-versa, if disabling Windows DNS Client Service will improve browser/system performance, then this will be my option.

Thank you in advance!

**Comment by brainscar** [comment]
dnscrypt-proxy has really good load balancing. Why not try both, then run a test?

**Comment by EstherMoellman** [comment]
@brainscar ,

Before asking here, your suggestion (thank you) was my first empirical test, just by trying the 2 possible combinations (DNSCrypt alone VS both services together)... and I haven't seen performance differences.

So, my first impulse was to disable DNS Client + to keep DNSCrypt alone. But I read lot of contradictory comments, docs ans explanations, many saying to disable DNS Client, and many saying that DNS Client should be always enabled (even with DNSCrypt) etc.

It would be great to have an official answer from @jedisct1

**Comment by jedisct1** [comment]
I don't think it will make any change in performance. But caching the exact same data twice, on the same machine, is just a waste of memory.
