### ISSUE TITLE
Forwarding fios-router.home to 192.168.1.1 seems not to work - did it wrong?

### ISSUE THREAD

**Issue by glnzglnz** [DNSCrypt/dnscrypt-proxy#816]
I have Simple DNSCrypt 0.6.4 (64-bit) pushing dnscrypt-proxy 2.0.22.

On every reboot of Win 10 Pro 64-bit version 1803 (home PC wired to 1Gbps FIOS gateway), I get two or three Warnings in Event Viewer with "Event 1014 DNS Client Events":

- Name resolution for the name wpad timed out after none of the configured DNS servers responded.
- Name resolution for the name _ldap._tcp.dc._msdcs.fios-router.home. timed out after none of the configured DNS servers responded.

PLEASE NOTE that the second Warning is about "fios-router.home", which is my Quantum G1100 gateway-router for my Verizon 1Gbps FIOS service.

I experimented and confirmed that there IS a relationship between dnscrypt-proxy and both Warnings above.  I first "Removed Service" using Simple DNSCrypt and rebooted, and the Warnings did NOT recur. Then I re-enabled the service and rebooted, and the Warnings occurred again.

I did some digging, and the wiki is giving me a clue for ONE of my Event 1014 Warnings - the second one about "fios-router.home", but I need your help to implement.

See the wiki about Forwarding at https://github.com/jedisct1/dnscrypt-proxy/wiki/Forwarding 

But how should i set this up for the Event 1014 Warning about
_ldap._tcp.dc._msdcs.fios-router.home ?

Should I just FORWARD that name to 192.168.1.1 (which is the router)? 
Don't I need a suffix, maybe for a port? 
Shouldn't it be to 192.168.1.1:something?  **How would I find the   :something  ?**

Thanks.

**Comment by glnzglnz** [comment]
Update - trying to follow the wiki link about Forwarding - 

(1) I put forwarding-rules.txt into the same folder as dnscrypt-proxy.toml.

(2) I added the line `forwarding_rules = "forwarding-rules.txt"` (using double-quotes not single quotes) to dnscrypt-proxy.toml right after the line `cache_neg_ttl = 60`

(3) The only line I put in  forwarding-rules.txt is `fios-router.home 192.168.1.1`

Is that correct?

**RESULTS - The above didn't work, and on reboots I continue to get the Event 1014 Warning "Name resolution for the name _ldap._tcp.dc._msdcs.fios-router.home. timed out after none of the configured DNS servers responded."**

What next?

**Comment by brainscar** [comment]
Try this:

`home 192.168.1.1`
`192.in-addr.arpa 192.168.1.1`

Or if all fails, try your Windows hosts file.
