### ISSUE TITLE
FetchCurrentDNSCryptCert does not honor proxy settings

### ISSUE THREAD

**Issue by z0w13** [DNSCrypt/dnscrypt-proxy#817]
Currently [FetchCurrentDNSCryptCert](https://github.com/jedisct1/dnscrypt-proxy/blob/0a535e28ab9c39a7123720419f35ee24f796bb4b/dnscrypt-proxy/dnscrypt_certs.go#L23) does not honor proxy settings causing it to try direct connection regardless of these settings.

It seems that miekg/dns does not currently support proxy dialers (Unless I missed that), so some changes would be required to support that as well.

**Comment by jedisct1** [comment]
Waiting for your contribution to support this :)
