### ISSUE TITLE
Little Snitch Flagging dnscrypt-proxy as being modified - Checksum mismatch

### ISSUE THREAD

**Issue by mw3demo** [DNSCrypt/dnscrypt-proxy#819]
The new version of Little Snitch have a feature that stores the checksum of programs in a database when you first allow a rule, if that checksum changes, a warning pops up. I have had numerous reboots with no warning, but had one a one a few weeks ago and uninstalled and reinstalled dnscrypt-proxy. Its been a week or so, with numerous reboots and no issues, but today the warning came up again. See attached.

Thoughts?

<img width="766" alt="Screenshot 2019-05-13 at 09 49 25" src="https://user-images.githubusercontent.com/4109485/57612836-1a020f00-7565-11e9-8048-729c8d808886.png">

**Comment by jedisct1** [comment]
dnscrypt-proxy never modifies itself. It doesn't contain any code to do so.

So, either this is a false positive, or something else changed it. Maybe Homebrew updated it.

**Comment by mw3demo** [comment]
Hey @jedisct1, 

I don't have Homebrew installed, and would also believe its a false positive. I'll further investigate by doing the checksums manually.
