### ISSUE TITLE
Why was DNSCrypt version indication removed on the dnscrypt proxy?

### ISSUE THREAD

**Issue by MystesofEternity** [DNSCrypt/dnscrypt-proxy#821]
Hi, I would like to ask why this change was implemented? I only noticed this just today after I updated to the latest version last week, where there was no more indicator of DNSCrypt version (i.e. DNSCrypt v1, DNSCrypt v2).

Personally, I think this feature must be retained for those who are looking to maximize their security and only limit themselves to DNSCrypt servers that are using the latest version of DNSCrypt.

**Comment by r4sas** [comment]
Read: https://github.com/jedisct1/dnscrypt-proxy/commit/0a535e28ab9c39a7123720419f35ee24f796bb4b

**Comment by MystesofEternity** [comment]
Ah thank you very much for that
I suppose the situation described in that page is something that can't be helped
