### ISSUE TITLE
Blacklisted entries takes too long to be resolved on Firefox

### ISSUE THREAD

**Issue by semente** [DNSCrypt/dnscrypt-proxy#822]
Blacklisted entries takes too long to be resolved on Firefox causing many pages to take more than 60 seconds to load.

For instance, if I try open an web page that on its `<head>` contains a JavaScript that loads a resource from a blacklisted domain, the page won't load until the name resolution for that resource is over. For some reason, perhaps because dnscrypt-proxy returns REFUSED instead NXDOMAIN for the blacklisted domains, Firefox wait some timeout until cancel the request.

If I try to access the blacklisted domain directly, I noticed the same issue on Firefox and also on GNOME Web Browser (epiphany), but on epiphany I couldn't reproduce the same issue when the blacklisted domain is an external resource of a page such as a JavaScript file.

I'm using dnscrypt-proxy 2.0.19.

**Comment by jedisct1** [comment]
I haven't been able to reproduce this using Firefox (assuming that you don't have anything else such as `dnsmasq` in front of `dnscrypt-proxy`).

But you can set `refused_code_in_responses = false` to return a successful but false response instead of `REFUSED`.

**Comment by semente** [comment]
No, I don't have dnsmasq in front of dnscrypt-proxy. 

Unfortunately the version I'm using (2.0.19, from Debian buster/testing) do not have the option `refused_code_in_responses`.

**Comment by semente** [comment]
Oh, man. I had this on my `resolv.conf`:

```
options edns0 single-request-reopen
```

By removing this line it seems working fine now! Got it from https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux. What it really does? Is it important?

**Comment by jedisct1** [comment]
`options edns0` alone is probably fine.

`single-request-reopen` changes the way queries for both IPv4 and IPv6 are handled, but it's not necessary at all, and is apparently a bad idea. I've removed it from the Wiki page.

Thanks!

**Comment by semente** [comment]
awesome jedisct! thank you!
