### ISSUE TITLE
Proper Syntax for IPV6 Listening configuration

### ISSUE THREAD

**Issue by mbze430** [DNSCrypt/dnscrypt-proxy#823]
I like to find out what is the proper syntax to add to here for listening on IPv6 iface

## Note: When using systemd socket activation, choose an empty set (i.e. [] )             .

listen_addresses = ['0.0.0.0:5300']

is it:         .

listen_addresses = ['0.0.0.0:5300'],['IPv6 address:port'] or ['0.0.0.0:5300,'IPv6 address:port']

or do you need a ',' (comma) or just blank space?

**Comment by r4sas** [comment]
https://github.com/jedisct1/dnscrypt-proxy/blob/0e2d78d21bd0763636fcc8ef52f79a5095d49994/dnscrypt-proxy/example-dnscrypt-proxy.toml#L36

**Comment by mbze430** [comment]
Thanks the toml sample I got didn't have that.  I might have an older version.... Maybe
