### ISSUE TITLE
How to help the project?

### ISSUE THREAD

**Issue by EncryptTown** [DNSCrypt/dnscrypt-proxy#824]
Hi @jedisct1 ,

I'd like to help your amazing project but I don't know how.
Maybe a donation?
Does the wiki need any help?

I'm running a server, but would like to do more! :)
Maybe run it on .onion too? Or is there not a lot of need for tor servers?

Any ideas are appreciated!
Thank you for your hard work. dnscrypt is awesome!!

**Comment by EncryptTown** [comment]
Or maybe another server list mirror? :smile:

**Comment by jedisct1** [comment]
What's really badly needed now is a nice graphical client for MacOS.

And maybe an equivalent to DNSCloak for Android.

It would be awesome if you could help with that!

**Comment by s-s** [comment]
> And maybe an equivalent to DNSCloak for Android.

A friend of mine is doing a port ATM.

**Comment by jedisct1** [comment]
Awesome news!

**Comment by EncryptTown** [comment]
Hi @jedisct1 , unfortunately, as much as I want to, I have no experience with MacOS.
However, if there is ever any task related to docker, the website, servers, tor, vue, etc. I'd love for you to let me know.

**Comment by ghost** [comment]
@jedisct1 
I use FLutter to make GUI's for all Desktops and Mobile.
The same code works on all the above OS's
Its very easy to link Flutter with golang also.

ONce setup and compiling and packaging, it will be very easy for you and others to extend it.
I can help you. Just contact me.
