### ISSUE TITLE
issue with ecc vpn dns quiery

### ISSUE THREAD

**Issue by absynteZero** [DNSCrypt/dnscrypt-proxy#825]
Hi,

I use openvpn and dnscrypt proxy from years and months.

I use too edit config and use them as well.

I was using dnscrypt and i just try doh.

The issue is will is use doh, the (crypto) ecc vpn dns queries aren't solved...or blocked.

Normal RSA queries are nice, only ecc.

Daemon is open in firewall, and i've already try with firewall full open..

I just try again with dnscrypt, it works...only doh.

I try so many settings, i cant fix the problem.

I use w10 x64 and dnscrypt proxy v2.22 if i remeber, the last version x64 windows.

If i edit ethernet to 9.9.9.9 all is fine, if i use dnscrypt all is fine but doh not...

I give my conf..

listen_addresses = ['127.0.0.1:53','127.0.0.1:53', '[::1]:53']

max_clients = 25

ipv4_servers = true

ipv6_servers = false

block_ipv6 = true

###########

dnscrypt_servers = false

doh_servers = true

require_dnssec = true

require_nolog = true

require_nofilter = true

################

timeout = 2500

cert_refresh_delay = 240

offline_mode = false

lb_strategy ='random'

force_tcp = false

#fallback_resolver = '0:53'

refused_code_in_responses = true

ignore_system_dns = true

netprobe_timeout = 0

################

tls_disable_session_tickets = true

tls_cipher_suite = [52393, 52392]

keepalive = 30

################

cache = false

cache_size = 512

cache_min_ttl = 600

cache_max_ttl = 86400

cache_neg_ttl = 60

################

#log_level = 0

#log_file = 'dnscrypt-proxy.log'

#log_files_max_size = 10

#log_files_max_age = 3

#log_files_max_backups = 1

#[query_log]

#file = 'query.log'

#format = 'tsv'

################

[static.'dns.oszx.co:443']
stamp = 'sdns://AgIAAAAAAAAADDUxLjM4LjgzLjE0MYAAC2Rucy5vc3p4LmNvCi9kbnMtcXVlcnk'

[static.'doh.appliedprivacy.net:443']
stamp = 'sdns://AgcAAAAAAAAAAKA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OKBoo-sB-l8CxNNfOhHQBMrwiyJL7qfXnFiMfxPIYTNgLqDvR4Wu5wydV1_nM4MG2T6nlhHl_tzvU2LdZsmLYLstvSAcVDa2UaK1QVwWz9ltGpcJ_ZyPJ-73XPlz2YL_5o5Y8BZkb2guYXBwbGllZHByaXZhY3kubmV0Bi9xdWVyeQ'

[static.'commons-host:443']
stamp= 'sdns://AgUAAAAAAAAAACA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OAxjb21tb25zLmhvc3QKL2Rucy1xdWVyeQ'

[static.'dns.sb:443']
stamp = 'sdns://AgUAAAAAAAAAACA9pLcWNKQTwc7zSqltJaQBY01M82w7Ezx0KU5I5jcBKgpkb2guZG5zLnNiCi9kbnMtcXVlcnk'

[static.'doh-blahdns-de:443']
stamp = 'sdns://AgMAAAAAAAAADjE1OS42OS4xOTguMTAxABJkb2gtZGUuYmxhaGRucy5jb20KL2Rucy1xdWVyeQ'

[static.'doh-ibksturm:443']
stamp = 'sdns://AgcAAAAAAAAAACA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBRpYmtzdHVybS5zeW5vbG9neS5tZQovZG5zLXF1ZXJ5'

#[static.'securedns-doh:443']
#stamp = 'sdns://AgcAAAAAAAAADjE0Ni4xODUuMTY3LjQzID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4EGRvaC5zZWN1cmVkbnMuZXUKL2Rucy1xdWVyeQ'

[static.'aaflalo-me:443']
stamp = 'sdns://AgMAAAAAAAAADjE3Ni41Ni4yMzYuMTc1ID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4DmRucy5hYWZsYWxvLm1lCi9kbnMtcXVlcnk'

[static.'doh-de-blahdns:443']
stamp = 'sdns://AgMAAAAAAAAADjE1OS42OS4xOTguMTAxABJkb2gtZGUuYmxhaGRucy5jb20KL2Rucy1xdWVyeQ'

[static.'powerdns-doh:443']
stamp = 'sdns://AgcAAAAAAAAAACA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBBkb2gucG93ZXJkbnMub3JnAS8'

[static.'doh-crypto-sx:443']
stamp = 'sdns://AgcAAAAAAAAADTEwNC4xOS4xOTguMjkgHdhQioxWWQQ5fHhkUeCPV2E888inI_bzef1MOFi2858NZG9oLmNyeXB0by5zeAovZG5zLXF1ZXJ5'

Thanks if you can help to run it.

Best regards

**Comment by jedisct1** [comment]
>  the (crypto) ecc vpn dns queries aren't solved

Can you clarify what this is?

The configuration you posted doesn't make much sense. Start with the default one (`dnscrypt-proxy.toml`) and change only one thing at a time. If you want to use specific servers, put their name in the `servers_list` property.
