### ISSUE TITLE
dnscrypt-proxy can't query pgp servers.

### ISSUE THREAD

**Issue by brainscar** [DNSCrypt/dnscrypt-proxy#827]
**steps to reproduce:**

- set _ignore_system_dns = true_
- import a pgp key (ie. any from https://www.archlinux.org/master-keys/) 
using:  gpg --receive-keys insert_key_here

**outcome:** 

> gpg: keyserver receive failed: Server indicated a failure

**outcome when disabling dnscrypt/changing to regular dns server:**

> gpg: Total number processed: 1
> gpg:               imported: 1

**some information about pgp key servers:**

https://roll.urown.net/server/pgp-keyserver.html

**Comment by brainscar** [comment]
Can't reproduce anymore.

Tried to capture it with wireshark. Suddenly started working... go figure.

**Comment by jedisct1** [comment]
Computers :)
