### ISSUE TITLE
Running in background sometimes get process killed on asuswrt

### ISSUE THREAD

**Issue by thuantran** [DNSCrypt/dnscrypt-proxy#83]
Hi there,

This has happened with some of my users, but somehow it happened to me today. The log at level 2 is as follows:
```
Feb  3 12:06:01 dnscrypt-proxy[1657]: Source [http://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
Feb  3 12:06:01 dnscrypt-proxy[1657]: Starting dnscrypt-proxy 2.0.0rc
Feb  3 12:06:01 dnscrypt-proxy[1657]: Now listening to 127.0.0.1:65053 [UDP]
Feb  3 12:06:01 dnscrypt-proxy[1657]: Now listening to 127.0.0.1:65053 [TCP]
Feb  3 12:06:01 dnscrypt-proxy[1657]: System DNS configuration not usable yet, exceptionally resolving [dns.google.com] using fallback resolver [8.8.8.8:53]
Feb  3 12:06:03 dnscrypt-proxy[1657]: [google] OK (DoH) - rtt: 191ms
Feb  3 12:06:03 dnscrypt-proxy[1657]: Server with the lowest initial latency: google (rtt: 191ms)
Feb  3 12:06:03 dnscrypt-proxy[1657]: dnscrypt-proxy is ready - live servers: 1
Feb  3 12:23:39 dnscrypt-proxy[1657]: Stopped.
```

The command I used to run dnscrypt-proxy is:
```nonroot nobody dnscrypt-proxy -config dnscrypt-proxy.toml > /dev/null 2>&1 &```

My users said that running using daemonize mode helped, so I have switched to that for now and monitoring. I checked your code and the message is printed from:
```
func (app *App) Stop(service service.Service) error {
	dlog.Notice("Stopped.")
	return nil
}
```
in main.go. There's nothing to go from there, any idea?

Best regards,
Thuan

**Comment by jedisct1** [comment]
> any idea?

None :(

**Comment by jedisct1** [comment]
```sh
 nonroot nobody dnscrypt-proxy -config dnscrypt-proxy.toml > /dev/null 2>&1 &
```

Try `nohup` before the command, or use a service manager such as runit.

What happened is probably just that the shell session ended, and so did your background jobs.

**Comment by thuantran** [comment]
I forgot to copy paste but I did use nohup :(

**Comment by jedisct1** [comment]
That's weird, then :(

The `stopped` message means that the process didn't crash but was cleanly stopped, at user's (or shell's) request.

**Comment by jedisct1** [comment]
The shell appears to kill it.
You should try to run it like other system services instead of the command-line.
