### ISSUE TITLE
Way to fallback to be able to open network login page on public network

### ISSUE THREAD

**Issue by slaufmann** [DNSCrypt/dnscrypt-proxy#831]
Many public network like they are present in hotels, trains, etc. use a so called "network login page" where one has to login or just acknowledge some terms of use.

I am using dnscrypt-proxy 2.0.19 on Debian 10 (buster) on a single system (laptop) and experienced that sometimes this login page can not be opened.
I suspect that this is because DNS traffic is blocked until the login process for the public network is completed. But since I had to disable the automatic DNS setup of NetworkManager in order to not override my settings to use dnscrypt-proxy i have no way to know which IP this login page would be one.

Do you have any recommendations on how to solve this?

Thank your for your efforts, i really like dnscrypt-proxy. :)

**Comment by jedisct1** [comment]
[captive-browser](https://github.com/FiloSottile/captive-browser) is a very good way to deal with these annoying captive portals in a secure way.

**Comment by slaufmann** [comment]
Thank you very much, i will give it a try.
