### ISSUE TITLE
dnscrypt-proxy AppArmor profile path edit + permissions

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#837]
Hi!

I use a AppArmor profile of dnscrypt-proxy. I edited it.

```text
#include <tunables/global>

/etc/dnscrypt-proxy/dnscrypt-proxy flags=(attach_disconnected) {
#include <abstractions/base>
#include <abstractions/nameservice>
#include <abstractions/openssl>

capability chown,
capability dac_override,
capability net_bind_service,
capability setgid,
capability setuid,
capability sys_resource,

/etc/dnscrypt-proxy.** r,
/etc/dnscrypt-proxy/dnscrypt-proxy.log* rw,
/etc/dnscrypt-proxy/public-resolvers.md* rw,
/etc/dnscrypt-proxy/public-resolvers.md.minisig* rw, ??? (or r?)

/tmp/.tmp	w,
owner /tmp/.tmp	r,

/run/systemd/notify	rw,
/lib/x86_64-linux-gnu/ld-.so	mr,
@{PROC}/sys/kernel/hostname	r,
@{PROC}/sys/net/core/somaxconn	r,
/etc/ld.so.cache r,
/usr/local/lib/{@{multiarch}/,}libldns.so	mr,
/usr/local/lib/{@{multiarch}/,}libsodium.so*	mr,
}
```

I have all files in one folder at `/etc/dnscrypt-proxy`.
Can I remove?

```text
/tmp/.tmp	w,
owner /tmp/.tmp	r,
```

Have I set the permissions correctly?

Need `public-resolvers.md.minisig` read access or read+write access?

**Comment by jedisct1** [comment]
```text
#include <abstractions/openssl>
...
/usr/local/lib/{@{multiarch}/,}libldns.so	mr,
/usr/local/lib/{@{multiarch}/,}libsodium.so*	mr,
```

dnscrypt-proxy doesn't use any of these libraries.

Where does that AppArmor profile come from?

**Comment by ghost** [comment]
From here:
https://github.com/trailofbits/algo/blob/master/roles/dns_encryption/files/apparmor.profile.dnscrypt-proxy

**Comment by ghost** [comment]
I removed now:
#include <abstractions/openssl>
...
/usr/local/lib/{@{multiarch}/,}libldns.so	mr,
/usr/local/lib/{@{multiarch}/,}libsodium.so*	mr,

Do dnscrypt-proxy use this?
  /tmp/*.tmp						w,
  owner /tmp/*.tmp					r,

Status of AppArmor:
1 processes are unconfined but have a profile 
/etc/dnscrypt-proxy/dnscrypt-proxy (45708)

I hope it is correct.

**Comment by jedisct1** [comment]
It doesn't access `/tmp/.tmp` unless there's a reference to this weird path in your configuration file.

Maybe Algo has some special configuration file that does something in `/tmp/.tmp`?

I don't know. The default configuration file doesn't.
