### ISSUE TITLE
About Windows automatically import and update the blacklist problem

### ISSUE THREAD

**Issue by ysz223** [DNSCrypt/dnscrypt-proxy#84]
Will the windows system how to use `domains-blacklist-all.conf` automatically import and automatically update to the blacklist? Thank you!

**Comment by jedisct1** [comment]
Hi,

You need Python installed on your computer to run the script.

If you use exactly the example configuration, the constantly update output can be directly downloaded here: https://download.dnscrypt.info/blacklists/domains/

But if you made changes to the rules, you need to generate the file yourself.

**Comment by ysz223** [comment]
@jedisct1 

Thank you!

After downloading mybase.txt at `https://download.dnscrypt.info/blacklists/domains/`, is not it necessary to delete `blacklist.txt` and replace it with `mybase.txt`?

Also, in `dnscrypt-proxy.toml` `# blacklist_file = 'blacklist.txt'` need to add the following line `blacklist_file = 'mybase.txt'`?

**Comment by jedisct1** [comment]
You can indeed replace

```toml
# blacklist_file = 'blacklist.txt' 
```

with

```toml
blacklist_file = 'mybase.txt'
```

If you don't change the file name. That's probably easier!

mybase is the list I use, but it's not the best. Everybody wants to allow or block different things.

**Comment by ysz223** [comment]
@jedisct1 

Thank you!

Can I manually create a list of `domains-blacklist-all.conf` inside a blacklist? Or, how do I manually add a new list?

For example, I want to add `https://easylist-downloads.adblockplus.org/easylistchina.txt` this list, how?

Or is it possible to create a gadget that allows us to generate our own personalized list as needed using this gadget?

Sorry, this is just a personal idea.

**Comment by jedisct1** [comment]
The file `domains-blacklist-local-additions.txt` is exactly designed for that purpose. You can add anything you want there, and it will be merged with other entries to build the final file.

There is also the `domains-whitelist.txt` file, that includes domains that you never want to be blocked.

**Comment by ysz223** [comment]
@jedisct1 

Can you give an example of how to use?

**Comment by ghost** [comment]
dnscrypt-proxy-win64-2.0.0rc3 / windows 7 (x64)

`domains-blacklist-local-additions.txt` and `domains-whitelist.txt` seem really pertinent. I do not localize their settings in _example-dnscrypt-proxy.toml_. Is it planned to include their settings in the config, are they usable already as such and active as soon as added in the dnscrypt-proxy folder?

**Comment by jedisct1** [comment]
Not really.

They are part of the python script, that builds one final, optimized version of the blocking rules.
