### ISSUE TITLE
Fallback resolver unreachable

### ISSUE THREAD

**Issue by NicoVarg99** [DNSCrypt/dnscrypt-proxy#840]
My network blocks regular dns requests.
When dnscrypt-proxy starts, it fails with the following error:
`Unable to use source [public-resolvers]: [No IP found for [download.dnscrypt.info]]`

Is there a way to save the public resolvers list for the next computer startup?

A quick fix is putting in /etc/hosts the line "37.59.238.213 download.dnscrypt.info" but it is not the right way to do it, as it might change in the future.

**Comment by jedisct1** [comment]
The resolvers list will be cached, but after some time, it will need to be updated.

Indeed, the IP may change in the future. DNS solves this. But if you block DNS, this is not going to work.

**Comment by NicoVarg99** [comment]
Maybe my question wasn't clear enough.
My university network blocks all dns requests and this is not in my control.
There is no way I can reach a regular dns server.

**Comment by jedisct1** [comment]
How are you accessing websites?

If this is through a proxy, you can configure it (SOCKS or HTTP proxies) in the configuration file.

**Comment by NicoVarg99** [comment]
Normally the DHCP gives you a DNS server IP (that changes over time) which is the only one not blocked.
I use the network without proxies.

In my /etc/resolv.conf i use 127.0.0.1 in order to use dnscrypt-proxy

**Comment by jedisct1** [comment]
What you can do is set `/etc/resolv.conf` to the DHCP-provided DNS resolver, start `dnscrypt-proxy` so that the resolvers list is downloaded, and then bump `refresh_delay` up in order to cache the file for a longer time than the default.

As long as your computer doesn't stay offline for more than this delay, you should be fine.
