### ISSUE TITLE
non RFC8484 parameter 'body_hash' in DoH requests

### ISSUE THREAD

**Issue by appliedprivacy** [DNSCrypt/dnscrypt-proxy#844]
dnscrypt-proxy appears to add a `body_hash` HTTP parameter to DoH queries:

https://github.com/jedisct1/dnscrypt-proxy/blob/5c9edfccfe67474bee2836ada67f955f10e43357/dnscrypt-proxy/xtransport.go#L209

Since that is not found in RFC8484 we where wondering why dnscrypt-proxy has that parameter unlike other DoH clients that don't have it.

commit: https://github.com/jedisct1/dnscrypt-proxy/commit/70bdd4642510f8903e1c1a45910a47f90436db0e

changelog says:

> https://github.com/jedisct1/dnscrypt-proxy/blob/a8045e0a7a34d358a806e0fea1a10cab315ab12a/ChangeLog#L37

Is this workaround still required?

**Comment by jedisct1** [comment]
This is required for caches and CDNs that don't use the body content in order to compute the cache key.
