### ISSUE TITLE
DNS Stamp Hashes

### ISSUE THREAD

**Issue by 2k1dmg** [DNSCrypt/dnscrypt-proxy#845]
Hello, if you can tell me where to get the hash [Hashes (comma-separated) on https://dnscrypt.info/stamps/] when creating a DNS Stamp? I want to do for "dns.google", but I don’t know where to find the hash.

**Comment by jedisct1** [comment]
Congrats for running the Google DNS resolvers!

In the public lists, the stamp for your resolvers already includes the certificate hashes.

If a `SHOW_CERTS` environment variable is defined when started dnscrypt-proxy, certificate hashes will be printed.

**Comment by 2k1dmg** [comment]
I use `cloudflare-doh` and [dns.google](https://dns.google) is DoT. Maybe `SHOW_CERTS` add in `dnscrypt-proxy.toml`?
```
[static.'cloudflare-doh']
# cloudflare-dns.com/dns-query (DoT: one.one.one.one, 1dot1dot1dot1.cloudflare-dns.com)
# dnssec/no-log/no-filter 1.0.0.1
stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjGgKSuRcnA2MM_hchL0ZJ7FEqZPzVRgCT9UlgxyXqDXa84g63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk'

[static.'cloudflare-doh-test']
# cloudflare-dns.com/dns-query (DoT: one.one.one.one, 1dot1dot1dot1.cloudflare-dns.com)
# dnssec/no-log/no-filter 1.0.0.1
stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEAEmNsb3VkZmxhcmUtZG5zLmNvbQovZG5zLXF1ZXJ5'

[static.'quad9-doh']
# dns.quad9.net/dns-query (DoT: dns.quad9.net)
# dnssec/no-log/filter 9.9.9.9
stamp = 'sdns://AgMAAAAAAAAABzkuOS45Ljmgj2gmo0sC4xnSdosccJTmAQxXC9BdHcAUWT6eFqOr5Wsg63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgNZG5zLnF1YWQ5Lm5ldAovZG5zLXF1ZXJ5'
```

**Comment by jedisct1** [comment]
You don't need to manually add these. They are already available in the public list.

For Cloudflare, use `cloudflare` or `cloudflare-ipv6` in the `servers_list`. For Google, use `google`.

**Comment by jedisct1** [comment]
You can see the list of servers here: https://dnscrypt.info/public-servers

And there are more lists: https://github.com/jedisct1/dnscrypt-proxy/wiki/DNS-server-sources

**Comment by 2k1dmg** [comment]
Thanks I know that the program automatically uses the fastest from list in `sources` or `server_names`. There is no difference between them, but I want to use my.
