### ISSUE TITLE
Problem cloaking pixabay.com?

### ISSUE THREAD

**Issue by ajp2k13** [DNSCrypt/dnscrypt-proxy#846]
I'm having trouble cloaking pixabay.com to safesearch.pixabay.com, it just returns the same IP as pixabay.com. If I set it up in Dnsmasq like this it works:

host-record=safesearch.pixabay.com,176.9.158.70
cname=pixabay.com,safesearch.pixabay.com

**Comment by ajp2k13** [comment]
Update: If I cloak it to 176.9.158.70 it works...

**Comment by jedisct1** [comment]
`safesearch.pixabay.com` and `pixabay.com` have the same set of IP address.

`safesearch.pixabay.com` used to return a different address (`176.9.158.70` indeed) until May 9th, but this is not the case any more.

**Comment by ajp2k13** [comment]
Thanks, very confusing! Don't know why they did that...

If I use the IP for cloaking it only sort of works, lots of images missing for some reason..

**Comment by jedisct1** [comment]
Since this method is still documented on their website, this is probably configuration issue on their side.

I dropped them a message on their contact page. Feel free to do the same: https://pixabay.com/service/contact/

**Comment by ajp2k13** [comment]
Thanks, will do!

On a sidenote, any idea when the next version will be released with the added logging features like cache hits etc?

**Comment by jedisct1** [comment]
Maybe tonight.

**Comment by ajp2k13** [comment]
Don't mean to rush you, just curious! :)

Thanks!
