### ISSUE TITLE
empty DoH POST requests?

### ISSUE THREAD

**Issue by appliedprivacy** [DNSCrypt/dnscrypt-proxy#848]
Due to the fact that the requests contain the `body_hash` parameter we assume we are looking at requests from dnscrypt-proxy DoH clients.
Many of them result in `400 Bad Request` and look like this:

`"POST /query?body_hash=<hash> HTTP/2.0" "-"`
(last field is the HTTP body)

Are there any cases where dnscrypt-proxy would sends such requests?

**Comment by jedisct1** [comment]
What is the hash value? If it sends an empty body, the hash can only be `cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce`

**Comment by appliedprivacy** [comment]
There are actually multiple different hashes and if that is indeed just a hash of the body than I guess nginx's `$request_body` does not contain what I think it does, since it is always "-", which I assume means "no body was in the HTTP request".

**Comment by jedisct1** [comment]
https://www.ruby-forum.com/t/how-to-log-post-body-data/235770

**Comment by appliedprivacy** [comment]
From looking at content-length they are not empty. Closing.
