### ISSUE TITLE
Update minisign public key / incorrect minisign signatures (2.0.24) ?

### ISSUE THREAD

**Issue by SilmorSenedlen** [DNSCrypt/dnscrypt-proxy#849]
Goog day
All attempts to verify signatures fault in current(2.0.24) release.
I can assume that either the key with which the signatures were created has changed, or the signatures themselves are incorrect for some reason.

> D:\Soft\Sec\dnscrypt-proxy>minisign -Vm dnscrypt-proxy-win64-2.0.24.zip
> Signature verification failed
> 
> D:\Soft\Sec\dnscrypt-proxy>minisign -Vm dnscrypt-proxy-win64-2.0.23.zip
> Signature and comment signature verified
> Trusted comment: timestamp:1556487635   file:dnscrypt-proxy-win64-2.0.23.zip

There is also a question: is it possible in any way to get the public key from signature, which was created by that key?
Did not find the answer to this question in minisign docs.

Best regards,

**Comment by jedisct1** [comment]
Thanks for reporting this and for having taken the time to check the signatures.

Not sure what happened, but I triggered a new build of the same revision, and looks like the files and signatures match now.

The signature doesn't include include the public key itself, however it contains a short key identifier, that you can also find in the public key file.

The minisign tools currently doesn't have an option to print just that identifier, but that is a trivial addition I can add.

**Comment by SilmorSenedlen** [comment]
> The minisign tools currently doesn't have an option to print just that identifier, but that is a trivial addition I can add.

Thx Frank, it would be great!


Now verifying successful, but I noticed that some signatures are missing:

dnscrypt-proxy-android_arm64-2.0.24.zip
dnscrypt-proxy-freebsd_amd64-2.0.24.tar.gz
dnscrypt-proxy-freebsd_arm-2.0.24.tar.gz
dnscrypt-proxy-freebsd_armv7-2.0.24.tar.gz 
dnscrypt-proxy-linux_mips-2.0.24.tar.gz
dnscrypt-proxy-linux_mips64le-2.0.24.tar.gz
