### ISSUE TITLE
Questions regarding public-resolvers

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#85]
Hi Frank, hi all,

Running dnscrypt-proxy-win64-2.0.0rc2 flawlessly on Win7 (x64)

1- I read in dnscrypt-proxy.toml
```
[sources.'public-resolvers']
refresh_delay = 168
```
I assume _168_ is expressed in hours, hence _7 days_.
Pros and cons when modifying this delay? I have in mind public-reolvers' list modified at the source and possibly delayed up to 6 days for the user. Any con in `setting refresh_delay = 24` for instance?

What happens when this public-resolvers list is updated? Does DNSCrypt-proxy have to be restarted?

2- Is it possible to manually update the public-resolvers list ? If so, by downloading it from http://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md but then _should public-resolvers.md.minisig_ be downloaded as well?

Thanks

**Comment by jedisct1** [comment]
Curently, the cache files are redownloaded, but in order to take advantage of new resolvers that could have appeared, the proxy needs to be restarted. This could be improved in a future version, though.

Indeed, 168 is 7 days. It sounds reasonable. Even if you have configured only 3 servers, it is very unlikely that the 3 of them will disappear or change configuration the same week. But there's nothing wrong with shortening the delay to 24 hours.

To force an update, just delete the files and restart the proxy. They will be immediately re-downloaded.

The `.minisig` files are required. These are digital signature for each file.
If a signature is missing or if is not valid for the given content, both will be deleted, as thus both re-downloaded at the next restart.

**Comment by ghost** [comment]
OK, Frank, thanks.
When you write
> To force an update, just delete the files and restart the proxy. They will be immediately re-downloaded.

I guess you mean to delete _public-resolvers.md_ & _public-resolvers.md.minisig_
I'm cautious because I don't want to break things :=)

> Curently, the cache files are redownloaded, but in order to take advantage of new resolvers that could have appeared, the proxy needs to be restarted. This could be improved in a future version, though

So one has to be aware that he should restart the proxy within a delay corresponding to the `refresh_delay`, at least for the time being.

Of course some "major" resolvers are always on the list (and it is those I use) but experience shows that some new resolvers sometimes appear and disappear shortly after. This is where having several of them is most valuable, but I have in mind a user who would happen to have chosen 1 or 2 "exotic" resolver(s) only in `server_names` and that these vanish once the list is updated and the proxy restarted : that might lead to reported false issues here...

Thanks again, Frank. Many questions, some naive, but it's the/my lot when starting new applications.

**Comment by jedisct1** [comment]
You are correct. The files to be deleted are `public-resolvers.md` and `public-resolvers.md.minisig`. Or just `*.md` and `*.md.minisig`.

You are right, 7 days may indeed a bit too long as a default. I'll shorten it to 3 days.

**Comment by ghost** [comment]
OK for the files in case of a manual list update. I got it. 
I was only wondering about the `refresh_delay`, just to know. Anyway it's easily accessible in the config.

My last question and after no more, promised!

We have,
```
[blacklist]
  ## Path to the file of blocking rules (absolute, or relative to the same directory as the executable file)
  # blacklist_file = 'blacklist.txt'
  ## Optional path to a file logging blocked queries
  # log_file = 'blocked.log'
```

```
[ip_blacklist]
  ## Path to the file of blocking rules (absolute, or relative to the same directory as the executable file)
  # blacklist_file = 'ip-blacklist.txt'
  ## Optional path to a file logging blocked queries
  # log_file = 'ip-blocked.log'

```
I understand different files for the blacklists (address and IP) but I'm surprised by having different files for the blocked queries: why isn't it possible to have one file only to log blocked addresses and IPs ? It's only logging ...

I'm finished with my questions, thanks again. :=)

**Comment by jedisct1** [comment]
Here's a simple illustration why we need two files:

```
172*
```

What would that block? All domain names starting with `172`, or all IP addresses starting with `172`?

```
cafe*
```

Block `cafepress.com` or block IPv6 addresses starting with the hexadecimal string `CAFE` ?

**Comment by ghost** [comment]
I'm not referring to the `blacklist_file`, but to the `log_file`
i understand different files required for blocking but less for logging ...

**Comment by jedisct1** [comment]
Oh, you were referring to logging, not to the rules. The logged information is not exactly the same in both cases (when an IP is blocked, we also log the corresponding name). It also makes it easier to know what blacklist triggered the block without adding yet another field to each line.
Oh, and the actual reason might be that these are two independent modules and that it made the code simpler :)

**Comment by ghost** [comment]
> Oh, you were referring to logging, not to the rules. 

Yes. I notice now I hadn't expressed myself correctly.

>  It also makes it easier to know what blacklist triggered the block without adding yet another field to each line.

True, now that I think about it ...

OK. I opened the door, feel better now without mysteries in my mind, thanks Frank and for your work and for that extra time answering to my candid questions!
I'll close the door.
