### ISSUE TITLE
Help installing dnscrypt on Archer C7 V2

### ISSUE THREAD

**Issue by 948127524** [DNSCrypt/dnscrypt-proxy#850]
Hi, I saw your post in https://github.com/dyne/dnscrypt-proxy/issues/9 
Can you tell me the process to install 2.0.4 on LibreCMC? I'm not entirely sure of the architecture and what binaries to move

**Comment by jedisct1** [comment]
This is a MIPS processor, so you should download the `linux_mips` version.
