### ISSUE TITLE
ver. 2.0.24 can't start on Win 8.1 (x64)

### ISSUE THREAD

**Issue by SilmorSenedlen** [DNSCrypt/dnscrypt-proxy#851]
Good day
After attempt to start, dnscrypt-proxy stalled, in log(0-2 severity) only such sting present:

`[2019-06-04 01:00:32] [NOTICE] Network not available yet -- waiting...`

If try(x86 and x64, binaries get after #849 was closed) to run -check, result is the same.

Reverting to version 2.0.23 resolve this issue.

**Comment by jedisct1** [comment]
Oh, fantastic. 

Can you try changing the netprobe_address and see if it helps?

**Comment by SilmorSenedlen** [comment]
Yes, if set to 0, it works.
But if value >= 1 - endless waiting.

**Comment by jedisct1** [comment]
`netprobe_address`, not the timeout.

**Comment by SilmorSenedlen** [comment]
Sorry : /

After adding **netprobe_address**(not present in my config) dnscrypt-proxy starting without problems with **netprobe_timeout** >= 1

**Comment by jedisct1** [comment]
What address did you use? The one from the example configuration (`255.255.255.0:53`)?

**Comment by mrlenxa** [comment]
I was having the same issue (only on a Windows 7 host) and I was using a copy of the example configuration which had 255.255.255.0:53 as the netprobe_address. However, it seems the only way to get the service to start is when using a netprobe_timeout value of (-1) or zero. It will not start when using a value > 0

**Comment by phonphen** [comment]
I was having the same issue on a Windows 10 x64 1903

**Comment by SilmorSenedlen** [comment]
> What address did you use?

No, my own gateway IP address. Port 53 as in example.

**Comment by jedisct1** [comment]
Can you try a different IP address than `255.255.255.0:53`? Maybe the same as the fallback resolver?

I have a Mac, I don't have Windows, so while I'm trying to do my best to make this work for Windows users, I can't test it and really need help for issues that only happen on this platform.

**Comment by jedisct1** [comment]
Ok, so the problem seems to be that Windows refuses to send packets to `255.255.255.0`. Great :(

**Comment by r4sas** [comment]
> Ok, so the problem seems to be that Windows refuses to send packets to `255.255.255.0`. Great :(

Yes, it does...

**Comment by jedisct1** [comment]
Version 2.0.25 has been tagged, and new binaries should show up soon.

Sorry for that regression :(

/cc @bitbeans
