### ISSUE TITLE
Init service stops at random on EdgeRouter X SFP

### ISSUE THREAD

**Issue by rahuljawale** [DNSCrypt/dnscrypt-proxy#852]
First of all, great work! 
But I have been having problems with getting dnscrypt-proxy 2 service to run reliably on EdgeRouter X SFP. 

The service stops at random when I use the init scripts. It sticks/starts working fine once in 5 tries and remains up and running as long as I don't fiddle with it again. But if I start the service by calling the binary `./dnscrypt-proxy` the service runs stable. 

Is there a way I can capture verbose logs of what is happening ? Also, what other information do you need to analyze the issue better, I will try to provide as much as I can.

Build / Release : 2.0.25 MIPS LE
EdgeRouter X SFP : EdgeOS 1.9.7

**Comment by jedisct1** [comment]
Maybe your system doesn't have collected enough entropy at startup time.

Try installing `rng-tools`, `haveged` or `jitterentropy`.

**Comment by rahuljawale** [comment]
Just an update, DNSCrypt-proxy appears to be running stable after upgrade
to EdgeMax 2.0.4.
