### ISSUE TITLE
refresh_delay is no longer being respected

### ISSUE THREAD

**Issue by uBlock-user** [DNSCrypt/dnscrypt-proxy#854]
dnscrypt-proxy is updating the **public-resolvers.md** and the **public-resolvers.md.minisig** on my Windows 10 device every 24 hours even though **refresh_delay** is set to 72(hours) in `dnscrypt-proxy.toml`

![](https://i.gyazo.com/2a292d53cb5ccc3a0a6778a600e47083.png)

The **Date Modified** time stamp is getting updated every 24 hours as per the above image which shouldn't happen every 24 hours but instead every 72 hours. I believe this is a regression as this didn't happen before.

**Comment by jedisct1** [comment]
I think `refresh_delay` was never implemented.

**Comment by uBlock-user** [comment]
If that's the case, then how did it work before ?  It used to work till 2.0.24, so that doesn't make sense.

**Comment by jedisct1** [comment]
Cached files were valid for 24 hours. This is a hardcoded value.

**Comment by uBlock-user** [comment]
So this is fixed now ? Which build version ?

**Comment by jedisct1** [comment]
Only partially.

**Comment by uBlock-user** [comment]
Will it still force update every 24 hours ?

**Comment by jedisct1** [comment]
There are two durations. The first one is used when the proxy starts. If the cache is fresher than it, it's not reloaded. That one should honor `refresh_delay` now, although I don't have a computer to test.

The second one is how frequently background refresh happen, so that if you stop the server and start it again the next day, the cache will still be fresh enough to avoid a reload. That one happens every 24 hour.

**Comment by uBlock-user** [comment]
> The second one is how frequently background refresh happen, so that if you stop the server and start it again the next day, the cache will still be fresh enough to avoid a reload. That one happens every 24 hour.

and that's the one which is not yet fixed because you don't have a computer to test ?

**Comment by uBlock-user** [comment]
Yesterday I removed this chunk from the config --

```
## Quad9 over DNSCrypt - https://quad9.net/

  # [sources.quad9-resolvers]
  # urls = ["https://www.quad9.net/quad9-resolvers.md"]
  # minisign_key = "RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN"
  # cache_file = "quad9-resolvers.md"
  # prefix = "quad9-"
```
and today the timestamp didn't change, so the force update didn't get fired. Weird thing, it starts with `#` so it should be ignored in the first place.

**Comment by jedisct1** [comment]
It's the other one. That one can probably stay as is.

**Comment by uBlock-user** [comment]
Well it seems as long as I don't restart the dnscrypt-service, the update doesn't happen. I will observe again and report back.

**Comment by KrasnayaPloshchad** [comment]
Thank you, I understand why `refresh_delay` doesn’t works for me.

**Comment by uBlock-user** [comment]
Well, that didn't work, so the only way to stop the updates happening every 24 hours is to hash tag out the `url` with `#`, a useable workaround. When are you going to release the partial fix build, jedisct ?

**Comment by jedisct1** [comment]
Probably not this month. The Paris Fashion Week just started and will keep me busy for the forthcoming weeks.

**Comment by uBlock-user** [comment]
One more thing, why can you not fix it fully ?

**Comment by jedisct1** [comment]
I depends on what you mean by "fix fully".

`refresh_delay` represents how old a cache file can be without being considered invalid when the proxy starts.

Preloading uses a different, internal parameter. Adding a knob for it in the configuration file is likely to cause more harm than good. Randomizing that parameter may actually be a better option.

**Comment by uBlock-user** [comment]
I meant it shouldn't download an update every 24 hours like it's doing now or after every service-restart. Can you not fix that ?

**Comment by jedisct1** [comment]
Can you explain why?

**Comment by jedisct1** [comment]
`refresh_delay` applies to `-service restart`, too.

The other delay is something internal that you shouldn't have to care about. If it's set too high, startup times will be longer and updates will happen more frequently.

**Comment by uBlock-user** [comment]
> The other delay is something internal that you shouldn't have to care about. If it's set too high, startup times will be longer and updates will happen more frequently.

That's what I don't like. Everytime I restart the service the update happens.

**Comment by jedisct1** [comment]
Using the current code after the fix?

**Comment by jedisct1** [comment]
How frequently are you restarting it? Does it happen if you restart it a couple minutes or seconds after a start?

**Comment by uBlock-user** [comment]
Ofcourse not, you haven't released the updated build of the fix yet, so will it take care of that ?

**Comment by uBlock-user** [comment]
> How frequently are you restarting it?

Every day once. 

> Does it happen if you restart it a couple minutes or seconds after a start?

It happens once after I restart the service.

**Comment by jedisct1** [comment]
Cool, then. I thought you were reporting that `refresh_delay` didn't work after it had been implemented.

**Comment by uBlock-user** [comment]
You haven't answered my questionyet . Will the update still happen after I restart the service everytime with the fixed version ?
