### ISSUE TITLE
BSD socket activation behaviour

### ISSUE THREAD

**Issue by jackivanov** [DNSCrypt/dnscrypt-proxy#855]
There is no systemd in BSDs, and It would be good if we can abstract from the OS's way of socket activation/binding to a non existent IP, and let the daemon do the work. 

FreeBSD - IP_BINDANY
OpenBSD - SO_BINDANY

**Comment by jedisct1** [comment]
Do you know how to achieve that in Go?

I don't see any ways to set socket options before `bind(2)` is called.

**Comment by jackivanov** [comment]
I'm not very good at golang, but I guess we need to make a syscall. Here is an example for linux:
`syscall.SetsockoptInt(fileDescriptor, syscall.SOL_IP, syscall. IP_FREEBIND, 1)`
and `fileDescriptor` can be gathered from `listenerUDP`

**Comment by jackivanov** [comment]
@jedisct1 In any case, I may try that out and send a PR

**Comment by jedisct1** [comment]
Syscalls can be made, but once we get `listenerUDP`, the `bind(2)` call was already made, so it's too late.

It would be wonderful if you could help :)

**Comment by jedisct1** [comment]
Here's how it might be possible to do it, thanks to @rs:

https://gist.github.com/rs/06f481daa37773afd677595f8450dfaf
