### ISSUE TITLE
Domain exists:  probably not, or blocked by the proxy

### ISSUE THREAD

**Issue by ninhhv** [DNSCrypt/dnscrypt-proxy#858]
When I do command "sudo ./dnscrypt-proxy -resolve google.com" on local of dnscrypt-proxy server, i see output:

Resolving [google.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -

Help me, please!

**Comment by r4sas** [comment]
Please, firstly read the wiki carefully.
https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation#setting-up-dnscrypt-proxy-general-guidelines

And then provide full information about configuration and how it started.
