### ISSUE TITLE
dnscrypt-proxy v.2.0.25 crashes with pihole and pizero w

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#859]
it is from version 2.0.22 up to 2.0.25 that I am testing excellent dnscryp-proxy service, calling it locally on port 127.0.0.54 in pihole latest release 4.3.1 installed on a raspberry pi zero w

works fine but during the day I am forced to restart the pizero w when the internet connection fails.

I sent for a pi3b a + hoping that a more powerful CPU could solve my problem.

but I wonder why it crashes?

the dnscrypt service is also limited, but sometimes there is a point where not so much pihole crashes but dnscrypt service no longer handles dns calls.

I set cloudflare as a solver and dnssec true in the configuration file

**Comment by jedisct1** [comment]
Maybe it's running out of memory? The system logs may provide some information.

Also you can try dnscrypt instead of doh, it may be more stable.

**Comment by tigernero79** [comment]
no, it doesn't run out of memory because I access pihole quietly, it's the dnscrypt-proxy that goes stalled.

you told me to try dnscrypt and no dncrypt-proxy,

would it be dot instead of doh?

where do I find the file that works with pihole? so how do i do with dnscrypt-proxy?

I used your guide to pihole,

https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0

which runs on pizero w which has 512mb of ram

and that's fine if it weren't for dnscrypt-proxy to be installed and sometimes 
I have to start the service restart command from the terminal

**Comment by tigernero79** [comment]
there was this guide what do you think?

https://docs.pi-hole.net/guides/dns-over-https/

**Comment by jedisct1** [comment]
Is it stalling or crashing?

What are you seeing in system logs and in the dnscrypt-proxy logs?

If it is crashing, what happens if you run it from the command line? Do you see a stack trace when it crashes?

If it is stalling and not crashing, if you enable the query log, do you still see client queries? With what return code?

Sorry, I don't use Pi-Hole. The only thing I contributed to the guide you reference to is mention the `-resolve` command at the end.

**Comment by tigernero79** [comment]
then as soon as it crashes again I will give 

./dnscrypt-proxy command -resolve www.google.it 

and I'll see that it comes back as an answer. 

 in practice dnscrypt does not block but does not resolve the calls.  

I set up cloudflare with dnssec true

**Comment by tigernero79** [comment]
in truth I could see that if I enable on pi hole dnscrypt-proxy on port 54 in localhost, 127.0.0.1 # 54.

 it is all the pizero w that goes in block, if pi hole I remove the call to dnscrypt it does not stop. so something blocks more hole i guess

**Comment by tigernero79** [comment]
@jedisct1 I noticed that the pizero w with Pi hole crashes only if I set a single dnscrypt in my cloudflare case. Example 
`server_names = ['cloudflare'] `
In file dnscrypt-proxy.toml
  if I leave dnscrypt-proxy free to choose the DNS provider alone about 39 if I am not mistaken Pi I hope and with Pi Jole it works of the big one and does not get stuck.  can it be 1.1.1.1 of cloudflare which makes crashsre dnscrypt and Pi hole?

**Comment by jedisct1** [comment]
What is the stack trace displayed on the console when it crashes?

**Comment by tigernero79** [comment]
@jedisct1 
unfortunately when I set as cloud name only cloudflare, the pi zero w was totally blocked and did not even give me access to the terminal.

only thing I noticed sometimes putting cloudflare as the only dnscrypt server that didn't communicate well because when I launched the command

`sudo journalctl -u dnscrypt-proxy -f`

I noticed a string of 24-digit strings around AAABB perhaps inherent to encrypted communication

I stopped working and restarted and everything was fine until the new block

**Comment by jedisct1** [comment]
Maybe try a different power supply. The Raspberry Pi needs a good stable power supply, and the computations required when DoH connections are established may cause instability.

**Comment by tigernero79** [comment]
@jedisct1 
I use a 5v 3a I think well enough however I have 2 days that I have not set the server name, let dnscrypt-proxy use the faster one and it has not been blocked anymore.

I believe it is cloudflare the problem, because 1.1.1.1 gives problems while 1.0.0.1 does not.

I don't know how you can communicate your dnscrypt with the server name, but with cloudflare something is not right in my humble opinion.

if it had been a power supply, even if no server name was set, it would have to be blocked instead of working well.

**Comment by tigernero79** [comment]
I put cloudflare back as a server name and I will make screenshots of the error that you only set

**Comment by jedisct1** [comment]
Also, the config file has this section:

```toml
## On non-Intel CPUs such as MIPS routers and ARM systems (Android, Raspberry Pi...),
## the following suite improves performance.
## ...
# tls_cipher_suite = [52392, 49199]
```

You can uncomment this.

**Comment by tigernero79** [comment]
Ok thanks i try

**Comment by tigernero79** [comment]
@jedisct1 I uncommented that entry and I'll let you know if it crashes.

about that string I was telling you about I made you a screenshot and I put you in precise error code.

can it be why it crashes with just the cloudflare?

or is it normal?

` 22 22:45:45 Pi_Raspy dnscrypt-proxy[315]: [2019-06-22 22:45:45] [ERROR] Get                                                                    https://dns.cloudflare.com/dns-query?ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAA                                                                   AAA: net/http: request canceled while waiting for connection (Client.Timeout exc                                                                   eeded while awaiting headers)
`
![Immagine](https://user-images.githubusercontent.com/35575744/59968798-ec36bf80-953f-11e9-93dd-9e2c17536b9c.png)

however I will see after a uncomment if it stops.

but that strange voice he refers to?
dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAA                                                                   AAA: net/http: request

**Comment by tigernero79** [comment]
so I gave a nice one

` sudo ./dnscrypt-proxy -service restart`

and I got this

![Immagine](https://user-images.githubusercontent.com/35575744/59968838-dd044180-9540-11e9-996c-acadcdec845b.png)

**Comment by jedisct1** [comment]
There is no crash here.

Connecting to Cloudflare was very slow, and it eventually timed out. If you enable other servers,  servers that respond faster will be used instead.

You don't even need to enable all of them. Enable them all first, then look at the latencies when the proxy starts to see which ones would be good for you.

**Comment by tigernero79** [comment]
however after the modification you suggested seems to be going ok.  otherwise it will not set any same server, leaving dnscrypt to choose the fastest server.  for now everything is ok.  thanks I close the post.
