### ISSUE TITLE
Domain exists: probably not, or blocked by the proxy - pihole

### ISSUE THREAD

**Issue by modem7** [DNSCrypt/dnscrypt-proxy#860]
Same as  #858,

```
./dnscrypt-proxy -resolve google.com
Resolving [google.com]

Domain exists:  probably not, or blocked by the proxy
Canonical name: -
IP addresses:   -
TXT records:    -
```

Running it in conjunction with pihole on an rpi3. Installed using: https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0 as a guide

```

server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']

## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.
## Note: When using systemd socket activation, choose an empty set (i.e. [] ).

listen_addresses = ['127.0.0.1:5353', '[::1]:5353']
```

```
sudo ./dnscrypt-proxy -list
[2019-06-17 18:34:05] [NOTICE] Network connectivity detected
[2019-06-17 18:34:05] [NOTICE] Source [public-resolvers.md] loaded
cloudflare
scaleway-fr
google
yandex
```

```
sudo ./dnscrypt-proxy -check
[2019-06-17 18:33:55] [NOTICE] Network connectivity detected
[2019-06-17 18:33:55] [NOTICE] Source [public-resolvers.md] loaded
[2019-06-17 18:33:55] [NOTICE] Configuration successfully checked
```

If I enable dnscrypt as the upstream resolver, I get the above error, if I enable pihole w/ cloudfare as the upstream, I get the following:

```
./dnscrypt-proxy -resolve google.com
Resolving [google.com]

Domain exists:  yes, 4 name servers found
Canonical name: google.com.
IP addresses:   216.58.204.46, 2a00:1450:4009:811::200e
TXT records:    v=spf1 include:_spf.google.com ~all docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e facebook-domain-verification=22rm551cu4k0ab0bxsw536tlds4h95 globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8=
Resolver IP:    162.158.33.10
```

Please let me know if there are any other config listings I need to post! Thanks!

**Comment by TraderStf** [comment]
With 2.0.25, don't get this kind of report, [Notice]s are missing.

```
./dnscrypt-proxy -list
ads-securedns-ipv6-doh
```
Correct, only one 'server_names',' IP4/IP6_serverS' true.

```
./dnscrypt-proxy -check
```
Returns nothing, just get a new prompt.

```
./dnscrypt-proxy -resolve google.com
-cut-
Resolver IP:    37.139.9.35 (dns2.securedns.eu.)
```
Is similar; ok.

**Comment by TraderStf** [comment]
Could it be this commented setting?
```
## HTTP/HTTPS proxy only for DoH servers
# http_proxy = "http://127.0.0.1:8888"
```

**Comment by modem7** [comment]
Hmmm, attempted to uncomment that, and restart the service, but still no go. 

My conf:
http://paste.debian.net/1088224/

I'm sure this is an ID10T issue on my end.

Edit: 
sudo /opt/Dnscrypt-proxy/dnscrypt-proxy -version
2.0.25

**Comment by TraderStf** [comment]
I saw on the doc:
- you have to change, port, your port is 5353 but not these 2 in your .toml, specially the second one, I don't know if it's required too.
```
fallback_resolver = '9.9.9.9:53'
netprobe_address = "9.9.9.9:53"
```
- the doc, he sets dnssec to true, I don't know if there is a reason, or just an example for the explanations.
```
require_dnssec = false
```

Try to change the 2x53 into 2x5353

**Comment by modem7** [comment]
But 9.9.9.9 is for quadnine, not for internal, so it wouldn't be listening on 5353 at their end.

## Address and port to try initializing a connection to, just to check
## if the network is up. It can be any address and any port, even if
## there is nothing answering these on the other side. Just don't use
## a local address, as the goal is to check for Internet connectivity. 


Also just checked to see if it was listening and it certainly is: 

dnscrypt- 8117     user    5u  IPv4 5039668      0t0  TCP 127.0.0.1:54 (LISTEN)
dnscrypt- 8117     user    7u  IPv6 5039670      0t0  TCP [::1]:54 (LISTEN)

**Comment by modem7** [comment]
OK, this has been resolved. 

It seems I was running both the installed service and the /opt/ service. 

I stopped the opt service, restarted the installed service, and all seems to be working as expected.
