### ISSUE TITLE
Can dnscrypt-proxy run on the not-rooted Android?

### ISSUE THREAD

**Issue by majiayeah** [DNSCrypt/dnscrypt-proxy#865]
Hi all,

Can dnscrypt-proxy run on the not-rooted Android?

I just downloaded the files in released page, put it in the internal storage of Termux, and run it in Termux on a **not-rooted** Android phone, then failed.

```sh
./dnscrypt-proxy
Termux outputs: Permission denied.
```

I have read all wiki and issues, including Thread 41, and could not find any explicit instruction that whether 
 dnscrypt-proxy can run on the not-rooted Android or not? If yes, how? 

Could anyone help me?

**Comment by r4sas** [comment]
It can be started, but not on default 53 port.

**Comment by majiayeah** [comment]
I have modified the config file to listen 127.0.0.1:5353, 
but still got permission denied.

How to start it in Termux on not-rooted phone, please?

**Comment by majiayeah** [comment]
> It can be started, but not on default 53 port.

I have modified the config file to listen 127.0.0.1:5353,
but still got permission denied.

How to start it in Termux on not-rooted phone, please?

**Comment by r4sas** [comment]
> How to start it in Termux on not-rooted phone, please?

Anyway, if you can start it, you will not be able to use it because system will continue usage of standart DNS server.

Why you got "permission denied" is not known. Re-check your files access rigths.
