### ISSUE TITLE
Add my new private unlimited bandwidth dnscrypt server to server list.

### ISSUE THREAD

**Issue by Ammykm** [DNSCrypt/dnscrypt-proxy#869]
Hello,
Wonderfull project by the way.

I would like o add my private dns server ( dnscrypt ) to public server with server name and stamps also i would like to ask if i purchase a domain name ( dnscrypt.co.uk ) and point it to dnscrypt domain name and activate ipv6 and ipv4 ( my vps have both ). I really would like to setup a server like this one https://dnscrypt.nl and share it with world i managed to use your docker server on Vultr but couldn't use my stamps as its not added to public server.md yet 

much appreciate the guide.

PS- once i get the detailed about how to setup the server including pointing domain name and activate ipv6 on dnscrypt server i lunch the server and send you the detailes like this one 

FEATURES
DNSSEC validation for better security
Caching
No logs
ED25519 and ED448 algorithm support
Query prefetching to reduce latency
Query minimization for improved privacy
No forwarding to external/upstream DNS servers
Daily certificate rotation for forward secrecy
Supporting the latest DNSCrypt protocol
Unbound DNS resolver
Pi-hole compatible

and this too.
Server name xxx
Provider name xxx
FQDN xxx
IPv4 address xxx
IPv6 address xxx
Port 443
Thanks a lots 
/Ammy

**Comment by jedisct1** [comment]
Hi Ammy,

Your server addition would be very welcome!

All that is needed is a description, and the stamps. 

Then you can submit a pull request here: https://github.com/DNSCrypt/dnscrypt-resolvers or just open an issue with the details and I'll take care of adding it.

**Comment by Ammykm** [comment]
Thanks for the reply,

Details will be provided soon as im going to upgrade my server ram and cpu.
i want to buy a domain name dnscrypt.co.uk to mach the server name in UK and how to point it to my ip address that is will dnscrypt server main dns. as i describe above, And what about the IPV6 as my vps have it. i deploy dnscrypt server before but it doesn't shows ipv6 and now i want to have both in the server. what to do?
many thanks again.

**Comment by Ammykm** [comment]
Hello, 
This my Details for the UK DNSCRYPT server.
Stamp for dnscrypt-proxy 2.x:

Server name :- dnscrypt.co.uk
Provider name :- 2.dnscrypt-cert.dnscrypt.co.uk
FQDN :- dnscrypt.co.uk >> coming soon 💯 
IPv4 address :- 178.159.10.115
IPV6= 2a01:a500:375:0001:0000:0000:39a7:f5e6

-------------------------------- -------------------------------------------------------  sdns://AQcAAAAAAAAAEjE3OC4xNTkuMTAuMTE1OjQ0MyDRBy6TkwUZoKbHspdDR6U5kBcz2kDKXrSkvxcZMX4EtB4yLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQuY28udWs
---------------------------------------------------------------------------------------
DNSCrypt server resolver hosted in London. 
DNSSEC validation for better security, Caching, Non-logging, IPV6 Support. Fast and secure.

ps> this server is Unlimited bandwidth 🥇 
if you need and more info please type here .
//Ammy
