### ISSUE TITLE
about forward configuration

### ISSUE THREAD

**Issue by CNMan** [DNSCrypt/dnscrypt-proxy#87]
i want to use domain names in https://github.com/felixonmars/dnsmasq-china-list/blob/master/accelerated-domains.china.conf as forwarding rules,can i config a public forward server address and keep only domain names in forwarding-rules.txt?

thanks.

**Comment by jedisct1** [comment]
Hi!

You need to give the IP for every entry. That list can be easily converted with
```sh
sed -e 's|/| |g' -e 's|^server= ||'
```

though.

**Comment by CNMan** [comment]
@jedisct1 thanks
