### ISSUE TITLE
How to add dnscrypt server to server list? 

### ISSUE THREAD

**Issue by Ammykm** [DNSCrypt/dnscrypt-proxy#870]
Hello,
This my Details for the UK DNSCRYPT server.
Stamp for dnscrypt-proxy 2.x:

Server name :- dnscrypt.co.uk
Provider name :- 2.dnscrypt-cert.dnscrypt.co.uk
FQDN :- dnscrypt.co.uk >> coming soon 💯
IPv4 address :- 178.159.10.115
IPV6= 2a01:a500:375:0001:0000:0000:39a7:f5e6

-------------------------------- ------------------------------------------------------- sdns://AQcAAAAAAAAAEjE3OC4xNTkuMTAuMTE1OjQ0MyDRBy6TkwUZoKbHspdDR6U5kBcz2kDKXrSkvxcZMX4EtB4yLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQuY28udWs
DNSCrypt server resolver hosted in London.
DNSSEC validation for better security, Caching, Non-logging, IPV6 Support. Fast and secure.

ps> this server is Unlimited bandwidth 🥇
if you need and more info please type here .
//Ammy

**Comment by jedisct1** [comment]
Hi Ammy,

Looks like the dnscrypt-wrapper proxy works, but the resolver itself doesn't return anything.

Can you take a look?

**Comment by Ammykm** [comment]
Hi.
What resolver?
and what do you need me to do? 
I used your docker on vultr to build it that's all, is thers anything i can do more?
:)

**Comment by jedisct1** [comment]
May it be a firewall issue?

If you are using this image, the resolver is unbound.

Are you able to use it with this configuration?

**Comment by Ammykm** [comment]
I can.t use it

**Comment by jedisct1** [comment]
:(

**Comment by Ammykm** [comment]
That's why i need your help

**Comment by Ammykm** [comment]
how to modify unbound, i can't find it? please little bit help with this

**Comment by jedisct1** [comment]
Can you try the instructions here? https://github.com/jedisct1/dnscrypt-proxy/wiki/Manually-updating-your-DNSCrypt-server

**Comment by Ammykm** [comment]
I did trying the instructions , what now?

**Comment by Ammykm** [comment]
Congratulations! The container has been properly initialized.
Take a look up above at the way dnscrypt-proxy has to be configured in order
to connect to your resolver. Then, start the container with the default command.
Starting DNSCrypt service for provider:
2.dnscrypt-cert.dnscrypt.co.uk
Starting pre-service scripts in /etc/runit_init.d
Generate crypt key pair... ok.
Secret key stored in /opt/dnscrypt-wrapper/etc/keys/short-term/1561824553.key
[53] 29 Jun 16:09:13.198 [notice] [main.c:673] Generating pre-signed certificate.
[53] 29 Jun 16:09:13.198 [notice] [main.c:680] TXT record for signed-certificate:
* Record for nsd:
[53] 29 Jun 16:09:13.198 [notice] [main.c:695] Certificate stored in /opt/dnscrypt-wrapper/etc/keys/short-term/1561824553.c      ert.
2.dnscrypt-cert 86400   IN      TXT     "DNSC\000\002\000\000\189|\019M>\185\166\189U\142/b\008\154\147\231\218cg\220\246\1      67N\180rL\2420\031\012\150\174\150\156\148\252do\024\134\217YG\204pS\145\1920B\195\029\127x\145\092m\029\001~\203T\021\002'      ;\203\155\156\228\146\030\153\195\135{1]2\137Q\031\187\134\020\224\255R\235\173A\014e+\0019(;\203\155\156\228\146\030]\023\      141)]\023\141)]\024\222\169"

* Record for tinydns:
'2.dnscrypt-cert:DNSC\000\002\000\000\275|\023M\076\271\246\275U\216/b\010\232\223\347\332cg\334\366\247N\264rL\3620\037\01      4\226\256\226\234\224\374do\030\206\331YG\314pS\221\3000B\303\035\177x\221\134m\035\001~\313T\025\002';\313\233\234\344\222      \036\231\303\207{1]2\211Q\037\273\206\024\340\377R\353\255A\016e+\0019(;\313\233\234\344\222\036]\027\215)]\027\215)]\030\3      36\251:86400

setup in directory /opt/unbound/etc/unbound
generating unbound_server.key
Generating RSA private key, 3072 bit long modulus (2 primes)
.................................++++
..........................++++
e is 65537 (0x010001)
generating unbound_control.key
Generating RSA private key, 3072 bit long modulus (2 primes)
...........................................................................................................................      ........................................................++++
...........................................................................................++++
e is 65537 (0x010001)
create unbound_server.pem (self signed certificate)
create unbound_control.pem (signed client certificate)
Signature ok
subject=CN = unbound-control
Getting CA Private Key
Setup success. Certificates created. Enable in unbound.conf file to use
./run: line 102: /proc/sys/vm/drop_caches: Read-only file system
Error: error sending query: Could not send or receive, because of network error
Error: error sending query: Could not send or receive, because of network error
timeout: run: unbound: (pid 31) 315s
./run: line 102: /proc/sys/vm/drop_caches: Read-only file system
Error: error sending query: Could not send or receive, because of network error
Error: error sending query: Could not send or receive, because of network error
kill: run: unbound: (pid 84) 15s
./run: line 102: /proc/sys/vm/drop_caches: Read-only file system
ok: run: dnscrypt-wrapper: (pid 32) 362s

**Comment by Ammykm** [comment]
still error if you check in the end and i can't find unbound.

**Comment by jedisct1** [comment]
I bought a Vultr instance to try to see what was wrong. Following the instructions reproduced the issue you were seeing. Everything starts, but Unbound can't send anything.

Looks like this is a firewall issue. I never use CentOS (as recommended by the guide), so I don't know if this is a new issue in CentOS, or something specific to Vultr, but anyway, I did the following and everything started to work.

Edit `/etc/sysconfig/iptables` and replace its content with the one from [`that file`](https://gist.githubusercontent.com/jedisct1/ee059b8ad2b84e404e639738c4c9eaa6/raw/b31ddba9dbf0c7fd8ec6299c858614d8d24776b1/iptables).

Then, type: `systemctl reload iptables`

And everything should start working :)

I updated the guide with these instructions. Hopefully this will work for you, too.

**Comment by Ammykm** [comment]
Thanks for the reply.
I delete my instance and will buy another one with scale way and see how it works
Thanks

**Comment by Ammykm** [comment]
installed,
how to add server name if you  still didn't updated mine in server list. or should i use only my stamps to check if its work or not

**Comment by Ammykm** [comment]
Stamp for dnscrypt-proxy 2.x:
  ```sdns://AQcAAAAAAAAAEDE3OC4xNTkuMi43MDo0NDMgGBJx_uhd4uH8S7ewYLY9omhAKCHwwI9pXHWm7l_B8OEfMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNvLW5zMA```

**Comment by Ammykm** [comment]
error on my another server, just tried to install and test dnscrypt
```
./dnscrypt-proxy -service install
./dnscrypt-proxy: line 30: server_names: command not found
./dnscrypt-proxy: line 36: listen_addresses: command not found
./dnscrypt-proxy: line 41: max_clients: command not found
./dnscrypt-proxy: line 55: ipv4_servers: command not found
./dnscrypt-proxy: line 58: ipv6_servers: command not found
./dnscrypt-proxy: line 61: dnscrypt_servers: command not found
./dnscrypt-proxy: line 64: doh_servers: command not found
./dnscrypt-proxy: line 70: require_dnssec: command not found
./dnscrypt-proxy: line 73: require_nolog: command not found
./dnscrypt-proxy: line 76: require_nofilter: command not found
./dnscrypt-proxy: line 79: disabled_server_names: command not found
./dnscrypt-proxy: line 88: force_tcp: command not found
timeout: invalid time interval ‘=’
Try 'timeout --help' for more information.
./dnscrypt-proxy: line 111: keepalive: command not found
./dnscrypt-proxy: line 118: refused_code_in_responses: command not found
./dnscrypt-proxy: line 148: cert_refresh_delay: command not found
./dnscrypt-proxy: line 193: fallback_resolver: command not found
./dnscrypt-proxy: line 199: ignore_system_dns: command not found
./dnscrypt-proxy: line 209: netprobe_timeout: command not found
./dnscrypt-proxy: line 220: netprobe_address: command not found
./dnscrypt-proxy: line 233: log_files_max_size: command not found
./dnscrypt-proxy: line 236: log_files_max_age: command not found
./dnscrypt-proxy: line 239: log_files_max_backups: command not found
./dnscrypt-proxy: line 253: block_ipv6: command not found
./dnscrypt-proxy: line 291: cache: command not found
./dnscrypt-proxy: line 296: cache_size: command not found
./dnscrypt-proxy: line 301: cache_min_ttl: command not found
./dnscrypt-proxy: line 306: cache_max_ttl: command not found
./dnscrypt-proxy: line 311: cache_neg_min_ttl: command not found
./dnscrypt-proxy: line 316: cache_neg_max_ttl: command not found
./dnscrypt-proxy: line 326: [query_log]: command not found
./dnscrypt-proxy: line 335: format: command not found
./dnscrypt-proxy: line 352: [nx_log]: command not found
./dnscrypt-proxy: line 361: format: command not found
./dnscrypt-proxy: line 382: [blacklist]: command not found
./dnscrypt-proxy: line 410: [ip_blacklist]: command not found
./dnscrypt-proxy: line 438: [whitelist]: command not found
./dnscrypt-proxy: line 472: [schedules]: command not found
./dnscrypt-proxy: line 511: [sources]: command not found
./dnscrypt-proxy: line 515: [sources.public-resolvers]: command not found
./dnscrypt-proxy: line 516: urls: command not found
./dnscrypt-proxy: line 517: cache_file: command not found
./dnscrypt-proxy: line 518: minisign_key: command not found
./dnscrypt-proxy: line 519: refresh_delay: command not found
./dnscrypt-proxy: line 520: prefix: command not found
./dnscrypt-proxy: line 544: [static]: command not found
./dnscrypt-proxy: line 546: [static.dnscrypt.co-ns0]: command not found
./dnscrypt-proxy: line 547: stamp: command not found
```

**Comment by jedisct1** [comment]
Meanwhile, I was trying to understand how to install it on Vultr.

If you still have the Vultr instance, can you try to run the following script? https://gist.githubusercontent.com/jedisct1/b8393a058ba3cfc1335379c4ac41969f/raw/9600ddbc354992b3e988d0f14f12e9983ab102c4/centos5-docker-dnscrypt-server.sh

**Comment by jedisct1** [comment]
You can also use it as an install script. I updated the instructions here: https://github.com/jedisct1/dnscrypt-proxy/wiki/DNSCrypt-server-with-vultr.com

And verified that they work on a new as well as on an existing Vultr instance.

**Comment by Ammykm** [comment]
I have VPS with quickhostuk, I’ll try to install it using your script you provided and I’ll install DNSCRYPT V2 on another VPS and use the stamp that generated on the VPS CentOS, is that all? Still how can I use my own server name in server name toml file of DNSCrypt V2 using my own DNSCrypt in that shows on dns leak test.
Thank you for the effort you make to make the dns more secure, don’t know how to repay you 
Thanks

**Comment by jedisct1** [comment]
The script starts with:

```sh
SERVER="$(hostname)"
```

You can replace this with:

```sh
SERVER="your host name"
```

**Comment by Ammykm** [comment]
You mean replace it in toml file 
My server name for example “ DNSCrypt.co-uk , that I will add it in server name instead of , Cloudflare, google etc 
And I’ll add it to static “ deleting google and replace DNSCrypt.co-uk and I’ll put the stamp that I generated in VPS CentOS 
If I got it right?

**Comment by jedisct1** [comment]
Test is as a static server, and if it works, it can be added with any name tou want (as long as it is unique) in the `public-resolvers.md` file.

**Comment by Ammykm** [comment]
Ok will test it as static without adding anything, and see if it’s work. 
After that can I do it by myself I mean add the server name into public-resolver.md file 
Of course I’ll check to be unique name.
Or should I contact you to add the server name ?

**Comment by Ammykm** [comment]
Last question.

Let’s I setup CentOS 7 and install docker and then start docker and after that I run you bash scripts that you provided me earlier ( Vultr scripts ) and then I stamp and cert , public key “ everything have generated “ on the VPS . How to rest it and see The DNSCrypt-server is working and nothing wrong with resolver before I use it on another VPs
Thanks again

**Comment by Ammykm** [comment]
Hello,
How to test the server if its working or not. I used your latest script you provided yesterday . and wanna test it but how?

Generate provider key pair... ok.
Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAEDE3OC4xNTkuMi43MDo0NDMgvMqXpsXJwIu4SwfwJznbNGyHGHuGxHFPHap                               gvWxna9AfMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LnVrLW5zMA

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=BCCA:97A6:C5C9:C08B:B84B:07F0:2739:DB34:6C87:187                               B:86C4:714F:1DAA:60BD:6C67:6BD0
                 --resolver-address=178.159.2.70:443
                 --provider-name=2.dnscrypt-cert.dnscrypt.uk-ns0
Keys are stored in public.key & secret.key.

**Comment by Ammykm** [comment]
Hello,
I tired this one on scaleway .

Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAEDEwLjE4LjE1MC4yNTo0NDMgMQ5gio0GwQV2eHdV59Sq7ztdQxaqcqn3r3XyQkfmfjUfMi5kbnNjcnlwdC1jZXJ0LnNydi5kbnNjcnlwdC5ubA

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=310E:608A:8D06:C105:7678:7755:E7D4:AAEF:3B5D:4316:AA72:A9F7:AF75:F242:47E6:7E35
                 --resolver-address=10.18.150.25:443
                 --provider-name=2.dnscrypt-cert.srv.dnscrypt.nl
Keys are stored in public.key & secret.key.

**Comment by Ammykm** [comment]
I think this working , but i don't how Lol
Can you test it, and im using private IP , as your script picked it up
