### ISSUE TITLE
Dnscrypt new server in Amsterdam shows ips from Finland in dns leak test

### ISSUE THREAD

**Issue by Ammykm** [DNSCrypt/dnscrypt-proxy#871]
Hello, 

I used this instructions on Scaleway this time https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes
and when i installed DNScrypt proxy 2 on linux MX to test my sdns stamp and server name details below , it gave me ips from Finland instead Amsterdam. Please check below the details 
 stamp and server name.

--resolver-address=51.15.44.12:443
--provider-name=2.dnscrypt-cert.srv.dnscrypt.nl
 sdns://AQcAAAAAAAAADzUxLjE1LjQ0LjEyOjQ0MyBc-grZgMnMQqvM7afMn4gzXHy1e5LdsNWP3mQLU20FxB8yLmRuc2NyeXB0LWNlcnQuc3J2LmRuc2NyeXB0Lm5s

Any tips or maybe troubleshooting please
Thanks

**Comment by jedisct1** [comment]
Hi Ammy,

This IP address is in Amsterdam.

`dnsleaktest` may be using an outdated geo IP database.

**Comment by Ammykm** [comment]
Hi,

And what to do, 
Can you please tell me how to test the server before setting up DNSCrypt proxy 2 on another server 
Like I want to test my server ( DNSCrypt server ) before testing it to see if it’s work 
That will give me time to troubleshoot before I contact you ( both of us saving time ;) ) and good to know to test it as there is no YouTube video explain how to do that and the only video on YouTube is How to install DNSCrypt proxy 2 on Linux using other resolver and I wan to test mine. 
Thanks for the reply

**Comment by Ammykm** [comment]
Working .
Yay. I’ll give you the details of the server later on so you can add the server if you want to resolver md list so people can use it 
:) thanks 
Have a nice day tho
