### ISSUE TITLE
dnscrypt.ca Hosting Issues (Resolver List Update Request)

### ISSUE THREAD

**Issue by dnscrypt-ca** [DNSCrypt/dnscrypt-proxy#872]
I am having some billing issues with my hosting provider.  The servers are currently up but in order to minimize possible downtime for users, could you please comment out or remove all four entries for dnscrypt.ca?

If all goes well I will hopefully have the same stamps reinstated soon.

s.

**Comment by Ammykm** [comment]
Hello,

Can please post your installation for DNSCrypt server IPV6 here.
As I saw in your website that you managed to install 4 ip’s 2 ipv4 and 2 ipv6 one same cert. 
hope you can help me out with this as I want to share my server here too with world 
Much appreciated 
Ammy

**Comment by dnscrypt-ca** [comment]
Hi Ammykm,

I see in one of the issues you opened that you are using the docker image.  I have never seen or tried the docker image.  I use Unbound and [dnscrypt-wrapper](https://github.com/Cofyc/dnscrypt-wrapper) on my servers with somewhat custom scripts for key rotation, so my help may be limited.

Having said that, here is probably not the best place for that.  You're welcome to contact me via the dnscrypt.ca web site if you like and I'll help however I can.

s.

**Comment by ibksturm** [comment]
hi @Ammykm 

you could also take a look on my dnscrypt/dot/doh implementation on https://github.com/ibksturm/dnscrypt-switzerland

greets

**Comment by Ammykm** [comment]
Hi @ibksturm  
Thanks for the link :)

**Comment by jedisct1** [comment]
Hi!

The four entries have been removed, thanks for the notice!

The resolvers list has a dedicated repository: https://github.com/DNSCrypt/dnscrypt-resolvers
