### ISSUE TITLE
DoH fatal remote error: tls on 2.0.24. 2.0.23 is fine

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#873]
Problem is simple. 
Using dnscrypt-proxy 2.0.23 as client connected to DoH server with unbound > rust-doh > Nginx (TLS 1.3 only) and generated stamp from your 'Online DNS Stamp calculator' 
is working stable, fast and so on is fine.

Upgrading to 2.0.24 or above won't work.
And the following error is shown:

```
[2019-07-04 00:33:44] [ERROR] Get https://doh.test.com/link?ct=&dns=555hBBGGGHHFDEDEDAA: remote error: tls: protocol version not supported
[2019-07-04 00:33:44] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable

```
Going back to the previous version 2.0.23 or below corrects the problem at once.

```
[2019-07-04 00:38:03] [NOTICE] [.de] OK (DoH) - rtt: 13ms
[2019-07-04 00:38:03] [NOTICE] Server with the lowest initial latency: nl (rtt: 13ms)
[2019-07-04 00:38:03] [NOTICE] dnscrypt-proxy is ready - live servers: 1
```

Whats wrong?
Give me a shout if more info is preferable.

**Comment by TraderStf** [comment]
And with 2.0.25?

**Comment by ghost** [comment]
@TraderStf Thanks for your help
2.0.25 is a [Windows only release](https://github.com/jedisct1/dnscrypt-proxy/issues/851). 

`The example IP address for network probes didn't work on Windows - This is a regression introduced in version 2.0.24.`

Won't fix the problem, or do you have other experiences?

**Comment by jedisct1** [comment]
Are you using the precompiled binaries?

**Comment by ghost** [comment]
@jedisct1 Nup not using the pre-compiled binaries. 
It does indeed work with the pre-compiled units.

Stupid me not to test your pre-compiled binaries first, probably because;
Self compiling has always worked on Fedora 29 and Buster ARM, until version 24 occurred.
I also see no errors or problems during compiling. Very sorry about that.

Now rest my question what goes wrong?
On which OS do you compile your pre-compiled ARM binaries?

**Comment by jedisct1** [comment]
The OS shouldn't matter, but maybe your Go version is too old.

**Comment by ghost** [comment]
> The OS shouldn't matter, but maybe your Go version is too old.

Golang is fine as it is on 1.11 on both Fedora 29 ARM and Buster ARM.
It looks as if the problem is fixed, compiling on another ARM device. 

I probably have a disk with cures. 
And as a result, go clean couldn't find/proces the correct dependencies.
And maybe therefore strange error messages like: `TLS: protocol version not supported`

I didn't see any error messages while compiling, also nothing in the logs to mention.

I don't get it. Dependencies are hash verified.
Apparently I'm just stupid :)

And you shouldn't spend your valuable time in this stupidity.
I am so sorry.
