### ISSUE TITLE
go get github.com/jedisct1/dnscrypt-proxy failed.

### ISSUE THREAD

**Issue by hongyi-zhao** [DNSCrypt/dnscrypt-proxy#874]
Hi all,

I try to compile dnscrypt-proxy with the following method but failed as follows:

$ go get github.com/jedisct1/dnscrypt-proxy
package github.com/jedisct1/dnscrypt-proxy: no Go files in /home/werner/go/src/github.com/jedisct1/dnscrypt-proxy

This is the suggested method for general compiling go-based programs.  Any hints for this issue?

Regards

**Comment by jedisct1** [comment]
You need to specify the path where the source code is.

```sh
go get github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy
```

**Comment by jedisct1** [comment]
Or better, clone the repository, enter the `dnscrypt-proxy/dnscrypt-proxy` directory and type `go build`.
