### ISSUE TITLE
[Solved] Update raspbian to buster error bind: address already in use

### ISSUE THREAD

**Issue by tigernero79** [DNSCrypt/dnscrypt-proxy#876]
both Debian and raspbian have updated their version to the release buster.  I proceeded to install raspbian buster image from scratch on my pizero w but when the dnscrypt service installed via your guide starts I get a "bind: address already in use" error how can it be solved?  bug fixable in a new release?
I can still navigate
```
pi@PiVpnPiHole:/opt/dnscrypt-proxy $ sudo ./dnscrypt-proxy restart
[2019-07-08 07:51:49] [NOTICE] Network connectivity detected
[2019-07-08 07:51:49] [NOTICE] Source [public-resolvers.md] loaded
[2019-07-08 07:51:49] [NOTICE] dnscrypt-proxy 2.0.25
[2019-07-08 07:51:49] [FATAL] listen udp 127.0.0.1:54: bind: address already in use
pi@PiVpnPiHole:/opt/dnscrypt-proxy $
```

**Comment by jedisct1** [comment]
I bought a Pi Zero, installed Raspbian Lite on it and verified that it's the current version based on Debian Buster.

And there is nothing listening to port 54 (Why port 54 btw?). Nothing listening to port 53 either, and I was able to install dnscrypt-proxy using the generic instructions.

So... I don't know. Looks like you installed or changed something that you didn't mention.

**Comment by tigernero79** [comment]
then my procedure: installed pihole which manages dns on port 53 of his, if you install it you will see that from the menu pihole dns you can establish which dns also use a custom one, therefore being the port 53 already used, in dnscrypt I set the listening on port  54 and in pihole set dns to 127.0.0.1#54 in localhost.  working setting on old stretch version, on last Bond error buster as written above.  although navigation still works.

![Screenshot_20190709-031727_Chrome](https://user-images.githubusercontent.com/35575744/60852467-1e127c00-a1f8-11e9-80cd-c23f59694501.jpg)

**Comment by tigernero79** [comment]
in practice, I installed raspbian lite (buster), 
installed pihole via their bash script.
`curl -sSL https://install.pi-hole.net | bash`
then downloaded and installed dnscrypt.  
set in the dnscrypt configuration file the listening on port 54 (the 53 is used by pihole) 
`listen_addresses = ['127.0.0.1:54', '[::1]:54']`

In the pihole settings dns voice set dnscrypt dns calling in localhost on port 54 with 127.0.0.1 # 54.  
this works well on stretch now that i have buster 
i noticed from terminal rebooting dnscrypt error bind as posted above.

**Comment by tigernero79** [comment]
I discovered error, it was mine instead of writing 
`sudo ./dnscrypt-proxy -service restart`
I gave the command
`sudo ./dnscrypt-proxy restart`
without service option, which carelessly apologizes
