### ISSUE TITLE
[question] [wiki] [documentation] what is the purpose of `netprobe_timeout`

### ISSUE THREAD

**Issue by Nesos-ita** [DNSCrypt/dnscrypt-proxy#879]
I can't find on the wiki any documentation about that option, the config file display this:  
`Maximum time (in seconds) to wait for network connectivity before initializing the proxy. Useful if the proxy is automatically started at boot, and network connectivity is not guaranteed to be immediately available. Use 0 to not test for connectivity at all, and -1 to wait as much as possible.`  

But i don't get why this is necessary (i have changed it to 0 to disable that)

**Comment by jedisct1** [comment]
I couldn't find anything about this on the Wiki either.

But it does what the description says. The proxy can be automatically started at boot, but without Internet connectivity. Maybe because WiFi is slow to connect, DHCP is slow, a VPN has to be started, a password has to be entered manually, or it is an on-demand dial-up link.

Or maybe because all the services are started simultaneously without dependencies.

That seems to be especially useful on Windows.

**Comment by Nesos-ita** [comment]
Thanks but i still don't get the problem/why that option is needed.
I have set it as a service that start on boot on windows and i have manually disconnected and reconnected wifi after boot without any problem, also hibernating the pc (thus the service is never stopped but the connection is).
Without connection dns resolution will fail, with connection it works just like normal dns.
am i missing something?  

If i set that option to 60 seconds this means that for the first 60 seconds the program will not resolve anything because is waiting for connection?  
The wait time is applied only on program launch or also if internet connection goes away because for example i disconnect and reconnect wifi, sleep mode, other...

Windows servicies support dependency (this needs that to be started) but afaik there is no real "network service" that if started means that you are connected.
Task scheduler supports that: "run the task only if an internet connection is present"  
in case you need it.

**Comment by jedisct1** [comment]
Without connectivity, resolvers list cannot be downloaded.

**Comment by Nesos-ita** [comment]
oh ok, so since i use only cloudflare and set it as static that's no problem for me.  
or you suggest to avoid setting it as static?

**Comment by jedisct1** [comment]
If you are using a static entry, it will stop working if the parameters change.

In particular, as soon as the Globalsign certificate expires, or if Cloudflare switches to a different authority, it will break and you will have to figure it and fix it yourself.

This is planned to happen soon for Google users, for example.

I'd recommend only using static entries for your own resolvers, but that's your choice.
