### ISSUE TITLE
[FATAL] No servers configured

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [DNSCrypt/dnscrypt-proxy#88]
I'm using the default config .toml to see which servers have the best latency.
The application exits with this output

`[2018-02-04 09:11:52] [NOTICE] Source [http://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded`
`[2018-02-04 09:11:52] [FATAL] No servers configured`

**Comment by jedisct1** [comment]
Pretty sure you changed something to the default config file :)

**Comment by Marco-vW** [comment]
What's on the last line below in your dnscrypt-proxy.toml config file?

```
## List of servers to use
## If this line is commented, all registered servers matching the require_* filters
## will be used
## The proxy will automatically pick the fastest, working servers from the list.

server_names = ['cisco']
```

**Comment by Unkn0wn-MDCLXIV** [comment]
`# server_names = ['scaleway-fr', 'google', 'yandex']`

**Comment by pjnsmb** [comment]
you have to remove the # in front of server_names !

**Comment by jedisct1** [comment]
No, leaving the comment mark is the right thing to do in order to use all the resolvers.

**Comment by Marco-vW** [comment]
Either re-install or copy an un-edited dnscrypt-proxy.toml config file to the location where it's stored. 

You shouldn't get the line

`[2018-02-04 09:11:52] [FATAL] No servers configured
`

with the hashtag in front of the line I mentioned previously when dnscrypt-proxy is able to load its source list  with resolvers as the previous line in your first post mentions.

**Comment by mastad0n** [comment]
Hmm I was able to replicate this just now.

My installation is working, but when I try to replicate the error (just now) by commenting the line, I get the same error:

>[FATAL] No servers configured

When I use a fresh .toml, I get the same issue.

This is the first time I notice since my line is always un-commented.

Are you using Linux?

**Comment by ghost** [comment]
I had the same issue and @jedisct1 resolution worked. Use a fresh .toml
