### ISSUE TITLE
Host file iOS 

### ISSUE THREAD

**Issue by JuliusBairaktaris** [DNSCrypt/dnscrypt-proxy#881]
Where do I add a host file on iOS ?
For example https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts.txt

**Comment by jedisct1** [comment]
Without any context, I'm going to assume that you are talking about DNSCloak.

![image](https://user-images.githubusercontent.com/124872/60976549-2bca1d80-a32e-11e9-96a2-9ae915f064ca.png)

Blacklists and whitelists are not host files, but you already saw that in the documentation.
