### ISSUE TITLE
IPV6 docker image won't installed because there IPV4 docker installed!

### ISSUE THREAD

**Issue by Ammykm** [DNSCrypt/dnscrypt-proxy#886]
Hi @jedisct1 ,

I installed docker image on the server uisng ipv4 and tried to make a new directory to install docker with ipv6 but it shows error that i can't IPV6 on the same server 

```sh
docker run --ulimit nofile=90000:90000 --name=dnscrypt-server-n -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server-n init -N ns0.dnscrypt.nl-eu -E [2001:bc8:1824:1535::1]:443
Unable to find image 'jedisct1/dnscrypt-server-n:latest' locally
docker: Error response from daemon: pull access denied for jedisct1/dnscrypt-server-n, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

Any recommendation on this 
Thanks
Ammy

**Comment by jedisct1** [comment]
Hi Ammy,

`jedisct1/dnscrypt-server-n`: this is the name of the image, that has to exist on the [Docker Hub](https://hub.docker.com/). There is an image named `dnscrypt-server` but none named `dnscrypt-server-n`.

`--name=dnscrypt-server-n`: that one is fine, you can create new containers with any name, from the same image.

**Comment by jedisct1** [comment]
Just to keep things organized: there is a dedicated [dnscrypt-server](https://github.com/jedisct1/dnscrypt-server-docker) repo.

**Comment by Ammykm** [comment]
Hi @jedisct1 ,

I used your docker image on scaleway with ipv4 and i would like to use it again with ipv6 on the same server , then i got the error above that you saw

Ammy

**Comment by jedisct1** [comment]
Try replacing `jedisct1/dnscrypt-server-n` with `jedisct1/dnscrypt-server`.

**Comment by Ammykm** [comment]
Hey @jedisct1 

I used this one before 
docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server init -N ns0.dnscrypt.nl-eu -E 51.15.44.12:443

and can i use this one with this config


docker run --ulimit nofile=90000:90000 --name=dnscrypt-server-n -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server-n init -N ns0.dnscrypt.nl-eu-ipv6 -E [2001:bc8:1824:1535::1]:443

**Comment by Ammykm** [comment]
got this

 docker run --ulimit nofile=90000:90000 --name=dnscrypt-server-n -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server-n init -N ns0.dnscrypt.nl-eu-ipv6 -E [2001:bc8:1824:1535::1]:443
Unable to find image 'jedisct1/dnscrypt-server-n:latest' locally
docker: Error response from daemon: pull access denied for jedisct1/dnscrypt-server-n, repository does not exist or may require 'docker login'.
See 'docker run --help'.

**Comment by Ammykm** [comment]
i change the name  and it's work now
