### ISSUE TITLE
IPV6 not connecting!

### ISSUE THREAD

**Issue by Ammykm** [DNSCrypt/dnscrypt-proxy#887]
Hi @jedisct1 ,

I installed you docker image on both ipv4 and ipv6 and it's installed after little bit guide of yours by chaing the --name , IPV4 working , but IPV6 not working , can ping using ping6 but it's not connecting to dnscrypt-wrapper
Thanks
Ammy

**Comment by dnscrypt-ca** [comment]
I was trying to help Ammykm with this a bit and was wondering if it is possible to have a single docker container that has both IPv4 and IPv6 listeners.  Would I be correct in my understanding that a docker container can only run a single instance of an application and as a result multiple containers are required to listen on both IPv4 and IPv6?

PS: I believe this question belongs in /DNSCrypt/dnscrypt-server-docker/ but do not know if it is possible to relocate it there.

**Comment by r4sas** [comment]
Who prevent you to create few port forwardings?
Is in your docker configuration IPv6 really enabled?

Really, RTFM.

**Comment by Ammykm** [comment]
Hey @r4sas 

Yes IPv6 it’s already enabled and ping6 google.com working

**Comment by r4sas** [comment]
Recheck all your port bindings, firewall settings.

**Comment by Ammykm** [comment]
sudo lsof -i -P -n | grep LISTEN 
sudo netstat -tulpn | grep LISTEN
sudo nmap -sTU -O IP-address-Here

Like this

**Comment by Ammykm** [comment]
netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:553           0.0.0.0:*               LISTEN      15978/unbound
tcp        0      0 10.0.3.1:53             0.0.0.0:*               LISTEN      1291/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      26489/sshd
tcp        0      0 127.0.0.1:8953          0.0.0.0:*               LISTEN      15978/unbound
tcp6       0      0 :::22                   :::*                    LISTEN      26489/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      19436/dnscrypt-wrap
tcp6       0      0 :::443                  :::*                    LISTEN      32227/dnscrypt-wrap

**Comment by Ammykm** [comment]
Hi @r4sas @jedisct1 ,
@jedisct1 i really want to change and modified unbound but i can't find in in docker image 
how to find the files in docker image , i mean unbound, dnscrypt etc..
i think the issue is here , 


[1563441081] unbound[11478:0] error: can't bind socket: Address in use for 127.0.0.1 port 8953
[1563441081] unbound[11478:0] error: cannot open control interface 127.0.0.1 8953

**Comment by jedisct1** [comment]
This is when running two containers simultaneously, right?

It's probably easier to run just one, and forward IPv6 traffic to the IPv4 address.

**Comment by Ammykm** [comment]
Thanks for the reply @jedisct1 
I'm tring to run ipv4 && ipv6 on your docker image, ipv4 work fine but not ipv6 
i appricate if you just tell me how to forward IPV6 traffic to IPV4 so i have both IP's working on dnscrypt-server docker image
Thanks

**Comment by jedisct1** [comment]
Unfortunately my Linux expertise is pretty limited and I have no idea how to do that, but @r4sas must know :)

**Comment by Ammykm** [comment]
@jedisct1 
So you saying i can't install both ipv6 and ipv4 on the same docker image? 
i don't think forward traffic to ipv4 will solve it as you see above there is traffic and both ports are open for ipv6 and ipv4

**Comment by jedisct1** [comment]
The same container can serve IPv4 and IPv6. I think all it would take is run a second `dnscrypt-wrapper` service, with the same parameters except the IP.

**Comment by Ammykm** [comment]
@jedisct1 

 can you send me the command please , like the first one with ipv4 1.2.3.4 and ipv6 1111.2222.3333.4444 , 
i did it before and it shows that i cant run the same container , see below.
docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server init -N ns0.dnscrypt.nl-eu-ipv6 -E [2001:bc8:1824:1535::1]:443

docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server init -N ns0.dnscrypt.nl-eu -E 51.15.44.12:443

**Comment by r4sas** [comment]
`docker run ... -p 443:443/udp -p 443:443/tcp -p 2000:aaaa:bbbb::cccc:443:443/udp -p 2000:aaaa:bbbb::cccc:443:443/tcp ...` like this, I dont remember correct syntax.
And I done this without host network.

**Comment by Ammykm** [comment]
Hi @r4sad 
What is that ... the 3 dots ?

**Comment by r4sas** [comment]
Cutoff to reduce message lenght. In your case it must be like
`docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 51.15.44.12:443:443/udp -p 51.15.44.12:443:443/tcp -p 2001:bc8:1824:1535::1:443:443/udp -p 2001:bc8:1824:1535::1:443:443/tcp jedisct1/dnscrypt-server init -N ns0.dnscrypt.nl-eu -E 51.15.44.12:443`

About IPv6 addresses in port mapping I dont remember is needed to use `[ ]` or no.

**Comment by Ammykm** [comment]
Hi @r4sas , @dnscrypt-ca @jedisct1 

I think there is something missing i got this message below , and there is only ipv4 nameserver , what about ipv6 name 

docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 51.15.44.12:443:443/udp -p 51.15.44.12:443:443/tcp -p 2001:bc8:1824:1b41::1:443:443/udp -p 2001:bc8:1824:1b41::1:443:443/tcp jedisct1/dnscrypt-server init -N exo.dnscrypt.nl-eu -E 51.15.44.12:443
docker: invalid publish opts format (should be name=value but got '51.15.44.12:443:443/udp').
See 'docker run --help'.

**Comment by Ammykm** [comment]
Hi @r4sas @dnscrypt-ca @jedisct1 
Please see below, also there is no nameesver for ipv6 its only for ipv4 (exo.dnscrypt.nl-eu) ipv6 ( exo.dnscrypt.nl-eu-ipv6) where should i assign it

```
docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 51.15.44.12:443:443/udp -p 51.                                          15.44.12:443:443/tcp -p [2001:bc8:1824:1b41::1]:443:443/udp -p [2001:bc8:1824:1b41::1]:443:443/tcp jedisct1                                          /dnscrypt-server init -N exo.dnscrypt.nl-eu -E 51.15.44.12:443
Unable to find image 'jedisct1/dnscrypt-server:latest' locally
latest: Pulling from jedisct1/dnscrypt-server
921b31ab772b: Pull complete
a154aaf8da8d: Pull complete
f99a5d8e4343: Pull complete
5a61e3824f56: Pull complete
4c95246a3950: Pull complete
7704b45090de: Pull complete
0d2821bef68e: Pull complete
04fb2fb38897: Pull complete
724a6f0f6bf4: Pull complete
d0c7e1d56bce: Pull complete
c5b61a4ca4f0: Pull complete
0b4c0d3d6a62: Pull complete
2349401d8007: Pull complete
9c11bf8a4f3f: Pull complete
a3f7def21e77: Pull complete
Digest: sha256:c77fd79871686080ba5e403c3297b39b03a5a6488bed2850dd3e948e2af3cf0b
Status: Downloaded newer image for jedisct1/dnscrypt-server:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint dnscrypt-se                                          rver (b5241ebc9f0a8d15d7f5caf3391fb0f14ba0e386945423969a9856dc6f493679): Error starting userland proxy: lis                                          ten tcp 51.15.44.12:443: bind: cannot assign requested address.
ERRO[0006] error waiting for container: context canceled
```

**Comment by Ammykm** [comment]
Hi @jedisct1 
Does your docker image listen to IPV6 , as i saw in your unbound there is no interface for ipv6 
You have only one interface who listening to interface: 0.0.0.0 and not to interface: ::0 correct me if i'm wrong.

You have had only allow access to this access-control: 0.0.0.0/0 allow
  access-control: ::0/0 allow
Should i add this to your unbound to be like
do-ip6: yes
interface: 0.0.0.0
interface: ::0
access-control: ::1 allow
Thanks 
if this fixed so it will be easy for others if they want to configure their dnscrypt server with both ipv4 and ipv6

Thanks

**Comment by jedisct1** [comment]
You probably shouldn't have to change anything to unbound. Unbound is only used internally, users never connect directly to it.

I think what should be added is a second `dnscrypt-wrapper` instance, with an IPv6 address for the `--ext-address=...` parameter.

**Comment by Ammykm** [comment]
Hi @jedisct1

Can you please type all the command you mention above —ext ipv6 so I can change only the ipv6 to mine 
Thanks

**Comment by jedisct1** [comment]
The image needs to be rebuilt with the new service. I'll try to do that, but I don't know Docker very well and I don't have IPv6 connectivity so this will take a bit of time.

**Comment by Ammykm** [comment]
Hi again @jedisct1

I read a little bit on IPV6 on docker documentation’s website and here’s the link

https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/

Thanks

**Comment by jedisct1** [comment]
https://github.com/jedisct1/encrypted-dns-server will make this so much easier.
