### ISSUE TITLE
When I installed this program on centos, I got the problem of "./dnscrypt-proxy-service: No such file or directory".

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#889]
When I installed this program on centos, I got the problem of "./dnscrypt-proxy-service: No such file or directory".
I followed the wiki and found "./dnscrypt-proxy-service: No such file or directory" when running "./dnscrypt-proxy-resolve example.com" on my centos7 server.
I hope to get answers, thank you.

**Comment by ghost** [comment]
But when I checked, I found this file.

**Comment by jedisct1** [comment]
`./dnscrypt-proxy service`
`./dnscrypt-proxy resolve example.com`

There is a space, not a `-` after `dnscrypt-proxy`.
