### ISSUE TITLE
About dnscrypt.org

### ISSUE THREAD

**Issue by dbaio** [DNSCrypt/dnscrypt-proxy#89]
Hi.

I don't know if here is the best place to ask this.

In FreeBSD we fetch dnscrypt-proxy 1.9.5 through https://download.dnscrypt.org/dnscrypt-proxy/ .

This site will be available again?

Regards.

**Comment by jedisct1** [comment]
I don't own that domain any more, and I don't know who does. So, probably not. It might even be eventually used to spread malware.

But version 2 will be released in a couple days :)

**Comment by dbaio** [comment]
Ok, thanks for the information.
