### ISSUE TITLE
How to find what software is listening to port 53 on Windows?

### ISSUE THREAD

**Issue by JuliusBairaktaris** [DNSCrypt/dnscrypt-proxy#896]
The program is not working for me at all somehow windows is able to use 127.0.0.1 as my dns server and still resolve everything with that

**Comment by jedisct1** [comment]
When following the installation instructions from the documentation, at what step did you get a different result than the expected one?

**Comment by JuliusBairaktaris** [comment]
Nowhere that’s why I asked otherwise I would have tried to figure out myself. Even when the proxy is turned off and I just have 127.0.0.1 and ::1 as my dns Servers Windows can still resolve all ips magically. I noticed that when trying to create a blacklist and when using 1.1.1.1/help

**Comment by r4sas** [comment]
According to topic, example how find process listening port:
```cmd
> netstat -ano | find "LISTENING" | find ":53"
  TCP    127.0.0.1:53           0.0.0.0:0              LISTENING       1844
> tasklist | find "1844"
dnscrypt-proxy.exe            1844 Services                   0      9,516 K
```
