### ISSUE TITLE
Got problem with forwarding-rules

### ISSUE THREAD

**Issue by Elypha** [DNSCrypt/dnscrypt-proxy#898]
Hi there,

The forwarding-rules feature seems not working on my PC.
I'm working on windows 10 1903 18362.239 and dnscrypt-proxy is 2.0.25.
My config in .toml file is:
```
...
forwarding_rules = "E:\\DNSCrypt-proxy\\forwarding-rules.txt"
...
```
In forwarding-rules.txt:
```
...
163.com 114.114.114.114,223.5.5.5
...
```
I find that I'm able to visit 163.com because a secondary DNS (114.114.114.114) is set up in my system. If I leave it blank, the website will not work.

In terminal, `nslookup www.163.com 127.0.0.1` returns that:
```
nslookup www.163.com 127.0.0.1
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
```
In query.log, it reads:
```
time:1564119929	host:127.0.0.1	message:www.163.com	type:A	return:DROP	cached:0	duration:1	server:dnscrypt.nl-ns0
time:1564119931	host:127.0.0.1	message:www.163.com	type:AAAA	return:DROP	cached:0	duration:1	server:dnscrypt.nl-ns0
time:1564119933	host:127.0.0.1	message:www.163.com	type:A	return:DROP	cached:0	duration:1	server:dnscrypt.nl-ns0
...
```
(BTW, is it expected to get "return:DROP" here?)
I tried many random domains in forwarding-rules.txt and none of them works with forwarding-rules enabled. These domains are all existing ones and can be resolved through dns server like 1.1.1.1 and 114.114.114.114.
```
nslookup www.163.com 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
DNS request timed out.
    timeout was 2 seconds.
Name:    www.163.com.lxdns.com
Addresses:  157.185.164.73
          157.185.167.18
Aliases:  www.163.com
          www.163.com.163jiasu.com
```
```
nslookup www.163.com 114.114.114.114 
Server:  public1.114dns.com                
Address:  114.114.114.114                  
                                           
Non-authoritative answer:                  
Name:    z163ipv6.v.bsgslb.cn              
Addresses:  240e:93d:1::1:17               
          240e:93d:1::1:18                 
          240e:93d:1::1:16                 
          219.150.124.163                  
          219.150.124.160                  
          219.150.124.159                  
          219.150.124.154                  
          219.150.124.165                  
          219.150.124.153                  
          219.150.124.161                  
          219.150.124.156                  
          219.150.124.164                  
          219.150.124.157                  
Aliases:  www.163.com                      
          www.163.com.163jiasu.com         
          www.163.com.bsgslb.cn            
```
If I comment that line in forwarding-rules, all works fine (it resolves through proxy). I think the dnscrypt-proxy does read the forwarding-rules.txt and forward the dns request, but it seems that something later goes wrong :(
Could someone kindly help me out?

**Comment by misaka00251** [comment]
Have the same issue. Forwarding requests is not working...

Set the rules:

```
www.baidu.com 114.114.114.114,223.5.5.5
```

Then try to open Baidu in Chrome or any modern browser, it will say `www.baidu.com’s server IP address could not be found.`.

logs:

```
[2019-09-07 00:04:33]	127.0.0.1	www.baidu.com	A	DROP	3ms	-
[2019-09-07 00:04:33]	127.0.0.1	www.baidu.com	A	DROP	3ms	-
```

However, using `dig www.baidu.com` is fine. `ping` can also resolve the right IP address.

Environment: Windows 10 x64 Pro 1809 w/ dnscrypt-proxy 2.0.25.
