### ISSUE TITLE
How to install on Debian 10?

### ISSUE THREAD

**Issue by ysz223** [DNSCrypt/dnscrypt-proxy#899]
How to configure the installation in Debian 10? Thank you!

**Comment by jedisct1** [comment]
Hi,

Follow the generic Linux instructions from the documentation.

They should work well with Debian 10.

**Comment by ysz223** [comment]
The documentation is out of date, the Debian 10 Appmarketer is now ready to be installed to a stable version, why can't it be configured automatically and used directly after installation?

**Comment by jedisct1** [comment]
Can you clarify what it out of date in these instructions? Or even improve them since this is a Wiki?

I don’t know what Appmarketer is, sorry.
