### ISSUE TITLE
From OLD dnscrypt-proxy to NEW one

### ISSUE THREAD

**Issue by michael1900** [DNSCrypt/dnscrypt-proxy#9]
What are the steps to do to use new dnscrypt-proxy for users using old 1.x version on High Sierra with brew?

**Comment by jedisct1** [comment]
Uninstall 1.x with `brew uninstall`.

Download the new one, and store it wherever you want.

Tweak the `.toml` file according to your needs.

Run it with `./dnscrypt-proxy`, check that everything works as expected.

Looks good? You can have it automatically start at boot with:

```sh
./dnscrypt-proxy -service install
```

It's installed? Let's start it without having to reboot:

```sh
./dnscrypt-proxy -service start`
```

Done!

Want to temporarily stop it?

```sh
./dnscrypt-proxy -service stop
```

Want to uninstall it?

```sh
./dnscrypt-proxy -service uninstall
```

That's it!

**Comment by jedisct1** [comment]
Ah, maybe you need to sprinkle `sudo` before these commands in order to listen to port 53 :)

**Comment by jedisct1** [comment]
But a Homebrew formula is likely to be available after 2.0.0 final is tagged no matter what.

Homebrew maintainers are always very reactive.

**Comment by michael1900** [comment]
Thank for reply. Maybe i will wait new homebrew formula when 2.0.0 will be available. Obviously i will unistall to old one before.

What you think? This can be a good way to do the changing?

**Comment by jedisct1** [comment]
Sounds reasonable!
