### ISSUE TITLE
Build DNSCrypt with gccgo on Solaris 10

### ISSUE THREAD

**Issue by yvoinov** [DNSCrypt/dnscrypt-proxy#90]
Build DNSCrypt with gccgo on Solaris 10 - is it possible in principe? May be, have some documentation, how to build from sources?

**Comment by jedisct1** [comment]
Probably.

It compiles fine with regular Go, though, so solaris/amd64 binaries can be added to the list of official precompiled binaries available for download.

**Comment by yvoinov** [comment]
Also, would like to run not only on Solaris 11, but also on Solaris 10 which have gccgo, and on Solaris/sparc. If required, I have SPARCv9 server under Solaris 10 with GCC 5.5 (and gccgo, of course).

**Comment by jedisct1** [comment]
Solaris/sparc requires gccgo indeed. I have no idea how to do that and if it works, though since gccgo is always running a bit behind upstream go.

**Comment by yvoinov** [comment]
It has. OpenCSW has both gccgo, for x64 and SPARC.

**Comment by jedisct1** [comment]
Unfortunately I have no idea about how to do this, but maybe you can find help in more specialized forums about Go and Solaris.
If you ever find how to do this, adding the procedure to the documentation would be great!

**Comment by yvoinov** [comment]
All other software I'm running written on compatible C/C++, has good compiler, and builds and runs on all servers without issues.

May be, when I have free time, I'll trying to find any solution. Can't guarantee I'll want to waste time for that. Don't think so good idea to waste time for compatibility issue for only one service. It's more easy to me just get rid dnscrypt from my systems completely. I do not want to fight with incompatible and unsupported (at least on my platform) software.

But generally,  IMHO it is a very bad idea - decrease service compatibility whenever any benefits and gains.

As old IT maxima said: "Compatibility is more important than performance".
