### ISSUE TITLE
Req: Automatic Blacklist of Parent Domain, via response, via Wildcard

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#900]
Without filtering CNAMEs and their associated domains, dnscrypt blacklists are currently only filtering a small percentage of potentially malicious and unwanted domains.  Sometimes there are multiple CNAMES that reveal their actual hidden associations in replies which are difficult to block with Dnscrypt. For example... I have blacklisted wildcard: *analytics* however, dnsmasq shows  dnscrypts responses for the following domains:
```

13:19:30 dnsmasq[1211]: query[A] s.update.fbsbx.com from 192.168.50.142
13:19:30 dnsmasq[1211]: forwarded s.update.fbsbx.com to 127.0.0.1
13:19:30 dnsmasq[1211]: reply s.update.fbsbx.com is
13:19:30 dnsmasq[1211]: reply s.agentanalytics.com is
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 52.20.233.11
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 35.170.177.215
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 34.235.44.232
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 34.194.252.192
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 18.206.130.128
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 52.202.107.183
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 18.209.97.44
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 35.173.82.169
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 23.22.178.204
13:19:30 dnsmasq[1211]: reply agentanalytics.com is 18.206.103.1
```

So if dnsmasq cached these IPS, then clearly dnscrypt does not currently include functionality to automatically block the analytic domain's parent zone based on reply. These IP's should not be cached. Please include the ability to block parent domains based on replies, via wildcards from blacklist.txt

**Comment by rugabunda** [comment]
Previously you stated "I think you got confused by what dnsmasq is logging, which, granted, is very confusing. There is only one question here A s.update.fbsbx.com, and one matching response CNAME s.update.fbsbx.com. The rest is garbage ignored by resolvers, as it is not within the parent zone."

Actually if you look at s.update.fbsbx.com in dnsmasq you will find it points to an analytics domain. For example Robtex demonstrates S.update.fbsbx.com is a CNAME to s.agentanalytics.com, as does dnsmasq, hence you see **cname** in dnsmasq, as demonstrated in the comment below in relation to itunes.  https://www.robtex.com/dns-lookup/s.update.fbsbx.com

Hence, s.update.fbsbx.com is of course used by dnscrypt and dnsmasq etc, however it is pointing to IP's associated with s.agentanalytics.com.

In all earnesty, I have opened a question at [StackExchange regarding your claims which make no sense to me at all](https://security.stackexchange.com/questions/214373/securing-dns-by-blocking-querys-and-responses-dnscrypt-questions) 

These IP's are not ignored by the stub resolver, they passed on by dnscrypt to dnsmasq where they are cached and associated to the parent zone. I saw s.update.fbsbx.com in Umatrix while browsing facebook, what ip then would it be associated with except s.agentanalytics.com ip addresses? Well of course it is s.agentanalytics.com IP addresses.

**Comment by rugabunda** [comment]
To filter this conveniently and automatically, dnscrypt would need the ability to monitor & block matching of CNAME's, replace cached IP with 127.0.0.1 and or automatically add the parent zone to the blacklist.  Otherwise dnsmasq and or other revolvers cache  must be cleared or timed out before blacklist is effective.

**Comment by rugabunda** [comment]
Here are more examples confirmed here, if one wanted to wildcard block akami in association with itunes, just for illustration, : https://www.robtex.com/dns-lookup/su.itunes.apple.com

You would need to block su.itunes.apple.com and xp.apple.com. If dnscrypt included blacklisting of tricky/hidden cname's parent domains associated with dnscrypt blacklist, then this would best be automated! Pretty necessary unless you prefer watching tens of thousands of dns query responses while browsing the web and then, associating them to akami (or a million other possibilities), and then inputting them into the blacklist manually.  

Without filtering responses, dnscrypt blacklists are currently only filtering a small percentage of potentially malicious and unwanted domains.


```

13:55:28 dnsmasq[26607]: query[A] su.itunes.apple.com from 192.168.50.96
13:55:28 dnsmasq[26607]: forwarded su.itunes.apple.com to 127.0.0.1

13:55:29 dnsmasq[26607]: reply su.itunes.apple.com is <CNAME>
13:55:29 dnsmasq[26607]: reply su-cdn.itunes-apple.com.akadns.net is <CNAME>
13:55:29 dnsmasq[26607]: reply su-applak.itunes-apple.com.akadns.net is <CNAME>
13:55:29 dnsmasq[26607]: reply su.itunes.apple.com.edgekey.net is <CNAME>
13:55:29 dnsmasq[26607]: reply e673.dsce9.akamaiedge.net is 184.50.162.217

13:55:29 dnsmasq[26607]: query[A] xp.apple.com from 192.168.50.96
13:55:29 dnsmasq[26607]: forwarded xp.apple.com to 127.0.0.1
13:55:29 dnsmasq[26607]: reply xp.apple.com is <CNAME>
13:55:29 dnsmasq[26607]: reply xp.itunes-apple.com.akadns.net is <CNAME>
13:55:29 dnsmasq[26607]: reply xp.apple.com.edgekey.net is <CNAME>
13:55:29 dnsmasq[26607]: reply e17437.dscb.akamaiedge.net is 23.214.192.96

```

**Comment by jedisct1** [comment]
Name blacklists are applied to incoming queries. If there is a match, nothing will be forwarded to upstream resolvers. They will not know that a client asked for one of these names.

The flipside that responses are not inspected for `CNAME` records possibly matching blacklists.

This will probably not be implemented, but what you can do is block IP addresses instead, as these rules are applied to responses.

**Comment by rugabunda** [comment]
@jedisct1  Thank you for the response.  So when I have spent a few years compiling 20,000 ever changing ip addresses, by manually combing through responses for my large corporation, and before many of those IP's inevitably change, should I expect dnscrypt to slow down if I have for example 8000 clients using a dnscrypt resolver to filter every dns response through a 20,000 long ip block list?

Feature request: search CNAME records with blacklist, apply to parent zone.

**Comment by jedisct1** [comment]
You can assign that feature request to your employees, then :)

That being said, a 20,000 long IP block list is not a problem and I suspect people use large lists than that already. This is not a `hosts` file; IP addresses are indexed in a prefix tree, so on the worst case, it will only take 14 memory reads to check for a match. That's nothing.
