### ISSUE TITLE
How to use only DoH servers (outgoing tcp connection)?

### ISSUE THREAD

**Issue by Vai3soh** [DNSCrypt/dnscrypt-proxy#902]
Config:
doh_servers = true
force_tcp = true

On some servers I observe that they use outgoing udp connection, for example:
server_names = ['rubyfish-uw']

I'm blocking udp:
`iptables -I OUTPUT -o eth0 -p udp -j REJECT`

And log:

```
Aug 03 10:17:41 jo dnscrypt-proxy[22890]: [2019-08-03 10:17:41] [NOTICE] dnscrypt-proxy 2.0.19
Aug 03 10:17:41 jo dnscrypt-proxy[22890]: [2019-08-03 10:17:41] [NOTICE] Now listening to 127.0.0.1:5789 [UDP]
Aug 03 10:17:41 jo dnscrypt-proxy[22890]: [2019-08-03 10:17:41] [NOTICE] Now listening to 127.0.0.1:5789 [TCP]
Aug 03 10:17:41 jo dnscrypt-proxy[22890]: [2019-08-03 10:17:41] [ERROR] write udp 192.168.1.10:35701->9.9.9.9:53: write: operation not permitted
Aug 03 10:17:41 jo dnscrypt-proxy[22890]: [2019-08-03 10:17:41] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
```
As you can see, he wants to send the  udp package to 9.9.9.9

Whether it is possible to force not to use these servers? And use only DOH servers. (tcp)

**Comment by Vai3soh** [comment]
And another question:
proxy = "socks5://127.0.0.1:9050"
If authorization?

**Comment by Vai3soh** [comment]
I run DEBUG=1 and understand why a request is sent to 9.9.9.9:
this fallback_resolver
Is it possible to send it by tcp?

**Comment by jedisct1** [comment]
Hi,

Version 2.0.19 is old, can you try a more recent one?

Just curious: why are you blocking outgoing UDP?

UDP is generally faster than TCP, and even HTTP is abandoning TCP for UDP (HTTP3/QUIC).

Also, if you use DNSCrypt, or if you use DoH servers that include an IP address, the fallback resolver will not be used.

**Comment by Vai3soh** [comment]
> Version 2.0.19 is old, can you try a more recent one?

   Yes. This from repos. debian.

>  Just curious: why are you blocking outgoing UDP?

   I use unbound + dnscrypt-proxy + redsocks (can only tcp).

> DoH servers that include an IP address, the fallback resolver will not be used.

   How do you know it's that server (where fallback resolver will not be used)? And another way: 
   fallback_resolver = 127.0.0.1:222 . He won't be able to send the package.

**Comment by jedisct1** [comment]
dnscrypt-proxy already supports SOCKS, and also does caching, so you may not need unbound nor redsocks.

**Comment by Vai3soh** [comment]
Ok .thanks.
> supports SOCKS

authorization support?

**Comment by jedisct1** [comment]
yes.
