### ISSUE TITLE
New string

### ISSUE THREAD

**Issue by ooonea** [DNSCrypt/dnscrypt-proxy#903]
Hi dear, when can you update the strings in the public server files?

suami (France): sdns://AQcAAAAAAAAAEjE2My4xNzIuMTM1LjkxOjQ0MyAa1c2tko5PA1_fBzSXfz3pIB-3QKK04gA99gF7D_ePqBwyLmRuc2NyeXB0LWNlcnQuZnIuc3VhbWkuY29t

charis (Amsterdam): sdns://AQcAAAAAAAAAETUxLjE1LjEwNi4xNzY6NDQzIGcUiAnFqewnNLjh8DUYpcePX07pXc3sDOf2U-vpI55WHjIuZG5zY3J5cHQtY2VydC5hbXMuY2hhcmlzLmNvbQ

Thank you so much.

**Comment by jedisct1** [comment]
Hello!

The stamps have been updated :)

Thanks for the heads up and have a great weekend!
