### ISSUE TITLE
IPv6 forwarding issue?

### ISSUE THREAD

**Issue by whoizit** [DNSCrypt/dnscrypt-proxy#906]
```
dnscrypt-proxy-2.0.25
yggdrasil-0.3.5
```
`0200::/7` network https://yggdrasil-network.github.io/faq.html 

/etc/resolv.conf
`nameserver 127.0.0.1`

/etc/dnscrypt-proxy/dnscrypt-proxy.toml
`forwarding_rules = '/etc/dnscrypt-proxy/forwarding-rules.txt'`

/etc/dnscrypt-proxy/forwarding-rules.txt
```
ygg 200:1e4b:b2df:69ba:1eba:fdf9:edde:3712
isp 200:1e4b:b2df:69ba:1eba:fdf9:edde:3712
```
```
$ dig AAAA @200:1e4b:b2df:69ba:1eba:fdf9:edde:3712 +short medium.isp mesh.ygg map.ygg
200:1e4b:b2df:69ba:1eba:fdf9:edde:3712
303:60d4:3d32:a2b9::4
21f:dd73:7cdb:773b:a924:7ec0:800b:221e

$ dig AAAA medium.isp mesh.ygg map.ygg

; <<>> DiG 9.14.4 <<>> AAAA medium.isp mesh.ygg map.ygg
;; global options: +cmd
;; connection timed out; no servers could be reached
;; connection timed out; no servers could be reached
;; connection timed out; no servers could be reached
```
this works for dnsmasq

**Comment by jedisct1** [comment]
Maybe IPv6 addresses requires brackets around them?

**Comment by ghost** [comment]
> Maybe IPv6 addresses requires brackets around them?

No, it doesn't. Both dnsmasq and dnscrypt not requires the brackets for IPv6 addresses. This feature only used in URI.

**Comment by whoizit** [comment]
anyway not works

**Comment by jedisct1** [comment]
Add the port:

```
[200:1e4b:b2df:69ba:1eba:fdf9:edde:3712]:53
```
