### ISSUE TITLE
[suggestion] DANE validation

### ISSUE THREAD

**Issue by Dr-Flay** [DNSCrypt/dnscrypt-proxy#907]
Before you say I am talking stupid, I have to admit to originally being against what I am about to propose, but on further thought I realise maybe I'm not seeing the potential.

Could adding DANE validation to the DNS layer be the way we finally get it ?
Currently the only way to have automatic DANE validation has been with a now EOL browser extension.
If it hadn't been for DANE validation I would have been unaware of an extension I had that had hijacked my DNS lookups.

It makes sense to have it in the software you are using for notifications, but as the likelihood of  any browser adopting it soon is very slim, even though DNSSEC is now widely available for client and server, I come to think maybe the model established by this project is the way to make full use of it.

Perhaps it is something more suited to bolting into a container such as Simple DNSCrypt rather than the core, though I suspect it would have enough requirements in common with the core code that it could be more optimal to have it as core functionality.

Initially my reason for being against the idea is the problem of client feedback.
After discussing it more I had reduced the point of what DANE validation gives, to being a glorified dynamic blocklist. Generally we let them do their job with minimal interaction, so maybe this could be brutal but work.
Granted considering the lack of uptake this would have to be an opt-in feature.

I know it smells like a cludge, but if the proxy can set some relevant flags for use by the builders of the wrappers, then perhaps giving user feedback and interaction is not such a problem ?
User overrides could be handled like adding white or blacklist entries.

Feel free to shoot me down, as this obviously is beyond the remit of what DNSCrypt is, or perhaps started as, but I think that the real power of DNSCrypt is the proxy rather than just the protocol.
I got a bit annoyed at Leo using the old Cisco reference during a recent episode of Security Now, so quickly put a blog together about using DoH with any software and sent Steve Gibson a tweet. He thankfully had another look at how things are now and gave a glowing review of DNSCrypt Proxy and the handy Windows wrapper.
This project has already gone beyond where it started and crazy at it seems to many supports competing standards which make the original protocol of this project a secondary consideration for many.

Would DANE validation be such a crazy string to add to the already impressive bow ?

**Comment by jedisct1** [comment]
Hi,

I'm not sure I follow.

For HTTP, DANE never caught up, and web browsers have implemented better mechanisms (HPKP and CT).

DANE is now only used by email servers to check if mail can be delivered over TLS. Nobody's using it besides email, and even for email, it is in the process of being replaced by MTA-STS that doesn't require DNSSEC.

I'm not sure what `dnscrypt-proxy` would do here. Act as a mail server that does DANE validation before forwarding email to another server?

That's a little bit out of scope, and people wanting to do this should rather install postfix.
