### ISSUE TITLE
public-resolvers.md mirror

### ISSUE THREAD

**Issue by vbauerster** [DNSCrypt/dnscrypt-proxy#908]
Hi! First of all thank you for your great work!

My ISP is blocking whole `github.com`. Can we have a mirror for `public-resolvers.md` say on `gitlab.com`?

**Comment by jedisct1** [comment]
The [example configuration](https://github.com/jedisct1/dnscrypt-proxy/blob/faa931585ba91d2f07287f0730506cfdbf320e28/dnscrypt-proxy/example-dnscrypt-proxy.toml#L519) file has two distinct URLs (and the second is actually the primary one, not GitHub). If the configuration cannot be fetched from an URL of the list, other URLs should be tried automatically.

The documentation also lists [more mirrors](https://github.com/jedisct1/dnscrypt-proxy/wiki/DNS-server-sources).

**Comment by jedisct1** [comment]
Having `github.com` blocked is not great :( Hopefully this is just temporary and you can use a VPN meanwhile.

**Comment by jedisct1** [comment]
[Staticaly](https://staticaly.com/) can also come in handy to access GitHub if it is blocked.
