### ISSUE TITLE
About google server

### ISSUE THREAD

**Issue by ysz223** [DNSCrypt/dnscrypt-proxy#91]
After installing google server, webpage can not be opened, why is this so?

**Comment by jedisct1** [comment]
Can you see the https://dns.google.com webpage?

**Comment by ysz223** [comment]
Under normal circumstances can not open https://dns.google.com , can not open the network environment can not be used?

**Comment by jedisct1** [comment]
If you block Google, but need to access Google, you will be blocked, so you won't access Google.

**Comment by ysz223** [comment]
Are networks in certain countries around the world that do not have regular access to Google services and are there ways to use Google's DNS in this country's networked environment?

**Comment by jedisct1** [comment]
Probably not. If Google is blocked, the Google DNS services are blocked too, even more when they are served over HTTPS like Google websites.

**Comment by ysz223** [comment]
However, when I directly 8.8.8.8 and 4.4.4.4 replacement can be used on the system, which is why?

**Comment by jedisct1** [comment]
Maybe because HTTP is filtered but not UDP yet. This is just a question of time.
