### ISSUE TITLE
Dnscrypt-proxy will use some ports which I have reserved for specific usage. 

### ISSUE THREAD

**Issue by hongyi-zhao** [DNSCrypt/dnscrypt-proxy#911]
Hi,

I use the latest git version of dnscrypt-proxy on my Debian 9 box.  At the same time, I also run the haproxy on the same box, and I want to reserve some specific ports for using by haproxy.  For this purpose, I do the the following setting by using net.ipv4.ip_local_reserved_ports:

$ sudo sysctl net.ipv4.ip_local_reserved_ports
net.ipv4.ip_local_reserved_ports = 8886-8890,10001-15000

But, some times, the dnscrypt-proxy still will use the above ports for dns query.  See the  following info on my box:

werner@localhost:~$ lsof -i :8889
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnscrypt- 1971 werner   70u  IPv4 303785      0t0  TCP localhost:6077->localhost:8889 (CLOSE_WAIT)

When I meet this case, the haproxy will fail to binding the corresponding port, so will failed to start.  And even I kill the above process:

$ kill 1971

Still I can find the  port will not be released immediately, see following:

werner@localhost:~$ netstat -anp | grep ":8889"
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:8889          127.0.0.1:6077          TIME_WAIT   - 

Whether this is a bug of dnscrypt-proxy?  How to solve this issue?
 
Regards

Hongyi

**Comment by jedisct1** [comment]
You know Linux way better than I do, so I can't really help here.

What is listening to `localhost` on port `6077`?

Maybe you can use a different local IP for `dnscrypt-proxy` than `127.0.0.1`?

**Comment by hongyi-zhao** [comment]
The 6077 is the local port which dnscrypt-proxy listening on:

werner@localhost:~$ lsof -i :6077
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnscrypt- 2032 werner    3u  IPv4  42130      0t0  UDP localhost:6077 
dnscrypt- 2032 werner    5u  IPv4  42131      0t0  TCP localhost:6077 (LISTEN)
werner@localhost:~$ pgrep -af 6077
2032 /usr/local/sbin/dnscrypt-proxy -config config/dnscrypt-proxy_tcp_arvind-io_6077.toml

**Comment by hongyi-zhao** [comment]
In the config/dnscrypt-proxy_tcp_arvind-io_6077.toml, I use the following setting:

listen_addresses = ['127.0.0.1:6077']

**Comment by hongyi-zhao** [comment]
I will see so many local ports are using in the state: CLOSE_WAIT:

werner@localhost:~$ lsof -i :6077
COMMAND     PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
dnscrypt- 38260 werner    3u  IPv4 1637858      0t0  UDP localhost:6077 
dnscrypt- 38260 werner    5u  IPv4 1637859      0t0  TCP localhost:6077 (LISTEN)
dnscrypt- 38260 werner    8u  IPv4 1866216      0t0  TCP localhost:6077->localhost:12433 (CLOSE_WAIT)
dnscrypt- 38260 werner   15u  IPv4 1805860      0t0  TCP localhost:6077->localhost:41418 (CLOSE_WAIT)
dnscrypt- 38260 werner   22u  IPv4 1875022      0t0  TCP localhost:6077->localhost:23886 (CLOSE_WAIT)
dnscrypt- 38260 werner   23u  IPv4 1875030      0t0  TCP localhost:6077->localhost:41583 (CLOSE_WAIT)
dnscrypt- 38260 werner   28u  IPv4 1805288      0t0  TCP localhost:6077->localhost:57899 (CLOSE_WAIT)
dnscrypt- 38260 werner   29u  IPv4 1875071      0t0  TCP localhost:6077->localhost:8335 (CLOSE_WAIT)
dnscrypt- 38260 werner   32u  IPv4 1875086      0t0  TCP localhost:6077->localhost:65002 (CLOSE_WAIT)
dnscrypt- 38260 werner   34u  IPv4 1831734      0t0  TCP localhost:6077->localhost:58870 (CLOSE_WAIT)
dnscrypt- 38260 werner   35u  IPv4 1877178      0t0  TCP localhost:6077->localhost:35148 (CLOSE_WAIT)
dnscrypt- 38260 werner   42u  IPv4 1884247      0t0  TCP localhost:6077->localhost:29985 (CLOSE_WAIT)
dnscrypt- 38260 werner   46u  IPv4 1831828      0t0  TCP localhost:6077->localhost:21209 (CLOSE_WAIT)

**Comment by jedisct1** [comment]
The port numbers you are seeing on the right side are source ports from connecting clients.

`dnscrypt-proxy` doesn't have anything to do with these. The only port it listens to is `6077`.

You need to take a look at the clients connecting to `dnscrypt-proxy`. Since `6077` is a funky port number and Linux doesn't support DNS resolution on non-standard port, there is another piece in the puzzle that you didn't talk about.

And this is what is connecting to `dnscrypt-proxy`, and what uses source ports that don't pay attention to `net.ipv4.ip_local_reserved_ports`.
