### ISSUE TITLE
Poor rtt on connect, resolving is fine, only some places

### ISSUE THREAD

**Issue by dnscrypt-ca** [DNSCrypt/dnscrypt-proxy#912]
I have a cron'ed script on my web server that basically connects to my own two DNSCrypt servers with dnscrypt-proxy, attempts to resolve a name, compares the current test status with what is shown on my web site, makes any necessary changes to the status listed on my site, and emails me whenever changes happen.  This script has been working fine for a while.  A couple days ago I started getting lots of automated notifications from this script that my servers were going up and down like crazy, even though they have been functioning normally the whole time.  And now for the rabbit hole...

I found that my web server was having a hard time connecting with dnscrypt-proxy to my servers (OVH Montreal), has terrible rtt times, and sometimes will timeout.  Strangely once it is connected, name resolution seems fine.  After a pile of hair yanking and trying dnscrypt-proxy everywhere I could, here is what I seem to have:

site | machine | os | has problem
-- | ---------------------- | ------------------- | ---
1 | VM on i5 laptop | Devuan ASCII | yes
1 | C2D desktop | Debian Stretch | yes
1 | i5 desktop | Win 7 | yes
2 | i3 laptop | Win 7 | yes
3 | i5 desktop | Debian Jessie | no
3 | Banana Pi M1 | Bananian | no

All three sites are connected to [Teksavvy](https://teksavvy.com/), Site 1 and Site 2 are both 15Mbit DSL while Site 3 is unreliable 6Mbit DSL in the woods (I am actually lucky to get 4Mbit on a good day).  So the least powerful device on the crappiest Internet connection is the one that works, and gets consistent 25ms to 30ms rtt times... while the fastest hardware on the best Internet connection is getting all kinds of times and sometimes timeouts.  I keep reconnecting over and over and sometimes I'll get both servers at 30ms or so, sometimes I get one or the other at 500ms+, and sometimes one or both will timeout.

I am testing by downloading a fresh dnscrypt-proxy v2.0.25, copying the example .toml file to dnscrypt-proxy.toml, adding the following two lines:

> server_names = ['dnscrypt.ca-1', 'dnscrypt.ca-2']
> listen_addresses = ['127.0.0.99:53']

and running ./dnscrypt-proxy directly.

If I do not specify my own servers and allow the client to connect to all servers (whatever the defaults are) then on the "working" machines at site 3 I get rtt times below 300ms for pretty much all servers it is able to connect to.  On the "non working" machines (everything at Site 2 and Site 3) I get 4 to 6 timeouts and a half dozen servers at over 500ms.

The router at Site 2 is about a year old and is the one provided by Teksavvy (I am not in a position of political authority to change this one).  The router at Site 1 was the C2D machine with Stretch and some iptables rules to enable masq'ing and forwarding, it has been since changed out with a basic DLink device with default firmware, but that didn't seem to affect the problem at all.  The router at Site 3 is a Asus RT-N12 with dd-wrt on it.

Based on all this it seems the problem is not router specific or ISP specific or hardware specific and it doesn't even seem to be limited to my servers.  The problem does however seem to be at two specific locations.  Both the "problem locations" do not seem to have any other trouble with latency, and even leaving a ping running from the web server at Site 2 to dns1.dnscrypt.ca provides very stable times in the high 20's and low 30's.

Has anyone seen anything even close to this before, and is there any kind soul who might be willing to run the test and connect to dnscrypt.ca-1 and dnscrypt.ca-2 a bunch of times to see if they can reproduce this (preferably from somewhere other than Teksavvy)?  Is there any test I can run to narrow down why this is happening?

**Comment by jedisct1** [comment]
What does a `traceroute` show from these different hosts? Maybe there is congestion at one of the transit providers.

**Comment by dnscrypt-ca** [comment]
Hey Frank, thanks for the reply.  Here's a sample of traceroutes:
```
1  192.168.0.1 (192.168.0.1)  1.262 ms  1.755 ms  2.500 ms
2  lo0-0-lns04-tor.teksavvy.com (206.248.155.241)  20.962 ms  20.840 ms  24.604 ms
3  ae1-2140-bdr01-tor2.teksavvy.com (69.196.136.138)  44.463 ms  24.501 ms ae0-2150-bdr01-tor.teksavvy.com (69.196.136.172)  27.820 ms
4  * * ae12-0-bdr01-tor.teksavvy.com (206.248.155.10)  30.927 ms
5  * 192.99.146.163 (192.99.146.163)  42.954 ms *
6  192.99.146.163 (192.99.146.163)  42.881 ms *  37.527 ms
7  * * *
8  * * *
9  * * ip132.ip-192-99-183.net (192.99.183.132)  39.030 ms

 
1  192.168.1.1 (192.168.1.1)  0.577 ms  0.937 ms  1.152 ms
2  lo0-0-lns01-tor2.teksavvy.com (206.248.155.132)  17.955 ms  18.837 ms  20.288 ms
3  ae0-2150-bdr01-tor.teksavvy.com (69.196.136.172)  22.365 ms ae1-2140-bdr01-tor2.teksavvy.com (69.196.136.138)  24.498 ms ae0-2150-bdr01-tor.teksavvy.com (69.196.136.172)  25.724 ms
4  * ae12-0-bdr01-tor.teksavvy.com (206.248.155.10)  28.871 ms *
5  * 192.99.146.163 (192.99.146.163)  41.779 ms *
6  * * *
7  * * *
8  * * *
9  * ip132.ip-192-99-183.net (192.99.183.132)  29.978 ms  31.342 ms
```
The first is from Site 2 (one of the "bad" sites) and the second is from Site 3 (the "working" site).  At the bad site I ran the traceroute a bunch of times and ran dnscrypt-proxy in between each time.  The traceroutes came back consistently with everything below 50ms while the dnscrypt-proxy connections were often between 500ms and 550ms, with the occasional timeout and 1 or 2 in 10 attempts I would get a dnscrypt-proxy rtt value between 30ms and 35ms.

I let a ping [to dnscrypt.ca-1] run while I walked the dog this morning and this is the end of what I came home to:

```
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2700 ttl=52 time=28.3 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2701 ttl=52 time=28.9 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2702 ttl=52 time=29.1 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2703 ttl=52 time=30.7 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2704 ttl=52 time=31.0 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2705 ttl=52 time=30.7 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2706 ttl=52 time=30.1 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2707 ttl=52 time=29.0 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2708 ttl=52 time=29.1 ms
64 bytes from ip132.ip-192-99-183.net (192.99.183.132): icmp_seq=2709 ttl=52 time=28.2 ms
^C
--- dns1.dnscrypt.ca ping statistics ---
2709 packets transmitted, 2708 received, 0% packet loss, time 2717799ms
rtt min/avg/max/mdev = 23.386/30.688/197.918/9.602 ms
```

2709 pings in 45 minutes and not one of them was over 200ms with a clear average right around 30ms.  I then tried to connect to just dnscrypt.ca-1 with dnscrypt proxy a dozen times fairly quickly with a few seconds between attempts and got:

```
38ms
timeout
527ms
513ms
500ms
31ms
32ms
527ms
36ms
timeout
456ms
525ms
```

Which I thought was slightly above average compared to what I have been seeing.  I did the same thing from my PC (30km away from the bad site, on the crappy 4Mbit DSL connection) and all of my connections were under 30ms except one that was 69ms.

I am hoping to setup a laptop at my house this weekend, run the test, take it to the bad site on Monday, rerun the test, and then bring the laptop home and test again to see what that produces.  I'd still be really interested to know if anyone can reproduce this from a non-Teksavvy location.

Do those numbers make any sense at all?  Is there anything different between the way dnscrypt-proxy determines rtt and the way ping does?

**Comment by dnscrypt-ca** [comment]
After various attempts to troubleshoot this, all sites seem to be working now, which is good.  However, I do not have a definitive answer to what exactly the problem was, which sucks. :-(

**Comment by jedisct1** [comment]
Weird :(

ICMP (`ping`) and UDP packets are different protocols and be routed differently. If there is some stateful NAT on the way, the number of states can be reached for a given protocol, not for another.

The benchmark run by dnscrypt-proxy at startup sends actual DNS queries. It doesn't use `ping`.

But well...  glad to hear that everything now appears to be fine :)
