### ISSUE TITLE
DNS requests being timed out after wake from sleep

### ISSUE THREAD

**Issue by hoppingninja666** [DNSCrypt/dnscrypt-proxy#913]
I use Linux Mint Tessa. So, I have been facing this issue for a long time. I use dnscrypt-proxy with dnsmasq. When I put my laptop to sleep, after waking up DNS resolve fails. I have to manually restart dnscrypt-proxy.socket to get it to work. I checked status for dnscrypt-proxy.service. It reported no errors.

**Comment by jedisct1** [comment]
DO NOT USE SYSTEMD SUCKETS.

If you do, you're completely on your own.
