### ISSUE TITLE
dnscrypt-proxy doesn't work after reboot

### ISSUE THREAD

**Issue by Saya47** [DNSCrypt/dnscrypt-proxy#916]
Hello I have followed all steps in the guide for linux ubuntu.
And I got it working just fine and installed it as service.
But now after a reboot it doesn't work anymore!

Trying to resolve:
```
s@ubuntu:~$ nslookup google.com
;; connection timed out; no servers could be reached
```

dnscrypt-proxy is running tho:
```
s@ubuntu:~$ sudo ss -lp 'sport = :domain'
[sudo] password for s: 
Netid State   Recv-Q   Send-Q      Local Address:Port       Peer Address:Port                                                                                 
udp   UNCONN  0        0               127.0.0.1:domain          0.0.0.0:*      users:(("dnscrypt-proxy",pid=701,fd=3))                                       
udp   UNCONN  0        0                   [::1]:domain             [::]:*      users:(("dnscrypt-proxy",pid=701,fd=6))                                       
tcp   LISTEN  0        128             127.0.0.1:domain          0.0.0.0:*      users:(("dnscrypt-proxy",pid=701,fd=5))                                       
tcp   LISTEN  0        128                 [::1]:domain             [::]:*      users:(("dnscrypt-proxy",pid=701,fd=7))      
```
Thanks for your time and effort.

**Comment by jedisct1** [comment]
What is the content of the /etc/resolv.conf file? Maybe you don’t have a DNS resolver configured any more.
It should contain “nameserver 127.0.0.1”

**Comment by Saya47** [comment]
```
s@ubuntu:~$ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 127.0.0.53
```
lol wow it has changed although I had systemd masked to null...
I'm on Ubuntu 18.04.2, I don't understand why this has happened.

```
systemctl stop systemd-resolved
systemctl mask systemd-resolved
```
I'm sorry I didn't pay much attention to the end of instructions. So I think my options are, either lock the resolv.conf file or use dnscrypt with systemd, cause it's systemd that's modifying the file, right?
Because I have uninstalled resolvconf.
Thanks again :D

**Comment by jedisct1** [comment]
Yes, that’s systemd changing this behind your back.

**Comment by r4sas** [comment]
> systemctl mask systemd-resolved

Masking is not enough as for me, systemd starts it anyway (seen that in ubuntu 18.04). I think better disable it fully and re-write resolve.conf.
```bash
sudo systemctl disable systemd-resolved
sudo rm /etc/resolve.conf
echo nameserver 127.0.0.53 | sudo tee /etc/resolv.conf
```
