### ISSUE TITLE
generate-domains-blacklists: Can't upload several blocking-lists

### ISSUE THREAD

**Issue by Decopi** [DNSCrypt/dnscrypt-proxy#919]
@jedisct1 and @r4sas , please help me once again:

The generate-domains-blacklists works like a charm. I was able to deal with lot of lists without issues.

Unfortunately I can't upload the following blocking lists:
https://www.squidblacklist.org/downloads/dg-ads.acl (here is the error message: https://pastebin.com/DCh81AxP).
https://blocklist.site/app/dl/youtube (here is the error message: https://pastebin.com/n6SbG4AH).
https://blocklist.site/app/dl/spam (here is the error message: https://pastebin.com/wZwaKB9n).
https://blocklist.site/app/dl/ads (here is the error message: https://pastebin.com/3L5nHFNR).
https://blocklist.site/app/dl/tracking (here is the error message: https://pastebin.com/iY2ycuZC).

This time I was careful:
- I confirm, all the links above perfectly open in browsers and apparently nothing seems to be blocking them
- I tested in different computers/internet connection and no changes, no upload with generate-domains-blacklists
- I tested link by link alone (avoiding any conflict with other lists)

Am I doing something wrong?
Do these lists above need any special settings?

**Comment by jedisct1** [comment]
Maybe due to abuse, they are blocking all queries coming from Python scripts:

```sh
curl -i -H'User-Agent: Python-urllib/2.7' https://blocklist.site/app/dl/youtube
```

```text
HTTP/2 403
...
<title>Access denied | blocklist.site used Cloudflare to restrict access</title>
```

**Comment by Decopi** [comment]
@jedisct1 sorry I didn't understand your answer. I suppose you meant to say the servers of these blocking lists are limited or blocked specifically for Python' scripts. Right? Anyway, Is there any kind of possible solution?

**Comment by jedisct1** [comment]
You can try the latest version of the script here: https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/utils/generate-domains-blacklists/generate-domains-blacklist.py

But if these servers explicitly set up rules to block Python scripts (and probably other kind of scripts), we should respect their choice, no matter what the reasons are.

**Comment by Decopi** [comment]
@jedisct1 you did the trick. Thks.
The new version works like a charm. All lists uploaded.
My intention is to use the generate-domains-blacklists just once a month. So, no abuse from my side.

But if they block the new version, an alternative might be (manually) to upload and insert these lists into domains-blacklist-local-additions.txt. Right?

**Comment by jedisct1** [comment]
Yeah :(
