### ISSUE TITLE
about resolvconf support on linux

### ISSUE THREAD

**Issue by CNMan** [DNSCrypt/dnscrypt-proxy#92]
running dnscrypt-proxy on raspberrypi,but i need clean /etc/resolv.conf and add `nameserver 127.0.0.1` every reboot.

`/etc/resolv.conf`
```
# Generated by resolvconf
nameserver ISPDNS1 
nameserver ISPDNS2
```
https://packages.debian.org/sid/amd64/dnscrypt-proxy/filelist
`/lib/systemd/system/dnscrypt-proxy-resolvconf.service`
```
[Unit]
Description=DNSCrypt proxy resolvconf support
Documentation=man:dnscrypt-proxy(8)
After=dnscrypt-proxy.socket
Requires=dnscrypt-proxy.socket
ConditionFileIsExecutable=/sbin/resolvconf

[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/bin/sh -c 'systemctl show dnscrypt-proxy.socket \
                    | grep ListenDatagram \
                    | cut -d "=" -f 2 \
                    | cut -d ":" -f 1 \
                    | awk \'{ print "nameserver " $1 }\' \
                    | /sbin/resolvconf -a lo.dnscrypt-proxy'
ExecStop=/sbin/resolvconf -d lo.dnscrypt-proxy

[Install]
WantedBy=multi-user.target
Also=dnscrypt-proxy.socket
```

**Comment by jedisct1** [comment]
Yes, changing the DNS settings on Linux/systemd is complicated.

If you find how to do that (without `chattr +i /etc/resolv.conf`), it would be great to write a documentation page about it.

**Comment by CNMan** [comment]
`/etc/resolvconf.conf`
```
# Configuration for resolvconf(8)
# See resolvconf.conf(5) for details

resolv_conf=/etc/resolv.conf
# If you run a local name server, you should uncomment the below line and
# configure your subscribers configuration files below.
# name_servers=127.0.0.1

# Mirror the Debian package defaults for the below resolvers
# so that resolvconf integrates seemlessly.
dnsmasq_resolv=/var/run/dnsmasq/resolv.conf
pdnsd_conf=/etc/pdnsd.conf
unbound_conf=/var/cache/unbound/resolvconf_resolvers.conf
```
after search and find uncomment `# name_servers=127.0.0.1` works for me.but don't know how to change it via systemd.

`/etc/resolv.conf`
```
# Generated by resolvconf
nameserver 127.0.0.1
```

**Comment by ghost** [comment]
I might be able to help.

In systemd file:

[Resolve]
DNS=127.0.0.1
FallbackDNS=(optional, and repetitive because of fallback_resolver in .toml)

Then in your \*.network configuration file (/etc/systemd/network/*.network)

[DHCP]
UseDNS=false

Documentation is found here: https://www.freedesktop.org/software/systemd/man/resolved.conf.html
