### ISSUE TITLE
dnscrypt.ca Server #2 Relocation

### ISSUE THREAD

**Issue by dnscrypt-ca** [DNSCrypt/dnscrypt-proxy#920]
One of my servers is moving to a new building to help increase fault tolerance.  The new stamps are:

```
dnscrypt.ca-2

Free, Canadian, uncensored, no-logs, encrypted, and DNSSEC validated DNS service for your pleasure.

sdns://AQcAAAAAAAAAETE0OS41Ni4yMjguNDU6NDQzIAEIVKs7Vqfu-dORWP72ggv_k6I1fIkWCNueFdO74BGFHTIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5jYS0y
```

and 

```
dnscrypt.ca-2-ipv6

Free, Canadian, uncensored, no-logs, encrypted, and DNSSEC validated DNS service for your pleasure.

sdns://AQcAAAAAAAAAHFsyNjA3OjUzMDA6MTIwOmI5Yjo6MjAwXTo0NDMgmHxwqJfb2hUaNK1LVeqADvVhzASq1cV90sPYYfwX9CkiMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNhLTItaXB2Ng
```

dnscrypt.ca-1 and dnscrypt.ca-1-ipv6 remain the same.

s.

**Comment by dnscrypt-ca** [comment]
I should add that Server #2 is still available at the current/old address and will remain up for a few days to allow clients time to update their public resolver list.

s.

**Comment by jedisct1** [comment]
The list has been updated!

Hope they will like their new home! :)

**Comment by dnscrypt-ca** [comment]
Excellent, thanks for such a quick reply Frank! (y)

s.

**Comment by jedisct1** [comment]
Anytime.

Have a nice day!
