### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by zypA13510** [DNSCrypt/dnscrypt-proxy#921]
Duplicate of #616 (but I can't reopen or comment).

Use case: I'm installing this on my Synology NAS. I know there is a [package](https://synocommunity.com/package/dnscrypt-proxy) (and it's in the wiki) but unfortunately, that package conflicts with the official "DNS Server" package, which happens to be a dependency of the official AD (Active Directory) Server package.

So now the most promising option for me is the docker engine. I know there're many dockerfiles in the wild, I've even written one myself. But I think a maintained and updated official image would be better, right? We have [dnscrypt-server](https://hub.docker.com/r/jedisct1/dnscrypt-server) and why we can't have dnscrypt-proxy?

If you will accept, I'm willing to get a PR ready.

**Comment by jedisct1** [comment]
The maintained and updated official image can be yours!

I have no use for docker client-side, and can't even install Docker on my router. So it would be better maintained as a separate project, by someone who actually uses it :)

If you feel like your image is the best, and are committed to keeping it updated, feel free to add it to the Wiki!

**Comment by zypA13510** [comment]
Why an **official** image can be beneficial:
* Seamless build integration - the build can run in the same CI pipeline, thus pushing newer images can be completely automated. No need to watch the release page to manually build a new image and push.
* Recognition and more contribution - most of the times, dockerfiles in spin-off repositories fail to gather enough recognition (e.g. GitHub stars), and when their maintainers have to stop working on them for various reasons, they are dead. Whereas an official repo usually attracts more contributors.

**Comment by jedisct1** [comment]
Yes, totally !

But I'm not a Linux user, so I'm just not the one who will do it, test it, keep it up to date, document it and answer tickets about it.

If you are willing to commit to this, go ahead :)

**Comment by PeterDaveHello** [comment]
I can do it.

**Comment by PeterDaveHello** [comment]
@jedisct1 would you consider to move this project into @DNSCrypt this time?

**Comment by PeterDaveHello** [comment]
@jedisct1 can you also grant me admin permission on this repo so that I can hook it with Docker hub?

**Comment by jedisct1** [comment]
Sure!

But now that GitHub Packages exists, maybe we can use it instead of the Docker Hub for new packages?

**Comment by PeterDaveHello** [comment]
It's still in beta stage, we can try to use both maybe.

**Comment by hostmaster** [comment]
It would be good to start small probably. Simply a `Dockerfile` would be a good start. It has no dependencies on a specific docker infrastructure.

**Comment by jedisct1** [comment]
Maybe a good starting point: https://hub.docker.com/r/klutchell/dnscrypt-proxy

**Comment by hostmaster** [comment]
@jedisct1 it seems to me that https://github.com/klutchell/dnscrypt-proxy is excellent and high quality.  I believe @klutchell 's great work deserves the "official" badge.
