### ISSUE TITLE
Help: Question about Cloaking/Forwarding

### ISSUE THREAD

**Issue by Decopi** [DNSCrypt/dnscrypt-proxy#922]
By using Cloaking/Forwarding, I tried to redirect www.reddit.com to old.reddit.com
Unfortunately I failed.
I tested with many wildcards combinations.

Is there a way to do that?

Thks!

**Comment by jedisct1** [comment]
DNS cannot change website names, only IP addresses. If www. and old. have the same IP addresses (and I think they do), cloaking cannot work.
