### ISSUE TITLE
Feature request: support a set of fallback resolvers

### ISSUE THREAD

**Issue by Thermi** [DNSCrypt/dnscrypt-proxy#926]
the connectivity check should support IPv4 and IPv6. If a site is by chance IPv6 only, the dnscrypt-proxy configuration needs to be manually changed in order to make use of it (in the absence of any 6-to-4 transition technologies).

**Comment by jedisct1** [comment]
Can you clarify what you were trying to do, what happened and what you would have expected to happen instead?

The connectivity check doesn't do anything with IPv4 or IPv6, it checks that the network interface can be used.

**Comment by Thermi** [comment]
Sorry, I was writing from memory and it was wrong. It actually pertains the fallback_resolver. In my case, a fritzbox provides DNS and other services (DHCP, Internet Gateway using AFTR (4in6)) to the LAN. The 4in6 tunnel was down, which, it seems, the fritzbox also uses to resolve DNS requests. So the default DNS server did not work and the configured fallback_resolver also didn't. IPv6 itself still worked though.

**Comment by jedisct1** [comment]
You can use an IPv4 address as the fallback resolver, and keep the IPv6 resolver on the router (fritzbox?).

**Comment by Thermi** [comment]
Well, in that failure mode, the resolver on the fritzbox is unusable because it depends on IPv4 network access, which failed. If it was possible to use a list of resolvers in the fallback_resolver setting and Ipv6 addresses (haven't tried that yet), it wouldn't be a problem anymore.

**Comment by jedisct1** [comment]
`fallback_resolver` only supports one resolver, but you can put an IPv6 address here.

**Comment by Thermi** [comment]
Yes and if my system roams into an IPv4 only network with a broken default DNS resolver, I'll have to edit the config again. It seems kind of redundant to do so and not have this feature.

**Comment by jedisct1** [comment]
Some people may want to use IPv6 even if IPv4 is available, or the other way round.

I'd rather leave these choices as settings than introduce some magic, that will add complexity for little gains.

**Comment by Thermi** [comment]
> Some people may want to use IPv6 even if IPv4 is available, or the other way round.

How does my proposal prevent a user from doing that?

> I'd rather leave these choices as settings than introduce some magic, that will add complexity for little gains.

It'd still be a setting and there weren't any magic. Right now dnscrypt-proxy needs manual intervention if DNS is broken on the network and the fallback_resolver isn't reachable. The proposal would just allow users to add a second DNS server, possibly with a different protocol family, so such a failover is possible.

**Comment by jedisct1** [comment]
Got it. I was confused by all these details, that fritzbox thing (I have no idea what it is) and the issue title.

So, if I understand correctly, what you want is something like `fallback_resolvers`, that would accept a list of fallback resolvers.

And maybe try the first one, and if it times out, use the next one for future queries, and if we are using the last one of the list and it fails, start with the first one again.

Can you implement and document this?

**Comment by Thermi** [comment]
Yes, kind of like that. It'd make sense to try them in a RR fashion. I'll need to improve my Golang game to do that, but it shouldn't be a problem.

Fritzbox is a brand of home modems and routers made by AVM, primarily used in Germany.
