### ISSUE TITLE
Unable to use source [public-resolvers] ... EOF

### ISSUE THREAD

**Issue by mystiquewolf** [DNSCrypt/dnscrypt-proxy#929]
Installed via apt install dnscrypt-proxy. Ubuntu 19.04. dnscrypt-proxy 2.0.19+ds1-2. Sometimes when i start the computer it says this and i have to restart the service via systemctl manually, after that it runs okay. Happens just sometimes.

![image](https://user-images.githubusercontent.com/16529989/64906143-16d18800-d6eb-11e9-80e4-ec377e352d5d.png)

**Comment by jedisct1** [comment]
Uninstall everything and try a more recent version using the generic installation instructions for Linux. https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux
