### ISSUE TITLE
[ISSUE] WiFi hotspot - Too many connections

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#93]
### Too many connections

Problem exists since beta-stage. 100% reproductive. Win8.1 [x64]
I didn't find troubles on my side searching my OS/Firewall settings, so I decide open issue topic now.

If I will start WiFi hotspot (using standard Microsoft Virtual Adapter) on PC to share Internet, dnscrypt-proxy will stuck on PC after 2-3 minutes. Errors in log ( `log_level = 0` ):

```
[WARNING] Too many connections (max=250)
... lot of lines ...
```
If I've stop and turn off WiFi hotspot completely, this doesn't help, PC still continue generating errors` Too many connections`. In such situation I can fix it with **reinstalling** the service (restarting doesn't help).

_Note:_ I've never had self- `Stopped` message (like other people on routers), until I restart the service manually.

----------------------------------------------

### About another known error: `No items in the list` :

Just remind you. Nothing was changed since my two already closed reports about this issue.

I still have this error using **any** *.bat command.
This error-message goes first, then common dnscrypt-proxy messages at the bottom.

**(Some early-middle betas didn't have such problems)**

**Comment by GrizzlyJr** [comment]
change your max_clients = 250 on dnscrypt-proxy.toml. try 4 times from default to max_clients = 1000 or 10 times to max_clients = 2500. FYI, mine max_clients = 10000.

**Comment by iWARR** [comment]
@GrizzlyJr 

Thanks, I've understand the way of benchmark. But what are suggested values for 2-5 devices at small network, before I start? How many clients you have for the `10000` value?

**Comment by jedisct1** [comment]
Not sure what you are doing, but I hardly have more than 10 simultaneous connections.
You must have a loop or something.

**Comment by iWARR** [comment]
@jedisct1 

Tested with 10000. It's stuck, but this time  with no any `[WARNING]` in the log.
Working a few minutes longer. 1 PC, 1 smartphone.

> You must have a loop or something.

May be yes, may be no. Never didn't have such trouble with v1.
However, my Firewall rules changing and improving also...
So, can't say for sure.

_Additional info:_ If connection stuck, I see that something trying resolve network with Google DNS. I think, it's a Browser. But, really, it's doesn't matter, because Google DNS are blocked forever with Firewall.

**Comment by jedisct1** [comment]
Try `ignore_system_dns = true` maybe.

**Comment by iWARR** [comment]
### Downgraded to v1.9.5 - NO ISSUES (same OS settings & Firewall settings)

v1.9.5 tested, works and doesn't break dnscrypt-proxy service connection, when WiFi hotspot is running.
So, you can move this thread from `Closed` to `Open` **Issues** again.

(And with v1 WiFi connection establishes a bit faster, I think)

-------------------------

**P.S.** Working link for freshy `dnscrypt-resolvers.csv` (that much more informative compared to *.md) is wanted.

**Comment by iWARR** [comment]
**2.0.0 Final - Working & Fast! (But still have some ISSUES)**

- WiFi connecton fixed. No breaks with dnscrypt-proxy service.
  Connection on mobile devices establishes fast and working fast! Thanks!

- Overall speed increased. The Browser make connection faster. Thanks!

- Still have strange message with *.bat : `No items in the list`

-  **[ISSUE] : In this version the `log file for the application` was not created in some case!**

```
## log file for the application

log_level = 0
log_file = 'C:\Program Files\dnscrypt-proxy\log\Connections.log'

## Use the system logger

use_syslog = true
```

**Comment by iWARR** [comment]
### Sorry, but it stuck.

 This time it worked longer time without issues, but suddenly dnscrypt-proxy lost connection (hotspot + Local Network).

**Comment by iWARR** [comment]
- When I launch dnscrypt-proxy with commands, there is no error `No items in the list`.
  So, I guess, the `*.bat` files have some incompatible lines for Windows.

  And I have to press `Ctrl+C` to exit from scenario. Why it says `[RETURN]`?

- log file for the application was not created because I had `use_syslog = true` turned on.
  I guess, I have to use **or** Windows system logger **or** application log only?
  Is this "by design" to avoid slowdowns?

- What kind of parametes I can play with, to try troubleshoot disconnections? May be some connection tweaking with `max_clients / timeout / ttl` ? Which one parameters I can try turn off for "exlcude" testing?

  (In 2.0.0 my disconnections often happens after ~1,5 hours, basicly, when IDLE. (All power saving options on Network adapters are tured off on my mashine). Never had such troubles through the years.

**Comment by jedisct1** [comment]
Yes, logs are either printer, or stored in a file, or send to the system logger.

**Comment by iWARR** [comment]
### v2.0.2 - OK!

This version works nice! I don't have "Too many connections" issue any more.
Local Network works, no dnscrypt-proxy service disconnections on my "Server"-machine.
Just my report to you. Thanks!

**Comment by jedisct1** [comment]
Great!
