### ISSUE TITLE
DNS over TCP /etc/resolv.conf 'options use-vc' broken

### ISSUE THREAD

**Issue by adrelanos** [DNSCrypt/dnscrypt-proxy#930]
Using the Debian package https://packages.debian.org/buster/dnscrypt-proxy I cannot make dnscrypt-proxy work when `/etc/resolv.conf` contains

    options use-vc

DNS stops working completely.

`/lib/systemd/system/dnscrypt-proxy.socket` contains by debian default already

```
[Socket]
ListenStream=127.0.2.1:53
ListenDatagram=127.0.2.1:53
```

And `/etc/dnscrypt-proxy/dnscrypt-proxy.toml` already contains

    listen_addresses = []

Using `force_tcp = true` in config does not help either.

**Comment by jedisct1** [comment]
Maybe TCP doesn't work when sockets are handled by systemd? I have no idea. 

Try removing `dnscrypt-proxy.socket` and put `127.0.2.1:53` in `listen_addresses` instead.

**Comment by adrelanos** [comment]
Tried that.

    sudo systemctl mask dnscrypt-proxy.socket
    sudo reboot

> Sep 16 07:07:27 host dnscrypt-proxy[603]: [2019-09-16 07:07:27] [FATAL] listen udp 127.0.2.1:53: bind: permission denied

No firejail / no apparmor for dnscrypt-proxy.

`sudo netstat -tulpen` does not show anything already listening there.

**Comment by jedisct1** [comment]
The package probably installs its own systemd file that prevents you from using the configuration file.

Remove any trace of `dnscrypt-proxy`, and follow the generic Linux installation instructions: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux
