### ISSUE TITLE
[Feature request] Disable HINFO responces

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-proxy#932]
I want to hide what DNS server I use in responses. It's shows when IPv6 is blocked or when refused requests looks like as HINFO. Can you set NXDOMAIN instead HINFO or disable this messages?

in **dnsutils.go**:
`hinfo.Cpu = "This query has been locally blocked"`
`hinfo.Os = "by dnscrypt-proxy"`

in **plugin_block_ipv6.go**:
`hinfo.Cpu = "AAAA queries have been locally blocked by dnscrypt-proxy"`
`hinfo.Os = "Set block_ipv6 to false to disable this feature" `

**Comment by jedisct1** [comment]
Look for "hinfo" in the configuration file, not in the source code :)

**Comment by black-cerberon** [comment]
In config it can be set REFUSED or HINFO or IP as responce. How it set with custom HINFO or void message like it?
`hinfo.Cpu = ""`
`hinfo.Os = ""`

**Comment by jedisct1** [comment]
You can't send a custom `HINFO`, but `REFUSED` shouldn't send any records besides the question.

**Comment by black-cerberon** [comment]
Anyway, if `block_ipv6=true` and `blocked_query_response='refused'`, then return `HINFO`

**Comment by black-cerberon** [comment]
Also, if it set to `blocked_query_response='a:127.0.0.1,aaaa:::1'`, `MX` return as `HINFO`

`>host mc.yandex.ru`
`mc.yandex.ru has address 127.0.0.1`
`mc.yandex.ru has IPv6 address ::1`
`mc.yandex.ru host information "This query has been locally blocked" "by dnscrypt-proxy"`

**Comment by jedisct1** [comment]
Since we are not returning the correct answer, having an extra record justifying why is useful, if only for troubleshooting purpose.
If you really want a different message, the best option is to change these, and you already found how to do it :)
