### ISSUE TITLE
DNSCrypt listen on 127.0.0.1 instead of 127.0.2.1

### ISSUE THREAD

**Issue by adrelanos** [DNSCrypt/dnscrypt-proxy#934]
`/lib/systemd/system/dnscrypt-proxy.socket` uses

    ListenStream=127.0.2.1:53
    ListenDatagram=127.0.2.1:53

Mandatory access control (MAC) with firejail caused an issue.

https://github.com/netblue30/firejail/issues/2966

However if DNS was listening on IP 127.0.0.1 port 53 it would work since this is the standard DNS listener.

Why does DNSCrypt listen on `127.0.2.1` and not on `127.0.0.1` by default?

**Comment by jedisct1** [comment]
`dnscrypt-proxy` doesn't install any file called `dnscrypt-proxy.socket`, so that has to be something that was installed by some 3rd party package.

Remove it, and you can configure what addresses to listen to in the `dnscrypt-proxy.toml` file.
