### ISSUE TITLE
query log not able to log stdout. (docker)

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#935]
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Logging
I am using dnscrypt-proxy with docker, i want log just stdout , so i can using `docker logs` to check the query log.

**Comment by jedisct1** [comment]
Maybe you can simply run `tail -F /tmp/query.log`?

**Comment by ghost** [comment]
because it was docker  , we do not want the log file use much more disk size. just send them into stdout, docker will manage the log size.

**Comment by ghost** [comment]
May be i need fork and maintain a lighter version of dnscrypt-proxy, no log file need.

**Comment by jedisct1** [comment]
Logging to `/dev/stdout` works :)

```toml
log_files_max_size = 0

[query_log]
file = '/dev/stdout'
```

**Comment by ghost** [comment]
Thanks. it works.
