### ISSUE TITLE
[ANNOUNCE] New DNSCrypt server proxy

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#937]
[Encrypted DNS Server](https://github.com/jedisct1/encrypted-dns-server) (that really needs a better name) is a new proxy to run your own DNSCrypt server, written in Rust.

Some advantages over `dnscrypt-wrapper`:

- Very easy to setup. No need for external scripts. It automatically generates a provider key pair if there isn't any, and automatically generates and rotates certificates as well.
- It can detect and redirect TLS traffic. So you can run a DNSCrypt and a web server on the same IP and port. Or a DNSCrypt and DoH server, all on port 443.
- It can listen to multiple IP addresses simultaneously (e.g. IPv4 and IPv6).

Most importantly, it will soon support the IP hiding [Anonymized DNSCrypt](https://raw.githubusercontent.com/DNSCrypt/dnscrypt-protocol/master/ANONYMIZED-DNSCRYPT.txt) extension, and eventually have a built-in DoH server, that handles TLS certificates with zero configuration via Let's Encrypt.

It will also probably soon include a DNS cache ([EDIT]: Done), the ability for clients to authenticate before they can use the service, as well as Prometheus metrics.

And if you are currently running `dnscrypt-wrapper`, your keys can be imported.

This is still very new, but if you feel brave, give it a try!

**Comment by ghost** [comment]
>encrypted-dns-server (that really needs a better name)

It's easy to rename existing repos, if you are willing to accept community suggestions here:
* dnscrypt-[adapter](https://en.wikipedia.org/wiki/Adapter_pattern) is a common synonym for wrapper
* dnscrypt-tunnel would be reasonable
* however I'd prefer dnscrypt-exitnode, as a polite nod to TOR, unless the term is too loaded
* okay tier: dnscrypt-provider

**Comment by jedisct1** [comment]
Thanks for your suggestions, @mkirisame !

Maybe we can find something that also conveys the fact that it will support more protocols than DNSCrypt.

**Comment by jedisct1** [comment]
`scaleway-fr` was migrated to the new software last night, and it made a huge difference on latency and the number of `SERVFAIL`.

**Comment by ghost** [comment]
And my thanks for your work, if you allow one more post, I don't want to get spammy:
SecureDNS is a nice name prefix, it is currently used by a community member though:
https://securedns.eu/#about
Crypt or secure is just shorter and nicer than encrypted. I'll go back to lurking now and hope more people will chime in with their ideas.

**Comment by dnscrypt-ca** [comment]
> Most importantly, it will soon support the IP hiding [Anonymized DNSCrypt](https://raw.githubusercontent.com/DNSCrypt/dnscrypt-protocol/master/ANONYMIZED-DNSCRYPT.txt) extension, and eventually have a built-in DoH server, that handles TLS certificates with zero configuration via Let's Encrypt.

Do I understand correctly that once Encrypted DNS Server [by any name other than Rose] has a built-in DoH server, then cargo, rust-doh, nginx, and certbot are all no longer going to be external requirements?  And that a single native executable will be the only thing needed to run both DNSCrypt and DoH services with automated key rotation on both IPv4 and IPv6 of a single server?

s.

**Comment by jedisct1** [comment]
@dnscrypt-ca Yes, exactly.

Setting up an encrypted DNS server should be as simple as possible.

**Comment by dnscrypt-ca** [comment]
Please excuse my Canadian but... Wow, that sounds awesome eh!

If I may put forth a naming suggestion: NameCrypt or namecrypt-server.  It is a bit of a nod to DNSCrypt, and at the same time refers to multiple encryption techniques used with name servers.

**Comment by ghost** [comment]
This is incredible. Thank you. From the n00b perspective (which is my perspective). I suggest DNSCrypt-Server as it follows and makes since because I am using the DNSCrypt-Proxy on my Mac. If there ever is a dedicated APP (other than DNSCloak), then DNSCrypt-iOSAPP or DNSCrypt-MacAPP so I don't have to run terminal...

**Comment by jedisct1** [comment]
Updated docker images are now available. Instead of checking out `jedisct1/dnscrypt-server:latest`, you can check out `jedisct1/dnscrypt-server:beta` to use it.
