### ISSUE TITLE
No support for DoT

### ISSUE THREAD

**Issue by ivar-it** [DNSCrypt/dnscrypt-proxy#938]
Hello,

I have setup a own DoT server and trying to use DNScrypt to connect to it.

I have made a stamp for that 

```
openssl asn1parse -in /etc/letsencrypt/live/pihole.haxx.info/chain.pem -out /dev/stdout -noout -strparse 4 | openssl dgst -sha256
(stdin)= 3e1a1a0f6c53f3e97a492d57084b5b9807059ee057ab1505876fd83fda3db838

python3 dnsstamp.py dot -a 185.35.200.250 -n pihole.haxx.info -t 3e1a1a0f6c53f3e97a492d57084b5b9807059ee057ab1505876fd83fda3db838

DoT DNS stamp

DNSSEC: no
No logs: no
No filter: no
IP Address: 185.35.200.250
Hostname: pihole.haxx.info
Hashes: ['3e1a1a0f6c53f3e97a492d57084b5b9807059ee057ab1505876fd83fda3db838']
Bootstrap IPs: []

sdns://AwAAAAAAAAAADjE4NS4zNS4yMDAuMjUwID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4EHBpaG9sZS5oYXh4LmluZm8

```

But when adding the stamp to the .toml config and trying to start i get this error.

`PS C:\Users\mrper\Desktop\win64> .\dnscrypt-proxy.exe
[2019-09-21 18:10:47] [NOTICE] dnscrypt-proxy 2.0.27
[2019-09-21 18:10:47] [NOTICE] Network connectivity detected
[2019-09-21 18:10:47] [NOTICE] Source [public-resolvers.md] loaded
[2019-09-21 18:10:47] [FATAL] Stamp error for the static [pihole] definition: **[Unsupported stamp version or protocol]**`

Why is this not working? :|

**Comment by jedisct1** [comment]
I was about to respond, but since the title was changed, looks like you figured it out by yourself :)

DoT is not supported, you need to upgrade to DNSCrypt or DoH.

**Comment by uBlock-user** [comment]
You can use https://github.com/AdguardTeam/dnsproxy if you want DoT specifically.
