### ISSUE TITLE
Help wanted: DNSCrypt 2.0.27 won't start on Raspberry Pi

### ISSUE THREAD

**Issue by Coder84619** [DNSCrypt/dnscrypt-proxy#939]
I'm using Ryan Erickson's blogpost on how to configure DNSCrypt for my Raspberry Pi. I made it through the entire post, using DNSCrypt 2.0.27, but I get an exception error when it starts:

pi@raspberrypi:~/dnscrypt-proxy $ sudo systemctl status dnscrypt-proxy

● dnscrypt-proxy.service - Encrypted/authenticated DNS proxy

Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)

Active: activating (auto-restart) (Result: exit-code) since Sun 2019-09-22 19:13:38 BST; 18s ago

Process: 2346 ExecStart=/opt/dnscrypt-proxy/dnscrypt-proxy (code=exited, status=255/EXCEPTION)

Main PID: 2346 (code=exited, status=255/EXCEPTION)

I'm not sure what's wrong or where to go to troubleshoot. I've reset the dnscrypt-proxy.toml file a number of times and only made two changes from the template (for troubleshooting):

I uncommented the server_names and left all the default names (I want to only use dnscrypt.nl-ns0 eventually, but just want to get it working up front). And I changed the listening address to use my real local IP but use port 5353 (unused). I've also tried 127.0.0.1:5353, with no luck.

What can I do to troubleshoot what's going on?

TIA.

**Comment by sondr3** [comment]
Just hit the same snag on my Raspberry Pi 3. System information:

```
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
```

EDIT: Version 2.0.25 works fine, but I couldn't get 2.0.26 og 2.0.27 to start.
EDIT2: Nevermind, seems I just used the wrong port? I changed from `5353` to `5300` and now 2.0.27 works again.

**Comment by Coder84619** [comment]
I've tried 5353, 5300 and other ports to no avail.

**Comment by jedisct1** [comment]
Run it directly from the command line (not as a background service), it will print what's wrong.
