### ISSUE TITLE
[FATAL] listen udp 127.0.0.1:53: bind: Only one usage of each socket address

### ISSUE THREAD

**Issue by kraith** [DNSCrypt/dnscrypt-proxy#940]
```text
PS C:\dnscrypt> .\dnscrypt-proxy
[NOTICE] dnscrypt-proxy 2.0.27
[NOTICE] Network connectivity detected
[NOTICE] Source [public-resolvers.md] loaded
[NOTICE] Firefox workaround initialized
[FATAL] listen udp 127.0.0.1:53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

In `query.log` `server_name parse error`
Using `resmon`, only `dnscrypt-proxy` is using port `53`
What should I do?
I'm using Win10 1903

**Comment by jedisct1** [comment]
I don't know what `resmon` is, but apparently you need to use the `netstat` command to see what else is already listening to port 443: https://stackoverflow.com/questions/41836209/only-one-usage-of-each-socket-address-protocol-network-address-port-is-normall

**Comment by jedisct1** [comment]
`Using resmon, only dnscrypt-proxy is using port 53`

Since what you posted shows that it didn't start, `dnscrypt-proxy` shouldn't be listening to anything.

Maybe you tried to start it twice, possibly as a service first. If this is the case, stop the service (`./dnscrypt-service stop`).

**Comment by kraith** [comment]
Resmon = resource monitor
```text
Listening Ports     PID      Address   Port  Protocol

dnscrypt-proxy.exe  9156 IPv6 loopback   53   TCP
dnscrypt-proxy.exe  9156 IPv4 loopback   53   TCP
dnscrypt-proxy.exe  9156 IPv6 loopback   53   UDP
dnscrypt-proxy.exe  9156 IPv4 loopback   53   UDP
```
dnscrypt-proxy.exe is start automatically on startup as service  
When I using listen_addresses = [ ], no nore parse_error on log

**Comment by jedisct1** [comment]
So, it's already running. You can't run it again while it's already running.

**Comment by kraith** [comment]
Ok, Thank you for your replies

**Comment by uBlock-user** [comment]
Happens to me every time I restart, because I run two IPv4 addresses on the same port eg port 53
