### ISSUE TITLE
Is ESNI enabled by default when using DoH?

### ISSUE THREAD

**Issue by 35609902357** [DNSCrypt/dnscrypt-proxy#941]

**Comment by ghost** [comment]
No my friend, DoH does **not** encrypt SNI header.

![DOH_TEST](https://user-images.githubusercontent.com/37766263/65829119-136cfd80-e2a2-11e9-98a6-b1827e9f46f7.png)

Please stay safe!

**Comment by 35609902357** [comment]
How can ESNI be enabled in dnscrypt-proxy? Is there a line to write in dnscrypt-proxy.toml?

**Comment by jedisct1** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1500289

**Comment by 35609902357** [comment]
@jedisct1 A bug from Firefox does not address the point. So supposedly dnscrypt-proxy should encrypt SNI by default (even though ESNI checker by CloudFlare doesn't display it), but the image posted by @mkirisame shows SNI is actually unencrypted.

**Comment by jedisct1** [comment]
ESNI doesn't exist yet, it's still being designed.

What exists is an early experiment by Cloudflare and Mozilla, that turned out to be a good marketing tool. The web browser decides whether to enable this or not.

Right now, the rule hardcoded in Firefox is "enable it only if Firefox was configured to directly talk to Cloudflare DNS, and the user tries to connect to a Cloudflare customer".

The linked issue is not a bug. It's about an intentional limitation.

**Comment by uBlock-user** [comment]
https://github.com/DNSCrypt/dnscrypt-proxy/issues/622#issuecomment-432242143

**Comment by Mikaela** [comment]
It can actually be enabled in Firefox by setting `network.security.esni.enabled;true` in `about:config`, but you have to use a DNS-over-HTTPS provider (that doesn't have to be Cloudflare, while that is the only one Firefox ships with). https://bugzilla.mozilla.org/show_bug.cgi?id=1542754#c3 is another bug worth mentioning.

**Comment by jedisct1** [comment]
You don't have to just use a DNS-over-HTTPS provider. You have to configure Firefox to do the resolution itself, bypassing all system settings.

**Comment by 35609902357** [comment]
@Mikaela I'm aware of it, I was hoping to have it at router level to serve all clients. Thank you for pointing it out, and thank you @jedisct1 for your work and @mkirisame for the test. And thank you too @uBlock-user, I read that comment already, but I thought it was just an issue with Cloudflare's website.
