### ISSUE TITLE
Signature mismatch for downloaded files

### ISSUE THREAD

**Issue by 35609902357** [DNSCrypt/dnscrypt-proxy#942]
I tried every package of the 2.0.27 release and all return the same line when I check them with minisig:
both
`minisign -Vm dnscrypt-proxy-*-2.0.27.tar.gz -P RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3`
and
`minisign -Vm dnscrypt-proxy-*-2.0.27.tar.gz -p jedi-minisign.pub`
commands return the following output
`Signature key id in dnscrypt-proxy-*-2.0.27.tar.gz.minisig is 79833371EA15D7E4
but the key id in the public key is E7620F1842B4E81F`

**Comment by jedisct1** [comment]
The documentation is here: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation

The very first page indicates how to verify the signature.
