### ISSUE TITLE
DNSKEY RESPONSE_ERROR on doh-crypto-sx

### ISSUE THREAD

**Issue by TC1977** [DNSCrypt/dnscrypt-proxy#943]
Hi, I'm not sure if it's actually a dnscrypt-proxy error or just a problem with the server. But I'm in the process of tracking down repeated pihole-FTL crashes in my [pihole + dnscrypt-proxy setup](https://github.com/pi-hole/FTL/issues/645), which seem to be caused by some bad data getting passed to the dnsmasq code by dnscrypt-proxy. Tracking the query.log shows that the crashes always happen after a "DNSKEY RESPONSE_ERROR" for the org TLD passed to it by dnscrypt-proxy (but not _every_ time). These messages only seem to get passed by `doh-crypto-sx`, which is [run by](https://download.dnscrypt.info/dnscrypt-resolvers/v2/public-resolvers.md) @jedisct1 .

My setup:
Dell box converted to Ubuntu 18.04.3 LTS
dnscrypt-proxy 2.0.25 (from the shevchuk/shevchuk repo) 
pi-hole 4.3.2 with FTL 4.3.1 (latest versions)
specific config changes:
```
$ diff dnscrypt-proxy.toml dnscrypt-proxy.toml.orig
1,2c1
< # newest changes - turn on log level 2, turn on local log file, also uncomment query log, send to /var/log
< # newest changes Oct 1 - turn off local log file (leave query log), remove doh-crypto-sx
---
> 
31c30
< server_names = ['ventricle.us', 'cloudflare-ipv6', 'cloudflare', `doh-crypto-sx`]
---
> # server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']
37c36
< listen_addresses = ['127.0.2.1:5353','[::1]:5353']
---
> listen_addresses = []
59c58
< ipv6_servers = true
---
> ipv6_servers = false
71c70
< require_dnssec = true
---
> require_dnssec = false
124c123
< lb_strategy = 'p2'
---
> # lb_strategy = 'p2'
134c133
< #log_level = 2
---
> # log_level = 2
139c138
< #log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'
---
> # log_file = 'dnscrypt-proxy.log'
144c143
< use_syslog = true
---
> # use_syslog = true
156c155
< dnscrypt_ephemeral_keys = true
---
> # dnscrypt_ephemeral_keys = false
161c160
< tls_disable_session_tickets = true
---
> # tls_disable_session_tickets = false
200c199
< ignore_system_dns = true
---
> ignore_system_dns = false
331c330
<   file = '/var/log/dnscrypt-proxy/query.log'
---
>   # file = 'query.log'
```

query log right before and after two most recent crashes:
```
[2019-09-29 16:37:03]	::1	play.google.com	A	PASS	24ms	ventricle.us
[2019-09-29 16:37:03]	::1	play.google.com	AAAA	PASS	28ms	ventricle.us
[2019-09-29 16:37:04]	::1	www.google.org	AAAA	PASS	0ms	doh-crypto-sx
[2019-09-29 16:37:04]	::1	google.org	DS	PASS	0ms	doh-crypto-sx
[2019-09-29 16:37:04]	::1	org	DNSKEY	RESPONSE_ERROR	24ms	doh-crypto-sx
[2019-09-29 16:37:04]	127.0.0.1	org	DNSKEY	RESPONSE_ERROR	28ms	doh-crypto-sx
[2019-09-30 00:19:30]	::1	raw.githubusercontent.com	A	PASS	181ms	cloudflare-ipv6
[2019-09-30 00:19:30]	127.0.0.1	raw.githubusercontent.com	A	PASS	181ms	cloudflare
```
```
[2019-09-30 05:23:38]	::1	org	DNSKEY	PASS	22ms	ventricle.us
[2019-09-30 05:23:53]	::1	www.google.org	AAAA	PASS	0ms	ventricle.us
[2019-09-30 05:23:53]	::1	google.org	DS	PASS	0ms	ventricle.us
[2019-09-30 05:23:53]	::1	org	DNSKEY	RESPONSE_ERROR	112ms	doh-crypto-sx
[2019-09-30 05:23:53]	127.0.0.1	org	DNSKEY	RESPONSE_ERROR	30ms	doh-crypto-sx
[2019-10-01 09:23:46]	127.0.0.1	raw.githubusercontent.com	A	PASS	24ms	cloudflare
```

These are the corresponding packets from tshark:
```
26006 17920.260459    127.0.2.1 → 0.0.0.0      DNS 60 Standard query response 0x7870 Refused DNSKEY org OPT
26007 17920.287190    127.0.2.1 → 0.0.0.0      DNS 60 Standard query response 0x7870 Refused DNSKEY org OPT
26008 17920.287242      0.0.0.0 → 192.168.193.1 DNS 49 Standard query response 0xbc25 Refused DNSKEY org
26009 17921.172412 192.168.193.1 → 0.0.0.0      DNS 60 Standard query 0xbc25 A www.google.org
...
35820 27675.130518           :: → ::1          DNS 80 Standard query 0x6de1 DNSKEY org OPT
35821 27675.154996          ::1 → ::           DNS 80 Standard query response 0x6de1 Refused DNSKEY org OPT
35822 27675.183716    127.0.2.1 → 0.0.0.0      DNS 60 Standard query response 0x6de1 Refused DNSKEY org OPT
35823 27675.183852      0.0.0.0 → 192.168.193.1 DNS 49 Standard query response 0xd093 Refused DNSKEY org
35824 27676.130479 192.168.193.1 → 0.0.0.0      DNS 60 Standard query 0xd093 AAAA www.google.org
```
For now, I'm just going to drop `doh-crypto-sx` and see if that resolves the crashes. Could something have changed on the server-side code? I ran this setup without any problems until 9/25.

**Comment by jedisct1** [comment]
Hi,

Nothing has changed server-side, but some authoritative servers recently started to return a `REFUSED` error code, possibly due to rate limiting.

These responses got cached by the Cloudflare, and lasted for way too long.

The cache has been purged, and a new version of the proxy that reduces caching to the minimum on `REFUSED` responses has been deployed.

I will also probably add DNSCrypt (without filtering, unlike `sfw.scaleway-fr`) as an option for that resolver, as the new server proxy is way faster and more reliable that DoH.

Now, if pi-hole crashes when a `REFUSED` response is received, this is a completely different issue (and quite serious).

Let me know if `doh.crypto.sx` performs better for you now.

**Comment by TC1977** [comment]
Thanks! I've restarted using `doh-crypto-sx` and will let you know if I continue to see errors. I'll follow up with the pihole team in their issue.
