### ISSUE TITLE
Ubuntu PPA does not have most recent release (v2.0.27)

### ISSUE THREAD

**Issue by jdferron** [DNSCrypt/dnscrypt-proxy#944]
The listed PPA is not updated with the latest release: https://launchpad.net/~shevchuk/+archive/ubuntu/dnscrypt-proxy

Does the team have control over this PPA? Is it possible to get it updated?  Thanks!

**Comment by r4sas** [comment]
Specially4U:
![image](https://user-images.githubusercontent.com/7023612/66069227-a08cac80-e557-11e9-8d07-f28c1976db38.png)

**Comment by shvchk** [comment]
Hi guys, PPA maintainer here. I've updated packages (+ added eoan) and also enabled ARM builds (arm64, armhf).
