### ISSUE TITLE
generate-domains-blacklist.py generates files too small

### ISSUE THREAD

**Issue by 35609902357** [DNSCrypt/dnscrypt-proxy#947]
I used `generate-domains-blacklist.py` to generate a blacklist, and within the lists I put [this list](https://github.com/EnergizedProtection/block/raw/master/ultimate/formats/domains.txt) which is 19 MB big and contains around 900000 domains ([source](https://github.com/EnergizedProtection/block)). The output file is 10 MB and contains 528000 lines. AdAway using the same list generates a `hosts` file of the expected size.

**Comment by 35609902357** [comment]
More testing show that wildcards are not added (tried putting the link of the `domains-blacklist-local-additions.txt` inside the `domains-blacklist.conf` file, only the 3 regular domains present were added, all the wildcards were discarded).

Besides this, the content of the `domains-blacklist-local-additions.txt` file is never added, wildcards nor domains.

**Comment by jedisct1** [comment]
This is expected. Half of the entries from that list are redundant.

**Comment by jedisct1** [comment]
In that list alone:

```text
# Ignored duplicates: 360220
# Ignored entries due to the whitelist: 952
```

**Comment by 35609902357** [comment]
AdAway checks for duplicates as well, and that list is left untouched. Since is a list of lists it's supposed to be deduplicated already, but in any case, AdAway removes duplicates, so can it be a malfunctioning of the script?
