### ISSUE TITLE
Wildcards and local additions are not added

### ISSUE THREAD

**Issue by 35609902357** [DNSCrypt/dnscrypt-proxy#948]
Wildcards are not added (tried putting the link of the domains-blacklist-local-additions.txt inside the domains-blacklist.conf file, only the 3 regular domains present were added, all the wildcards were discarded).

Besides this, the content of the domains-blacklist-local-additions.txt file is never added, wildcards nor domains.

**Comment by jedisct1** [comment]
See the documentation about the format of these entries.

**Comment by 35609902357** [comment]
It behaves like this with [the file provided by you yourself](https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/utils/generate-domains-blacklists/domains-blacklist-local-additions.txt)

**Comment by jedisct1** [comment]
Read the documentation :)

**Comment by 35609902357** [comment]
[I read it](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Public-blacklists). I used the file provided by you, isn't that supposed to work? Can you give me a link to a more specific page of the documentation?

**Comment by jedisct1** [comment]
Great! For example, can you explain what `=` does?

**Comment by 35609902357** [comment]
Why are you like this?

**Comment by r4sas** [comment]
Cause someone doesn't read docs.

**Comment by 35609902357** [comment]
Went to [the documentation](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Public-blacklists) for automating blacklist creation, tested [the files you provided](https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/utils/generate-domains-blacklists/domains-blacklist-local-additions.txt), nothing is added to the blacklist from that file. I tried to put the link to the file into `domains-blacklist.conf`, it doesn't add any wildcard, only the domains inside of it. So why don't you just link the relative documentation since apparently it's unlinked from the relative pages where it should be linked.

**Comment by 35609902357** [comment]
@jedisct1 after roaming through the whole documentation I found nothing about how to use the [domains-blacklist-local-additions.txt](https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/utils/generate-domains-blacklists/domains-blacklist-local-additions.txt) file. [The script](https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/utils/generate-domains-blacklists/generate-domains-blacklist.py) doesn't contain any reference to it also. Where can I find the instruction for using it?

**Comment by jedisct1** [comment]
The `domains-blacklist.conf` configuration file is a set of URLs where list of rules are loaded from.

They can be loaded from remote websites (`http://` or `https://`) or from local files (`file://`).

`domains-blacklist-local-additions.txt` is just an example of a local file name. You can have as many lists loaded from local files as needed, and call them as you wish.

Local files are expected to contain [filters](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters) for `dnscrypt-proxy`, whereas some heuristics are applied to remote content in order to guess where the domain names are.
