### ISSUE TITLE
Proposal: allow continuing if at least one resolver is okay

### ISSUE THREAD

**Issue by alisonatwork** [DNSCrypt/dnscrypt-proxy#949]
This morning I encountered a problem where `dnscrypt-proxy` did not start up due to a single bad entry in the public resolvers file.

```
PS C:\ProgramData\chocolatey\lib\dnscrypt-proxy\tools\win64> .\dnscrypt-proxy.exe
[2019-10-06 10:13:25] [NOTICE] dnscrypt-proxy 2.0.27
[2019-10-06 10:13:25] [NOTICE] Network connectivity detected
[2019-10-06 10:13:25] [NOTICE] Source [public-resolvers.md] loaded
[2019-10-06 10:13:25] [ERROR] Invalid or unsupported stamp: [sdns://AgMAAAAAAAAAJzIwMDE6MTlmMDo3MDAxOjU1NTQ6NTQwMDowMmZmOmZlNTc6MzA3NyBsA2QQ3lR1Nl9Ygfr8FdBIpL-doxmHECRx3T5NIXYYtxNkbnMuY29udGFpbmVycGkuY29tCi9kbnMtcXVlcnk]
[2019-10-06 10:13:25] [CRITICAL] Unable to use source [public-resolvers]: [Invalid stamp (IP address)]
[2019-10-06 10:13:25] [FATAL] Invalid stamp (IP address)
PS C:\ProgramData\chocolatey\lib\dnscrypt-proxy\tools\win64> notepad .\public-resolvers.md
PS C:\ProgramData\chocolatey\lib\dnscrypt-proxy\tools\win64> .\dnscrypt-proxy.exe
[2019-10-06 10:14:26] [NOTICE] dnscrypt-proxy 2.0.27
[2019-10-06 10:14:26] [NOTICE] Network connectivity detected
[2019-10-06 10:14:26] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolver [114.114.114.114:53]
[2019-10-06 10:14:27] [NOTICE] Source [public-resolvers.md] loaded
...
```

The error is shown as (`Invalid or unsupported stamp`). I resolved it by commenting out the bugged entry and restarting. I don't think the comment made a difference, but by changing the signature it forced a re-download of the public resolvers file.

The frustrating thing as an end-user is that my system has no DNS at all until `dnscrypt-proxy` starts up, which means very little network-related stuff in the OS works. I would prefer that it make a best effort to start up rather than refusing to start up at all.

My proposal is to add some kind of configuration option that would result in a behavior like this:

```diff
--- a/dnscrypt-proxy/config.go
+++ b/dnscrypt-proxy/config.go
@@ -587,8 +587,11 @@ func (config *Config) loadSource(proxy *Proxy, requiredProps stamps.ServerInform
        }
        registeredServers, err := source.Parse(cfgSource.Prefix)
        if err != nil {
-               dlog.Criticalf("Unable to use source [%s]: [%s]", cfgSourceName, err)
-               return err
+               if len(registeredServers) == 0 {
+                       dlog.Criticalf("Unable to use source [%s]: [%s]", cfgSourceName, err)
+                       return err
+               }
+               dlog.Warnf("Error in source [%s]: [%s] -- Continuing with reduced server count [%d]", cfgSourceName, err, len(registeredServers))
        }
        for _, registeredServer := range registeredServers {
                if len(config.ServerNames) > 0 {
```

I.e. if at least one good entry was found before encountering the error, it will hobble along with just those servers until the next time the resolver file is downloaded.

An alternative option might be a "self-healing" behavior, where if it encounters an error with the cached resolver file on startup, it proactively downloads a fresh one to check if that has better information. This is the inverse behavior suggested on #810 where the proposal was to retain the old cached resolver file to rollback in case the new one has errors.

If this sounds like a reasonable feature I'm willing to try make a PR.

**Comment by IceCodeNew** [comment]
Same problem here.

It makes no sense to block client from starting while the DNS servers specified (In this case are Cloudflare and Quad9) in the configuration files are all alive.
The [DNS server in problem](sdns://AgMAAAAAAAAAJzIwMDE6MTlmMDo3MDAxOjU1NTQ6NTQwMDowMmZmOmZlNTc6MzA3NyBsA2QQ3lR1Nl9Ygfr8FdBIpL-doxmHECRx3T5NIXYYtxNkbnMuY29udGFpbmVycGkuY29tCi9kbnMtcXVlcnk) should not bother me.

**Comment by jedisct1** [comment]
Thank you!
