### ISSUE TITLE
Suggestion: Allow cloaking to support pattern matching and timebase rules

### ISSUE THREAD

**Issue by opav** [DNSCrypt/dnscrypt-proxy#95]
Cloaking will be very powerful and useful if it supports pattern matching and time-base rules.

Please consider enhancing it, thank you.

**Comment by jedisct1** [comment]
There hasn't been any progress on this issue for 30 days, so it is unlikely to happen. I had no time to work on this and no one stepped in to help either, so it's sadly not worth keeping this issue open any longer.
