### ISSUE TITLE
Install problem,use blacklist.txt problem

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#951]
Windows 10 x64 
Use dnscrypt-proxy within simple dnscrypt,open domain blacklist and add more resource for block AD.
But build the blacklist.txt is very difficult,need a better way to deal with .

Use blacklist.txt that update list is very hard.

Openwrt x64
Install dnscrypt-proxy use some versions,but dnscrypt-proxy could not to used ,install jedisct1 dnscrypt-proxy by hand,it is not processing very well, change to dnscrypt-proxy v2 through command.
v2.0.27,hope upgrade to more functions,support TLS,and foke ID,random data flag to hidden tracker and jump firewall.Maybe have a better way to install,and more speed up.

Install dnscrypt-proxy is very hard,most time have not internet.

**Comment by jedisct1** [comment]
Can you clarify what the question is?
