### ISSUE TITLE
Use parallel queries to speed up resolving by querying all upstream servers simultaneously

### ISSUE THREAD

**Issue by hongyi-zhao** [DNSCrypt/dnscrypt-proxy#955]
Could this feather be added to dnscrypt-proxy?

**Comment by jedisct1** [comment]
Ouch, can you imagine the implications on servers, if all queries, from all servers, were sent simultaneously to all of them?

All the servers would go down, so it wouldn't speed up much :)

Also, from a privacy perspective, that would not be great. The less parties know a about your activity, the better.

**Comment by hongyi-zhao** [comment]
I think there should be some algorithms in the client to optimize this thing when doing para queries.  

The dnsproxy can do so, but I don't inspect the corresponding code in it yet:

```
https://github.com/AdguardTeam/dnsproxy

-s, --all-servers Use parallel queries to speed up resolving by querying all upstream servers simultaneously
```
