### ISSUE TITLE
Is there any way to exam the cache status of dnscrypt-proxy?

### ISSUE THREAD

**Issue by arkninja** [DNSCrypt/dnscrypt-proxy#957]
Hi guys,

We have deployed a dnscrypt-proxy server in office with thousands of clients using this DNS proxy server. We would like to know how many lines of DNS record were cached, as well as the hit rate of the cache. Is there any way to get those info?

Greatly thank you for any help you may offer.

**Comment by r4sas** [comment]
RTFM: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Caching#dns-cache

For receiving info about current caching state you can try write plugin, but idk if here possibility to get that info.

**Comment by jedisct1** [comment]
You can turn on query logging, especially with the LTSV output.

It includes a lot of information about each transaction, including cache usage.

Using Elasticsearch/Fluentd/Kibana, you can build pretty dashboards from this.
