### ISSUE TITLE
A cloaking rule can map to multiple IP addresses？

### ISSUE THREAD

**Issue by yyy8888** [DNSCrypt/dnscrypt-proxy#958]
A cloaking rule can map to multiple IP addresses？What is the format?

**Comment by jedisct1** [comment]
Hi,

Yes, absolutely.

See the [documentation on cloaking](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Cloaking).

And I also just added some documentation about this in the `example-cloaking-rules.txt` file.

Thanks!
