### ISSUE TITLE
new blacklist/whitelist re-loaded automatically ?

### ISSUE THREAD

**Issue by scubasunny** [DNSCrypt/dnscrypt-proxy#965]
Just a small question, are the various lists, blacklist, whitelist, cloaking etc. somehow re-loaded automatically ?
or do i have to restart dnscrypt-proxy always manually after a change has happened?

e.g as i update the blacklist every day by cronjob

**Comment by AlphaTangoCharly** [comment]
All lists modifications require a restart of DNSCrypt-proxy to be handled.
I update as well my blacklists once a day with a script and to make it simpler I've added a call to DNSCrypt-proxy's `service-restart.bat` in the script to have it be done automatically.

**Comment by scubasunny** [comment]
ok, that's fine, not hard to do but when i see that the public-resolvers.md file is reloaded automatically, why not to do the same with some other lists on a configurable timeline ?
Maybe a nice feature request ;-)

**Comment by AlphaTangoCharly** [comment]
DNSCrypt-proxy must be restarted to validate its lists' modifications (as well of course as that of its .toml configuration) and I think (without being affirmative) that restarting DNSCrypt-proxy initializes its cache; if so this would invalidate the pertinence of any automated restart. I'm not sure about the cache, I know it's all in RAM and gets lost when DNSCrypt-proxy is closed, but is it as well when DNSCrypt-proxy is restarted? Testing would be easy, asking is easier :=)

**Comment by jedisct1** [comment]
It's in the planned list of features to add soon.

There is even a pull request for it, so it should have been implemented a long time ago already, but I've been distracted by other things.

Don't worry, it will eventually happen :)
