### ISSUE TITLE
[QUESTION] DNS Stamp calculator erroneous DNSSEC info for comodo-2 ?

### ISSUE THREAD

**Issue by AlphaTangoCharly** [DNSCrypt/dnscrypt-proxy#968]
I happen to test a DNS server alone to see how it manages.
I had a look at comodo-2 over at the [Online DNS Stamp calculator](https://dnscrypt.info/stamps/).
Checking comodo-2's stamp shows as empty all three _DNSSEC_, _No logs_, _No filter_ boxes.

Fine, except that when checking with the [DNSSEC Resolver Test](https://dnssec.vs.uni-due.de/) site, the test indicates: _Yes, your DNS resolver validates DNSSEC signatures_

I emphasize on the fact comodo-2 is the only live-server:
```
[NOTICE] Anonymized DNS: routing [comodo-02] via [sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM]
[NOTICE] [comodo-02] OK (DNSCrypt) - rtt: 11ms
[NOTICE] Server with the lowest initial latency: comodo-02 (rtt: 11ms)
[NOTICE] dnscrypt-proxy is ready - live servers: 1
```
So I'm wondering on what reference I must rely concerning DNSSEC validation, the _Online Stamp calculator_ or the the _DNSSEC Resolver test_?

Thanks.

**Comment by uBlock-user** [comment]
You're using Anonymized DNS, so none of these params matter anymore.

**Comment by jedisct1** [comment]
Oh, you're right, Comodo supports DNSSEC now!

I think they didn't when they got added to the list, but upgraded their software, and they now support it.

I'm going to update the relevant stamp to set the DNSSEC flag. Thanks!
