### ISSUE TITLE
log issue

### ISSUE THREAD

**Issue by CNMan** [DNSCrypt/dnscrypt-proxy#97]
```sudo ./dnscrypt-proxy -service stop
[2018-02-06 18:16:58] [NOTICE] Starting dnscrypt-proxy 2.0.0rc3
[2018-02-06 18:16:58] [NOTICE] Service stopped```
Starting maybe should be Stopping?

**Comment by jedisct1** [comment]
Thanks!

This is the first message printed when the application starts. I just removed the word "Starting" to remove the confusion.

Btw, version 2.0.0 final is out :)

**Comment by CNMan** [comment]
i replace dnscrypt-proxy with 2.0.0 final, but log show 2.0.0rc3

**Comment by CNMan** [comment]
the log is printed by command `sudo ./dnscrypt-proxy -service stop`,not first start.
```
pi@raspberrypi:~ $ cd /home/pi/dnscrypt-proxy
pi@raspberrypi:~/dnscrypt-proxy $ sudo ./dnscrypt-proxy -service stop
[2018-02-07 04:46:09] [NOTICE] Starting dnscrypt-proxy 2.0.0rc3
[2018-02-07 04:46:09] [NOTICE] Service stopped
pi@raspberrypi:~/dnscrypt-proxy $
```

log file:
```[2018-02-07 04:46:09] [NOTICE] Stopped.```
