### ISSUE TITLE
Version 2.0.29 beta 3 released

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#972]
With quite a lot of internal changes and improvements, so discuss any regression here :)

**Comment by Zastoff** [comment]
anon-kama, anon-suami, anon-charis seems to have the same sdns in relays.md

**Comment by Samillion** [comment]
Genuinely loving these updates. Keep up the awesome work, guys. Thank you.

```
server_names = ['developerli-de', 'opennic-ethservices', 'dnscrypt-01.adsnomore.io', 'dnswarden-dc1', 'dnswarden-dc2', 'scaleway-fr', 'bottlepost-dns-nl', 'developerli-fr']

routes = [
   { server_name='developerli-de', via=['anon-kama', 'anon-ibksturm'] },
   { server_name='opennic-ethservices', via=['anon-kama', 'anon-ibksturm'] },
   { server_name='dnscrypt-01.adsnomore.io', via=['anon-kama', 'anon-ibksturm'] },
   { server_name='dnswarden-dc1', via=['anon-kama', 'anon-ibksturm'] },
   { server_name='dnswarden-dc2', via=['anon-kama', 'anon-ibksturm'] },
   { server_name='scaleway-fr', via=['anon-kama', 'anon-ibksturm'] },
   { server_name='bottlepost-dns-nl', via=['anon-kama', 'anon-ibksturm'] },
   { server_name='developerli-fr', via=['anon-kama', 'anon-ibksturm'] }
]
```

**Comment by jedisct1** [comment]
Thanks @Samillion. The routing table looks cleaner now!

If `server_names` is just `['developerli-de', 'opennic-ethservices', 'dnscrypt-01.adsnomore.io', 'dnswarden-dc1', 'dnswarden-dc2', 'scaleway-fr', 'bottlepost-dns-nl', 'developerli-fr']` your routing table could now be as simple as:

```toml
routes = [
   { server_name='*', via=['anon-kama', 'anon-ibksturm'] }
]
```

**Comment by jedisct1** [comment]
@Zastoff Fixed, thanks :)

**Comment by Samillion** [comment]
@jedisct1 Oh, wow! I didn't even notice that part. Amazing, just read the notes if the list is short then that should be fine.

Thank you again, very impressive to be honest.

**Comment by jedisct1** [comment]
I'm going to release a new beta.

With minor changes (mainly about improved logging), but this brings us closer to releasing a final (non-beta) version.

Thanks a lot everyone for your invaluable help and feedback regarding the new features!

**Comment by mattriots** [comment]
Hey all - Thank you for this amazing work and updates!
Noob question - what is the best way to update to the new beta? I am currently on beta 1 but want to catch up to 3. Do i just need to replace the dnscrypt-proxy executable file with the new one? Or delete - then reinstall the new beta? Or is there any documentation you could point me to help guide me through an easier way?
again sorry for the Noob questions - I really want to learn how to implement this properly. Any help is much appreciated

**Comment by jedisct1** [comment]
Hi @mattriots 

Yes, replacing the `dnscrypt-proxy` executable and restarting the service is all it takes.

You may also compare your configuration file with the more recent example configuration, since new features may have been added.

Here, the anonymized DNS section learned new tricks: https://github.com/DNSCrypt/dnscrypt-proxy/blob/92e632daf1b9048b937073688643fbb023b60f56/dnscrypt-proxy/example-dnscrypt-proxy.toml#L567-L590

But configuration files are always backwards compatible.

**Comment by mattriots** [comment]
@jedisct1 Thanks for the quick reply! I stumbled upon an update script you wrote and I'm figuring out how to get that going - seems like it will do all the hard work for me.
Thanks again and I'm looking forward to new releases - hopefully someday in the near future I will be learned enough to contribute - Keep up the great work.

**Comment by Samillion** [comment]
@mattriots Agreed, wonderful script and made the whole process even easier.

I haven't added it to cron, I just run it from `myscripts/` folder and restart `dnscrypt-proxy` when it's done with `-service restart`. Definitely adding it to cron soon, I'm just too lazy. 😄

**Comment by jedisct1** [comment]
To give credit where credit's due: @NoSubstitute and @zero77 are the authors of that script.
I just made a couple fixes.

**Comment by delusion2019** [comment]
> Thanks @Samillion. The routing table looks cleaner now!
> 
> If `server_names` is just `['developerli-de', 'opennic-ethservices', 'dnscrypt-01.adsnomore.io', 'dnswarden-dc1', 'dnswarden-dc2', 'scaleway-fr', 'bottlepost-dns-nl', 'developerli-fr']` your routing table could now be as simple as:
> 
> ```toml
> routes = [
>    { server_name='*', via=['anon-kama', 'anon-ibksturm'] }
> ]
> ```

Can we use Automatic server picking with " { server_name='*', via=['anon-kama', 'anon-ibksturm'] }" and they will be all routed through those relays or we need server with some kind of special support? like  "'developerli-de', 'opennic-ethservices', 'dnscrypt-01.adsnomore.io', 'dnswarden-dc1', 'dnswarden-dc2', 'scaleway-fr', 'bottlepost-dns-nl', 'developerli-fr'"

**Comment by iWARR** [comment]
Just want to clarify.

Connections for relays goes through UDP and port 443, that is unusual. This is only exception from the standards in my entire firewall scheme.

Usually, UDP connections have to use port 53 and TCP connections - port 443. Here we have "switched" standard scheme within relays - UDP on port 443. Is it normal? (Anyway, it works also).

**Comment by jedisct1** [comment]
@delusion2019 Yes, you can totally use `server_name = '*'`, but make sure to use a `server_list` that includes servers distinct from relays. Or else, the fastest route from a relay is likely to be the resolver operated by the same entity, which kinda defeats the whole purpose of using a relay :)

**Comment by jedisct1** [comment]
@iWARR Yes, this is normal, and you'd better not close UDP port 443 as this is the standard port for QUIC / HTTP/3.

**Comment by iWARR** [comment]
@**jedisct1** Thanks. I'll make a note for this useful info.

I have everything restricted by default and just have to allow parameters for things I need. I will open 443 (UDP) for dnscrypt-proxy (only). And the same I'll do for other programs only when I need them. When HTTP3 will be ready for public and browsers will support this, I'll change my rules correspondigly.

wiki: 

> QUIC is used by more than half of all connections from the Chrome web browser to Google's servers. Most other web browsers do not support the protocol. 

I don't use Chrome and I don't want this "black-box" connections to Google.

If  **Go** language supports QUICK for server / balancing, that's OK. 443 (UDP) will be allowed for dnscrypt-proxy (only).

**Comment by privacyguy123** [comment]
Having a problem with the Anonymized DNS in Beta 3, was working in Beta 1 but now the output in command prompt doesn't state whether it's working or not.

**Comment by jedisct1** [comment]
@privacyguy123 It didn't do anything in beta 1; relaying doesn't work with DoH.

**Comment by privacyguy123** [comment]
> 
> 
> @privacyguy123 It didn't do anything in beta 1; relaying doesn't work with DoH.

Strange, the command prompt output made it seems like it was working. O.o

**Comment by iWARR** [comment]
@jedisct1 

Can you, please, remind me a proper link to a **Go** devs thread on GitHub?
I will try kindly ask them improve log-management part.

**Comment by jedisct1** [comment]
Can we stay on topic?

**Comment by jedisct1** [comment]
2.0.29 final is out!
