### ISSUE TITLE
Windows service is killed by event 7000 if there is no network on startup

### ISSUE THREAD

**Issue by alisonatwork** [DNSCrypt/dnscrypt-proxy#976]
My laptop usually doesn't have internet connection when I start it up, and sometimes it can be 20 minutes or so till I connect it to the wifi. This should be handled by the `netprobe_timeout` setting - by putting it to `-1` it should retry up to 1 hour until the network appears. However, this does not work.

This is what appears in the event log:

```
由于下列错误，dnscrypt-proxy 服务启动失败: 
服务没有及时响应启动或控制请求。
等待 dnscrypt-proxy 服务的连接超时(45000 毫秒)。
``` 

Sorry my Windows is Chinese, but this is events 7000 and 7009: https://support.microsoft.com/zh-cn/help/922918/a-service-does-not-start-and-events-7000-and-7011-are-logged-in-window

If a service doesn't respond within 30-45 seconds, the Windows service manager will just kill it.

A temporary workaround might be to install the service with a retry behavior, so Windows will restart it after it dies, but I think the right fix here is to move the netprobe into the main loop of the service instead of making it happen while loading the config file on startup.

Moving this code into the main loop might break startup behavior on other OSes, however. And it will definitely affect the startup commands like `list`, `check` and so on.

I don't really have time to look into this right now, so opening a ticket instead.

**Comment by jedisct1** [comment]
Moving the netprobe doesn't look like a good fix. Loading the lists or benchmarking the servers may also exceed the service deadline.

Ideally, the service should return immediately, and everything will then happen in the main loop.

I once tried to reorganize the code and `kardanios/service` to do this, but couldn't get something that didn't break either systemd or the windows service manager.

**Comment by alisonatwork** [comment]
Okay, I've made an attempt to address this in PR #991 

I am not sure of how it will impact systemd. If it's using the PID file, then it shouldn't be any different from before, because the PID file doesn't get created until `appMain`. If it's not using the PID file... then that's beyond my basic systemd knowledge 🤣 But looking at the source code of kardianos/service, it doesn't seem like there is any special state that is maintained in the `Run` loop for systemd, so I think it should be okay.

**Comment by alisonatwork** [comment]
More interesting reading if anyone searches this thread and wants to know more about how Windows service state transitions: https://docs.microsoft.com/en-us/windows/win32/services/service-status-transitions

**Comment by jedisct1** [comment]
So, this is fixed :) Thank you Alison! That was a long-standing issue.
