### ISSUE TITLE
netprobe_timeout is always set to 1 hour, ignores configuration

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#977]
### PROBLEM

If no Internet connection, then installation procedure will fail.
This installation method is not good for privacy, because I can't make a necessary offline prepearations for the first safe connection for machine/device.

Now, in this case, I have to tolerate an unwanted leaks for the first service installation (while DNSCrypt not yet on stream) and wait for the fallback downloading with unsafe network config also.
Then you can have proceed with your wanted (usual) dnscrypt configuration.

In fact, every time, for the first setup, I need to set a standard DNS config for the machine AND have connectivity, then install dnscrypt-proxy, then reconfig network settings for dnscrypt-proxy.
Fallback resolver, in this case, can't do his job for the 1-st installation, because dnscrypt-proxy Service can't install, if no connectivity.

Fixing this should help for another problem, that appears time to time - service may stuck if *.md files missing or become obsolete (time bias: long time in offline, restoring backup, etc).
Same thing for Android. 

### WORKAROUND

First preconfiguration steps for dnscrypt-proxy (service installation in Windows) should be possible in offline mode.

An ability of configuring of your favorite "Ready to go" pack from offline: 

  - Putting your "Ready to go" dnscrypt-proxy folder on disk
  - Setting the local IPs for DNS in Windows Network configuration
  - Installation of dnscrypt-proxy
  - Turning Network adapter (Internet) on
  - Restarting dnscrypt-proxy to intitiate *.md files downloading through fallback resolver
  - You are ready to go within safe DNS config from the start

### EXPECTED PROS

- Less leaks
- Less stuck on Windows (probably on Android also)

--------------
**P.S.**
- Described problem is an old issue... But more older builds didn't have such service issue (as I remember right)...
- v2.0.29-beta.3 works well, Anonymized DNS works (don't forget allow an IP of the chosen relay in your Firewall). Thanks for imrpoving sec. options!
- Wish you remember https://github.com/DNSCrypt/dnscrypt-proxy/issues/901#issuecomment-517969724 and make logging output better on Windows. (Also, take a note, that switching places of IP | Domain in Cloaking and Forwarding .*txt files will be better on Windows - this is a standard way of input writes on Windows, that is more reasonable, comfortable and universal with 3-rd party hosts lists).
- Thank you!

**Comment by iWARR** [comment]
If you want, I can provide more information about Android issues during first setup also. These are different OS, of course, but it may help to understand a problem, that may appear a bit relative...

Сommonly encountered problem is a first launch. In a fact, in both OS I need set a system to regular DNS first and go to online within nonworking blacklist. As well, Windows and Android have a tons of hidden spying links, starting these leaks immidiately after first connection.

At present time, dnscrypt-proxy for Android needs several reboots having usafe config within nonworking blacklist before starting work at full of power. This is a big problem and very unhandy 
way to operate.

**Comment by iWARR** [comment]
No comment?

I'm completely wrong???

**Comment by jedisct1** [comment]
The rephase:

The message `Network not available yet -- waiting...` is printed if there is no network connectivity, and waits for up to 1 hour before proceeding, no matter what the `netprobe_timeout` value is.

--

Indeed, this is a bug. The `netprobe_timeout` configuration (or command-line) value wasn't properly used, and the timeout ended up always being 1 hour. This has been fixed by 94c16c3. Thanks!

**Comment by iWARR** [comment]
OK. Will test your next version.

... Please, just one comment about my petition about improving  logging output... Is this possible?

May be good idea will be to add an opton in *toml, smth like

`format = 'tsv'`

but for manual order of columns:

`order = 'Date, Time, Ping, Server, Action, Domain'` , etc. 

...and user will decide what columns he wants and in which order.

Also, less (unwanted) columns = faser writes, better reperesentation, looks better and faster to analyse. Look at 2-nd pic here: https://github.com/DNSCrypt/dnscrypt-proxy/issues/901#issuecomment-517969724

Also, an assignable number of singns per each column is important for the sure and nice formatting...
