### ISSUE TITLE
Running two dnscrypt-proxy services on Windows

### ISSUE THREAD

**Issue by privacyguy123** [DNSCrypt/dnscrypt-proxy#979]
Is it possible to have a switch somewhere or multiple instances of DNSCrypt to use one set of settings when Tor is conncted and another set when not?

EDIT: On Windows, preferably both running as services.

**Comment by jedisct1** [comment]
I don't see any reliable way to do that without using a script that start both Tor and services expecting it.

**Comment by privacyguy123** [comment]
There's no way to have 2 seperate DNSCrypt instances running as services in Windows, one on 127.0.0.1 & 127.0.0.2 for example?

Failing that, if socks5 proxy is activated in config, can it not be set to fallback to non proxy'd DNS?

**Comment by jedisct1** [comment]
That can probably be done if you register the service manually with the `sc` command. But you know Windows way better than I do.

**Comment by privacyguy123** [comment]
Hmm ... will that automatically assign 127.0.0.2 if multiple DNSCrypt services exist? I'm not seeing an option for custom bind addresses in Windows.

**Comment by jedisct1** [comment]
The bind address is set in the configuration file, and you can have multiple configuration files.

**Comment by evilvibes** [comment]
maybe something like NSSM (Non-Sucking Service Manager) could help you. https://nssm.cc/

**Comment by privacyguy123** [comment]
Installing it into the registry myself worked, which could definitely have been circumvented by adding a switch to the dnscrypt-proxy.exe to install itself as a service with a custom name provided by the user ...

Tell me this: is there any reason it has to be listening on port 53?

**Comment by jedisct1** [comment]
You can use any port, if you ever manage to configure Windows to use a different port than 53 for DNS.

**Comment by privacyguy123** [comment]
So this is not possible as Windows won't allow 2 dnscrypt-proxy instances to listen on port 53 simultaneously?

**Comment by privacyguy123** [comment]
What happened to these switches? They fix everything I've asked here.

> In addition to the command-line switches available on other platforms, the Windows builds of the proxy add the following switches:

    --install: install the proxy as a service.
    --install-with-config-file=<config file>: install the proxy as a service, using the provided configuration file (dnscrypt-proxy.conf). Double check that the configuration file is valid prior to installing the service.
    --uninstall: uninstall the service (but not the software - the service can be restarted later)
    --service-name=<name>: set the service name (by default: dnscrypt-proxy). Multiple services with a different configuration can run simultaneously if they use distinct service names. --service-name must be combined with --install, --install-with-config-file or --uninstall.

>

**Comment by privacyguy123** [comment]
![image](https://user-images.githubusercontent.com/50337995/67634279-a3a65e80-f8b1-11e9-89c3-cbe755981190.png)

One listening on 127.0.0.1 and 127.0.0.2 - only works if you remove the '[::1]:53' from one of the configs.

**Comment by jedisct1** [comment]
Maybe you can simply use a DNS relay instead? As a bonus, it will be 10x faster than relaying through Tor.

**Comment by privacyguy123** [comment]
I guess I could change to Quad9, Cloudflare aren't offering support for DNSCrypt protocol so can't be relayed and they're the fastest option ...
