### ISSUE TITLE
Frequent freezes on RaspberryPi: dnscrypt-proxy not responding unless restarted

### ISSUE THREAD

**Issue by andreagrandi** [DNSCrypt/dnscrypt-proxy#983]
Hi,

I've been using my PiHole for nearly 2 years and always kept updated. Yesterday I tried to install and enable DNSCrypt too, following this tutorial: https://medium.com/@d.robertson/pi-hole-dnscrypt-and-rogue-dns-requests-f48394c9d6d3
and I was able to make it work. This morning I noticed that DNS replies had become slow so I tried to investigate and logging into my PiHole with SSH I tried to use `dig`:

```
root@raspberrypi:/tmp# dig @127.0.0.1 -p 4053 dev.to

; <<>> DiG 9.10.3-P4-Raspbian <<>> @127.0.0.1 -p 4053 dev.to
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

So I restarted the client with `dnscrypt-proxy -service restart` and everything worked again. After a couple of hours it happened again and this time I first disabled `DNSSEC` in the PiHole settings, then I restarted `dnscrypt-proxy` again.

But after 1-2 hours I was still having the same problem. At this point I simply stopped `dnscrypt-proxy` and changed my PiHole settings to simply use CloudFlare DNS directly.

Is there any known issue with the RaspberryPi? I really would like to make `dnscrypt-proxy` work for my PiHole.

Happy to give more technical details on request.

Cheers

**Comment by jedisct1** [comment]
Anything else running simultaneously? Maybe the Rpi is running out of memory?

**Comment by jedisct1** [comment]
Also, if you're using DoH, you may want to change `tls_cipher_suite` (see the comment above it).

**Comment by andreagrandi** [comment]
> Anything else running simultaneously? Maybe the Rpi is running out of memory?

I don't remember the exact number but from the web panel I seem to remember it was no more than 25% taken, but I will double check next time it happens. Anything else I should check wheenever it happens again? Cheers

**Comment by andreagrandi** [comment]
Oh one thing I did: the tutorial suggested to disable the **cache**... could this be the problem?

**Comment by andreagrandi** [comment]
> Also, if you're using DoH, you may want to change `tls_cipher_suite` (see the comment above it).

thanks for this advice! I've just enabled that line, let's see if it helps. I will keep you updated. Thanks!
