### ISSUE TITLE
dnscrypt-proxy 2.0.29-beta3 with cisco and a relay stops resolving

### ISSUE THREAD

**Issue by TheGITofTeo997** [DNSCrypt/dnscrypt-proxy#984]
Hello, first i am sorry if i open an issue like this without providing much information, but i am encountering an issue.
I've been using DNSCrypt for a lot of time happily till version 0.28, now i am on 0.29-3 anonymized via a relay.

I don't know where the problem is and/or if i can provide any log, if so, please tell me where and i will be happy to provide it.

So the issue is that at a given specific time, the dnscrypt proxy just stops working, serivce status shows everything is okay and all is going smoothly, but i just can't resolve DNSs.

If i give a service dnscrypt-proxy restart, everything gets back to normal in 1 second, but you will agree with me this is annoying. The proxy is currently running on a Raspberry, raspbian stretch of course with pihole, and i am forwarding all to cisco via anon-charis.

Is this a known bug? Just tell me what i can provide to help troubleshooting this and i will be happy to do it. Thanks in advance

**Comment by jedisct1** [comment]
Can you try with a different resolver than `cisco`?

**Comment by TheGITofTeo997** [comment]
> 
> 
> Can you try with a different resolver than `cisco`?

Yes, of course. If you have one preferred just tell me and i will try it as soon as possible.

However, i don't know if it's the anonymized relay or what, as i said nothing wrong is shown

**Comment by jedisct1** [comment]
I know that Cisco has a bug with large questions, that may prevent anomymization from working correctly.

Try any other one :)

**Comment by TheGITofTeo997** [comment]
> 
> 
> I know that Cisco has a bug with large questions, that may prevent anomymization from working correctly.
> 
> Try any other one :)

Got it, do you think this is probably solvable? I feel comfortable with cisco and it would be a shame not to use it. Anyway i will monitor the situation with another one, thank you so much for the support!

**Comment by jedisct1** [comment]
It's up to them :(

You can still use this resolver, but not through a relay.

**Comment by TheGITofTeo997** [comment]
Hello, 
unluckily i have to tell you that the issue is still actual even though i am **NOT** using anonymized relays. I am still using cisco as resolvers but "freezes unless restarted" are still a thing (albeit in minor quantity). This, to me, is a behaviour that looks like the one in #983 

I remember one time it started to happen in 0.28 (always used cisco) and now is still happening in 0.29 final, i will try now to update to 0.30 to see if it is solved, thank you for the support.

**Comment by stephen-d-hill** [comment]
I have the same problem, and I'm on v2.0.31. 
My cache was enabled, I am not using a relay and I'm using cisco-familyshield.

syslog:
`
Nov 16 12:40:20 hill dnscrypt-proxy[3949]: Server [cisco-familyshield] returned temporary error code [2] -- Upstream server may be experiencing connectivity issues  

Nov 16 15:10:18 hill dnscrypt-proxy[3949]: [2.dnscrypt-cert.opendns.com.] the key validity period for this server is excessively long (365 days), significantly reducing reliability and forward security.
Nov 16 15:10:18 hill dnscrypt-proxy[3949]: [cisco-familyshield] OK (DNSCrypt) - rtt: 19ms                                                                                                                                 Nov 16 15:10:18 hill dnscrypt-proxy[3949]: [2.dnscrypt-cert.opendns.com.] the key validity period for this server is excessively long (365 days), significantly reducing reliability and forward security.
Nov 16 15:10:18 hill dnscrypt-proxy[3949]: [cisco-familyshield] OK (DNSCrypt) - rtt: 20ms`
