### ISSUE TITLE
upgrade idea,maybe not very well

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#986]
In China ,the Internet is not very well,more interfere.
So hope like kadnode to used BitTorrent network for DNS.
![Image 1](https://user-images.githubusercontent.com/17021524/67610103-1ca59900-f780-11e9-8513-049dbe4bd8f3.png)

If the idea is not very well ,so sorry!

**Comment by jedisct1** [comment]
I think Kadnode can be used already.

You  can forward `*.p2p` to a Kadnode server that runs locally.
