### ISSUE TITLE
Installed failed

### ISSUE THREAD

**Issue by jkle112** [DNSCrypt/dnscrypt-proxy#987]
Used dnscrypt-proxy-linux_x86_64-2.0.29-beta.3.tar.gz in Openwrt/Lede,
used the page :https://github.com/dnscrypt/dnscrypt-proxy/wiki/Installation-on-OpenWRT to install,but something is changed.

![Image 1](https://user-images.githubusercontent.com/17021524/67617631-8bacdd00-f7d4-11e9-8a9d-7f236ac23ab0.png)

the config check could not to used.
Jump this way,the line is show me no internet.
Need help !

**Comment by jedisct1** [comment]
It says version `1.9.5`, which is a very old version that didn't work the same way.

Looks like in addition to the instructions you linked, you also installed an old package. You need to uninstall it.
I think the command is `opkg remove --autoremove dnscrypt-proxy`.
