### ISSUE TITLE
dnscrypt-proxy 2.0.0 final shows as dnscrypt-proxy 2.0.0rc3 in dnscrypt-proxy.log file

### ISSUE THREAD

**Issue by pjnsmb** [DNSCrypt/dnscrypt-proxy#99]
dnscrypt-proxy 2.0.0 final shows as :

Starting dnscrypt-proxy 2.0.0rc3 in dnscrypt-proxy.log file

using  dnscrypt-proxy-linux_x86_64-2.0.0.tar.gz

**Comment by jedisct1** [comment]
I think Travis uploaded binaries built just before the version change.

New binaries will be available in a couple seconds.

But there are no changes besides the printed version, so you don't need to redownload them unless seeing "rc3" really makes you nervous :)

Thanks!
