### ISSUE TITLE
Client authentication howto?

### ISSUE THREAD

**Issue by emilvandenberg** [DNSCrypt/dnscrypt-proxy#992]
In #599 the following is stated: "Certificate-based authentication solves this. Users can be identified using their public key, and having public keys leaked is harmless. This is easy to implement both for DNSCrypt and DoH."

Is there an explanation how to achieve this?

**Comment by jedisct1** [comment]
Another mechanism was implemented.

See the `query_meta` parameter in the configuration file:

```text
## Additional data to attach to outgoing queries.
## These strings will be added as TXT records to queries.
## Do not use, except on servers explicitly asking for extra data
## to be present.

# query_meta = ["key1:value1", "key2:value2", "key3:value3"]
```

Arbitrary key/value pairs can be attached to queries that way. 

This works with any protocol, can be used for other purposes than authentication, doesn't use EDNS, and is compatible with ephemeral keys.

**Comment by emilvandenberg** [comment]
merci beaucoup!

**Comment by emilvandenberg** [comment]
I have an additional question: is there also an explanation how to implement this server side, using (for example) DOH?

**Comment by jedisct1** [comment]
On the server, you have to use some DNS library to parse queries, and look for optional records in the additional section.
I'm not aware of an existing opensource example doing that, though.

**Comment by emilvandenberg** [comment]
Thanks for the reply. I am wondering what would be the best way to achieve this. I discovered in #937 that you are considering building client authentication for the DNSCrypt server proxy. Would that be the best way forward? And if so, is there an estimation when the client authentication could be working? If there is work that can easily be delegated, I am willing to help.

**Comment by jedisct1** [comment]
Hi Emil,

I don't need this feature, so this is not something I'm planning to implement in the server in a near future, unless it pays the bills.

But if you want to implement this, I'd be glad to review and merge the code. Parsing the DNS records would be simple and quick, but in order for that to be useful, we need to add a couple authentication backends, administration tools and write the related documentation. And that's quite time consuming.

**Comment by emilvandenberg** [comment]
Thanks for the reply, I'll think about it.

**Comment by emilvandenberg** [comment]
Hi @jedisct1,

I agree that we would need to be able to connect to a couple of backends. In my situation, I would need to do a Rest call for checking the credentials that were in the query_meta. Doing a Rest call is probably not what you were thinking of, so I would like to know what your opinion is. I think in this way we can already use different backends with not too much work.

I would implement it as follows:

- read the data from query_meta
- send the data to a (configurable) endpoint
- if the endpoint is not within a DMZ, it should be possible to configure authentication (that’s probably different from the authentication data that is being verified)
- if the service doesn’t reply in a simple true/false fashion, there should be a way to configure how the response is to be validated
- the answers should probably be cached

What do you think about this approach as a first step? Other backends could of course be added later.
I’d like to experiment with this in a fork. I would be nice if you give me some pointers on how to read the query-meta records.

Greets,
Emil

**Comment by jedisct1** [comment]
I don't need that feature, this is your fork, for yourself, so feel free to do what *you* need :)

Maybe the list of authentication tokens can be stored in something like LMDB. So that you don't need to implement caching, and updates can be instant. The LMDB database can then be populated from PostgreSQL or whatever, either as a whole or as updates.

**Comment by emilvandenberg** [comment]
Thanks!
