### ISSUE TITLE
Multiple instances causing DNS leaks (Windows)

### ISSUE THREAD

**Issue by privacyguy123** [DNSCrypt/dnscrypt-proxy#994]
This certainly has me stumped - I've got the multiple instances running as services in Windows listening on 127.0.0.1 and 127.0.0.2 yet when I force set my adapters DNS to .2 its picking up the DNS used in .1s config on dnsleaktest.com 😕

**Comment by jedisct1** [comment]
`dnscrypt-proxy` doesn't know anything about your system configuration. It just listens to the configured addresses, and forwards to the configured servers.

**Comment by privacyguy123** [comment]
Am I wrong in thinking forcing the adapter to listen to 127.0.0.2 should prevent this? Why would it show the server on 127.0.0.1s config file on dnsleaktest.com?

**Comment by iWARR** [comment]
@privacyguy123 

In Windows two entry fields for DNS IPs of the Network Adapter configuration are likely "one pool" - it's just Primary and Alternative IPs for ONE configuration: if primary (127.0.0.1) is unavailable / offline, then OS trying to use an alternative IP (127.0.0.2).

So, yes, I think you are wrong trying to "separate" them outside in spite of Windows habits. Both your services will try to use both IPs at the same time, that will produce a chaos in your Network DNS config.

-------------------------------------------------------------

**The next note is relative to your another issue** https://github.com/DNSCrypt/dnscrypt-proxy/issues/979 , if you still trying to achieve DNS setup for TOR using 2 services (if I'm understood right):

The only way to make a proper reaction is rewriting dnscrypt-proxy service (this is on author's side), but this might be a very complicated task:

- TOR-relative settings in toml should be recognized as "separated" settings inside the service construction.
- dnscrypt-proxy Service have to recognize whether TOR was launched immidately (I can't imagine how) and reconfigure himself automatically on the way (shutdown the regular config and starting use SOCKS + TCP only).

- After closing TOR the dnscrypt-proxy Service have to shutdown SOCKS connection on the way and recover regular (standard) config back.

(Insane task, but nothing is impossible, I beleive).

**Comment by privacyguy123** [comment]
I think I understand now - the TAP Adapter with 127.0.0.2 in its config is using the regular adapter with 127.0.0.1 to connect to the internet, so of course it's going to "leak."
