### ISSUE TITLE
Flush DNS cache if disconnected? Option request.

### ISSUE THREAD

**Issue by ropucyka** [DNSCrypt/dnscrypt-proxy#995]
Option for cases when internet (adapter) disabled-enabled and device receive new external ip address, but DNS cache still storing old ip of device and you lost access to local resources if trying to open them through device hostname.

Example:
Local device has DNS name: x_sukablyat_x.ru and assotiated ip 8.8.8.8
you reconnected internet and now device has new ip: 8.8.4.4
So now, if try to open local resources through x_sukablyat_x.ru - DNS cache will return old ip 8.8.8.8 as result - lost access to local resources if using device hostname to open them.

**Comment by jedisct1** [comment]
How to know when the external IP address has changed?

**Comment by ibksturm** [comment]
privjet @ropucyka 

[offtopic] the correct writing of the russian word you mesn in latin is ssukabliat with „double s“ and „i“, i actually try to learn russia 🖖 [/offtopic]

**Comment by ropucyka** [comment]
@jedisct1
What for need to know? Only cache flush as option, i think.
Or i just not found how to not cache user defined hostnames:)

privet @ibksturm
Without "double s". Я (бл**я**ть) - sounds like "ya" in latin, so "i" also wrong.
сука блять - suka blyat' It's bad words, you not need to learn them, man)

**Comment by ibksturm** [comment]
privet @ropucyka 
„ia“ or „ja“ = how german / swiss german nativ speaker would spell it ^^ 
„ss“ = as i would speak in german too...

i training russia on going to work / home... traiveling by train makes it very comfortable, listen to lessions by app and write down what i hear in my book 🤘

„tschorta s dva“ better than the thing about horny dogs ;) 🐕
-> the guys of Team AdGuard @ameshkov told me too that‘s not a... nice word ;)

So better we all go back to coding ^^

**Comment by jedisct1** [comment]
Is the startup very slow? Unless you have huge blacklists, `dnscrypt-proxy -service restart` would flush the cache :)

**Comment by ropucyka** [comment]
@jedisct1 
In my blacklist 174 entries.

> dnscrypt-proxy -service restart would flush the cache

Of course, because this tool storing cache only in memory.

**Comment by jedisct1** [comment]
174 entries is nothing. Restart should instantaneous :)
