### ISSUE TITLE
Load user configuration settings from separate file

### ISSUE THREAD

**Issue by mxfm** [DNSCrypt/dnscrypt-proxy#999]
Currently the only way to configure dnscrypt-proxy is to edit toml file, which is also the sole configuration file. Some distros may ship this file in package and after update (depending on package management) either user settings are overwritten, or (most likely) changes are not propagated to the config file. In any case, this requires manual user intervention to correct version conflicts. 

Please provide separate configuration file which overrides settings in main toml file.

**Comment by jedisct1** [comment]
No.

**Comment by mxfm** [comment]
Is it because of lack of interest? Or due to technical limitations of toml config files?

**Comment by jedisct1** [comment]
TOML doesn’t support inclusion of external files. So we’d have to invent something, and try to get this implemented upstream. Which is is unlikely to be accepted as it would be non-standard.
Similar requests have been made to extend TOML but the answer was to use a script that concatenation files instead.
